### PR TITLE
Revert "[Core] Add resize to pointer_vector"

### PR DESCRIPTION
**Pull request by tteschemacher**
Reverts KratosMultiphysics/Kratos#6275

### CODE REVIEW

**Review by loumalouomega — APPROVED** [review]
OK, sorry for the previous approval. I always thought the same that the resize was lacking

**Comment by tteschemacher** [comment]
Anyways, thanks. Without that the use of it is very limited...

**Comment by philbucher** [comment]
can this branch be deleted?

**Comment by tteschemacher** [comment]
This branch is restored and now in #6306 

Feel free to approve it that we can delete it ;)

**Pull request merged**
