### PR TITLE
[Core][AtomicUtilities] remove OMP 3 feature

### PR DESCRIPTION
**Pull request by philbucher**
**Description**
Updating code to be compatible with MSVC

FYI @maceligueta

### CODE REVIEW

**Comment by maceligueta** [comment]
Hi @philbucher , yesterday I was trying `#pragma omp atomic` with a bool assign and it wasn't even compiling in linux. It required to add `write`. After a while I realized that `#pragma omp atomic write `  does not compile in Windows. thanks to the CI.

**Comment by philbucher** [comment]
thanks for the info @maceligueta 

so probably we do need the `KRATOS_COMPILED_IN_WINDOWS` to check the compiler?

**Comment by maceligueta** [comment]
I just took a look at the OpenMP 2.0 documentation and the options for `atomic `are really limited, as it is restricted to scalars (maybe not even bools are included) and keywords like `write `or `read `are not supported.
https://www.openmp.org/wp-content/uploads/cspec20.pdf
I would avoid any method which uses these extra keywords.

**Comment by RiccardoRossi** [comment]
either we completely remove the atomicassign, or we emulate it in win by using low level functions (probably compiler specific)

the problem is that interoperability is not guaranteed

https://stackoverflow.com/questions/41309299/mixing-c11-atomics-and-openmp/41316118#41316118

**Comment by maceligueta** [comment]
Just to leave my opinion, I think we should stick to those keywords supported by OpenMP 2.0. When we migrate to c++11 stl parallelism, this limitation will disappear.
By the way, I recently started using ParallelUtilities and they are quite easy to handle. Still wondering how to deal with those `schedule` keywords though.

**Comment by philbucher** [comment]
@maceligueta regarding the `schedule` I think this is not really portable as with C++11 we would have to implement our own scheduling :sweat_smile: 

Although it might make sense to pass an additional argument to specify the scheduling, which can then internally be used or not
what do you think @RiccardoRossi

**Comment by philbucher** [comment]
The pure `atomic` works with `int` and `double` no?
=> maybe we can use `static_assert` to check the types (then it won't only fail in the CI), then we don't have to completely remove `AtomicAssign`

**Comment by RiccardoRossi** [comment]
well, we can add a parameter to the partition, defaulting to
static....would not be difficult to implement something on the line of what
openmp does

take a look at
https://youtu.be/SJm-_nGV1Zk

**Comment by philbucher** [comment]
@RiccardoRossi you sure you shared the correct link?
Not sure how ROM is related to openmp :smile:

**Comment by RiccardoRossi** [comment]
oops

**Comment by philbucher** [comment]
@maceligueta @RiccardoRossi what do you think about my last commit?

**Comment by maceligueta** [comment]
With your last commit things are much clearer for anyone who uses the method. I am only worried about the overhead it may cause, but these functions do not look heavy, I am not sure.

**Comment by maceligueta** [comment]
Oh, forget it, its an assert, so it’s checked at compile time. Perfect then!

**Comment by philbucher** [comment]
> Oh, forget it, its an assert, so it’s checked at compile time. Perfect then!

yep static_assert is compiletime :)
having the error at compiletime is also a lot clearer to me
BTW I tried to search for an atomic assign in the code but didn't find one (wanted for testing purposes)

Another note: maybe we should also have AtomicMult and AtomicDiv => e.g. needed [here](https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/constraints/linear_master_slave_constraint.h#L370)

**Comment by RiccardoRossi** [comment]
why this *=??

the reset should be done in the strategy if needed...

**Comment by maceligueta** [comment]
@philbucher  Yes, it makes sense to add AtomicMult and AtomicDiv, because we already have the addtition and subtraction. I am not a big fan of abbreviated words, I would prefer AtomicMultiplication or AtomicMultiply, but I understand that the style is already marked by the existing methods.
I don't understand your last question @RiccardoRossi

**Comment by philbucher** [comment]
@RiccardoRossi are you fine with the changes?

**Comment by RiccardoRossi** [comment]
the use of those classes is not yet widespread, so if there is agreeemnt
about using longer names, no resistnace from my side.

what i am worried is that i don t think it is a good idea to throw an error
if a feature is not implemented. If you are somewhere and the error is
thrown, what would u do?

Riccardo

**Comment by philbucher** [comment]
> the use of those classes is not yet widespread, so if there is agreeemnt
about using longer names, no resistnace from my side.

I don't have a strong opinion. Only that it should be in a different PR :)

> what i am worried is that i don t think it is a good idea to throw an error
if a feature is not implemented. If you are somewhere and the error is
thrown, what would u do?

I don't understand, it is a compiletime error if I use a type that is not compatible with atomic assign on another OS => this will then never make it to master to avoid the problems @maceligueta had

**Comment by RiccardoRossi** [comment]
scenario: you have a code that wprks, and you are required tonrun om a
given server. you compile there and it fails.

what do you do?

**Comment by philbucher** [comment]
well then the code would not work on that cluster either way ...
I mean all I do it to issue a nice error

Without this error it would not compile somewhere else where the `AtomicAssign` is used

> what do you do?

open an issue

**Comment by philbucher** [comment]
to add to my answer, lets say we don't merge this and someone uses a type (lets use `long` as example) that doesn't work on the cluster, we have a problem. Then the code will not compile on this cluster as is

What I am trying to achieve with this PR is to only allow types that we know work on ALL OSs that we use, including clusters.
If we merge this PR then we limit the types to be used to only a few that hopefully work everywhere. If then we still have allowed a type that we will find to not work in the future, then we can add it to this static_assert and refactor the corresponding code.
=> by having it then in the static_assert we are sure that this type will not again be used in the future

**Comment by RiccardoRossi** [comment]
i am not sure about your point...if you do not add the function, you will not be able to use it ... so you oblige people to look for alternatives.

on thr contrary if you add the function it will work locally and for example, for this specific case,  fail in the CI

**Comment by philbucher** [comment]
@RiccardoRossi I am quite confused, I am not sure we are speaking abt the same thing
maybe we can speak on the phone in the next days

**Comment by maceligueta** [comment]
@RiccardoRossi , the OpenMP 2.0 manual explicitly says that atomic operations are limited to _scalars_, understanding _scalars_ as the types this PR allows in compile time. Other types of variables simply do not compile in Windows, so @philbucher  is bringing those limitations to the wrapper that is calling OpenMP (AtomicUltilities).

**Comment by philbucher** [comment]
@maceligueta do you need the AtomicAssign?

**Comment by maceligueta** [comment]
Now that I know that I can’t use bools... no. You are right. I can use the other methods.

**Comment by maceligueta** [comment]
Exactly, that’s what I did in my last PR. I added 1 to an integer. It works like a bool.

**Comment by RiccardoRossi** [comment]
just to tell that i spoke with @philbucher and i now understood the PR.

My only point is that instead of templating, we may want to have

~~~
AtomicAssign(double)
AtomicAssign(int)
~~~

instead of

~~~cpp
template<class TDataType> AtomicAssig ...
~~~

and then removing the ones that do not compile

in any case fine for me whatever you choose

**Comment by philbucher** [comment]
so for me it makes sense to go with the the templated function and the static assert => this way if in the future we allow more types it would be easier to add

**Review by RiccardoRossi — APPROVED** [review]

**Comment by maceligueta** [comment]
Weird! @AlejandroCornejo and myself are getting compilation erros from this PR:
```
In file included from /home/maceli/kratos/applications/DEMApplication/custom_strategies/strategies/explicit_solver_continuum.cpp:7:0:
/home/maceli/kratos/kratos/utilities/atomic_utilities.h: In function 'void Kratos::AtomicAssign(TDataType&, const TDataType&)':
/home/maceli/kratos/kratos/utilities/atomic_utilities.h:98:19: error: invalid form of '#pragma omp atomic' before ';' token
     target = value;
                   ^
applications/DEMApplication/CMakeFiles/KratosDEMCore.dir/build.make:110: recipe for target 'applications/DEMApplication/CMakeFiles/KratosDEMCore.dir/custom_strategies/strategies/explicit_solver_continuum.cpp.o' failed
gmake[2]: *** [applications/DEMApplication/CMakeFiles/KratosDEMCore.dir/custom_strategies/strategies/explicit_solver_continuum.cpp.o] Error 1
```
I am using gcc compiler v 6.1.1. in Linux. @AlejandroCornejo is also experiencing the problem in Linux.

**Comment by maceligueta** [comment]
Now I think that we will avoid many problems if we just delete the method `AtomicAssign`.

**Comment by RiccardoRossi** [comment]
if we do

~~~cpp
#pragma omp atomic write
    target = value;
~~~

instead of 

~~~cpp
#pragma omp atomic
    target = value;
~~~

it compiles for me

**Comment by maceligueta** [comment]
#7608

**Comment by maceligueta** [comment]
`#pragma omp atomic write` is not recognized by OpenMP 2.0

**Pull request merged**
