### PR TITLE
Improve adjoint sensitivity analysis

### PR DESCRIPTION
**Pull request by MFusseder**
This pull request contains some improvements of the adjoint elements and conditions:

- a member variable ```mHasRotationDofs``` was added to the adjoint element base class in order to tell the adjoint element if the primal element has also rotational-Dofs

- The constructor of the adjoint condition base class was modified

### CODE REVIEW

**Review by armingeiser — DISMISSED** [review]
Looks good from my side, lets wait if @philbucher has comments.

**Review by philbucher — DISMISSED** [review]
ok also from my side

Btw I think there are some adjoint tests currently failing if they are run from kratos/python_scripts/run_test.py, can you please have a look (In a separate PR or here, up to you)

**Comment by MFusseder** [comment]
@philbucher I will have a look on the test cases. Thank you for the hint and for your review.

**Comment by MFusseder** [comment]
Sorry guys, I just figured out that I missed the check for the rotational dofs in one situation. I fixed this within the last added commit.

**Review by philbucher — APPROVED** [review]

**Pull request merged**
