### PR TITLE
[Core] Reactivating ContactStructuralMechanicsApplication on Appveyor

### PR DESCRIPTION
**Pull request by loumalouomega**
@roigcarlo reduced to 20 min the compilation time of appveyor, so let's reactivate my app (that maybe doesn't work in Windows anymore :P)

### CODE REVIEW

**Comment by roigcarlo** [comment]
Seems that you have some compile errors :P

**Comment by loumalouomega** [comment]
This is due to recent changes done by @adityaghantasala I expected that, I think that the master does not compile even in Linux right now, I cannot check it now

**Comment by adityaghantasala** [comment]
I did not change anything regarding the compilation.  Also the branch I made passed all appvoyer and tarvis !!

**Comment by loumalouomega** [comment]
My application was not compiled in appveyor, that's why I asked to manually
check that.

**Comment by loumalouomega** [comment]
I fixed the compilation issue

**Comment by loumalouomega** [comment]
Ping @roigcarlo

**Review by roigcarlo — APPROVED** [review]

**Comment by loumalouomega** [comment]
Thanks

**Pull request merged**
