### PR TITLE
[AnalysisStage] adding call to solver.Clear() in Finalize

### PR DESCRIPTION
**Pull request by philbucher**
based on the problems we have in #3885 :
>@KratosMultiphysics/technical-committee how about we add a call to solver.Clear() in the finalization of the analysis-stage? (in a separate PR ofc)
>This would have two benefits:
>1. If Clear is properly implemented in the solvers then the fix from this PR will automatically be applied too
>2. In a multi-stage-analysis it might be good to clear the previous stages to free some memory.

what do you think?

### CODE REVIEW

**Comment by philbucher** [comment]
I updated the fluid-solvers to match the proposed implementation
Still works for me

**Comment by jcotela** [comment]
Posting as a comment, rather than a review. I have to say that I do not really agree with this proposal. If we accept that the solver manages its data (strategy, builder and solvers,...), the solver should have the "freedom" to clear it only when needed, which it currently does. The problems with the strategy that make this Clear() necessary appeared because at some point we made the strategy clear its data during destruction (which I think is a mistake, but is unfortunately needed due to the way that the trilinos solvers work) and to me it looks like we are trying to solve the problem by doubling down on the same approach.

Since the problems that motivated this PR are due to defects in the design of the fluid solvers, I would rather improve them (also removing the code duplication that this PR correctly removes) than force the stage to call solver.Clean() during finalization.

I am fine with calling solver.Clear() between stages in a multi-stage solution, but I think that the code will be clearer if that is made explicit when the time comes.

**Comment by jcotela** [comment]
Hi @philbucher is this still needed?

**Comment by philbucher** [comment]
Hm I left it open as a reminder, but I am still not sure what would be the correct way to go here

**Comment by philbucher** [comment]
closing this for now, it should be done better, esp the trilinos related things
since we will eventually switch away from Trilinos I would rather investigate effort then to make it work properly

**Pull request closed without merging**
