### PR TITLE
Revert "[Structural] Remove UseGeometryIntegrationMethod from base solid"

### PR DESCRIPTION
**Pull request by loumalouomega**
Reverts KratosMultiphysics/Kratos#11155

### CODE REVIEW

**Review by rubenzorrilla — CHANGES_REQUESTED** [review]
Instead of reverting and doing the more simpler later on, I'd directly do the more simpler.

**Comment by loumalouomega** [comment]
> Instead of reverting and doing the more simpler later on, I'd directly do the more simpler.

After reading the code, I think it is no possible to do it simpler, and this completely breaks our code and it is essential

**Comment by loumalouomega** [comment]
The only thing I can think as simpler is to define it as a property...

**Comment by ddiezrod** [comment]
Just for you to have the context @rubenzorrilla , we have a couple of elements in altair where we move the integration nodes at each time step to correctly integrate the region of interest, thats why we override this method with UseGeometryIntegrationMethod = false

**Comment by pooyan-dadvand** [comment]
> Instead of reverting and doing the more simpler later on, I'd directly do the more simpler.

What is your suggestion for simpler?

**Comment by rubenzorrilla** [comment]
> > Instead of reverting and doing the more simpler later on, I'd directly do the more simpler.
> 
> What is your suggestion for simpler?

Not mine, @loumalouomega's one (he said so in the PR related to this one).

**Review by rubenzorrilla — APPROVED** [review]

**Pull request merged**
