### PR TITLE
Bug fix detected in issue  #11231

### PR DESCRIPTION
**Pull request by joaquinirazabal**
**📝 Description**
This PR fixes the problem encountered in #11231. The error appeared when #10924 was uploaded, the test should be updated then.

**🆕 Changelog**
Update history dependent CLs test.

### CODE REVIEW

**Review by ChengshunShang1996 — DISMISSED** [review]
Perfect. Thanks for your work! @joaquinirazabal

**Comment by salvalatorre** [comment]
Sorry, but I must be missing something... How is it that the tests have passed till now, then?

**Comment by joaquinirazabal** [comment]
Good point, @salvalatorre. It seems that the CI is only running the nightly tests...

Running DEMApplication tests
/__w/Kratos/Kratos/bin/Custom/applications//DEMApplication/tests/test_DEMApplication.py
test_execution (test_restart.TestRestartOneBall) ... 2.148s ...ok
test_execution (test_restart.TestRestartTwoBalls) ... 2.246s ...ok
test_SearchA (test_DEM_search_tolerance.TestSearchTolerance) ... 9.718s ...ok
test_SearchB (test_DEM_search_tolerance.TestSearchTolerance) ... 8.193s ...ok
test_SearchC (test_DEM_search_tolerance.TestSearchTolerance) ... 8.168s ...ok
test_SearchD (test_DEM_search_tolerance.TestSearchTolerance) ... 8.228s ...ok
test_Run (Chung_Ooi_test_1.ChungOoiTest1) ... 1.730s ...ok
test_Run (Chung_Ooi_test_2.ChungOoiTest2) ... 12.217s ...ok
test_Run (Chung_Ooi_test_3.ChungOoiTest3) ... 9.231s ...ok
test_Run (Chung_Ooi_test_4.ChungOoiTest4) ... 31.890s ...ok

----------------------------------------------------------------------
Ran 10 tests in 93.774s

**Comment by philbucher** [comment]
The short suite should be part of the nightly one

See e.g. StructuralMechanics

**Comment by joaquinirazabal** [comment]
I've just added the small suite to the nightly one, let's see if all tests are working properly now...

**Comment by salvalatorre** [comment]
Good work everybody!

**Comment by joaquinirazabal** [comment]
Everything is working as expected now

**Review by ChengshunShang1996 — APPROVED** [review]
Nice done! Thanks @joaquinirazabal

**Pull request merged**
