### PR TITLE
[Core] remove unused linear transformation processes

### PR DESCRIPTION
**Pull request by matekelemen**
**Description**
Remove two untested, unused classes: ```TranslationProcess``` and ```RotationProcess```. Additionally, they reimplement functionality from ```Quaternion``` and ```GeometricalTransformationUtilities```.

It is unclear to me what they actually do, but since there aren't any tests or uses for them, I think we'd be better off without them. Let me know if this is actually a dependency on some branch.

Closes issue #8647.

### CODE REVIEW

**Comment by RiccardoRossi** [comment]
@matekelemen by which processes would u substitute those?

from the input i mean

**Comment by philbucher** [comment]
> @matekelemen by which processes would u substitute those?
> 
> from the input i mean

Quaternion and GeometricalTransformationUtilities I would say

**Comment by matekelemen** [comment]
> @matekelemen by which processes would u substitute those?
> 
> from the input i mean

I'm not aware of any existing processes that would fully replace them. However, the tools to implement their functionality are already written (```Quaternion``` and ```GeometricalTransformationUtilities``` for example). That said, I don't think they need replacing right now because they aren't used anywhere.

If these processes do have an expected use case, I recommend updating them because I don't think they are functional in their current state. For example:
- the rotation convention is not documented so the user would have to figure it out for themselves by looking though the code
- [this](https://github.com/KratosMultiphysics/Kratos/blob/18ec62515bc82b5c1ca8007cc7250bddec100c93/kratos/processes/rotation_operation.h#L172) is a reference to an ```rvalue``` and so immediately becomes dangling
- the copy assignment operator takes and returns the [wrong type](https://github.com/KratosMultiphysics/Kratos/blob/18ec62515bc82b5c1ca8007cc7250bddec100c93/kratos/processes/rotation_operation.h#L265)

**Comment by mpentek** [comment]
@KratosMultiphysics/technical-committee a PR long open. Should the old functionalities be updated/tested or left alone?

**Review by rubenzorrilla — APPROVED** [review]
I think we can safely remove these as we can always recover them from the repo history.

**Pull request merged**
