### PR TITLE
[OptimizationApp] Marking test a expected failure until fixed

### PR DESCRIPTION
**Pull request by roigcarlo**
**📝 Description**
Marking a problematic test as expected fail until fixed.

@avdg81 @SADPR  This should get rid of the failing CI tests.

@sunethwarna I marked it as expected failure until fixed as is holding down several PR.

### CODE REVIEW

**Comment by sunethwarna** [comment]
Thanks. I'm check it once I'm back

**Review by sunethwarna — DISMISSED** [review]

**Review by sunethwarna — COMMENTED** [review]
It does not fail always RYT?, so I think we need to comment out the test.

**Comment by roigcarlo** [comment]
O you are right...

**Comment by avdg81** [comment]
> **📝 Description** Marking a problematic test as expected fail until fixed.
> 
> @avdg81 @SADPR This should get rid of the failing CI tests.
> 
> @sunethwarna I marked it as expected failure until fixed as is holding down several PR.

Thanks for taking action @roigcarlo, really appreciate that. And thanks in advance to @sunethwarna for his willingness to look into the problem.

**Review by sunethwarna — DISMISSED** [review]
Thanks @roigcarlo

**Review by rubenzorrilla — APPROVED** [review]

**Pull request merged**
