### PR TITLE
[External] Update pybind11 to 2.10

### PR DESCRIPTION
**Pull request by loumalouomega**
**📝 Description**

Update pybind11 to 2.10. Required for compatibility with MinGW.

**🆕 Changelog**

- Update pybind11 to 2.10.

### CODE REVIEW

**Comment by loumalouomega** [comment]
@roigcarlo I can confirm that now MinGW works

**Comment by roigcarlo** [comment]
Perfect, once it passes the CI we can merge

**Comment by loumalouomega** [comment]
> Perfect, once it passes the CI we can merge

A priori the conflicting one is the legacy Intel Compiler?

**Comment by roigcarlo** [comment]
What you mean by conflicting? It has not even started. With intel ones never knows

**Comment by loumalouomega** [comment]
> What you mean by conflicting? It has not even started. With intel ones never knows

I mean that usually Pybind gives problems with Intel compiler

**Comment by loumalouomega** [comment]
@roigcarlo why CI is not starting?

**Comment by roigcarlo** [comment]
It finals to trigger sometimes. Just make an empty commit to force it

**Comment by loumalouomega** [comment]
> It fails to trigger sometimes. Just make an empty commit to force it

Done, still the same

**Comment by roigcarlo** [comment]
> > It fails to trigger sometimes. Just make an empty commit to force it
> 
> Done, still the same

They are working now... is takes a few seconds to trigger

**Comment by loumalouomega** [comment]
> > > It fails to trigger sometimes. Just make an empty commit to force it
> > 
> > 
> > Done, still the same
> 
> They are working now... is takes a few seconds to trigger

https://www.youtube.com/watch?v=c9EBhaULToU

**Review by roigcarlo — APPROVED** [review]

**Comment by loumalouomega** [comment]
@philbucher if you merge https://github.com/KratosMultiphysics/Kratos/pull/10161 I will merge this

**Pull request merged**
