### PR TITLE
DEM problems with doubles and integers

### PR DESCRIPTION
**Pull request by salvalatorre**
Solved problems when checking against the default Parameters. Integers were found when expecting doubles

### CODE REVIEW

**Comment by maceligueta** [comment]
I think unnecessary files were uploaded. .lst, .mdpa, etc

**Comment by salvalatorre** [comment]
Files removed!

**Review by GuillermoCasas — APPROVED** [review]

**Review by maceligueta — COMMENTED** [review]
It still shows me some files

**Review by maceligueta — CHANGES_REQUESTED** [review]
Still some files?

**Comment by maceligueta** [comment]
I would remove all those folders called Candelier_Post_Files_... As far as I know they are results that you obtain when you run the example, but they are not necessary in the repository.

**Comment by salvalatorre** [comment]
Let us see...

**Comment by salvalatorre** [comment]
Done!

**Review by maceligueta — APPROVED** [review]

**Pull request merged**
