### PR TITLE
Adding a new material Parameter Rolling Friction with Walls

### PR DESCRIPTION
**Pull request by joaquinirazabal**
Sometimes it is necessary to assign different rolling friction between particles and between walls. I added a new material parameter called Rolling Friction with Walls. The changes in the GidInterface are already prepared to be submitted when the pull request is merged.

### CODE REVIEW

**Review by GuillermoCasas — COMMENTED** [review]
Are you sure this is correct? Should in not call the GetRollingFrictionWithWalls here?
else if (wall) {
 +            equiv_rolling_friction_coeff = GetRollingFriction() * GetRadius();
          }		          }

**Comment by joaquinirazabal** [comment]
It is not correct, of course. Thank you Guillermo, I have just corrected it.

**Comment by maceligueta** [comment]
In the last days I've been thinking about backward compatibility. The users of dempack often run old cases with the newest code. Can we add a line to check if the parameter exists in the properties? In case it doesn't, we can add it with the same value as the normal rolling friction. There's a method (in python) called ModifyProperties, which should include all the modifications of the properties.

**Comment by joaquinirazabal** [comment]
Great, I am going to do it, I will tell when it is changed

**Comment by joaquinirazabal** [comment]
I've just changed ModifyProperties to allow backward compatibility

**Comment by joaquinirazabal** [comment]
All changes have been submitted

**Review by maceligueta — APPROVED** [review]

**Comment by joaquinirazabal** [comment]
Merged

**Pull request merged**
