### PR TITLE
[Metis] make output of debug-modelpart depending on verbosity

### PR DESCRIPTION
**Pull request by philbucher**
It is quite verbose to print it unconditional

I hope this change is ok, seems more natural to me

### CODE REVIEW

**Comment by philbucher** [comment]
ping :)

**Comment by philbucher** [comment]
ping :D

**Comment by philbucher** [comment]
u there @roigcarlo ?

**Comment by philbucher** [comment]
ping

**Review by roigcarlo — APPROVED** [review]
Sorry @philbucher , I am with external projects and issues tend to slip from my sight. 
All good !

**Comment by philbucher** [comment]
no problem, thx :)

**Pull request merged**
