### PR TITLE
[MeshingApplication] Dropping support MMG below 5.5 

### PR DESCRIPTION
**Pull request by loumalouomega**
**📝 Description**

Dropping support MMG below 5.5. Related #10162

**🆕 Changelog**

- [Dropping support MMG below 5.5](https://github.com/KratosMultiphysics/Kratos/commit/861c729585c029b448bf4652670cd90d8ac99854)
- [Update CI](https://github.com/KratosMultiphysics/Kratos/commit/46dda2b06dc1625e604b72419620c80bf4a533da)
- [Update Dockerfile](https://github.com/KratosMultiphysics/Kratos/commit/88dcae4b4cb2171165b50a83ba46b7a39227867d)
- [Adding compilation fail check](https://github.com/KratosMultiphysics/Kratos/pull/10164/commits/c0970d8a548b143318d57d0e1813731cfa8189f9)

### CODE REVIEW

**Comment by marcnunezc** [comment]
Thanks!

I would like to add an error message at the [CMakeLists.txt](https://github.com/KratosMultiphysics/Kratos/blob/master/applications/MeshingApplication/CMakeLists.txt) if MMG version < 5.5

I am not sure if it is possible to know which version the user is compiling with at compile time though. Do you know if it can be done?

**Comment by roigcarlo** [comment]
Not with the current mechanism we have, but we can either change our findMMG.cmake or directle parse the `CMAKE_RELEASE_VERSION_[MAJOR/MINOR]` variable from the located mmg dir to extract the major. Maybe a combination of both?

**Comment by loumalouomega** [comment]
I will try to add the message

**Comment by loumalouomega** [comment]
I did it in the code, in CMake was impossible without overcomplex stuff

**Review by philbucher — APPROVED** [review]

**Pull request merged**
