### PR TITLE
[MLMC] Skip test

### PR DESCRIPTION
**Pull request by riccardotosi**
**Description**
Skip tests if Fluid app is not found. This is a workaround, since the dependency is removed in #8088.

Please mark the PR with appropriate tags: 
- Bugfix

**Changelog**
Please summarize the changes in one list to generate the changelog:
E.g.
- Skip tests if Fluid app is not found..

### CODE REVIEW

**Review by philbucher — APPROVED** [review]
thx

**Comment by philbucher** [comment]
BTW this is not a workaround, this is how it should be

**Comment by riccardotosi** [comment]
> BTW this is not a workaround, this is how it should be

I say workaround because in  #8088 we are removing the dependency. The only thing is that we are not sure about when  #8088 will be merged. Probably not the finest word choice, I agree

**Comment by philbucher** [comment]
ah ok :)

**Pull request merged**
