### PR TITLE
[ContactStructuralMechanicsApplication] Several updates and new test

### PR DESCRIPTION
**Pull request by loumalouomega**
Hertz frictional added. 100 tests :)

### CODE REVIEW

**Comment by loumalouomega** [comment]
The big number of lines is due to mdpa

**Comment by philbucher** [comment]
> The big number of lines is due to mdpa

:(
How big is this file?

**Review by AlejandroCornejo — APPROVED** [review]
congratrs hehe

**Comment by loumalouomega** [comment]
> > The big number of lines is due to mdpa
> 
> :(
> How big is this file?

1 Mega

**Comment by philbucher** [comment]
oh ok

sorry for often being the bad guy :sweat_smile:

**Comment by loumalouomega** [comment]
> oh ok
> 
> sorry for often being the bad guy sweat_smile

We could reduce the size of the mdpa storing the submodelparts in colors (and compressing the file later)

https://github.com/KratosMultiphysics/Kratos/blob/6c4ce2fc402603b7a4d629e14b38e4411b1eae7a/kratos/utilities/assign_unique_model_part_collection_tag_utility.cpp#L190

**Pull request merged**
