### PR TITLE
[Core] deprecate old gid output

### PR DESCRIPTION
**Pull request by philbucher**
this PR adds a deprecation-warning to the old gig-output in the core
@maceligueta @GuillermoCasas you seems to still be using this, is it feasible to update to the newer process?

Also the trilinos-version is deleted, it is not used anywhere

### CODE REVIEW

**Comment by maceligueta** [comment]
Thanks for the warning @philbucher . We will migrate asap. In the meantime, from my side this PR can approved (if nobody is using the trilinos version).

**Comment by philbucher** [comment]
ping

**Review by loumalouomega — APPROVED** [review]
OK (the trilinos_gid_output was duplicated, I had not notice)

**Comment by pooyan-dadvand** [comment]
@KratosMultiphysics/technical-committee agrees with the deprecation.

**Pull request merged**
