### PR TITLE
[Core] Hotfix implicit mortar mapper

### LINKED ISSUE #3370: [Core] Mortar mapper with linear solver
@loumalouomega 

I tried to use your mortar mapper in the core (`simple_mortar_mapper_process.h`) and it throws this error when specifying the linear solver in the constructor. 
```
Error: attempting to do a GetValue for: NODAL_MAUX variable #2503569152 unfortunately the variable is not in the database and the operations is not threadsafe (this function is being called from within a parallel region)
```
Actually, I don't really know how this works so I can't give you more information than that.

### PR DESCRIPTION
**Pull request by loumalouomega**
Fixes  #3370

As you can see it was a very stupid mistake. I added a tests to avoid this in the future

### CODE REVIEW

**Comment by philbucher** [comment]
@loumalouomega I recently noticed that the mortar-mapper-tests in the core are not in any testing suite 
I am not 100% sure, can you check pls?

**Comment by loumalouomega** [comment]
You are right @philbucher

**Comment by loumalouomega** [comment]
In fact @philbucher there were missing three tests suites, all mine

**Comment by loumalouomega** [comment]
Ping @rubenzorrilla

**Comment by philbucher** [comment]
take a look at codacy pls

**Comment by loumalouomega** [comment]
Curious, I look at the moment and I thought that test was missing

**Comment by loumalouomega** [comment]
Anyone?

**Review by rubenzorrilla — APPROVED** [review]

**Pull request merged**
