### PR TITLE
[Core][Py-LinearSolverFactory] clean deprecated code

### PR DESCRIPTION
**Pull request by philbucher**
I think it is time to clean this, it has been there for a while
Esp because there are some changes coming, see [this comment](https://github.com/KratosMultiphysics/Kratos/pull/6482#issuecomment-608456537)

### CODE REVIEW

**Review by rubenzorrilla — COMMENTED** [review]
It has been there for quite a long time. Thanks for the clean up.

However, we need to update the GUIs before merging this. I'll do it so for the GiD one ASAP.

**Comment by philbucher** [comment]
I thought the interface was already updated long ago
I think I broke sth back then and someone had to fix it :)

**Comment by rubenzorrilla** [comment]
> I thought the interface was already updated long ago
> I think I broke sth back then and someone had to fix it :)

It should be easy. I guess it's only changing the `super_lu` by the `sparse_lu` and removing the old GMRES (we forgot to do it when we cleaned up the GMRES solvers).

**Comment by philbucher** [comment]
Can this be merged now @rubenzorrilla ?

**Review by rubenzorrilla — APPROVED** [review]
I think so. The GUI is already updated.

**Pull request merged**
