### PR TITLE
[Core] Fix BB check

### PR DESCRIPTION
**Pull request by loumalouomega**
**📝 Description**

Fix BB check

**🆕 Changelog**

- [Fix BB check](https://github.com/KratosMultiphysics/Kratos/commit/e3d4f41f9464fe3f04949820d5e4dfb4d4fd6eda)

### CODE REVIEW

**Comment by ddiezrod** [comment]
test to cover the bug?

**Comment by loumalouomega** [comment]
> test to cover the bug?

The search is not merged, the test is added in the search PR

**Comment by ddiezrod** [comment]
> > test to cover the bug?
> 
> The search is not merged, the test is added in the search PR

the function PointIsInsideBoundingBox is already in master and it seems the bug is there, so you can create a small test just for that function, right?

**Comment by loumalouomega** [comment]
> > > test to cover the bug?
> > 
> > 
> > The search is not merged, the test is added in the search PR
> 
> the function PointIsInsideBoundingBox is already in master and it seems the bug is there, so you can create a small test just for that function, right?

**Review by ddiezrod — APPROVED** [review]
Thanks, sorry for being annoying :)

**Pull request merged**
