### PR TITLE
[Core] Add strings to elements via python

### PR DESCRIPTION
**Pull request by oberbichler**
example:
```python
element.SetValue(THIS_VARIABLE_CONTAINS, "a string")
```

### CODE REVIEW

**Comment by philbucher** [comment]
fine for me, but can you please also add it for conditions to be consistent?

approval up to @KratosMultiphysics/technical-committee

**Comment by loumalouomega** [comment]
Idem

**Comment by oberbichler** [comment]
done

The possibility to add a `Parameters` variable would also be nice but I already get a compiler error when declaring the variable...

**Comment by RiccardoRossi** [comment]
mmm,

i don't love the idea of passing strings since they are REALLY slow.

do you really need this feature?

**Comment by oberbichler** [comment]
We use this function to pass some data for validating element formulations as a json string. This allows us to change the data very easy and quick. The validation is only used during the development of the elements but the possibility to pass strings might be useful also in other scenarios so I think it would be nice-to-have in the core.

Of corse we need to be careful with the usage when performance is critical. In **my opinion** this is the responsibility of the developer/user and should not prevent us from providing a possible useful feature.

**Comment by pooyan-dadvand** [comment]
I agree with this addition and I also see the concern of @RiccardoRossi but hope that users are responsible.

**Comment by pooyan-dadvand** [comment]
Added to technical committee todo to be approved

**Comment by pooyan-dadvand** [comment]
Approved in @KratosMultiphysics/technical-committee

**Review by RiccardoRossi — APPROVED** [review]

**Comment by philbucher** [comment]
@oberbichler before you start using this extensively, usually check in the Elements are done in `Check`
=> we can discuss it but I could imagine that this is what you would like to do

**Comment by oberbichler** [comment]
Actually I have no plans to use string-variables in the final code. But the functions helps us a lot to check the element formulations with Carat while porting the code to Kratos.

**Pull request merged**
