### PR TITLE
[MPI][ParFillComm] improve check

### PR DESCRIPTION
**Pull request by philbucher**
minor, missed this last time

### CODE REVIEW

**Comment by philbucher** [comment]
@marcnunezc @inigolcanalejo apparently a test in the potentialapp fails randomly:
~~~
 ======================================================================
FAIL: test_EmbeddedCircle (potential_flow_test_factory.PotentialFlowTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/__w/Kratos/Kratos/bin/Custom/applications/CompressiblePotentialFlowApplication/tests/potential_flow_test_factory.py", line 98, in test_EmbeddedCircle
    self._runTest(settings_file_name)
  File "/__w/Kratos/Kratos/bin/Custom/applications/CompressiblePotentialFlowApplication/tests/potential_flow_test_factory.py", line 258, in _runTest
    potential_flow_analysis.Run()
  File "/__w/Kratos/Kratos/bin/Custom/KratosMultiphysics/analysis_stage.py", line 50, in Run
    self.RunSolutionLoop()
  File "/__w/Kratos/Kratos/bin/Custom/KratosMultiphysics/CompressiblePotentialFlowApplication/potential_flow_analysis.py", line 108, in RunSolutionLoop
    self.FinalizeSolutionStep()
  File "/__w/Kratos/Kratos/bin/Custom/KratosMultiphysics/analysis_stage.py", line 145, in FinalizeSolutionStep
    process.ExecuteFinalizeSolutionStep()
  File "/__w/Kratos/Kratos/bin/Custom/KratosMultiphysics/from_json_check_result_process.py", line 134, in ExecuteFinalizeSolutionStep
    self.__check_values(node.Id, "Node", value, value_json, variable_name)
  File "/__w/Kratos/Kratos/bin/Custom/KratosMultiphysics/from_json_check_result_process.py", line 262, in __check_values
    self.assertTrue(isclosethis, msg=msg)
AssertionError: False is not true : Error checking Node #2 for variable VELOCITY_POTENTIAL results:
21.6501775785466 != 28.6815154944978; rel_tol=0.000000000001, abs_tol=0.000000001
~~~
can you please have a look?

**Comment by marcnunezc** [comment]
> @marcnunezc @inigolcanalejo apparently a test in the potentialapp fails randomly:
> 
> ```
>  ======================================================================
> FAIL: test_EmbeddedCircle (potential_flow_test_factory.PotentialFlowTests)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/__w/Kratos/Kratos/bin/Custom/applications/CompressiblePotentialFlowApplication/tests/potential_flow_test_factory.py", line 98, in test_EmbeddedCircle
>     self._runTest(settings_file_name)
>   File "/__w/Kratos/Kratos/bin/Custom/applications/CompressiblePotentialFlowApplication/tests/potential_flow_test_factory.py", line 258, in _runTest
>     potential_flow_analysis.Run()
>   File "/__w/Kratos/Kratos/bin/Custom/KratosMultiphysics/analysis_stage.py", line 50, in Run
>     self.RunSolutionLoop()
>   File "/__w/Kratos/Kratos/bin/Custom/KratosMultiphysics/CompressiblePotentialFlowApplication/potential_flow_analysis.py", line 108, in RunSolutionLoop
>     self.FinalizeSolutionStep()
>   File "/__w/Kratos/Kratos/bin/Custom/KratosMultiphysics/analysis_stage.py", line 145, in FinalizeSolutionStep
>     process.ExecuteFinalizeSolutionStep()
>   File "/__w/Kratos/Kratos/bin/Custom/KratosMultiphysics/from_json_check_result_process.py", line 134, in ExecuteFinalizeSolutionStep
>     self.__check_values(node.Id, "Node", value, value_json, variable_name)
>   File "/__w/Kratos/Kratos/bin/Custom/KratosMultiphysics/from_json_check_result_process.py", line 262, in __check_values
>     self.assertTrue(isclosethis, msg=msg)
> AssertionError: False is not true : Error checking Node #2 for variable VELOCITY_POTENTIAL results:
> 21.6501775785466 != 28.6815154944978; rel_tol=0.000000000001, abs_tol=0.000000001
> ```
> 
> can you please have a look?

Ok! I will try to see if there's a race condition somewhere in the processes.

Is this happening in the new CI? If it is too annoying we can maybe disable the test until we find the issue.

**Comment by philbucher** [comment]
yes its only in the new CI
it is not urgent, thx

**Comment by philbucher** [comment]
ping

**Review by sunethwarna — APPROVED** [review]
:+1:

**Comment by philbucher** [comment]
thx

**Pull request merged**
