### PR TITLE
Adding appveyor support

### LINKED ISSUE #1301: Windows build before merge into master
Dear all,

In the last months, the master branch was often not compiling under windows: 
Would it be possible to include a mandatory windows build before a pull request can be merged into master?

### PR DESCRIPTION
**Pull request by roigcarlo**
This will enable us to use appveyor. Sorry for being a merge from a fork but it was impossible to test this without polluting the rest of the branches from the main repo.

Some important remarks:
- Builds the same as Travis except for the external solver application. This is currently not possible to build due to blas/lapack dependencies. I am working to fix this.
- Due to physical ram limitations I added an option do dissable AMGCL. @RiccardoRossi can you please check that the wards are ok?
- It uses python2.7. I have an issue opened in the appvetor github to check if they can compile a boost.python version that uses any python3 version. When they answer I will change this accordingly or leave it as is.
- I will not enable this straight away. This only enables us to do it. I need to check how to properly initialize appveyor in the main repo without triggering builds to branches that have no appveyor file.

@oberbichler I saw that you had a branch similar to this one, so I added you as a reviewer as well :)

Also this fixes #1301

### CODE REVIEW

**Comment by roigcarlo** [comment]
Ping someone

**Review by loumalouomega — APPROVED** [review]

**Comment by loumalouomega** [comment]
Am I someone?

**Comment by roigcarlo** [comment]
Thx

**Comment by pooyan-dadvand** [comment]
I like the name of commit [afb67eb](https://github.com/KratosMultiphysics/Kratos/pull/1360/commits/afb67ebcf013c5c7512cc3aed7e745051b79f9eb) !! :smile:

**Pull request merged**
