### PR TITLE
Improve import settings

### PR DESCRIPTION
**Pull request by philbucher**
this makes it more understandable what options are available, before it was quite confusing
No functionalities were added or removed

FYI @mpentek

### CODE REVIEW

**Comment by sunethwarna** [comment]
I was thinking, can we unify the _ImportModelPart method in base python_solver to use DistributedImportModelPartUtility if in the case of IsDistributed() is true?, then we can get rid of lots of duplicated code.

**Comment by philbucher** [comment]
> I was thinking, can we unify the _ImportModelPart method in base python_solver to use DistributedImportModelPartUtility if in the case of IsDistributed() is true?, then we can get rid of lots of duplicated code.

Quite the opposite, it should be refactored into a standalone utility or so such that it can be used standalone too (which we do a lot e.g. in the tests)
There is no real reason this has to be in the `PythonSolver`

I wanted to clean this up for a long time already but never got to it...

**Comment by philbucher** [comment]
no idea why the CI keeps crashing in the build, I am only modifying python-scripts
Will try again tmr

**Comment by philbucher** [comment]
ok now it passed the CI, no clue why it was failing yesterday
Maybe the github servers had a bad day :)

**Comment by philbucher** [comment]
if there are no comments can someone approve please?
@sunethwarna ?

**Review by sunethwarna — APPROVED** [review]
I am ok with the changes... thanks :)

**Pull request merged**
