### PR TITLE
Disabling travis applications

### PR DESCRIPTION
**Pull request by roigcarlo**
@KratosMultiphysics/technical-committee 
Seems that travis is still taking too long and I cannot attend people 24/7, so I suggest to dissable applications until we find a way to reduce the times to something bearable.

Ps: I found how to assing issues/pr to whole teams.

### CODE REVIEW

**Review by RiccardoRossi — COMMENTED** [review]
...this is very risky...

can't we just wait longer? (or tech people to resume the build?)

**Comment by roigcarlo** [comment]
Its not 100% sure that if you rebuild you are going to pass, only if travis had time to upload the cache before the image is shut down.
I know it's risky but I also understand that waiting 2-3h to merge a change in a python script may be a bit too much

**Comment by RiccardoRossi** [comment]
I do see your point, however i still vote for keeping them active. Only very few builds should trigger a recompile of the whole kratos, so the wait should not be desesperating.

The point is that we are many people working on each of the applications. If we don't do something about that they will get destroyed very fast.

**Comment by RiccardoRossi** [comment]
just to say that here essentislly they say not to use submodules

https://github.com/blog/2104-working-with-submodules

**Comment by roigcarlo** [comment]
Ok, Im closing this one, let's find another solution...

**Pull request closed without merging**
