### PR TITLE
update solid solver scripts

### PR DESCRIPTION
**Pull request by josep-m-carbonell**
-add variables and add dofs has been improved in the base scripts
-compatibility is kept
-some tests have been done to check that they are slightly faster (2'' for  1M nodes)

### CODE REVIEW

**Comment by josep-m-carbonell** [comment]
It is not ready yet,  some shell tests fail.

**Comment by josep-m-carbonell** [comment]
I think that now is ready

**Comment by AFranci** [comment]
For me is ok!

**Review by AFranci — APPROVED** [review]

**Comment by josep-m-carbonell** [comment]
Thank you @AFranci

**Pull request merged**
