### PR TITLE
Removing KRATOS_TRY and KRATOS_CATCH from several places in the DEM App (performance)

### PR DESCRIPTION
**Pull request by maceligueta**
Some KRATOS_TRY are removed.
This has proven to have a major effect in performance for small cases (65% of time reduction). In big cases it is also noted but the effect is less evident.

### CODE REVIEW

**Review by farrufat-cimne — COMMENTED** [review]
ok

**Review by salvalatorre — APPROVED** [review]

**Comment by pooyan-dadvand** [comment]
@maceligueta 65% is too much.... Actually it makes me think something is wrong with your measurement.... According to this [report on c++ performance](http://www.open-std.org/jtc1/sc22/wg21/docs/TR18015.pdf) with new implementations it must be almost null if there are no exception (page 40). And even for old way implementation it should be around 6% (page  39)

**Comment by maceligueta** [comment]
I will check it again before merging anything. Will post the results here.

**Comment by pooyan-dadvand** [comment]
It would be great! Just to add that both GCC and MSVC implementing the fast way

**Comment by maceligueta** [comment]
I did the test many times again, and my first estimation had some kind of big mistake.
Removing Try and Catch do not provide any improvement. Actually, the CPU time increases.
Under the order:
time likwid-pin -c 3 python KratosDEM.py 
I had the following results:
CPU Time with KRATOS TRY: 8.035, 8.069, 8.012 (and many others around 8.0)
CPU Time without KRATOS_TRY: 8.281, 8.190, 8.330 (and manu others around 8.25)

It is hard to explain, but removing KRATOS_TRY actually increases the execution time!

**Comment by pooyan-dadvand** [comment]
When you have try catch, you are saying that any exception from inferior methods is handled here, so maybe it gives some better perspective to optimizer.....

**Pull request closed without merging**
