### PR TITLE
[Core] Adding flip flags to variable utils

### PR DESCRIPTION
**Pull request by loumalouomega**

### CODE REVIEW

**Review by philbucher — APPROVED** [review]
looks good to me

**Comment by philbucher** [comment]
appveyor does not compile (not bcs of timeout)

**Comment by loumalouomega** [comment]
compiler is out of heap space  == no memory for compiling. Any suggestion @roigcarlo ?

**Comment by roigcarlo** [comment]
Maybe we have to split the unity file of tests...

**Comment by loumalouomega** [comment]
> Maybe we have to split the unity file of tests...

Perhaps

**Comment by philbucher** [comment]
now it compiled :)

**Pull request merged**
