### PR TITLE
[Meshing] Correcting the way the process know when to remesh

### PR DESCRIPTION
**Pull request by AlejandroCornejo**
I've made a change in the way the process detects if it has to remesh. Currently it was not working properly

### CODE REVIEW

**Review by loumalouomega — DISMISSED** [review]
Did you run the tests?

**Comment by AlejandroCornejo** [comment]
> Did you run the tests?

from the Meshing?

**Comment by loumalouomega** [comment]
> > Did you run the tests?
> 
> from the Meshing?

Yes

**Comment by AlejandroCornejo** [comment]
I'll do it @loumalouomega

**Review by loumalouomega — CHANGES_REQUESTED** [review]
Block until tests pass

**Comment by loumalouomega** [comment]
Does it work now?

**Review by loumalouomega — APPROVED** [review]

**Comment by AlejandroCornejo** [comment]
I have some concerns regarding this

**Comment by loumalouomega** [comment]
> I have some concerns regarding this

Why?

**Comment by RiccardoRossi** [comment]
this might affect @riccardotosi and @marcnunezc 

please guys take a look and give your approval before it is merged

**Comment by marcnunezc** [comment]
Hi! In our applications we are not using the mmg_process.py (the PYTHON process), since we use the metric and mmg process directly from c++, so this does not affect our cases.

In any case, why did you say that these changes are concerning @AlejandroCornejo?

**Comment by loumalouomega** [comment]
I don't get it, we just corrected this this morning, why did you merged?, BTW, the branch is alive

**Pull request merged**
