### PR TITLE
[MLMC] Add methods to get and set materials filename

### LINKED ISSUE #8304: Annoying multiple repetitions of ReadMaterialsUtility warnings
**Description**
I am running the following case:

1. initialize and run problem on mesh 0
2. refine using meshing application --> mesh 1
3. initialize and run problem on mesh 1
4. refine using meshing application --> mesh 2
5. initialize and run problem on mesh 2
6. etc.

Starting from stage 3., many warnings as
~~~bash
[WARNING] ReadMaterialsUtility: WARNING:: The properties ID: 1 in mesh ID: 0 is already defined. This will overwrite the existing values
[WARNING] ReadMaterialsUtility: WARNING:: The properties ID: 1 already has variables.
[WARNING] ReadMaterialsUtility: The properties ID: 1 already has CONDUCTIVITY.
Overwriting 1 with 1
[WARNING] ReadMaterialsUtility: The properties ID: 1 already has DENSITY.
Overwriting 1 with 1
[WARNING] ReadMaterialsUtility: The properties ID: 1 already has SPECIFIC_HEAT.
Overwriting 1 with 1
~~~
appear. This becomes quite annoying for my application of interest, since the workflow is repeated multiple times. **Is there a way to avoid the printing of such warnings?**

I already know that I could set
~~~python3
model.GetModelPart(model_part_name).ProcessInfo.SetValue(KratosMultiphysics.IS_RESTARTED, True)
~~~
but this **does not work** in my case.

I attach a zip folder with a simplified case. It only requires the `ConvectionDiffusionApplication` to be reproduced. As you may observe, when running the problem a second time (i.e. step 3.), the warnings appear.
[test_read_materials.zip](https://github.com/KratosMultiphysics/Kratos/files/5987956/test_read_materials.zip)

**Scope**
Which areas of Kratos are involved
E.g.
- KratosCore

### PR DESCRIPTION
**Pull request by riccardotosi**
**Description**
This PR adds two methods to the project parameters wrapper. One method gets the materials filename, the other sets the materials filename.
This addition allows to change the materials filename to `""` after serialization.

**Changelog**
Please summarize the changes in one list to generate the changelog:
E.g.
- Add `SetMaterialsFilename` and `GetMaterialsFilename` methods

### CODE REVIEW

**Comment by riccardotosi** [comment]
It seems #8332 is required to merge this.

**Comment by riccardotosi** [comment]
@marcnunezc, can you have a look at the changes related to the serialization? The changes I introduce set the `materials filename = ""`, to remove the printing of many warnings. All tests work fine (both python and compss).

**Comment by marcnunezc** [comment]
> @marcnunezc, can you have a look at the changes related to the serialization? The changes I introduce set the `materials filename = ""`, to remove the printing of many warnings. All tests work fine (both python and compss).

Seems ok to me, is it ready to merge?

**Comment by riccardotosi** [comment]
> 
> 
> > @marcnunezc, can you have a look at the changes related to the serialization? The changes I introduce set the `materials filename = ""`, to remove the printing of many warnings. All tests work fine (both python and compss).
> 
> Seems ok to me, is it ready to merge?

Yes, I guess so. I will open a parallel MR in XMC and then we can merge the two PRs together.

**Comment by riccardotosi** [comment]
@marcnunezc if you agree with the changes, can you approve?

**Review by marcnunezc — APPROVED** [review]

**Pull request merged**
