### PR TITLE
[Core][Geometry] QuadraturePointCurveOnSurface

### PR DESCRIPTION
**Pull request by tteschemacher**
Hi all,

I am adding here the corresponding quadrature point for curve on surfaces. It authomatically sums up with the essential length segments in the quadrature point.

The theory can be taken from https://amses-journal.springeropen.com/articles/10.1186/s40323-018-0109-4
Eq. (11)

Thanks!

### CODE REVIEW

**Comment by tteschemacher** [comment]
@pooyan-dadvand do you agree with this implementation?

**Comment by tteschemacher** [comment]
@pooyan-dadvand I removed the constructors which are not needed at the moment. Can we merge it?

**Review by pooyan-dadvand — APPROVED** [review]
👍

**Comment by tteschemacher** [comment]
thanks!

**Pull request merged**
