### PR TITLE
[Core] Extend InvertMatrix for bounded matrices

### PR DESCRIPTION
**Pull request by loumalouomega**

### CODE REVIEW

**Comment by AlejandroCornejo** [comment]
It is the same that you sent me? If it is the case check the compilation. I had to add a few lines declaring sizes

**Comment by loumalouomega** [comment]
> It is the same that you sent me? If it is the case check the compilation. I had to add a few lines declaring sizes

A little better

**Comment by AlejandroCornejo** [comment]
I wait for @RiccardoRossi to approve

**Comment by loumalouomega** [comment]
> I wait for @RiccardoRossi to approve

You were right, some size was missing

**Comment by loumalouomega** [comment]
Anyone?

**Review by AlejandroCornejo — APPROVED** [review]

**Comment by loumalouomega** [comment]
@AlejandroCornejo check your branch now

**Pull request merged**
