### PR TITLE
[Core] Adding value_type typedef to PointerVector

### PR DESCRIPTION
**Pull request by tteschemacher**
Hi all,

I would like to change the typedef in the pointer_vector for the data_type to the value_type. This is then the same type as the std::vector has. To template classes with the container this would allow a consitant templatisation.

### CODE REVIEW

**Review by pooyan-dadvand — APPROVED** [review]
For the record, the title is wrong. It adds the value_type typedef

**Review by pooyan-dadvand — CHANGES_REQUESTED** [review]
Seems that I missread the code. So I just block it to check the compatibility

**Comment by tteschemacher** [comment]
I checked without the value_type and Travis and Appeveyor pass the checks.

**Comment by tteschemacher** [comment]
@pooyan-dadvand can we merge this?

**Comment by pooyan-dadvand** [comment]
This is API breaker and we should pass by @KratosMultiphysics/technical-committee

**Comment by pooyan-dadvand** [comment]
@KratosMultiphysics/technical-committee agreed to this change.

**Comment by philbucher** [comment]
ping @pooyan-dadvand you did not approve

**Comment by tteschemacher** [comment]
Can I merge this?

Thanks!

**Comment by tteschemacher** [comment]
@pooyan-dadvand you requested changes. I suppose we can merge this, right?

**Review by pooyan-dadvand — APPROVED** [review]

**Pull request merged**
