### PR TITLE
initial support for trilinos mumps

### PR DESCRIPTION
**Pull request by RiccardoRossi**
title says it all

@philbucher @armingeiser @loumalouomega this requires recent version of trilinos configured to use mumps during the compilation. The package that comes with the latest ubuntu complies with this requirement.

Note that i had to change slightly the way the solver was called, which might break some old code. we shall discuss this...

### CODE REVIEW

**Comment by philbucher** [comment]
@RiccardoRossi that was fast!

Just for me to understand, you install mumps and tell Trilinos during its compilation to make use of it?
Which version of Trilinos/mumps do you use?

**Comment by RiccardoRossi** [comment]
Old versions of trilinos supported mumps 4.9. It looks like the later ones also support 5.1.2 (the latest).

If you go for compiling trilinos on your own, than you should first compile mumps and then configure trilinos by activating the MUMPS_TPL (part of Amesos).
Nice thing is that the trilinos that comes with ubuntu 18.04 has that active, so you can test drive it with relative ease. 

One of the problems with the current PR was that i had to change the solver interface. I believe that the old one was broken for direct solvers (in MPI)

the new interface is of the type

     {
          "solver_type": "AmesosSolver",
          "amesos_solver_type" : "Amesos_Mumps",   ...HERE IT COULD BE Amesos_Superludist, Amesos_Klu
          "scaling":false,
          "trilinos_amesos_parameter_list": {}
     }

also i think that we should remove the "scaling" option, anyway the solvers do it (better) internally

**Comment by philbucher** [comment]
@RiccardoRossi I will wait a bit with 18.04 so I will install trilinos myself.

Regarding mumps I assume you have installed he MPI-parallel version? Also then you installed all the required dependencies?
~~~
If you want to use the parallel (distributed memory MPI based) version, 
you need:
-> MPI
-> BLAS library 
-> BLACS library
-> LAPACK and ScaLAPACK libraries
~~~

Did you also install the following?
~~~
For performance (time and memory issues) we very strongly recommend to install:
-> SCOTCH and/or METIS for the sequential and parallel versions
~~~

**Comment by philbucher** [comment]
@RiccardoRossi I installed ubuntu 18.04 and installed trilinos & stuff with the package manager
Worked out of the box, also Mumps came with it

The test runs for me

How should we proceed?

**Comment by RiccardoRossi** [comment]
Hi @philbucher  the bad thing is that i had to slightly change the existing interface in order to make this possible.

In my opinion we could still merge the PR as i think it was a very rarely used feature...

**Comment by philbucher** [comment]
You mean that all the direct solvers have to be used through Amesos?

**Comment by RiccardoRossi** [comment]
yes. Actually i fail to understand how it could work before...

**Comment by philbucher** [comment]
@RiccardoRossi I did some cleanup an improvements, now I think it works nicely

Basically any solver compiled with amesos would work without requiring further modifications

I also updated the python-solvers in the applications

**Comment by philbucher** [comment]
@RiccardoRossi I think I found a better way of handling the solver selection, similar to what aztec and ML do

Please give me time until tmr then I think we can have a good and consistent solution

**Comment by philbucher** [comment]
@RiccardoRossi what I wanted to do did not work bcs Amesos seems to have a different interface than Aztec

Therefore this is ready to be reviewed (and merged) imo

**Comment by RiccardoRossi** [comment]
Hi @philbucher ok, then let's put it into.

also i think we should soon solve #615. @pooyan-dadvand please take a look at asap, i think it would be a nice-to-have for release 6.0 (not a blocker though...)

**Review by philbucher — DISMISSED** [review]

**Comment by philbucher** [comment]
I would merge it tmr in case someone wants to have a look

**Comment by RiccardoRossi** [comment]
ok, i am travelling, so if tomorrow night no one had objections please go ahead with the merging

cheers
Riccardo

**Comment by philbucher** [comment]
@RiccardoRossi ok I will do that

In the last commit I renamed the solver name to be consistent with the others in trilinos

**Review by philbucher — APPROVED** [review]

**Pull request merged**
