### PR TITLE
[ContactStructuralMechanicsApplication] Some cleaning

### PR DESCRIPTION
**Pull request by loumalouomega**

### CODE REVIEW

**Review by RiccardoRossi — COMMENTED** [review]
what are u solving with this?

**Comment by loumalouomega** [comment]
It is an intermediate cleaning before migrate to the table logger

**Comment by loumalouomega** [comment]
Sorry wrong PR. Don't read previous comment.

This is just a cleaning, removing unused stuff and adding a new test

**Comment by RiccardoRossi** [comment]
but i see that you are changing something about the frictional contact. is the current problem fixed?

**Comment by loumalouomega** [comment]
No, but this is a minor necessary change

**Comment by loumalouomega** [comment]
Can anyone approve?

**Review by marandra — APPROVED** [review]
Sure

**Comment by loumalouomega** [comment]
Thanks

**Pull request merged**
