### PR TITLE
Removing apis from explicit instantiations

### LINKED ISSUE #4718: [StructuralMechanics] compiler warnings in Travis
can you please have a look?
~~~
In file included from /home/travis/build/KratosMultiphysics/Kratos/cmake_build/applications/StructuralMechanicsApplication/cotire/KratosStructuralMechanicsCore_CXX_unity.cxx:80:0:
/home/travis/build/KratosMultiphysics/Kratos/applications/StructuralMechanicsApplication/custom_response_functions/adjoint_elements/adjoint_finite_difference_base_element.cpp: At global scope:
/home/travis/build/KratosMultiphysics/Kratos/applications/StructuralMechanicsApplication/custom_response_functions/adjoint_elements/adjoint_finite_difference_base_element.cpp:629:55: warning: type attributes ignored after type is already defined [-Wattributes]
 template class KRATOS_API(STRUCTURAL_MECHANICS_APPLICATION) AdjointFiniteDifferencingBaseElement<ShellThinElement3D3N>;
                                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/travis/build/KratosMultiphysics/Kratos/applications/StructuralMechanicsApplication/custom_response_functions/adjoint_elements/adjoint_finite_difference_base_element.cpp:630:55: warning: type attributes ignored after type is already defined [-Wattributes]
 template class KRATOS_API(STRUCTURAL_MECHANICS_APPLICATION) AdjointFiniteDifferencingBaseElement<CrBeamElementLinear3D2N>;
                                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/travis/build/KratosMultiphysics/Kratos/applications/StructuralMechanicsApplication/custom_response_functions/adjoint_elements/adjoint_finite_difference_base_element.cpp:631:55: warning: type attributes ignored after type is already defined [-Wattributes]
 template class KRATOS_API(STRUCTURAL_MECHANICS_APPLICATION) AdjointFiniteDifferencingBaseElement<TrussElement3D2N>;
                                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/travis/build/KratosMultiphysics/Kratos/applications/StructuralMechanicsApplication/custom_response_functions/adjoint_elements/adjoint_finite_difference_base_element.cpp:632:55: warning: type attributes ignored after type is already defined [-Wattributes]
 template class KRATOS_API(STRUCTURAL_MECHANICS_APPLICATION) AdjointFiniteDifferencingBaseElement<TrussElementLinear3D2N>;
                                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/travis/build/KratosMultiphysics/Kratos/cmake_build/applications/StructuralMechanicsApplication/cotire/KratosStructuralMechanicsCore_CXX_unity.cxx:81:0:
/home/travis/build/KratosMultiphysics/Kratos/applications/StructuralMechanicsApplication/custom_response_functions/adjoint_elements/adjoint_finite_difference_shell_element.cpp:208:55: warning: type attributes ignored after type is already defined [-Wattributes]
 template class KRATOS_API(STRUCTURAL_MECHANICS_APPLICATION) AdjointFiniteDifferencingShellElement<ShellThinElement3D3N>;
                                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/travis/build/KratosMultiphysics/Kratos/cmake_build/applications/StructuralMechanicsApplication/cotire/KratosStructuralMechanicsCore_CXX_unity.cxx:82:0:
/home/travis/build/KratosMultiphysics/Kratos/applications/StructuralMechanicsApplication/custom_response_functions/adjoint_elements/adjoint_finite_difference_cr_beam_element_3D2N.cpp:101:55: warning: type attributes ignored after type is already defined [-Wattributes]
 template class KRATOS_API(STRUCTURAL_MECHANICS_APPLICATION) AdjointFiniteDifferenceCrBeamElement<CrBeamElementLinear3D2N>;
                                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/travis/build/KratosMultiphysics/Kratos/cmake_build/applications/StructuralMechanicsApplication/cotire/KratosStructuralMechanicsCore_CXX_unity.cxx:83:0:
/home/travis/build/KratosMultiphysics/Kratos/applications/StructuralMechanicsApplication/custom_response_functions/adjoint_elements/adjoint_finite_difference_truss_element_3D2N.cpp:242:55: warning: type attributes ignored after type is already defined [-Wattributes]
 template class KRATOS_API(STRUCTURAL_MECHANICS_APPLICATION) AdjointFiniteDifferenceTrussElement<TrussElement3D2N>;
                                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/travis/build/KratosMultiphysics/Kratos/applications/StructuralMechanicsApplication/custom_response_functions/adjoint_elements/adjoint_finite_difference_truss_element_3D2N.cpp:243:55: warning: type attributes ignored after type is already defined [-Wattributes]
 template class KRATOS_API(STRUCTURAL_MECHANICS_APPLICATION) AdjointFiniteDifferenceTrussElement<TrussElementLinear3D2N>;
                                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/travis/build/KratosMultiphysics/Kratos/cmake_build/applications/StructuralMechanicsApplication/cotire/KratosStructuralMechanicsCore_CXX_unity.cxx:84:0:
/home/travis/build/KratosMultiphysics/Kratos/applications/StructuralMechanicsApplication/custom_response_functions/adjoint_elements/adjoint_finite_difference_truss_element_linear_3D2N.cpp:65:55: warning: type attributes ignored after type is already defined [-Wattributes]
 template class KRATOS_API(STRUCTURAL_MECHANICS_APPLICATION) AdjointFiniteDifferenceTrussElementLinear<TrussElementLinear3D2N>;
                                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/travis/build/KratosMultiphysics/Kratos/cmake_build/applications/StructuralMechanicsApplication/cotire/KratosStructuralMechanicsCore_CXX_unity.cxx:85:0:
/home/travis/build/KratosMultiphysics/Kratos/applications/StructuralMechanicsApplication/custom_response_functions/adjoint_elements/adjoint_solid_element.cpp:328:55: warning: type attributes ignored after type is already defined [-Wattributes]
 template class KRATOS_API(STRUCTURAL_MECHANICS_APPLICATION) AdjointSolidElement<TotalLagrangian>;
~~~

### PR DESCRIPTION
**Pull request by roigcarlo**
closes #4718

### CODE REVIEW

**Comment by loumalouomega** [comment]
The thing is, if not exposed to python the API is not mandatory?

**Comment by roigcarlo** [comment]
I am not sure if the instantiation needs to be exposed. In any case, it dosn't look like anyone is using it outside the app kernel.

I am testing another solution moving the decorator.

**Comment by philbucher** [comment]
I think travis does not build bcs it is a draft PR

**Comment by philbucher** [comment]
@roigcarlo is it ok to mark it as ready for review to make travis build it?

**Comment by roigcarlo** [comment]
Ok, but still not sure if it will fix the problem

**Comment by philbucher** [comment]
ok

**Review by philbucher — APPROVED** [review]
warnings are gone, thx @roigcarlo

**Pull request merged**
