### PR TITLE
[ConstitutiveLaws] Extension of the serial-parallel rule of mixtures 

### PR DESCRIPTION
**Pull request by jsebasgp1**
**📝 Description**
Preparing the SP RoM to be used with advanced CLs such the High cycle fatigue CL and let it work with the advance in time process.

**🆕 Changelog**
- Defined new Has/Set/Get/Calculate Value methods
- Implementing the InitializeMaterialResponse methods
- Implemented new variables to control the internal variables evolution at the component level (UNIAXIAL_STRESS_FIBER & UNIAXIAL_STRESS_MATRIX)

### CODE REVIEW

**Review by AlejandroCornejo — DISMISSED** [review]
Seems ok to me

**Comment by loumalouomega** [comment]
CI is failing

**Review by loumalouomega — APPROVED** [review]

**Review by SergioJimenezReyes — APPROVED** [review]
Thanks for the changes @loumalouomega 
It looks fine to me.

**Comment by SergioJimenezReyes** [comment]
I am merging it @jsebasgp1 because I need these changes

**Pull request merged**
