### PR TITLE
[Structural][BaseSolid] not building RHS in CalculateLeftHandSide

### PR DESCRIPTION
**Pull request by philbucher**
discovered by @emiroglu 

not sure if there is a reason this was like this @RiccardoRossi @loumalouomega

### CODE REVIEW

**Review by loumalouomega — APPROVED** [review]
Ups, sorry

**Comment by philbucher** [comment]
tests are running, merging

**Comment by RiccardoRossi** [comment]
looks like an error...

**Comment by philbucher** [comment]
What do you mean?

**Comment by RiccardoRossi** [comment]
that i think thencorrection you did is correct, and that the nase class had
an error

**Pull request merged**
