### PR TITLE
[Core][Integration] Create Integration Points

### PR DESCRIPTION
**Pull request by tteschemacher**
Hi all,

I am adding here a interface which allows to CreateIntegrationPoints. If certain geometries need own integration methods, or don't provide the data via the GeomertyData this interface should be used.

Thx!

### CODE REVIEW

**Comment by philbucher** [comment]
general question, does this have to be a function of `Geometry`?
To me it looks like this could be done from an external utility

EDIT:
basically refactor `CreateIntegrationPoints` to be in a utility

**Comment by tteschemacher** [comment]
It could be, but then you would need to know about the derived type. So we are making use of the hierarchy here. That's why I want to put it as an interface, here.

**Comment by tteschemacher** [comment]
I am closing this PR. All developments are transferred to #6277.

**Comment by pooyan-dadvand** [comment]
Do you need the branch?

**Pull request closed without merging**
