### PR TITLE
[Core][MPI] Update `SearchUtilities`. Transition for #11719

### PR DESCRIPTION
**Pull request by loumalouomega**
**📝 Description**

This PR is updating `SearchUtilities`. Transition for https://github.com/KratosMultiphysics/Kratos/pull/11719.

**🆕 Changelog**

- [Update `SearchUtilities`](https://github.com/KratosMultiphysics/Kratos/commit/bd5410c1ab8a343e375cc9302f1150626a38bb7d)
- [Update tests for search utilities](https://github.com/KratosMultiphysics/Kratos/commit/0a5beb7e607e42470b3407b3e67f9aa843817fae)

### CODE REVIEW

**Comment by loumalouomega** [comment]
@roigcarlo ?

**Review by roigcarlo — COMMENTED** [review]
Why do you change the type of `all_points_ids` in the test from `std::size_t` to `long int`, but then in search utilities is still `IndexType` (which is `std::size_t`) for the globals, but `std::ptrdiff_t` for the locals? 

Rest of the changes are ok, but I don't get the type switches you made :S

**Comment by loumalouomega** [comment]
> Why do you change the type of `all_points_ids` in the test from `std::size_t` to `long int`, but then in search utilities is still `IndexType` (which is `std::size_t`) for the globals, but `std::ptrdiff_t` for the locals?
> 
> Rest of the changes are ok, but I don't get the type switches you made :S

I needed the negative ids in order to determine null sets :P

**Review by roigcarlo — APPROVED** [review]
omg.. ok

**Pull request merged**
