### PR TITLE
[Core] Restoring NODE_PROPERTY_ID from deprecated

### PR DESCRIPTION
**Pull request by MZecchetto**
Dear all,
with this PR I ask to retrieve the `NODE_PROPERTY_ID` variable from the deprecated ones.
I need it to correctly set the property of the elements after the re-meshing process. Its value is set in the PfemFluidApp and retrieved in the DelaunayApp. 
Open to better suggestions.
With best regards,

Massimiliano

### CODE REVIEW

**Comment by loumalouomega** [comment]
Just to say that you don't need to do that in order to preserve the properties (and you avoid to store integers in all nodes). See https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/utilities/assign_unique_model_part_collection_tag_utility.cpp (it is used here for example fro remeshing https://github.com/KratosMultiphysics/Kratos/blob/master/applications/MeshingApplication/custom_processes/mmg_process.cpp)

**Comment by MZecchetto** [comment]
Dear @loumalouomega,
thanks for the hint. 
I understand that adding another integer to the nodes is probably not the best way to proceed, but what I have is always a single sub model part with a cloud of points having different values for the nodal variables and a list of properties that belong to that sub model part. Furthermore, at each iteration the re-meshing process adds and deletes a lot of nodes, so I need to assign a `Tag` also to these new ones. Using an integer the PfemFluidApp is able to handle this and with two lines of code the party is over.
Retrieving the property from the elements of the previous mesh is not an option.
Anyway, if retrieving `NODE_PROPERTY_ID` is not possible, I'll arrange myself otherwise. Kindly advise.

**Comment by philbucher** [comment]
hi @MZecchetto 
Side comment: You can define the needed variable in both apps, it will be the same (was changed like a year ago)
This way you can access it from both apps

**Comment by MZecchetto** [comment]
Thanks for letting me know @philbucher!

**Pull request closed without merging**
