### PR TITLE
DEM and Swimming DEM to json...

### PR DESCRIPTION
**Pull request by maceligueta**
This tries to bring back everything that was lost when we reverted the PR 771

### CODE REVIEW

**Comment by pooyan-dadvand** [comment]
It seems that travis is failing to find the compiler. @roigcarlo any idea?

**Comment by roigcarlo** [comment]
Seems like an connection error to me. I will re activate the push integration

**Comment by roigcarlo** [comment]
Ready.

**Review by farrufat-cimne — APPROVED** [review]
It includes the latest changes made to DEM application

**Pull request merged**
