### PR TITLE
[Core] Make private copy constructor of Variable

### PR DESCRIPTION
**Pull request by loumalouomega**
**📝 Description**

Making private* copy constructor of Variable. For memory safety.

FYI @ddiezrod, related #7296

*So it can be used by a friend class. Required for new resgitry FYI @pooyan-dadvand 

**🆕 Changelog**

- [Remove copy constructor of Variable](https://github.com/KratosMultiphysics/Kratos/commit/b9e047bcf7112a796ea3cbcceb25958faa1be18d)
- [Better private so it be declared as friend class for new registry](https://github.com/KratosMultiphysics/Kratos/pull/10381/commits/ba70f311fa1aaca6009bc05fa7f6e64654626f58)
- [Passing by reference in VariableUtils](https://github.com/KratosMultiphysics/Kratos/commit/4503ccd5322ee1e4f5cf0979dfd435285c56d62a)
- [Pass by reference in debug_utilities](https://github.com/KratosMultiphysics/Kratos/commit/802c1b925324e0cb1a221415064b6b3c67263016)
- [Fix MeshingApp](https://github.com/KratosMultiphysics/Kratos/commit/cdd9864d2cee53ec3d05b0b00a57f0860a3bd6d0)
- [Fix fluid app](https://github.com/KratosMultiphysics/Kratos/commit/de0d283f0383ee4c898b1577e9629b8f3a7da7bc)
- [Fix Structural app](https://github.com/KratosMultiphysics/Kratos/commit/dff5d8a35ca5327eb324685e2278afc79fbe4a77)
- [Using reference in StatisticsApplication](https://github.com/KratosMultiphysics/Kratos/pull/10381/commits/3c0ac69cad95cb7a82a2c7766f0a7e5572449b66)

### CODE REVIEW

**Comment by matekelemen** [comment]
Weeeell, if we were to follow along these lines, all constructors should be made private to avoid creating dangling references.

**Comment by loumalouomega** [comment]
> Weeeell, if we were to follow along these lines, all constructors of `Variable` should be made private to avoid creating dangling references.

And tried, but then macros don't work

**Comment by matekelemen** [comment]
Yep, you'd have to define some ```VariableFactory``` friend class that has access to the private constructors of ```Variable```. Technically, it would be the only class authorized to instantiate ```Variable```, so the macros would need to be changed accordingly.

I'm not too serious about it though, and don't want to force you to do it.

**Comment by loumalouomega** [comment]
> Yep, you'd have to define some `VariableFactory` friend class that has access to the private constructors of `Variable`. Technically, it would be the only class authorized to instantiate `Variable`, so the macros would need to be changed accordingly.
> 
> I'm not too serious about it though, and don't want to force you to do it.

@pooyan-dadvand maybe we can solve the problem we mentioned instead of delete with private+friend

**Comment by loumalouomega** [comment]
Okay, looks like this is ready @KratosMultiphysics/technical-committee

**Review by RiccardoRossi — COMMENTED** [review]
i think this is a wise change, and i would be favorable to have it in.

@KratosMultiphysics/technical-committee do you have any resistance to this?

**Review by rubenzorrilla — COMMENTED** [review]
I also agree with the change. Besides, the other changes fix some potential memory issues so IMO this is ready to be merged.

Just mentioning that the variable factory @matekelemen is pointing will (soon) be the `Registry`. Hence, making the registry friend of the `Variable` should be the unique requirement as observed by @matekelemen .

**Review by rubenzorrilla — APPROVED** [review]
I think this should go in.

**Pull request merged**
