### PR TITLE
[Core] Deprecate old projection methods

### PR DESCRIPTION
**Pull request by rubenzorrilla**
**Description**
This PR deprecates the old `ProjectionPoint` method according to the discussion in #8491. So far only the "simple" geometries have been modified. @tteschemacher will proceed with the IGA-related geometries.

`ClosestPoint` method will be deprecated in an future PR.

**Changelog**
Deprecation of the `ProjectPoint` method in favor of the  `ProjectPointLocalToLocalSpace` and `ProjectPointGlobalToLocalSpace`.

### CODE REVIEW

**Review by rubenzorrilla — COMMENTED** [review]
@tteschemacher changes have been done accordingly. I also agree on adding the deprecation warning in the "standard" geometries only.

**Comment by rubenzorrilla** [comment]
It seems that there is a `model_tolerance` leftover.

**Comment by rubenzorrilla** [comment]
@tteschemacher it seems that there are still some issues with the debug compilations.

**Comment by tteschemacher** [comment]
> 
> 
> @tteschemacher it seems that there are still some issues with the debug compilations.

here we go.

**Comment by tteschemacher** [comment]
@rubenzorrilla @roigcarlo this is finished from my side and I think we should merge as soon as possible to avoid further conflicts.

**Comment by rubenzorrilla** [comment]
Completely agree, but I we need someone to review / approve it.

**Review by roigcarlo — DISMISSED** [review]
Blame me if it breaks something :+1:

**Review by roigcarlo — APPROVED** [review]

**Review by tteschemacher — APPROVED** [review]

**Pull request merged**
