### PR TITLE
Error with the OMP using unordered_map

### PR DESCRIPTION
**Pull request by loumalouomega**
Error detected by @annasophie91

### CODE REVIEW

**Comment by loumalouomega** [comment]
I tried several ways to fill the unordered_map in OMP, but it always defers from the single thread output, so I decided to remove it definitely

**Review by annasophie91 — APPROVED** [review]

**Comment by RiccardoRossi** [comment]
Hi Vicente.

The unordered_map is not threasafe, so you can not concurrently use it.
However you can use one different unordered_map per thread

Cheers
Riccardo

**Comment by loumalouomega** [comment]
@RiccardoRossi That is what I tried, but it was either slow and giving different results comparing with one thread solution

**Comment by RiccardoRossi** [comment]
I think you must be doing something wrong, we 'll discuss this in person on
the first week of September

Ciao
Riccardo

**Pull request merged**
