### PR TITLE
[Core][Analysis] Define _AdvanceTime in base analysis

### PR DESCRIPTION
**Pull request by loumalouomega**
**📝 Description**

In @KratosMultiphysics/altair  we define in the analysis the method _AdvanceTime, which by default calls the method from the solver as it is done right now in the base analysis class. I think unifying interfaces could benefit, reducing code duplication and extending modularity of current analysis

**🆕 Changelog**

- Define _AdvanceTime in base analysis

### CODE REVIEW

**Review by rubenzorrilla — CHANGES_REQUESTED** [review]
With this you're opening the possibility to calculate the time step in the analysis stage, something that now is forbidden, making mandatory to calculate it in the solver. 

I'd prefer to keep the way it is right now, but we can discuss it in the @KratosMultiphysics/technical-committee.

**Comment by loumalouomega** [comment]
> With this you're opening the possibility to calculate the time step in the analysis stage, something that now is forbidden, making mandatory to calculate it in the solver.
> 
> I'd prefer to keep the way it is right now, but we can discuss it in the @KratosMultiphysics/technical-committee.

As I said, we do like this in @KratosMultiphysics/altair, the idea is to unify interfaces. (and this is just one step, the simplest one I found...)

**Comment by sunethwarna** [comment]
My thoughts on this :)

We define `start_time`, `end_time` in the `problem_data` section, and time step somewhere in the `solver_settings` (not in a consistent manner also). Which kind of feels like time marching is a shared responsibility between the `AnalysisStage` and `PythonSolver`. Wouldn't it be better to leave this responsibility with one class?

**Comment by miguelmaso** [comment]
> We define `start_time`, `end_time` in the `problem_data` section, and time step somewhere in the `solver_settings` (not in a consistent manner also). Which kind of feels like time marching is a shared responsibility between the `AnalysisStage` and `PythonSolver`. Wouldn't it be better to leave this responsibility with one class? It would be harder with the automatic time marching, but is there a way to have it also? Just looking for options :)

from my point of view, `start_time` and `end_time` belong to the continuous problem and the `time_step` belongs to the discrete problem. So I find cleaner having different classes managing different things. Of course, they have the same units, but are still different.

**Comment by rubenzorrilla** [comment]
> > We define `start_time`, `end_time` in the `problem_data` section, and time step somewhere in the `solver_settings` (not in a consistent manner also). Which kind of feels like time marching is a shared responsibility between the `AnalysisStage` and `PythonSolver`. Wouldn't it be better to leave this responsibility with one class? It would be harder with the automatic time marching, but is there a way to have it also? Just looking for options :)
> 
> from my point of view, `start_time` and `end_time` belong to the continuous problem and the `time_step` belongs to the discrete problem. So I find cleaner having different classes managing different things. Of course, they have the same units, but are still different.

Totally agree. Note that for the same physics time marching might be completely different depending on the explicit/implicit nature of the strategy, something that is managed at the solver level.

**Comment by ddiezrod** [comment]
I agree that the better place for the AdvanceTimeStep function is inside solver. Our problem was that in some cases we want to finish our analysis exactly at the final time given by the user. The end of the simulation is controlled inside the analysis, that is why the simpler solution I saw was to move the AdvanceTime function to the analysis so it can change the delta time provided by the solver so it can be adjusted with respect to the final time.

**Comment by RiccardoRossi** [comment]
so, we @KratosMultiphysics/technical-committee  agree about this change.

also once we give up with this restriction we shall also add a _Predict() and _SolveSolutionStep() methods defaulting to the current behaviour. We shall comment those functions telling that by default they should call the solver ...

**Review by rubenzorrilla — APPROVED** [review]
Removing my blockage after our discussion in the @KratosMultiphysics/technical-committee

**Comment by loumalouomega** [comment]
Hurray

**Comment by philbucher** [comment]
why did you call it `_AdvanceTime` and not `_AdvanceInTime` (consistent with the solver)?

**Comment by loumalouomega** [comment]
You are technically right, but the main point was to unify with our
internal analysis implementation (maybe we should have changed that at that
time). Do you consider that in this case we should impose consistency?

**Comment by philbucher** [comment]
Given that this is the main interface to Kratos and super easy to make backward compatible, I would say yes, it is worth unifying

**Comment by philbucher** [comment]
also it returns a time, but does not take a time as input :sweat_smile:

**Pull request merged**
