### PR TITLE
[StructuralMechanics] Fix EigenPost test

### PR DESCRIPTION
**Pull request by philbucher**
I found the error, no clue how it was working before, basically I used `AssertAlmostEqual` wrong

I also had to update the tests values, I don't know why but I checked with another example and the animation is still correct. It could also be that the tests values were wrong the entire time and since I used `AssertAlmostEqual` wrong they were not checked.

I changed the process to take the decimal_places instead of the tolerance as input, I think this makes more sense. Hope this is ok for you (I plan to migrate the `CompareTwoPointOutputFilesProcess` so this is also a preparation for this)

Could you please check if the tests in the MeshingApp still work, I don't have mmg compiled.

### CODE REVIEW

**Comment by philbucher** [comment]
see #1812

**Comment by loumalouomega** [comment]
The keys of the variables are changed. If your test included rotations and displacement probably are inverted in order.

**Comment by loumalouomega** [comment]
In conclusion the order of the dofs set is altered

**Review by loumalouomega — APPROVED** [review]
Oki doki

**Comment by philbucher** [comment]
yep that might be the reason, I have DISPLACEMENT and ROTATION

Have you tried the tests in the meshingapp?

**Comment by loumalouomega** [comment]
Nope, but I don't use the dof keys...I will check

**Comment by philbucher** [comment]
ping @loumalouomega do you want to run the tests before I merge this?

**Comment by loumalouomega** [comment]
It's OK, proceed

**Pull request merged**
