### PR TITLE
[Core] Exposing geometry of Elements/Conditions

### PR DESCRIPTION
**Pull request by philbucher**
Discussed with @jcotela 
With this one can access the `Geometry` of `Elements` and `Conditions` from Python
This helps to avoid things like [this](https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/python/add_mesh_to_python.cpp#L60-L83)

However it can be difficult if ppl start using the Geometry to create new Elems/Conds

### CODE REVIEW

**Comment by jcotela** [comment]
@KratosMultiphysics/technical-committee I believe this allows us to have a cleaner interface (currently we are allowing python access to geometry methods through elements/conditions), but we need to take care about what people can do with the geometry. Should the geometry be exposed as a pointer or a reference? Should we allow creating new elements from python using the returned geometry (only possible with pointer returns)?

**Comment by philbucher** [comment]
thanks for summing up the important points @jcotela

**Comment by jcotela** [comment]
We have discussed this at @KratosMultiphysics/technical-committee and the decision was to go with references (it is simpler, and we can always move to pointers in the future if we think we need them). Regarding the methods to provide access to, we would restrict it to methods to ask information about the geometry (nodes, normals, area, volume,... essentially what we access now through elements/conditions) and not give access to the internals for now.

**Comment by jcotela** [comment]
Also, I forgot to say that a GetGeometry method (replicating the one in C) would be preferred to the add_property approach, since in our experience it is easier for new developers if the class interface is as similar as possible between the Python and C++ layers.

**Comment by philbucher** [comment]
@KratosMultiphysics/technical-committee done

**Comment by philbucher** [comment]
ping @KratosMultiphysics/technical-committee

**Review by RiccardoRossi — APPROVED** [review]

**Comment by philbucher** [comment]
@pooyan-dadvand do you also want to review this or shall I merge?

**Comment by pooyan-dadvand** [comment]
Sorry, it was self assigned for discussion in the technical committee. 
It is ok for merge! :+1:

**Comment by philbucher** [comment]
thanks!

**Pull request merged**
