### PR TITLE
[ContactStructuralMechanicsApplications] FIxing compilation error

### PR DESCRIPTION
**Pull request by loumalouomega**
Hotfix for Release 7.0

### CODE REVIEW

**Review by philbucher — APPROVED** [review]

**Comment by loumalouomega** [comment]
@roigcarlo can you merge this?

**Comment by philbucher** [comment]
doesn't this also need a fix in Master?

**Comment by loumalouomega** [comment]
> doesn't this also need a fix in Master?

Already merged

**Comment by roigcarlo** [comment]
@loumalouomega Can you ping me the PR to the master?

**Review by roigcarlo — APPROVED** [review]
@loumalouomega Told me this is a cherry pick from master, so ok.

**Comment by loumalouomega** [comment]
@roigcarlo I cannot merge

**Comment by roigcarlo** [comment]
Ups sorry, I put some draconic requisites, let me change to something more normal

**Comment by loumalouomega** [comment]
Thanks

**Pull request merged**
