### PR TITLE
Remove OpenCl-Application

### PR DESCRIPTION
**Pull request by philbucher**
as discussed

### CODE REVIEW

**Review by RiccardoRossi — COMMENTED** [review]
I just saw that OCL spatial searching as done by @roigcarlo is in there.

@roigcarlo to me the application can be removed, but i let you approving (i originally forgot about your searching stuff...sorry)

**Review by roigcarlo — APPROVED** [review]
@RiccardoRossi No problem. I will keep that in a private repo. 👍

**Comment by philbucher** [comment]
ok then I will merge this some time next week
or just tell me if you need more time for saving the files @roigcarlo 

they should however also be in the previous releases ...

**Comment by roigcarlo** [comment]
Nono, the backup is done, go ahead

**Pull request merged**
