### PR TITLE
[HDFApp] XDMF - adding support for point based entities

### PR DESCRIPTION
**Pull request by philbucher**
**Description**
With this paraview can also display the point based entities, works like a charm now :)

@sunethwarna I think there are no tests for this part of the code or are there?

source: http://www.xdmf.org/index.php/XDMF_Model_and_Format#Topology

### CODE REVIEW

**Comment by sunethwarna** [comment]
This is really cool :) :+1: 

as for the test, we only have one test but it may not cover what you want :/
https://github.com/KratosMultiphysics/Kratos/blob/fa6e5150c1e458a24a14eda8ea9af61e00262934/applications/HDF5Application/tests/test_hdf5_xdmf.py#L55-L74

**Review by sunethwarna — DISMISSED** [review]

**Comment by philbucher** [comment]
cool I will do the tests asap

**Review by sunethwarna — APPROVED** [review]
Thanks @philbucher :)

**Comment by philbucher** [comment]
we decided not to add a test (for now) as this is quite tricky to test

**Pull request merged**
