### PR TITLE
Structural/Adding_damage_constitutive_law_for_masonry_3D

### PR DESCRIPTION
**Pull request by philipkalkbrenner**
Modified the masonry 2D law for use in 3D,
A test is added

### CODE REVIEW

**Comment by philbucher** [comment]
the test fails
Please make sure the tests are running in Release and FullDebug before making a PR

**Comment by philipkalkbrenner** [comment]
OK. Thanks.
On my machine the tests are running without errors. So I would need some help to solve this issue, please.

**Comment by AlejandroCornejo** [comment]
@philipkalkbrenner come to my office if you want and I'll show you the errors

**Comment by AlejandroCornejo** [comment]
@philbucher Do you know what this means: **Error: bad size**?? In windows we do not have this error..

**Comment by philbucher** [comment]
this error means that you are accessing a memory location that you shouldn't :)
typically this happens when iterating over a vector where the size is too small

This is afaik only checked when compiled in `FullDebug` for performance reasons
Have you tried in fulldebug?

**Review by AlejandroCornejo — APPROVED** [review]
Now if the checks pass you can merge @philipkalkbrenner

**Comment by philipkalkbrenner** [comment]
THANKS @loumalouomega  and  @AlejandroCornejo

**Comment by loumalouomega** [comment]
imagen

**Pull request merged**
