### PR TITLE
[Fluid/RANS] RANS Turbulence models integration - Step 1

### PR DESCRIPTION
**Pull request by sunethwarna**
Hi,

I have developed RANS for three different turbulence models with followings.

1. Three turbulence models (k-epsilon, k-omega, k-omega-sst)
2. All three turbulence models are capable to be used with either FractionalStep or Monolithic formulations from FluidApp.
3. All above mentioned Fractional step and Monolithic solvers with turbulence models are capable with URANS and RANS both.
4. Adjoints for turbulence models with flow solver adjoints

In order to achieve all of the above while having easily managable code, I had to deviate from existing way I was doing RANS. So this PR is the first PR in order to get things settled. **Now FluidApp doesnt have any dependency on RANS, but RANS is still dependent on FluidApp for fluid solvers.**

I have broken down Final PR into few steps so, it would be easier for review.

This PR has two tasks:
1. It removes all the RANS intrusions in Fluid App (Primal and Adjoint both)
2. It removes almost everything from RANS App, otherwise, when I do the PR for primal RANS stuff, it would be too much diff.

All the tests are passing in FluidApp, and RANS app tests are temporarily removed.

### CODE REVIEW

**Review by philbucher — DISMISSED** [review]
nice cleanup!
Thx for separating into multiple PRs

Since this only removes things I give it a go :+1: 

Can you please wait a few days with merging?
I think others might want to have a look too, you are modifying FluidDynamics after all ;)

**Comment by sunethwarna** [comment]
Thanks... For sure I will wait :)

**Review by adityaghantasala — DISMISSED** [review]

**Review by rubenzorrilla — APPROVED** [review]
Approving as this is only clean up. Sorry for the delay.

**Comment by sunethwarna** [comment]
thanks everyone :)

**Pull request merged**
