### PR TITLE
[BruteForcePointLocator] Add FindObject

### PR DESCRIPTION
**Pull request by miguelmaso**
**📝 Description**
With this changes it is possible to find a geometrical object (e.g. `FindIntersectedGeometricalObjects` returns a pointer vector of geometrical objects)

**🆕 Changelog**
- Add `FindObject`
- Style guide

### CODE REVIEW

**Comment by philbucher** [comment]
Personally I am ok with merging this, but for me the question is more if we want to extend this class even though we have better options available (e.g. BinSearch) Why don't you use that one?

**Comment by miguelmaso** [comment]
I want to project a line on a volume and do some operations at every node of the line (integrate along the direction of projection, search at a specified distance, find the bounds...)

g854

In a first stage, I use `FindIntersectedGeometricalObjects` (uses an octree, more or less like the bin based point locator) to find all the elements intersected by the projection of each point.

In a second stage, every node uses `BruteForcePointLocator` to perform the operations. Note that the candidates are very few elements.

**Comment by miguelmaso** [comment]
> In a first stage, I use `FindIntersectedGeometricalObjects` (uses an octree, more or less like the bin based point locator) to find all the elements intersected by the projection of each point.
> 
> In a second stage, every node uses `BruteForcePointLocator` to perform the operations. Note that the candidates are very few elements.

Maybe the `BinBased` is faster than all of this?

**Review by philbucher — APPROVED** [review]
ok then :)
If you know what you are doing then fine :)

**Comment by miguelmaso** [comment]
> the question is more if we want to extend this class even though we have better options available (e.g. BinSearch) Why don't you use that one?

thanks, this question helped me to find a better solution

**Pull request closed without merging**
