### PR TITLE
[Core] Replace Cotire with CMake Unity Build

### PR DESCRIPTION
**Pull request by loumalouomega**
**Description**
From the official Cotire repo: https://github.com/sakra/cotire

> The functionality provided by cotire has been superseded by features added to CMake 3.16. Support for pre-compiling and unity builds is now built into CMake. Thus, there will not be any further updates or support for this project.

**Requires CMake 3.16** (which is available in many distros since long time ago).

As you can see in the changes the usage is much simpler (this PR removes lines instead of adding). Compilation is done in the standard way:

~~~sh
cmake --build "${KRATOS_BUILD}/${KRATOS_BUILD_TYPE}" --target install -- -j$(nproc)
~~~

instead of:

~~~sh
cmake --build "${KRATOS_BUILD}/${KRATOS_BUILD_TYPE}" --target all_unity    -- -j$(nproc) && \
cmake --build "${KRATOS_BUILD}/${KRATOS_BUILD_TYPE}" --target install/fast -- -j$(nproc)
~~~

And you don't need to explicitly cotire anything, you only need to add to your compilation the following flag: CMAKE_UNITY_BUILD=ON. CMake does the rest.

Last but not least, in order to exclude from unity it is necessary to change the property `SKIP_UNITY_BUILD_INCLUSION` instead of `COTIRE_EXCLUDED`.

But first let's see if in compiles in the CI...

**Changelog**
- refactor main CMake files
- Clean existing CMake application files
- Add missing compilation guards

### CODE REVIEW

**Comment by loumalouomega** [comment]
@roigcarlo and @philbucher the only remaining problem is the zlib compilation in Windows

**Comment by philbucher** [comment]
wow cool!

Unfortunately I have no clue abt the Win error :/

it even works in CentOS :smile:

**Comment by philbucher** [comment]
zlib seems to be missing the include guards
not sure if relevant

**Comment by philbucher** [comment]
@loumalouomega maybe you can test it locally with setting `FORCE_LOCAL_ZLIB_COMPILATION` to `ON`

**Comment by roigcarlo** [comment]
That should solve the zlib problems. It is a little ugly, maybe the correct solution would be to enable unity build per project as recommended in the doc.

Also, we need to tweak the `UNITY_BUILD_BATCH_SIZE`. With Cotire we could select a batch size of `-jProcs`, which meant that it scaled the size of the unity files not to a static number but to `total_files / num_procs`. It seems not possible to do this directly with cmake. I am investigating if we could obtain this number ourselves.

**Comment by loumalouomega** [comment]
@roigcarlo any idea how to solve it?, why libz is different of other libraries which are compiled at the same time?

**Comment by roigcarlo** [comment]
@loumalouomega Mm not sure what you mean. Zlib problems are solved. 

The issue in windows now are some templates from the structural, I will take a look next week it shouldn't be hard to fix

**Comment by philbucher** [comment]
regarding zlib it seems like we also compile examples?
Cannot we remove those? (in separate PR?)

**Comment by philbucher** [comment]
> The issue in windows now are some templates from the structural, I will take a look next week it shouldn't be hard to fix

oh no not the `AdjointSolidElement` again 🙈 
I fought with this quite a bit already :/

**Comment by roigcarlo** [comment]
> regarding zlib it seems like we also compile examples?

We can but the compilation is like 0.5 seconds, also the fix is require minimal changes so I will leave them enabled

**Comment by philbucher** [comment]
FYI @sunethwarna:
~~~ C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(1069,5): warning MSB8027: Two or more files with the name of test_utilities.cpp will produce outputs to the same location. This can lead to an incorrect build result.  The files involved are D:\a\Kratos\Kratos\applications\RANSApplication\custom_utilities\test_utilities.cpp, D:\a\Kratos\Kratos\applications\RANSApplication\tests\cpp\k_epsilon\test_utilities.cpp, D:\a\Kratos\Kratos\applications\RANSApplication\tests\cpp\k_omega\test_utilities.cpp, D:\a\Kratos\Kratos\applications\RANSApplication\tests\cpp\k_omega_sst\test_utilities.cpp. [D:\a\Kratos\Kratos\build\Custom\applications\RANSApplication\KratosRANSCore.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(1069,5): warning MSB8027: Two or more files with the name of element_data_utilities.cpp will produce outputs to the same location. This can lead to an incorrect build result.  The files involved are D:\a\Kratos\Kratos\applications\RANSApplication\custom_elements\data_containers\k_epsilon\element_data_utilities.cpp, D:\a\Kratos\Kratos\applications\RANSApplication\custom_elements\data_containers\k_omega_sst\element_data_utilities.cpp. [D:\a\Kratos\Kratos\build\Custom\applications\RANSApplication\KratosRANSCore.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(1069,5): warning MSB8027: Two or more files with the name of k_element_data.cpp will produce outputs to the same location. This can lead to an incorrect build result.  The files involved are D:\a\Kratos\Kratos\applications\RANSApplication\custom_elements\data_containers\k_epsilon\k_element_data.cpp, D:\a\Kratos\Kratos\applications\RANSApplication\custom_elements\data_containers\k_omega\k_element_data.cpp, D:\a\Kratos\Kratos\applications\RANSApplication\custom_elements\data_containers\k_omega_sst\k_element_data.cpp. [D:\a\Kratos\Kratos\build\Custom\applications\RANSApplication\KratosRANSCore.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(1069,5): warning MSB8027: Two or more files with the name of omega_element_data.cpp will produce outputs to the same location. This can lead to an incorrect build result.  The files involved are D:\a\Kratos\Kratos\applications\RANSApplication\custom_elements\data_containers\k_omega\omega_element_data.cpp, D:\a\Kratos\Kratos\applications\RANSApplication\custom_elements\data_containers\k_omega_sst\omega_element_data.cpp. [D:\a\Kratos\Kratos\build\Custom\applications\RANSApplication\KratosRANSCore.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(1069,5): warning MSB8027: Two or more files with the name of test_afc_elements.cpp will produce outputs to the same location. This can lead to an incorrect build result.  The files involved are D:\a\Kratos\Kratos\applications\RANSApplication\tests\cpp\k_epsilon\test_afc_elements.cpp, D:\a\Kratos\Kratos\applications\RANSApplication\tests\cpp\k_omega\test_afc_elements.cpp, D:\a\Kratos\Kratos\applications\RANSApplication\tests\cpp\k_omega_sst\test_afc_elements.cpp. [D:\a\Kratos\Kratos\build\Custom\applications\RANSApplication\KratosRANSCore.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(1069,5): warning MSB8027: Two or more files with the name of test_conditions.cpp will produce outputs to the same location. This can lead to an incorrect build result.  The files involved are D:\a\Kratos\Kratos\applications\RANSApplication\tests\cpp\k_epsilon\test_conditions.cpp, D:\a\Kratos\Kratos\applications\RANSApplication\tests\cpp\k_omega\test_conditions.cpp. [D:\a\Kratos\Kratos\build\Custom\applications\RANSApplication\KratosRANSCore.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(1069,5): warning MSB8027: Two or more files with the name of test_cwd_elements.cpp will produce outputs to the same location. This can lead to an incorrect build result.  The files involved are D:\a\Kratos\Kratos\applications\RANSApplication\tests\cpp\k_epsilon\test_cwd_elements.cpp, D:\a\Kratos\Kratos\applications\RANSApplication\tests\cpp\k_omega\test_cwd_elements.cpp, D:\a\Kratos\Kratos\applications\RANSApplication\tests\cpp\k_omega_sst\test_cwd_elements.cpp. [D:\a\Kratos\Kratos\build\Custom\applications\RANSApplication\KratosRANSCore.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(1069,5): warning MSB8027: Two or more files with the name of test_rfc_elements.cpp will produce outputs to the same location. This can lead to an incorrect build result.  The files involved are D:\a\Kratos\Kratos\applications\RANSApplication\tests\cpp\k_epsilon\test_rfc_elements.cpp, D:\a\Kratos\Kratos\applications\RANSApplication\tests\cpp\k_omega\test_rfc_elements.cpp, D:\a\Kratos\Kratos\applications\RANSApplication\tests\cpp\k_omega_sst\test_rfc_elements.cpp. [D:\a\Kratos\Kratos\build\Custom\applications\RANSApplication\KratosRANSCore.vcxproj]
~~~

**Comment by philbucher** [comment]
@KratosMultiphysics/altair does this affect you? Do you use cotire?

**Comment by ddiezrod** [comment]
> @KratosMultiphysics/altair does this affect you? Do you use cotire?

We have it as an option, but now is off by default. I think we are ok with the changes.

**Comment by loumalouomega** [comment]
Thanks @philbucher for fixing evil Windows

**Review by philbucher — DISMISSED** [review]
This is a better and cleaner/native solution than Cotire
It works in the CI and also seems to be ok for @KratosMultiphysics/altair 
Furthermore once this is in I can do #8404 
Since this is also used by very few devs I don't expect trouble from this

Bottom line: approving without much fuss :)
@loumalouomega please wait until tmr with merging in case someone has a final veto

thx for the effort!

**Comment by sunethwarna** [comment]
@loumalouomega could you wait with merging. I am not sure how critical are those warnings...

**Comment by philbucher** [comment]
> Also, we need to tweak the UNITY_BUILD_BATCH_SIZE. With Cotire we could select a batch size of -jProcs, which meant that it scaled the size of the unity files not to a static number but to total_files / num_procs. It seems not possible to do this directly with cmake. I am investigating if we could obtain this number ourselves.

@roigcarlo it seems like the build is slower now in the CI but I guess this is related to how many cores we use
On my PC is is quite a bit faster for some reason :man_shrugging:

**Comment by loumalouomega** [comment]
imagen

**Comment by roigcarlo** [comment]
@philbucher Yes, it slower, by far. As I said some coments above:

> Also, we need to tweak the UNITY_BUILD_BATCH_SIZE. With Cotire we could select a batch size of -jProcs, which meant that it scaled the size of the unity files not to a static number but to total_files / num_procs. It seems not possible to do this directly with cmake. I am investigating if we could obtain this number ourselves.

We should fix that before merging, but I haven't have time. The default value for that variable is something like 8, its very low, in any case if you want to merge fast we should increase it to ~32 or so.

**Comment by loumalouomega** [comment]
Can I merge now?

**Comment by philbucher** [comment]
> Can I merge now?

I think @roigcarlo wants to take a look

**Comment by roigcarlo** [comment]
I wouldn't mibd to to fix the parallel build, first but if you are fine with the current CI times we can do it later.

As you preffer

**Comment by loumalouomega** [comment]
> I wouldn't mibd to to fix the parallel build, first but if you are fine with the current CI times we can do it later.
> 
> As you preffer

If you don't know when are you going to have time to patch it, we can merge now, to avoid potential conflicts, do you agree?

**Comment by loumalouomega** [comment]
> I wouldn't mibd to to fix the parallel build, first but if you are fine with the current CI times we can do it later.
> 
> As you preffer

I did it myself, let's see

**Comment by loumalouomega** [comment]
@roigcarlo it worked, approval?

**Comment by loumalouomega** [comment]
> @roigcarlo it worked, approval?

 30 m vs 1h 41 m:

imagen

vs

imagen

**Review by roigcarlo — APPROVED** [review]
:+1:

**Comment by loumalouomega** [comment]
> +1

imagen

**Comment by loumalouomega** [comment]
BTW, you can adjust the number of files in the batch with the variable KRATOS_UNITY_BUILD_BATCH_SIZE

**Comment by philbucher** [comment]
nice work!

**Pull request merged**
