### PR TITLE
Ci/updating wheel builder

### PR DESCRIPTION
**Pull request by roigcarlo**
**Description**
Made several changes to the linux wheel scripts / dockerfiles.

**Changelog**
- Fixed several broken packages
- Added support for python 3.6 - 3.10
- Added individual interface and core targets
- Split core/interface compilation
- Tweak the wheel script to it does not delete temporal files from the core in the packaging stage.

### CODE REVIEW

**Comment by armingeiser** [comment]
Is it necessary to add the json files per application in `scripts/wheels/linux/applications`?

**Comment by philbucher** [comment]
> As far as I know yes.
> I am on it right now. I am trying to make it through CMake at configure time so we don't need to maintain it.,

ah is that where you use the generator expressions? :D

**Comment by roigcarlo** [comment]
> ah is that where you use the generator expressions? :D

:)

**Comment by roigcarlo** [comment]
If there is no complain with the changes, please someone approve. I will need some more PR after this one to set everything online and I prefer to split it into different parts, as otherwise it would grow to large to review.

As a follow up, the parts left to be done are:
- [ ] Include windows builds
- [ ] generate meta-files for all the applications automatically ( or have them as part of the applications, still haven't decided this )
- [ ] Activate HDF5
- [ ] Automatic upload to pypy / custom archive server
- [ ] Try to add support for Python 3.5.

**Review by philbucher — APPROVED** [review]

**Comment by roigcarlo** [comment]
Thx!

**Comment by philbucher** [comment]
@roigcarlo there is a CMake message that is a bit confusing to me, the `Interface List`
~~~
**** configuring KratosFluidDynamicsApplication ****
Adding application '/home/philipp/software/Kratos_master/applications/CoSimulationApplication'
**** configuring KratosCoSimulationApplication ****
Adding application '/home/philipp/software/Kratos_master/applications/MappingApplication'
**** configuring KratosMappingApplication ****
Adding application '/home/philipp/software/Kratos_master/applications/MeshMovingApplication'
**** configuring KratosMeshMovingApplication ****
Interface List: ;Kratos;KratosLinearSolversApplication;KratosStructuralMechanicsApplication;KratosFluidDynamicsApplication;KratosCoSimulationApplication;KratosMappingApplication;KratosMeshMovingApplication

***********************************************************************

        LIST OF APPLICATIONS THAT ARE GOING TO BE COMPILED:
~~~

It is also a bit awkwardly formatted.

Question: Is this information needed in production or can it be removed? If not a better message / formatting would be very helpful, can you please take a look?

**Comment by roigcarlo** [comment]
> Question: Is this information needed in production or can it be removed? If not a better message / formatting would be very helpful, can you please take a look?

No, no need in production. Let me remove it

**Pull request merged**
