### PR TITLE
[Core] Add missing radius array validation and creation to search strategies in Python bindings

### PR DESCRIPTION
**Pull request by loumalouomega**
**📝 Description**

It includes validation of the size of the radius array and ensures it is equal to the size of the input elements, nodes, or conditions array, depending on the context. KRATOS_ERROR_IF statements have been added to perform these checks, and if the sizes do not match, an error message is printed.

**🆕 Changelog**

- [Add missing radius array validation and creation to search strategies in Python bindings](https://github.com/KratosMultiphysics/Kratos/commit/c9bb63c1a238e15707dfdf35d5c67f697ecb1a13)

### CODE REVIEW

**Comment by matekelemen** [comment]
why don't you perform the check directly in `CopyRadiusArrayToPython`?

**Comment by loumalouomega** [comment]
> why don't you perform the check directly in `CopyRadiusArrayToPython`?

Because I did not realize that :P

**Comment by loumalouomega** [comment]
> > why don't you perform the check directly in `CopyRadiusArrayToPython`?
> 
> Because I did not realize that :P

Okay, you can do it, because you check against the size of the vector of entities, so it would not work

**Comment by loumalouomega** [comment]
Ping @matekelemen @roigcarlo

**Review by roigcarlo — APPROVED** [review]

**Pull request merged**
