### PR TITLE
[Core] Apply table process

### PR DESCRIPTION
**Pull request by miguelmaso**
**📝 Description**
This process sets a variable from a table.
More or less, it works as AssignScalarVariableProcess, but the value is defined by a table.

**🆕 Changelog**
- Add ApplyTableToVariableProcess
- Add test

### CODE REVIEW

**Comment by miguelmaso** [comment]
@AFranci does it solves your problem?

**Review by ipouplana — COMMENTED** [review]
Very nice @miguelmaso !

**Comment by AFranci** [comment]
> @AFranci does it solves your problem?

no pandas at the end??

**Comment by miguelmaso** [comment]
> > @AFranci does it solves your problem?
> 
> no pandas at the end??

#9831 is even better

**Comment by rubenzorrilla** [comment]
> > > @AFranci does it solves your problem?
> > 
> > 
> > no pandas at the end??
> 
> #9831 is even better

I was about to suggest this :+1:

**Pull request closed without merging**
