### PR TITLE
Warnings in Structural Mechanics due to HCF CL

### PR DESCRIPTION
**Pull request by SergioJimenezReyes**
Hope this solves the issue #5003 
I've modified a SetValue method which was not coincident with the one in the base class.

### CODE REVIEW

**Review by loumalouomega — DISMISSED** [review]
Thanks

**Comment by philbucher** [comment]
thx, but the warnings are still there, check the Clang CI

**Comment by SergioJimenezReyes** [comment]
@AlejandroCornejo and myself have tried it but we are not sure about how to solve the problem. 
As @philbucher mentioned in #5003 warnings are related with has, getvalue and setvalue methods and appear while compiling in Linux.
These appear recusrively for each of the yield surfaces for which the CL has been implemented. 
I have noticed that the warning are only refered to methods with int variables but not to has/getvalue/setvalue methods writen for doubles (which are also implemented in the CL). In addition to this, the warnings appear together with references to damage CL (which is the base class) and the has/getvalue/setvalue methods for vectors and matrices variables. (Has/Setvalue/Getvalue methods for int are not implemented in damage CL and I am not sure if this can be the reason for the warning messages).
It would be really helpful if @loumalouomega or @philbucher can have a look when you have time because at this moment I am quite lost. Thanks.

 I paste here an example of these warnings:
2020-03-24T10:58:11.1424901Z In file included from /__w/Kratos/Kratos/build/Custom/applications/StructuralMechanicsApplication/cotire/KratosStructuralMechanicsCore_CXX_unity.cxx:5:
2020-03-24T10:58:11.1425197Z In file included from /__w/Kratos/Kratos/applications/StructuralMechanicsApplication/structural_mechanics_application.cpp:21:
2020-03-24T10:58:11.1440992Z In file included from /__w/Kratos/Kratos/applications/StructuralMechanicsApplication/structural_mechanics_application.h:148:
2020-03-24T10:58:11.1447205Z /__w/Kratos/Kratos/applications/StructuralMechanicsApplication/custom_advanced_constitutive/generic_small_strain_high_cycle_fatigue_law.h:173:10: warning: 'Kratos::GenericSmallStrainHighCycleFatigueLaw<Kratos::GenericConstitutiveLawIntegratorDamage<Kratos::VonMisesYieldSurface<Kratos::VonMisesPlasticPotential<6> > > >::Has' hides overloaded virtual functions [-Woverloaded-virtual]
2020-03-24T10:58:11.1447444Z     bool Has(const Variable<int>& rThisVariable) override;
2020-03-24T10:58:11.1447587Z          ^
2020-03-24T10:58:11.1559116Z /__w/Kratos/Kratos/applications/StructuralMechanicsApplication/structural_mechanics_application.h:772:141: note: in instantiation of template class 'Kratos::GenericSmallStrainHighCycleFatigueLaw<Kratos::GenericConstitutiveLawIntegratorDamage<Kratos::VonMisesYieldSurface<Kratos::VonMisesPlasticPotential<6> > > >' requested here
2020-03-24T10:58:11.1559409Z     const GenericSmallStrainHighCycleFatigueLaw <GenericConstitutiveLawIntegratorDamage<VonMisesYieldSurface<VonMisesPlasticPotential<6>>>> mSmallStrainHighCycleFatigue3DLawVonMisesVonMises;
2020-03-24T10:58:11.1559628Z                                                                                                                                             ^
2020-03-24T10:58:11.1560683Z /__w/Kratos/Kratos/applications/StructuralMechanicsApplication/custom_advanced_constitutive/generic_small_strain_isotropic_damage.h:214:10: note: hidden overloaded virtual function 'Kratos::GenericSmallStrainIsotropicDamage<Kratos::GenericConstitutiveLawIntegratorDamage<Kratos::VonMisesYieldSurface<Kratos::VonMisesPlasticPotential<6> > > >::Has' declared here: type mismatch at 1st parameter ('const Variable<Kratos::Vector> &' (aka 'const Variable<vector<double> > &') vs 'const Variable<int> &')
2020-03-24T10:58:11.1560978Z     bool Has(const Variable<Vector> &rThisVariable) override;
2020-03-24T10:58:11.1561306Z          ^
2020-03-24T10:58:11.1562384Z /__w/Kratos/Kratos/applications/StructuralMechanicsApplication/custom_advanced_constitutive/generic_small_strain_isotropic_damage.h:221:10: note: hidden overloaded virtual function 'Kratos::GenericSmallStrainIsotropicDamage<Kratos::GenericConstitutiveLawIntegratorDamage<Kratos::VonMisesYieldSurface<Kratos::VonMisesPlasticPotential<6> > > >::Has' declared here: type mismatch at 1st parameter ('const Variable<Kratos::Matrix> &' (aka 'const Variable<matrix<double> > &') vs 'const Variable<int> &')
2020-03-24T10:58:11.1562658Z     bool Has(const Variable<Matrix> &rThisVariable) override;
2020-03-24T10:58:11.1562788Z          ^
2020-03-24T10:58:11.1562950Z In file included from /__w/Kratos/Kratos/build/Custom/applications/StructuralMechanicsApplication/cotire/KratosStructuralMechanicsCore_CXX_unity.cxx:5:

**Comment by loumalouomega** [comment]
> hidden overloaded virtual function

I cannot understand why these warning..., technically the override is correct...

**Review by loumalouomega — APPROVED** [review]

**Comment by philbucher** [comment]
I will take a look, can you please wait with merging?

**Comment by SergioJimenezReyes** [comment]
> I will take a look, can you please wait with merging?

No problem, thanks

**Comment by philbucher** [comment]
closing as fixed in #8214

**Pull request closed without merging**
