### PR TITLE
[Core] Missing sqrt in displacement criteria

### PR DESCRIPTION
**Pull request by loumalouomega**
This was removed by an error, restoring.

@marandra and @ddiezrod noticed. Sorry for the change

### CODE REVIEW

**Review by ddiezrod — APPROVED** [review]
Thanks ;)

**Comment by ddiezrod** [comment]
@loumalouomega I was thinking that some tests could fail now, have you checked it?

**Comment by philbucher** [comment]
Yep this could really affect test results 

Please give us some days to check our stuff

Also this should really go in only after the release

**Comment by loumalouomega** [comment]
All tests work:
image

@philbucher we restored a old behavior, this is a fix, we didn't notice because we don't use to use the displacement criteria (by default)

**Comment by ddiezrod** [comment]
@philbucher This is making some tests from @KratosMultiphysics/altair group to fail and as @loumalouomega  said it recovers its old behaviour so I think it should go in this release...

**Comment by philbucher** [comment]
I known you only restored old behavior, but it can still break tests
No problem if one knows abt it but really frustrating if one does not (this PR was created in the evening and merged the next morning, not sure how many devs are aware of it)
Thats why I think you should have waited for the opinion of @KratosMultiphysics/technical-committee

**Comment by loumalouomega** [comment]
@philbucher the previous and **wrong** behaviour was in general more strict than the correct one. This means that tests created with this criteria should, and indeed, pass

**Comment by philbucher** [comment]
I know it is wrong but again, changing it without other devs knowing abt it is really frustrating

I know that theoretically it should not break tests, but practice is unfortunately different as @ddiezrod himself reports

**Comment by marandra** [comment]
The real problem in the case of the residual_criteria bug some months ago was that the test was changed to pass with the wrong values. That led to really frustrating debugging.

**Comment by loumalouomega** [comment]
> The real problem in the case of the residual_criteria bug some months ago was that the test was changed to pass with the wrong values. That led to really frustrating debugging.

Sorry

**Pull request merged**
