### PR TITLE
Feature memory manager

### PR DESCRIPTION
**Pull request by pooyan-dadvand**
This PR adds `MemoryInfo` which proivdes:
```c++
 static std::size_t GetPeakMemoryUsage()
```
which returns the peak memory used by Kratos+Python and 
```c++
 static std::size_t GetCurrentMemoryUsage() 
```
which returns the memory used by Kratos+Python in bytes at that moment.

Example:
``` python
memory_info=MemoryInfo()
print(memory_info)
```
results in
```
MemoryInfo
Current Memory Usage : 35.43 MB
Peak Memory Usage    : 421.2 MB
```
Note:
 *  The information is taken from OS and may vary in each execution depending on page allocation and other factors. 
 *  The supported platforms are Windows, Linux and OSX. 

@ipouplana would you please check if it compiles in OSX?
@jrubiogonzalez and @pablobecker would you please check if the information it gives is relevant with your measurements in your codes?

@KratosMultiphysics/technical-committee There are 3 new macros defined:

* `KRATOS_COMPILED_IN_LINUX`
* `KRATOS_COMPILED_IN_OSX` 
* `KRATOS_COMPILED_IN_WINDOWS`

Are you agree?

### CODE REVIEW

**Comment by maceligueta** [comment]
No problem from my side.

**Comment by ipouplana** [comment]
This afternoon I will try to compile this branch in macOS.

**Review by roigcarlo — COMMENTED** [review]
Works to me :+1:

**Comment by ipouplana** [comment]
Compiled on macOS High Sierra without errors 👍

**Comment by pooyan-dadvand** [comment]
Thanks @ipouplana, would you please check if it gives you some memory usage which is not zero?

After `from KratosMultiphysics import *` you can just run the example above.

**Comment by ipouplana** [comment]
Hi @pooyan-dadvand, this code:

~~~
from KratosMultiphysics import *
memory_info=MemoryInfo()
print(memory_info)
~~~

gives this output:

~~~
client82-10-192-164:Downloads ignasi$ python3 memory_example.py 
 |  /           |             
 ' /   __| _` | __|  _ \   __|
 . \  |   (   | |   (   |\__ \ 
_|\_\_|  \__,_|\__|\___/ ____/
           Multi-Physics 5.3.0-cdceab6c75
MemoryInfo
Current Memory Usage : 23.2 MB
Peak Memory Usage    : 23.23 MB
~~~

Regards

**Comment by pooyan-dadvand** [comment]
Perfect! Thanks @ipouplana!

**Review by RiccardoRossi — APPROVED** [review]
looks good to me.

**Comment by philbucher** [comment]
@pooyan-dadvand do you still need this branch or can it be deleted?

**Comment by pooyan-dadvand** [comment]
I wanted to continue on it but I will create another one

Thanks for hint.

**Pull request merged**
