### PR TITLE
[MPM] Using core newton raphson strategy

### PR DESCRIPTION
**Pull request by peterjwilson**
Inspired by [Phil](https://github.com/KratosMultiphysics/Kratos/pull/6401#pullrequestreview-357413932), MPM now uses the core newton raphson strategy. 

Let me know if you guys feel any of these points are wrong:
- For an implicit solve, it looks likes all the MPM-specific things are in the mpm_bossak_scheme, not in the strategy.
- The MPM newton raphson looks almost identical to the core one.
- Tests are all fine
- I did another external example dynamic implicit case which turned out to be identical too

### CODE REVIEW

**Review by bodhinandach — CHANGES_REQUESTED** [review]
Let me hold for a while, I tested this last time and it didn't work that simple. But I forgot what was the reason.
@peterjwilson Can you do me a favor really quick: can you run in FullDebug mode the tests? If it does work, can you run a dynamic case example in FullDebug? Any case will be okay. Almost all the unit tests are static, so I just want to know if it works okay in general.

**Comment by tteschemacher** [comment]
If it doesn't work we should better figure out why and fix it accordingly instead of keeping a copy of it in the master

**Comment by philbucher** [comment]
aw man who doesn't love when sth custom is replaced by something from the core :heart_eyes:

**Comment by bodhinandach** [comment]
I recalled what I have done. The last time that I checked, it was working okay, no problem at all with using the one in the core. However, the performance of MPM simulations become significantly slower, around 2 times slower. So I reverted back. 

My hypothesis was as there are more loops on the one in the core, but that doesn't make much sense. That will be helpful if you can investigate further on this.

**Comment by peterjwilson** [comment]
Continued in PR #6807 , closing this.

**Pull request closed without merging**
