### PR TITLE
[Core] Renaming RayCasting tolerance variable

### PR DESCRIPTION
**Pull request by marcnunezc**
Hi! This was suggested by @rubenzorrilla. 

In this PR I rename the variable `ExtraRayEpsilon` that is used to set the tolerance of the apply_ray_casting_process, since it's current name is not clear enough.

### CODE REVIEW

**Comment by pooyan-dadvand** [comment]
@rubenzorrilla the `RelativeTolerance` is used in ApplyRayCastingProcess. Wouldn't be better to use `RayCastingRelativeTolerance` to emphasis that it is relative?

**Comment by rubenzorrilla** [comment]
> @rubenzorrilla the `RelativeTolerance` is used in ApplyRayCastingProcess. Wouldn't be better to use `RayCastingRelativeTolerance` to emphasis that it is relative?

Agree. I'd clearly state that it is a relative tolerance. I like `RayCastingRelativeTolerance`.

**Comment by marcnunezc** [comment]
Ok! I changed the name to `RayCastingRelativeTolerance`

**Review by rubenzorrilla — APPROVED** [review]

**Review by pooyan-dadvand — APPROVED** [review]
:+1:

**Pull request merged**
