### PR TITLE
Core/update compare two files check process

### PR DESCRIPTION
**Pull request by philbucher**
taken from #2417

### CODE REVIEW

**Review by loumalouomega — CHANGES_REQUESTED** [review]
I have some manual calls to this process, can you do a grep and check that the model part is removed there?

**Comment by philbucher** [comment]
@loumalouomega done

**Comment by loumalouomega** [comment]
Can you merge with the master?, I just merged a pr using this, so I assume it will stop working the test_remesh_sphwre.py in the MeshingApplication

**Comment by philbucher** [comment]
done

**Comment by philbucher** [comment]
anything else @loumalouomega ?

**Review by loumalouomega — APPROVED** [review]

**Comment by philbucher** [comment]
thx

**Pull request merged**
