### PR TITLE
[Mapping] deprecate mesh conformity check

### PR DESCRIPTION
**Pull request by philbucher**
**Description**
This PR deprecates `AreMeshesConforming`. I want to refactor the internals of the mapper to reduce the memory footprint, then this check will no longer be possible. In any case this fct doesn't really belong to the mapper and should be separated.

@roigcarlo I think we spoke about an alternative already at the time when you added this fct.

This PR is part of the cleanup of the MappingApp before starting to move parts of it to the core

FYI @KratosMultiphysics/altair

### CODE REVIEW

**Comment by ddiezrod** [comment]
We are currently using this function in @KratosMultiphysics/altair . If we are going to deprecate it then it should be substituted by something else, in my opinion.

**Comment by philbucher** [comment]
I know, thats why I am deprecating it first :)
I already said when it was added that I will remove it again at some point bcs it can no longer work. IIRC we added it as it was a fast and easy hack

@roigcarlo you had a differen suggestion, sth with `NEIGHBOR_NODES` no?

**Comment by philbucher** [comment]
just to add that I wouldn't change this if I could maintain it. :/
But it blocks important developments related to improving the searching, which I guess you will also profit from :)

**Comment by roigcarlo** [comment]
It could be implemented outside the mapper indeed. The main caveat is that we need calculate again a parallel search to calculate the distances, which is expensive and since we already had that data through the mapper interfaces...

But if you are going to remove it I guess we will need to create a separate process...

**Comment by philbucher** [comment]
my plan is to create the search structure only on the fly and don't safe it, as I have to recreate it anyway if I need it.
This way I can safe memory and simplify the implementation

**Comment by pooyan-dadvand** [comment]
I imagine this function could be a utility and reused in different places.

**Comment by philbucher** [comment]
@pooyan-dadvand and I just discussed this and I realized that the current implementation most probably doesn't work when the nodes are the same but the connectivities are different. I.e. in this case it would still say it is conforming

**Comment by pooyan-dadvand** [comment]
Is it possible to move it to a separate utility? In which the name already says that it checks the nodes positions conformity?

**Comment by philbucher** [comment]
not really
This check is never done explicitly. It only checks if there is more than one search iteration
https://github.com/KratosMultiphysics/Kratos/blob/e88045ab437fb451ed1ae8d8c61e33f9b06725ef/applications/MappingApplication/custom_searching/interface_communicator.cpp#L66-L68

I.e. in order to port it to a utility I would need to copy the entire search architecture, which is ~50% of the code in the MappingApp

**Comment by philbucher** [comment]
I thought some more and I think I can support this for a little longer since it apparently is not straightforward to be replaced
Nevertheless it is a hack and IMO this should not be part of the mapper

Hence I propose the following compromise:
Officially this fct is deprecated and it will ONCE issue a deprecation warning, but I will not remove it in the near future

can we agree on this @KratosMultiphysics/altair ?

**Comment by ddiezrod** [comment]
> I thought some more and I think I can support this for a little longer since it apparently is not straightforward to be replaced
> Nevertheless it is a hack and IMO this should not be part of the mapper
> 
> Hence I propose the following compromise:
> Officially this fct is deprecated and it will ONCE issue a deprecation warning, but I will not remove it in the near future
> 
> can we agree on this @KratosMultiphysics/altair ?

I think this is fair enough. I don't love to throw warnings that can confuse the user but I think this is reasonable. The only thing, please do not use a very alarming warning mesage. ;)

**Comment by philbucher** [comment]
@ddiezrod is this warning ok for you?

**Comment by ddiezrod** [comment]
> @ddiezrod is this warning ok for you?

Thats fine for me, yes.

**Review by ddiezrod — APPROVED** [review]

**Pull request merged**
