### PR TITLE
[Core] mpi unittest fixes

### PR DESCRIPTION
**Pull request by philbucher**
**Description**
Now the level and verbosity should be passed correctly

I also took the chance to refactor using the newer and simple `argparse` instead of `getopt`

@sunethwarna @riccardotosi can you please test it with your code if it really works now?

### CODE REVIEW

**Comment by philbucher** [comment]
FYI @roigcarlo `argparse` shows the usage if it fails by itself, which I find pretty cool.
Example:
~~~
usage: run_python_mpi_tests.py [-h] [-c COMMAND] [-l {all,nightly,small,validation}] [-v {0,1,2}]
                               [-n PROCESSES] [-m MPI_COMMAND] [-f MPI_FLAGS] [-p NUM_PROCESSES_FLAG]
run_python_mpi_tests.py: error: unrecognized arguments: -k2
~~~

**Comment by riccardotosi** [comment]
I will try!

**Review by riccardotosi — APPROVED** [review]
In #8075 it worked.

**Comment by philbucher** [comment]
@roigcarlo is this PR ok with you?

I will push some more improvements and corrections soon, e.g. more explanations for the arguments

**Review by sunethwarna — APPROVED** [review]

**Review by roigcarlo — APPROVED** [review]

**Pull request merged**
