### PR TITLE
[Python interface] Typo with contact_structural_mechanics_application

### PR DESCRIPTION
**Pull request by loumalouomega**

### CODE REVIEW

**Review by philbucher — APPROVED** [review]
How could this be unnoticed for so long?

**Comment by loumalouomega** [comment]
No idea

**Comment by jcotela** [comment]
Guys, application_interface is obsolete and unused (that's why you never noticed)

**Comment by loumalouomega** [comment]
Should we remove it then?

**Comment by jcotela** [comment]
@loumalouomega it is on the plan (I think there is an issue for that?). In any case I'd wait a little bit more until all old uses of it are removed, as in the PR removing the benchmarking.

**Comment by loumalouomega** [comment]
Ok I will merge this anyway and we will see in the future

**Pull request merged**
