### PR TITLE
Enhance adjoint test cases

### PR DESCRIPTION
**Pull request by MFusseder**
Within this pull request I changed some material properties and precision requirements in the adjoint sensitivity analysis test cases in order to enhance their numerical robustness.

### CODE REVIEW

**Comment by philbucher** [comment]
:+1: 
two more errors:
~~~
======================================================================
FAIL: test_local_stress_response (test_adjoint_sensitity_analysis_beam_3d2n_structure.TestAdjointSensitivityAnalysisBeamStructure)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/philippb/software/Kratos_prod/applications/StructuralMechanicsApplication/tests/test_adjoint_sensitity_analysis_beam_3d2n_structure.py", line 75, in test_local_stress_response
    self.assertAlmostEqual(sensitivities_to_check[1], reference_values[1], 3)
AssertionError: 38125.18252084602 != 38125.18144970003 within 3 places

======================================================================
FAIL: test_strain_energy_response (test_adjoint_sensitity_analysis_beam_3d2n_structure.TestAdjointSensitivityAnalysisBeamStructure)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/philippb/software/Kratos_prod/applications/StructuralMechanicsApplication/tests/test_adjoint_sensitity_analysis_beam_3d2n_structure.py", line 124, in test_strain_energy_response
    self.assertAlmostEqual(sensitivities_to_check[2], reference_values[2], 4)
AssertionError: -124.00605217810677 != -124.00616062621255 within 4 places

----------------------------------------------------------------------
~~~

**Review by philbucher — APPROVED** [review]
now the tests are running

**Comment by MFusseder** [comment]
Finally, thank God!

**Comment by armingeiser** [comment]
It would be nice if we would not define the number of decimals, but the number of significant digits in the assertions.

**Comment by armingeiser** [comment]
It seems that python unittest does not offer such a comparison...

**Pull request merged**
