### PR TITLE
[Core] Missing python methods for constraints

### PR DESCRIPTION
**Pull request by loumalouomega**
Basically the Get/Set and Has methods

### CODE REVIEW

**Comment by roigcarlo** [comment]
I think part of this PR is conflicting with #3465

**Comment by loumalouomega** [comment]
No, this PR is a cherrypick of #3465, and #3465 is not merging with master and is for after release

**Comment by roigcarlo** [comment]
Hoo I see, ok then! (maybe you can mark that its cherry pick next time :P)

Seems that using unity there are conflicts with the add_mesh_to_python, but apart from that good to me 👍

**Comment by loumalouomega** [comment]
Fixing and compiling with Cotire

**Comment by loumalouomega** [comment]
Fix @roigcarlo

**Comment by loumalouomega** [comment]
@roigcarlo Ping

**Review by roigcarlo — APPROVED** [review]

**Pull request merged**
