### PR TITLE
debugging CI

### PR DESCRIPTION
**Pull request by philbucher**

### CODE REVIEW

**Comment by marcnunezc** [comment]
@roigcarlo this is what I commented to you yesterday

We also tried a few things here #6231

I can see that it worked when compiling only the necessary apps to run the CPFApp but it fails when compiling everything right?

**Comment by roigcarlo** [comment]
Yep, Trying in my local lets see if I can give you some clue :S

**Comment by philbucher** [comment]
sorry guys this is such a pain, I also have no clue what is happening. My best guess is that you have a mem-error somewhere (see https://github.com/KratosMultiphysics/Kratos/pull/6229#issuecomment-574668477)
I tried different things, but it seems not to be deterministic
I would try to run the tests a few times and see if the problem happens, but I think this only makes sense locally

One thing you could do is to get the docker image and try it directly there with the same configuration. But I would first try to run it locally
Also I would try with 1 omp thread

**Comment by roigcarlo** [comment]
Well I am getting a double free corruption in the Compressible Potential flow. Investigating...

**Comment by roigcarlo** [comment]
Oh wait, I think I know which is the problem....

**Comment by roigcarlo** [comment]
Testing in #6268 (I've created another branch because I was unable to undo all the comments quickly)

**Comment by roigcarlo** [comment]
What makes me thing, if this is the problem, maybe we should take a look at the `run_tests.py` script, as it imports the applications carelessly in alphabetic order :S

**Pull request closed without merging**
