### PR TITLE
[Core][Geometries]Fixes #2367

### LINKED ISSUE #2367: [Core][Geometries]Triangle2D3 has only one integration point by default
@KratosMultiphysics/technical-committee 

https://github.com/KratosMultiphysics/Kratos/blob/c4c4fc35f587a5ccfc0d65d77c8b0a5684c3476f/kratos/geometries/triangle_2d_3.h#L2131

In the other hand the Quadrilateral2D4 uses 4 GP by default:

https://github.com/KratosMultiphysics/Kratos/blob/c4c4fc35f587a5ccfc0d65d77c8b0a5684c3476f/kratos/geometries/quadrilateral_2d_4.h#L1115

### PR DESCRIPTION
**Pull request by loumalouomega**
It fixes #2367

### CODE REVIEW

**Comment by loumalouomega** [comment]
Apparently some tests fail

**Comment by roigcarlo** [comment]
No expert on the topic but you probably have to change the reference file that the test is using to compare the output

**Review by pooyan-dadvand — CHANGES_REQUESTED** [review]
You cannot ask for PR (to be accidentally approved) on behavior change of a frequently used feature without having your discussion in issue concluded

**Comment by loumalouomega** [comment]
Understood

**Comment by pooyan-dadvand** [comment]
Sorry to be so direct....

**Comment by loumalouomega** [comment]
Don't worry, I understand, I just did the PR because it was only one line of correction and because I thought that I had found a certain bug

**Pull request closed without merging**
