### PR TITLE
[StructuralMechanicsApplication] Not computing tangent tensor for explicit computation in SPrism

### PR DESCRIPTION
**Pull request by loumalouomega**
This is equivalent to #3993 for SPrism

The Kirchoff approximation is considered to avoid the tangent tensor

### CODE REVIEW

**Comment by loumalouomega** [comment]
Ping

**Comment by loumalouomega** [comment]
Ping @frastellini

**Comment by philbucher** [comment]
I cannot approve as I don't know the details here...

**Comment by loumalouomega** [comment]
> I cannot approve as I don't know the details here...

Yes, the ping is for @frastellini, it does the same basically than the previous PR for solid elements, but for this element. I recommend to do the same for others elements

**Review by frastellini — APPROVED** [review]
This implementation will really help with the performance of explicit scheme.

**Comment by frastellini** [comment]
It would be good to think in a more general implementation that could be also employed by all elements when running under explicit scheme, where tangent matrix is not necessary

**Pull request merged**
