### PR TITLE
[HDF5][Feature] Add ALL_VARIABLES inputs/outputs

### PR DESCRIPTION
**Pull request by sunethwarna**
**Description**
This PR adds the ability to input and output all variables from following containers

`Nodal` historical container:
- `ALL_VARIABLES` input allowed
- `ALL_VARIABLES` output allowed

`Nodal` non-historical container:
- `ALL_VARIABLES` input allowed

`Condition` datal container:
- `ALL_VARIABLES` input allowed

`Element` datal container:
- `ALL_VARIABLES` input allowed

This **does not break** the existing use cases as well as the interface.

**Changelog**
- Adds support to input/output `ALL_VARIABLES` from a data container.

### CODE REVIEW

**Review by philbucher — COMMENTED** [review]
where does the `mComponentNames` come from?

**Comment by sunethwarna** [comment]
> where does the mComponentNames come from?

They are given via json settings.

**Comment by philbucher** [comment]
Hm I still don't fully understand
for Input it comes from the h5 file (I assume)
But where does it come from for the output?

**Comment by sunethwarna** [comment]
It is only there for `NodalHistorical` container where the list of variables are taken from the `ModelPart`
https://github.com/KratosMultiphysics/Kratos/blob/613203e7c328c48f3613cd3116df05c3b536aa93/applications/HDF5Application/custom_io/hdf5_nodal_solution_step_data_io.cpp#L106-L123

**Comment by philbucher** [comment]
ok now I understand
how about for the Input: `ALL_VARIABLES_FROM_FILE`
and for the output: `ALL_VARIABLES_FROM_VARIABLES_LIST`?

**Comment by sunethwarna** [comment]
@philbucher Done :)

**Review by philbucher — APPROVED** [review]

**Pull request merged**
