### PR TITLE
DEM Bugfix ComputeWear

### PR DESCRIPTION
**Pull request by salvalatorre**

### CODE REVIEW

**Comment by salvalatorre** [comment]
One moment, checking something...

**Review by ipouplana — DISMISSED** [review]

**Review by maceligueta — CHANGES_REQUESTED** [review]
I think the division over the area is wrong

**Comment by maceligueta** [comment]
Shouldn't we divide the wear over the element area? Now, you are dividing each projection to each node over an area which is affected by neighbour elements, if I understood right.

**Comment by salvalatorre** [comment]
Changed the uniformization by area criterion: from the tributary area of each nodes to the element area

**Review by maceligueta — APPROVED** [review]

**Pull request merged**
