### PR TITLE
[Core] Point output process open/close file every time we write

### PR DESCRIPTION
**Pull request by ddiezrod**
This fixes the problems described in https://github.com/KratosMultiphysics/Kratos/issues/11208 , opening and closing the file after every print.

### CODE REVIEW

**Comment by matekelemen** [comment]
This results in a behaviour change at process construction time if a file already exists. I'd add an extra flag to the input parameters that defines what to do in such cases, and have a default value that ensures the old behaviour. For example:
```json
{
     ...
    "overwrite" : true // overwrite existing files at process construction if true, throw an exception otherwise
}
```

**Comment by philbucher** [comment]
I think it is ok as is if the tests pass

Existing files is ok, used for restarts

**Comment by mpentek** [comment]
What is the performance change, when you have 1000 files or similar order? I know it is not efficient to have some many ASCII files open, but is opening and closing at each time step better?

**Comment by ddiezrod** [comment]
> What is the performance change, when you have 1000 files or similar order? I know it is not efficient to have some many ASCII files open, but is opening and closing at each time step better?

I'll run a test tomorrow and give you some numbers

**Comment by ddiezrod** [comment]
@matekelemen That is true, although the entity search is done only once at the very beginning, so I assume that the difference wont be too big (I might be wrong)

**Comment by mpentek** [comment]
> Hm that is more than I thought I don't oppose the changes, but perhaps someone could tests this also on the cluster?
> 
> @mpentek could you do this?
> 
> @ddiezrod can you please post your script?

I can first test on a cluster in 1-2 weeks. We have had cases with 2000-3000 files, although rarely. Also, this there is the option of piping point output to H5.

@ddiezrod is that an option?

**Review by philbucher — APPROVED** [review]
I think this is ok as is, since it solves relevant issues.

IMO if this becomes a bottleneck, then whatever it is used for should probably be replaced by sth more appropriate

@mpentek please block if you dont agree

@ddiezrod please wait until Monday with the merge to see if others have concerns too

**Comment by mpentek** [comment]
I do agree with @philbucher, that such an output is anyway a bottleneck. So one thing is to have the correct syntax for the ascii-based point out, other is to see if an h5-based one meanwhile works and is the proper way for multiple points.

@ddiezrod is this PR urgent?
@matekelemen we had the discussion on piping to h5, is that in a state that we (@ddiezrod, @mtnzguillermo) can test?

As some of our campaigns use the point output a lot, on clusters, I will block this change before we have a working and tested solution.

**Review by mpentek — CHANGES_REQUESTED** [review]
@ddiezrod we need a test on a cluster, with a real model part and many output points, including restart.

**Comment by ddiezrod** [comment]
fine to me @mpentek , we need to fix this but it is not urgent

**Comment by ddiezrod** [comment]
@mpentek Were you able to test this? its becoming more urgent in our side...

**Comment by mpentek** [comment]
> @mpentek Were you able to test this? its becoming more urgent in our side...

Sorry, did not happen and most probably I will cause delay, if you depend on my input. I strongly urge a change like this to be tested on a cluster, with MPI, a large model, many output files and restart.

If you consider to proceed without doing so, I will not block, but I am not in favor of doing so.

**Comment by ddiezrod** [comment]
Ok, I'll wait and add some fix in our private repo.

**Pull request closed without merging**
