### PR TITLE
[ContactStructuralMechanicsApplication] Custom Predict() for contact

### PR DESCRIPTION
**Pull request by loumalouomega**
Current approaches doesn't work, this one does (very simple indeed)

### CODE REVIEW

**Comment by loumalouomega** [comment]
Ping @KratosMultiphysics/structural-mechanics

**Comment by loumalouomega** [comment]
Anyone?

**Review by philbucher — APPROVED** [review]
seems ok :)

**Comment by loumalouomega** [comment]
Thanks

**Pull request merged**
