### PR TITLE
Adding missing files

### PR DESCRIPTION
**Pull request by roigcarlo**
Tests are working for me both with the runner and from the script. In serial at least.
Dosn't seems to be really nothing wrong with the tests perse but it had some other problems.

I am going to check the MPI ones now.

### CODE REVIEW

**Comment by philbucher** [comment]
is there a problem currently?

**Comment by roigcarlo** [comment]
Yes, test were not being installed if one sets a custom install path

**Review by philbucher — APPROVED** [review]
Thanks

Can this somehow be made global such that it does not have to be included in each CMakeLists?

**Comment by philbucher** [comment]
ping @roigcarlo is this still relevant?

**Comment by roigcarlo** [comment]
Yes it is! why didn't I merge that OO

**Comment by roigcarlo** [comment]
Thx btw!!

**Pull request merged**
