### PR TITLE
[StructuralMechanics] formatting Klaus elements

### PR DESCRIPTION
**Pull request by philbucher**
Just applying better formatting and removing the `this->` which are not needed
This is done before we start refactoring some stuff to not have cosmetic changes all over the place

Note that I will not do more changes in this PR, this PR is purely cosmetic, any other changes will be done in a future PR

tests are working

### CODE REVIEW

**Comment by loumalouomega** [comment]
> Just applying better formatting and removing the `this->` which are not needed
> This is done before we start refactoring some stuff to not have cosmetic changes all over the place
> 
> Note that I will not do more changes in this PR, this PR is purely cosmetic, any other changes will be done in a future PR
> 
> tests are working

Thanks, I didn't like those this->

**Comment by loumalouomega** [comment]
I would add separator between methods on the .cpp files

**Comment by philbucher** [comment]
I can, but I would prefer to do any manual formatting in a different PR

**Comment by philbucher** [comment]
closing, since I messed sth up

**Pull request closed without merging**
