### PR TITLE
[Core][MPI] Adding `SpecializedSpatialSearchMPI` class, which provides MPI interface to `SpecializedSpatialSearch`

### PR DESCRIPTION
**Pull request by loumalouomega**
**📝 Description**

Following the implementation detailed in https://github.com/KratosMultiphysics/Kratos/pull/11205, this Pull Request introduces `SpecializedSpatialSearchMPI`. This new feature operates similarly to `SpecializedSpatialSearch`, but with added compatibility for MPI. Please note that this feature can only be used in conjunction with the container from PR #11205.

`SpecializedSpatialSearchMPI` functions by establishing local searches using a `SpecializedSpatialSearch` within each partition. Leveraging the containers defined in PR #11205, the solution is then synchronized across all partitions. This approach ensures efficient and consistent data sharing in a distributed computing environment.

Similar to https://github.com/KratosMultiphysics/Kratos/pull/11224, but for `SpecializedSpatialSearch`. In fact there are common changes and probably some conflict will appear once one of them is merged.

**TODO**: Implement asynchronous version (I will add it to this PR, but I open the PR now, so I can easily track myself)

**🆕 Changelog**

- Adding `SpecializedSpatialSearchMPI` via `kratos/mpi/spatial_containers/specialized_spatial_search_mpi.cpp`
- Added factory `SpecializedSpatialSearchMPIFactory` via `kratos/mpi/spatial_containers/specialized_spatial_search_mpi_factory.h`
- Expose to python in `kratos/mpi/python/add_mpi_search_strategies_to_python.cpp`
- Update python serial test to support MPI test
- Changes from https://github.com/KratosMultiphysics/Kratos/pull/11303
- Changes from https://github.com/KratosMultiphysics/Kratos/pull/11247
- Changes from https://github.com/KratosMultiphysics/Kratos/pull/11243
- Changes from https://github.com/KratosMultiphysics/Kratos/pull/11205
- Changes from https://github.com/KratosMultiphysics/Kratos/pull/11244

### CODE REVIEW

**Comment by loumalouomega** [comment]
Ready @pooyan-dadvand

**Comment by loumalouomega** [comment]
@roigcarlo why FullDebug GCC Ci is not even running?

**Comment by roigcarlo** [comment]
It runs. but fulldebug is the longest queue, if there are many PR running it could be delayed quite a lot...

**Comment by loumalouomega** [comment]
Closing as included in https://github.com/KratosMultiphysics/Kratos/pull/11719

**Pull request closed without merging**
