### PR TITLE
Fixing properties

### PR DESCRIPTION
**Pull request by miguelmaso**
#2333

### CODE REVIEW

**Comment by miguelmaso** [comment]
For some reason, the python tests were passing.
Those changes could affect to some applications
imagen

**Review by pooyan-dadvand — DISMISSED** [review]
Thanks for the fix #2333 

👍

**Comment by miguelmaso** [comment]
@roigcarlo can you take a look?
Before the last commit, `test_model_part_io.py` was failing

**Review by roigcarlo — APPROVED** [review]
It works in my machine. Seems odd it was not failing on travis. Maybe it was not in the small suit. Anyway everything seems good 👍

**Comment by philbucher** [comment]
@miguelmaso this breaks `AddProperties`?
Should we change it to `GetProperties`?

**Comment by miguelmaso** [comment]
@philbucher this breaks `AddProperties`
We shouldn't change it to `GetProperties`. Now both methods are consistent
The previous implementation of `AddProperties`was loking for a property with Id=MeshIndex

https://github.com/KratosMultiphysics/Kratos/blob/fa29cca45df76fb7a1976a8e044eb27215662e65/kratos/includes/model_part.h#L617-L619

https://github.com/KratosMultiphysics/Kratos/blob/cacbcf9a0e0f39c59ac432a23191d010ef8f887b/kratos/sources/model_part.cpp#L547-L554

**Comment by philbucher** [comment]
So if I understand correctly I have to check if AddProperties still adds the correct properties?

**Comment by miguelmaso** [comment]
You can check it
Technically, `AddProperties` is still adding the same property. The change is on the check performed before adding the property.
`AddProperties` was failing when a property with Id=0 was already present in the model part

**Pull request merged**
