### PR TITLE
[Trilinos] python module

### PR DESCRIPTION
**Pull request by philbucher**
this PR updates the TrilinosApp to become a python-module

I also updated the usages of the trilinos-linear-solver-factory, please take a look

Note that #5243 should be merged first otherwise some imports will break

### CODE REVIEW

**Comment by philbucher** [comment]
once this is merged I will proceed with StructuralMechanics

After that pretty much all apps that I am involved are updated

**Comment by philbucher** [comment]
Can someone please take a look?
I can only port StructuralMechanics after that, otherwise I will have many conflicts

**Review by jcotela — APPROVED** [review]
:+1:

**Comment by philbucher** [comment]
thx

**Pull request merged**
