### PR TITLE
[Pfem] migrating materials from mdpa to json

### PR DESCRIPTION
**Pull request by MZecchetto**
@KratosMultiphysics/pfem,
this PR moves the material data from the *.mdpa file to a new, dedicated *.json file (examples in pfem and sdem tests).
The next step would be add variable-to-variable dependencies (e.g. `DENSITY-TEMPERATURE`).
**This breaks the current GiD interface.** 
To be considered as a proposal.
Waiting for your feedback.

Max

### CODE REVIEW

**Review by ipouplana — COMMENTED** [review]
I totally agree with this change. Although it will break the current interface, it will be very useful in the future to make the coupling of pfem with other apps easier. 
I guess this would require updating the GUI to write the materials.json, and updating all the pfem examples' and tests'

**Comment by maceligueta** [comment]
Nice! Maybe @jginternational  should be aware of this. I do not recommend merging this PR until a PR for the GUI is ready to be merged as well. As @ipouplana  was saying, the examples and the tests should be adapted to the new style, too.

**Comment by jginternational** [comment]
It should be easy to implement in the GUI

**Comment by AFranci** [comment]
Hi @jginternational 
How are going these developments? We would need them in order to go ahead with other improvements.

Thank you!

**Comment by MZecchetto** [comment]
@GuillermoCasas , @joaquinirazabal I updated also the SDEM-PFEM test and the SDEM-PFEM example. Test ran OK.

**Review by AFranci — DISMISSED** [review]

**Review by AFranci — APPROVED** [review]

**Pull request merged**
