### PR TITLE
Adding the GeneralizedInversed and it test

### PR DESCRIPTION
**Pull request by loumalouomega**

### CODE REVIEW

**Comment by loumalouomega** [comment]
@pooyan-dadvand I change the seed to a fix one, now is supposed to give always the same value. Regarding #169

**Review by pooyan-dadvand — CHANGES_REQUESTED** [review]
I would not put random numbers in a unit test because it may give false failing and even in a correct failing is very difficult to reproduce the error. (I understand its use in another cases like stress tests)

Is there any special reason to use random numbers?

**Comment by loumalouomega** [comment]
@RiccardoRossi told me to use a "bizarre" matrix, and I decided to use the rand function

**Comment by pooyan-dadvand** [comment]
In this case I would put some knowingly "difficult" matrix instead of random.

**Comment by loumalouomega** [comment]
Suggestions?, do I sue the magic matrix from Matlab?

**Comment by pooyan-dadvand** [comment]
I would use a real case from any formulation you like. Even if it is not bad condition, at least it represents the normal use.

**Comment by loumalouomega** [comment]
I will consider a preciously generated random matrix, non symmetric for the aim of completeness, and check previously that it has inverse

**Comment by loumalouomega** [comment]
imagen

**Comment by loumalouomega** [comment]
Solved

**Comment by loumalouomega** [comment]
@pooyan-dadvand The tests are modified at #169

**Review by pooyan-dadvand — APPROVED** [review]

**Comment by pooyan-dadvand** [comment]
Now test work fine in windows! Thanks

**Pull request merged**
