### PR TITLE
[CI] attempting cancel redundant builds

### PR DESCRIPTION
**Pull request by philbucher**
unfortunately github does not support this yet, but someone made an action for this :)

### CODE REVIEW

**Comment by philbucher** [comment]
seems to work

should we give this a go and test in in practice?

**Comment by roigcarlo** [comment]
mm so is this like the autocancel?

**Comment by philbucher** [comment]
yes exactly
source: https://github.com/rokroskar/workflow-run-cleanup-action

"This action cleans up previously running instances of a workflow on the same branch. This accomplishes the task of automatically cancelling CI runs on pushes to the same branch, which is a common feature in most CI systems but currently not possible with GitHub actions."

**Review by roigcarlo — APPROVED** [review]
:+1: Perfect then. It seems to work!

**Comment by philbucher** [comment]
yep I watched it a bit seems to be correctly working :)

**Pull request merged**
