### PR TITLE
Correcting the tetrahedron volume

### PR DESCRIPTION
**Pull request by loumalouomega**

### CODE REVIEW

**Comment by loumalouomega** [comment]
@pooyan-dadvand Regarding #121, I used Felippa formulation, it is necessary to update the geometry utilities (I just changed the volume, but the function CalculateGeometryData is still using the olf formula)

**Comment by roigcarlo** [comment]
@loumalouomega At the end it seems that the tetrahedra had indeed negative volume, so it was ok as it was.

**Comment by loumalouomega** [comment]
@roigcarlo Then this should be removed?

**Comment by roigcarlo** [comment]
I think so. @pooyan-dadvand ?

**Comment by pooyan-dadvand** [comment]
We should leave the volume calculation as it was.

**Comment by loumalouomega** [comment]
OK

**Pull request closed without merging**
