### PR TITLE
attempt to solve #2048 and #1929

### PR DESCRIPTION
**Pull request by RiccardoRossi**
title says it all

### CODE REVIEW

**Comment by armingeiser** [comment]
I am able to compile it with this setting.
I get a warning:
```LINK : /LTCG wurde angegeben, es ist jedoch keine Codegenerierung erforderlich. Entfernen Sie /LTCG aus der Linkbefehlszeile, um die Linkerleistung zu erhöhen.```
which translates to something like ```LINK : /LTCG was defined, but no code generation is necessary, remove /LTCG to improve linking performance```

Still the memory consumption is very high, but at least it fits in my 16GB now.

**Comment by maceligueta** [comment]
@f-zarate  confirms that he managed to compile Kratos with this change.

**Review by maceligueta — DISMISSED** [review]

**Comment by RiccardoRossi** [comment]
@armingeiser could u try to directly remove the /LTCG in that file? if it works push the change in the PR...

**Comment by armingeiser** [comment]
I get a cmake error if i remove the flag, but switching it off works.

**Comment by RiccardoRossi** [comment]
@roigcarlo i let you review this. If you accept please merge without waiting for me

**Review by roigcarlo — APPROVED** [review]
Works for me too

**Comment by roigcarlo** [comment]
I'll merge this as is flagged for 6.0 and it has passed the tests

**Pull request merged**
