### PR TITLE
ruben's review

### PR DESCRIPTION
**Pull request by pablobecker**
**📝 Description**
Changes to generic_find_elements_neighbours_process based on the review by Ruben https://github.com/KratosMultiphysics/Kratos/pull/9894/

**🆕 Changelog**
-Changed several variable to auto
- variable name styling
- other minor changes

### CODE REVIEW

**Review by rubenzorrilla — DISMISSED** [review]
Very good. I think this addresses all the comments. Thanks for doing it so quickly.

**Comment by pablobecker** [comment]
when charly suggested a change to get the pointers, i forgot to do the same change in the test. I guess that was the reason why nightly was failing

**Comment by pablobecker** [comment]
all tests passed. can you approve again?

**Review by rubenzorrilla — APPROVED** [review]
Sure. Thanks  @pablobecker !

**Pull request merged**
