### PR TITLE
Sdem/proper python imports

### PR DESCRIPTION
**Pull request by GuillermoCasas**

### CODE REVIEW

**Comment by GuillermoCasas** [comment]
This PR addresses #4540

**Comment by maceligueta** [comment]
I understand that this PR does not bring any behaviour change, right? Just changes the way modules are imported. So if tests pass, no problem with approving.

**Comment by GuillermoCasas** [comment]
> I understand that this PR does not bring any behaviour change, right? Just changes the way modules are imported. So if tests pass, no problem with approving.

Exactly.

**Review by ipouplana — APPROVED** [review]
Good!

**Pull request merged**
