### PR TITLE
[StructuralMechApp] Adding include to make it to compile

### PR DESCRIPTION
**Pull request by AlejandroCornejo**
That's it

### CODE REVIEW

**Comment by AlejandroCornejo** [comment]
solving https://github.com/KratosMultiphysics/Kratos/issues/10757

**Review by loumalouomega — DISMISSED** [review]

**Comment by loumalouomega** [comment]
It would be less "time compilation consuming" if the include is added in the cpp that require it instead in the base class header

**Comment by AlejandroCornejo** [comment]
> It would be less "time compilation consuming" if the include is added in the cpp that require it instead in the base class header

ok, I'll change it in a few hours

**Review by loumalouomega — APPROVED** [review]

**Review by atfard — APPROVED** [review]

**Comment by ipouplana** [comment]
Thank you @AlejandroCornejo !

**Pull request merged**
