### PR TITLE
[FastPR][Fluid] Update Sod tube test values

### LINKED ISSUE #10267: Mark Sod Shock Tests as Expected Failures
## Issue
The [sod shock tube](https://github.com/KratosMultiphysics/Kratos/blob/bcc76e7de708a8a468c2233e236a7d541dd3127d/applications/FluidDynamicsApplication/tests/sod_shock_tube_test.py) tests fail in master but are not run in the CI, which sends poor unaware devs who run tests locally (eg: me) on pointless bughunts. The tests are added to the validation suite (not run in the CI) but not the nightly suite (run in the CI) and are **not marked expected failures** even though they fail and the people working on it know about that (#10209).

## Request
Mark the failing tests as expected failures.

### PR DESCRIPTION
**Pull request by rubenzorrilla**
**📝 Description**
The Sod tube tests with shock capturing return a slightly different value to that of the test. Most probably some of the latest improvements caused these.

Closes #10267

### CODE REVIEW

**Review by loumalouomega — APPROVED** [review]
Thanks, this was failing in some of my machines, but I didn't want to complain

**Comment by rubenzorrilla** [comment]
Seems that `MultiLevelMonteCarloApplication` is failing... Very rare as changes in here have nothing to do with this one... Any hint @riccardotosi ?

**Comment by riccardotosi** [comment]
It seems fixed ;)

**Comment by rubenzorrilla** [comment]
> It seems fixed ;)

Well, I just re-ran the failing CI. Lets see if it happens again. Thanks in any case :wink:

**Pull request merged**
