### PR TITLE
[StructuralMechanicsApplication] Adds some additional small and nightly tests

### PR DESCRIPTION
**Pull request by loumalouomega**
I will upload soon a validation test.

Reminder to myself, @loumalouomega add the check of the friction angle in the MC

### CODE REVIEW

**Review by AlejandroCornejo — DISMISSED** [review]

**Comment by loumalouomega** [comment]
@AlejandroCornejo I added the tensile test as validation

**Review by AlejandroCornejo — APPROVED** [review]

**Comment by philbucher** [comment]
@loumalouomega the test "TensileTestStructuralTest" takes forever, I had to kill it on my machine
Can you please reduce the time? I would say it should not take more than 2-3 seconds
also check it in FullDebug please, it should not take ages

**Comment by loumalouomega** [comment]
It is a validation test, it is not supposed to be run every time, just for
validation. The validation tests of the FSI take even longer

**Comment by philbucher** [comment]
so far the tests in StuctMech took a bit less than one minute
Now each time I want to run the tests I will have to comment this one ... :/
This beats the purpose

If you insist leaving it there then we have to remove the validation-suite from the AllSuite, which I also don't like, bcs then it will not be run

**Comment by loumalouomega** [comment]
As I say, validation are long tests, you should not run only the nightly or small:

~~~sh
python3 test_StructuralMechanicsApplication.py -l nightly
~~~

**Comment by philbucher** [comment]
sure, but this test takes ~6min!
Anyway, I opened a PR for this

**Pull request merged**
