### PR TITLE
[Core][Model] Info => Warning when using flat map

### PR DESCRIPTION
**Pull request by philbucher**
name says it all

I suggest to also add a date when the flat map will be removed

### CODE REVIEW

**Review by loumalouomega — DISMISSED** [review]
OK

**Review by loumalouomega — DISMISSED** [review]
Re-OK

**Comment by pooyan-dadvand** [comment]
@KratosMultiphysics/technical-committee agrees on warning and with end of November as the removal date

**Comment by philbucher** [comment]
I added the date, can someone approve pls?

**Review by rubenzorrilla — APPROVED** [review]

**Comment by philbucher** [comment]
Thx

**Pull request merged**
