### PR TITLE
[Core] BrepCurve and corresponding ReadIn

### PR DESCRIPTION
**Pull request by tteschemacher**
**Description**
Adds the BrepCurve which relies on a NurbsCurve.

Currently, a tool to fulfill the setup of the other geometries. However, yet, the trimming is not attached as too many PRs are pending which would involve changes and conflicts on this. Once needed this can be easily added.

### CODE REVIEW

**Review by rickyaristio — DISMISSED** [review]

**Comment by tteschemacher** [comment]
officially I have to wait for any @KratosMultiphysics/technical-committee answers. Are there any concerns, @philbucher @pooyan-dadvand ?

**Review by philbucher — APPROVED** [review]
:+1:

**Comment by tteschemacher** [comment]
Das ist das größte für mich 💯

**Comment by tteschemacher** [comment]
thanks for the review

**Pull request merged**
