### PR TITLE
Core/fix nightly build errors

### LINKED ISSUE #1249: Nightly test not running
Nightly builds are down since 21/12/2017. Working on it, I created the issue to track.

### PR DESCRIPTION
**Pull request by roigcarlo**
Fixes #1249 
Problem was a combination of several problems:
- Swimming DEM had an error while checking if the old incompressible fluid application was compiled. 
- Solid Mechanics had a new dependency
- Both combined were making the script finish before the unasisted updates freed the so, and the mails were not able to be send. It should be fixed.

### CODE REVIEW

**Review by pooyan-dadvand — COMMENTED** [review]
@roigcarlo have you asked @KratosMultiphysics/dem team if they really need the incompressible or not?

**Comment by maceligueta** [comment]
I've seen that the Incompressible is imported from many scripts in the Swimming Dem App. Maybe @GuillermoCasas will take a look at it.

**Comment by roigcarlo** [comment]
As far as CMake concerns SwimmingDEM does not use the incompressible app, so it should not be there in my opinion.

For the record, the dependencies are:
- KratosDEMApplication 
- KratosFluidDynamicsApplication

If the script needs both applications that's another story

**Comment by maceligueta** [comment]
I put the check in CMake because I had some issues with outdated versions of the Incompressible App. If you have the Incompressible App OFF, but it was compiled long ago, the examples run but can yield strange errors...

**Comment by roigcarlo** [comment]
For me its ok if you want to leave it, but then we have to compile the incompressible fluid in the nightlies or disable the swimming dem. 
You are the users of dem afterall so, you tell me :D

**Comment by maceligueta** [comment]
Let's remove the check, then. I will create a PR.

**Comment by roigcarlo** [comment]
:+1: Then please someone approve it before 20:00 so it can start compiling again

**Comment by maceligueta** [comment]
PR #1255

**Comment by GuillermoCasas** [comment]
Let me look into this. I will try to remove the imports everywhere if I can

**Comment by roigcarlo** [comment]
Solved conflicts with #1255

**Comment by roigcarlo** [comment]
Ping. someone can approve pls?

**Review by maceligueta — APPROVED** [review]

**Pull request merged**
