### PR TITLE
correcting trilinos tests

### PR DESCRIPTION
**Pull request by RiccardoRossi**
I will polish the implementation according to #3073 in another PR once model_part clear makes it to the master, nevertheless this is a hotfix to get the trilinos tests to run correctly

@philbucher i am naming you here just to tell that this is solved

### CODE REVIEW

**Review by roigcarlo — APPROVED** [review]

**Review by philbucher — APPROVED** [review]
test are running for me now, thanks for fixing @RiccardoRossi !

FYI there are some more AMGCL-warnings here:
`AMGCL: Unknown parameter class`

**Comment by roigcarlo** [comment]
Can we marge? I really really need this :D

**Comment by philbucher** [comment]
go ahead from my side :)

**Comment by RiccardoRossi** [comment]
@philbucher yes, concerning AMGCL i fixed the openmp version but not the mpi version of amgcl.

I'll take a look to it when i can

**Comment by philbucher** [comment]
prefect!

**Pull request merged**
