### PR TITLE
[MPM] make axisymmetry volume and mass consistent

### PR DESCRIPTION
**Pull request by peterjwilson**
Hi @KratosMultiphysics/mpm this is a quick fix of the particle generator. For the axisymmetric case, it used to only correct the 'disk' mass, but leave the volume as non-axisymmetric (but this didn't fail in the element because later the volume was determined from the mass). This fix makes the mass and volume consistent with each other at particle generation.

### CODE REVIEW

**Review by bodhinandach — APPROVED** [review]

**Comment by tteschemacher** [comment]
nice. thanks for pointing it out

**Review by tteschemacher — APPROVED** [review]

**Comment by peterjwilson** [comment]
Hi @philbucher , it looks like ContactStructuralMechanics is failing in FullDebug Clang

********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang: note: diagnostic msg: /tmp/KratosContactStructuralMechanicsCore_CXX_unity-b5429d.cpp
clang: note: diagnostic msg: /tmp/KratosContactStructuralMechanicsCore_CXX_unity-b5429d.sh
clang: note: diagnostic msg: 

********************
make[3]: *** [applications/ContactStructuralMechanicsApplication/CMakeFiles/KratosContactStructuralMechanicsCore_unity.dir/build.make:80: applications/ContactStructuralMechanicsApplication/CMakeFiles/KratosContactStructuralMechanicsCore_unity.dir/cotire/KratosContactStructuralMechanicsCore_CXX_unity.cxx.o] Error 254

**Comment by philbucher** [comment]
hm :/
compilation issues in ConstactStructuralMechanics are not new
@loumalouomega how about you exclude some files the cotire build to reduce the memory consumption during compilation?

**Comment by philbucher** [comment]
actually this problems crashes all CI-runs atm

**Pull request merged**
