### PR TITLE
Cps/add minor changes

### PR DESCRIPTION
**Pull request by inigolcanalejo**
Here there is just some clean up and updating of the python interface

### CODE REVIEW

**Comment by marcnunezc** [comment]
I'm fine with the changes! However:

Now that you are doing some clean up in the python interface, shall we remove the "itertools.chain" call in order to only use built-in python functions (as pointed out by @philbucher in another PR)? 

[In the adjoint branch](https://github.com/KratosMultiphysics/Kratos/blob/bf8ec4cd9d7019d4747b2c68a65acc4cdf411ae6/applications/CompressiblePotentialFlowApplication/python_scripts/compute_lift_process.py#L45), I split the loop into two loops.

**Comment by inigolcanalejo** [comment]
> I'm fine with the changes! However:
> 
> Now that you are doing some clean up in the python interface, shall we remove the "itertools.chain" call in order to only use built-in python functions (as pointed out by @philbucher in another PR)?
> 
> [In the adjoint branch](https://github.com/KratosMultiphysics/Kratos/blob/bf8ec4cd9d7019d4747b2c68a65acc4cdf411ae6/applications/CompressiblePotentialFlowApplication/python_scripts/compute_lift_process.py#L45), I split the loop into two loops.

Good point, I think I am going to leave it like this for the moment. The idea is anyway to have just one modelpart for the body (airfoil/wing/aircraft) in the end when we have 2 and 3D working in incompressible and compressible with sensitivities. The reason to separate now is just to make life easier while developing (and debugging :-)). Long story shore: I will remove itertools in the end if that is ok.

**Review by marcnunezc — APPROVED** [review]
> Good point, I think I am going to leave it like this for the moment. The idea is anyway to have just one modelpart for the body (airfoil/wing/aircraft) in the end when we have 2 and 3D working in incompressible and compressible with sensitivities. The reason to separate now is just to make life easier while developing (and debugging :-)). Long story shore: I will remove itertools in the end if that is ok.

Ok, I see!

**Review by philbucher — APPROVED** [review]
Very nice, this is the latest standard of python in Kratos :+1: 

Note: Now you ALWAYS have to import the python-scripts with the full name, i.e. `KratosMultiphysics.CompressibleApp.script_name`

@marcnunezc regarding the itertools, it is better to make many small PRs, this is much easier to review than huge ones that change many things

**Pull request merged**
