### PR TITLE
[Core] Bugfix StructuredMeshGenerator

### PR DESCRIPTION
**Pull request by philbucher**
Hi @pooyan-dadvand 
there is a small bug in the Process, one cannot turn off the creation of a skin part because the check was missing in an if statement
Therfore I changed 
`(i == 0) || (i == mNumberOfDivisions) || (j == 0) || (j == mNumberOfDivisions)`
to 
`mCreateSkinSubModelPart && ( (i == 0) || (i == mNumberOfDivisions) || (j == 0) || (j == mNumberOfDivisions) )`

I also adapted one test to disable the creation of a skin part

### CODE REVIEW

**Comment by RiccardoRossi** [comment]
i suggest as reviewr @jcotela who i think is the author of this one

**Comment by jcotela** [comment]
@RiccardoRossi I did an older python version of the thing, the C++ implementation 100% Pooyan.

**Comment by jcotela** [comment]
Anyways, the changes look OK to me, but I'd prefer to give @pooyan-dadvand time to review.

**Comment by philbucher** [comment]
ping @pooyan-dadvand

**Review by pooyan-dadvand — APPROVED** [review]
👍

**Comment by philbucher** [comment]
thanks

**Pull request merged**
