### PR TITLE
Core bugfix. GetModelPart was crashing with an empty name of ModelPart ("")

### PR DESCRIPTION
**Pull request by maceligueta**
The crash was at this line:
auto search = mroot_map.find(subparts_list[0]);
A verification has been introduced at the beginning of the function.

### CODE REVIEW

**Review by RiccardoRossi — DISMISSED** [review]

**Comment by pooyan-dadvand** [comment]
I agree with the PR but I think it would be better to do the same in modelpart constructor avoiding the creation of the modelpart with empty name.

**Comment by RiccardoRossi** [comment]
I agree with Pooyan. However  i think that for the specific case at hand this is not happening (i mean, in the test by @maceligueta the empty named modelpart is not created

**Comment by maceligueta** [comment]
Exactly, it's a call to a SubModelPart. Even if the mdpa is correct, some line might call GetModePart("") due to an error in the json file. The problem is that right now Kratos is crashing with no further explanation, rather than telling the user the reason. That's why I introduced this fix.

**Comment by maceligueta** [comment]
I just pushed a verification of not-empty name when creating a ModelPart

**Review by RiccardoRossi — APPROVED** [review]

**Pull request merged**
