### PR TITLE
Hotfix/#6165

### PR DESCRIPTION
**Pull request by roigcarlo**
That one should replace #6171 When #6165 is merged to the core.

### CODE REVIEW

**Review by RiccardoRossi — COMMENTED** [review]
from the parallelism point of view, this fix looks correct to me. not sure about the overall speed. opinions?

**Review by loumalouomega — APPROVED** [review]

**Comment by rubenzorrilla** [comment]
@roigcarlo finally, what should we do with this?

**Comment by roigcarlo** [comment]
If the parent is merged we can merge it. The only bloquer was not being in the master.

**Comment by roigcarlo** [comment]
If so please approve, as the Merge to releases need 2 checks

**Review by rubenzorrilla — APPROVED** [review]

**Pull request merged**
