### PR TITLE
update in ContactMechanicsApp

### PR DESCRIPTION
**Pull request by lluis-mv**
some corrections in ContactMechanics (Elasto-plastic point contact conditions)

Accidently, there is a new element (that will be corrected in a new PR)

In CompoundBoundingBox I modified a few lines in the CreateBoundingBoxMesh but I aut-indented with a different format than yours and now it looks like if I've changed everything. I do not know how to "revert/correct" it.

### CODE REVIEW

**Comment by josep-m-carbonell** [comment]
Hi Lluís, I will check changes as soon as possible. Concerning to indentation check the wiki
https://github.com/KratosMultiphysics/Kratos/wiki/How-to-configure-clang‐format. 
I personally don't like this format, but is the one chosen as reference.

**Comment by lluis-mv** [comment]
Hi. I will check the identation style!
There is no rush. I did these changes time ago in a branch and today I needed them for the Biot contact we talked the other day.

**Review by josep-m-carbonell — APPROVED** [review]
OK

**Comment by lluis-mv** [comment]
thank you, @josep-m-carbonell

**Pull request merged**
