### PR TITLE
Adding integration points for line_gauss_lobatto

### PR DESCRIPTION
**Pull request by zidanmahmoud**
Adding up to 10 gauss points to the Gauss Lobatto rule. I have checked the values of the positions and weights using a Python code and a Matlab code to generate the integration points.

### CODE REVIEW

**Comment by philbucher** [comment]
to me this looks fine
objections @KratosMultiphysics/technical-committee ?

**Comment by philbucher** [comment]
@zidanmahmoud please merge master to trigger the CI

**Comment by rubenzorrilla** [comment]
No concerns. Please go ahead.

**Review by philbucher — APPROVED** [review]
ok from my side, I think it has been open long enough
Should not affect anyone, please go ahead @zidanmahmoud

**Comment by zidanmahmoud** [comment]
Thank you @philbucher @rubenzorrilla

**Pull request merged**
