### PR TITLE
Porting OMP loops to Parallel Utilities 12

### LINKED ISSUE #8508: Related to the header file "calculate_octree_signed_distance_to_3d_skin_process.h"
**Description**
While Porting OMP stuff to Parallel Utilities (in PR #8507):
I have observed that, this [header file](https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/processes/calculate_octree_signed_distance_to_3d_skin_process.h) is not included in the compilation or not used anymore, is it so? Because, I made some mistakes in this file (which I got to know later) not being recognized while compilation (including some syntax errors).

**Scope**
- KratosCore

### PR DESCRIPTION
**Pull request by ashishdarekar**
**Description**
This PR ports the OMP Parallel Loops to Parallel Utilities

- ParallelUtilities

**Changelog**
-Replaced Simple OMP For loop with Parallel Utitlities
-Replaced OMP Parallel For loops with Private variables with ParallelUtilities(TLS)
-Deleted the unwanted header file (issue #8508)

### CODE REVIEW

**Review by loumalouomega — CHANGES_REQUESTED** [review]
Thanks, I will block until we merge a certain changes I have done to fix a bug in the mortar mapper, and I assume there will be conflicts, and the issue was OMP related. OS it is relevant to block

**Comment by philbucher** [comment]
@loumalouomega did you already start with the changes?

@ashishdarekar I guess we wait, in any case seems that this causes some tests to fail, so lets keep it on hold

**Comment by loumalouomega** [comment]
> @loumalouomega did you already start with the changes?
The PR is already there, but I cannot find it because is not mine, is the swap bug fix.
> 
> @ashishdarekar I guess we wait, in any case seems that this causes some tests to fail, so lets keep it on hold

**Comment by philbucher** [comment]
ah ok, no worries then we wait

**Comment by loumalouomega** [comment]
> ah ok, no worries then we wait

 #8548 was merged, if the CI passes we can merge this

**Review by loumalouomega — DISMISSED** [review]

**Review by loumalouomega — APPROVED** [review]

**Comment by philbucher** [comment]
image

:D

**Comment by loumalouomega** [comment]
> image
> 
> :D

It was my code at the end

**Pull request merged**
