### PR TITLE
Reducing verbosity nighly tests. Using logger in model_part_io.cpp

### PR DESCRIPTION
**Pull request by loumalouomega**
This additionally will reduce verbosity on tests based in full simulation @marandra

### CODE REVIEW

**Comment by marandra** [comment]
Hi @loumalouomega , great improvement to the output of the tests. There are a very few more messages that I am still getting, in case you can do something about them:

```
 |  /           |             
 ' /   __| _` | __|  _ \   __|
 . \  |   (   | |   (   |\__ \ 
_|\_\_|  \__,_|\__|\___/ ____/
           Multi-Physics 5.3.0-678dc1638-Debug
Importing    KratosStructuralMechanicsApplication
     KRATOS   ___|  |                   |                   |                     
            \___ \  __|  __| |   |  __| __| |   |  __| _` | |                   
                  | |   |    |   | (    |   |   | |   (   | |                     
            _____/ \__|_|   \__,_|\___|\__|\__,_|_|  \__,_|_| MECHANICS     
Importing    KratosExternalSolversApplication
Initializing KratosExternalSolversApplication... 
ExternalSolversApplication: succesfully imported 
EigenSolversApplication: not imported 
FEASTSolver solver is not included in the compilation of the External Solvers Application
........................................Formfinding strategy created!
......................................ATTENTION! setting the RHS to zero!
.....Formfinding strategy created!
RESIDUAL CRITERION :: Ratio = 1;  Norm = 4.35465
RESIDUAL CRITERION :: Ratio = 1;  Norm = 6.68763e-16
RESIDUAL CRITERION :: Ratio = 1;  Norm = 6.27873e-15
......ATTENTION! setting the RHS to zero!
..ATTENTION! setting the RHS to zero!
................ATTENTION! setting the RHS to zero!
.ATTENTION! setting the RHS to zero!
...................................
----------------------------------------------------------------------
Ran 143 tests in 752.885s

OK

```

**Comment by marandra** [comment]
...even though I realize now that they are not related to model_part_io.cpp

**Comment by pooyan-dadvand** [comment]
@roigcarlo I think we should redirect the logger output by passing the test output stream to the logger output.

**Comment by roigcarlo** [comment]
Ok, good idea, this way we can control what is being printed. Should we do it in this PR?

**Comment by pooyan-dadvand** [comment]
I would, if not it will print lot of outputs in the nightly tests. You may update the title

**Comment by loumalouomega** [comment]
Oki

**Comment by roigcarlo** [comment]
:+1: Also this will solve the print problems in #1121

**Comment by loumalouomega** [comment]
@roigcarlo does this PR miss something?

**Comment by roigcarlo** [comment]
I should have done the logger integration but I have other fixes going on, maybe is better to merge and I will fix it in another branch. @pooyan-dadvand is that ok?

**Comment by roigcarlo** [comment]
@loumalouomega I am about to push a separate PR for all the problems with the printing in the tests, so feel free to merge this one.

**Comment by loumalouomega** [comment]
The approve...

**Review by roigcarlo — APPROVED** [review]

**Pull request merged**
