### PR TITLE
[NOT TO BE MERGED] disabling both cpp and python tests

### PR DESCRIPTION
**Pull request by inigolcanalejo**
Trying to find the following error given by CI:
```
corrupted size vs. prev_size
Aborted (core dumped)
##[error]Process completed with exit code 134.
```

### CODE REVIEW

**Comment by inigolcanalejo** [comment]
It seems to fail with cpp disabled and python enabled. Ill try disabling python too.

**Comment by inigolcanalejo** [comment]
@philbucher disabling all the tests (both cpp and python) still crashes, are you sure the error comes from the potential app?

**Comment by marcnunezc** [comment]
In #6227 the CI worked when the PotentialFlow was completely removed from compilation. Very weird :/ Any clue on what to try now?

**Comment by inigolcanalejo** [comment]
It is indeed weird. Yesterday @philbucher suggested it might be something related to the way we load the application. Ill try here again removing the application completely.

**Comment by marcnunezc** [comment]
If the problem is coming when we load the app, could we try to remove the import to python of the processes/utilities/etc to see where the error is happening?

**Comment by inigolcanalejo** [comment]
> utilities

Sounds like a good plan

**Comment by inigolcanalejo** [comment]
> If the problem is coming when we load the app, could we try to remove the import to python of the processes/utilities/etc to see where the error is happening?

I am not sure if this is what you meant, but I deleted the cpp test files completely so that there are no includes and I also commented the import from the python file

**Pull request closed without merging**
