### PR TITLE
func and test to compute upwinded density

### PR DESCRIPTION
**Pull request by eloisabaez**
n this pull request are functions to compute the density and an "upwinded density" which adds an artificial viscosity and the corresponding tests.

The density is calculated following Eq. 8.9 from Flight Vehicle Aerodynamics by Mark Drela.
densityeq
densitygraph

And the upwinded density is computed using Eq. 2.12 from Fully Simultaneous Coupling of the Full Potential Equation and the Integral Boundary Layer Equations in Three Dimensions by Brian Nishida
upwinddensityeq
upwinddensitygraph

### CODE REVIEW

**Review by inigolcanalejo — DISMISSED** [review]

**Comment by eloisabaez** [comment]
It seems as if everyone's pull requests from the last day are failing the tests

**Comment by inigolcanalejo** [comment]
Yeah... it seems so... https://github.com/KratosMultiphysics/Kratos/pull/7029#issuecomment-639313258

**Comment by inigolcanalejo** [comment]
https://github.com/KratosMultiphysics/Kratos/pull/7031 should solve the problem, you could try to merge master once https://github.com/KratosMultiphysics/Kratos/pull/7031 is merged

**Review by inigolcanalejo — APPROVED** [review]
:+1: 

It would be nice to have a separate test for the ComputeDensity. We can do it in a future PR

**Pull request merged**
