### PR TITLE
Feature variable utils check helpers

### PR DESCRIPTION
**Pull request by jcotela**
I'm defining a few functions for tasks that I find myself doing everytime I write an Element::Check method:
Checking if a variable has been registered
Checking if a variable has been added to a node's SolutionStepData
Checking if a node has a given DOF

I also included tests and examples (the base CFD elements use the new methods now).

@roigcarlo Can you check the macro defined in `8a378e6`? It works for me, but I'd prefer to have a second opinion...

### CODE REVIEW

**Comment by roigcarlo** [comment]
@jcotela Looks good! in fact I had something similar already done for the geometry in https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/tests/geometries/test_geometry.h#L35, but the trick of rising the KRATOS_ERROR after the function call its better that was I came with. 

The only problem I see is that maybe the output is confusing if it keeps printing the error associated to the exception you are capturing ( it happened to me ). If it is a problem it can be deactivated redirecting the std::cout during the check ( see me example ). If that's not a problem for you then 👍

**Comment by jcotela** [comment]
Thanks for the hints! I didn't notice the issue of the confusing output because I only ran this within our C tests, which already throw away most output by default.
Maybe it would be worth it to merge the two macros? I can check it tomorrow.

**Comment by roigcarlo** [comment]
Yep, with your PR the other its not necessary anymore, I can take a look as well tomorrow

**Comment by RiccardoRossi** [comment]
Hi Jordi,
i would put the additional funcitons in another header, just because variable_utils includes the model part and you would not want to include it in all the elements

**Comment by jcotela** [comment]
@RiccardoRossi I've moved the functions to their own header.
@roigcarlo I could not reproduce the issue with the output, so I'm going ahead with a slightly modified version of my last commit.

**Review by RiccardoRossi — APPROVED** [review]
+1 (apart for the spelling mistake)

**Comment by jcotela** [comment]
@roigcarlo I have just fixed the spelling mistake that Riccardo pointed out. Can you confirm you are OK with the change? Otherwise I'll revert and merge.

**Comment by roigcarlo** [comment]
Oh, that was mine sorry. Yep its good thx! (and sorry :P)

**Comment by pooyan-dadvand** [comment]
Sorry for my late reply (after merge) but I would unify this with the checks.h macros. Actually I have made them macro to address the issue of the error source without having to dig in the stack. Even you can put the macros in checks.h

**Comment by jcotela** [comment]
@pooyan-dadvand the new macro is already in checks.h, (in fact we removed a similar one from the geometry tests)

**Comment by pooyan-dadvand** [comment]
I was referring to the checks you added to see if the variable is registered and added to nodal data. Using macro for these checks gives the correct line number and file even if you don't catch the error in your check method.

**Comment by jcotela** [comment]
@pooyan-dadvand Should we move the new variable checks to checks.h then? I didn't consider it (I was concerned about introducing more `#includes` in checks.h, but I guess this is not really a problem, since nodes and  variables are only used within macros). If so, I'll do it once I'm back.

**Comment by pooyan-dadvand** [comment]
And creating a macro for getting the correct code location would also help

**Pull request merged**
