### PR TITLE
[DO NOT MERGE][ContactStructuralMechanicsApplication] Fix nightly CI

### PR DESCRIPTION
**Pull request by loumalouomega**
This PR is to check the fixes of the nightly CI (and eventually merge)

### CODE REVIEW

**Comment by philbucher** [comment]
Do you want to see if your tests work in the nightly build?

**Comment by loumalouomega** [comment]
Yes, that's why I aim to check test by test. I deactivate all tests and put
as small test the one I want to check.

**Comment by rubenzorrilla** [comment]
@loumalouomega Is this still required?

**Comment by loumalouomega** [comment]
> 
> 
> @loumalouomega Is this still required?

Yes, but I do not how to proceed without uploading thousands of commits and check if the CI works. There is a way to replicate the CI in my machine?, I assume the CI works wioth a certain docker and I can use the docker image to debug, @philbucher ?

**Comment by philbucher** [comment]
I guess this is no longer needed in the menatime?

**Comment by loumalouomega** [comment]
Nope

**Pull request closed without merging**
