### PR TITLE
[Core] Remove unused folders

### LINKED ISSUE #5806: [Core][Clean Up] Are the following folder necesaries?
https://github.com/KratosMultiphysics/Kratos/tree/master/packaging_aux 

https://github.com/KratosMultiphysics/Kratos/tree/master/problemtype_generator

Last update of both folders was 6 years ago

### PR DESCRIPTION
**Pull request by loumalouomega**
Fixes #5806

### CODE REVIEW

**Comment by philbucher** [comment]
This is up to @roigcarlo , to me looks unused but he knows better :)

**Comment by roigcarlo** [comment]
I think its fine but let me discuss it first with ricc

**Comment by roigcarlo** [comment]
@KratosMultiphysics/technical-committee We decided to remove the packaging one and move the problemtype generator to legagy repo

**Comment by loumalouomega** [comment]
> 
> 
> @KratosMultiphysics/technical-committee We decided to remove the packaging one and move the problemtype generator to legagy repo

So I revert the problemtype generator?

**Review by philbucher — APPROVED** [review]
I moved the problemtype_generator to the legacy-app, hence this can be merged as is

**Pull request merged**
