### PR TITLE
[Core] Adding Kratos::Filesystem

### PR DESCRIPTION
**Pull request by philbucher**
This PR adds the capabilities of [`std::filesystem` (c++17)](https://en.cppreference.com/w/cpp/filesystem) by using the [external library ghc](https://github.com/gulrak/filesystem) (license: BSD3)
It is header only and pure c++11, like pybind in a nutshell

This is a "temporary" solution until we have c++17, which will take many years. Filesystem is a very useful and powerful library, esp for writting platform-independent code. Hence I would really like to have it it Kratos / I think many could use it & benefit from it .

I implemented a "switch" mechanism, if c++17 is used and `filesystem` is available, then it will use the one from the STL

in a small project of mine I tried this in Ubuntu, Win & MacOS, with & without c++17, works like a charm

The usage is pretty straight forward, same as e.g. `Kratos::shared_ptr` => `Kratos::filesystem`

This is a better solution than #4923 
closes #4923

### CODE REVIEW

**Comment by philbucher** [comment]
hm again some very strange appveyor errors :roll_eyes: 
@roigcarlo could you please have a look when you have time? Not urgent though I guess...

**Comment by philbucher** [comment]
Ok nevermind, now compiles :)

**Review by loumalouomega — CHANGES_REQUESTED** [review]
Can we integrate with OSUtilities? (replacing duplicated methods), otherwise we will have duplicated utilities

**Comment by philbucher** [comment]
I would remove the OSUtils after this is merged. It is only a duplication of filesystem (and currently has only one method on master)

**Comment by loumalouomega** [comment]
> I would remove the OSUtils after this is merged. It is only a duplication of filesystem (and currently has only one method on master)

In that case I would remove it in this PR, and close #4923

**Comment by philbucher** [comment]
Makes sense to me
Lets wait for @KratosMultiphysics/technical-committee

**Comment by philbucher** [comment]
ping @pooyan-dadvand please check this

**Comment by philbucher** [comment]
@pooyan-dadvand it passes all checks including the actions

**Comment by philbucher** [comment]
@loumalouomega I only deprecated `OSUtilities` in this PR, because some refactoring is necessary, esp for paths-handling (which is also available in filesystem)
Internally also OSUtilities uses filesystem now, so it should not be difficult to update in a next step

**Comment by pooyan-dadvand** [comment]
Seems that gcc 4.8.5 in Centos don't understand the `__has_include` macro:

```
error: missing binary operator before token "("
 #if defined(__cplusplus) && __cplusplus >= 201703L && defined(__has_include) && __has_include(<filesystem>)
```

**Comment by philbucher** [comment]
ok I suspected this could happen, it is C++17
I will move it to the next line, then it will not even see it, one sec

**Comment by philbucher** [comment]
@pooyan-dadvand could you please try again?
Now should work, sorry for the inconvenience

**Comment by pooyan-dadvand** [comment]
Now works! Thanks for the change!! :+1:

**Comment by philbucher** [comment]
Nice!
Should we merge it then or wait?

**Comment by pooyan-dadvand** [comment]
@KratosMultiphysics/technical-committee approves it!

**Comment by philbucher** [comment]
@loumalouomega can you please remove your block?

**Review by loumalouomega — DISMISSED** [review]

**Review by loumalouomega — APPROVED** [review]
I added the thanks

**Pull request merged**
