### PR TITLE
[Core][ContactStructuralMechanicsApplication] Adding python process interface to SimpleMortarMapper

### PR DESCRIPTION
**Pull request by loumalouomega**
So it can be called from the *.json Parameters without additional  modifications

BTW: I discovered that Parameters do not have a copy constructor interface in python. That's why the Parameters are duplicated

### CODE REVIEW

**Comment by philbucher** [comment]
What is the usecase for this?

We thought long if Mapping should be a process or not, but decided against it bcs basically the usage is problem dependent and hence it is not possible to be generalized

**Comment by loumalouomega** [comment]
> What is the usecase for this?
> 
> We thought long if Mapping should be a process or not, but decided against it bcs basically the usage is problem dependent and hence it is not possible to be generalized

In contact many values are only in the slave domain, until now I had to hardcode the mapper, the idea is to use this instead, so I have more flexibility. This is extensible to other uses

**Comment by philbucher** [comment]
but if you had it hardcoded so far it sounds like this is not optional
making it a process makes it possible to be used wrong

=> thats what I meant that it is really problem dependent

**Comment by loumalouomega** [comment]
> but if you had it hardcoded so far it sounds like this is not optional
> making it a process makes it possible to be used wrong

This is also because I did not have this alternative 

> => thats what I meant that it is really problem dependent

I think there nothing wrong to allow to the user/developer to use it if it fits their needs. Maybe some people could use it only for postprocess reasons.

**Comment by philbucher** [comment]
but can you use the contact without the mapper?
If no then I don't think it should be optional (i.e. a process)

Regarding the other use-cases I am really not sure if it is applicable. Until we have a concrete usecase that could really benefit from such a feature I would not add it to the core

**Comment by loumalouomega** [comment]
> but can you use the contact without the mapper?
> If no then I don't think it should be optional (i.e. a process)

Yes, I can. It's for a development stuff. I can move it to the Contact, but like the cpp process is on the core I think the python one should be there too

> Regarding the other use-cases I am really not sure if it is applicable. Until we have a concrete usecase that could really benefit from such a feature I would not add it to the core

Again, I can move it to the my app, but then will be restricted to my app, despite to use only core technology. This is a python script, does not add additional compilation time and it is not mandatory

**Comment by philbucher** [comment]
Still it is sth that has to be maintained 

If there is no concrete usecase for it then I would leave it in contact for now

**Comment by loumalouomega** [comment]
> Still it is sth that has to be maintained

Not many lines, but OK

> If there is no concrete usecase for it then I would leave it in contact for now

Ok, if that you think it is the best I will

**Comment by loumalouomega** [comment]
@philbucher file moved

**Comment by philbucher** [comment]
ok from my side 
Approval I leave to @rubenzorrilla since I don't use this

**Comment by loumalouomega** [comment]
I basically just added ExecuteInitializeStep

**Review by philbucher — APPROVED** [review]
appriving since looks good to me 

FYI @rubenzorrilla

**Pull request merged**
