### PR TITLE
[GeoMechanics] Reverting changes from 0bce654

### PR DESCRIPTION
**Pull request by roigcarlo**
**Description**
Should solve #8966 

Note, this merges the changes into GeoMechanicsBranch, not into master. @rubenzorrilla / @pablobecker  Please double check this is ok and its consistent with the master.

**Changelog**
- Restoring changes #8717 dropped in 0bce654

### CODE REVIEW

**Review by Vahid-Galavi — APPROVED** [review]

**Comment by Vahid-Galavi** [comment]
Thanks a lot @roigcarlo for the fix!

**Comment by roigcarlo** [comment]
Np :+1:. Could you confirm it works on your side too before merging?

**Review by rubenzorrilla — APPROVED** [review]
I think this brings the latest changes. :+1:

**Comment by Vahid-Galavi** [comment]
> Np 👍. Could you confirm it works on your side too before merging?

Yes, it works! Well done @roigcarlo!

**Pull request merged**
