### PR TITLE
[Core] Fixing error when trying to post-process submodelparts with VTKProcess

### PR DESCRIPTION
**Pull request by loumalouomega**
When a submodelpart only  contains conditions or elements, if the `output_sub_model_parts` is set to true and error is thrown. This fixes that, so it creates an auxiliar modelpart that is later removed, which contains the elements/conditions + the nodes contained on those elements/conditions

### CODE REVIEW

**Comment by philbucher** [comment]
I don’t really like the submodelparts option, since it creates more problems than it solves

Can we speak in person abt removing it rather than adding hacks like this?

**Review by philbucher — CHANGES_REQUESTED** [review]
Thanks for the effort nevertheless, blocking until discussed

**Comment by loumalouomega** [comment]
Later?

**Comment by philbucher** [comment]
I discussed this change with @adityaghantasala and we agreed that this should not be merged as is, since it is quite a hacky solution for a small benefit.

Instead in a PR @adityaghantasala is abt to make he is going to change the default of outputting submodelparts to false, which should solve this problem in most cases.

Actually we were both surprised that it is possible to have conditions/elements in submodelparts without the corresponding nodes. Neither of us has seen this so far and we think that it is quite a unique case, for which we should not make such a big effort

If it remains a big problem and source of inconvenience we can again discuss it in the future.

Also if you want we can discuss this in person @loumalouomega

**Comment by loumalouomega** [comment]
We can discuss now if you are in your office, but my contact problems there
are several submodelparts containing only conditions.

**Comment by philbucher** [comment]
we are both here, just come by

**Comment by loumalouomega** [comment]
I solved the conflicts and moved to a private function as we discussed

**Comment by loumalouomega** [comment]
I fixed the testing error

**Review by philbucher — APPROVED** [review]
Approving, as discussed in person, thx

**Review by adityaghantasala — APPROVED** [review]

**Comment by loumalouomega** [comment]
Thanks

**Pull request merged**
