### PR TITLE
[CORE + NOT to Merge yet] Using BoundedVector and BoundedMatrix inside ConstitutiveLaw

### PR DESCRIPTION
**Pull request by AlejandroCornejo**
Dear @KratosMultiphysics/all 

In this PR I'll add all the changes regarding the change from **Vector/Matrix to BoundedVector/BoundedMatrix** inside the `constitutive_law `class.

This will enhance the velocity of the calculation since the sizes of the matrices will be know at compile time. (I'll perform a benchmark to check it).

I am going to update the `StructuralMechanicsApp `as a starting point so everyone will see how it is done. Later I'll update the `ConstitutiveLawsApp `and the  `FemToDemApp`

### CODE REVIEW

**Comment by AlejandroCornejo** [comment]
@AFranci This could be a good oportunity to change all the Vector/Matrix that are allocated so much times inside the PFEM and improve quite a lot the velocity of the App ! :D 🚀

**Comment by AlejandroCornejo** [comment]
Apparently I have a compilation problem when changind the variable type of the `GREEN_LAGRANGE_STRAIN_VECTOR `for example inside `variables.h` because it does no know what BoundedVector<double, 6> is... Any hint? :)

**Review by loumalouomega — CHANGES_REQUESTED** [review]
Blocking until is fixed and tests pass

**Comment by loumalouomega** [comment]
Do we still need this branch @AlejandroCornejo ?, can we remove it?

**Pull request closed without merging**
