### PR TITLE
StructuralMechanics move test to validation

### PR DESCRIPTION
**Pull request by philbucher**
Moving a very slow est to Validation
Now it should again work in the Nightly Tests

### CODE REVIEW

**Review by KlausBSautter — APPROVED** [review]

**Comment by RiccardoRossi** [comment]
guys, i am not against this change HOWEVER a beam test should take no time.

why is this taking so long??

**Comment by philbucher** [comment]
This is a full rollup test with 1500 time steps

**Comment by RiccardoRossi** [comment]
can't this be done in, say, 20 steps? 

In any case even with 1500 steps, if you have 20 elements it should take nothing...

**Comment by philbucher** [comment]
We know, we know
Work in progress :)

**Pull request merged**
