### PR TITLE
[dem] Fix memory access for 1N conditions

### PR DESCRIPTION
**Pull request by KlausBSautter**
Hi, I recently made a PR #8406 to enable the direct use of 1 noded conditions. All worked fine on Linux until we ran the new test cases on a windows machine and had our simulation crashed. So we found a function that I missed and which accessed memory that is not allocated. 

This problem is fixed with this PR.

### CODE REVIEW

**Comment by maceligueta** [comment]
Hi @KlausBSautter I am glad you detected the source of the problem. However, I thought of an alternative to your implementation that could save you from allocating a matrix every time you check the contact between a sphere and a point.

- I would remove `FastIntersection1D`
- Instead of calling `FastIntersection1D`, I would call a new function called `FastVertexCheck `in `GeometryFunctions`
- The code inside `FastVertexCheck ` would contain just:
```cpp
        double dist_sq = 0.0;
        array_1d<double, 3> normal_v;
        for (unsigned int j = 0; j < 3; j++) {
            normal_v[j] = Particle_Coord[j] - Coord[j];
            dist_sq += normal_v[j] * normal_v[j];
        }
        if (dist_sq <= Radius * Radius) { return true; }
        return false;
```

I am proposing this because, apparently, you do not need the LocalCoordinates matrix for anything. Does this make any sense?

**Comment by KlausBSautter** [comment]
Yes this makes sense, I actually thought of the same but didnt want to change too much Code :D I'll do this change tmr. Thanks for the comment!

**Comment by KlausBSautter** [comment]
@maceligueta I re-wrote the code. Is this how you wanted it to be?

You will also note that I changed 
`FE_Geom.WorkingSpaceDimension()`
to
`FE_Geom.size()`

I was wondering about that and then saw that this has been changed by me 3 years ago when we did the RigidFace2N3D. It was `FE_Geom.size()` before and now I changed it back. I was probably confused by the naming, on my machine, the Kratos tests and my local tests this does not change the results but could again lead to memory problems. I am pretty sure it is correct now.

**Comment by maceligueta** [comment]
Honestly, I am not 100% sure if `GE_Geom.size()` is correct or not. It seems correct to me, but I would need to get deep into the calls inside those ifs to really understand if it should be WorkingDimension instead. 
@joaquinirazabal might help us with this eventually.
Since the tests are passing fine, I approve the PR. But I will open an issue so we can make sure when @joaquinirazabal is back.

**Review by maceligueta — APPROVED** [review]

**Comment by KlausBSautter** [comment]
thanks @maceligueta !

**Pull request merged**
