### PR TITLE
[StructuralMechanicsApplication][Hotfix] Wrong dof list on conditions

### PR DESCRIPTION
**Pull request by loumalouomega**
Without this the line load doesn't work on more than 1 thread

### CODE REVIEW

**Comment by RiccardoRossi** [comment]
@loumalouomega @roigcarlo i think this should be backported to Release. 

If it cannot make for the release being compiled now, let's have it for one of the bugfix releases

**Comment by loumalouomega** [comment]
@RiccardoRossi approve this, it solves the problem for the release

**Comment by loumalouomega** [comment]
Look the target Release 6.0

**Comment by roigcarlo** [comment]
Shall we merge it or no? It would be great if we can have everything in the release 6.0 before noon so the binaries are there for the evening

**Comment by loumalouomega** [comment]
Yes, this is important

**Review by roigcarlo — APPROVED** [review]
I will approve it myself then.

**Comment by loumalouomega** [comment]
Can we approve this?

**Review by RiccardoRossi — APPROVED** [review]
important one.

ping @roigcarlo --> this should go in release

**Comment by roigcarlo** [comment]
I'm gonna merge this or otherwise I won't have time to make a release before leaving.

**Pull request merged**
