### PR TITLE
[Core][TO DISCUSS NOT TO MERGE] Modification of geometry to allow external pointer vectors

### PR DESCRIPTION
**Pull request by tteschemacher**
Hi all,

I'd have a very small modification for the geometry. This would allow the possibility to exchange the PointerVector and link it to different ones. 

With the suggested strategy one can have the pointer vector stored at multiple objects. Or exchange it if necessary.

This would help us to link from inside the geometry to a foreign list of nodes which might be stored at special classes (in our case Nurbs classes, but any kind of shape is possible).

Do you think this would go in a possible direction?

@KratosMultiphysics/technical-committee @KratosMultiphysics/implementation-committee

### CODE REVIEW

**Comment by loumalouomega** [comment]
Both Travis and Appveyor are failing

**Comment by loumalouomega** [comment]
Adding discussion to @KratosMultiphysics/implementation-committee

**Comment by tteschemacher** [comment]
> 
> 
> Both Travis and Appveyor are failing

at least Codacy says yes ;)

**Comment by loumalouomega** [comment]
> > Both Travis and Appveyor are failing
> 
> at least Codacy says yes ;)

**Comment by philbucher** [comment]
closing since we found a better way of doing this: #4872

**Pull request closed without merging**
