### PR TITLE
[MeshingApplication] Installation of MMG and PMMG libs

### PR DESCRIPTION
**Pull request by loumalouomega**
**Description**
Without this, I cannot execute MMG tests

**Changelog**
- Installation of MMG libs

### CODE REVIEW

**Comment by marcnunezc** [comment]
Ok to me if it is needed but I have some questions:

What error do you get when running? Why is it not working on your system as it right now?


Does this avoid having to add the mmg lib path in LD_LIBRARY_PATH?

**Comment by loumalouomega** [comment]
> Does this avoid having to add the mmg lib path in LD_LIBRARY_PATH?

That's the idea (and I forgot that, so now I know what I was doing wrong :P)

**Comment by marcnunezc** [comment]
Very cool! I just tested this and it works fine, this simplifies the MMG installation as it not needed to append manually the libs path into LD_LIBRARY_PATH.

I took the chance to also update the PMMG install here.

**Comment by marcnunezc** [comment]
@AlejandroCornejo can you confirm if this works on your environment in windows? 

@roigcarlo do you see any potential issue with this?

**Comment by loumalouomega** [comment]
> @AlejandroCornejo can you confirm if this works on your environment in windows?
> 
> @roigcarlo do you see any potential issue with this?

Mayeb we can create a cmake amcro so it can be used in several places

**Comment by roigcarlo** [comment]
No problem form my side :+1:

**Comment by loumalouomega** [comment]
Ping

**Comment by roigcarlo** [comment]
I can approve if you want, but I can only confirm it works on linux (haven't tested in win)

**Comment by loumalouomega** [comment]
Can we test it on Windows?

**Review by marcnunezc — APPROVED** [review]
I tried on Windows and it works fine for me, I dont need to set explicitly the path to the mmg lib.

**Pull request merged**
