### PR TITLE
Test/enabling test hdf5

### LINKED ISSUE #2687: Adding HDF5Application to nightly tests
The HDF5Application should be added to the nightly tests, first of all to test if the app itself works and second, bcs more other apps start to depend on it (see #2686 ).
The tricky thing (the stuff I don't know :) ) is to add the installation of the hdf-libs, as described in the [Application-README(https://github.com/KratosMultiphysics/Kratos/tree/master/applications/HDF5Application)]
@roigcarlo can you please help with this?

### PR DESCRIPTION
**Pull request by roigcarlo**
This should close #2687.

I am not sure about the order change in the apt-get instruction since the unasisted upgrades from ubuntu are still happening but should be safe with the 5 min sleep.

### CODE REVIEW

**Comment by philbucher** [comment]
That was fast, thx!
There is no way to test this except approving and merging right?

**Review by msandre — APPROVED** [review]
It looks good to me. Like @philbucher I don't know if we can test it before merging. Thanks!

**Comment by roigcarlo** [comment]
No way to test, but the only problem should be the unasisted updates. Anyway I can check the log of the machine directly so if something goes wrong I can fix it before next nightly

**Comment by philbucher** [comment]
@roigcarlo can this be merged to get test it in the nightly build?

**Comment by roigcarlo** [comment]
sure

**Comment by philbucher** [comment]
I didn't receive the nightly report, seems like sth went wrong :)

**Comment by roigcarlo** [comment]
Yep not event sent from the server, investigating...

**Pull request merged**
