### PR TITLE
[Core] Adding version check for intel compiler in Cmake

### PR DESCRIPTION
**Pull request by philbucher**
The pybind error works, but it still compiles half of the code

Having this error makes it fail immediately

### CODE REVIEW

**Comment by philbucher** [comment]
see #1988

**Comment by philbucher** [comment]
@roigcarlo I disabled the warning (if omp is switched of) abt missing omp pragmas

**Comment by philbucher** [comment]
ping @roigcarlo

**Review by roigcarlo — APPROVED** [review]
Sorry I forgot about this. I will approve but have in mind that we still have heavy problems using intel

**Comment by philbucher** [comment]
thx

**Comment by philbucher** [comment]
I know there are still problems but this is unrelated/required in any case

**Pull request merged**
