### PR TITLE
[Core][MPI] Considering general data communicator instead of sub data communicator

### PR DESCRIPTION
**Pull request by loumalouomega**
**📝 Description**

Modify https://github.com/KratosMultiphysics/Kratos/pull/11719

Considering general data communicator instead of sub data communicator

**TODO**: Using coloring utilities instead of manual coloring

**🆕 Changelog**

- [Update search utilities](https://github.com/KratosMultiphysics/Kratos/commit/3a54ce5d05a84eb56eb7a877d920f3a903853aae)
- [Update the `SpatialSearchResultContainer` adding `SpatialSearchCommunicator` enum](https://github.com/KratosMultiphysics/Kratos/commit/f8a029dc83dcfe12a18e5442a60d0a503b976367)
- [Update the `SpatialSearchResultContainerVector` adding `SpatialSearchCommunicator` enum](https://github.com/KratosMultiphysics/Kratos/commit/8ff6850ebccb5fddeb389f678c66c9c27ed034a4)
- [Update the `SearchWrapper` consistently](https://github.com/KratosMultiphysics/Kratos/commit/d4e5cdcf13efdd3c37d0c51af3d352aed4d482fe)
- [Update python exposition](https://github.com/KratosMultiphysics/Kratos/commit/a3ec6bbf9b57c74e7be9d5a0a943a5addb8285e1)

### CODE REVIEW

**Comment by pooyan-dadvand** [comment]
Before starting a detailed review, why are you still keeping the pointwise communicator as an option? what is the benefit?

**Comment by loumalouomega** [comment]
> Before starting a detailed review, why are you still keeping the pointwise communicator as an option? what is the benefit?

Here are the key reasons for the finally proposed design:

1. **Personal reason**: The development of the pointwise ("heterogeneous") communicator was a significant effort on my part, resulting in a design that I personally liked. This reason is purely subjective.

2. **Performance and resource efficiency**: Initial tests, but with a limited number of partitions, have shown that in certain scenarios, the pointwise communicator (referred to as "heterogeneous" communication) outperforms the default "homogeneous" communication mode in terms of speed and memory usage. This evidence supports its potential advantage in specific use cases. By default is "homogeneous", but I like the idea of leting the power use to decide.

3. **Future-proofing and flexibility**: The implementation of a templated design framework with the pointwise communicator is a strategic step toward enabling asynchronous communication capabilities in the future. I believe that asynchronous communication will significantly enhance performance and scalability, making it a valuable solution.

By maintaining the "heterogeneous" communicator as an option, we aim to offer users, especially those with advanced requirements, the flexibility to choose the most suitable communication strategy for their particular context. This approach aligns with our commitment to providing versatile and high-performance computing solutions.

**Comment by loumalouomega** [comment]
Git is broken...

**Comment by loumalouomega** [comment]
Okay, I see why is not appearing differences, apparently git yesterday didsome weird things. I will merge directly

**Pull request merged**
