### PR TITLE
Pfem warnings removed

### PR DESCRIPTION
**Pull request by maceligueta**

### CODE REVIEW

**Review by pooyan-dadvand — APPROVED** [review]
👍 

But seems that the tests are not running

**Comment by josep-m-carbonell** [comment]
Did you try to change the a BigText a little bit to avoid the multi-comment warning instead of removing these lines?

**Comment by maceligueta** [comment]
Honestly, I did not find the exact cause of the warning. I tried to, but I did not want to dedicate much time to keep something which just brings aesthetics. 
This warning was showing up for several days and nobody fixed it, but this solution is working. If you find a better one, that would be great! The branch is not merged yet.

**Review by josep-m-carbonell — APPROVED** [review]

**Comment by josep-m-carbonell** [comment]
In my computer it does not appear the warning anymore just taking the \ away in the corresponding line.

**Pull request merged**
