### PR TITLE
[Core] adding functions to check if an app is available

### PR DESCRIPTION
**Pull request by philbucher**
This can be useful, at least I would like to use it :)

refactored from `run_tests.py` and #3562 , I can solve the conflicts there afterwards

### CODE REVIEW

**Comment by philbucher** [comment]
ping @roigcarlo

**Review by roigcarlo — APPROVED** [review]
👍 

Sorry I missed the notification
Just a heads up, I have detected a bug with this code that happens when
1- You compile KratosCore, AppA, AppB
2- You compile KratosCore, AppB

You try to run/detect applications compiled, it detects A and B, while only B is up to date, which may cause errors.

Aside from that all good!

**Comment by roigcarlo** [comment]
I mean, the same error is currently in the run_tests.py scrip, I just don't konow how to solve it yet.

**Comment by philbucher** [comment]
no worries, thx!

The error you describe does not happen if the `KratosMultiphysics` folder is deleted in the configure.sh right?
=> same as what is described in #2848 right?

**Comment by roigcarlo** [comment]
Yep its the same thing

**Pull request merged**
