### PR TITLE
Disabling processes

### PR DESCRIPTION
**Pull request by roigcarlo**
Process are not ready for the generator.

### CODE REVIEW

**Review by jcotela — DISMISSED** [review]
:+1: Unrelated to this PR, but can I ask you to also remove references to the application_interface from the generator, when you have the time? I want to push for removing that file in the next release cycle.

**Comment by roigcarlo** [comment]
I can do it here, its quite fast

**Comment by roigcarlo** [comment]
Done

**Review by jcotela — APPROVED** [review]
thanks, reapproving

**Comment by philbucher** [comment]
is this branch still needed?

**Comment by loumalouomega** [comment]
Can we delete this branch @roigcarlo ?

**Comment by roigcarlo** [comment]
Yes we can

**Pull request merged**
