### PR TITLE
[Poro] Adding explicit solver (mechanical only for the moment)

### PR DESCRIPTION
**Pull request by ipouplana**
**Description**
A explicit solver is added for the mechanical solution. The hydro-mechanical coupled explicit solver will be added in a future PR.

**Changelog**
- Added poro explicit solver
- Added central differences and velocity verlet schemes
- Added necessary variables
- Minor cleanup

### CODE REVIEW

**Review by salvalatorre — DISMISSED** [review]
Good job!

**Comment by ipouplana** [comment]
@salvalatorre could you re-approve ? 
I had to merge the master branch to resolve some conflicts with the previous PR and your revision was dismissed...

**Comment by salvalatorre** [comment]
> @salvalatorre could you re-approve ?
> I had to merge the master branch to resolve some conflicts with the previous PR and your revision was dismissed...

No problem, good!

**Review by salvalatorre — APPROVED** [review]

**Comment by RiccardoRossi** [comment]
guys did u rake a look at how we organized the runge kutta dtrategy? ask to
Ruben about that

**Comment by ipouplana** [comment]
I’ll take a look. Thanks!

**Pull request merged**
