### PR TITLE
[Core] Trying to fix KratosGlobals Windows random fail

### PR DESCRIPTION
**Pull request by loumalouomega**
**📝 Description**

Trying to fix KratosGlobals Windows random fail

@roigcarlo I think it is related with the life span of the kernel if used as it is now

**🆕 Changelog**

- [Trying to fix KratosGlobals Windows random fail](https://github.com/KratosMultiphysics/Kratos/commit/4c9d73a7c014d98e83c6fc1220201c631e10f2d8)

### CODE REVIEW

**Comment by loumalouomega** [comment]
@roigcarlo let's see now

**Comment by loumalouomega** [comment]
@roigcarlo looks like fixed

**Comment by loumalouomega** [comment]
@roigcarlo this may blocking other CI, can you take a look?

**Review by roigcarlo — APPROVED** [review]
I will approve because this is critical. 

`python_version = Kernel(using_mpi).PythonVersion()` was creating a copy of the kernel uninitialized.

I will follow this PR with another that prevents to make accidental copies of the kernel...

**Comment by loumalouomega** [comment]
> I will approve because this is critical.
> 
> `python_version = Kernel(using_mpi).PythonVersion()` was creating a copy of the kernel uninitialized.
> 
> I will follow this PR with another that prevents to make accidental copies of the kernel...

**Pull request merged**
