### PR TITLE
Feature has table

### LINKED ISSUE #31: Develompents for tables and properties for the usage in the ConstitutiveLaw
I would like to know how to work with tables in a proper way. My question is related with this and with the assignation of tables to Properties. 

If I have a YOUNG_MODULUS variable that is defined by a Table for different temperatures, how I check if the value is supplied by a table of the properties or by a variable of the properties ? Is there any method implemented for that issue?

@KratosMultiphysics/technical-committee

### PR DESCRIPTION
**Pull request by pooyan-dadvand**
A `HasTable` method is implemented in Properties and a test in c++ is implemented. This closes #31. The python interface is still missing.

### CODE REVIEW

**Review by josep-m-carbonell — APPROVED** [review]
Thank you Pooyan. Everything seems ok.

**Comment by pooyan-dadvand** [comment]
I have only compiled and test it on windows. @josep-m-carbonell have you test it on Linux?

**Comment by RiccardoRossi** [comment]
@pooyan, i compiled this in linux. i would say it is ok. 3 cpp tests fail but i think are fixed on master...that is, go ahead

**Comment by josep-m-carbonell** [comment]
@pooyan-dadvand , I compiled it too in linux. No error in tests related to this new implementation.

**Pull request merged**
