### PR TITLE
Skipping FSI tests if a required application is missing.

### PR DESCRIPTION
**Pull request by jcotela**
Possible solution for Issue #248

### CODE REVIEW

**Review by RiccardoRossi — APPROVED** [review]
+1 for the merge of this.

my only concern is if it will work on python2. However the code is already failing so it would not be a regression

**Comment by jcotela** [comment]
@RiccardoRossi Good point about python 2 (I think it can be solved by adding some kind of `from __future__ import`). Do we have a machine where we can test it?

**Review by rubenzorrilla — APPROVED** [review]
Everything makes sense to me. Thanks @jcotela!

**Comment by jcotela** [comment]
According to [PEP 3110](https://www.python.org/dev/peps/pep-3110/#compatibility) the `catch Exception as e` syntax should be supported as is by python 2.6 and newer, which is consistent with our other requirements. Based on that, I'm going ahead and merging this.

**Pull request merged**
