### PR TITLE
Core _init_ compatibility with python 2.7 and improved readability

### PR DESCRIPTION
**Pull request by maceligueta**

### CODE REVIEW

**Review by rubenzorrilla — APPROVED** [review]
Thanks MA!

**Comment by roigcarlo** [comment]
Just curiosity, what was the problem?

**Comment by maceligueta** [comment]
The substitution of {0} was not working. In the console, it was printing {0}. Also, I added the name of the main script, to help the user identify where to add the import (I have noticed sometimes that Python complains about 'not importing a certain module from the main script' but then it makes reference to a script that isn't the one you called).

**Comment by roigcarlo** [comment]
Ok thx @maceligueta !

**Pull request merged**
