### PR TITLE
Correcting components variables

### PR DESCRIPTION
**Pull request by bodhinandach**

### CODE REVIEW

**Comment by bodhinandach** [comment]
[TestMPM2D_case1_test.gid.zip](https://github.com/KratosMultiphysics/Kratos/files/1902690/TestMPM2D_case1_test.gid.zip)
@loumalouomega can you please check this?

**Comment by loumalouomega** [comment]
[TestMPM2D_case1_test.gid.tar.gz](https://github.com/KratosMultiphysics/Kratos/files/1902817/TestMPM2D_case1_test.gid.tar.gz)

Now it works

**Review by loumalouomega — APPROVED** [review]
Ok, this solves the problem

**Comment by loumalouomega** [comment]
Ping @bodhinandach, @iiaconeta   and @antonialarese ParticleMechanicsApplication is now compatible with pybind

**Comment by bodhinandach** [comment]
Thanks, @loumalouomega for the help. I updated the interface in GiD as well and recheck with small examples. They are working okay.

**Pull request merged**
