### PR TITLE
Add SetTime method for cosimulation solver_wrapper

### PR DESCRIPTION
**Pull request by ghanique-altair**
**📝 Description**
This development enable to send the global time of a cosimulation to a steady solver through the solver_wrapper. This is only usefull for steady solvers which need to update parameters depending on the global time and then reproduce a so-called transient behavior.

**🆕 Changelog**
 - Modified CosimulationApplication : add SetTime method to solver_wrapper to send global time to steady solvers

### CODE REVIEW

**Comment by philbucher** [comment]
Thanks for the contribution
Please give me a few day to think about this, maybe there is a better way of doing this
I coupled with steady state solvers before, then it was working

**Comment by philbucher** [comment]
`AdvanceInTime` already get the current global time, did you try using this?

**Comment by ghanique-altair** [comment]
For sure I tried, but in the case, the time sent to the steady solver is one step late.

**Comment by philbucher** [comment]
But AdvanceInTime is called before your proposed SetTime method

**Comment by ghanique-altair** [comment]
AdvanceInTime get the currentTime from the transient solver, so you have to wait for the next call of AdvanceInTime to be able to sent that time value to a steady solver, so it is one step late.

**Comment by philbucher** [comment]
Ok now I understand

Given that the global time is already in the processInfo of the coupled solver, I am leaning towards passing this one to the solver-wrappers. Checking it now ...

**Comment by philbucher** [comment]
can you check if it works with my commit?

Now you can access the global time from the solver wrapper

**Comment by ghanique-altair** [comment]
Ok, thanks to your modification I can access to the global time of the cosimulation in my Flux solver_wrapper by using 'solver'._parent_process_info[KM.TIME]. This way will be deliver in the Flux solver_wrapper (delivered in Flux setup). Can you commit your modification in the main branch of Kratos ?

**Review by philbucher — APPROVED** [review]

**Comment by philbucher** [comment]
> Can you commit your modification in the main branch of Kratos ?

yes, will happen automatically as soon as the pipelines passed

**Pull request merged**
