### PR TITLE
[StructuralMechanicsApp] Repairing SpectralDecomposition

### LINKED ISSUE #4528: [StructuralMechanicsApplication] SpectralDecomposition and GaussSeidelEigenSystem Unexpected Results
Could it be that in constitutive_law_utilities -> SpectralDecomposition the eigenvectors and eigenvalues called from GaussSeidelEigenSystem in the math_utils.h come switched? So that the first entry of the eigen_values_matrix does not refer to the first entry of the eigen_vector_matrix.
eigen_values_matrix(0,0) has not eigen_vectors_matrix(0) as its corresponding eigenvector. 
I am having some issues with that sice I am using SpectralDecomposition for my d+d- damage law  for masonry.
@AlejandroCornejo told me to tag @marandra 
Thanks,
Philip

### PR DESCRIPTION
**Pull request by philipkalkbrenner**
There has been an index error in the function SpectralDecomposition. Fixes #4528

### CODE REVIEW

**Review by RiccardoRossi — COMMENTED** [review]
@marandra this is on you right?

i mean, the change was deliberate ?

**Review by loumalouomega — CHANGES_REQUESTED** [review]
I am quite sure this has been extensively tested, where is the problem?

**Comment by philipkalkbrenner** [comment]
@loumalouomega we discussed this some time ago in issue #4528

**Comment by loumalouomega** [comment]
> @loumalouomega we discussed this some time ago in issue #4528

You need to refer the original issue, sorry

**Review by loumalouomega — APPROVED** [review]
Release of my block

**Review by AlejandroCornejo — DISMISSED** [review]
My CL are okkey with this change

**Comment by marandra** [comment]
No conflicts from my side. Our CL (Traction-only damage) does not use SpectralDecomposition, only the eigensystem from math_utils.

The original issue was with the eigensystem returned by math_utils, where eigenvectors where transposed with respect to literature and other programs (e.g. numpy, matlab).

**Review by philbucher — CHANGES_REQUESTED** [review]
Why do you comment tests?

**Comment by loumalouomega** [comment]
> Why do you comment tests?

True, I though it was a whitespace

**Review by loumalouomega — CHANGES_REQUESTED** [review]
Decomment tests

**Comment by loumalouomega** [comment]
Update the values if they were wrong

**Comment by philipkalkbrenner** [comment]
I will decomment the tests!

**Comment by loumalouomega** [comment]
> I will decomment the tests!

But check that still work, and if doesn't update the values

**Comment by philipkalkbrenner** [comment]
Tests have been decommented and I put new values that work

**Review by philbucher — APPROVED** [review]

**Review by loumalouomega — APPROVED** [review]

**Pull request merged**
