### PR TITLE
[Core] Unifiyng all the cpp test on the core under KratosCoreFastSuite

### PR DESCRIPTION
**Pull request by loumalouomega**

### CODE REVIEW

**Comment by loumalouomega** [comment]
Also removing Test at the beginning of the test name to avoid TestTest

**Review by RiccardoRossi — COMMENTED** [review]
why do we need to unify this?

**Comment by RiccardoRossi** [comment]
I mean, it would not be a bad feature that they are in different suites, as long as they are always run bt the run_tests.py

**Comment by loumalouomega** [comment]
I think that for consistency with the applications should be moved to one
unified suite.

**Comment by loumalouomega** [comment]
Right now all the tests, except the ones I did are on the same suite. It's my fault

**Comment by pooyan-dadvand** [comment]
If they are fast (milliseconds < a second) I would put them in the fast suite

**Comment by loumalouomega** [comment]
All of them are fast

**Comment by RiccardoRossi** [comment]
not a fastpr

**Comment by loumalouomega** [comment]
OK, now only affects to my own tests and just changes the name. These are my tests and is my decision to change the name

**Review by RiccardoRossi — APPROVED** [review]

**Pull request merged**
