### PR TITLE
Poromechanics main python script rewritten as a class

### PR DESCRIPTION
**Pull request by ipouplana**
Essentially, the main python script is now a class derived from AnalysisStage

### CODE REVIEW

**Comment by philbucher** [comment]
Nice addition @ipouplana 

Note that I am abt to do some improvements to the AnalysisStage to further converge things in the BaseClass
I will do this by the beginning of next week latest

**Comment by ipouplana** [comment]
Ok @philbucher, then maybe it is better that I wait to your improvements before merging this PR

**Comment by philbucher** [comment]
@ipouplana if you merge the master then I can properly review this
Currently it shows some "old" changes

**Comment by ipouplana** [comment]
Thanks @philbucher .

Yes, I still need to merge the master branch into this one and adapt some methods... I'll try to do it this weekend, but I'm not sure if I'll have time... When I am done I will tell you so that you can review this PR.

Regards

**Comment by ipouplana** [comment]
I'll close this PR and delete the branch because there are some strange changes in the tetgen module that I don't want to merge... 
I just created another branch with my actual changes (feature-poro-analysis) and when I finish the work on that branch I'll open a new PR and let you know @philbucher

**Pull request closed without merging**
