### PR TITLE
Fixing multiple phantoms error measurements

### PR DESCRIPTION
**Pull request by jgonzalezusua**
**Description**
This PR is aimed to fix a problem with the facewatchers' measurements when multiple phantoms are used in the `SwimmingDEMApplication`. The `analytic_data_procedures.py` has been updated to fix with the new requirements of the h5py 3.0.0 version.

Please mark the PR with appropriate tags: 
- Enhancement
- Bugfix

**Changelog**
- Modification of the RunAnalytics function in `DEM_analysis_stage.py`
- Update `analytic_data_procedures.py`

### CODE REVIEW

**Comment by jgonzalezusua** [comment]
In my machine the tests run OK, but in a local branch. We have to wait to see if the tests in remote run as expected.

**Comment by jgonzalezusua** [comment]
These changes are provisional, I will make some modifications in the scripts to optimize the writing process

**Comment by jgonzalezusua** [comment]
There is a problem with the import of h5py in windows

**Comment by maceligueta** [comment]
This can be discussed, but we could install h5py in the windows CI:
https://github.com/KratosMultiphysics/Kratos/blob/0951944c3c4b3f981078314c275531a5abeeb3b4/.github/workflows/ci.yml#L149
adding h5py at the end of that line. @roigcarlo 
I don't really know why it is not failing in linux, it must be preinstalled somehow.

**Comment by jgonzalezusua** [comment]
I do not know how these imports were implemented before. They were in master before I open this branch

**Comment by jgonzalezusua** [comment]
So, can h5py be installed in windows? 
@roigcarlo

**Comment by roigcarlo** [comment]
No problem from my side :+1: . Btw linux version works because it was a req for the HDF5 application, which is only tested there.

**Comment by philbucher** [comment]
note that if you use non-standard python modules the tests should have `skipTest` otherwise they fail if the module is not available

**Comment by jgonzalezusua** [comment]
I will wait until the committee agrees with the changes in the` ci.yml`.
Ping @KratosMultiphysics/technical-committee

**Comment by maceligueta** [comment]
> note that if you use non-standard python modules the tests should have `skipTest` otherwise they fail if the module is not available

Do you mean in local machines of other developers?

**Comment by jgonzalezusua** [comment]
> > > note that if you use non-standard python modules the tests should have `skipTest` otherwise they fail if the module is not available
> > 
> > 
> > Do you mean in local machines of other developers?
> 
> for example

Do you agree with the change in the ci, @philbucher?

**Comment by philbucher** [comment]
> > > > note that if you use non-standard python modules the tests should have `skipTest` otherwise they fail if the module is not available
> > > 
> > > 
> > > Do you mean in local machines of other developers?
> > 
> > 
> > for example
> 
> Do you agree with the change in the ci, @philbucher?

Yes

**Review by maceligueta — APPROVED** [review]

**Comment by maceligueta** [comment]
That cleanup of the Analytic watcher was very necessary, though we had not noticed before. Thanks @jgonzalezusua !!

**Pull request merged**
