### PR TITLE
[ConstitutiveLaws] Continue transition of cpp tests from SMA

### PR DESCRIPTION
**Pull request by marandra**
**Description**
Enable cpp tests in CLA

**Changelog**
- Add python script for running cpp tests
- Fix includes
- Uncomment sources in CMakeLists 
- Register tests to ConstitutiveLawsFastSuite

### CODE REVIEW

**Review by philbucher — DISMISSED** [review]
👍 thx

**Comment by marandra** [comment]
There are some failing tests though, @AlejandroCornejo is looking into it

**Comment by AlejandroCornejo** [comment]
> 
> 
> There are some failing tests though, @AlejandroCornejo is looking into it

I'll check it as soon as the compilation is Win is working again :) (see https://github.com/KratosMultiphysics/Kratos/pull/8669)

**Comment by AlejandroCornejo** [comment]
Today I'm solving this

**Comment by marandra** [comment]
Compilation is failing in Windows, but passing in Linux (tests are expected to fail for now).
Any idea @roigcarlo or @philbucher ?

**Comment by philbucher** [comment]
now should workl

**Comment by marandra** [comment]
Thanks @philbucher !

**Comment by AlejandroCornejo** [comment]
Now should be fine @marandra

**Comment by AlejandroCornejo** [comment]
BTW, It has **quadratic** convergence ;) @marandra

**Comment by marandra** [comment]
Thanks @AlejandroCornejo . All seems ready. Someone approve please?

**Review by AlejandroCornejo — APPROVED** [review]

**Pull request merged**
