### PR TITLE
disable C++ non-standard compiler specific extensions

### PR DESCRIPTION
**Pull request by philbucher**
**📝 Description**
Wanted to do this for a while, this should help with portability

### CODE REVIEW

**Comment by RiccardoRossi** [comment]
i am not really positive about deactivating it by default...let s.doscuss it in tje next TC meeting

**Comment by RiccardoRossi** [comment]
i am not really positive about deactivating it by default...let s.doscuss it in tje next TC meeting

**Comment by RiccardoRossi** [comment]
in essence i would make it very clear how to deactivate them...bit i would not change the default...

**Comment by philbucher** [comment]
I am not sure I follow

Why would you allow them in the first place? I.e. it is frustrating to develop only to realize when CI is not passing that some compiler extensions were unknowingly used :thinking: 

Or even worse, some extensions are used that are not caught by the CI, but then it fails on the cluster that has an other/older toolchain

**Comment by RiccardoRossi** [comment]
it looks like i posted in the wrong pr.

i am not positove about tests being turned off in release

**Comment by philbucher** [comment]
So do you agree with this PR then?

**Review by loumalouomega — COMMENTED** [review]
I agree

**Review by RiccardoRossi — APPROVED** [review]
@KratosMultiphysics/technical-committee i am approving since i think we all agree about this.

@philbucher please wait until tomorrow night to merge it in case someone in @KratosMultiphysics/technical-committee wants to rise a last minute red flag

**Comment by RiccardoRossi** [comment]
we spoke about in @KratosMultiphysics/technical-committee and we are all positive, so please go ahead with the merging

**Pull request merged**
