### PR TITLE
[ParticleMechanics] Remove jacobian storage from MP element

### PR DESCRIPTION
**Pull request by bodhinandach**
I am removing the variables to store jacobian in MP element as it is not needed for integration purpose. I am not sure why it is there, as they are quite expensive memory wise. Including its initial condition, inverse, and determinant, there are a lot of memory being wasted. 
Maybe @iiaconeta can ellaborate this? All tests are running okay, btw.

### CODE REVIEW

**Comment by bodhinandach** [comment]
ping @antonialarese @iiaconeta

**Review by loumalouomega — APPROVED** [review]
Ok for me

**Review by antonialarese — APPROVED** [review]
Fine for me. Not sure why these function were needed. Please, ask Ilaria (not through GitHub) just to be sure.

**Comment by bodhinandach** [comment]
@antonialarese Will confirm with her tomorrow. We'll have a skype meeting.

**Pull request merged**
