### PR TITLE
[Core] Properties: printing the ofstream operator

### PR DESCRIPTION
**Pull request by philbucher**
output currently when printing properties:
`Properties`

after (e.g.):
~~~
Properties
    CONSTITUTIVE_LAW : 0x1db1ab0
    YOUNG_MODULUS : 1e+10
    TORSIONAL_INERTIA : 1e+06
    POISSON_RATIO : 0.29
    I33 : 1e+06
    I22 : 1e+06
    DENSITY : 0
    CROSS_AREA : 1
This properties contains 0 tables
~~~

@KratosMultiphysics/technical-committee I checked other classes, often only `Info` is printed, which in many cases only prints the name of the object
think it would be a good idea to apply the change of this PR (taken originally from `ModelPart`) also to other classes, e.g. `ProcessInfo`

### CODE REVIEW

**Comment by josep-m-carbonell** [comment]
Why you don't want to print the properties?

**Comment by philbucher** [comment]
@josep-m-carbonell 
I think you mean:
`print(props)` => this is actually what I would like to do

Currently this only prints `Properties`, but I think it makes more sense to have the same printed as in C, which is what I am proposing in this PR

**Comment by philbucher** [comment]
ping

**Comment by maceligueta** [comment]
I think this should work like you are proposing. However, I wonder whether the string should be returned by the Properties class instead of doing all the work in the python interface.

**Comment by pooyan-dadvand** [comment]
hmmmm, 

This is something which is lost in migration to Pybind.... originally the boost::python interface used to use the stream operator<< to print which in most cases is printing info() and then data(). The original idea behind these two methods was to info to give a very brief information about the class and data to print its state. 

I think that the solution of @philbucher is the less intrusive one.

**Review by RiccardoRossi — DISMISSED** [review]
+1 for this change. Actually i think that we shall do something equivalent essentially in all of the python interface. I should have done this when porting to pybind... but i thought that the ::info was the correct way.

maybe we could ask at pybind forum what is the reccomended way of replicating str(self)

**Comment by philbucher** [comment]
@RiccardoRossi I just asked in the chatroom of pybind, then I saw that you asked the exact same question five days ago :D

Outcome for everyone else:
There is no equivalent to `self_ns::str(self)` from boost, so what we use seems to be the way to go

**Comment by philbucher** [comment]
@KratosMultiphysics/technical-committee after getting the answer from the PyBind-guys, I created a macro for exposing the `<<` operator, with this solution the printing of objects is the same in C++ as well as in Python.

Please have a look, my idea is to use this also for the other classes that were working with boost

**Comment by philbucher** [comment]
@KratosMultiphysics/technical-committee this is ready to be reviewed
Thanks to @jcotela the changes needed are minimal, so now we can get the same printing-behavior of objects in C++ and in Python

**Comment by jcotela** [comment]
I'll refrain from approving because I made one of the commits, but I think this is ready for merging. We need to start using it more often, too.

**Comment by philbucher** [comment]
@jcotela my intention is to use this also for other classes once this is merged

**Comment by philbucher** [comment]
someone?
@KratosMultiphysics/technical-committee

**Review by pooyan-dadvand — COMMENTED** [review]
I would not define the whole line as macro as it reduces the readability. I would put only the lambda function in a macro so the `.def("__str__",`  would be visible in python interfaces

**Comment by philbucher** [comment]
Good suggestion @pooyan-dadvand , will change it
Thanks

**Comment by philbucher** [comment]
@pooyan-dadvand done

**Review by pooyan-dadvand — APPROVED** [review]
Thanks! 👍

**Comment by philbucher** [comment]
thanks

**Pull request merged**
