### PR TITLE
[Core][CI] Activating MMG

### PR DESCRIPTION
**Pull request by loumalouomega**
Basically that, let's see if works

### CODE REVIEW

**Comment by philbucher** [comment]
only minor warnings being turned into errors otherwise seems to work :+1:

**Comment by loumalouomega** [comment]
> 
> 
> only minor warnings being turned into errors otherwise seems to work 👍

Yep, I see

**Comment by loumalouomega** [comment]
> 
> 
> only minor warnings being turned into errors otherwise seems to work 👍

Looks like we need to compile the shared version (*.so) instead of the static ones (*.a)

**Comment by oberbichler** [comment]
Docker build is running...

After that the following files are available:
```
/usr/local/bin/mmg2d_O3
/usr/local/bin/mmg3d_O3
/usr/local/bin/mmgs_O3
/usr/local/include/mmg/libmmg.h
/usr/local/include/mmg/libmmgf.h
/usr/local/include/mmg/mmg2d/libmmg2d.h
/usr/local/include/mmg/mmg2d/libmmg2d.h
/usr/local/include/mmg/mmg2d/libmmg2df.h
/usr/local/include/mmg/mmg2d/libmmg2df.h
/usr/local/include/mmg/mmg2d/libmmgtypes.h
/usr/local/include/mmg/mmg2d/libmmgtypes.h
/usr/local/include/mmg/mmg2d/libmmgtypesf.h
/usr/local/include/mmg/mmg2d/libmmgtypesf.h
/usr/local/include/mmg/mmg3d/libmmg3d.h
/usr/local/include/mmg/mmg3d/libmmg3d.h
/usr/local/include/mmg/mmg3d/libmmg3df.h
/usr/local/include/mmg/mmg3d/libmmg3df.h
/usr/local/include/mmg/mmg3d/libmmgtypes.h
/usr/local/include/mmg/mmg3d/libmmgtypes.h
/usr/local/include/mmg/mmg3d/libmmgtypesf.h
/usr/local/include/mmg/mmg3d/libmmgtypesf.h
/usr/local/include/mmg/mmgs/libmmgs.h
/usr/local/include/mmg/mmgs/libmmgs.h
/usr/local/include/mmg/mmgs/libmmgsf.h
/usr/local/include/mmg/mmgs/libmmgsf.h
/usr/local/include/mmg/mmgs/libmmgtypes.h
/usr/local/include/mmg/mmgs/libmmgtypes.h
/usr/local/include/mmg/mmgs/libmmgtypesf.h
/usr/local/include/mmg/mmgs/libmmgtypesf.h
/usr/local/lib/libmmg.a
/usr/local/lib/libmmg.so
/usr/local/lib/libmmg2d.a
/usr/local/lib/libmmg2d.so
/usr/local/lib/libmmg3d.a
/usr/local/lib/libmmg3d.so
/usr/local/lib/libmmgs.a
/usr/local/lib/libmmgs.so
```

**Comment by loumalouomega** [comment]
> 
> 
> Docker build is running...
> 
> After that the following files are available:
> 
> ```
> /usr/local/bin/mmg2d_O3
> /usr/local/bin/mmg3d_O3
> /usr/local/bin/mmgs_O3
> /usr/local/include/mmg/libmmg.h
> /usr/local/include/mmg/libmmgf.h
> /usr/local/include/mmg/mmg2d/libmmg2d.h
> /usr/local/include/mmg/mmg2d/libmmg2d.h
> /usr/local/include/mmg/mmg2d/libmmg2df.h
> /usr/local/include/mmg/mmg2d/libmmg2df.h
> /usr/local/include/mmg/mmg2d/libmmgtypes.h
> /usr/local/include/mmg/mmg2d/libmmgtypes.h
> /usr/local/include/mmg/mmg2d/libmmgtypesf.h
> /usr/local/include/mmg/mmg2d/libmmgtypesf.h
> /usr/local/include/mmg/mmg3d/libmmg3d.h
> /usr/local/include/mmg/mmg3d/libmmg3d.h
> /usr/local/include/mmg/mmg3d/libmmg3df.h
> /usr/local/include/mmg/mmg3d/libmmg3df.h
> /usr/local/include/mmg/mmg3d/libmmgtypes.h
> /usr/local/include/mmg/mmg3d/libmmgtypes.h
> /usr/local/include/mmg/mmg3d/libmmgtypesf.h
> /usr/local/include/mmg/mmg3d/libmmgtypesf.h
> /usr/local/include/mmg/mmgs/libmmgs.h
> /usr/local/include/mmg/mmgs/libmmgs.h
> /usr/local/include/mmg/mmgs/libmmgsf.h
> /usr/local/include/mmg/mmgs/libmmgsf.h
> /usr/local/include/mmg/mmgs/libmmgtypes.h
> /usr/local/include/mmg/mmgs/libmmgtypes.h
> /usr/local/include/mmg/mmgs/libmmgtypesf.h
> /usr/local/include/mmg/mmgs/libmmgtypesf.h
> /usr/local/lib/libmmg.a
> /usr/local/lib/libmmg.so
> /usr/local/lib/libmmg2d.a
> /usr/local/lib/libmmg2d.so
> /usr/local/lib/libmmg3d.a
> /usr/local/lib/libmmg3d.so
> /usr/local/lib/libmmgs.a
> /usr/local/lib/libmmgs.so
> ```

Ok, let's try now, I thougth we only had the static ones

**Comment by oberbichler** [comment]
One minute age that was also true :)

**Comment by oberbichler** [comment]
I think you were faster then docker. In case that the current build fails we should start it again in order to be sure that the current image is used.

**Comment by loumalouomega** [comment]
> 
> 
> I think you were faster then docker. In case that the current build fails we should start it again in order to be sure that the current image is used.

Now it works :)

**Comment by philbucher** [comment]
~~~
Running tests for MeshingApplication
.......
  ## Warning: MMG5_surf: at least 1 negative or null density.
..
----------------------------------------------------------------------
Ran 9 tests in 30.410s
~~~

lets see what the nightly does

**Review by philbucher — APPROVED** [review]
:+1:

**Comment by philbucher** [comment]
@loumalouomega can you please take a look at the tests that fail in nightly?
~~~
 Running tests for ContactStructuralMechanicsApplication
 ................................................................................F....F
 ======================================================================
 FAIL: test_execution (NightlyTests.BeamAxilContactTest)
 ----------------------------------------------------------------------
 Traceback (most recent call last):
   File "/__w/Kratos/Kratos/bin/Custom/applications/ContactStructuralMechanicsApplication/tests/contact_structural_mechanics_test_factory.py", line 78, in test_execution
     self.test.RunSolutionLoop()
   File "/__w/Kratos/Kratos/bin/Custom/KratosMultiphysics/analysis_stage.py", line 69, in RunSolutionLoop
     self.FinalizeSolutionStep()
   File "/__w/Kratos/Kratos/bin/Custom/KratosMultiphysics/analysis_stage.py", line 145, in FinalizeSolutionStep
     process.ExecuteFinalizeSolutionStep()
   File "/__w/Kratos/Kratos/bin/Custom/KratosMultiphysics/from_json_check_result_process.py", line 141, in ExecuteFinalizeSolutionStep
     self.__check_values(node.Id, "Node", value[component_index], value_json, variable_name+component)
   File "/__w/Kratos/Kratos/bin/Custom/KratosMultiphysics/from_json_check_result_process.py", line 262, in __check_values
     self.assertTrue(isclosethis, msg=msg)
 AssertionError: False is not true : Error checking Node #1001 for variable REACTION_X results:
 502134.129950 != 441099.286656; rel_tol=0.00001, abs_tol=0.001
 
 ======================================================================
 FAIL: test_execution (NightlyTests.PlateTest)
 ----------------------------------------------------------------------
 Traceback (most recent call last):
   File "/__w/Kratos/Kratos/bin/Custom/applications/ContactStructuralMechanicsApplication/tests/contact_structural_mechanics_test_factory.py", line 78, in test_execution
     self.test.RunSolutionLoop()
   File "/__w/Kratos/Kratos/bin/Custom/KratosMultiphysics/analysis_stage.py", line 69, in RunSolutionLoop
     self.FinalizeSolutionStep()
   File "/__w/Kratos/Kratos/bin/Custom/KratosMultiphysics/analysis_stage.py", line 145, in FinalizeSolutionStep
     process.ExecuteFinalizeSolutionStep()
   File "/__w/Kratos/Kratos/bin/Custom/KratosMultiphysics/from_json_check_result_process.py", line 134, in ExecuteFinalizeSolutionStep
     self.__check_values(node.Id, "Node", value, value_json, variable_name)
   File "/__w/Kratos/Kratos/bin/Custom/KratosMultiphysics/from_json_check_result_process.py", line 262, in __check_values
     self.assertTrue(isclosethis, msg=msg)
 AssertionError: False is not true : Error checking Node #1159 for variable DISPLACEMENT_X results:
 0.0000000 != 0.0013110; rel_tol=0.000001, abs_tol=0.001
 ~~~

**Comment by loumalouomega** [comment]
> @loumalouomega can you please take a look at the tests that fail in nightly?
> 
> ```
>  Running tests for ContactStructuralMechanicsApplication
>  ................................................................................F....F
>  ======================================================================
>  FAIL: test_execution (NightlyTests.BeamAxilContactTest)
>  ----------------------------------------------------------------------
>  Traceback (most recent call last):
>    File "/__w/Kratos/Kratos/bin/Custom/applications/ContactStructuralMechanicsApplication/tests/contact_structural_mechanics_test_factory.py", line 78, in test_execution
>      self.test.RunSolutionLoop()
>    File "/__w/Kratos/Kratos/bin/Custom/KratosMultiphysics/analysis_stage.py", line 69, in RunSolutionLoop
>      self.FinalizeSolutionStep()
>    File "/__w/Kratos/Kratos/bin/Custom/KratosMultiphysics/analysis_stage.py", line 145, in FinalizeSolutionStep
>      process.ExecuteFinalizeSolutionStep()
>    File "/__w/Kratos/Kratos/bin/Custom/KratosMultiphysics/from_json_check_result_process.py", line 141, in ExecuteFinalizeSolutionStep
>      self.__check_values(node.Id, "Node", value[component_index], value_json, variable_name+component)
>    File "/__w/Kratos/Kratos/bin/Custom/KratosMultiphysics/from_json_check_result_process.py", line 262, in __check_values
>      self.assertTrue(isclosethis, msg=msg)
>  AssertionError: False is not true : Error checking Node #1001 for variable REACTION_X results:
>  502134.129950 != 441099.286656; rel_tol=0.00001, abs_tol=0.001
>  
>  ======================================================================
>  FAIL: test_execution (NightlyTests.PlateTest)
>  ----------------------------------------------------------------------
>  Traceback (most recent call last):
>    File "/__w/Kratos/Kratos/bin/Custom/applications/ContactStructuralMechanicsApplication/tests/contact_structural_mechanics_test_factory.py", line 78, in test_execution
>      self.test.RunSolutionLoop()
>    File "/__w/Kratos/Kratos/bin/Custom/KratosMultiphysics/analysis_stage.py", line 69, in RunSolutionLoop
>      self.FinalizeSolutionStep()
>    File "/__w/Kratos/Kratos/bin/Custom/KratosMultiphysics/analysis_stage.py", line 145, in FinalizeSolutionStep
>      process.ExecuteFinalizeSolutionStep()
>    File "/__w/Kratos/Kratos/bin/Custom/KratosMultiphysics/from_json_check_result_process.py", line 134, in ExecuteFinalizeSolutionStep
>      self.__check_values(node.Id, "Node", value, value_json, variable_name)
>    File "/__w/Kratos/Kratos/bin/Custom/KratosMultiphysics/from_json_check_result_process.py", line 262, in __check_values
>      self.assertTrue(isclosethis, msg=msg)
>  AssertionError: False is not true : Error checking Node #1159 for variable DISPLACEMENT_X results:
>  0.0000000 != 0.0013110; rel_tol=0.000001, abs_tol=0.001
> ```

I know, but those test only fail in machines different to mine, I don¡t know how to debug them. there is a way to debug using a docker?

**Comment by philbucher** [comment]
> I know, but those test only fail in machines different to mine, I don¡t know how to debug them. there is a way to debug using a docker?

Yes you can get the image locally (`docker pull oberbichler/kratos-dev:latest` I think)
Then you can do anything with it

I had a similar problem, I also got the image locally, started it and then inside of it I could check what is happening
=> this is done with `docker run -i` I think, might be that you need another flag
For my case (not Kratos) I used this command: `docker run -v `pwd`:`pwd` -w `pwd` -i -t philbucher/dummy /bin/bash`

@marcnunezc I think you also used docker locally right? How did you run it? Thx

**Comment by marcnunezc** [comment]
Hi!

I was using a modified version of the Dockerfile from oberbichler/kratos-dev:latest where I include the [environtmental variables that we add in Kratos CI](https://github.com/KratosMultiphysics/Kratos/blob/ef87296232d7ead2f296dd786689cd021fa48625/.github/workflows/ci.yml#L43-L50). 


[Dockerfile.zip](https://github.com/KratosMultiphysics/Kratos/files/4158146/Dockerfile.zip)


Then I build the docker container in the path where I have the Dockerfile with:

`
docker build .  -t your-tag`

Once it's built, you can run the container with:

`
docker run -it your-tag`

Then I manually clone the Kratos repo and compile Kratos.

**Pull request merged**
