### PR TITLE
[CI] compiling  apps used in altair in centos7

### PR DESCRIPTION
**Pull request by ddiezrod**
The apps used in altair side are now compiled in CI in centos 7. Fingers crossed.

### CODE REVIEW

**Comment by philbucher** [comment]
@ddiezrod since the centos compilation will use its own configure, can you please rename it to `configure_centos.sh`? Thx

**Comment by philbucher** [comment]
ping @ddiezrod

**Comment by ddiezrod** [comment]
@philbucher I didnt for get it ;) I just need some time to see why we are getting this error

**Comment by ddiezrod** [comment]
CI should pass now @philbucher

**Review by philbucher — APPROVED** [review]
:+1:

**Pull request merged**
