### PR TITLE
[StructuralMechanicsApplication] added rot DOFS to 3D base load condition

### PR DESCRIPTION
**Pull request by aronnoordam**
rotation DOFS are now added to the base_load_condition in 3D

### CODE REVIEW

**Comment by philbucher** [comment]
can you please explain why this change is needed and what it is used for?

**Comment by aronnoordam** [comment]
It is needed for an upcoming update in the moving load, where I want the displacement and rotation at the location of the moving load. Where the calculation of the rotation and displacement is different in case rotation DOFS are active

**Comment by philbucher** [comment]
Ok for me

@loumalouomega please approve if you agree

**Review by loumalouomega — APPROVED** [review]

**Comment by loumalouomega** [comment]
I agree

**Comment by aronnoordam** [comment]
thanks

**Pull request merged**
