### PR TITLE
Activating swimming dem

### PR DESCRIPTION
**Pull request by roigcarlo**
Now its active

### CODE REVIEW

**Review by maceligueta — DISMISSED** [review]

**Comment by roigcarlo** [comment]
@maceligueta , @GuillermoCasas 

The bulk of the changes to make it compile in win again is done.

I was unable no matter what I tried to make the variables exportable to python, provided that the mechanism work in other applications I suspect that there is something weird going on here, but I don't know the application well enough to identify where ( I suspect the problem may come due to wring include orders/cycles). Could you check that?

**Comment by maceligueta** [comment]
As far as I see on Appveyor, only two variables are affected: SCALAR_ERROR and AVERAGED_FLUID_VELOCITY. I will take a look at them tomorrow. Thanks @roigcarlo !!

**Comment by GuillermoCasas** [comment]
Thank you, @roigcarlo and @maceligueta. I do not know what is wrong with these variables, we can discuss it today, Miguel Ángel.

**Review by maceligueta — APPROVED** [review]

**Comment by maceligueta** [comment]
Though I took part in the commits, my part was minor. That's why I approved. @roigcarlo , if you want to wait for @GuillermoCasas ' approval, that's fine, too.

**Comment by roigcarlo** [comment]
Np, fine to me, merging

**Comment by philbucher** [comment]
is this branch still needed?

**Comment by maceligueta** [comment]
Deleted!

**Pull request merged**
