### PR TITLE
Adding appveyor submodules

### PR DESCRIPTION
**Pull request by roigcarlo**
This is for testing.

### CODE REVIEW

**Comment by philbucher** [comment]
I thought the plan was to not use submodule? => #2651

**Comment by roigcarlo** [comment]
No no, this is a different sort of problem. The submodule is already there, but we cannot use it in appveyor as a submodule because I get the repo as a bundle, not with the git command.

**Comment by philbucher** [comment]
I though the submodule should be removed, then you would not have to go through the struggle of adding it

**Comment by roigcarlo** [comment]
Ideally yes, I would like to remove all submodules but as you mark in #2651 we state the necessity of that library being in a submodule, and I can't remember any plan to remove it as for now. In any case that would be decision of @josep-m-carbonell.

That being said, the fact that tetgen is in a submodule or as a external library does not affect the fact that I have to download it from some place to fulfill the dependency. In this case it is more convenient to use the submodule repo as the origin for the dependency, but we could download it from the official repo as well (but then we have to select the correct version blah blah...).

Also if I make this work we may try to add dependencies for other applications (Eigensolver, etc...)

**Comment by roigcarlo** [comment]
@josep-m-carbonell Tetgen is included now and it compiles, but I use some special compilation flags in appveyor in order to speed it up and it seems that is producing some conflicts with the tetgen cmake.

May I add a custom build mode for tetgen to bypass this? Probably I only have to add a flag to override the optimization level.

**Comment by josep-m-carbonell** [comment]
Thank you Carles. Yes, it is important to compile it with the correct optimization level.

**Comment by roigcarlo** [comment]
Well now it passes. If you like the solution we can merge.

**Review by maceligueta — APPROVED** [review]

**Pull request merged**
