### PR TITLE
Cleaning MMg test after example migration

### PR DESCRIPTION
**Pull request by loumalouomega**

### CODE REVIEW

**Comment by loumalouomega** [comment]
The tests are now here https://github.com/KratosMultiphysics/Examples/tree/master/mmg_remeshing_examples

**Review by pooyan-dadvand — CHANGES_REQUESTED** [review]
There are 94 files changed many of them in other applications. (like @KratosMultiphysics/dem )

@loumalouomega Are you sure this PR is correct?

**Comment by loumalouomega** [comment]
Huuum, probably the PR mesh up again with the @KratosMultiphysics/dem  for some reason. I can clean the thing easily, one moment

**Comment by loumalouomega** [comment]
Merging with the master solved the problem
imagen

**Comment by pooyan-dadvand** [comment]
strange.... let's get som from @KratosMultiphysics/dem team.

**Comment by loumalouomega** [comment]
Probably was some mistake with the Gitkraken, some times it doesn't merge, but instead it does a commit with all the changes in the master. Look the message of the commit 54c03fa it says "Merge master", but in the 94e6846 says "Merge branch 'master' into feature-cleaning-moved-tests-MMG"

**Comment by loumalouomega** [comment]
PING

**Review by pooyan-dadvand — APPROVED** [review]
:+1:

**Pull request merged**
