### PR TITLE
[MeshingApplication] Adapting MmgProcess to be able to remesh prisms

### PR DESCRIPTION
**Pull request by loumalouomega**
This refactor allows two things:

- To remesh prisms elements collapsing them as triangles, re-meshing with MMGS, and then extruding again.
- In order to make so I needed to do some refactoring, now the MmgProcess can remesh meshes with entities that is not able to remesh, they just will be not considered (previously an error was thrown). With this is possible to consider for example meshes that combines hexahedron and tetrahedron, without error.

To make this possible, the flags OLD_ENTITY and NEW_ENTITY are considered

A test is added

Includes #5143

### CODE REVIEW

**Comment by loumalouomega** [comment]
Includes #5143

**Review by AlejandroCornejo — APPROVED** [review]
I suppose that all the test are ok

**Comment by loumalouomega** [comment]
I will wait until #5143 is approved

**Comment by loumalouomega** [comment]
Thanks

**Pull request merged**
