### PR TITLE
[MPM][To discuss not to merge] Using Quadrature Points

### PR DESCRIPTION
**Pull request by tteschemacher**
Hi,
I am adding here a first draft to discuss how the integration of quadrature points can look like for the mpm. Not able to run yet.

### CODE REVIEW

**Review by antonialarese — COMMENTED** [review]
@tteschemacher can we have a brief talk on these pull requests? It is a huge change, I do not want to loose something. Are you thinking of discussing it in the next meeting? Or maybe before?

**Comment by tteschemacher** [comment]
Yes, of course. This PR needs to be discussed in detail. There are also some issues which will need the agreement of the mpm team.

This PR is still in draft and I need to do some more modifications, but maybe it's a good moment to start taking about it.

It's depending on some other PRs so it ll get smaller as well.

**Comment by antonialarese** [comment]
OK, great

**Comment by tteschemacher** [comment]
I am closing this PR as we did this change already within others.

**Pull request closed without merging**
