### PR TITLE
Disabling pip modules for numpy and hdf5

### PR DESCRIPTION
**Pull request by roigcarlo**
It just takes too much time. In any case we can enable it later if we find a way to speed up the compilation.

### CODE REVIEW

**Comment by maceligueta** [comment]
I managed to pass the tests adding expected failures and moving 'import h5py' to inner parts of the code... Not very clean.

**Comment by roigcarlo** [comment]
Agree, but if there is no other solution right now we will have to live with it

**Comment by maceligueta** [comment]
do we merge then?

**Comment by roigcarlo** [comment]
Good to me, but I can't approve since I created the PR

**Review by maceligueta — APPROVED** [review]

**Pull request merged**
