### PR TITLE
Memory leak solved for repetitive runs of Kratos cases

### PR DESCRIPTION
**Pull request by maceligueta**
A memory leakage problem was detected and fixed. It was located in the GidPost library, which was not freeing memory, due to a coincidence in function names (hdestroy). The Gid Team is also informed of this.
Other memory leaks were caused by circular references in Python (jus DEM application was checked). Weak references are used to avoid them.

### CODE REVIEW

**Comment by maceligueta** [comment]
@GuillermoCasas : can you check this?

**Review by GuillermoCasas — APPROVED** [review]
Very nice! I am glad we found it. It would have taken me for ever to solve this. now I will check to see it it solves it for swimming_DEM too.

**Comment by roigcarlo** [comment]
We should remove the valgrind outputs before merge

**Comment by pooyan-dadvand** [comment]
Great!!

**Pull request merged**
