### PR TITLE
[CI] Centos - treating warnings as errors

### PR DESCRIPTION
**Pull request by ddiezrod**
We have been treating warnings as errors for a while in our altair CI system, so in order to not include new ones from core we'd like to add this here too, so we don't break anything.

To be discussed with @KratosMultiphysics/technical-committee

### CODE REVIEW

**Review by loumalouomega — DISMISSED** [review]

**Comment by ddiezrod** [comment]
Ok now we see here the same error that @pablobecker was obtaining when trying to merge master. 

```
[ 16%] Building CXX object kratos/CMakeFiles/KratosCore.dir/Unity/unity_8_cxx.cxx.o
In file included from /__w/Kratos/Kratos/kratos/tests/cpp_tests/sources/test_filesystem.cpp:21,
                 from /__w/Kratos/Kratos/build/Custom/kratos/CMakeFiles/KratosCore.dir/Unity/unity_8_cxx.cxx:28:
/__w/Kratos/Kratos/kratos/includes/kratos_filesystem.h:43:76: error: 'deprecated' attribute directive ignored [-Werror=attributes]
 namespace KRATOS_DEPRECATED_MESSAGE("Please use std::filesystem directly") filesystem {
                                                                            ^~~~~~~~~~
cc1plus: all warnings being treated as errors
```

It seems that this error is only fixed in gcc 10 https://gcc.gnu.org/bugzilla/show_bug.cgi?id=79817

Should we skip this warning?

**Comment by loumalouomega** [comment]
> Ok now we see here the same error that @pablobecker was obtaining when trying to merge master.
> 
> ```
> [ 16%] Building CXX object kratos/CMakeFiles/KratosCore.dir/Unity/unity_8_cxx.cxx.o
> In file included from /__w/Kratos/Kratos/kratos/tests/cpp_tests/sources/test_filesystem.cpp:21,
>                  from /__w/Kratos/Kratos/build/Custom/kratos/CMakeFiles/KratosCore.dir/Unity/unity_8_cxx.cxx:28:
> /__w/Kratos/Kratos/kratos/includes/kratos_filesystem.h:43:76: error: 'deprecated' attribute directive ignored [-Werror=attributes]
>  namespace KRATOS_DEPRECATED_MESSAGE("Please use std::filesystem directly") filesystem {
>                                                                             ^~~~~~~~~~
> cc1plus: all warnings being treated as errors
> ```
> 
> It seems that this error is only fixed in gcc 10 [gcc.gnu.org/bugzilla/show_bug.cgi?id=79817](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=79817)
> 
> Should we skip this warning?

image

**Review by philbucher — APPROVED** [review]

**Comment by ddiezrod** [comment]
Thanks a lot @philbucher ! I am not sure why I needed the Wno-maybe-uninitialized in the past because I had some warning coming from FluidDynamicsApp but it seems it is gone now. Merging this!

**Comment by philbucher** [comment]
Happy to help :) 
Feel free to ping me if sth with my developments is bot working 😄

**Pull request merged**
