### PR TITLE
[CI] adding PotentialFlow in Win-CI

### PR DESCRIPTION
**Pull request by philbucher**
**Description**
Seems to be forgotten, it is there in the Linux CI

### CODE REVIEW

**Comment by marcnunezc** [comment]
It fails, it seems a conflict with a common variable in the FluidApp.

**Comment by philbucher** [comment]
it is not in the DEMApp but in the Dem-variables in the Core
if @maceligueta agrees I suggest to move it to the fluid-variables (still in the Core) then you can include it

in any case it appears to be only used once in the DEM app in python hence should be fine

**Comment by maceligueta** [comment]
Go ahead, no problem. Actually, DRAG_COEFFICIENT should not be in the DEM Application either, it should only be in in Swimming DEM App. I will open a new issue as a reminder to clean that up.

**Review by marcnunezc — APPROVED** [review]

**Comment by philbucher** [comment]
Thx @marcnunezc

**Pull request merged**
