### PR TITLE
[Core] Ray Casting - create virtualfunction to set distances

### PR DESCRIPTION
**Pull request by ddiezrod**
As an alternative to https://github.com/KratosMultiphysics/Kratos/pull/10982, here I am just making private functions protected and using a virtual function to set the nodal distances.

The idea is that I will create a class on our side that does what we need: using ray casting, classify nodes as in, out or interface.

### CODE REVIEW

**Review by rubenzorrilla — COMMENTED** [review]
Just pointing that I'm much more in favor of this solution. I think it much clean as it doesn't pollute current implementation and having a new class gives us more flexibility to deal with the eventual corner cases that may appear in your target application.

**Comment by ddiezrod** [comment]
This is fine for me too, shall we merge this?

**Review by pooyan-dadvand — COMMENTED** [review]
Also agree that this is a clean solution! 

But I would make the function more generic by passing the node and the ray_distance, so the derived class can use it to fix the interface nodes or any other operation with node based on its position.

**Comment by ddiezrod** [comment]
I have tried my best do it generic (I think it makes a lot of sense that we only pass the node and the ray distance to a function that can be overrided by other classes) and also more or less efficient, so I had to store the distance_variable and the distance gettter in the class. @pooyan-dadvand @rubenzorrilla

**Review by rubenzorrilla — APPROVED** [review]
This makes perfect sense for me. Thanks @ddiezrod for taking my comments into consideration.

**Pull request merged**
