### PR TITLE
[StructuralMechanicsApplication] Adding test to compare the different models for perfect plasticity

### PR DESCRIPTION
**Pull request by loumalouomega**
Applies a cyclic load (double cyclic in fact). Then compares that the resulting Von Mises stress is the same for the three models.

TODO: Compare tangent matrices

### CODE REVIEW

**Comment by loumalouomega** [comment]
The resulting loading cycle is as follows:

u = t*sin(w*t)*A*X + t*sin(2*w*t)*B*X

With VM:

imagen

**Comment by AlejandroCornejo** [comment]
What do you mean by "three models? thank you

**Comment by philbucher** [comment]
@tteschemacher also had the idea to have a unified testcase for all CLaws

=> we should add this to the list of points to be discussed in our meeting next week

**Comment by philbucher** [comment]
take a look at codacy

**Comment by loumalouomega** [comment]
> What do you mean by "three models? thank you

The ones from @marandra , @frastellini and @AlejandroCornejo (you)

**Comment by loumalouomega** [comment]
> @tteschemacher also had the idea to have a unified testcase for all CLaws
> 
> => we should add this to the list of points to be discussed in our meeting next week

OK

**Comment by loumalouomega** [comment]
> take a look at codacy

I will

**Comment by AlejandroCornejo** [comment]
> 
> 
> > What do you mean by "three models? thank you
> 
> The ones from @marandra , @frastellini and @AlejandroCornejo (you)

aaah okkey thank you

**Comment by loumalouomega** [comment]
Done @philbucher

**Comment by marandra** [comment]
Good idea!

**Comment by loumalouomega** [comment]
Ping

**Comment by AlejandroCornejo** [comment]
the comments have been adressed

**Review by AlejandroCornejo — APPROVED** [review]

**Pull request merged**
