### PR TITLE
Fixing amgcl unpredictability bug

### PR DESCRIPTION
**Pull request by RiccardoRossi**
the title says it all. the pr also cleans up the testing.

I would like to acknowledge that the fix was carried out by @ddemidov in the base amgcl. here i am just bringing Kratos up to speed.

### CODE REVIEW

**Comment by RiccardoRossi** [comment]
ouch! we have a problem, AMGCL now relies on "small_vector.hpp" which was added in boost 1.58.

I will take a look if i can add some sort of define to have a fallback implementation if this is not available

**Comment by ddemidov** [comment]
I could replace `small_vector` with `std::vector` in amgcl implementation. That would cost a dynamic memory allocation on each `inner_product`, but I think it would not be too expensive. This could even be done conditionally, depending on `BOOST_VERSION` macro.

**Comment by RiccardoRossi** [comment]
Hi Denis

Yes I was checking that, however what about using openmp reduce?

Alternatively you could also use a std::array of large size and accumulate
from begin to begin+nthreads. It is a bit ugly but that would work

If you want this evening I can do a PR on the amgcl repo

Cheers
Riccardo

**Comment by philbucher** [comment]
hi @RiccardoRossi can you pls make it compile then I can test it

**Comment by roigcarlo** [comment]
@philbucher We have some problems with this since the current fix requires a file is only available from boost 1.58. I think @RiccardoRossi  is looking for an alternative fix

**Comment by RiccardoRossi** [comment]
@philbucher this should now work

**Comment by philbucher** [comment]
now the test work

**Comment by RiccardoRossi** [comment]
can u approve?

**Review by philbucher — APPROVED** [review]
works for me

**Pull request merged**
