### PR TITLE
[Core] Correcting parameters configure on Residual criteria

### PR DESCRIPTION
**Pull request by loumalouomega**
Wrong order of arguments

### CODE REVIEW

**Review by RiccardoRossi — APPROVED** [review]
I think that this fix is important as short term fix, 
however i also believe that we should employ the classical Validation mechanism and only use
"relative_tolerance" and "absolute_tolerance"

the idea is that if someone wants to do a AndCriteria, he would have to do:

      criteria_type : "AndCriteria",
      first_criteria : {
                     criteria_type : "ResidualCriteria",
                     "relative_tolerance" : 1e-4
             },
      second_criteria : {
                     criteria_type : "DisplacementCriteria",
                     "relative_tolerance" : 1e-6
             }

aside of this **WE HAVE A PROBLEM with ResidualCriteria + MPCs.** If MPCs are used, the residual is not zero within the domain ... which would make this to never converge.
We need to open an issue about this and to find a solution

**Comment by loumalouomega** [comment]
I would add a new method that just adds the missing parameters and doesn't throw an error when something is not the defaults is defined. The reason I did this check it was because the and and or criteria can be used and the check can fail then.

**Comment by loumalouomega** [comment]
Respect the residual with MPC we can discuss it, but I think is as easy as set to zero the rhs component after save the reaction value.

**Comment by RiccardoRossi** [comment]
regarding MPCs , the point is that you do not know in the convergence criterias which dofs are masters or slave.

about the defaults if you define

~~~
{
      "criteria_type" : "name",
      "relative_tolerance" : 1e-6,
      "absolute_tolerance" : 1e-20
}
~~~

i would not add any other criterion for these...

**Comment by loumalouomega** [comment]
> regarding MPCs , the point is that you do not know in the convergence criterias which dofs are masters or slave.
> 

I meant in the builder and solver, when computing the reactions, not in the criteria

**Comment by loumalouomega** [comment]
> about the defaults if you define
> 
> ```
> {
>       "criteria_type" : "name",
>       "relative_tolerance" : 1e-6,
>       "absolute_tolerance" : 1e-20
> }
> ```
> 
> i would not add any other criterion for these...

Again, the problem is how do you combine them with or_criteria or and_criteria.

**Pull request merged**
