### PR TITLE
[ContactStructuralMechanicsApplication] Update app to use #5390…

### PR DESCRIPTION
**Pull request by loumalouomega**

### CODE REVIEW

**Comment by loumalouomega** [comment]
@tteschemacher this replaces  #5399

**Comment by loumalouomega** [comment]
Ping @tteschemacher

**Comment by philbucher** [comment]
he is on holiday next week

**Review by AlejandroCornejo — APPROVED** [review]

**Comment by tteschemacher** [comment]
I think it's a very nice use of the couplinggeomegry. Thanks for adapting!

**Comment by tteschemacher** [comment]
Maybe we can optimize a bit more. I'll have a look when I'm back. But I think it's really cool to have something more from the core!

**Pull request merged**
