### PR TITLE
[Potential Flow] Adding echo level

### PR DESCRIPTION
**Pull request by inigolcanalejo**
**Description**
Adding echo level to control the verbosity of the warnings within the application.

### CODE REVIEW

**Comment by philbucher** [comment]
I like the idea!

**Comment by inigolcanalejo** [comment]
Thanks! I was wondering whether there is a better way of doing this or whether there was already a variable defined at the core that we can use.

**Comment by inigolcanalejo** [comment]
Also I chose to use the same echo level as at the solver. I'm not sure whether it would be better to have an independent one for these warnings like "warnings_echo_level" or it just makes it more complicated adding another echo level more...

**Comment by marcnunezc** [comment]
> I like the idea!

I was expecting a blocker from you 😄 

I also like the idea! 

Maybe this variable could be added in a future PR to the core and make the python_solver.py add it to the ProcessInfo automatically? There are probably more use cases of echo_level that could depend on the solver_settings echo_level.

**Comment by philbucher** [comment]
On problem I see with the Core is that one solver can have multiple ModelParts (any coupled solver). What to do then?

I would merge this and see if we want to unify in the future

**Review by philbucher — APPROVED** [review]

**Comment by inigolcanalejo** [comment]
> On problem I see with the Core is that one solver can have multiple ModelParts (any coupled solver). What to do then?
> 
> I would merge this and see if we want to unify in the future

ok!

**Pull request merged**
