### PR TITLE
Correcting geometry normal

### PR DESCRIPTION
**Pull request by RiccardoRossi**
This branch changes the name of the function 

Normal --> AreaNormal (normal proportional to the area)

and adds a function UnitNormal

the name change is done intentionally since the old function Normal was giving back the unit normal and this was needed to trigger a compiler error.

I made an attempt to compile everything in the public repository but there might be someone using the method in private applications. my suggestion is to keep the method AreaNormal in testing on one own's computer and then prior to merging to replace the AreaNormal method back to Normal which is a better name.

### CODE REVIEW

**Comment by loumalouomega** [comment]
Let me try and I will approve it

**Review by loumalouomega — APPROVED** [review]
It works

**Review by pooyan-dadvand — CHANGES_REQUESTED** [review]
The idea was to turn back the name to Normal after cleaning up the compiler errors. Wasn't it?

**Comment by RiccardoRossi** [comment]
yes, however my exact proposal is to open another issue and to change back AreaNormal->Normal in one month from now.

this way if someone uses it during the next month he will stil get a compiler error

**Review by pooyan-dadvand — APPROVED** [review]
:+1: 

**Important Note** this is the first step for changing Normal behavior. #940 is a reminder for second step

**Pull request merged**
