### PR TITLE
[FastPR][Core] Edges() warnings removal in discontinuous distance

### PR DESCRIPTION
**Pull request by rubenzorrilla**
:top:

### CODE REVIEW

**Comment by philbucher** [comment]
Same comment as in #5295

**Review by loumalouomega — APPROVED** [review]
Travis is failing because (the lack) of this

**Comment by philbucher** [comment]
> Travis is failing because (the lack) of this

Travis fails bcs for some reason it is out of memory

**Comment by loumalouomega** [comment]
OK, I thought it was something related with the fact we wanted to make the
deprecated errors instead of warnings.

**Comment by philbucher** [comment]
> OK, I thought it was something related with the fact we wanted to make the deprecated errors instead of warnings. El mar., 23 jul. 2019 8:14, Philipp Bucher <notifications@github.com> escribió:

This will never be possible ...

**Comment by rubenzorrilla** [comment]
In accordance with what we decided in  #4831 I'm merging this.

**Pull request merged**
