### PR TITLE
[NOT TO MERGE] Fixing weird double free

### PR DESCRIPTION
**Pull request by roigcarlo**

### CODE REVIEW

**Comment by philbucher** [comment]
how did you come up with this?
maybe the FluidDynApp should be imported in the __init__ of the compressibleApp?

**Comment by roigcarlo** [comment]
That could also solve the problem. Sadly not the one we are looking for :(

**Comment by philbucher** [comment]
I mean how did you know it could be related to this?
I couldn't even reproduce the problem

**Comment by roigcarlo** [comment]
Since the error happens at the application exit and commenting everything did not make any difference I remembered that we use to have problems with Trilinos similar to this one. But still not 100% if this is going to solve the issue with the CI.

**Comment by philbucher** [comment]
hm no always the same problem :/

any other idea @roigcarlo ?

**Comment by roigcarlo** [comment]
Not right now. i will keep investigating

**Comment by marcnunezc** [comment]
Hi @roigcarlo @philbucher @inigolcanalejo 

From what I have tested, i have seen that the following combinations produce the error:

- PotentialFlow + Mapping + CoSim
- PotentialFlow + Mapping + Contact
And obviously:
- PotentialFlow + Mapping + Contact + CoSim

Disabling only mapping or only the potential flow seems to work when everything is compiled. If mapping and potential flow are compiled together, it works as long as  CoSim and Contact are not compiled.

**Comment by RiccardoRossi** [comment]
can it be a redefinition of a variable?

i an cc ing charlie since he recently found a problem wjtb that

@croig

**Comment by roigcarlo** [comment]
> can it be a redefinition of a variable?
>
> i an cc ing charlie since he recently found a problem wjtb that
>
> @CRoig

That's not me :)

It may be the case. If so the candidates to cause problems are:
HEAT_CAPACITY_RATIO <-- FluidDynamics
DRAG_COEFFICIENT <-- DEM

**Comment by rubenzorrilla** [comment]
> > can it be a redefinition of a variable?
> > i an cc ing charlie since he recently found a problem wjtb that
> > @CRoig
> 
> That's not me :)
> 
> It may be the case. If so the candidates to cause problems are:
> HEAT_CAPACITY_RATIO <-- FluidDynamics
> DRAG_COEFFICIENT <-- DEM

Aside of this problem, you shouldn't need to redefine any variable in the FluidDynamicsApplication as you are already deriving from it.

**Comment by philbucher** [comment]
hm congrats seems like you found it :)

**Comment by marcnunezc** [comment]
I removed all previous changes and merged master to make sure thats the issue!

**Comment by philbucher** [comment]
> I removed all previous changes and merged master to make sure thats the issue!

makes sense

Strange that this doesn't happen locally
I often run the tests in FullDebug but this didn't happen to me

**Comment by philbucher** [comment]
@marcnunezc didn't you want to reenable PotentialFlow again?

**Comment by philbucher** [comment]
did this test fail always or only sometimes?

**Comment by marcnunezc** [comment]
Yeah just realized it wasn't enabled :sweat_smile:

**Comment by marcnunezc** [comment]
> did this test fail always or only sometimes?

I tried two or three times to run the tests and it failed every time

**Comment by philbucher** [comment]
not again :sweat:

**Comment by marcnunezc** [comment]
:(

Actually if you check the output of the "correct" commit "[skip ci] enabling all apps" 473fc18, the CompressiblePotentialFlow is not included in the build for some reason.

**Comment by philbucher** [comment]
closing since this should be fixed in #6366

**Pull request closed without merging**
