### PR TITLE
[Core] Extend python interface for CalculateOnIntegrationPoints for Conditions

### PR DESCRIPTION
**Pull request by tteschemacher**
Hi all,

I am just extending the python interface of CalculateOnIntegrationPoints to the conditions.

There is no s or anything changed just the one from element is also applicable for conditions now.

### CODE REVIEW

**Review by philbucher — COMMENTED** [review]
+1
I will approve tmr in case others want to say sth

**Review by RiccardoRossi — APPROVED** [review]
looks good to me. 

Eventually (in a different PR) we should get rid of the "GetValues" function

**Comment by tteschemacher** [comment]
Thanks!!

Sure. They are not applied a lot anyways...

**Comment by philbucher** [comment]
@tteschemacher could you please add deprecation warnings to the Get... functions in the py-interface? Much appreciated :)

**Pull request merged**
