### PR TITLE
[Core][Geometry] Fixing NurbsCurveOnSurfaceGeometry

### PR DESCRIPTION
**Pull request by andreas-apostolatos**
Dear all,

I am creating this pull request in order to finalize the NurbsCurveOnSurfaceGeometry class for which some functions are still pending implementation.

Thanks!

### CODE REVIEW

**Comment by loumalouomega** [comment]
Travis fails

**Comment by tteschemacher** [comment]
Do you have an idea how to solve it, @loumalouomega ? That's why it got seperated because this function caused issues...

**Comment by loumalouomega** [comment]
> 
> 
> Do you have an idea how to solve it, @loumalouomega ? That's why it got seperated because this function caused issues...

I created a PR some time ago that fully removed the warnings, I don't remember why it was not a solution

**Comment by philbucher** [comment]
I think he is asking abt why adding the function in this PR fails

**Comment by loumalouomega** [comment]
> 
> 
> I think he is asking abt why adding the function in this PR fails

Sorry :P:

home/travis/build/KratosMultiphysics/Kratos/kratos/geometries/nurbs_curve_on_surface_geometry.h:76:90: note:   template argument deduction/substitution failed:

**Comment by andreas-apostolatos** [comment]
> > I think he is asking abt why adding the function in this PR fails
> 
> Sorry :P:
> 
> home/travis/build/KratosMultiphysics/Kratos/kratos/geometries/nurbs_curve_on_surface_geometry.h:76:90: note: template argument deduction/substitution failed:

Hello together,

yes @philbucher is right, adding the function Create() leads to this error because I unfortunately don't know how to implement it. Tobi mentioned something about an intrusive pointer but I would like to have a little bit deeper info, thanks once more!

**Comment by tteschemacher** [comment]
@andreas-apostolatos do you think this error massage is explanative enough? With the quadrature points we found out that the Create cannot be used at the moment. Do you agree to have it like this?

**Comment by andreas-apostolatos** [comment]
> @andreas-apostolatos do you think this error massage is explanative enough? With the quadrature points we found out that the Create cannot be used at the moment. Do you agree to have it like this?

Yes, I find it quite sufficient

**Review by tteschemacher — APPROVED** [review]
It's a minor change. It does open better error understanding, thus, I'm approving.

**Pull request merged**
