### PR TITLE
[Core] Split filesystem ext to avoid errors

### PR DESCRIPTION
**Pull request by loumalouomega**
**📝 Description**

Split filesystem ext to avoid errors

**🆕 Changelog**

- [Split filesystem ext to avoid errors](https://github.com/KratosMultiphysics/Kratos/commit/181151a45377ce643f92c6bf6f587afec3b24047)

### CODE REVIEW

**Review by philbucher — CHANGES_REQUESTED** [review]
I will take a look later

what is the error?

**Comment by loumalouomega** [comment]
> I will take a look later
> 
> what is the error?

@pablobecker ?

**Comment by ddiezrod** [comment]
Is it related to this? https://github.com/KratosMultiphysics/Kratos/pull/10455

**Comment by loumalouomega** [comment]
> Is it related to this? #10455

Yes, the other one is simpler, I will close @roigcarlo remove the branch if not needed

**Comment by ddiezrod** [comment]
Well if this fixes the problem then it is better to go this way, dont you think?

**Pull request closed without merging**
