### PR TITLE
[PFEM Fluid] Post process ModelPart with all elements (inc. triangles)

### PR DESCRIPTION
**Pull request by maceligueta**
First version (in Python) of a new output for PFEM Fluids. To be tested.
A new ModelPart dedicated to PostProcess is used. This ModelPart receives all elements from the main_model_part, including those in SubModelParts that are no longer present in the parent modelpart (spoiled structure by PFEM fast remeshing)

### CODE REVIEW

**Comment by maceligueta** [comment]
Please @pooyan-dadvand take a look at this commit: https://github.com/KratosMultiphysics/Kratos/pull/3389/commits/333070150c4f19428ec524972e7eee0a4d9224c4

**Comment by pooyan-dadvand** [comment]
@maceligueta It would be better to add the virtual method to the base class

**Review by ipouplana — DISMISSED** [review]
Since we don't have output_configuration in ProjectParameters of tests, I just introduced a minor correction in 7d2ab6a so that they pass. Other than that, everything seems right to me.

**Comment by maceligueta** [comment]
Thanks @ipouplana !

**Comment by maceligueta** [comment]
@pooyan-dadvand , I did not think about that, thanks. However, the method `WriteNodeMesh` is not present in the base class (IO), so I think this is the upper level for this method. 
Should we put more virtuals in the file? or just the minimum?

**Comment by pooyan-dadvand** [comment]
So I would add the method to the IO and make it virtual. Consider that IO should define the common interface.

**Comment by pooyan-dadvand** [comment]
All methods that are implemented in derived ones should be virtual in IO

**Comment by maceligueta** [comment]
@pooyan-dadvand , the virtual method is now in the base class. 
I think we can merge this, @AFranci .
Can anyone approve?

**Review by ipouplana — APPROVED** [review]

**Comment by pooyan-dadvand** [comment]
Ok from my side. :+1:

**Pull request merged**
