### PR TITLE
Errorchecking add variables

### PR DESCRIPTION
**Pull request by RiccardoRossi**
this PR is an attempt of closing #492 using the latest suggestion by @pooyan-dadvand.

with the modified code, the example by @philbucher fails with the error 

     RuntimeError: Error: attempting to add the variable: PENALTY to the model part with name: Test which is not empty

### CODE REVIEW

**Comment by philbucher** [comment]
Cool!
Always impressive how sth so minor can save so much time :D
Minor:
Why not ‘KRATOS_ERROS_IF_NOT‘ in combination with ‘NumberOfNodes ==0‘?

**Comment by RiccardoRossi** [comment]
it would work, HOWEVER every time we touch this we recompile the whole kratos :-D

(edit) read: i feel soooo lazy about changing this...

**Review by pooyan-dadvand — APPROVED** [review]
:+1

**Comment by pooyan-dadvand** [comment]
I agree that the comment of @philbucher slightly improves the code. But we are in the model part class and using internal methods is not harmful.

**Pull request merged**
