### PR TITLE
[Structural] revert parameter removal

### LINKED ISSUE #5496: [STRUCTURAL] Is it right to remove fields from parameters?
Just a philosophical question about whether it is correct to apply _RemoveValue_ to the Parameters that are provided to an AnalysisStage. Like it is done here:
https://github.com/KratosMultiphysics/Kratos/blob/448dac3784ed96095300694f572cc437fad19ead/applications/StructuralMechanicsApplication/python_scripts/python_solvers_wrapper_structural.py#L70
We came accross this question when we were launching multiple Stages with the same parameters, and all of a sudden some fields were missing beacause they were being removed automatically. We could bypass the problem by keeping a copy of the original Parameters, but we found it weird. 
I thought it was worth mentioning it. How do you run multiple Analyses in the same run at @KratosMultiphysics/structural-mechanics team? Do you keep a copy as we did?
@philbucher @lgratiela @RiccardoRossi @loumalouomega

### PR DESCRIPTION
**Pull request by philbucher**
closes #5496

### CODE REVIEW

**Comment by philbucher** [comment]
@loumalouomega I started applying the same in Contact, but you might need to complete it, thx :)

**Comment by loumalouomega** [comment]
Do we need to define those parameters on the defaults to avoid crash?

**Comment by philbucher** [comment]
> Do we need to define those parameters on the defaults to avoid crash?

yes, see the changes in Structural

I would have done it for you but I am not 100% sure how i works in contact

**Comment by loumalouomega** [comment]
> > Do we need to define those parameters on the defaults to avoid crash?
> 
> yes, see the changes in Structural
> 
> I would have done it for you but I am not 100% sure how i works in contact

In theory my defaults only affect contact settings, I will approve and fix it later if broke

**Review by loumalouomega — APPROVED** [review]
OK

**Review by maceligueta — APPROVED** [review]

**Comment by loumalouomega** [comment]
Let's play a game...

**Pull request merged**
