### PR TITLE
Fixing some tests that fail when mpi size is 1.

### PR DESCRIPTION
**Pull request by jcotela**
**📝 Description**
Some MPI tests are currently failing when run with `mpirun -np 1` and I understand that it is just because these tests are not designed to work that way. I tried to skip or adjust them as appropriate.

**🆕 Changelog**
- Fixed some tests MPI that were failing when run on a single process

### CODE REVIEW

**Review by roigcarlo — APPROVED** [review]
:+1: Yep I did not design those to work with np 1. (or the class for what it matters)

If you are interested I can modify them to run in serial as well.

**Comment by philbucher** [comment]
Should this be added to the CI?

**Comment by jcotela** [comment]
@roigcarlo if I understood correctly, most failing tests are for an utility that checks for consistency between processes, so for me it makes sense that it auto-succeeds or is skipped if there is only one process.

I found this while working on something else, I just wanted to have a clean test output for further development.

**Comment by jcotela** [comment]
@philbucher I do not know about the current CI setup, but I suspect that this thing of running with -np 1 is a somewhat marginal use case...

I will go ahead and merge, let me know if I can help with an eventual CI modification.

**Comment by roigcarlo** [comment]
@philbucher Na, no need to add. This is only for debug, it does not affect any functionality. As @jcotela said the main purpose of this is to ensure that variable values are in synch at different stages of the execution.

In any case, we should use this to make tests for processes, but not the other way around.

**Pull request merged**
