### PR TITLE
[dem] Important bugfix for the automatic coordination number in DEM Continuum

### PR DESCRIPTION
**Pull request by maceligueta**
There was a sentence outside the IF
The maximum distance was recalculated always, something which was changing the search tolerance when the sample was breaking.

### CODE REVIEW

**Comment by ipouplana** [comment]
Hi @maceligueta , Travis test is failing because 2 DEM tests are failing after this change. Could you take a look at it?

**Review by salvalatorre — APPROVED** [review]
Looks like a fine work at this stage...

**Comment by ipouplana** [comment]
Hi, I am compiling it right now. I'll test it as soon as it finishes.

But if you already tested it, you can go ahead and merge it.

**Comment by salvalatorre** [comment]
Well, I just launched a simulation in hpc0 using this code... Let us hope it holds up so I don't have to take that approval back... ;)

**Pull request merged**
