### PR TITLE
[Core]Moving to the core CheckAndPrepareModelProcess

### PR DESCRIPTION
**Pull request by loumalouomega**
The code can be used in any application

### CODE REVIEW

**Comment by loumalouomega** [comment]
It can  be use in the structural and fluid application for example

**Comment by philbucher** [comment]
The name of the parameters in Fluid are different, so I am not sure if it would work

Also if I remember correctly they do sth slightly different than in structural, have you checked?

**Comment by RiccardoRossi** [comment]
i don t think this should be in the core...

as philipp commented it may be domain specific and...i would love to get rid of this im the mid lomg term...

**Comment by loumalouomega** [comment]
True, I forgot that with tthe new Model this will be obsolete. 

Besides, for the structural is exactly the same

~~~py
        self.computing_model_part_name  = Parameters["computing_model_part_name"].GetString()
        self.structural_model_part_names = Parameters["problem_domain_sub_model_part_list"]
        self.processes_model_part_names = Parameters["processes_sub_model_part_list"]
~~~

**Comment by philbucher** [comment]
so can we close this then?

**Comment by loumalouomega** [comment]
Ok :(

**Pull request closed without merging**
