### PR TITLE
[Travis] activating Trilinos & Metis

### PR DESCRIPTION
**Pull request by philbucher**
Some more testing to see what is possible :)
Only possible with Ubuntu 18

based on #5368

### CODE REVIEW

**Comment by philbucher** [comment]
wow this seems to work too!

It is almost out of time but I think once it cashes it the compilation time will decrease again
Also if we only install the required trilinos libs and not all then it will also be a bit faster

it currently crashes when trying to run the cpp-tests: It tries to import trilinos, but the MPI-Core is not imported, hence it fails (undefined symbols)
=> This will be fixed properly once I improved the integration of the cpp-tests

**Comment by philbucher** [comment]
now it should work

The TrilinosApp is disabled until a fix for the C-Tests is found (see my previous post)

What do you think @roigcarlo ?

**Review by roigcarlo — COMMENTED** [review]
Looks nice, and dosen't seem to have an impact in the compile time (bit we shopuld monitor that closely) so for me its ok.

I would like to hear from the others as well

**Comment by philbucher** [comment]
now it works both for the MetisApp and the TrilinosApp

**Review by RiccardoRossi — COMMENTED** [review]
@KratosMultiphysics/technical-committee agrees to merging this, nevertheless right now the core appears to be compiled twice so this should be verified

**Comment by philbucher** [comment]
I now use the minimum necessary packages of Trilinos

Travis compiled it in 28 min!
I think this can go in and we can investigate separately why the Core is compiled twice

**Comment by philbucher** [comment]
@roigcarlo did you have a chance to take a look?
Sorry to bother you :/
Thanks!

**Comment by roigcarlo** [comment]
If it compiles in 28 min go ahead!

**Comment by philbucher** [comment]
Ok then lets see what happens
Worst case we disable it again

**Comment by philbucher** [comment]
Hm can you approve pls? :)

**Review by roigcarlo — APPROVED** [review]

**Comment by philbucher** [comment]
hm seems like it now recompiles also some things of the fluid 😕 
I will take a close look during the day what happens with the build time and worst case disable it again

We can speak tmr in person

**Pull request merged**
