### PR TITLE
[Fluid] minor refactoring by using parallel utilities

### PR DESCRIPTION
**Pull request by philbucher**
**Description**
If this doesn't spark joy then you clearly don't love clean code :D

Jokes aside, @rubenzorrilla I don't know if this has tests, please check, it should work
in any case this is how you use the "private" approach with the ParallelUtilities

### CODE REVIEW

**Comment by rubenzorrilla** [comment]
Unfortunately the estimate Dt utility has no tests yet. As I'm adapting it to consider the compressible flow (or other thermal related) formulation I'll try this in there.

Thanks!!!!!!

**Comment by rubenzorrilla** [comment]
I tried in my local branch and it worked! Many thanks!

The unique difference that comes to my mind with respect to my previous implementation is that I was passing an already created instance of the TLS instead of calling the default constructor. Could this be the issue?

**Comment by philbucher** [comment]
you could also create it before (then it would be `firstprivate`) but then you have one line of code more
Thats why I like this one so much, you can construct it in place :)

**Comment by rubenzorrilla** [comment]
> you could also create it before (then it would be `firstprivate`) but then you have one line of code more
> Thats why I like this one so much, you can construct it in place :)

This is what I though. It seems that my problem was different (I guess I missed the `&` Lambda capture).

In any case it works. Would you mind if we close this PR and I include the changes in the upcoming PR cleaning and adapting the utility to the compressible N-S case?

**Comment by philbucher** [comment]
sure, I mainly created this PR for demonstration purposes :)
Do what you want with it :D

**Comment by rubenzorrilla** [comment]
Closing as we will add this to an upcoming clean up of the utility.

**Pull request closed without merging**
