### PR TITLE
Sdem/porting to pybind

### PR DESCRIPTION
**Pull request by roigcarlo**
@GuillermoCasas I found some problems and made some changes in the interface. Please can you check I did not break anything?

I also need to compile it in win, so maybe further changes will be needed.

### CODE REVIEW

**Review by GuillermoCasas — COMMENTED** [review]
As I said, it was ongoing work... I will test it as soon as possible. There is just one thing I am really concerned about: Now the DEM_application depends on the swimming_DEM_application, right? Is that not, to say the least, a bad design? Cheers

**Comment by roigcarlo** [comment]
Oh sorry, miss the ongoing part in the mail.
I am not sure to understand your concern, where is the dependency of DEM from Swimming?

**Comment by GuillermoCasas** [comment]
It got confused sorry :S

**Comment by maceligueta** [comment]
@GuillermoCasas  and @roigcarlo , what should we do here? Should we merge from master and keep adapting until it works? I think this is pretty urgent, as SDEM is not working on master branch.

**Comment by roigcarlo** [comment]
I made the PR because I though the porting was finished, since it is not the case we can just discard the PR.
If you give me something I can use to test I can finish the port myself.

As you prefer

**Review by RiccardoRossi — COMMENTED** [review]
@roigcarlo i see nothing wrong with this pr (apart for importing omp.h, but this is offtopic).

However i am not working with this app. so i guess it is better that someone else approves

**Comment by maceligueta** [comment]
It took me a while, but finally I managed to run the Candelier test. Links are gone, corrupted files in the repo have been restored. However, someone using this app with examples different from Candelier should try it and say something (@salvalatorre @GuillermoCasas @ipouplana ). I suspect there are still some changes to do. At least pybind is working.

**Review by maceligueta — APPROVED** [review]

**Comment by maceligueta** [comment]
(I approved after talking with @GuillermoCasas in person)

**Pull request merged**
