### PR TITLE
[Fluid] Weakly compressible darcy relative velocity

### PR DESCRIPTION
**Pull request by rubenzorrilla**
**📝 Description**
Adding the solid fraction velocity to the Darcy term calculation. The changes in the solver are to avoid misunderstandings with the variable lists names (these are not only material variables).

@RiccardoRossi [here](https://github.com/user-attachments/files/17957066/test_darcy_term.zip) you can find a tiny example on how to use it (see the MainKratos.py).

EDIT: note that I took the chance to correct a tiny error in the Darcy part of the stabilization constants.

### CODE REVIEW

**Review by RiccardoRossi — DISMISSED** [review]
looks good to me.

thx @rubenzorrilla

**Comment by rubenzorrilla** [comment]
@jgonzalezusua note that I required to rename the variable also in your solver. I think this one is more convenient as we are now using this list to also add non material-related variables.

**Comment by rubenzorrilla** [comment]
@RiccardoRossi should be ready now.

**Review by RiccardoRossi — APPROVED** [review]

**Comment by jgonzalezusua** [comment]
Sorry for the late response... I agree with the changes in my solver

**Pull request merged**
