### PR TITLE
[Chimera] removed deprecated includes

### PR DESCRIPTION
**Pull request by philbucher**
**Description**
No longer needed

### CODE REVIEW

**Comment by philbucher** [comment]
@adityaghantasala seems like there are still some usages of `VariableComponents`
Can you please take a look? => this might hide bugs

**Comment by adityaghantasala** [comment]
This should not cause any bugs as the whole use of variables is templated. Nevertheless, I will check.

**Comment by adityaghantasala** [comment]
There was a typedef of var component which was never used. I deleted it and now it should work.

**Comment by philbucher** [comment]
can you approve and merge then @adityaghantasala ?
Thx

**Review by adityaghantasala — APPROVED** [review]
Thank you @philbucher

**Pull request merged**
