### PR TITLE
[Core] Adding missing Faces() method to the Triangle3D3 and Quadrilateral3D4

### PR DESCRIPTION
**Pull request by loumalouomega**
This PR adds the missing methods  to the Triangle3D3 and Quadrilateral3D4

Adding test

### CODE REVIEW

**Comment by loumalouomega** [comment]
Ping

**Comment by loumalouomega** [comment]
Ping @roigcarlo

**Comment by roigcarlo** [comment]
At @KratosMultiphysics/technical-committee we agree with the changes but we are still discussing the behaviour of some of the methods.

**Comment by loumalouomega** [comment]
How is this discussion going?

**Comment by RiccardoRossi** [comment]
Let me explain my point of view on this issue, and on the related #4221 since this may explain the rationale currently employed in the geometry

In the original design "faces" returned the boundaries of the object.

this means that 
Tetrahedra3D4 (WorkingSpaceDimension()==3) should return 4 faces, the triangles
Triangle2D3 (WorkingSpaceDimension()==2) should return 3 face, which really are the edges of the triangle 
Line2D2 (WorkingSpaceDimension()==1) should return 2 "faces" (which are the end points)

the rationale behind this choice was that this way be calling faces it was releatively easy to compute integrals on the boundaries of the domain.

By doing a quick grepping through the code, i would say that **it is currently used this way.**

My personal point of view would be to also employ the very same rationale also for the case of Triangle3D3 (3 faces, the edges) or Line3D2 (2 faces, the points)

On my side, I am open to discuss other options, however please beware since they may imply behviour changes through the code.

**Comment by RiccardoRossi** [comment]
After a productive discussion with @loumalouomega we have two positions

**Current Status/my understanding** (admittedly with a wrong implementation in some geometries)
* Tetrahedra3D4   Faces()->4 Triangle3D3   Edges() -> 6 Line3D3
* Triangle2D3        Faces()->3 Line2D2   Edges() -> 3 Line2D2 (note: Faces actually returns Edges())
* Line2D2              Faces()->2 Point2D    Edges() -> **ERROR** 
* Triangle3D3        Faces()->3 Line3D3   Edges() -> 3 Line3D3 (note: **no/wrong implementation**)
* Line3D2              Faces()->2 Point3D    Edges() -> **ERROR** 

**Vicente's proposal**
* Tetrahedra3D4   Faces()->4 Triangle3D3   Edges() -> 6 Line3D3
* Triangle2D3        Faces()->3 **ERROR**   Edges() -> 3 Line2D2
* Line2D2              Faces()->2 **ERROR**   Edges() -> 1 Line2D2 
* Triangle3D3        Faces()->**2 Triangle3D3**   Edges() -> 3 Line3D3 (note: **no/wrong implementation**)
* Line3D2              Faces()->**ERROR**     Edges() -> 1 Line3D3 (note: **no/wrong implementation**)

The advantage of current proposal is that Faces is defined both in 2D and 3D with "resonable values" (in the context of making boundary integrals)

The advantage of Vicente's proposal is that geometrical operations are more consistently defined, particularly in the context of searching. See

https://github.com/KratosMultiphysics/Kratos/blob/b5a4c962b30aeb4230b10fee784ff906b97b65c7/kratos/processes/find_intersected_geometrical_objects_process.cpp#L236

and

https://github.com/KratosMultiphysics/Kratos/blob/b5a4c962b30aeb4230b10fee784ff906b97b65c7/kratos/processes/find_intersected_geometrical_objects_process.cpp#L214

**Comment by RiccardoRossi** [comment]
Maybe one option would be to have in the geometry a method say

"BoundaryEntities" which returns either faces or edges (or points) and to have Faces and Edges to be consistent with their geometrical meaning.

i mean:


  | BoundaryEntity | Faces | Edges | Points
-- | -- | -- | -- | --
Line2D2 | call Points() | error | return 1 Line2D2 | return 2 Point2D
Line3D2 | call Points() | error | return 1 Line3D2 | return 2 Point3D
Triangle2D3 | call Edges() | error | return 3 Line2D2 | return 3 Point2D
Triangle3D3 | call Edges() | return 1 Triangle 3D3 | return 3 Line3D2 | return 3 Point3D
Tetrahedra3D4 | call Faces() | return 4 Triangle 3D3 | return 6 Line3D2 | return 4 Point3D
Point2D | error | error | error | return 1 Point2D
Point3D | error | error | error | return 1 Point3D



Note however that pursuing this would imply some code breakage...

**Comment by loumalouomega** [comment]
> Maybe one option would be to have in the geometry a method say
> 
> "BoundaryEntities" which returns either faces or edges (or points) and to have Faces and Edges to be consistent with their geometrical meaning.
> 
> i mean:
>   	BoundaryEntity 	Faces 	Edges 	Points
> Line2D2 	call Points() 	error 	return 1 Line2D2 	return 2 Point2D
> Line3D2 	call Points() 	error 	return 1 Line3D2 	return 2 Point3D
> Triangle2D3 	call Edges() 	error 	return 3 Line2D2 	return 3 Point2D
> Triangle3D3 	call Edges() 	return 1 Triangle 3D3 	return 3 Line3D2 	return 3 Point3D
> Tetrahedra3D4 	call Faces() 	return 4 Triangle 3D3 	return 4 Line3D2 	return 2 Point2D
> Point2D 	error 	error 	error 	return 1 Point2D
> Point3D 	error 	error 	error 	return 1 Point3D
> 
> Note however that pursuing this would imply some code breakage...

I agree upon the points defined, but maybe @pooyan-dadvand doesn't like the idea of adding new methods to the geometries. We should agree an expected behavior and modify the geometries accordingly. 

Additionally I would like to highlight the importance of adding tests for all the remaining geometries. Time to time errors appear in legacy not tested functions, as we saw recently on the quadratic line. The newcomer developers assume that all of this is working properly, but this is not the case in many functions. I understand that we mostly use the linear geometries, but as @GuillermoCasas suggested in a  @KratosMultiphysics/implementation-committee  meeting, it is better to remove non-tested methods, so at least the error will tell you that method is not defined yet, instead of giving a false hope that the geometries are 100% functional and ready to use.

**Comment by rubenzorrilla** [comment]
> Maybe one option would be to have in the geometry a method say
> 
> "BoundaryEntities" which returns either faces or edges (or points) and to have Faces and Edges to be consistent with their geometrical meaning.
> 
> i mean:
>   	BoundaryEntity 	Faces 	Edges 	Points
> Line2D2 	call Points() 	error 	return 1 Line2D2 	return 2 Point2D
> Line3D2 	call Points() 	error 	return 1 Line3D2 	return 2 Point3D
> Triangle2D3 	call Edges() 	error 	return 3 Line2D2 	return 3 Point2D
> Triangle3D3 	call Edges() 	return 1 Triangle 3D3 	return 3 Line3D2 	return 3 Point3D
> Tetrahedra3D4 	call Faces() 	return 4 Triangle 3D3 	return 4 Line3D2 	return 2 Point2D
> Point2D 	error 	error 	error 	return 1 Point2D
> Point3D 	error 	error 	error 	return 1 Point3D
> 
> Note however that pursuing this would imply some code breakage...

I like the idea of having a method to return those entities required to perform the boundary integrals in each one of the geometries. Thus, I'd say that in general terms I'm in favour of this `Boundaries()` or `BoundaryEntity()` method. 

However I feel that it would be quite hard to distinguish which `Faces()` or `Edges()` calls should remain as they are and which ones should be changed to a `Boundaries()` call. Having this in mind, if we decide it is required to modify the current implementation, @loumalouomega approach (based on throwing errors when you are not calling the proper method) seems to be more easy from the transition point of view.

BTW, @RiccardoRossi in your table I think that the tetra must be `return 6 Line3D2` and `return 4 Point3D` for the `Edges()` and `Points()` calls.

**Comment by pooyan-dadvand** [comment]
> "BoundaryEntities" which returns either faces or edges (or points) and to have Faces and Edges to be consistent with their geometrical meaning.

I like the idea but not the name...

**Comment by RiccardoRossi** [comment]
@rubenzorrilla thx, i updated the table

about the name of "BoundaryEntities" ... listening to proposals :-)

maybe "GetSkin"?

**Comment by pooyan-dadvand** [comment]
`Boundaries`?

**Comment by RiccardoRossi** [comment]
I would prefer "Skin" than "Boundaries" ...

**Comment by RiccardoRossi** [comment]
ut ultimately i can also live with "boundaries"

**Comment by pooyan-dadvand** [comment]
for a line? our a triangle? 

`Contours`?

**Comment by RiccardoRossi** [comment]
I prefer "Boundaries" then :-)

In any case beyond the naming, 
the point  is that if we decide to go this way, we will have quite a lot of silent breakage through the code, since it would imply changing the behaviour of existing function (Edges and Faces). 
If we want to do that we need to decide a changing strategy to have the compiler help...

**Comment by pooyan-dadvand** [comment]
Are they used in the repo?

**Comment by loumalouomega** [comment]
> Are they used in the repo?

What do you mean?

**Comment by pooyan-dadvand** [comment]
If any application uses the current edge and face methods

**Comment by loumalouomega** [comment]
> If any application uses the current edge and face methods

Several, that's why I updated the methods, I needed to update FindIntersecionGeometricalObjects, without manually update

**Comment by RiccardoRossi** [comment]
We have been discussing this in @KratosMultiphysics/technical-committee and we are in agreement about the solution with a new function.

the idea that the new function, wich we suggest calling **GenerateBoundaryEntities** (we reached an agreement on this)
is implemented in the base class as (pseudo code)

[Edit: changing WorkingSpaceDimension() -> LocalSpaceDimension() according to the feedback of @loumalouomega )

~~~cpp
template< class TOutputType >
std::vector< Geometry<TOutputType> > GenerateBoundaryEntities()
{
    if(this->LocalSpaceDimension()==3) 
         return this->GenerateFaces();
    else if(this->LocalSpaceDimension()==2) 
         return this->GenerateEdges();
    else(this->LocalSpaceDimension()==1) 
         return this->GeneratePoints();   
}
~~~
this function is, at least initially, not virtual

this is a "Behaviour Change" PR. 
In order to perform the migration **we would deprecate** "Faces" "Edges" and "Points"

note that the "Generate" in the name is intended to communicate to the user that the boundary entities (faces, edges, etc) are computed on the fly and not stored.

This is done so, to allow in a future to possibly store such entities if precomputed

**Comment by loumalouomega** [comment]
> We have been discussing this in @KratosMultiphysics/technical-committee and we are in agreement about the solution with a new function.
> 
> the idea that the new function, wich we suggest calling **GenerateBoundaryEntities** (we reached an agreement on this)
> is implemented in the base class as (pseudo code)
> 
> ```c++
> template< class TOutputType >
> std::vector< Geometry<TOutputType> > GenerateBoundaryEntities()
> {
>     if(this->WorkingSpaceDimension()==3) 
>          return this->GenerateFaces();
>     else if(this->WorkingSpaceDimension()==2) 
>          return this->GenerateEdges();
>     else(this->WorkingSpaceDimension()==1) 
>          return this->GeneratePoints();   
> }
> ```
> 
> this function is, at least initially, not virtual
> 
> this is a "Behaviour Change" PR.
> In order to perform the migration **we would deprecate** "Faces" "Edges" and "Points"
> 
> note that the "Generate" in the name is intended to communicate to the user that the boundary entities (faces, edges, etc) are computed on the fly and not stored.
> 
> This is done so, to allow in a future to possibly store such entities if precomputed

But the methods of Edges and Faces will disappear?, what will happen with the geometries which local space dimension is different of the working space dimension?

**Comment by RiccardoRossi** [comment]
@loumalouomega  the point is to have the old methods Edges, Faces to be removed (well deprecated to start with)

the new methods GenerateEdges and GenerateFaces will behave the way described in the table, which as i understand is what you were asking for.

Of course this will imply propagating changes through the code ... but we see this as the only clean solution.

Does this solve your problem?

**Comment by loumalouomega** [comment]
> @loumalouomega the point is to have the old methods Edges, Faces to be removed (well deprecated to start with)
> 
> the new methods GenerateEdges and GenerateFaces will behave the way described in the table, which as i understand is what you were asking for.
> 
> Of course this will imply propagating changes through the code ... but we see this as the only clean solution.
> 
> Does this solve your problem?

But in your proposal you are using WorkingSpaceDimension, do you mean WorkingSpaceDimension or LocalSpaceDimension?, there are no geometries with WorkingSpaceDimension == 1, how do you get with this method the edges in a 3D triangle?, calling directly GenerateEdges?

**Comment by RiccardoRossi** [comment]
@loumalouomega the method GenerateEdges and GenerateFaces will have to be implemented in the geometries as described on the table...

the old methods Edges and Faces will eventually be removed. (deprecated for starter)

the method GenerateBoundaryEntities should indeed depend on the WorkingSpaceDimension but deoending on that will call either GenerateFaces or GenerateEdges depending on the WorkingSpaceDimension. What the method GenerateFaces and GenerateEdges will do will actually depend on the specific geometry.

**Comment by RiccardoRossi** [comment]
CORRECTION: @loumalouomega was right! (and i was wrong :-( :-( ) 

we should use LocalSpaceDimension() within BoundaryEntities to match the table value.

i'll update the pseudo code i posted

**Comment by loumalouomega** [comment]
> CORRECTION: @loumalouomega was right! (and i was wrong :-( :-( )
> 
> we should use LocalSpaceDimension() within BoundaryEntities to match the table value.
> 
> i'll update the pseudo code i posted

Ok, that was my question :)

**Comment by pooyan-dadvand** [comment]
But local space dimension can be 3 for a triangle2D2... Are you sure that Dimension is not better? A triangle is always 2D and quadrilateral also. Even if they are in 3D space.

**Comment by loumalouomega** [comment]
LocalSpaceDimension is 2 for Triangle2D3 and for the Triangle3D3. The WorkingSpaceDimension is 2 for Triangle2D3 and 3 for Triangle3D3

**Comment by pooyan-dadvand** [comment]
But why not Dimension? One can implemented the triangle with area shape functions with 3 local axis

**Comment by loumalouomega** [comment]
> But why not Dimension? One can implemented the triangle with area shape functions with 3 local axis

Well, I am not against anything, I want something consistent in order to use it knowing the behavior expected

**Comment by loumalouomega** [comment]
Any case  we should move the discussion to #4767

**Comment by RiccardoRossi** [comment]
@pooyan-dadvand if we want to comply with the table we posted than it has to be LocalSpaceDimension ... (which is always 2 for any triangle)

**Comment by RiccardoRossi** [comment]
we have been speaking in the @KratosMultiphysics/technical-committee in this case the Dimension() and the LocalSpaceDimension() calls should return the same values. 

so you can go ahead with using LocalSpaceDimension as discussed

i will approve the PR on behalf of the technical committee

**Pull request closed without merging**
