### PR TITLE
[ContactStructuralMechanicsApplication] Replace error fro warning

### PR DESCRIPTION
**Pull request by loumalouomega**
The current error doesn't allow to remesh contact problems

### CODE REVIEW

**Comment by RiccardoRossi** [comment]
vicente, wasn t there an open discussion about ensureproperties?

**Comment by philbucher** [comment]
> vicente, wasn t there an open discussion about ensureproperties?

this one? #5339

**Comment by loumalouomega** [comment]
> vicente, wasn t there an open discussion about ensureproperties?

@philbucher approved. This is nothing to do. This reverts a recent change that I did and I haven't think about its effects in remeshing

**Comment by loumalouomega** [comment]
This is small and simple, can anyone approve?

**Review by philbucher — APPROVED** [review]

**Comment by loumalouomega** [comment]
Thanks

**Pull request merged**
