### PR TITLE
Feature build mode fixes

### PR DESCRIPTION
**Pull request by jcotela**
I'm changing a couple of things from CMakeLists according to recent suggestions.

- If `CMAKE_BUILD_TYPE` is not set by the user (in the configure script) it now defaults to `Release`.

- From the discussion in #580, I'm removing the -ffast-math compiler flag from the CMakeLists file. Now it will only be used if it is explicitly defined in the configure script.

Personally, I'd llike to add the -ffast-math flag again, but only for `Release` and `RelWithDebInfo` modes, since it seems to provide some speedup (see #369), but I'll wait to see if other people agree.

### CODE REVIEW

**Comment by roigcarlo** [comment]
@jcotela No problems with this but in case we always default to Release I would need to define another "Custom" build mode that does nothing so I can manually set the flags for travis/amazon via the config file.

I can do it myself in a separate release or here as you like.

**Comment by pooyan-dadvand** [comment]
@jcotela As discussed in #580 the difference was really subtle: 2-5% so for me adding it or not is not a big difference. I understood that the problem and uncertainty it produces in additional libraries is not paying off its improvement but of course this is my opinion.

**Review by pooyan-dadvand — APPROVED** [review]
:+1:

**Comment by jcotela** [comment]
OK, then we merge as-is. If someone wants ffast-math, it can still be passed from the configure script in the usual CMake way (CMAKE_CXX_FLAGS, etc.).

**Pull request merged**
