### PR TITLE
[Core] Transition PR for #3185

### PR DESCRIPTION
**Pull request by loumalouomega**
This just moves the existing factories to the factories folder to reduce changes on #3185

### CODE REVIEW

**Comment by rubenzorrilla** [comment]
In general terms, I'd say that I'm favor of any movement that reduces the amount of files in the `includes` folder. 

However, before making any strong opinion I'd like to know which is the potential number of factories that we will have in such `factories` folder after #3185 is (eventually) merged.

**Comment by philbucher** [comment]
I also agree about moving those includes to its specific folder
From what I understood the number of factories will be ~10-20 right?

**Comment by loumalouomega** [comment]
> In general terms, I'd say that I'm favor of any movement that reduces the amount of files in the `includes` folder.
> 
> However, before making any strong opinion I'd like to know which is the potential number of factories that we will have in such `factories` folder after #3185 is (eventually) merged.

This is part of #3185

**Comment by loumalouomega** [comment]
The number of factories will depend, #3185 is only the solving strategies, but eventually we will add the processes. I don't know what else @pooyan-dadvand

**Comment by pooyan-dadvand** [comment]
I agree with this move. In future we can add the factory base class and the other standard ones there

**Comment by loumalouomega** [comment]
> I agree with this move. In future we can add the factory base class and the other standard ones there

In fact that is what happens on #3185

**Comment by rubenzorrilla** [comment]
OK. If this is the case, I also agree.

**Comment by loumalouomega** [comment]
Can we proceed then?

**Comment by philbucher** [comment]
@KratosMultiphysics/technical-committee I approve this since I believe this is a good change and we have other more important things to discuss, imo no point discussing this PR
Also many of you answered already

**Review by philbucher — APPROVED** [review]

**Pull request merged**
