### PR TITLE
Giving consisting names to the solvers operations

### PR DESCRIPTION
**Pull request by loumalouomega**

### CODE REVIEW

**Comment by loumalouomega** [comment]
@msandre Do you agree with the recent changes?

**Comment by msandre** [comment]
Hi, I think it is good to be consistent. My preference would be to leave "Strategy" out of the function names. It is the same in all the functions and it makes reading the functions less natural. E.g., StrategyInitialize() does not follow the "imperative" naming convention, but Initialize() does.

**Comment by rubenzorrilla** [comment]
Thanks Tote! @msandre the point was that these "splitted" resolution methods had different names in the FluidDynamics and StructuralMechanics apps. This is somehow strange in combined solvers. We have discussed this morning about unifying names.

**Comment by rubenzorrilla** [comment]
@msandre what is your proposal? Maybe InitializeStrategy(), PredictStrategy()?

**Comment by msandre** [comment]
To clarify, I'm not opposed to the changes. I'm just saying the function names are a bit non-conforming in my opinion. To me the cleanest way would be

GetStrategy().Initialize()
GetStrategy().InitializeSolutionStep()

instead of

InitializeStrategy()
InitializeSolutionStepStrategy()
etc.

**Comment by rubenzorrilla** [comment]
+1. In this way a unique GetStrategy() method is required in the base class.

**Comment by rubenzorrilla** [comment]
@msandre , @loumalouomega , I've just realized that this solution is not valid in case you need to perform some action which do not belong to the strategy. For instance

`def `StrategyInitializeSolutionStep(self):`
`        (self.bdf_process).Execute()`
`        (self.solver).InitializeSolutionStep()`

Probably this is why we chose this solution in the past...

**Comment by msandre** [comment]
Ok, I'm not sure what the dependence is of the solver on the bdf process. Ideally, the logic needed to initialize solution step of the strategy would be inside the strategy.

**Comment by rubenzorrilla** [comment]
This was just an example, in this case the time integration is done within the element and the scheme only updates the database. My point is that if you need to perform any particular action (e.g. divergence clearance in fluid solvers) independent to the Newton-Raphson, the GetStrategy() method does not allow to do that.

**Comment by pooyan-dadvand** [comment]
I don't like the names neighter....

**Comment by rubenzorrilla** [comment]
@loumalouomega @msandre after a short discussion with @pooyan-dadvand , we both think that the best approach is to kept the usual nomenclature. I've slightly modified the fluid dynamics solvers in order to fit into that. Thank you very much!

**Comment by loumalouomega** [comment]
Oki

**Review by rubenzorrilla — APPROVED** [review]

**Pull request merged**
