### PR TITLE
[Structural] making theComputingModelPart optinal

### LINKED ISSUE #3886: [StructMech] Why is the computing_model_part needed?
@KratosMultiphysics/structural-mechanics 

Related to #3879 and #3813 i came across some questions: 

Why is the computing model part needed in the structural mechanics solver?
Would it be possible to get rid of the following 3 settings in the .json?
* computing_model_part_name
* problem_domain_sub_model_part_list
* processes_sub_model_part_list

All that i see is happening, is that all elements and nodes are copied from problem_domain_sub_model_part_list and all conditions from processes_sub_model_part_list.

In the standard case that everything from the .mdpa should be considered, less user settings would be required, if the main_model_part would directly be used to compute the system.

If one does not wan't to consider certain conditions, it should be enough to remove the related process that applies the values.
If one does not wan't to consider certain elements, they could be deactivated explicitly.

### PR DESCRIPTION
**Pull request by philbucher**
FINALLY :DDD

This PR makes the ComputingModelPart legacy :D
I.e. Instead of using the ComputingModelPart we directly use the MainModelPart

 => It will **not break old cases**, if `problem_domain_sub_model_part_list` or `processes_sub_model_part_list` is present in the settings (which it is for old cases) then nothing changes
The interface does not write these parameters any more, this was changed in #4978 and https://github.com/KratosMultiphysics/GiDInterface/pull/598

@loumalouomega @AlejandroCornejo I am not sure how much this will affect the contact. As mentioned, old cases should not be affected since the computing-mp is still constructed, but not sure what happens for new cases.
We could easily make the old behavior default in contact, then you have more time for the transition

closes #3886

### CODE REVIEW

**Comment by loumalouomega** [comment]
Vicente is scared of this, I use extensively the computing model part and I assume it continously. In fact I even create submodelparts called ComputingContactX for the active contacting conditions :P

**Review by loumalouomega — CHANGES_REQUESTED** [review]
Blocking until I check my app is not broken

**Comment by philbucher** [comment]
I know you use it a lot, previously we had no choice :/

How abt the following: 
In **Structural** we pass the **Main**ModelPart to the B&S (long term solution). 
In **Contact** you can still work with ComputingModelParts, if you want. As long as they are SubModelParts of the MainModelPart (which I assume is already now the case) then your contact conditions will also be assembled in the B&S
What do you think?

**Comment by loumalouomega** [comment]
> I know you use it a lot, previously we had no choice :/
> 
> How abt the following:
> In **Structural** we pass the **Main**ModelPart to the B&S (long term solution).
> In **Contact** you can still work with ComputingModelParts, if you want. As long as they are SubModelParts of the MainModelPart (which I assume is already now the case) then your contact conditions will also be assembled in the B&S
> What do you think?

Let me check the thing

**Comment by philbucher** [comment]
Did you check @loumalouomega ?

**Comment by loumalouomega** [comment]
> Did you check @loumalouomega ?

Nope, I am in several things right now

**Comment by philbucher** [comment]
any news?
Just had another discussion with @KlausBSautter where a lot of confusion was created thx to the computing-mp :)

**Comment by loumalouomega** [comment]
My tests fail, so I would need to refactor my app first

**Comment by philbucher** [comment]
hm this should not crash tests, might do so in the future
Did you add the crashing tests recently? (~last two months, after https://github.com/KratosMultiphysics/GiDInterface/pull/598)

**Comment by loumalouomega** [comment]
Nope, I really need more time to fully study

**Comment by philbucher** [comment]
Ok

Just for your info:

On my machine:
MASTER:
~~~
...........F.............F..............F.......................F...................
Ran 84 of 795 test cases in 0.129537s. 4 failed:
    TestDualShapeFunctionDerivativesQuadrilateral2 Failed with message: 
        Error: YOUR INITIAL SPLITTING DOES NOT COINCIDE WITH THE CURRENT ONE

in /home/philippb/software/Kratos_Master/applications/ContactStructuralMechanicsApplication/tests/cpp_tests/test_derivatives.cpp:406:void Testing::TestDerivatives(ModelPart&, Condition::Pointer, Condition::Pointer, Condition::Pointer, Condition::Pointer, const vector<long unsigned int>&, Testing::IndexType, const vector<double>&, Testing::IndexType, Testing::DerivateToCheck, Testing::CheckLevel) [with long unsigned int TDim = 3ul; long unsigned int TNumNodes = 4ul; Condition::Pointer = intrusive_ptr<Condition>; Testing::IndexType = long unsigned int]

    TestJacobianDerivativesQuadrilateral2 Failed with message: 
        Error: YOUR INITIAL SPLITTING DOES NOT COINCIDE WITH THE CURRENT ONE

in /home/philippb/software/Kratos_Master/applications/ContactStructuralMechanicsApplication/tests/cpp_tests/test_derivatives.cpp:406:void Testing::TestDerivatives(ModelPart&, Condition::Pointer, Condition::Pointer, Condition::Pointer, Condition::Pointer, const vector<long unsigned int>&, Testing::IndexType, const vector<double>&, Testing::IndexType, Testing::DerivateToCheck, Testing::CheckLevel) [with long unsigned int TDim = 3ul; long unsigned int TNumNodes = 4ul; Condition::Pointer = intrusive_ptr<Condition>; Testing::IndexType = long unsigned int]

    TestMixedULMLinearSolverThreeDoFSystem Failed with message: 
        Error: Check failed because std::abs(ref_Dx[i] - Dx[i])/std::abs(ref_Dx[i]) = 0.0515687 is not near to 0.0 = 0 within the tolerance 0.05
in /home/philippb/software/Kratos_Master/applications/ContactStructuralMechanicsApplication/tests/cpp_tests/test_mixedulm_linear_solver.cpp:698:virtual void Testing::TestMixedULMLinearSolverThreeDoFSystem::TestFunction()

    TestShapeFunctionDerivativesQuadrilateral2 Failed with message: 
        Error: YOUR INITIAL SPLITTING DOES NOT COINCIDE WITH THE CURRENT ONE

in /home/philippb/software/Kratos_Master/applications/ContactStructuralMechanicsApplication/tests/cpp_tests/test_derivatives.cpp:406:void Testing::TestDerivatives(ModelPart&, Condition::Pointer, Condition::Pointer, Condition::Pointer, Condition::Pointer, const vector<long unsigned int>&, Testing::IndexType, const vector<double>&, Testing::IndexType, Testing::DerivateToCheck, Testing::CheckLevel) [with long unsigned int TDim = 3ul; long unsigned int TNumNodes = 4ul; Condition::Pointer = intrusive_ptr<Condition>; Testing::IndexType = long unsigned int]

Unittests: Finished running cpp unit tests! 
Unittests: 
Running python tests ... 
.......!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! LUSkylineFactorization::factorize: Error zero sum
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! LUSkylineFactorization::factorize: Error zero sum (LOTS of those, deleted for readability)
ResidualBasedBlockBuilderAndSolver: ATTENTION! setting the RHS to zero!
ResidualBasedBlockBuilderAndSolver: ATTENTION! setting the RHS to zero!
ResidualBasedBlockBuilderAndSolver: ATTENTION! setting the RHS to zero!
ResidualBasedBlockBuilderAndSolver: ATTENTION! setting the RHS to zero!
ResidualBasedBlockBuilderAndSolver: ATTENTION! setting the RHS to zero!
ResidualBasedBlockBuilderAndSolver: ATTENTION! setting the RHS to zero!
F...........................................................
======================================================================
FAIL: test_execution (SmallTests.SimplePatchTestThreeDMeshTying)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/philippb/software/Kratos_Master/applications/ContactStructuralMechanicsApplication/tests/contact_structural_mechanics_test_factory.py", line 78, in test_execution
    self.test.RunSolutionLoop()
  File "/home/philippb/software/Kratos_Master/kratos/python_scripts/analysis_stage.py", line 69, in RunSolutionLoop
    self.FinalizeSolutionStep()
  File "/home/philippb/software/Kratos_Master/kratos/python_scripts/analysis_stage.py", line 141, in FinalizeSolutionStep
    process.ExecuteFinalizeSolutionStep()
  File "/home/philippb/software/Kratos_Master/kratos/python_scripts/from_json_check_result_process.py", line 134, in ExecuteFinalizeSolutionStep
    self.__check_values(node.Id, "Node", value, value_json, variable_name)
  File "/home/philippb/software/Kratos_Master/kratos/python_scripts/from_json_check_result_process.py", line 262, in __check_values
    self.assertTrue(isclosethis, msg=msg)
AssertionError: False is not true : Error checking Node #195 for variable DISPLACEMENT_Y results:
nan != -0.0416306; rel_tol=0.000001, abs_tol=0.001

----------------------------------------------------------------------
Ran 67 tests in 3.879s

FAILED (failures=1)
~~~

THIS BRANCH:
~~~
Running cpp unit tests ... 
...........F.............F..............F.......................F...................
Ran 84 of 795 test cases in 0.119897s. 4 failed:
    TestDualShapeFunctionDerivativesQuadrilateral2 Failed with message: 
        Error: YOUR INITIAL SPLITTING DOES NOT COINCIDE WITH THE CURRENT ONE

in /home/philippb/software/Kratos_Master/applications/ContactStructuralMechanicsApplication/tests/cpp_tests/test_derivatives.cpp:406:void Testing::TestDerivatives(ModelPart&, Condition::Pointer, Condition::Pointer, Condition::Pointer, Condition::Pointer, const vector<long unsigned int>&, Testing::IndexType, const vector<double>&, Testing::IndexType, Testing::DerivateToCheck, Testing::CheckLevel) [with long unsigned int TDim = 3ul; long unsigned int TNumNodes = 4ul; Condition::Pointer = intrusive_ptr<Condition>; Testing::IndexType = long unsigned int]

    TestJacobianDerivativesQuadrilateral2 Failed with message: 
        Error: YOUR INITIAL SPLITTING DOES NOT COINCIDE WITH THE CURRENT ONE

in /home/philippb/software/Kratos_Master/applications/ContactStructuralMechanicsApplication/tests/cpp_tests/test_derivatives.cpp:406:void Testing::TestDerivatives(ModelPart&, Condition::Pointer, Condition::Pointer, Condition::Pointer, Condition::Pointer, const vector<long unsigned int>&, Testing::IndexType, const vector<double>&, Testing::IndexType, Testing::DerivateToCheck, Testing::CheckLevel) [with long unsigned int TDim = 3ul; long unsigned int TNumNodes = 4ul; Condition::Pointer = intrusive_ptr<Condition>; Testing::IndexType = long unsigned int]

    TestMixedULMLinearSolverThreeDoFSystem Failed with message: 
        Error: Check failed because std::abs(ref_Dx[i] - Dx[i])/std::abs(ref_Dx[i]) = 0.0653955 is not near to 0.0 = 0 within the tolerance 0.05
in /home/philippb/software/Kratos_Master/applications/ContactStructuralMechanicsApplication/tests/cpp_tests/test_mixedulm_linear_solver.cpp:698:virtual void Testing::TestMixedULMLinearSolverThreeDoFSystem::TestFunction()

    TestShapeFunctionDerivativesQuadrilateral2 Failed with message: 
        Error: YOUR INITIAL SPLITTING DOES NOT COINCIDE WITH THE CURRENT ONE

in /home/philippb/software/Kratos_Master/applications/ContactStructuralMechanicsApplication/tests/cpp_tests/test_derivatives.cpp:406:void Testing::TestDerivatives(ModelPart&, Condition::Pointer, Condition::Pointer, Condition::Pointer, Condition::Pointer, const vector<long unsigned int>&, Testing::IndexType, const vector<double>&, Testing::IndexType, Testing::DerivateToCheck, Testing::CheckLevel) [with long unsigned int TDim = 3ul; long unsigned int TNumNodes = 4ul; Condition::Pointer = intrusive_ptr<Condition>; Testing::IndexType = long unsigned int]

Unittests: Finished running cpp unit tests! 
Unittests: 
Running python tests ... 
.................................................................F.
======================================================================
FAIL: test_execution (NightlyTests.ALMStaticEvolutionLoadFrictionTestContact)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/philippb/software/Kratos_Master/applications/ContactStructuralMechanicsApplication/tests/contact_structural_mechanics_test_factory.py", line 78, in test_execution
    self.test.RunSolutionLoop()
  File "/home/philippb/software/Kratos_Master/kratos/python_scripts/analysis_stage.py", line 69, in RunSolutionLoop
    self.FinalizeSolutionStep()
  File "/home/philippb/software/Kratos_Master/kratos/python_scripts/analysis_stage.py", line 141, in FinalizeSolutionStep
    process.ExecuteFinalizeSolutionStep()
  File "/home/philippb/software/Kratos_Master/kratos/python_scripts/from_json_check_result_process.py", line 134, in ExecuteFinalizeSolutionStep
    self.__check_values(node.Id, "Node", value, value_json, variable_name)
  File "/home/philippb/software/Kratos_Master/kratos/python_scripts/from_json_check_result_process.py", line 262, in __check_values
    self.assertTrue(isclosethis, msg=msg)
AssertionError: False is not true : Error checking Node #73 for variable AUGMENTED_NORMAL_CONTACT_PRESSURE results:
-1.0290924 != -1.0308019; rel_tol=0.000001, abs_tol=0.001

----------------------------------------------------------------------
Ran 67 tests in 3.420s

FAILED (failures=1)
~~~

NIGHTLY:
~~~
Running tests for ContactStructuralMechanicsApplication
.................................................................F.
======================================================================
FAIL: test_execution (NightlyTests.ALMStaticEvolutionLoadFrictionTestContact)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/Kratos/applications/ContactStructuralMechanicsApplication/tests/contact_structural_mechanics_test_factory.py", line 78, in test_execution
    self.test.RunSolutionLoop()
  File "/home/ubuntu/Kratos/kratos/python_scripts/analysis_stage.py", line 69, in RunSolutionLoop
    self.FinalizeSolutionStep()
  File "/home/ubuntu/Kratos/kratos/python_scripts/analysis_stage.py", line 141, in FinalizeSolutionStep
    process.ExecuteFinalizeSolutionStep()
  File "/home/ubuntu/Kratos/kratos/python_scripts/from_json_check_result_process.py", line 134, in ExecuteFinalizeSolutionStep
    self.__check_values(node.Id, "Node", value, value_json, variable_name)
  File "/home/ubuntu/Kratos/kratos/python_scripts/from_json_check_result_process.py", line 262, in __check_values
    self.assertTrue(isclosethis, msg=msg)
AssertionError: False is not true : Error checking Node #73 for variable AUGMENTED_NORMAL_CONTACT_PRESSURE results:
-1.0290924 != -1.0308019; rel_tol=0.000001, abs_tol=0.001

----------------------------------------------------------------------
Ran 67 tests in 105.586s
~~~

**Comment by philbucher** [comment]
@loumalouomega if you need more time then I suggest I slightly change this, such that the computing-mp is optional
Then you can take as much time as you need :)

**Comment by loumalouomega** [comment]
> @loumalouomega if you need more time then I suggest I slightly change this, such that the computing-mp is optional
> Then you can take as much time as you need :)

Thanks, that would be very helpful

**Comment by ddiezrod** [comment]
@philbucher Just out of curiosity, if you use the main model part or a submodelpart from it as computing model part, how do you solve coupled problems where you have two different solvers?

**Comment by philbucher** [comment]
@ddiezrod different solvers have different (Main)ModelParts

**Comment by ddiezrod** [comment]
@philbucher So you have different nodes and pass the information from one side to the other at each iteration? What is the advantage in that case?

**Comment by philbucher** [comment]
Speaking for partitioned coupling (FSI etc), this is what we (Chair of Structural Analysis @TUM/Munich) mostly do (=> what the CoSimulationApp does)

Yes we have completely independent Models. Advantages:
- We can use existing solvers as black-box, without having to know anything abt the inside implementation and stuff
- We can respect the different requirements of the physics easily by having non-matching meshes on the interface. E.g. in FSI, Fluid typically requires a very fine mesh in the boundary layer to resolve the flow near the boundary, whereas the structural problem is fine with a coarser discretization
- Furthermore we can set up the models completely independent, which is a huge advantage for debugging them

The information is passed using a Mapper (=> MappingApplication)

I hope I didn't explain it too bad :)

**Comment by ddiezrod** [comment]
@philbucher Ok, I see. Its an interesting view, specially point 2. I am little worried about memory footprint though... Thanks very much for the explanation!

**Comment by philbucher** [comment]
alright, now the ComputingModelPart is **OPTIONAL** (by default is still used to not change the current behavior)

I will create an issue to discuss if the interface should (for pure structural cases) from now on not use the ComputingModelPart

**Review by loumalouomega — APPROVED** [review]
Thanks

**Pull request merged**
