### PR TITLE
[Travis] Turning some warnings into errors

### PR DESCRIPTION
**Pull request by philbucher**
This would turn some specific compiler warnings into errors
This is a draft, if @KratosMultiphysics/technical-committee agrees we can add more warnings to this list in the future

the first commit wont compile bcs there are currently some warnings, if it is accepted I can fix those

### CODE REVIEW

**Comment by maceligueta** [comment]
I like the idea of treating warnings as errors. @philbucher  It seems like you just activated two types of them. I am for activating as many types as possible.

**Comment by philbucher** [comment]
@maceligueta I added the two only for demonstration purposes

If @KratosMultiphysics/technical-committee agrees in general to this then ofc I will add more flags

@roigcarlo btw travis still attempts to run the tests even if the compilation failed, this I guess is not the intended behavior?

**Comment by roigcarlo** [comment]
@philbucher Not intended but known, Its a side effect.

I use different commands to compile, install and run. Non of them have any clue of what the other has done and Travis reports them separately (I have no way to query for the result of the previous step). In that case the error of the compilation will propagate to the other stages, but they still are going to be executed.

**Review by RiccardoRossi — DISMISSED** [review]
i don't think we should treat as error the unused variables.

there are corner cases in which you cannot avoid it, as it is needed in a pragma. for example if you deactivate openmp you'll get some of those

**Comment by philbucher** [comment]
@RiccardoRossi are you sure? So far Kratos managed to avoid it ...
This means you would leave such a warning forever?

@KratosMultiphysics/technical-committee here is the list of warnings that I propose to turn into errors. They are not hard to fix, so it wont impose additional work for the developer but will help to keep the code clean:
- maybe-uninitialized
- unused-variable
- suggest-override (this one I strongly recommend)
- return-type (if one forgets to return sth from a fct that is non-void)
- comparing different types (e.g. signed and unsigned int)
- misleading indentation, if parenthesis are missing, e.g 
~~~
if (....)
    line1;
    line2; // this one is not protected by the if
~~~

**Comment by loumalouomega** [comment]
+1 for the identification, I have seen error related in our code many times

**Comment by philbucher** [comment]
@RiccardoRossi I just compiled with omp disabled and there were no warnings abt unused variables

**Comment by pooyan-dadvand** [comment]
Technical Committee: Considered to be a good idea and @roigcarlo (with @philbucher help?) would try to add (incrementally) some warnings to travis first and then to appveyor.

**Comment by philbucher** [comment]
@roigcarlo I searched the travis script for a good location for adding the flags, but I am now sure if this is where you want them.

**Comment by RiccardoRossi** [comment]
Hi @philbucher are u SURE you compiled without fopenmp? I am pretty sure it should be problematic...

**Comment by philbucher** [comment]
@RiccardoRossi I don't have fopenmp in my configure-script and I used `KRATOS_EXCLUDE_OPENMP` to disable omp
Ofc there are then the warnings abt unused pragmas but nothing related to unused variables

Plus this is only activated in travis/appveyor and there no warnings are showing up atm

Once this is ready to be merged I will test it on my machine again, i.e. using the same flags and disable omp.

**Comment by roigcarlo** [comment]
To add flags related with warnings the proper place would be here:
https://github.com/KratosMultiphysics/Kratos/blob/master/scripts/build/travis/configure_travis_trusty.sh#L75-L76

At least for travis

**Comment by RiccardoRossi** [comment]
@roigcarlo wouldn't it be better to add those flags in the CMakeLists on the base of kratos (for gcc and clang) ? that way they would not be optional...

**Comment by philbucher** [comment]
@RiccardoRossi then they would even be enforced for development apps
At least my compilation is not always clean when I develop stuff

Only when it goes to master I think it should be clean => that why I thought Travis would be a good place for this

**Comment by roigcarlo** [comment]
Not sure we want to do that. The output with these flags can greatly vary between compiler versions ( and compilers themselves). I would say it is ok to have them under a controlled environment but adding them "on the wild" will not be very user friendly.

If you want we could add them to one of the builds types (FullDebug) for example.

**Comment by RiccardoRossi** [comment]
what about adding them here:

https://github.com/KratosMultiphysics/Kratos/blob/master/CMakeLists.txt#L91

(btw as i see the suggest_override is there already)

**Comment by philbucher** [comment]
Then while development Kratos would not even compile if one of those warnings is issued and turned into an error
=> suggest override is just a warning

Or think abt some other enviroments, e.g. a cluster on which some more warning might be issues due to reasons we cannot know/think of

or new compiler-versions / non-standard compilers might also make it impossible to compile...

**Comment by RiccardoRossi** [comment]
okk

**Comment by philbucher** [comment]
@roigcarlo I put the flags now in the place you suggested

@KratosMultiphysics/technical-committee now the following warnings are turned into errors **in Travis**:
- unused-variable
- misleading-indentation 
- return-type
- sign-compare
- suggest-override

**Comment by philbucher** [comment]
Works in Travis, i.e. currently none of the warnings I turn into errors is present
=> Kratos is quite clean atm

From my side I am done

@KratosMultiphysics/technical-committee feel free to approve and merge when convenient

**Comment by roigcarlo** [comment]
For me it is ok as well. If @RiccardoRossi agrees we can merge

**Comment by RiccardoRossi** [comment]
@roigcarlo to me ok. i am dismissing my review, i let you approve ...

**Comment by philbucher** [comment]
ping @roigcarlo :)

**Review by roigcarlo — APPROVED** [review]
Thought i approve it already sorry :+1:

**Comment by philbucher** [comment]
thx

**Comment by armingeiser** [comment]
Is there a "best practice" to fix of compiler warnings that are treated as errors? Doing it by fixing one, pushing, waiting for the Travis build can be really time consuming.
Locally i get many compiler warnings from the "rapidjson" library, so one can not really see the ones coming from the current changes.

**Comment by philbucher** [comment]
I see several options:
- disable the warnings from rapidjson. We can talk abt how to do this next week
- enable the same thing (turning warmings into errors) also locally by setting the compiler flags.

**Comment by pooyan-dadvand** [comment]
The idea is to have your code free of warnings in your compiler before uploading.

Nevertheless we can improve the situation to put some flags per compilers to force them all show more or less the same warnings that are set to error.

**Comment by loumalouomega** [comment]
The warnings of the rapidjson can disappear once I make work the nohlan json. Right now I am having problems due to the nature of the iterators and the adaptors

**Comment by philbucher** [comment]
@armingeiser you can also use the same compiler-flags as travis, then it will also not compile locally

**Pull request merged**
