### PR TITLE
Adding tests for PfemFluidApplication

### PR DESCRIPTION
**Pull request by jgonzalezusua**
Essentially we can summarize the changes in the following:
- We have added 3 small tests and (3) -> 1 nightly test. We run all of them in around 9 minutes in FullDebug.
- We replaced some std::cout by some KRATOS_INFO so that we can hide them when running the test.
- We added another parameter to the constructor of remesh_fluid_domains_process.py in order to avoid writing the totalvolumebeforemeshing.txt when running the test.
- The tests have been generated from two examples that have been uploaded in the Examples repository.

The only thing left is making those test run nightly... Do any of you know how to do that?

### CODE REVIEW

**Comment by josep-m-carbonell** [comment]
I think tests will not run nightly because Pfem is not compiled nightly. I don't remember if that had a relationship with the licence of the mesher in 3D. If not,  we can ask to add the applications to the nigthly build. 
To have an idea of the time taken by the tests you must run them when compilation is done in FullDebug. This is the way tests are run nigthly.

**Comment by ipouplana** [comment]
Thanks @josep-m-carbonell . Tomorrow we will run all tests in FullDebug and if they are too long we will shorten them.
Regarding nightly compilation and testing, we can ask Carlos Roig about that...

**Comment by maceligueta** [comment]
Just referencing @roigcarlo to know about the policy on submodules. Can we download them from Travis? Is there enough time left for it? I guess we are close to the limit.

**Comment by jgonzalezusua** [comment]
We have removed two tests in order to reduce the running time and in FullDebug we made it in 9 minutes using a slow PC. 
@AFranci, can you please look into this PR and tell us if it breaks something in your code?

**Comment by AFranci** [comment]
It looks fine to me! Thank you for working on the tests!

**Review by AFranci — APPROVED** [review]

**Comment by jgonzalezusua** [comment]
@roigcarlo Hi Carlos, do you know something about this error? Is it our fault?
image

**Comment by ipouplana** [comment]
@roigcarlo it seems travis already worked ;)

Regards

**Comment by roigcarlo** [comment]
Sorry for the late reply. no this happens sometimes. Is due to a network error on their side, just relaunch and should work fine

**Pull request merged**
