### PR TITLE
[Core] Adding SetStiffnessMatrixIsBuilt and GetStiffnessMatrixIsBuilt to ImplicitSolvingStrategy

### LINKED ISSUE #10109: Why is BaseType::mStiffnessMatrixIsBuilt always false in Residualbased_newton_raphson_strategy.h?
In the KratosCore,
Why is BaseType::mStiffnessMatrixIsBuilt always false in Residualbased_newton_raphson_strategy.h? 

In other words, how can only build and solve the RHS the first iteration.  BaseType::mRebuildLevel doesn't to anything now because in every call, a check for BaseType::mRebuilLevel  and BaseType::mStiffnessMatrixIsBuilt is done. While BaseType::mStiffnessMatrixIsBuild is always false. 

Is it required to copy SolveSolutionStep() in an inherited class, copy everything and add BaseType::mStiffnessMatrixIsBuild = True?

### PR DESCRIPTION
**Pull request by loumalouomega**
**📝 Description**

Adding SetStiffnessMatrixIsBuilt and GetStiffnessMatrixIsBuilt to ImplicitSolvingStrategy

Fixes https://github.com/KratosMultiphysics/Kratos/issues/10109

**🆕 Changelog**

- Adding SetStiffnessMatrixIsBuilt and GetStiffnessMatrixIsBuilt to ImplicitSolvingStrategy
- Moving build level methods to Access category

### CODE REVIEW

**Comment by loumalouomega** [comment]
Related  #10109

**Comment by loumalouomega** [comment]
Ping @KratosMultiphysics/technical-committee

**Comment by loumalouomega** [comment]
> Ping @KratosMultiphysics/technical-committee

👋

**Comment by roigcarlo** [comment]
@KratosMultiphysics/technical-committee agrees with the changes, but please ensure to make the minimal changes for the PR (if you want to move a function make another PR)

**Comment by loumalouomega** [comment]
> @KratosMultiphysics/technical-committee agrees with the changes, but please ensure to make the minimal changes for the PR (if you want to move a function make another PR)

Done, I will move back after merge of this

**Review by roigcarlo — APPROVED** [review]

**Pull request merged**
