### PR TITLE
Adding references to definition of mrModelPart

### PR DESCRIPTION
**Pull request by pooyan-dadvand**
I have notice that some classes in Kratos are storing mrModelPart as a copy and not as a reference. Although it may work in these cases but results in a memory overhead by having several copies of the modelpart and its sub modelparts.

So I have added references to definition of mrModelPart and change the corresponding constructors. I found them by a grep of mrModelPart. So if there are classes with other member name I have not found them.

### CODE REVIEW

**Review by loumalouomega — APPROVED** [review]
Good improvement

**Comment by RiccardoRossi** [comment]
in this line, wouldn't it make sense to make the modelpart NON copy constructible?

**Comment by pooyan-dadvand** [comment]
Or maybe we should put the copy constructor explicit. So you can copy it if you explictly call it.

**Comment by RiccardoRossi** [comment]
+1 for making it explicit

**Pull request merged**
