### PR TITLE
[Core] Use bdf1 coefficients if prev_delta_time close to zero

### PR DESCRIPTION
**Pull request by ddiezrod**
I make the change here discussed in https://github.com/KratosMultiphysics/Kratos/issues/5515

### CODE REVIEW

**Review by rubenzorrilla — APPROVED** [review]

**Comment by philbucher** [comment]
I will have a look by tmr

**Review by rubenzorrilla — CHANGES_REQUESTED** [review]
MeshMovingApplication test cases crash.

**Comment by ddiezrod** [comment]
@philbucher @rubenzorrilla 

I found a bug in MovingMeshApplication that is causing this. There is a set_and_fill_buffer function in mesh_base_solver. It is supposed to clone the required time steps to fill the buffer size. Problem is that it does this using as delta_time the value from ProcessInfo:

https://github.com/KratosMultiphysics/Kratos/blob/e1b170c985dd6733364776cd21e3a064c61ca979/applications/MeshMovingApplication/python_scripts/mesh_solver_base.py#L188

But at the time this function is called, delta_time has not being assigned and therefore it simply clones the time step, several times over time = 0.0. That is why even if buffer is filled TIME and DELTA_TIME are always zero, and therefore the check I just changed is used.

My point is that this delta_time should be computed from time_step settings (so, something != 0.0) and therefore my check should never be used.

This will change anyway the result of the test, which I consider is wrong right now. In my experience is much better to have small unit tests for each part of the code rather than this full regression test. (Or at least have both)

**Comment by philbucher** [comment]
I know that this can be a problem, sorry for the inconvenience
I will take a look asap

**Comment by ddiezrod** [comment]
@philbucher I think it can be solved just by doing in the mentioned line

`delta_time = self.settings["time_stepping"]["time_step"].GetDouble()`

that could moved to a function so you avoid code duplication with AdvanceInTime and it is ready to be overrided by other solver if needed.

**Comment by philbucher** [comment]
@ddiezrod unfortunately it is not that easy in this case, the mesh solver itself does not require time(-integration)
However if it is used together with the fluid solver (ALE), then it does need it for the computation of the mesh-velocity (which is what fails now). The problem there is that the the Fluid solver controls the timestep and we don't have access to it from the mesh solver (and as you pointed out it is not yet available at the beginning).

I will think abt sth

BTW we have the same situation in the Structural Solver where this was copy pasted from :D
@RiccardoRossi maybe you have a comment :)

**Review by loumalouomega — COMMENTED** [review]
Can you apply this to the bdf schemes too?

**Comment by philbucher** [comment]
> Can you apply this to the bdf schemes too?

I suggest to refactor the bdf schemes to use the `time_discretization` then this will automatically be included

**Comment by loumalouomega** [comment]
> > Can you apply this to the bdf schemes too?
> 
> I suggest to refactor the bdf schemes to use the `time_discretization` then this will automatically be included

I was suggesting that, sorry if it wasn't clear

**Comment by loumalouomega** [comment]
BTW, travis fails

**Comment by ddiezrod** [comment]
@loumalouomega sure, I will apply the changes there. Some tests are failing in MeshMovingApp because buffer is not being correctly filled in the tests. @philbucher is thinking something to fix it.

**Comment by philbucher** [comment]
> @loumalouomega sure, I will apply the changes there. Some tests are failing in MeshMovingApp because buffer is not being correctly filled in the tests. @philbucher is thinking something to fix it.

thanks a lot, but please in a separate PR :)

**Comment by philbucher** [comment]
So @AndreasWinterstein and I had a long discussion abt this:
Basically the point  was that we are not sure what is better for the stability (especially in FSI) and the order of the time integration if we start with a BDF1 compared to BDF2 with a "fake" previous step
We had a [PhD Thesis](https://mediatum.ub.tum.de/doc/1223319/1223319.pdf) doing a small investigation (page 38-39)
Our concern is that we lower the order to 1 order if we start with BDF1 (this is basically the outcome of the investigation in the thesis)
We are however not sure if 1. these findings are also applicable to "real" problems and 2. if the "fake" timestep bdf2 is better

**Conclusion:**
For now I will update the results in the MeshMovingApp.
In case this will actually become problematic with our FSI cases, then I will reopen this discussion again

**Comment by philbucher** [comment]
> So @AndreasWinterstein and I had a long discussion abt this:
> Basically the point was that we are not sure what is better for the stability (especially in FSI) and the order of the time integration if we start with a BDF1 compared to BDF2 with a "fake" previous step
> We had a [PhD Thesis](https://mediatum.ub.tum.de/doc/1223319/1223319.pdf) doing a small investigation (page 38-39)
> Our concern is that we lower the order to 1 order if we start with BDF1 (this is basically the outcome of the investigation in the thesis)
> We are however not sure if 1. these findings are also applicable to "real" problems and 2. if the "fake" timestep bdf2 is better
> 
> **Conclusion:**
> For now I will update the results in the MeshMovingApp.
> In case this will actually become problematic with our FSI cases, then I will reopen this discussion again

I updated the results in the MeshMovingApp. We will test this more in the future but for now I suggest to merge this @ddiezrod 
ping @rubenzorrilla

**Comment by ddiezrod** [comment]
@philbucher Thank you very much! @rubenzorrilla can you approve this?

**Review by rubenzorrilla — APPROVED** [review]
Sorry, I didn't note that I was the blocker.

**Pull request merged**
