### PR TITLE
[Iga] Allow Strong Supports

### PR DESCRIPTION
**Pull request by tteschemacher**
Hi,

I am adding hear the search to the nodes which are on the boundaries of certain nurbs curve or surface geometries.

And a beautiful test ;)

### CODE REVIEW

**Comment by philbucher** [comment]
looks good to me

unfortunately a change in geometry.h xD

**Comment by tteschemacher** [comment]
> 
> 
> looks good to me
> 
> unfortunately a change in geometry.h xD

Thanks. The change in geometry.h is due to PR #6800, which I think needs a decission from the @KratosMultiphysics/technical-committee

**Review by dagmawibekel — COMMENTED** [review]
Unfortnuately the tests are failing.

**Comment by tteschemacher** [comment]
Even more core changes, I think you like this @philbucher ? ;)

**Comment by tteschemacher** [comment]
@dagmawibekel , @philbucher let's end the party here?

**Comment by philbucher** [comment]
> @dagmawibekel , @philbucher let's end the party here?

But
But

It is just getting started ...

**Comment by tteschemacher** [comment]
na, na, no one wants this party here anymore. People are sick of the noise. People want a merged quietness.

**Review by dagmawibekel — APPROVED** [review]

**Comment by tteschemacher** [comment]
The dream 💯 thanks

**Pull request merged**
