### PR TITLE
[core] Adding aliasing check to matrix

### PR DESCRIPTION
**Pull request by pooyan-dadvand**
This PR adds a debug aliasing check to matrix constructor and assignment operators (=, +=, -=) and provides the corresponding function for all expressions in AMatrix and Kratos.

### CODE REVIEW

**Comment by jcotela** [comment]
I am adding a collection of debug-only tests for aliasing, which seem to work as intended. Please check if I misunderstood some of the tested cases and feel free to suggest more tests.

Regarding the PR itself, the only thing I don't understand is why it is needed to check for aliasing on copy construction, but I may be missing something here.

**Comment by pooyan-dadvand** [comment]
@jcotela you are right with constructor! I was considering the dual space in this case!! 🤓 😆

**Comment by pooyan-dadvand** [comment]
@jcotela thanks for adding tests, I had them in AMatrix but not migrate it here....

**Comment by pooyan-dadvand** [comment]
I was doing the same!

**Comment by pooyan-dadvand** [comment]
@jcotela would you please also take out the check in the constructor as you were mentioning?

**Comment by RiccardoRossi** [comment]
we were in 3 doing the same :-)

**Comment by RiccardoRossi** [comment]
i just committed a minor addition to the tests to check that

      noalias(A) = prod(A,B) 

throws

**Review by RiccardoRossi — DISMISSED** [review]

**Comment by jcotela** [comment]
@pooyan-dadvand I removed the check in the copy constructor. I think this is basically done, but I'd rather not approve myself.

**Comment by pooyan-dadvand** [comment]
I cannot approve my PR neither... @RiccardoRossi would you please approve it?

**Review by RiccardoRossi — APPROVED** [review]

**Review by RiccardoRossi — DISMISSED** [review]

**Review by jcotela — APPROVED** [review]
re-approving, since apparently the merge is blocking us now.

**Pull request merged**
