### PR TITLE
[Core][Logger] Logger color and prefix - improve visibility of warnings

### PR DESCRIPTION
**Pull request by armingeiser**
This is an attempt to improve the logging as discussed in #5620. 

Currently warning messages look the same as messages in other severity levels. This makes it very hard to filter them among many other logging lines. In order to make them more visible this PR adds the possibility to highlight logger messages with a prefix and/or colors.
Like this it is easier to see them in the terminal output, and search them in a log file using a unique search key.

The mechanism is the same as for setting the severity and works for one message at the time.
After every message, the color is reset to the default. 

E.g. Warning messages are modified to:

```[WARNING] label: message```

if colored logging is activated, warning messages will also be printed in yellow.
This applies to both, messages from python and cpp.

without coloring:
image
with coloring:
image

### CODE REVIEW

**Review by loumalouomega — CHANGES_REQUESTED** [review]
This is a duplication, please use #include "utilities/color_utilities.h"

All the colors are there, or can be extended, and it takes into consideration if using Windows

**Comment by armingeiser** [comment]
@loumalouomega thanks, wasn't aware of this. I will definitely make use of those definitions. instead of the MessageColor class. The flag  `KRATOS_LOGGER_USE_COLORS` could then probably also be removed.

I could solve both prefix and color also using if else:
```cpp
    void LoggerOutput::WriteMessage(LoggerMessage const& TheMessage)
    {
        auto message_severity = TheMessage.GetSeverity();
        if (TheMessage.WriteInThisRank() && message_severity <= mSeverity)
        {
            if (message_severity == LoggerMessage::Severity::WARNING)
                mrStream << KYEL << "[WARNING]" ;

            if(TheMessage.IsDistributed())
                mrStream << "Rank " << TheMessage.GetSourceRank() << ": ";

            if(TheMessage.GetLabel().size())
                mrStream << TheMessage.GetLabel() << ": " << TheMessage.GetMessage();
            else
                mrStream << TheMessage.GetMessage();

            if (message_severity == LoggerMessage::Severity::WARNING)
                mrStream << RST;
        }
    }
```

thats much less changes just not customizable.

**Comment by philbucher** [comment]
I added this to the committee TODO

**Review by pooyan-dadvand — CHANGES_REQUESTED** [review]
I think that imposing the prefix in the Logger level is to sever as it imposes it to all outputs. On the other side, you have all the information to do this in the output itself and let the customization door open.

**Comment by roigcarlo** [comment]
@KratosMultiphysics/technical-committee agrees on having output colors in the screen. However, this has to be an **optional** feature (by default OFF) that it is switched on by a **compilation flag**. The reasoning of this is that this kind of capabilities might not be supported in HPC platforms neither in output to file nor in some terminals.

Having said this, we agree on:
- Convergence --> Green
- No convergence --> Red
- Warnings --> Yellow

**Comment by loumalouomega** [comment]
> 
> 
> @KratosMultiphysics/technical-committee agrees on having output colors in the screen. However, this has to be an **optional** feature (by default OFF) that it is switched on by a **compilation flag**. The reasoning of this is that this kind of capabilities might not be supported in HPC platforms neither in output to file nor in some terminals.
> 
> Having said this, we agree on:
> 
>     * Convergence --> Green
> 
>     * No convergence --> Red
> 
>     * Warnings --> Yellow

Just to mention I am considering those colors, but as I use Solarized terminal color scheme it changes green to gray

**Comment by loumalouomega** [comment]
BTW: https://github.com/fmtlib/fmt

**Comment by armingeiser** [comment]
* The prefix was added in #5700.
* There is a cleaner PR about the colors #6124 

So i will close this as it is not needed anymore.

**Pull request closed without merging**
