### PR TITLE
[Discussion][StructuralMechanics] defaulting to implicit time-integration

### PR DESCRIPTION
**Pull request by philbucher**
same as is done in contact

Should the user have to specify the time-integration-method or not?

What do others think?

### CODE REVIEW

**Review by loumalouomega — APPROVED** [review]
OK for me, in any case we need a less "cutre" solution. The wrapper has it own problems

**Comment by philbucher** [comment]
what is "cutre"? 

Are there still problems with the wrappers? I thought those were solved in the meantime?

**Comment by loumalouomega** [comment]
> what is "cutre"?
> 
> Are there still problems with the wrappers? I thought those were solved in the meantime?

Billig in german is quite close

**Comment by loumalouomega** [comment]
> what is "cutre"?
> 
> Are there still problems with the wrappers? I thought those were solved in the meantime?

We should have a more integrated solution, but for now is OK

**Comment by philbucher** [comment]
ok

**Comment by philbucher** [comment]
seems like none is against it, merging

**Pull request merged**
