### PR TITLE
[ExternalSolversApplication] Excluding Pastix from Cotire

### PR DESCRIPTION
**Pull request by loumalouomega**

### CODE REVIEW

**Review by roigcarlo — APPROVED** [review]

**Review by RiccardoRossi — COMMENTED** [review]
why so? i routinely compile with cotire

**Review by RiccardoRossi — CHANGES_REQUESTED** [review]
please take a look at my comment before merging (blocking for this reason)

**Comment by loumalouomega** [comment]
The output I got is the following:

~~~
/home/vicente/src/Kratos/applications/ExternalSolversApplication/external_includes/pastix_complex_solver.h:171: referencia a `z_pastix(pastix_data_t**, int, int, int*, int*, std::complex<double>*, int*, int*, std::complex<double>*, int, int*, double*)' sin definir
clang: error: linker command failed with exit code 1 (use -v to see invocation)
~~~

**Comment by RiccardoRossi** [comment]
i have the impression that you did not compkle the complex version of the
lib

**Comment by loumalouomega** [comment]
How do I compile the complex version?

**Comment by RiccardoRossi** [comment]
i thimk it js in the pastix makefle

**Comment by marandra** [comment]
Just to mention that I am getting the same error, with Clang and GCC.

For installing Pastix, I followed directions in the wiki, so probably @loumalouomega  and I have the same version.

**Comment by loumalouomega** [comment]
One thing, I tried the new version 6.0 https://gitlab.inria.fr/solverstack/pastix and they changed the API, maybe we need to update the solver too.

**Comment by loumalouomega** [comment]
@RiccardoRossi if I uncomment the part relative to complex number in config.in I cannot comile the ExternalSolverApplication later, even without Cotire:

~~~sh
# Uncomment the following lines for float=complex support
VERSIONFLT  = _complex
CCTYPESFLT := $(CCTYPESFLT) -DTYPE_COMPLEX
~~~

**Comment by loumalouomega** [comment]
Can you share your config.in? @RiccardoRossi

**Comment by loumalouomega** [comment]
Besides, did you know this solver from INRIA? https://gitlab.inria.fr/solverstack/fabulous

**Comment by loumalouomega** [comment]
Any hint why?

**Comment by RiccardoRossi** [comment]
**
    HOSTARCH=i686_pc_linux
    VERSIONBIT=_32bit
    EXEEXT=
    OBJEXT=.o
    LIBEXT=.a
    CCPROG=gcc -Wall
    CFPROG=f77
    CCFOPT=-O3     _CCFLAGS_
    CCFDEB=-O0 -g3 _CCFLAGS_
    #-g3 pour avoir les macros dans gdb

    LKFOPT=
    MKPROG=make 
    MPCCPROG=mpicc -Wall
    ARFLAGS=ruv
    ARPROG=ar
    EXTRALIB=-lblas -lg2c -lm -lrt _LDFLAGS_

    VERSIONMPI=_mpi
    VERSIONSMP=_smp
    VERSIONSCH=_static
    VERSIONINT=_int
    VERSIONPRC=_simple
    VERSIONFLT=_real
    VERSIONORD=_scotch

    # uncomment the following lines for integer=long support
    #VERSIONINT=_long
    #CCPROG:=$(CCPROG) -DFORCE_LONG
    #MPCCPROG:=$(MPCCPROG) -DFORCE_LONG

    # uncomment the following lines for double precision support
    VERSIONPRC=_double
    CCPROG:=$(CCPROG) -DFORCE_DOUBLE
    MPCCPROG:=$(MPCCPROG) -DFORCE_DOUBLE

    # uncomment the following lines for float=complex support
    #VERSIONFLT=_complex
    #CCPROG:=$(CCPROG) -DFORCE_COMPLEX
    #MPCCPROG:=$(MPCCPROG) -DFORCE_COMPLEX

    # uncomment the following lines for sequential (NOMPI) version
    #VERSIONMPI=_nompi
    #CCPROG:=$(CCPROG) -DFORCE_NOMPI
    #MPCCPROG:=$(CCPROG)
    _MPCCPROG_

    # uncomment the following lines for non-threaded (NOSMP) version
    #VERSIONSMP=_nosmp
    #CCPROG:=$(CCPROG) -DFORCE_NOSMP
    #MPCCPROG:=$(MPCCPROG) -DFORCE_NOSMP

    # uncomment the following lines for local allocation (SMP version)
    # CCPROG:=$(CCPROG) -DNUMA_ALLOC
    # MPCCPROG:=$(MPCCPROG) -DNUMA_ALLOC

    # uncomment the following lines for using metis ordering 
    #VERSIONORD=_metis
    #METIS_HOME= metis-4.0
    #CCPROG:=$(CCPROG) -DMETIS
    #MPCCPROG:=$(MPCCPROG) -DMETIS
    #EXTRALIB:=$(EXTRALIB) -L$(METIS_HOME) -lmetis 


    #
    # MARCEL
    #
    #flags de bases pour marcel
    # CFLAGS_MARCEL=`pm2-config --cflags` -I${PM2_ROOT}/marcel/include/pthread
    #Flag pour l'utilistaion des bulles
    # CFLAGS_MARCEL:=${CFLAGS_MARCEL} -DPASTIX_DYNSCHED -DPASTIX_BUBBLESCHED
    # VERSIONSCH=dyn
    # Flag pour attibuée aux bulles parentes les sous-arbres de charge faible
    #CFLAGS_MARCEL:=${CFLAGS_MARCEL} -DPASTIX_DYNSCHED_OVERHEAD

    # VERSIONSMP:=$(VERSIONSMP)_marcel
    CCFOPT:=$(CCFOPT) $(CFLAGS_MARCEL)
    CCFDEB:=$(CCFDEB) $(CFLAGS_MARCEL)
    # EXTRALIB:=$(EXTRALIB) `pm2-config --libs`
    # EXTRALIB:=$(EXTRALIB) -lpthread
  **

**Comment by loumalouomega** [comment]
Can you please you attach the file?, It is difficult to try to identify what is what in my configuration file

**Comment by loumalouomega** [comment]
I solve the problem, I wasn't compiling using 

    make all_unity install/fast

**Pull request closed without merging**
