### PR TITLE
[Travis] deactivate CSharpApp until tests are fixed

### PR DESCRIPTION
**Pull request by philbucher**
title says all
There is a test failing randomly which blocks other PRs from being merged

@loumalouomega your solution was not working bcs the cpp-tests are run from somewhere else, the only way to deactivate is to temp remove the App from travis

### CODE REVIEW

**Review by loumalouomega — DISMISSED** [review]
OK, all this work for nothing :(

**Comment by philbucher** [comment]
:/ 

Well an alternative solution would be to comment the failing C-test, then it could remain in Travis
What so you think?

**Comment by loumalouomega** [comment]
I prefer to comment the checks on the c tests, and keep the compilation, that way at least we know that the compilation is not broken (like last time)

**Review by loumalouomega — DISMISSED** [review]
I agree with myself

**Comment by philbucher** [comment]
Thx
Now there is another error in Travis

**Comment by loumalouomega** [comment]
unused variable

**Review by loumalouomega — APPROVED** [review]

**Pull request merged**
