### PR TITLE
[MeshingApplication] Moving SPR test examples to Examples repository

### PR DESCRIPTION
**Pull request by loumalouomega**
This helps to reduce the size of the repo

### CODE REVIEW

**Review by AlejandroCornejo — APPROVED** [review]
okkey @loumalouomega

**Comment by philbucher** [comment]
does this also fix the error in the nightly tests?

**Comment by loumalouomega** [comment]
> does this also fix the error in the nightly tests?

This is a test_example, is not run on the server. What error do your mean?

**Comment by philbucher** [comment]
~~~
Running tests for MeshingApplication
...
  ## Warning: _MMG5_surf: at least 1 negative or null density.
E.
======================================================================
ERROR: test_execution (meshing_application_test_factory.ThreeDShellTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/Kratos/applications/MeshingApplication/tests/meshing_application_test_factory.py", line 69, in tearDown
    self.test.Finalize()
  File "/home/ubuntu/Kratos/kratos/python_scripts/analysis_stage.py", line 115, in Finalize
    process.ExecuteFinalize()
  File "/home/ubuntu/Kratos/kratos/python_scripts/compare_two_files_check_process.py", line 88, in ExecuteFinalize
    self.__CompareSolMetricFile()
  File "/home/ubuntu/Kratos/kratos/python_scripts/compare_two_files_check_process.py", line 322, in __CompareSolMetricFile
    lines_ref, lines_out = self.__GetFileLines()
  File "/home/ubuntu/Kratos/kratos/python_scripts/compare_two_files_check_process.py", line 111, in __GetFileLines
    raise Exception(err_msg)
Exception: The specified reference file name "/home/ubuntu/Kratos/applications/MeshingApplication/tests/mmg_lagrangian_test/test_remesh_shell_result.sol" is not valid!

----------------------------------------------------------------------
Ran 5 tests in 40.084s
~~~

Aren't you checking the nightly-build-reports?

**Comment by loumalouomega** [comment]
> ```
> Running tests for MeshingApplication
> ...
>   ## Warning: _MMG5_surf: at least 1 negative or null density.
> E.
> ======================================================================
> ERROR: test_execution (meshing_application_test_factory.ThreeDShellTest)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/home/ubuntu/Kratos/applications/MeshingApplication/tests/meshing_application_test_factory.py", line 69, in tearDown
>     self.test.Finalize()
>   File "/home/ubuntu/Kratos/kratos/python_scripts/analysis_stage.py", line 115, in Finalize
>     process.ExecuteFinalize()
>   File "/home/ubuntu/Kratos/kratos/python_scripts/compare_two_files_check_process.py", line 88, in ExecuteFinalize
>     self.__CompareSolMetricFile()
>   File "/home/ubuntu/Kratos/kratos/python_scripts/compare_two_files_check_process.py", line 322, in __CompareSolMetricFile
>     lines_ref, lines_out = self.__GetFileLines()
>   File "/home/ubuntu/Kratos/kratos/python_scripts/compare_two_files_check_process.py", line 111, in __GetFileLines
>     raise Exception(err_msg)
> Exception: The specified reference file name "/home/ubuntu/Kratos/applications/MeshingApplication/tests/mmg_lagrangian_test/test_remesh_shell_result.sol" is not valid!
> 
> ----------------------------------------------------------------------
> Ran 5 tests in 40.084s
> ```
> 
> Aren't you checking the nightly-build-reports?

For now are quite not human readable :P, sorry I haven't checked in a week. I will take  a look

**Comment by loumalouomega** [comment]
It works fine in my machine, @philbucher this error is because the file is not found in the machine?

**Comment by loumalouomega** [comment]
OK, I discovered that I need to update the version of MMG. I need to update some results too

**Comment by loumalouomega** [comment]
#4547 updates the precompiled library

**Comment by loumalouomega** [comment]
#4548 will fix the rest of the tests

**Pull request merged**
