### PR TITLE
[CconstitutiveLawsApp] Increase stability when Dissipation->1.0

### PR DESCRIPTION
**Pull request by AlejandroCornejo**
adding a condition when dissipation reaches 1.0 (numerical instabilities arise)

### CODE REVIEW

**Comment by SergioJimenezReyes** [comment]
Nice!

**Comment by SergioJimenezReyes** [comment]
Fine to me, I found problems when kp nearly is =1 so this will help a lot with stability.

**Review by SergioJimenezReyes — DISMISSED** [review]

**Review by loumalouomega — DISMISSED** [review]
We should update the equivalent finite strain versions

**Comment by AlejandroCornejo** [comment]
> We should update the equivalent finite strain versions

DONE

**Review by loumalouomega — DISMISSED** [review]

**Review by SergioJimenezReyes — DISMISSED** [review]

**Comment by AlejandroCornejo** [comment]
**the result now is** 
image
 and **previously** was:
image

**Comment by SergioJimenezReyes** [comment]
I have been working on this for the last week as the proposed solution broke the kinematic plasticity. The 0 stress condition is too strong. I have come out with a solution and an alternative hardening curve to overcome the the issue. I will commit the changes soon.

**Comment by AlejandroCornejo** [comment]
The test are passing, merge when possible Sergio

**Comment by AlejandroCornejo** [comment]
Ups, I am the one that created the PR haha plas @SergioJimenezReyes approve the PR

**Review by SergioJimenezReyes — APPROVED** [review]
Nice to me. Finally, it has not been necessary to modify the finite strain laws @loumalouomega

**Pull request merged**
