### PR TITLE
[StructuralApplication] Removing old StructuralApplication

### PR DESCRIPTION
**Pull request by loumalouomega**
StructuralApplication is 100% legacy code, doesn' even compile with pybind and anyway we have several backups in the old releases

Additionally this reduces confusion with newcomers

### CODE REVIEW

**Comment by vryy** [comment]
what are the components that do not compile with pybind?

**Comment by loumalouomega** [comment]
Everything that is exported to python, in the current master branch the application does not compile

**Comment by vryy** [comment]
Is that pybind advertised to compile similarly to boost.python and no intervention is required?

**Comment by loumalouomega** [comment]
> Is that pybind advertised to compile similarly to boost.python and no intervention is required?

Yes:

https://github.com/KratosMultiphysics/Kratos/wiki/Porting-to-PyBind11---common-steps

**Comment by philbucher** [comment]
Also it will be completely broken when switching to AMatrix
There are no tests at all!

**Comment by josep-m-carbonell** [comment]
@philbucher and @loumalouomega, are you kicking out an application without asking the mantainer fisrt? . It is the way to go from now on? Maybe you can help the mantainer to keep the compatibility instead of pushing him and his team out.

**Comment by loumalouomega** [comment]
The maintainer is @vryy

**Comment by loumalouomega** [comment]
> @philbucher and @loumalouomega, are you kicking out an application without asking the mantainer fisrt? . It is the way to go from now on? Maybe you can help the mantainer to keep the compatibility instead of pushing him and his team out.

I will expand my explanation, I was not at home. The application is legacy, but of course I expected to @vryy to ask a way to keep the application up to date, and in fact he did. 

I was not planning to merge without his explicit concern, and anyway as I said in the first comment is easy to revert and restore the application.

**Comment by RiccardoRossi** [comment]
@vryy the structural mechanics is long unmantained (in the master branch). For example it has not been ported to pybind (a change that happend around 1 year ago) nor to the change in the model.
Additionally, the constitutive laws have also not be ported to the newer format and they will be incompatible once we remove the old API (you were mentioned in the PR)

taking all of this into account i would agree with @loumalouomega and @philbucher that the application is pure legacy and we should consider removing it, particularly taking into account that the relevant parts were ported to the StructuralMechanicsApplication for quite some time now.

Nevertheless i think that we shall not do this without a (well, another) word of warning, even outside of github. I'll block for now, until we speak "in voice" with @vryy (i will also try to reach Prof. Meschke to speak about this)

**Review by RiccardoRossi — CHANGES_REQUESTED** [review]
blocking until speaking with the persons involved

**Comment by loumalouomega** [comment]
> @vryy the structural mechanics is long unmantained (in the master branch). For example it has not been ported to pybind (a change that happend around 1 year ago) nor to the change in the model.
> Additionally, the constitutive laws have also not be ported to the newer format and they will be incompatible once we remove the old API (you were mentioned in the PR)
> 
> taking all of this into account i would agree with @loumalouomega and @philbucher that the application is pure legacy and we should consider removing it, particularly taking into account that the relevant parts were ported to the StructuralMechanicsApplication for quite some time now.
> 
> Nevertheless i think that we shall not do this without a (well, another) word of warning, even outside of github. I'll block for now, until we speak "in voice" with @vryy (i will also try to reach Prof. Meschke to speak about this)

Agreed, I should have blocked myself

**Comment by pooyan-dadvand** [comment]
@RiccardoRossi have you contacted @vryy ?

It would be great to remove this app for the release.

**Comment by RiccardoRossi** [comment]
as discussed in @KratosMultiphysics/technical-committee this will go forward after speaking with the mantainers at the workshop

**Pull request closed without merging**
