### PR TITLE
[Ci] Docker: specify mmg install dir for 5.5.1

### PR DESCRIPTION
**Pull request by philbucher**
**Description**
this should fix the CI

In the future we should not install external libs in the root but in their dedicated folders to avoid interaction issues

### CODE REVIEW

**Comment by marcnunezc** [comment]
This might require to change the configure files? 

https://github.com/KratosMultiphysics/Kratos/blob/6d4eb17043de165502b69f93d1c599f843633f76/.github/workflows/configure.sh#L70-L71

**Review by loumalouomega — DISMISSED** [review]
Yep

**Comment by loumalouomega** [comment]
> This might require to change the configure files?
> 
> https://github.com/KratosMultiphysics/Kratos/blob/6d4eb17043de165502b69f93d1c599f843633f76/.github/workflows/configure.sh#L70-L71

Yep

**Comment by philbucher** [comment]
I am not changing the path for 5.4, only for the (not yet used 5.5) hence it should work as is

**Comment by philbucher** [comment]
hm now we have a hen-egg problem
I disabled MMG temporarily, will enable it again once the docker image is built
sorry for the inconvenience

**Comment by philbucher** [comment]
can someone approve please?
Merging PRs is blocked...

**Review by marcnunezc — APPROVED** [review]

**Pull request merged**
