### PR TITLE
[dem] Avoid creating rigid bodies from SubModelParts coming from couplings

### PR DESCRIPTION
**Pull request by maceligueta**
When the walls are the skin of a flexible structure, transferred by some coupling algorithm, they must not be a RigidBody. So there's no need to assign any scheme or information relative to rigid bodies. This is not necessary when you are transferring to the parent modelpart od DEM Walls, but is very necessary if you decide to tranfer the skin of a structure **to a SubModelPart** of the DEM Walls ModelPart. 
All this will disappear when the DEM migrates to a more json-based input, where probably a process will convert selected SubModelParts into rigid bodies, leaving the rest as just SubModelParts.

### CODE REVIEW

**Comment by maceligueta** [comment]
@AlejandroCornejo and @JoseMGonzalez-UPC , this might be of your interest

**Comment by farrufat-cimne** [comment]
Does it require "RIGID_BODY_OPTION" to be added in the interface? (In the submodelpart writing )

**Comment by philbucher** [comment]
@KlausBSautter maybe this is also interesting for you

**Comment by maceligueta** [comment]
> Does it require "RIGID_BODY_OPTION" to be added in the interface? (In the submodelpart writing )

Not really, this option should be added by the coupling utilities which transfer walls to the DEM.

**Comment by maceligueta** [comment]
hi @farrufat-cimne , check Coday suggestions. Almost all of them would disappear if we change 'from dem import *' to 'import dem as DEM'. Then the variables would be called 'DEM.TOTAL_FORCES'

**Comment by maceligueta** [comment]
I forgot about this PR, it seems tests were failing due to external reasons. Now everything fine.
Can someone approve?

**Review by salvalatorre — APPROVED** [review]
Nice piece of work!

**Pull request merged**
