### PR TITLE
Moving Communicator implementation to cpp

### PR DESCRIPTION
**Pull request by jcotela**
Essentially what it says in the title. I believe this is useful as a way to avoid recompiling everything that uses a ModelPart every time something changes in the DataCommunicator.

I discussed with @philbucher forward-declaring Communicator in ModelPart as a less intrusive, alternative solution, but I could not make it work because some ModelPart functions have Communicator::Pointer types in their signature).

### CODE REVIEW

**Comment by loumalouomega** [comment]
@jcotela I think you can forward declare not just classes but methods, but I have been looking on StackoverFlow and it is not straightforward as i pressumed.

**Comment by jcotela** [comment]
What I would need to forward-declare here is just `Communicator::Pointer`. I could probably re-declare the type as
```C++
class Communicator;
typedef Kratos::shared_ptr<Communicator> CommunicatorPointerType;
```
but this is one more thing to change if we ever want to change pointer types again, so I thought that moving definitions to cpp is just overall cleaner.

**Review by philbucher — APPROVED** [review]
looks good to me even though it is a bit tough to be reviewed

Thanks :+1:

**Comment by jcotela** [comment]
@philbucher the only (minor) change is bb6f811328a360a02654a51eed9e9b494851edc4, the rest is taking the existing code and moving it over to the cpp.

**Pull request merged**
