### PR TITLE
[ContactStructuralMechanicsApplication] @philbucher suggestion

### PR DESCRIPTION
**Pull request by loumalouomega**
Basically that from #7031

### CODE REVIEW

**Comment by philbucher** [comment]
seems not to work :/
Did you try locally?

**Comment by loumalouomega** [comment]
> seems not to work :/

CI passes

> Did you try locally?

It worked in my machine, maybe as it was already compiled it did nothing

**Comment by philbucher** [comment]
Well it works in the sense it compiles

but checking the output one can see that the files are not excluded from cotire

**Comment by loumalouomega** [comment]
> Well it works in the sense it compiles
> 
> but checking the output one can see that the files are not excluded from cotire

This also means that now we can just simply remove the exclusion because now the CI compiles as it did before (maybe that day GitHub reduced the RAM of the CI for some reason)

**Comment by loumalouomega** [comment]
Let's see

**Comment by philbucher** [comment]
the point is that sometimes it works and sometimes it doesn't, because the memory consumption is on the edge (and since we are adding more things rather than removing it becomes more and more an issue). So I am guessing depending on the other processes running during compilation it might fail or not

**Comment by loumalouomega** [comment]
> the point is that sometimes it works and sometimes it doesn't, because the memory consumption is on the edge (and since we are adding more things rather than removing it becomes more and more an issue). So I am guessing depending on the other processes running during compilation it might fail or not

Ok, I will try again to loop. How do I check that the cotire is removing some files?

**Comment by philbucher** [comment]
you should see the files being compiled separtely (like the `interface_preprocess`)

~~~
Scanning dependencies of target KratosContactStructuralMechanicsCore_unity
[100%] Building CXX object applications/ContactStructuralMechanicsApplication/CMakeFiles/KratosContactStructuralMechanicsCore_unity.dir/custom_utilities/interface_preprocess.cpp.o
[100%] Building CXX object applications/ContactStructuralMechanicsApplication/CMakeFiles/KratosContactStructuralMechanicsCore_unity.dir/cotire/KratosContactStructuralMechanicsCore_CXX_unity.cxx.o
~~~

**Comment by loumalouomega** [comment]
> you should see the files being compiled separtely (like the `interface_preprocess`)
> 
> ```
> Scanning dependencies of target KratosContactStructuralMechanicsCore_unity
> [100%] Building CXX object applications/ContactStructuralMechanicsApplication/CMakeFiles/KratosContactStructuralMechanicsCore_unity.dir/custom_utilities/interface_preprocess.cpp.o
> [100%] Building CXX object applications/ContactStructuralMechanicsApplication/CMakeFiles/KratosContactStructuralMechanicsCore_unity.dir/cotire/KratosContactStructuralMechanicsCore_CXX_unity.cxx.o
> ```

OK

**Comment by loumalouomega** [comment]
@philbucher The problem was I (and you) wrote condition_file instead of ${condition_file}
imagen

**Review by philbucher — APPROVED** [review]
Cool thx!

**Comment by loumalouomega** [comment]
> Cool thx!

But windows is still failing :(

**Comment by philbucher** [comment]
> But windows is still failing :(

that has to wait until next week I am afraid :/

**Pull request merged**
