### PR TITLE
[Core] Transition. Adding register for processes

### PR DESCRIPTION
**Pull request by loumalouomega**
This is a transition PR for creating processes just with the given name

The Create of all processes, and the corresponding register must be implemented in a future PR

### CODE REVIEW

**Comment by loumalouomega** [comment]
Ping @KratosMultiphysics/technical-committee

**Comment by philbucher** [comment]
can you please add the PRs to the @KratosMultiphysics/technical-committee project? Otherwise we miss them :/

**Comment by loumalouomega** [comment]
> 
> 
> can you please add the PRs to the @KratosMultiphysics/technical-committee project? Otherwise we miss them :/

OK

**Comment by pooyan-dadvand** [comment]
I'm not sure if we can make the registration automatic rather than populating all the files with manual registration. My idea is to do it in the same way of tests in which each test case is automatically registered.

**Comment by loumalouomega** [comment]
> 
> 
> I'm not sure if we can make the registration automatic rather than populating all the files with manual registration. My idea is to do it in the same way of tests in which each test case is automatically registered.

Huuum, that will be interesting (not just for this, but for many prone to be registered classes)

**Comment by pooyan-dadvand** [comment]
> > I'm not sure if we can make the registration automatic rather than populating all the files with manual registration. My idea is to do it in the same way of tests in which each test case is automatically registered.
> 
> Huuum, that will be interesting (not just for this, but for many prone to be registered classes)

Exactly! Thats the idea!

**Comment by loumalouomega** [comment]
> 
> 
> > > I'm not sure if we can make the registration automatic rather than populating all the files with manual registration. My idea is to do it in the same way of tests in which each test case is automatically registered.
> > 
> > 
> > Huuum, that will be interesting (not just for this, but for many prone to be registered classes)
> 
> Exactly! Thats the idea!

What should I do with this then?

**Comment by loumalouomega** [comment]
I will close this, as it duplicates  #7004

**Pull request closed without merging**
