### PR TITLE
[Fluid, Core] Incised elements - Ausas modified shape functions

### PR DESCRIPTION
**Pull request by frawahl**
**Description**
In order to consider incised, and not only completely cut, elements in `EmbeddedFluidElementDiscontinuous`, the local flag `CALCULATE_EXTRAPOLATED_EDGE_DISTANCES` is added. For incised fluid elements, the edges which are cut by the extrapolated skin geometry, which caused the element to be incised in the first place, are identified. Corresponding edge ratios are calculated and saved in `ELEMENTAL_EXTRAPOLATED_EDGE_DISTANCES`. 
From the extrapolated and original edge ratios `ELEMENTAL_DISTANCES_WITH_EXTRAPOLATED` are calculated and saved. This information is then used for `Triangle2D3AusasIncisedShapeFunctions` and `Tetrahedra3D4AusasIncisedShapeFunctions` for incised elements. 
Those elements are then also visualized in `EmbeddedSkinVisualizationProcess`.

**Changelog**
- Added local flag `CALCULATE_EXTRAPOLATED_EDGE_DISTANCES` to `CalculateDiscontinuousDistanceToSkinProcess`
- Added variables `ELEMENTAL_EXTRAPOLATED_EDGE_DISTANCES` and `ELEMENTAL_DISTANCES_WITH_EXTRAPOLATED` to Kratos
- Added `ComputePlaneEdgeIntersection`(..) to `IntersectionUtilities`
-  If  `CALCULATE_EXTRAPOLATED_EDGE_DISTANCES` flag is given, `ELEMENTAL_EXTRAPOLATED_EDGE_DISTANCES` and `ELEMENTAL_DISTANCES_WITH_EXTRAPOLATED` are calculated in `CalculateDiscontinuousDistanceToSkinProcess`
- Added `IsAusasIncised`() to `EmbeddedDiscontinuousData` and `EmbeddedSkinVisualizationProcess`, which evaluates to True, if element is incised and `CALCULATE_EXTRAPOLATED_EDGE_DISTANCES` flag was given
- Added classes `Triangle2D3AusasIncisedShapeFunctions` and `Tetrahedra3D4AusasIncisedShapeFunctions`, which override `SetPositiveSideCondensationMatrix`(..) and `SetNegativeSideCondensationMatrix`(..)
- For incised elements, for `IsAusasIncised`() evaluates to True, `Triangle2D3AusasIncisedShapeFunctions` (2D) and `Tetrahedra3D4AusasIncisedShapeFunctions` (3D) are used in `EmbeddedFluidElementDiscontinuous` and boudary terms are applied
- Added distance modification of `ELEMENTAL_EXTRAPOLATED_EDGE_DISTANCES` and `ELEMENTAL_DISTANCES_WITH_EXTRAPOLATED` to `DistanceModificationProcess`
- Added `CALCULATE_EXTRAPOLATED_EDGE_DISTANCES` to `partitioned_embedded_fsi_base_solver`
- Adapted and added tests
- Added incised elements, for which Ausas Incised shape functions are being used, to `EmbeddedSkinVisualizationProcess`

### CODE REVIEW

**Comment by rubenzorrilla** [comment]
As it is right now this PR involves changes in several delicate parts of the code. We should consider splitting it. I'd do:
1. For the distance algorithm changes
2. For the Ausas shape functions enhancements
3. For the `FluidDynamicsApplication` changes

**Comment by frawahl** [comment]
> As it is right now this PR involves changes in several delicate parts of the code. We should consider splitting it. I'd do:
> 
>     1. For the distance algorithm changes
> 
>     2. For the Ausas shape functions enhancements
> 
>     3. For the `FluidDynamicsApplication` changes

Alright, I'll do that. Because of dependency I'll do `FluidDynamicsApplication` and `CalculateDiscontinuousDistanceToSkinProcess` first, then shape functions, then distance modification.

**Comment by rubenzorrilla** [comment]
> > As it is right now this PR involves changes in several delicate parts of the code. We should consider splitting it. I'd do:
> > ```
> > 1. For the distance algorithm changes
> > 
> > 2. For the Ausas shape functions enhancements
> > 
> > 3. For the `FluidDynamicsApplication` changes
> > ```
> 
> Alright, I'll do that. Because of dependency I'll do `FluidDynamicsApplication` and `CalculateDiscontinuousDistanceToSkinProcess` first, then shape functions, then distance modification.

I don't think you need to do the changes in the `FluidDynamicsApplication` together with the distance ones. We just add the new projected edges capability but with no uses in Kratos (aside of the tests OFC). Isn't it?

**Comment by rubenzorrilla** [comment]
@frawahl can we close this one? I think that the ones that you already merged plus #8281 cover all the changes in here.

**Comment by frawahl** [comment]
> @frawahl can we close this one? I think that the ones that you already merged plus #8281 cover all the changes in here.

Still in here and in no other branch is:

- distance modification of ELEMENTAL_EDGE_DISTANCES_EXTRPOLATED
- skin visualization of elements using Ausas incised shape functions
- CALCULATE_EDGE_DISTANCES and CALCULATE_EDGE_DISTANCES_EXTRAPOLATED for partitioned embedded FSI solver

**Comment by frawahl** [comment]
UPDATES:

- Since `ELEMENTAL_DISTANCES_WITH_EXTRAPOLATED` are now stored in `ELEMENTAL_DISTANCES` variable as well, they will be modified by the `DistanceModificationProcess`. So we could think about whether it is necessary to modify `ELEMENTAL_EDGE_DISTANCES_EXTRAPOLATED` (for the linear interpolation at the extrapolated edge intersection of `AusasIncisedShapeFunctions`) or not.

- For the adaptation of the `EmbeddedSkinVisualization` to Ausas incised elements is taken care of by PR  #8311

**Comment by rubenzorrilla** [comment]
@frawahl next week we should recover this.

**Comment by frawahl** [comment]
> @frawahl next week we should recover this.

I think we should merge #8281 first, then #8311.

Then we could think about ..
- whether we want to add the option to use Edge Constraint Penalization,
- whether we want to modify `ELEMENTAL_EDGE_DISTANCES_EXTRAPOLATED` in the `DistanceModificationProcess` to be consistent with the splitting.

**Comment by rubenzorrilla** [comment]
@frawahl Now that the other two PRs are merged, should we save something from this one or not? Isn't this the very first you opened that we decided to split?

**Pull request closed without merging**
