### PR TITLE
[ContactStructuralMechanicsApplication] Adding checking normal process

### PR DESCRIPTION
**Pull request by loumalouomega**
I should have implemented this before, as the 95% of the problems with the contact are related with wrong normals. The process checks the normals and inverts wrong elements and conditions. Test added

### CODE REVIEW

**Review by AlejandroCornejo — DISMISSED** [review]
that's a good thing to have Vicente, now the related issue is still relevant?

**Comment by loumalouomega** [comment]
> that's a good thing to have Vicente, now the related issue is still relevant?

We can live with that, but I suggest to provide good initial information

**Comment by loumalouomega** [comment]
@AlejandroCornejo I fixed one compilation error

**Review by philbucher — DISMISSED** [review]
Isnt this the same as the TetraMeshOrientatiin used in Fluids? @jcotela 

Maybe could be unified

**Comment by philbucher** [comment]
@rubenzorrilla

**Comment by loumalouomega** [comment]
> Isnt this the same as the TetraMeshOrientatiin used in Fluids? @jcotela
> 
> Maybe could be unified

It is not the same, that only check volume is not inverted. This checks the surfaces on the interface too. Besides, is not limited to tetra and triangles, is general

**Comment by philbucher** [comment]
codacy has many suggestions

**Comment by loumalouomega** [comment]
Done @philbucher

**Comment by philbucher** [comment]
appveyor complains

**Comment by loumalouomega** [comment]
> 
> 
> appveyor complains

I know, I am on it. I haven't use Windows in millenia and first the system is being updated

**Comment by loumalouomega** [comment]
@AlejandroCornejo now it compiles with appveyor

**Review by AlejandroCornejo — APPROVED** [review]
okkey

**Pull request merged**
