### PR TITLE
[BIG WIP] [MPI] Replacing Trilinos with AMGCL

### PR DESCRIPTION
**Pull request by philbucher**
Right now we use Trilinos for our MPI-capabilities, which is mainly the distributed matrices and the mpi-solvers.
The problem with Trilinos is that is a very large library and not easy to compile, especially on clusters it can be quite tough. Since we anyway only use a small part of it, it would be nice to no longer depend on Trilinos.

In order to replace Trilinos we basically need a different library that offers distributed linear algebra functionalities.
In discussions it came up several times if AMGCL could do this job. This would be very convenient for us since we are already using it.
I thought of making an issue but then it seemed easier to create the framework of files that is needed right away, this way it is easier to see what we actually need from AMGCL.

@ddemidov when you have time it would be nice to take a look at this, I guess we will need your assistance here. First if what we are thinking of is possible with AMGCL and second how to do things in a smart way.

Here is a rough list of **functionalities that we need from the Kratos point of view** (basically everything would go into the MPI-Core):
- A `BuilderAndSolver` that is built around the AMGCL distributed matrix
- An `AmgclMPISpace` which wraps certain things like getting the size of matrices
- An `AmgclMPIDofUpdater` for the `Scheme`s. @RiccardoRossi I think you said that this could be done with `GlobalPointer`s right?
- Exposure of the already existing Schemes, Strategies etc with the `AmgclMPISpace`. I did most of this already since I wanted to see what functions we need in the `AmgclMPISpace`.
- Exposure of the MPI-linear solvers through the MPI-Core. This needs a bit of refactor, not sure how the Trilinos solvers would word without Epetra. However from what I saw in AMGCL I think this can be made working. In the meantime we would already have the AmgclMPI-Solver which has a very good performance.

Here is a rough list of **functionalities that we need from the AMGCL**:
- Creating the Matrix Graph and filling it later in the FE assembly with values.
- The functionalities that are in the `AmgclMPISpace`
- Solving the system of equations, but this is ofc already there (needs some refactor though)

I checked the [distributed matrix of AMGCL](https://github.com/ddemidov/amgcl/blob/master/amgcl/mpi/distributed_matrix.hpp) and I think it does not have all those functionalities yet, but I am not sure.
Also I couldn't find the distributed-vector, but I guess it exists (?). At least I think I found sth based on the builtin-backend

@ddemidov @KratosMultiphysics/technical-committee what are your thoughts/opinion on this? Is it realistic / does it make sense to use AMGCL or not?

@KratosMultiphysics/technical-committee please feel free to add requirements etc in case I forgot sth

### CODE REVIEW

**Comment by ddemidov** [comment]
I have mixed feelings about this :).

The problem I personally always had with big packages like PETSC or Trilinos is that they require the user to adapt their own data structures like matrices or vectors in order to use them. This is a big investment to ask from the user, and it makes it hard to integrate different packages or to move away from them if the need arises.

Amgcl interface was designed so that the users could use their own datatypes as easily as possible. On the other hand, when we move into the MPI domain, things get more complicated. It is relatively hard for a user to come up with their own effective implementation of a distributed matrix, so maybe it does make sense to provide some help from amgcl side.

> Here is a rough list of functionalities that we need from the AMGCL:

> - Creating the Matrix Graph and filling it later in the FE assembly with values.

It should be possible (and makes sense in my opinion) to add the functionality into amgcl, although the tasks of efficiently assembling the matrix and efficiently using it inside the solver could be somewhat orthogonal (and sometimes contradictory).

> - The functionalities that are in the AmgclMPISpace

I briefly checked fb71dcdfab1b4ea5d939b2b5f9f1f89caaf13e4f, and it looks like most of it should be a direct translation from amgcl backend interface, or easy enough to implement.

> - Solving the system of equations, but this is ofc already there (needs some refactor though)

> I checked the distributed matrix of AMGCL and I think it does not have all those functionalities yet, but I am not sure. Also I couldn't find the distributed-vector, but I guess it exists (?).

There is no distributed vector in amgcl, the local and remote parts of the vector are stored explicitly (and [`amgcl::mpi::communication_pattern`](https://github.com/ddemidov/amgcl/blob/461a66ce6d197a3816218bf94ffd114a367c1ef1/amgcl/mpi/distributed_matrix.hpp#L50-L51) is used for the exchange). There is (was?) no need for a distributed vector in the user-facing API.

**Comment by RiccardoRossi** [comment]
Hi @philbucher @ddemidov 
I just want to spend some words about the 3 "difficult" operations i think we need to get rid of epetra.
I think that the updating could be done on our side, or anyhow should not be too difficult to do...
Also, if we had this we could use the very same interface even in serial

1 - graph assembly (mounting the non zero structure of the matrix). Right now we have a code that looks more or less as

~~~
LinearMap distribution_map(...) //here we tell which lines are owned on each processor

Graph Agraph;

for(auto& elem : mrModelPart.Elements() )
{
    auto& equation_ids = elem.EquationId() //vetor of indices to where we need to assemble

    Agraph.AddZeros(equation_ids, equation_ids);
}

Agraph.Finalize()
DistributedMatrix A(Agraph);
//here we can delete the graph, anyway we can get it from A...
~~~

2 - Assembly of a local matrices and vectors onto the large matrixç

~~~
A, b are large "distributed" entities (normally initialized with zero, and already with the correct nonzero structure)

for(auto& elem : mrModelPart.Elements() )
{
    auto& equation_ids = elem.EquationId() //vetor of indices to where we need to assemble
    Alocal,blocal = elem.CalculateLocalSystem() //this are small matrices

    A.Assemble(Alocal,equation_ids) // this means Aglobal[equationids[i],equationids[j]] += Alocal[i,j]
    //this is for a square matrix, eventually we would also need for a rectangular one -->
    
    b.assemble(blocal,equationids); //bglobal[equationids[i] += blocal[i]
}

A.Finalize()
b.Finalize();
~~~

3 - apply dirichlet boundary conditions. Here we would need to multiply in place by a diagonal_vector to the left and to the right, and then to be able to set to a given value some diagonal entries

**Comment by philbucher** [comment]
thanks for your insights @ddemidov

**Comment by RiccardoRossi** [comment]
Addingto my own post, i have the impression that we need something on the line of 

~~~
std::unordered_map< IndexType, PartitionIndexType > IndexMap
...
owner_cpu = IndexMap[i]
~~~

probably encapsulated in a class, that can give us for every index which is the processor that owns it (and myabe what is its local index, the GID and LID of epetra map)

the graph object would then look something like

~~~
std::unordered_map< IndexType, std::unordered_set< IndexType > > Agraph.
~~~

the idea is that we would have to construct this locally and then, upon finalize, we would send the nonlocal stuff to the owner processor, so that it can be consturcted. Doing this with our internal communicator mechanism should not be difficult.

**Comment by philbucher** [comment]
closing this as we now have our own distributed csr matrix: #6623

**Pull request closed without merging**
