### PR TITLE
StructuralMech checking for Imports

### PR DESCRIPTION
**Pull request by philbucher**
applying #1190 for StructuralMechanics (works after this is merged)
also some minor Cleanup on the way

I removed the imports of the ExternalSolversApp from the Solvers, I think it is not needed there.

@qaumann I removed the ExternalSolversApp from the HarmonicSolver, is this ok? I couldn't find any dependenices, but I cannot run all the test on my machine

### CODE REVIEW

**Review by loumalouomega — DISMISSED** [review]
Thanks

**Comment by loumalouomega** [comment]
Let's wait until the #1190 is merged

**Comment by philbucher** [comment]
can you reapprove, I had to fix a merge conflict?

**Review by loumalouomega — DISMISSED** [review]
Let's wait for #1190

**Review by loumalouomega — APPROVED** [review]

**Comment by philbucher** [comment]
@KratosMultiphysics/structural-mechanics and @rubenzorrilla  I am merging now (tests are all working)

In case sth stops working pls let me know

FYI  if you used solvers from the ExternalSolversApplication without importing this App in the MainKratos then it will no longer work.
You HAVE to import it explicitly

**Pull request merged**
