### PR TITLE
[Core] Add solve methods for dense matrices

### PR DESCRIPTION
**Pull request by qaumann**
Adds solve methods for dense matrices to be linear solver base class. This will be used for Eigen's dense solvers (see #6199).

### CODE REVIEW

**Comment by qaumann** [comment]
@KratosMultiphysics/technical-committee could anyone please review this?

**Comment by pooyan-dadvand** [comment]
Shouldn't be defined by using LinearSolver<DenseSpace,DenseSpace>?

**Comment by philbucher** [comment]
> Shouldn't be defined by using LinearSolver<DenseSpace,DenseSpace>?

https://github.com/KratosMultiphysics/Kratos/blob/0437b4cb6bfe5cb050e108517e9daa6ebd1b083a/kratos/linear_solvers/linear_solver.h#L63-L73

it should, can you please try @qaumann ?

**Comment by philbucher** [comment]
unclear to me is how well it works in combination with the existing B&S, strategies etc, since the all have a different space as template argument

**Comment by qaumann** [comment]
> Shouldn't be defined by using LinearSolver<DenseSpace,DenseSpace>?

@pooyan-dadvand thanks for the idea, this works. I had to add a new factory for the dense solvers though, but all changes can be included in the EigenSolversApplication. I will close this PR and add the changes to the original one.


> unclear to me is how well it works in combination with the existing B&S, strategies etc, since the all have a different space as template argument

@philbucher If defined as Pooyan pointed out, the dense solver can be used with a strategy. Although I do not think the dominant use case is to use the dense solvers with the existing strategies, which include most probably large sparse systems. I want to use the dense solvers for my reduced systems, which are small and dense; here the dense solvers outperform the sparse solvers by far.

**Pull request closed without merging**
