### PR TITLE
[HDF5] Feature/hdf5 default for windows

### PR DESCRIPTION
**Pull request by armingeiser**
Works for the tests that use HDF5 in the StructuralMechanicsApplication.

Open points:
* is it necessary to change it in the hdf5_file.cpp?
* all the tests are hardcoded to "file_driver" : "core" - switch that to "windows" if on windows?
* Even if i do that, still all HDF5 tests fail, saying the *.h5 file cannot be opened.

### CODE REVIEW

**Review by msandre — APPROVED** [review]
Thankst :+1:

**Comment by msandre** [comment]
> is it necessary to change it in the hdf5_file.cpp?

At the moment, hdf5_file.cpp checks for windows and throws an error if there is a driver mismatch. I like the solution in the hdf5_io.py you proposed better than changing the c++ implementation.

> all the tests are hardcoded to "file_driver" : "core" - switch that to "windows" if on windows?

"core" means don't write the file to disk, just store it in memory, which is preferred for the c++ tests. If windows can't deal with that I would say python tests are enough on windows.

**Comment by msandre** [comment]
Can test if the hdf5 python tests work with this modification?

**Comment by armingeiser** [comment]
No, none of the tests of the HDF5 application work in windows. 
I can only say that it works for the StructuralMechanicsApplication

**Comment by msandre** [comment]
ok, still you can go ahead with the merge.

**Pull request merged**
