### PR TITLE
[Structural] EigenSolver with constraints

### PR DESCRIPTION
**Pull request by philbucher**
**requires #5501 to compile**

this PR makes the EigenStrategy to consider constraints (which was already working before the refactoring of the BlockB&S)

I added a test which runs an eigenvalue analysis with and without constraints and checks if the results are the same to make sure that this does not brake again

### CODE REVIEW

**Comment by loumalouomega** [comment]
> **requires #5501 to compile**
Why you don't use the utilities?: https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/utilities/constraint_utilities.cpp

The B&S uses that basically

**Review by loumalouomega — CHANGES_REQUESTED** [review]
Try to use: https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/utilities/constraint_utilities.cpp

**Comment by philbucher** [comment]
hm interesting, let my try, thx

**Comment by philbucher** [comment]
does not work :/

I guess it makes sense, since I am applying MPCs on a matrix that does not have the MPCs assembled in the matrix. What do you think?

**Comment by adityaghantasala** [comment]
I think the `ApplyConstraints` in the utilities is just adjusting the slave value to make it according to the Master-Slave equation. But the `ApplyConstraints` needed by the `EigenStrategy` to do `T'*K*T` operation ... so they are different.

**Comment by adityaghantasala** [comment]
Apart from that the usage of BuilderAndSolver for modifying the K and M matrices looks good. 
Test also looks good to me.

**Review by loumalouomega — DISMISSED** [review]
Release my block

**Comment by adityaghantasala** [comment]
@philbucher  tarvis and appveyor is failing

**Comment by philbucher** [comment]
now it should work @adityaghantasala ;)

**Comment by philbucher** [comment]
ping

**Review by adityaghantasala — APPROVED** [review]

**Comment by philbucher** [comment]
thx

**Pull request merged**
