### PR TITLE
Testing coverage utilities DO NOT MERGE

### PR DESCRIPTION
**Pull request by roigcarlo**
**Description**
This is a testing PR to try to add coverage to Kratos. No Idea how it works yet so do not merge

### CODE REVIEW

**Review by philbucher — CHANGES_REQUESTED** [review]
request changes to avoid accidental merge, as discussed

**Comment by roigcarlo** [comment]
Closing PR. I will leave the branch alive just in case we want  to retake this at some point.

**Comment by loumalouomega** [comment]
> Closing PR. I will leave the branch alive just in case we want to retake this at some point.

What is the status of this?

**Comment by roigcarlo** [comment]
Is closed because is something we cannot afford to execute at every build right now. As I said is interesting to have the branch open because I don't remember by hearth all the changes I did to integrate this, but I suppose if you want to delete it I can eventually reproduce it again.

**Comment by loumalouomega** [comment]
> Is closed because is something we cannot afford to execute at every build right now. As I said is interesting to have the branch open because I don't remember by hearth all the changes I did to integrate this, but I suppose if you want to delete it I can eventually reproduce it again.

We can keep it then

**Pull request closed without merging**
