### PR TITLE
[MappingApplication] Fixing pure 2D geometry in 2D-3D projection mapper

### PR DESCRIPTION
**Pull request by loumalouomega**
**📝 Description**

The 2D/3D mapper performs projections based on a normal, which is computed in the 2D mesh. Previously, I was supplying a 2D mesh in a 3D space. However, when the space is 2D, the mapper fails due to an error in the `Normal` implementation. This error occurs when the geometry checks if the local space is smaller than the working space.

To fix this, I added a check to determine if the geometry is a pure 2D mesh. If so, a normal vector is now explicitly defined in the Z direction, ensuring the projection works correctly even in 2D space.

**🆕 Changelog**

- [Fixing pure 2D geometry in 2D-3D projection mapper](https://github.com/KratosMultiphysics/Kratos/commit/5f074d8eea0a5e0cdd42399c3e043e34cc1c63fd)

### CODE REVIEW

**Comment by ddiezrod** [comment]
approving as this looks as a small detail and its kind of urgent for us. If you have any comments, we can create a new PR @philbucher

**Review by ddiezrod — DISMISSED** [review]

**Comment by loumalouomega** [comment]
@roigcarlo do you think it is possible to make a minor, tiny, little, release?

**Comment by roigcarlo** [comment]
Once it's merged, no problem

**Review by ddiezrod — APPROVED** [review]

**Comment by loumalouomega** [comment]
@roigcarlo this is merged. It is actually only two commits. Due to a merge conflicts it looks like more:

- https://github.com/KratosMultiphysics/Kratos/commit/5f074d8eea0a5e0cdd42399c3e043e34cc1c63fd
- https://github.com/KratosMultiphysics/Kratos/pull/12847/commits/ab6da2c5312d68e89a2ce334789cecd3fd4e718b

**Pull request merged**
