### PR TITLE
[core] Adding utility function to add ordered nodes in batch to modelpart

### PR DESCRIPTION
**Pull request by jcotela**
**📝 Description**
Adding an utility function to add nodes in batch to a ModelPart, assuming that the nodes are already ordered.

Development by @jrubiogonzalez, I am just migrating it to Kratos Core in this PR.

**🆕 Changelog**
- Add ModelPartUtils::AddNodesFromOrderedContainer

### CODE REVIEW

**Review by sunethwarna — COMMENTED** [review]
Hi @jcotela . How urgent is this?

**Comment by jcotela** [comment]
Hi @sunethwarna there will be a PR soon from our side that requires this function, but I separated it because it is a standalone thing and the other PR is quite big. If you think that it might conflict with changes on your side, we can move it to a separate utility.

**Comment by pooyan-dadvand** [comment]
@sunethwarna, Do you think this is in conflict with your PointerVectorSet PR? I think it is a complimentary to it. No?

We use this in the voxel mesher that we want to pass to GitHub

**Comment by sunethwarna** [comment]
Hi, sorry for the confusion. @jcotela you can go ahead. :)

**Review by ddiezrod — APPROVED** [review]

**Pull request merged**
