### PR TITLE
[Core] Fix geometry shape function container

### PR DESCRIPTION
**Pull request by tteschemacher**
Hi,

there were some errors in the existent version of the geometry shape function container concerning the high order derivatives.

### CODE REVIEW

**Comment by pooyan-dadvand** [comment]
So the problems were copy constructor and the access to the container which was transposed?

Would you please add some tests covering these issues?

**Comment by tteschemacher** [comment]
There are more. But those are the most obvious ones.

**Comment by tteschemacher** [comment]
These are some bugs concerning the geometry shape function container. But there's something weird with the geometry data holding this container. I added some tests. Those are more comprehensive. I put them into #6277 .

**Comment by tteschemacher** [comment]
Any further suggestions? @pooyan-dadvand

**Review by pooyan-dadvand — APPROVED** [review]
:+1:

**Pull request merged**
