### PR TITLE
[Core] Memory error on SkinDetectionProcess

### PR DESCRIPTION
**Pull request by loumalouomega**
Check if this works, the test works

### CODE REVIEW

**Review by AlejandroCornejo — APPROVED** [review]

**Comment by loumalouomega** [comment]
Can you check it works with your problem?

**Comment by AlejandroCornejo** [comment]
I'll tell you something,  thank you

**Comment by RiccardoRossi** [comment]
guys, try it with valgrind....

**Comment by loumalouomega** [comment]
It is supposed to be solved.

**Pull request merged**
