### PR TITLE
[Core] Remove old import mechanism

### LINKED ISSUE #5268: Deprecating the old importing mechanism
the old importing mechanism will be now deprecated.

the following warning will be issued:

    The python-import-mechanism used for application "' + application_name
    is DEPRECATED!
    Please check the following website for instuctions on how to update it:
    https://github.com/KratosMultiphysics/Kratos/wiki/Applications-as-python-modules
    The old mechanism will be removed on 01.10.2019!

important messages:

* current code will stop working on 1/10/2019
* info can be found in the wiki page [DOC](https://github.com/KratosMultiphysics/Kratos/wiki/Applications-as-python-modules)

### PR DESCRIPTION
**Pull request by philbucher**
closes #5268 

As long announced, this PR removes the old import mechanism => #5268 

**This will be merged 1. October!**

Many Apps have already been updated, the core is updated in #5448 

@KratosMultiphysics/all please update your code if you haven't yet done it. You can test your code with this branch

### CODE REVIEW

**Comment by philbucher** [comment]
@KratosMultiphysics/all I recommend to check your applications against this branch to check that nothing breaks on 1. October

**Comment by inigolcanalejo** [comment]
The tests run in the CompressiblePotentialFlowApplication

**Comment by jcotela** [comment]
I checked FluidDynamics and ConvectionDiffusion, but I had to merge master before they worked (see merge commit). ConvectionDiffusion tests are still failing, but that will be solved in #5569.

**Comment by philbucher** [comment]
@KratosMultiphysics/technical-committee can you approve pls?
It is 1. October :tada:

**Review by rubenzorrilla — APPROVED** [review]

**Comment by philbucher** [comment]
thx

**Pull request merged**
