### PR TITLE
[Core] Fix Clang warning

### PR DESCRIPTION
**Pull request by philbucher**
and turning this warning into an error in the CI
It is easy to avoid but can lead to memory problems

### CODE REVIEW

**Comment by philbucher** [comment]
ping :)

**Review by roigcarlo — APPROVED** [review]
> ping :)

Ok boomer

**Comment by philbucher** [comment]
> Ok boomer

why? :sweat_smile:

**Comment by roigcarlo** [comment]
I was approving it when you sent the ping :rofl:

**Pull request merged**
