### PR TITLE
Addition of a structural Python solvers wrapper

### PR DESCRIPTION
**Pull request by rubenzorrilla**
This new file is just a Python solver factory. The unique purpose of it is to allow both serial and parallel runs to be launched directly from GiD interface.

### CODE REVIEW

**Review by loumalouomega — APPROVED** [review]
This is OK

**Comment by pooyan-dadvand** [comment]
Is it also related to release?

**Comment by rubenzorrilla** [comment]
Yes it is.

**Comment by pooyan-dadvand** [comment]
Have you also merged it to the release branch?

**Comment by rubenzorrilla** [comment]
Merged and tested in both serial and parallel executions.

**Pull request merged**
