### PR TITLE
[StructuralMechanics] adding printing of convergence info

### PR DESCRIPTION
**Pull request by philbucher**
This print was missing
Done in the same style as in Fluid

@KlausBSautter in some of your tests it now prints that no convergence is achieved. Can you please have a look after this is merged?

### CODE REVIEW

**Review by loumalouomega — APPROVED** [review]
This is supposed to be printed already for the strategy

**Comment by philbucher** [comment]
hm it is not ...
I will check it, but in any case I think that it is a good idea if the solver also prints it
Otherwise in a coupled problem it is hard to identify where the prints (from) the strategy come from

**Comment by KlausBSautter** [comment]
> @KlausBSautter in some of your tests it now prints that no convergence is achieved. Can you please have a look after this is merged?

@philbucher how can this happen? The tests normally run until they converge

**Comment by philbucher** [comment]
> > @KlausBSautter in some of your tests it now prints that no convergence is achieved. Can you please have a look after this is merged?
> 
> @philbucher how can this happen? The tests normally run until they converge

Apparently not, but I am not sure if you would have noticed it if they were not converging (unless you increased the echo-level and checked the output of the conv-criteria)

The results have not changed, just the problem is not converging. Not sure if it is a problem, thats why I think it is easier if you take a look at it yourself at some point

**Pull request merged**
