### PR TITLE
[Core][SeveralApps] Replace DetMat with Det (MatUtils, deprecated some days ago)

### PR DESCRIPTION
**Pull request by loumalouomega**
**Description**
Replace DetMat with Det (MathUtils, deprecated some days ago)

**Changelog**
- Replace DetMat with Det (MathUtils, deprecated some days ago)

### CODE REVIEW

**Comment by philbucher** [comment]
Why does it fail in particle?
Did sth change?
I thought this was a simle rename?

**Comment by loumalouomega** [comment]
> Why does it fail in particle?
> Did sth change?
> I thought this was a simle rename?

It failed because for the 10th decimal in some simulation, as I am not responsible of MPM I reverted (It was supposed to give the same result BTW, but I don't want to debug something is not my application.)

**Comment by loumalouomega** [comment]
> Why does it fail in particle?
> Did sth change?
> I thought this was a simle rename?

https://github.com/KratosMultiphysics/Kratos/runs/1989475561

imagen

**Comment by philbucher** [comment]
> > Why does it fail in particle?
> > Did sth change?
> > I thought this was a simle rename?
> 
> https://github.com/KratosMultiphysics/Kratos/runs/1989475561
> 
> imagen

yes I know, but if a test suddenly starts to fail (I didn't see this one fail before and I check lots of CI builds) I suspect that there might be sth fishy going on

What exactly changed in this regard in #8341?
Maybe this discovered a bug?

**Comment by loumalouomega** [comment]
> > > Why does it fail in particle?
> > > Did sth change?
> > > I thought this was a simle rename?
> > 
> > 
> > [KratosMultiphysics/Kratos/runs/1989475561](https://github.com/KratosMultiphysics/Kratos/runs/1989475561)
> > imagen
> 
> yes I know, but if a test suddenly starts to fail (I didn't see this one fail before and I check lots of CI builds) I suspect that there might be sth fishy going on
> 
> What exactly changed in this regard in #8341?
> Maybe this discovered a bug?

I just deprecated the DetMat with Det, to avoid code duplication. In theory the code is the same. I dont' know what is happening

**Comment by philbucher** [comment]
> In theory the code is the same.

this is what worries me
can you please check in detail?

**Comment by roigcarlo** [comment]
Since the error is in the 17th significant decimal you can ignore it. I would change the test to it has a relative tolerance of 1e-16 if you want but that's perfectly fine.

If you exceed the double precision any change in types (exp, changing a return 0.0 to a return 0) can cause the difference.

**Comment by loumalouomega** [comment]
imagen
vs
imagen

Where:
imagen

Is the same!

**Comment by philbucher** [comment]
hm ok

well then maybe the suggestion of @roigcarlo makes sense if @KratosMultiphysics/mpm agrees

Sorry for the noise :)

Probably better if someone except me approves as I have no clue apparently :D

**Comment by loumalouomega** [comment]
> hm ok
> 
> well then maybe the suggestion of @roigcarlo makes sense if @KratosMultiphysics/mpm agrees
> 
> Sorry for the noise :)
> 
> Probably better if someone except me approves as I have no clue apparently :D

I will merge this as it is and change the missing one in the MPM app in an independent PR, so the MPM developers can check that everything is OK

**Review by roigcarlo — APPROVED** [review]

**Pull request merged**
