### PR TITLE
[Core] Fix Profiler Link Error on Windows

### PR DESCRIPTION
**Pull request by matekelemen**
Forgot to export symbols on windows.

### CODE REVIEW

**Comment by ddiezrod** [comment]
I am still getting an error when trying to include the profiler in my app :/ 
```
[1/4] Building CXX object kratos\applications\ThermomechanicalApplication\CMakeFiles\KratosThermomechanicalCore.dir\custom_elements\thermomechanic_small_displacement.cpp.obj
FAILED: kratos/applications/ThermomechanicalApplication/CMakeFiles/KratosThermomechanicalCore.dir/custom_elements/thermomechanic_small_displacement.cpp.obj
C:\PROGRA~2\MICROS~3\2019\PROFES~1\VC\Tools\MSVC\1428~1.293\bin\Hostx64\x64\cl.exe  /nologo /TP -DKRATOS_ENABLE_PROFILING -DKRATOS_PYTHON -DKRATOS_SMP_OPENMP -DKratosThermomechanicalCore_EXPORTS -DTHERMOMECHANICAL_APPLICATION=EXPORT,API -IC:\workspaces\KratosDev\Poesis3\build\RelWithDebInfo\kratos\applications\ThermomechanicalApplication -IC:\workspaces\KratosDev\Poesis3\applications\ThermomechanicalApplication -IC:\workspaces\KratosDev\Poesis3\kratos\external_libraries\zlib -IC:\workspaces\KratosDev\Poesis3\build\RelWithDebInfo\kratos\external_libraries\zlib -IC:\workspaces\KratosDev\Poesis3\kratos\external_libraries -IC:\workspaces\KratosDev\Poesis3\kratos\kratos -IC:\workspaces\KratosDev\Poesis3\kratos\applications\StructuralMechanicsApplication -IC:\workspaces\KratosDev\Poesis3\kratos\applications\ConstitutiveLawsApplication -IC:\workspaces\KratosDev\Poesis3\applications\ThermomechanicalApplication\..\AltairExtensionApplication -IC:\workspaces\KratosDev\Poesis3\external_libraries\boost -D_SILENCE_ALL_CXX17_DEPRECATION_WARNINGS /W1 /bigobj /EHsc /Zc:__cplusplus -DBOOST_ALL_NO_LIB -D_SCL_SECURE_NO_WARNINGS -openmp /MD /Zi /O2 /Ob1 /DNDEBUG -std:c++17 /showIncludes /Fokratos\applications\ThermomechanicalApplication\CMakeFiles\KratosThermomechanicalCore.dir\custom_elements\thermomechanic_small_displacement.cpp.obj /Fdkratos\applications\ThermomechanicalApplication\CMakeFiles\KratosThermomechanicalCore.dir\ /FS -c C:\workspaces\KratosDev\Poesis3\applications\ThermomechanicalApplication\custom_elements\thermomechanic_small_displacement.cpp
C:\workspaces\KratosDev\Poesis3\kratos\kratos\utilities/profiler_impl.h(56): error C2491: 'Kratos::Internals::Profiler<TTimeUnit>::Profile': definition of dllimport function not allowed  
ninja: build stopped: subcommand failed.
 *  Terminal will be reused by tasks, press any key to close it. 
```

**Comment by matekelemen** [comment]
I'll need to set up a dedicated windows machine ...

**Comment by ddiezrod** [comment]
It compiles now, but I am still getting the same error when trying to include the profiler.h in any other app

**Comment by matekelemen** [comment]
The only reason I separated function definitions from their declarations is to maintain a tidy overview of the class. Moving them back in the class definition shouldn't have any effect on performance.

That said, I refuse to believe that the current code can't be correctly exported on windows. I'll try to get this working once I manage to get and set up a windows machine, but that'll take a while because I'll be on holiday for a while.

Feel free to move the definitions in the meantime.

**Pull request closed without merging**
