### PR TITLE
PfemApplication update

### PR DESCRIPTION
**Pull request by josep-m-carbonell**
The PR of the PfemApplication is here to suggest corrections and improvements and to test the compatibility and possible conflicts with other applications:

Main changes:
1. The previous PfemApplication is now the DelaunayMeshingApplication with some minor bug corrections in the boundary management. (To do next: There is still some work to do to manage correctly the boundary skin and the composite conditions.)
2. The new PfemApplication contains a re-implementation of the fluid element of the PfemFluidDynamicsApplication considering the call to the constitutive-law. (the new element implementation is more general and more expensive, some methods and calls can be optimized, this would be done in a next step.)
3. A reduced version of meshing processes from the PfemFluidApplication are now in the PfemApplication, however a review is needed to improve them. (The implementation have been kept at this first step)
4. The PfemApplication is now using the general segregated strategy of the SolidMechanicsApplication as well as the Velocity based solid elements implemented in the SolidMechanicsApplication. (To do: a profiling to apply optimisations are needed to get faster calculation speeds.)
5. Composite solver is under testing to be used by the PfemSolid thermo-mechanical problems. It also must to consider different FSI strategies. 

New  features and improvements for Solid and Fluid simulation with the Pfem will be the objectives after this PR. There is also the need for adapting the GiD interface to write the calculation files properly.

### CODE REVIEW

**Comment by ipouplana** [comment]
Nice work @josep-m-carbonell ! 
@jgonzalezusua and me are preparing now a 3D test for the PfemFluidDynamicsApplication. Today we will upload it so that we can check that everything works after merging this PR.

**Comment by ipouplana** [comment]
In fact, we will upload the 3D tests in this branch so that we can check it faster.

Note: the 2D tests were already implemented, but we will add at least one 3D case.

**Comment by josep-m-carbonell** [comment]
Good, no test has been carried on in 3D for the new element. If you upload them I will adapt them for the PfemApplication.  To reproduce non-newtonian tests, the needed laws must be added to the ConstitutiveModelsApplication, they are not complex, we can take the non-newtonian FluidDynamicsApp Laws as reference for the implementation.

**Comment by lluis-mv** [comment]
Hi @josep-m-carbonell , I did a quick look yesterday and everything looks fine to me!

**Review by lluis-mv — DISMISSED** [review]

**Comment by maceligueta** [comment]
Sorry, I can't review a PR with 578 modified files. It would be great is PR's were smaller, with specific changes.
At least, are the old examples running fine with this? I mean the examples that @ipouplana and @jgonzalezusua pushed in the past.

**Comment by josep-m-carbonell** [comment]
Hello @maceligueta, examples are working. I don't know how github counts the files... We do not have so many files. Some of them are just deleted renamed and copied to another application. I guess their are counted several times. You can compile and run the tests. This is not a PR for a specific correction it has more general objectives.

**Comment by jgonzalezusua** [comment]
Hello @josep-m-carbonell, we have run some cases using PfemFluidDynamicsApplication and they do not work. I copy here the error messages, the first one appears when we run a new case as a test and the second one when we run a random case. The error appear both in 2D and 3D.

```

ERROR: test_execution (NightTests.Water_sloshing_3D_Newtonian_Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jgonzalez/Kratos/applications/PfemFluidDynamicsApplication/tests/TestFactory.py", line 41, in test_execution
    self.test.Run()
  File "/home/jgonzalez/Kratos/applications/PfemFluidDynamicsApplication/python_scripts/MainFluidPFEM.py", line 101, in Run
    self.Initialize()
  File "/home/jgonzalez/Kratos/applications/PfemFluidDynamicsApplication/python_scripts/MainFluidPFEM.py", line 159, in Initialize
    self.model_processes = process_handler.ProcessHandler(self.Model, process_parameters)
  File "/home/jgonzalez/Kratos/applications/SolidMechanicsApplication/python_scripts/process_handler.py", line 35, in __init__
    self.Sort()
  File "/home/jgonzalez/Kratos/applications/SolidMechanicsApplication/python_scripts/process_handler.py", line 116, in Sort
    self.list_of_processes += self.ConstructList( self.ProcessList(self.settings["problem_process_list"]) )
  File "/home/jgonzalez/Kratos/applications/SolidMechanicsApplication/python_scripts/process_handler.py", line 177, in ConstructList
    unsorted_process_list.append(self.ConstructProcess(process))
  File "/home/jgonzalez/Kratos/applications/SolidMechanicsApplication/python_scripts/process_handler.py", line 165, in ConstructProcess
    kratos_module = __import__(process["kratos_module"].GetString())
  File "/home/jgonzalez/Kratos/KratosMultiphysics/PfemApplication.py", line 9, in <module>
    from KratosPfemApplication import *
ImportError: generic_type: type "SetActiveFlagProcess" is already registered!

```
```

Traceback (most recent call last):
  File "MainKratos.py", line 4, in <module>
    import KratosMultiphysics.PfemFluidDynamicsApplication     
  File "/home/jgonzalez/Kratos/KratosMultiphysics/PfemFluidDynamicsApplication.py", line 8, in <module>
    from KratosPfemFluidDynamicsApplication import *
ImportError: generic_type: type "SplitElementsProcess" is already registered!
```
Do you know how to address this?

**Review by jgonzalezusua — CHANGES_REQUESTED** [review]
I request changes regarding the error found when running the examples using PfemFluidDynamicsApplication.

**Comment by josep-m-carbonell** [comment]
Hello @jgonzalezusua , this is because the input files you have generated are importing the PfemApplication, that now is the DelaunayMeshingApplication. The python scripts of the PfemFluidDynamicsApplication does not have to import the PfemApplication anymore. Change the previous import to : from KratosMultiphysics.DelaunayMeshingApplication import*

**Comment by jgonzalezusua** [comment]
Hello @josep-m-carbonell, I did the changes that you said and the tests run correctly. We will update this branch (after the master merge that you did yesterday) and we will upload a 3D test before approving the PR.

**Review by jgonzalezusua — DISMISSED** [review]

**Comment by josep-m-carbonell** [comment]
I have added the 3D tests to PfemApp, can you please reapprove it in order to Merge ?  @jgonzalezusua  @lluis-mv  Thank you!

**Review by RiccardoRossi — DISMISSED** [review]
need to verify that there are no changes in the core...with 925 archives this takes time... i'll try to check this today

**Review by jgonzalezusua — APPROVED** [review]

**Comment by josep-m-carbonell** [comment]
There are no changes in the Core, but we can wait you to check it.

**Pull request merged**
