### PR TITLE
[Core] Add epsilon definition to globals

### PR DESCRIPTION
**Pull request by loumalouomega**

### CODE REVIEW

**Comment by RiccardoRossi** [comment]
what is the problem with using the numeric limits?

**Comment by loumalouomega** [comment]
I don't like to copy paste all the time the epsilon

**Comment by RiccardoRossi** [comment]
but why don't you use directly 

std::numeric_limits<double>::epsilon()
std::numeric_limits<double>::max()

i don't see any good reason for adding global constants that are only a copy of those...

**Comment by RiccardoRossi** [comment]
in any case let's see the opinion of @KratosMultiphysics/technical-committee

**Comment by loumalouomega** [comment]
I use them, but I need to copy again and again every time I need them. Is easier to remeber Globals::Epsilon than the whole std::numeric_limit<double>::epsilon

**Comment by loumalouomega** [comment]
The same for the max

**Comment by oberbichler** [comment]
We should be careful with `std::numeric_limit::epsilon()`. AFAIK we are using it in a wrong way for comparing numbers (e.g. in #2757 or #2609).

**Comment by oberbichler** [comment]
To clarify my concerns:

A simple check with `epsilon`

```
def almost_equal(a, b):
    return abs(a - b) <= epsilon
```

e.g. will produce

```
almost_equal(a, 0) # true for tons of values
almost_equal(a, 1) # only true for a = 0.9999999999999998, 0.9999999999999999, 1 or 1.0000000000000002 and no other value!
almost_equal(a, 4) # only true for a = 4.0 and no other value!
```

**Comment by loumalouomega** [comment]
This is just adding a definition, the use is a different thing

**Comment by philbucher** [comment]
I think it would make sense to add a function to Globals `IsAlmostEqual` with a tolerance larger than the epsilon for the reasons @oberbichler pointed out

**Comment by RiccardoRossi** [comment]
@oberbichler your concern makes full sense to me. I think we should add the function that @philbucher  proposes, however in my opinion that function mustn't be in globals but rather in a "normal" utility.

On the other hand i don't really see why we should add Epsilon while e can call 

     std::numeric_limits<double>::epsilon

which is standardized.

**Comment by oberbichler** [comment]
@loumalouomega True, but I think that people might misunderstand the meaning of `epsilon`.

@philbucher @RiccardoRossi  The problem with this tolerance-thing is, that there is no general way to write `IsAlmostEqual` (at least I have not found one).

Don't get me wrong. The code above is completely correct. It's just not the safe tolerance check that people might expect.

E.g. writing `almost_equal(a, 4)` instead of `a == 4` to avoid an equality check with floats does not make sense because it's actually the same.

Maybe a good documentation is enough.

**Comment by loumalouomega** [comment]
Ok, I will close this anyway, I see people don't agree

**Comment by msandre** [comment]
@philbucher @oberbichler here are some functions for comparing floats, to give some ideas...

https://github.com/chromium/chromium/blob/master/cc/base/math_util.cc#L156
https://github.com/chromium/chromium/blob/master/cc/base/math_util.h#L141
https://github.com/chromium/chromium/blob/master/cc/base/math_util.cc#L575

**Pull request closed without merging**
