### PR TITLE
Core/move variable redistribution utility from fsi

### PR DESCRIPTION
**Pull request by jcotela**
Moving VariableRedistributionUtility to core so that @philbucher and @AndreasWinterstein can use it from their application.

### CODE REVIEW

**Review by rubenzorrilla — DISMISSED** [review]
Thanks for the migration @jcotela

**Comment by jcotela** [comment]
Travis was failing because the test for the variable redistribution utility requires InterfacePreprocess, which is still in the FSI Application (and I was not planning to move it). I added a skip for the test if the application is not available.

**Review by philbucher — APPROVED** [review]
Thanks @jcotela

**Comment by philbucher** [comment]
@jcotela can this be merged?

**Comment by jcotela** [comment]
@philbucher yes. For some reason I had missed your review. Merging.

**Pull request merged**
