### PR TITLE
fixing the unused parameters warnings

### LINKED ISSUE #2989: [AMGCL] many warnings after #2807
@RiccardoRossi @ddemidov after #2807 AMGCL throws a lot of warnings about unknown parameters

This is some tests-output:
~~~
AMGCL WARNING: unknown parameter coarsening
AMGCL WARNING: unknown parameter npre
AMGCL WARNING: unknown parameter npost
AMGCL WARNING: unknown parameter coarse_enough
AMGCL WARNING: unknown parameter relax
AMGCL WARNING: unknown parameter coarsening
AMGCL WARNING: unknown parameter npre
AMGCL WARNING: unknown parameter npost
AMGCL WARNING: unknown parameter coarse_enough
AMGCL WARNING: unknown parameter relax
AMGCL WARNING: unknown parameter coarsening
AMGCL WARNING: unknown parameter npre
AMGCL WARNING: unknown parameter npost
AMGCL WARNING: unknown parameter coarse_enough
AMGCL WARNING: unknown parameter relax
AMGCL WARNING: unknown parameter coarsening
AMGCL WARNING: unknown parameter npre
AMGCL WARNING: unknown parameter npost
AMGCL WARNING: unknown parameter coarse_enough
AMGCL WARNING: unknown parameter relax
AMGCL WARNING: unknown parameter coarsening
AMGCL WARNING: unknown parameter npre
AMGCL WARNING: unknown parameter npost
AMGCL WARNING: unknown parameter coarse_enough
AMGCL WARNING: unknown parameter relax
AMGCL WARNING: unknown parameter coarsening
AMGCL WARNING: unknown parameter npre
AMGCL WARNING: unknown parameter npost
AMGCL WARNING: unknown parameter coarse_enough
AMGCL WARNING: unknown parameter relax
AMGCL WARNING: unknown parameter coarsening
AMGCL WARNING: unknown parameter npre
AMGCL WARNING: unknown parameter npost
AMGCL WARNING: unknown parameter coarse_enough
.AMGCL WARNING: unknown parameter relax
AMGCL WARNING: unknown parameter coarsening
AMGCL WARNING: unknown parameter npre
AMGCL WARNING: unknown parameter npost
AMGCL WARNING: unknown parameter coarse_enough
AMGCL WARNING: unknown parameter relax
AMGCL WARNING: unknown parameter coarsening
AMGCL WARNING: unknown parameter npre
AMGCL WARNING: unknown parameter npost
AMGCL WARNING: unknown parameter coarse_enough
AMGCL WARNING: unknown parameter relax
AMGCL WARNING: unknown parameter coarsening
AMGCL WARNING: unknown parameter npre
AMGCL WARNING: unknown parameter npost
AMGCL WARNING: unknown parameter coarse_enough
.........AMGCL WARNING: unknown parameter M
~~~

I looked around a bit but I couldn't figure out how to fix it

can you please have a look?

### PR DESCRIPTION
**Pull request by RiccardoRossi**
fixes #2989

### CODE REVIEW

**Comment by jcotela** [comment]
I still get the `AMGCL WARNING: unknown parameter M` messages with this branch. You can see those in `test_amgcl_no_amg_only_preconditioner (test_linear_solvers.TestLinearSolvers)` in the core, for example.
One question: wouldn't it make sense to use the kratos logger mechanism in the `AMGCL_PARAM_UNKNOWN` macro (which is defined on the kratos side) rather than having it output to cerr?`

**Comment by jginternational** [comment]
This is critical. Execution time warnings are redirected the same way as errors (if the case is launched from GiD) so the user gets an error message even if the calculation went fine.

**Comment by RiccardoRossi** [comment]
@jcotela, i could not reproduce exactly the warning you posted. however i did fix smthg which removed one warning about coarsening that was leftover.

if you have the occasion take a look if it is now ok

**Comment by jcotela** [comment]
@RiccardoRossi I still get the warnings with the latest version (6.0.0-ba93b42fb3)
```
test_amgcl_no_amg_only_preconditioner (test_linear_solvers.TestLinearSolvers) ... AMGCL WARNING: unknown parameter M
AMGCL WARNING: unknown parameter M
AMGCL WARNING: unknown parameter M
AMGCL WARNING: unknown parameter M
AMGCL WARNING: unknown parameter M
ok
```
@sunethwarna could you also try this branch out when you have time? In case I have something strange going on with my system.

**Comment by jcotela** [comment]
BTW my output matches the one travis is giving in this PR.

**Comment by RiccardoRossi** [comment]
@jcotela, i am not sure of what is happening. this is the output on my computer 

 riccardo  fix_amgcl_warnings*  ~/.../kratos/tests  git status
On branch fix_amgcl_warnings
Your branch is up to date with 'origin/fix_amgcl_warnings'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	../../.vscode/
	../../applications/MeshMovingApplication/tests/test_mdpa_files/rectangle_2D3N_test_0.mdpa
	../../applications/MeshMovingApplication/tests/test_mdpa_files/rectangle_2D3N_test_1.mdpa
	../../applications/MeshMovingApplication/tests/test_mdpa_files/rectangle_2D4N_test_0.mdpa
	../../applications/MeshMovingApplication/tests/test_mdpa_files/rectangle_2D4N_test_1.mdpa
	../../debug_build/
	../python_scripts/model_serialization.rest
	../python_scripts/out.out
	model_serialization.rest

nothing added to commit but untracked files present (use "git add" to track)
 riccardo  fix_amgcl_warnings*  ~/.../kratos/tests  python3 test_linear_solvers.py --verbose
 |  /           |             
 ' /   __| _` | __|  _ \   __|
 . \  |   (   | |   (   |\__ \ 
_|\_\_|  \__,_|\__|\___/ ____/
           Multi-Physics 6.0.0-ba93b42fb3-FullDebug
test_amgcl_bicgstab_ilu0 (__main__.TestLinearSolvers) ... ok
test_amgcl_bicgstab_spai0 (__main__.TestLinearSolvers) ... ok
test_amgcl_bicgstabl (__main__.TestLinearSolvers) ... ok
test_amgcl_idr_ilu0 (__main__.TestLinearSolvers) ... ok
test_amgcl_no_amg_only_preconditioner (__main__.TestLinearSolvers) ... ok
test_amgcl_unpreconditioned (__main__.TestLinearSolvers) ... ok
test_bicgstab_iluk (__main__.TestLinearSolvers) ... ok
test_bicgstab_in_core (__main__.TestLinearSolvers) ... ok
test_cg_in_core (__main__.TestLinearSolvers) ... ok
test_cg_spai0 (__main__.TestLinearSolvers) ... ok
test_deflated_cg_in_core (__main__.TestLinearSolvers) ... ok
test_lgmres_iluk (__main__.TestLinearSolvers) ... ok
test_pastix (__main__.TestLinearSolvers) ... Importing    KratosExternalSolversApplication 
Initializing KratosExternalSolversApplication... 
skipped 'Pastix solver is not included in the compilation of the External Solvers Application'
test_skyline_lu (__main__.TestLinearSolvers) ... ok
test_superlu (__main__.TestLinearSolvers) ... ok
test_tfqmr_in_core (__main__.TestLinearSolvers) ... 


ok

----------------------------------------------------------------------
Ran 16 tests in 0.582s

OK (skipped=1)

**Comment by jcotela** [comment]
@RiccardoRossi could it be that you have some CMAKE definitions related to AMGCL? I could see a different version of the `AMGCL_PARAM_UNKNOWN` macro being used depending on include order or due to manual redefinition...

**Comment by RiccardoRossi** [comment]
@jcotela i would say i have nothing specific of amgcl (serial) in the configure.

here is what i use


clear

#you may want to decomment this the first time you compile
rm CMakeCache.txt
rm *.cmake
rm -rf CMakeFiles\

#export BOOST_ROOT=/home/rrossi/data/compiled_libraries/boost
##-D_GLIBCXX_DEBUG

cmake ..  									                            \
-G"Kate - Unix Makefiles" \
-DCMAKE_C_COMPILER=/usr/bin/gcc    \
-DCMAKE_INSTALL_RPATH="/home/rrossi/kratos/libs"                      \
-DCMAKE_INSTALL_RPATH_USE_LINK_PATH=TRUE                                \
-DCMAKE_CXX_COMPILER=/usr/bin/g++ 						                \
-DCMAKE_CXX_FLAGS="${CMAKE_CXX_FLAGS} -msse3 -std=c++14  " 					        \
-DCMAKE_C_FLAGS="${CMAKE_C_FLAGS} -msse3 " 					            \
-DCMAKE_BUILD_TYPE=FullDebug 							                \
-DINCOMPRESSIBLE_FLUID_APPLICATION=OFF  						            \
-DMESHING_APPLICATION=OFF 							                    \
-DEXTERNAL_SOLVERS_APPLICATION=ON						                \
-DINCLUDE_PASTIX=OFF \
-DPASTIX_INSTALL_DIR="/home/rrossi/data/scratch/pastix_5.2.2.22/install" \
-DSCOTCH_INSTALL_DIR="/usr/lib" \
-DPFEM_APPLICATION=OFF 								                    \
-DSTRUCTURAL_APPLICATION=OFF 							                \
-DCONVECTION_DIFFUSION_APPLICATION=ON 						            \
-DLAGRANGIAN_MPM_APPLICATION=OFF                                          \
-DFLUID_DYNAMICS_APPLICATION=ON 						                \
-DMESH_MOVING_APPLICATION=ON 								                    \
-DFSI_APPLICATION=ON 								                    \
-DOPENCL_APPLICATION=OFF							                    \
-DMIXED_ELEMENT_APPLICATION=OFF							                \
-DMETIS_APPLICATION=ON								                    \
-DUSE_METIS_5=ON                                                        \
-DPARMETIS_ROOT_DIR="/usr/lib"  \
-DTRILINOS_APPLICATION=OFF							                    \
-DTRILINOS_LIBRARY_PREFIX="trilinos_" \
-DTRILINOS_LIBRARY_DIR="/usr/lib/x86_64-linux-gnu"		\
-DTRILINOS_INCLUDE_DIR="/usr/include/trilinos"		\
-DDEM_APPLICATION=ON								                    \
-DSWIMMING_DEM_APPLICATION=OFF                                          \
-DSOLID_MECHANICS_APPLICATION=OFF   					                    \
-DCONSTITUTIVE_MODELS_APPLICATION=OFF \
-DSTRUCTURAL_MECHANICS_APPLICATION=ON 					                \
-DCONTACT_STRUCTURAL_MECHANICS_APPLICATION=OFF 					                \
-DPFEM_BASE_APPLICATION=OFF                                              \
-DPFEM_SOLID_MECHANICS_APPLICATION=OFF 					                \
-DINSTALL_EMBEDDED_PYTHON=ON                                           \
-DPYTHON_LIBRARY="/usr/lib/x86_64-linux-gnu/libpython3.6m.so" \
-DPYTHON_INCLUDE_DIRS="/usr/include/python3.6" \
-DCLICK2MOLD_APPLICATION=ON \
-DKRATOS_BUILD_TESTING=ON \
-DTRILINOS_USE_AMGCL=ON \
-DIGA_STRUCTURAL_MECHANICS_APPLICATION=ON \
-DUSE_COTIRE=ON \

#-DAMATRIX_DIR="/home/riccardo/Kratos/external_libraries/a_matrix/"


#decomment this to have it verbose
make all_unity install/fast -j3

**Comment by RiccardoRossi** [comment]
just to tell that i also verified without cotire and i get the same result...

**Comment by philbucher** [comment]
@RiccardoRossi does `riccardo fix_amgcl_warnings* ~/.../kratos/tests python3 test_linear_solvers.py --verbose` really increase the verbosity?
I thought you have to specify `-v2`

**Comment by RiccardoRossi** [comment]
@philbucher if you run from within the tests directory, you need to run with --verbose... otherwise it does not run

can u see if it works for you if you run when running only the test_linear_solvers.py and not all the tests?

**Comment by RiccardoRossi** [comment]
ok, i see what is happening:

when i run ONLY the test test_linear_solvers.py

i get no warnings...

when i run the same test from within the run_tests.py i do get the warnings.

@roigcarlo this shouldn't happen...any hint of what could be wrong?

in any case i think i have a fix, however i would need someone to take a look if what i did is still equivalent to what was there before (i hope so...but it is just sooooo easy to make this wrong...)

**Comment by philbucher** [comment]
@RiccardoRossi even with your last fix I get some warnings:
~~~
 |  /           |             
 ' /   __| _` | __|  _ \   __|
 . \  |   (   | |   (   |\__ \ 
_|\_\_|  \__,_|\__|\___/ ____/
           Multi-Physics 6.0.0-ba93b42
test_amgcl_bicgstab_ilu0 (__main__.TestLinearSolvers) ... ok
test_amgcl_bicgstab_spai0 (__main__.TestLinearSolvers) ... ok
test_amgcl_bicgstabl (__main__.TestLinearSolvers) ... ok
test_amgcl_idr_ilu0 (__main__.TestLinearSolvers) ... ok
test_amgcl_no_amg_only_preconditioner (__main__.TestLinearSolvers) ... AMGCL WARNING: unknown parameter M
AMGCL WARNING: unknown parameter M
AMGCL WARNING: unknown parameter M
ok
test_amgcl_unpreconditioned (__main__.TestLinearSolvers) ... ok
test_bicgstab_iluk (__main__.TestLinearSolvers) ... ok
test_bicgstab_in_core (__main__.TestLinearSolvers) ... ok
test_cg_in_core (__main__.TestLinearSolvers) ... ok
test_cg_spai0 (__main__.TestLinearSolvers) ... ok
test_deflated_cg_in_core (__main__.TestLinearSolvers) ... ok
test_lgmres_iluk (__main__.TestLinearSolvers) ... ok
test_pastix (__main__.TestLinearSolvers) ... Importing    KratosExternalSolversApplication 
Initializing KratosExternalSolversApplication... 
ok
test_skyline_lu (__main__.TestLinearSolvers) ... ok
test_superlu (__main__.TestLinearSolvers) ... ok
test_tfqmr_in_core (__main__.TestLinearSolvers) ... 


ok

----------------------------------------------------------------------
Ran 16 tests in 0.236s

OK
~~~

I use the following cmd: `runkratos test_linear_solvers.py -v`

**Comment by philbucher** [comment]
> when i run ONLY the test test_linear_solvers.py
> 
> i get no warnings...
> 
> when i run the same test from within the run_tests.py i do get the warnings.
> 
> @roigcarlo this shouldn't happen...any hint of what could be wrong?

I get warnings in both cases ...

**Comment by RiccardoRossi** [comment]
@philbucher  hash tag is 83fd2d3331 on my computer  and ba93b42 on yours so you are not on the latest...

i now get clean output both for the single test and when i run all the tests

 riccardo  fix_amgcl_warnings*  ~/.../kratos/tests  python3 test_linear_solvers.py -v
 |  /           |             
 ' /   __| _` | __|  _ \   __|
 . \  |   (   | |   (   |\__ \ 
_|\_\_|  \__,_|\__|\___/ ____/
           Multi-Physics 6.0.0-83fd2d3331-FullDebug
test_amgcl_bicgstab_ilu0 (__main__.TestLinearSolvers) ... ok
test_amgcl_bicgstab_spai0 (__main__.TestLinearSolvers) ... ok
test_amgcl_bicgstabl (__main__.TestLinearSolvers) ... ok
test_amgcl_idr_ilu0 (__main__.TestLinearSolvers) ... ok
test_amgcl_no_amg_only_preconditioner (__main__.TestLinearSolvers) ... ok
test_amgcl_unpreconditioned (__main__.TestLinearSolvers) ... ok
test_bicgstab_iluk (__main__.TestLinearSolvers) ... ok
test_bicgstab_in_core (__main__.TestLinearSolvers) ... ok
test_cg_in_core (__main__.TestLinearSolvers) ... ok
test_cg_spai0 (__main__.TestLinearSolvers) ... ok
test_deflated_cg_in_core (__main__.TestLinearSolvers) ... ok
test_lgmres_iluk (__main__.TestLinearSolvers) ... ok
test_pastix (__main__.TestLinearSolvers) ... Importing    KratosExternalSolversApplication 
Initializing KratosExternalSolversApplication... 
skipped 'Pastix solver is not included in the compilation of the External Solvers Application'
test_skyline_lu (__main__.TestLinearSolvers) ... ok
test_superlu (__main__.TestLinearSolvers) ... ok
test_tfqmr_in_core (__main__.TestLinearSolvers) ... 


ok

----------------------------------------------------------------------
Ran 16 tests in 0.603s

OK (skipped=1)

**Comment by philbucher** [comment]
@RiccardoRossi true, sorry I didn't see your last commit
recompiling right now

btw your code-comments are a lot more readable if you wrap them in `~~~`

**Comment by philbucher** [comment]
@RiccardoRossi it works now for me, my output is also clean!
Thanks for fixing!

approval and final check I leave to @jcotela

**Comment by sunethwarna** [comment]
@jcotela @RiccardoRossi It is working for me too with the last commit. Thank you

**Comment by jcotela** [comment]
OK the last commit also removed the warnings for me.

**Review by jcotela — COMMENTED** [review]
The PR works as intended and I am willing to approve, however, I'd like to understand why are we writing directly to cerr in `AMGCL_PARAM_UNKNOWN` instead of using the logger (or kratos error) mechanism. @RiccardoRossi could you comment on that?

**Comment by RiccardoRossi** [comment]
@jcotela this is part of the library, not of the kratos...

**Comment by jcotela** [comment]
There is a default implementation that is part of the library (`util.hpp`), but we are deliberately redefining it (to the same contents as the default) in `amgcl_solver.h`, `amgcl_ns_solver.h`, `amgcl_mpi_solver.h` and `amgcl_mpi_schur_complement_solver.h`, all of which are on the kratos side. I will not block the PR for this, but I think it is a missed opportunity to bring it in line with the available kratos logging mechanisms.

**Review by jcotela — APPROVED** [review]

**Comment by RiccardoRossi** [comment]
@jcotela, you are right, i forgot about the warnings.

unfortunately i cannot make this to compile with the logger. my best intent is to do the following:

      #ifndef AMGCL_PARAM_UNKNOWN
      #  define AMGCL_PARAM_UNKNOWN(name)                                            \
             Kratos::Logger("AMGCL WARNING: ") << KRATOS_CODE_LOCATION << Kratos::Logger::Severity::WARNING << " unknown parameter " << name << std::endl;
      #endif

however i cannot make it to compile... for no obvious reason.

I will merge the current correction since it cleans up the output, but **i will leave open this branch to see if we further correct it with redirecting to the logger**

**Comment by ddemidov** [comment]
Sorry, I was not mentioned here, so just seen this. 

@RiccardoRossi, @jcotela, I agree that using kratos logger is the way to go. What compile errors do you get with this? Is it a matter of include order/missing include?

**Comment by RiccardoRossi** [comment]
@ddemidov sorry i didn't mention you. The issue with the warnings was kratos-side not amgcl side.

concerning redirection to our logger i tried to do

     #ifndef AMGCL_PARAM_UNKNOWN
     #  define AMGCL_PARAM_UNKNOWN(name)         
           Kratos::Logger("AMGCL WARNING: ") << KRATOS_CODE_LOCATION << Kratos::Logger::Severity::WARNING << " unknown parameter " << name << std::endl 
      std::endl 
           #endif

here

https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/linear_solvers/amgcl_solver.h#L22

the error i get is:

     In file included from /home/riccardo/Kratos/kratos/sources/standard_linear_solver_factory.cpp:27:0:
      /home/riccardo/Kratos/kratos/linear_solvers/amgcl_solver.h:26:22: error: expected unqualified-id before string constant
       Kratos::Logger("AMGCL WARNING: ") << KRATOS_CODE_LOCATION <<     Kratos::Logger::Severity::WARNING << " unknown parameter " << name << std::endl
                      ^~~~~~~~~~~~~~~~~
       /home/riccardo/Kratos/kratos/linear_solvers/amgcl_solver.h:26:22: error: expected ‘)’ before string constant

**Comment by jcotela** [comment]
@RiccardoRossi @ddemidov I have just pushed a version of the macro that compiles to this branch. Essentially, the problem is that we are using the macro from outside of the Kratos namespace, so we need to be extra careful when qualifying our class names.

(Edited to add:) note that this required adding a `Kratos::` qualifier in the `KRATOS_CODE_LOCATION` macro definition too.

**Comment by RiccardoRossi** [comment]
@jcotela are u sure you pushed? i cannot see your changes

**Comment by jcotela** [comment]
@RiccardoRossi they don't appear as part of this PR, I created a new one to continue the discussion (#3293)

**Pull request merged**
