### PR TITLE
[Core] Adding methods to constraints to recover the dofs vectors

### PR DESCRIPTION
**Pull request by loumalouomega**
I add this methods in order to be able to access to the vector of dofs from the constraints, this could be used in order compute the MPC in a explicit way

### CODE REVIEW

**Comment by adityaghantasala** [comment]
There is already `GetDofsList` function .. ! 
https://github.com/KratosMultiphysics/Kratos/blob/169a21a286f74584567fad27b5a3fcf69009a272/kratos/includes/master_slave_constraint.h#L312

This gets both slave and master dofs !!

**Comment by RiccardoRossi** [comment]
the nice thing of Vicente's version is that you can get a reference to the slave and master dofs (should be const reference)

aside of this,
what i think is that we should have a function "Apply" which actually applies the action of the constraint.

that would be quite helpful to actually enforce the constraints in the predict (see discussion in the parallel PR on the block builder and solver)

**Comment by loumalouomega** [comment]
> the nice thing of Vicente's version is that you can get a reference to the slave and master dofs (should be const reference)
> 
> aside of this,
> what i think is that we should have a function "Apply" which actually applies the action of the constraint.
> 
> that would be quite helpful to actually enforce the constraints in the predict (see discussion in the parallel PR on the block builder and solver)

@RiccardoRossi already using a const reference. Huuum, I haven't seen the previous implementation. Do you thing does it harm the new one?, this way the creation of a new DofVector is avoided, which is expensive in explicit

**Comment by adityaghantasala** [comment]
Ok I see ... ! 
We should also consider adding such a function to element and condition based classes also !

**Review by adityaghantasala — APPROVED** [review]

**Comment by loumalouomega** [comment]
Thanks

**Pull request merged**
