### PR TITLE
Core/feature has properties method

### LINKED ISSUE #1409: Can't check if Element has NULL properties because all calls to the properties have the check inside
I wanted to do some operations in the destructor of an element. These operations depend on some information I get from the properties. But the load of Kratos creates Elements with NULL properties. So I wanted to do something like:
`if (pGetProperties != nullptr) { a = GetProperties()[YOUNG_MODULUS]; }`
However, I did not find any method that gets the pointer without doing the check (in debug mode).
One possible solution would be a method called 'HasProperties()'.
Another possibility is to leave some methods without the check. I prefer the first one.

### PR DESCRIPTION
**Pull request by jcotela**
This fixes #1409 
@KratosMultiphysics/dem can you test that this solves the debug error?

### CODE REVIEW

**Comment by maceligueta** [comment]
It's perfect. It stopped crashing and Valgrind is 100% clean!

**Review by maceligueta — DISMISSED** [review]

**Comment by joaquinirazabal** [comment]
Sorry I messed up this branch, I was in the wrong branch. Can you dissmiss my changes?

**Comment by joaquinirazabal** [comment]
Ok, I reverted previous commit. Sorry again!

**Review by maceligueta — APPROVED** [review]

**Comment by maceligueta** [comment]
No problem! It is ok again. Approved,

**Pull request merged**
