### PR TITLE
[Core] Replace find nodal h settings

### PR DESCRIPTION
**Pull request by loumalouomega**
As asked by @pooyan-dadvand

### CODE REVIEW

**Comment by loumalouomega** [comment]
Anyone?

**Comment by RiccardoRossi** [comment]
why is this change needed?

**Comment by RiccardoRossi** [comment]
oh, i see.

**Comment by RiccardoRossi** [comment]
but...why are u changing the name?

**Comment by loumalouomega** [comment]
@pooyan-dadvand asked for that in a comment in the previous PR once merged

**Comment by loumalouomega** [comment]
imagen

**Review by philbucher — APPROVED** [review]

**Pull request merged**
