### PR TITLE
[ContacTStructuralMechanicsApplication] Some updates on ContacTStructuralMechanicsApplication

### PR DESCRIPTION
**Pull request by loumalouomega**
This is transition PR for future PR

### CODE REVIEW

**Comment by philbucher** [comment]
I will review after you are done with your commits
Please let me know

**Comment by loumalouomega** [comment]
This one in particular is done, I am just updating while the review comes.

**Review by philbucher — APPROVED** [review]
I do not understand the algorithmic changes but I guess you know what you are doing since it is your app :)

**Comment by loumalouomega** [comment]
Thanks

**Pull request merged**
