### PR TITLE
[Core][ParallelUtilities] clean includes

### PR DESCRIPTION
**Pull request by philbucher**
**Description**
This PR cleans a bit the includes
This is important as the ParallelUtilties are included in lots of places and I would like to keep dependencies to a minimum

### CODE REVIEW

**Comment by rubenzorrilla** [comment]
Just wondering if in this particular case it would make sense to include the `reduction_utilities.h` and `atomic_utilities.h` in the `parallel_utils.h`. Then users wouldn't require to take care of these includes (OFC this is not optimal from the compilation perspective).

**Comment by philbucher** [comment]
> Just wondering if in this particular case it would make sense to include the `reduction_utilities.h` and `atomic_utilities.h` in the `parallel_utils.h`. Then users wouldn't require to take care of these includes (OFC this is not optimal from the compilation perspective).

ok lets see what @RiccardoRossi says

**Comment by RiccardoRossi** [comment]
well i tend to agree about having different includes. i don't have a strong opinion though...

**Comment by philbucher** [comment]
closing, the @KratosMultiphysics/technical-committee decided to leave this as is as we couldn't decide whether the proposed solution is better or not

**Pull request closed without merging**
