### PR TITLE
[Core] Interpolative Material Properties

### LINKED ISSUE #1642: problem in GetConstitutiveLaw
Hi @philbucher @jcotela we have a problem with the new usage of GetConstitutiveLaw

the point is that the signature of the function is currently

         const ConstitutiveLaw& GetConstitutiveLaw(

this means that when you do

        constitutive_law = self._GetConstitutiveLaw( mat["constitutive_law"]["name"].GetString() )
        prop.SetValue(KratosMultiphysics.CONSTITUTIVE_LAW, constitutive_law)

you first get a reference and then you try to assign that reference to the SetValue.

This is not correct, since a CONSTITUTIVE_LAW is ConstitutiveLaw::Pointer
I think that boost::python is (in my opinion incorrectly) creating a new Pointer. Pybind throws an error.

### PR DESCRIPTION
**Pull request by philbucher**
This PR adds the option for interpolative material properties.
We briefly discussed this already in #825 and unfortunately there is no easy way of achieving this. I also discussed this with several ppl here at the chair and with @jcotela 

The solution I came up with is to create a `Property` for each `Element` / `Condition`, which gets the interpolated value directly. The interpolation is done using tables.

I am using this for some months already and it is working fine

The input looks like this:

~~~json
"Variables": {
    "YOUNGS_MODULUS": { "@table": "Table1" },
    "LOCAL_INERTIA_TENSOR" : [[1.27, { "@table": "Table5" }],
                              [{ "@table": "Table2" }, 0.257]],
    "POISSON_RATIO": 0.39
}
...
"Table1": {
    "input_variable": "TEMPERATURE",
    "output_variable": "YOUNG_MODULUS",
    "data": [
        [ 0.0,   100.0 ],
        [ 200.0, 500.0 ]
    ],
    "input_variable_location": "geom_entity/nodes"
}
~~~

If a variable is getting an interpolated value , then instead of passing a value we pass the reference to the table with which the interpolation is done.
During the creation, the input value is taken form the `Element` / `Condition` (specified with `input_variable_location`), either from the nodes or from the entity itself.

The advantage of the implementation is that the usual way of applying the properties (i.e. what is done so far) is NOT affected. I only check once at the beginning if Interpolation is needed and if not, everything goes the old way.
Also I am only changing only one Python file

I know that what I do is not the intended use of the Properties (i.e. shared object btw Elements and Conditions) and I also know abt the Layer issue with the GiD output, but I need this for modeling the Wind-Turbine Blades, where the Material Properties are changing along the blade (based on tabular data)

I already spoke with @jcotela abt how this could be solved in a proper way but also we couldn't think of an easy solution (the main struggle is how to pass the input variable from the element/condition to the property for the interpolation without changing the interface in the elements)

I am happy to help with the proper implementation of this, since I think it is sth also others could use

A tests is provided of course

@RiccardoRossi this should also fix #1642

### CODE REVIEW

**Comment by jcotela** [comment]
I'm leaving a comment for now, since we already discussed this and I'd like to give others a chance to review. I believe that this is a clear improvement over the current situation, although I'd also like to find a more general solution, preferably one that does not imply a different property for each interpolated element.

However, I do not think this is a fix for #1642. I believe that the main issue there is that the current implementation forces us to do the pointer management in python, which is more error-prone. I think it would be cleaner if we return a pointer from the C++ layer (preferably in the function called by `KratosMultiphysics.KratosGlobals.GetConstitutiveLaw`) so that we are not forced to always do the clone (which you'll still need here, unfortunately). We can discuss if this is something for this PR or for a new one, but I just wanted to mention that I do not consider that issue closed.

**Comment by loumalouomega** [comment]
One question, when interpolates, does it take the value using the nodal values and interpolating to the Gauss Points?, or it is just taken a given value?

**Comment by philbucher** [comment]
The values either come from nodes (i.e. `"input_variable_location": "nodes"`) or from the element/condition itself (i.e. `"input_variable_location": "geom_entity"`)

The values used for the Interpolation can e.g. be specified in the mdpa

**Comment by pooyan-dadvand** [comment]
I'm not against this PR but definitely is not the way to go in long term ... An alternative solution would be to pass this management to the `GeometricalObject `base class. Another option would be to add following new methods:
`GetInterpolatedValue(Variable const&, Node const&)`
`GetInterpolatedValue(Variable const&, GeometricalObject const&)`

to the `Properties `and impose the overhead there

Again this was my loud reflection for long term ....

**Comment by jcotela** [comment]
@pooyan-dadvand I agree with the sentiment, but this way starts to get complicated fast... First we need to know which variable (and/or which value) is the entry to get output from the table, which can easily be problem dependent: in @philbucher's application the entry value is a local coordinate, in fluid problems it could be the ambient temperature, for example. Should the constitutive law know how to do this? The properties? The geometrical object? How does the user set it all up?

**Comment by pooyan-dadvand** [comment]
@jcotela I agree with you. These are the reason that I did not implement it as I say.... but I should admit that on that time we gave less importance to it as the set value process results to be a useful hack. Now we should re think it again.

**Comment by RiccardoRossi** [comment]
@philbucher i yet did not have time to look into this in detail, however at first sight i am a bit lost. 

for example i don't understand what you are trying to express by

        "LOCAL_INERTIA_TENSOR" : [[1.27, { "@table": "Table5" }],
                              [{ "@table": "Table2" }, 0.257]],

**Comment by philbucher** [comment]
the matrix for "LOCAL_INERTIA_TENSOR" is size 2x2
its entries are:
[0,0]: 1.27
[0,1]: interpolated value using "Table5"
[0,0]: interpolated value using "Table2"
[1,1]: 0.257

**Comment by PhilippeBussetta** [comment]
@philbucher to be sure, you solve a mechanical problem not themo-mechanical?
The value of the variables is constant during the problem or depend of the solution?

**Comment by RiccardoRossi** [comment]
@philbucher can u point me to where this interpolation is done ?

**Comment by philbucher** [comment]
@PhilippeBussetta I am solving a pure mechanical problem
The value is constant, being read at the beginning of the simulation

@RiccardoRossi the Interpolation is done [in this function](https://github.com/KratosMultiphysics/Kratos/blob/fe5a2874287000c2f4cd76014d11197198b423f7/kratos/python_scripts/read_materials_process.py#L463)

**Review by RiccardoRossi — CHANGES_REQUESTED** [review]
@philbucher we spoke about this a bit also with @pooyan-dadvand , and we are not convinced that this is a  solution that should go mainstream. I am blocking the PR for this reason (sorry).

The main criticism is that having one different property per each element is a real killer. 

let me review your PR with some more time and try to come up with a proposal. Please be patient though since as of now we are polishing the release

**Comment by philbucher** [comment]
@RiccardoRossi that is fine, I know that this solution is not the best one.
Since I only change a python file I can include it with not too much effort

I would really like to have a better solution myself, but this is somehow over my head, so thanks for taking a look

**Comment by loumalouomega** [comment]
@KratosMultiphysics/technical-committee Maybe this can be an opportunity to think about a good solution for this. I think it is not necessary to have a different property for each material, with the table would be enough. The thing would be think in a way to automate the GetValue in order to take into account the variation of the parameter.

Maybe creating the method `GetValueFromTable`, the main issue here would be that would require to specify the X value to interpolate in the table.

**Comment by philbucher** [comment]
@loumalouomega passing the x-value is exactly the problem. If you don't want to change the interface to the element

**Comment by loumalouomega** [comment]
I know, but better that small change than adding N number of properties (in my opinion)

**Comment by loumalouomega** [comment]
Hi, we need to test the correct working of the tables on properties, I will try to induce the minimum conflict with this in case you want to continue developing this in the future

**Comment by philbucher** [comment]
I am using this in production so I am quite sure that the tables are working as expected 
Or what exactly do you mean?

I am planning on doing this in a better way in the future but it will require changes in the elements

**Comment by loumalouomega** [comment]
Just some example in #2050

**Comment by philbucher** [comment]
Ah thx

I am planning on making a proper attempt after the release, since also others at the chair asked me if this is possible

In a nutshell it will require to pass the Geometry and the DataContainer to the Props. This is where/why some changes are necessary

**Comment by loumalouomega** [comment]
Keep us infomed @ipouplana and I will use it eventually

**Comment by RiccardoRossi** [comment]
@philbucher i think that the solution to your original problem is to use an "adaptor" that either gives back the value of the variable or, if possible, it gives back the interpolated value.

regarding passing the geometry and the datavalue container to the properties i am honestly quite contrary... recall that Properties must be shared between many elemens. You should NOT have one property per element...

**Comment by philbucher** [comment]
@RiccardoRossi I intend to do what you describe as adaptor

I know props are shared, I will NOT change this (even though I am currently doing it)

To return an interpolated value the props have to know sth abt the element (e.g. if the interpolation is based on a value of the Element)
This is why I would pass Geometry and DataContainer. This happens each time the element asks for a property and therefore it would be threadsafe

I will make a draft soon then it should become clear

**Comment by pooyan-dadvand** [comment]
Just to leave an idea that for the interpolation it would be better to pass a function object to `GetValue `rather than geometry and data value container.

**Comment by loumalouomega** [comment]
Just to say that if I can help with the implementation tell me, me and @ipouplana are interested in this feature

**Comment by philbucher** [comment]
Thx for the help
I will start very soon since the stage and the solver are at least on the way now

**Comment by loumalouomega** [comment]
@philbucher and @jcotela  can we discuss about this in our next meeting?, yesterday we started a discussion here in Barcelona, and would be nice to extend points of view

**Comment by philbucher** [comment]
@loumalouomega sure sounds good

I will try to make an implementation draft over the weekend then

**Comment by philbucher** [comment]
@loumalouomega unfortunately I didn't have time this weekend :/

I thought abt it and maybe its better to talk abt it first in skype.
I am a bit busy this week and Thursday is public holiday here, Friday would work for me.

Here is a brief collection of thoughts. To interpolate whatever values we need in the Properties:
- Access to DataValueContainer (elem.GetValue)
- Access to the Nodes or even better to the Geometry
- Interpolation to the GPs should be possible
- ... possibly more in the future

=> Passing a std::function object as @pooyan-dadvand suggests might not be a bad idea! We can use std::bind to pass certain things with it (I use this in the current mappers)
We have to make it efficient though, I think those objects are rather heavy

For different types of interpolation I think we should derive separate, specialized Properties from `Property` => interpolation could be done based on Tables, geometry,...
If we can make it that general then the user can just derive an own specialized PropertyObject and work with it

What do you think?

**Comment by loumalouomega** [comment]
I need to think, a lot of new information and I need to process it. I am
worried of the performance, many of the options are quite heavy.

**Comment by philbucher** [comment]
closing this since it wont go in

proper version is #2349

**Pull request closed without merging**
