### PR TITLE
[Core] modelpart fix printing

### LINKED ISSUE #4279: [Tests] Test object printing is failing in Windows
The test is failing because apparently the order of submodelparts are not the same in Linux and windows and `-outlet-` is printed before `-inlets-`causing the comparison to fail.

@philbucher would you please take a look at it? I don't know the purpose of the test so I didn't want it to change it by myself

### PR DESCRIPTION
**Pull request by philbucher**
now the submodelparts are printed in alphabetical order and hence deterministically, so the test should now work in any OS

closes #4279 

@roigcarlo I guess this should also be applied to the release-branch

### CODE REVIEW

**Comment by philbucher** [comment]
Can we merge this?
The same fix was merged to the release branch

**Comment by roigcarlo** [comment]
Thought it was merged :S

**Comment by philbucher** [comment]
Nope, requires approval :)

**Review by roigcarlo — DISMISSED** [review]
For me it looks ok. but I don't know if can break other tests, so please be careful :S

**Comment by philbucher** [comment]
It should not break any other tests, essentially there was no test for this before I added it (I remember this feature broke when we moved to pybind)

Will check once again nevertheless, cannot merge now anyway bcs of #4297

**Comment by philbucher** [comment]
tests are running, will merge once the CI passed

**Comment by philbucher** [comment]
I had to fix a broken / wrong push, can you reapprove pls?

**Comment by philbucher** [comment]
ping @roigcarlo

**Review by roigcarlo — APPROVED** [review]

**Comment by philbucher** [comment]
thx

**Pull request merged**
