### PR TITLE
cps/hotfix-windows-compilation

### PR DESCRIPTION
**Pull request by inigolcanalejo**
@jginternational does this solve https://github.com/KratosMultiphysics/Kratos/issues/5525? Unfortunately I don't have a windows machine to try on.

### CODE REVIEW

**Comment by jginternational** [comment]
Maybe I'm doing something wrong but I still get the message:
```

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol "__declspec(dllimport) void __cdecl Kratos::PotentialFlowUtilities::CheckIfWakeConditionsAreFulfilled<3>(class Kratos::ModelPart const &,double const &,int const &)" (__imp_??$CheckIfWakeConditionsAreFulfilled@$02@PotentialFlowUtilities@Kratos@@YAXAEBVModelPart@1@AEBNAEBH@Z) referenced in function "void __cdecl Kratos::Python::AddCustomUtilitiesToPython(class pybind11::module &)" (?AddCustomUtilitiesToPython@Python@Kratos@@YAXAEAVmodule@pybind11@@@Z)	KratosCompressiblePotentialFlowApplication	E:\PROYECTOS\Kratos\cmake_build\applications\CompressiblePotentialFlowApplication\add_custom_utilities_to_python.obj	1	
Error	LNK2019	unresolved external symbol "__declspec(dllimport) void __cdecl Kratos::PotentialFlowUtilities::CheckIfWakeConditionsAreFulfilled<2>(class Kratos::ModelPart const &,double const &,int const &)" (__imp_??$CheckIfWakeConditionsAreFulfilled@$01@PotentialFlowUtilities@Kratos@@YAXAEBVModelPart@1@AEBNAEBH@Z) referenced in function "void __cdecl Kratos::Python::AddCustomUtilitiesToPython(class pybind11::module &)" (?AddCustomUtilitiesToPython@Python@Kratos@@YAXAEAVmodule@pybind11@@@Z)	KratosCompressiblePotentialFlowApplication	E:\PROYECTOS\Kratos\cmake_build\applications\CompressiblePotentialFlowApplication\add_custom_utilities_to_python.obj	1	

```

I'm going to clean everything and try to recompilate

**Comment by rubenzorrilla** [comment]
If I'm not wrong, `KRATOS_API` goes in the class declaration.

**Review by jginternational — APPROVED** [review]

**Comment by inigolcanalejo** [comment]
Good to know! I didn't know that it has to be in the template instantiation. Thanks @jginternational!

**Comment by jginternational** [comment]
Fixed #5525

**Pull request merged**
