### PR TITLE
[Core] Improvement on quadratic extrapolation

### PR DESCRIPTION
**Pull request by loumalouomega**
@ZhimingGuo Fix problem found in #4710. This PR offers and improvement on GP extrapolation on quadratic meshes. I cleaned up and simplified the process on the way

BEFORE:

imagen

AFTER:

imagen

The actual fix is on commit https://github.com/KratosMultiphysics/Kratos/pull/4761/commits/5e1f427b9adea9ee8c115cd3d2481220732e822e, as the comment of the commit says, "Revert if considered officially CHAPUZA"

### CODE REVIEW

**Comment by philbucher** [comment]
to me this looks ok but I don't know what the correct solution is

**Comment by loumalouomega** [comment]
> to me this looks ok but I don't know what the correct solution is

I think there is not correct solution, but the previous one was supposed to be already correct

**Comment by loumalouomega** [comment]
Ping @ZhimingGuo

**Comment by loumalouomega** [comment]
Ping @ZhimingGuo

**Comment by loumalouomega** [comment]
@philbucher can we proceed?, or do we wait for @ZhimingGuo?

**Review by philbucher — APPROVED** [review]
I cannot really check if now it is better but I think we waited long enough, go ahead please

**Comment by loumalouomega** [comment]
Thanks

**Comment by ZhimingGuo** [comment]
I made one test, the result is reasonable. i am ok.

**Comment by loumalouomega** [comment]
Nice

**Comment by ZhimingGuo** [comment]
busy for these days, sorry for late response!

**Pull request merged**
