### PR TITLE
fix response function test

### LINKED ISSUE #2022: [StructuralMechanics] errors in tests related to ResponseFunctions
From the nightly report:

compiler warning:
~~~
/home/ubuntu/Kratos/applications/StructuralMechanicsApplication/custom_response_functions/response_utilities/eigenfrequency_response_function_utility.h:342:47: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
~~~

test errors:
~~~
======================================================================
ERROR: test_execution (structural_response_function_test_factory.TestMassResponseFunction)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/Kratos/applications/StructuralMechanicsApplication/tests/structural_response_function_test_factory.py", line 74, in test_execution
    self.assertAlmostEqual(self.value, 1569.9999999999998)
  File "/usr/lib/python3.5/unittest/case.py", line 861, in assertAlmostEqual
    if round(abs(second-first), places) == 0:
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'

Stdout:
/home/ubuntu/Kratos/applications/StructuralMechanicsApplication/tests/response_function_tests

======================================================================
ERROR: test_execution (structural_response_function_test_factory.TestStrainEnergyResponseFunction)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/Kratos/applications/StructuralMechanicsApplication/tests/structural_response_function_test_factory.py", line 85, in test_execution
    self.assertAlmostEqual(self.value, 8.484005297318718e-05)
  File "/usr/lib/python3.5/unittest/case.py", line 861, in assertAlmostEqual
    if round(abs(second-first), places) == 0:
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'

Stdout:
/home/ubuntu/Kratos/applications/StructuralMechanicsApplication/tests/response_function_tests
~~~

### PR DESCRIPTION
**Pull request by armingeiser**
closes #2022

### CODE REVIEW

**Comment by philbucher** [comment]
can you please also fix the compiler warning?

**Review by dbaumgaertner — APPROVED** [review]
@armingeiser just a side comment. right now there is the folder "custom_response_functions" which only contains another folder with several response utilities. Wouldnt it make sense, in this case, to cut one folder level and rename the top folder to something like "custom_resposne_function_utilities" because the response functions are actually defined in the python script

**Comment by philbucher** [comment]
@dbaumgaertner this folder will also contain the adjoint elements and stuff

We could still discuss the name though

**Comment by dbaumgaertner** [comment]
Ah ok. Then it makes perfect sense!

**Pull request merged**
