### PR TITLE
Adding Biot as a parameter

### PR DESCRIPTION
**Pull request by salvalatorre**

### CODE REVIEW

**Review by ipouplana — APPROVED** [review]
Thanks @salvalatorre !

**Comment by maceligueta** [comment]
It would be nice if you also export the variable BIOT_COEFFICIENT to python. In case someone wants to modify it from Python.
Also, I think you could remove those lines you left commented out. Can we delete them, @ipouplana ?

**Review by ipouplana — CHANGES_REQUESTED** [review]
I forgot one thing.
You should add the new BIOT_COEFFICIENT parameter in the PoroMaterials.json (and .mdpa) of the 3 tests of the Poro. App [Poro tests](https://github.com/KratosMultiphysics/Kratos/tree/master/applications/PoromechanicsApplication/tests/element_tests).
I just calculated the value of the BC using the values of Young, Poisson and Ks of those tests and are the following:
- arc_length_test -> 0.98833
- consolidation_interface_3D -> 0.99999
- undrained_soil_column_2D -> 0.99999

You can check afterwards if the tests are running ok. If you find errors, maybe we will have to add the BC with a higher number of digits...

**Comment by ipouplana** [comment]
> It would be nice if you also export the variable BIOT_COEFFICIENT to python. In case someone wants to modify it from Python in the future.
> Also, I think you could remove those lines you left commented out. Can we delete them, @ipouplana ?

Go ahead, we can check in the history of the file anyway...

**Review by ipouplana — APPROVED** [review]
Great !

**Review by maceligueta — APPROVED** [review]

**Pull request merged**
