### PR TITLE
[Core] Missing protected in ReadMaterialsUtility

### PR DESCRIPTION
**Pull request by loumalouomega**
Just that

### CODE REVIEW

**Comment by loumalouomega** [comment]
Can anyone approve?

**Comment by philbucher** [comment]
Is this necessary?
I thought we still have no consensus in how to proceed overall with the mat-reading
@RiccardoRossi ?

**Comment by loumalouomega** [comment]
> 
> 
> Is this necessary?
> I thought we still have no consensus in how to proceed overall with the mat-reading
> @RiccardoRossi ?

For consistency I would say yes, there are other methods which are already protected, but not this one

**Review by philbucher — DISMISSED** [review]
approving based on this comment of @RiccardoRossi :
https://github.com/KratosMultiphysics/Kratos/pull/6136#discussion_r373456992

**Comment by loumalouomega** [comment]
Can anyone approve this?

**Comment by philbucher** [comment]
I did ...
but you need to merge master

**Comment by loumalouomega** [comment]
> I did ...
> but you need to merge master

Ups...

**Review by philbucher — APPROVED** [review]

**Comment by loumalouomega** [comment]
question, the new checks are mandatory?

**Comment by loumalouomega** [comment]
> 
> 
> question, the new checks are mandatory?

I cant see the details

**Comment by philbucher** [comment]
Yes, I just changed it 5 mins ago
Please merge master again, sorry for the inconveniece, should not happed again, only created some hassle in the transition period (which is during these days)
Once completed we will make a post informing everyone

**Comment by philbucher** [comment]
ok now you can merge once the checks passed :+1:

**Pull request merged**
