### PR TITLE
[Core] Printing number of geometries in the PrintData of the ModelPart

### PR DESCRIPTION
**Pull request by loumalouomega**
Minor add (I assume does not require a large discussion)

### CODE REVIEW

**Comment by philbucher** [comment]
@loumalouomega this PR made me realize that we might have a problem with the implementation in MPI, can you please keep it on hold until this was discussed?
Thx

**Comment by loumalouomega** [comment]
OK, but this junts prints data. The problem may come from the communicator which is not updated?

**Comment by philbucher** [comment]
Well the geometries would no longer live in the ModelPart, so the code you are adding here would have to be removed

**Comment by loumalouomega** [comment]
Of course, and will be added to the mesh.h

**Comment by tteschemacher** [comment]
Thanks @loumalouomega!

I think we can add it and modify it if it is required at another position, later.

**Comment by loumalouomega** [comment]
OK for me

**Review by tteschemacher — APPROVED** [review]

**Pull request merged**
