### PR TITLE
[Core] Minor typos in `linear_solver.h` doxygen

### PR DESCRIPTION
**Pull request by loumalouomega**
**📝 Description**

Minor typos in `linear_solver.h` doxygen.

**🆕 Changelog**

- [Minor typos in `linear_solver.h` doxygen](https://github.com/KratosMultiphysics/Kratos/commit/f7751eb5e44dcf4ed742d813bfcf3b9c5289b171)

### CODE REVIEW

**Review by philbucher — APPROVED** [review]

**Comment by philbucher** [comment]
@loumalouomega random question, are you using the MUMPS linear solver in altair?

**Comment by loumalouomega** [comment]
> @loumalouomega random question, are you using the MUMPS linear solver in altair?

That's the idea

**Comment by philbucher** [comment]
Do you have any experiences with it?
Like performance, stability etc?

Perhaps @ddiezrod can comment?

**Comment by loumalouomega** [comment]
> Do you have any experiences with it? Like performance, stability etc?
> 
> Perhaps @ddiezrod can comment?

Huuum, to have a proper benchmark is still peding. But  a priori MUMPs is fatser and more robust in MPI.

**Comment by ddiezrod** [comment]
> @loumalouomega random question, are you using the MUMPS linear solver in altair?

Hi @philbucher , not yet, we are still using pardiso.

**Comment by philbucher** [comment]
> > @loumalouomega random question, are you using the MUMPS linear solver in altair?
> 
> Hi @philbucher , not yet, we are still using pardiso.

Interesting, can you share why? I am just generally interested in direct solvers and their performance/behavior
I thought you were planning to use MUMPS in MPI? Are you currently not using a direct solver in MPI-simulations?

I know that there is also an MPI-parallel implementation of pardiso, but afaik this one is not integrated into Kratos

**Comment by loumalouomega** [comment]
> > > @loumalouomega random question, are you using the MUMPS linear solver in altair?
> > 
> > 
> > Hi @philbucher , not yet, we are still using pardiso.
> 
> Interesting, can you share why? I am just generally interested in direct solvers and their performance/behavior I thought you were planning to use MUMPS in MPI? Are you currently not using a direct solver in MPI-simulations?

We use direct solvers, currently in MPI we are using the ones existing in Trilinos. For MUMPS there are additional considerations for license reasons and is not the default one.

> I know that there is also an MPI-parallel implementation of pardiso, but afaik this one is not integrated into Kratos

No, Pardiso only in serial right now.

**Pull request merged**
