### PR TITLE
Rom brief description and some logos

### PR DESCRIPTION
**Pull request by SADPR**
**📝 Description**
This is a README.md pull request. I added some logos to the following applications:
- FluidDynamicsApplication
- ConvectionDiffusionApplication
- RomApplication
- CoSimulationApplication

I also added a text to the RomApplication README.md.

### CODE REVIEW

**Comment by loumalouomega** [comment]
Why do you call the FluidDynamicsApplication as CFD application?

**Comment by SADPR** [comment]
I changed to Fluid Dynamics (in the logo), previously it was for the letters to fit better.

**Review by loumalouomega — APPROVED** [review]
Okay from my side, wait to @philbucher and @rubenzorrilla to confirm CoSim and Fluid apps

**Comment by loumalouomega** [comment]
Can yo share the template so we can add the logos to other apps?

**Comment by SADPR** [comment]
Just right click and Save As ".svg" to the following image:
logos
Your inkscape might not have the Kratos Multiphysics font:
D3 Euronism

**Comment by loumalouomega** [comment]
> Just right click and Save As ".svg" to the following image: logos Your inkscape might not have the Kratos Multiphysics font: D3 Euronism

Please, upload here: https://github.com/KratosMultiphysics/Documentation/tree/master/Templates_files/Kratos_logo

**Comment by rubenzorrilla** [comment]
> they are not really readable in dark-mode: image

Besides, it is not advised to use times-type fonts to do graphical stuff.

**Pull request closed without merging**
