### PR TITLE
[StructuralMechanicsApplication] Replace Edges Faces with GenerateEdges and GenerateFaces

### PR DESCRIPTION
**Pull request by loumalouomega**
Just that

### CODE REVIEW

**Comment by tteschemacher** [comment]
Can Edges() and Faces() be removed then from the base class?

**Comment by loumalouomega** [comment]
> 
> 
> Can Edges() and Faces() be removed then from the base class?

Not now for retro-compatibility reasons

**Comment by philbucher** [comment]
@rubenzorrilla could you please check if this is the correct usage? I still don't fully understand when to use what

**Comment by tteschemacher** [comment]
> 
> 
> > Can Edges() and Faces() be removed then from the base class?
> 
> Not now for retro-compatibility reasons

Is there anybody else using that?

**Comment by loumalouomega** [comment]
> 
> 
> > > Can Edges() and Faces() be removed then from the base class?
> > 
> > 
> > Not now for retro-compatibility reasons
> 
> Is there anybody else using that?

It is still used in several places

**Review by rubenzorrilla — APPROVED** [review]
I think that in this case it is correct.

**Comment by AlejandroCornejo** [comment]
I use this methods in my elements I think. Should I replace `Edges()` by `GenerateEdges()` right? Why did we change that (just curiosity :))

**Comment by rubenzorrilla** [comment]
If you need the edges yes. The problem comes when you require the edges in 2D but you ask for them through the old `Faces()` method.

If you use the method to perform a boundary integral (lines in 2D or faces in 3D) you can use the `GenerateBoundaryEntities` as well.

**Pull request merged**
