### PR TITLE
[StructuralMechanicsApplication] The "moment reactions" are called TORQUE => MOMENT_REACTION

### LINKED ISSUE #1719: The "moment reactions" are called TORQUE
@KratosMultiphysics/structural-mechanics we shall find a better name for this...

### PR DESCRIPTION
**Pull request by loumalouomega**
Fixes #1719

### CODE REVIEW

**Comment by philbucher** [comment]
Looks good to me
I would like to add a warning, can you wait until tmr with merging pls?

**Review by philbucher — APPROVED** [review]
ok for me

**Comment by RiccardoRossi** [comment]
guys, take care not to break the solid...

**Comment by loumalouomega** [comment]
I added a new variable, not touching the previous one

**Comment by philbucher** [comment]
good thinking @loumalouomega !

**Comment by RiccardoRossi** [comment]
@jginternational does this need changes on the interface side?

**Comment by loumalouomega** [comment]
It is a minor change, doing

**Comment by loumalouomega** [comment]
https://github.com/KratosMultiphysics/GiDInterface/commit/f236f29757f4b29d79ecfa0120c75fc7e08b0024

**Pull request merged**
