### PR TITLE
[Core][GeomContainer] Allow existing geometries

### PR DESCRIPTION
**Pull request by philbucher**
This is a bugfix, that allows for adding existing Geometries, like it is done for Nodes, Elements and Conditions in the ModelPart.

Without this, Geometries cannot be used with SubSub...ModelParts

Test is added

### CODE REVIEW

**Review by loumalouomega — DISMISSED** [review]

**Comment by loumalouomega** [comment]
Ci is failing

**Comment by philbucher** [comment]
Yes need to update an error message 

Anyway want to add couple more tests

**Comment by philbucher** [comment]
I added a bunch of tests, which show basic and relevant usecases. Those were failing before my fix!

Now this is ready to be merged :)

**Review by loumalouomega — APPROVED** [review]
It is OK

**Pull request merged**
