### PR TITLE
[Core] Clean up and refactor of `AssignScalarFieldToEntitiesProcess` and `AssignScalarVariableToEntitiesProcess`

### PR DESCRIPTION
**Pull request by loumalouomega**
**📝 Description**

Some clean up and refactor of `AssignScalarFieldToEntitiesProcess` and `AssignScalarVariableToEntitiesProcess`

**🆕 Changelog**

- [Clean up AssignScalarFieldToEntitiesProcess](https://github.com/KratosMultiphysics/Kratos/commit/d2dda549754c1da0864103d77efabc48f8142b84)
- [Clean up AssignScalarVariableToEntitiesProcess](https://github.com/KratosMultiphysics/Kratos/commit/cdde58bb64b4c973a56bc64bc4954a4bea871aaa)
- [Update python interface](https://github.com/KratosMultiphysics/Kratos/commit/5c58b32a0df1dbbe511ae432f13c46dd518e518a)
- [Clean up python processes](https://github.com/KratosMultiphysics/Kratos/commit/99dadbcd8c778b5d63e9f500bc38e85adbd38f65)
- [Clean up test](https://github.com/KratosMultiphysics/Kratos/commit/2a5737b80f4a6a82fd8a984084ae0b3449148adb)

### CODE REVIEW

**Comment by loumalouomega** [comment]
Heloo @rubenzorrilla @roigcarlo

**Comment by roigcarlo** [comment]
Ok, but update the doc to reflect the new historical switch

**Review by roigcarlo — APPROVED** [review]

**Comment by loumalouomega** [comment]
> > @roigcarlo Doc added
> 
> Ok but next time, there was already a [`master`/docs/pages/Kratos/Processes/Assign_Values/assign_scalar_variable_process.md](https://github.com/KratosMultiphysics/Kratos/blob/master/docs/pages/Kratos/Processes/Assign_Values/assign_scalar_variable_process.md?rgh-link-date=2024-04-18T07%3A40%3A13Z) which refereed to the entities generic process, just change the value. No need to duplicate, just to add the new option

Those are different processes, take a look

**Comment by roigcarlo** [comment]
Nut sure to follow you.

The only difference is that the name of the .md is different and the fact that in the older version the entry point for master_salve is called `AssignScalarVariableToConstraintsProcess` and in your version is called `AssignScalarVariableToMasterSlaveConstraintsProcess`

**Comment by loumalouomega** [comment]
> Nut sure to follow you.
> 
> The only difference is that the name of the .md is different and the fact that in the older version the entry point for master_salve is called `AssignScalarVariableToConstraintsProcess` and in your version is called `AssignScalarVariableToMasterSlaveConstraintsProcess`

Yes, the problem is that for legacy reasons we have some processes with duplicated functionalities

**Comment by roigcarlo** [comment]
Visible confusion ¿?

There is only one `AssignVariableToXXXXX process (for example, for nodes as they have historical values):

Screenshot_2024-04-18_11-03-05

The entry point for that process is the file `AssignScalarVariableToEntitiesProcess`. This process internally calls different specialized version that should not be directly used by the user which are (and that's the reason they only appear as "entry points" in the dock page I linked):

* if value is number:
AssignScalarVariableToNodesProcess(self.model_part, params)
AssignScalarVariableToConditionsProcess(self.model_part, params)
AssignScalarVariableToElementsProcess(self.model_part, params)
AssignScalarVariableToMasterSlaveConstraintsProcess(self.model_part, params)

* if value is vector
AssignScalarFieldToNodesProcess(self.model_part, params)
AssignScalarFieldToConditionsProcess(self.model_part, params)
AssignScalarFieldToElementsProcess(self.model_part, params)

There is no duplicity here, the only think that has changed is that now there is an additional json config that allows the `` to also be able to call 

AssignScalarVariableHistoricalToNodesProcess(self.model_part, params)
AssignScalarFieldHistoricalToNodesProcess(self.model_part, params)

if the new switch you added is on.

Those new options and entry points is what I meant you to add in the doc.

**Comment by matekelemen** [comment]
@loumalouomega why did you adapt this process for `MasterSlaveConstraint`s? Are you using the `DataValueContainer` of `MasterSlaveConstraint`s somewhere?

I'm asking because neither `MasterSlaveConstraint` nor `LinearMasterSlaveConstraint` actually uses the `DataValueContainer` member `MasterSlaveConstraint::mData`, and I'm thinking about removing it because it's confusing.

**Comment by matekelemen** [comment]
Btw it seems to me that you could have used [proxies](https://github.com/KratosMultiphysics/Kratos/blob/d476ee0ed847d38aabfe25b6c24f6378a07b882a/kratos/utilities/proxies.h#L38) for this PR.

**Comment by loumalouomega** [comment]
> Btw it seems to me that you could have used [proxies](https://github.com/KratosMultiphysics/Kratos/blob/d476ee0ed847d38aabfe25b6c24f6378a07b882a/kratos/utilities/proxies.h#L38) for this PR.

I didn't knwo about that

**Comment by loumalouomega** [comment]
> @loumalouomega why did you adapt this process for `MasterSlaveConstraint`s? Are you using the `DataValueContainer` of `MasterSlaveConstraint`s somewhere?
> 
> I'm asking because neither `MasterSlaveConstraint` nor `LinearMasterSlaveConstraint` actually uses the `DataValueContainer` member `MasterSlaveConstraint::mData`, and I'm thinking about removing it because it's confusing.

To be consistent...

**Comment by loumalouomega** [comment]
> > @loumalouomega why did you adapt this process for `MasterSlaveConstraint`s? Are you using the `DataValueContainer` of `MasterSlaveConstraint`s somewhere?
> > I'm asking because neither `MasterSlaveConstraint` nor `LinearMasterSlaveConstraint` actually uses the `DataValueContainer` member `MasterSlaveConstraint::mData`, and I'm thinking about removing it because it's confusing.
> 
> To be consistent...

I am using it and it is used somewhere...

**Pull request merged**
