### PR TITLE
Addition of PERIODIC flag and a new joint activation process in PoromechanicsApp

### PR DESCRIPTION
**Pull request by ipouplana**
In essence, this PR adds the PERIODIC flag discussed in issue #336 along with a new process in the PoromechanicsApplication that uses the periodic conditions to set as active or inactive the pre-defined joint elements. 

@jcotela I have also modified the residualbased_block_builder_and_solver_periodic.h from the FluidDynamicsApplication with the new PERIODIC flag, but I did not touch anything from the trilinos_block_builder_and_solver_periodic.h...

Furthermore, @RiccardoRossi I had to modify one line in the ConstructMatrixStructure of the residualbased_block_builder_and_solver.h to avoid a problem with the size of matrix A when using periodic conditions.

@lorenzogracia , in order to implement the joint activation process, I had to use the NODAL_CAUCHY_STRESS_TENSOR previously defined in the DamApplication. Since the DamApp. derives from Poro.App., I moved this variable to the Poro. App. and modified your python solvers to import the variable from the Poro.

### CODE REVIEW

**Review by jcotela — CHANGES_REQUESTED** [review]
👍 for the changes on the periodic things, but I would ask you to re-check which files you are adding for the gid models. To keep download size small, we should try not to add gid files in our examples: keep the mdpa, keep the py and json or other configurationion files. Probably also the input files for GiD, but please remove the *png files.

**Review by jcotela — APPROVED** [review]

**Comment by jcotela** [comment]
Thanks @ipouplana I'm approving the changes to avoid blocking you but, since the periodic condition is the only part I checked, please wait a bit to see if someone else has more observations.

**Comment by ipouplana** [comment]
Ok, thanks @jcotela. I will wait until the rest of reviewers comment on this PR.

**Review by lorenzogracia — APPROVED** [review]
@ipouplana Regarding the definition of NODAL_CAUCHY_STRESS_TENSOR  in the poromechanics instead of dam there is no inconvenience, so go ahead.

**Comment by ipouplana** [comment]
If by the end of the day @RiccardoRossi shows no objections, I will merge this PR.

**Comment by RiccardoRossi** [comment]
Hi Ignaci,

for me i can merge. My only question is if you really need to call as "NODAL_" the cauchy stress. Can't you just plot CAUCHY_STRESS on the nodes?

anyway this is definitely not a reason for blocking the push. 

cheers

**Comment by ipouplana** [comment]
The NODAL_ was added just as a means to distinguish the stresses computed at the Gauss points (CHAUCHY_STRESS_TENSOR) from the smoothed nodal version. Sometimes we plot both of them in the post-process...

**Comment by RiccardoRossi** [comment]
Hi Ignasi,

i think you can plot both of them without having to distinguish the names, as one is printed on the gauss points and the other on the nodes

**Comment by ipouplana** [comment]
I know it, but it would be confusing for the end user...

**Comment by jcotela** [comment]
@RiccardoRossi every time I tried to do that, GiD refused to load it.

**Comment by RiccardoRossi** [comment]
ok then, sorry for the noise

**Pull request merged**
