### PR TITLE
[Core] Row operation not properly working on AMatrix

### PR DESCRIPTION
**Pull request by loumalouomega**
Fast patch. I can't see the origin of the error, if I print the values are apparently the same (maybe a memory leak, I can't use valgring->Ubuntu 18.10 has a broken valgring)

### CODE REVIEW

**Comment by josep-m-carbonell** [comment]
I think this is bad patch. If "row" does not work properly, it must be solved not patched.

**Comment by jcotela** [comment]
@loumalouomega which is the original problem? Is this giving you a segfault?

**Comment by loumalouomega** [comment]
> I think this is bad patch. If "row" does not work properly, it must be solved not patched.

Of course, that it is what I pretend with this PR, to "correct" the issue for the people porting their code to AMatrix not having this as bottleneck and inform about the issue.

**Comment by loumalouomega** [comment]
> @loumalouomega which is the original problem? Is this giving you a segfault?

No, the final result is different, but if I print the values it is the same, that's why i think is a memory leak, but I cannot check it because in Ubuntu 18.10 valgrind doesn't work

**Comment by jcotela** [comment]
@loumalouomega Is there a test I can try to see this? I'd like to take a look.

**Comment by loumalouomega** [comment]
> @loumalouomega Is there a test I can try to see this? I'd like to take a look.

Yes, the both tests of the two processes patched, the nodal_area_process and the nodal_gradient_process

**Comment by josep-m-carbonell** [comment]
>` I think this is bad patch. If "row" does not work properly, it must be solved not patched.`
> 
> Of course, that it is what I pretend with this PR, to "correct" the issue for the people porting their code to AMatrix not having this as bottleneck and inform about the issue.

I am sorry I have not seen any correction in the row method of Amatrix, only particular fixes in two processes.

**Comment by loumalouomega** [comment]
> > ` I think this is bad patch. If "row" does not work properly, it must be solved not patched.`
> > Of course, that it is what I pretend with this PR, to "correct" the issue for the people porting their code to AMatrix not having this as bottleneck and inform about the issue.
> 
> I am sorry I have not seen any correction in the row method of Amatrix, only particular fixes in two processes.

I was not able to fix the row operation, and this is not the intend of this PR. I am not able to find the reason the operation doesn't work properly

**Comment by pooyan-dadvand** [comment]
@loumalouomega Have you tried it in FullDebug? If not please check it in FullDebug

**Comment by loumalouomega** [comment]
> @loumalouomega Have you tried it in FullDebug? If not please check it in FullDebug

FullDebug with the glib flag

**Comment by pooyan-dadvand** [comment]
I would also go for fixing the row rather than making a patch as @josep-m-carbonell mentioning

**Comment by pooyan-dadvand** [comment]
Row has a clean test so please check it with valgrind. What is the problem with ubuntu valgrind?

**Comment by loumalouomega** [comment]
> Row has a clean test so please check it with valgrind. What is the problem with ubuntu valgrind?

The last Ubuntu 18.10 (not LTS) the valgring doesn't work, it gives an error when running anything, according to the Ubuntu forum they are concerned (but not doing anything right now).

I have a virtual machine with LTS, I can try with that.

**Comment by pooyan-dadvand** [comment]
> I have a virtual machine with LTS, I can try with that.

Please!

**Comment by loumalouomega** [comment]
> > I have a virtual machine with LTS, I can try with that.
> 
> Please!

On it

**Comment by loumalouomega** [comment]
@jcotela told me that the error is located. Should I close this or we proceed with this and wait for the proper fix?

**Comment by pooyan-dadvand** [comment]
I would keep it open until it is fixed

The problem is the fact that the AMatrix vectors are column vector and here we assigning a row vector to them. One solution would be to change the LHS to row_vector type which is the correct type but @jcotela realizes that there are many such a use cases which make such a fix very difficult. So I should figure out another way to deal with this problem

**Comment by loumalouomega** [comment]
I will close this, as @pooyan-dadvand is currently working on solving this issue

**Pull request closed without merging**
