### PR TITLE
DEM Adding RBE implementations to problem types

### PR DESCRIPTION
**Pull request by salvalatorre**
Adding RBE, Herschel-Bulkley implementations and some bug fixes to the new github problem type structure.
The path of KratosDEM.py and KratosSwimmingDEM.py should be still manually set to point to the local Kratos folders, as it was for the older problem types.

### CODE REVIEW

**Comment by salvalatorre** [comment]
Of course, this pull request passed my benchmarks... Further testing would be advisable, anyway :)

**Comment by joaquinirazabal** [comment]
Great work, Salva, it is working for me. However, I am still having problems with matplotlib, do you know something new about that?

**Comment by salvalatorre** [comment]
Yes, that is a pending task I still have to solve... F-DEMPack complains about that, but the same simulation would run when using the command line... :(

**Comment by joaquinirazabal** [comment]
Ok, thanks!

**Review by joaquinirazabal — APPROVED** [review]
OK!

**Pull request merged**
