### PR TITLE
[Core] correcting serializer test

### PR DESCRIPTION
**Pull request by philbucher**
Minor copy-paste error (found it while looking at the travis output)

### CODE REVIEW

**Review by roigcarlo — APPROVED** [review]
:+1: 

Was this the unused variable one ?

**Comment by philbucher** [comment]
the unused typedef:
~~~
In file included from /home/travis/build/KratosMultiphysics/Kratos/cmake_build/kratos/cotire/Kratos_CXX_unity_52_64.cxx:12:0:
/home/travis/build/KratosMultiphysics/Kratos/kratos/tests/includes/test_serializer.cpp: In member function ‘virtual void Kratos::Testing::TestSerializerBoundedMatrix::TestFunction()’:
/home/travis/build/KratosMultiphysics/Kratos/kratos/tests/includes/test_serializer.cpp:290:56: warning: typedef ‘using Matrix26Int = class boost::numeric::ublas::bounded_matrix<int, 2ul, 6ul>’ locally defined but not used [-Wunused-local-typedefs]
             using Matrix26Int = bounded_matrix<int,2,6>;
~~~

**Comment by roigcarlo** [comment]
Aaa that one, nice :+1:

**Comment by philbucher** [comment]
@roigcarlo it seems like appveyor is hanging somehow
I would still push this, I think it should be safe to commit

**Pull request merged**
