### PR TITLE
[core] Adding assign dofs to dof updater

### PR DESCRIPTION
**Pull request by josep-m-carbonell**
Adding a method to dof_updater to assign the solution to the dof's variables

### CODE REVIEW

**Review by msandre — CHANGES_REQUESTED** [review]
Please fix the formatting of the new code. 

Consider renaming `rDx` to `rX`

**Comment by josep-m-carbonell** [comment]
I kept the same format of the file, but I modified it as you requested now.

**Comment by josep-m-carbonell** [comment]
@msandre , are the changes ok ?

**Review by msandre — APPROVED** [review]
Thanks

**Pull request merged**
