### PR TITLE
[Core][ParallelUtils] adding support for exceptions

### LINKED ISSUE #9259: Errors in parallel regions are not correctly captured with visual studio compiler
**Description**
I know this is mainly a known problem. I just wanted to create the issue as I did not find any related to this.

The problem is that the run crashes if we try to throw any error in parallel regions using visual studio, so the user has no clue why their run failed. It seems gcc has something like an auto-wrapper for parallel regions using some kind of try-catch that visual studio lacks. This happens even if you are running with just one thread. I tried also adding KRATOS_TRY - KRATOS_CATCH but the run still crashes without any message.

I discussed with @pooyan-dadvand the possibility of calling the logger before the exception, but this seems more like a dirty trick than a real solution. I wonder if someone has any ideas of how this could be solved or if there is any current work around for it.

Thanks!

**Environment**
- Visual Studio (any version)

@roigcarlo @KratosMultiphysics/technical-committee

### PR DESCRIPTION
**Pull request by philbucher**
This PR is a draft to add exception handling to the `ParallelUtilities`. With this the exceptions occurring inside shared memory parallel regions will be properly printed. Following [this article](https://docs.microsoft.com/en-us/cpp/parallel/concrt/convert-an-openmp-loop-that-uses-exception-handling?view=msvc-170) it was actually quite straight forward.

My solution works for OpenMP based parallelism as well as for C++11 based parallelism

I used a similar principle as `KRATOS_TRY` / `KRATOS_CATCH`

So far I only ported one loop, if the solution is accepted I can also port the other ones

closes #9259 

example of an error from within a parallel region:
~~~
    TestParUtilsExceptions Failed with message: 
        Error: The following errors occured in a parallel region!
Thread #2 caught exception: Error: inside parallel region

in kratos/tests/cpp_tests/utilities/test_parallel_utilities.cpp:424:auto Testing::TestParUtilsExceptions::TestFunction()::(anonymous class)::operator()(double &) const
Thread #0 caught exception: Error: inside parallel region

in kratos/tests/cpp_tests/utilities/test_parallel_utilities.cpp:424:auto Testing::TestParUtilsExceptions::TestFunction()::(anonymous class)::operator()(double &) const
Thread #4 caught exception: Error: inside parallel region

in kratos/tests/cpp_tests/utilities/test_parallel_utilities.cpp:424:auto Testing::TestParUtilsExceptions::TestFunction()::(anonymous class)::operator()(double &) const
Thread #1 caught exception: Error: inside parallel region

in kratos/tests/cpp_tests/utilities/test_parallel_utilities.cpp:424:auto Testing::TestParUtilsExceptions::TestFunction()::(anonymous class)::operator()(double &) const
Thread #3 caught exception: Error: inside parallel region

in kratos/tests/cpp_tests/utilities/test_parallel_utilities.cpp:424:auto Testing::TestParUtilsExceptions::TestFunction()::(anonymous class)::operator()(double &) const


in kratos/utilities/parallel_utilities.h:199:void BlockPartition<vector<double, allocator<double> > &, __gnu_cxx::__normal_iterator<double *, vector<double, allocator<double> > >, 128>::for_each(TUnaryFunction &&) [TContainerType = vector<double, allocator<double> > &, TIteratorType = __gnu_cxx::__normal_iterator<double *, vector<double, allocator<double> > >, TMaxThreads = 128, TUnaryFunction = (lambda at /home/philipp/software/Kratos_master/kratos/tests/cpp_tests/utilities/test_parallel_utilities.cpp:423:33)]
~~~

### CODE REVIEW

**Comment by ddiezrod** [comment]
I checked this in one of my examples and it's working perfectly! I think this is really useful so I hope this can get merged. Thanks a lot @philbucher ;)!

**Comment by Vahid-Galavi** [comment]
We also checked it here and it works! Thanks @philbucher for the solution.

**Comment by philbucher** [comment]
@KratosMultiphysics/technical-committee now it is fully implemented and fully tested

**Review by RiccardoRossi — COMMENTED** [review]
what about the performance impact?

do you see any difference with or without this in loops that DO NOT throw exceptions?

**Comment by philbucher** [comment]
> what about the performance impact?
> 
> do you see any difference with or without this in loops that DO NOT throw exceptions?

**Short version:**
No measurable difference

**Long version:**
Thx to using the partitioning we don't need to check in each iteration but only in each thread, hence I don't expect a large, or any performance impact. In order to be sure I did a small test (see code attached to be sure). Test was done with 5 threads (my machine has 5 cores) and compiled with Clang 10. Since only the relative differences matter I think this is good.
The differences in the timings are not measurable

~~~c++
KRATOS_TEST_CASE_IN_SUITE(ParUtilsTiming, KratosCoreFastSuite)
{
    std::cout << std::endl;

    constexpr int num_runs = 20;

    const std::vector<std::size_t> vec_sizes {
        1000,
        10000,
        100000,
        1000000,
        10000000,
        100000000,
        1000000000
    };

    for (const std::size_t nsize : vec_sizes) {
        std::vector<double> data_vector(nsize, 2.54);

        double total_time = 0.0;

        for (int i=0; i<num_runs; ++i) {
            const auto timer_omp = BuiltinTimer();

            block_for_each(data_vector, [](double& item){
                item += std::pow(5.0, 0.1);
            });

            total_time += timer_omp.ElapsedSeconds();
        }

        std::cout << "TIMER PAR UTILS EXCEPTIONS for vec size " << nsize << " | time: " << total_time/num_runs << std::endl;
    }
}
~~~

**Comment by pooyan-dadvand** [comment]
I am not sure if the power function is not covering the difference as it is very expensive.

I believe the norm of the vector would be a better measure for your time comparison test cases

**Comment by philbucher** [comment]
I tried a bunch of different functions now but again, no measurable difference

**Review by pooyan-dadvand — APPROVED** [review]
@KratosMultiphysics/technical-committee agrees on this change and see it very useful

Thanks

**Comment by philbucher** [comment]
for the record, I updated the description in the Wiki

**Pull request merged**
