### PR TITLE
[FEMDEM] Adding various things

### PR DESCRIPTION
**Pull request by AlejandroCornejo**
In this PR I'm adding the Mohr-Coulomb yield surf and performed a tiny modification in the mmg_process.py in order to remesh when necessary.
Also some methods required for a project.

### CODE REVIEW

**Comment by AlejandroCornejo** [comment]
I've run the meshing test and the output is:
```
 |  /           |
 ' /   __| _` | __|  _ \   __|
 . \  |   (   | |   (   |\__ \
_|\_\_|  \__,_|\__|\___/ ____/
           Multi-Physics 7.0.0-94699e53fe-RelWithDebInfo
Compiled with OpenMP support.
Maximum OpenMP threads: 12.
Importing    KratosMeshingApplication
Initializing Kratos MeshingApplication...
CPP Unittests: StructuralMechanicsApplication not compiled
Unittests:
Running cpp unit tests ...
..........................
Ran 26 of 656 test cases in 1.14527s. OK.
Unittests: Finished running cpp unit tests!
Unittests:
Running python tests ...
Unittests: TetrahedraReconnectUtility process is not compiled and the corresponding tests will not be executed
Unittests: TetrahedraReconnectUtility process is not compiled and the corresponding tests will not be executed
..Triangle3D3: The [3](-0.263419,0.338901,0.252524) is in a distance: 0.00577466
Triangle3D3: The [3](-0.263419,0.338901,0.252524) is in a distance: 0.00304678
Triangle3D3: The [3](-0.175526,0.458274,0.0892903) is in a distance: 0.0256271
Triangle3D3: The [3](0.188049,0.199199,-0.415604) is in a distance: 0.0104827
Triangle3D3: The [3](-0.00841796,-0.480796,-0.136297) is in a distance: 0.00164565
Triangle3D3: The [3](0.441501,-0.0450113,0.223748) is in a distance: 0.00969658
Triangle3D3: The [3](-0.406118,-0.116707,0.259395) is in a distance: 0.0180281
Triangle3D3: The [3](-0.06218,-0.495917,0.00377325) is in a distance: 0.00620845
Triangle3D3: The [3](0.0890529,-0.486855,0.0674224) is in a distance: 0.0113554
Triangle3D3: The [3](0.0604449,0.37817,0.318612) is in a distance: 0.0166365
Triangle3D3: The [3](-0.351819,-0.304748,0.177182) is in a distance: 0.00117434
Triangle3D3: The [3](0.112221,-0.371227,0.312282) is in a distance: 0.0272063
Triangle3D3: The [3](-0.42709,-0.255216,0.0541861) is in a distance: 0.0490162
Triangle3D3: The [3](-0.263419,0.338901,0.252524) is in a distance: 0.0164197
Triangle3D3: The [3](-0.175526,0.458274,0.0892903) is in a distance: 0.0135515
.EEEEEEEE
======================================================================
ERROR: test_execution (meshing_application_test_factory.TwoDDynamicBeamTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\KRATOS_MULTIPHYSICS\Kratos\applications\MeshingApplication\tests\meshing_application_test_factory.py", line 64, in test_execution
    self.test.RunSolutionLoop()
AttributeError: 'TwoDDynamicBeamTest' object has no attribute 'test'

======================================================================
ERROR: test_execution (meshing_application_test_factory.TwoDDynamicBeamTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\KRATOS_MULTIPHYSICS\Kratos\applications\MeshingApplication\tests\meshing_application_test_factory.py", line 69, in tearDown
    self.test.Finalize()
AttributeError: 'TwoDDynamicBeamTest' object has no attribute 'test'

======================================================================
ERROR: test_execution (meshing_application_test_factory.TwoDDynamicBeamLineLoadTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\KRATOS_MULTIPHYSICS\Kratos\applications\MeshingApplication\tests\meshing_application_test_factory.py", line 64, in test_execution
    self.test.RunSolutionLoop()
AttributeError: 'TwoDDynamicBeamLineLoadTest' object has no attribute 'test'

======================================================================
ERROR: test_execution (meshing_application_test_factory.TwoDDynamicBeamLineLoadTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\KRATOS_MULTIPHYSICS\Kratos\applications\MeshingApplication\tests\meshing_application_test_factory.py", line 69, in tearDown
    self.test.Finalize()
AttributeError: 'TwoDDynamicBeamLineLoadTest' object has no attribute 'test'

======================================================================
ERROR: test_execution (meshing_application_test_factory.ThreeDShellTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\KRATOS_MULTIPHYSICS\Kratos\applications\MeshingApplication\tests\meshing_application_test_factory.py", line 64, in test_execution
    self.test.RunSolutionLoop()
AttributeError: 'ThreeDShellTest' object has no attribute 'test'

======================================================================
ERROR: test_execution (meshing_application_test_factory.ThreeDShellTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\KRATOS_MULTIPHYSICS\Kratos\applications\MeshingApplication\tests\meshing_application_test_factory.py", line 69, in tearDown
    self.test.Finalize()
AttributeError: 'ThreeDShellTest' object has no attribute 'test'

======================================================================
ERROR: test_execution (meshing_application_test_factory.ThreeDDynamicBeamTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\KRATOS_MULTIPHYSICS\Kratos\applications\MeshingApplication\tests\meshing_application_test_factory.py", line 64, in test_execution
    self.test.RunSolutionLoop()
AttributeError: 'ThreeDDynamicBeamTest' object has no attribute 'test'

======================================================================
ERROR: test_execution (meshing_application_test_factory.ThreeDDynamicBeamTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\KRATOS_MULTIPHYSICS\Kratos\applications\MeshingApplication\tests\meshing_application_test_factory.py", line 69, in tearDown
    self.test.Finalize()
AttributeError: 'ThreeDDynamicBeamTest' object has no attribute 'test'

----------------------------------------------------------------------
Ran 7 tests in 8.547s

FAILED (errors=8)
```

**Comment by AlejandroCornejo** [comment]
ping @loumalouomega

**Comment by loumalouomega** [comment]
@AlejandroCornejo , the tests fail. Let me think why

**Review by loumalouomega — APPROVED** [review]
OK

**Comment by philbucher** [comment]
guys I think this broke several tests:
~~~
Running tests for MeshingApplication
.....FF
  ## Warning: MMG5_surf: at least 1 negative or null density.
EFF
======================================================================
ERROR: test_execution (meshing_application_test_factory.ThreeDShellTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/Kratos/applications/MeshingApplication/tests/meshing_application_test_factory.py", line 64, in test_execution
    self.test.RunSolutionLoop()
  File "/home/ubuntu/Kratos/applications/StructuralMechanicsApplication/python_scripts/adaptative_remeshing_structural_mechanics_analysis.py", line 102, in RunSolutionLoop
    self.InitializeSolutionStep()
  File "/home/ubuntu/Kratos/kratos/python_scripts/analysis_stage.py", line 125, in InitializeSolutionStep
    self.ApplyBoundaryConditions() #here the processes are called
  File "/home/ubuntu/Kratos/kratos/python_scripts/analysis_stage.py", line 186, in ApplyBoundaryConditions
    process.ExecuteInitializeSolutionStep()
  File "/home/ubuntu/Kratos/applications/MeshingApplication/python_scripts/mmg_process.py", line 364, in ExecuteInitializeSolutionStep
    self._ExecuteRefinement()
  File "/home/ubuntu/Kratos/applications/MeshingApplication/python_scripts/mmg_process.py", line 477, in _ExecuteRefinement
    self.mmg_process.Execute()
RuntimeError: Error: attempting to add a new Condition with Id :53, unfortunately a (different) Condition with the same Id already exists




in kratos/includes/model_part.h:1125:void ModelPart::AddConditions(TIteratorType, TIteratorType, ModelPart::IndexType) [with TIteratorType = boost::iterators::indirect_iterator<__gnu_cxx::__normal_iterator<intrusive_ptr<Condition>*, vector<intrusive_ptr<Condition>, allocator<intrusive_ptr<Condition> > > >,...>; ModelPart::IndexType = long unsigned int]
   kratos/includes/model_part.h:1149:void ModelPart::AddConditions(TIteratorType, TIteratorType, ModelPart::IndexType) [with TIteratorType = boost::iterators::indirect_iterator<__gnu_cxx::__normal_iterator<intrusive_ptr<Condition>*, vector<intrusive_ptr<Condition>, allocator<intrusive_ptr<Condition> > > >,...>; ModelPart::IndexType = long unsigned int]
   /home/ubuntu/Kratos/applications/MeshingApplication/custom_processes/mmg_process.cpp:187:void MmgProcess<TMMGLibrary>::ExecuteInitializeSolutionStep() [with MMGLibrary TMMGLibrary = (MMGLibrary)2]
   /home/ubuntu/Kratos/applications/MeshingApplication/custom_processes/mmg_process.cpp:102:void MmgProcess<TMMGLibrary>::Execute() [with MMGLibrary TMMGLibrary = (MMGLibrary)2]


======================================================================
FAIL: test_execution (meshing_application_test_factory.TwoDDynamicBeamTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/Kratos/applications/MeshingApplication/tests/meshing_application_test_factory.py", line 69, in tearDown
    self.test.Finalize()
  File "/home/ubuntu/Kratos/kratos/python_scripts/analysis_stage.py", line 115, in Finalize
    process.ExecuteFinalize()
  File "/home/ubuntu/Kratos/kratos/python_scripts/compare_two_files_check_process.py", line 88, in ExecuteFinalize
    self.__CompareSolMetricFile()
  File "/home/ubuntu/Kratos/kratos/python_scripts/compare_two_files_check_process.py", line 322, in __CompareSolMetricFile
    lines_ref, lines_out = self.__GetFileLines()
  File "/home/ubuntu/Kratos/kratos/python_scripts/compare_two_files_check_process.py", line 135, in __GetFileLines
    self.assertTrue(num_lines_ref == num_lines_out, msg=err_msg + self.info_msg)
AssertionError: False is not true : Files have different number of lines!
Num Lines Reference File: 217
Num Lines Output File: 222
[CompareTwoFilesCheckProcess]: Failed with following parameters:
{
    "comparison_type": "sol_file",
    "dimension": 2,
    "help": "This process checks that two files are the same. This can be used in order to create tests, where a given solution is expected",
    "output_file_name": "mmg_lagrangian_test/beam2D_test_step=10.sol",
    "reference_file_name": "mmg_lagrangian_test/beam2D_test_result.sol",
    "relative_tolerance": 1e-09,
    "remove_output_file": true,
    "tolerance": 1e-06
}

======================================================================
FAIL: test_execution (meshing_application_test_factory.TwoDDynamicBeamLineLoadTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/Kratos/applications/MeshingApplication/tests/meshing_application_test_factory.py", line 69, in tearDown
    self.test.Finalize()
  File "/home/ubuntu/Kratos/kratos/python_scripts/analysis_stage.py", line 115, in Finalize
    process.ExecuteFinalize()
  File "/home/ubuntu/Kratos/kratos/python_scripts/compare_two_files_check_process.py", line 88, in ExecuteFinalize
    self.__CompareSolMetricFile()
  File "/home/ubuntu/Kratos/kratos/python_scripts/compare_two_files_check_process.py", line 322, in __CompareSolMetricFile
    lines_ref, lines_out = self.__GetFileLines()
  File "/home/ubuntu/Kratos/kratos/python_scripts/compare_two_files_check_process.py", line 135, in __GetFileLines
    self.assertTrue(num_lines_ref == num_lines_out, msg=err_msg + self.info_msg)
AssertionError: False is not true : Files have different number of lines!
Num Lines Reference File: 215
Num Lines Output File: 231
[CompareTwoFilesCheckProcess]: Failed with following parameters:
{
    "comparison_type": "sol_file",
    "dimension": 2,
    "help": "This process checks that two files are the same. This can be used in order to create tests, where a given solution is expected",
    "output_file_name": "mmg_lagrangian_test/beam2D_line_load_test_step=10.sol",
    "reference_file_name": "mmg_lagrangian_test/beam2D_line_load_test_result.sol",
    "relative_tolerance": 0.001,
    "remove_output_file": true,
    "tolerance": 0.001
}

======================================================================
FAIL: test_execution (meshing_application_test_factory.ThreeDShellTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/Kratos/applications/MeshingApplication/tests/meshing_application_test_factory.py", line 69, in tearDown
    self.test.Finalize()
  File "/home/ubuntu/Kratos/kratos/python_scripts/analysis_stage.py", line 115, in Finalize
    process.ExecuteFinalize()
  File "/home/ubuntu/Kratos/kratos/python_scripts/compare_two_files_check_process.py", line 88, in ExecuteFinalize
    self.__CompareSolMetricFile()
  File "/home/ubuntu/Kratos/kratos/python_scripts/compare_two_files_check_process.py", line 322, in __CompareSolMetricFile
    lines_ref, lines_out = self.__GetFileLines()
  File "/home/ubuntu/Kratos/kratos/python_scripts/compare_two_files_check_process.py", line 135, in __GetFileLines
    self.assertTrue(num_lines_ref == num_lines_out, msg=err_msg + self.info_msg)
AssertionError: False is not true : Files have different number of lines!
Num Lines Reference File: 76
Num Lines Output File: 104
[CompareTwoFilesCheckProcess]: Failed with following parameters:
{
    "comparison_type": "sol_file",
    "dimension": 3,
    "help": "This process checks that two files are the same. This can be used in order to create tests, where a given solution is expected",
    "output_file_name": "mmg_lagrangian_test/test_remesh_shell_step=2.sol",
    "reference_file_name": "mmg_lagrangian_test/test_remesh_shell_result.sol",
    "relative_tolerance": 0.001,
    "remove_output_file": true,
    "tolerance": 0.001
}

======================================================================
FAIL: test_execution (meshing_application_test_factory.ThreeDDynamicBeamTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/Kratos/applications/MeshingApplication/tests/meshing_application_test_factory.py", line 69, in tearDown
    self.test.Finalize()
  File "/home/ubuntu/Kratos/kratos/python_scripts/analysis_stage.py", line 115, in Finalize
    process.ExecuteFinalize()
  File "/home/ubuntu/Kratos/kratos/python_scripts/compare_two_files_check_process.py", line 88, in ExecuteFinalize
    self.__CompareSolMetricFile()
  File "/home/ubuntu/Kratos/kratos/python_scripts/compare_two_files_check_process.py", line 322, in __CompareSolMetricFile
    lines_ref, lines_out = self.__GetFileLines()
  File "/home/ubuntu/Kratos/kratos/python_scripts/compare_two_files_check_process.py", line 135, in __GetFileLines
    self.assertTrue(num_lines_ref == num_lines_out, msg=err_msg + self.info_msg)
AssertionError: False is not true : Files have different number of lines!
Num Lines Reference File: 236
Num Lines Output File: 477
[CompareTwoFilesCheckProcess]: Failed with following parameters:
{
    "comparison_type": "sol_file",
    "dimension": 3,
    "help": "This process checks that two files are the same. This can be used in order to create tests, where a given solution is expected",
    "output_file_name": "mmg_lagrangian_test/beam3D_test_step=3.sol",
    "reference_file_name": "mmg_lagrangian_test/beam3D_test_result.sol",
    "relative_tolerance": 0.001,
    "remove_output_file": true,
    "tolerance": 0.001
}

----------------------------------------------------------------------
Ran 9 tests in 32.948s

FAILED (failures=4, errors=1)
~~~

**Comment by loumalouomega** [comment]
I am quite sure we run the tests

**Comment by loumalouomega** [comment]
Indeed

**Pull request merged**
