### PR TITLE
[FastPR][Core] Enabling += operator in automatic differentiation.

### PR DESCRIPTION
**Pull request by rubenzorrilla**
**Description**
This makes possible to use the `+=` operators when using automatic differentiation for the elemental RHS and LHS generation. This will avoid the auxiliary arrays bottlenecks.

Credit to @RiccardoRossi (I just checked out the file from his draft PR #7972 ). Once this is merged, we can update the elements accordingly.

### CODE REVIEW

**Comment by loumalouomega** [comment]
Thanks @rubenzorrilla for saying Automatic Differentation, which is the technically correct. We should create a test in order to avoid issues in futures changes. I still need to check that it works with my implementations

**Review by loumalouomega — CHANGES_REQUESTED** [review]
Thanks @rubenzorrilla for saying Automatic Differentation, which is the technically correct. We should create a test in order to avoid issues in futures changes. I still need to check that it works with my implementations, because I already implemented += in my local implementation

**Comment by rubenzorrilla** [comment]
> Thanks @rubenzorrilla for saying Automatic Differentation, which is the technically correct. We should create a test in order to avoid issues in futures changes. I still need to check that it works with my implementations, because I already implemented += in my local implementation

Would be nice to have such test. However, I don't know how to do it.. Just mentioning that the old behavior is kept by default, so the old element generation scripts should work as they used to. My plan is to merge this and amend the fluid elements in a future PR (maybe we can do so with yours).

**Comment by loumalouomega** [comment]
> > Thanks @rubenzorrilla for saying Automatic Differentation, which is the technically correct. We should create a test in order to avoid issues in futures changes. I still need to check that it works with my implementations, because I already implemented += in my local implementation
> 
> Would be nice to have such test. However, I don't know how to do it.. Just mentioning that the old behavior is kept by default, so the old element generation scripts should work as they used to. My plan is to merge this and amend the fluid elements in a future PR (maybe we can do so with yours).

Just mentioning, I am right now checking my stuff works and patching. We can think in a test in a future. A very cutre way will be to generate a very simple element and check that the output is the same, but I am not sure if this will be problemantic depending of the version of sympy

**Comment by rubenzorrilla** [comment]
> > > Thanks @rubenzorrilla for saying Automatic Differentation, which is the technically correct. We should create a test in order to avoid issues in futures changes. I still need to check that it works with my implementations, because I already implemented += in my local implementation
> > 
> > 
> > Would be nice to have such test. However, I don't know how to do it.. Just mentioning that the old behavior is kept by default, so the old element generation scripts should work as they used to. My plan is to merge this and amend the fluid elements in a future PR (maybe we can do so with yours).
> 
> Just mentioning, I am right now checking my stuff works and patching. We can think in a test in a future. A very cutre way will be to generate a very simple element and check that the output is the same, but I am not sure if this will be problemantic depending of the version of sympy

The unique thing that comes to my mind is something like this... But as you said it could be problematic... @RiccardoRossi any idea?

**Review by loumalouomega — APPROVED** [review]
I have documented the base utilities, replace duplicated code in mine, added TODOs and check that it works

**Comment by rubenzorrilla** [comment]
@RiccardoRossi merging so we can start to apply it to the "symbolic" family of elements.

**Pull request merged**
