### PR TITLE
Reducing the step precision in gidoutput

### PR DESCRIPTION
**Pull request by bodhinandach**
A small change in printing precision of time for better output handling as stated in issue #2098.

### CODE REVIEW

**Review by loumalouomega — DISMISSED** [review]
For me OK, let's wait for @jginternational

**Comment by roigcarlo** [comment]
Also ok!

**Comment by jcotela** [comment]
Just a minor comment: if we change this, we should also change the precision used by the gid_output_process to write the list file(s)... Otherwise we could get file names that don't match.

**Comment by bodhinandach** [comment]
@jcotela Indeed, actually my change is according to the precision level in the gid_output_process to write the list files. Please refer to:
https://github.com/KratosMultiphysics/Kratos/blob/551a38c4b7da28ad14f6ba3ada7c7a1cf343db3b/kratos/python_scripts/gid_output_process.py#L569

**Comment by jcotela** [comment]
Then I would suggest changing the precision there, instead of in gidpost. The reasoning is that we have direct control of gid_output_process, while the changes in gidpost might easily be lost next time we update it.

**Comment by bodhinandach** [comment]
@jcotela I have tried to do that there as I wrote in a comment in issue #2098.

**Comment by jcotela** [comment]
So, just for me to understand the problem: if you set the line you cited above to `pretty_label = "_{0:.16g}".format(step_label)`, it does not print the same filename as gidpost?

Anyway, I agree with what has been mentioned in the other thread: using the step count (not time) as label would get rid of this problem.

**Comment by bodhinandach** [comment]
@jcotela thanks a lot for the suggestions. I have consulted with the GiD team and we came up with a solution. I will push it in this branch.

**Comment by bodhinandach** [comment]
@loumalouomega @jcotela please confirm the recent commits. With the current code, we modify the precision in the `gid_output_process` by converting it to a string and then again back to python double.

**Review by loumalouomega — APPROVED** [review]
Thanks! :+1:

**Review by jcotela — APPROVED** [review]
:+1: OK for me

**Pull request merged**
