### PR TITLE
 [Core] Adding HDF5 file to gitignore

### PR DESCRIPTION
**Pull request by loumalouomega**

### CODE REVIEW

**Comment by philbucher** [comment]
seems good to me, one question though:
Does the `*.h5` ending matter when reading those files? It might be the case that some reference files have to be committed.

Btw where did you come across the h5 files? I though the tests using them automatically delete them afterwards?

**Comment by loumalouomega** [comment]
Nope, the h5 files are still there in some tests

**Comment by philbucher** [comment]
which test are you referring to?
Independent of this PR I still think they should be removed

**Comment by jcotela** [comment]
@loumalouomega the hdf5 files should be deleted by the tests. If you got them, it is likely that the relevant test is failing. It would be useful if you could tell us which ones in order to fix it.

**Comment by loumalouomega** [comment]
I will check

**Comment by loumalouomega** [comment]
OK, right now the only tests generating files are the *.dat files generated in the FluidDynamicsApplication

**Comment by loumalouomega** [comment]
FluidDynamicsApplication/tests/CylinderTest/cylinder_test_probe1.dat
FluidDynamicsApplication/tests/CylinderTest/cylinder_test_probe2.dat
FluidDynamicsApplication/tests/CylinderTest/NoSlip2D_cylinder_drag.dat

**Comment by loumalouomega** [comment]
I will close this then

**Pull request closed without merging**
