### PR TITLE
Apps/proper pybind namespace

### PR DESCRIPTION
**Pull request by philbucher**
using the proper pybind namesapce in the EigenSolversApp and the MeshmovingApp

FYI @oberbichler @armingeiser @AndreasWinterstein

### CODE REVIEW

**Review by jcotela — APPROVED** [review]
:+1: Thanks a lot for taking the time to clean up this.

**Review by armingeiser — APPROVED** [review]

**Comment by philbucher** [comment]
@bodhinandach here you have an example of how you should update your app

Thanks!

**Comment by bodhinandach** [comment]
got it @philbucher!

**Comment by philbucher** [comment]
seconds too late :)

**Pull request merged**
