### PR TITLE
Fixing potentially unsafe access in parallel regions.

### PR DESCRIPTION
**Pull request by jcotela**
Minor issue in the fractional step conditions: Reading ProcessInfo might not be threadsafe if FRACTIONAL_STEP is for some reason uninitialized.

### CODE REVIEW

**Comment by jcotela** [comment]
I fixed the formatting in the last commit, please disregard whitespace in the review (or check only the first commit).

**Comment by philbucher** [comment]
such things should be solved with #2993 right?

**Comment by jcotela** [comment]
@philbucher you are right, I forgot we were also including this particular issue there. 

I'm a bit of two minds regarding what to do now. On one hand, the fix in your PR is cleaner. On the other, it might also take longer to merge, since it is much more complex/intrusive, and once it is merged I'll have to do a pass removing this kind of redefinitions on all my elements anyways.

**Comment by philbucher** [comment]
@jcotela I was just curious, please go ahead with this PR

**Review by RiccardoRossi — APPROVED** [review]
i am approving since the fix is ok, however note that this will always return 0 if it is not initialized, so it will not be a memory error but the simulation will fail

**Comment by jcotela** [comment]
@RiccardoRossi I agree, even if it does not segfault, the element is useless. However, the GiD interface is using it by default on fluid problems (even if monolithic), relying on the solver to replace them. I had to disable the element replacing in a test I'm trying now and this was giving me trouble, so I thought I could make it a bit more robust.

**Pull request merged**
