### PR TITLE
[Exaqute] Application creation

### PR DESCRIPTION
**Pull request by riccardotosi**
The aim of this application is to store here developments (in my case related to the ExaQUte project) that are not still ready to be merged in the corresponding application. This decision came after a discussion with @RiccardoRossi and @rubenzorrilla.
Referencing other ExaQUte members: @marcnunezc, @roigcarlo.

### CODE REVIEW

**Review by RiccardoRossi — APPROVED** [review]

**Review by philbucher — CHANGES_REQUESTED** [review]
**I am not sure if this should go into the main-repo!**

In general I would say that we should not commit project related stuff unless it is general enough for other applications as well
I mean, pretty much every phd student has one or several projects, if everyone would commit this then we would have a huge mess.

Furthermore if you have developments that are not ready, then you can have them in a separate branch or fork until they are ready to be merged/integrated in one of the apps

Also what happens to this app after Exacute is over?

**Comment by RiccardoRossi** [comment]
dear @philbucher

we doscussed this with @rubenzorrilla

this will be a "research application". we cannot keep having branches
opened since we will have many of them and it becomes inviable

**Comment by RiccardoRossi** [comment]
just to add that this should not go in the CI, and maintenance should be on
the mantainer

**Comment by rubenzorrilla** [comment]
> **I am not sure if this should go into the main-repo!**
> 
> In general I would say that we should not commit project related stuff unless it is general enough for other applications as well
> I mean, pretty much every phd student has one or several projects, if everyone would commit this then we would have a huge mess.
> 
> Furthermore if you have developments that are not ready, then you can have them in a separate branch or fork until they are ready to be merged/integrated in one of the apps
> 
> Also what happens to this app after Exacute is over?

In general terms, you are completely right and I totally agree. However, the features of this application will be moved to the FluidDynamicsApplication as soon as they are mature enough, sufficiently validated and optimal (e.g. @riccardotosi is aiming to test several error estimators in this app. and then the optimal one will be implemented in the FluidDynamicsApplication). Thus, more than a "project" application, we can think of this application as a FluidDynamicsApplication (as well as other fluid related apps) sandbox.

Since it raised in the framework of the ExaQUte project, we agreed in this name. The idea is that, as soon as we have the core and research applications (@KratosMultiphysics/technical-committee  must push this forward) this application will automatically become a research one.

Since the ExaQUte project involves quite a lot of developers, and quite a lot of applications wich are constantly evolving, Even though I think that your concern is fair enough, I feel that the fork solution might introduce complexities which will not exist when we solve the core and research stuff.

**Comment by philbucher** [comment]
@RiccardoRossi can we discuss this in person since you are here?

@exacuteguys: what happens to this app after exacute?

**Review by philbucher — APPROVED** [review]
Removing block after talking to @RiccardoRossi 

maybe in the future we can find a better solution to include such dev-apps (e.g. research-app or external-app) we will see

**Pull request merged**
