### PR TITLE
[Core] Enhance mp  to work with GeometryType

### PR DESCRIPTION
**Pull request by dagmawibekel**
Hi,
this PR makes it possible to create elements and conditions with GeometrieVectors.

### CODE REVIEW

**Comment by philbucher** [comment]
isn't this a duplicate of #6335?

**Comment by dagmawibekel** [comment]
I don't know tbh. I was talking to @tteschemacher and he was suggesting to do it this way. 
I'll look at the other pr. Thanks!

**Comment by philbucher** [comment]
@dagmawibekel good to see you are also working on this
Here are a few things / code of conduct for contributing (@KratosMultiphysics/technical-committee we should push this!):
- changes in the Core should be done (if possible) in separate PRs
- Tests for new features are mandatory
- In general, the smaller the PRs are, the faster they are accepted. If you change many files involving many ppl then approval can take long. 
    - I.e. in this case you seem to have many changes unrelated to the changes in the core, I would make a separate PR merging only those (isn't there already one?)
    - Especially with cosmetic changes (e.g. changing `int` to `std::size_t`) it is preferred to make separate PRs, those can be approved very fast
    - This way of working takes some time to getting used to, but I believe it pays of, especially when working in a team.

**Comment by tteschemacher** [comment]
These are different things. This PR adds the overloaded create new element with a pointer to the Geometry. The one which was excluded to python did accept a list of nodes only

The other PR adds the corresponding create geometries. Thus, those one can be used in combination.

**Comment by tteschemacher** [comment]
I think in this case you didn't want to merge the shell test branch, did you?

**Comment by philbucher** [comment]
#6335 also adds the functions with Geom-pointers as input : https://github.com/KratosMultiphysics/Kratos/pull/6335/files#diff-4671399f60e098fe7aa9200eeb335d20R1790-R1793

**Comment by philbucher** [comment]
ah nevermind now I got it, sorry

**Comment by dagmawibekel** [comment]
Ups. I'll make a different clean PR!

**Comment by tteschemacher** [comment]
> Ups. I'll make a different clean PR!

That would be the easiest I suppose.

**Comment by rubenzorrilla** [comment]
@dagmawibekel did you intentionally keep the branch opened?

**Comment by dagmawibekel** [comment]
Actually it can be deleted, since I have a new clean branch

**Pull request closed without merging**
