### PR TITLE
[External] Adding Google benchmark option in CMake

### PR DESCRIPTION
**Pull request by loumalouomega**
**📝 Description**

Related https://github.com/KratosMultiphysics/Kratos/pull/12861

This PR adds (as external download like in GTest) Google benchmark, see https://github.com/google/benchmark. It will generate one binary per file automatically detected in the `benchmark` folder. The executable will be in the binary `benchmark` folder.

It is activated with `KRATOS_BUILD_BENCHMARK`, which is disabled by default.

Here an example of usage:

~~~c++
// System includes

// External includes
#include <benchmark/benchmark.h>

// Project includes
#include "geometries/point.h"
#include "geometries/triangle_3d_3.h"
#include "utilities/geometry_utilities/nearest_point_utilities.h"

namespace Kratos
{

// Sample data for benchmarking
Point::Pointer p_point_1(make_shared<Point>( 0.0, 0.0, 0.0));
Point::Pointer p_point_2(make_shared<Point>( 1.0, 0.0, 0.0));
Point::Pointer p_point_3(make_shared<Point>( 0.0, 1.0, 0.0));

Triangle3D3<Point> triangle(p_point_1, p_point_3, p_point_2);
Point nearest_point(0.0, 0.0, 0.0);
Point inside_point(0.2, 0.1, 0.00);

static void BM_TriangleNearestPoint(benchmark::State& state) {
    for (auto _ : state) {
        NearestPointUtilities::TriangleNearestPoint(inside_point, triangle, nearest_point);
    }
}

// Register the function as a benchmark
BENCHMARK(BM_TriangleNearestPoint);

}  // namespace Kratos

BENCHMARK_MAIN();
~~~

It also includes a python script in order to compare the results (exported as json), example:

image

**🆕 Changelog**

- [Adding Google benchmark option in CMake](https://github.com/KratosMultiphysics/Kratos/commit/e7df3b3c73d29c2cd6f01b796b3f0f17e6ba3352)
- [Add benchmark for nearest point calculation in triangle geometry (example)](https://github.com/KratosMultiphysics/Kratos/commit/c4a47dede0c0eada55c80b5d10c98617ab1eb031)
- [Add script to generate combined plots from Google Benchmark JSON outputs](https://github.com/KratosMultiphysics/Kratos/commit/27ae59b4d9ce74c1b637742bf0d39e0c318e301b)

### CODE REVIEW

**Review by roigcarlo — COMMENTED** [review]
From my side, :+1: 

Thx for the clean implementation.

Could you add a `kratos_add_benchmarks` call into the core to compile the example maybe? or you plan to do it in another PR¿

**Comment by loumalouomega** [comment]
> Could you add a `kratos_add_benchmarks` call into the core to compile the example maybe? or you plan to do it in another PR¿

I don't get you

**Comment by roigcarlo** [comment]
You add an example but its not compiling, or I am missing something?

**Review by roigcarlo — APPROVED** [review]
Well to be honest it does not matter in the CI, ok

**Pull request merged**
