### PR TITLE
[Core] Unify SearchUtilities

### PR DESCRIPTION
**Pull request by loumalouomega**
**📝 Description**

As there is no direct MPI dependency in the `MPISearchUtilities`, only`Datacommunicator`, I move the code to the core so it can be reused in serial/MPI without MPICore dependency.

**🆕 Changelog**

- [Unify SearchUtilities](https://github.com/KratosMultiphysics/Kratos/commit/de1f6be4a882169e7eb819f5c068374a970ba8aa)

### CODE REVIEW

**Comment by loumalouomega** [comment]
Cloasing https://github.com/KratosMultiphysics/Kratos/pull/11689 as it is included here

**Comment by loumalouomega** [comment]
@philbucher intel compiler is failing: https://github.com/KratosMultiphysics/Kratos/actions/runs/6638261215/job/18034253599?pr=11710

**Comment by loumalouomega** [comment]
@pooyan-dadvand @roigcarlo

**Comment by loumalouomega** [comment]
This is the only pending transition PR for #11719, can you check @roigcarlo

**Comment by roigcarlo** [comment]
On it

**Review by roigcarlo — APPROVED** [review]
:+1: Fine, I just wanted to make sure there were no mpi dependencies after changing the utlities, but I forgot it existed. 

All right!

**Pull request merged**
