### PR TITLE
[Iga] Remove anurbs dependencies from the IgaApplication

### PR DESCRIPTION
**Pull request by tteschemacher**
Hi,

I would like to remove the ANurbs dependency of the IgaApplication as the dependencies of the application are unfortunately not working with the latest version anymore and as we want to move to the CAD geometries in the Core. Can you agree with that @oberbichler ?

### CODE REVIEW

**Comment by oberbichler** [comment]
Since I had to progress with the library while waiting on your I/O the current state of ANurbs is not compatible wirh Kratos anymore. If you want to get the last compatible version you should check the commit id inside the travis build script (which is probably more then a year old).

**Comment by tteschemacher** [comment]
Do you prefer that we keep the dependencies?

**Comment by oberbichler** [comment]
I don’t know what you want to do. If you just want to get this running then you must use an old version. Actually no one is using this application (at least I am not using it since a year).

**Comment by tteschemacher** [comment]
I want to have an application for Iga stuff.

thomas <notifications@github.com> schrieb am Mi., 4. Sep. 2019, 22:27:

**Comment by oberbichler** [comment]
That was the intention when I created this application... I have no problem removing the links. Actually it was the plan to implement the library in Kratos…

A small update on how to proceed would be very helpful.

**Review by philbucher — APPROVED** [review]
approving since this will be soon in the Core

**Comment by tteschemacher** [comment]
Ok so my goal would be as following:
1. cleaning up the IgaApplication that it compiles without dependencies
2. introducing simple conditions (load/ support/ couping) and elements (1p(Membrane) 3p/ 5p/ 7p) that show the way that Iga can be now used with the stuff from the core. On this developement we can then enhance the much mor sofisticated coupling conditions/elements that you developed.
3. to enlargen the scope and the possibilities I would like to derive the IgaApplication from the StructuralMechanicsApplication. All processes are already depending on it thus we can also let the elements being derived from the StructuralMechanics. We discussed already about a possible integration of sensitivities and here derivation would ease the procedure a lot. Hopefully, as things are in the core then, we will be able to put import options already in the StructuralMechanics, this would reduce the size of the IgaApp heavily.

Is this also ok for you @oberbichler please also post your suggestions.

**Pull request merged**
