### PR TITLE
Change due to modifications in SolidMechanicsApplication

### PR DESCRIPTION
**Pull request by joaquinirazabal**
Some changes were developed in the SolidMechanicsApplication related to the convergence criterion that broke our code. From my point of view, it would be better to rely less on other applications. Do you think this is ok?

Dam tests are running correctly, there are differences in some of them, but those differences are always lower than 0.001% (negligible).

### CODE REVIEW

**Comment by ipouplana** [comment]
Hi @joaquinirazabal.
Dependencies on other applications have advantages and disadvantages, and I think that in general the number of advantages is larger than the number of disadvantages...
Having said that, I see no problem in using the convergence criterion of the Kratos core

**Review by ipouplana — APPROVED** [review]

**Comment by loumalouomega** [comment]
@ipouplana can you extend your argument?, personally I try to use as much as I can the things implemented on the Core. The core has more extended tests, and is more stable on time (we try not to change often the core implementations). 

Besides, I don't understand the need of duplicate code between applications and the core if doesn't add new features, it makes the code more difficult to maintain and bugs are more difficult to tackle

**Comment by ipouplana** [comment]
Hi @loumalouomega , maybe I was not very clear before. 

I was not saying that it is bad to use the things implemented in the Core. On the contrary, I too believe it is better to use the things that are already in the Core (if they are useful). 

I was trying to say that having dependencies on other applications is normally better than not having any dependencies but then reimplementing or copying things by yourself.

The problem is that sometimes you need to use specific things that are not in the Core, but are already in other applications. Then, I see normal to have dependencies on those applications. 
And I quite don't like the idea of sending all what is inside an application to the Core because, in my opinion, it should remain clean and general to everyone in Kratos.

**Comment by joaquinirazabal** [comment]
Thanks for the explanation, I totally agree. Merged!

**Comment by loumalouomega** [comment]
Agree too, thanks for the explanation.

**Pull request merged**
