### PR TITLE
[StructuralMechanicsApplication] Clean up and reducing code duplication in hyperelastic NeoHoolkean  laws

### PR DESCRIPTION
**Pull request by loumalouomega**
Complements #2862

In order to prepare the hyperelastic CL for the creating the large deformation plasticity laws I cleaned up, reduced duplicated code and added missing methods to the NeoHookean hyperelastic laws

### CODE REVIEW

**Comment by loumalouomega** [comment]
@RiccardoRossi would be interesting to create a base Hyperelastic law, or you prefer to duplicate a little bit the code and ovoid that double heritage?

**Comment by frastellini** [comment]
thank you @loumalouomega I looks fine to me...

**Review by frastellini — APPROVED** [review]
It looks fine to me

**Comment by loumalouomega** [comment]
Thanks

**Pull request merged**
