### PR TITLE
[Core]Replacing int for std::size_t on SubModelPartUtility

### LINKED ISSUE #2191: Cpp test failure in master
@roigcarlo  would you please check if you have the same error? It also happens to me on `core/third-step-toward-amatrix` branch. Would you please also check that branch?

image

### PR DESCRIPTION
**Pull request by loumalouomega**

### CODE REVIEW

**Comment by loumalouomega** [comment]
@miguelmaso Can you check everything still works?

**Comment by loumalouomega** [comment]
@pooyan-dadvand Can you check if this give you problems. In my case was giving problems just in Debug. This solves the problem

**Comment by loumalouomega** [comment]
Ping

**Comment by roigcarlo** [comment]
The changes of type from `int` to `IndexType` are good to me.

Fix for #2191 has already been implemented in #2209. Aside from that, I have problems understanding other changes in the commit. What is the criteria to use referenced over non referenced variables? I see a lot of changes in that direction.

**Comment by loumalouomega** [comment]
The changes are in variables that used to be const int& -> const int and idem for the double. Adding missing references to some arrays

**Review by miguelmaso — APPROVED** [review]
sorry for the delay

**Pull request merged**
