### PR TITLE
Update linear solver names

### PR DESCRIPTION
**Pull request by philbucher**
using the new names to avoid deprecation-warnings

### CODE REVIEW

**Review by loumalouomega — APPROVED** [review]

**Comment by bodhinandach** [comment]
Hi @philbucher, Just want to check what is different between "AMGCL" and "amgcl"? Because some of my local tests are failing with "amgcl" after this is merged.

**Comment by philbucher** [comment]
AMGCL: old name
amgcl: new name

What is the error you get?

**Comment by bodhinandach** [comment]
The new amgcl can't solve the linear system involving zero stiffness diagonal. When I changed back to AMGCL that works fine. The error is that my residual goes to "-nan" from the very first step, therefore diverge.

**Comment by bodhinandach** [comment]
Also, I am afraid that the convergence rate of the new amgcl is slower than the old one. With the same number of iterations and same settings, the old one converges to the tolerance while the new one not.

**Comment by philbucher** [comment]
This is strange
It is supposed to be the exact same solver, only with a different name
I will check

**Comment by bodhinandach** [comment]
Okay. Let me know. I can show it to you tomorrow also.

**Comment by bodhinandach** [comment]
amgcl
AMGCL

amgcl
amgcl

Same settings, just changing the name.

**Comment by philbucher** [comment]
Sth is fishy
You are not getting deprecation-warnings which should be the case if you use the old name (AMGCL)

**Comment by philbucher** [comment]
solved in #4064

**Pull request merged**
