### PR TITLE
[Core][Model] changing to error when retrieving from flat map

### PR DESCRIPTION
**Pull request by philbucher**
as discussed / announced
I will remove the implementation in a future PR, this way it is easier to keep a nice error message

### CODE REVIEW

**Comment by philbucher** [comment]
@KratosMultiphysics/fluid-dynamics @rubenzorrilla There are some tests failing because they still use the flat-map
Can you please update the tests?

**Comment by philbucher** [comment]
@KratosMultiphysics/technical-committee : this will go in right after the release

**Comment by philbucher** [comment]
@KratosMultiphysics/technical-committee now it should work I believe
can someone approve it please?

**Review by loumalouomega — DISMISSED** [review]
:+1:

**Comment by philbucher** [comment]
Can you reapprove pls?

**Review by loumalouomega — APPROVED** [review]

**Comment by loumalouomega** [comment]
https://github.com/KratosMultiphysics/Kratos/pull/6138 I have this small PR wink 😉

**Comment by RiccardoRossi** [comment]
well done!

**Pull request merged**
