### PR TITLE
Correction of the Westergaard Formula

### PR DESCRIPTION
**Pull request by lorenzogracia**
Hydrodynamics effects are taken into account when the movement of the dam is  in the upstream direction

### CODE REVIEW

**Review by ipouplana — APPROVED** [review]
I know that this change is necessary, so I approve it. Perhaps, though, you could add a more clear comment on the fact the Westergaard effects are taken into account only when the unit_acceleration < 0.0 (regarding how one must orientate the dam in the model...)

**Comment by ipouplana** [comment]
@roigcarlo is it ok for us to merge this change? because I see that the following checks have failed:

continuous-integration/appveyor/branch — AppVeyor build failed 
continuous-integration/appveyor/pr — AppVeyor build failed

**Comment by roigcarlo** [comment]
Yep sorry, that was my fault. Its safe to merge.

**Comment by ipouplana** [comment]
Ok, no problem

**Pull request merged**
