### PR TITLE
[ContactStructuralMechanicsApplication] Adding frictional contact condition with penalty

### PR DESCRIPTION
**Pull request by loumalouomega**
This PR adds the frictional contact condition with penalty. The good news are that thanks to this I think I found why the ALM frictional was not working properly, I will do  a PR i the future fixing it (hopefully) 

The PR also adds several tests to ensure that the code is not broken

### CODE REVIEW

**Comment by loumalouomega** [comment]
This PR is big, but is basically for the tests files

**Comment by loumalouomega** [comment]
Ping @AlejandroCornejo

**Review by philbucher — APPROVED** [review]
looks good to me
only affects the contact app

**Comment by loumalouomega** [comment]
Thanks

**Pull request merged**
