### PR TITLE
[ShapeOpt] reorganize python scripts

### PR DESCRIPTION
**Pull request by adityaghantasala**
**Description**
Reorganizes the python scripts in to sub folders under python_scripts folder

It will be easy to review if you see the folder structure in this branch than going through the individual files as there is not much change in the content of the files.

### CODE REVIEW

**Review by armingeiser — COMMENTED** [review]
I like the organization of the files in subfolders. However my personal preference inside the application is relative imports over the verbose `KratosMultiphysics.ShapeOptimizationApplication...`

**Comment by adityaghantasala** [comment]
> I like the organization of the files in subfolders. However my personal preference inside the application is relative imports over the verbose `KratosMultiphysics.ShapeOptimizationApplication...`

@armingeiser  I agree that the this way is more verbose, other than relative imports ... is there any other reason why you prefer relative imports ? I checked other applications, and the "verbose" way is done there ... so I changed it to this way.

**Comment by armingeiser** [comment]
No this is really just my personal preference, most important is that is consistent in the application.

**Review by armingeiser — DISMISSED** [review]

**Review by dbaumgaertner — COMMENTED** [review]
It's great to see all those subtle improvements in the code organization here. Great job @adityaghantasala . 

About the imports. I remember @armingeiser and me having a lot of discussions about this. And every time I think about it, my opinion changes. But this, I guess, is a sign, that we should use whatever is the standard in the code. So I am fine with the verbose way of doing it here. 

Maybe still a suggestion: What about putting all those `custom_*.py` scripts in a "utilities" folder? Then, only the factories would be top-level under the folder "python_scripts". That would even look cleaner. 

Other than that I am fine with the changes.

**Comment by adityaghantasala** [comment]
@dbaumgaertner new utilities folder is now created ... as you mentioned, only factories are on top level. 

@armingeiser @dbaumgaertner can you see again and approve again ?

**Review by armingeiser — APPROVED** [review]

**Comment by adityaghantasala** [comment]
@armingeiser Thank you!

**Pull request merged**
