### PR TITLE
[Core] Using alias for ublas

### PR DESCRIPTION
**Pull request by pooyan-dadvand**
This PR is the first step to be taken in order to migrate from ublas dense matrix and vectors to AMatrix consists in use of Kratos alias for different matrix and vector classes of ublas doing the following replaces which are recommended to be done in following order:

1. Replacing the `boost::numeric::ublas::vector` with `DenseVector`
2. Replacing the `boost::numeric::ublas::matrix` with `DenseMatrix`
3. Replacing the `boost::numeric::ublas::bounded_vector` with `BoundedVector`
4. Replacing the `boost::numeric::ublas::bounded_matrix` with `BoundedMatrix`
5. Replacing the `bounded_vector` with `BoundedVector`
6. Replacing the `bounded_matrix` with `BoundedMatrix`
7. Relplacing the `matrix<` with `DenseMatrix<` **NOTE:** the `<` character should be included in this step to avoid unnecessary changes
8. Replacing the `boost::numeric::ublas::prod` with `prod`
9. Replacing the `boost::numeric::ublas::trans` with `trans`

The above changes has been made in the core. Nevertheless I have avoided to do a replace all in all applications in order to avoid merge conflicts with existing branches. So I would strongly recommend the @KratosMultiphysics/team-maintainers to perform the same steps in their applications after merging this PR which has the aliases in next days. At the end of this week we will proceed with replace all.

### CODE REVIEW

**Review by RiccardoRossi — APPROVED** [review]

**Comment by loumalouomega** [comment]
Do we change the same in our applications?

**Comment by pooyan-dadvand** [comment]
After merging this PR. Now it won't compile

**Comment by philbucher** [comment]
Will the UblasSpsce be replaced by the Amatrix Space?

**Comment by ipouplana** [comment]
Will there be a replacement for the expressions: inner_prod, outer_prod and norm_2?

**Comment by pooyan-dadvand** [comment]
Yes @philbucher the ublas space will be changed but not in this step. I think it would be after the release 6.

**Comment by pooyan-dadvand** [comment]
@ipouplana yes, most of them are defined and I will provide the rest I know. But I'm still in compiling phase of the Kratos and I'm not sure if I know all the used expressions to have the complete picture of the situation.

**Comment by pooyan-dadvand** [comment]
@KratosMultiphysics/team-maintainers now that this PR is merged, I would suggest you to change your applications following the steps mentioned above in the PR message as soon as possible. Please consider that in few days I will perform the replace all and leave the unmerged branches with conflict.

**Pull request merged**
