### PR TITLE
defining -DBOOST_UBLAS_MOVE_SEMANTICS

### PR DESCRIPTION
**Pull request by RiccardoRossi**
this option should activate move semantics for ublas types

**📝 Description**
tentatively activating ublas semantics for ublas types

Please mark the PR with appropriate tags: 
- improvement
-
**🆕 Changelog**
this option should activate move semantics for ublas types

### CODE REVIEW

**Review by roigcarlo — APPROVED** [review]
No problems on my side! :+1:

**Comment by RiccardoRossi** [comment]
@KratosMultiphysics/technical-committee do you have any concern about  merging this?

**Comment by philbucher** [comment]
Does it improve performance?
Are there any risks?

**Comment by RiccardoRossi** [comment]
according to the docs it should (according to the docs, it removes the need for noalias in some cases)... however i don't have a benchmark showing it.

still, the capability would be very useful

**Comment by RiccardoRossi** [comment]
just to add that the patch is there since about 2011 ... i just did not notice the option before

**Comment by rubenzorrilla** [comment]
Just mentioning that this change might give some problems with `matrix` class implementation in old versions of Boost library (I was using 1.61 :older_adult:). Checking the implementation reveals that my ancient Boost library one was slightly different. Updating the library to the latest release (1.78) solves the issue.

**Comment by AlejandroCornejo** [comment]
> Just mentioning that this change might give some problems with `matrix` class implementation in old versions of Boost library (I was using 1.61 🧓). Checking the implementation reveals that my ancient Boost library one was slightly different. Updating the library to the latest release (1.78) solves the issue.
> 
> EDIT: @KratosMultiphysics/all tagging everyone just in case this is also happening to you.

I am using 1.69 without any problem (as far as I know). Just for my curiosity, what problems did you have @rubenzorrilla ?

**Comment by rubenzorrilla** [comment]
Basically it was not compiling  because of the assignment definition of `matrix` class (see `matrix.hpp`) when compiling with move semantics, which in my old version was
```c++
#ifdef BOOST_UBLAS_MOVE_SEMANTICS

        /*! @note "pass by value" the key idea to enable move semantics */
        BOOST_UBLAS_INLINE
        fixed_matrix &operator = (matrix m) {
            assign_temporary(m);
            return *this;
        }
#else
```
which in newer versions should be
```c++
#ifdef BOOST_UBLAS_MOVE_SEMANTICS

        /*! @note "pass by value" the key idea to enable move semantics */
        BOOST_UBLAS_INLINE
        fixed_matrix &operator = (fixed_matrix m) {
            assign_temporary(m);
            return *this;
        }
#else
```

**Pull request merged**
