### PR TITLE
[Core] fix amatrix-compilation

### PR DESCRIPTION
**Pull request by philbucher**
there is another error related to the math-utils and the simple-mortar-mapper, but I was not able to figure it out, can you please have a look?
Thx

### CODE REVIEW

**Comment by philbucher** [comment]
Ping

**Comment by philbucher** [comment]
Ping

**Review by loumalouomega — APPROVED** [review]
🙃

**Comment by philbucher** [comment]
Thx, but there is another error...
Can you please try to compile the core with AMatrix?

**Comment by ddiezrod** [comment]
Hi guys! @philbucher @loumalouomega Did you manage to solve the error related to the math-utils and the simple-mortar-mapper? I took a look but could not find any reason why it is failing.

**Comment by philbucher** [comment]
nope I don't know why it fails

**Comment by loumalouomega** [comment]
Which test was failing?

**Comment by philbucher** [comment]
> Which test was failing?

not a test, the core does not compile with AMatrix bcs of sth related to your code
As I wrote in the first post of this PR

**Comment by ddiezrod** [comment]
@philbucher I found the problem with @pooyan-dadvand , you are trying to resize a BoundedMatrix which is not allowed in amatrix,  @loumalouomega easiest fix would be to use a Matrix in your mortar process.

**Comment by philbucher** [comment]
@pooyan-dadvand would it make sense to have a resize method in AMatrix that throws if the requested resize does not match the dimension?
This way I think we could avoid many problems and template Matrix/BoundedMatrix

**Comment by loumalouomega** [comment]
> @pooyan-dadvand would it make sense to have a resize method in AMatrix that throws if the requested resize does not match the dimension?
> This way I think we could avoid many problems and template Matrix/BoundedMatrix

I was thinking the same

**Comment by pooyan-dadvand** [comment]
It would be a solution. Nevertheless I don't like it because it gives a wrong message to developers seeing a resize in interface

**Comment by loumalouomega** [comment]
Ok, but creating two methods doing exactly the same just because of this breaks the point of using templates and confuses developers even more (even more than giving a dummy resize with error message)

**Comment by loumalouomega** [comment]
In my opinion

**Pull request merged**
