### PR TITLE
Adding warning to detect invalid overrides

### PR DESCRIPTION
**Pull request by roigcarlo**
Following #1663

### CODE REVIEW

**Review by loumalouomega — APPROVED** [review]
Thanks

**Comment by roigcarlo** [comment]
Not sure if is the problem of the warning but the build took much more time than the usual to complete. Let me investigate

**Comment by roigcarlo** [comment]
Also dosn't seem to provide any insight about overrides :S

**Comment by philbucher** [comment]
also it didn't show any warnings...

**Comment by roigcarlo** [comment]
Ok I will close it and When I find a solution that works I will reopen again

**Comment by philbucher** [comment]
I just rediscovered this, I am doing the same in #1841 , there travis took ~33min which seems normal to me
@roigcarlo I think it is ok but maybe you keep it in mind in your todays meeting of @KratosMultiphysics/technical-committee

**Comment by maceligueta** [comment]
Thanks Philip!

**Comment by pooyan-dadvand** [comment]
We will add the override warning to the gcc flags and see how we can handle libraries warnings

**Comment by RiccardoRossi** [comment]
@philbucher 

we @KratosMultiphysics/technical-committee suggest to add this compiler-by-compiler in the root CMakeLists.txt

**Comment by philbucher** [comment]
@RiccardoRossi @pooyan-dadvand isn't what you suggest exactly what I did in #1841?

**Pull request closed without merging**
