### PR TITLE
Rename `KRATOS_EXPECT_MATRIX_EQUAL` to `KRATOS_EXPECT_MATRIX_EQ`

### PR DESCRIPTION
**Pull request by avdg81**
**📝 Description**
This PR extracts the changes related to the macro renaming from PR #11506. The aim is to assist in breaking down PR #11506 into smaller pieces that can be reviewed more easily and which can be merged back separately. This commit renames the macro and it updates all of its usages.

### CODE REVIEW

**Comment by avdg81** [comment]
@roigcarlo: May I kindly ask you to review this small PR?

@loumalouomega: Are these simple changes in line with one of your suggestions for PR #11506?

**Comment by loumalouomega** [comment]
I am okay with changes

**Review by roigcarlo — APPROVED** [review]
:+1:

**Comment by philbucher** [comment]
does GTest have a matrix comparison?
Does it behave the same as ours?

**Comment by philbucher** [comment]
> does GTest have a matrix comparison? Does it behave the same as ours?

ping @avdg81

**Comment by avdg81** [comment]
> > does GTest have a matrix comparison? Does it behave the same as ours?
> 
> ping @avdg81

@philbucher: As far as I know, GTest doesn't have an `EXPECT` and/or `ASSERT` macro that is targeted at matrices. However, I would expect that we can write a validation function (or macro) for this purpose that is composed of the elementary assertions that GTest offers. Alternatively, I can imagine that we write a [matcher](https://google.github.io/googletest/reference/matchers.html) for this purpose that we then use in conjunction with the [`EXPECT_THAT`](https://google.github.io/googletest/reference/assertions.html#EXPECT_THAT) macro. Does this answer your question?

**Comment by roigcarlo** [comment]
Adding to @avdg81 answer, it does not have a direct matrix comparison, but it can compare any container that is iterable. The problem is that our matrices are not iterable (or at least it does not like the type of the iterator).

For the vectors its already done with iterators:

```c++
EXPECT_THAT(a, Pointwise(DoubleNear(tolerance), b));
```

**Pull request merged**
