### PR TITLE
[StructuralMechanics] removing old GP-fcts

### PR DESCRIPTION
**Pull request by philbucher**
This should be easy to review, I only remove wrapper functions

The functionalities were ported in earlier PRs

Not that this is not a PR against Master but into the renaming branch #2194

### CODE REVIEW

**Comment by philbucher** [comment]
@loumalouomega now you only have to change the solids and the solidshell

**Comment by philbucher** [comment]
@jcotela now StrucutralMechanics should be entirely ported

@loumalouomega could you please check the commits I did today?
Otherwise there is nothing left to do for you regrading this renaming Stuff in StructuralMechanics
(you might still want to check Contact and Meshing, I thing there are some renaming to be done)

**Review by loumalouomega — APPROVED** [review]
I was going to do the changes for the solid, but you did already, thanks

**Comment by loumalouomega** [comment]
For the contact mechanics I am scare of certain conflict with the current PR #2779

**Comment by philbucher** [comment]
@jcotela this compiles nicely with the CXX flag defined
I compiled the following apps:
~~~
                STRUCTURAL_MECHANICS_APPLICATION - ON
                FLUID_DYNAMICS_APPLICATION - ON
                MESH_MOVING_APPLICATION - ON
                EMPIRE_APPLICATION - ON
                EXTERNAL_SOLVERS_APPLICATION - ON
                MAPPING_APPLICATION - ON
                EIGEN_SOLVERS_APPLICATION - ON
                HDF5_APPLICATION - ON
~~~
Tests of StructuralMechanics also work

Feel free to merge this PR when you want

**Comment by jcotela** [comment]
@loumalouomega I'd say we postpone changing the contact part until after your PR is merged.

**Pull request merged**
