### PR TITLE
[CI][Win] re-adding contact

### PR DESCRIPTION
**Pull request by philbucher**
**Description**
This got lost in translation

### CODE REVIEW

**Review by loumalouomega — APPROVED** [review]

**Comment by philbucher** [comment]
@loumalouomega it seems like the Contact was never in the Win CI, only in the nightly build
=> tests are failing, this can only be merged once those pass
can you have a look please?

**Comment by loumalouomega** [comment]
Still not working. Only fails in to penalty tests

**Comment by philbucher** [comment]
@loumalouomega I am cleaning the list of my PRs
Since this needs your input, please reopen it by yourself when you have time, thx

**Comment by loumalouomega** [comment]
Okay

**Pull request closed without merging**
