### PR TITLE
Core/mixed generic criteria issue #7536

### LINKED ISSUE #7536: Improving output of MixedGenericCriteria
**Description**
The output can be made nicer of the `MixedGenericCriteria`
e.g.
~~~
 DISPLACEMENT : ratio = 1.64144e-07; exp.ratio = 5e-07 abs = 1.34002e-08 exp.abs = 5e-09
 ROTATION : ratio = 1.54434e-05; exp.ratio = 5e-07 abs = 5.03158e-08 exp.abs = 5e-09
~~~

would be easier to read as:
~~~
 DISPLACEMENT : ratio = 1.64144e-07; exp.ratio = 5e-07 abs = 1.34002e-08 exp.abs = 5e-09
 ROTATION :     ratio = 1.54434e-05; exp.ratio = 5e-07 abs = 5.03158e-08 exp.abs = 5e-09
~~~

not urgent, but would be nice to have

### PR DESCRIPTION
**Pull request by ashishdarekar**
**Description**
This PR is to solve the issue #7536

**Changelog**
- Implemented the Loop to calculate the exact number of spaces required before printing the required output. 
- Test Output:
image

closes #7536

### CODE REVIEW

**Comment by philbucher** [comment]
now the output looks like this (added some more vars to the output for demonstration):
~~~
CONVERGENCE CHECK:
 DISPLACEMENT      : ratio = 2.78659e-11; exp.ratio = 1e-07 abs = 1.88858e-14 exp.abs = 1e-09
 ROTATION          : ratio = 0; exp.ratio = 1e-07 abs = -nan exp.abs = 1e-09
 VOLUMETRIC_STRAIN : ratio = 6.54106e-11; exp.ratio = 1e-07 abs = 7.44584e-19 exp.abs = 1e-09
~~~

@rubenzorrilla since I also did some modifications, can you please have a look and approve if you like what you see? :)

**Comment by rubenzorrilla** [comment]
> now the output looks like this (added some more vars to the output for demonstration):
> 
> ```
> CONVERGENCE CHECK:
>  DISPLACEMENT      : ratio = 2.78659e-11; exp.ratio = 1e-07 abs = 1.88858e-14 exp.abs = 1e-09
>  ROTATION          : ratio = 0; exp.ratio = 1e-07 abs = -nan exp.abs = 1e-09
>  VOLUMETRIC_STRAIN : ratio = 6.54106e-11; exp.ratio = 1e-07 abs = 7.44584e-19 exp.abs = 1e-09
> ```
> 
> @rubenzorrilla since I also did some modifications, can you please have a look and approve if you like what you see? :)
> 
> EDIT I see now that the output of ROTATION is a bit screwed as the problem doesn't have real rotation dofs

Gorgeous :cupid: 

About the `ROTATION`, I wouldn't change nothing in the output as it makes no sense to check the convergence with an non-existent DOF. What we might do is to check that the variables asked for the convergence check are DOFs.

**Comment by philbucher** [comment]
I see that adding `ROTATION` caused more confusion than I anticipated :D

I added it only so that one can see how it looks with three variables, it has no physical meaning :D

**Review by philbucher — APPROVED** [review]
merging as the original issue with the alignment of the variables is solved

**Comment by rubenzorrilla** [comment]
> I see that adding `ROTATION` caused more confusion than I anticipated :D
> 
> I added it only so that one can see how it looks with three variables, it has no physical meaning :D

I mean that we could eventually add a check to be sure that the variables intended to be used in the convergence check are actually a DOF. In any case we can discuss it in a future PR.

Thanks @ashishdarekar @philbucher !!!!

**Comment by philbucher** [comment]
> I mean that we could eventually add a check to be sure that the variables intended to be used in the convergence check are actually a DOF. In any case we can discuss it in a future PR.

good idea
can you please open an issue describing your idea?

**Pull request merged**
