### PR TITLE
Restore changes in time integration methods for Solids

### PR DESCRIPTION
**Pull request by josep-m-carbonell**
The template specialization was ignored with the introduced changes. Tests failed. If it does not compile in windows, a different solution is needed.

### CODE REVIEW

**Comment by roigcarlo** [comment]
Sorry seems I did not ran the test correctly. I'll take a look now

**Review by roigcarlo — DISMISSED** [review]
I can't reproduce the error so i trust you on this. 

In the meantime, can you point to me which tests are failing. I recompiled from srcatch and tests seems to work for me:

image

Is there any other tests I am not running?

**Comment by josep-m-carbonell** [comment]
The ones related to Beams were failing in my computer, in ubuntu. They were accessing to the incorrect method definition.

**Comment by roigcarlo** [comment]
Thx, I will check in ubuntu

**Comment by roigcarlo** [comment]
@josep-m-carbonell I identified the bug and solved it ( I should have moved the generic implementation to the cpp).

Should I upload the changes here or you preffer to merge this and make a separate PR?¿

**Comment by josep-m-carbonell** [comment]
Ok, good news. You can call commit them here, aprove and merge. Thank you!

**Comment by josep-m-carbonell** [comment]
If it compiles, could you approve the PR? thank you

**Review by roigcarlo — APPROVED** [review]

**Pull request merged**
