### PR TITLE
[ContactStructuralMechanicsApplication] Separating KratosContactStructuralMechanicsCore and KratosContactStructuralMechanicsApplication

### LINKED ISSUE #4370: Deriving a class and issue with execution, i.e., ImportError: dynamic module does not define module export function
I have been trying to execute a very simple example case through derived class obtained from an existing class (application) in the Kratos directory. The example case works perfectly fine when running with the base application. However, with the derived application, it tends to throw an error. Similar error occurs if I try to open a python shell and import the application, namely:

`ImportError: dynamic module does not define module export function (PyInit_Name_of_Derived_Application)`

While I looked up for the error on the internet and Kratos Issues page, most common solution was with regards to `$PYTHONPATH` or `$LD_LIBRARY_PATH`. I have checked all the path configuration steps that is required for KratosMultiphysics to work seamlessly. 

Could someone suggest places or possible error? Kindly also guide me the necessary checkpoints that one must look at when deriving an application from an existing one within the Kratos directory.

### PR DESCRIPTION
**Pull request by loumalouomega**
Fixes #4370

### CODE REVIEW

**Review by roigcarlo — DISMISSED** [review]
Seems fine if compiles :+1:

**Comment by loumalouomega** [comment]
> Seems fine if compiles +1

And runs the tests

**Comment by loumalouomega** [comment]
@roigcarlo Looks like it fails on Windows

**Comment by roigcarlo** [comment]
It does, you have to export all the simbols of the core that would be used in other apps, or in this case, in the application part.

**Comment by loumalouomega** [comment]
Solved, I will need reapproval

**Comment by loumalouomega** [comment]
Ping @roigcarlo solved

**Review by roigcarlo — APPROVED** [review]

**Pull request merged**
