### PR TITLE
[Fluid][FSI] Import Metis before Trilinos application

### PR DESCRIPTION
**Pull request by rubenzorrilla**
Trying to run an MPI case in our in-house cluster raised a weird Metis symbols error.

As we experienced some time ago, importing the `MetisApplication` before the `TrilinosApplication` solved this.

### CODE REVIEW

**Review by philbucher — CHANGES_REQUESTED** [review]
can we speak about this?
IMO this should be done in the MainScript and not globally
Imagine you cannot compile Metis on the cluster for some reason
=> in that case you can partition locally and put the partitioned files on the cluster

If this PR goes through you are screwed in that case :)

**Review by roigcarlo — APPROVED** [review]

**Comment by roigcarlo** [comment]
@philbucher But if this is the case, this is not the only part of Kratos that will break I think. Most of the scripts using Trilinos right now assume that metis has been compiled.

I agree is not 100% correct but I don't think we have faced the situation you describe

**Comment by philbucher** [comment]
> @philbucher But if this is the case, this is not the only part of Kratos that will break I think. Most of the scripts using Trilinos right now assume that metis has been compiled.

Nope, it is only used in a single place right now, and only if you need it
I spent a very long time cleaning and refactoring this to reduce the depenedenices

**Comment by philbucher** [comment]
for the reference: https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/mpi/python_scripts/distributed_import_model_part_utility.py#L55
this is the only time metis is imported (in a standard Structural or Fluid MPI case) and only if you need it

Imagine we have our own partitioners some day, then this would also not be necessary

**Comment by rubenzorrilla** [comment]
> can we speak about this?
> IMO this should be done in the MainScript and not globally
> Imagine you cannot compile Metis on the cluster for some reason
> => in that case you can partition locally and put the partitioned files on the cluster
> 
> If this PR goes through you are screwed in that case :)

I understand your point. But as it is right now we are screwed as well. We can add a check to confirm that Metis has been compiled.

**Comment by rubenzorrilla** [comment]
> > @philbucher But if this is the case, this is not the only part of Kratos that will break I think. Most of the scripts using Trilinos right now assume that metis has been compiled.
> 
> Nope, it is only used in a single place right now, and only if you need it
> I spent a very long time cleaning and refactoring this to reduce the depenedenices

Our Metis application is only used for the partitioning (I acknowledge the clean up you did). I guess that what @roigcarlo says is that right now we need Metis library to be compiled (correct me if I'm wrong).

If we at some point have our own partitioner, I guess we will also have our own parallel vector and matrices, meaning that this problem will hopefully  disappear. Taking into account that we are way far from reaching this point, I wouldn't consider this as a blockage for the hotfix.

**Comment by philbucher** [comment]
> I understand your point. But as it is right now we are screwed as well. We can add a check to confirm that Metis has been compiled.

you can import it in the Main-script then it will work: https://github.com/KratosMultiphysics/GiDInterface/compare/philipp-temp (used GiD-repo bcs I don't know where this is in Kratos)

**Comment by philbucher** [comment]
> we need Metis library to be compiled (correct me if I'm wrong).

Only locally, but not on the cluster!

**Comment by rubenzorrilla** [comment]
> > we need Metis library to be compiled (correct me if I'm wrong).
> 
> Only locally, but not on the cluster!

Well, as far as I understand, you need the Metis libraries to compile the Trilinos one.

**Comment by rubenzorrilla** [comment]
> > I understand your point. But as it is right now we are screwed as well. We can add a check to confirm that Metis has been compiled.
> 
> you can import it in the Main-script then it will work: https://github.com/KratosMultiphysics/GiDInterface/compare/philipp-temp (used GiD-repo bcs I don't know where this is in Kratos)

The point is that the main script is the same for serial and MPI, while the solver is not. Of course it can be done, but I think it's more confuse for the user...

**Comment by philbucher** [comment]
> > > we need Metis library to be compiled (correct me if I'm wrong).
> > 
> > 
> > Only locally, but not on the cluster!
> 
> Well, as far as I understand, you need the Metis libraries to compile the Trilinos one.

afaik only for some solvers, but if some are problematic then those can be disabled: https://github.com/KratosMultiphysics/Kratos/tree/master/applications/TrilinosApplication#notes-for-compilation
I think only the `ML` solver needs it but not entirely sure

**Comment by philbucher** [comment]
> > > I understand your point. But as it is right now we are screwed as well. We can add a check to confirm that Metis has been compiled.
> > 
> > 
> > you can import it in the Main-script then it will work: https://github.com/KratosMultiphysics/GiDInterface/compare/philipp-temp (used GiD-repo bcs I don't know where this is in Kratos)
> 
> The point is that the main script is the same for serial and MPI, while the solver is not. Of course it can be done, but I think it's more confuse for the user...

in most cases it is, only is some very special situations it can be adapted (thats what it is designed for)  to accomodate special needs. Which IMO is the case when running on a cluster that has a specific problem

I think we can discuss it later in the meeting

**Comment by philbucher** [comment]
if trilinos really 100% depends on Metis then Metis should be imported in the `__init__.py` of the TrilinosApp, just like we do for the MPICore, this way it is portable also for other solvers such as the structural ones

**Comment by roigcarlo** [comment]
@KratosMultiphysics/technical-committee Agrees on try to import Trilinos Core at the `__init__.py` of the TrilinosApplication application with a Try/catch mechanism and print, in case of error, a message with a easy to read message and a link to the TrilinosApplication `README.md` where possible solutions for the error are explained.

**Pull request closed without merging**
