### PR TITLE
[SDEM] adding interpolation test

### PR DESCRIPTION
**Pull request by GuillermoCasas**
Adding new interpolation tests and a lot of cleanup, especially of the python-json interface. The jsons have been simplified. Also some systematic name changes have been applied. All tests are running.

### CODE REVIEW

**Comment by ipouplana** [comment]
Is pfem-dem test also running ?

**Comment by GuillermoCasas** [comment]
> Is pfem-dem test also running ?

Yes. Also after the latest corrections.

**Review by ipouplana — APPROVED** [review]
Good!

**Comment by GuillermoCasas** [comment]
There is no actual change in the core; the change proposed was already included in a previous merge

**Pull request merged**
