### PR TITLE
[CI] 2/2 Use ParMmg 1.4.0 and Mmg 5.6.0 in CI

### PR DESCRIPTION
**Pull request by marcnunezc**
**📝 Description**
continuation of #10474 

- [x]  Add new mmg and parmmg to Dockerfiles
- [ ]  Change versions used in ci.yml and nightly.yml
- [ ] Remove old versions from Dockerfile.

**🆕 Changelog**

- Use new versions in ci files. 
- Remove old versions from docker

### CODE REVIEW

**Comment by philbucher** [comment]
I think you could already remove the old version from the docker in this PR, since it will be pushed only after merging

**Comment by marcnunezc** [comment]
> I think you could already remove the old version from the docker in this PR, since it will be pushed only after merging

True, just did it. Older branches will need to merge master when opening a PR though, as their CI files will be outdated. (the other option is to wait some days to remove the older versions, but I agree to do it now)

**Review by loumalouomega — APPROVED** [review]

**Comment by loumalouomega** [comment]
@marcnunezc it would be a good opportunity to update MMG 5.7

**Comment by marcnunezc** [comment]
Yes I think I will close this and directly upgrade to 5.7.0.

**Pull request closed without merging**
