### PR TITLE
[Core] Removing warnings due to unitialized arrays

### LINKED ISSUE #6372: Master Compilation uninitialized error
Hi, I am compiling with the following flag:
`-Werror=maybe-uninitialized"`

and get compilation errors when trying to compile the current master.

> s.cpp.o
> In file included from /home/klaus/software/Kratos_Dev/kratos/tests/cpp_tests/spatial_containers/test_geometrical_objects_bins.cpp:21:0:
> /home/klaus/software/Kratos_Dev/kratos/spatial_containers/geometrical_objects_bins.h: In member function ‘void Kratos::GeometricalObjectsBins::AddObjectsToCells(TIteratorType, TIteratorType) [with TIteratorType = boost::iterators::indirect_iterator<__gnu_cxx::__normal_iterator<Kratos::intrusive_ptr<Kratos::Element>*, std::vector<Kratos::intrusive_ptr<Kratos::Element>, std::allocator<Kratos::intrusive_ptr<Kratos::Element> > > >, boost::iterators::use_default, boost::iterators::use_default, boost::iterators::use_default, boost::iterators::use_default>]’:
> /home/klaus/software/Kratos_Dev/kratos/spatial_containers/geometrical_objects_bins.h:330:53: error: ‘max_position[2]’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
>              for(std::size_t k = min_position[2] ; k < max_position[2] ; k++){
> /home/klaus/software/Kratos_Dev/kratos/spatial_containers/geometrical_objects_bins.h:331:57: error: ‘max_position[1]’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
>                  for(std::size_t j = min_position[1] ; j < max_position[1] ; j++){
> /home/klaus/software/Kratos_Dev/kratos/spatial_containers/geometrical_objects_bins.h:332:61: error: ‘max_position[0]’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
>                      for(std::size_t i = min_position[0] ; i < max_position[0] ; i++){
> /home/klaus/software/Kratos_Dev/kratos/spatial_containers/geometrical_objects_bins.h:134:65: error: ‘min_position[2]’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
>          const std::size_t index = I + J * mNumberOfCells[0] + K * mNumberOfCells[1] * mNumberOfCells[0];
> /home/klaus/software/Kratos_Dev/kratos/spatial_containers/geometrical_objects_bins.h:327:40: note: ‘min_position[2]’ was declared here
>              array_1d< std::size_t, 3 > min_position;
>                                         ^~~~~~~~~~~~
> /home/klaus/software/Kratos_Dev/kratos/spatial_containers/geometrical_objects_bins.h:327:40: error: ‘min_position[1]’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
> /home/klaus/software/Kratos_Dev/kratos/spatial_containers/geometrical_objects_bins.h:150:70: error: ‘min_position[0]’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
>          result.GetMaxPoint()[0] = mBoundingBox.GetMinPoint()[0] + (I + 1) * mCellSizes[0];

@philbucher asked me to create an issue about that. Could you link the responisble persons?

Klaus

### PR DESCRIPTION
**Pull request by loumalouomega**
Basically that (also replacing "\t" for "    ")

closes #6372

### CODE REVIEW

**Comment by loumalouomega** [comment]
~~~
E:/SRC/Kratos/kratos/spatial_containers/geometrical_objects_bins.h:330:53: warning: '*((void*)& max_position +16)' may be used uninitialized in this function [-Wmaybe-uninitialized]
  330 |             for(std::size_t k = min_position[2] ; k < max_position[2] ; k++){
E:/SRC/Kratos/kratos/spatial_containers/geometrical_objects_bins.h:331:57: warning: '*((void*)& max_position +8)' may be used uninitialized in this function [-Wmaybe-uninitialized]
  331 |                 for(std::size_t j = min_position[1] ; j < max_position[1] ; j++){
E:/SRC/Kratos/kratos/spatial_containers/geometrical_objects_bins.h:332:61: warning: 'max_position' may be used uninitialized in this function [-Wmaybe-uninitialized]
  332 |                     for(std::size_t i = min_position[0] ; i < max_position[0] ; i++){
E:/SRC/Kratos/kratos/spatial_containers/geometrical_objects_bins.h:330:53: warning: '*((void*)& min_position +16)' may be used uninitialized in this function [-Wmaybe-uninitialized]
  330 |             for(std::size_t k = min_position[2] ; k < max_position[2] ; k++){
E:/SRC/Kratos/kratos/spatial_containers/geometrical_objects_bins.h:331:57: warning: '*((void*)& min_position +8)' may be used uninitialized in this function [-Wmaybe-uninitialized]
  331 |                 for(std::size_t j = min_position[1] ; j < max_position[1] ; j++){
E:/SRC/Kratos/kratos/spatial_containers/geometrical_objects_bins.h:332:61: warning: 'min_position' may be used uninitialized in this function [-Wmaybe-uninitialized]
  332 |                     for(std::size_t i = min_position[0] ; i < max_position[0] ; i++){
~~~

**Review by philbucher — APPROVED** [review]
works, thx

**Comment by loumalouomega** [comment]
> 
> 
> works, thx

I didn't know there was an issue, I just saw the message and I got ansious, and my OCD did the rest

**Comment by pooyan-dadvand** [comment]
Thanks!

**Pull request merged**
