### PR TITLE
[External]Adding check for architecture in triangle.c

### PR DESCRIPTION
**Pull request by loumalouomega**
Error at compiling in not x86 architecture

### CODE REVIEW

**Comment by josep-m-carbonell** [comment]
Triangle is failing (segmentation fault) in Windows 10 when it is called, is this solving the failure ?

**Comment by loumalouomega** [comment]
No, this is solving an issue related with non x86 architectures. Maybe is
related, but a different check should be added.

**Comment by loumalouomega** [comment]
Ping @roigcarlo

**Review by roigcarlo — APPROVED** [review]
:+1:

**Pull request merged**
