### PR TITLE
[core] Redefinition of macro warning fixed

### PR DESCRIPTION
**Pull request by maceligueta**
I tried to reorder the includes, as I usually do with this type of warnings, but I had no success, due to recursive dependency.
This was the warning:
```
In file included from /usr/include/python2.7/Python.h:8:0,
                 from /home/maceli/kratos/external_libraries/pybind11/detail/common.h:111,
                 from /home/maceli/kratos/external_libraries/pybind11/pytypes.h:12,
                 from /home/maceli/kratos/external_libraries/pybind11/cast.h:13,
                 from /home/maceli/kratos/external_libraries/pybind11/attr.h:13,
                 from /home/maceli/kratos/external_libraries/pybind11/pybind11.h:43,
                 from /home/maceli/kratos/kratos/utilities/python_function_callback_utility.h:20,
                 from /home/maceli/kratos/kratos/processes/assign_scalar_field_to_conditions_process.h:28,
                 from /home/maceli/kratos/kratos/processes/assign_scalar_field_to_conditions_process.cpp:20:
/usr/include/python2.7/pyconfig.h:1193:0: warning: "_POSIX_C_SOURCE" redefined
 #define _POSIX_C_SOURCE 200112L
 ^
In file included from /usr/include/c++/5/x86_64-suse-linux/bits/os_defines.h:39:0,
                 from /usr/include/c++/5/x86_64-suse-linux/bits/c++config.h:2255,
                 from /usr/include/c++/5/string:38,
                 from /home/maceli/kratos/kratos/includes/model_part.h:22,
                 from /home/maceli/kratos/kratos/processes/assign_scalar_field_to_conditions_process.h:25,
                 from /home/maceli/kratos/kratos/processes/assign_scalar_field_to_conditions_process.cpp:20:
/usr/include/features.h:225:0: note: this is the location of the previous definition
 # define _POSIX_C_SOURCE 200809L
 ^
In file included from /usr/include/python2.7/Python.h:8:0,
                 from /home/maceli/kratos/external_libraries/pybind11/detail/common.h:111,
                 from /home/maceli/kratos/external_libraries/pybind11/pytypes.h:12,
                 from /home/maceli/kratos/external_libraries/pybind11/cast.h:13,
                 from /home/maceli/kratos/external_libraries/pybind11/attr.h:13,
                 from /home/maceli/kratos/external_libraries/pybind11/pybind11.h:43,
                 from /home/maceli/kratos/kratos/utilities/python_function_callback_utility.h:20,
                 from /home/maceli/kratos/kratos/processes/assign_scalar_field_to_conditions_process.h:28,
                 from /home/maceli/kratos/kratos/processes/assign_scalar_field_to_conditions_process.cpp:20:
/usr/include/python2.7/pyconfig.h:1215:0: warning: "_XOPEN_SOURCE" redefined
 #define _XOPEN_SOURCE 600
 ^
In file included from /usr/include/c++/5/x86_64-suse-linux/bits/os_defines.h:39:0,
                 from /usr/include/c++/5/x86_64-suse-linux/bits/c++config.h:2255,
                 from /usr/include/c++/5/string:38,
                 from /home/maceli/kratos/kratos/includes/model_part.h:22,
                 from /home/maceli/kratos/kratos/processes/assign_scalar_field_to_conditions_process.h:25,
                 from /home/maceli/kratos/kratos/processes/assign_scalar_field_to_conditions_process.cpp:20:
/usr/include/features.h:166:0: note: this is the location of the previous definition
 # define _XOPEN_SOURCE 700

```

### CODE REVIEW

**Comment by loumalouomega** [comment]
Everything that depends on pybind (well, from Python.h) is usually a pain in the ***. One solution is sometimes to move to a only header, but if it depends on Python.h will crash the compilation.

Which is the original warning?

**Comment by maceligueta** [comment]
@loumalouomega I pasted the full text of the warning in the description of the PR.

**Comment by maceligueta** [comment]
Note that I am still using Python 2.7

**Comment by loumalouomega** [comment]
@roigcarlo  I am lost

**Comment by maceligueta** [comment]
With the change I made, the warning disappears.

**Comment by roigcarlo** [comment]
Mmmm it hides the warning but is probably hidding a deeper problem. 
In this case the warning is correct. For some reason the same var is being defined twice. With this fix I am afriad you are priorizing the definition of the python library over the system one, which is dangerous at least. 

Not blocking it, but I would think twice before merging this.

**Review by RiccardoRossi — DISMISSED** [review]
@maceligueta this file is in processes, and it is "not allowed" to have a dependency on pybind outside of the "python" subdirectory...

**Comment by maceligueta** [comment]
Understood. I will try other things. Any idea on how to get rid of the warning is welcome.

**Comment by maceligueta** [comment]
@RiccardoRossi : I just realized that the process is already including an indirect dependency on pybind through the python_function_callback_utility.h. That's precisely the problem (see my first message in this PR)

**Comment by philbucher** [comment]
@maceligueta I just checked the python-callback-utility
Could your problem be solved if you separate this file into heaser&source such that all the pybind stuff is in the source only?

**Comment by maceligueta** [comment]
Actually, my problem got solved with my last commits. Now that I am not including pybind, nor adding any extra include, I am just waiting for Riccardo's response. @RiccardoRossi

**Review by philbucher — APPROVED** [review]
I compiled it and ran the tests, seems fine to me
I don't get warnings with GCC 5.4, but I also don't get any without
if you don't get any warnings any more @maceligueta then I would say you can go ahead

**Comment by maceligueta** [comment]
I will merge but I will open an issue for Riccardo to know that this process still depends on pybind (indirectly).

**Pull request merged**
