### PR TITLE
[Core] App-Template: Split into core/py-interface

### LINKED ISSUE #4576: TemplateApplication: Sources not splitted into Core & Python
Hi @roigcarlo 
I think it was discussed at some point to do the splitting of app-sources from python for every app right?
Just as a reminder, I think this is not yet done for the [template-application](https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/templates/template_application/CMakeLists.txt.in) that is used in the app-generator
I would do it myself but I don't know how :/

mentioning @KratosMultiphysics/technical-committee

### PR DESCRIPTION
**Pull request by philbucher**
closes #4576

I used GLOB_RECURSE right away, I think it is a good idea to directly use it for new apps
plus the install for the testing-files was missing

also did some minor corrections

### CODE REVIEW

**Comment by philbucher** [comment]
now should work, I created a dummy app to test it with

**Comment by loumalouomega** [comment]
I have a cmake code to automatically generate the .py of the app in case the apps it is outside of the application tree, do you think it is interesting to include it here?

**Comment by philbucher** [comment]
> I have a cmake code to automatically generate the .py of the app in case the apps it is outside of the application tree, do you think it is interesting to include it here?

I thought apps outside the tree is not preferred?
In any case, I would go for a separate PR

**Comment by loumalouomega** [comment]
> > I have a cmake code to automatically generate the .py of the app in case the apps it is outside of the application tree, do you think it is interesting to include it here?
> 
> I thought apps outside the tree is not preferred?
> In any case, I would go for a separate PR

OK

**Comment by philbucher** [comment]
ping @roigcarlo

**Review by roigcarlo — APPROVED** [review]
👍 

Nice job, I laso like the global recurse here, it should help people which is new to kratos by atuo adding sources.

**Pull request merged**
