### PR TITLE
Fix issue 887

### LINKED ISSUE #887: Point.h  compilation error Windows
I get an error when compiling Kratos with Visual Studio. 

As point.h is not longer a template, typename cannot be used in Visual Studio

C:\Kratos\kratos\geometries/point.h(83): error C2899: typename cannot be used outside a template declaration

@pooyan-dadvand  I guess you can simply delete them right?

### PR DESCRIPTION
**Pull request by pooyan-dadvand**
This PR removes typemanes preventing the windows compilation and fixes #887 

@ddiezrod would you please check if is compiled now?

### CODE REVIEW

**Review by loumalouomega — APPROVED** [review]
OK

**Comment by ddiezrod** [comment]
@pooyan-dadvand  It didnt pass the Travis check as it took too long. So...?

**Comment by pooyan-dadvand** [comment]
@ddiezrod is it compiling for you?

**Comment by pooyan-dadvand** [comment]
@ddiezrod it seems that it takes too long. Meanwhile, does it compile in your machine?

**Comment by ddiezrod** [comment]
@pooyan-dadvand well, all the errors related to this issue dissapeared. However there is another error that I could not see before.

Error	C2872	'vector': ambiguous symbol	Kratos	C:\Kratos\kratos\spaces\ublas_space.h	862

I dont know who would be in charge of this...

**Comment by pooyan-dadvand** [comment]
it should be `boost::numeric::ublas::vector<unsigned int>` Nevertheless I have not get this error.

**Comment by pooyan-dadvand** [comment]
Now I have updated the branch again. @ddiezrod would you please check if compiles?

**Comment by ddiezrod** [comment]
@pooyan-dadvand it compiles smoothly now , thanks !

**Comment by pooyan-dadvand** [comment]
So would you please approve it to be merged after Travis passes?

**Comment by ddiezrod** [comment]
@pooyan-dadvand  Travis failed again, same problem as before :(

**Comment by roigcarlo** [comment]
@pooyan-dadvand @ddiezrod Travis passing, I restarted the build. You can merge now

**Pull request merged**
