### PR TITLE
add missing model includes

### PR DESCRIPTION
**Pull request by armingeiser**

### CODE REVIEW

**Review by jcotela — APPROVED** [review]
Thanks for the fix!

**Comment by roigcarlo** [comment]
There are some duplications with #3096

**Comment by loumalouomega** [comment]
I did it first, but @philbucher ask me for changes

**Comment by loumalouomega** [comment]
BTW this missing includes probably are for using Cotire by default

**Comment by philbucher** [comment]
I think if exactly the same is commited then it should not make a difference...

**Comment by armingeiser** [comment]
@loumalouomega sorry, haven't seen that you already created a PR. I guess i will close this one, and create a new PR just with the HDF5 fixes.
According @jcotela these errrors pop up when COTIRE is not used (thats the case for me).

BTW @loumalouomega it's interesting that i only had to add 2 includes in the MeshingApplication, but in your PR more where needed. Do you know why this could be the case?

**Comment by philbucher** [comment]
> BTW @loumalouomega it's interesting that i only had to add 2 includes in the MeshingApplication, but in your PR more where needed. Do you know why this could be the case?

I think if you have MMG then it compiles more files

**Comment by jcotela** [comment]
@loumalouomega sorry, I didn't realize there was another PR with the meshing application changes.

**Pull request closed without merging**
