### PR TITLE
Removing trailing whitespaces in core

### PR DESCRIPTION
**Pull request by philbucher**
Since this messes with a lot of PRs and makes them harder to review, I took the effort to remove all of them
No other things were modified (can be seen when whitespace-changes are hidden)
screenshot from 2018-08-13 08-42-57

I used  `find . -type f -print0 | xargs -0 perl -pi -e 's/ +$//'` to do this in case someone is interested

### CODE REVIEW

**Comment by loumalouomega** [comment]
Not compiling

**Comment by loumalouomega** [comment]
Appveyor

**Comment by philbucher** [comment]
hm doesn't seem to be related
~~~
15.7.180.61344Fetching repository commit (7fe5f4f)...Error while copying content to a stream.
~~~

will restart it

**Comment by roigcarlo** [comment]
It happens some times, it is not our fault.

**Comment by philbucher** [comment]
now it worked

**Comment by philbucher** [comment]
Can I get an appoval pls? :)
I fear this will cause conflicts if left for too long

**Comment by RiccardoRossi** [comment]
Philipp...this will be in conflict with all the open prs....
I mean the other prs will have to resolve the conflict if you merge this.
I don't think this should be merged..

**Comment by RiccardoRossi** [comment]
For example with the model I will have a conflict in all the files because of this...

I do not want to block since I am on holidays...but please consider it...

**Comment by philbucher** [comment]
I see
Lets discuss it after the holidays then, sorry for disturbing

**Comment by RiccardoRossi** [comment]
@philbucher i now have a proper keyboard and can comment a little more extensively.

the problem with doing any formatting change is exactly the generation of conflicts with all of the openPRs.
this is actually one of the reasons for which we did not put automatic formatting at merging time (apart for difficulties in having proper formatting) 

we discussed this (the automatic formatting) extensively in @KratosMultiphysics/technical-committee and we did not come up with a good solution.

MAYBE what we could do is to allow your pass to go in and to have a script that everyone activates on his own branch so to get rid of conflicts, however i am honestly not sure of how well this would work.

...suggestions are very welcome...

**Comment by philbucher** [comment]
@KratosMultiphysics/technical-committee I see the struggle
I don't see this as high-priority, so feel free to close it if it is not desired.

**Comment by philbucher** [comment]
guess I'll close this then

**Pull request closed without merging**
