### PR TITLE
[DEM] inlet random deviation for 2D

### PR DESCRIPTION
**Pull request by farrufat-cimne**
and bugfix in angle units

### CODE REVIEW

**Comment by maceligueta** [comment]
@farrufat-cimne , after your last push this looks good to me, however we still need to add a minimal test for the inlet. Do you think this branch can be used for this?

**Comment by farrufat-cimne** [comment]
Sure, I will push a unittest for the inlet.

**Review by maceligueta — APPROVED** [review]

**Comment by philbucher** [comment]
Hey guys, I think this PR causes the following error if Kratos is compiled with `D_GLIBCXX_DEBUG`:
~~~
test_DEM2D_1 (test_DEM_2D.TestDEM2D) ... /usr/include/c++/5/debug/vector:409:error: attempt to subscript container 
    with out-of-bounds index 2, but container only holds 2 elements.

Objects involved in the operation:
sequence "this" @ 0x0x7ffddb40ac60 {
  type = NSt7__debug6vectorIdSaIdEEE;
}
~~~

can you please take a look?

**Comment by maceligueta** [comment]
Sure, I'll do it immediately.

**Pull request merged**
