### PR TITLE
[ReadMaterials] Throw warning if material is redefined in material.json

### LINKED ISSUE #5782: [ReadMaterials] Should submodelparts be able to have their own properties?
I have found that ReadMaterialsUtility throws an error if properties are assigned to both a child model part and its parent. I think that this could be allowed in some sittuations. 

For example, I think you might want to have a main model part with a property and then have an inlet model part that contains only conditions with a different property (with for example its own Heat Transfer Coefficient). Of course one solution could be to have the inlet and the rest of the main model part in the same level (so inlet is no longer a child of main), however that would be quite painful for us, as we would need to change all our input structure in @KratosMultiphysics/altair .

An intermediate solution could be maybe to throw a warning instead of an error. What do you think? @philbucher @KratosMultiphysics/altair @loumalouomega @KratosMultiphysics/design-committee

### PR DESCRIPTION
**Pull request by ddiezrod**
Closes https://github.com/KratosMultiphysics/Kratos/issues/5782

### CODE REVIEW

**Review by philbucher — CHANGES_REQUESTED** [review]
but this will not cover the case when you overwrite completely a submodelpart, which is invalid input
the other way round is ok, thats what we discussed in the other PR

**Comment by ddiezrod** [comment]
Ok, so you want to add a check (with an error) if the current modelpart has a submodelpart material which has already been applied. Is this correct?

**Comment by philbucher** [comment]
Yes exactly 

And please adapt the tests accordingly (well you wont be able to merge otherwise :) )

**Comment by ddiezrod** [comment]
Ok, so now, it checks if the parent model part properties are applied before or after the current submodelpart. 

first parent , then son -> Warning
first son, then parent -> Error

There was a sort of the materials, I moved it to a new function and pass the list as a copy.

**Review by philbucher — APPROVED** [review]
Thanks @ddiezrod !

I took the chance to remove some deprecation warnings and add another test

**Comment by loumalouomega** [comment]
I will merge this, as long as I predict a conflict in #2919 and I want to solve it in my free time

**Pull request merged**
