### PR TITLE
[Core] bug fix in integration utilities

### PR DESCRIPTION
**Pull request by sunethwarna**
A small bug fix in determining integration method.

### CODE REVIEW

**Review by jcotela — APPROVED** [review]
Approving.
@RiccardoRossi please check this one, the existing code was always using `GI_GAUSS_4`.

**Comment by philbucher** [comment]
@sunethwarna such changes should get the label "Behaviour Change" such that they can be tracked when creating releases

**Review by RiccardoRossi — APPROVED** [review]

**Comment by sunethwarna** [comment]
@philbucher @RiccardoRossi thanks :)

**Comment by loumalouomega** [comment]
This broke three of my contact tests...I spent the whole day looking for it

**Comment by loumalouomega** [comment]
I don't know why, the broken problems are static and this is only used to compute the mass matrix

**Comment by jcotela** [comment]
@loumalouomega sorry to hear about your tests. The impact of this change is that before you were always using GI_GAUSS_4 to integrate whatever calls this, while now you get your default order + 1. The only way I can see this impacting you is if your quantity is inexactly integrated by either/both of those quadrature orders.

**Comment by loumalouomega** [comment]
I see, but this is only used in the mass matrix computation (and this tests are static) and for the loads (but the loads are constant). So I am completely lost of the reasons

**Comment by loumalouomega** [comment]
What I want to say that maybe there is something deeper and more obscure

**Comment by loumalouomega** [comment]
I found the error, the conditions were inverted, for some reason the tests were passing in 4 order

**Pull request merged**
