### PR TITLE
[Core] Update json.hpp to 3.5

### PR DESCRIPTION
**Pull request by loumalouomega**
Details in : https://github.com/nlohmann/json/releases

Basically some bugfixes and:

- Structured bindings are now supported for JSON objects and arrays via the items() member function, so finally this code is possible:
- Added support for reading from FILE* to support situations in which streams are nit available or would require too much RAM.

We can add use of these features in a future PR for the Kratos::Parameters

### CODE REVIEW

**Comment by roigcarlo** [comment]
@KratosMultiphysics/technical-committee Agrees, but please @philbucher if you can, test if it works with Intel.

**Comment by philbucher** [comment]
I will check it next week

**Review by philbucher — APPROVED** [review]
tested with Intel, works, thx

**Comment by loumalouomega** [comment]
Bye bye tetgen

**Pull request merged**
