### PR TITLE
[Core] Documenting `Tester`

### PR DESCRIPTION
**Pull request by loumalouomega**
**📝 Description**

This PR refactors the Tester class in the Kratos framework, improving code readability and adding documentation.

**🆕 Changelog**

- [Documenting Tester](https://github.com/KratosMultiphysics/Kratos/commit/185748f434ad8cdb3391e11ed0ed63739bfaa680)
	1. Renamed method arguments to use the "r" prefix for reference arguments.
	2. Changed method signatures to use const-correctness and added missing parameters.
	3. Added detailed comments to describe the purpose and functionality of each method.
	4. Replaced `typedefs` with `using` statements for better readability.

### CODE REVIEW

**Review by roigcarlo — APPROVED** [review]
:+1: Ok, but we are dropping this @loumalouomega don't spend time in improving the tester :S

**Comment by loumalouomega** [comment]
> 👍 Ok, but we are dropping this @loumalouomega don't spend time in improving the tester :S

Ups, I thought you were going to interface the new library with this.

**Comment by roigcarlo** [comment]
So far in my dev branch there is no much left to maintain :P

**Comment by loumalouomega** [comment]
> So far in my dev branch there is no much left to maintain :P

Link?

**Comment by roigcarlo** [comment]
Is not upstream yet.

**Pull request merged**
