### PR TITLE
[ConstitutiveLaws] Solving plasticity tests error

### PR DESCRIPTION
**Pull request by SergioJimenezReyes**
**Description**
Correcting a plasticity test and the small strain plasticity integrator.

**Changelog**
- Increase the Fracture energy in the TensileTestStructural python test and updating the results.
- Removing the comments from the plasticity CL integrator
- Moving to the original version of the exponential softening curve; the idea of calling the linear curve when Gf < Gf_min has been changed by a Kratos ERROR message.

### CODE REVIEW

**Review by loumalouomega — DISMISSED** [review]

**Comment by philbucher** [comment]
@SergioJimenezReyes the results file is huge (1.8MB, ~1% of Kratos)
could you please in this or a followup PR reduce the size?
e.g. by checking less nodes or reducing the check frequency?
Thx

**Comment by SergioJimenezReyes** [comment]
> @SergioJimenezReyes the results file is huge (1.8MB, ~1% of Kratos)
> could you please in this or a followup PR reduce the size?
> e.g. by checking less nodes or reducing the check frequency?
> Thx

I can do it yes, but I am not the owner of the test. I have seen that @loumalouomega and @AlejandroCornejo worked on that file. Tell me if I need you want me to do something special or you are happy if I just increase the _time_frequancy_ (now it is set to 0.1)

**Comment by philbucher** [comment]
I think both would make sense
a frequency of 0.4 or so would already be better. Checking less nodes is already harder as you need to know the geometry

In any case this test should get a proper refactor as it is too fine and large IMO but probably not in this PR

hence increasing the freq would be a nice short solution, thx

**Comment by SergioJimenezReyes** [comment]
Done @philbucher. If you can approve I'll merge it

**Review by philbucher — APPROVED** [review]
Thx!

**Pull request merged**
