### PR TITLE
[Structural] some improvements in membrane

### PR DESCRIPTION
**Pull request by philbucher**
**Description**
@KlausBSautter I found some more minor issues in the membrane, same as with #8244 

can you please take a look?

### CODE REVIEW

**Review by KlausBSautter — APPROVED** [review]
:+1:

**Review by KlausBSautter — CHANGES_REQUESTED** [review]
you should pass a process info if you change the function arguments. One example:

https://github.com/KratosMultiphysics/Kratos/blob/542d4db7f31907b156947992642ed9f70aa5addd/applications/StructuralMechanicsApplication/custom_elements/membrane_element.cpp#L564

**Comment by philbucher** [comment]
> you should pass a process info if you change the function arguments. One example:
> 
> https://github.com/KratosMultiphysics/Kratos/blob/542d4db7f31907b156947992642ed9f70aa5addd/applications/StructuralMechanicsApplication/custom_elements/membrane_element.cpp#L564

yes that is what I would like you to do ;)

I am only pointing out some stuff but since you know better I would leave it to you
thx!

**Comment by KlausBSautter** [comment]
@philbucher

**Comment by KlausBSautter** [comment]
ah do I need to approve this myself?

**Comment by philbucher** [comment]
> ah do I need to approve this myself?

yes :)

**Review by KlausBSautter — APPROVED** [review]

**Pull request merged**
