### PR TITLE
[CI][EigenSolversApp] activate MKL for build/test

### PR DESCRIPTION
**Pull request by armingeiser**
This activates MKL for building and testing in the github CI under Ubuntu.
Now all tests from EigenSolversApplication run, including the MKL solvers.

image

### CODE REVIEW

**Comment by philbucher** [comment]
I think you have to source again in the other build-phases
Same as e.g. for PYTHONPATH

**Review by philbucher — DISMISSED** [review]
cool, thx!

**Comment by armingeiser** [comment]
A test from the CSharpWrapperApplication is now failing ...
```bash
    TestCSharpWrapperUpdateNodePosition Failed with message: 
        Error: Decomposition failed!
```

**Comment by philbucher** [comment]
hm there were problems with this tests also before 
@loumalouomega can you please have a look?
Probably specifying the linear solver would fix the issue

**Comment by loumalouomega** [comment]
Huuuum, let me see

**Comment by armingeiser** [comment]
The test `CSharpWrapperUpdateNodePositionWithJSON` has been set up to use the skyline_lu solver. The error disappears.

The test `TestCSharpWrapperUpdateNodePosition` is constructing the fastest available solver, which now is pardiso_lu. This one is still failing, saying that the decomposition failed. 

However locally i can run both tests also with the pardiso_lu or also sparse_lu solver...

**Comment by oberbichler** [comment]
👍

**Comment by philbucher** [comment]
@loumalouomega can you take a look please?

**Comment by loumalouomega** [comment]
> 
> 
> @loumalouomega can you take a look please?

The test is just moving the mesh,s hould not be a problem. The only solution I cn think of is manually assign the solver to avoid the problem.

**Review by philbucher — DISMISSED** [review]
thx!

@oberbichler @loumalouomega is this also ok for you?

**Comment by loumalouomega** [comment]
:+1:

**Review by loumalouomega — APPROVED** [review]

**Review by oberbichler — APPROVED** [review]

**Comment by oberbichler** [comment]
👍

**Comment by armingeiser** [comment]
For the record: 

The matrix that fails with pardiso_lu in the CSharpWrapperApplication is:
```
448718 -0.0314103 0 
-0.0314103 1.57051e+06 0 
0 0 448718 
```
The error happens in the decomposition.

However this matrix can be decomposed and successfully used for solving if added e.g. in the EigenSolversTest: 8b49572 (the test is added in the previous commit, but had a typo: 6d0a021)

**Comment by loumalouomega** [comment]
> For the record:
> 
> The matrix that fails with pardiso_lu in the CSharpWrapperApplication is:
> 
> ```
> 448718 -0.0314103 0 
> -0.0314103 1.57051e+06 0 
> 0 0 448718 
> ```

That's trivial, how can fail?

**Comment by armingeiser** [comment]
No idea...

**Pull request merged**
