### PR TITLE
[PotentialFlow] Adding embedded sensitivity matrix and adapting response function

### PR DESCRIPTION
**Pull request by marcnunezc**
Hi,

In this PR I am adding the sensitivity matrix with respect to the distance function for the potential flow, used to compute the sensitivities of the lift for embedded geometries. This will allow to perform optimization directly on the initial geometry:

embedded20

The sensitivities have been validated by comparing against the finite difference method:

incompressible_background1_naca0012_5 0_figure

### CODE REVIEW

**Comment by dbaumgaertner** [comment]
Nice example!

Out of curiosity, is the shape optimization done fully internally using the newly implemented sensitivities/response function and the capabilities from the shape optimization app of Kratos?

**Comment by marcnunezc** [comment]
> Nice example!
> 
> Out of curiosity, is the shape optimization done fully internally using the newly implemented sensitivities/response function and the capabilities from the shape optimization app of Kratos?

Yes! Apart from the specific potential_flow_response, the only thing I needed to add is this [process that I will add in the next PR](https://github.com/KratosMultiphysics/Kratos/blob/cps/adding-embedded-adjoint/applications/CompressiblePotentialFlowApplication/custom_processes/project_sensitivity_to_skin_process.cpp), to project the sensitivities calculated in the background mesh (NORMAL_SENSITIVITY), to the skin where I define the SHAPE_SENSITIVITY. (I am not sure if its 100% valid to simply interpolate the sensitivities from one model_part to the other though)

For the rest, the skin_model_part (what you see in the .gif) goes through the ShapeOptApp as if it was a nodal-based optimization problem (optimizers, filters, MeshMovingApp...).

In the "potential_flow_embedded_response" that I created (following what @armingeiser did [here](https://github.com/KratosMultiphysics/Kratos/issues/5043#issuecomment-499408104)), I'm doing the following for every optimization step:

1) Take the skin model part and load it in a background mesh
2) Solve the embedded potential flow problem
3) Compute embedded sensitivities in the background mesh. 
4) Project the sensitivities to the skin model part. This is done in the GetShapeGradient():
```
    def GetShapeGradient(self):

        skin_model_part = self.model.GetModelPart("skin")
        KratosMultiphysics.ComputeNodesMeanNormalModelPart(skin_model_part,False)
        KratosMultiphysics.CompressiblePotentialFlowApplication.ProjectSensitivityToSkinProcess(self.adjoint_model_part,skin_model_part).Execute()

        gradient = {}
        for node in skin_model_part.Nodes:
            gradient[node.Id] = node.GetSolutionStepValue(KratosMultiphysics.SHAPE_SENSITIVITY)
        return gradient
```

I would try to add both the process I mention and the potential_flow_response in following PRs so it can be further discussed.

**Comment by marcnunezc** [comment]
PD: I did a dummy commit to restart CI, since Travis failed after running out of time.

**Review by inigolcanalejo — APPROVED** [review]
Very impressive results! Looks good to me :+1:

**Pull request merged**
