### PR TITLE
[StructMech] add missing model parts to process_sub_model_part_list in adjoint tests

### PR DESCRIPTION
**Pull request by armingeiser**
requested in #3813

### CODE REVIEW

**Review by loumalouomega — DISMISSED** [review]

**Review by philbucher — DISMISSED** [review]

**Comment by MFusseder** [comment]
I added the "Structure" model part also to the primal parameters of the adjoint sensitivity tests because on my machine I got warnings therefor.
I realized that in some parameter files of the response functions test also some sub model parts are missing within the ```processes_sub_model_part_list``` e.g. in ```eigenfrequency_primal_parameters```. Is there are reason for this?

**Comment by armingeiser** [comment]
Yes, there is. E.g. the "Structure" model part is used in the HDF5 process, which we only use in the adjoint cases.

**Comment by philbucher** [comment]
Guys I think we should briefly speak in person, I am not sure if you completely understood what this setting is doing.
Just to avoid problems in the future

**Review by philbucher — APPROVED** [review]

**Comment by armingeiser** [comment]
Maybe not necessary anymore if #2704 gets merged

**Comment by philbucher** [comment]
is this still needed?
I think it has been fixed in the meantime

**Pull request closed without merging**
