### PR TITLE
Remove external solver dependency in tests

### PR DESCRIPTION
**Pull request by jcotela**
I have set the manufactured solution tests to skip unless the ExternalSolversApplication is available (since they use SuperLU)

### CODE REVIEW

**Comment by loumalouomega** [comment]
@jcotela @RiccardoRossi Should I remove my dependency too?

**Comment by jcotela** [comment]
@loumalouomega I'd say it is highly recommendable. Tests should fail because something is wrong, not because I'm compiling a different set of applications than the developer. Ideally, tests should only use the application they are testing, but I know this is not always possible. For those cases, making the tests skippable reduces the "noise" when tests are run.

**Review by rubenzorrilla — APPROVED** [review]
Makes sense to me. Thanks @jcotela.

**Comment by loumalouomega** [comment]
OK, I will remove my dependency

**Comment by loumalouomega** [comment]
@jcotela I still have one tests that just works with SuperLUSolver, basically because is a complex geometric tests that makes the factorization complicated and the Skyline gives problems (the iterative solvers give problems too). There is any way to check if the ExternalSolverApplication is compiled and just run that test in that case?

**Comment by jcotela** [comment]
@loumalouomega This is how I do it
https://github.com/KratosMultiphysics/Kratos/wiki/How-to-create-unitary-tests#skipping-tests-with-external-dependencies
You have the `SkipUnless` decorator too, to check for a "positive" condition (see this PR).
By the way, the meshing application has some tests for mmg which you are just not declaring if the mmg is not compiled. I'm sure this approach would work there too.

**Comment by loumalouomega** [comment]
@jcotela Thanks a lot!!!

**Pull request merged**
