### PR TITLE
[Core][Utilities] Modify ProjectionNurbsGeometryUtilities namespace to class

### PR DESCRIPTION
**Pull request by tteschemacher**
**Description**
This changes the ProjectionNurbsGeometryUtilities from a utility to a class with static functions.

Furthermore, we should discuss the possibility to get rid of the forward declaration of the Geometry.

### CODE REVIEW

**Comment by philbucher** [comment]
> Furthermore, we should discuss the possibility to get rid of the forward declaration of the Geometry.

what happens if you just include `geometry.h`?

**Comment by tteschemacher** [comment]
> 
> 
> > Furthermore, we should discuss the possibility to get rid of the forward declaration of the Geometry.
> 
> what happens if you just include `geometry.h`?

let's see...

**Comment by philbucher** [comment]
> > > Furthermore, we should discuss the possibility to get rid of the forward declaration of the Geometry.
> > 
> > 
> > what happens if you just include `geometry.h`?
> 
> let's see...

seems to work

**Comment by philbucher** [comment]
btw you also use the NurbsSurface [here](https://github.com/KratosMultiphysics/Kratos/pull/8598/files#diff-ed99a02ef2e274a93d41c975eb3dcb09a3e95e2122b7732dcff404adc8275b3aR132) but don't use it

why not including it too?

**Comment by tteschemacher** [comment]
ok nice.

 
> btw you also use the NurbsSurface [here](https://github.com/KratosMultiphysics/Kratos/pull/8598/files#diff-ed99a02ef2e274a93d41c975eb3dcb09a3e95e2122b7732dcff404adc8275b3aR132) but don't use it
> 
> why not including it too?

It works without, so no need to include it, no?

After merging #8490 and  #8491 I can refactor this class generically as well. Then this projection can be used for all high order geometries.

**Comment by tteschemacher** [comment]
are you happy to merge that? @rubenzorrilla that came from your wish ;)

**Comment by tteschemacher** [comment]
gentlemen, how about an approve? ;)

**Review by rubenzorrilla — APPROVED** [review]
Sorry for the delay. I missed this one. Thanks!

**Comment by tteschemacher** [comment]
Thanks a lot.

**Pull request merged**
