### PR TITLE
Change version

### PR DESCRIPTION
**Pull request by roigcarlo**
Forgot to update to 7.1.0

Btw we already hotfixed this in the release so the version is correct.

### CODE REVIEW

**Review by rubenzorrilla — APPROVED** [review]

**Review by philbucher — APPROVED** [review]
why is this done here too?
=> #6191

**Comment by roigcarlo** [comment]
That one is the default if is not defined while building the kratos_version.obj

**Comment by philbucher** [comment]
> That one is the default if is not defined while building the kratos_version.obj

so I guess they cannot be unified?

**Comment by roigcarlo** [comment]
What do you mean? Technically the one in the source will never be used, is just a fail safe mechanism in case something goes really wrong or someone manages to compile Kratos is ways i prefer not to thing of.

**Comment by philbucher** [comment]
well apparently the version exists in two places and I forgot (didn't know) about the this one

But you know better :)

**Pull request merged**
