### PR TITLE
[ContactStructuralMechanicsApp] Solving minor restart bug with contact

### PR DESCRIPTION
**Pull request by AlejandroCornejo**
name: ✨ Hotfix
about: Now restart with contact simulations WORKS

This was investigated by @lagoncalvesjr , I'm just merging the findings.

### CODE REVIEW

**Review by loumalouomega — APPROVED** [review]
<3

**Comment by loumalouomega** [comment]
> name: ✨ Hotfix about: Now restart with contact simulations WORKS
> 
> This was investigated by @lagoncalvesjr , I'm just merging the findings.

I see it was a very stupid error, thanks @AlejandroCornejo

**Comment by AlejandroCornejo** [comment]
> > name: ✨ Hotfix about: Now restart with contact simulations WORKS
> > This was investigated by @lagoncalvesjr , I'm just merging the findings.
> 
> I see it was a very stupid error, thanks @AlejandroCornejo

yes!! simple to solve but difficult to find, thanks to @roigcarlo and @lagoncalvesjr

**Comment by AlejandroCornejo** [comment]
please @lagoncalvesjr check if these changes are correct

**Comment by lagoncalvesjr** [comment]
Apparently, it is all fine @AlejandroCornejo . But it is failing in one of the compilation tests

**Comment by roigcarlo** [comment]
@lagoncalvesjr you can ignore win until I fix it, is a problem in the CI

**Pull request merged**
