### PR TITLE
Major fixes to the MacOS build script

### PR DESCRIPTION
**Pull request by matekelemen**
- enforce errors when unrecognized options are passed
- fix reporting which option is unrecognized
- fix symlinking python scripts to the install directory
- remove CMake's cache in the build directory before configuring
- support forwarding a list of options to CMake

### CODE REVIEW

**Comment by loumalouomega** [comment]
Di you tried with apple silicon + intel machines?

**Comment by matekelemen** [comment]
only silicon, I don't have an intel machine on hand :/

**Comment by loumalouomega** [comment]
> only silicon, I don't have an intel machine on hand :/

Usually is more complex to compile in silicon, so it should work. Anyway @jginternational, i think GiD team has an Intel Mac machine

**Review by roigcarlo — DISMISSED** [review]
I trust you on all mac related things guys.

**Comment by jginternational** [comment]
Yes we do

> > only silicon, I don't have an intel machine on hand :/
> 
> Usually is more complex to compile in silicon, so it should work. Anyway @jginternational, i think GiD team has an Intel Mac machine

I can try it there tomorrow

**Comment by matekelemen** [comment]
Hey @pasenau,

I added a command line option `-j` that gets forwarded to `cmake`, then eventually the build system, and sets the number of jobs to launch. It defaults to your suggestion (number of threads supported by the machine - `sysctl -n machdep.cpu.thread_count`).

I was under the false assumption that `-j` without an argument already defaulted to the thread count. Thanks for the report! It's nice to hear that the rest works on another Mac as well.

Have you also tried running Kratos? Is everything working as you'd expect?

**Comment by pasenau** [comment]
> Hey @pasenau,
> 
> I added a command line option `-j` that gets forwarded to `cmake`, then eventually the build system, and sets the number of jobs to launch. It defaults to your suggestion (number of threads supported by the machine - `sysctl -n machdep.cpu.thread_count`).
> 
> I was under the false assumption that `-j` without an argument already defaulted to the thread count. **Thanks for the report!** It's nice to hear that the rest works on another Mac as well.
> 
> Have you also tried running Kratos? Is everything working as you'd expect?

Hi,
i downloaded the [Examples repository](https://github.com/KratosMultiphysics/Examples.git) and run the validation example `Examples/fluid_dynamics/validation/body_fitted_cylinder_100Re/source` without problems. 
Here you can see the beginning and end of the log ( full log here: [test_macos_body_fitted_cylinder_100Re.log](https://github.com/KratosMultiphysics/Kratos/files/13307421/test_macos_body_fitted_cylinder_100Re.log) ):
```log
 |  /           |                  
 ' /   __| _` | __|  _ \   __|    
 . \  |   (   | |   (   |\__ \  
_|\_\_|  \__,_|\__|\___/ ____/
           Multi-Physics 9.3."1"-macos-06d16ca628-Release-x86_64
           Compiled for Mac OS and Python3.11 with Clang-17.0
Compiled with threading support.
Maximum number of threads: 4.
Importing    KratosFluidDynamicsApplication 
Initializing KratosFluidDynamicsApplication...
NavierStokesSolverMonolithic: Construction of NavierStokesSolverMonolithic finished. 
NavierStokesSolverMonolithic: Fluid solver variables added correctly. 
::[PythonSolver]::: Reading model part. 
SingleImportModelPart: Reading model part from file: "/Users/gid/Desktop/Kratos/Examples/fluid_dynamics/validation/body_fitted_cylinder_100Re/source/test_cylinder_100Re".mdpa
ModelPartIO:   [Reading Nodes    : 3072 nodes read]
ModelPartIO:   [Reading Elements : 5778 elements read] [Type: Element2D3N]
ModelPartIO:   [Reading Conditions : 366 conditions read] [Type: WallCondition2D2N]
ModelPartIO:   [Total Lines Read : 18997]
SingleImportModelPart: Finished reading model part from mdpa file.
ModelPart: -FluidModelPart- model part
    Buffer Size : 1
    Number of tables : 0
    Number of sub model parts : 6
    Current solution step index : 0
    DOMAIN_SIZE : 2

    Number of Geometries  : 0
    Mesh 0 :
        Number of Nodes       : 3072
        Number of Properties  : 2
        Number of Elements    : 5778
        Number of Conditions  : 366
        Number of Constraints : 0
     ...

::[PythonSolver]:: : Finished reading model part. 
Read materials: Started
[WARNING] ReadMaterialsUtility: WARNING:: The properties ID: 1 is already defined in model part FluidModelPart.Parts_Fluid. This will overwrite the existing values
Read materials: Finished
TetrahedralMeshOrientationCheck: No inverted elements found
Mesh orientation check found 366 inverted conditions.
NavierStokesSolverMonolithic: Model reading finished. 
NavierStokesSolverMonolithic: Fluid solver DOFs added correctly. 
[WARNING] VtkOutput: Modelpart "fluid_computational_model_part" has both elements and conditions.
Giving precedence to elements and writing only elements!
TimeBasedAsciiFileWriterUtility: File output buffer size set to 1 
for TimeBasedAsciiFileWriterUtility output file FluidModelPart.Drag_No_Slip_Cylinder_drag.dat 
Linear-Solver-Factory: Constructing a regular (non-complex) linear-solver 
NavierStokesSolverMonolithic: Solver initialization finished. 
Fluid Dynamics Analysis: Analysis -START-  
Fluid Dynamics Analysis: STEP:  1 
Fluid Dynamics Analysis: TIME:  0.1 
Fluid Dynamics Analysis: STEP:  2 
Fluid Dynamics Analysis: TIME:  0.2 
Fluid Dynamics Analysis: STEP:  3 
...
Fluid Dynamics Analysis: STEP:  449 
Fluid Dynamics Analysis: TIME:  44.90000000000037 
Fluid Dynamics Analysis: STEP:  450 
Fluid Dynamics Analysis: TIME:  45.00000000000037 
Fluid Dynamics Analysis: Analysis -END-  
```

Best,

Miguel Pasenau

**Comment by matekelemen** [comment]
@pasenau excellent, thanks!

@roigcarlo @loumalouomega can you please take another look / reapprove?

**Comment by loumalouomega** [comment]
I don't have a mac to check it

**Review by loumalouomega — DISMISSED** [review]

**Comment by pasenau** [comment]
🤣 
Hallo @matekelemen  again,

Now the problem appears when i run `./mac_build -t Release -a FluidDynamicsApplication` for a second time.
The error that appears ( full failed build log is here [mac_build_failed.log](https://github.com/KratosMultiphysics/Kratos/files/13310222/mac_build_failed.log)  ) is this one:

```text
...
...
-- Found PythonInterp: /usr/local/lib/python3.11/site-packages/python  
CMake Error at cmake_modules/FindPythonLibsNew.cmake:110 (message):
  Python config failure:

Call Stack (most recent call first):
  cmake_modules/pybind11Tools.cmake:16 (find_package)
  CMakeLists.txt:293 (include)


-- Configuring incomplete, errors occurred!
```

The file `/usr/local/lib/python3.11/site-packages/python` was not there before. It seems that the script `mac_build` creates this file.
(The owner of the file is $USER ( "gid" in my case) as it is the whole `/usr/local/lib` sub-tree ) :
```shell
$ ls -l /usr/local/lib/python3.11/site-packages/python
-rw-r--r--  1 gid  admin  5536432  9 nov 13:08 /usr/local/lib/python3.11/site-packages/python
```

If i remove this file, i am able to build Kratos again with  `./mac_build -t Release -a FluidDynamicsApplication` ( full log here 
[mac_build_ok.log](https://github.com/KratosMultiphysics/Kratos/files/13310353/mac_build_ok.log) ) as you can see here:

```text
...
...
[100%] Built target KratosFluidDynamicsApplication
Install the project...
-- Install configuration: "Release"
-- Deleting: /usr/local/lib/python3.11/site-packages/KratosMultiphysics
-- Deleting: /usr/local/lib/python3.11/site-packages/libs
-- Trying to install python stub files to enable python hinting support for cpp libraries in IDEs...
```

But the file `/usr/local/lib/python3.11/site-packages/python` is created again !!

May be there is a copy inside the script? , or it is the output of some cmake commands?

```shell
$ file  /usr/local/lib/python3.11/site-packages/python
/usr/local/lib/python3.11/site-packages/python: Mach-O 64-bit dynamically linked shared library x86_64
```

Looking at it with `otool -Dl /usr/local/lib/python3.11/site-packages/python` i followed a hint and found out that this file is a "copy of some sort" of `/usr/local/opt/python@3.11/Frameworks/Python.framework/Versions/3.11/Python` :

```shell
$ md5 /usr/local/lib/python3.11/site-packages/python /usr/local/opt/python@3.11/Frameworks/Python.framework/Versions/3.11/Python
MD5 (/usr/local/lib/python3.11/site-packages/python) = 1d6794ac14bf9c083b22c74c841f3de0
MD5 (/usr/local/opt/python@3.11/Frameworks/Python.framework/Versions/3.11/Python) = 1d6794ac14bf9c083b22c74c841f3de0
```

It seems that somewhere sort of a copy is being made, as it does not maintain neither the name nor the permissions...

Note that in my macOS both files are the same:
```shell
/usr/local/lib/python3.11/site-packages/python
/usr/local/lib/python3.11/site-packages/Python
```

Any ideas?

Miguel Pasenau

**Comment by matekelemen** [comment]
The latest commit finally fixes the issue of crashing on thrown exceptions (you may have seen it as trace trap crashes without any information).

**Review by roigcarlo — APPROVED** [review]

**Pull request merged**
