### PR TITLE
HOTFIX fluid dynamics Ausas condition and body fitted drag cpp tests.

### PR DESCRIPTION
**Pull request by rubenzorrilla**
Corrections in Ausas condition 2D test values and body fitted drag computation (missing buffer size and step setting)

### CODE REVIEW

**Comment by roigcarlo** [comment]
@rubenzorrilla Just to remind that if this is to be added to 5.3 please do not remove the branch on merge

**Comment by rubenzorrilla** [comment]
@roigcarlo thanks for the reminder! (Probably I'd have deleted it...)

**Review by jcotela — APPROVED** [review]
:+1: thanks @rubenzorrilla

**Comment by pooyan-dadvand** [comment]
I would delete the branch

**Comment by rubenzorrilla** [comment]
My bad. Thanks @pooyan-dadvand !

**Pull request merged**
