### PR TITLE
[StructuralMechanicsApplication] Properly initializing neighbours

### LINKED ISSUE #4289: failing structural tests in full debug
Hi guys, i am reporting here two problems i am getting while running tests of the structural mechanics app in FullDebug. I am in branch 
#4286 but i think that the problems are unrelated

@loumalouomega i consistently get the following:
~~~
test_execution (structural_mechanics_test_factory.SprismMembranePatchTests) ... ReadMaterialsUtility: WARNING:: The properties ID: 2 in mesh ID: 0 is already defined. This will overwrite the existing values
Check failed in file Check failed in file /usr/include/boost/numeric/ublas/storage.hpp at line 190:
i < size_
Check failed in file /usr/include/boost/numeric/ublas/storage.hpp at line 190:
i < size_
terminate called after throwing an instance of 'boost::numeric::ublas::bad_index'
  what():  bad index
[riccardo-XPS-8930:13068] *** Process received signal ***
[riccardo-XPS-8930:13068] Signal: Aborted (6)
[riccardo-XPS-8930:13068] Signal code:  (-6)
[riccardo-XPS-8930:13068] [ 0] /lib/x86_64-linux-gnu/libc.so.6(+0x3ef20)[0x7f2275aa3f20]
[riccardo-XPS-8930:13068] [ 1] /lib/x86_64-linux-gnu/libc.so.6(gsignal+0xc7)[0x7f2275aa3e97]
[riccardo-XPS-8930:13068] [ 2] /lib/x86_64-linux-gnu/libc.so.6(abort+0x141)[0x7f2275aa5801]
[riccardo-XPS-8930:13068] [ 3] /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x8c8b7)[0x7f226f7a38b7]
[riccardo-XPS-8930:13068] [ 4] /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x92a06)[0x7f226f7a9a06]
[riccardo-XPS-8930:13068] [ 5] /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x91a69)[0x7f226f7a8a69]
[riccardo-XPS-8930:13068] [ 6] /usr/lib/x86_64-linux-gnu/libstdc++.so.6(__gxx_personality_v0+0x2e8)[0x7f226f7a9418]
[riccardo-XPS-8930:13068] [ 7] /lib/x86_64-linux-gnu/libgcc_s.so.1(+0x10553)[0x7f226f2e0553]
[riccardo-XPS-8930:13068] [ 8] /lib/x86_64-linux-gnu/libgcc_s.so.1(_Unwind_Resume+0x125)[0x7f226f2e0dd5]
[riccardo-XPS-8930:13068] [ 9] /home/riccardo/Kratos/libs/Kratos.cpython-36m-x86_64-linux-gnu.so(+0x26c6b1)[0x7f2272b5a6b1]
[riccardo-XPS-8930:13068] [10] /home/riccardo/Kratos/libs/Kratos.cpython-36m-x86_64-linux-gnu.so(+0x2c585e)[0x7f2272bb385e]
[riccardo-XPS-8930:13068] [11] /home/riccardo/Kratos/libs/Kratos.cpython-36m-x86_64-linux-gnu.so(+0x2c21f5)[0x7f2272bb01f5]
[riccardo-XPS-8930:13068] [12] /home/riccardo/Kratos/libs/Kratos.cpython-36m-x86_64-linux-gnu.so(+0x4e654b)[0x7f2272dd454b]
[riccardo-XPS-8930:13068] [13] /home/riccardo/Kratos/libs/Kratos.cpython-36m-x86_64-linux-gnu.so(+0x33bd81)[0x7f2272c29d81]
[riccardo-XPS-8930:13068] [14] /usr/lib/x86_64-linux-gnu/libgomp.so.1(+0x1697e)[0x7f226f4fe97e]
[riccardo-XPS-8930:13068] [15] /lib/x86_64-linux-gnu/libpthread.so.0(+0x76db)[0x7f227584d6db]
[riccardo-XPS-8930:13068] [16] /lib/x86_64-linux-gnu/libc.so.6(clone+0x3f)[0x7f2275b8688f]
[riccardo-XPS-8930:13068] *** End of error message ***
Aborted (core dumped)
~~~

and ONCE i got an error thrown about GetValue(NEIGHBOUR_NODES) being used within a parallel region in a non-threadsafe manner (unfortunately no information is displayed on which test  )

### PR DESCRIPTION
**Pull request by loumalouomega**
This fixes #4289

I will port this to the Release branch

### CODE REVIEW

**Review by philbucher — APPROVED** [review]

**Comment by philbucher** [comment]
strange it wasn't failing for me

**Comment by loumalouomega** [comment]
> strange it wasn't failing for me

Because the loop was not in parallel, but it failed due to a memory error.

**Comment by loumalouomega** [comment]
@roigcarlo can this be ported to the Release?

**Comment by roigcarlo** [comment]
yes

**Pull request merged**
