### PR TITLE
[Core][VariableUtils] improve some fcts

### PR DESCRIPTION
**Pull request by philbucher**
now also accept std::vector

### CODE REVIEW

**Comment by loumalouomega** [comment]
Build of the test fails, okay fro my side

**Comment by philbucher** [comment]
Anyone?
@loumalouomega  😄

**Review by loumalouomega — APPROVED** [review]
I trust you

**Comment by philbucher** [comment]
> I trust you 

You shouldn't 
I don't even trust myself 🤣

**Pull request merged**
