### PR TITLE
[Core][Release] Residual criteria and block B&S correction

### PR DESCRIPTION
**Pull request by loumalouomega**
This cherry-picks #4286 into Release7-0

### CODE REVIEW

**Review by roigcarlo — APPROVED** [review]
I will approve @philbucher @loumalouomega but the number of cherrypicks is starting to get out of control...

**Comment by loumalouomega** [comment]
From #4340 we are already aware of that:

imagen

**Comment by loumalouomega** [comment]
~~~
Ran 637 of 638 test cases in 3.39751s. 1 failed:
    TestTotalLagrangian2D3_TransientSensitivity Failed with message: 
        Error: Check failed because adjoint_sensitivity = 1.52028e-05 is not near to finite_diff_sensitivity = 1.52073e-05 within the tolerance 1e-09
in /home/travis/build/KratosMultiphysics/Kratos/applications/StructuralMechanicsApplication/tests/cpp_tests/test_solid_transient_sensitivity.cpp:105:virtual void Testing::TestTotalLagrangian2D3_TransientSensitivity::TestFunction()
~~~
@philbucher Have we changed this test or something?

**Comment by philbucher** [comment]
I for sure have not, maybe @msandre has?

It worked on master so maybe there is sth differing btw the branches ...?

Wasn't there some modification done on this test recently? Can you check master vs release-branch if there are differences?

It gets tricky now ...
We have to be careful

**Comment by philbucher** [comment]
I talked, to @msandre , he hasn't changed the tests, but you have @loumalouomega => #4197 

Maybe these changes also have to be cherry-picked (don't beat us up @roigcarlo please :) )

**Comment by roigcarlo** [comment]
:man_shrugging:  Ok make antoher Pr then

**Comment by loumalouomega** [comment]
> I talked, to @msandre , he hasn't changed the tests, but you have @loumalouomega => #4197
> 
> Maybe these changes also have to be cherry-picked (don't beat us up @roigcarlo please :) )

imagen

**Comment by loumalouomega** [comment]
> man_shrugging Ok make antoher Pr then

OK

**Pull request merged**
