### PR TITLE
Migration of modal Analysis to Solid Mechanics

### PR DESCRIPTION
**Pull request by lorenzogracia**
Migration of eigensolver strategy, scheme, and utility.
Also it is added a function in the strategy for computing the participation of each mode.

### CODE REVIEW

**Comment by josep-m-carbonell** [comment]
Thank you Lorenzo. It looks all right. However let me take a more detailed look on it.  I will do it as soon as possible.

**Review by josep-m-carbonell — APPROVED** [review]
Hello Lorenzo. I have made some changes in your pull request. The solid_ prefix was not needed. Also the solvers were updated and the tests migrated. I am not compiling FEAST, so I could not check the tests. If you can do it I would appreciate.

**Comment by lorenzogracia** [comment]
Hello Josep Maria. I am going to check the tests that you have added. If everything goes well I will merge the branch.

**Comment by josep-m-carbonell** [comment]
Hi Lorenzo. I have also checked and corrected them. Now, in my computer,  they all run correctly.

**Comment by lorenzogracia** [comment]
Hi Josep Maria. I have also ran the solid examples and it seems that everything works properly. Maybe could be interesting write the eigenvalues in a text file (just a suggestion).

**Comment by josep-m-carbonell** [comment]
A good suggestion Lorenzo. Maybe a process in python can be created to do it. I don't know if you are doing it currently. Let's talk about it next days.
Thank you for the migration
Kind regards

**Pull request merged**
