### PR TITLE
Clearer print (and shorter) of the apps that are being compiled

### PR DESCRIPTION
**Pull request by maceligueta**
With the change, when you start the compilation, you would see:

```C++
***** LIST OF KRATOS APPLICATIONS THAT ARE GOING TO BE COMPILED: *****
 
                FLUID_DYNAMICS_APPLICATION - ON
                INCOMPRESSIBLE_FLUID_APPLICATION - ON
                DEM_APPLICATION - ON
                SWIMMING_DEM_APPLICATION - ON
                EXTERNAL_SOLVERS_APPLICATION - ON
 
**********************************************************************
 
********** LIST OF KRATOS APPLICATIONS THAT ARE SET TO OFF: **********
 
                CONVECTION_DIFFUSION_APPLICATION - OFF
                STRUCTURAL_APPLICATION - OFF
                SOLID_MECHANICS_APPLICATION - OFF
                CONTACT_MECHANICS_APPLICATION - OFF
                THERMO_MECHANICAL_APPLICATION - OFF
                ALE_APPLICATION - OFF
                FSI_APPLICATION - OFF
                MIXED_ELEMENT_APPLICATION - OFF
                PFEM_APPLICATION - OFF
                PFEM_SOLID_MECHANICS_APPLICATION - OFF
                PFEM_FLUID_DYNAMICS_APPLICATION - OFF
                MACHINING_APPLICATION - OFF
                OPENCL_APPLICATION - OFF
                MKL_SOLVERS_APPLICATION - OFF
                TRILINOS_APPLICATION - OFF
                MPI_SEARCH_APPLICATION - OFF
                METIS_APPLICATION - OFF
                MESHING_APPLICATION - OFF
 
**********************************************************************```

### CODE REVIEW

**Review by roigcarlo — CHANGES_REQUESTED** [review]
Nothing wrong but please let me change the application generator first as this change breaks the code there. I will push it directly to this branch

**Comment by maceligueta** [comment]
:+1:

**Comment by pooyan-dadvand** [comment]
Much better than before to see what is on or off!

**Comment by roigcarlo** [comment]
@maceligueta Sorry I forgot about this. Changes done

**Review by roigcarlo — APPROVED** [review]

**Comment by maceligueta** [comment]
I resolved the commits using the web editor...

**Review by roigcarlo — APPROVED** [review]

**Comment by philbucher** [comment]
this is broken with the new compilation mechanism

@maceligueta if you have time it would be cool if you could add it again :)
Thanks a lot!

**Comment by maceligueta** [comment]
Will take a look at it!

**Pull request merged**
