### PR TITLE
ADD_DEPENDENT_APPLICATIONS cmake

### PR DESCRIPTION
**Pull request by josep-m-carbonell**
Adding a flag in Cmake to add applications that are needed for the compilation of other applications. If you want this to be done automatically you add in the configure.sh 
-DADD_DEPENDENT_APPLICATIONS=ON
Else you will receive the errors during the compilation for not added or applications that are OFF and must be ON. 
If an Application has dependencies and you want this to added automatically you must add some lines to this CMakeList.txt reproducing the same behavior

### CODE REVIEW

**Comment by loumalouomega** [comment]
I like it, it would be a good idea to be ON by default but with a warning that you should activate it

**Comment by bodhinandach** [comment]
I like this one as well. Good for applications which are dependent on other applications.

**Review by AFranci — APPROVED** [review]

**Review by RiccardoRossi — COMMENTED** [review]
this is a quite manual mechanism... in particular it makes the CMakeLists in application to become a mess.

can't anyone propose a more structured approach?
in any case if you may  wait for @roigcarlo to be back from holidays before making other changes since this may well affect the travis etc.

**Comment by josep-m-carbonell** [comment]
If an automatic "less manual" mechanism is possible it will be welcomed. 
And about, "it becomes a mess", I think it is so clear, it only adds some lines that are ignored if the ADD_DEPENDENT_APPLICATIONS=OFF, or it is not included.

**Comment by jcotela** [comment]
@josep-m-carbonell the file CMakeLists.txt itself becomes a mess if everyone has to modify it to include dependencies.

**Comment by josep-m-carbonell** [comment]
And the CMakeList.txt said:
oh yes i am a mess

**Comment by josep-m-carbonell** [comment]
@jcotela I have talked with @roigcarlo to modify the CMakeList of each particular application to include the dependencies. It can be done and is a cleaner solution. You can discuss it in the committee and see if you like it.

**Comment by roigcarlo** [comment]
We have been speaking in the @KratosMultiphysics/technical-committee and we agreed that, while the solution I spoke with @josep-m-carbonell works, its very weak and it may crash at any time. 

We have some alternatives that we are studying right now:
- Making a cmake module to handle the dependencies and call it instead of the IF/ELSE currently used,
- Use the "target_dependency" function, but we are not sure on how exactly works
- Change the way the applications are added to the compilation process so we can even remove the CMakeLists.txt from the applications folder ( which will have his own way to define dependencies between applications )

Ideally the third option would be preferred, but we are still finding the best way to implementing without it being a disruptive change.

**Comment by josep-m-carbonell** [comment]
Ok, good news, go ahead with the best solution then.

**Comment by roigcarlo** [comment]
This is now implemented by #5825.

**Pull request merged**
