### PR TITLE
[VtkOutput] moving destructor to cpp

### LINKED ISSUE #3763: Compilation error in windows when compiling the master branch
Good afternoon,

Today I updated the code in my pc and I got the following compilation errors (visual studio):
~~~
//******************************************
Gravedad	Código	Descripción	Proyecto	Archivo	Línea	Estado suprimido
Error	LNK2019	símbolo externo "__declspec(dllimport) public: __cdecl Kratos::VtkOutput::VtkOutput(class Kratos::ModelPart &,class Kratos::Parameters)" (__imp_??0VtkOutput@Kratos@@QEAA@AEAVModelPart@1@VParameters@1@@Z) sin resolver al que se hace referencia en la función "class Kratos::VtkOutput * __cdecl pybind11::detail::initimpl::construct_or_initialize<class Kratos::VtkOutput,class Kratos::ModelPart &,class Kratos::Parameters,0>(class Kratos::ModelPart &,class Kratos::Parameters &&)" (??$construct_or_initialize@VVtkOutput@Kratos@@AEAVModelPart@2@VParameters@2@$0A@@initimpl@detail@pybind11@@YAPEAVVtkOutput@Kratos@@AEAVModelPart@4@$$QEAVParameters@4@@Z)	Kratos	D:\MasterKratos\Kratos\cmake_build\kratos\add_io_to_python.obj	1	
//******************************************
Gravedad	Código	Descripción	Proyecto	Archivo	Línea	Estado suprimido
Error	LNK2019	símbolo externo "__declspec(dllimport) public: virtual __cdecl Kratos::VtkOutput::~VtkOutput(void)" (__imp_??1VtkOutput@Kratos@@UEAA@XZ) sin resolver al que se hace referencia en la función "public: virtual void * __cdecl Kratos::VtkOutput::`scalar deleting destructor'(unsigned int)" (??_GVtkOutput@Kratos@@UEAAPEAXI@Z)	Kratos	D:\MasterKratos\Kratos\cmake_build\kratos\add_io_to_python.obj	1	

//******************************************
Gravedad	Código	Descripción	Proyecto	Archivo	Línea	Estado suprimido
Error	LNK2019	símbolo externo "__declspec(dllimport) public: void __cdecl Kratos::VtkOutput::PrintOutput(void)" (__imp_?PrintOutput@VtkOutput@Kratos@@QEAAXXZ) sin resolver al que se hace referencia en la función "void __cdecl Kratos::Python::AddIOToPython(class pybind11::module &)" (?AddIOToPython@Python@Kratos@@YAXAEAVmodule@pybind11@@@Z)	Kratos	D:\MasterKratos\Kratos\cmake_build\kratos\add_io_to_python.obj	1	
~~~
imagen

Anyone knows the cause of this?

Thank you all,

Alejandro

### PR DESCRIPTION
**Pull request by philbucher**
this should fix #3763

### CODE REVIEW

**Comment by philbucher** [comment]
@AlejandroCornejo can you try please?

**Comment by philbucher** [comment]
also compiles in appveyor

**Comment by adityaghantasala** [comment]
I am also making some changes to address the warnings that @loumalouomega  mentioned in #3763  !

**Comment by philbucher** [comment]
Ping @AlejandroCornejo

**Review by AlejandroCornejo — APPROVED** [review]
thank you @philbucher !!

**Comment by philbucher** [comment]
Does it compile for you now?

**Comment by AlejandroCornejo** [comment]
I'm trying to compile, let me check

**Comment by AlejandroCornejo** [comment]
it seems that we still have problems...
imagen

**Comment by philbucher** [comment]
hm then maybe its related to the hiding of functions which is fixed in #3768 

Otherwise I don't know

Lets try again after #3768 is merged

**Comment by philbucher** [comment]
can you try again please?

**Comment by AlejandroCornejo** [comment]
I've pulled this branch and i got the error messages still...
imagen

**Comment by philbucher** [comment]
hm ok :/

@roigcarlo then I guess we need your help, sorry for the inconveniences

**Comment by AlejandroCornejo** [comment]
I've restarted the pc and now the visual studio compiles... It's a kind of magic ^^

**Comment by philbucher** [comment]
Windows -,-
Does master compile or only this branch?

**Comment by loumalouomega** [comment]
Should we merge?

**Comment by philbucher** [comment]
ping @AlejandroCornejo

**Comment by AlejandroCornejo** [comment]
yes! it compiles. Than you

**Comment by philbucher** [comment]
> yes! it compiles. Than you

@AlejandroCornejo But which one? :D
Master or only this Branch?

**Comment by AlejandroCornejo** [comment]
all of them sorry haha

**Comment by philbucher** [comment]
ok thx then I am closing this one since it is not necessary

**Pull request closed without merging**
