### PR TITLE
[Core] update CMake

### PR DESCRIPTION
**Pull request by philbucher**
I am proposing to use `CMAKE_CXX_STANDARD`

Unfortunately this means that we also have to update the minimum version for CMake

Up for discussion

### CODE REVIEW

**Comment by roigcarlo** [comment]
I think we don't support 2.8 anyway so... 

>  I will vote yes

**Comment by philbucher** [comment]
I see that @ddiezrod gave :+1: 
@ddiezrod can you please try on one of your machines? I think you guys would be the main blocker here

**Comment by ddiezrod** [comment]
> I see that @ddiezrod gave +1
> @ddiezrod can you please try on one of your machines? I think you guys would be the main blocker here

I think this should work but let me run in the build machines to confirm it.

**Comment by ddiezrod** [comment]
Hmm this is failing in our centos machine. It is using cmake 2.8.12.2, should we postpone this change @pooyan-dadvand ?

**Comment by philbucher** [comment]
Hm thats what I suspected 
Is it possible for you to update your schmale?
I think version 3.1 was released in 2014 so it is also already quite old

**Comment by ddiezrod** [comment]
The officially supported versions for Altair are still centos 6.6/7.2 which come with CMake 2.8.12.2. I do not know if we can update it. @KratosMultiphysics/altair ?

**Comment by philbucher** [comment]
Hm ok then there is not much to discuss I guess :/
Thx for checking 

Btw is CentOS6 open source?
I.e. could the same configuration you have at Altair be included in the Kratos CI?
This would make things easier I guess

**Comment by ddiezrod** [comment]
Yes! I think that is a great idea. We actually use CentOS 7 in the build machines.

**Comment by jrubiogonzalez** [comment]
@philbucher If we add our CentOS configuration to the KratosCI, first beer when we meet in person is on me :)

That would save us so many headaches...

**Comment by philbucher** [comment]
So first I would finish the current CIs which is almost done

Then we could talk abt centos, there I can help you guys doing it. After all, you get paid to work on Kratos ;)

Do you have a dockerimage for centos?

**Comment by philbucher** [comment]
@ddiezrod could you please try again?
I now do NOT change the min required version, I am hoping that older CMakes will just ignore the `CMAKE_CXX_STANDARD`

**Comment by ddiezrod** [comment]
It does work in centos7 @philbucher

**Comment by philbucher** [comment]
> It does work in centos7 @philbucher

perfect thx

@roigcarlo is this ok then for you?

**Review by roigcarlo — APPROVED** [review]

**Comment by loumalouomega** [comment]
~~~
clang++: error: unsupported option '-fPIC' for target 'x86_64-w64-windows-gnu'
~~~
:P

**Comment by loumalouomega** [comment]
Maybe not related

**Comment by roigcarlo** [comment]
> clang++: error: unsupported option '-fPIC' for target 'x86_64-w64-windows-gnu'

Are you cross-compiling?

**Comment by loumalouomega** [comment]
Nope

**Comment by roigcarlo** [comment]
I don't understand that target then sorry :(

**Comment by philbucher** [comment]
Did you google it?

I this this change only enforces c++11 through cmakw

**Comment by loumalouomega** [comment]
Therefore I don't what is related then

**Comment by philbucher** [comment]
Can you give some more info?
Does it work without this change?
System?
Configure.sh?

**Comment by loumalouomega** [comment]
> 
> 
> Can you give some more info?
> Does it work without this change?
> System?
> Configure.sh?

I am testing stuff

**Comment by loumalouomega** [comment]
> 
> 
> > Can you give some more info?
> > Does it work without this change?
> > System?
> > Configure.sh?
> 
> I am testing stuff

Fix it in #6396

**Pull request merged**
