### PR TITLE
[StructuralMechanicsApplication] Setting Bossak as default scheme

### LINKED ISSUE #1743: StructuralMechanics dynamic solver should default to bossak instead of Newmark
@KratosMultiphysics/structural-mechanics as the title suggests, we should default to bossak instead of newmark. This is important since in the nonlinear range it is way more robust. User can simply select newmark if so it wishes.

### PR DESCRIPTION
**Pull request by loumalouomega**
Fixes #1743

### CODE REVIEW

**Review by RiccardoRossi — APPROVED** [review]

**Comment by RiccardoRossi** [comment]
uy, do the tests still pass?

**Comment by loumalouomega** [comment]
Of course

**Comment by loumalouomega** [comment]
@RiccardoRossi There is a fail on the tests, but it is a test from the core, the Redistance

**Comment by loumalouomega** [comment]
FAIL: test_model_part_sub_model_parts (test_redistance.TestRedistance)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/KratosMultiphysics/Kratos/kratos/tests/test_redistance.py", line 48, in test_model_part_sub_model_parts
    self.assertAlmostEqual(min_distance,-0.5049981495922843)
AssertionError: -0.5051939611353824 != -0.5049981495922843 within 7 places

**Comment by philbucher** [comment]
I think this one fails randomly

@roigcarlo do you know abt this?

**Comment by RiccardoRossi** [comment]
i cannot reproduce this locally. I tried even with 128 OpenMP processes and with valgrind...

does it ever fail locally on your computer?

**Comment by roigcarlo** [comment]
Now that you mention I been getting randomly fails of this test. To me it looks like something not initialized or a race condition, but that's all I can tell you. I will keep an eye on it

**Pull request merged**
