### PR TITLE
Calculating and setting reactions on whole of the domain; 

### PR DESCRIPTION
**Pull request by adityaghantasala**
removing the if condition checking if DOF is fixed.

This commit changes only the core builder and solvers.

This is following #1630 

Also should I change the other builder and solvers in applications to do the same ? Or should we leave the implementation like this as it is specific to them.

### CODE REVIEW

**Comment by jcotela** [comment]
@adityaghantasala regarding applications, I'd suggest doing at least the trilinos block builder and solver (the elimination version does not implement the reaction calculation for some reason).

**Comment by adityaghantasala** [comment]
@jcotela  Sure ... actually I have a different branch for each of application (if it has a builder and solver), where I changed respectively.  I will make a separate pull request for them.

**Review by jcotela — APPROVED** [review]
thanks for taking care of this.

**Comment by philbucher** [comment]
can the branch be deleted?

**Pull request merged**
