### PR TITLE
[StructuralMechanicsApplication]  Model in CheckAndPrepareModelProcess 

### LINKED ISSUE #2721: [StructuralMechanics] Using Model for creation of ComputingModelPart
I noticed that the Computation of the computingmodelpart is still based on ModelPart, see [here](https://github.com/KratosMultiphysics/Kratos/blob/master/applications/StructuralMechanicsApplication/python_scripts/check_and_prepare_model_process_structural.py#L25)

this will also work in the future but I see two issues with it:
- It is not consistent with the rest of the code
- it will be the only place in the projectparams where the name of the RootModelpart cannot be prepended, which imo can be confusing

should we change this @KratosMultiphysics/structural-mechanics ?

### PR DESCRIPTION
**Pull request by loumalouomega**
Fixes #2721

### CODE REVIEW

**Comment by philbucher** [comment]
my point was that  `problem_domain_sub_model_part_list` and `processes_sub_model_part_list` still directly construct submodelparts 
=> There we cannot use `RootModelPartName.SubModelPartName.SubSub...` which is inconsistent with the rest of ProjectParameters
Plus it doesn' work with SubSub...Modelparts

Thats why I also aked for the opinion of @RiccardoRossi

**Comment by loumalouomega** [comment]
Maybe this more like a short fix until the new Model is merged, but at least now it uses the model

**Comment by loumalouomega** [comment]
Do I close this then?

**Comment by loumalouomega** [comment]
Do I close this?

**Comment by philbucher** [comment]
can you leave it some more?
ping @RiccardoRossi

**Comment by RiccardoRossi** [comment]
i think that this will be solved automatically once we have the model finally in ... i really hope we'll be able to have that soon...

**Comment by loumalouomega** [comment]
Do I close this?

**Comment by philbucher** [comment]
@RiccardoRossi this will NOT be solved if the Model is merged, bc there are explicit calls to `GetSubModelPart` (from the MainModelPart used in the solver)

I mean [these lines](https://github.com/KratosMultiphysics/Kratos/blob/master/applications/StructuralMechanicsApplication/python_scripts/check_and_prepare_model_process_structural.py#L35-L40)

I think those should be replaced with direct calls to the Model

**Comment by loumalouomega** [comment]
What do we do with this?

**Comment by RiccardoRossi** [comment]
@msandre as i understand the lines you point to would eventually be removed if modelparts get to be automatically registered ... am i wrong?

btw as an offtopic comment ... i really hate the need of "CHeckAndPrepare" :-( (and i am the one to blame for it)

**Comment by msandre** [comment]
I think you mean @philbucher.

**Comment by philbucher** [comment]
@loumalouomega @RiccardoRossi I implemented now what I meant, I hope you can follow
The difference to the current situation is that now I can use not only SubModelParts of the MainModelPart but also SubSub-, SubSubSub- etc ModelParts for the construction of the COmputingModelPart
Is is needed for more complex models

Sorry this took so long, I also had to figure out how to do it properly

**Review by philbucher — APPROVED** [review]

**Pull request merged**
