### PR TITLE
[ContactStructuralMechanicsApplication] Improve self-contact

### PR DESCRIPTION
**Pull request by loumalouomega**
This PR improves the self-contact (previously was limited to very simple cases). Not it allows to compute more complex cases such the [following](https://github.com/KratosMultiphysics/Examples/tree/master/contact_structural_mechanics/use_cases/self_contact): 

In any case it is better by default to assign the master-slave relationship, it is faster and probably better conditioned. This is a complex topic, with very few literature and a lot of corner cases.

### CODE REVIEW

**Review by AlejandroCornejo — APPROVED** [review]

**Comment by philbucher** [comment]
cool feature, but why does the animation stop when the self-contact starts? :)

large mdpa file btw ...

**Comment by philbucher** [comment]
codacy has some suggestions

**Comment by loumalouomega** [comment]
> cool feature, but why does the animation stop when the self-contact starts? :)
 
It starts, you can run the example, maybe I should have considered stop the animation at the end 

> large mdpa file btw ...

😅

**Comment by loumalouomega** [comment]
> codacy has some suggestions

I will check

**Pull request merged**
