### PR TITLE
updated pybind to 2.6.2

### PR DESCRIPTION
**Pull request by philbucher**
**Description**
this contains some nice fixes esp for intel compilers

https://github.com/pybind/pybind11/releases/tag/v2.6.2

@KratosMultiphysics/altair can you please check this in your workflow?

TODO before merging:
- [x] try with Intel compiler (@philbucher)
- [ ] try with Altair workflow

### CODE REVIEW

**Comment by philbucher** [comment]
maybe at so point we should also update our [pybind11Tools](https://github.com/KratosMultiphysics/Kratos/blob/master/cmake_modules/pybind11Tools.cmake)

not sure though, as I remember we made some changes in there...

**Comment by ddiezrod** [comment]
I'll give it a try. We will need some time as we are having some problems with the latest merges in the centos7 machine

**Comment by RiccardoRossi** [comment]
any progress on this one? i think it is interesting

**Comment by philbucher** [comment]
I will finish this once I added Intel to the CI
Then in the future we have every configuration covered by the CI

**Comment by pooyan-dadvand** [comment]
In fact, right now the master branch is failing Altair workflow. (I am debugging it) I will check it after the main branch is fixed

**Comment by philbucher** [comment]
lets see if it compiles with the Intel compiler

@KratosMultiphysics/altair does this have a go from your side?

**Comment by pooyan-dadvand** [comment]
@ddiezrod would you please check it with our stable?

**Comment by philbucher** [comment]
closing for #8976 

Guys our review process is slower than the release cycle of pybind :(

This has been opened pretty much half a year ago

**Pull request closed without merging**
