### PR TITLE
Small update in Trilinos Solvers StructuralMechanics

### PR DESCRIPTION
**Pull request by philbucher**
Hi Guys,
I did some small cleanup in the Trilinossolvers of StructuralMechanics

Also I updated the printing-function in the Solver-baseclass, bcs otherwise everything is printed once per MPI-process

Furthermore I used the new importcheck in the trilinos-partitioningprocess

### CODE REVIEW

**Review by loumalouomega — DISMISSED** [review]
Looks OK

**Comment by philbucher** [comment]
I moved the `scheme_type` to the corresponding classes, could you pls have a look again?

btw @loumalouomega does `compute_contact_forces` need to be in the settings? It is not used in StructuralMechanics and also not in ContactStructuralMechanics

**Review by rubenzorrilla — DISMISSED** [review]
Everything looks good to me. Thanks @philbucher.

**Comment by loumalouomega** [comment]
We can remove the 'compute_contact_forces', is a legacy parameter not used anymore

**Comment by loumalouomega** [comment]
We can remove the 'compute_contact_forces', is a legacy parameter not used anymore

**Comment by philbucher** [comment]
Done, can you approve pls?

**Comment by philbucher** [comment]
can someone approve pls? (I am explicitly dismissing the code review recommendation bcs it is not working in this case)

**Review by loumalouomega — APPROVED** [review]
OK

**Pull request merged**
