### PR TITLE
Applying changes suggested

### PR DESCRIPTION
**Pull request by loumalouomega**
Related with #62 , applying suggested changes, maybe the tolerance is still to big.

### CODE REVIEW

**Review by ipouplana — COMMENTED** [review]
If you do not want to use std::numeric_limits::epsilon() as the tolerance because you fear that it would be too small, you could use 1.0e-8 which, if I am not mistaken, is the tolerance used in the method PointLocalCoordinates of the geometry.h

**Comment by roigcarlo** [comment]
`std::numeric_limits::epsilon()` is the computational tolerance, ie, the difference between 1.0 and the next possible number. It makes sense to use this on operations where you expect your operands to be "close" together:

```C++
// Fail
bool compare(const double a, const double b) {
    return a == b;
}

// Correct
bool compare(const double a, const double b) {
    return std::abs(a - b) < std::numeric_limits<double>::epsilon() ;
}
```

But I think @loumalouomega is more interested in some kind of "mathematical" tolerance.

**Comment by loumalouomega** [comment]
The discussion here is what tolerance consider, I think 1.0e-5 is small enough, but maybe you disagree with me

**Review by ipouplana — APPROVED** [review]
I do not find inappropriate to use 1.0e-5 as the tolerance, I was just stating what I saw in the core regarding tolerances.

**Pull request merged**
