### PR TITLE
[Core] Change SetValueOnIntegrationPoints to SetValuesOnIntegrationPoints

### PR DESCRIPTION
**Pull request by tteschemacher**
Hi all,

I know this is a major change. It would fix the interface name according to the other names. In python it is anyways already in that way.

### CODE REVIEW

**Comment by philbucher** [comment]
+1 from my side

**Review by loumalouomega — COMMENTED** [review]
OK

**Review by RiccardoRossi — COMMENTED** [review]
i also agree.

**Comment by rubenzorrilla** [comment]
:+1: Thanks!

**Comment by RiccardoRossi** [comment]
pooyan? charlie?

**Comment by pooyan-dadvand** [comment]
I also agree!

**Comment by philbucher** [comment]
I am a bit lost, is this still needed @tteschemacher ?
You merged another PR related to this, could you please give an update here? :)

**Comment by tteschemacher** [comment]
It is the suggestion to change the names, as the title says. That makes the naming more coherent.

The other PR was to enhance the input facilities of the according function. It allows to use python lists instead of parsed array_1d.

**Comment by philbucher** [comment]
Can you fix the CI then I guess this is ready since everyone agreed

**Comment by tteschemacher** [comment]
@KratosMultiphysics/technical-committee I fixed it accordingly. Can we merge this, now?

**Review by philbucher — APPROVED** [review]
approving since the rest of @KratosMultiphysics/technical-committee gave their approval and bcs this makes C++ and Python consistent

Thanks for the cleanup @tteschemacher

**Pull request merged**
