### PR TITLE
[Core] Remove KRATOS_ERRORs to allow for mixed dimension couplings (eg. point on a line)

### PR DESCRIPTION
**Pull request by peterjwilson**
**Description**
This allows the coupling geometries to accept geometries of different dimensions.

### CODE REVIEW

**Review by tteschemacher — APPROVED** [review]
Looks good. Those error checks were made for the initial concept. However, as we have additional complexity, the coupling geometries should be still capable to handle it.

**Review by rubenzorrilla — CHANGES_REQUESTED** [review]
But shouldn't you check the `WorkingSpaceDimension` instead?

**Comment by tteschemacher** [comment]
> But shouldn't you check the `WorkingSpaceDimension` instead?

Not really, because it doesn't matter in which dimension those are defined. You could e.g. couple a 2D problem with a 3D problem.

This error massage was a helper to achieve consistency. But the class can do much more without it...

**Review by philbucher — APPROVED** [review]
the rationale of @tteschemacher makes sense to me

**Comment by rubenzorrilla** [comment]
> > But shouldn't you check the `WorkingSpaceDimension` instead?
> 
> Not really, because it doesn't matter in which dimension those are defined. You could e.g. couple a 2D problem with a 3D problem.
> 
> This error massage was a helper to achieve consistency. But the class can do much more without it...

My point is, do we really want to allow the 2D - 3D coupling? (not sure, I've never thought about it)

**Comment by philbucher** [comment]
> My point is, do we really want to allow the 2D - 3D coupling? (not sure, I've never thought about it)

@rubenzorrilla ofc we allow this :sweat_smile: (speaking from a mapping and coupling in general perspective)
To give an example: For my turbine simulations I have a structural model made of shells and also one made of beams. For the beam model, the mapper has to transfer the information form a 1D beam mesh to the 2D surface mesh of the CFD

**Comment by philbucher** [comment]
you can also check the [thesis of one of our former colleagues](https://mediatum.ub.tum.de/doc/1281102/1281102.pdf), chapter 5

**Comment by rubenzorrilla** [comment]
> > My point is, do we really want to allow the 2D - 3D coupling? (not sure, I've never thought about it)
> 
> @rubenzorrilla ofc we allow this sweat_smile (speaking from a mapping and coupling in general perspective)
> To give an example: For my turbine simulations I have a structural model made of shells and also one made of beams. For the beam model, the mapper has to transfer the information form a 1D beam mesh to the 2D surface mesh of the CFD

Well, for me this is 2D / 2D. I think we had a misunderstanding in here...

**Review by rubenzorrilla — APPROVED** [review]
No more blockings.

**Comment by philbucher** [comment]
> What I had in mind was a 2D fluid with a 3D volumetric structure or viceversa. IMO we shouldn't allow this.

I don't have an example at hand but I know that such things are part of research quite recent. Also @pooyan-dadvand told me he was interested in this

**Comment by pooyan-dadvand** [comment]
Having a coupled shell and solid or beams and shells or a 1d line tubes to 3D fluid are just some examples of such coupling.

I remember that in the first implementation there was some code (which I don't remember what was exactly) that would rely on the dimension of the parts but we removed it during the design iterations.

**Comment by pooyan-dadvand** [comment]
Please note that the coupling geometry in this sense would come very useful in generating constrains with more complex kinematics

**Comment by rubenzorrilla** [comment]
> Having a coupled shell and solid or beams and shells or a 1d line tubes to 3D fluid are just some examples of such coupling.
> 
> I remember that in the first implementation there was some code (which I don't remember what was exactly) that would rely on the dimension of the parts but we removed it during the design iterations.

The 1D tube with 3D membrane is a really good example. Thanks for the comment.

**Pull request merged**
