### PR TITLE
[StructuralMechanics] AMatrix Typedefs

### PR DESCRIPTION
**Pull request by philbucher**
As requested

Tests are running in release and fulldebug

### CODE REVIEW

**Comment by loumalouomega** [comment]
Where is step 2 and 3?...6 is repeated

**Review by loumalouomega — APPROVED** [review]
It looks OK, did you run the tests?

**Comment by loumalouomega** [comment]
Well, if Travis compiles means that the tests pass

**Comment by philbucher** [comment]
Some steps were not necessary 

step 6 twice is a typo :)

Yep as I wrote passing both in release and FullDebug

**Review by loumalouomega — APPROVED** [review]
Approving

**Pull request merged**
