### PR TITLE
Removing deprecated test examples and adding new tests

### PR DESCRIPTION
**Pull request by loumalouomega**

### CODE REVIEW

**Comment by loumalouomega** [comment]
Concerning #368

**Comment by josep-m-carbonell** [comment]
As I mentioned in the issue. I think it will be better to add the tests concerning to the SolidMechanics elements to the SolidMechanics application instead of the structural.

**Comment by jcotela** [comment]
@josep-m-carbonell This PR should only concern the prism and shell elements, so this should not be a problem here.

**Comment by josep-m-carbonell** [comment]
@jcotela, I don't know if you have taken a look on it, @loumalouomega added a set of patch tests concerning to solid elements. Furthermore, "Prisms" are also solid elements, maybe they have to be moved to the application that contains the solid elements.....

**Comment by jcotela** [comment]
@josep-m-carbonell I did check the `mdpa` files uploaded. The ones I could find involve shell and sprism elements, which are implemented in the structural application.

**Comment by josep-m-carbonell** [comment]
:1st_place_medal: @jcotela , then you need to check them again.  You can start with this folder:
Kratos/applications/StructuralMechanicsApplication/tests/patch_test

**Comment by pooyan-dadvand** [comment]
Dear  @josep-m-carbonell

As you point out the origin of the StructuralMechanics application and its relation to SolidMechanics application I wanted to give you my personal point of view. 
It is true that the division was defined by solid and not solid elements considering the field of expertise of each team. Nevertheless after 2 years it is very clear to me that the vision of these two applications are not the same. In my opinion you have taken the SolidMechanics application very personal and maintaining it completely at your convenience (which is normal) but without considering the benefit of the entire project or even the crucial objectives of related applications. There were many occasions and observations in the past that leads me to this opinion. Just to mention few of them:
-	Several times rewriting the code and changing the interfaces without even notifying the related applications and breaking compatibility.
-	No concern about the testing and robustness of the code. There is no test at all in the application. 
-	Almost no concern about parallelism and efficiency of the code and breaking the OpenMP parallelism in different occasions. Not mentioning the MPI parallelization. 
-	Very resistance to any patch or modification in SolidMechanics application proposed by other developers while being proactive in rewriting and reorganizing the code by yourself. Some examples are, rejecting the patch for multi-scale constitutive law, stopping the migration of apply value processes to the core, rejecting the changes for nonlinear multilayer shells, etc. 
-	Completely ignoring the multi-disciplinary nature of the project and actively reject modifications or restriction comes from other disciplines.
-	No interest in team working and collaborative aspect of the project which is the most important nature of an open source project. 
-	And many more…..

Saying that, I have observed a very different behaviour in @KratosMultiphysics/structural-mechanics team. The most important one from my point of view is the collaborative nature of them (becoming the largest team in Kratos) and their concern in making it useful also for other applications and align with multi-disciplinary nature of the project. 
Observing such a directions in these two applications, I can tell that now they are two parallel applications with different objectives and not complementary ones as they were in origin. It is sad to arrive to this situation considering that any duplication of the work reduces the efficiency of the project as a whole… Nevertheless, for keeping the StructuralMechanics a high quality, stable and parallel application suitable for multi-disciplinary problems I don’t see any better solution.  On the other hand I think such a separation would give you more freedom in making the SolidMechanics the application you like.

**Comment by josep-m-carbonell** [comment]
Dear @pooyan-dadvand pooyan-dadvand

    Right now I am a little bit tired of working all day with the code trying to improve the robustness of several parts.  At the end of the day, the best thing, your message.
It hurts when I see that you are inventing a set of lies and excuses to justify the inconsistency of certain decisions.

 To answer your offensive affirmations: 

- Several times rewriting the code and changing the interfaces without even notifying the related applications and breaking compatibility.

In the last years, "yes years", I have not made any modification of this type. Maybe you talk about the change in the interfaces when json files and the new GiD interface was introduced and developments were needed.  I have worked in the starting point of the GiD interface to make it work for an initial version. A lot of things got broken in  Kratos, we still have thing that are not up to date.

- No concern about the testing and robustness of the code. There is no test at all in the application.

I am always very concerned on the robustness. I work hard for that, correcting errors instantaneously and improving structures, simplifying the code. Avoiding any duplication in all implemented parts of the applications which I am responsible, etc... If you find out any error you can correct it by yourself or reporting it here as an issue.
About the tests, it seems that you don't want to contribute on that. If any developer has any test to be included in the SolidMechanics App, it is really welcome. 
Right now, some of the tests are deprecated as they also are in the Structural mechanics (take a look on the issues) and other applications. It basically comes from  the change in the scripts due to the json format entries. It is different to program a new thing and put a test than go backwards and start to write tests for things that already work. It requires time and more developers. Everybody is gladly invited to do it.

-Almost no concern about parallelism and efficiency of the code and breaking the OpenMP parallelism in different occasions. Not mentioning the MPI parallelization.

This is definitively not true. I don't know where this idea comes from. I consider that a big rotten lie. I really don't know how you can tell that.

- Very resistance to any patch or modification in SolidMechanics application proposed by other developers while being proactive in rewriting and reorganising the code by yourself. Some examples are, rejecting the patch for multi-scale constitutive law, stopping the migration of apply value processes to the core, rejecting the changes for nonlinear multilayer shells, etc.

In one of the kratos meetings (2012-2013) you asked me to be the responsible of the SolidMechanics application, to clean, build and make it robust. It was a lot of work, since then, there have been several contributions from other developers, and the contribution of everybody is welcome. Well a minimum quality is required. I made also an extended work documenting all implemented things in the KratosWiki, you can check it. Everything was done to promote and make things easier for users and developers.

I think that you are inventing things in what you affirm. Who is saying that I am rejecting things? A patch for the multi-scale constitutive law? Changes for nonlinear multilayer shells? What you are talking about? We had a meeting with the people working in the multiscale some weeks ago to make advances together. It is incredible to read that. 

All the other opinions that you have added, do not deserve an answer. You're judging me by magnifying things, adding lies and inventions ... you're not being fair. I feel very offended and disappointed. I don't know what you want to get with this.

**Comment by jcotela** [comment]
Since this has quickly degenerated into ranting and accusations of lies, let me just say that the post of @pooyan-dadvand matches my personal experience.

@josep-m-carbonell I think that it is very telling that the some of the affirmations that you think "do not deserve an answer" are exemplified by this very thread. Indeed, there is not much to answer.

**Comment by maceligueta** [comment]
I don't think @pooyan-dadvand is lying. @josep-m-carbonell, maybe you do not share the same opinions, but I think it would have been nice a bit of self-criticism during the last years, specially about the bulletpoints Pooyan listed. 
Having said this, I honestly think that the Structural App can add tests of whatever they want, specially in such a situation of lack of communication. The exposed situation at least shows that the relationship with the Solid Mechanics App is far from ideal. So, repeting tests or code is maybe a minor problem here.

**Comment by RiccardoRossi** [comment]
@josep-m-carbonell, Regarding the initial subject of this conversation, it is interesting that you complain about the tests, since they were proposed for addition in https://github.com/KratosMultiphysics/Kratos/pull/44

which **you** have been keeping on hold since the 16th of february. I would suggest you to reread the discussion however you yourself purged it of the interesting parts.
In any case i see no problem in having the tests included in the Structural Application, they will help checking that the overall interface does not get broken.

Moving to the latest comments i can only say that i fully agree with the comments of @pooyan-dadvand  and @jcotela.

I always believed that "leading" an open source software (or application) is not only about the piece of software one writes but rather about holding together a community so that it goes in the "correct" direction, allowing other people to construct on the top of it. A Kratos application should be a place where people can contribute (ideally democratically) not an isolated kingdom with a lonely king ruling at his own wish!!
We clearly do not share this vision...

**Comment by loumalouomega** [comment]
I just want to say that I did this PR because I wanted to remove deprecated cases that were confusing to people not used to Kratos. First I did it directly with the SolidMechanics, but I erased that PR and I made a new one in the Structural, because I thought precisely that this was the best way to avoid the situation we have right now. 

I spent my time doing something simple and insignificant task(twice, three if we consider that frozen pull request #44...), precisely to make Kratos more accessible to people not related with the main developments in CIMNE. 

I am tired of spending my time and see how everything that touches in some way the SolidMechanics is the origin of a stupid discussion. Please we are supposed to be adults and **this is a public conversation**. I can imagine people outside CIMNE thinking that this is not a serious open source project to take into account to work.

**Comment by loumalouomega** [comment]
Besides, @josep-m-carbonell I remember perfectly when we were in SVN and some changes you did without consulting an breaking all the tests in the Structural mechanics, when you change `modulus` and when you change the way the computing model part worked.

imagen

**Comment by loumalouomega** [comment]
It has been almost three weeks since I created this PR @RiccardoRossi

**Comment by RiccardoRossi** [comment]
Hi @loumalouomega, it is very difficult to review a pull request that changes 331 files.

having said this, i am not contrary to removing completely the old unsupported tests

Regarding the new tests If possible i would like to have such tests in a format as in

https://github.com/KratosMultiphysics/Kratos/blob/feature-porting-elements/applications/StructuralMechanicsApplication/tests/test_patch_test_large_strain.py

since they would be much easier to debug...

**Comment by loumalouomega** [comment]
Yes, do you want me to adapt that the tests?

**Comment by RiccardoRossi** [comment]
I would propose to accept the current pull request, you could then adapt the tests as a second step ...

this would simplify the operation

**Review by RiccardoRossi — APPROVED** [review]
+1

**Pull request merged**
