### PR TITLE
[EigenSolversApp] adding solver error msg

### PR DESCRIPTION
**Pull request by philbucher**
now it prints the last error message of the solver in case of failure

### CODE REVIEW

**Comment by oberbichler** [comment]
👍 Did you also check that with the pardiso solver?

**Comment by philbucher** [comment]
I thought I had, but I did not, because it does not compile :(
Maybe we can discuss it in person if we can still somehow add it :)

**Comment by oberbichler** [comment]
Of course! To be honest the current design was a big mistake because it makes it very hard to implement solver-specific extensions. I made some changes on a local branch that are maybe useful also in this case. If you want we can take a look on it on Tuesday when I am back in the office.

**Comment by philbucher** [comment]
Closing since a better solution is implemented in #5684

**Pull request closed without merging**
