### PR TITLE
[Core] Adding HasIntersection method to Prism3D6N

### PR DESCRIPTION
**Pull request by loumalouomega**
This method was missing. Test added

### CODE REVIEW

**Comment by philbucher** [comment]
sorry no clue how this works :)
better let @rubenzorrilla have a look

**Comment by loumalouomega** [comment]
The same is done for Hexahedra, applied on Prism

**Review by philbucher — APPROVED** [review]
ok then, I trust you :)

**Comment by loumalouomega** [comment]
> ok then, I trust you :)

Thanks

**Pull request merged**
