### PR TITLE
[CI] adding docker for Jammy (Ubuntu 22.04)

### PR DESCRIPTION
**Pull request by philbucher**
see title

this only adds the new image
I will update the CI in an upcoming PR

### CODE REVIEW

**Comment by philbucher** [comment]
@marcnunezc @loumalouomega seems like MMG 5,4 does not work with the latest ubuntu
I remember that we discusses already a long time ago to drop support for it, now would be a good time, do you agree?

**Comment by loumalouomega** [comment]
> @marcnunezc @loumalouomega seems like MMG 5,4 does not work with the latest ubuntu
> I remember that we discusses already a long time ago to drop support for it, now would be a good time, do you agree?

Okay

**Comment by marcnunezc** [comment]
> @marcnunezc @loumalouomega seems like MMG 5,4 does not work with the latest ubuntu I remember that we discusses already a long time ago to drop support for it, now would be a good time, do you agree?

Yes, I agree as well.

**Review by roigcarlo — APPROVED** [review]
Do we want to use this in the CI?

**Comment by philbucher** [comment]
> Do we want to use this in the CI?

yes :)

**Pull request merged**
