### PR TITLE
core - mesh smoothing process - flag added in constructor

### PR DESCRIPTION
**Pull request by ddiezrod**
BoundaryFlag added in constructor in order to be able to use different flags such as STRUCTURE, etc

### CODE REVIEW

**Comment by ddiezrod** [comment]
ping pong @pooyan-dadvand

**Comment by ddiezrod** [comment]
Ok, anyone else? @roigcarlo @RiccardoRossi

**Review by roigcarlo — APPROVED** [review]
Up to my knowledge in this topic looks fine. :+1:

**Comment by ddiezrod** [comment]
Thanks @roigcarlo!  I already showed this to @pooyan-dadvand so I will just merge it.

**Pull request merged**
