### PR TITLE
[EigenSolvers] Conda MKL

### PR DESCRIPTION
**Pull request by oberbichler**
With these changes CMake is searching for MKL inside conda ONLY IF!! conda is active. That makes it possible to install MKL with conda with a single command under Windows/Linux/macOS instead of downloading and installing it from the Intel page (which also needs a registration).

It should not change the original behavior when compiling it with a manual installed Python/MKL. Maybe you can do a quick check on your machines.

BTW: As a consequence it also finds Boost, HDF5,... (header+precompiled libs) automatically from conda.

### CODE REVIEW

**Comment by loumalouomega** [comment]
Wow, ice cream for my eyes 👀

**Comment by oberbichler** [comment]
> Wow, ice cream for my eyes 👀

:kissing_heart:

**Comment by pooyan-dadvand** [comment]
Very interesting! How is the performance comparison with our without MKL?

**Comment by pooyan-dadvand** [comment]
Meanwhile, I like this feature. It makes the compilation easier.

**Comment by oberbichler** [comment]
[from the first pr](https://github.com/KratosMultiphysics/Kratos/pull/1132#issuecomment-349960185)

> Just from a quick benchmark: Structural analysis with ~60.000 dofs:
> 
> SuperLU Windows: 66sec
> SuperLU Linux: 16
> Eigen_SparseLU: 8
> Eigen_PardisoLU: 1
> Eigen_PardisoLDLT: 0.7
> Eigen_PardisoLLT: 0.5
> 
> Maybe it depends a bit on the problem/machine

We are only using it for the linear solvers.

Maybe it would make sense to add the feature "take stuff from conda IF conda is available" to the core. It is not EigenSolversApp-specific.

**Comment by philbucher** [comment]
@oberbichler can you please merge master such that this can be reviewed?

**Comment by philbucher** [comment]
@oberbichler I think you need to solve the conflicts again
Maybe we can discuss it again next week :)

**Comment by oberbichler** [comment]
@philbucher not perfect but good enough for an application. Would be nice if we can merge this. It makes it possible to use mkl+boost without manual download/installation.

**Review by philbucher — APPROVED** [review]
I discussed with @oberbichler and we decided to try this here first and then move it to the Core if it works fine.
thanks @oberbichler 

One thing, please merge master to make sure the tests in Win are working, since we enabled them yesterday

**Pull request merged**
