### PR TITLE
[CI] Clang FullDebug uses C++17

### PR DESCRIPTION
**Pull request by philbucher**
**Description**
As preparation for #6611 and to make transition (which will happen eventually) I want to compile one of the CI-builds in C++17 mode.

I think the more diverse compilation configurations we have the easier it is to spot bugs/problems

I also did minor cleanups in the configure file

### CODE REVIEW

**Comment by loumalouomega** [comment]
Can I add some macros that activate only for C++17?, there are several things that can be optimized with the new version

**Comment by philbucher** [comment]
> Can I add some macros that activate only for C++17?, there are several things that can be optimized with the new version

Personally I would love this but I think we should not do this, I think we should use and follow a consistent standard otherwise problems can easily occur

my motivation for this change is more to ensure a smooth transition (a friend told me a scary story of when they moved to a newer standard :sweat_smile:)
Also this makes sure that we not unknowingly use C++ features that are removed in newer versions (e.g. `auto_ptr`)

Right now Kratos works when compiled in C++17 mode and I would like to keep it that way :)

**Comment by philbucher** [comment]
@KratosMultiphysics/technical-committee approves this PR

two more things:
- We still officially use C++11, new feature must not be used
- It is not clear yet which version we will use in the future (see #6611)

**Comment by loumalouomega** [comment]
> @KratosMultiphysics/technical-committee approves this PR
> 
> two more things:
> 
>     * We still officially use C++11, new feature must not be used
> 
>     * It is not clear yet which version we will use in the future (see #6611)

Once this is merged I can add an interesting macro for C++17

**Comment by rubenzorrilla** [comment]
> > @KratosMultiphysics/technical-committee approves this PR
> > two more things:
> > ```
> > * We still officially use C++11, new feature must not be used
> > 
> > * It is not clear yet which version we will use in the future (see #6611)
> > ```
> 
> Once this is merged I can add an interesting macro for C++17

The agreement in the @KratosMultiphysics/technical-committee has been to NOT use any C++17 feature, meaning that developments must stick to C++11 standard. This means that no `__cplusplus` checks are allowed.

**Comment by loumalouomega** [comment]
> > > @KratosMultiphysics/technical-committee approves this PR
> > > two more things:
> > > ```
> > > * We still officially use C++11, new feature must not be used
> > > 
> > > * It is not clear yet which version we will use in the future (see #6611)
> > > ```
> > 
> > 
> > Once this is merged I can add an interesting macro for C++17
> 
> The agreement in the @KratosMultiphysics/technical-committee has been to NOT use any C++17 feature, meaning that developments must stick to C++11 standard. This means that no `__cplusplus` checks are allowed.

A Cmake macro that checks that the compiler actually compiles C++17 (and I assure you this is relevant for mac)

**Comment by rubenzorrilla** [comment]
> > > > @KratosMultiphysics/technical-committee approves this PR
> > > > two more things:
> > > > ```
> > > > * We still officially use C++11, new feature must not be used
> > > > 
> > > > * It is not clear yet which version we will use in the future (see #6611)
> > > > ```
> > > 
> > > 
> > > Once this is merged I can add an interesting macro for C++17
> > 
> > 
> > The agreement in the @KratosMultiphysics/technical-committee has been to NOT use any C++17 feature, meaning that developments must stick to C++11 standard. This means that no `__cplusplus` checks are allowed.
> 
> A Cmake macro that checks that the compiler actually compiles C++17 (and I assure you this is relevant for mac)

But what would be the point of this if we are just changing the Ubuntu CI?

**Comment by philbucher** [comment]
@loumalouomega what does such a macro have to do with this PR?

**Review by rubenzorrilla — APPROVED** [review]

**Comment by loumalouomega** [comment]
> @loumalouomega what does such a macro have to do with this PR?

I was mentioning,as it is related with c++17

**Comment by philbucher** [comment]
> > @loumalouomega what does such a macro have to do with this PR?
> 
> I was mentioning,as it is related with c++17

ah ok

well you could open a PR then we can see

**Comment by rubenzorrilla** [comment]
> > > @loumalouomega what does such a macro have to do with this PR?
> > 
> > 
> > I was mentioning,as it is related with c++17
> 
> ah ok
> 
> well you could open a PR then we can see

Or maybe add it to here to keep track of everything related with this #6611

**Pull request merged**
