### PR TITLE
Implement InitializeSolutionStep and PerformSolutionStep

### PR DESCRIPTION
**Pull request by oberbichler**

### CODE REVIEW

**Comment by oberbichler** [comment]
Btw: how should `PerformSolutionStep` deal with a matrix `rA` that is different from the one in `InitializeSolutionStep`? (@RiccardoRossi, @pooyan-dadvand)

**Review by RiccardoRossi — APPROVED** [review]
looks ok to me

**Comment by oberbichler** [comment]
Let's say I calculate the factoriation with `InitializeSolutionStep(matrix_a, ...)` and then I do `PerformSolutionStep(matrix_b, ...)`. Should `PerformSolutionStep` check `matrix_a` an `matrix_b` for equality?

**Comment by RiccardoRossi** [comment]
I would do the check only in debug mode. BTW, don't forget deleting the branch

**Comment by oberbichler** [comment]
If they are not equal it should throw an error (= Case A) or an new factorization (= Case B)?

Case A: It would be cleaner to remove the matrix argument in `PerformSolutionStep` because it must be the same matrix as in `InitializeSolutionStep`
Case B: I need to do this check also in release mode because otherwise the results may differ

**Comment by RiccardoRossi** [comment]
I would return an error, so that the user knows that something "strange" is going on. This is only my taste however...

**Comment by oberbichler** [comment]
👍 In this case I would remove the argument from `PerformSolutionStep` method.

(I know that this is not so important but I think it makes the design cleaner)

**Pull request merged**
