### PR TITLE
DEM all GUIs added to github

### PR DESCRIPTION
**Pull request by maceligueta**
The GUIs for Granular, Cohesive, Fluid coupling and Solid coupling are added to the DEM Application.

### CODE REVIEW

**Comment by maceligueta** [comment]
Now, all guis use the same 'scripts' folder, which is outside the problemtype, but inside the DEMpack folder. To try them, make a link to DEMpack from the problemtypes folder inside GiD

**Comment by farrufat-cimne** [comment]
looks ok

**Review by farrufat-cimne — APPROVED** [review]

**Comment by maceligueta** [comment]
Just to let @KlausBSautter  know about this.

**Comment by KlausBSautter** [comment]
thanks @maceligueta  I'll have a look

**Pull request merged**
