### PR TITLE
Revert Factories PR

### PR DESCRIPTION
**Pull request by roigcarlo**
Reverts KratosMultiphysics/Kratos#3185

I am very sorry to do that but I don't see any other solution.
Windows compilation is completely broken and the usage of the `KratosCommponents` has been affected across all platforms.

I would prefer a constructive solution but the fixes I can imagine could take long to implement.

About why this is happening: The use of RegisterPrototype in some headers is making the compiler create definitions for most of the new KratosComponents<...> instances and some of the old ones. This is crucial on how the new factory system works, so I cannot simply change it without breaking everything.

This problem is hidden in the CI for the most part as the problems this situation causes involve multiple transactional units, which unitary builds reduce. Same with windows. 

#8654 is an example of this double instantiation problem
#8667, #8663 Same but preventing it to compile do to the fact that windows visibility is hidden by default.

### CODE REVIEW

**Review by loumalouomega — CHANGES_REQUESTED** [review]
Can you wait at least this weekend so I can try to fix the bugs?

**Comment by pooyan-dadvand** [comment]
After checking the issue with @roigcarlo I also realized that the problem is in the template instantiation. So I would suggest to revert the branch so I would have time to finish the new registry which is not templated and won't have this problem.

**Comment by AlejandroCornejo** [comment]
mm Hi! What should I do in order to keep working in Win? Working in this branch?

**Comment by roigcarlo** [comment]
If you didn't update the master after #3185 you can keep working on win just fine, otherwise yes, change to this.

**Review by rubenzorrilla — APPROVED** [review]

**Review by loumalouomega — APPROVED** [review]

**Pull request merged**
