### PR TITLE
Feature add all overrides

### PR DESCRIPTION
**Pull request by RiccardoRossi**
hello everyone,

this branch adds the overrides everywhere employing the clang-tidy, following the procedure described by @loumalouomega.

The commit is pretty big, however
i subdivided the big push in quite a lot of different commits (by subdirectory) which can eventually be reverted independently. 

My idea is that as a very minimum it would be important to keep this for the applications (@jcotela, @msandre there is a commit for the fluidDynamics and another one for the AdjointFluid)

as well as for the strategies, geometries and linear_solvers. 

My proposal is that if someone is working in one of the changed subdirectory and fears problems at the moment of merging, then it should be easy to revert the specific commit that refers to the directory in question. We can repeat the same procedure later on and add the missing overrides.

### CODE REVIEW

**Comment by jcotela** [comment]
👍 for adding overrides
👎 for removing virtuals (yeah I know it is redundant, but I still check the `virtual` first, maybe it's just that I'm old fashioned)

**Comment by RiccardoRossi** [comment]
jeje

@jcotela sorry, that comes in a package. Actually the clang-tidy issues a warning telling that override => virtual and takes out the virtual keyword. Those guys write the compiler...so i assume they know about their business

**Comment by jcotela** [comment]
Yeah I know :( . In fact, you don't even need the `virtual` at all, since "virtualness" is inherited from the base class. Still, that is what I check first to see if I can/should override something.

**Comment by jcotela** [comment]
By the way, did we ever figure out if it should be `const override` or `override const`? I seem to remember some compilers had diverging opinions on that...

**Comment by RiccardoRossi** [comment]
@jcotela, i checked the documentation of the clang-tidy, and i don't think it is possible to avoid removing the virtuals. In my opinion the advantage of automatically adding the override greatly surpasses the "disadvantage" of removing the virtual... so i would not give up on using the tool just for this. 

regarding the const override, clang adds "const override".

**Comment by RiccardoRossi** [comment]
https://stackoverflow.com/questions/12771005/where-does-the-override-qualifier-go-with-trailing-return-types

according to this, i understand that clang is correct and (very) old gcc s have a bug

**Comment by jcotela** [comment]
@RiccardoRossi Well I agree this should be approved, but I'm refraining from insta-approving this to give others a chance to express their opinions.

**Comment by RiccardoRossi** [comment]
@jcotela, yes of course. There is no hurry on this, since we can repeat it with ease. 
However i believe it would be good to have this (or an equivalent pull request) merged before touching the base classes as we are doing in the geometry (for the PointLocalCoordinates, etc) or as we need to do if we want to address for example the #581.

**Review by loumalouomega — COMMENTED** [review]
For me OK, I will wait for as @jcotela for the feedback

**Comment by jcotela** [comment]
By the way @loumalouomega, is there a how-to regarding this `clang-tidy` tool? I had never heard of it...

**Comment by loumalouomega** [comment]
https://github.com/KratosMultiphysics/Kratos/wiki/How-to-use-Clang-Tidy-to-automatically-correct-code

**Comment by loumalouomega** [comment]
@jcotela I discovered that in the blog of this enterprise specialist in Qt and C++: https://www.kdab.com/category/blogs/

**Comment by loumalouomega** [comment]
Besides, this looks interesting: https://www.kdab.com/hotspot-gui-linux-perf-profiler/

**Comment by maceligueta** [comment]
I would push towards adding these lines in CmakeLists of the core (That's what we did in the DEM application because all the developers work with gcc):
```
if(GCC_VERSION VERSION_GREATER 5.1 OR GCC_VERSION VERSION_EQUAL 5.1)
  if(${CMAKE_COMPILER_IS_GNUCXX})
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wsuggest-override")
  endif(${CMAKE_COMPILER_IS_GNUCXX})
endif()
```

**Comment by RiccardoRossi** [comment]
hi @maceligueta, i am fine with adding those lines. 
However are u suggesting to add them IN ALTERNATIVE to the commit or IN ADDITION to the proposed commit?

**Comment by maceligueta** [comment]
I don't really mind, I was just proposing it. But it is very related to this PR, if the merge is not urgent we can add this task.

**Review by jcotela — APPROVED** [review]
👍

**Comment by jcotela** [comment]
@maceligueta I would not be opposed to forcing the compile flag either, at least for gcc

**Comment by loumalouomega** [comment]
Be prepared for a long long recompilation

**Comment by RiccardoRossi** [comment]
@maceligueta i just removed the patch you suggested since there are simply too many warnings (from the applications that i did not modify). This causes the travis compilation to fail, telling that the log is too long.

I am still in favor of adding the patch you suggested, however i would do it a bit later on, when other people corrected their application (applying the correction with clang-tidy is trivial, but you need the code you want to be modified to be compiled)

btw, the way you suggested of checking for the compiler version did not work on my computer. 

i did th same check following
[this link](https://stackoverflow.com/questions/4058565/check-gcc-minor-in-cmake)

    if(CMAKE_CXX_COMPILER_VERSION VERSION_GREATER 5.0)
         set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wsuggest-override")
    endif(CMAKE_CXX_COMPILER_VERSION VERSION_GREATER 5.0)

which does add the flag, and is apparently the "officially supported version" of the check. This however also needs cmake 2.8.10

**Comment by maceligueta** [comment]
Did you modify just the core? Or the whole folder including the apps? (sorry, I can't see the full path from the phone)

**Comment by RiccardoRossi** [comment]
Hi @maceligueta,

i modified the core and the applications that i am currently compiling, that is
FluidDynamics
ExternalSolvers
StructuralMechanics
Adjoint...
ConvectionDiffusion

the problem is that in the nightly build there are others that are still unmodified so this rises millons of warnings in the TravisCL. 
If you like on monday i can show you how to do it for your applications and we commit it as a different pull request.

**Pull request merged**
