### PR TITLE
Reordered member variables due to warning

### PR DESCRIPTION
**Pull request by maceligueta**

### CODE REVIEW

**Comment by rubenzorrilla** [comment]
For me it's ok. But just for my curiosity, what makes the difference in reordering the member variables?

**Comment by loumalouomega** [comment]
Avoid warnings, and I assume is better for the compiler

**Comment by maceligueta** [comment]
I just got a warning complaining about the order, I don't really know why it matters...

**Comment by rubenzorrilla** [comment]
@pooyan-dadvand , @RiccardoRossi any idea?

**Review by rubenzorrilla — APPROVED** [review]

**Comment by pooyan-dadvand** [comment]
the order of initialization in constructor should be the same as definition of the variables:

```C++
class Point{
  double mX;
  double mY;
public:
  Point(): mY(0.00), mX(0.00) // Warning
}
```

**Pull request merged**
