### PR TITLE
Clarification in CMakeList.txt Comments

### PR DESCRIPTION
**Pull request by roigcarlo**
This is for #390 

Please @qiukailu tell me if there is any other message that gives incorrect/outdated info.
I will also use this PR to check if #389 works :) (Edit: it does)

### CODE REVIEW

**Comment by roigcarlo** [comment]
And for the PR, just mark it as approved so I can merge it.
In Files Changed -> Review Changes -> Approve.

Or don't approve if you see something wrong ofc

**Review by qiukailu — APPROVED** [review]
looks good, thanks!

**Comment by qiukailu** [comment]
Hmm, apparently I do not have the required permissions to trigger automated merging, so someone with the proper privileges has to come in and help :) Thanks in advance.

**Comment by roigcarlo** [comment]
I beleive you need to be in Kratos team to do that, And I can't do it myself cose I created the PR, so @loumalouomega  we summon you to approve this.

**Review by loumalouomega — APPROVED** [review]

**Comment by pooyan-dadvand** [comment]
@qiukailu Just to say that whenever you want to join the group you are more than welcomed!

**Comment by qiukailu** [comment]
@pooyan-dadvand Thank you for the kind invitation. I will be more than happy to join, so please kindly add me to the group. Thank you~

**Pull request merged**
