### PR TITLE
Fixed ambiguous call to std::real in AMGCL

### PR DESCRIPTION
**Pull request by roigcarlo**
This should fix the problem in #1634. 

Probably not the best solution as MSVC will not define that var correctly. Ideas on how to solve this cleanly?
@ddemidov Has anyone had this problem before with amgcl?

### CODE REVIEW

**Comment by ddemidov** [comment]
How about using `BOOST_HAS_TR1_COMPLEX_OVERLOADS` macro from [Boost.config](http://www.boost.org/doc/libs/1_65_1/libs/config/doc/html/boost_config/boost_macro_reference.html#boost_config.boost_macro_reference.macros_that_describe_c__11_features_not_supported)?

Also, this probably should go directly to amgcl repository. Would you mind making a PR there?

**Comment by roigcarlo** [comment]
Sure thx :+1:

**Comment by marandra** [comment]
BOOST_HAS_TR1_COMPLEX_OVERLOADS is not solving it here...

**Comment by roigcarlo** [comment]
Let me take a look

**Comment by marandra** [comment]
...or most likely I am missing some definitions somewhere else

**Comment by roigcarlo** [comment]
`BOOST_HAS_TR1_COMPLEX_OVERLOADS` should be defined by boost depending on your compiler. Maybe boost has a problem detecting that you are using c++11 but seems pretty odd

**Comment by ddemidov** [comment]
The macro is correctly defined depending on compiler standard used:
```cpp
#include <iostream>
#include <boost/config.hpp>

int main() {
#ifdef BOOST_HAS_TR1_COMPLEX_OVERLOADS
    std::cout << 1 << std::endl;
#else
    std::cout << 0 << std::endl;
#endif
}
```
```sh
$ g++ -std=c++03 -o hello hello.cpp
$ ./hello
0
$ g++ -std=c++11 -o hello hello.cpp 
$ ./hello 
1
```

@roigcarlo , I *think* `<boost/config.hpp>` should be included somewhere in amgcl code, but its worth trying to include it directly into  `<amgcl/solver/bicgstabl.hpp>`.

**Comment by roigcarlo** [comment]
@ddemidov I think `<boost/config.hpp>` is already included through `<boost/tuple/tuple.hpp>`, which is currently in `<amgcl/solver/bicgstabl.hpp>`. But I will try to include it directly to see what happens

**Comment by marandra** [comment]
Adding `#include <boost/config.hpp>` doesn't help either.

I tried the previous attempt (if __cpluplus <= ...) and it did work.

**Comment by ddemidov** [comment]
@marandra , what is your boost version? It is possible `BOOST_HAS_TR1_COMPLEX_OVERLOADS` was defined later.

**Comment by ddemidov** [comment]
Although it seems the macro was defined [as early as v1.35](http://www.boost.org/doc/libs/1_35_0/libs/config/doc/html/boost_config/boost_macro_reference.html#boost_config.boost_macro_reference.macros_that_describe_optional_features)

**Comment by roigcarlo** [comment]
Can I check it in your machine directly if its possible @marandra?. Maybe using mac has something to do with the issue and its hard to reproduce here...

**Comment by marandra** [comment]
@ddemidov It is v1.62, which is Ok in the installation instruccions for macOS, but I see it is banned in the linux instruction. I am downgrading to v1.61 just in case.

@roigcarlo sure, I'll take it in a few minutes

**Comment by roigcarlo** [comment]
@ddemidov  I check it with @marandra and the problems seems to be that `BOOST_HAS_TR1_COMPLEX_OVERLOADS` is defined in `boost/tr1/detail/config.hpp` and `config/stdlib/libstdcpp3.hpp`. While `<boost/config.hpp>` only acts as a selector of the proper configure file.

I digged a while and these are my conclusions:

For what I can tell you, no `boost/tr1` is being used, so presumably I would say that while evaluating:

```C++
// if we don't have a std library config set, try and find one:
#if !defined(BOOST_STDLIB_CONFIG) && !defined(BOOST_NO_STDLIB_CONFIG) && !defined(BOOST_NO_CONFIG) && defined(__cplusplus)
#  include <boost/config/select_stdlib_config.hpp>
#endif
// if we have a std library config, include it now:
#ifdef BOOST_STDLIB_CONFIG
#  include BOOST_STDLIB_CONFIG
#endif
```

he does have a `BOOST_STDLIB_CONFIG` defined and I guess the problem is that for some reason in mac, clang-3.8 uses an std library which is not `libstdcpp3.hpp`, the only one that defines the macro, but that lib at the same times does implemented `std::real` overload for scalars, and for some reason is not marked as such.

Now the question would be if this is actually intentional or not. @marandra could you add this to the file:

```C++
#pragma message("BOOST_STDLIB_CONFIG=" BOOST_PP_STRINGIZE(BOOST_STDLIB_CONFIG))
```

And tell me what does it print?

**Comment by marandra** [comment]
@roigcarlo 
`warning: BOOST_STDLIB_CONFIG="boost/config/stdlib/libcpp.hpp" [-W#pragma-messages]`

**Comment by marandra** [comment]
@roigcarlo  to clarify, the version of clang is 
`clang version 5.0.1 (tags/RELEASE_501/final)`
and CMake version is 
`cmake version 3.10.2`

**Comment by roigcarlo** [comment]
Thx @msandre. Actually that confirms my suspect as `boost/config/stdlib/libcpp.hpp` does not define the macro we need

**Comment by ddemidov** [comment]
May be we should combine check for `__cplusplus` and `BOOST_HAS_TR1_COMPLEX_OVERLOADS`?

**Comment by roigcarlo** [comment]
That will probably cover most of the cases yep, but let me check what happens in windows as well before pushing any change.

For example, I know that MSVC does not respect the `__cplusplus` number, it's been stuck at 199711L for months...

**Comment by roigcarlo** [comment]
Honestly I don't understand the win implementation but they seem to be able to provide a generic implementation for `real` in `xcomplex`. I suspect they are casting the scalar to complex and then returning the real part... but I am not sure as the implementation is shady... 
The thing is it does not conflict with the ones in `<amgcl/solver/bicgstabl.hpp>`. So adding the  `__cplusplus` will cover everything. 

If there is a hurry I will add it now, but otherwise please let me try to fully understand the win implementation first

**Comment by marandra** [comment]
from my side, no need to rush.

**Comment by roigcarlo** [comment]
Just uploaded the file with the two checks. @pooyan-dadvand you know about this as well. Any idea?

**Comment by pooyan-dadvand** [comment]
Actually I had no idea about this problem and I don't understand why this macro giving problem just now. It might be a macro shadow problem. The expert here is @ddemidov and I rely on his solution.

**Comment by ddemidov** [comment]
Sorry for the late reply, this looks ok to me. @roigcarlo, will you make another PR against upstream amgcl?

**Comment by roigcarlo** [comment]
:+1:

**Comment by roigcarlo** [comment]
@KratosMultiphysics/technical-committee if someone approves I'll merge

**Review by RiccardoRossi — APPROVED** [review]

**Review by RiccardoRossi — APPROVED** [review]

**Pull request merged**
