### PR TITLE
[TrilinosApplication] Fix master DoFs in block builder and solver

### PR DESCRIPTION
**Pull request by loumalouomega**
**📝 Description**

Until now only local slave DoFs were filtered for the `mMasterIds` vector, in here all partitions slave DoFs are considered. I added two dynamic size C++ test (until now I was only checking up two partitions, therefore I was checking many cornercases), so the size of the test depends in the number of partitions considered.

(I discovered this looking for another bug) 

**🆕 Changelog**

- [Fix master dofs](https://github.com/KratosMultiphysics/Kratos/commit/b9c37f56e27a2c26e9bd4f6a72f0e0a363bceb6c)
- [Adding dynamic size testing in order to properly check fix](https://github.com/KratosMultiphysics/Kratos/commit/3a40ac97cb60f5cdaed6996688a8480f1387e915)

### CODE REVIEW

**Comment by loumalouomega** [comment]
Ci broken?

**Comment by roigcarlo** [comment]
Github api had a dowtime of about 1 min, it failed some of my merges too. Bad luck :(

**Comment by loumalouomega** [comment]
@roigcarlo can you check this?, in this case a test is actually added

**Comment by roigcarlo** [comment]
I'll take a look after lunch

**Review by roigcarlo — APPROVED** [review]
Ok,

Just as a curiosity: Why did you change some of the reference values in the tests, I get you want `E_100` as an alias and also `2 * E_100`, but then you can use `E_100 * 0.5` for `1034500000` or `E_100 * 0.25` for `517250000`.

**Pull request merged**
