### PR TITLE
[AtomicUtilities] adding AtomicMult

### PR DESCRIPTION
**Pull request by philbucher**
**Description**
To be used in the LinearMasterSlaveConstraint:
https://github.com/KratosMultiphysics/Kratos/blob/bd815e5fd0c17975627dc7b8351e459388bb9477/kratos/constraints/linear_master_slave_constraint.h#L370

### CODE REVIEW

**Review by loumalouomega — COMMENTED** [review]
Is this supported by MSVC?

**Comment by maceligueta** [comment]
Hi @philbucher , just a couple of comments derived from our conclusions out of
https://github.com/KratosMultiphysics/Kratos/pull/7608/files 

- OpenMP 2.0 only allows scalars, so maybe that static assert you coded some time before (see link) could be useful here
- The division operation and the power operation are also allowed by OpenMP 2.0, so we could take the chance to add `AtomicDiv `and `AtomicPow` in this PR.

**Comment by philbucher** [comment]
yes, it is used already for a while in the LinearMasterSlaveConstraint:
https://github.com/KratosMultiphysics/Kratos/blob/bd815e5fd0c17975627dc7b8351e459388bb9477/kratos/constraints/linear_master_slave_constraint.h#L370

**Comment by philbucher** [comment]
> Hi @philbucher , just a couple of comments derived from our conclusions out of
> https://github.com/KratosMultiphysics/Kratos/pull/7608/files
> 
>     * OpenMP 2.0 only allows scalars, so maybe that static assert you coded some time before (see link) could be useful here
> 
>     * The division operation and the power operation are also allowed by OpenMP 2.0, so we could take the chance to add `AtomicDiv `and `AtomicPow` in this PR.

wasn't there another reason we didn't add the `static_assert` for the other methods?

Also this is related to #8125, I think it makes sense to discuss these issues together

This is not an urgent PR anyway

**Comment by maceligueta** [comment]
The method we wanted to implement then was AtomicAssign, and we tried to restrict the use to scalars, but it did not work because the operations allowed are +=, -=, *=, /=, ^=, &=, |=, <<=, >>=. A simple assignation is not allowed, it seems.

**Comment by roigcarlo** [comment]
@maceligueta Why would you need an `AtomicAssign` operator? It is just syntax sugar, as you are not accessing the left value of the operator, a normal assignment will always take the value of the last thread that assigns the operator, wether is protected or not. In other words the protection just ensures that the last thread starting the operation will be the last thread finishing it, but it does not guarantee the value.

**Comment by philbucher** [comment]
> @maceligueta Why would you need an `AtomicAssign` operator? It is just syntax sugar, as you are not accessing the left value of the operator, a normal assignment will always take the value of the last thread that assigns the operator, wether is protected or not. In other words the protection just ensures that the last thread starting the operation will be the last thread finishing it, but it does not guarantee the value.

wont an unprotected assign be recognized as a race condition by a thread sanitizer?

**Comment by roigcarlo** [comment]
Atomics only prevent data race over instructions. It is true that it should be recognized as a race by a sanitizer, but is more a "scheduler" race rather than a "instruction" race.

Examples of what I mean:

```C++
// Race condition
auto a = 0;
#pragma parallel for
for(i = 1..N) {
    a = a + 1;
}

if(a == N) print("Ok!")

// Undefined behavior
auto a = 0;
#pragma parallel for
for(i = 1..N) {
    a = get_num_thread();
}

if(a == 0) print("Ok!")
```

In the first example the race condition appears because each thread requires the value calculated by others, and the operation `a = a + 1`. If i remember correctly this is called "read before write" and is internally executed as something like (oversimplifying @ calculations as typically do not impact in race conditions)

```Assembler
// All these are atomic.
ead @a reg1
read @i reg2
add reg2 reg1 reg1
store reg1 @a
```

Given a couple of processes if `store reg1 @a` happens on one process after `read @i reg2` and before `store reg1 @a` in the other, then the first process has lost its value.

If you are only making an assignment, you execute something like `store @i @a`, there is no race condition there over any instruction here, mainly because there is no instructions, the operation is atomic by itself. Notice that not even with `#pragma critical` you would be able to solve this.

This is why I don't understand why the need of the `AtomicAssign`. typically what you would want in this scenarios is a reduction or maybe a lastprivate.

**Comment by maceligueta** [comment]
> @maceligueta Why would you need an `AtomicAssign` operator? It is just syntax sugar, as you are not accessing the left value of the operator, a normal assignment will always take the value of the last thread that assigns the operator, wether is protected or not. In other words the protection just ensures that the last thread starting the operation will be the last thread finishing it, but it does not guarantee the value.

No, I don't want it and we actually removed it some months ago.

**Comment by roigcarlo** [comment]
> No, I don't want it and we actually removed it some months ago.

A ok, no problem then :+1: sorry for the noise.

**Comment by philbucher** [comment]
@RiccardoRossi can we merge this?
Then I can add the CXX version we spoke about

**Review by RiccardoRossi — APPROVED** [review]

**Pull request merged**
