### PR TITLE
fixing redistance 

### PR DESCRIPTION
**Pull request by RiccardoRossi**
fixes redistance. 

the problem was that in the latest commit i wrongly reverted to a old version. This should now be fixed

@jcotela this shall also fix Katsuo's problem

### CODE REVIEW

**Comment by philbucher** [comment]
Hi @RiccardoRossi 
I tried it many times and the result is that it always works in `FullDebug`, but it always fails in `Release`.
I always get one of the two values:

```
======================================================================
FAIL: test_model_part_sub_model_parts (__main__.TestRedistance)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_redistance.py", line 47, in test_model_part_sub_model_parts
    self.assertAlmostEqual(max_distance, 0.4473365725705744)
AssertionError: 0.44733589605275026 != 0.4473365725705744 within 7 places

----------------------------------------------------------------------
```
or
```
======================================================================
FAIL: test_model_part_sub_model_parts (__main__.TestRedistance)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_redistance.py", line 47, in test_model_part_sub_model_parts
    self.assertAlmostEqual(max_distance, 0.4473365725705744)
AssertionError: 0.4473360740876121 != 0.4473365725705744 within 7 places

----------------------------------------------------------------------
```

**Comment by RiccardoRossi** [comment]
@philbucher, thank you for your testing. i did some changes to hopefully minimize numerical errors. It now passes tests in release on my machine. Would u mind trying it over?

**Comment by philbucher** [comment]
Now it fails in both modes; FullDebug gives back always the same result:
```
======================================================================
FAIL: test_model_part_sub_model_parts (__main__.TestRedistance)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_redistance.py", line 47, in test_model_part_sub_model_parts
    self.assertAlmostEqual(max_distance, 0.44733610591604156)
AssertionError: 0.44733657257057446 != 0.44733610591604156 within 7 places

----------------------------------------------------------------------
```
Whereas Release gives again 2 different results
```
======================================================================
FAIL: test_model_part_sub_model_parts (__main__.TestRedistance)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_redistance.py", line 47, in test_model_part_sub_model_parts
    self.assertAlmostEqual(max_distance, 0.44733610591604156)
AssertionError: 0.44733589605275026 != 0.44733610591604156 within 7 places

----------------------------------------------------------------------
```
and
```
======================================================================
FAIL: test_model_part_sub_model_parts (__main__.TestRedistance)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_redistance.py", line 48, in test_model_part_sub_model_parts
    self.assertAlmostEqual(min_distance,-0.5049981495922843)
AssertionError: -0.5049973728612649 != -0.5049981495922843 within 7 places

----------------------------------------------------------------------
```

**Comment by RiccardoRossi** [comment]
mmm,

this is a precision error, which depends on the hardware etc. I did some more changes to hopefully reduce it (it never appears on my machine, independently on the number of threads i employ). Could u give another test?

**Review by philbucher — APPROVED** [review]
now it works always

**Pull request merged**
