### PR TITLE
[JsonCheckProcesses] making them MPI-compatible

### PR DESCRIPTION
**Pull request by philbucher**
by introducing the coordinate-based check for nodes. This is necessary bcs currently the IDs are reordered during the partitioning => #4324 
Now we can write tests where the reference results are the same in serial and MPI :tada: 

if #4324 gets solved this can be removed again, but until then it is necessary

Sorry for the minor cleanup I did, I spitted the commits accordingly

### CODE REVIEW

**Comment by philbucher** [comment]
I used the new feature in some of the tests in the MeshMovingApp already, bcs I will refactor some MPI-code there soon.
FYI @AndreasWinterstein

**Review by loumalouomega — DISMISSED** [review]
Maybe once we move this to C++ we can do something simpler and MPI aware (Compare strings is expensive and could fail)

**Review by loumalouomega — APPROVED** [review]

**Comment by philbucher** [comment]
> Maybe once we move this to C++ we can do something simpler and MPI aware (Compare strings is expensive and could fail)

sure, but what?
The previous check was also string based

**Comment by loumalouomega** [comment]
> > Maybe once we move this to C++ we can do something simpler and MPI aware (Compare strings is expensive and could fail)
> 
> sure, but what?
> The previous check was also string based

Yeah, but I simpler string. I don't know exactly how does affect that. In any case can be done using variable keys, which is an integer

**Pull request merged**
