### PR TITLE
[Core] Bound iterations in SVD decomposition

### PR DESCRIPTION
**Pull request by rubenzorrilla**
I found a case in which the SVD algorithm gets stuck. It makes sense to add a break loop condition.

### CODE REVIEW

**Review by loumalouomega — DISMISSED** [review]
Thanks, makes sense

**Comment by rubenzorrilla** [comment]
@loumalouomega can you approve again please? (I missed a coma :man_facepalming: )

**Review by loumalouomega — DISMISSED** [review]
I added a constructor with parameters, to avoid problems in the future with many inputs

**Comment by rubenzorrilla** [comment]
> I added a constructor with parameters, to avoid problems in the future with many inputs

Cool.

**Comment by rubenzorrilla** [comment]
Now you missed the coma :smile:

**Review by loumalouomega — DISMISSED** [review]
:P

**Comment by rubenzorrilla** [comment]
@loumalouomega  parameters can't be `const` if you need to validate them.

**Review by loumalouomega — APPROVED** [review]
Sorry, copy paste error

**Comment by loumalouomega** [comment]
@rubenzorrilla this is ready to merge

**Pull request merged**
