### PR TITLE
[Core] Fix use of CurveAxisIntersection in NurbsCurveOnSurface

### PR DESCRIPTION
**Pull request by tteschemacher**
Hey,

currently the wrong curve was used within the CurveAxisIntersection and thus not coinciding KnotVectors were not possible to compute correctly. This PR fixes this issue.

### CODE REVIEW

**Review by philbucher — COMMENTED** [review]
can you please add a test? ;)

**Comment by tteschemacher** [comment]
> can you please add a test? ;)

It is such a pleasure to do so. :P

**Review by philbucher — DISMISSED** [review]
:heart:

**Comment by tteschemacher** [comment]
@philbucher I am trying to rerun all jobs but it continuously fails before staring the build. Do you have any idea why this is happening.

**Comment by philbucher** [comment]
The CI image was updated from ubuntu 18 to ubuntu 20
Merging master should fix the problem

**Comment by tteschemacher** [comment]
> 
> 
> The CI image was updated from ubuntu 18 to ubuntu 20
> Merging master should fix the problem

thanks a lot, it's working now.

**Review by philbucher — APPROVED** [review]

**Comment by tteschemacher** [comment]
Thanks a lot for the review!!

**Pull request merged**
