### PR TITLE
[ContactStructuralMechanicsApplication] No verbosity on strategy

### PR DESCRIPTION
**Pull request by loumalouomega**
The "MESH MOVED" output interfere with my table stream

### CODE REVIEW

**Comment by philbucher** [comment]
why don't you set the echo-level of the solver to the one of the strategy?

**Comment by loumalouomega** [comment]
Because it conflicts with my table stream

**Comment by philbucher** [comment]
you mean that you use the ech-lvl of the solver for the table stream?

**Review by philbucher — APPROVED** [review]
ok then :)

**Pull request merged**
