### PR TITLE
Correction in submodelparts writing

### PR DESCRIPTION
**Pull request by rubenzorrilla**
Before this PR, all the mainmodelpart nodes, elements and conditions were written in every submodelpart section.

### CODE REVIEW

**Review by loumalouomega — DISMISSED** [review]
Strange that we hadn't see this until today

**Comment by loumalouomega** [comment]
BTW it is in cammelcase, maybe we should change it too

**Comment by pooyan-dadvand** [comment]
I agree with the @loumalouomega about `r_sub_model_part`

**Comment by pooyan-dadvand** [comment]
Would you please add a test for this part?

**Review by loumalouomega — DISMISSED** [review]
OK

**Comment by rubenzorrilla** [comment]
There are still some potential issues if the base Condition2D2N is used. Let's wait for @RiccardoRossi and @pooyan-dadvand decision.

**Comment by rubenzorrilla** [comment]
@RiccardoRossi I've merged the master (including the empty GeometryData fix) into this branch and everything is ok, so we're are ready to merge that. @pooyan-dadvand this PR already includes the test you ask me for.

**Review by RiccardoRossi — APPROVED** [review]

**Comment by philbucher** [comment]
My student noticed this bug today as well. Thx for fixing it @rubenzorrilla !

**Pull request merged**
