### PR TITLE
missing cd in docker file

### PR DESCRIPTION
**Pull request by philbucher**
**Description**
fixing docker build

### CODE REVIEW

**Review by loumalouomega — APPROVED** [review]

**Comment by philbucher** [comment]
hm looking at the output I think now 5.5 overwrote 5.4 since they both install in the root directories

@loumalouomega do you know how to install mmg user-local?

**Comment by loumalouomega** [comment]
Yes

**Comment by loumalouomega** [comment]
You can compile it whenever you want and point to the folder in the configure.sh

**Comment by philbucher** [comment]
yes I know but what is is the cmake command :)
Can you post your local build commands?

**Comment by loumalouomega** [comment]
> yes I know but what is is the cmake command :)
> Can you post your local build commands?

~~~sh
-DINCLUDE_MMG=ON                              \
-DMMG_ROOT="/home/vmataixf/src/mmg/build/"    \
~~~

**Comment by philbucher** [comment]
I mean the build commands for mmg itself

**Comment by loumalouomega** [comment]
~~~sh
cmake .. \
-DCMAKE_BUILD_TYPE=Release                                  \
-DLIBMMG_SHARED=ON                                          \
-DLIBMMG_STATIC=OFF                                         \
-DLIBMMGS_SHARED=ON                                         \
-DLIBMMGS_STATIC=OFF                                        \
-DLIBMMG2D_SHARED=ON                                        \
-DLIBMMG2D_STATIC=OFF                                       \
-DLIBMMG3D_SHARED=ON                                        \
-DLIBMMG3D_STATIC=OFF                                       \

#decomment this to have it verbose
# make VERBOSE=1 -j$(nproc)
make -j$(nproc)

~~~

**Pull request merged**
