### PR TITLE
Windows compilation error fix

### PR DESCRIPTION
**Pull request by rubenzorrilla**
Supressing typename outside of template

### CODE REVIEW

**Comment by rubenzorrilla** [comment]
This fixes #156.

**Comment by pooyan-dadvand** [comment]
Looks perfect! Please let me check if it compiles.

**Comment by pooyan-dadvand** [comment]
It compiles but I have notice that the `TestMathUtilsInvMatTest` fails. 

```
TestMathUtilsInvMatTest Failed with message:
        Error:  Determinant of the matrix is zero or almost zero!!!, InputMatrixDet = 0

in kratos/utilities/math_utils.h:236:MathUtils<double>::InvertMatrix
```

@rubenzorrilla would you please check the c++ tests?

**Comment by pooyan-dadvand** [comment]
OK, seems that master does the same... 

I will make an issue for that

**Review by pooyan-dadvand — APPROVED** [review]
👍

**Pull request merged**
