### PR TITLE
[CI] Test - add tests in windows

### PR DESCRIPTION
**Pull request by ddiezrod**

### CODE REVIEW

**Comment by philbucher** [comment]
wow now it really slow :sweat_smile: 
@roigcarlo the issue with the cotire you mentioned in #6412 cannot be resolved or requires some effort?

**Comment by roigcarlo** [comment]
No we cannot install with cotire, unless you manually navigate through all the folders an collet the DLL, python files and build the dirs manually. 

But try to force the /O0 flag that may help with the compilation speed

**Comment by philbucher** [comment]
hm is it already building for ~2,5hrs :sweat_smile:

**Comment by philbucher** [comment]
> But try to force the /O0 flag that may help with the compilation speed

@oberbichler do you have an idea how to do this?

**Comment by roigcarlo** [comment]
> `No space left on device.`

Ouch.. that's new :_D

**Comment by philbucher** [comment]
> > `No space left on device.`
> 
> Ouch.. that's new :_D

:/

1,5 hrs is anyway too long I would say...

**Comment by roigcarlo** [comment]
Then no more ideas from my side sorry. We could problably install it manually but it will take some time

**Comment by roigcarlo** [comment]
@philbucher We can do this: https://github.com/sakra/cotire/blob/master/MANUAL.md#installing-files-generated-by-unity-targets

But for tat we need to change all CMakes of all applications...

**Comment by philbucher** [comment]
The modification is rather small right?
We could try with the core I guess
Don’t think we can get rid of Cotire after seeing the build times without

**Pull request closed without merging**
