### PR TITLE
Signed tetrahedron volume computation for checking inner points

### PR DESCRIPTION
**Pull request by AFranci**

### CODE REVIEW

**Comment by maceligueta** [comment]
Just for curiosity, why aren't we using the methods of the geometry here? Looks like these operations should be in the core...

**Review by josep-m-carbonell — APPROVED** [review]
It seems ok

**Comment by maceligueta** [comment]
I am still curious about my previous question @AFranci  @josep-m-carbonell

**Comment by AFranci** [comment]
I have only done a correction in a function of the PFEMBase that is currently used. However, you are right and maybe this should be placed in the core. We will discuss it with Giuseppe Maria.

**Pull request merged**
