### PR TITLE
[Core] add checks for variable in dof constructor

### PR DESCRIPTION
**Pull request by philbucher**
This PR adds checks in the constructor of the dof, if the Dof-/Reaction-Variable are in the VariablesList

### CODE REVIEW

**Review by RiccardoRossi — COMMENTED** [review]
this PR makes sense to me, although i would like @pooyan-dadu vand to approve it.

i also would like to ask you  to test that the error is actually being issued

**Comment by philbucher** [comment]
It is being raised, thats why I had to adjust two tests

I will add a c-test for it

**Comment by philbucher** [comment]
@pooyan-dadvand I added the tests for the additions I do in this PR

I also added tests for some more functions

**Comment by philbucher** [comment]
@maceligueta there are some errors in the DEM-tests due to this PR
Should I try to fix those or do you want to do it yourself?

**Comment by maceligueta** [comment]
I can't fix it during the morning, if there's rush you can do it. I am curious about it because we barely use the dofs...

**Comment by philbucher** [comment]
There is not really a rush
If its ok then you can do it when you have time

**Comment by maceligueta** [comment]
I fixed the problem. Should I push to this branch?

**Comment by philbucher** [comment]
Thx @maceligueta

**Comment by philbucher** [comment]
ping @pooyan-dadvand

**Review by pooyan-dadvand — COMMENTED** [review]
I like the idea but it is not a good idea to throw an error in constructor, it would be better to have it somewhere else if is possible. Also I would put it as a debug error not in release

**Comment by philbucher** [comment]
@pooyan-dadvand why is it not a good idea to throw in the constructor?
I looked through the file but I didn't find a better place for it

e.g. Dof doesn't have a `Check` function

Now I am still throwing in the constructor, but only in debug

**Comment by pooyan-dadvand** [comment]
The reason is that the state of the object is undefined after sending an exception in constructor and this causes memory leak. In our case that error make a exit this is not a big problem. BTW, if it is the only place to do something that can go wrong throwing an exception is the best option as described [here](https://isocpp.org/wiki/faq/exceptions#ctor-exceptions). Also exception handling in constructor has a performance overhead but I cannot quantify it for our case.

**Comment by philbucher** [comment]
Thanks for the explanation!

The check is now only done in debug, do you still think there will be a performance overhead?
If it does throw the execution is terminated so in this case I guess the overhead does not really matter

**Comment by pooyan-dadvand** [comment]
It is ok now. In fact an optimization would be to add noexcept in release mode but I'm not sure about how much it may improve the current one. so leave it as it is.

**Comment by philbucher** [comment]
ok

can I get an approval then? :)

**Comment by philbucher** [comment]
ping @pooyan-dadvand

**Comment by philbucher** [comment]
ping @pooyan-dadvand

**Comment by philbucher** [comment]
ping @pooyan-dadvand

**Review by pooyan-dadvand — APPROVED** [review]
👍 

Sorry for delay...

**Comment by philbucher** [comment]
thx!

**Pull request merged**
