### PR TITLE
Fix history

### PR DESCRIPTION
**Pull request by roigcarlo**
This is an ongoing attempt to restore the disruption in history during c5f57ba38c9d7d6d0086d159394534b76dd3fec7

### CODE REVIEW

**Comment by josep-m-carbonell** [comment]
Hey @roigcarlo, I see that you are trying to solve something I broke accidentally. I was doing some trials in a fork to perform a sparse-checkoutd and something wrong happened. The master branch was renamed when the sparse checkout. But it was not a new branch, it was pointing to the master. . So I had master and sparse-master locally but the sparse-master was in fact the master. I wanted to push the sparse-master to a fork but I made a mistake to the upstream repository it was pointing. The push modified the master. The thing was that the master was not protected for administrators in github. .I have tryed to recover everything but I destroyed the history. I am sorry. I have included the protection of merge to the master for administrators after this unfortunate event.

**Comment by pooyan-dadvand** [comment]
@josep-m-carbonell, thanks for your explanation. Fortunately Git gives different possibilities to deal with this kind of problems. Nevertheless, a notification just after the accident would reduce the effort to recover everything. 

This branch is an attempt to restore the history of these files again. However we should check if active branches should do rebase or not after this merge. So as @roigcarlo mentioned please do not merge it yet.

**Comment by josep-m-carbonell** [comment]
I apologise for that. There was a lot of activity and merges these days. I hope it can be restored. I will not do merge don't worry.

**Comment by roigcarlo** [comment]
@KratosMultiphysics/team-maintainers  we will proceed to merge this, It is a dangerous PR as it changes the history of the master so problems are expected to happen.

The most common problem will be that your branch is "out of synch". Probability of this increases if your branch is very old or was made between certain commits. Please do not try to fix it by yourself If this happens please just contact with me (roigcarlo@gmail.com or @roigcarlo) and I'll help you fix it back.

**Review by pooyan-dadvand — APPROVED** [review]
:+1:

**Comment by loumalouomega** [comment]
imagen

**Comment by jcotela** [comment]
@roigcarlo When should we expect potential problems? On merging the master onto our branches or on PR?

**Comment by jcotela** [comment]
Also, thanks @roigcarlo for solving this issue. :+1:

**Pull request merged**
