### PR TITLE
Adding sum to amatrix interface

### PR DESCRIPTION
**Pull request by pooyan-dadvand**
Adding sum operator to the AMatrix interface with test

### CODE REVIEW

**Comment by josep-m-carbonell** [comment]
Thank you Pooyan, I will try to compile and test it tomorrow morning.

**Comment by josep-m-carbonell** [comment]
I think it is ok , however the compilation is not successful, it seems it can not detect the method, it is using a Vector class of ublas instead of amatrix.:

/shell_cross_section.hpp: In member function ‘void Kratos::ShellCrossSection::Ply::SetUpIntegrationPoints(int)’:
/home/cpuigbo/Kratos/applications/SolidMechanicsApplication/custom_utilities/shell_cross_section.hpp:416:35: error: ‘sum’ was not declared in this scope
                           ip_w /= sum( ip_w );
                                   ^~~
/home/cpuigbo/Kratos/applications/SolidMechanicsApplication/custom_utilities/shell_cross_section.hpp:416:35: note: suggested alternative:
In file included from /usr/include/boost/numeric/ublas/matrix_expression.hpp:16:0,
                 from /usr/include/boost/numeric/ublas/io.hpp:19,
                 from /home/cpuigbo/Kratos/kratos/includes/ublas_interface.h:51,
                 from /home/cpuigbo/Kratos/kratos/geometries/geometry_data.h:22,
                 from /home/cpuigbo/Kratos/kratos/geometries/geometry.h:27,
                 from /home/cpuigbo/Kratos/kratos/geometries/line_2d_2.h:25,
                 from /home/cpuigbo/Kratos/kratos/geometries/triangle_2d_3.h:26,
                 from /home/cpuigbo/Kratos/applications/SolidMechanicsApplication/solid_mechanics_application.cpp:15:
/usr/include/boost/numeric/ublas/vector_expression.hpp:1587:5: note:   ‘boost::numeric::ublas::sum’
     sum (const vector_expression<E> &e) {

**Comment by josep-m-carbonell** [comment]
Compiling... I merged the incorrect branch, there are too much branches.

**Comment by josep-m-carbonell** [comment]
It seems that the sum compiles.
Two other things appeared:
```
 inner_prod(Normal, prod(D,Normal))   produced:
/home/cpuigbo/Kratos/kratos/includes/amatrix_interface.h:571:59: error: no match for ‘operator[]’ (operand types are ‘const AMatrix::MatrixProductExpression<Kratos::Internals::Matrix<double, 0, 0>, Kratos::Internals::Matrix<double, 0, 1> >’ and ‘std::size_t {aka long unsigned int}’)
             result += the_expression1[i] * the_expression2[i];
                                            ~~~~~~~~~~~~~~~^
/home/cpuigbo/Kratos/kratos/includes/amatrix_interface.h: In instantiation of ‘void Kratos::Internals::Matrix<TDataType, TSize1, TSize2>::resize(std::size_t, std::size_t, bool) [with TDataType = double; long unsigned int TSize1 = 3; long unsigned int TSize2 = 3; std::size_t = long unsigned int]’:
/home/cpuigbo/Kratos/kratos/utilities/quaternion.h:224:13:   required from ‘void Kratos::Quaternion<T>::ToRotationMatrix(TMatrix3x3&) const [with TMatrix3x3 = Kratos::Internals::Matrix<double, 3, 3>; T = double]’
/home/cpuigbo/Kratos/applications/SolidMechanicsApplication/custom_utilities/shellq4_corotational_coordinate_transformation.hpp:211:27:   required from here
/home/cpuigbo/Kratos/kratos/includes/amatrix_interface.h:211:26: error: no matching function for call to ‘Kratos::Internals::Matrix<double, 3, 3>::resize(std::size_t&, std::size_t&)’
         base_type::resize(NewSize1,NewSize2);
```
Matrix needs the constructor and a copy constructor of these types:

```
Matrix A(IdentityMatrix(3));
Matrix A(3,2,0.0);
```
This two constructors are offering problems.

`range (as an method and as a type) , project  and  matrix_row (as a type) are missing and not compiling.
`
Compressed matrix in Builder and Solvers still need ublas.

**Review by josep-m-carbonell — APPROVED** [review]

**Comment by jcotela** [comment]
@josep-m-carbonell The `resize` and `matrix_row` issues are addressed on [the wiki](https://github.com/KratosMultiphysics/Kratos/wiki/Porting-to-AMatrix).

Regarding this:

> Matrix A(IdentityMatrix(3));
> Matrix A(3,2,0.0);

The first one works for me (I am testing it on the core/add_aliasing_check_to_amatrix branch, so maybe this branch is different, but at least we know it will work eventually). The second one should be replaced by `Matrix A(ScalarMatrix(3,2,0.0));`.

I confirm that I could reproduce this one:
```
 inner_prod(Normal, prod(D,Normal))   produced:
/home/cpuigbo/Kratos/kratos/includes/amatrix_interface.h:571:59: error: no match for ‘operator[]’ (operand types are ‘const AMatrix::MatrixProductExpression<Kratos::Internals::Matrix<double, 0, 0>, Kratos::Internals::Matrix<double, 0, 1> >’ and ‘std::size_t {aka long unsigned int}’)
             result += the_expression1[i] * the_expression2[i];
```

The compressed matrix is not in amatrix, so the plan is to keep using the ublas one for the time being. I cannot comment on `range` or `project`, I am not familiar with those.

**Comment by josep-m-carbonell** [comment]
@jcotela  the problem here  
`Matrix A(IdentityMatrix(3));`
Is that is not doing it well, it complains later with the size of A when you operates with it.

About row_matrix, the problem is that in some places it uses it as a type:
`typedef matrix_row< const MatrixType > ConstMatrixRowType;`
How we must replace this?

**Comment by jcotela** [comment]
The type of `row` is `AMatrix::MatrixRow<TExpressionType>`, so I guess it would be `typedef AMatrix::MatrixRow<const MatrixType>` in your case. @pooyan-dadvand It would probably make sense to declare a kratos "alias" for that type in amatrix_interface.

I'd say that the issue with the IdentityMatrix is a bug. Could you provide an example of what you got to help debug it?

**Comment by pooyan-dadvand** [comment]
I see, I will merge this one and add the alias for matrix row in another branch

**Comment by pooyan-dadvand** [comment]
@josep-m-carbonell The problem with the `operator []` is a difficult one... With current design of AMatrix we can not handle this expression efficiently.... (I can explain it with detail when we meet) 

So I would suggest you to use a temporary vector for these cases:
```c++
 inner_prod(Normal, BoundedVector<double, 3>(prod(D,Normal)))
```

**Pull request merged**
