### PR TITLE
[Core] move linear constraint to Constraints folder

### PR DESCRIPTION
**Pull request by philbucher**
previously the `constraints` folder did not exist, now it does

@adityaghantasala is there a reason the `LinearMasterSlaveConstraint` is not separated into header/source?

### CODE REVIEW

**Comment by adityaghantasala** [comment]
Thanks for that ... In principle it looks fine .   I will just check the includes again and will approve this ..  !

**Comment by adityaghantasala** [comment]
There is no reason as I remember ... Jut that constraints folder is created recently and we did not move it when its created ... !

**Review by adityaghantasala — APPROVED** [review]
All good ... carry on !

**Comment by philbucher** [comment]
thx

**Pull request merged**
