### PR TITLE
[Core] Moving integration_values_extrapolation_to_nodes_process to the core

### LINKED ISSUE #4527: vtk output for nodal data
I want to output stress to vtk results, such as VON_MISES_STRESS or CAUCHY_STRESS_TENSOR. should i set the variable in parameter element_data_value_variables?  i have tried, but got nothing

### PR DESCRIPTION
**Pull request by loumalouomega**
Fixes #4527

Ping @AlejandroCornejo, I think you use it right now

### CODE REVIEW

**Review by philbucher — DISMISSED** [review]
Thanks

**Comment by adityaghantasala** [comment]
Nice ... Can we also add a test for this process !?

**Comment by adityaghantasala** [comment]
Sorry my bad there is already a test ... 
Thank you ...

**Comment by philbucher** [comment]
appveyor fails

**Comment by AlejandroCornejo** [comment]
apart from being moved to the core it is the same right? as far as i can see

**Comment by adityaghantasala** [comment]
@loumalouomega  there are a still MeshingApplication references in comments and text in the header file. 
Also you are using KRATOS_API(MESHING_APPLICATION) in the class definition .. probably this is the reason why appveyor is failing !

**Comment by loumalouomega** [comment]
> @loumalouomega there are a still MeshingApplication references in comments and text in the header file.
> Also you are using KRATOS_API(MESHING_APPLICATION) in the class definition .. probably this is the reason why appveyor is failing !

Solved

**Comment by loumalouomega** [comment]
> apart from being moved to the core it is the same right? as far as i can see

Yes

**Comment by loumalouomega** [comment]
Any approval please?

**Review by AlejandroCornejo — APPROVED** [review]

**Pull request merged**
