### PR TITLE
[DEM] Clean constitutive laws

### PR DESCRIPTION
**Pull request by farrufat-cimne**
**📝 Description**
Functions in the base DiscontinuumLaw now return error if called. Derived ones must be used.
Functions in the base ContinuumLaw now return error if called. Derived ones must be used.

Also removed all functions and variables related with the deprecated automatic timestep calculation (the functions were deprecated and the stiffness variables being used were not dependent on the selected law).

### CODE REVIEW

**Comment by maceligueta** [comment]
@KlausBSautter . Since your tests are not in the CI, can you please try them with this branch? (no rush)

**Comment by farrufat-cimne** [comment]
Sorry, something went rlly bad in one of the lasts pushes. 
I'll fix it and reopen the PR

**Comment by farrufat-cimne** [comment]
Fixed. Sorry for the inconvenience.

Importing DEMApplication...  done.
...................................
----------------------------------------------------------------------
Ran 35 tests in 8.967s

OK

**Review by maceligueta — APPROVED** [review]
Approving. Let's hope @KlausBSautter will not have problems this time...

**Comment by KlausBSautter** [comment]
checking it right now. thanks for the hint @maceligueta

**Comment by KlausBSautter** [comment]
ok, it works, thanks :)

**Pull request merged**
