### PR TITLE
[Core] [Important Change] Unifying variables with components

### PR DESCRIPTION
**Pull request by pooyan-dadvand**
@KratosMultiphysics/all 

This PR converts the `VariablesComponent` of a variable to a `Variable`. This means that from now on, `DISPLACEMENT_X` would be `Variable<double>` instead of being `VariableComponent<VectorComponentAdaptor<array_1d<double, 3> > >` The idea is to reduce the huge amount of code duplications and templates which are everywhere in our codes and have the same implementation everywhere for a `Variable<double>` regardless to if is a component or not. 

This PR adds the following methods to the `VariableData` and `Variable` which are accessible from the python:

- `IsComponent()` : true or false
- `GetComponentIndex()`: 0 base index
- `GetSourceVariable()`: returns the *this for normal variables and the source for a component 

Of course, many parts of the code should be updated to accommodate this change. The main change would be replacing `VariableComponent<VectorComponentAdaptor<array_1d<double, 3> > >`  `Variable<double>` 

I still need to clean up the core code and there are applications that should be updated. So I  make it a draft PR.

### CODE REVIEW

**Comment by pooyan-dadvand** [comment]
I would encourage all to revise their applications in this branch and update them to be compatible with these changes

**Comment by loumalouomega** [comment]
This PR could have simplified a lot #6420, hehe. I will check this PR and it influence carefully (but this will simplify my code a lot)

**Comment by pooyan-dadvand** [comment]
Now the tests for @KratosMultiphysics/structural-mechanics application and @KratosMultiphysics/fluid-dynamics applications are running on my machine

**Comment by pooyan-dadvand** [comment]
> This PR could have simplified a lot #6420, hehe. I will check this PR and it influence carefully (but this will simplify my code a lot)

You are right... I should have done this before

**Comment by philbucher** [comment]
can you merge master and solve the conflicts to trigger CI?

**Review by RiccardoRossi — COMMENTED** [review]
@KratosMultiphysics/all 

This is a large change, but will simplify massively our life.

we need everyone to  **create a PR based on this one and fixing own applications. Commits need to push to this branch AND NOT TO MASTER**

 the change is to
change

VariableComponent<VectorComponentAdaptor<array_1d<double, 3> > >  --> Variable<double>

unfortunately we cannot use automatic replacement, since we may have multiple methods which do the same but have a different implementation for VariableComponent and Variable<double>, so manual inspection is needed.

**Comment by loumalouomega** [comment]
I fixed the conflict from GitHub, it may be not compile, I will switch branch and check it out

**Comment by armingeiser** [comment]
No change necessary in `EigensolversApplication` and `ShapeOptimizationApplication`. FYI @oberbichler @dbaumgaertner

**Comment by joaquinirazabal** [comment]
DamApp and FreSurfaceApp are ok @djvicente @ipouplana @antonialarese

**Comment by ipouplana** [comment]
DemStructuresCoupling Application and Poromechanics Application are fixed.

**Comment by loumalouomega** [comment]
@RiccardoRossi mentioned to do independent PR for the apps

**Comment by rubenzorrilla** [comment]
No change is required in the `FSIApplication`.

**Comment by pooyan-dadvand** [comment]
Seems that now the build is passing!

**Comment by pooyan-dadvand** [comment]
Seems that now the build is passing!

**Comment by miguelmaso** [comment]
sorry, I pushed changes by mistake

**Comment by philbucher** [comment]
@sunethwarna can you please check this? I think some of your tests are failing too

**Comment by sunethwarna** [comment]
RANS and HDF5 is changed accordingly :)

**Comment by pooyan-dadvand** [comment]
@loumalouomega thanks for merging and resolving the conflicts!

**Comment by loumalouomega** [comment]
> @loumalouomega thanks for merging and resolving the conflicts!

:+1:

**Comment by philbucher** [comment]
@loumalouomega I think you wrote the (C++) test that is failing, can you have a look please?

**Comment by loumalouomega** [comment]
> @loumalouomega I think you wrote the (C++) test that is failing, can you have a look please?

Huuum, it is a very simple test that checks the clone operator, this is dangerous

**Comment by loumalouomega** [comment]
> @loumalouomega I think you wrote the (C++) test that is failing, can you have a look please?

I run the tests after merge the master and it worked. I don't know why is failing

**Comment by loumalouomega** [comment]
> > @loumalouomega I think you wrote the (C++) test that is failing, can you have a look please?
> 
> I run the tests after merge the master and it worked. I don't know why is failing

I added manually the initialize, probably with the recent changes the rest of the components are not initialized if one of them is initialized manually

**Comment by philbucher** [comment]
still fails in Win, don't get why:
~~~
Ran 995 of 996 test cases in 9.48512s. 1 failed:
    TestConstraintCloneOperator Failed with message: 
        Error: Check failed because p_clone_of_const->GetValue(VELOCITY_Z) = 16 is not near to 0.00 = 0 within the tolerance 2.22045e-16
in kratos/tests/cpp_tests/sources/test_constraint.cpp:60:Testing::TestConstraintCloneOperator::TestFunction
~~~

**Comment by philbucher** [comment]
ah I think it is the same error but in a different test
@loumalouomega is this so?

**Comment by adityaghantasala** [comment]
@philbucher  the master_slave_constraint.h is not yet changed to adapt. There is still a Kratos::VariableComponentType defined can this be a reason ?

**Comment by philbucher** [comment]
> @philbucher the master_slave_constraint.h is not yet changed to adapt. There is still a Kratos::VariableComponentType defined can this be a reason ?

idk
I guess @pooyan-dadvand can answer this better...

**Comment by loumalouomega** [comment]
> > @philbucher the master_slave_constraint.h is not yet changed to adapt. There is still a Kratos::VariableComponentType defined can this be a reason ?
> 
> idk
> I guess @pooyan-dadvand can answer this better...

Looks like the problem is that the variables are not initialized in all the components, when only one of the components is set. I was thinking how to solve this without adding a lot of additional checks or executions adding additional computational cost

**Comment by pooyan-dadvand** [comment]
> > @philbucher the master_slave_constraint.h is not yet changed to adapt. There is still a Kratos::VariableComponentType defined can this be a reason ?
> 
> idk
> I guess @pooyan-dadvand can answer this better...

Simply because I missed it. As changing all of them would give compilation problem I just tried to change the ones which give error in compile or tests. This won't be clean until we change all of them.

**Comment by pooyan-dadvand** [comment]
> > > @philbucher the master_slave_constraint.h is not yet changed to adapt. There is still a Kratos::VariableComponentType defined can this be a reason ?
> > 
> > 
> > idk
> > I guess @pooyan-dadvand can answer this better...
> 
> Looks like the problem is that the variables are not initialized in all the components, when only one of the components is set. I was thinking how to solve this without adding a lot of additional checks or executions adding additional computational cost

Thanks for the hint! Seems that I forgot to add this case to the data value container tests

**Comment by loumalouomega** [comment]
@pooyan-dadvand I may have a solution; i will push the changes. I could not find a more elegant way, as it is not possible to access a variable just from its key (that would be cool)

**Comment by philbucher** [comment]
@loumalouomega maybe better make a PR against this one if the changes need to be discussed

**Comment by loumalouomega** [comment]
> @loumalouomega maybe better make a PR against this one if the changes need to be discussed

:+1:

**Comment by loumalouomega** [comment]
> @loumalouomega maybe better make a PR against this one if the changes need to be discussed

See #6756

**Comment by pooyan-dadvand** [comment]
Seems that there is a segmentation fault in ShapeOptimizationApplication tests

**Comment by philbucher** [comment]
I am not sure if it in the tests, I think it happens when the app is being imported
Unfortunately the output is usually a bit messed up so I also cannot really tell

Strange

@pooyan-dadvand did you try the shapeoptapp locally?

**Comment by armingeiser** [comment]
I am not sure if it is the ShapeOpt...

Locally (compiled with gcc) i get a segfault in 3/20 runs of 
```
python run_tests.py -a StructuralMechanicsApplication -l small
```


however no segfault (at least in 20 runs) with the same command above but for (KratosCore, ShapeOptimization, ConvectionDiffusion, EigenSolvers or MeshMoving) - always using only one application.

**Comment by philbucher** [comment]
@armingeiser 
- did you pull the latest changes of @pooyan-dadvand ?
- can you say which test fails?

**Comment by armingeiser** [comment]
>     * did you pull the latest changes of @pooyan-dadvand ?

Yes on commit cd31b75 

>     * can you say which test fails?

unfortunately not

**Comment by loumalouomega** [comment]
I need to fix the compilation, sorry

**Comment by loumalouomega** [comment]
@pooyan-dadvand I don't know why tests are failing with clang, apparently everything is OK

**Comment by pooyan-dadvand** [comment]
> I am not sure if it in the tests, I think it happens when the app is being imported
> Unfortunately the output is usually a bit messed up so I also cannot really tell
> 
> Strange
> 
> @pooyan-dadvand did you try the shapeoptapp locally?

Yes and it works in my machine...

**Comment by armingeiser** [comment]
@philbucher @pooyan-dadvand I investigated a little more (pulled the latest changes):

I get the segfault locally when running 

```
applications/StructuralMechanicsApplication/tests$ python test_StructuralMechanicsApplication.py
```

also if only the cpp tests are running 

```python
if __name__ == '__main__':
    KratosMultiphysics.Logger.PrintInfo("Unittests", "\nRunning cpp unit tests ...")
    run_cpp_unit_tests.run()
    KratosMultiphysics.Logger.PrintInfo("Unittests", "Finished running cpp unit tests!")

   # all python tests are commented out
```

**Comment by philbucher** [comment]
@armingeiser can you please increase the tests-verbosity to see which test is crashing?

**Comment by armingeiser** [comment]
If the application is just imported, the segfault is not happening.
If only the (small) python tests are running without the cpp tests, it is also not happening.

So it has something to do with the cpp tests.

**Comment by armingeiser** [comment]
After running several times, `TestSPRErrorProcess1` is always the last one that succeeds before the segfault. 

In what order are they running? Is it possible to have an output at the start of each test?

**Comment by philbucher** [comment]
can you please post the output? I am a bit confused what is happening

**Comment by armingeiser** [comment]
```
python test_StructuralMechanicsApplication.py
 |  /           |
 ' /   __| _` | __|  _ \   __|
 . \  |   (   | |   (   |\__ \
_|\_\_|  \__,_|\__|\___/ ____/
           Multi-Physics 7.1.0-0eb481d079-Release
Compiled with OpenMP support.
Maximum OpenMP threads: 16.
Importing    KratosStructuralMechanicsApplication 
    KRATOS   ___|  |                   |                   |
           \___ \  __|  __| |   |  __| __| |   |  __| _` | |
                 | |   |    |   | (    |   |   | |   (   | |
           _____/ \__|_|   \__,_|\___|\__|\__,_|_|  \__,_|_| MECHANICS
Initializing KratosStructuralMechanicsApplication...
TestCalculateCharacteristicLength                                       OK.

TestCalculateElementLength                                              OK.

... several other tests ...

TestRuleOfMixturesConstitutiveLawTetrahedronTwoLayers                   OK.

TestSPRErrorProcess1                                                    OK.

Segmentation fault (core dumped)
```

**Comment by loumalouomega** [comment]
> ```
> python test_StructuralMechanicsApplication.py
>  |  /           |
>  ' /   __| _` | __|  _ \   __|
>  . \  |   (   | |   (   |\__ \
> _|\_\_|  \__,_|\__|\___/ ____/
>            Multi-Physics 7.1.0-0eb481d079-Release
> Compiled with OpenMP support.
> Maximum OpenMP threads: 16.
> Importing    KratosStructuralMechanicsApplication 
>     KRATOS   ___|  |                   |                   |
>            \___ \  __|  __| |   |  __| __| |   |  __| _` | |
>                  | |   |    |   | (    |   |   | |   (   | |
>            _____/ \__|_|   \__,_|\___|\__|\__,_|_|  \__,_|_| MECHANICS
> Initializing KratosStructuralMechanicsApplication...
> TestCalculateCharacteristicLength                                       OK.
> 
> TestCalculateElementLength                                              OK.
> 
> ... several other tests ...
> 
> TestRuleOfMixturesConstitutiveLawTetrahedronTwoLayers                   OK.
> 
> TestSPRErrorProcess1                                                    OK.
> 
> Segmentation fault (core dumped)
> ```

Ok, I assume the error is in the TestSPRErrorProcess2 (that's mine)

**Comment by loumalouomega** [comment]
> > ```
> > python test_StructuralMechanicsApplication.py
> >  |  /           |
> >  ' /   __| _` | __|  _ \   __|
> >  . \  |   (   | |   (   |\__ \
> > _|\_\_|  \__,_|\__|\___/ ____/
> >            Multi-Physics 7.1.0-0eb481d079-Release
> > Compiled with OpenMP support.
> > Maximum OpenMP threads: 16.
> > Importing    KratosStructuralMechanicsApplication 
> >     KRATOS   ___|  |                   |                   |
> >            \___ \  __|  __| |   |  __| __| |   |  __| _` | |
> >                  | |   |    |   | (    |   |   | |   (   | |
> >            _____/ \__|_|   \__,_|\___|\__|\__,_|_|  \__,_|_| MECHANICS
> > Initializing KratosStructuralMechanicsApplication...
> > TestCalculateCharacteristicLength                                       OK.
> > 
> > TestCalculateElementLength                                              OK.
> > 
> > ... several other tests ...
> > 
> > TestRuleOfMixturesConstitutiveLawTetrahedronTwoLayers                   OK.
> > 
> > TestSPRErrorProcess1                                                    OK.
> > 
> > Segmentation fault (core dumped)
> > ```
> 
> Ok, I assume the error is in the TestSPRErrorProcess2 (that's mine)

BTW, 16 threads, not bad

**Comment by philbucher** [comment]
yes `TestSPRErrorProcess2` is next in the tests

**Comment by philbucher** [comment]
@armingeiser can you run only this test to see if it crashes?

**Comment by armingeiser** [comment]
I think both, `TestSPRErrorProcess2` and `TestSPRErrorProcess1` have an issue, only if i deactivate them both, i get no segfault (at least with 50 runs)

**Comment by armingeiser** [comment]
> @armingeiser can you run only this test to see if it crashes?

How can i run a single cpp test?

**Comment by philbucher** [comment]
https://github.com/KratosMultiphysics/Kratos/wiki/How-to-create-unitary-tests#how-to-run-tests-1

**Comment by armingeiser** [comment]
Yes i get a segfault also when running them individually. (TestSPRErrorProcess1 fails less often then TestSPRErrorProcess2)

**Comment by philbucher** [comment]
thanks @armingeiser

**Comment by pooyan-dadvand** [comment]
@loumalouomega would you please take a look at those tests?

**Comment by loumalouomega** [comment]
"Solved" @pooyan-dadvand the things failing were solved in the master in a independent PR :)

**Comment by philbucher** [comment]
hm indeed the tests are passing now
thx @loumalouomega

**Comment by loumalouomega** [comment]
> hm indeed the tests are passing now
> thx @loumalouomega

(When I refactor conditions in the contact I discover that I was still using some variables without reference or pointer :P, I fixed sneakily)

**Comment by pooyan-dadvand** [comment]
Thanks, to @loumalouomega for the last fix and to all for adapting the codes.

**Comment by pooyan-dadvand** [comment]
@KratosMultiphysics/all  We would merge this PR on the beginning of the next week. Please consider revising your applications before it merges.

**Review by rubenzorrilla — APPROVED** [review]

**Pull request merged**
