### PR TITLE
Added a missing KratosMultiphysics

### PR DESCRIPTION
**Pull request by jcotela**
Fix for a small bug in trilinos_restart_utility.py

### CODE REVIEW

**Review by philbucher — APPROVED** [review]
Thx @jcotela I missed this

**Comment by RiccardoRossi** [comment]
hi, merge the bugfix now if we need. We would like to make the release branch in a question of minutes

**Comment by jcotela** [comment]
I don't think this is used (yet) from the current interface? Only the new main scripts (structure and fluid) use it, but they are not merged as of now (and the fluid one won't be yet). However, if you want to merge, do it yourself, I'm not authorized to skip travis.

**Comment by philbucher** [comment]
For me it is also not necessary since not used yet in the interface

**Comment by RiccardoRossi** [comment]
I will not skip travis

in any case if it is not needed then best not merge it before the release

**Comment by pooyan-dadvand** [comment]
I have merged it before release branch. But I wasn't sure to delete the branch.

**Comment by jcotela** [comment]
It is fine to delete it

**Pull request merged**
