### PR TITLE
[MeshingApp] cmake modifications

### PR DESCRIPTION
**Pull request by mohittyagi-k**
**Description**

To avoid failure on Altair side.

@loumalouomega @philbucher @roigcarlo @ddiezrod @KratosMultiphysics/altair

### CODE REVIEW

**Review by philbucher — APPROVED** [review]
looks good to me, consistent with other apps

Can you also please check if the [application template](https://github.com/KratosMultiphysics/Kratos/tree/master/kratos/templates/template_application) is up to date for your purposes?
Thx!

**Comment by mohittyagi-k** [comment]
> Can you also please check if the [application template](https://github.com/KratosMultiphysics/Kratos/tree/master/kratos/templates/template_application) is up to date for your purposes?

Probably it would be good to replace `CMAKE_SOURCE_DIR` with  `KRATOS_SOURCE_DIR` 
https://github.com/KratosMultiphysics/Kratos/blob/eea65e7eb00d2a6421d91f81a9cf743af931b9e8/kratos/templates/template_application/CMakeLists.txt.in#L8

**Comment by philbucher** [comment]
could you make a PR please? Thx a lot

**Review by roigcarlo — APPROVED** [review]
:+1: Actually all `${CMAKE_SOURCE_DIR}` should be changed to `${KRATOS_SOURCE_DIR}` in our side too. 

Thx

**Comment by philbucher** [comment]
> +1 Actually all `${CMAKE_SOURCE_DIR}` should be changed to `${KRATOS_SOURCE_DIR}` in our side too.
> 
> Thx

like in all the apps you mean?

**Comment by roigcarlo** [comment]
Yep

**Comment by mohittyagi-k** [comment]
@roigcarlo @philbucher I have made the change in CMake files. Please have a look https://github.com/KratosMultiphysics/Kratos/pull/7707

**Pull request merged**
