### PR TITLE
[ContactStructuralMechanicsApplication] Transition PR. Removing wrapper

### PR DESCRIPTION
**Pull request by loumalouomega**
Next step will be to remove duplicated analysis

### CODE REVIEW

**Review by AlejandroCornejo — APPROVED** [review]

**Comment by loumalouomega** [comment]
BTW @AlejandroCornejo the missing change I mentioned the other day is already merged, feel free to experiment with the frictional contact

**Review by philbucher — COMMENTED** [review]
:+1:

**Comment by loumalouomega** [comment]
@philbucher now that we use the pythonic structure, should we move the file to folders to be more ordered?, like moving the solvers to the same folder

**Comment by philbucher** [comment]
That is a very good question, I would say yes (in fact I do it already in the cosim app)
But I don’t know how ...
Also we should not break too many things
I would propose to put the solvers, the trilinos solvers and the processes into separate subfolders
As a first step
What do you think?

**Comment by loumalouomega** [comment]
I agree, one thing, I started a new job this Monday, so my availability will be considerably reduced

**Comment by philbucher** [comment]
I know
Congrats btw, you made it out :)

**Pull request merged**
