### PR TITLE
[StructuralMechanicsApplication] Fixing lack of mass transfer on explicit MPC

### PR DESCRIPTION
**Pull request by loumalouomega**
This PR adds the mass transfer of explicit MPC. In a future Steiner contribution should be added. Fix recent test failing

### CODE REVIEW

**Comment by loumalouomega** [comment]
Ping

**Comment by KlausBSautter** [comment]
I am checking it right now

**Comment by loumalouomega** [comment]
> I am checking it right now

:)

**Review by KlausBSautter — APPROVED** [review]

**Comment by KlausBSautter** [comment]
ok from my side

**Pull request merged**
