### PR TITLE
[Core][MPI] Support for STL output operations in MPI

### PR DESCRIPTION
**Pull request by loumalouomega**
**📝 Description**

This PR introduces MPI support for STL output operations. It also improves documentation. It adds the corresponding test.

**🆕 Changelog**

- [Adding doc](https://github.com/KratosMultiphysics/Kratos/commit/12b7249dd59ddb706362da27ddb45d60e7b0f590)
- [MPI support for output](https://github.com/KratosMultiphysics/Kratos/commit/b06d93ca923ceabed5d3580bb70d066b64fb7bd1)
- [Adding STLIO tests in python (SMP/MPI)](https://github.com/KratosMultiphysics/Kratos/commit/9b57724719af1cdc8108ced788cf350bfbb944bc)

### CODE REVIEW

**Comment by loumalouomega** [comment]
@roigcarlo I cannot replicate the error in Windows Ci, apparently I am trying to write in a protected folder

**Comment by philbucher** [comment]
really curious what the problem could be

do you have any idea?

**Comment by loumalouomega** [comment]
> really curious what the problem could be
> 
> do you have any idea?

No idea, but I "fixed it" using tempfile module in python.  A priori looks like writting has been blocked for some reason

**Comment by loumalouomega** [comment]
815jp8

**Review by ddiezrod — APPROVED** [review]
This looks fine to me ;)

**Pull request merged**
