### PR TITLE
[Fluid] Fixed Fulldebug error in compressible symbolic tests

### PR DESCRIPTION
**Pull request by EduardGomezEscandell**
**📝 Description**
Matrices were intialized with size `(block_size, num_nodes)` when they should have been `(num_nodes, block_size)`. This initially remained silent but the error was caught in FullDebug.

Noticed by @marcnunezc [here](https://github.com/KratosMultiphysics/Kratos/pull/9687#issuecomment-1046660890).

**🆕 Changelog**
Fixed matrix initialization in tests.

### CODE REVIEW

**Comment by EduardGomezEscandell** [comment]
Nightly run:

https://github.com/KratosMultiphysics/Kratos/actions/runs/1875784598

**Comment by marcnunezc** [comment]
> Nightly run:
> 
> https://github.com/KratosMultiphysics/Kratos/actions/runs/1875784598

If I'm not mistaken, this run may fail (running out of time) as the tetrahedra test is still in the nightly suite. 

I already merged #9687, so you can merge master and run again the nightly to make sure it works.

**Comment by EduardGomezEscandell** [comment]
Nightly run, with master merged:

https://github.com/KratosMultiphysics/Kratos/actions/runs/1875859453

**Comment by EduardGomezEscandell** [comment]
Nightly build with latest changes:

https://github.com/KratosMultiphysics/Kratos/actions/runs/1877285329

**Review by marcnunezc — APPROVED** [review]

**Pull request merged**
