### PR TITLE
[Core] Updating the FindTRILINOS to accept static libraries

### PR DESCRIPTION
**Pull request by loumalouomega**
Without this change is not possible to consider ".a" when compiling Trilinos

### CODE REVIEW

**Comment by philbucher** [comment]
can you run in MPI with this then?

**Comment by loumalouomega** [comment]
Compiling...

**Review by RiccardoRossi — COMMENTED** [review]
with .a there are severe prpblems with the linking order...i would advise against using it

**Comment by loumalouomega** [comment]
Effectively, if I use self-cmpiled libraries I have the same error with Trilinos, If I compile with static libraries I have an error of compilation arriving to certain point for linking issues as @RiccardoRossi says.

**Comment by loumalouomega** [comment]
> with .a there are severe prpblems with the linking order...i would advise against using it

In any case this PR doesn't change current behavior. I am not able right now to compile it. Any suggestion? (I tried with self compiled shared libraries and the error persists)

**Comment by loumalouomega** [comment]
I close this until I found a definitve solution for the problem

**Pull request closed without merging**
