### PR TITLE
[Core][ConnectivityPreserveModeler] Adding error in case input is submodelpart

### PR DESCRIPTION
**Pull request by philbucher**
taken from #2417

### CODE REVIEW

**Comment by philbucher** [comment]
now it should work with the current master

**Comment by rubenzorrilla** [comment]
I have no objections, but I prefer @RiccardoRossi to do the final approve.

**Comment by philbucher** [comment]
ok thx
After all it was @RiccardoRossi that came up with this, I just made it a separate PR

**Review by RiccardoRossi — APPROVED** [review]

**Comment by pooyan-dadvand** [comment]
Why we need to make this error? This will break current usages... and is a valid operation to clone a sub modelpart.

**Comment by jrubiogonzalez** [comment]
We make use of this, we create a modelpart from a submodelpart, it is quite useful in some cases, like in FSI or in ours where we have different problem domains.

**Comment by philbucher** [comment]
@RiccardoRossi this was initiated by you, should we revert?

**Comment by RiccardoRossi** [comment]
@pooyan-dadvand i honestly believe it is not a safe operation to clone a submodelpart.

Nevertheless if you are using this in production and it works correctly than let's revert the error throwing

**Comment by pooyan-dadvand** [comment]
I would revert it for now and please provide me with an unsafe case to see how we can avoid it.

**Comment by RiccardoRossi** [comment]
@philbucher do you do the reverting?

@pooyan-dadvand i'll think about and post here

**Comment by RiccardoRossi** [comment]
as an example of unsafe stuff, a property may belong to a father modelpart but not to a submodelpart. It may however happen that an element in a submodelpart does require that property

**Comment by philbucher** [comment]
@RiccardoRossi I can do the reverting if you want, just give me a go

I think this discussion is not over yet, therefore let me know if I should revert

**Comment by RiccardoRossi** [comment]
@philbucher revert this for now (thx) so to avoid breaking stuff. Eventually we can add it again if we consider that it is better to reactivate it

**Comment by pooyan-dadvand** [comment]
Thanks guys!

**Pull request merged**
