### PR TITLE
[Core] GenericFindElementsNeighbours using Execute

### PR DESCRIPTION
**Pull request by rubenzorrilla**
**📝 Description**
The `GenericFindElementsNeighbours` process uses the `ExecuteInitialize` method instead of the `Execute` one, which is the one the other neighbor calculation processes are using. On top of being inconsistent, this is quite misleading for developers, as calling the `Execute` turns into do nothing as it is calling the base class empty implementation. This turns into a segfault when asking for the neighbors. Figuring this out might not be straightforward for newbies.

Besides, I also realized that the current implementation is not following the base `Process` public API as there is a `public` `HasNeighboursInFaces`. This is only used in the tests so we may remove it (asking @pablobecker since, as far as I understand, he implemented it in #9894). If it can't be removed, I think it should be moved to a separate class and be implemented as a `static` function. Note that this doesn't require anything from the process, but makes it mandatory to keep it alive to be called.

### CODE REVIEW

**Review by loumalouomega — APPROVED** [review]
Okay from my side, I see that ExecuteInitialize still works and throws a warning

**Comment by rubenzorrilla** [comment]
> Okay from my side, I see that ExecuteInitialize still works and throws a warning

Yes. We'd better keep it for a while. In any case I'll wait for @pablobecker 's answer about the `HasNeighboursInFaces`. If possible, I'd remove it in this PR.

**Comment by pablobecker** [comment]
Since the goal of the original PR was to directly replace the old process and that this is meant to be used a a tool by other processes, I thought it made more sense to compute the neighb at Initialize. But you're right that other neigh processes do the computation at Execute, so good for me to keep things consistent. Regarding the HasNeighboursInFaces function, why not make it an utility? it could be useful (for example I am checking faces with nullptr exactly for this reason in https://github.com/KratosMultiphysics/Kratos/pull/9949 )

**Comment by ddiezrod** [comment]
This goes further than the scope of this MR, but I am quite hesitant about the separation in processes that are called only in Execute and those that are called in ExecuteInitialize, InitializeSolStep etc. This one is a good example. It only does one thing so it would make sense to only implement Execute function, but also, it would make sense to be able to add it to the list of processes in case your solver/analysis does not call it ( I was in fact already doing this)

I think this is something that was discussed some time ago, but probably adding a list of "operations" in your ProjectParameters would fix this problem. This could be a list of processes which are called at the same moment as the ExecuteInitialize but they would only be called through Execute function,  I think that would be more clear.

**Comment by rubenzorrilla** [comment]
Here my two cents.

> Regarding the HasNeighboursInFaces function, why not make it an utility? it could be useful (for example I am checking faces with nullptr exactly for this reason in #9949 )

OK. Now I see why there are no usages yet (#9949 is still pending). My concern is that placing it inside a process is not the proper place. I think this is very suited to be either inside any of the current utilities in the Kratos core (not sure in which one)  or in a new one. Having said so, maybe we can do this in a standalone PR as we're changing many files in here.

> This goes further than the scope of this PR, but I am quite hesitant about the separation in processes that are called only in Execute and those that are called in ExecuteInitialize, InitializeSolStep etc. This one is a good example. It only does one thing so it would make sense to only implement Execute function, but also, it would make sense to be able to add it to the list of processes in case your solver/analysis does not call it ( I was in fact already doing this)

Absolutely agree. Indeed these kind of routines are a process because historical reasons. However, they are not a utility as you want to enforce an API. Not long ago we created the concept of `Operations` for the sake of multistage coupling, which only feature such `Execute` method. So these, are IMO an operation. The point is that refactoring everything at this point is most probably a worthless effort.

About the possibility of calling these kind of routines from the json process list, I tend to disagree. Such processes lists were conceived (mainly) for the initial and BCs impositions. Note that adding them in the json lists translates the logic to the GUI that writes those json files. Besides, processes like the one in this PR are normally crucial operations in your resolution procedure that are to be called once, so you want to keep them controlled and hidden inside the solver.

A different thing would be other kind of processes with many customizable settings (e.g. level set convection). I agree that your comment in this context makes much more sense. However, these are not the majority of the cases (I mean processes with many customizable settings that are not BC related or postprocessing).

> 
> I think this is something that was discussed some time ago, but probably adding a list of "operations" in your ProjectParameters would fix this problem. This could be a list of processes which are called at the same moment as the ExecuteInitialize but they would only be called through Execute function, I think that would be more clear.

While it is technically possible, this would add extra complexity to our execution, which is a bit complex right now (I'm posting the complaints and feedback from some newcomers). Hence, I'd only add this if there is a technical limitation that impedes achieving the same with current capabilities.

**Comment by ddiezrod** [comment]
Ok  @rubenzorrilla I see you point and also makes sense. Anyway, I do not want to move the internal logics of the solver to the GUI. I was thinking more in very specific cases like benchmarks or validations where you need to do an operation that you would not do in a "standard" run. You might end up at the end adding more things to the solver to be able to run the problem, when they are not needed usually and might be quite heavy (as neighbors elements are), or even worse, you just cannot run your validation because the solver/analysis cannot be changed at that point.

**Comment by rubenzorrilla** [comment]
> Ok @rubenzorrilla I see you point and also makes sense. Anyway, I do not want to move the internal logics of the solver to the GUI. I was thinking more in very specific cases like benchmarks or validations where you need to do an operation that you would not do in a "standard" run. You might end up at the end adding more things to the solver to be able to run the problem, when they are not needed usually and might be quite heavy (as neighbors elements are), or even worse, you just cannot run your validation because the solver/analysis cannot be changed at that point.

Yes... sometimes it would be nice to have a bit more of flexibility while developing or testing, but I think that we'll need to live with that... :disappointed:

**Comment by rubenzorrilla** [comment]
I think we discussed all the concerns so I'll merge this to start the PR with the modifications related to the `HasNeighboursInFaces`. Besides, this is blocking #10096.

**Pull request merged**
