### PR TITLE
Feature dam release 5.3

### PR DESCRIPTION
**Pull request by djvicente**
Some changes need to be introduced in the Release 5.3. These changes are related to two topics:
- Delete references to 'mesh_id' parameter
- Modify impose water temperature process to fix some bugs

### CODE REVIEW

**Comment by joaquinirazabal** [comment]
I run some benchmark cases and everything works properly.

**Review by roigcarlo — APPROVED** [review]
Ok to me. Did not run any benchmark but it compiles. @jginternational tells me that this is also part of a GiD interface change so I will asume de deletion of `mesh_id` is reflected there as well.

I will feel more confident if someone else approves this as well

**Review by ipouplana — APPROVED** [review]
I approve this PR too ;)

**Comment by roigcarlo** [comment]
I will update the release tomorrow then 👍

**Comment by djvicente** [comment]
Hi @roigcarlo!
Thank you for your comments and for your quick response. Indeed, mesh_id has been removed from the interface. Other minor changes were included to fix a bug.
Regards,

**Comment by jginternational** [comment]
@roigcarlo @djvicente mesh_id was removed last week

KratosMultiphysics/GiDInterface#187
KratosMultiphysics/GiDInterface#288

**Pull request merged**
