### PR TITLE
[CLA] Solving nightly tests and reimplementing Finite Strain Isotropic and Kinematic plasticity (Again)

### PR DESCRIPTION
**Pull request by AlejandroCornejo**
**Description**
In this PR I'm revisiting the finite strain plasticity, performing a **more simple and reusable implementation**. Now it is not based on a multiplicative split of F but on the calculation of the logarithmic Hencky strain. **This allows the use of the small strain return mapping**. The finite strain plasticity integrators have been **removed** (unused now).

This PR also updates the nightly test (now passing)

### CODE REVIEW

**Review by loumalouomega — CHANGES_REQUESTED** [review]
Huuum, I need to process this. The question, with this we lose the hyperelastic predictor?

**Comment by loumalouomega** [comment]
> Huuum, I need to process this. The question, with this we lose the hyperelastic predictor?

I am sad of removing so many hours of work. I don't know, can we move it as laws not compiled by default?

**Comment by AlejandroCornejo** [comment]
> 
> 
> Huuum, I need to process this. The question, with this we lose the hyperelastic predictor?

Because now it is not required... We take advantage of the Hencky hiperelastic CL to do the prediction :) please, see:

imagen

**Comment by loumalouomega** [comment]
> > Huuum, I need to process this. The question, with this we lose the hyperelastic predictor?
> 
> Because now it is not required... We take advantage of the Hencky hiperelastic CL to do the prediction :) please, see:
> 
> imagen

True, but then the prediction is always linear elasticity?

**Comment by AlejandroCornejo** [comment]
Not exactly, the rpediction is done by means of the Hencky hiper law, which is, as you say, a linear relationshipt between the log strain and the kirchoff stress

**Comment by loumalouomega** [comment]
> Not exactly, the rpediction is done by means of the Hencky hiper law, which is, as you say, a linear relationshipt between the log strain and the kirchoff stress

Yes, but what I meant is that you cannot choose any specific hyperelastic behaviour. Well, the thing is that I am Ok, but I feel bad for removing all the previous work, and we may preserve it in some manner

**Comment by AlejandroCornejo** [comment]
Yes! I understand Vicente, let's see more opinions and we decide to maintain what's now there or not :)

**Comment by AlejandroCornejo** [comment]
BTW:

imagen

**Comment by AlejandroCornejo** [comment]
I'll solve the checks, what do you guys think about maintaining the old finite strain laws? @RiccardoRossi @philbucher

**Comment by AlejandroCornejo** [comment]
> 
> 
> Yes! I understand Vicente, let's see more opinions and we decide to maintain what's now there or not :)

Guys! the faster we decide the sooner the nightly build will be passing!! :)

**Comment by philbucher** [comment]
> > Yes! I understand Vicente, let's see more opinions and we decide to maintain what's now there or not :)
> 
> Guys! the faster we decide the sooner the nightly build will be passing!! :)

I agree
If it works and passes the tests then I would merge as is
Updates can then always be done later!

**Review by philbucher — APPROVED** [review]

**Comment by philbucher** [comment]
> I'll solve the checks, what do you guys think about maintaining the old finite strain laws? @RiccardoRossi @philbucher

Hm not sure, not an expert in this area

**Comment by philbucher** [comment]
I mean if you have the same capabilities then I guess you can eventually remove them I would say

**Comment by philbucher** [comment]
ping @loumalouomega

**Comment by loumalouomega** [comment]
> ping @loumalouomega 

Are we going to preserve old implementation in some sort of manner?

**Comment by philbucher** [comment]
> > ping @loumalouomega
> 
> Are we going to preserve old implementation in some sort of manner?

if unused I would remove

**Comment by loumalouomega** [comment]
> > > ping @loumalouomega
> > 
> > Are we going to preserve old implementation in some sort of manner?
> 
> if unused I would remove

I would keep, as it holds a lot of work, and it is a different implementation with a different theory behind. We are discarding because a test I created previously, which it worked until a warning was replaced with an error.

**Comment by philbucher** [comment]
I don't have a strong opinion

I would strongly prefer through to have the nightly tests pass and to clarify/fix the issue you address in future PRs

**Comment by loumalouomega** [comment]
OK, let me do a backup and then I'll agree to merge this (I am not
currently at home)

**Comment by philbucher** [comment]
> OK, let me do a backup

you understand how git works don't you :D

**Comment by loumalouomega** [comment]
Yes, but I want to do a branch with the proper changes...

**Comment by RiccardoRossi** [comment]
if they work or they can be fixed with relatively little effort i wpuld
also keep
..

**Review by loumalouomega — APPROVED** [review]

**Pull request merged**
