### PR TITLE
Adding missing geometries to python

### PR DESCRIPTION
**Pull request by loumalouomega**
Some geometries are not compiling. Besides, there is any way to pass a python list of nodes instead of all the nodes one by one?

### CODE REVIEW

**Comment by RiccardoRossi** [comment]
@loumalouomega  it looks good to me. approving... however it has conflicts

**Comment by loumalouomega** [comment]
This is strange, I cherrypick from the branch, so the conflict is supposed to be solved automatically

**Comment by loumalouomega** [comment]
I was that I added in a different order, sorry

**Comment by pooyan-dadvand** [comment]
OK for me but appveyor is complaining.

**Comment by roigcarlo** [comment]
@pooyan-dadvand Time limit as always. It is failing like 90% of the PR...

**Review by RiccardoRossi — APPROVED** [review]

**Pull request merged**
