### PR TITLE
[Core] Using critical to remove tree reduction in construct matrix structure

### PR DESCRIPTION
**Pull request by RiccardoRossi**
@roigcarlo @pooyan-dadvand this branch implements the change to the ConstructMatrixStructure we discusses with Jesus.

@roigcarlo could u profile that? the only differene should be in the initial construction. It may be worth to try it with the google dense hash if we want to check the maximum performance

### CODE REVIEW

**Comment by pooyan-dadvand** [comment]
Much simpler! I would keep it unless it reduces the performance considerably. @RiccardoRossi do you have a time comparison between them?

**Comment by RiccardoRossi** [comment]
triaged, to be merged after  5.3

**Comment by RiccardoRossi** [comment]
Code is cleaner and faster, at least when using many cores, so i would suggest merging this.

Nevertheless, It would be good if someone could try this in windows as well as to battle test it a little since it is a routine used by everyone

**Comment by RiccardoRossi** [comment]
@pooyan-dadvand, @roigcarlo has all the time comparisons. Carlos, maybe you could post a snapshot of the profiling you did for POP

**Comment by RiccardoRossi** [comment]
@roigcarlo ping :-D

**Review by roigcarlo — DISMISSED** [review]
Sorry I though I already approved it.

**Comment by philbucher** [comment]
is this still active?
the branch is stale for over 3 months

**Comment by RiccardoRossi** [comment]
It would be worth to refresh it. System construction was sensibly faster on many processors when this technique was employed. also code was faster

**Comment by pooyan-dadvand** [comment]
I would say for the next release

**Comment by pooyan-dadvand** [comment]
I have add a after release label to keep track of such postponed PRs

**Comment by philbucher** [comment]
ping

**Comment by pooyan-dadvand** [comment]
I think this conflict needs @RiccardoRossi attention

**Comment by loumalouomega** [comment]
Two things

- This PR right now has a conflict
- It enters in conflict with #3245

**Comment by pooyan-dadvand** [comment]
IMO this is more important that #3245 

I would first go for this one.

**Comment by philbucher** [comment]
what is the status of this?

**Comment by loumalouomega** [comment]
> what is the status of this?

¯\_(ツ)_/¯

**Review by pooyan-dadvand — APPROVED** [review]
Approving after so many time in queue!

**Comment by philbucher** [comment]
whoever merges this could you please merge master and run the tests locally before merging?

**Comment by philbucher** [comment]
guess this won't make it to the release after the major update of the B&S ...

**Comment by RiccardoRossi** [comment]
This was included in the updated builder and solver. I am closing this

**Pull request closed without merging**
