### PR TITLE
mpi-python can be compiled without metis if wanted

### PR DESCRIPTION
**Pull request by maceligueta**
The pre-existing variable MPI_NEEDED can be set to ON in the configure.

### CODE REVIEW

**Comment by philbucher** [comment]
So now we can compile with MPI without having to compile Trilinos and Metis?

**Review by jcotela — DISMISSED** [review]
:+1: This will work, but I believe that just removing the old line always setting `MPI_NEEDED` to OFF would achieve the same effect.

**Review by roigcarlo — DISMISSED** [review]

**Comment by maceligueta** [comment]
@philbucher  I found this feature necessary for those cases where you don't really need to solve linear systems in MPI. In my case I just needed to run several equal processes which share the inputs, compute slightly different equations and gather the results. If you need to solve a system you can't dodge Trilinos. 
@jcotela : you are right, I will modify it.

**Comment by RiccardoRossi** [comment]
this looks correct to me

**Review by RiccardoRossi — APPROVED** [review]

**Pull request merged**
