### PR TITLE
[MeshingApplication] Hotfix deprecated ModelPart constructor

### PR DESCRIPTION
**Pull request by loumalouomega**
Fixes https://github.com/KratosMultiphysics/Kratos/issues/4336

### CODE REVIEW

**Comment by loumalouomega** [comment]
@juliobarna can you check it works?

**Comment by loumalouomega** [comment]
@juliobarna Maybe the error is repeated in other files, feel free to fix them too. As you can see it is easy, you call to the Model from the model part, create the auxiliar model part, and remove it once you are done (otherwise it will be alive on memory)

**Comment by philbucher** [comment]
the model-part constructor was removed in #3835

**Review by juliobarna — APPROVED** [review]
including "includes/legacy_structural_app_vars.h" for the variable IS_CONTACT_MASTER.

**Pull request merged**
