### PR TITLE
The path for the clusters clu was not correctly set

### PR DESCRIPTION
**Pull request by salvalatorre**

### CODE REVIEW

**Comment by joaquinirazabal** [comment]
I thought that line (os.chdir('..')) was removed because if it is there benchmarks don't work. Now, I run benchmarks and they work correctly with this change. For me is ok!

**Comment by salvalatorre** [comment]
If you think that's OK then I need your approval to proceed ;)

**Review by joaquinirazabal — APPROVED** [review]

**Comment by maceligueta** [comment]
Hi! I am against using os.chdir so frequently. It has proven to be very prone to errors. If the problem is reading a file called 'whatever.clu', we should read the file '/full_path_to_whatever/whatever.clu' instead of changing the working path. @salvalatorre , can you do this and remove the last os.chdir you added?

**Comment by salvalatorre** [comment]
I only moved the already existing os.chdir. I didn't add any.

**Comment by maceligueta** [comment]
I see. We will remove those chdir later on. But it is a pending task.

**Comment by salvalatorre** [comment]
+1

**Pull request merged**
