### PR TITLE
[Core][Fix] Set all components when setting one of them

### PR DESCRIPTION
**Pull request by loumalouomega**
This is not the most elegant way, but I don't know how to find a variable using only its key

### CODE REVIEW

**Comment by loumalouomega** [comment]
> This is not the most elegant way, but I don't know how to find a variable using only its key

Fix issues in #6686

**Comment by loumalouomega** [comment]
As this just adds a test I will directly merge

**Comment by pooyan-dadvand** [comment]
You should have wait for some aproval.....
I fixed it in the main branch....

**Comment by loumalouomega** [comment]
> You should have wait for some aproval.....
> I fixed it in the main branch....

I only added a test after fixing conflicts

**Pull request merged**
