### PR TITLE
Trying to fix ci

### PR DESCRIPTION
**Pull request by roigcarlo**
Trying to fix the Ci.

So fair i managed to track down the segfault to `std::codecvt<char16_t, char, __mbstate_t>::` several functions.
Current guess is that is something related with the locale or conflicting versions of glibc/libstdc++

First commit tries to remove LD_LIBRARY_PATH prepend in order to remove possible incorrect versions of glibc added by an update of the docker container?

### CODE REVIEW

**Comment by roigcarlo** [comment]
@philbucher @matekelemen @sunethwarna if you have any idea about why the container got corrupted I am all ears. I am a little bit desperate.

**Comment by philbucher** [comment]
What is the problem? I was not checking the CI runs the last couple days

**Comment by roigcarlo** [comment]
The image broke after merging #11790. It compiles, but is unable to launch python

**Comment by philbucher** [comment]
I see
Can you run a hello world program with Python?
To see if it is Kratos or actually python

**Comment by roigcarlo** [comment]
Its any c++ code that prints under some circumstantes (no idea what causes it yet), I already run several tests locally.

As I suspected, seems that removing the LD_LIBRARY_PATH prepend has solved the issue with clang. If this works I will fix intel tomorrow morning and merge so people can work, and I will dig further.

**Comment by roigcarlo** [comment]
A ok, so the problem IS in the intelOneApi. What an amazing surprise.

**Comment by matekelemen** [comment]
@roigcarlo is there a way to emulate a github runner locally on my machine?

**Comment by roigcarlo** [comment]
Hey, yep you can use https://github.com/nektos/act

Anyway its under control now, should be fixed in a couple of commits ;)

**Review by loumalouomega — APPROVED** [review]

**Review by loumalouomega — APPROVED** [review]

**Comment by sunethwarna** [comment]
@roigcarlo Can we merge this?

**Review by philbucher — COMMENTED** [review]
Interesting that this suddenly became a problem 
It has worked for years

FYI this would be needed anytime we use sth from Intel. I am a bit puzzled there is no tests with Intel, when there should be

@roigcarlo can you check to make sure mkl is properly enabled? I was pretty sure that there are tests using it

**Comment by roigcarlo** [comment]
Hey, it is enabled, and its working.

It was working before also. The problem is that while updating the image we rebuild everything, and the docker script does not take a fixed version of the base image or intel OneApi, so it took the latest which were not tested.

The problem came because Intel OneAPI now is adding a buch of dirs in the LD_LIBRARY_PATH which caused two different versions of glibc to be active at the same time, being the intel ones prioritary (probably the glibc used to build the intel compiled that is installed), which in the end caused the function responsible to cast from char_16 to utf-8 to fail.

> can you check to make sure mkl is properly enabled? I was pretty sure that there are tests using it

I will double check, but I am pretty sure it is enabled in gcc. It has never been enabled with clang precisely because it was impossible to link mkl while compiling with anything other than gcc.

**Comment by roigcarlo** [comment]
@philbucher Confirm it works:

With gcc + mkl:

```bash
     Kratos  _     _                       ____        _
           | |   (_)_ __   ___  __ _ _ __/ ___|  ___ | |_   _____ _ __ ___
           | |   | | '_ \ / _ \/ _` | '__\___ \ / _ \| \ \ / / _ \ '__/ __|
           | |___| | | | |  __/ (_| | |   ___) | (_) | |\ V /  __/ |  \__ \
           |_____|_|_| |_|\___|\__,_|_|  |____/ \___/|_| \_/ \___|_|  |___/
Initializing KratosLinearSolversApplication...
Using Intel MKL version 2024.0.0 build 20231011
MKL processor: Intel(R) Architecture processors
KratosGeoSettlement: Importing StructuralMechanicsApplication

...

test_FEAST_with_eigen_solver (test_eigen_solvers.TestEigenSolvers) ... 0.075s ...ok
```

vs clang:

```bash
     Kratos  _     _                       ____        _
           | |   (_)_ __   ___  __ _ _ __/ ___|  ___ | |_   _____ _ __ ___
           | |   | | '_ \ / _ \/ _` | '__\___ \ / _ \| \ \ / / _ \ '__/ __|
           | |___| | | | |  __/ (_| | |   ___) | (_) | |\ V /  __/ |  \__ \
           |_____|_|_| |_|\___|\__,_|_|  |____/ \___/|_| \_/ \___|_|  |___/
Initializing KratosLinearSolversApplication...
KratosGeoSettlement: Importing StructuralMechanicsApplication

....

test_FEAST_with_eigen_solver (test_eigen_solvers.TestEigenSolvers) ... 0.000s ...skipped 'FEAST is not available'
```

from: 
- gcc: https://github.com/KratosMultiphysics/Kratos/actions/runs/8339533973/job/22821716806
- clang: https://github.com/KratosMultiphysics/Kratos/actions/runs/8339533973/job/22821717232

**Comment by philbucher** [comment]
Thanks for checking 
The tests with Pardiso are also running?

I know that the container was rebuilt, was just wondering why now the behavior changed

Maybe we should rebuild it on a regular basis to catch those things early 
How about every other week?

**Comment by philbucher** [comment]
Ok pardiso tests are running, all good then

**Comment by roigcarlo** [comment]
> Maybe we should rebuild it on a regular basis to catch those things early
How about every other week?

Yep that's a good idea, and keep one under a  :stable tag so if things like this happen again we have a backup

**Pull request merged**
