### PR TITLE
[CI] Add statistics application

### PR DESCRIPTION
**Pull request by sunethwarna**
This PR is to add StatisticsApplication to CI (linux and windows both).
Application maintainers:
@sunethwarna 
@mpentek 

There are 5 cpp tests, 54 MPI tests and 66 OpenMP tests.

Extensive user guide is provided via README.md file.

### CODE REVIEW

**Comment by philbucher** [comment]
I agree with adding it

@pooyan-dadvand @roigcarlo @rubenzorrilla @RiccardoRossi if this is ok for you then I don't think we need to discuss it

**Comment by roigcarlo** [comment]
Good from my side

**Comment by pooyan-dadvand** [comment]
@KratosMultiphysics/technical-committee agrees!

**Review by philbucher — APPROVED** [review]

**Comment by sunethwarna** [comment]
Thanks everyone :)

**Pull request merged**
