### PR TITLE
[Core] making global pointers to occupy exactly 1 

### PR DESCRIPTION
**Pull request by RiccardoRossi**
This optimizes GlobalPointers in the case in which kratos is compiled without mpi.

this is done by removing the rank (following an idea originally proposed by @pooyan-dadvand )

note that if one enables mpi (which is also done automatically if trilinos or metis are included) than the globalpointers will occupy 1pointer and 1integer (as they are doing now).

to have an idea of the impact let's consider a classic 3D case with tets, in which we have 1M elements and 200k nodes.

as an estimation we will have 200000*16 neighbour elements and approximately the same nodal neighbours. the memory saving in this case should be in the range of 24MB for each neighbour type. not enormous but also not neglibible

### CODE REVIEW

**Comment by philbucher** [comment]
image

@RiccardoRossi @pooyan-dadvand 
no offence, just making fun :D

**Comment by philbucher** [comment]
makes sense to me

I guess there is no better way except using the macro everywhere?

**Comment by loumalouomega** [comment]
> image
> 
> @RiccardoRossi @pooyan-dadvand
> no offence, just making fun :D

That's the opposite of KDE project

**Comment by RiccardoRossi** [comment]
@philbucher  no offence taken ;-) . I find some truth in what you say ... and ... @loumalouomega you already know i don't love KDE ;-)

**Comment by RiccardoRossi** [comment]
> makes sense to me
> 
> I guess there is no better way except using the macro everywhere?

this is conditional compilation...so i guess is where ifdefs make sense...(i mean, what i have done)

**Comment by philbucher** [comment]
Have you tried compiling this without mpi?
Arent there some usages of the GP where the rank is an input or output?

**Comment by RiccardoRossi** [comment]
i did compile without mpi, but i will verify what you say

**Comment by RiccardoRossi** [comment]
I spent some time verifying, and i think that the code is ok right now. 

if there is no other objection i think this is ready to be merged

**Comment by philbucher** [comment]
can you please merge master before merging?

**Review by pooyan-dadvand — APPROVED** [review]
👍

**Comment by RiccardoRossi** [comment]
master was merged.

**Pull request merged**
