### PR TITLE
[Core] bring back proper object printing in python

### PR DESCRIPTION
**Pull request by philbucher**
see #2735 

The printing in python was limited since we moved to pybind
this PR updates the rest of the core, the main discussion was happening in #2735 

I use `__str__` instead of `__repr__` since this is supposed to print information in a readable way
See the python-docs for [`__str__`](https://docs.python.org/3/reference/datamodel.html#object.__str__) and [`__repr__`](https://docs.python.org/3/reference/datamodel.html#object.__repr__)

### CODE REVIEW

**Review by RiccardoRossi — COMMENTED** [review]
this PR misses the modified define_python.h

btw why a macro and not a function?

**Comment by philbucher** [comment]
> this PR misses the modified define_python.h

what do you mean?
The macro (along with quite some discussion on how to do this) was introduced in #2735 and is already in master: 
https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/includes/define_python.h#L98-L105

> btw why a macro and not a function?

For me it felt more natural to use a macro for this, also I don't know if using a fct for this would have been possible

**Comment by RiccardoRossi** [comment]
sorry i was in a old PR

we (and Pooyan here agrees, he did not think about at the time of reviewing) would propose to use 
smthg like

        template< class T>
              std::string PrintObject(const T& object) ... 

the rationale is that it is always better to avoid macros if you can do it by a function

**Comment by philbucher** [comment]
ok I see what I can do

**Comment by philbucher** [comment]
@RiccardoRossi @pooyan-dadvand done, now the printing is done with a function, I removed the Macro

**Comment by RiccardoRossi** [comment]
i think you shall also change the uses of macro in the code...

**Comment by philbucher** [comment]
> i think you shall also change the uses of macro in the code...

I did ... I removed the macro entirely, it wouldn't compile if I left it somewhere

**Comment by philbucher** [comment]
ping @KratosMultiphysics/technical-committee

**Comment by pooyan-dadvand** [comment]
As I approved once without success I would let others to do it.

**Comment by RiccardoRossi** [comment]
Ok thx, now code looks fine. I would approve...but you hae a conflict

**Review by RiccardoRossi — DISMISSED** [review]

**Comment by philbucher** [comment]
thx
conflicts fixed

**Comment by philbucher** [comment]
@roigcarlo I though merging master does not require re-approval any more?
Guess it still does in case there are conflicts

**Review by RiccardoRossi — APPROVED** [review]

**Comment by philbucher** [comment]
thanks :tada:

**Pull request merged**
