### PR TITLE
Fix compilation warning about unused variable

### PR DESCRIPTION
**Pull request by marandra**
This PR removes an unused variable that triggered a warning during compilation:
`.../Kratos/kratos/utilities/bounding_box_utilities.h:883:18: warning: private field 'mrdimension' is not used [-Wunused-private-field]`

I noticed that most of the code of this routine is commented out. @RiccardoRossi , I think git "blames" you. Let me know if you want me to clean the code up.

### CODE REVIEW

**Comment by marandra** [comment]
Sorry, I PRed too soon

**Comment by marandra** [comment]
Now

**Comment by RiccardoRossi** [comment]
this looks ok to me, however @pooyan-dadvand could you see if you also agree?

**Comment by marandra** [comment]
Ping @pooyan-dadvand

**Review by RiccardoRossi — DISMISSED** [review]

**Comment by marandra** [comment]
@RiccardoRossi I removed unused code I mentioned to you before

**Comment by marandra** [comment]
@RiccardoRossi I noticed that @loumalouomega has a pending PR #1752 that modifies `ModelPart mr_model_part;` to `ModelPart & mr_model_part;` I think it is easier to merge this PR first, but let me know it is not the case.

**Review by RiccardoRossi — APPROVED** [review]

**Pull request merged**
