### PR TITLE
adding parallel ilu - bumping up to take advantage of latest changes in AMGCL

### PR DESCRIPTION
**Pull request by RiccardoRossi**
this is around 50% faster on 24 cores due to parallelization of the triangular solve (thx @ddemidov !!)

OLD VERSION TIMINGS FOR 1M elements
SimpleTube3D.o1162461:system solve time: 12.1437
SimpleTube3D.o1162461:system solve time: 12.352
SimpleTube3D.o1162461:system solve time: 4.30905
SimpleTube3D.o1162461:system solve time: 3.9493
SimpleTube3D.o1162461:system solve time: 3.43912
SimpleTube3D.o1162461:system solve time: 3.75573
SimpleTube3D.o1162461:system solve time: 3.5352
SimpleTube3D.o1162461:system solve time: 3.75189
SimpleTube3D.o1162461:system solve time: 3.57321
SimpleTube3D.o1162461:system solve time: 3.75615

new versions timings for the same problem
system solve time: 7.84308
system solve time: 8.02038
system solve time: 3.23133
system solve time: 2.57848
system solve time: 2.81888
system solve time: 2.49997
system solve time: 2.94038
system solve time: 2.56448
system solve time: 3.0457
system solve time: 2.55972

### CODE REVIEW

**Comment by ddemidov** [comment]
There were more recent changes: I've also parallelized `gauss_seidel` smoother and got rid of (obsolete) `parallel_ilu0` and `multicolor_gauss_seidel`. Also, I've just tagged version [1.0.0](https://github.com/ddemidov/amgcl/releases/tag/1.0.0).

**Comment by RiccardoRossi** [comment]
Sorry, I ll correct that tomorrow

Cheers
Riccardo

**Review by ddemidov — APPROVED** [review]

**Comment by jrubiogonzalez** [comment]
Great! Thank you very much.

**Review by roigcarlo — APPROVED** [review]
:+1:

**Pull request merged**
