### PR TITLE
[StructuralMechanicsApplication] Not throwing warning in case of using directly the main model part

### PR DESCRIPTION
**Pull request by loumalouomega**
In some of my tests I use the main model part directly so the warning is redundant

### CODE REVIEW

**Review by philbucher — CHANGES_REQUESTED** [review]
The check is correct!

If you use the MainModelPart directly but not add it to the ComputingModelPart then you might not have all Nodes/Elements/Conditions in it!

**Comment by loumalouomega** [comment]
> The check is correct!
> 
> If you use the MainModelPart directly but not add it to the ComputingModelPart then you might not have all Nodes/Elements/Conditions in it!

Computing model part is part of the main

**Comment by philbucher** [comment]
Yes, it is a subset, not the entire one

e.g. there could be nodes in the MainModelPart that are not added into the ComputingModelPart
Since you specify a Process / Materials using the MainModelPart, you would clearly also want all Nodes to be added to the ComputingModelPart
=> If you don't add the MainModelPart to the ComputingModelPart then you miss them

**Comment by loumalouomega** [comment]
OK

**Comment by philbucher** [comment]
This usually does not happen for small problems, but we had some problems with larger problems already

**Pull request closed without merging**
