### PR TITLE
missing include in applicaiton template

### LINKED ISSUE #7786: Error while compiling new application (following tutorial)
Hi everyone,

I am new to Kratos and I tried the [Tutorial](https://github.com/KratosMultiphysics/Kratos/wiki/Kratos-For-Dummies:-Stationary-heat-transfer) to get an idea how to work with Kratos C++ codes.  I was able to to update the config file for compiling it but I am still getting an error and do not know what I am doing wrong.  The definition of the variables seem to cause the problem:
 
[error.txt](https://github.com/KratosMultiphysics/Kratos/files/5523006/error.txt)

Does anyone know how can I fix this? Did I miss something or is something else on the tutorial perhaps not up-to-date to compile with the newest version?

Thanks in advance!

### PR DESCRIPTION
**Pull request by philbucher**
**Description**
Adds a missing include

@PhiHo-eng this should solve your problem, can you give it a try?

closes #7786

### CODE REVIEW

**Comment by PhiHo-eng** [comment]
@philbucher I added the missing include, but I did not change the output. I still get several errors regarding the "Variables"

[error.txt](https://github.com/KratosMultiphysics/Kratos/files/5523280/error.txt)

**Comment by marcnunezc** [comment]
> @philbucher thank you for your fast response
> I added the missing include, but it did not change the output. I still get several errors regarding the "Variables"
> 
> [error.txt](https://github.com/KratosMultiphysics/Kratos/files/5523280/error.txt)

Hi @PhiHo-eng ,

Did you add it in the file "my_laplacian_application_variables.h"?

the file would look like this:

```cpp
//    |  /           |
//    ' /   __| _` | __|  _ \   __|
//    . \  |   (   | |   (   |\__ `
//   _|\_\_|  \__,_|\__|\___/ ____/
//                   Multi-Physics
//
//  License:         BSD License
//                   Kratos default license: kratos/license.txt
//
//  Main authors:    @{KRATOS_APP_AUTHOR}
//

#if !defined(KRATOS_MY_LAPLACIAN_APPLICATION_VARIABLES_H_INCLUDED )
#define  KRATOS_MY_LAPLACIAN_APPLICATION_VARIABLES_H_INCLUDED

// System includes

// External includes

// Project includes
#include "includes/define.h"
#include "containers/variable.h"

namespace Kratos
{
KRATOS_DEFINE_VARIABLE( double, POINT_HEAT_SOURCE )

}

#endif	/* KRATOS_MY_LAPLACIAN_APPLICATION_VARIABLES_H_INCLUDED */


```

**Comment by PhiHo-eng** [comment]
First I modified only the template... Now it works. Thank you very much!

**Comment by marcnunezc** [comment]
> First I modified only the template... Now it works. Thank you very much!

Nice, is the rest working fine for you? I also had to add the following include:


```cpp
#include "includes/variables.h"
```
Otherwise the condition in the tutorial, which uses TEMPERATURE, does not find the variable
maybe we can also add it in the template @philbucher ?

**Comment by philbucher** [comment]
@marcnunezc I removed this include because 
- it is a heavy include
- it is often included for the sake of being included, even though it is not used
- I want to break this up further to reduce the compile times in the future

However I don't know how to fix properly the tutorial, I have to think about it

**Comment by marcnunezc** [comment]
> @marcnunezc I removed this include because
> 
> * it is a heavy include
> * it is often included for the sake of being included, even though it is not used
> * I want to break this up further to reduce the compile times in the future
> 
> However I don't know how to fix properly the tutorial, I have to think about it

Ok! In the meantime, should we add this include in the header of the element and condition in the tutorial?

https://github.com/KratosMultiphysics/Kratos/wiki/Tutorial:-Creating-the-Element#header-and-source-files

https://github.com/KratosMultiphysics/Kratos/wiki/Tutorial:-Creating-the-Conditions#creating-a-custom-condition-to-incorporate-the-thermal-loads

**Review by marcnunezc — APPROVED** [review]

**Comment by philbucher** [comment]
> Ok! In the meantime, should we add this include in the header of the element and condition in the tutorial?
> 
> https://github.com/KratosMultiphysics/Kratos/wiki/Tutorial:-Creating-the-Element#header-and-source-files
> 
> https://github.com/KratosMultiphysics/Kratos/wiki/Tutorial:-Creating-the-Conditions#creating-a-custom-condition-to-incorporate-the-thermal-loads

Ah there it is, I didn't find it :D
Could you please add it? Thx!

**Comment by marcnunezc** [comment]
Sure!

**Pull request merged**
