### PR TITLE
[PotentialFlow] Adding pseudo time stepping

### PR DESCRIPTION
**Pull request by inigolcanalejo**
Pseudo time stepping is added. 

This is useful to be able to do load control for nonlinear problems and it will also ease the coupling with the cosimulation application.

Basically RunSolutionLoop and AdvanceInTime are removed so that the ones in the base classes are used.

### CODE REVIEW

**Comment by rubenzorrilla** [comment]
As far as I see the custom potential flow analysis stage is only required to create the solvers, meaning that it should be possible to use the base fluid one once the factories are ready.

Aside of this, have you tested the GUI? I'm pretty sure that we are not writing the `time_stepping` to the json. I think that would be nice to have this option in the GUI too.

**Comment by philbucher** [comment]
> As far as I see the custom potential flow analysis stage is only required to create the solvers, meaning that it should be possible to use the base fluid one once the factories are ready.

looks like it to me

@inigolcanalejo @marcnunezc you seem to have a lot of code for backward-compatibility. It is almost 2 yeasrs old, I think it is time to remove it :)

**Comment by inigolcanalejo** [comment]
> al flow analysis stage is only required to create the solvers, meaning that it should be possible to use the base fluid one once the factories are ready.

Yes, you are right. Ill remove this script when the factories are ready.

> Aside of this, have you tested the GUI? I'm pretty sure that we are not writing the `time_stepping` to the json. I think that would be nice to have this option in the GUI too.

Ill update the GUI according to these changes.


> @inigolcanalejo @marcnunezc you seem to have a lot of code for backward-compatibility. It is almost 2 yeasrs old, I think it is time to remove it :)

I do this here https://github.com/KratosMultiphysics/Kratos/pull/6666, is this what you mean?

**Comment by inigolcanalejo** [comment]
I think this is ready to be merged unless you require further changes

**Review by philbucher — APPROVED** [review]
:+1:

**Review by marcnunezc — APPROVED** [review]
Ok!!

**Comment by inigolcanalejo** [comment]
Thanks!

**Pull request merged**
