### PR TITLE
[CMake] Update Kratos version to 10.1

### PR DESCRIPTION
**Pull request by loumalouomega**
**📝 Description**

Update Kratos version to 10.1

**🆕 Changelog**

- [Update Kratos version to 10.1](https://github.com/KratosMultiphysics/Kratos/commit/66213a7c7ebdd1c49e54954ed785118785febb43)

### CODE REVIEW

**Review by roigcarlo — CHANGES_REQUESTED** [review]
Please make the PR from https://github.com/KratosMultiphysics/Kratos/compare/master...Release-10.1

Which also contains the changes for the wheels

**Comment by loumalouomega** [comment]
> Please make the PR from [master...Release-10.1](https://github.com/KratosMultiphysics/Kratos/compare/master...Release-10.1)
> 
> Which also contains the changes for the wheels

DO you mean to cherry pick to that brach as well¿?

**Comment by roigcarlo** [comment]
No need, you can just merge the changes in that branch directly

**Comment by roigcarlo** [comment]
I'll do it

**Pull request closed without merging**
