### PR TITLE
[Core][Template] Allowing custom tree in TemplateApplication.py

### PR DESCRIPTION
**Pull request by loumalouomega**
This is an alternative approach to #5805, in this case pure python is used, and it will work both with link and install

### CODE REVIEW

**Comment by philbucher** [comment]
So this makes using „external“ applications easy right?
But how do you import them? With or without „KratosMultiphysics.“?

Can you show an example?

**Comment by loumalouomega** [comment]
> 
> 
> So this makes using „external“ applications easy right?
> But how do you import them? With or without „KratosMultiphysics.“?
> 
> Can you show an example?

With the current approach, the link, it just allows to work in the same way is done in the current apps. With the install I assume it will work to due to being considering always the path to the current folder

**Comment by philbucher** [comment]
Hm I think you misunderstood 
Could you show an example of how you can use e.g. your pythonwrappersApp?

**Comment by loumalouomega** [comment]
Here: https://github.com/loumalouomega/KratosPythonWrapperApplication/blob/master/PythonWrapperApplication/PythonWrapperApplication.py

**Comment by loumalouomega** [comment]
I will close this due to the future changes this will be affected

**Pull request closed without merging**
