### PR TITLE
[Trilinos] optionally disable solvers

### PR DESCRIPTION
**Pull request by philbucher**
On some clusters compiling Trilinos can be a huge pain (I guess all of us had this pleasure already :/)
Hence it would be nice to be able to disable features that one does not use
By default they are enabled ofc

@AndreasWinterstein can you please try with this

### CODE REVIEW

**Comment by RiccardoRossi** [comment]
In my opinion everything should be enabled by default with the option of eventually disabling something

**Comment by philbucher** [comment]
> In my opinion everything should be enabled by default with the option of eventually disabling something

this is exactly how it works

now is ready for review

**Comment by RiccardoRossi** [comment]
much better now. 

If we can still throw an error when trying to use a solver we did not compile for it would be ideal.

that could be achieved by adding to the python interface a dummy class, and overriding the constructor (i mean the pybind "init") so that it throws a meaningful error

**Comment by philbucher** [comment]
I can do that but in 99% of the cases we use the factory and I am not sure how easy or if possible at all it would be do achieve the same behavior there

Also if I explicitly add sth to the configure to disable a solver I think it shouldn’t be a surprise if it fails when I try to use it xD ...

I will still try

**Comment by RiccardoRossi** [comment]
ok i see your argument. do not spend to much time on it then.

**Comment by philbucher** [comment]
@RiccardoRossi I added some basic checks
I tried first in C++ but it gets out of hand very fast :/
I can revert the last commit if you don't like it

**Comment by philbucher** [comment]
@AndreasWinterstein this is ready for being tested

@loumalouomega if you want you could try to compile the TrilinosApp on this branch, you can now disable the things that give problems

**Review by RiccardoRossi — APPROVED** [review]

**Comment by philbucher** [comment]
merging after speaking to @AndreasWinterstein in person

**Pull request merged**
