### PR TITLE
[Core] Moving auxiliar files of the python tests in the core to reduce mesh in tests folder

### PR DESCRIPTION
**Pull request by loumalouomega**
Basically that

Complements #3373

### CODE REVIEW

**Comment by philbucher** [comment]
take a look at codacy pls

**Comment by loumalouomega** [comment]
Done @philbucher

**Comment by loumalouomega** [comment]
I solved the conflicts with the recent changes

**Comment by loumalouomega** [comment]
@KratosMultiphysics/implementation-committee I think this is our job

**Review by philbucher — DISMISSED** [review]
looks like a good cleanup to me :+1: 

Also this has been there forever, IMO time to merge

**Comment by loumalouomega** [comment]
> looks like a good cleanup to me +1
> 
> Also this has been there forever, IMO time to merge

I need re-approval after merging up

**Review by philbucher — APPROVED** [review]

**Comment by philbucher** [comment]
Thanks for the patience

**Comment by loumalouomega** [comment]
> Thanks for the patience

Longer was my patience with GoT. And tomorrow is finally here :D

**Pull request merged**
