### PR TITLE
Hotfix/fixing 3156

### PR DESCRIPTION
**Pull request by roigcarlo**
Don't know who is the responsible of the app ( I can take care if its orphan )

Also, I sneakily added another fix to the core which could cause a warning in newer versions of cmake 🤫

### CODE REVIEW

**Comment by philbucher** [comment]
thx, bit with GCC 5.4 I still get the following warnings:
~~~
In file included from /home/philippb/software/Kratos_aux/kratos/includes/data_communicator.h:23:0,
                 from /home/philippb/software/Kratos_aux/kratos/input_output/logger_message.h:34,
                 from /home/philippb/software/Kratos_aux/kratos/input_output/logger.h:23,
                 from /home/philippb/software/Kratos_aux/kratos/utilities/math_utils.h:27,
                 from /home/philippb/software/Kratos_aux/applications/MeshingApplication/custom_processes/metrics_levelset_process.cpp:14:
/home/philippb/software/Kratos_aux/kratos/containers/array_1d.h: In static member function ‘static Kratos::MetricsMathUtils<TDim>::TensorArrayType Kratos::MetricsMathUtils<TDim>::IntersectMetrics(const TensorArrayType&, const TensorArrayType&) [with long unsigned int TDim = 2ul; Kratos::MetricsMathUtils<TDim>::TensorArrayType = Kratos::array_1d<double, 3ul>]’:
/home/philippb/software/Kratos_aux/kratos/containers/array_1d.h:132:23: warning: ‘*((void*)& StressVector +16)’ may be used uninitialized in this function [-Wmaybe-uninitialized]
         data_ (v.data_) {}
                       ^
In file included from /home/philippb/software/Kratos_aux/applications/MeshingApplication/custom_processes/metrics_levelset_process.cpp:14:0:
/home/philippb/software/Kratos_aux/kratos/utilities/math_utils.h:1483:17: note: ‘*((void*)& StressVector +16)’ was declared here
         TVector StressVector;
                 ^
In file included from /home/philippb/software/Kratos_aux/kratos/includes/data_communicator.h:23:0,
                 from /home/philippb/software/Kratos_aux/kratos/input_output/logger_message.h:34,
                 from /home/philippb/software/Kratos_aux/kratos/input_output/logger.h:23,
                 from /home/philippb/software/Kratos_aux/kratos/utilities/math_utils.h:27,
                 from /home/philippb/software/Kratos_aux/applications/MeshingApplication/custom_processes/metrics_levelset_process.cpp:14:
/home/philippb/software/Kratos_aux/kratos/containers/array_1d.h:132:23: warning: ‘*((void*)& StressVector +8)’ may be used uninitialized in this function [-Wmaybe-uninitialized]
         data_ (v.data_) {}
                       ^
In file included from /home/philippb/software/Kratos_aux/applications/MeshingApplication/custom_processes/metrics_levelset_process.cpp:14:0:
/home/philippb/software/Kratos_aux/kratos/utilities/math_utils.h:1483:17: note: ‘*((void*)& StressVector +8)’ was declared here
         TVector StressVector;
                 ^
In file included from /home/philippb/software/Kratos_aux/kratos/includes/data_communicator.h:23:0,
                 from /home/philippb/software/Kratos_aux/kratos/input_output/logger_message.h:34,
                 from /home/philippb/software/Kratos_aux/kratos/input_output/logger.h:23,
                 from /home/philippb/software/Kratos_aux/kratos/utilities/math_utils.h:27,
                 from /home/philippb/software/Kratos_aux/applications/MeshingApplication/custom_processes/metrics_levelset_process.cpp:14:
/home/philippb/software/Kratos_aux/kratos/containers/array_1d.h:132:23: warning: ‘StressVector’ may be used uninitialized in this function [-Wmaybe-uninitialized]
         data_ (v.data_) {}
                       ^
In file included from /home/philippb/software/Kratos_aux/applications/MeshingApplication/custom_processes/metrics_levelset_process.cpp:14:0:
/home/philippb/software/Kratos_aux/kratos/utilities/math_utils.h:1483:17: note: ‘StressVector’ was declared here
         TVector StressVector;
                 ^
In file included from /home/philippb/software/Kratos_aux/kratos/includes/data_communicator.h:23:0,
                 from /home/philippb/software/Kratos_aux/kratos/input_output/logger_message.h:34,
                 from /home/philippb/software/Kratos_aux/kratos/input_output/logger.h:23,
                 from /home/philippb/software/Kratos_aux/kratos/utilities/math_utils.h:27,
                 from /home/philippb/software/Kratos_aux/applications/MeshingApplication/custom_processes/metrics_levelset_process.cpp:14:
/home/philippb/software/Kratos_aux/kratos/containers/array_1d.h: In function ‘<built-in>’:
/home/philippb/software/Kratos_aux/kratos/containers/array_1d.h:196:9: warning: ‘*((void*)& StressVector +40)’ may be used uninitialized in this function [-Wmaybe-uninitialized]
         data_  = v.data_;
         ^
In file included from /home/philippb/software/Kratos_aux/applications/MeshingApplication/custom_processes/metrics_levelset_process.cpp:14:0:
/home/philippb/software/Kratos_aux/kratos/utilities/math_utils.h:1483:17: note: ‘*((void*)& StressVector +40)’ was declared here
         TVector StressVector;
                 ^
In file included from /home/philippb/software/Kratos_aux/kratos/includes/data_communicator.h:23:0,
                 from /home/philippb/software/Kratos_aux/kratos/input_output/logger_message.h:34,
                 from /home/philippb/software/Kratos_aux/kratos/input_output/logger.h:23,
                 from /home/philippb/software/Kratos_aux/kratos/utilities/math_utils.h:27,
                 from /home/philippb/software/Kratos_aux/applications/MeshingApplication/custom_processes/metrics_levelset_process.cpp:14:
/home/philippb/software/Kratos_aux/kratos/containers/array_1d.h:196:9: warning: ‘*((void*)& StressVector +32)’ may be used uninitialized in this function [-Wmaybe-uninitialized]
         data_  = v.data_;
         ^
In file included from /home/philippb/software/Kratos_aux/applications/MeshingApplication/custom_processes/metrics_levelset_process.cpp:14:0:
/home/philippb/software/Kratos_aux/kratos/utilities/math_utils.h:1483:17: note: ‘*((void*)& StressVector +32)’ was declared here
         TVector StressVector;
                 ^
In file included from /home/philippb/software/Kratos_aux/kratos/includes/data_communicator.h:23:0,
                 from /home/philippb/software/Kratos_aux/kratos/input_output/logger_message.h:34,
                 from /home/philippb/software/Kratos_aux/kratos/input_output/logger.h:23,
                 from /home/philippb/software/Kratos_aux/kratos/utilities/math_utils.h:27,
                 from /home/philippb/software/Kratos_aux/applications/MeshingApplication/custom_processes/metrics_levelset_process.cpp:14:
/home/philippb/software/Kratos_aux/kratos/containers/array_1d.h:196:9: warning: ‘*((void*)& StressVector +24)’ may be used uninitialized in this function [-Wmaybe-uninitialized]
         data_  = v.data_;
         ^
In file included from /home/philippb/software/Kratos_aux/applications/MeshingApplication/custom_processes/metrics_levelset_process.cpp:14:0:
/home/philippb/software/Kratos_aux/kratos/utilities/math_utils.h:1483:17: note: ‘*((void*)& StressVector +24)’ was declared here
         TVector StressVector;
                 ^
In file included from /home/philippb/software/Kratos_aux/kratos/includes/data_communicator.h:23:0,
                 from /home/philippb/software/Kratos_aux/kratos/input_output/logger_message.h:34,
                 from /home/philippb/software/Kratos_aux/kratos/input_output/logger.h:23,
                 from /home/philippb/software/Kratos_aux/kratos/utilities/math_utils.h:27,
                 from /home/philippb/software/Kratos_aux/applications/MeshingApplication/custom_processes/metrics_levelset_process.cpp:14:
/home/philippb/software/Kratos_aux/kratos/containers/array_1d.h:196:9: warning: ‘*((void*)& StressVector +16)’ may be used uninitialized in this function [-Wmaybe-uninitialized]
         data_  = v.data_;
         ^
In file included from /home/philippb/software/Kratos_aux/applications/MeshingApplication/custom_processes/metrics_levelset_process.cpp:14:0:
/home/philippb/software/Kratos_aux/kratos/utilities/math_utils.h:1483:17: note: ‘*((void*)& StressVector +16)’ was declared here
         TVector StressVector;
                 ^
In file included from /home/philippb/software/Kratos_aux/kratos/includes/data_communicator.h:23:0,
                 from /home/philippb/software/Kratos_aux/kratos/input_output/logger_message.h:34,
                 from /home/philippb/software/Kratos_aux/kratos/input_output/logger.h:23,
                 from /home/philippb/software/Kratos_aux/kratos/utilities/math_utils.h:27,
                 from /home/philippb/software/Kratos_aux/applications/MeshingApplication/custom_processes/metrics_levelset_process.cpp:14:
/home/philippb/software/Kratos_aux/kratos/containers/array_1d.h:196:9: warning: ‘*((void*)& StressVector +8)’ may be used uninitialized in this function [-Wmaybe-uninitialized]
         data_  = v.data_;
         ^
In file included from /home/philippb/software/Kratos_aux/applications/MeshingApplication/custom_processes/metrics_levelset_process.cpp:14:0:
/home/philippb/software/Kratos_aux/kratos/utilities/math_utils.h:1483:17: note: ‘*((void*)& StressVector +8)’ was declared here
         TVector StressVector;
                 ^
In file included from /home/philippb/software/Kratos_aux/kratos/includes/data_communicator.h:23:0,
                 from /home/philippb/software/Kratos_aux/kratos/input_output/logger_message.h:34,
                 from /home/philippb/software/Kratos_aux/kratos/input_output/logger.h:23,
                 from /home/philippb/software/Kratos_aux/kratos/utilities/math_utils.h:27,
                 from /home/philippb/software/Kratos_aux/applications/MeshingApplication/custom_processes/metrics_levelset_process.cpp:14:
/home/philippb/software/Kratos_aux/kratos/containers/array_1d.h:196:9: warning: ‘StressVector’ may be used uninitialized in this function [-Wmaybe-uninitialized]
         data_  = v.data_;
         ^
In file included from /home/philippb/software/Kratos_aux/applications/MeshingApplication/custom_processes/metrics_levelset_process.cpp:14:0:
/home/philippb/software/Kratos_aux/kratos/utilities/math_utils.h:1483:17: note: ‘StressVector’ was declared here
~~~

**Comment by roigcarlo** [comment]
Honestly I don't know about those ones. @pooyan-dadvand Some help?

**Comment by roigcarlo** [comment]
@philbucher I propose to merge this and adress the other warnings in a separate PR as I don't have any clue about the second one. I'll remove the closing comment for the issue.

**Review by philbucher — APPROVED** [review]
makes sense to me :+1: 
Thx in any case

**Pull request merged**
