### PR TITLE
[Core] Removed unused class VectorMap

### PR DESCRIPTION
**Pull request by loumalouomega**
**📝 Description**

Removed unused class VectorMap. This class is not used anywhere, and there are not even tests for it. The class does not even compile on Windows with C++17, and has not been updated in years.

**🆕 Changelog**

- [Removed unused class VectorMap](https://github.com/KratosMultiphysics/Kratos/commit/a9db3ba0657ce48f7bd262c38d3f604e83fc4991)

### CODE REVIEW

**Comment by matekelemen** [comment]
A map stored in contiguous memory is not a bad idea tho. I'm aching to try out one of [these](https://github.com/Tessil?tab=repositories) for example.

**Comment by loumalouomega** [comment]
> A map stored in contiguous memory is not a bad idea tho. I'm aching to try out one of [these](https://github.com/Tessil?tab=repositories) for example.

This was added by @RiccardoRossi, do you think is still needed?

**Comment by loumalouomega** [comment]
> > A map stored in contiguous memory is not a bad idea tho. I'm aching to try out one of [these](https://github.com/Tessil?tab=repositories) for example.
> 
> This was added by @RiccardoRossi, do you think is still needed?

Hello @RiccardoRossi

**Comment by loumalouomega** [comment]
> > > A map stored in contiguous memory is not a bad idea tho. I'm aching to try out one of [these](https://github.com/Tessil?tab=repositories) for example.
> > 
> > 
> > This was added by @RiccardoRossi, do you think is still needed?
> 
> Hello @RiccardoRossi

👋 @RiccardoRossi

**Comment by loumalouomega** [comment]
> > > > A map stored in contiguous memory is not a bad idea tho. I'm aching to try out one of [these](https://github.com/Tessil?tab=repositories) for example.
> > > 
> > > 
> > > This was added by @RiccardoRossi, do you think is still needed?
> > 
> > 
> > Hello @RiccardoRossi
> 
> 👋 @RiccardoRossi

👋 👋 @RiccardoRossi

**Comment by loumalouomega** [comment]
> > > > > A map stored in contiguous memory is not a bad idea tho. I'm aching to try out one of [these](https://github.com/Tessil?tab=repositories) for example.
> > > > 
> > > > 
> > > > This was added by @RiccardoRossi, do you think is still needed?
> > > 
> > > 
> > > Hello @RiccardoRossi
> > 
> > 
> > 👋 @RiccardoRossi
> 
> 👋 👋 @RiccardoRossi

👋👋👋👋

**Comment by RiccardoRossi** [comment]
@KratosMultiphysics/technical-committee agrees about removing

**Review by RiccardoRossi — APPROVED** [review]
approving on behalf or @KratosMultiphysics/technical-committee

**Pull request merged**
