### PR TITLE
investigating_0_threads_issue

### PR DESCRIPTION
**Pull request by RiccardoRossi**
**Description**
adds errors (even in release mode) in the case zero threads are found

Please mark the PR with appropriate tags: 
debugging

**Changelog**

### CODE REVIEW

**Comment by roigcarlo** [comment]
@RiccardoRossi Shall we merge this?

**Review by RiccardoRossi — COMMENTED** [review]
not sure, as it would have a performance impact. I think we should close it ... but...opinions?

**Comment by roigcarlo** [comment]
Same, closing

**Comment by loumalouomega** [comment]
Do we still need this branch @RiccardoRossi ?, can we remove it?

**Pull request closed without merging**
