### PR TITLE
[Mapping/CoSim] missing sync and other fixes

### LINKED ISSUE #7780: [MappingApplication] Is there a missing synchronize in MPI?
**Description**
Regarding #7728, I have been trying to do the following.

All run in MPI:
- Run a FluidDyn simulation (initial_model_part)
- Remesh with ParMmg (getting a main_model_part)
- Map the velocity and pressure fields from initial model_part to the main_model_part
- Run the FluidDyn simulation with the new mesh and fields (main_model_part).

What I am experiencing is that after mapping the fields, the new simulation genereates weird features in the field. This are caused due to a lack of synchornization of the values of the velocity across ranks. 

This is the correct mapped field.
image

Field after some seconds of simulation (see the peaks on the velocity field).
image

If after performing the mapping I run the lines: 
```python
main_model_part.GetCommunicator().SynchronizeVariable(KratosMultiphysics.VELOCITY)
main_model_part.GetCommunicator().SynchronizeVariable(KratosMultiphysics.PRESSURE)

```

The weird effects do not happen. 

image

If the velocity is compared among ranks, it can be seen that without the synchronization, different ranks have different values of VELOCITY on the same node. 

The mapping parameters that I use are:

```python
mapper_settings = KratosMultiphysics.Parameters("""{
"mapper_type": "nearest_element",
"interface_submodel_part_origin": "Parts_Fluid",
"interface_submodel_part_destination": "Parts_Fluid",
"search_radius" : 0.01,
"echo_level" : 0
}""")

# creating a mapper for distributed memory
mpi_mapper = KratosMapping.MapperFactory.CreateMPIMapper(
    initial_main_model_part,
    main_model_part,
    mapper_settings)
mpi_mapper.Map(KratosMultiphysics.VELOCITY, KratosMultiphysics.VELOCITY)
mpi_mapper.Map(KratosMultiphysics.PRESSURE, KratosMultiphysics.PRESSURE)


```

@philbucher Have you experienced this? Is there anything am I doing wrong? Is it expected that the user synchronizes the variables after mapping?

**Scope**
- Mapping application
- Fluid Dynamics application

**To Reproduce**
Find the script in this zip (run with 4 procs on master branch).

[mapping_sync_cylinder_test.zip](https://github.com/KratosMultiphysics/Kratos/files/5518144/mapping_sync_cylinder_test.zip)

Lines 126 and 127 are commented (which perform the sync). **MMG/ParMMG is not required**

**Expected behavior**
That variables are synchronized after mapping. 

**Environment**
Please specify your operating system, kratos branch, python version or any other library versions that you consider relevant.
E.g.:
- OS: Ubuntu 18.04
- Branch: master
- Python 3.6.9

### PR DESCRIPTION
**Pull request by philbucher**
This PR implements several small fixes and improvements in the Mapping and the CoSimApp, things that have been on my todo list for a long time. They are all linked thats why I had to do the changes in one go to make sure it works everywhere
Here is a list of features:
- Mapping of nonhistorical values is now officially supported (unofficially was working for a while, so there nothing really has changed. I just checked in detail that it was fully working also for corner cases). Documentation is added.
- The CoSimApp also supports the new mapping features
- Extensive tests are added in both apps
- A missing sync for MPI was added: closes #7780
- Tests in the MappingApp were a bit modernized
- Some deprecated syntax in the Core was updated, see #8612

### CODE REVIEW

**Comment by philbucher** [comment]
FYI @ddiezrod seems like you already do the sync somewhere else, after this is merged you can remove it

**Comment by ddiezrod** [comment]
> FYI @ddiezrod seems like you already do the sync somewhere else, after this is merged you can remove it

Thanks @philbucher ! I will do this

**Comment by rubenzorrilla** [comment]
> FYI @ddiezrod seems like you already do the sync somewhere else, after this is merged you can remove it

Just as a reminder for myself, If I don't remember wrong, I also added the sync in the FSI app.

**Comment by riccardotosi** [comment]
Thanks @philbucher!

**Comment by philbucher** [comment]
if there are no complaints an approval would be appreciated :)

**Review by rubenzorrilla — APPROVED** [review]

**Pull request merged**
