### PR TITLE
[Core] Variable redistribution warnings and test upgrade

### LINKED ISSUE #8136: [KratosCore][TODO] Upgrade `VariableRedistributionUtility` tests
**Description**
Currently the `VariableRedistributionUtilities` tests in the `test_variable_redistribution.py` file use the `InterfacePreprocess` utility, which belongs to the `FSIApplication`. This means that the testing of a `KratosCore` feature depends on an application, which is a complete non-sense. 

These tests also require a clean up.

**TODO**
- [x] Remove the `InterfacePreprocess` usage from the `test_variable_redistribution.py`
- [x] Upgrade tests
- [x] Add MPI execution

### PR DESCRIPTION
**Pull request by rubenzorrilla**
This PR fixes a small warning in the `VariableRedistributionUtilities` and upgrades the testing as demanded in #8136.

Fixes #8136.

### CODE REVIEW

**Review by philbucher — DISMISSED** [review]
thx, but tests are failing
maybe some synchronization is missing?

**Comment by rubenzorrilla** [comment]
> thx, but tests are failing
> maybe some synchronization is missing?

I don't think so as we already use this in MPI for the FSI. I think it should be something related to the test (most probably a minor thing when setting the values).

**Comment by philbucher** [comment]
good luck with debugging :D

**Review by philbucher — DISMISSED** [review]
:+1:

**Review by philbucher — APPROVED** [review]

**Pull request merged**
