### PR TITLE
Feature porting elements

### PR DESCRIPTION
**Pull request by RiccardoRossi**
This is a pretty large commit which makes the compilation of the StructuralMechanicsApplication independent from that of the SolidMechanics.

@AndreasWinterstein @msandre @marandra 
it has the potential to disrupt things, so please try it out and give feedback before i do commit.

### CODE REVIEW

**Comment by loumalouomega** [comment]
@RiccardoRossi I haven't finished yet with the axisymetric elements

**Review by loumalouomega — CHANGES_REQUESTED** [review]
Let me finish the axisymetric elements please

**Comment by loumalouomega** [comment]
@RiccardoRossi Let me add the axisymetric case for the total lagrangian element and I am done (maybe I will not be able to have it finished until Monday)

**Review by loumalouomega — APPROVED** [review]

**Comment by loumalouomega** [comment]
@RiccardoRossi Done, I just need to do the tests for the axisymmetric elements, but I will postpone for the next week

**Comment by philbucher** [comment]
I compiled the branch and get this warning:

`/home/philippb/software/Kratos/applications/StructuralMechanicsApplication/custom_elements/total_lagrangian.cpp: In member function ‘void Kratos::TotalLagrangian::CalculateB(Kratos::Matrix&, Kratos::Matrix&, Kratos::Matrix&, unsigned int, const IntegrationPointsArrayType&, unsigned int)’:
/home/philippb/software/Kratos/applications/StructuralMechanicsApplication/custom_elements/total_lagrangian.cpp:418:16: warning: ‘Radius’ may be used uninitialized in this function [-Wmaybe-uninitialized]
         double Radius; `

Running the tests shows 4 errors: (sorry for bad formatting, copy-pasting doesn't really work)

ERROR: test_damped_mdof_system_dynamic (test_spring_damper_element.SpringDamperElementTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/philippb/software/Kratos/applications/StructuralMechanicsApplication/tests/test_spring_damper_element.py", line 238, in test_damped_mdof_system_dynamic
    mp = self._set_up_mdof_system()
  File "/home/philippb/software/Kratos/applications/StructuralMechanicsApplication/tests/test_spring_damper_element.py", line 101, in _set_up_mdof_system
    self._add_variables(mp)
  File "/home/philippb/software/Kratos/applications/StructuralMechanicsApplication/tests/test_spring_damper_element.py", line 21, in _add_variables
    mp.AddNodalSolutionStepVariable(StructuralMechanicsApplication.NODAL_MASS)
AttributeError: module 'KratosMultiphysics.StructuralMechanicsApplication' has no attribute 'NODAL_MASS'


ERROR: test_execution (test_spring_damper_element.SpringDamperElementTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/philippb/software/Kratos/applications/StructuralMechanicsApplication/tests/test_spring_damper_element.py", line 323, in test_execution
    self.test_undamped_mdof_system_dynamic()
  File "/home/philippb/software/Kratos/applications/StructuralMechanicsApplication/tests/test_spring_damper_element.py", line 150, in test_undamped_mdof_system_dynamic
    mp = self._set_up_mdof_system()
  File "/home/philippb/software/Kratos/applications/StructuralMechanicsApplication/tests/test_spring_damper_element.py", line 101, in _set_up_mdof_system
    self._add_variables(mp)
  File "/home/philippb/software/Kratos/applications/StructuralMechanicsApplication/tests/test_spring_damper_element.py", line 21, in _add_variables
    mp.AddNodalSolutionStepVariable(StructuralMechanicsApplication.NODAL_MASS)
AttributeError: module 'KratosMultiphysics.StructuralMechanicsApplication' has no attribute 'NODAL_MASS'

ERROR: test_undamped_mdof_system_dynamic (test_spring_damper_element.SpringDamperElementTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/philippb/software/Kratos/applications/StructuralMechanicsApplication/tests/test_spring_damper_element.py", line 150, in test_undamped_mdof_system_dynamic
    mp = self._set_up_mdof_system()
  File "/home/philippb/software/Kratos/applications/StructuralMechanicsApplication/tests/test_spring_damper_element.py", line 101, in _set_up_mdof_system
    self._add_variables(mp)
  File "/home/philippb/software/Kratos/applications/StructuralMechanicsApplication/tests/test_spring_damper_element.py", line 21, in _add_variables
    mp.AddNodalSolutionStepVariable(StructuralMechanicsApplication.NODAL_MASS)
AttributeError: module 'KratosMultiphysics.StructuralMechanicsApplication' has no attribute 'NODAL_MASS'


ERROR: test_undamped_sdof_system_harmonic (test_spring_damper_element.SpringDamperElementTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/philippb/software/Kratos/applications/StructuralMechanicsApplication/tests/test_spring_damper_element.py", line 198, in test_undamped_sdof_system_harmonic
    mp = self._set_up_sdof_system()
  File "/home/philippb/software/Kratos/applications/StructuralMechanicsApplication/tests/test_spring_damper_element.py", line 126, in _set_up_sdof_system
    self._add_variables(mp)
  File "/home/philippb/software/Kratos/applications/StructuralMechanicsApplication/tests/test_spring_damper_element.py", line 21, in _add_variables
    mp.AddNodalSolutionStepVariable(StructuralMechanicsApplication.NODAL_MASS)
AttributeError: module 'KratosMultiphysics.StructuralMechanicsApplication' has no attribute 'NODAL_MASS'

FAIL: test_execution (NightlyTests.ShellQ4ThickDrillingRollUpTests)
Traceback (most recent call last):
  File "/home/philippb/software/Kratos/applications/StructuralMechanicsApplication/tests/NightlyTests.py", line 41, in test_execution
    self.test.Solve()
  File "/home/philippb/software/Kratos/applications/StructuralMechanicsApplication/tests/Kratos_Execute_Structural_Test.py", line 116, in Solve
    process.ExecuteFinalizeSolutionStep()
  File "/home/philippb/software/Kratos/kratos/python_scripts/from_json_check_result_process.py", line 107, in ExecuteFinalizeSolutionStep
    self.assertAlmostEqual(value, value_json, msg=("Error checking node "+str(node.Id)+" "+out.GetString()+" results."), delta=tol)
AssertionError: 16339579.78694977 != 16339579.437823443 within 0.001 delta : Error checking node 1 REACTION_X results.

Stdout:
0
Construction of MechanicalSolver finished
::[Mechanical Solver]:: Variables ADDED
::[Mechanical Solver]:: Variables ADDED
::[Mechanical Solver]:: Model reading starts.
    Import input model part.
-computing_domain- model part
    Number of tables : 0
    Number of sub model parts : 0

    Mesh 0 : 
        Number of Nodes      : 243
        Number of Properties : 5
        Number of Elements   : 160
        Number of Conditions : 1


finished reading materials
    Constitutive law initialized.
::[Mechanical Solver]:: Model reading finished.
::[Mechanical Solver]:: DOF's ADDED
::[Mechanical Solver]:: -START-
::[Mechanical Solver]:: -END- 
[]

@qaumann I think this is what you recently commited?
Maybe this is solved in a local commit of @loumalouomega , see #487

**Comment by qaumann** [comment]
Hi @philbucher,
the NODAL_MASS is not a member of the StructuralMechanicsApplication but the KratosMultiphysics core, it is imported incorrectly as of commit fa6ebcceded2b54677b357b2f232ed1ff5954364. I will change that.
The assertion error in the ShellQ4ThickDrillingRollUpTests and the warning in the lagrangian element should not have anything to do with my commits regarding the spring/damper element.

**Comment by loumalouomega** [comment]
I will check it as soon as I arrive to the office, I checked everything
before leaving on Friday, but maybe I forgot something

**Comment by qaumann** [comment]
Commit f6c42b6e150b05bc8db8c097ff5e096d357e121b fixes the problem with the SpringDamperElementTests. The ShellQ4ThickDrillingRollUpTests still fail.

**Comment by loumalouomega** [comment]
@philbucher If the error is still appearing I can modify the process to take into account the relative error instead of the absolute error

**Comment by philbucher** [comment]
now all the tests are working

**Pull request merged**
