### PR TITLE
[Core] Using MSYS2 blas libraries to simplify installation

### PR DESCRIPTION
**Pull request by loumalouomega**
Just that

### CODE REVIEW

**Review by roigcarlo — DISMISSED** [review]

**Comment by RiccardoRossi** [comment]
quite long ago we decided to go for native compilatikn in win. cannot we use msvc for the wheels?

**Comment by roigcarlo** [comment]
This is for mingw only as I understand

**Comment by loumalouomega** [comment]
> 
> 
> This is for mingw only as I understand

Yep

**Comment by loumalouomega** [comment]
I will add to the wiki later

**Comment by loumalouomega** [comment]
Travis compilation takes to long for some reason (this PR does not affect anything)

**Comment by loumalouomega** [comment]
FYI: https://github.com/KratosMultiphysics/Kratos/wiki/Windows-Install-(MinGW)

**Comment by loumalouomega** [comment]
Just to mention that compiles way faster than the MVS @AlejandroCornejo

**Comment by loumalouomega** [comment]
I need reapproval @roigcarlo

**Comment by AlejandroCornejo** [comment]
Interesting! In this way we can compile Kratos in Windows without MSV? Maybe I'll have a look and see its velocity

**Review by roigcarlo — APPROVED** [review]

**Comment by loumalouomega** [comment]
> Interesting! In this way we can compile Kratos in Windows without MSV? Maybe I'll have a look and see its velocity

The compilation is way faster, the code I haven't checked, but the compilation is absolutely faster. Additionally the result is better integrated (as in Linux)

**Comment by loumalouomega** [comment]
https://github.com/KratosMultiphysics/Kratos/wiki/Windows-Install-(MinGW) @AlejandroCornejo

**Pull request merged**
