### PR TITLE
[StructuralMechanicsApplication] Some compiler warnings  fixes

### LINKED ISSUE #2710: [StructuralMechanics] some compiler warnings
I would have fixed them myself but I don't know how
related to #2612 
~~~
/home/philippb/software/Kratos_Master/applications/StructuralMechanicsApplication/custom_processes/spr_error_process.cpp:275:61: warning: attribute ignored in explicit instantiation ‘class Kratos::SPRErrorProcess<2ul>’ [-Wattributes]
 template KRATOS_API(STRUCTURAL_MECHANICS_APPLICATION) class SPRErrorProcess<2>;
                                                             ^
/home/philippb/software/Kratos_Master/applications/StructuralMechanicsApplication/custom_processes/spr_error_process.cpp:275:61: note: no attribute can be applied to an explicit instantiation
/home/philippb/software/Kratos_Master/applications/StructuralMechanicsApplication/custom_processes/spr_error_process.cpp:276:61: warning: attribute ignored in explicit instantiation ‘class Kratos::SPRErrorProcess<3ul>’ [-Wattributes]
 template KRATOS_API(STRUCTURAL_MECHANICS_APPLICATION) class SPRErrorProcess<3>;
                                                             ^
/home/philippb/software/Kratos_Master/applications/StructuralMechanicsApplication/custom_processes/spr_error_process.cpp:276:61: note: no attribute can be applied to an explicit instantiation
~~~

and

~~~
/home/philippb/software/Kratos_Master/applications/StructuralMechanicsApplication/custom_processes/spr_error_process.cpp: In instantiation of ‘void Kratos::SPRErrorProcess<TDim>::CalculateSuperconvergentStresses() [with long unsigned int TDim = 2ul]’:
/home/philippb/software/Kratos_Master/applications/StructuralMechanicsApplication/custom_processes/spr_error_process.cpp:275:61:   required from here
/home/philippb/software/Kratos_Master/applications/StructuralMechanicsApplication/custom_processes/spr_error_process.cpp:119:60: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
                 for(IndexType i_node_loop = 0; i_node_loop < num_nodes; ++i_node_loop) { // FIXME: Avoid this double loop, extreamily expensive
                                                            ^
/home/philippb/software/Kratos_Master/applications/StructuralMechanicsApplication/custom_processes/spr_error_process.cpp: In instantiation of ‘void Kratos::SPRErrorProcess<TDim>::CalculateSuperconvergentStresses() [with long unsigned int TDim = 3ul]’:
/home/philippb/software/Kratos_Master/applications/StructuralMechanicsApplication/custom_processes/spr_error_process.cpp:276:61:   required from here
/home/philippb/software/Kratos_Master/applications/StructuralMechanicsApplication/custom_processes/spr_error_process.cpp:119:60: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
~~~

### PR DESCRIPTION
**Pull request by loumalouomega**
Fixes #2710

### CODE REVIEW

**Comment by loumalouomega** [comment]
Can you try again the cpp tests?, I don't have any problem

**Review by philbucher — APPROVED** [review]
Compiler-warnings are gone, now running the tests

**Comment by philbucher** [comment]
test still fails:
~~~
Ran 27 of 439 test cases in 0.006655s. 1 failed:
    TestTestSPRErrorProcess2 Failed with message: 
        Error: Check failed because (0.122409 - process_info[ERROR_OVERALL])/0.122409 is greater than 1.0e-5
in /home/philippb/software/Kratos_prod/applications/StructuralMechanicsApplication/tests/cpp_tests/test_spr_error_process.cpp:286:virtual void Testing::TestTestSPRErrorProcess2::TestFunction()
~~~

**Comment by loumalouomega** [comment]
imagen
Mine works, can you try with one thread (I am running with 4, but maybe is failing because of that)

**Comment by philbucher** [comment]
Hm for me it fails with any number of threads

**Comment by loumalouomega** [comment]
Huuuuum, it is giving always the same error?, did you compile the meshing?

**Comment by philbucher** [comment]
Yep always the same
With and without meshing compiled
with 1 and many threads

**Comment by loumalouomega** [comment]
Huuum, which compiler?, here using clang

**Comment by philbucher** [comment]
Default in ubuntu 16.02: GCC 5.4

**Comment by philbucher** [comment]
Do you have an idea where sth could go wrong?

**Comment by loumalouomega** [comment]
I don't have a clue, can you try with clang, GCC 5 have some problematic (I know because CUDA only works with GCC 5 and I have several problem because of that)

**Comment by RiccardoRossi** [comment]
gcc 5 must work...as well as gcc 4.9...

are u guys sure it is not a tolerance problem?

**Comment by philbucher** [comment]
I think it is a tolerance-issue, my machine sometimes behaves slightly different

**Comment by loumalouomega** [comment]
Are you a 32 bit person?

**Comment by philbucher** [comment]
what an insult!
ofc not xD

**Comment by philbucher** [comment]
merging since I need this for #2709

**Comment by RiccardoRossi** [comment]
...you should not merge if the test fails... that can break travis if at some point we activate tests in your app.

**Comment by philbucher** [comment]
the failing test is already in master (in StructuralMechanics), this PR was only to remove some compiler warnings

in any case, I will open an issue EDIT: => #2715

**Pull request merged**
