### PR TITLE
Warning in constructor with Builder and Solver

### PR DESCRIPTION
**Pull request by rubenzorrilla**
A warning apperared in the constructor with Builder and Solver since mReformDofSetAtEachStep was assigned as mReformDofSetAtEachStep. Now the value of mReformDofSetAtEachStep is set according to the constructor value.

### CODE REVIEW

**Comment by rubenzorrilla** [comment]
@longchentum @RiccardoRossi this is still pending...

**Comment by rubenzorrilla** [comment]
@RiccardoRossi ping!

**Review by loumalouomega — APPROVED** [review]
Alright

**Review by pooyan-dadvand — COMMENTED** [review]
👍

**Pull request merged**
