### PR TITLE
[Strucutral] adding Check in test

### PR DESCRIPTION
**Pull request by philbucher**
the test fails in FullDebug, you didn't add the `Check` call

this will not compile now, please take a look

### CODE REVIEW

**Comment by KlausBSautter** [comment]
thanks @philbucher. I guess this
https://github.com/KratosMultiphysics/Kratos/blob/9951c84941173db559a6ad8e9b0199375e4be717/applications/StructuralMechanicsApplication/tests/cpp_tests/test_membrane.cpp#L23-L29

should fix it

**Comment by KlausBSautter** [comment]
> this will not compile now, please take a look

but I had no problem compiling it

**Comment by inigolcanalejo** [comment]
looks good to me

**Comment by KlausBSautter** [comment]
the tests failed in the automated testing.... strange

**Comment by KlausBSautter** [comment]
@philbucher, I can't reproduce this on my machine.

> Running cpp tests
Ran 1335 of 1463 test cases in 20.0798s. OK
corrupted size vs. prev_size
Aborted (core dumped)
##[error]Process completed with exit code 134.

**Comment by philbucher** [comment]
thats the problem if I run the tests:
~~~
    TestMembraneElement3D3N Failed with message: 
        Error: Check failed because vector relative_error with values
[81](1.46272e-07,9.98607e-11,7.42666e-11,1.38848e-07,5.24272e-11,1.11143e-11,1.546e-07,1.38483e-10,1.64954e-10,9.98607e-11,1.37799e-07,7.96259e-11,7.57995e-11,1.93889e-07,5.50226e-11,5.57454e-11,1.06912e-07,1.34501e-11,2.56439e-10,1.17536e-10,2.56644e-07,7.58107e-11,2.45766e-10,3.09843e-07,1.86351e-11,3.24458e-10,2.19107e-07,6.94375e-08,4.8331e-10,3.21559e-10,9.63228e-08,1.36216e-10,1.8076e-11,1.51967e-10,3.68221e-10,5.44484e-10,3.3914e-10,9.69199e-08,2.88361e-10,4.49006e-11,1.41818e-07,1.03024e-10,2.72377e-10,1.24621e-10,4.7442e-10,6.36844e-10,2.65953e-10,1.54982e-07,3.34607e-10,2.97299e-10,2.51739e-07,1.45162e-10,2.01469e-10,1.33376e-10,7.73033e-08,5.82428e-11,2.87426e-12,1.13226e-10,8.87327e-11,4.08752e-11,1.12603e-07,1.6304e-10,1.35015e-10,1.34145e-10,5.3407e-08,1.77097e-10,5.64514e-11,1.63557e-10,2.06306e-11,1.0259e-10,6.47683e-08,2.07592e-10,5.72001e-10,3.839e-10,1.09561e-07,1.87879e-10,2.5524e-10,1.27795e-10,8.01754e-10,3.60059e-10,1.5045e-07)
Is not near vector expected_relative_error with values
[1.46272e-07, 1.01309e-10, 1.7542e-10, 1.38848e-07, 5.24272e-11, 1.11143e-11, 1.546e-07, 1.38483e-10, 4.36637e-11, 9.98607e-11, 1.37799e-07, 7.96259e-11, 4.13558e-11, 1.93889e-07, 7.57346e-11, 5.57454e-11, 1.06912e-07, 1.22961e-10, 1.48198e-10, 4.76131e-10, 2.56644e-07, 7.58107e-11, 2.45766e-10, 3.09843e-07, 1.86351e-11, 3.24458e-10, 2.19107e-07, 6.94375e-08, 4.53837e-10, 3.21559e-10, 9.63228e-08, 1.36216e-10, 1.80921e-11, 1.51967e-10, 5.95519e-10, 5.44484e-10, 3.3914e-10, 9.69199e-08, 2.88361e-10, 4.4912e-11, 1.41818e-07, 1.03024e-10, 2.72377e-10, 1.24621e-10, 4.7442e-10, 6.36844e-10, 1.31188e-09, 1.54982e-07, 3.34607e-10, 4.79801e-10, 2.51739e-07, 6.5135e-10, 1.80061e-09, 1.33376e-10, 7.7201e-08, 2.9421e-10, 2.87426e-12, 2.76943e-10, 3.00404e-10, 2.12235e-10, 1.12454e-07, 1.38858e-10, 1.98338e-10, 1.34145e-10, 5.35485e-08, 3.15205e-10, 5.64514e-11, 1.63557e-10, 2.06306e-11, 1.0259e-10, 6.47683e-08, 1.26292e-10, 1.54817e-10, 3.839e-10, 1.09561e-07, 1.87879e-10, 2.5524e-10, 1.27795e-10, 1.35031e-10, 3.60059e-10, 1.5045e-07]
Mismatch found in component 1:
9.98607e-11 not near 1.01309e-10 within relative tolerance 1e-05.

in /home/philippb/software/Kratos_prod/applications/StructuralMechanicsApplication/tests/cpp_tests/test_membrane.cpp:112:virtual void Testing::TestMembraneElement3D3N::TestFunction()

    TestMembraneElement3D4N Failed with message: 
        Error: Check failed because vector relative_error with values
[144](7.83999e-08,2.07661e-11,2.85724e-10,1.19754e-07,8.65071e-10,2.89525e-11,6.33064e-08,2.82743e-10,1.74072e-10,7.2825e-08,6.42001e-10,2.88665e-10,3.33604e-10,6.68996e-08,2.00192e-10,4.53289e-09,4.32224e-07,2.7898e-09,2.27917e-10,5.86098e-08,8.7405e-11,4.75574e-11,3.37453e-08,5.11246e-10,1.89339e-10,5.48483e-10,1.30489e-07,1.03838e-09,2.25407e-09,3.2299e-05,4.0335e-10,9.35853e-11,1.21407e-07,1.93356e-10,2.52909e-10,6.80807e-08,1.19369e-07,1.68719e-08,2.34604e-09,1.88332e-07,2.8173e-10,7.03615e-10,3.79648e-07,4.00185e-10,3.32229e-10,2.00084e-07,1.4725e-09,1.6338e-08,1.42023e-09,4.33054e-07,5.17739e-11,1.55683e-10,1.19192e-07,1.9482e-11,1.20997e-10,7.45499e-08,1.74085e-10,1.35033e-09,7.50741e-08,3.79546e-10,1.08822e-09,8.94358e-09,3.24597e-05,1.96137e-10,3.07522e-10,3.59943e-07,5.85245e-09,6.71526e-10,2.7272e-07,1.00948e-08,4.0224e-10,2.25422e-07,6.34281e-08,4.35143e-10,9.80188e-10,3.78726e-07,9.22299e-10,5.11919e-10,1.51191e-07,4.39806e-10,1.56239e-10,8.05854e-06,4.61837e-11,1.43498e-09,2.45672e-10,5.8201e-08,4.41583e-11,1.18456e-10,7.45737e-08,3.29172e-10,4.67768e-11,1.12637e-07,7.96767e-11,3.50898e-10,1.97563e-07,3.7942e-09,1.02271e-10,4.02299e-10,1.21535e-07,1.35096e-09,3.54967e-10,2.72596e-07,4.18195e-10,3.41251e-10,3.05914e-07,8.06141e-10,2.40174e-09,3.57271e-07,7.30872e-08,7.78619e-10,3.12537e-10,2.00391e-07,1.30849e-09,1.19542e-09,8.16507e-06,1.21762e-09,1.98132e-10,1.60951e-07,1.13284e-10,7.20921e-10,8.85562e-11,3.3535e-08,2.30117e-10,2.43833e-10,7.4882e-08,3.67425e-12,1.27725e-09,1.97588e-07,9.34133e-10,4.73999e-10,7.85588e-08,1.15703e-10,1.25474e-10,4.97367e-10,6.78623e-08,1.12826e-08,6.10938e-11,2.24558e-07,8.04859e-10,5.16429e-09,3.56122e-07,4.28199e-10,8.84211e-11,1.84727e-07)
Is not near vector expected_relative_error with values
[7.83999e-08, 2.07838e-11, 2.85724e-10, 1.19805e-07, 2.53715e-09, 6.58355e-10, 6.34008e-08, 5.77027e-11, 3.9188e-10, 7.30737e-08, 2.26601e-10, 2.88665e-10, 1.56401e-10, 6.67553e-08, 2.00164e-10, 3.7924e-09, 4.32224e-07, 2.78981e-09, 3.98132e-10, 5.89574e-08, 2.76404e-10, 1.40101e-10, 3.35175e-08, 1.16888e-10, 5.6946e-10, 5.4851e-10, 1.3056e-07, 2.87022e-10, 2.06904e-12, 3.2299e-05, 4.79543e-10, 9.35669e-11, 1.21407e-07, 1.03257e-09, 2.52929e-10, 6.84278e-08, 1.20185e-07, 1.68722e-08, 9.15427e-10, 1.88326e-07, 3.92703e-10, 5.80919e-11, 3.79004e-07, 7.25958e-10, 8.25508e-10, 2.00979e-07, 1.47245e-09, 1.6338e-08, 1.42025e-09, 4.38993e-07, 6.80859e-09, 2.92253e-11, 1.19192e-07, 4.58938e-11, 1.20997e-10, 7.48042e-08, 1.48577e-10, 3.63387e-09, 7.41823e-08, 1.16976e-11, 1.08821e-09, 8.9436e-09, 3.25153e-05, 3.11555e-10, 4.59753e-11, 3.59894e-07, 2.29186e-09, 6.19311e-10, 2.72257e-07, 1.00945e-08, 1.85752e-09, 2.25757e-07, 6.36167e-08, 2.45672e-10, 9.80188e-10, 3.78806e-07, 1.66561e-10, 3.77833e-10, 1.51191e-07, 1.15385e-10, 4.436e-10, 8.086e-06, 4.61353e-11, 1.95153e-10, 2.45672e-10, 5.88961e-08, 1.05936e-09, 4.80807e-11, 7.45737e-08, 1.67813e-10, 2.08987e-10, 1.12515e-07, 5.10433e-11, 1.02384e-09, 1.9622e-07, 7.09616e-10, 1.02271e-10, 1.0528e-09, 1.21355e-07, 7.72253e-10, 3.54967e-10, 2.72712e-07, 4.1818e-10, 1.81686e-10, 3.05914e-07, 8.06128e-10, 1.81512e-09, 3.57271e-07, 7.28385e-08, 7.78619e-10, 3.12537e-10, 2.00335e-07, 3.25997e-09, 4.32728e-09, 8.16507e-06, 1.47387e-09, 7.04346e-10, 1.60776e-07, 1.28813e-09, 1.48714e-09, 3.26769e-10, 3.37628e-08, 6.24457e-10, 7.40437e-10, 7.46591e-08, 9.46029e-11, 3.09336e-10, 1.9826e-07, 9.3412e-10, 1.80188e-10, 7.87286e-08, 2.51837e-10, 1.04632e-09, 4.97367e-10, 6.78623e-08, 7.14672e-09, 3.06683e-10, 2.24474e-07, 2.04464e-09, 3.84428e-09, 3.56122e-07, 1.10454e-09, 3.60626e-10, 1.84727e-07]
Mismatch found in component 1:
2.07661e-11 not near 2.07838e-11 within relative tolerance 1e-05.
~~~

**Comment by philbucher** [comment]
ping @inigolcanalejo @KlausBSautter I cannot approve myself :)

**Review by KlausBSautter — APPROVED** [review]

**Pull request merged**
