### PR TITLE
[Release 8.0] Porting #6984

### PR DESCRIPTION
**Pull request by roigcarlo**
This was not automatic.

Can you check that no other PR is missing for the MPM app since the creation of Release 8.0¿?

### CODE REVIEW

**Comment by roigcarlo** [comment]
Ping @KratosMultiphysics/mpm

**Comment by roigcarlo** [comment]
Was https://github.com/KratosMultiphysics/Kratos/pull/6898?

**Comment by roigcarlo** [comment]
Closing since nobody answered. I understand this is due for 8.1 now.

**Comment by tteschemacher** [comment]
Sorry I haven't seen it before. It's fine to go for 8.1, but what exactly was the problem?

**Comment by roigcarlo** [comment]
#6984 was marked to be ported to 8.0, but that PR was done after a change (I believe #6898) which was merged after the Release branch was created, so I couldn't cherry pick it directly into the release.

Anyway since release is already done we could move this to a possible 8.0.1 or 8.1.

**Comment by tteschemacher** [comment]
ok, perfect. Sorry again. I haven't seen it. In either case there is no hurry to add it. But there is no bug that we'll need to fix?

**Comment by roigcarlo** [comment]
No, I mean, the Release has de old code (not sure if it is a bug or an improvement), but the new one will have the fix as it is already in the master.

**Pull request closed without merging**
