### PR TITLE
[MPICore] write partitioned files in folder

### PR DESCRIPTION
**Pull request by philbucher**
**Description**
As the title says. By default the partitioned files are written directly in the working directory, which creates a huge mess for many cores
With this PR they are written to a folder, using our ghc::filesystem. I admit this is not the best solution, but since now moving to C++17 is within reach I think it can be accepted

I made the necessary adaptions to the import utility
Furthermore the tests in the MPICore were cleaned a bit and updated

Unfortunately it is not possible as of now to specify the folder, this would require more refactoring. In any case I think this solution should already improve a lot the current situation

FYI @KratosMultiphysics/altair not sure if this is relevant for you

### CODE REVIEW

**Comment by philbucher** [comment]
ok now it should work properly, I updated the description of the PR

**Comment by adityaghantasala** [comment]
Thanks for the improvement. I faced and still face this issue. 
My solution was to put the initial ".mdpa" file into a spearate folder under the working directory. Then the partitioned "mdpa"s are also written into that folder with out making a mess of the working directory.  This may not be THE solution but it was easy way out.

**Comment by philbucher** [comment]
thanks for sharing @adityaghantasala this also sounds like a viable solution, I simply didn't think about this one :)

**Comment by marcnunezc** [comment]
I just want to say that I find this very useful as well!

**Comment by philbucher** [comment]
as an alternative to hardcoding this behavior I could introduce a flag to maintain the current behavior by default
Sth like `WRITE_PARTITIONED_FILES_IN_FOLDER`

For reference the `IO` flags
https://github.com/KratosMultiphysics/Kratos/blob/66f1a277ecf2b06e5a53202ea7b4f6a5dd7142d0/kratos/includes/io.h#L70-L76

I would like some opinions on this, can you please react to this post with:
- :+1: for adding the flag and keeping the current behavior
- :-1: for NOT adding the flag and ALWAYS writing the partitioned files in a folder

**Comment by roigcarlo** [comment]
> I would like some opinions on this, can you please react to this post with:

    +1 for adding the flag and keeping the current behavior
    -1 for NOT adding the flag and ALWAYS writing the partitioned files in a folder

I voted for the :-1: but I would add another option to add flags but with the new behavior as default, with `WRITE_PARTITIONED_FILES_WITHOUT_FOLDER` or something

**Comment by rubenzorrilla** [comment]
Which is the reasoning behing keeping the old behaviour? Taking into account that this change is retro-compatible by definition, as it only affect those files that are to be partitioned, I'd vote for changing it if there is no strong opinion against.

**Comment by roigcarlo** [comment]
I think the only case would be if you already have a pre-partitoned case prior to this change. But moving the files would do just fine.

To be honest I can't come up with a any other situation when the old behavior would be better, I just wanted to leave doors open just in case, but I doubt I'd use it.

**Comment by philbucher** [comment]
I am perfectly fine with only having the new behavior, just thought I'd ask :)
then I leave it as is

**Comment by philbucher** [comment]
I added the behavior changed flag

**Comment by philbucher** [comment]
Since the reactions were very positive I propose the following:
- merge this PR as is
- if someone complains or this gives other problems I can still add the flag to restore the original behavior

**Comment by philbucher** [comment]
anyone approves? :)

**Review by roigcarlo — APPROVED** [review]

**Comment by roigcarlo** [comment]
Seems it has conflicts :S

**Comment by philbucher** [comment]
> Seems it has conflicts :S

I shouldn't modify the same files in multiple PRs :)

can you repprove pls?

**Review by roigcarlo — APPROVED** [review]

**Pull request merged**
