### PR TITLE
[HDF5] Cotire compilation

### PR DESCRIPTION
**Pull request by sunethwarna**
Hi, this is the first attempt to get HDF5Application to compile in cotire. I'm not sure the way i added the application is correct or not to the git workflow. How do we specify the HDF library paths? Are they available by default in CI?

I changed the annonymous method names to unique ones so that cotire would not complain.

All the tests in FluidDynamics and HDF5 are passsing (including the adjoint tests)

### CODE REVIEW

**Review by philbucher — APPROVED** [review]
Perfect!
If it compiles locally then it should also compile in the CI
I took care abt the installation of the hdf-libs already, it should be found automatically 

I am curious, why did you choose to rename the fcts instead of excluding the problematic files from cotire?

**Comment by sunethwarna** [comment]
The CI is failing with exit code 1, and doesn't show any errors. :|

**Comment by sunethwarna** [comment]
I changed the names since, these are local, and the name changes makes more sense in my opinion... Is it better to remove them from cotire?

**Comment by philbucher** [comment]
> The CI is failing with exit code 1, and doesn't show any errors. :|

but it worked ...
I also thought it showed an error, but now seems ok

**Comment by sunethwarna** [comment]
For me it failed, but I restarted it again, then it somehow worked... :) :) Thanks @philbucher

**Pull request merged**
