### PR TITLE
fix CableNetApp after #6686

### PR DESCRIPTION
**Pull request by philbucher**
@roigcarlo can you please port this to the release branch?
Thx

necessary for #6994

### CODE REVIEW

**Comment by roigcarlo** [comment]
Mmm that will have to go for 8.1 I can't modify the tag now.

We plan it for net week or so anyway

**Comment by RiccardoRossi** [comment]
anyhow, we will also need fixes for mpm in the 8.1

**Comment by philbucher** [comment]
ok no problem :)

**Comment by philbucher** [comment]
this will no longer be needed after #6994

**Review by KlausBSautter — APPROVED** [review]
thanks

**Pull request merged**
