### PR TITLE
[Core] missing include

### LINKED ISSUE #7800: [Windows] Compilation ERROR
I've just updated the master and i get this error when compiling:

`D:\KRATOS_MULTIPHYSICS\Kratos\kratos\utilities\file_name_data_collector.cpp(107): error C2039: 'isdigit': no es un miembro de 'std' [D:\KRATOS_MULTIPHYSICS\Kratos\build\Release\kratos\Kr
atosCore.vcxproj]`

and

`D:\KRATOS_MULTIPHYSICS\Kratos\kratos\utilities\file_name_data_
collector.cpp(458): error C2039: 'isdigit': no es un miembro d e 'std' [D:\KRATOS_MULTIPHYSICS\Kratos\build\Release\kratos\Kr atosCore.vcxproj]`

Any ideas?

(no es un miembro de == it's not a member of)

### PR DESCRIPTION
**Pull request by philbucher**
**Description**
closes #7800 

can you please try @AlejandroCornejo ?

### CODE REVIEW

**Comment by AlejandroCornejo** [comment]
> 
> 
> **Description**
> closes #7800
> 
> can you please try @AlejandroCornejo ?

Now the file compiles, I'll confirm when the whole compilation is done :D

**Review by sunethwarna — APPROVED** [review]
thanks @philbucher. I am still wondering how it was able to compile this in windows CI?

**Review by AlejandroCornejo — APPROVED** [review]
Now it compiles! THX

**Comment by philbucher** [comment]
> thanks @philbucher. I am still wondering how it was able to compile this in windows CI?

cotire :)

**Pull request merged**
