### PR TITLE
[Core] Add fill methods to AMatrix

### PR DESCRIPTION
**Pull request by pooyan-dadvand**
This PR adds two new methods `fill` and `fill_identity` to the kratos AMatrix matrix. The tests are in AMatrix and not migrated here. 

@jcotela would you please check if this works for you?

### CODE REVIEW

**Comment by jcotela** [comment]
@pooyan-dadvand I had to change a type to be able to compile (with gcc, if it is relevant).
The fill_identity method works in non-square matrices, but it gives rather counter-intuitive results
```
import KratosMultiphysics as k
>>> b = k.Matrix(2,3)
>>> print(b)
[2,3]((4.64501e-310,5.72939e-313,6.91203e-310),(6.91203e-310,0,1.0854e-71))
>>> b.fill(-1)
>>> print(b)
[2,3]((-1,-1,-1),(-1,-1,-1))
>>> b.fill_identity()
>>> print(b)
[2,3]((1,0,0),(1,0,0))
```
Should we fix it or just disallow it for non-square matrices?

**Comment by jcotela** [comment]
@pooyan-dadvand I have added a fill method for vectors and ublas equivalents for backwards compatibility, so that tests can be migrated safely.

**Comment by jcotela** [comment]
@pooyan-dadvand The tests for vectors in `test_vector_interface.py` currently test for slicing options that are not supported by AMatrix:
```python
        slice4 = v[0::2] # slice get with step
        self.assertEqual(len(slice4),3)
        for i,value in enumerate(slice4):
            self.assertEqual(value, 2*i )

        slice5 = v[::-1] # slice get with reverse step
        self.assertEqual(len(slice5),5)
        for i,value in enumerate(slice5):
            self.assertEqual(value, 4-i )
```
both fail with a message stating that `The AMatrix only supports continuous slices with step == 1`. Should we remove those tests, mark them as expected errors or something else entirely?

**Comment by jcotela** [comment]
@pooyan-dadvand as discussed, I have removed the tests for unsupported slicing and added a check in fill_identity. I'm not sure if a debug check would be better, but I guess that this one is rare enough that a release check should not affect performance too much.

**Review by RiccardoRossi — APPROVED** [review]

**Comment by pooyan-dadvand** [comment]
Thanks @jcotela for improving it

**Pull request merged**
