### PR TITLE
[Core] default echo-level = 0

### LINKED ISSUE #3357: Too many echo_level
Hi you all,

I'm having a problem when trying to write some ProblemParameters.json files, related with que quantity of **echo_level** entries that, for some reason, **MUST** be placed. 

For example: 

- In a simple 2D CFD case, echo_level appears inside `problem_data `and in `solver_settings`. 
- In a 2D FSI case, whose ProjectParameters contains informaton for both Fluid and Structural, echo_level appears 5 times:
    - problem_data > echo_level
    - solver_settings > echo_level
    - solver_settings > structure_solver_settings  > echo_level
    - solver_settings > fluid_solver_settings> echo_level
    - solver_settings > mesh_solver_settings> echo_level
- In the new Conjugate heat transfer application, that contains Buoyancy (Fluid + Convection diffusion) and Convection diffusion (yes, again), we have 3 application, so guess what:
    - problem_data > echo_level
    - solver_settings > echo_level
    - solver_settings > fluid_domain_solver_settings> echo_level
    - solver_settings > fluid_domain_solver_settings > fluid_solver_settings> echo_level
    - solver_settings > fluid_domain_solver_settings > thermal_solver_settings> echo_level
    - solver_settings > solid_domain_solver_settings> thermal_solver_settings> echo_level
    - solver_settings > coupling_settings > echo_level

And I still get this error message:

 ```
 File "E:\KratosDeploy\applications\convection_diffusion_application\python_scripts\conjugate_heat_transfer_solver.py", line 28, in __init__
    super(ConjugateHeatTransferSolver, self).__init__(model, custom_settings)
  File "E:\KratosDeploy\kratos\python_scripts\python_solver.py", line 34, in __init__
    self.echo_level = self.settings["echo_level"].GetInt()
RuntimeError: Error: --------- ERROR : --------- getting a value that does not exist. entry string : echo_level

in kratos/includes/kratos_parameters.h:251:Parameters::GetValue
```

Of course, the user interface SHOULD NOT ask the user all this echo_levels. I think that if a user needs to set different values for this variable in more than 5 places, it can be done by editing manually the json file. 

BUT (as a conclusion), would it be possible to have a default value for all the echo_level in kratos? I mean, If I erase (or forget, or consider not necessary) that entry in a json file, **it should never throw an error, just take 0 as default**.

@KratosMultiphysics/kratos-core-team

### PR DESCRIPTION
**Pull request by philbucher**
fixes #3357

### CODE REVIEW

**Review by loumalouomega — DISMISSED** [review]
imagen

**Comment by jcotela** [comment]
Not opposed to the change, but note that setting an `echo_level` in the default parameters of the solvers will always silently override this "default". Conversely, not setting an `echo_level` in the default parameters of the solver will not allow the user to override the default at all... (it would be an error in json validation).

**Comment by philbucher** [comment]
@jcotela this is unfortunate :/
Plus this way we have to validate the settings before we call the baseclass.constructor, otherwise the echo_level from the derived solver will be ignored

**Comment by philbucher** [comment]
I took a closer look and I think this is basically the same problem we are also having in other places => validating settings in derived classes

The proper solution would be to implement #2241 and solve this properly. This would also help if more settings are added to the Base-classes, bcs then we would have the same problem again.

**Conclusion:** I suggest to wait until #2241 is implemented (which itself is waiting for #58 )

**Comment by jginternational** [comment]
😢

**Comment by RiccardoRossi** [comment]
question is the split of validate and assign already implementing a function proposed by Armin equivlaent to a merge?

**Comment by philbucher** [comment]
I will try once PR #3889 of @armingeiser is merged

**Comment by philbucher** [comment]
closing since this is solved properly in #4736

**Pull request closed without merging**
