### PR TITLE
[PoroApp] Warning removed (deprecated NR constructor)

### PR DESCRIPTION
**Pull request by ipouplana**
**Description**
This PR adds removes a deprecation warning from the Nethon-Raphson strategy (constructor with linear solver).

**Changelog**

- The NR and Arc-Length strategies from PoromechanicsApp. now use the core NR strategy without linear solver in the arguments.
- The construction of the strategy in the Poromechanics Solver has been updated to account for this change.

### CODE REVIEW

**Review by philbucher — APPROVED** [review]
:+1:

**Comment by RiccardoRossi** [comment]
@ipouplana as a minor comment, take into account that the option of using old stiffness in first iteration should be very useful in your applications

**Comment by philbucher** [comment]
FYI @roigcarlo @RiccardoRossi this threw an error in the MPICore with Clang in Fulldebug:
~~~
/lib/x86_64-linux-gnu/libc.so.6(+0x46210)[0x7efd03f17210]
/__w/Kratos/Kratos/bin/FullDebug/libs/Kratos.cpython-38-x86_64-linux-gnu.so(_ZNKSt8equal_toIiEclERKiS2_+0x1a)[0x7efd025aeb6a]
/__w/Kratos/Kratos/bin/FullDebug/libs/Kratos.cpython-38-x86_64-linux-gnu.so(_ZNSt8__detail13_Equal_helperIiSt4pairIKiSt6vectorIiSaIiEEENS_10_Select1stESt8equal_toIiEmLb0EE9_S_equalsERKS9_RKS7_RS2_mPNS_10_Hash_nodeIS6_Lb0EEE+0x5c)[0x7efd025aeafc]
/__w/Kratos/Kratos/bin/FullDebug/libs/Kratos.cpython-38-x86_64-linux-gnu.so(_ZNKSt8__detail15_Hashtable_baseIiSt4pairIKiSt6vectorIiSaIiEEENS_10_Select1stESt8equal_toIiESt4hashIiENS_18_Mod_range_hashingENS_20_Default_ranged_hashENS_17_Hashtable_traitsILb0ELb0ELb1EEEE9_M_equalsERS2_mPNS_10_Hash_nodeIS6_Lb0EEE+0x50)[0x7efd025aea60]
/__w/Kratos/Kratos/bin/FullDebug/libs/Kratos.cpython-38-x86_64-linux-gnu.so(_ZNKSt10_HashtableIiSt4pairIKiSt6vectorIiSaIiEEESaIS5_ENSt8__detail10_Select1stESt8equal_toIiESt4hashIiENS7_18_Mod_range_hashingENS7_20_Default_ranged_hashENS7_20_Prime_rehash_policyENS7_17_Hashtable_traitsILb0ELb0ELb1EEEE19_M_find_before_nodeEmRS1_m+0x6a)[0x7efd025ae98a]
/__w/Kratos/Kratos/bin/FullDebug/libs/Kratos.cpython-38-x86_64-linux-gnu.so(_ZNKSt10_HashtableIiSt4pairIKiSt6vectorIiSaIiEEESaIS5_ENSt8__detail10_Select1stESt8equal_toIiESt4hashIiENS7_18_Mod_range_hashingENS7_20_Default_ranged_hashENS7_20_Prime_rehash_policyENS7_17_Hashtable_traitsILb0ELb0ELb1EEEE12_M_find_nodeEmRS1_m+0x2d)[0x7efd025ae3dd]
/__w/Kratos/Kratos/bin/FullDebug/libs/libKratosCore.so(_ZNSt8__detail9_Map_baseIiSt4pairIKiSt6vectorIiSaIiEEESaIS6_ENS_10_Select1stESt8equal_toIiESt4hashIiENS_18_Mod_range_hashingENS_20_Default_ranged_hashENS_20_Prime_rehash_policyENS_17_Hashtable_traitsILb0ELb0ELb1EEELb1EEixEOi+0x56)[0x7efd00ae3c06]
/__w/Kratos/Kratos/bin/FullDebug/libs/libKratosCore.so(_ZNSt13unordered_mapIiSt6vectorIiSaIiEESt4hashIiESt8equal_toIiESaISt4pairIKiS2_EEEixEOi+0x2d)[0x7efd00478d1d]
/__w/Kratos/Kratos/bin/FullDebug/libs/libKratosCore.so(+0x1447504)[0x7efd00116504]
/__w/Kratos/Kratos/bin/FullDebug/libs/libKratosCore.so(+0x1447925)[0x7efd00116925]
/lib/x86_64-linux-gnu/libomp.so.5(__kmp_invoke_microtask+0x93)[0x7efcfea9f5f3]
/lib/x86_64-linux-gnu/libomp.so.5(+0x45e45)[0x7efcfea38e45]
/lib/x86_64-linux-gnu/libomp.so.5(__kmp_fork_call+0x23cd)[0x7efcfea3172d]
/lib/x86_64-linux-gnu/libomp.so.5(__kmpc_fork_call+0x181)[0x7efcfea214b1]
/__w/Kratos/Kratos/bin/FullDebug/libs/libKratosCore.so(_ZN6Kratos41FindGlobalNodalElementalNeighboursProcess15GetNeighbourIdsERNS_16PointerVectorSetINS_4NodeILm3ENS_3DofIdEEEENS_13IndexedObjectESt4lessImESt8equal_toImENS_13intrusive_ptrIS5_EESt6vectorISC_SaISC_EEEE+0x127)[0x7efd00115f07]
/__w/Kratos/Kratos/bin/FullDebug/libs/Kratos.cpython-38-x86_64-linux-gnu.so(+0x11c224a)[0x7efd030b124a]
/__w/Kratos/Kratos/bin/FullDebug/libs/Kratos.cpython-38-x86_64-linux-gnu.so(+0x11c2198)[0x7efd030b1198]
/__w/Kratos/Kratos/bin/FullDebug/libs/Kratos.cpython-38-x86_64-linux-gnu.so(+0x11c1e6f)[0x7efd030b0e6f]
/__w/Kratos/Kratos/bin/FullDebug/libs/Kratos.cpython-38-x86_64-linux-gnu.so(+0x11c1d0d)[0x7efd030b0d0d]
/__w/Kratos/Kratos/bin/FullDebug/libs/Kratos.cpython-38-x86_64-linux-gnu.so(+0x11c1c55)[0x7efd030b0c55]
/__w/Kratos/Kratos/bin/FullDebug/libs/Kratos.cpython-38-x86_64-linux-gnu.so(+0x258cee)[0x7efd02147cee]
python3(PyCFunction_Call+0x59)[0x5f4249]
python3(_PyObject_MakeTpCall+0x296)[0x5f46d6]
python3[0x50a9a3]
python3(_PyEval_EvalFrameDefault+0x5736)[0x570286]
python3[0x50a14e]
python3(_PyEval_EvalFrameDefault+0x71e)[0x56b26e]
python3(_PyFunction_Vectorcall+0x1b6)[0x5f7146]
python3(_PyEval_EvalFrameDefault+0x849)[0x56b399]
python3(_PyEval_EvalCodeWithName+0x26a)[0x56955a]
~~~

I haven't seen this one yet, lets watch it

**Comment by roigcarlo** [comment]
@philbucher sorry I am out of context, when does this error appears? Its only Poro related?

**Comment by philbucher** [comment]
I am not sure, the output is usually a bit messed up, but probably while running the MPI-Core cpp tests
In any case it is not Poro related (Poro is not in the CI afaik)

**Pull request merged**
