### PR TITLE
Hotfix variable list

### PR DESCRIPTION
**Pull request by roigcarlo**
This moves the VariableList variable to variables_list_data_value_container. Follow #968 to check why this is done.

### CODE REVIEW

**Comment by roigcarlo** [comment]
Looks it compile, windows still haven't finish, if you approve I'll merge as soon as win has finished. No signs is going to fail anyway...

**Comment by roigcarlo** [comment]
Compiling in win :+1:

**Review by josep-m-carbonell — APPROVED** [review]
It compiles in windows and linux

**Review by pooyan-dadvand — APPROVED** [review]
Nice to delete so many lines!
:+1:

**Pull request merged**
