### PR TITLE
Some bugs

### PR DESCRIPTION
**Pull request by salvalatorre**
Wear, Reactions and Sea Surface bugs. Aesthetics.

### CODE REVIEW

**Comment by salvalatorre** [comment]
@roigcarlo , @pooyan-dadvand:
This is some bug fixes we would like to add to the Release 5.2, how should we proceed?

**Comment by roigcarlo** [comment]
I'll take care

**Comment by salvalatorre** [comment]
Thanks :+1:

**Review by GuillermoCasas — APPROVED** [review]

**Comment by roigcarlo** [comment]
Just don't delete the branch when this is merged pls, then its easier to integrate

**Pull request merged**
