### PR TITLE
the defaults were wrongly set

### PR DESCRIPTION
**Pull request by RiccardoRossi**
correcting the defaults in the interval_utility.

I also this should be cherry picked and added to the release branch

### CODE REVIEW

**Review by rubenzorrilla — APPROVED** [review]

**Comment by rubenzorrilla** [comment]
@roigcarlo Charlie, would you mind to cherrypick this to the release branch?

**Comment by roigcarlo** [comment]
Ok I'll take care of this 👍

**Comment by roigcarlo** [comment]
Btw Grtz for PR #1000 !!! 🎉 🎉 🎉

**Comment by RiccardoRossi** [comment]
yeeee

**Comment by roigcarlo** [comment]
I think I broke something by calling #1001 with the same name as this one. Let me rename and rerun Travis

**Comment by roigcarlo** [comment]
Can we merge this?

**Review by RiccardoRossi — COMMENTED** [review]
i cannot approve it. i think it should be merged

**Pull request merged**
