### PR TITLE
[Core] Kratos Checks for NaN.

### PR DESCRIPTION
**Pull request by manuelmessmer**
**Description**
Finally, I remembered to address issue #7730.

**Changelog**
- Did changes as explained in issue #7730 to catch NaN values in unit tests.
- Add unit test to check if NaN's are really catched.

I did not run all test so far, but I found 1 test in the SMA and 2 tests in the Core that do fail now due to NaN values.

### CODE REVIEW

**Comment by roigcarlo** [comment]
Solution looks good to me, so I am afraid that test failing are indeed test failing because we were checking things wrong before....

**Comment by manuelmessmer** [comment]
@roigcarlo Yes, unfortunately I think you are right.

**Comment by manuelmessmer** [comment]
Any other  comments how we wanna proceed with this? I checked again the CI output and it seems pretty certain that some tests fail due to NaN values. These are:
Core:
- TestMathUtilsMatrixSquareRoot
- TestTetrahedra3D4AverageElementSizeDerivatives
SMA:
- TestConstitutiveLawIntegrateStressPlasticitySmallStrain
ContactSMA:
- TestMixedULMLinearSolverRealSystem
ParticleApplication
- TestParticleMathUtilsEigenValueVectorsCalculation
- TestParticleMathUtilsQRFactorizationCalculation
- TestParticleStressInvariantsUtilsStressInvariantsCalculation

**Comment by roigcarlo** [comment]
I would mark the tests as expected failures, merge this PR and ping the responsible of the different apps in which tests are failing.

I will try to take a look at the core ones, but my knowledge is limited for tests with underlying physics.

**Comment by loumalouomega** [comment]
> I would mark the tests as expected failures, merge this PR and ping the responsible of the different apps in which tests are failing.
> 
> I will try to take a look at the core ones, but my knowledge is limited for tests with underlying physics.

Since when these tests are failing?

**Comment by roigcarlo** [comment]
@manuelmessmer found a bug on how nan values where being tested in #7730, he made the appropiate changes and then those test appear as failures.

**Comment by loumalouomega** [comment]
OK, I will check, strange

**Comment by loumalouomega** [comment]
> @manuelmessmer found a bug on how nan values where being tested in #7730, he made the appropiate changes and then those test appear as failures.

I checked, and there are non NaNs, I don't understand

**Comment by roigcarlo** [comment]
> I checked, and there are non NaNs, I don't understand

```
TestTetrahedra3D4AverageElementSizeDerivatives Failed with message: 
        Error: Check failed because analytical_derivative = 248832 is not near to fd_derivative = -nan within the tolerance 1e-07

```

Several like this one. Changing it to vector will only make it appear for every element of the vector I think

**Comment by loumalouomega** [comment]
I changed the things related to my code, the remaining things are not mine

**Comment by sunethwarna** [comment]
> Several like this one. Changing it to vector will only make it appear for every element of the vector I think

I think some of them are mine, but I specifically tested them before for NaNs, like printing them. Anyways I'll also take a look.

**Comment by sunethwarna** [comment]
I fixed my test. It was a typo (a big typo error) from my side. Thanks to @manuelmessmer PR, it is caught :) :+1:

**Comment by manuelmessmer** [comment]
Now, also all Particle tests should be fixed.

**Comment by philbucher** [comment]
seems like now only one more test is failing:
~~~
TestExplicitSolvingStrategyRungeKutta4 Failed with message: 
        Error: Check failed because p_test_node->FastGetSolutionStepValue(TEMPERATURE) = -nan is not near to 681.238 = 681.238 within the tolerance 0.001
in kratos/tests/cpp_tests/strategies/strategies/test_explicit_strategies.cpp:135:virtual void Testing::TestExplicitSolvingStrategyRungeKutta4::TestFunction()
~~~

ping @rubenzorrilla @riccardotosi

**Comment by manuelmessmer** [comment]
I think, this got a bit lost. @rubenzorrilla @riccardotosi

**Comment by riccardotosi** [comment]
The test has been fixed. @manuelmessmer, let me know if more is needed from my side.

**Comment by manuelmessmer** [comment]
Well now we have some new failing tests. @tteschemacher I guess these are yours?

**Comment by philbucher** [comment]
since this constantly causes conflicts and the checks in the IGAApp are not working anyway I suggest to disable them and fix this PR asap before new conflicts arise

@tteschemacher is that ok for you?

**Comment by tteschemacher** [comment]
Yes, sure. But please let's deactivate only the cpp tests. Is that possible?

Especially the compilation is very important as there will be a continuous update in the near future.

**Comment by philbucher** [comment]
> Yes, sure. But please let's deactivate only the cpp tests. Is that possible?
> 
> Especially the compilation is very important as there will be a continuous update in the near future.

sure, I would comment as little as possible (i.e. only the checks that fail)

**Comment by tteschemacher** [comment]
ok then I'll comment only the corresponding lines...

**Review by philbucher — APPROVED** [review]
👍🏻

**Comment by philbucher** [comment]
Lets merge before more conflicts arise IMO

**Comment by manuelmessmer** [comment]
Finaly, here we go!! Thanks to everyone!

**Pull request merged**
