### PR TITLE
[Core] Extend Kratos Parameters to support @include_json in array items

### PR DESCRIPTION
**Pull request by sunethwarna**
**📝 Description**
As stated in the title, this PR extends to support to have `@include_json` in array items in recursive manner. A test is also added.

**🆕 Changelog**
- Extended `@include_json` to support array items
- Added a test

### CODE REVIEW

**Review by loumalouomega — APPROVED** [review]

**Comment by matekelemen** [comment]
plz wait a moment

**Comment by loumalouomega** [comment]
Can we delete the branch?

**Comment by matekelemen** [comment]
Please.
Not.
Yet.

**Review by matekelemen — COMMENTED** [review]
👍

**Pull request merged**
