### PR TITLE
[ContactStructuralMechanicsApplication] Error in outcome fixed 

### PR DESCRIPTION
**Pull request by loumalouomega**
**Description**
This fixes a bug in the output

**Changelog**
- Fix bug

### CODE REVIEW

**Comment by loumalouomega** [comment]
There is something strange, I will reopen when found it

**Comment by loumalouomega** [comment]
The problem was somewhere else

**Comment by loumalouomega** [comment]
Ping @AlejandroCornejo

**Comment by AlejandroCornejo** [comment]
it is ready?

**Review by AlejandroCornejo — APPROVED** [review]
nice!

**Comment by loumalouomega** [comment]
> it is ready?

Yes, but only solves the issue of the outcome

**Pull request merged**
