### PR TITLE
[Core] Model part adding AddGeometries

### PR DESCRIPTION
**Pull request by loumalouomega**
**Description**
Adds AddGeometries to ModelPart

**Changelog**
- Added AddGeometries

### CODE REVIEW

**Review by tteschemacher — APPROVED** [review]
It looks good to me. It is the same as the other interfaces, so it should be fine.

Thanks a lot for adding it.

**Comment by loumalouomega** [comment]
Thanks

**Review by rubenzorrilla — COMMENTED** [review]
No test?

**Comment by loumalouomega** [comment]
> No test?

Ups (anyway these are simple functions)

**Comment by rubenzorrilla** [comment]
> > No test?
> 
> Ups (anyway these are simple functions)

Simple functions of a key class of Kratos. I think that a test is a must in this case.

**Comment by loumalouomega** [comment]
> > > No test?
> > 
> > 
> > Ups (anyway these are simple functions)
> 
> Simple functions of a key class of Kratos. I think that a test is a must in this case.

I know, I was trying to avoid the adding...

**Comment by loumalouomega** [comment]
See #8822

**Pull request merged**
