### PR TITLE
Femdem/Correcting the way I compute the damping matrix

### PR DESCRIPTION
**Pull request by AlejandroCornejo**
In this PR I'm implementing the CalculateLHS method in order to compute properly the Damping matrix in the FEM2DEM app.

### CODE REVIEW

**Comment by loumalouomega** [comment]
@AlejandroCornejo there is an specific method in elements for damping matrix, can you check first if that fits your needs?

**Comment by AlejandroCornejo** [comment]
> 
> 
> @AlejandroCornejo there is an specific method in elements for damping matrix, can you check first if that fits your needs?

yes exactly I use the CalculateDampingMatrix already implemented but I had to reimplement my CalculateLHS in order to take into account the damage! :)

**Review by loumalouomega — APPROVED** [review]
OK then

**Comment by roigcarlo** [comment]
Did you make something unusual with this branch? everyone repo is broken because its impossible to fetch and I don't understand why :S

**Comment by AlejandroCornejo** [comment]
mm @roigcarlo i dont think so but which is the problem?

**Comment by AlejandroCornejo** [comment]
how can we reset the appveyor compilation?

**Comment by loumalouomega** [comment]
You log and reset

**Comment by roigcarlo** [comment]
There was a problem fetching the branch, probably because there was another version in the local repos of people computer with the same name, but im not 100% sure

**Pull request merged**
