### PR TITLE
[StructuralMechanicsApplication] Logger compilation issue with std::vector

### PR DESCRIPTION
**Pull request by loumalouomega**
For some reason stopped compiling

### CODE REVIEW

**Review by philbucher — CHANGES_REQUESTED** [review]
Wait, are you including the stl-io?
https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/utilities/stl_io.h

**Comment by loumalouomega** [comment]
Trying

**Comment by philbucher** [comment]
this must work, I even made a test for this
https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/tests/utilities/test_stl_io.cpp

**Comment by loumalouomega** [comment]
@philbucher With the missing include it compiles, I assume it passed travis due to Cotire

**Review by philbucher — APPROVED** [review]
How was this compiling all the time

Is it only compiled when you habe mmg compiled?

**Comment by loumalouomega** [comment]
No, this just computes the metric. Doesn't need the MMG

**Pull request merged**
