### PR TITLE
Create kratos docker

### PR DESCRIPTION
**Pull request by philbucher**
this creates a docker-image with a compiled Kratos

Can be very useful e.g. for other CIs (e.g. GiDInterface)

### CODE REVIEW

**Comment by philbucher** [comment]
should work now once, jut needs to finish compiling :)

What do you think @roigcarlo ?

**Comment by roigcarlo** [comment]
@RiccardoRossi will be superhappy to see this :smile:

**Comment by philbucher** [comment]
> @RiccardoRossi will be superhappy to see this smile

Why? :)

**Comment by philbucher** [comment]
The image with everything has 1.72 GB

**Comment by roigcarlo** [comment]
He always wanted that :D

**Comment by philbucher** [comment]
ah

well, he can have it if he approves ;)

**Comment by oberbichler** [comment]
Maybe we should also build the releases (-> label) and specify `runkratos` as entrypoint.

**Comment by philbucher** [comment]
> Maybe we should also build the releases (-> label) and specify `runkratos` as entrypoint.

Sounds good
Although I am not sure if we can/should use runkratos. Firstly bcs it is not needed as second bcs I am not even sure it works with MPI

**Comment by armingeiser** [comment]
> Although I am not sure if we can/should use runkratos

I would say if possible use python directly.

**Comment by philbucher** [comment]
The more I think abt this image, the more things that we can do with it come to my mind 
Stay tuned :D

**Comment by loumalouomega** [comment]
> 
> 
> The more I think abt this image, the more things that we can do with it come to my mind
> Stay tuned :D

I would like to create Jupyuter notebooks with binder, https://mybinder.org/, so we can introduce and present Kratos more easily

**Comment by oberbichler** [comment]
I thought `runkratos` was the usual procedure :)

Something like `docker run kratos:v7 main.py` would be nice (I know. The command has to be longer at the end...).

@loumalouomega My personal experience: with binder the loading time is endless. Usually `pip` packages are the better choice for this kind of tasks.

**Comment by philbucher** [comment]
> Something like docker run kratos:v7 main.py would be nice (I know. The command has to be longer at the end...).

:+1:

**Comment by philbucher** [comment]
Does anyone have more comments or can we merge this?
I would like to use it myself right away and fix/update things if necessary

**Review by roigcarlo — APPROVED** [review]
To me looks fine

**Comment by philbucher** [comment]
Cool thx 
Next step will be to use this image in the nightly build instead of re-building Kratos

**Pull request merged**
