### PR TITLE
[MeshMovingApplication] fix compiling issues on windows

### PR DESCRIPTION
**Pull request by longchentum**
Compiling issues are fixed on windows. According to @AndreasWinterstein the function ComputeKernelValue can be replaced.

### CODE REVIEW

**Review by philbucher — CHANGES_REQUESTED** [review]
Guys this function was recently added by @rubenzorrilla 
@rubenzorrilla can you please have a look, there seems to be an issue with the windows compilation

@longchentum did you run the tests?

**Comment by longchentum** [comment]
I did not run the tests yet. If this function is needed, we can rewrite it so that it can compile on windows.

**Comment by philbucher** [comment]
#2148 has not solved the problem, @rubenzorrilla can you please have a look?

**Comment by philbucher** [comment]
closing since solved in #2179

**Pull request closed without merging**
