### PR TITLE
Replacing python_process for Process

### LINKED ISSUE #2314: [Question][Probably duplicated]Python processes depend on python_process or Kratos::Process?
@KratosMultiphysics/technical-committee 

Should the processes on python derive from Kratos::Process or from python_process?

https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/python_scripts/python_process.py

Many python processes derive from KM.Process:

https://github.com/KratosMultiphysics/Kratos/blob/9c05d22f06183081c78afa4c66996c76c13b88f6/kratos/python_scripts/read_materials_process.py#L15

I will vote to remove/deprecate the python_process and eplace everywhere where is used for Kratos::Process

### PR DESCRIPTION
**Pull request by loumalouomega**
Fixes #2314

### CODE REVIEW

**Comment by loumalouomega** [comment]
Many of the processes already derived from Process, i just corrected the text and add a deprecated warning

**Comment by philbucher** [comment]
ok for me but lets also have @maceligueta a look

Dont wanna be the only one to blame :)

**Comment by loumalouomega** [comment]
Ping @maceligueta

**Comment by maceligueta** [comment]
No complaints from my side.

**Review by philbucher — APPROVED** [review]
ok then

**Pull request merged**
