### PR TITLE
[README] Update to 9.5

### PR DESCRIPTION
**Pull request by loumalouomega**
**📝 Description**

Update README to 9.5

**🆕 Changelog**

- [Update README](https://github.com/KratosMultiphysics/Kratos/commit/11ca014cce75db07c32f96d9dabc0903276f52fb)

### CODE REVIEW

**Review by roigcarlo — APPROVED** [review]

**Comment by roigcarlo** [comment]
Probably needs a retrigger :S

**Comment by loumalouomega** [comment]
> Probably needs a retrigger :S

Doesn't look like it works...

**Comment by loumalouomega** [comment]
> > Probably needs a retrigger :S
> 
> Doesn't look like it works...

Huuum, can you just simply cherry-pick with your superior adming powers?

**Comment by roigcarlo** [comment]
aaaaaa Now i see the problem, you are trying to merge into Release-9.5, not into master. 

There is no setup for that, once the branch is created is frozen. But you may reopen the pr into master.

**Pull request closed without merging**
