### PR TITLE
[Core] Adding GlobalCoordinates with custom integration method

### LINKED ISSUE #10232: GlobalCoordinates calculation
**Description**
I have realized that when I use the method `GlobalCoordinates` in `geometry.h`, the calculation of the shape functions does not take into account the integration method, leading to inaccurate results when I get the global coordinates of the integration points. The code is below:

```
    /** This method provides the global coordinates to
    *   the corresponding integration point
    * @param rResult The global coordinates
    * @param IntegrationPointIndex The index of the integration point
    * @return the global coordinates
    */
    void GlobalCoordinates(
        CoordinatesArrayType& rResult,
        IndexType IntegrationPointIndex
    ) const
    {
        noalias(rResult) = ZeroVector(3);

        const Matrix& N = this->ShapeFunctionsValues();

        for (IndexType i = 0; i < this->size(); i++)
            noalias(rResult) += N(IntegrationPointIndex, i) * (*this)[i];
    }
```
Should the function `ShapeFunctionsValues()` have the integration method as an argument?

**Scope**
- KratosCore

### PR DESCRIPTION
**Pull request by loumalouomega**
**📝 Description**

Adding GlobalCoordinates with custom integration method. Fixes #10232

**🆕 Changelog**

- [Adding GlobalCoordinates with custom integration method](https://github.com/KratosMultiphysics/Kratos/commit/fbe58e22a6159fc75ff4cf1f085ddd21fdbd21fe)

### CODE REVIEW

**Comment by jgonzalezusua** [comment]
Ok, thanks @loumalouomega. When it passes the CI, I can approve the PR

**Review by jgonzalezusua — DISMISSED** [review]

**Comment by loumalouomega** [comment]
Can I proceed @KratosMultiphysics/technical-committee ?

**Comment by loumalouomega** [comment]
Anyone?

**Comment by loumalouomega** [comment]
@KratosMultiphysics/technical-committee 👋

**Comment by loumalouomega** [comment]
> @KratosMultiphysics/technical-committee 👋

Can I merge this?, it is a very small change (only adds, dones't change anything)

**Comment by rubenzorrilla** [comment]
For me it makes sense. Maybe what we could do is to take the chance to make the current `GlobalCoordinates` to call this one with the default integration method. Something like
````c++
void GlobalCoordinates(
        CoordinatesArrayType& rResult,
        IndexType IntegrationPointIndex
        ) const
    {
        GlobalCoordinates(rResult, IntegrationPointIndex, GetDefaultIntegrationMethod());
    }
````

**Comment by rubenzorrilla** [comment]
> > For me it makes sense. Maybe what we could do is to take the chance to make the current `GlobalCoordinates` to call this one with the default integration method. Something like
> > ```c++
> > void GlobalCoordinates(
> >         CoordinatesArrayType& rResult,
> >         IndexType IntegrationPointIndex
> >         ) const
> >     {
> >         GlobalCoordinates(rResult, IntegrationPointIndex, GetDefaultIntegrationMethod());
> >     }
> > ```
> 
> Okay, I hope this doesn't break existing code

mmm... I think it shouldn't... Basically we are doing the very same no? In any case, forget about my comment if you think there is any chance to break something.

**Comment by loumalouomega** [comment]
.............................

> > > For me it makes sense. Maybe what we could do is to take the chance to make the current `GlobalCoordinates` to call this one with the default integration method. Something like
> > > ```c++
> > > void GlobalCoordinates(
> > >         CoordinatesArrayType& rResult,
> > >         IndexType IntegrationPointIndex
> > >         ) const
> > >     {
> > >         GlobalCoordinates(rResult, IntegrationPointIndex, GetDefaultIntegrationMethod());
> > >     }
> > > ```
> > 
> > 
> > Okay, I hope this doesn't break existing code
> 
> mmm... I think it shouldn't... Basically we are doing the very same no? In any case, forget about my comment if you think there is any chance to break something.

No, I checked, a priori doesn't break because is not virtual method (i thought it was virtual)

**Comment by loumalouomega** [comment]
> .............................
> 
> > > > For me it makes sense. Maybe what we could do is to take the chance to make the current `GlobalCoordinates` to call this one with the default integration method. Something like
> > > > ```c++
> > > > void GlobalCoordinates(
> > > >         CoordinatesArrayType& rResult,
> > > >         IndexType IntegrationPointIndex
> > > >         ) const
> > > >     {
> > > >         GlobalCoordinates(rResult, IntegrationPointIndex, GetDefaultIntegrationMethod());
> > > >     }
> > > > ```
> > > 
> > > 
> > > Okay, I hope this doesn't break existing code
> > 
> > 
> > mmm... I think it shouldn't... Basically we are doing the very same no? In any case, forget about my comment if you think there is any chance to break something.
> 
> No, I checked, a priori doesn't break because is not virtual method (I thought it was virtual)

It is done BTW

**Comment by loumalouomega** [comment]
@rubenzorrilla

**Review by rubenzorrilla — APPROVED** [review]
Very good. Thanks @loumalouomega.

**Pull request merged**
