### PR TITLE
[Dam] Move simplified joint CLs to the DamApplication

### PR DESCRIPTION
**Pull request by joaquinirazabal**
**Description**
The simplified bilinear CL has been moved to the DamApplication where two different CLs have been created. In the first one the breakage is driven by a cohesion parameter (used for soil/dam joints) and in the second one the breakage depends on the tensile and compressive ultimate stress (used for vertical joints).

**Changelog**
- Remove simplified bilinear CL from PoromechanicsApplication.
- Add the two new contact laws to the Dam Application.

### CODE REVIEW

**Comment by philbucher** [comment]
Please wait with merging I have a comment, will post in a few min

**Comment by philbucher** [comment]
@joaquinirazabal I saw that you modified the NR strategy in the core (I know you reverted the changes and that they were only used fo debugging most probably)
Unfortunately those changes will appear in the history of the file, which makes debugging changes more difficult.
I recommend the following:

- if possible please merge this PR with a [squash merge](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/merging-a-pull-request#merging-a-pull-request-on-github), this way only the actual changes of the PR will go into master as one (big) commit. This way the changes in the NR-Strategy will not go into the history. Note that then you also loose the individual commits of this PR, not sure if you need them
- For the future: Don't commit the changes when you are sure they are only temp. This way they will never even go into the history

Thanks!

**Comment by joaquinirazabal** [comment]
Thank you for the comment, @philbucher. I will do what you suggest. For the future, I will take into account your advice about not committing temp changes, it makes sense.

**Comment by joaquinirazabal** [comment]
Ping @ipouplana

**Review by ipouplana — APPROVED** [review]
Sorry, it's ok for me!

**Pull request merged**
