### PR TITLE
[StructuralMechanicsApplication] Adding INTEGRATION_COORDINATES to beam elements

### PR DESCRIPTION
**Pull request by loumalouomega**
**Description**
Adding INTEGRATION_COORDINATES to beam elements CalculateOnIntegrationPoints. This is required by a user external to GitHub

**Changelog**
- Adding INTEGRATION_COORDINATES to beam elements CalculateOnIntegrationPoints

### CODE REVIEW

**Comment by philbucher** [comment]
no objections
FYI this beam will most probably be removed, @KlausBSautter is working on a replacement

**Comment by loumalouomega** [comment]
> no objections
> FYI this beam will most probably be removed, @KlausBSautter is working on a replacement

Approval?

**Comment by philbucher** [comment]
> > no objections
> > FYI this beam will most probably be removed, @KlausBSautter is working on a replacement
> 
> Approval?

I leave to @KlausBSautter as I have no clue :D

**Review by KlausBSautter — APPROVED** [review]
👍

**Pull request merged**
