### PR TITLE
updating CMAKE list for windows

### PR DESCRIPTION
**Pull request by AlejandroCornejo**
I add the required flags for compiling Kratos in Win with VS 2017 properly.

### CODE REVIEW

**Comment by maceligueta** [comment]
Hi @roigcarlo , if this variable is not defined, we could not compile in Windows.

**Comment by loumalouomega** [comment]
> 
> 
> I add the required flags for compiling Kratos in Win with VS 2017 properly.

I notice this long time ago, the NOMINMAX did not worked to me

**Comment by roigcarlo** [comment]
To be honest I don't know what this is. It compiles without ti in my machine, but if you need it...

**Comment by roigcarlo** [comment]
Ok just read what it is. No problem from my side, but according to @AlejandroCornejo mail and what this does we should not have this problem. Windows.h is only included in `gidpost`, `zlib` and the `memory_profiler`. Are you compiling with cotire or something?

**Comment by AlejandroCornejo** [comment]
> 
> 
> Ok just read what it is. No problem from my side, but according to @AlejandroCornejo mail and what this does we should not have this problem. Windows.h is only included in `gidpost`, `zlib` and the `memory_profiler`. Are you compiling with cotire or something?

Hi! yes, since I see the option in the "tutorial" I add the compilation with COTIRE

**Comment by roigcarlo** [comment]
Haaa then probably this is the problem, could you try something. Instead of adding this to the cmake, try to add it to the "add_memory_info_to_python.cpp" like this:

```c++
// External includes
#include <pybind11/pybind11.h>

// Project includes
#define NOMINMAX
#include "includes/memory_info.h"
#undef NOMINMAX
```

Anyway I am fine if you want to pass it as an argument, just bear in mind that it may break people that is using `min` and `max` functions outside the stl library. but I think nobody is using that anymore.

**Comment by philbucher** [comment]
see #6062 
wouldn't a cleaner solution be to move the `windows.h` header to the cpp and / or guard it with `WIN32_LEAN_AND_MEAN` or `VC_EXTRALEAN`?

**Comment by roigcarlo** [comment]
Actualy that should work, as I assume that we would move the *.cpp into the core.

**Comment by philbucher** [comment]
@KratosMultiphysics/technical-committee: we will put the `windows.h` include in a cpp, this should solve the problem.
(@roigcarlo please correct me if I am wrong)

**Pull request closed without merging**
