### PR TITLE
[PoroMechanics] clean python-scripts

### PR DESCRIPTION
**Pull request by philbucher**
Hi @ipouplana 
I want to do some cleaning in the core and did the cleaning in your app right away

Tests are running, but please check yourself if I broke sth

### CODE REVIEW

**Comment by ipouplana** [comment]
Ok, thanks @philbucher . I will try these changes this afternoon (or evening) and I'll tell you

**Comment by philbucher** [comment]
ok, no need to hurry

**Review by ipouplana — APPROVED** [review]
Everything is ok!

**Comment by philbucher** [comment]
@ipouplana in the long run I recommend you to update the python-interface to the latest version as described [here](https://github.com/KratosMultiphysics/Kratos/wiki/Applications-as-python-modules#2-the-second-step-depends-if-a-large-application-which-needs-backwards-compatibility-or-a-small-application-where-backwards-compatibility-is-not-a-problem-eg-because-only-few-people-use-itapplications-that-have-no-python-files)
The newer apps use it already

Theroetically the app should be ready now, but if you use any python-script from it then it will have to be preceeded by `KratosMultiphysics.PoromechanicsApplication`, this is basically what I did in this PR

If you have questions just ask me
This way you will be on the safe side once the "old" python interface will become deprecated

**Pull request merged**
