### PR TITLE
[Core] fix compiler error

### PR DESCRIPTION
**Pull request by philbucher**
I managed to break the compilation even though we have Travis ...
Sorry

### CODE REVIEW

**Comment by philbucher** [comment]
I should have merged master in #2969 before merging it ...

**Review by jcotela — APPROVED** [review]
:+1: for finding a new way of breaking kratos.

**Review by roigcarlo — APPROVED** [review]

**Comment by philbucher** [comment]
> +1 for finding a new way of breaking kratos.

I can break things you never thought could be broken :D

**Review by RiccardoRossi — APPROVED** [review]

**Comment by loumalouomega** [comment]
> > +1 for finding a new way of breaking kratos.
> 
> I can break things you never thought could be broken :D

I was thinking in uploading a meme, but then I reminded that this is public website...

**Comment by philbucher** [comment]
> > > +1 for finding a new way of breaking kratos.
> > 
> > 
> > I can break things you never thought could be broken :D
> 
> I was thinking in uploading a meme, but then I reminded that this is public website...

that usually does not stop you ;)

**Comment by philbucher** [comment]
btw this branch is currently compiling in Travis
once it passed I will merge it into the other branches that are not compiling bcs of this

Sorry again

**Comment by philbucher** [comment]
I relaunched all affected PRs :)

**Pull request merged**
