### PR TITLE
[ContactStructuralMechanicsApplication] Replacing Set for map on search

### PR DESCRIPTION
**Pull request by loumalouomega**
This is necessary for development on the frictional formulation

### CODE REVIEW

**Comment by loumalouomega** [comment]
Ping @KratosMultiphysics/structural-mechanics

**Comment by loumalouomega** [comment]
Anyone?

**Review by philbucher — APPROVED** [review]
seems ok to me from the implementational point of view but I don't know the details of the algorithm

**Comment by loumalouomega** [comment]
It is just that for the frictional I need to keep the conditions that remain in contact instead of erasing everything (this was the current approach, easier to implement). I just changed the set to a map and that way I can keep the track of the conditions

**Comment by loumalouomega** [comment]
Thanks

**Pull request merged**
