### PR TITLE
Generalized application sourcetree

### PR DESCRIPTION
**Pull request by roigcarlo**
This allows for the inclusion of external application directories in Kratos compilation process.

Ongoing PR, mostly to discuss the implementation

## How this works?
It iterates over all directories specified in a variable, in this case 
`-DKRATOS_EXTERNAL_APPLICATIONS_DIR` which contains a list of paths separated by `;` and adds them as sub-directories of the project ( the ones created in cmake_build/CMakeFiles )

## What else is needed?
For this to work I assume different things:
- Every directory in `KRATOS_EXTERNAL_APPLICATIONS_DIR` has the same structure as the applications directory in kratos. One CMakeList.txt listing all the applications inside and a collection of application directories.
- The folder is not called `applications` (more on this later)

## Example
I have the following:
- **Kratos**: located in `$HOME/Kratos`
- **KratosExternalApplications**: located in `$HOME/KratosExternalApplications` with a custom CMakeList.txt:

```CMake
set(CMAKE_INCLUDE_CURRENT_DIR ON)

#echo of user defined options
SET(LIST_OF_APPS "\
EXTERNAL_FSI_APPLICATION;\
")

message( " ")
message( " ")
message( "***** LIST OF KRATOS EXTERNAL APPLICATIONS THAT ARE GOING TO BE COMPILED: *****")
message( " ")

FOREACH(APP ${LIST_OF_APPS})
IF(${${APP}} MATCHES ON)
message("                ${APP} - ${${APP}}")
ENDIF(${${APP}} MATCHES ON)
ENDFOREACH()
message( " ")
message( "**********************************************************************")
message( " ")

message( "********** LIST OF KRATOS APPLICATIONS THAT ARE SET TO OFF: **********")
message( " ")
FOREACH(APP ${LIST_OF_APPS})
IF(${${APP}} MATCHES OFF)
message("                ${APP} - ${${APP}}")
ENDIF(${${APP}} MATCHES OFF)
ENDFOREACH()
message( " ")
message( "**********************************************************************")

message( " ")
message( " ")

#include subdirectories for compilation
if(${EXTERNAL_FSI_APPLICATION} MATCHES ON)
  add_subdirectory(FSIapplication)
endif(${EXTERNAL_FSI_APPLICATION} MATCHES ON)
```
- A Copy of the FSIApplication called ExternalFSIApplication inside KratosExternalApplications

- A configuration file with the following extra lines:
```bash
-DKRATOS_EXTERNAL_APPLICATION_DIR="$HOME/KratosExternalApplications"                        \
-DEXTERNAL_FSI_APPLICATION=ON 								                                \
```

## Possible improvements
Right now there is still something I don't like. The use of 

```CMake
add_subdirectory(${APPLICATION_EXTERNAL_DIR} ${CMAKE_CURRENT_BINARY_DIR}/${APPLICATION_EXTERNAL_DIR})
```
makes the generated code for the application appear under the absolute path for the application. Example: `Kratos/cmake_build/home/ExternalApplications/ExternalFSIApplication`. It works but it is not very fancy. I am working on this.

@jcotela As we are touching the applications seems a good moment for `applications_interface.py` to mysteriously disappear...

### CODE REVIEW

**Comment by roigcarlo** [comment]
Next commit should solve the problem with ugly directory paths. Now it takes the last folder name as the root folder for the configuration files to appear, like this:

image

**Comment by pooyan-dadvand** [comment]
@roigcarlo Thanks for the effort. My idea was somehow different. I was trying to make the Kratos work as a sub project in another one with a CMakeList in the root of MyApp:
 
```
ParentSoftware
|_Kratos
|_ParentApplications
|_CMakeLists.txt
```

Let say, to make the build "nest-able". This means that I would compile from the root "ParentSoftware" directory and the root CMakeLists would simply include subdirectories Kratos and ParentApplications. For doing that I observed that they are some path in the kratos CMakeLists which are not compatible. 

Just to add that I think this approach would be slightly more modular. Letting Kratos to be used a part of larger projects without changing the global hierarchy of them.

**Comment by roigcarlo** [comment]
Oh, I see, I understand another think.
What you want to do would require more work indeed

**Comment by RiccardoRossi** [comment]
@pooyan-dadvand i am in favor of actually permitting what @roigcarlo is introducing.

It breaks nothing, and it allows to easily have nested applications, so i would allow it. Longer term we could look for more sophisticated solutions

**Comment by pooyan-dadvand** [comment]
I agree that it is a useful change and also I need it for my proposal.

**Comment by pooyan-dadvand** [comment]
@RiccardoRossi I have not approved it as you told me that you would ask for minor changes.

**Comment by roigcarlo** [comment]
@RiccardoRossi ping

**Comment by marandra** [comment]
I tested it with my external application and compilation works perfectly.

I am not sure if/how it impacts external python processes though. For example, I am getting:
```
File "/home/mraschi/Projects/Kratos/kratos/python_scripts/process_factory.py", line 15,
in ConstructListOfProcesses
    python_module = __import__(item["python_module"].GetString())
ImportError: No module named 'write_elements_homogenized_output'
```
How should I modify the configuration of the process in the ProcessParameters.json, currently being:
```
{
        "python_module": "write_elements_homogenized_output",
        "kratos_module": "KratosMultiphysics.MultiscaleROMApplication",
        "process_name": "WriteElementsHomogenizedOutput",
        "Parameters":{
            "model_part_name": "RVE",
	    "filename": "homogenized_stress.dat",
            "variable_name": "CAUCHY_STRESS_VECTOR"
	        }
        }
```

**Comment by roigcarlo** [comment]
@marandra Good catch. I think the error is produced because the application importer thinks that all applications are located inside kratos/applications, which should be the case if someone installs kratos in a different directory ( which I did in the tests) but may not be true if its installed in the source.

Let me take a look at it

**Comment by marandra** [comment]
Hi @roigcarlo !

**Comment by roigcarlo** [comment]
Ups sorry, totally forgot about this :S

I was looking for a solution and the only thing I could come up with in your case is to add your folder application  to the python path, like:

```
KratosPath: /home/me/Kratos
app1 path: /home/me/projects/externalApp
```

then 

```Bash
export PYTHONPATH=/home/me/Kratos:/home/me/projects/externalApp:/home/me/projects/externalApp/python_scripts
```

Can you check if this works for you? I will try to come up with a better solution in the meantime

**Comment by pooyan-dadvand** [comment]
We will go through this maybe next week. I will let you know the result

**Comment by marandra** [comment]
@roigcarlo Adding the external application paths to the python path is working for me. Thanks for the workaround!

**Comment by roigcarlo** [comment]
Can we merge then?

**Review by pooyan-dadvand — DISMISSED** [review]
👍

**Comment by pooyan-dadvand** [comment]
Anyone can re-approve it after resolving the conflict

**Comment by roigcarlo** [comment]
I will fix the problem now

**Review by loumalouomega — APPROVED** [review]

**Comment by philbucher** [comment]
is the branch still needed?

**Pull request merged**
