### PR TITLE
[Core] Buffer position update in UpdateCurrentPosition

### PR DESCRIPTION
**Pull request by loumalouomega**
This allows to uses any value of the buffer (not just the last one)

Requested by @Vahid-Galavi in https://github.com/KratosMultiphysics/Kratos/issues/4594

### CODE REVIEW

**Review by RiccardoRossi — APPROVED** [review]
ok

**Comment by philbucher** [comment]
Please wait for my review, I would like to take a look too
Thx!

**Review by Vahid-Galavi — APPROVED** [review]

**Review by Vahid-Galavi — APPROVED** [review]

**Comment by Vahid-Galavi** [comment]
Thanks @loumalouomega!

**Comment by philbucher** [comment]
@Vahid-Galavi usually the one that opens the PR merges it
Please wait next time, I also wanted to have a look

Looks fine to me btw

**Comment by Vahid-Galavi** [comment]
@philbucher thanks for your remark. I clicked the push request accidentally and there was no way to go back...

**Comment by philbucher** [comment]
No worries :)
Btw don’t forget to delete the branch after merging

**Pull request merged**
