### PR TITLE
[Docs] Adding logo to documentation

### PR DESCRIPTION
**Pull request by loumalouomega**
**📝 Description**

Adding logo to documentation

**🆕 Changelog**

- [Adding logo](https://github.com/KratosMultiphysics/Kratos/commit/5e90af6a0c268da4ba3e9eef705e29369b07cae7)

### CODE REVIEW

**Comment by roigcarlo** [comment]
I dn't know if the assets folder is autmatically detected by jenkyns. :S

**Comment by sunethwarna** [comment]
I used everywhere, the relative path. Not sure thats the problem tho.

**Comment by loumalouomega** [comment]
> I used everywhere, the relative path. Not sure thats the problem tho.

Maybe is not compatible with the theme. Which theme are we using?, to look for documentation

**Comment by sunethwarna** [comment]
We are using https://jekyllthemes.io/theme/documentation

**Comment by loumalouomega** [comment]
Huuum, I followed https://stackoverflow.com/questions/30551501/unable-to-set-favicon-using-jekyll-and-github-pages

Maybe is because the relative path?

**Comment by loumalouomega** [comment]
@sunethwarna how do I compile this locally, so I can test it locally instead of trial and error?

**Comment by sunethwarna** [comment]
@loumalouomega see #10627

**Comment by loumalouomega** [comment]
What is the status of this?

**Comment by loumalouomega** [comment]
> What is the status of this?

Idem

**Comment by roigcarlo** [comment]
I did not have time to look at this since is low prio, but looking at the PR, why do you need to add bootstrap a a new header html to add the logo? It would be easier to just add it in the top nav bar no?

**Comment by loumalouomega** [comment]
> I did not have time to look at this since is low prio, but looking at the PR, why do you need to add bootstrap a a new header html to add the logo? It would be easier to just add it in the top nav bar no?

This is what I found in the documentation: https://github.com/mmistakes/jekyll-theme-basically-basic/blob/master/_includes/head.html

**Comment by loumalouomega** [comment]
Do i close this @roigcarlo ?

**Comment by loumalouomega** [comment]
Maybe I just close it

**Pull request closed without merging**
