### PR TITLE
bugfix and test for the case in which the modeler is called multiple times

### PR DESCRIPTION
**Pull request by RiccardoRossi**
i wonder how this could be working before...

### CODE REVIEW

**Comment by RiccardoRossi** [comment]
this fixes #1854

**Review by juliobarna — APPROVED** [review]
it is ok.

**Comment by loumalouomega** [comment]
Can we delete this branch?

**Comment by philbucher** [comment]
is this branch still needed?

**Comment by rubenzorrilla** [comment]
I don't think so.

**Pull request merged**
