### PR TITLE
[ConvDiff] Adding to ConvectionDiffusionApplication to CI

### PR DESCRIPTION
**Pull request by rubenzorrilla**
We agreed that we want to have the convection - diffusion capabilities as core features. We are already making some efforts to clean up and prepare the application to this. I think that having it in the CI will simplify this job (aside of the fact that if we want it to be core must be in the CI).

I took the chance to add some missing applications in the GitLab Trusty build (now it coincides with the Travis one).

Let's check how this affects to the building times.

### CODE REVIEW

**Comment by philbucher** [comment]
I don’t have objections, but regarding Travis I think we should first add Trilinos and Metis (#5372) since those are crucial for most MPI capabilities of Kratos 
If after that there is still enough time then I would go ahead here

BTW @roigcarlo do you agree with starting to add more apps to the new CI?
Or is it still „experimental“?
Afaik the Win build still fails occasionally

**Comment by roigcarlo** [comment]
Its experimental but is stable enough to accept new apps. This should allow us to stress the machine.

As fot Trilinos and Metis, I don't know if we are going to have enough time in Travis to compile the. we are quite at the limit again.... I think it would be better to star focusing on the gitlab ones

**Comment by rubenzorrilla** [comment]
> I don’t have objections, but regarding Travis I think we should first add Trilinos and Metis (#5372) since those are crucial for most MPI capabilities of Kratos
> If after that there is still enough time then I would go ahead here
> 
> BTW @roigcarlo do you agree with starting to add more apps to the new CI?
> Or is it still „experimental“?
> Afaik the Win build still fails occasionally

Agree. Metis and Trilinos are more relevant in this sense.

**Comment by rubenzorrilla** [comment]
Closing. At this point I think is better to open a new PR.

**Pull request closed without merging**
