### PR TITLE
[dem] Memory management problem (bugfix)

### PR DESCRIPTION
**Pull request by maceligueta**
I ran valgrind with the tests and a memory problem was detected. I hope it was the source of the crash with the actions.

### CODE REVIEW

**Review by philbucher — APPROVED** [review]
now at least on my machine it no longer crashes, thx @maceligueta

**Comment by maceligueta** [comment]
@philbucher thank you for pointing out the location of the error. 
By the way, my local FullDebug compilation of Kratos was not crashing, isn't it including the flag D_GLIBCXX_DEBUG? I thought it was.

**Comment by philbucher** [comment]
it is not!
I think there is an issue with Trilinos, also according to @RiccardoRossi Kratos becomes even much slower
see also #715

**Comment by philbucher** [comment]
and #580

I myself have a custom config "SuperDebug" which in addition to `FullDebug` also adds `D_GLIBCXX_DEBUG`.

**Comment by maceligueta** [comment]
Lol. Ok, I thought the difference between FullDebug and Debug was exactly the addition of two flags, one of which was exactly this one. Ok ok, Of course I will add it immediately, as I used to have it.

**Pull request merged**
