### PR TITLE
[Structural] remove computing model part

### PR DESCRIPTION
**Pull request by philbucher**
**Description**
This PR FINALLY completely removes the computing model part from StructuralMechanics.
The computing model part was not used for a while already (#6217)

I marked as API-breaker and Behavior change, but it should not break existing things, as I said the critical change was #6217

@loumalouomega please check if this works with the contact, I don't know the details of the implementation

@KratosMultiphysics/structural-mechanics

### CODE REVIEW

**Comment by philbucher** [comment]
@loumalouomega can you please update the Contact accordingly?

**Comment by loumalouomega** [comment]
I will, but I am on holidays and my availability is limited, sorry 🙏

**Comment by philbucher** [comment]
this is not urgent!
Enjoy your holidays!

**Review by loumalouomega — DISMISSED** [review]
All OK

**Comment by philbucher** [comment]
awesome thanks

I will merge after vacation period as this is an important change

**Comment by philbucher** [comment]
@RiccardoRossi is aware of this now, I will hence merge on Monday

**Review by KlausBSautter — APPROVED** [review]
nice work!

**Comment by philbucher** [comment]
Finally !!!!

(@roigcarlo FYI this should go to the release notes of the next release)

**Pull request merged**
