### PR TITLE
[SDEM] Adding rigid rotation process for ALE fluid

### PR DESCRIPTION
**Pull request by ipouplana**
- It is based on Rodrigues' rotation formula.
- For the moment the angular velocity is constant, but we can upgrade this process in the future to accept a function.

### CODE REVIEW

**Review by GuillermoCasas — APPROVED** [review]
Great!

**Comment by adityaghantasala** [comment]
Is there a specific reason you did this using Rodrigues' rotation formula ? Can't the same be done using the  Quaternion  implementation in the core ?

**Comment by GuillermoCasas** [comment]
> Is there a specific reason you did this using Rodrigues' rotation formula ? Can't the same be done using the Quaternion implementation in the core ?

@ipouplana , please, take a look at this

**Comment by ipouplana** [comment]
There was not a specific reason. We implemented this process some time ago without knowing that there was an alternative process in the core...
@adityaghantasala could you please indicate us which is the process you mention (the file) ?
Thanks in advance

**Comment by adityaghantasala** [comment]
Have a look at this utility 

https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/utilities/quaternion.h

Here is the theory ... 

https://en.m.wikipedia.org/wiki/Quaternions_and_spatial_rotation

**Comment by GuillermoCasas** [comment]
> Have a look at this utility
> 
> https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/utilities/quaternion.h
> 
> Here is the theory ...
> 
> https://en.m.wikipedia.org/wiki/Quaternions_and_spatial_rotation

Oh, I see that you are not referring to an already-made utility or process that rotates a point given an axis  and an angular velocity. 

The fact that one can use quaternions to implement a rotation does not mean that any rotation must use them. The Rodrigues formula is simple and easy to implement and that is why it was chosen for this particular application in the first place. There is really no need for quaternions here, I think.

**Comment by adityaghantasala** [comment]
Yes that is not already well formed process. that is a utility. 

Why I pointed to this utility is that it also has the same purpose but a different technology. Instead of having multiple things that do the same thing, its better to have one centralized implementation which everyone can use. 
I think soon people will want to use this feature in other applications too. So having a centralized implementation is useful.

**Pull request merged**
