### PR TITLE
[Core] cleanup from_json_check_result_process

### PR DESCRIPTION
**Pull request by philbucher**
I want to port this process to be MPI-compatible, but first I make this separate PR which contains ONLY cleanup

### CODE REVIEW

**Comment by loumalouomega** [comment]
I was thinking to this in pure c++, to make the check much faster, but OK

**Review by loumalouomega — DISMISSED** [review]

**Comment by philbucher** [comment]
> I was thinking to this in pure c++, to make the check much faster, but OK

you think it will make a big difference?

**Comment by loumalouomega** [comment]
> > I was thinking to this in pure c++, to make the check much faster, but OK
> 
> you think it will make a big difference?

Probably, because accessing to database is significantly slower in python

**Comment by philbucher** [comment]
> > > I was thinking to this in pure c++, to make the check much faster, but OK
> > 
> > 
> > you think it will make a big difference?
> 
> Probably, because accessing to database is significantly slower in python

That's true. In case you do this, can you please wait until I am done with porting it to MPI?
Should only be a couple of changes, but just in order to avoid conflicts

**Comment by loumalouomega** [comment]
Of course, is not for now, is for the future...

**Comment by philbucher** [comment]
can yu reapprove pls?

**Review by loumalouomega — APPROVED** [review]

**Pull request merged**
