### PR TITLE
3D constitutive tensor to 2D component correction

### PR DESCRIPTION
**Pull request by josep-m-carbonell**
Correction of an error detected in the constitutive model application. It is important to fix it in the release.

### CODE REVIEW

**Review by roigcarlo — APPROVED** [review]
Ok to me. 

Just to confirm, This is going to be merged in the Release 5.2. Is that ok ?

**Comment by josep-m-carbonell** [comment]
Yes, it is. Is there any schedule for the release?

**Comment by roigcarlo** [comment]
Should be by the end of Nov @pooyan-dadvand has the exact date.

**Comment by josep-m-carbonell** [comment]
Ok, thank you

**Comment by pooyan-dadvand** [comment]
End of November!

**Pull request merged**
