### PR TITLE
[Core] Update scripts and CI to LinearSolversApplication

### PR DESCRIPTION
**Pull request by loumalouomega**
Basically that

### CODE REVIEW

**Review by philbucher — DISMISSED** [review]

**Review by philbucher — DISMISSED** [review]

**Comment by philbucher** [comment]
we first need to update the apps only after that we can update the CI

**Comment by loumalouomega** [comment]
> we first need to update the apps only after that we can update the CI

OK

**Review by philbucher — COMMENTED** [review]
can you please make a PR with only the changes on the `scripts` folder?
The CI can only be updated after we updated the apps

**Review by philbucher — APPROVED** [review]
this can be merged after #7252 

It would be good to squash the commits to keep history clean ;)

just merge master after #7252 is merged, you won't need reapproval

**Comment by loumalouomega** [comment]
> this can be merged after #7252
> 
> It would be good to squash the commits to keep history clean ;)
> 
> just merge master after #7252 is merged, you won't need reapproval

I forgot to squash, sorry

**Comment by philbucher** [comment]
> > this can be merged after #7252
> > It would be good to squash the commits to keep history clean ;)
> > just merge master after #7252 is merged, you won't need reapproval
> 
> I forgot to squash, sorry

no worries

I think in the long run it makes sense to use it to keep the history cleaner
But tbd, its not that important

**Pull request merged**
