### PR TITLE
Utility to calculate level-set negative area

### LINKED ISSUE #8101: Level-set convection process
**Description**
I would like to know if there is any function available that computes the wet area and volume of the elements inside a given surface, such as in XFEM. The function takes into account the level-set function so that there will be elements cut by the interface with part of their area inside and outside. 

Then, should the Navier Stokes Two-Fluid Solver be used when the level_set_convection_process is called in order to update the position of the interface?

Eventually, is there any Example test available in which this process is used? 

**Scope**
- Documentation

### PR DESCRIPTION
**Pull request by pau-mar**
**Description**
This PR contains a utility to calculate the area inside the negative DISTANCE nodes. 
Closes #8101

**Changelog**
- Created new utility in FluidDynamicsApplication

### CODE REVIEW

**Comment by mrhashemi** [comment]
Hi,
Please take a look at:
MassConservationCheckProcess::ComputeVolumesAndInterface

**Review by philbucher — COMMENTED** [review]
hey,
Can you please:
- separate into header/source?
- clean up the comments
- check the style guide for variable namings (e.g. `mrModelPart`)
- use the parallel Utilites instead of OMP directly => seach for `block_for_each` in the code

**Review by philbucher — CHANGES_REQUESTED** [review]
This PR does a lot of changes to a lot of important classes and functionalities.
Please split it into smaller PRs so that the changes can be discussed easier

**Comment by pau-mar** [comment]
As @mrhashemi  pointed out this utility does the same as MassConservationCheckProcess::ComputeVolumesAndInterface therefore this PR can be closed without inconvinient.

**Pull request closed without merging**
