### PR TITLE
remove IS_INACTIVE variable from structural_application

### PR DESCRIPTION
**Pull request by vryy**

### CODE REVIEW

**Review by RiccardoRossi — APPROVED** [review]
@vryy i am fine with those changes.

with that IS_INACTIVE is completely removed from the structural_application?

one comment: if you see my commit, i posted a small unit test for the base gid_io. Don't you want to do something similar for your "custom_gid_io"?

**Comment by vryy** [comment]
@RiccardoRossi I believe it's completely removed. Since I can't find it more in the structural_application by grep.
I'll take a look on your test with gid_io

**Comment by RiccardoRossi** [comment]
@vryy you should delete the branch once merged. (this time i'll do it, no prob)

**Comment by vryy** [comment]
@RiccardoRossi Sure, next time I'll do it

**Pull request merged**
