### PR TITLE
Disabled Contact structural mechanichs application

### PR DESCRIPTION
**Pull request by roigcarlo**
This will temporally disable the application from the nightly builds until its fixed.

### CODE REVIEW

**Comment by pooyan-dadvand** [comment]
👍

**Comment by roigcarlo** [comment]
Approve :smile: ?

**Comment by pooyan-dadvand** [comment]
@loumalouomega can we disable it until you make it working again?

**Comment by loumalouomega** [comment]
It works in my branch, but I cannot merge my brunch until we have solve the pending pr

**Review by loumalouomega — APPROVED** [review]

**Pull request merged**
