### PR TITLE
Removing unnecessary imports, repairing symbolic links

### PR DESCRIPTION
**Pull request by salvalatorre**
Removing several unnecessary imports and repairing some symbolic links that did not properly work.

### CODE REVIEW

**Review by GuillermoCasas — APPROVED** [review]
It seems allright!

**Comment by maceligueta** [comment]
I talked with @jcotela and it seems like the Fluid Dynamics App requires (in general) the External Solvers Application. However, removing the import of the External App in these files shouldn't be problematic.
Concerning the Solid Mechanics App, it was being imported for the Embedded. Apparently, the Embedded process requires Elements (triangles) to be in a model part. Since the DEM App contains no triangular Elements and the Core does not either, we imported the Solid Mech App. We can remove this import now, and when we re-activate the embedded back we will look for a cleaner solution.

**Comment by maceligueta** [comment]
I just commented that to explain why those apps are being imported, they are not useless.
Let's merge and we will fix the problems when someone finds them.

**Comment by salvalatorre** [comment]
OK. I had just launched the benchmark Swimming DEM GiD simulation and ran fine so I assumed those imports were not necessary. Thanks for the info! Thanks both...

**Comment by jcotela** [comment]
@maceligueta There are now a few dummy elements and conditions in the [core](https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/includes/kratos_application.h), I believe that they were added to solve this problem. If you want generic trianlges, you can write them as `Element2D3N` or `Element3D3N` in the mpda and you will be able to read the model part using only the core.

**Comment by maceligueta** [comment]
Good to know, @jcotela! We will use them, thanks.

**Comment by RiccardoRossi** [comment]
Hi
   Just to tell that you should not use symbolic links, as they are not
portable (for example to win)

Cheers
Riccardo

**Comment by salvalatorre** [comment]
Thanks for your comments!

**Pull request merged**
