### PR TITLE
[Structural] optionally disable advanced claws

### PR DESCRIPTION
**Pull request by philbucher**
With this we can optionally disable the advanced constitutive laws which reduces the compilation time ~35%

I moved the advanced constitutive laws into a separate folder which makes the switch very easy

ofc by default they are being compiled

### CODE REVIEW

**Comment by AlejandroCornejo** [comment]
In my opinion makes sense, thanks @philbucher

**Comment by loumalouomega** [comment]
Can we merge #5665 first?

**Comment by philbucher** [comment]
> Can we merge #5665 first?

fine for me
just wanted to reinitiate the discussion

**Comment by rubenzorrilla** [comment]
Just wondering, but would it make sense that the default compilation is without the advanced stuff? I have the feeling that in the majority of the cases such advanced claws are only used by the researchers fully involved on these.

**Comment by philbucher** [comment]
> Just wondering, but would it make sense that the default compilation is without the advanced stuff? I have the feeling that in the majority of the cases such advanced claws are only used by the researchers fully involved on these.

@rubenzorrilla don't open Pandora's box :D

I agree but then it is excluded from the CI etc ...
I think there are many more reasons why it has to remain enabled by default (also bcs @RiccardoRossi wants it)

**Comment by philbucher** [comment]
btw I will solve the conflicts once more before it goes in, doing it constantly is too much effort

**Comment by rubenzorrilla** [comment]
> > Just wondering, but would it make sense that the default compilation is without the advanced stuff? I have the feeling that in the majority of the cases such advanced claws are only used by the researchers fully involved on these.
> 
> @rubenzorrilla don't open Pandora's box :D
> 
> I agree but then it is excluded from the CI etc ...
> I think there are many more reasons why it has to remain enabled by default (also bcs @RiccardoRossi wants it)

Understood. The CI reasoning is enough to close Pandora's box again.

**Comment by philbucher** [comment]
@RiccardoRossi do you have objections?

**Comment by philbucher** [comment]
I talked to Riccardo in person, he is fine with it, if also the other CLaw devs are (which I understand is the case)

I will fix the conflicts and then we can merge it

**Comment by loumalouomega** [comment]
In conclussion, by default all will be compiled, but advanced CL will be not mandatory?

**Comment by AlejandroCornejo** [comment]
Do we have to modify something in the configure.sh??

**Comment by philbucher** [comment]
Yes by default all of them are enabled, the have to be explicitly disabled
Only thing is that the advanced laws are in a different folder

**Comment by philbucher** [comment]
closing, I did a clean version of this in #5843

**Pull request closed without merging**
