### PR TITLE
[Core] Replace Elements Process - data is not being conserved

### PR DESCRIPTION
**Pull request by ddiezrod**
@pablobecker this should fix one of our failing tests

### CODE REVIEW

**Review by loumalouomega — APPROVED** [review]
Ok

**Comment by RiccardoRossi** [comment]
@ddiezrod data is now contained in the geometry, so if you keep the gomeetry it should be conserved automatically!

**Review by RiccardoRossi — COMMENTED** [review]
i mean, it should now be 

     elem.GetGeometry().Data() = ...

@pooyan-dadvand can u confirm?

**Comment by pablobecker** [comment]
that's why this line is no longer needed

**Review by RiccardoRossi — APPROVED** [review]
oh, i understood you were adding it.

my bad

**Comment by RiccardoRossi** [comment]
one question though. How was it compiling before? 

@pooyan-dadvand what is the Data() method of the element doing??

**Comment by ddiezrod** [comment]
@RiccardoRossi good point. Element/Conditions are derived from geometrical object which calls the geometry Data Value Container...

Now what I do not understand is why when doing 
`p_new_entity->Data() = it_entity->Data();`

the values were being restored to zero

**Comment by RiccardoRossi** [comment]
i looked in the code right now.
we have

~~~
    DataValueContainer& Data()
    {
        return pGetGeometry()->GetData();
    }
~~~

so what we were doing was to copy Data() onto itself.
That should  work unless the assignement operator has a problem when acting on the same data ... @pooyan-dadvand ?

**Comment by pooyan-dadvand** [comment]
Because I am not guarding the `operator=` of the `DataValueContainer `against the self assignment and the first line of it is clear which clears the both sides.... we may guard the self assignment by:

```c++
if(&rOther == this) 
   return this;
```

**Pull request merged**
