### PR TITLE
Removing warnings Clang in StructuralMechanicsApplication

### PR DESCRIPTION
**Pull request by loumalouomega**

### CODE REVIEW

**Comment by philbucher** [comment]
Thx!
But werent there also warnings in the shellse?

**Comment by loumalouomega** [comment]
I used clang-tidy, so I assumed that they were included, I will do manually...

**Comment by loumalouomega** [comment]
Done

**Review by philbucher — DISMISSED** [review]
thx!

**Comment by loumalouomega** [comment]
There still one warning concerning the new bbar element, but the only way to remove it is to modify the KinematicVariables struct that share all the solid elements

**Review by philbucher — APPROVED** [review]
seems fine to me, but I cannot check bcs I don't use clang

**Comment by loumalouomega** [comment]
@roigcarlo Do you thing could be agood idea to compile Travis with clang, in order to check the warnings too?

**Comment by philbucher** [comment]
I think there is a flag for this even for GCC but I didn't use it bcs Trilinos then prints hundrets of override warnings and I couldn't see the Kratos output any more

@roigcarlo maybe you could add this to the travis if you wanna stick with gcc?

**Comment by roigcarlo** [comment]
I preffer @philbucher approach tbh, I don't think adding another full build its a good idea at this time (also last time I tried to move to clang was a disaster). I will look out for that precise flag and add it 👍

**Comment by philbucher** [comment]
@roigcarlo I think I used sth [like this](https://stackoverflow.com/questions/29145476/requiring-virtual-function-overrides-to-use-override-keyword)

**Comment by roigcarlo** [comment]
Ok, let me add it to travis to se what happens

**Pull request merged**
