### PR TITLE
[ShapeOpt] avoid circular import problems

### PR DESCRIPTION
**Pull request by armingeiser**
In a packaged version of Kratos for CentOS using python 3.4 the circular import of the mapper factory does not work.

By moving the import inside the constructor where it is used, the problem is solved.

TODO: Does this happen because of ...
* ... python 3.4?
* ... packaging Kratos (installing python files and not only links)
* ... centOS

### CODE REVIEW

**Comment by philbucher** [comment]
@pooyan-dadvand @roigcarlo looks like someone else discovered your problems :|
@armingeiser I can explain you tmr what is happening

**Review by dbaumgaertner — APPROVED** [review]

**Comment by philbucher** [comment]
@ddiezrod @pablobecker could you please explain how you solve this in your cases?

**Comment by ddiezrod** [comment]
We had some problems at the beginning with the new install structure. Most of them were corrected moving the imports to the top of the files, this case seems to be the opposite so I dont really know whats going on here...

**Comment by pooyan-dadvand** [comment]
hmmmm... It seems to be related to the [difference of module load in python 2.7 and 3.4](https://chrisyeh96.github.io/2017/08/08/definitive-guide-python-imports.html#python-2-vs-python-3). Like missing `__init__.py` which is not necesary after 3.3.  

Usually the problem is not in the file you are doing the import but in the module that you are importing. Basically any import that could include your current module in the one importing.

**Comment by roigcarlo** [comment]
Is this still relevant? Should we merge it?

**Comment by armingeiser** [comment]
I completely forgot about this. I will need to merge master in order to trigger the required CI checks, right?

**Comment by roigcarlo** [comment]
Yup

**Pull request merged**
