### PR TITLE
[Trilinos] rename trilinos_application to TrilinosApplication

### PR DESCRIPTION
**Pull request by philbucher**
I searched, I think I found all places where renaming was necessary

Users should not be affected since we always import `KratosMultiphysics.TrilinosApplication`

### CODE REVIEW

**Comment by philbucher** [comment]
as requested by @RiccardoRossi marking this as AfterRelease

**Comment by philbucher** [comment]
release is done, conflicts are solved, this is ready for being merged :)

**Comment by philbucher** [comment]
ping

**Comment by pooyan-dadvand** [comment]
@KratosMultiphysics/technical-committee we like the idea and the new name but it seems that we will lose the history at least in GitHub interface. We still haven't check if we cannot follow the history in other GUIs

It would be great if you can check this.

**Comment by philbucher** [comment]
@KratosMultiphysics/technical-committee it seems like git is not able to track the renamings :(
I seached online and tried different things, but unfortunately without success :(

What should we do with this then?

@maceligueta I checked the DEM-App, you also seem to have lost the file-history after your renaming, or do you have a better solution?

**Comment by maceligueta** [comment]
@philbucher Exactly. We did not find a solution. According to what I googled, I think that git can possibly track the full history, but GitHub can't, currently.
Just for the record, once you are at the history page for some file, you can edit the http address putting the name of the old folder, then you can see the rest of the history.

**Comment by philbucher** [comment]
Thanks @maceligueta I will take another look

**Comment by philbucher** [comment]
I checked, apparently with `git log --follow file_name` one can still get the entire history of the file

source: http://thisbythem.com/blog/preserving-history-when-renaming-files-in-git/

**Comment by maceligueta** [comment]
Check out this extension for Chrome!!
https://chrome.google.com/webstore/detail/follow-for-github/agalokjhnhheienloigiaoohgmjdpned/related
It really works.
Thanks @roigcarlo .

**Comment by philbucher** [comment]
awesome!
Sounds like the history is not a problem any more :D

**Review by jcotela — APPROVED** [review]
@KratosMultiphysics/technical-committee approves.

**Pull request merged**
