### PR TITLE
Adding vector GidIO to python

### PR DESCRIPTION
**Pull request by loumalouomega**
Adding missing method to python

### CODE REVIEW

**Comment by jcotela** [comment]
What is the intended use for this? Mainly, I'm worried about how GiD will understand a vector of arbitrary (not 2 or 3) size.

**Comment by loumalouomega** [comment]
The idea is to use a vector of 3 components (the standard one) or 6 components (like stresses) in 3D, 2 and 3 in 2D. Without this is not possible to post a metric for example (my problem right now)

**Comment by loumalouomega** [comment]
Right now this is the implementation:

~~~c
    /**
     * writes nodal results for variables of type Vector
     * (note that only vectors with 3 components can be printed)
     */
    void WriteNodalResults( Variable<Vector> const& rVariable,
                            NodesContainerType& rNodes,
                            double SolutionTag, std::size_t SolutionStepNumber)
    {

        Timer::Start("Writing Results");

        GiD_fBeginResult( mResultFile, (char*)(rVariable.Name().c_str()), "Kratos",
                         SolutionTag, GiD_Matrix,
                         GiD_OnNodes, NULL, NULL, 0, NULL );
        for (NodesContainerType::iterator i_node = rNodes.begin();
                i_node != rNodes.end() ; ++i_node)
        {
            Vector& tempVector = i_node->FastGetSolutionStepValue(rVariable,
                                 SolutionStepNumber);
            if (tempVector.size() ==3 )
                GiD_fWriteVector(mResultFile, i_node->Id(), tempVector(0), tempVector(1), tempVector(2) );
            else if (tempVector.size() == 6 )
                GiD_fWrite3DMatrix( mResultFile, i_node->Id(), tempVector(0), tempVector(1), tempVector(2),
                                    tempVector(3), tempVector(4), tempVector(5) );
        }
        GiD_fEndResult(mResultFile);

        Timer::Stop("Writing Results");

    }
~~~

**Comment by jcotela** [comment]
Ok, if you take care to only print in sizes that GiD understands that's fine 👍

**Comment by loumalouomega** [comment]
For a metric in 2D it needs an extra check, which is the working dimension, but the problem is that the node doesn't know the working dimension. 

In this case there will be no error, but will represent a 2D matrix as a 3 components vector (X, Y, Z)

**Comment by loumalouomega** [comment]
Ping

**Comment by pooyan-dadvand** [comment]
But the question is if someones write a vector(5) and if is supported by GiD.

**Comment by loumalouomega** [comment]
The thing is that the current implementation will allow only to use the a vector of 3 components or 6 components

**Comment by loumalouomega** [comment]
This two options are supported by GiD

**Comment by pooyan-dadvand** [comment]
Is there any test for this? Would you please add one?

**Comment by loumalouomega** [comment]
Do you mean in python or cpp?, in any case the currecnt python test lacks of many checks

**Comment by pooyan-dadvand** [comment]
I would prefer a cpp one but python test is also welcomed

**Comment by loumalouomega** [comment]
OK, do I add other methods lacking to the existing test?

**Comment by pooyan-dadvand** [comment]
It would be great!!

**Comment by loumalouomega** [comment]
Test added

**Review by pooyan-dadvand — APPROVED** [review]
:+1:

**Pull request merged**
