### PR TITLE
[MeshingApplication] Some minor fixes

### PR DESCRIPTION
**Pull request by loumalouomega**
This adds some fixes detected by @tteschemacher

### CODE REVIEW

**Comment by loumalouomega** [comment]
@tteschemacher can we merge this?

**Comment by tteschemacher** [comment]
Perfect. Works with the changes. Thanks a lot!

**Review by tteschemacher — APPROVED** [review]

**Comment by loumalouomega** [comment]
Mesh

**Comment by dagmawibekel** [comment]
Please wait a little longer until you merge it to the master, since i encoutered problems and i'm trying to figure out if there is sth wrong from my side or from mmg.

**Comment by loumalouomega** [comment]
Ups

**Comment by loumalouomega** [comment]
In any case what this PR did is not harming, just adds some extra checks to avoid errors

**Comment by dagmawibekel** [comment]
I'll let you know as soon as i found the error.

**Comment by dagmawibekel** [comment]
I am trying to narrow down the error. The mmg process is remeshing my background mesh and the visualization of the mesh created with mmg looks quite good. However after remeshing i get a segmentation fault in the very first timestep and i think it is related to the remeshing of my domain. Somehow i get a ZeroDivisionError in the apply_outlet_process, which i don't get when don't remesh the background mesh. i included the error message to make it clearer... 

Traceback (most recent call last):
  File "MainKratos.py", line 216, in <module>
    simulation.Run()
  File "/home/mdagmawib/Kratos/KratosRelease/kratos/python_scripts/analysis_stage.py", line 48, in Run
    self.RunSolutionLoop()
  File "/home/mdagmawib/Kratos/KratosRelease/kratos/python_scripts/analysis_stage.py", line 63, in RunSolutionLoop
    self.InitializeSolutionStep()
  File "/home/mdagmawib/Kratos/KratosRelease/kratos/python_scripts/analysis_stage.py", line 126, in InitializeSolutionStep
    self.ApplyBoundaryConditions() #here the processes are called
  File "MainKratos.py", line 37, in ApplyBoundaryConditions
    super(FluidDynamicsAnalysisWithFlush,self).ApplyBoundaryConditions()
  File "/home/mdagmawib/Kratos/KratosRelease/kratos/python_scripts/analysis_stage.py", line 188, in ApplyBoundaryConditions
    process.ExecuteInitializeSolutionStep()
  File "/home/mdagmawib/Kratos/KratosRelease/applications/FluidDynamicsApplication/python_scripts/apply_outlet_process.py", line 88, in ExecuteInitializeSolutionStep
    self._ComputeOutletCharacteristicVelocity()
  File "/home/mdagmawib/Kratos/KratosRelease/applications/FluidDynamicsApplication/python_scripts/apply_outlet_process.py", line 142, in _ComputeOutletCharacteristicVelocity
    outlet_avg_vel_norm /= tot_len
ZeroDivisionError: float division by zero
BuilderAndSolver: Clear Function called
Segmentation fault (core dumped)

**Comment by loumalouomega** [comment]
I don't know that process, which information requires?

**Comment by rubenzorrilla** [comment]
It is a method inside the `NavierStokesWallCondition`. It adds an extra contribution to prevent inflow from the outlet. At first glance it seems that `tot_len` is zero.

**Comment by loumalouomega** [comment]
OK, @dagmawibekel I compiled your branch again and I rerun, the problem is that you are remeshing only the computing model part, you should remesh the main model part. In your MainKratos.py change:

~~~py
        print("KratosMultiphysics.MeshingApplication.MmgProcess2D")
        mmg_process = KratosMultiphysics.MeshingApplication.MmgProcess2D(
                self._GetSolver().GetComputingModelPart(),
                mmg_parameters)
        mmg_process.Execute()
~~~

with

~~~py
        print("KratosMultiphysics.MeshingApplication.MmgProcess2D")
        mmg_process = KratosMultiphysics.MeshingApplication.MmgProcess2D(
                self._GetSolver().GetComputingModelPart().GetRootModelPart(),
                mmg_parameters)
        mmg_process.Execute()
~~~

**Comment by dagmawibekel** [comment]
First of all thanks! I changed it as you (@loumalouomega) proposed to overcome the problem with the output_process. However, i still get an error (segmentation fault) in the second step, which i don't get if i do not remesh the background mesh. 

Fluid Dynamics Analysis: Analysis -START-  
Fluid Dynamics Analysis: STEP:  1 
Fluid Dynamics Analysis: TIME:  0.01 
ResidualBasedBlockBuilderAndSolver: Setting up the dofs
ResidualBasedBlockBuilderAndSolver: Number of threads1

ResidualBasedBlockBuilderAndSolver: Initializing element loop
ResidualBasedBlockBuilderAndSolver: Initializing ordered array filling

ResidualBasedBlockBuilderAndSolver: Number of degrees of freedom:68430
ResidualBasedBlockBuilderAndSolver: Finished setting up the dofs
ResidualBasedBlockBuilderAndSolver: End of setup dof set

Setup Dofs Time: 0.0925948
Setup System Time: 0.00116091
System Matrix Resize Time: 0.210177
System Construction Time: 0.304008
Fluid Dynamics Analysis: STEP:  2 
Fluid Dynamics Analysis: TIME:  0.02 
Segmentation fault (core dumped)

**Pull request merged**
