### PR TITLE
ASCII logo for Optimization Application

### PR DESCRIPTION
**Pull request by Igarizza**
**📝 Description**
I have tried the full-name Optimization Application, but the name is too big. I have used the abbreviation we have used a lot. 

Here, is how it looks:

Screenshot from 2023-05-10 10-29-54

Please mark the PR with appropriate tags: 
- Api Breaker, Mpi, etc...

**🆕 Changelog**
Please summarize the changes in one list to generate the changelog:
E.g.
- Added feature X to Y
- Added Foo Application
- Fixed X (#XXXX Reference to issue if apply) 
- etc...

### CODE REVIEW

**Comment by RezaNajian** [comment]
@Igarizza @sunethwarna we have App/Application three times repeated. I would suggest to drop App/Application and only keep Optimization. What do you think ?!

**Review by RezaNajian — COMMENTED** [review]
@Igarizza   we have App/Application three times repeated. I would suggest to drop App/Application and only keep Optimization. What do you think ?!

**Comment by Igarizza** [comment]
> @Igarizza we have App/Application three times repeated. I would suggest to drop App/Application and only keep Optimization. What do you think ?!

It doesn't bother me. In my opinion "Optimization" is way too long for logo. Having just "Opt" is too short. "Optimiz", etc. doesn't sound like a correct shortening. Also, two other prints are just some standart Kratos logs and they may change in the future; hence, I think Logo should be in some sence independent from them.

**Comment by RezaNajian** [comment]
@Igarizza ok fine then please merge it. Tnx.

**Review by RezaNajian — APPROVED** [review]

**Review by sunethwarna — APPROVED** [review]

**Pull request merged**
