### PR TITLE
[CoSim] missing changes for multi coupling and FSCI example

### PR DESCRIPTION
**Pull request by philbucher**
**Description**
This PR does minor missing refactor to enable multi-/ nested coupling aka where one coupled simulation can be used in another one.
E.g. FSCI (FSI with control) where the inner solution is the structure coupled with the controller and then this coupled simulation is coupled with the fluid
((S <=> C) <=> F)

@adityaghantasala those are basically the changes we did together some time ago :)

@mpentek you can use this to test, it should work but I will add some tests before merging

This PR is also a prerequisite for moving the implementation of the `CouplingInterfaceData` to C++ which will help a lot for dropping the numpy dependency in the future (for most things)

### CODE REVIEW

**Comment by philbucher** [comment]
reminder: delete branch CoSim/changes-to-make-multicoupling after this is merged

**Comment by philbucher** [comment]
@mpentek I got the (FS)CI case to work now, based on the Sdof FSI! I think it is quite cool, esp that we can take a preexisting case in a new simulation. Take a look at `cosim_sdof_fsci_parameters.json`

- I don't really know how to tune the parameters of the controller/damper, hence the reduction in amplitude is quite small, see the following pic. The original amplitude was ~0.2, now is ~0.15. Also the controller doesn't really move, I think the amplitudes should be reversed. Can you help me?
- I had to add `add_values` to the pure FSI Sdof case for now as otherwise the reactions from the damper would be overwritten. I will think of a better solution for this, most probably we will have to improve a bit the sdof solver itself.

image

**Comment by mpentek** [comment]
> @mpentek I got the (FS)CI case to work now, based on the Sdof FSI! I think it is quite cool, esp that we can take a preexisting case in a new simulation. Take a look at `cosim_sdof_fsci_parameters.json`
> 
> * I don't really know how to tune the parameters of the controller/damper, hence the reduction in amplitude is quite small, see the following pic. The original amplitude was ~0.2, now is ~0.15. Also the controller doesn't really move, I think the amplitudes should be reversed. Can you help me?
> * I had to add `add_values` to the pure FSI Sdof case for now as otherwise the reactions from the damper would be overwritten. I will think of a better solution for this, most probably we will have to improve a bit the sdof solver itself.
> 
> image

I pushed a WIP sdof-sdof as I think there might be some issue we need to resolve. Now the structure and "controller" parameters are at least tuned such that the controller should noticably reduce the vibration amplitude of the structure, when this is excited close to the eigenfrequency (either by fluid/root point disp/external force).

**Comment by mpentek** [comment]
@philbucher the SDoF-SDoF- seems to work fine. the FSCI coupling is problematic (the controller does not even output a file), so I think something is still wrong with the syntax.

**Review by mpentek — APPROVED** [review]

**Pull request merged**
