### PR TITLE
[SMA] Correcting CL tests

### LINKED ISSUE #7762: Test failure in Structural plasticity
~~~
======================================================================
FAIL: test_execution (structural_mechanics_test_factory.SmallDeformationPlasticityTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/philipp/software/Kratos_MasterBranch/applications/StructuralMechanicsApplication/tests/structural_mechanics_test_factory.py", line 72, in test_execution
    self.test.RunSolutionLoop()
  File "/home/philipp/software/Kratos_MasterBranch/install/KratosMultiphysics/analysis_stage.py", line 69, in RunSolutionLoop
    self.FinalizeSolutionStep()
  File "/home/philipp/software/Kratos_MasterBranch/install/KratosMultiphysics/analysis_stage.py", line 151, in FinalizeSolutionStep
    process.ExecuteFinalizeSolutionStep()
  File "/home/philipp/software/Kratos_MasterBranch/install/KratosMultiphysics/from_json_check_result_process.py", line 55, in ExecuteFinalizeSolutionStep
    self.assertTrue(self.process.IsCorrectResult(), "Results do not coincide with the JSON reference\n" + self.process.GetErrorMessage())
AssertionError: False is not true : Results do not coincide with the JSON reference
Error checking for variable UNIAXIAL_STRESS in GP 0, results:
Element 1 2980492!=3000002; rel_tol=1e-06, abs_tol=0.001
Error checking for variable UNIAXIAL_STRESS in GP 1, results:
Element 1 2980492!=3000002; rel_tol=1e-06, abs_tol=0.001
Error checking for variable UNIAXIAL_STRESS in GP 2, results:
Element 1 2980492!=3000002; rel_tol=1e-06, abs_tol=0.001
Error checking for variable UNIAXIAL_STRESS in GP 3, results:
Element 1 2980492!=3000002; rel_tol=1e-06, abs_tol=0.001
Error checking for variable UNIAXIAL_STRESS in GP 4, results:
Element 1 2980492!=3000002; rel_tol=1e-06, abs_tol=0.001
Error checking for variable UNIAXIAL_STRESS in GP 5, results:
Element 1 2980492!=3000002; rel_tol=1e-06, abs_tol=0.001
Error checking for variable UNIAXIAL_STRESS in GP 6, results:
Element 1 2980492!=3000002; rel_tol=1e-06, abs_tol=0.001
Error checking for variable UNIAXIAL_STRESS in GP 7, results:
Element 1 2980492!=3000002; rel_tol=1e-06, abs_tol=0.001
~~~

can you Guys please check?
We want to have it all working for the upcoming release
Cheers

### PR DESCRIPTION
**Pull request by AlejandroCornejo**
I corrected the results of the tests according to the more updated version of the CL.

I must say that there are 3 tests that are still failling (Trusses, Beams)

closes #7762

### CODE REVIEW

**Review by philbucher — APPROVED** [review]
thx!

then tonight we will hopefully for the very first time have a clean nightly build (since we moved to github actions almost a year ago!) :D

**Review by loumalouomega — APPROVED** [review]

**Comment by AlejandroCornejo** [comment]
Just in case you didn't notice,  there are 3 tests that are still failling (Trusses, Beams)

**Comment by philbucher** [comment]
> I must say that there are 3 tests that are still failling (Trusses, Beams)

can you post the failures?
I didn't get them

**Comment by AlejandroCornejo** [comment]
> > I must say that there are 3 tests that are still failling (Trusses, Beams)
> 
> can you post the failures?
> I didn't get them

======================================================================
ERROR: test_formfinding_trusses (test_patch_test_formfinding_trusses.TestPatchTestFormfinding)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/alejandro/907A2DE47A2DC834/Kratos/Kratos/applications/StructuralMechanicsApplication/tests/test_patch_test_formfinding_trusses.py", line 171, in test_formfinding_trusses
    formfinding_strategy = self._setup_formfinding(mp)
  File "/media/alejandro/907A2DE47A2DC834/Kratos/Kratos/applications/StructuralMechanicsApplication/tests/test_patch_test_formfinding_trusses.py", line 112, in _setup_formfinding
    move_mesh_flag)
TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. KratosStructuralMechanicsApplication.FormfindingStrategy(arg0: Kratos.ModelPart, arg1: Kratos.Scheme, arg2: Kratos.LinearSolver, arg3: Kratos.ConvergenceCriteria, arg4: Kratos.BuilderAndSolver, arg5: Kratos.ModelPart, arg6: bool, arg7: str, arg8: Kratos.Parameters, arg9: int, arg10: bool, arg11: bool, arg12: bool)

Invoked with: <Kratos.ModelPart object at 0x7f48b9ee7490>, <Kratos.ResidualBasedIncrementalUpdateStaticScheme object at 0x7f48bd749340>, <Kratos.ResidualCriteria object at 0x7f48bd7496f8>, <Kratos.ResidualBasedBlockBuilderAndSolver object at 0x7f48bd7496c0>, <Kratos.ModelPart object at 0x7f48b9ee7490>, False, 'none', <Kratos.Parameters object at 0x7f48bd749068>, 1000, True, True, True

======================================================================
ERROR: test_cr_beam_nonlinear (test_patch_test_cr_beam.StaticPatchTestBeam3D2N)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/alejandro/907A2DE47A2DC834/Kratos/Kratos/applications/StructuralMechanicsApplication/tests/test_patch_test_cr_beam.py", line 559, in test_cr_beam_nonlinear
    self._solve_nonlinear(mp)
  File "/media/alejandro/907A2DE47A2DC834/Kratos/Kratos/applications/StructuralMechanicsApplication/tests/test_patch_test_cr_beam.py", line 116, in _solve_nonlinear
    convergence_criterion = KratosMultiphysics.MixedGenericCriteria(
AttributeError: module 'KratosMultiphysics' has no attribute 'MixedGenericCriteria'

======================================================================
ERROR: test_cr_beam_nonlinear (test_patch_test_cr_beam.StaticPatchTestBeam2D2N)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/alejandro/907A2DE47A2DC834/Kratos/Kratos/applications/StructuralMechanicsApplication/tests/test_patch_test_cr_beam.py", line 1057, in test_cr_beam_nonlinear
    self._solve_nonlinear(mp)
  File "/media/alejandro/907A2DE47A2DC834/Kratos/Kratos/applications/StructuralMechanicsApplication/tests/test_patch_test_cr_beam.py", line 722, in _solve_nonlinear
    convergence_criterion = KratosMultiphysics.MixedGenericCriteria(
AttributeError: module 'KratosMultiphysics' has no attribute 'MixedGenericCriteria'

----------------------------------------------------------------------

**Comment by SergioJimenezReyes** [comment]
Thx!

**Comment by philbucher** [comment]
> > > I must say that there are 3 tests that are still failling (Trusses, Beams)
> > 
> > 
> > can you post the failures?
> > I didn't get them
> 
> ```
> ======================================================================
> ERROR: test_formfinding_trusses (test_patch_test_formfinding_trusses.TestPatchTestFormfinding)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/media/alejandro/907A2DE47A2DC834/Kratos/Kratos/applications/StructuralMechanicsApplication/tests/test_patch_test_formfinding_trusses.py", line 171, in test_formfinding_trusses
>     formfinding_strategy = self._setup_formfinding(mp)
>   File "/media/alejandro/907A2DE47A2DC834/Kratos/Kratos/applications/StructuralMechanicsApplication/tests/test_patch_test_formfinding_trusses.py", line 112, in _setup_formfinding
>     move_mesh_flag)
> TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
>     1. KratosStructuralMechanicsApplication.FormfindingStrategy(arg0: Kratos.ModelPart, arg1: Kratos.Scheme, arg2: Kratos.LinearSolver, arg3: Kratos.ConvergenceCriteria, arg4: Kratos.BuilderAndSolver, arg5: Kratos.ModelPart, arg6: bool, arg7: str, arg8: Kratos.Parameters, arg9: int, arg10: bool, arg11: bool, arg12: bool)
> 
> Invoked with: <Kratos.ModelPart object at 0x7f48b9ee7490>, <Kratos.ResidualBasedIncrementalUpdateStaticScheme object at 0x7f48bd749340>, <Kratos.ResidualCriteria object at 0x7f48bd7496f8>, <Kratos.ResidualBasedBlockBuilderAndSolver object at 0x7f48bd7496c0>, <Kratos.ModelPart object at 0x7f48b9ee7490>, False, 'none', <Kratos.Parameters object at 0x7f48bd749068>, 1000, True, True, True
> 
> ======================================================================
> ERROR: test_cr_beam_nonlinear (test_patch_test_cr_beam.StaticPatchTestBeam3D2N)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/media/alejandro/907A2DE47A2DC834/Kratos/Kratos/applications/StructuralMechanicsApplication/tests/test_patch_test_cr_beam.py", line 559, in test_cr_beam_nonlinear
>     self._solve_nonlinear(mp)
>   File "/media/alejandro/907A2DE47A2DC834/Kratos/Kratos/applications/StructuralMechanicsApplication/tests/test_patch_test_cr_beam.py", line 116, in _solve_nonlinear
>     convergence_criterion = KratosMultiphysics.MixedGenericCriteria(
> AttributeError: module 'KratosMultiphysics' has no attribute 'MixedGenericCriteria'
> 
> ======================================================================
> ERROR: test_cr_beam_nonlinear (test_patch_test_cr_beam.StaticPatchTestBeam2D2N)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/media/alejandro/907A2DE47A2DC834/Kratos/Kratos/applications/StructuralMechanicsApplication/tests/test_patch_test_cr_beam.py", line 1057, in test_cr_beam_nonlinear
>     self._solve_nonlinear(mp)
>   File "/media/alejandro/907A2DE47A2DC834/Kratos/Kratos/applications/StructuralMechanicsApplication/tests/test_patch_test_cr_beam.py", line 722, in _solve_nonlinear
>     convergence_criterion = KratosMultiphysics.MixedGenericCriteria(
> AttributeError: module 'KratosMultiphysics' has no attribute 'MixedGenericCriteria'
> 
> ----------------------------------------------------------------------
> ```

@AlejandroCornejo I think you are not compiling the latest master, those tests are in the CI
probably your python scripts have a different version than your compiled code

**Comment by AlejandroCornejo** [comment]
It was a recent version of the master (this morning). Anyway I've done a merge and recompiled and it happens the same to me :S

**Comment by AlejandroCornejo** [comment]
Seems that something is wrong with the MMG?

**Comment by marcnunezc** [comment]
> Seems that something is wrong with the MMG?

Yes! Sorry for the inconvenience, was temporarily fixed in #7772 . Merge master to get the fix!

**Comment by philbucher** [comment]
the test in Structural still fail

**Comment by AlejandroCornejo** [comment]
> the test in Structural still fail

yes, I've just checked, How is this possible? I'll check again tomorrow :S

**Comment by AlejandroCornejo** [comment]
This brach got bugged I don't know why. Continue in https://github.com/KratosMultiphysics/Kratos/pull/7779

**Pull request closed without merging**
