### PR TITLE
[Fluid] Fix embedded drag calculation

### PR DESCRIPTION
**Pull request by rubenzorrilla**
This PR fixes two minor issues in the embedded drag calculation. The first is an import module related one. The second is an memory error that occurs when the embedded drag is computed before the buffer has been filled (@dagmawibekel  I think this is the one you found some time ago...).

### CODE REVIEW

**Review by philbucher — APPROVED** [review]
looks ok to me

**Comment by rubenzorrilla** [comment]
> looks ok to me

Thanks!

**Comment by sunethwarna** [comment]
Hi, tafter this PR , the adjoint sensitivity tests in fluid dynamics fails since, the drag calculation process ignores the first calculation step of drag in following line.
https://github.com/KratosMultiphysics/Kratos/blob/260699ca86e730a687567a7442eaf42a4c109a0d/applications/FluidDynamicsApplication/python_scripts/compute_drag_process.py#L90

If this is required as a fix for embedded drag calculation, then we need a proper solution for transient discrete adjoint calculation as well. One would be to put this in the embedded drag calculation process since this is a fix for embedded drag calculation, not for whole drag process ryt? Other one is, we have to redesign the adjoint one element tests, which is little bit troublesome as I see. Any other ideas? :/

@rubenzorrilla 

PS: This affects all the unit tests which uses the normal drag process as well.

**Comment by philbucher** [comment]
that is a bummer

@sunethwarna why are those tests not in the CI?

**Comment by sunethwarna** [comment]
Maybe they were not added due to time limitations in the CI? I can try adding them to CI as well if it is allowed :) @rubenzorrilla can provide a better answer :|

**Comment by sunethwarna** [comment]
Other thing is, if we want to add them to CI, we need the HDF5Application as well since adjoint calculation requires primal solution in h5 files, which is a no go ryt?

**Comment by philbucher** [comment]
ah ok thats the reason.
For Travis I think it is not worth the effort, but for the [new actions](https://github.com/KratosMultiphysics/Kratos/actions) we have more options, and I would really make an effort to also include the HDF-app there asap.
However this will probably only happen beginning of next year

**Comment by rubenzorrilla** [comment]
Actually, I think that what we did in here is correct, as it prevents a memory leak. Does it make sense to calculate the sensitivities if the buffer is not completely filled yet?

**Comment by sunethwarna** [comment]
In fluid dynamics, the buffer size is two. So it is ok to skip calculating drag on the 0th step (initial step, which is skipped by the fluid dynamics solver). But in the first step, fluid dynamics solver calculates drag.

Wouldn't the condition be like the following?
`if(((current_time >= self.interval[0]) and  (current_time < self.interval[1])) and (current_step + 1 >= self.model_part.GetBufferSize())):`

**Comment by rubenzorrilla** [comment]
> In fluid dynamics, the buffer size is two. So it is ok to skip calculating drag on the 0th step (initial step, which is skipped by the fluid dynamics solver). But in the first step, fluid dynamics solver calculates drag.
> 
> Wouldn't the condition be like the following?
> `if(((current_time >= self.interval[0]) and (current_time < self.interval[1])) and (current_step + 1 >= self.model_part.GetBufferSize())):`

The buffer size is not necessarily two. It depends on the time discretization scheme you use. In case you use the BDF2, it is three.

What you post is actually what it is right now implemented.

**Comment by sunethwarna** [comment]
@rubenzorrilla , we still miss the equal sign in the check, which causes the adjoint sensitivity tests to fail :/

**Comment by sunethwarna** [comment]
This is what we have
`(current_step + 1 > self.model_part.GetBufferSize())`
and this is what I propose
`(current_step + 1 >= self.model_part.GetBufferSize())`

Will this be a  problem in embedded drag calculation?

**Comment by rubenzorrilla** [comment]
> @rubenzorrilla , we still miss the equal sign in the check, which causes the adjoint sensitivity tests to fail :/

You're right. I missed your `>=`.  No, actually `>=` is better. I'd recover the branch and fix it ASAP. Sorry for the inconveniences.

**Comment by sunethwarna** [comment]
thanks :)

**Pull request merged**
