### PR TITLE
[Core] Refactor and clean up `CalculateNodalAreaProcess`

### PR DESCRIPTION
**Pull request by loumalouomega**
**📝 Description**

 This PR refactors and clean up `CalculateNodalAreaProcess`:

  - Header clean up.
  - Defined Model/Parameters constructors and methods for the `CalculateNodalAreaProcess` class.
  - Added/modified class methods for `CalculateNodalAreaProcess`, including constructors, destructor, `Execute()` method descriptions, and `GetDefaultParameters()` method.
  - Expose new `Model`/`Parameters` constructor to python.
  - Replace `typdef` by `using`.
  - Adds documentation for the `CalculateNodalAreaProcess` process. It describes the functionality, parameters, and defaults of the process.

**🆕 Changelog**

- [Refactor and clean up `CalculateNodalAreaProcess`](https://github.com/KratosMultiphysics/Kratos/commit/f1ba80fdc2db8a2491c195c2f35d7eafac6675bc)
- [Expose new Model/Parameters constructor to python](https://github.com/KratosMultiphysics/Kratos/commit/2fd2da9ba806a9dc08850ad94606ad5318f8750d)
- [Update documentation](https://github.com/KratosMultiphysics/Kratos/commit/6735e7a8bff3059b0d4a63cffa830ddb764623ab)
- [Minor replace for typedef by using in C++ test](https://github.com/KratosMultiphysics/Kratos/commit/c3bd1f2bdbf4bf6076110f5840b86061f4626e32)

### CODE REVIEW

**Comment by loumalouomega** [comment]
@roigcarlo apparentlt the documentation build is failing, can you guess why?

**Comment by loumalouomega** [comment]
> Looks good to me? where do you see the error?
> 
> Edit: You can see it here [kratosmultiphysics.github.io/Kratos/pages/Kratos/Processes/Calculation/calculate_nodal_area_process.html](https://kratosmultiphysics.github.io/Kratos/pages/Kratos/Processes/Calculation/calculate_nodal_area_process.html)
> 
> It does not appear on the side menu because you didn't add it, but the page is correctly deployed

**Comment by loumalouomega** [comment]
Anyone?¿

**Review by roigcarlo — APPROVED** [review]
:+1: As far as i can tell the code is ok and doc is there.

**Pull request merged**
