### PR TITLE
[Core] Avoiding need to register dummy conditions to use custom DoF with the constraints

### PR DESCRIPTION
**Pull request by loumalouomega**
This add automatically the dofs and equations ids of the constraints into the complete system. Some code from the Block B&S has been copied, the only way to reduce this code cuplications is unfortunely to refactor a little bit the Block B&S

### CODE REVIEW

**Comment by loumalouomega** [comment]
There is a test on https://github.com/KratosMultiphysics/Kratos/tree/core/dummy-condition branch. But I don't want to put dummy conditions or any additional things to create a test

**Comment by adityaghantasala** [comment]
I understand why this is required. Is there a reason why it is passed through scheme ? This can be doen without involving the scheme. The constraints are directly asked for their contribution (modification), for example : 
https://github.com/KratosMultiphysics/Kratos/blob/c23b34e7839555ca1ab699f5968f5cabc2bbb242/kratos/solving_strategies/builder_and_solvers/residualbased_block_builder_and_solver_with_constraints.h#L717

**Comment by adityaghantasala** [comment]
Asking the constraint directly for their eq ids and dofs will avoid having `Constraint_EquationId` and `GetConstraintDofList` functions in scheme base class which actually are the only ones in connection to the constraints.

**Comment by loumalouomega** [comment]
Do you mean not to add it to scheme.h?, the idea is to be consistent with the current implementation

**Comment by adityaghantasala** [comment]
Yes not to add to scheme.h.
The constraints do not pass through the scheme also in the Build  function.

**Comment by loumalouomega** [comment]
That is easy

**Comment by loumalouomega** [comment]
Done

**Comment by adityaghantasala** [comment]
yes exactly like this.

**Review by adityaghantasala — APPROVED** [review]
Please proceed merging as soon as the tests pass !

**Comment by loumalouomega** [comment]
Thanks

**Pull request merged**
