### PR TITLE
[Core] Minor include cleaning

### PR DESCRIPTION
**Pull request by loumalouomega**
Just some includes that can be removed

### CODE REVIEW

**Comment by loumalouomega** [comment]
Ping @roigcarlo

**Comment by roigcarlo** [comment]
Are you 200% sure nobody was cascade-using the ones in integration point??

**Comment by loumalouomega** [comment]
Yes, I compiled many applications

**Review by roigcarlo — APPROVED** [review]
Ok...

**Comment by loumalouomega** [comment]
I am doing it to reduce for the greater good :D

**Pull request merged**
