### PR TITLE
[CompareTwoFilesCheckProcess] new syntax

### PR DESCRIPTION
**Pull request by philbucher**

### CODE REVIEW

**Review by loumalouomega — DISMISSED** [review]
OK

**Review by jcotela — DISMISSED** [review]
Approving since this is just really a cleanup, but we should probably speak about why this process needs to be mpi-aware (I would think that even in mpi the comparison is done from a single process?)

**Comment by philbucher** [comment]
The process writing the file might not be the one checking it, therefore the barrier is needed

Btw the syntax I adopted from your test fails in Travis

**Comment by jcotela** [comment]
Still, I don't love that this forces the user to call this process from all ranks (otherwise we are creating a deadlock).

I will look into the test issue on Monday, I guess I am missing a & somewhere but I don't have an mpi installation to test.

**Comment by philbucher** [comment]
Ok lets discuss it on Monday

**Comment by jcotela** [comment]
I think I fixed the pybind issue with DataCommunicator. Some core and structural tests are still failing, however (due to tolerance issues, I believe).

**Comment by philbucher** [comment]
seems to work now :)

**Comment by philbucher** [comment]
can someone approve pls? :)

**Review by jcotela — APPROVED** [review]

**Pull request merged**
