### PR TITLE
Core/adding debug helpers

### PR DESCRIPTION
**Pull request by RiccardoRossi**
some more debug wards in the case of FastGetsolutionStepValue

### CODE REVIEW

**Comment by philbucher** [comment]
Out of curiosity : is using KRATOS_DEBUG_ERROR the same as protecting KRATOS_ERROR with the compiler directive?
I.e. is the compiler smart enough to optimize the additional calls away?

**Comment by RiccardoRossi** [comment]
it is the same as

#ifdef KRATOS_DEBUG
        KRATOS_ERROR ...
#endif KRATOS_DEBUG

so, the compiler will simply not see this code since  the preprocessor will take it away

**Comment by philbucher** [comment]
I mean does the [additional if statement](https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/includes/exception.h#L165) have an impact on the performance?

**Comment by philbucher** [comment]
ping

**Review by philbucher — APPROVED** [review]
Looks reasonable

**Comment by pooyan-dadvand** [comment]
Your doubt about the if is correct but it is too easy for any optimizer to be worried about.

**Pull request merged**
