### PR TITLE
Documentation/adding feature lists

### PR DESCRIPTION
**Pull request by pooyan-dadvand**
This PR adds the feature list for the core and main applications. Any contribution to it is more than welcomed.

### CODE REVIEW

**Review by jcotela — DISMISSED** [review]

**Comment by jcotela** [comment]
Note that travis is failing with some strange error about examples.

**Comment by pooyan-dadvand** [comment]
@roigcarlo Would you please take a look at it to see why travis and appveyor are failing?

**Comment by roigcarlo** [comment]
@pooyan-dadvand Time limit.

As a reminder for everyone, you can check the causes in the message tab. It is far clearer than travis:

> Build execution time has reached the maximum allowed time for your plan (60 minutes).

**Comment by roigcarlo** [comment]
Ok, the error with travis is due to https://github.com/KratosMultiphysics/Kratos/pull/1575/commits/533657c175563175da6b30b5789019149e3eef28 adding the submodule examples.

Is this intentional ?

**Comment by loumalouomega** [comment]
@roigcarlo You have pointed to a typo, which submodule?, be careful with submodules http://slopjong.de/2013/06/04/git-why-submodules-are-evil/

**Comment by roigcarlo** [comment]
@loumalouomega Look closely, there is a new folder along with the typo correction. The submodule is "examples", but it is not set in the .gitmodules, and seems that travis tries to download everything recursively, which cannot because it does not have the location of examples.

Appveyor on the other hand only downloads the main repo so everything its ok.

**Comment by loumalouomega** [comment]
Okidoki

**Comment by roigcarlo** [comment]
@pooyan-dadvand Now it works. If someone can please approve.

**Review by roigcarlo — APPROVED** [review]
I can! But I shouldn't so I will have to check this in the config....

**Pull request merged**
