### PR TITLE
[ContactStructuralMechanicsApplication] Adapt interface of the conditions

### PR DESCRIPTION
**Pull request by loumalouomega**
As #6772 but for contact

### CODE REVIEW

**Comment by loumalouomega** [comment]
Some tests are failing, wait for approval

**Review by philbucher — COMMENTED** [review]
if you want to be sure you didn't miss anything you could remove this method from the baseclass
then it will not compile if you missed sth
Thats how I did it

**Comment by loumalouomega** [comment]
> if you want to be sure you didn't miss anything you could remove this method from the baseclass
> then it will not compile if you missed sth
> Thats how I did it

Now the problem is not in the conditions, but the calls from strategies and stuff

**Comment by loumalouomega** [comment]
I think is fixed, running all tests

**Comment by philbucher** [comment]
> Now the problem is not in the conditions, but the calls from strategies and stuff

are you sure?
I ported quite a lot now and I think I fixed those issues

**Comment by loumalouomega** [comment]
> > Now the problem is not in the conditions, but the calls from strategies and stuff
> 
> are you sure?
> I ported quite a lot now and I think I fixed those issues

I have my own stuff...

**Comment by philbucher** [comment]
ah ok

Well I would strongly recommend working top to bottom, start with the B&S, then the Schemes and other classes and only then the elements/conditions

Once I am done with Structural I will create an issue explaining this

**Comment by loumalouomega** [comment]
> ah ok
> 
> Well I would strongly recommend working top to bottom, start with the B&S, then the Schemes and other classes and only then the elements/conditions
> 
> Once I am done with Structural I will create an issue explaining this

:+1:

**Comment by loumalouomega** [comment]
All test run, this can be merged :D

**Review by philbucher — APPROVED** [review]
ok, thx

I didn't check in detail, I trust you can do this right :)

But nice that there seem to not be any race-conditions there!

**Pull request merged**
