### PR TITLE
[StructuralMechanicsApplication] Some flags incorrectly set on elastic CL

### PR DESCRIPTION
**Pull request by loumalouomega**
Some minor correction on CL flags on elastic laws

### CODE REVIEW

**Review by AlejandroCornejo — APPROVED** [review]

**Comment by loumalouomega** [comment]
Thanks!

**Comment by philbucher** [comment]
Have you run all the tests?

**Comment by loumalouomega** [comment]
This change doesn't affect to the tests, it just modifies some methods that are call for post-process of for complex-combination laws

**Comment by loumalouomega** [comment]
In fact I just detected that some minor things are missing sorry, one sec

**Pull request merged**
