### PR TITLE
[Core] Bugfix Geometry Id

### PR DESCRIPTION
**Pull request by tteschemacher**
Fixing the bug for ids larger than 63.

### CODE REVIEW

**Comment by tteschemacher** [comment]
The problem was that sizeof gives the size in bytes but not bits. So we always changed the 7th and 6th bit. That's why the highest possible id was 63.

Please let it go. @pooyan-dadvand

**Comment by tteschemacher** [comment]
Ping @pooyan-dadvand

**Comment by tteschemacher** [comment]
@pooyan-dadvand

**Review by pooyan-dadvand — APPROVED** [review]
My fault! I should have noticed it!!

**Comment by tteschemacher** [comment]
Thank you!

Well, playing with bits is dangerous... ;)

**Comment by pooyan-dadvand** [comment]
Indeed is dangerous! :smirk: 

Do you need the branch?

**Comment by tteschemacher** [comment]
No just forgot to delete. Thanks for reminding.

**Pull request merged**
