### PR TITLE
Modifying stress tensor names

### PR DESCRIPTION
**Pull request by salvalatorre**

### CODE REVIEW

**Comment by salvalatorre** [comment]
The NODAL_CAUCHY_STRESS_TENSOR variable could not be removed because it is currently being used by the Dam application.

**Review by ipouplana — APPROVED** [review]
Thanks @salvalatorre

**Comment by maceligueta** [comment]
Should we update the DAM application then? It might be dangerous to change the Poromechanics without updating the DAM app, no?

**Comment by ipouplana** [comment]
@KratosMultiphysics/Dam

**Comment by ipouplana** [comment]
I think that these changes should not affect the DamApplication... 
However, what do you think @joaquinirazabal?

**Comment by salvalatorre** [comment]
I'll put the merge off till @joaquinirazabal comments on this...

**Comment by joaquinirazabal** [comment]
Thank you for pointing it out, no problem from the DamApplication side.

**Pull request merged**
