### PR TITLE
[StructuralMechanicsApplication] Fix plain strain bug

### LINKED ISSUE #7715: Plain strain bug?
Hi,
I'm trying to run a simple test which consists of a cylindrical ring subjected to an external unitary pressure. I'm using the Structural Mechanics Application.
I'm using plane strain conditions. The problem is that, while sigma_r and sigma_theta are correct and close enough to the analytical solution, sigma_z turns out to be 0, when theory says that it should not the case.
I'm adding some snapshots. Could you please have a look?
Thanks!

@KratosMultiphysics/structural-mechanics 
@KratosMultiphysics/dem 

sigma_radial
sigma_theta
sigma_axial

### PR DESCRIPTION
**Pull request by loumalouomega**
**Description**
Fixes #7715 

Related #3935

**Changelog**
- Adding post-process  for sigma_zz = mu * (sigma_xx + sigma_yy)

### CODE REVIEW

**Comment by philbucher** [comment]
Why is this fixed in the element and it the law?
I.e. the same bug will happen in shells and membranes?

**Comment by philbucher** [comment]
*and not in the law?

**Comment by loumalouomega** [comment]
> Why is this fixed in the element and it the law?
> I.e. the same bug will happen in shells and membranes?

As this intersects with #3935 I opened this as an extended discussion.

**Comment by Vahid-Galavi** [comment]
> **Description**
> Fixes #7715
> 
> Related #3935
> 
> **Changelog**
> 
> * Adding post-process  for sigma_zz = mu * (sigma_xx + sigma_yy)

This is only valid for elastic materials, or at least if you assume that the behaviour is elastic in the out-of-plain direction. In my opinion, sigma_zz should directly come from the constitutive law.

**Comment by loumalouomega** [comment]
> > **Description**
> > Fixes #7715
> > Related #3935
> > **Changelog**
> > 
> > * Adding post-process  for sigma_zz = mu * (sigma_xx + sigma_yy)
> 
> This is only valid for elastic materials, or at least if you assume that the behaviour is elastic in the out-of-plain direction. In my opinion, sigma_zz should directly come from the constitutive law.

Yes, that's true. Maybe I close this, and we properly fix it adressing #3935

**Pull request closed without merging**
