### PR TITLE
[ContactStructuralMechanicsApplication] First explicit contact working

### PR DESCRIPTION
**Pull request by loumalouomega**
Some improvements will come in a future PR

This includes #3800, I will merge it ASAP

### CODE REVIEW

**Comment by philbucher** [comment]
I will take a look after you merged master

**Comment by loumalouomega** [comment]
Today I am out, later I will do it. Thanks

**Review by philbucher — APPROVED** [review]
looks ok to me

**Comment by loumalouomega** [comment]
Thanks, I will create a PR for the missing corrections. I don't have any computer with me right now so I can't do it

**Pull request merged**
