### PR TITLE
[solid mechs] Warnings removal

### PR DESCRIPTION
**Pull request by maceligueta**

### CODE REVIEW

**Review by josep-m-carbonell — COMMENTED** [review]
I don't know if the KRATOS_API(SOLID_MECHANICS_APPLICATION) can be taken away @roigcarlo. Maybe windows will not compile.

**Comment by roigcarlo** [comment]
Yep @josep-m-carbonell is right. Let me test that on win first please. We had problems in the past with those...

**Comment by maceligueta** [comment]
Appveyor has compiled correctly, and it includes the Solid Mechanics.

**Comment by maceligueta** [comment]
What should we do with this? Do we accept Appveyor as 'Windows Compilation'?

**Review by roigcarlo — APPROVED** [review]
It's ok for me if Appveyor don't complain.

Anyway If it crashes we can always turn back but looks safe.

**Comment by maceligueta** [comment]
I will wait for the last word from the Maintainer, @josep-m-carbonell .

**Comment by josep-m-carbonell** [comment]
For me it is ok @maceligueta, thank you to clean it !!

**Pull request merged**
