### PR TITLE
[ParticleMechanics] Renumbering MPM element ID convention

### PR DESCRIPTION
**Pull request by bodhinandach**
@philbucher as you suggested yesterday to create new nodes for coupling purposes, I notice a weird convention that is currently used in the MPM element creation process (it has been a question to me for a long time), i.e. it also considers the node's ID to determine the starting new element's ID.
 
I just modified it as such that node's, element's, and condition's IDs are distinct and well numbered. Tests are also modified accordingly; all the results values are the same, I just modify in number behind "PARTICLE_XX".

### CODE REVIEW

**Review by philbucher — APPROVED** [review]
looks ok to me

just also FYI @antonialarese

**Comment by bodhinandach** [comment]
@philbucher Thanks! 
I also get some questions to you: The new nodes created with respect to the condition also need to have some variables, perhaps with respect to coupling I suppose. Would you be able to tell me some of it which is normally required?

**Comment by antonialarese** [comment]
I really don't know the reason of the strange numbering. Does Ilaria has some motivation on that?
Fine for me, in any case. Thank you Nanda

**Comment by bodhinandach** [comment]
@philbucher @antonialarese @iiaconeta I think I understand why this convention is done. Basically, it's to have both the grid and the particle (different output files) visualized at the same time through GiD. This will create an error in visualization. I will revert this PR back to the previous convention and readjust the condition id. Sorry for not checking it before creating the PR.

**Pull request merged**
