### PR TITLE
[CI][Linux] adding GeoMechanicsApplication

### PR DESCRIPTION
**Pull request by Vahid-Galavi**
Add GeoMechanicsApplication to the list

### CODE REVIEW

**Comment by philbucher** [comment]
@Vahid-Galavi who are the two maintainers for your app?
see https://github.com/KratosMultiphysics/Kratos/wiki/Continuous-Integration#rules-for-adding-an-application-to-the-ci

**Comment by roigcarlo** [comment]
aside form @philbucher , seems that there are some tests that take too long, we should reduce them in any case.
Also looking into the clang error

**Comment by Vahid-Galavi** [comment]
> @Vahid-Galavi who are the two maintainers for your app?
> see https://github.com/KratosMultiphysics/Kratos/wiki/Continuous-Integration#rules-for-adding-an-application-to-the-ci

At the moment, I am the only one maintaining the app.

**Comment by Vahid-Galavi** [comment]
> aside form @philbucher , seems that there are some tests that take too long, we should reduce them in any case.
> Also looking into the clang error

@roigcarlo Can you please indicate which ones should be reduced?

**Comment by philbucher** [comment]
> > aside form @philbucher , seems that there are some tests that take too long, we should reduce them in any case.
> > Also looking into the clang error
> 
> @roigcarlo Can you please indicate which ones should be reduced?

I recommend to use #7818 for getting info abt which tests are the slow ones

**Comment by roigcarlo** [comment]
Agree with @philbucher, its hard to tell which one is being slow, as time usually multiplies ~tenfold when running in the CI machine, but the timing should give you an idea if some of the tests are taking more time than others.

From my experience, typically tests that require running a full simulation and compare the results with a solved problem tend to be the problem, we usually move those to the 'nightly' or 'validation' suits.

**Comment by Vahid-Galavi** [comment]
> Agree with @philbucher, its hard to tell which one is being slow, as time usually multiplies ~tenfold when running in the CI machine, but the timing should give you an idea if some of the tests are taking more time than others.
> 
> From my experience, typically tests that require running a full simulation and compare the results with a solved problem tend to be the problem, we usually move those to the 'nightly' or 'validation' suits.

@roigcarlo Thanks for the hint! I will check again the tests.

**Comment by Vahid-Galavi** [comment]
> > > aside form @philbucher , seems that there are some tests that take too long, we should reduce them in any case.
> > > Also looking into the clang error
> > 
> > 
> > @roigcarlo Can you please indicate which ones should be reduced?
> 
> I recommend to use #7818 for getting info abt which tests are the slow ones

Thanks @philbucher !

**Comment by roigcarlo** [comment]
Already in the CI.

**Pull request closed without merging**
