### PR TITLE
[StructuralMechanicsApplication] A lot of cleaning in tests

### PR DESCRIPTION
**Pull request by loumalouomega**
This removes almost all the warnings from all the small, validation and some validation tests

### CODE REVIEW

**Comment by loumalouomega** [comment]
> This removes almost all the warnings from all the small, validation and some validation tests

imagen

**Review by philbucher — APPROVED** [review]
Thanks a lot
Sorry for the late response I am on vacation 

Are all the tests still running? Did you also run the validation suite?
If yes then please go ahead

**Comment by philbucher** [comment]
> > This removes almost all the warnings from all the small, validation and some validation tests
> 
> imagen

Btw I am not sure this is the correct use of this meme...
I am not sure if rather someone else should „award“ you with this one (fyi @rolandwuechner for some advanced meme usage ;) )

**Comment by loumalouomega** [comment]
> 
> 
> Thanks a lot
> Sorry for the late response I am on vacation
> 
> Are all the tests still running? Did you also run the validation suite?
> If yes then please go ahead

Indeed (but I have not updated all the ValidationTests)

**Comment by loumalouomega** [comment]
> 
> 
> > > This removes almost all the warnings from all the small, validation and some validation tests
> > 
> > 
> > imagen
> 
> Btw I am not sure this is the correct use of this meme...
> I am not sure if rather someone else should „award“ you with this one (fyi @rolandwuechner for some advanced meme usage ;) )

I am quite sure this meme is done right

**Comment by philbucher** [comment]
> I am quite sure this meme is done right

Ok then I learned sth :)

**Pull request merged**
