### PR TITLE
[StructuralMechanicsApplication] Hotfix test failing

### PR DESCRIPTION
**Pull request by loumalouomega**

### CODE REVIEW

**Comment by loumalouomega** [comment]
Partially Fixes #1810

**Review by roigcarlo — APPROVED** [review]

**Comment by philbucher** [comment]
Thx for fixing 

I will take a look at my test in the next days

**Comment by philbucher** [comment]
@roigcarlo how could sth be merged if the tests were not running?

@loumalouomega are the other tests all working, I mean the ones in the night and validation suite?

**Comment by loumalouomega** [comment]
I just checked the small because right now are the blockers

**Comment by roigcarlo** [comment]
Once this is merged just retrigger the build

**Comment by loumalouomega** [comment]
I was thinking on that :dancer:

**Comment by philbucher** [comment]
@roigcarlo I meant how could sth be merged if Travis was failing?

**Comment by loumalouomega** [comment]
The merge from yesterday was from a branch quite old, so it was already compiled and checked by Travis

**Comment by roigcarlo** [comment]
It can happen if the branch was realy old. Anyway, that test in particular may well pass sometimes, so could have also been bad luck :S. Hopefuly @loumalouomega catch it fast

**Pull request merged**
