### PR TITLE
Add cr beam truss

### PR DESCRIPTION
**Pull request by alinurikayis**

### CODE REVIEW

**Review by loumalouomega — CHANGES_REQUESTED** [review]
Please, clean your branch, and just add changes related with the CRBeamTruss

**Comment by pooyan-dadvand** [comment]
There are lot of modification in DEM application. I understand that you are moving some of it variables. So I add @maceligueta to the converstation.

**Review by loumalouomega — CHANGES_REQUESTED** [review]
You still need to clean this PR (many things not related with StructuralMechanicsApplication)

**Comment by maceligueta** [comment]
In these cases, one can merge master into this branch (in order to solve the conflicts in the branch), then merge is simpler.

**Comment by loumalouomega** [comment]
I already did that, many changes are new an the master don't overwrite the
changes.

**Review by pooyan-dadvand — CHANGES_REQUESTED** [review]
Why we need a duplicate variable for normal ones ending with _RING?

For example DIAMETER should be distinguished from DIAMETER_RING in this element or we should using both of them at the same time?

**Comment by AndreasWinterstein** [comment]
The elements in this branch are already in the master branch by merging the branch "feature-porting-elemens". This means that this pull request should not be merged and is to be deleted. @KlausBSautter please delete this branch.

**Pull request closed without merging**
