### PR TITLE
[Core] Fix memory error in FromJSONCheckResultProcess

### LINKED ISSUE #6942: Memory error in FromJSONCheckResultProcess
This happens in one of the Mappingtests in MPI only
reason is that [those](https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/processes/from_json_check_result_process.cpp#L483-L484) containers can be empty in MPI but you don't check it

~~~
#4  0x00007ffff283331e in Kratos::FromJSONCheckResultProcess::FillDatabase (this=0x1604030, 
    rResults=..., rNodesArray=warning: RTTI symbol not found for class 'Kratos::PointerVectorSet<Kratos::Node<3ul, Kratos::Dof<double> >, Kratos::IndexedObject, std::less<unsigned long>, std::equal_to<unsigned long>, Kratos::intrusive_ptr<Kratos::Node<3ul, Kratos::Dof<double> > >, std::vector<Kratos::intrusive_ptr<Kratos::Node<3ul, Kratos::Dof<double> > >, std::allocator<Kratos::intrusive_ptr<Kratos::Node<3ul, Kratos::Dof<double> > > > > >'
..., rElementsArray=..., NumberOfGP=0)
    at /home/philipp/software/Kratos_aux/kratos/processes/from_json_check_result_process.cpp:504
        r_var_database = @0x16039d0: {<std::vector<Kratos::EntityDatabase, std::allocator<Kratos::EntityDatabase> >> = std::vector of length 0, capacity 0, 
          _vptr$VariableDatabase = 0x7ffff43175c8 <vtable for Kratos::VariableDatabase+16>}
        r_variable_name = Python Exception <class 'gdb.error'> There is no member named _M_dataplus.: 

        is_saved_as_components = false
        p_var_array = @0x1603600: 0x7ffff43e4548 <Kratos::FORCE>
        __range2 = std::vector of length 1, capacity 1 = {0x7ffff43e4548 <Kratos::FORCE>}
        __begin2 = 0x7ffff43e4548 <Kratos::FORCE>
        __end2 = 0x1604a40
        it_node_begin = {<boost::iterators::iterator_adaptor<boost::iterators::indirect_iterator<__gnu_cxx::__normal_iterator<Kratos::intrusive_ptr<Kratos::Node<3, Kratos::Dof<double> > > const*, std::vector<Kratos::intrusive_ptr<Kratos::Node<3, Kratos::Dof<double> > >, std::allocator<Kratos::intrusive_ptr<Kratos::Node<3, Kratos::Dof<double> > > > > >, boost::iterators::use_default, boost::iterators::use_default, boost::iterators::use_default, boost::iterators::use_default>, __gnu_cxx::__normal_iterator<Kratos::intrusive_ptr<Kratos::Node<3, Kratos::Dof<double> > > const*, std::vector<Kratos::intrusive_ptr<Kratos::Node<3, Kratos::Dof<double> > >, std::allocator<Kratos::intrusive_ptr<Kratos::Node<3, Kratos::Dof<double> > > > > >, Kratos::Node<3, Kratos::Dof<double> >, boost::iterators::use_default, Kratos::Node<3, Kratos::Dof<double> >&, boost::iterators::use_default>> = {<boost::iterators::iterator_facade<boost::iterators::indirect_iterator<__gnu_cxx::__normal_iterator<Kratos::intrusive_ptr<Kratos::Node<3, Kratos::Dof<double> > > ---Type <return> to continue, or q <return> to quit---
~~~

### PR DESCRIPTION
**Pull request by loumalouomega**
Fixes #6942

Checking containers are not empty

### CODE REVIEW

**Comment by philbucher** [comment]
Now the memory error is solved (thx) but I get this error: `RuntimeError: Error: Is not possible to initialize the node database`

**Comment by loumalouomega** [comment]
> Now the memory error is solved (thx) but I get this error: `RuntimeError: Error: Is not possible to initialize the node database`

I will add a check that is rank 0 for that

**Comment by philbucher** [comment]
> > Now the memory error is solved (thx) but I get this error: `RuntimeError: Error: Is not possible to initialize the node database`
> 
> I will add a check that is rank 0 for that

I am quite sure this is wrong
The results have to be checked on all ranks!

**Comment by philbucher** [comment]
what did you do differently than the py-version?
There it was working fine

**Comment by loumalouomega** [comment]
> 
> 
> what did you do differently than the py-version?
> There it was working fine

Sorry, I meant I will check that the array is not empty

**Comment by loumalouomega** [comment]
> 
> 
> > what did you do differently than the py-version?
> > There it was working fine
> 
> Sorry, I meant I will check that the array is not empty

Done

**Review by philbucher — APPROVED** [review]
now it works, thx

**Pull request merged**
