### PR TITLE
[ConstitutiveLawsApplication] Fix typo

### PR DESCRIPTION
**Pull request by loumalouomega**
**📝 Description**

This PR fixes the most extended typo auxiliar -> auxiliary

Part of #10180

**🆕 Changelog**

- auxiliar -> auxiliary

### CODE REVIEW

**Comment by loumalouomega** [comment]
Anyone?

**Comment by loumalouomega** [comment]
@KratosMultiphysics/structural-mechanics 👋

**Review by SergioJimenezReyes — COMMENTED** [review]
Thanks Vicente!

**Review by SergioJimenezReyes — APPROVED** [review]

**Comment by loumalouomega** [comment]
@SergioJimenezReyes I removed approval by error

**Pull request merged**
