### PR TITLE
Correcting factor AreaNornal

### PR DESCRIPTION
**Pull request by loumalouomega**
#1158

### CODE REVIEW

**Comment by maceligueta** [comment]
Can you do the same in the 2D triangle? it was commented at the @KratosMultiphysics/technical-committee meeting.

**Comment by loumalouomega** [comment]
A 2D triangle does not have a normal, the line can have it, but not a surface in a 2D space.

**Comment by maceligueta** [comment]
Ok, I thought you could use the normal for rotations and so on (only if you have 3 component vectors in the 2D problem). Let's forget what I said.

**Comment by rubenzorrilla** [comment]
@loumalouomega would you mind to run all the core tests before merging? I'm afraid that we'll need to update some of them (the modified shape functions ones).

**Comment by loumalouomega** [comment]
Ok

**Comment by loumalouomega** [comment]
Done @rubenzorrilla

**Review by rubenzorrilla — APPROVED** [review]
@loumalouomega  thanks a lot!

**Pull request merged**
