### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by philbucher**

### CODE REVIEW

**Comment by philbucher** [comment]
again appveyor does not seem to build it

@roigcarlo any idea?

**Comment by roigcarlo** [comment]
Mm sometimes it fails, I think its their fault.
I will force trigger it.

**Comment by roigcarlo** [comment]
Well seems that there is a general problem:
https://help.appveyor.com/discussions/problems/23201-request-to-github-web-hook-has-been-made-from-prohibited-ip-address

I will keep an eye on this

Edit:
Working now.

**Comment by philbucher** [comment]
now it works again
Thx @roigcarlo 

can someone reapprove pls?

**Comment by philbucher** [comment]
anyone? :)
Its just a typo-correction

**Review by roigcarlo — APPROVED** [review]

**Comment by philbucher** [comment]
thx :)

**Pull request merged**
