### PR TITLE
[CI] DockerImage with ubuntu 20.04

### PR DESCRIPTION
**Pull request by philbucher**
This is NOT yet used in the CI, that will be a second step

I used `20-04` in the naming now, I think that makes it more clear, even though so far we use the other names (e.g. `trusty`, `bionic`, `focal`).
What do you think?

### CODE REVIEW

**Comment by oberbichler** [comment]
👍 I am not so familiar with the ubuntu versions… would `20` be enough?

**Comment by philbucher** [comment]
It was released ~1 week ago so I think we are pretty up to date :)

**Comment by oberbichler** [comment]
Just thinking if 20 would be enough (insteat of 20-04) because the next LTS Ubuntu would be 21.

**Comment by rubenzorrilla** [comment]
> It was released ~1 week ago so I think we are pretty up to date :)

I've just upgraded my OS and I found out that they plan to release a 20.4.1 in a few months. Just as a reminder for us to also upgrade it in here.

**Comment by oberbichler** [comment]
But would we use then two images for 20.4 and 20.4.1? Or just one for the actual 20.x.y? Anyway nothing really important...

**Comment by rubenzorrilla** [comment]
> But would we use then two images for 20.4 and 20.4.1? Or just one for the actual 20.x.y? Anyway nothing really important...

I'd do the 20.4.y (it seems that the one they've just released has some minors to be fixed).

**Comment by philbucher** [comment]
There is only one image of each Ubuntu 
I guess they apply the patches as sone as they are released

Only 20 is not enough IMO since they release a new version every 6 months which means there will be also 20-10

But my main question remains unanswered, should we go for the names (focal in this case like we used to do) OR use the numbers

**Comment by rubenzorrilla** [comment]
> There is only one image of each Ubuntu
> I guess they apply the patches as sone as they are released
> 
> Only 20 is not enough IMO since they release a new version every 6 months which means there will be also 20-10
> 
> But my main question remains unanswered, should we go for the names (focal in this case like we used to do) OR use the numbers

For me the numbers are more clear (there is no natural way to sort animals :smile: )

**Review by roigcarlo — APPROVED** [review]

**Comment by roigcarlo** [comment]
Ups, forgot to leave a comment in the approval: 
- For me 20 alone is also not enough
- We should go for numbers, as animal names are misleading anyway. We already had problems with that some days ago

**Pull request merged**
