### PR TITLE
Attention Errors in override geometry methods

### PR DESCRIPTION
**Pull request by josep-m-carbonell**
the modified lines do not have a method to override.....some additional corrections are needed

### CODE REVIEW

**Review by ipouplana — APPROVED** [review]
Thanks @josep-m-carbonell , 
yesterday I saw that the nightly build failed because of this error, and Ruben already opened another pull request to fix it and change various things in the geometries (#659)...
However, it seems right to correct the error asap, so I approve this PR.

**Comment by josep-m-carbonell** [comment]
I think is better to delete methods that are not consistent with the base class. If you have already done it in another PR, then merge is needed. I don't know if everything is correct, prisms had also something wrong.

**Review by loumalouomega — APPROVED** [review]
OK for me, but I will wait for the approval of @ipouplana

**Comment by ipouplana** [comment]
I am compiling the branch... when it is ready I will post here to merge the branch

**Comment by ipouplana** [comment]
By the way @josep-m-carbonell , I just realized that there are no files changed in this PR...
Shouldn't we just delete the PR?

**Comment by rubenzorrilla** [comment]
@ipouplana I thought that we finally did solve this on Monday. Which is the difference of this PR? (I just want to avoid any undesired merge conflict)

**Comment by ipouplana** [comment]
@rubenzorrilla that's the same I was wondering... After the merge of  #659 on monday, perhaps we don't need this PR anymore...

**Comment by rubenzorrilla** [comment]
@ipouplana I agree. Actually, no warning nor errors appear in the nightly compilation.

**Pull request merged**
