### PR TITLE
[FreeSurface] Adding tests

### PR DESCRIPTION
**Pull request by joaquinirazabal**
Two tests, one for 2D and other for 3D, have been added to the FreeSurfaceApplication.

### CODE REVIEW

**Review by antonialarese — APPROVED** [review]
Thank you Joaquín. Just a question: How much time does it take to run this tests? @rubenzorrilla @roigcarlo  is there any rule to follow about duration of the full run? Is it written anywhere?

**Review by antonialarese — DISMISSED** [review]

**Comment by roigcarlo** [comment]
Usually we divide them in categories:
* **Small**: 1 min to run them all
* **Nightly**: 15 min to run them all
* **Everything else**: Whatever it takes

**Comment by joaquinirazabal** [comment]
It only takes 10 seconds to run them all in my computer :)

**Review by philbucher — CHANGES_REQUESTED** [review]
can you please reduce the size of "applications/FreeSurfaceApplication/tests/Reservoir3D/Reservoir3D.mdpa"? this is quite large for the main repo and recently we have undertaken large efforts to reduce the size of Kratos
Large examples should go to the examples repo

**Review by philbucher — APPROVED** [review]
Thanks

**Review by antonialarese — APPROVED** [review]
thanks

**Pull request merged**
