### PR TITLE
[CI] add Core build without Unity

### LINKED ISSUE #8404: [CI] Adding not cotired compilation to CI
**Description**
Adding not cotired compilation to CI in order to avoid the problems that appear after a merge and the not cotired compilation fails. This is because there is not cotired CI right now, and the CI does not block the merge

@KratosMultiphysics/technical-committee

### PR DESCRIPTION
**Pull request by philbucher**
**Description**
In the past we quite often had the problem that some includes were missing which is often ok when using the unity build but is failing in normal compilations

this PR adds a build of the Core with Clang to prevent this (at least for the Core). I am only adding the Core as this would be too slow when all the apps are added too

Better version of #8485 

closes #8404

### CODE REVIEW

**Review by loumalouomega — DISMISSED** [review]
OK, but may still fail for apps

Maybe we can do a not mandatory CI which checks the compilation at the end (I don't know just thinking)

**Comment by philbucher** [comment]
in my experience the Apps rarely fail bcs of this

and compiling them too takes much more time, and if it is not mandatory then ppl wouldn't wait which defeats the purpose

I would add this and see how things develop in the future

**Comment by philbucher** [comment]
build time for Core (with MPICore) + cpp tests is 17 min, I think this is pretty reasonable

**Comment by roigcarlo** [comment]
Following the conversation I had with @philbucher some days ago, maybe this is a good excuse to disable the cache build in the unity based and enable it here, it should benefit more from it

**Comment by philbucher** [comment]
> Following the conversation I had with @philbucher some days ago, maybe this is a good excuse to disable the cache build in the unity based and enable it here, it should benefit more from it

done

we are taking it out as it was rarely working and was consuming time in regular builds
Reason it rarely worked is that we don't have enough temp storage to save multiple builds
and since the CI runs up to 5 builds in parallel they were constantly overwriting each other

in a followup PR I will remove ccache from the dockerimage to save space

**Comment by philbucher** [comment]
@roigcarlo I misunderstood you, now it uses ccache for the non-unity build

**Comment by philbucher** [comment]
ok now it is ready :tada: 

conclusion:
- the build without unity uses Clang and CCache
- caching works, I checked:
~~~
/usr/bin/docker exec  fa05ebd21d5d74cb5a83a11b8b20bf669720111a205382dbc5c5ea3d175d7993 sh -c "cat /etc/*release | grep ^ID"
Cache Size: ~122 MB (128434243 B)
/usr/bin/tar -xz -f /__w/_temp/849cd1a0-a908-4445-b510-1ada8d5dae33/cache.tgz -C /github/home/.ccache
Cache restored from key: Linux-no-unity-ccache-be1fa5e9b81a3b1160c9023a8486c92483146bbc
~~~
- build time after caching: < 1min
- the temp space we have should be enough to cache a few builds

**Review by roigcarlo — APPROVED** [review]
:+1:

**Pull request merged**
