### PR TITLE
[CoSim] silence prints from EmpireAPI in tests

### PR DESCRIPTION
**Pull request by philbucher**
By default the cosim_EmpireAPI prints some things that make the output of the tests harder to read.
Now is silenced

### CODE REVIEW

**Comment by adityaghantasala** [comment]
Why again a `EMPIRE_API.conf` instead putting those two or more (in future) in the `settings` itself ?

**Comment by philbucher** [comment]
> Why again a `EMPIRE_API.conf` instead putting those two or more (in future) in the `settings` itself ?

done, no the file is no longer used for Kratos

**Comment by philbucher** [comment]
Ping @adityaghantasala

**Review by adityaghantasala — APPROVED** [review]

**Comment by philbucher** [comment]
thx

**Pull request merged**
