### PR TITLE
[Core][MPI] Adding SynchronizeVariable to bool variables

### PR DESCRIPTION
**Pull request by loumalouomega**
This was missing , part of #4556

### CODE REVIEW

**Comment by loumalouomega** [comment]
@jcotela #3672 is merged, what should I do in this PR?

**Comment by loumalouomega** [comment]
> does this make sense?

Well, if not I can remove it

**Comment by loumalouomega** [comment]
@jcotela and @philbucher I have some questiosn of how to properly tests this on MPI

**Comment by loumalouomega** [comment]
I still have problem with Trilinos: 

:P 

~~~sh
from KratosTrilinosApplication import *
ImportError: /home/vicente/src/Kratos/libs/KratosTrilinosApplication.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN9ML_Epetra11SetDefaultsENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERN7Teuchos13ParameterListEPiPdb
~~~

@jcotela @roigcarlo  any idea?

**Comment by roigcarlo** [comment]
> I still have problem with Trilinos:
> 
> :P
> 
> ```shell
> from KratosTrilinosApplication import *
> ImportError: /home/vicente/src/Kratos/libs/KratosTrilinosApplication.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN9ML_Epetra11SetDefaultsENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERN7Teuchos13ParameterListEPiPdb
> ```
> 
> @jcotela @roigcarlo any idea?

That one means that trilinos is not correctly compiled. Try to LD_PRELOAD all trilinos libs.

**Comment by loumalouomega** [comment]
> LD_PRELOAD

Looks like I am unable to make it work, then you suggest to directly compile Trilinos from scratch?

**Comment by roigcarlo** [comment]
Yep. I am afraid. If you can compiling as a static libs tend to reduce the linking problems and the "symbol not found" ones. Is not the ideal solution but it makes all the process more bearable.

**Comment by jcotela** [comment]
@loumalouomega I have been refactoring the MPICommunicator in the last weeks and it should now have the features you need to Synchronize `Variable<bool>`. I would suggest closing this PR and adopting the version of #4745 once it is merged instead (I believe no further change would be needed from your side).

Sorry for the inconvenience.

**Comment by loumalouomega** [comment]
OK; I will need to port #4745 to #4556

**Pull request closed without merging**
