### PR TITLE
[Core] Removing one warning in nurbs_curve_geometry

### PR DESCRIPTION
**Pull request by loumalouomega**
~~~
/home/vicente/src/Kratos/kratos/geometries/nurbs_curve_geometry.h:408:39: warning: adding 'int' to a string does not append to the string [-Wstring-plus-int]
        return TWorkingSpaceDimension + " dimensional nurbs curve.";
~~~

### CODE REVIEW

**Review by philbucher — APPROVED** [review]
thanks

**Comment by loumalouomega** [comment]
Still more warnings apparently :P

**Comment by philbucher** [comment]
there are more in master?

**Comment by philbucher** [comment]
hm Travis looks clean now

**Comment by loumalouomega** [comment]
In the night compilation I mean

**Comment by loumalouomega** [comment]
~~~
/home/vicente/src/Kratos/kratos/geometries/nurbs_shape_function_utilities/nurbs_utilities.h:78:21: warning: unused function 'GetPolynomialDegree' [-Wunused-function]
    static SizeType GetPolynomialDegree(const SizeType NumberOfKnots, const SizeType NumberOfControlPoints)
                    ^
/home/vicente/src/Kratos/kratos/geometries/nurbs_shape_function_utilities/nurbs_utilities.h:88:21: warning: unused function 'GetNumberOfKnots' [-Wunused-function]
    static SizeType GetNumberOfKnots(const SizeType PolynomialDegree, const SizeType NumberOfControlPoints)
                    ^
/home/vicente/src/Kratos/kratos/geometries/nurbs_shape_function_utilities/nurbs_utilities.h:108:21: warning: unused function 'GetNumberOfSpans' [-Wunused-function]
    static SizeType GetNumberOfSpans(const SizeType PolynomialDegree, const SizeType NumberOfKnots)
                    ^
In file included from /home/vicente/src/Kratos/kratos/tests/cpp_tests/geometries/test_nurbs_surface_shape_functions.cpp:22:
In file included from /home/vicente/src/Kratos/kratos/geometries/nurbs_shape_function_utilities/nurbs_surface_shape_functions.h:19:
In file included from /home/vicente/src/Kratos/kratos/geometries/nurbs_shape_function_utilities/nurbs_curve_shape_functions.h:23:
/home/vicente/src/Kratos/kratos/geometries/nurbs_shape_function_utilities/nurbs_utilities.h:78:21: warning: unused function 'GetPolynomialDegree' [-Wunused-function]
    static SizeType GetPolynomialDegree(const SizeType NumberOfKnots, const SizeType NumberOfControlPoints)
                    ^
/home/vicente/src/Kratos/kratos/geometries/nurbs_shape_function_utilities/nurbs_utilities.h:88:21: warning: unused function 'GetNumberOfKnots' [-Wunused-function]
    static SizeType GetNumberOfKnots(const SizeType PolynomialDegree, const SizeType NumberOfControlPoints)
                    ^
/home/vicente/src/Kratos/kratos/geometries/nurbs_shape_function_utilities/nurbs_utilities.h:108:21: warning: unused function 'GetNumberOfSpans' [-Wunused-function]
    static SizeType GetNumberOfSpans(const SizeType PolynomialDegree, const SizeType NumberOfKnots)

~~~

**Comment by philbucher** [comment]
I will take care

**Comment by tteschemacher** [comment]
shouldn't those warnings be already resolved?

**Comment by loumalouomega** [comment]
Yep, I think have non been solved (why my proposal was not right?, that one
removed the warnings)

**Pull request merged**
