### PR TITLE
[Core] fix __cplusplus

### PR DESCRIPTION
**Pull request by philbucher**
see https://devblogs.microsoft.com/cppblog/msvc-now-correctly-reports-__cplusplus/

now `__cplusplus` returns the correct value also with MSVC

### CODE REVIEW

**Comment by roigcarlo** [comment]
Wait what? they fixed it? After so may years.... Is this true or is it an April's fool joke?

**Comment by philbucher** [comment]
yes, the blog entry is two years old
I am using this for some time already in another project and it works fine
If you check the CI-output of the first two commits you can see that it also works correctly here

Only thing is that the minimum output is the one for C++14 (obviously :laughing:)

**Review by roigcarlo — APPROVED** [review]
Well is a nice step in the right direction from their side ( I hope this time it gets regularly updated :_D )

**Comment by philbucher** [comment]
it also works for C++17 :) (https://github.com/philbucher/communication-tests/runs/551589115?check_suite_focus=true check the output of "Run tests")

Not sure why this Compiler option is not the default

**Comment by philbucher** [comment]
> Not sure why this Compiler option is not the default

thats the answer:

> You need to compile with the /Zc:__cplusplus switch to see the updated value of the __cplusplus macro. We tried updating the macro by default and discovered that a lot of code doesn’t compile correctly when we change the value of __cplusplus. We’ll continue to require use of the /Zc:__cplusplus switch for all minor versions of MSVC in the 19.xx family.

**Comment by loumalouomega** [comment]
imagen

**Pull request merged**
