### PR TITLE
[Core] Comments from @rubenzorrilla from #10453

### PR DESCRIPTION
**Pull request by loumalouomega**
**📝 Description**

Comments from @rubenzorrilla from #10453.

**🆕 Changelog**

- [Moving enum](https://github.com/KratosMultiphysics/Kratos/commit/3945750570675fff76cdf3fc129f0b04c0e8b159)
- [Remove comment](https://github.com/KratosMultiphysics/Kratos/commit/8e501bb4440ccd6032ba7e29bb0680f2b16f381b)

### CODE REVIEW

**Review by rubenzorrilla — COMMENTED** [review]
There is still the issue with the `public static` method. If it can be `static` in my opinion it shoulb be moved to a separate utility to keep the standard process API.

**Comment by loumalouomega** [comment]
> There is still the issue with the `public static` method. If it can be `static` in my opinion it shoulb be moved to a separate utility to keep the standard process API.

The thing is that in order to check the function in a cpp test it is easier if the method is static, otherwise I need to create a dummy process just to check it.

**Comment by rubenzorrilla** [comment]
> > There is still the issue with the `public static` method. If it can be `static` in my opinion it shoulb be moved to a separate utility to keep the standard process API.
> 
> The thing is that in order to check the function in a cpp test it is easier if the method is static, otherwise I need to create a dummy process just to check it.

Honestly, I think this is not enough justification to extend the API...

**Comment by loumalouomega** [comment]
> > > There is still the issue with the `public static` method. If it can be `static` in my opinion it shoulb be moved to a separate utility to keep the standard process API.
> > 
> > 
> > The thing is that in order to check the function in a cpp test it is easier if the method is static, otherwise I need to create a dummy process just to check it.
> 
> Honestly, I think this is not enough justification to extend the API...

Okay

**Comment by rubenzorrilla** [comment]
> > > > There is still the issue with the `public static` method. If it can be `static` in my opinion it shoulb be moved to a separate utility to keep the standard process API.
> > > 
> > > 
> > > The thing is that in order to check the function in a cpp test it is easier if the method is static, otherwise I need to create a dummy process just to check it.
> > 
> > 
> > Honestly, I think this is not enough justification to extend the API...
> 
> Okay

It is still in there... I'm not concerned about the `static` I'm concerned about the fact that you're adding a method to the public API. I think that processes should stick to the one in `process.h` (it is admittedly true that we didn't follow this in the past).

Considering that you initially made it `static` it could be technically placed somewhere else. If you aim to use it only for the testing I'd put it in a unnamed namespace in the corresponding cpp test. Otherwise, we can put it in any auxiliary utility.

**Comment by loumalouomega** [comment]
> > > > > There is still the issue with the `public static` method. If it can be `static` in my opinion it shoulb be moved to a separate utility to keep the standard process API.
> > > > 
> > > > 
> > > > The thing is that in order to check the function in a cpp test it is easier if the method is static, otherwise I need to create a dummy process just to check it.
> > > 
> > > 
> > > Honestly, I think this is not enough justification to extend the API...
> > 
> > 
> > Okay
> 
> It is still in there... I'm not concerned about the `static` I'm concerned about the fact that you're adding a method to the public API. I think that processes should stick to the one in `process.h` (it is admittedly true that we didn't follow this in the past).
> 
> Considering that you initially made it `static` it could be technically placed somewhere else. If you aim to use it only for the testing I'd put it in a unnamed namespace in the corresponding cpp test. Otherwise, we can put it in any auxiliary utility.

Yes, but the return type is an enum that you ask me to take out

**Comment by rubenzorrilla** [comment]
> > > > > > There is still the issue with the `public static` method. If it can be `static` in my opinion it shoulb be moved to a separate utility to keep the standard process API.
> > > > > 
> > > > > 
> > > > > The thing is that in order to check the function in a cpp test it is easier if the method is static, otherwise I need to create a dummy process just to check it.
> > > > 
> > > > 
> > > > Honestly, I think this is not enough justification to extend the API...
> > > 
> > > 
> > > Okay
> > 
> > 
> > It is still in there... I'm not concerned about the `static` I'm concerned about the fact that you're adding a method to the public API. I think that processes should stick to the one in `process.h` (it is admittedly true that we didn't follow this in the past).
> > Considering that you initially made it `static` it could be technically placed somewhere else. If you aim to use it only for the testing I'd put it in a unnamed namespace in the corresponding cpp test. Otherwise, we can put it in any auxiliary utility.
> 
> Yes, but the return type is an enum that you ask me to take out

But can't you access to the enum if it is within the class namespace? (maybe I'm missing something)

**Comment by loumalouomega** [comment]
> > > > > > > There is still the issue with the `public static` method. If it can be `static` in my opinion it shoulb be moved to a separate utility to keep the standard process API.
> > > > > > 
> > > > > > 
> > > > > > The thing is that in order to check the function in a cpp test it is easier if the method is static, otherwise I need to create a dummy process just to check it.
> > > > > 
> > > > > 
> > > > > Honestly, I think this is not enough justification to extend the API...
> > > > 
> > > > 
> > > > Okay
> > > 
> > > 
> > > It is still in there... I'm not concerned about the `static` I'm concerned about the fact that you're adding a method to the public API. I think that processes should stick to the one in `process.h` (it is admittedly true that we didn't follow this in the past).
> > > Considering that you initially made it `static` it could be technically placed somewhere else. If you aim to use it only for the testing I'd put it in a unnamed namespace in the corresponding cpp test. Otherwise, we can put it in any auxiliary utility.
> > 
> > 
> > Yes, but the return type is an enum that you ask me to take out
> 
> But can't you access to the enum if it is within the class namespace? (maybe I'm missing something)

I hope last refactor makes you happy

**Comment by rubenzorrilla** [comment]
> > > > > > > > There is still the issue with the `public static` method. If it can be `static` in my opinion it shoulb be moved to a separate utility to keep the standard process API.
> > > > > > > 
> > > > > > > 
> > > > > > > The thing is that in order to check the function in a cpp test it is easier if the method is static, otherwise I need to create a dummy process just to check it.
> > > > > > 
> > > > > > 
> > > > > > Honestly, I think this is not enough justification to extend the API...
> > > > > 
> > > > > 
> > > > > Okay
> > > > 
> > > > 
> > > > It is still in there... I'm not concerned about the `static` I'm concerned about the fact that you're adding a method to the public API. I think that processes should stick to the one in `process.h` (it is admittedly true that we didn't follow this in the past).
> > > > Considering that you initially made it `static` it could be technically placed somewhere else. If you aim to use it only for the testing I'd put it in a unnamed namespace in the corresponding cpp test. Otherwise, we can put it in any auxiliary utility.
> > > 
> > > 
> > > Yes, but the return type is an enum that you ask me to take out
> > 
> > 
> > But can't you access to the enum if it is within the class namespace? (maybe I'm missing something)
> 
> I hope last refactor makes you happy

This is exactly what I meant since the beginning.

Also note that the point in here isn't what makes me happy but that we cannot freely extend the API of this sort of classes, specially if they belong to the `KratosCore`. This is in my opinion a bad practice that we shouldn't promote in new developments.

**Review by rubenzorrilla — DISMISSED** [review]
Approving. Thanks for taking into account my considerations.

**Comment by loumalouomega** [comment]
@roigcarlo windows compilation fails and I don't know why

**Comment by roigcarlo** [comment]
Looking into it

**Comment by roigcarlo** [comment]
Still testing, but most likely the error is because of MS headers redefining the "ERROR" keyword in the return types of the geometrical utilities when included by the CoSimApplication when compiled using unitary builds (some windows.h will probably gets included from behind).

I would just simply change that for something else.

**Review by rubenzorrilla — APPROVED** [review]

**Pull request merged**
