### PR TITLE
__import__ => importlib

### PR DESCRIPTION
**Pull request by philbucher**
I updated many occurrences throughout the code

this should help with #5192 and eventually #5170

### CODE REVIEW

**Comment by philbucher** [comment]
FYI @KratosMultiphysics/technical-committee @KratosMultiphysics/altair

**Comment by philbucher** [comment]
I have not updated the apps where I was not sure how to
SwimmingDEM @GuillermoCasas 
DEM @KratosMultiphysics/dem 
ShapeOpt @armingeiser @dbaumgaertner

**Comment by philbucher** [comment]
thanks a lot @farrufat-cimne !

**Comment by philbucher** [comment]
can this be merged @roigcarlo? Or is sth missing?

**Comment by philbucher** [comment]
ping @roigcarlo

**Review by roigcarlo — APPROVED** [review]
@philbucher Ok to me :+1:

**Comment by philbucher** [comment]
thx

**Pull request merged**
