### PR TITLE
[CI] add Clang

### PR DESCRIPTION
**Pull request by philbucher**
first attempt without caching

### CODE REVIEW

**Comment by philbucher** [comment]
@oberbichler apparently clang has a problem with Intel OpenMP which for some reason seems to be installed in docker:
~~~
OMP: Error #15: Initializing libiomp5.so, but found libomp.so.5 already initialized.
~~~

googling it shows that it can be related to conda: https://github.com/dmlc/xgboost/issues/1715

**Comment by philbucher** [comment]
@oberbichler @roigcarlo do you know how to use `ccache` with Clang?
I tried different things but I cannot get it to work
One suspicion I have is that ccache is not installed for clang:

content of `/usr/lib/ccache` on the **github runner**:
~~~
lrwxrwxrwx 1 root root 16 Feb  6 14:51 c++ -> ../../bin/ccache
lrwxrwxrwx 1 root root 16 Feb  6 14:50 c89-gcc -> ../../bin/ccache
lrwxrwxrwx 1 root root 16 Feb  6 14:50 c99-gcc -> ../../bin/ccache
lrwxrwxrwx 1 root root 16 Feb  6 14:51 cc -> ../../bin/ccache
lrwxrwxrwx 1 root root 16 Feb  6 14:50 g++ -> ../../bin/ccache
lrwxrwxrwx 1 root root 16 Feb  6 14:50 g++-7 -> ../../bin/ccache
lrwxrwxrwx 1 root root 16 Feb  6 14:50 gcc -> ../../bin/ccache
lrwxrwxrwx 1 root root 16 Feb  6 14:50 gcc-7 -> ../../bin/ccache
lrwxrwxrwx 1 root root 16 Feb  6 14:50 x86_64-linux-gnu-g++ -> ../../bin/ccache
lrwxrwxrwx 1 root root 16 Feb  6 14:50 x86_64-linux-gnu-g++-7 -> ../../bin/ccache
lrwxrwxrwx 1 root root 16 Feb  6 14:50 x86_64-linux-gnu-gcc -> ../../bin/ccache
lrwxrwxrwx 1 root root 16 Feb  6 14:50 x86_64-linux-gnu-gcc-7 -> ../../bin/ccache
~~~

same but on **my local machine**:
~~~
lrwxrwxrwx 1 root root 16 Feb  8 12:50 c++ -> ../../bin/ccache
lrwxrwxrwx 1 root root 16 Feb  8 12:50 c89-gcc -> ../../bin/ccache
lrwxrwxrwx 1 root root 16 Feb  8 12:50 c99-gcc -> ../../bin/ccache
lrwxrwxrwx 1 root root 16 Feb  8 12:50 cc -> ../../bin/ccache
lrwxrwxrwx 1 root root 16 Feb  8 12:50 clang -> ../../bin/ccache
lrwxrwxrwx 1 root root 16 Feb  8 12:50 clang++ -> ../../bin/ccache
lrwxrwxrwx 1 root root 16 Feb  8 12:50 g++ -> ../../bin/ccache
lrwxrwxrwx 1 root root 16 Feb  8 12:50 g++-7 -> ../../bin/ccache
lrwxrwxrwx 1 root root 16 Feb  8 12:50 gcc -> ../../bin/ccache
lrwxrwxrwx 1 root root 16 Feb  8 12:50 gcc-7 -> ../../bin/ccache
lrwxrwxrwx 1 root root 16 Feb  8 12:50 x86_64-linux-gnu-g++ -> ../../bin/ccache
lrwxrwxrwx 1 root root 16 Feb  8 12:50 x86_64-linux-gnu-g++-7 -> ../../bin/ccache
lrwxrwxrwx 1 root root 16 Feb  8 12:50 x86_64-linux-gnu-gcc -> ../../bin/ccache
lrwxrwxrwx 1 root root 16 Feb  8 12:50 x86_64-linux-gnu-gcc-7 -> ../../bin/ccache
~~~


Other than that it seems to work fine
Only issue is linking MKL with Clang, but this can be figured out in a different PR

**Comment by philbucher** [comment]
wow clang seems to be almost twice as fast compiling compared to gcc :eyes:

**Comment by oberbichler** [comment]
Cool!

Have you tried to set `CC` and  `CXX` to `ccache clang` and `ccache clang++`? It is faster than gcc, I don't think there is any hurry.

**Comment by philbucher** [comment]
> Cool!
> 
> Have you tried to set `CC` and `CXX` to `ccache clang` and `ccache clang++`? It is faster than gcc, I don't think there is any hurry.

I think I tried every possible combination
Maybe we can discuss in person

In any case then this is ready, the Clang build was usually less than half hour, which is much faster than the gcc build

**Review by oberbichler — APPROVED** [review]

**Comment by philbucher** [comment]
I will merge this now to see how Clang is running in other PRs

**Comment by philbucher** [comment]
btw in order to complete the required checks master needs to be merged

**Pull request merged**
