### PR TITLE
CSharpWrapper features

### PR DESCRIPTION
**Pull request by HubertBalcerzak**
* Kratos mesh manipulation
* Kratos variable extraction
* surface stress calculation
* modelpart wrapper
* many API improvements

### CODE REVIEW

**Comment by loumalouomega** [comment]
I would consider this PR or a following PR to move the code files to the proper folders following the standard Kratos code structure

**Comment by HubertBalcerzak** [comment]
@loumalouomega How does standard Kratos code structure apply here? This application does not introduce any custom Kratos components

**Comment by loumalouomega** [comment]
At least move the classes to custom_includes and custom_sources (this is a custom Kratos structure)

**Review by loumalouomega — COMMENTED** [review]
:D

**Review by philbucher — APPROVED** [review]
looks ok to me

**Pull request merged**
