### PR TITLE
[CMake] Some minor tabulation missing

### PR DESCRIPTION
**Pull request by loumalouomega**
**📝 Description**

Some minor tabulation missing

**🆕 Changelog**

- [Some minor tabulation missing](https://github.com/KratosMultiphysics/Kratos/commit/51b9447db5f8204aa416a9a797bfd1a1ed5e8f69)

### CODE REVIEW

**Comment by roigcarlo** [comment]
I don't know if its inteded, but you replaced all tabs with spaces.

**Comment by loumalouomega** [comment]
That's the point

**Comment by loumalouomega** [comment]
> I don't know if its inteded, but you replaced all tabs with spaces.

Yes, in addition to missing tabs that's the point

**Comment by roigcarlo** [comment]
I got confused by the commit descriptions.

I don't have any strong prefference so, since it was 50% 50% ok from my side.

**Comment by loumalouomega** [comment]
> I got confused by the commit descriptions.
> 
> I don't have any strong prefference so, since it was 50% 50% ok from my side.

The last commit is to print the c flags at the end, because it is repeated several times

**Review by roigcarlo — APPROVED** [review]

**Pull request merged**
