### PR TITLE
[Core] add len to matrix in python

### PR DESCRIPTION
**Pull request by qiukailu**
**Description**
Support the len() method for Matrix in Python

**Changelog**
- added len() method for Matrix in core
- added python unit tests to cover len()

**Additional info**
Add any other relevant information here.

### CODE REVIEW

**Comment by qiukailu** [comment]
I guess this PR is more of a curious question. I noticed that for Matrix, there is no support for len() method in Python, whereas for Vector, len() has been implemented. I am curious whether there is a specific reason for not having len() for matrices? 

My use case for this is: in a piece of python code, I need to deal with a variable object and its data. It could be a scalar, a vector, or a matrix, but I can't tell beforehand which type it is. By asking for the size of its data(1, 3, or 9), I can distinguish and perform subsequent operations accordingly. That's why I come to rely on the len() method to get the size of the data.

If there is a better way to get it done, please let me know your suggestions. Thanks!

**Review by loumalouomega — COMMENTED** [review]
I agreewith this

**Comment by philbucher** [comment]
does numpy do this in the same way?

**Comment by roigcarlo** [comment]
I would change it so:

- `matrix.shape` returns a tuple with the actual lengths (x,y)
- `matrix.size` returns the number of elements
- `len(matrix)` returns the number of rows

Otherwise can be misleading (as @philbucher says numpy matrices do not have that behavior and we are supporting them de-facto)

**Comment by oberbichler** [comment]
Probably checking the type with `isinstance` would be the classical way.

AFAIK `len(ndarray)` gives you the number of rows and `len(scalar)` gives you an exception. In `numpy` you would do `numpy.size(object)` to get the expected result. I guess it should work without `numpy` so I would propose to add `Kratos.size(double/Vector/Matrix)` as a static method.

Just adding it as a member function to Vector and Matrix does not cover the Scalar case.

**Comment by philbucher** [comment]
No matter what we decide I think it would be good to be consistent with numpy

=> in order to ensure this we can add a test that runs both with Kratos.Matrix an np.array. This way it would be enforced that they work in the same way

**Review by RiccardoRossi — APPROVED** [review]
ok.

MAYBE we should also eventually add "shape" but ok for now

**Comment by philbucher** [comment]
> ok.
> 
> MAYBE we should also eventually add "shape" but ok for now

@KratosMultiphysics/technical-committee gave its ok :)

**Comment by philbucher** [comment]
@qiukailu what is the status of this?

I will merge next wee unless you have concerns

**Comment by roigcarlo** [comment]
Ping. What is the status? Is marked for the next release and seems to be fine. Can be merged?

**Pull request merged**
