### PR TITLE
Feature disable pfem

### PR DESCRIPTION
**Pull request by roigcarlo**
Disables pfem by default since compilation fails

### CODE REVIEW

**Review by RiccardoRossi — APPROVED** [review]
switched off by default until the mantainer (i am not clear who's in charge here) fixes the compilation

**Comment by roigcarlo** [comment]
Don't forget to delete the branches :smile:

**Comment by maceligueta** [comment]
At the @KratosMultiphysics/technical-committee we talked about the possibility of completely removing this application. Actually, the newest implementation of the PFEM is located in the PfemBaseApplication. We (@KratosMultiphysics/pfem) don't like the new name, but the good one was in use. We all should take a decision about this.

**Comment by RiccardoRossi** [comment]
I don't remember the discussion but i could be positive on this.

is it @antonialarese  the one in charge of the old app?
maybe ilaria? (i don't see her in github)

**Comment by RiccardoRossi** [comment]
Hi again,

i just checked the code and the last changes to the application are over 7 month old and done by me as a pure maintenance.

my vote is +1 for deleting it unless someone steps in.

**Comment by josep-m-carbonell** [comment]
It is ok for me too.

**Comment by pooyan-dadvand** [comment]
👍 to remove it.

And also to change the PfemBaseApplication to PfemApplication.

**Comment by antonialarese** [comment]
It is ok to remove it.

**Pull request merged**
