### PR TITLE
Add case where CMAKE_BUILD_TYPE is passed directly to cmake

### PR DESCRIPTION
**Pull request by marandra**
Hi @roigcarlo 

This PR is the same as #6190. For some reason (probably it's too old?) that PR was not passing CI checks.

The reason for the PR is exactly what you said, in my case it is needed it for building from my IDE.

### CODE REVIEW

**Review by roigcarlo — DISMISSED** [review]

**Comment by philbucher** [comment]
I think sth is going wrong with `runkratos`
@marandra do you compile `runkratos` locally?

**Comment by marandra** [comment]
No @philbucher I usually set if to OFF. I am checking it now

**Comment by roigcarlo** [comment]
mmmm maybe its trying to link against debug python, but that should be fine, unless we had an error in travis (same problem as trying to compile the runkratos in win with debug)

**Comment by marandra** [comment]
> I think sth is going wrong with `runkratos`
> @marandra do you compile `runkratos` locally?

@philbucher : `runkratos` seems to compile normally here.

**Comment by philbucher** [comment]
hm maybe this can be the final incentive to disable the old CI :)

**Comment by philbucher** [comment]
for some reason the CI was not triggered
can you try to merge master @marandra ?

**Comment by marandra** [comment]
any clue @philbucher @roigcarlo ?

**Comment by roigcarlo** [comment]
According to Kitware:

> CMake has several default build types, but if nothing is specified when configuring your project it defaults to an empty string and no optimization flags are used

So we have to check that the content of the variable is empty, not the variable per se. hope this fixes it.

**Comment by roigcarlo** [comment]
Mm I cannot approve because I made a commit @philbucher ?

**Review by philbucher — APPROVED** [review]

**Pull request merged**
