### PR TITLE
[Core] Add Calculate methods for int and array_1d<double,6> in Condition and Element

### PR DESCRIPTION
**Pull request by ddiezrod**

### CODE REVIEW

**Review by loumalouomega — DISMISSED** [review]
Okay from my side. No conflict a priori. I would expose the python part

**Comment by ddiezrod** [comment]
> Okay from my side. No conflict a priori. I would expose the python part

okidoki

**Review by loumalouomega — APPROVED** [review]

**Comment by RiccardoRossi** [comment]
Wow, 2151 of the 31st of december.

Will this be the latest merge of 2024?

Cheers
RICCARDO

**Comment by ddiezrod** [comment]
@RiccardoRossi crimen never sleeps 😄

**Pull request merged**
