### PR TITLE
[Core][VTK] make vtk default settings static

### PR DESCRIPTION
**Pull request by armingeiser**
As it is done in the GiDOutputProcess.

### CODE REVIEW

**Comment by adityaghantasala** [comment]
curious  ! Why is this required ?

**Comment by armingeiser** [comment]
It is helpful if you wan't to look at the defaults without/before creating an instance. 
E.g. in the ShapeOptimizationApplication we wan't to change some of the default settings. So what we can do like this, is to get a copy of the static variable, modify the settings and call ValidateAndAssignDefaults with those modified settings. 
Then we create the actual instance of the vtkio.

```python
tmp_default_parameters = VtkOutputProcess.default_parameters.Clone() #important to Clone so the originals do not get overwritten
tmp_default_parameters["folder_name"].SetString("Optimization_Results")

current_parameters.ValidateAndAssignDefaults(tmp_default_parameters)

vtk_io = VtkOutputProcess(model, current_parameters)
``` 
Like this we do not duplicate default settings, but just reuse them from the place where they are originally defined.

**Comment by adityaghantasala** [comment]
I see ... I am not against but concerned that this is not consistent with the way processes are doing right now !

**Comment by philbucher** [comment]
Hm I think this might be a blocker for #3766 
We are trying to find a common format for the output processes

@armingeiser why don't you do it manually?
~~~py
if not user_defined_settings.Has("folder_name"):
    user_defined_settings.AddEmptyValue("folder_name").SetString("Optimization_Results")
~~~

This is also what I do in similar situations

**Comment by philbucher** [comment]
maybe also a function `AssignDefaults()` (without Validation) could do the job, I would have like this also in other cases already

now that #58 is merged we can again work on the `Parameters`

**Comment by armingeiser** [comment]
@philbucher of course i could do it manually, but doing this for more than one setting or even nested settings (as for GiD) is very tedious.

`AssignDefaults()` could probably also do the job.

**Comment by armingeiser** [comment]
I created #3889 as suggested by @philbucher.

**Comment by philbucher** [comment]
do you still need the branch?

**Pull request closed without merging**
