### PR TITLE
Fluid/feature python solver missing parameter errors

### PR DESCRIPTION
**Pull request by jcotela**
Forcing the user to define the `model_part_name` and `domain_size`, since we cannot assume any reasonable defaults (at least now we get an error message).

### CODE REVIEW

**Review by rubenzorrilla — DISMISSED** [review]
Makes sense.

**Comment by jcotela** [comment]
@rubenzorrilla should we do the same thing for the `structure_model_part` parameter of the FM-ALE embedded?

**Comment by rubenzorrilla** [comment]
Yes, I think that it makes sense as well.

**Comment by jcotela** [comment]
Ok, I've added it, but please check it because I don't have any case to validate it.

**Review by rubenzorrilla — APPROVED** [review]

**Pull request merged**
