### PR TITLE
[Hotfix]Adding missing methods of Has and SetValue for booleans in ConstitutiveLaws

### PR DESCRIPTION
**Pull request by loumalouomega**
@marandra This was the reason because you couldn't define the Has method for a boolean

### CODE REVIEW

**Comment by loumalouomega** [comment]
Besides, there are Doxygen definitions both in the header and the source file, maybe e should keep just one to avoid problem in the future

**Comment by pooyan-dadvand** [comment]
The code is ok, Would you  please add a test?

Meanwhile I would suggest to use flag instead of variable<bool>. Consider that internally I store one double for such a bool value to avoid padding problem.

**Comment by loumalouomega** [comment]
Do I add a test for checking that the Has method works?, because for the base class is always going to be false.

**Comment by loumalouomega** [comment]
Related to  #1650

**Comment by pooyan-dadvand** [comment]
You may add it for the base class to get false and @marandra can test it in his CL test to be true

**Comment by loumalouomega** [comment]
OK

**Comment by loumalouomega** [comment]
OK

**Comment by loumalouomega** [comment]
Done

**Comment by loumalouomega** [comment]
I added some other tests, would be interesting to add tests for the PullBack and push back methods

**Comment by loumalouomega** [comment]
For a future PR

**Comment by RiccardoRossi** [comment]
@pooyan-dadvand i would say that a flag cannot be used in this context...

**Review by pooyan-dadvand — APPROVED** [review]
:+1:

**Pull request merged**
