### PR TITLE
[CORE] Solving compilation warning due to the initial state

### PR DESCRIPTION
**Pull request by AlejandroCornejo**
That's it

### CODE REVIEW

**Comment by AlejandroCornejo** [comment]
Dear @Vahid-Galavi Can you try and see if there's this warning? :) THX

**Review by philbucher — APPROVED** [review]
This makes sense :D

**Comment by AlejandroCornejo** [comment]
> 
> 
> This makes sense :D

yes... I was really dumb haha

**Comment by Vahid-Galavi** [comment]
> Dear @Vahid-Galavi Can you try and see if there's this warning? :) THX

I tested on both Windows and Linux. It works!

**Review by Vahid-Galavi — COMMENTED** [review]
It works!

**Comment by Vahid-Galavi** [comment]
Approve button is not active for me to approve this code review.

**Comment by AlejandroCornejo** [comment]
> Approve button is not active for me to approve this code review.

It is approved!! I thought that it will work for you since was ok for me. Luckily I was right ;)

**Pull request merged**
