### PR TITLE
[CI] turn all warnings into errors with GCC

### PR DESCRIPTION
**Pull request by philbucher**
**Description**
Since the compilation has been quite clean and stable for a long time already, I would like to switch from selectively turning warnings into errors to turning ALL warnings into errors

Before I would fix them manually and then push the fix together with turning the warning into an error.
With this change we can avoid this altogether

### CODE REVIEW

**Comment by philbucher** [comment]
ah I am stupid, this will not work bcs of the deprecation warnings :(

(also now another warning appeared that has to be fixed, but I guess one by one is the only way)

**Comment by philbucher** [comment]
now it works, I didn't think of disabling the deprecation warnings here before (they anyway have no use in the CI)

Now it is possible to turn all warnings into errors, like we started doing in #8067

**Review by rubenzorrilla — APPROVED** [review]
Thanks for the fix.

**Comment by philbucher** [comment]
FYI @ddiezrod :)

**Pull request merged**
