### PR TITLE
[DEM] Improve mesh creator from previous calculations for clusters and spheres

### PR DESCRIPTION
**Pull request by joaquinirazabal**
The creation of sphere and clusters mdpa files has been improved, now it works for 2D and 3D indistinctly and not .msh nor .res files are needed.

This allows the removal of two unused variables: ORIENTATION_REAL and ORIENTATION_IMAG.

### CODE REVIEW

**Comment by philbucher** [comment]
@KlausBSautter this might be interesting for you

**Comment by KlausBSautter** [comment]
@joaquinirazabal does this make the spheretree thing redundant? Is there an example, on how to use it?

**Comment by joaquinirazabal** [comment]
Hi, @KlausBSautter. No, this is a utility to create a ".mdpa" of spheres or clusters from the results of a previous simulation.

For the moment if you include in the AdditionalFinalizeOperations function of DEM_analysis_stage.py this:
    import mesh_creator_cluster
    clusters_mp_filename_post = self.problem_name + 'DEM_Post'
    mesh_creator_cluster.WriteClusterMdpaFromResults(self.problem_name + 'DEM_Clusters', self.main_path, clusters_mp_filename_post, self.cluster_model_part)

It will generate a new ".mdpa" file that can be used in the following calculations.

Let's see what @salvalatorre and @maceligueta say, maybe we can improve this.

**Comment by maceligueta** [comment]
Hello @joaquinirazabal , I think it's fine. 
Lately I have been using a version of this for plain spheres and I realized that, at least for me, it is not that useful to have this feature being called from the Stage itself, because you either write many mdpa's or you overwrite one again and again. For me it was more useful to have this utility called from outside as an independent script, once the computation is finished: it reads certain output files and then writes the new mdpa's.
I guess both possibilities are ok. Just decide what is best for you and I am good with it.

**Review by salvalatorre — APPROVED** [review]
For me it is more than OK!

**Comment by joaquinirazabal** [comment]
I agree, @maceligueta, so I leave the PR as it is, without changing the AdditionalFinalizeOperations. In case you need to use it, @KlausBSautter you can call the function the way I told you from another independent script.

Thanks for the review!

**Pull request merged**
