### PR TITLE
[CI] Extent errors compilation in CI

### PR DESCRIPTION
**Pull request by loumalouomega**
**📝 Description**

This adds errors that used to be (according to my memory) part of the ancient CI with Travis. I don't know if I don't remember properly, or it is just my imagination.

**🆕 Changelog**
- Extent errors compilation in CI

### CODE REVIEW

**Comment by philbucher** [comment]
Dont we have Wall and Wpendantic somewhere?

Probably better to add those if they are not already there

Do you get warnings?
Can also be compiler dependent

**Comment by loumalouomega** [comment]
> Dont we have Wall and Wpendantic somewhere?

We used to in Travis..., but when e migrated to Github CI we remove them....

> Probably better to add those if they are not already there

Okay

> Do you get warnings? Can also be compiler dependent

It is compiler dependent (the flags are different in clang and gcc)

**Comment by loumalouomega** [comment]
> Do you get warnings? 

In my local machine if I compile with these flags it fails, I do not understand why here it works...

**Comment by loumalouomega** [comment]
> > Do you get warnings?
> 
> In my local machine if I compile with these flags it fails, I do not understand why here it works...

Okay, it is because Unity and in the Fluid, we just do not compile with Unity the Core

**Comment by roigcarlo** [comment]
@loumalouomega as @philbucher we already have `-Wall`. We can add this but it won't add any other flag.

**Comment by loumalouomega** [comment]
> @loumalouomega as @philbucher we already have `-Wall`. We can add this but it won't add any other flag.

So if we want to add flags?

**Comment by roigcarlo** [comment]
Not sure what you mean, you can add all the flags you want, but they are already included in the -Wall

**Comment by roigcarlo** [comment]
Here: https://github.com/KratosMultiphysics/Kratos/blob/master/.github/workflows/configure.sh#L67

**Comment by loumalouomega** [comment]
> Not sure what you mean, you can add all the flags you want, but they are already included in the -Wall

But not as error

**Comment by roigcarlo** [comment]
Yes, the werror comes from the KRATOS_CMAKE_FLAGS which is added before the Wall of the configure, so every warning is still an error.

**Comment by loumalouomega** [comment]
> Yes, the werror comes from the KRATOS_CMAKE_FLAGS which is added before the Wall of the configure, so every warning is still an error.

Okay, so I will cherrypick the fix of this PR and close this

**Pull request closed without merging**
