### PR TITLE
[PotentialFlow] Add process to compute quantities on wing sections

### PR DESCRIPTION
**Pull request by marcnunezc**
**Description**
This process finds the section of a wing for a given plane (geometrical plane defined with its normal vector and a point, not an aircraft 😄 ) and computes a given set of variables on the section in a new model part. 

Very useful to plot typical pressure distribution plots. 

@inigolcanalejo I changed the name and generalised the process to use any variable.

**Changelog**
- Adding new wing section process and cpp tests.

### CODE REVIEW

**Comment by inigolcanalejo** [comment]
@marcnunezc let me know when this is ready for review

**Comment by marcnunezc** [comment]
It is ready!

**Review by inigolcanalejo — APPROVED** [review]
Looks good! I have been using this process for the last months and it works perfect :+1: I see that you made it even more flexible!

Just a question from my experience: sometimes one wants to plot a variable in the same section for consecutive pseudo time steps (e.g. when doing load stepping in a nonlinear problem). In these cases I am creating a new model part with a new name to avoid mixing data from different time steps, is there a better way of doing this?

Thanks for adding this function, it is quite crucial to verify the solvers :rocket:

**Comment by marcnunezc** [comment]
> Just a question from my experience: sometimes one wants to plot a variable in the same section for consecutive pseudo time steps (e.g. when doing load stepping in a nonlinear problem). In these cases I am creating a new model part with a new name to avoid mixing data from different time steps, is there a better way of doing this?

Considering how the process works right now, I would remove and create a new model part each pseudo time step (after plotting/storing the data). 

If the geometry is not changing we could avoid doing the search of the entities intersected by the plane every time, which would be more efficient for the next steps.  Are you referring to this? It would be a bit complicated since we can have many sections defined. 

If you are referring as to how to store all the data in a single model part for all time steps, I think it is best to store the data to file  at each time step and avoid storing it in Kratos.

**Pull request merged**
