### PR TITLE
[CMake][MeshingApplication] Update MMG cmake modules (from MMG repository)

### PR DESCRIPTION
**Pull request by loumalouomega**
**📝 Description**

Update MMG cmake modules (from MMG repository)

FYI @Clouzetpierre

**🆕 Changelog**

- [Update MMG cmake modules (from MMG repository)](https://github.com/KratosMultiphysics/Kratos/commit/b541f774e8a3656c89420e0e9e92a085fa29633f)

### CODE REVIEW

**Comment by loumalouomega** [comment]
This is failing in my machine (I just copied from official CMake, veryfying now)

**Comment by loumalouomega** [comment]
Related: https://github.com/MmgTools/mmg/pull/194

**Comment by marcnunezc** [comment]
Do older versions also work with these new CMake modules?

**Comment by loumalouomega** [comment]
> Do older versions also work with these new CMake modules?

If the CI passes then yes

¯\_(ツ)_/¯

**Review by marcnunezc — APPROVED** [review]

**Pull request merged**
