### PR TITLE
Update Kratos logo

### PR DESCRIPTION
**Pull request by loumalouomega**

### CODE REVIEW

**Review by jcotela — APPROVED** [review]

**Comment by roigcarlo** [comment]
Ok but since we are changing the logo, could we make the mesh the height of the text? I always have found the white space in the top left part a little bit off.

**Review by jcotela — DISMISSED** [review]
please see @roigcarlo's comments. Also, we should make sure this does not confilct with #1259

**Comment by maceligueta** [comment]
And maybe we could add some margin on the left and bottom. I see that the text is touching the limits of the picture... is this wanted?

**Comment by loumalouomega** [comment]
kratos

Is this OK?

**Review by roigcarlo — APPROVED** [review]

**Comment by loumalouomega** [comment]
Ok, I will commit the new logo to the documentation repo

**Comment by pooyan-dadvand** [comment]
@loumalouomega The font is ok but the please update the logo with @jcotela version.

**Comment by pooyan-dadvand** [comment]
By the way thanks for actualizing the font. Do you have a vectorial version?

**Comment by loumalouomega** [comment]
I am using @jcotela  version. The file is in https://raw.githubusercontent.com/KratosMultiphysics/Documentation/master/Wiki_files/Home/kratos.png and the vectorial version is https://raw.githubusercontent.com/KratosMultiphysics/Documentation/master/Wiki_files/Home/kratos.svg

The font is https://www.fontzillion.com/fonts/digital-dream-design/d3-euronism?utm_source=fontsquirrel.com&utm_medium=matcherator_link&utm_campaign=d3euronism

**Comment by pooyan-dadvand** [comment]
Perfect! Thanks!

**Pull request merged**
