### PR TITLE
Feature dem rot integration

### PR DESCRIPTION
**Pull request by joaquinirazabal**
Adding a new pointer for the integration of the rotation. Now if you choose any scheme for the integration of the translational motion you can select for the rotational motion: "Direct Integration (example, Forward Euler -> Forward Euler)", "Runge Kutta" and "Quaternion Integration".

The scheme has been erased from the strategy.

It compiles with the swimming DEM application, I think everything work.

### CODE REVIEW

**Review by GuillermoCasas — CHANGES_REQUESTED** [review]
Very nice job! A few little things:
1. You are passing the angular_velocity non-const and the angular_momentum as const. Is this logical? (in function UpdateRotationalVariables)
2. The name 'CalculateNewRotationalVariablesofSpheres' should be 'CalculateNewRotationalVariablesOfSpheres'
3. You are using DEM_MODULUS_3 where you could use the inner product (and avoid the sqrt)
4. you are forgetting a few noalias(), such as in quarter_local_angular_velocity = local_angular_velocity + 0.25 * local_angular_acceleration * delta_t; and other places around there
5. I do not like the one liners such as if(verbose). Just asking you to reconsider
6. The comment //                 DEMIntegrationScheme::Pointer pScheme, can be removed (why keep it?)
7. Use std::cos and std::sin (for example in sin(linear_omega * (time - velocity_start_time)) * inv_linear_omega;
8. Check indentation around #if not "TestType" in self.DEM_parameters.keys():. Also remove the comment if possible
9. We have to talk about thi: return globals().get(class_name)(). I did it too but it is not the way to go.
10. The message summary = 'The class corresponding to the translational integration scheme name (' + name + ') has not been added to python. Please, select a different name or add the required class.' should read summary = 'The class corresponding to the translational integration scheme named ' + name + ' has not been added to python. Please, select a different name or add the required class.'
11. We are propagating bare C-arrays in Kratos. We must talk about this (e.g., moments_of_inertia[(j + 2) % 3])

**Review by GuillermoCasas — APPROVED** [review]
There are still some undone optimizations in some cluster classes but someone else should do them.

**Comment by joaquinirazabal** [comment]
Tank you for the feedback, Guillermo, very interesting suggestion, I comment them below:

1. You are passing the angular_velocity non-const and the angular_momentum as const. Is this logical? (in function UpdateRotationalVariables) -> In the Runge-Kutta scheme we assume that the 
change in angular momentum can be approximated by increments due to the change in the external torques at every time step, so we calculate the change new angular momentum and then update the other rotational variables.
2. The name 'CalculateNewRotationalVariablesofSpheres' should be  'CalculateNewRotationalVariablesOfSpheres' -> Changed
3. You are using DEM_MODULUS_3 where you could use the inner product (and avoid the sqrt) -> Changed.
4. you are forgetting a few noalias(), such as in quarter_local_angular_velocity = local_angular_velocity + 0.25 * local_angular_acceleration * delta_t; and other places around there -> Changed.
5. I do not like the one liners such as if(verbose). Just asking you to reconsider -> This was from before, I am not really sure what is this for, I commented them in the integration schemes, do you think they will be avoided in all the code?
6. The comment // DEMIntegrationScheme::Pointer pScheme, can be removed (why keep it?) -> Removed.
7. Use std::cos and std::sin (for example in sin(linear_omega * (time - velocity_start_time)) * inv_linear_omega; -> Changed.
8. Check indentation around #if not "TestType" in self.DEM_parameters.keys():. Also remove the comment if possible -> Removed.
9. We have to talk about thi: return globals().get(class_name)(). I did it too but it is not the way to go. -> Left as it was for reconsidering it.
10. The message summary = 'The class corresponding to the translational integration scheme name (' + name + ') has not been added to python. Please, select a different name or add the required class.' should read summary = 'The class corresponding to the translational integration scheme named ' + name + ' has not been added to python. Please, select a different name or add the required class.' -> Changed.
11. We are propagating bear C-arrays in Kratos. We must talk about this (e.g., moments_of_inertia[(j + 2) % 3]) -> Left as it was for reconsidering it.

I also removed deprecated schemes: constant average acceleration and mid point scheme.

**Comment by joaquinirazabal** [comment]
Merged!

**Comment by maceligueta** [comment]
Did you guys check that the tests were OK?

**Pull request merged**
