### PR TITLE
[ContactStructuralMechanicsApplication] Improvement on allocation on  derivatives utilities

### PR DESCRIPTION
**Pull request by loumalouomega**
Recent changes make fail the derivatives on FullDebug, this fixes that and additionally improves the number of allocations needed for the computations

### CODE REVIEW

**Review by philbucher — DISMISSED** [review]

**Comment by loumalouomega** [comment]
I found that some validation tests stopped working, working on that

**Comment by loumalouomega** [comment]
Now it is fixed, additionally I moved the code to cpp (at the beginning I did this because I was taking to long to debug for the linking time, so I moved to the cpp, as the effort was already done I decided to move the code definetively to the cpp)

**Review by philbucher — APPROVED** [review]
Looks ok to me

**Comment by loumalouomega** [comment]
I only have one question, @roigcarlo I realized that it compiled in appveyor without using KRATOS_API, it does that normal?

**Pull request merged**
