### PR TITLE
[GeoMechanicsApps] Deriving elements from Structural

### PR DESCRIPTION
**Pull request by roigcarlo**
Draft for testing #8769

### CODE REVIEW

**Comment by Vahid-Galavi** [comment]
Now Works!
Can we merge it with master?

**Comment by roigcarlo** [comment]
Sure, let me convert it to a PR

**Review by loumalouomega — APPROVED** [review]
Ok from my side

**Review by Vahid-Galavi — APPROVED** [review]
Approved.

**Pull request merged**
