### PR TITLE
[CI] Add IgaApplication to the CI

### PR DESCRIPTION
**Pull request by tteschemacher**
Dear all, especially @KratosMultiphysics/technical-committee,

I'd like to add the IgaApplication to the CI. At the moment the IgaApplication is very light, which should also remain like this in the future as we want to use as many features from the StructuralMechanicsApplication as possible.

### CODE REVIEW

**Comment by philbucher** [comment]
Seems like it doesn't compile in GCC, probably some warnings are treated as errors

**Comment by tteschemacher** [comment]
Some missing overrides. I'll fix them.

**Comment by tteschemacher** [comment]
@KratosMultiphysics/technical-committee @philbucher it seems to work now. I want to officially announce my application to become a member of the CI with IGA ;)

**Comment by philbucher** [comment]
@tteschemacher this has a lot of fixes for the IGA-App
Could you please make a separate PR and first merge the non-CI changes?
That would make review much easier

**Comment by tteschemacher** [comment]
I just deleted this branch #6606. The correction of the IGA stuff is a separate thing. However, the essential things needed within this PR are only the lines adding it to the CI, configure and nightly build. I suppose there can't be any big code mistakes.

I needed to put it in one pr to see if it passes the CIs.

**Comment by tteschemacher** [comment]
@KratosMultiphysics/technical-committee are you ok with adding the IgaApplication to the CI?

**Comment by tteschemacher** [comment]
ping @KratosMultiphysics/technical-committee

**Comment by tteschemacher** [comment]
@RiccardoRossi @pooyan-dadvand @philbucher @rubenzorrilla do you agree with that?

**Comment by philbucher** [comment]
for me ok, even though the IGA-App is quite new/small. I think it is clear at this point that a lot of developments are going into it and it will be an important feature in the future

**Comment by tteschemacher** [comment]
Thanks @philbucher 

The sooner we add it, the sooner we have the quality check. And it does not affect the compilation time significantly.

@RiccardoRossi @pooyan-dadvand @rubenzorrilla @roigcarlo how about you?

**Comment by RiccardoRossi** [comment]
@KratosMultiphysics/technical-committee approves

**Review by RiccardoRossi — APPROVED** [review]

**Comment by tteschemacher** [comment]
Thank you!

**Pull request merged**
