### PR TITLE
Update FluidTransport python solver to model v3

### PR DESCRIPTION
**Pull request by ipouplana**
Adapting FluidTransportApp with model v3 in the new python standard (#2417)

### CODE REVIEW

**Review by RiccardoRossi — CHANGES_REQUESTED** [review]
please wait to merge...i would like to first merge model_v3 to master

**Comment by ipouplana** [comment]
Ok

**Comment by RiccardoRossi** [comment]
btw @roigcarlo why appveyor does not appear in the checks herE?

**Comment by roigcarlo** [comment]
Because only merges to master trigger builds.

**Comment by RiccardoRossi** [comment]
ok i merged. @ipouplana you closed this branch (i hope it was not me at least) either merge it to the master, or just do a new PR with this... 

if you go for a new PR, do not forget to delete this

**Comment by ipouplana** [comment]
Yes, I closed this PR, but I will open a new one to merge our branch against master.

**Comment by RiccardoRossi** [comment]
thx, then i'll delete the branch

**Pull request closed without merging**
