### PR TITLE
Removinf typeid from model_part_io

### PR DESCRIPTION
**Pull request by loumalouomega**

### CODE REVIEW

**Comment by loumalouomega** [comment]
Solving #1321

**Comment by roigcarlo** [comment]
Warnings gone :+1: 
but is there any particular reason to change all the loops?
The ones in the lines 143, 290, 364, 394 are the only ones that maybe can have a performance effect...

**Comment by roigcarlo** [comment]
Also, the warning appears only in this file, so no need to change anything else.

**Comment by loumalouomega** [comment]
What do you mean?

**Comment by roigcarlo** [comment]
You said in the commit 

> if this is what you mean I can apply to the conditions and other components

No need for that that I am aware

**Comment by loumalouomega** [comment]
I addedto the conditions, and I removed some other warning (related with identation), can we proceed?

**Comment by loumalouomega** [comment]
Ping @roigcarlo

**Comment by roigcarlo** [comment]
Could you revert the ++i?

**Comment by loumalouomega** [comment]
Done, I removed the CammelCase of some methods that I implemented

**Review by roigcarlo — APPROVED** [review]

**Comment by loumalouomega** [comment]
Thanks, I saw that there are many methods not documented in the Doxygen, if I can I will do a separate PR adding the proper documented methods.

**Pull request merged**
