### PR TITLE
Cps/relocate nodal normal neighbour comp

### PR DESCRIPTION
**Pull request by LHoeffner**
calls for the utilities preparing nodal values have been moved from the define_wake_process to the boundary condition process (apply_far_field_process). 

As they are generally (always?) used together, the location of these lines did not make a difference so far. For FSI however, the wake is redefined after every iteration by calling the define_wake_process. This triggered overwrites which will be avoided by this merge since the apply_far_field_process is still only used once.

### CODE REVIEW

**Comment by marcnunezc** [comment]
This looks fine to me. I will wait for @inigolcanalejo or others to also take a look before approving.

Remember that you can add reviewers to the pull request, so that they receive a notification!

**Comment by rubenzorrilla** [comment]
Correct me if I'm wrong but the aim of the PR is to compute the normal and the neighbors once, something that was not happening with the previous implementation. Thus, you moved the call to this utilities to another process so they are called once.

The question is, if the normal and neighbors computation is always required, why don't you put it in the `Initialize` method of the solver?

**Comment by LHoeffner** [comment]
> Correct me if I'm wrong but the aim of the PR is to compute the normal and the neighbors once, something that was not happening with the previous implementation. Thus, you moved the call to this utilities to another process so they are called once.
> 
> The question is, if the normal and neighbors computation is always required, why don't you put it in the `Initialize` method of the solver?

I agree, tested it and this also works well for the examples I have at hand. Lets wait for @inigolcanalejo (who should be back on Thursday) to comment before pulling.

**Comment by philbucher** [comment]
guys have you considered using the Normal provided by `Geometry`?
I feel like the NormalClacUtils are a leftover from times when the Normal was not available through `Geometry`

**Comment by marcnunezc** [comment]
Hi @LHoeffner, do you get problems now with FSI cases?

We can still restore this branch if needed to move the FindNeighbourElements() call to the potential_solver.py.

**Comment by LHoeffner** [comment]
@marcnunezc thanks but I do not think this will be necessary (thus I closed this request). I will include this change in a future request containing all FSI implementations if required.

**Pull request closed without merging**
