### PR TITLE
Revert "Dem moving to json"

### PR DESCRIPTION
**Pull request by maceligueta**
Reverts KratosMultiphysics/Kratos#771

### CODE REVIEW

**Comment by loumalouomega** [comment]
Before check the PR, does this revert https://github.com/KratosMultiphysics/Kratos/pull/782?

**Comment by maceligueta** [comment]
Revert of 771

**Comment by loumalouomega** [comment]
Now reverts 782 too

**Comment by loumalouomega** [comment]
Compiling....

**Review by loumalouomega — APPROVED** [review]
It compiles

**Pull request merged**
