### PR TITLE
[Core] Enhancement of some geometries ( `Hexahedra3D8`, `Quadrilateral3D4`,  `Prism3D6`, `Piramid3D5`, `Triangle3D6`, `Tetrahedra3D10` and `Tetrahedra3D4`) with  `CalculateDistance`

### PR DESCRIPTION
**Pull request by loumalouomega**
**📝 Description**

The PR contains a number of enhancements and additions to of some geometries, specifically `Hexahedra3D8`, `Quadrilateral3D4`,  `Prism3D6`, `Piramid3D5`, `Triangle3D6`, `Tetrahedra3D10` and `Tetrahedra3D4`.

1. A new method `CalculateDistance` is added to  `Hexahedra3D8`, `Quadrilateral3D4`,  `Prism3D6`, `Triangle3D6`, `Tetrahedra3D10`, `Piramid3D5` and `Tetrahedra3D4`. This method calculates the distance from a point to the closest point of the geometry. The calculation depends on the geometrical conditions of the entity, such as whether the point is outside or inside the geometry. 
2. The method is then used to generate triangles and calculate the distances between them and the point in global coordinates. The minimum distance is returned.
3. Test are added, to check if the distance calculation for is correct.

The PR also contains minor formatting changes and updates in the documentation of the code.

**🆕 Changelog**

- [Adding `Triangle3D3CalculateDistance` test](https://github.com/KratosMultiphysics/Kratos/pull/11252/commits/54016e477d87f7686f32f78559bffa090b764407)
- [Adding `CalculateDistance` to `Hexahedra3D8`](https://github.com/KratosMultiphysics/Kratos/commit/41fa56b855d054211047bb55d313fcfa01eac1c8)
- [Adding `CalculateDistance` to `Quadrilateral3D4`](https://github.com/KratosMultiphysics/Kratos/commit/6a6100597c7ca0245926b1997ac23ce483752f4c)
- [Adding `CalculateDistance` to `Tetrahedra3D4`](https://github.com/KratosMultiphysics/Kratos/commit/c241203fc775bbc4d91d8b7401570c49b3c452a1)
- [Adding `CalculateDistance` to `Prism3D6`](https://github.com/KratosMultiphysics/Kratos/pull/11252/commits/669f84c18162e9c6a55bce728b424f6addcf2c01)
- [Adding `CalculateDistance` to `Piramid3D5`](https://github.com/KratosMultiphysics/Kratos/pull/11252/commits/215280c6ce38c7beb27f4de1f759126e8fbde010)
- [Adding `CalculateDistance` to `Triangle3D6`](https://github.com/KratosMultiphysics/Kratos/pull/11252/commits/4a30a661cb41cc71edde43720519a80a1b08a441)
- [Adding `CalculateDistance` to `Tetrahedra3D10`](https://github.com/KratosMultiphysics/Kratos/pull/11252/commits/1c026ae539bed64a1e8e8c08f21dbd6b362e1bfc)
- [Adding `Hexahedra3D8CalculateDistance` test](https://github.com/KratosMultiphysics/Kratos/commit/37d8c0ae029e482c443ca6d710176499ffdc32d3)
- [Adding `Tetrahedra3D4CalculateDistance` test](https://github.com/KratosMultiphysics/Kratos/commit/4c00ec325264a16c22edbc0856329e5455f4038f)
- [Adding `Quadrilateral3D4CalculateDistance` test](https://github.com/KratosMultiphysics/Kratos/commit/82634aed8cacf516e7a45dc9e5566cd7f133d33b)
- [Adding `Prism3D6CalculateDistance` test](https://github.com/KratosMultiphysics/Kratos/pull/11252/commits/ce230e21e27fb440555754b0942f87acfb1864b5)
- [Adding `Pyramid3D5CalculateDistance` test](https://github.com/KratosMultiphysics/Kratos/pull/11252/commits/62d23e757648e86e860c0961613812d8a8387d42)
- [Adding `Triangle3D6CalculateDistance` test](https://github.com/KratosMultiphysics/Kratos/pull/11252/commits/2ac7da2b20622cdd434ce484e6cdad2abb664404)
- [Adding `Tetrahedra3D10CalculateDistance` test](https://github.com/KratosMultiphysics/Kratos/pull/11252/commits/bc5e17c3ef4c5d68e8a7c1b1ed824d49e6331ce1)

### CODE REVIEW

**Comment by loumalouomega** [comment]
Anyone?

**Comment by pooyan-dadvand** [comment]
GenerateFaces is very inefficient. Is it possible to be avoided?

**Comment by loumalouomega** [comment]
> GenerateFaces is very inefficient. Is it possible to be avoided?

I can manually create the connectivities, but then it will be a bit verbose, but I can try it.

**Comment by loumalouomega** [comment]
Ping, anyone?, this only adds, doesn't change behaviour at all

**Review by ddiezrod — APPROVED** [review]

**Pull request merged**
