### PR TITLE
[StructuralMechanics] Make consistent GetValue, Has, CalculateValue functions in plasticity and damage CLs

### PR DESCRIPTION
**Pull request by marandra**
- Added missing SetStrainVector(...) when computing Constitutive Tensor in base and bbar elements. 
- Make consistent GetValue, SetValue, Has, CalculateValue functions in plasticity and damage CL

### CODE REVIEW

**Review by loumalouomega — DISMISSED** [review]
Finally I can reactive the remeshing tests

**Comment by marandra** [comment]
thanks!

**Comment by philbucher** [comment]
Sorry the core does not compile atm, fixed in #3292

**Review by philbucher — APPROVED** [review]

**Comment by loumalouomega** [comment]
I will merge this, so I can reactivate the tests

**Pull request merged**
