### PR TITLE
[Structural] updating Interfaces I

### PR DESCRIPTION
**Pull request by philbucher**
This PR updates the Interfaces of 
- `EquationIdVector`
- `GetDofList`
- `Check`

Please check, tests are running in my machine

### CODE REVIEW

**Review by loumalouomega — DISMISSED** [review]
OK

**Review by philbucher — COMMENTED** [review]
@armingeiser @MFusseder please check this carefully
This gave me quite some headaches :sweat_smile:

**Comment by philbucher** [comment]
ok now that the adjoint fixed are merged this is ready

**Comment by philbucher** [comment]
can this be merged or are there concerns?

**Review by armingeiser — APPROVED** [review]
From my side it is fine.

**Pull request merged**
