### PR TITLE
[Core] Bugfix in "Solve" of PythonSolver

### PR DESCRIPTION
**Pull request by philbucher**
Found by @bodhinandach 

I am not sure abt the effects of this
I think we should rather sooner than later remove this for good ...

In Fluid and Structure this is not used for a while already but some others might still be using it

### CODE REVIEW

**Comment by RiccardoRossi** [comment]
+1 for the change. did u try to grep for usages?

**Comment by philbucher** [comment]
I found the following usages:
- contact_structural_mechanics_implicit_dynamic_solver.py @loumalouomega 
- contact_structural_mechanics_static_solver.py @loumalouomega 
- navier_stokes_compressible_solver.py @jcotela 
- mok_benchmark_test.py @rubenzorrilla 
- structural_mechanics_adjoint_static_solver.py @armingeiser @MFusseder

**Comment by loumalouomega** [comment]
I override the Solve in the contact, I don't even use Predict, because it breaks the contact simulation

**Comment by philbucher** [comment]
@loumalouomega but you are not calling `Solve` since your AnalysisStage does not override the BaseClass-`RunMainSolutionLoop`, which calls the fcts separately

Can you check pls?

**Comment by loumalouomega** [comment]
Ok

**Comment by RiccardoRossi** [comment]
anyway the solve method should not be defined ...

Riccardo

**Comment by loumalouomega** [comment]
Ok for me, but the add of the check added many warnings to my tests :P

**Review by loumalouomega — APPROVED** [review]

**Comment by philbucher** [comment]
> Ok for me, but the add of the check added many warnings to my tests :P

this is very likely, you should not use it :)

**Comment by philbucher** [comment]
@loumalouomega why don't you remove `Solve`? then the warnings will disappear

**Comment by philbucher** [comment]
what should we do with this?

**Comment by bodhinandach** [comment]
I am voting to remove `Solve` to reduce deprecated codes.

**Comment by philbucher** [comment]
> I am voting to remove `Solve` to reduce deprecated codes.

so do I, but we cannot just break things ...

**if none complains I would merge this after 15.12**
otherwise please let me know

ping @jcotela @rubenzorrilla please check if this is ok for you otherwise let me know

**Comment by jcotela** [comment]
@philbucher I do not think that this change is relevant to the compressible solver, no objections from my side.

**Review by roigcarlo — APPROVED** [review]
👍

**Comment by philbucher** [comment]
I will run the tests again before merging this
=> next week, just to be safe since this has the potential for breaking stuff ...

**Comment by philbucher** [comment]
I ran the tests in the involved applications, I didn't get more errors than in master

Therefore I will merge this on Friday

**Pull request merged**
