### PR TITLE
[Structural] not use ComputingModelPart by default

### PR DESCRIPTION
**Pull request by philbucher**
With this PR (FINALLY) the ComputingModelPart is no longer used by default, now by default the entire (aka Main-) ModelPart is being passed to the B&S

it is backward compatible with the Contact where the ComputingMP is still required
@loumalouomega (or others) this gives you more time to update

### CODE REVIEW

**Comment by loumalouomega** [comment]
I will need time to update the tests and examples

**Comment by philbucher** [comment]
> I will need time to update the tests and examples

It is backward compatible, will only issue some warnings

**Comment by loumalouomega** [comment]
> 
> 
> > I will need time to update the tests and examples
> 
> It is backward compatible, will only issue some warnings

OK

**Review by loumalouomega — DISMISSED** [review]
Let's see

**Comment by philbucher** [comment]
@RiccardoRossi I would like your opinion on this, are you ok with this change?

**Review by RiccardoRossi — COMMENTED** [review]
I am in favor of those changes.
Also the warnings are pretty clear to me.

I am a little worried since It may affect users . in particular @ipouplana @jrubiogonzalez this may affect structural solutions. @ipouplana can u try out if your solvers still work after this?

**Comment by ipouplana** [comment]
Thanks @RiccardoRossi , I'll try it asap.

**Comment by ipouplana** [comment]
I just run the Poromechanics tests in this branch and everything is ok :)

**Comment by philbucher** [comment]
note that setting `use_computing_model_part` to false preserves the old behavior

**Review by philbucher — COMMENTED** [review]
@KlausBSautter I had to resolve a conflict but I am not sure it was correct, can you please check this commit?

**Comment by ddiezrod** [comment]
> I just run the Poromechanics tests in this branch and everything is ok :)

What about our ThermoMechanical app, will it be affected by these changes? @ipouplana

**Comment by philbucher** [comment]
did the thermomechanical ever use StructuralMechanics?
It is anyway in the legacy apps repo now

**Comment by ddiezrod** [comment]
> did the thermomechanical ever use StructuralMechanics?
> It is anyway in the legacy apps repo now

Its not that one, its in the private side.

**Comment by ipouplana** [comment]
> > I just run the Poromechanics tests in this branch and everything is ok :)
> 
> What about our ThermoMechanical app, will it be affected by these changes? @ipouplana

I just checked the tests and the example of the cylinder and everything is working also in this branch.

**Comment by philbucher** [comment]
Thx for testing 

Everyone happy now?

**Comment by KlausBSautter** [comment]
please wait, apparently my tests are still failing
Edit: @philbucher I am happy now :+1:

**Comment by loumalouomega** [comment]
@philbucher I need to check first (I forgot this)

**Comment by loumalouomega** [comment]
Go ahead

**Review by loumalouomega — APPROVED** [review]
:+1:

**Comment by loumalouomega** [comment]
I will fully clean up my app after merge

**Pull request merged**
