### PR TITLE
[Core] Move VariablesListDataValueContainer to source file

### PR DESCRIPTION
**Pull request by loumalouomega**
**📝 Description**
Move VariablesListDataValueContainer to source file in order to reduce compilation times

**🆕 Changelog**
- Move most of the code to source file
- Remove unused includes (also reduces compilation time)
- Move some functions to be in the proper category (Access, Inquiry, etc...)
- Adding some const to some methods

### CODE REVIEW

**Review by rubenzorrilla — CHANGES_REQUESTED** [review]
See the thoughts of @KratosMultiphysics/technical-committee in #10062.

**Comment by loumalouomega** [comment]
> See the thoughts of @KratosMultiphysics/technical-committee in #10062.

This file does not have template

**Comment by loumalouomega** [comment]
> > See the thoughts of @KratosMultiphysics/technical-committee in #10062.
> 
> This file does not have template

If you mean this : `Also splitting in cpp and header implies essentially losing the repo history, something we don't really love`. Please cite the specific line, because I though you mean what @roigcarlo said and I was lost.

I understand about the losing repo history, but this specific file is included many times and its slowing down significantly. Besides the history is still in the header file, it will be more complex to blame, but a priori it is possible to manually blame.

**Comment by rubenzorrilla** [comment]
I meant the conclusions of the discussion posted by @RiccardoRossi. See _Originally posted by @RiccardoRossi in https://github.com/KratosMultiphysics/Kratos/issues/10062#issuecomment-1193785589_

**Comment by loumalouomega** [comment]
> I meant the conclusions of the discussion posted by @RiccardoRossi. See _Originally posted by @RiccardoRossi in [#10062 (comment)](https://github.com/KratosMultiphysics/Kratos/issues/10062#issuecomment-1193785589)_

Okay, is this open to discussion or it is a closed no, and therefore should i close this PR?

**Comment by rubenzorrilla** [comment]
About this particular class the position to leave it as it is was clear (at least for the near future). Having said this, I'd close this PR.

**Comment by loumalouomega** [comment]
> About this particular class the position to leave it as it is was clear (at least for the near future). Having said this, I'd close this PR.

I will close, but leave the branch until the discussion in the issue is more detailed

**Comment by loumalouomega** [comment]
Do I delete this brnahc or do you think it could be interesting?

**Pull request closed without merging**
