### PR TITLE
Making serializer base class load and save methods private.

### LINKED ISSUE #3876: [Core][Serializer] Many warnings in the master
~~~
/home/vicente/src/Kratos/kratos/includes/serializer.h:696:5: warning: 'Kratos::Serializer::save' hides overloaded virtual function [-Woverloaded-virtual]
    KRATOS_SERIALIZATION_DIRECT_SAVE(long long)
    ^
/home/vicente/src/Kratos/kratos/includes/serializer.h:58:10: note: expanded from macro 'KRATOS_SERIALIZATION_DIRECT_SAVE'
    void save(std::string const & rTag, type const & rValue)         \
         ^
/home/vicente/src/Kratos/kratos/containers/flags.h:434:18: note: hidden overloaded virtual function 'Kratos::Flags::save' declared here: different number
      of parameters (1 vs 2)
    virtual void save(Serializer& rSerializer) const;
~~~

### PR DESCRIPTION
**Pull request by jcotela**
@loumalouomega this makes the warnings you reported in #3876 go away for me. Can you give it a try?

Fixes #3876

### CODE REVIEW

**Review by loumalouomega — DISMISSED** [review]
Yep, it works

**Review by RiccardoRossi — COMMENTED** [review]
@jcotela this is indeed an interesting solution, however i am not clear on what is the expected behaviour.
the serializer is not saving itself...so i think this function is never used. @pooyan-dadvand or @roigcarlo what do you think?

**Comment by jcotela** [comment]
@RiccardoRossi note that these functions did not exist until you added serialization for flags in #3461, so I'd say that the serializer was not expected (up to now, at least) to be able to serialize itself. I believe that, if we ever need this feature, we could still implement proper public `Serializer::save(Serializer& rSerializer)` and `Serializer::load(Serializer& rSerializer)` methods with the correct signatures.

**Comment by RiccardoRossi** [comment]
Actually what we could do is to implement the Serializer::load/save and throw an error in there saying it is not possible.
that should get us rid of the warning and give the correct message if one attempts to.
what do you think?

**Comment by jcotela** [comment]
If we are not going to provide this feature, I believe it would be better for it to be a compilation error rather than a runtime error, but as you prefer.

**Comment by RiccardoRossi** [comment]
@jcotela i don't get you. A compilation error would be better, however how do we achieve it?

**Comment by jcotela** [comment]
You cannot call Serializer::Save(Serialier&) now because it is private. If you implement the function in the expected place (so public) and make it throw an error, people will be able to use it from other functions, but it will fail at runtime.

Maybe I am misunderstanding you, but this is what I had in mind with my comment.

**Comment by RiccardoRossi** [comment]
then let's implement it empty, as private and throw an error in there... i would say it is better that having a not working implementation with the only aim of silencing warnings.

or...maybe it is me not understanding you :-D

**Comment by jcotela** [comment]
Unless I am misunderstanding the `using` keyword, this PR should be making the public `Flags::Save` and `Flags::Load` private for `Serializer` (and any classes deriving from it). If desired, you could still call the methods from within `Serializer` itself and it would call those in the base class, I am just removing them from the public interface of `Serializer`.

**Comment by jcotela** [comment]
@RiccardoRossi I have implemented an alternative fix based on composition (serializer no longer derives from flags) as suggested by @pooyan-dadvand. The thing compiles fine, but I am not sure how to check if I broke anything (looks like serializer flags were only used in MPI?). Could you take a look?

**Review by RiccardoRossi — DISMISSED** [review]

**Review by philbucher — APPROVED** [review]
reapproving after fixing merge-conflict

**Pull request merged**
