### PR TITLE
[PFEMFluid] Reduction parameter must be value

### PR DESCRIPTION
**Pull request by jginternational**
**Description**
Parameters in reduction must be value, not referenced
https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-2/compiler-error-c3030?view=msvc-160

image

**Changelog**
double &NormP is now double NormP in:
- applications\PfemFluidDynamicsApplication\custom_strategies\strategies\two_step_v_p_strategy.h
- applications\PfemFluidDynamicsApplication\custom_strategies\strategies\v_p_strategy.h

### CODE REVIEW

**Comment by AFranci** [comment]
thanks!

**Review by AFranci — DISMISSED** [review]

**Comment by philbucher** [comment]
I would say this is wrong
I guess the reference was there for a reason
I would use a local var for the reduction and then assign it afterwards to the referenced variable

**Comment by jginternational** [comment]
You are right @philbucher 

@AFranci i just needed it in order to build, and pass the tests of the interface

**Review by AFranci — APPROVED** [review]
I cannot check it, I trust you

**Pull request merged**
