### PR TITLE
[Core] Add compatibility to python 3.5 time_based_ascii_file_writer_utility.py

### LINKED ISSUE #7833: [Fluid] Error in tests because of time_based_ascii_file_writer_utility
**Description**
`FluidDynamicsApplication` tests are failing because of the `time_based_ascii_file_writer_utility.py`. I guess it is related to #7805 .

The error says `invalid file: PosixPath("xxxxxxxxxx")`

**Scope**
- `FluidDynamicsApplication` tests

**To Reproduce**
Run all the tests in the application and the error will pop up.

**Expected behavior**
I think it doesn't manage to open the check files.

**Environment**
Please specify your operating system, kratos branch, python version or any other library versions that you consider relevant.
E.g.:
- OS: Ubuntu 16.10
- Branch: master
- Python 3.5.1

### PR DESCRIPTION
**Pull request by marcnunezc**
**Description**
Possible solution to #7833 

Taken from: https://stackoverflow.com/questions/42694112/when-using-pathlib-getting-error-typeerror-invalid-file-posixpathexample-t
- Converting to string path object before open()

closes #7833

### CODE REVIEW

**Comment by marcnunezc** [comment]
Can you check if this solves your issue @rubenzorrilla ?

**Comment by philbucher** [comment]
Now I remember having similar issues
Lets hope that it works now :)
Thx @marcnunezc

**Comment by rubenzorrilla** [comment]
> Can you check if this solves your issue @rubenzorrilla ?

Sure. Let me check.

**Comment by rubenzorrilla** [comment]
Now it works! I'm addressing the convection-diffusion related one in another PR. There were other issues in the solvers wrapper that I'll correct together with this one.

**Review by rubenzorrilla — APPROVED** [review]

**Pull request merged**
