### PR TITLE
[CoSim] port MPM-FEM coupling

### PR DESCRIPTION
**Pull request by philbucher**
This is an initial draft of porting the FEM-MPM-coupling from the EmpireApplication to the CoSimApp

@bodhinandach I did the things I told you, can you please complete it and test it? The following things are not ready yet:
- CoSim-Projectparams: Please have a look, I did it based on one of your examples (also the velocity transfer is missing)
- The particle-SolverWrapper is not ready I think, you need to do some extra things in there right?
- The operation to calculate the normal should be ready, but I am not sure since I couldn't test it (unfortunately I have not yet implemented a testing workflow for those things)

Please let me know once you have an example set up then I can also test it

FYI @jginternational @VeronikaSinger @antonialarese 

part of #5140

### CODE REVIEW

**Comment by bodhinandach** [comment]
@philbucher I added a simple static hyperelastic beam test of MPM-FEM coupling to the nightly build as it is not so heavy. Here is the image:
Screenshot from 2019-07-12 11-50-39
The analytical solution to this problem is at y=−0.67806m, which is adequately close to the obtained solution. Now, this branch is ready for a review.

**Comment by philbucher** [comment]
@bodhinandach nice work!
Some comments:
- I don't fully understand your test-case, is it the same you had before? I.e. the mpm falling on the structure? Could you please post a video with both domains, I am curious
- The test is only one TS right?
- The test seems to be quite large in terms of number of nodes/elements. At least the structure I am quite sure can be reduced.
- With this test in the nightly queue we will exceed the time limit in the nightly build. Once you have reduced the size of your test I will move one of the FSI tests to the validation suite such that MPM can be in the nightly

**Comment by bodhinandach** [comment]
@philbucher my answer:
* it is a static case of a hyperelastic cantilever beam with fix support at its left-end. Half of the beam is FEM, and the other half is MPM particles. In the middle, the coupling of displacement and forces are done. As it is static, there is no video. I choose this example as I can measure it analytically and it is not so heavy.

ok
* I am not sure what does TS mean...

TimeStep
* This only run static. So should I reduce the size still?

Yes it takes ~10 sec on my machine (i.e. ~300 in the nightly build). In general, tests should be as small as possible => your mesh is quite fine, just make it a bit coarser (also then the mdpa-files will be smaller)
In the fsi-tests the fluid is very coarse, otherwise we could never use it in a test

**Comment by philbucher** [comment]
@bodhinandach I just saw that I by accident made the answers inline, sorry ...

**Comment by bodhinandach** [comment]
@philbucher Okay will reduce the size.

**Comment by bodhinandach** [comment]
@philbucher sorry for taking some time, I found a minor bug in MPM and fixed those. Now the small test is working. Could you check? I guess there is a conflict also with your recent merge.

**Comment by bodhinandach** [comment]
I solve the conflict, but this still has a problem with your newly implemented function: `_AllocateHistoricalVariablesFromCouplingData()` as in MPM, the `MPM_Coupling_Interface` ModelPart is created after the other model parts are created in Initialized.

**Comment by philbucher** [comment]
> I solve the conflict, but this still has a problem with your newly implemented function: `_AllocateHistoricalVariablesFromCouplingData()` as in MPM, the `MPM_Coupling_Interface` ModelPart is created after the other model parts are created in Initialized.

@bodhinandach let me think abt this, I will push the solution then

**Comment by philbucher** [comment]
@bodhinandach I will discuss the proper solution with @adityaghantasala in the next days.
If you want you can go ahead and merge (I cannot approve since I opened this PR), now everything from your side is ok

if you want to get it running, then for now just [comment those lines](https://github.com/KratosMultiphysics/Kratos/blob/master/applications/CoSimulationApplication/python_scripts/base_classes/co_simulation_solver_wrapper.py#L134-L140). This is only a sanity check, I will see how to proceed here

Thanks for the good work! :+1:

**Review by bodhinandach — APPROVED** [review]
@philbucher Okay, let's merge this one first, as such that the test can be run while the new implementations are added. Thanks a lot for your help too!

**Comment by philbucher** [comment]
:tada:

**Pull request merged**
