### PR TITLE
[Fldyn] remove enrichment in almost full/empty two fluid element

### PR DESCRIPTION
**Pull request by ddiezrod**
After latest changes in math utils, we have found that when an element is cut by the interface very close to a node, diagonal enrichment matrix is almost singular and math utils throws an error.

Solution proposed here is not to apply the enrichment for such elements. If you find this ok, I will apply this same change to the other two fluids elements.

PD: sorry for the "chosmetic" changes, I can remove them if you prefer so.

### CODE REVIEW

**Comment by RiccardoRossi** [comment]
@ddiezrod i don't think you can do this if the viscosity is low... can you test it with a very slowly climbing free surface?

@swenczowski you tested this carefully, could u take a look?

**Comment by ddiezrod** [comment]
@swenczowski @RiccardoRossi Well, actually we were never able to simulate such process, if we try to simulate a filling with a plane free surface that rises slowly, free surface becomes unstable (kind of boiling) unless we use a very small time step. We never found a solution for that, do you have any idea?

**Comment by RiccardoRossi** [comment]
@swenczowski has been trying this and the instabilities were caused by the modifications we were applying when one of the two areas was getting small. He hence put a very small tolerance to the corrections. Am i right simon?

**Comment by swenczowski** [comment]
@RiccardoRossi @ddiezrod, I am sorry that I do not have any experience with the `TwoFluidVMS` element. However, we made a series of tests on the `TwoFluidNavierStokes` element. The mentioned problems of singular enrichment matrices and of an unstable "boiling" surface were also observed in this context. The `TwoFluidNavierStokes` element offers a mechanism that - if I understand correctly - does something similar to what is suggested here. The  activation was discussed with @rubenzorrilla in

https://github.com/KratosMultiphysics/Kratos/pull/3386/commits/1ae8320d855c6a3b652117ffabaf11e9ade2fca1#r234160190

EDIT: For me, the conversation is no longer visible, I am quoting:

> The value resulted from a series of numerical experiments. The set-up was chosen such that the water surface coincided with element boundaries. The following parameters were considered:

> spurious velocities
> mass conservation
> convergence (never turned out to be an issue in these experiments)

> Higher values of the parameter turned out to cause mass losses and spurious velocities at the same time. Lowering the parameter value decreased the mass losses steadily. From these aspects, it would make sense, to allow even the smallest subdivisions of elements.
On the other hand, for an infinitively small subdivision, we find p = p_h and p_enr = 0. If p_h and u_h already satisfy res_enr = 0 (such as e.g. in a hydrostatic case), then the matrix K_enr (is equal to ( d res_enr / d p_enr ) ) is approximately a zero-matrix. The inversion of such a matrix causes problems or at least inexactness in the static condensation. For such a case, the algorithm provides a solution, that is applied of the "min_area_ratio" is not reached.

> For the given reasons, I would suggest to choose a small value that, however, is not zero.


I think this is what @RiccardoRossi refers to.

**Comment by RiccardoRossi** [comment]
@swenczowski is there any posssibility that you verify if this modification still works correctly with your examples? if so, please approve

**Comment by rubenzorrilla** [comment]
@RiccardoRossi this modification do not involve @swenczowski examples (they test the `two_fluid_navier_stokes`element).

**Review by RiccardoRossi — DISMISSED** [review]

**Comment by ddiezrod** [comment]
@swenczowski If you can check it, I can do the corresponing change in the TwoFluidNavierStokes as well. in this branch. Or if the test is somewhere in the FluidDynamics app I can check it myself..

**Comment by swenczowski** [comment]
@ddiezrod At the moment, the test configuration is not on GitHub. If you could transfer the modification to the TwoFluidNavierStokes element, I will give it a try.

**Comment by ddiezrod** [comment]
@swenczowski I applied same changes to the TwoFluidNavierStokes, could you check if everything is working fine with the change?

**Comment by pablobecker** [comment]
can you also add it to the stokes element?

**Comment by ddiezrod** [comment]
@pablobecker if @swenczowski confirms that tests pass for NavierStokes I will upload the same changes to stokes element

**Comment by swenczowski** [comment]
I will recompile with the changes as soon as possible.

**Comment by RiccardoRossi** [comment]
ping @swenczowski (wow, it feels so good to ping someone else instead of being pinged :-D)

**Comment by swenczowski** [comment]
Sorry for the missing feedback here on GitHub - the conversation was continued in an e-mail exchange with @ddiezrod. 

For my test case, the weir, the suggested approach works fine and keeps also the slowly moving surface smooth.

The benchmark case with the filling column was forwarded to @ddiezrod who wanted to test further aspects of the implementation.

**Comment by ddiezrod** [comment]
@RiccardoRossi @swenczowski I found an error in min_area_ratio! @swenczowski fixed it some time ago, but did not change in the template file so I reintroduced it again in a previous PR. I will try the test now using min_area_ratio = 1e-7

**Comment by swenczowski** [comment]
Thank you, I just wanted to remark this deviation. Just came across some notes I made from the tests:

- Plot of the divergence field: No considerable differences
- Water surface with slight motion: No considerable differences
- However I remarked one thing (and just tested again): If the "distance_threshold" of the DistanceModificationProcess is set to very low values, at times a warning appears saying: "Error:  Condition number of the matrix is too high!"

This should be fixed by the latest change.

**Comment by ddiezrod** [comment]
Hi @swenczowski, , I ran your test and for both cases (after and before changes here) solution explodes after a certain time. This happens after inlet velocity is switched back to zero again. The problem is that after this  point, you find recirculation in the outlet, where some parts of it become an inlet and solution crashes. I would say it has nothing to do with present changes.

**Comment by swenczowski** [comment]
Just to be able to follow your procedure:
As I understand, you start the filling process of the column. After a while, you stop it and allow the water surface to come to a rest. This is what I did in the following example (using your implementation). A series of screenshots is attached where no comparable problem appears - I am probably considering the wrong case. 

One thing I observed is that problems occur once the surface gets to close to a pressure boundary condition. Thus, I stopped the filling in the middle of the column height and used a freeboard for the torrent simulations.

Initial condition: Water remains at rest for 0.5 s of simulated time.
Bildschirmfoto vom 2019-03-20 11-42-15

Filling process: For several seconds, water enters the domain with considerable velocity.
Bildschirmfoto vom 2019-03-20 11-42-32

End of filling process: Water surface smoothes.
Bildschirmfoto vom 2019-03-20 11-42-47

Waiting for 9 more seconds: Water surface becomes flat and no disturbances can be observed.
Bildschirmfoto vom 2019-03-20 11-43-13

A look at the velocity field shows that also inflow over the boundary takes place in this case.

**Comment by ddiezrod** [comment]
hmm maybe I missed something, @swenczowski could you please point to me which exact version of kratos were you using for running that test?

**Comment by swenczowski** [comment]
According to the header, `Multi-Physics 7.0.0-eebc6f3` is used. 
(My apologies for accidently closing the PR)

EDIT: While lowering the filling velocity, I could now observe a first crash with the message `terminate called after throwing an instance of 'Kratos::Exception'
  what():  Error:  Condition number of the matrix is too high!, cond_number = 1.21468e+12
`

**Comment by ddiezrod** [comment]
@swenczowski , I could not find that commit, can you please show me the output of `git show`?

**Comment by swenczowski** [comment]
The command "git show" returns the following:

commit eebc6f310674fd7cad646e807ab7c34fe4deac81
Author: Daniel Diez <ddiez@europe.altair.com>
Date:   Tue Mar 12 16:36:13 2019 +0100

    applying changes to element and reconciling template and element

diff --git a/applications/FluidDynamicsApplication/custom_elements/two_fluid_navier_stokes.cpp b/applications/FluidDynamicsApplication/custom_elements/two_fluid_navier_stokes.cpp
index 8c2daf4..c28578b 100644
--- a/applications/FluidDynamicsApplication/custom_elements/two_fluid_navier_stokes.cpp
+++ b/applications/FluidDynamicsApplication/custom_elements/two_fluid_navier_stokes.cpp

**Comment by ddiezrod** [comment]
@swenczowski I ran the test with the same branch as you (eebc6f3) and solution crashes even if I remove the condition number check to invert the matrix.

**Comment by swenczowski** [comment]
Ok, I will checkout this branch once again, recompile and run the case once again to make sure that there is no influence of any local implementation.

At the moment I cannot understand where the different behaviour results from.

**Comment by ddiezrod** [comment]
After discussing this with @swenczowski we found that the problem was in the CALCULATE_EXACT_DISTANCES flag, without it, it works fine. I will check it later but problem is not related to this PR.

**Comment by ddiezrod** [comment]
@swenczowski can you approve this then?

**Comment by swenczowski** [comment]
@ddiezrod I am sorry but I am not assigned as a reviewer. Also, I am not confident enough to decide in this case. All I can say is that the suggested implementation does not seem to show drawbacks compared to the current code. Personally, I did not experience the described problems that motivated this change and cannot state whether it is an improvement for the two-fluid element.

@jcotela @RiccardoRossi @pablobecker, I am forwarding the question to you as the assigned reviewers.

**Comment by RiccardoRossi** [comment]
i have no problems with accepting this. my only concern was about Simon's
opinion, however if he is fine with the change please go ahead

Riccardo

**Comment by ddiezrod** [comment]
then can you approve it @RiccardoRossi ?

**Review by RiccardoRossi — APPROVED** [review]

**Comment by philbucher** [comment]
do you still need the branch @ddiezrod ?

**Comment by ddiezrod** [comment]
@philbucher Nop, sorry I forgot to delete it

**Pull request merged**
