### PR TITLE
[Core] This messages should be removed, as all of the PR has been merged already

### PR DESCRIPTION
**Pull request by loumalouomega**
**Description**
This messages should be removed, as all of the PR has been merged already

**Changelog**
- Remove old legacy messages

### CODE REVIEW

**Comment by rubenzorrilla** [comment]
I though the same but maybe makes sense to leave them in there for a while.

**Comment by loumalouomega** [comment]
> I though the same but maybe makes sense to leave them in there for a while.

Maybe some, but, all of them?, some are almost 2 years old

**Comment by rubenzorrilla** [comment]
> > I though the same but maybe makes sense to leave them in there for a while.
> 
> Maybe some, but, all of them?, some are almost 2 years old

That's true... Indeed, I'd keep only the scheme API one only.

**Comment by philbucher** [comment]
how about we clean this every time we had a release?
I.e. the release branch still has the messages, and we clean them right after the release was made?

**Comment by loumalouomega** [comment]
Approval?

**Comment by rubenzorrilla** [comment]
In this I tend to agree @philbucher , I'd leave it as it is until the next release.

**Comment by loumalouomega** [comment]
Should this be updated for the release? @roigcarlo

**Review by rubenzorrilla — APPROVED** [review]
I also think now is time to remove the super old ones.

**Pull request merged**
