### PR TITLE
DEM and SDEM: aliasing matrices and vectors for porting to AMatrix

### PR DESCRIPTION
**Pull request by maceligueta**
Title says it all.
I did not change the stuff related to inverting matrices or computing the determinant, because @pooyan-dadvand told me to wait for a later stage for doing this change (AMatrix not fully ready for it).

### CODE REVIEW

**Comment by maceligueta** [comment]
Please @salvalatorre can you test the swimming DEM with this branch?
If nothing is broken, please someone approve.

**Comment by maceligueta** [comment]
@salvalatorre , you told me in person that there's a problem with the solution of the fluid. Could you find what is the source of the issue? I understood that the problem is in the master branch already.

**Comment by salvalatorre** [comment]
Roger that!

**Comment by maceligueta** [comment]
Just for the record, the problematic PR is #1864

**Review by salvalatorre — APPROVED** [review]
OK!

**Pull request merged**
