### PR TITLE
[RANS] Using ParallelLevelSetDistanceCalculator in Bodyfitted Domain DISTANCE Calculation

### PR DESCRIPTION
**Pull request by sunethwarna**
**Description**
This PR replaces `DISTANCE` calculation done using `VariationalDistanceCalculationProcess` to `ParallelLevelSetDistanceCalculator`. Tested with OpenMP and MPI as well.

**Changelog**
- Changed `DISTANCE` calculation method for bodyfitted domains in RANS

Change of test references are due to change in DISTANCE calculation method. The results were again validated against benchmark cases.

### CODE REVIEW

**Comment by philbucher** [comment]
@rubenzorrilla @adityaghantasala you know this part better than I do :)

**Comment by adityaghantasala** [comment]
I discussed with @sunethwarna  for some minor changes.

**Comment by sunethwarna** [comment]
@adityaghantasala could you have a look at this when you have time? I applied your suggestions :)

**Review by adityaghantasala — DISMISSED** [review]
All fine now. Thank you Suneth

**Review by adityaghantasala — APPROVED** [review]

**Pull request merged**
