### PR TITLE
[Core][AnalysisStage] make time of processes-initialization deterministic

### PR DESCRIPTION
**Pull request by philbucher**
This PR makes the time the processes are created deterministic
This is necessary bcs the processes can only be created after the ModelParts are read.

The reason is that since the model is passed to the constructor of the Processes, the modelpart is then extracted from the modelpart already in the constructor, such that the process does not have to save the Model AND the ModelPart. E.h. [here](https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/python_scripts/assign_scalar_variable_process.py#L45)

I discussed this already with @jcotela but please feel free to also discuss it in the @KratosMultiphysics/technical-committee

### CODE REVIEW

**Review by RiccardoRossi — COMMENTED** [review]
on my side i am ok with this

**Comment by philbucher** [comment]
ping @KratosMultiphysics/technical-committee

**Comment by philbucher** [comment]
ping @KratosMultiphysics/technical-committee

**Comment by pooyan-dadvand** [comment]
We could not make a committee meeting last week... hope to have it this week

**Comment by pooyan-dadvand** [comment]
@KratosMultiphysics/technical-committee needs more feedback from other developers.
@rubenzorrilla @loumalouomega @adityaghantasala @msandre and others would you please give your opinion on this?

**Review by loumalouomega — DISMISSED** [review]
For me is OK

**Comment by philbucher** [comment]
thanks for addressing this in the committee!
Whoever checks this please take into consideration my first comment I wrote

**Comment by philbucher** [comment]
ping @msandre @adityaghantasala @rubenzorrilla

**Comment by msandre** [comment]
Ok for me too :+1:

**Comment by rubenzorrilla** [comment]
OK for me as well.

**Comment by philbucher** [comment]
can we merge this then?

**Review by msandre — APPROVED** [review]
I think everyone is ok with it so approving.

**Pull request merged**
