### PR TITLE
Revert "Feature add work equiv lineload3D "

### PR DESCRIPTION
**Pull request by KlausBSautter**
Reverts KratosMultiphysics/Kratos#880

With respect to #915 we revert these changes and will take care about it after the next release.

### CODE REVIEW

**Review by RiccardoRossi — COMMENTED** [review]
wouldn't it make sense to keep the tests? i guess they should work also with the old implementation

**Comment by KlausBSautter** [comment]
Not the new tests I added as they consider work equivalent nodal moments in the force equilibirum

**Review by RiccardoRossi — APPROVED** [review]
+1 for me, however it would be best if @loumalouomega gives green light

**Comment by pooyan-dadvand** [comment]
Does this affect inclusion of the beam and truss?

**Comment by philbucher** [comment]
No, it has nothing to do with the beam or truss

Only affects the load condition, thats why everything is solved with merging this PR

**Comment by loumalouomega** [comment]
Green light

**Pull request merged**
