### PR TITLE
[Fluid][Core][Fast PR] move TEMPERATURE_GRADIENT to core

### PR DESCRIPTION
**Pull request by pablobecker**
**Description**
@rubenzorrilla  we were having issues with the variable TEMPERATURE_GRADIENT when it was added in multiple applications (we need it also in our apps ). It was crashing in runtime.
with @pooyan-dadvand @ddiezrod we tried to find the reason why it fails but could not identify it yet.

Please mark the PR with appropriate tags: 
- Fluid, Core.

**Changelog**
Moves the TEMPERATURE_GRADIENT variable from the fluid app to the core

### CODE REVIEW

**Comment by philbucher** [comment]
ok for me
IMO this should have a high prio for being solved properly

**Comment by pablobecker** [comment]
> ok for me
> IMO this should have a high prio for being solved properly

yes, fully agree. This looks like something that failed here but could've been in any other variable. I did not want to "fix" things this way but our altair repo was getting too outdated, so i went for this while we find the root cause. 
Please discuss it in the technical comitee, Pooyan ran this with valgrind , perhaps you can find the cause with some brainstorming

**Comment by roigcarlo** [comment]
In any case I think we can approve the change in the meantime (I moved this issue to the next meeting to do anyway)

**Review by rubenzorrilla — APPROVED** [review]
OK as a temporary solution. But please note that we are just hiding the problem. This may occur with any other variable. As @philbucher and @roigcarlo said this is main priority now.

**Comment by pablobecker** [comment]
fully agree, we have to find the root cause

**Pull request merged**
