### PR TITLE
missing include

### PR DESCRIPTION
**Pull request by roigcarlo**
**Description**
Missing include.

### CODE REVIEW

**Review by philbucher — APPROVED** [review]
I also get this error
thx for fixing

**Comment by marandra** [comment]
Thanks! It is from a PR merged yesterday, i just saw the compilation error. Do you know how could it pass the compilation in the CI?

**Comment by roigcarlo** [comment]
Yep, its because unity merges together all the cpp, so if some needs a header that is missing it can "take"  it from another file so to say.

**Comment by marandra** [comment]
I see. That's why in my local machine it compiled normally (unity, clang 11, ninja) , but in the cluster it failed (gcc, make).
But we have compilation without unity in the CI, right?

**Comment by philbucher** [comment]
> But we have compilation without unity in the CI, right?

we do but since it takes waaaaaaaaaaaaaaaaaaaaaaaay longer basically only the core is compiled

**Comment by marandra** [comment]
So we should be aware that using unity can potentially introduce bugs. I think this is an issue to take into account. Maybe require normal compilation for PR, or something like that?

**Comment by marandra** [comment]
Or it is not as serious as I imagine?

**Comment by roigcarlo** [comment]
Well in fact we have one for the core, but not for the apps, as @philbucher says is unrealistically long to compile without unity (we are speaking of 10x to 20x times slower). Anyway that only applies to CI builds, in local machines there is no good reason to use unity build.

**Comment by philbucher** [comment]
Yes it is serious
For more complex things I myself compile and test with and without unity (locally)

As I said the Core is also checked without unity (since recently only), but having the apps compiled without unity is not possible bcs it just takes way too long (several times longer). In theory the github CI might be able to handle it, but then our CI will take many hours and it would slow down development too much
Also I don't want to overload it too much, it is free and I don't want to give Microsoft reasons to change that

**Comment by philbucher** [comment]
@marandra why do you use unity build for development in C++?
This is much slower as you have to recompile the entire App each time you change sth

**Comment by marandra** [comment]
> @marandra why do you use unity build for development in C++?
> This is much slower as you have to recompile the entire App each time you change sth

Well, I hadn't a clear idea of its scope until now. I was testing it and I liked the speedup of the first compilation, but as you said, then it's infuriatingly slow for development.

Anyways, now I know better. Thanks @roigcarlo and @philbucher for the explanations.

**Pull request merged**
