### PR TITLE
[Core] Adding CheckDefaults and RecursivelyCheckDefaults

### PR DESCRIPTION
**Pull request by loumalouomega**
This can be used in order to check before ValidateAndAssign, avoiding the error thrown. This returns true if everything is OK and false otherwise

### CODE REVIEW

**Comment by pooyan-dadvand** [comment]
What would be the purpose/use case of this new feature? @KratosMultiphysics/technical-committee we think that just having the true/false return does not give enough info to do something with it.

**Comment by loumalouomega** [comment]
> What would be the purpose/use case of this new feature? @KratosMultiphysics/technical-committee we think that just having the true/false return does not give enough info to do something with it.

What else do you suggest?, an enum to identify the different options?

**Comment by loumalouomega** [comment]
Any suggestion apart from the enun?

**Comment by roigcarlo** [comment]
Is this feature still needed? 

What would be the usecase then?

**Comment by loumalouomega** [comment]
> Is this feature still needed?
> 
> What would be the usecase then?

This can be used in order to check before ValidateAndAssign, avoiding the error thrown. This returns true if everything is OK and false otherwise

**Comment by rubenzorrilla** [comment]
> > Is this feature still needed?
> > What would be the usecase then?
> 
> This can be used in order to check before ValidateAndAssign, avoiding the error thrown. This returns true if everything is OK and false otherwise

But if it returns `false` it means that what you are passing is not valid, meaning that the `ValidateAndAssign` will throw the error afterwards. Am I wrong?

**Comment by loumalouomega** [comment]
> > > Is this feature still needed?
> > > What would be the usecase then?
> > 
> > 
> > This can be used in order to check before ValidateAndAssign, avoiding the error thrown. This returns true if everything is OK and false otherwise
> 
> But if it returns `false` it means that what you are passing is not valid, meaning that the `ValidateAndAssign` will throw the error afterwards. Am I wrong?

If you get a false, you can act in consequence and do something to avoid the error

**Comment by philbucher** [comment]
So basically you want to bypass the validate-fct?

**Comment by loumalouomega** [comment]
> So basically you want to bypass the validate-fct?

No, I want to do an initial check, and then after solve the issues check (right now is extremely aggressive)

**Comment by philbucher** [comment]
> If you get a false, you can act in consequence and do something to avoid the error

but what would you do?
The function does not give you any info except that your parameters have things the defaults don't have

**Comment by loumalouomega** [comment]
> > If you get a false, you can act in consequence and do something to avoid the error
> 
> but what would you do?
> The function does not give you any info except that your parameters have things the defaults don't have

Do you suggest to return a list of parameters missing or defined and should not being defined?, that would be cool

**Comment by rubenzorrilla** [comment]
> > > If you get a false, you can act in consequence and do something to avoid the error
> > 
> > 
> > but what would you do?
> > The function does not give you any info except that your parameters have things the defaults don't have
> 
> Do you suggest to return a list of parameters missing or defined and should not being defined?, that would be cool

Kind of. Actually this is what we discussed in the @KratosMultiphysics/technical-committee

**Comment by loumalouomega** [comment]
> > > > If you get a false, you can act in consequence and do something to avoid the error
> > > 
> > > 
> > > but what would you do?
> > > The function does not give you any info except that your parameters have things the defaults don't have
> > 
> > 
> > Do you suggest to return a list of parameters missing or defined and should not being defined?, that would be cool
> 
> Kind of. Actually this is what we discussed in the @KratosMultiphysics/technical-committee

OK, I will see

**Pull request closed without merging**
