### PR TITLE
removing ExternalSolversApp from CI

### PR DESCRIPTION
**Pull request by philbucher**
**Description**
Now that the ExternalSolversApplication is officially deprecated, I want to remove it from the CI to see if it is still used

TODO after this is merged: remove blas & lapack from docker

### CODE REVIEW

**Comment by philbucher** [comment]
seems like it is no longer used :)

**Comment by philbucher** [comment]
checking also nightly build here: https://github.com/KratosMultiphysics/Kratos/actions/runs/537921412

**Comment by philbucher** [comment]
nightly build also works, then I would say that this should go in

**Review by roigcarlo — APPROVED** [review]
:tada:

**Pull request merged**
