### PR TITLE
[IntervalUtility] Time comparison

### PR DESCRIPTION
**Pull request by miguelmaso**
**📝 Description**
This fixes a test in #10238 (`testInitialTime`). I haven't pushed directly to #10238 because this should be discussed in another PR.

If this PR is rejected, a better solution for applying initial conditions should be found (see #7544)

**🆕 Changelog**
- Update `double` comparison

### CODE REVIEW

**Review by loumalouomega — DISMISSED** [review]
Okay from my side. TODO: move this piece of code to cpp

**Comment by miguelmaso** [comment]
@loumalouomega , the float comparison is fixed and a test is added. Ready for review

**Review by loumalouomega — APPROVED** [review]
Okay, thanks

**Comment by matekelemen** [comment]
I've updated ```IntervalUtility``` in [this branch](https://github.com/KratosMultiphysics/Kratos/tree/core/interval-utility-2) but I couldn't open a PR for it yet because it relies on #10052, which has been stuck in *core PR review limbo* for ages. That branch fixes this issue, as well as adds the possibility to use it with integers.

I'd appreciate it if I didn't have to completely rewrite the stuff I've done, but I'm open to suggestions.

**Comment by miguelmaso** [comment]
Thanks @matekelemen , your [branch](https://github.com/KratosMultiphysics/Kratos/tree/core/interval-utility-2) is very nice.

The aim of this PR is to fix a float comparison, which produces wrong results in non-zero initial times.

What do you prefer, merge this PR or close it and wait for #10052 and [branch](https://github.com/KratosMultiphysics/Kratos/tree/core/interval-utility-2)?

**Comment by matekelemen** [comment]
@miguelmaso well, if another PR depends on this one, I won't hold you back; who knows when mine will get reviewed.

**Comment by miguelmaso** [comment]
@matekelemen sorry for the delay

#10238 depends on this, but is closed. So, this can also be closed

If possible, add a test like this (if I'm not wrong, it fails with the current master)
```py
    def test_LargeBoundaries(self) -> None:
        for begin, end in ((0.0, 1000.0), (1000.0, 1000.0)):
```
or even, with larger values...

**Comment by miguelmaso** [comment]
To avoid messing up this [branch](https://github.com/KratosMultiphysics/Kratos/tree/core/interval-utility-2)

**Pull request closed without merging**
