### PR TITLE
[CI] add FullDebug Build

### PR DESCRIPTION
**Pull request by philbucher**

### CODE REVIEW

**Comment by philbucher** [comment]
wow this was almost too easy :stars: 

Once this is in I would do some cleanup related to setting of env-variables
Two more things:
- Now we also have a nightly build with FullDebug, probably not what we want, since it can take a lot of time, and then we can exceed the 6hr limit
- we might think of increasing the time limit in `run_tests.py` for a FullDebug build

**Comment by oberbichler** [comment]
As discussed today we should check if we can reproduce the current segfault bug local with the Kratos image.

**Review by oberbichler — APPROVED** [review]

**Comment by armingeiser** [comment]
:+1:

If we have such a "Release" after each push to master, i think we need to also add the testing. I think the pipeline should be `build - test - deploy`. 
It happens from time to time that 2 concurrent PRs are merged in a small time frame and then they break build/tests on master.

An option to reduce traffic would be to do this on a daily basis (nightly) because there are often many PRs merged on a single day.

**Comment by philbucher** [comment]
> It happens from time to time that 2 concurrent PRs are merged in a small time frame and then they break build/tests on master.

I think this can be solved with the settings that PRs have to be up-to-date with master in order to be merged
I.e. if one PR is merged then the next one first has to merge Master (which would break in your example)

**Comment by armingeiser** [comment]
To be honest i do not think that is realistic given that ther are several PRs merged every day... that would mean even after approval it would be necessary to merge master again, reapprove, wait for CI and merge quickly - if another one is faster - repeat...

Or do i get this wrong?

**Comment by philbucher** [comment]
Guess that’s the reason it is not activated 
Btw no reapproval is necessary if you only merge master

Personally I don’t think it is a problem, breaking sth in this way rarely happens
And if it does we know very soon and can fix it

**Comment by armingeiser** [comment]
Sorry i just see i commented in the wrong thread. My points where meant for #6349

**Pull request merged**
