### PR TITLE
add process to fix variables without modifying the values

### PR DESCRIPTION
**Pull request by armingeiser**

### CODE REVIEW

**Comment by loumalouomega** [comment]
Can you add the processes for vector variables as well?

**Comment by armingeiser** [comment]
There is one for vectors and one for scalars (the vector process internally calls the scalar process, as its done for the "assign" processes).

**Comment by loumalouomega** [comment]
Sorry I look so fast

**Review by loumalouomega — APPROVED** [review]
Ok

**Review by philbucher — APPROVED** [review]
I am impressed, I don't have a single comment for sth new to the Core
++1, thanks for this

**Review by philbucher — APPROVED** [review]
I approve twice since the work is so good!

**Comment by loumalouomega** [comment]
@philbucher

**Review by philbucher — APPROVED** [review]

**Pull request merged**
