### PR TITLE
[Structural] optionally disable advanced claws 2

### PR DESCRIPTION
**Pull request by philbucher**
same as #5668 but started again from scratch to avoid conflicts

In #5668 agreement was acheived, by default the everything is compiled

### CODE REVIEW

**Review by loumalouomega — APPROVED** [review]
Conflicts here we go

**Comment by philbucher** [comment]
thx
Lets hope there are not many conflicts

At least there are no open PRs

**Comment by loumalouomega** [comment]
> 
> 
> thx
> Lets hope there are not many conflicts
> 
> At least there are no open PRs

Subproperties->Rule of mixtures

**Comment by philbucher** [comment]
no conflicts in subprops

**Comment by loumalouomega** [comment]
But in rule of mixtures, and a big conflict in other PR

**Pull request merged**
