### PR TITLE
Solving interface problems with pybind

### PR DESCRIPTION
**Pull request by roigcarlo**
Several fixes for the python interface.

### CODE REVIEW

**Review by maceligueta — APPROVED** [review]

**Comment by maceligueta** [comment]
I approved because thanks to these changes the DEM application works again. Thanks @roigcarlo .
Let's see if @pooyan-dadvand @jcotela  and @RiccardoRossi  don't complain.
@KlausBSautter  and @KratosMultiphysics/dem : this PR fixes the application.

**Comment by maceligueta** [comment]
By the way, @RiccardoRossi made me note that 
`modelpart.Elements.clear()`
is not a safe operation. I understand that clear() does not go accross levels of submodelparts. However, I can't find an equivalent which I can call, as all options require a certain Flag to decide wheter to erase or not to erase the Elements. Should we add this option? I would ask to do it in a separate PR, because this one is an urgent fix for the DEM application.

**Review by jcotela — APPROVED** [review]
:+1: no objections from my side.

**Comment by RiccardoRossi** [comment]
@maceligueta there is a local flag "ALL_ENTITIES" defined in the modelpart.

I THINK that the usage should be 

model_part.RemoveElementsFromAllLevels(ALL_ENTITIES)

having said this i haven't used it so far, and i am not sure of how it shoudl be done exactly, nor if the local flag is actually exported to python. @roigcarlo @pooyan-dadvand could you comment on this?

anyhow, this is NOT a blocker for the merge, simply an improvement suggestion

**Comment by roigcarlo** [comment]
I will merge, but let's keep this discussion in a issue.

**Comment by pooyan-dadvand** [comment]
If I remember correctly the `ALL_ENTITIES` is for migration in MPI and not needed to be passed to remove elements which the names says it will remove elements.

**Comment by GuillermoCasas** [comment]
Great! Thank you @roigcarlo @maceligueta

**Pull request merged**
