### PR TITLE
renaming explicit structural mechanic files

### LINKED ISSUE #1597: ExplicitStrategy defined both in the core and in the StructuralMechanicsApplication
@KlausBSautter the title says it all. 

this is actually an error... can't u use the explicit strategy in the core? If not, you'll have to rename your strategy.

HOWEVER, by far the best option would be to reuse the one in the core ... so do not rename it lightly...

### PR DESCRIPTION
**Pull request by KlausBSautter**
Closes #1597

### CODE REVIEW

**Comment by KlausBSautter** [comment]
sry I did sth wrong ...

edit: should be ok now

**Review by philbucher — APPROVED** [review]
Seems ok to me

Maybe some day one can merge it with the core

**Comment by loumalouomega** [comment]
Related with Explicit strategy of the core, it doesn't look like does nothing, any idea how is used?

**Comment by philbucher** [comment]
@loumalouomega no, see #1597

**Comment by loumalouomega** [comment]
OK

**Pull request merged**
