### PR TITLE
[Core] initial cleanup of LockObject

### PR DESCRIPTION
**Pull request by philbucher**
**Description**
As discussed in the last meeting, this is a first cleanup of the `LockObject`
I am only replacing the omp-macro and removing the unused functions, I am NOT touching the copy/move ctors => to be done separately

### CODE REVIEW

**Comment by philbucher** [comment]
@pooyan-dadvand the `Chunk` used `GetThreadNumber` and `GetNumberOfThreads`
Esp the first one will be very hard to replace with C++11 parallelism, as @RiccardoRossi and I already explained

I noticed thought that `Chunk` and the `MemoryPools` are not used anywhere (except some tests), maybe they can be removed?

**Comment by philbucher** [comment]
alternatively we could also use the `OpenMPUtils` for the `Chunk` until we have the better solution.
At least this way we could finish the `LockObject`

**Comment by pooyan-dadvand** [comment]
I would keep the chunk as I want to turn back to it. But I agree that we might use the OpenMPUtils until I find a C++ solution for it.

**Comment by philbucher** [comment]
> I would keep the chunk as I want to turn back to it. But I agree that we might use the OpenMPUtils until I find a C++ solution for it.

done in #7600

**Comment by philbucher** [comment]
this should be ready now

**Review by pooyan-dadvand — APPROVED** [review]
:+1:

**Pull request merged**
