### PR TITLE
[CI] Adding `CoSimulationApplication` to Centos CI

### PR DESCRIPTION
**Pull request by loumalouomega**
**📝 Description**

In this PR we modify the `.github/workflows/centos_configure.sh` file.

1. An additional application, `CoSimulationApplication`, was added to the configuration script for CentOS. This is accomplished with the following line:
   ```
   add_app ${KRATOS_APP_DIR}/CoSimulationApplication;
   ```

2. Some modifications were made to the cmake configuration section, basically aesthetic modifying spaces.

NOTE: A priori this will fail until modifications in CoSimIO lib is updated. 

**🆕 Changelog**

- [Adding `CoSimulationApplication` to Centos CI](https://github.com/KratosMultiphysics/Kratos/commit/5e96795819053566de94b093fa06a18082fa3bf1)

### CODE REVIEW

**Comment by loumalouomega** [comment]
@philbucher CoSimIO fails compilation in CoSimulationApplication in Centos, but not if downloaded directly?

**Review by philbucher — DISMISSED** [review]

**Comment by philbucher** [comment]
strange, it fails in the filesystem lib (which is also used by the rest of Kratos)

**Comment by loumalouomega** [comment]
> strange, it fails in the filesystem lib (which is also used by the rest of Kratos)

If you compile directly is not a problem...

**Comment by ddiezrod** [comment]
Maybe you need this? 
https://stackoverflow.com/questions/53852684/stdfilesystem-link-error-on-ubuntu-18-10
https://github.com/stefanhaustein/TerminalImageViewer/issues/103


ping @qiukailu

**Comment by loumalouomega** [comment]
> Maybe you need this? [stackoverflow.com/questions/53852684/stdfilesystem-link-error-on-ubuntu-18-10](https://stackoverflow.com/questions/53852684/stdfilesystem-link-error-on-ubuntu-18-10)
> 
> [stefanhaustein/TerminalImageViewer#103](https://github.com/stefanhaustein/TerminalImageViewer/issues/103)
> 
> ping @qiukailu

Yes a priori I already tried that and doesn't work :P

**Comment by loumalouomega** [comment]
> > Maybe you need this? [stackoverflow.com/questions/53852684/stdfilesystem-link-error-on-ubuntu-18-10](https://stackoverflow.com/questions/53852684/stdfilesystem-link-error-on-ubuntu-18-10)
> > [stefanhaustein/TerminalImageViewer#103](https://github.com/stefanhaustein/TerminalImageViewer/issues/103)
> > ping @qiukailu
> 
> Yes a priori I already tried that and doesn't work :P

Fixed, also in CoSimIO:  https://github.com/KratosMultiphysics/CoSimIO/pull/365

**Review by philbucher — APPROVED** [review]

**Comment by ddiezrod** [comment]
@qiukailu you can now merge master in your gitlab merge branch so centos will pass

**Comment by loumalouomega** [comment]
> @qiukailu you can now merge master in your gitlab merge branch so centos will pass

In or machines should pass with the previous patch which I cherry-pikced myself as we have gcc 8

**Pull request merged**
