### PR TITLE
Structural/shells get claws

### PR DESCRIPTION
**Pull request by clazaro**
**📝 Description**
Adding a test of initial strains in a Q4 thick shell element.

**🆕 Changelog**
- Added test files into `StructuralMechanicsApplication/tests/InitialStateElasticity/`
- Added the corresponding class in `structural_mechanics_test_factory.py`

I didn't add the test into `test_StructuralMechanicsApplication.py` as I wasn't sure if it has to be included into the smallSuite or the nightSuite.

### CODE REVIEW

**Comment by philbucher** [comment]
@clazaro I guess you need to merge master into your branch

**Comment by clazaro** [comment]
Thanks @philbucher, still learning. I think master is merged now...

**Comment by philbucher** [comment]
Seems like sth went wrong, now there are even more changes

It seems like instead of merging origin/master you merged  origin/structural/shells-get-claws

**Comment by clazaro** [comment]
I'm closing this PR and starting a new one from scratch...

**Pull request closed without merging**
