### PR TITLE
[Testing] Split Checks

### PR DESCRIPTION
**Pull request by roigcarlo**
**📝 Description**
This splits the check.h file into two. Expect and Check. Incode checks reamin the same, and tests assertions will use the expect interface. This change does nothing by its own and its needed for #11506 as requested by @loumalouomega.

String checks may require further changes in the GTest PR.

**🆕 Changelog**
- Split check.h in check.h and expect.h

### CODE REVIEW

**Review by loumalouomega — DISMISSED** [review]
If only these changes then Okay. But maybe should a warning be added in Cmake, otherwise many branches of developers may not compile or change behaviour

**Comment by roigcarlo** [comment]
I would add the warning in the other PR, this at most will cause a couple of tests from branches to fail, but if they keep using checks it will break nothing

**Review by loumalouomega — DISMISSED** [review]

**Review by loumalouomega — DISMISSED** [review]

**Comment by loumalouomega** [comment]
Some Ci are failing due segmentation fault

**Comment by roigcarlo** [comment]
@loumalouomega I am aware. I get mails from the CI

**Review by loumalouomega — DISMISSED** [review]

**Review by loumalouomega — APPROVED** [review]

**Pull request merged**
