### PR TITLE
Remove wind turbine application

### PR DESCRIPTION
**Pull request by jcotela**
Removing out of date application, since it is unfortunately not a priority to maintain it at the moment and it is growing increasingly out of date. I created an archival version at https://github.com/jcotela/kratos-wind-turbine-application

### CODE REVIEW

**Comment by jcotela** [comment]
By the way, this is related to #2035

**Review by roigcarlo — COMMENTED** [review]
Ok, but we probably have to delete it from the application_interface.py

**Comment by jcotela** [comment]
@roigcarlo in fact, I think we should remove the application interface. Is anyone still using it?

**Comment by roigcarlo** [comment]
I don't think so, but I don't know it for sure. Who was using this application?

**Comment by jcotela** [comment]
This one? I think the last known user was myself back in 2013. But the application interface has been "legacy" for nearly least as long as that.

**Comment by roigcarlo** [comment]
Then we can just remove it from there, but maybe we can do it in another Pr. I see many outdated apps and apps that no longer exists still inside...

**Comment by jcotela** [comment]
@roigcarlo I removed the wind_turbine_application from applications_interface.py. Still, I think we should remove applications_interface.py alltogether as soon as possible.

**Comment by roigcarlo** [comment]
:+1: Agree. But maybe is a good idea to discuss this first in the committee, not quite sure which apps are still using that

**Review by roigcarlo — APPROVED** [review]

**Comment by jcotela** [comment]
The `applications_interface` was used a long time ago by the main script to import applications, before we had the capabilities to do `from KratosMultiphysics.MyApplication import *`. The only applications still requiring it would be those that don't have an `ApplicationName.py` script inside. You can see an example of the old syntax here:
https://github.com/KratosMultiphysics/Kratos/blob/30bb367a43063a8f4c7488ecd8975fc8c688bd46/applications/metis_application/test_exemples/square_domain/square_domain.py#L25-L37

**Comment by roigcarlo** [comment]
I see. Then we can delete it :+1:

**Pull request merged**
