### PR TITLE
bugfix for lgmres - to be ported upstream?

### PR DESCRIPTION
**Pull request by RiccardoRossi**
@ddemidov i am patching kratos version of AMGCL as you propose. @ddiezrod @pooyan-dadvand give me the green light if you agree

### CODE REVIEW

**Comment by ddemidov** [comment]
We can do this upstream, but I am planning to re-port lgmres from scipy, so it should not really matter.

**Comment by RiccardoRossi** [comment]
ok i'll fix locally. @ddiezrod can u approve?

**Review by loumalouomega — APPROVED** [review]

**Comment by ddemidov** [comment]
I think I found a nicer fix for the problem, committed upstream (https://github.com/ddemidov/amgcl/commit/65c04673d3c1cbeb61950d215a675f70553b94cf). The commit removes `store_Av` option from lgmres which seems to be broken for right-preconditioning. With the fix applied, the matrices from #3066 are solved well both with left and right preconditioning (and the default right one works better, which is consistent with gmres behavior):

* LGMRES, left preconditioning:
```
./solver -A problems/kratos-3066/A_0.0128735_1.mm -f problems/kratos-3066/b_0.0128735_1.mm.rhs -p solver.{type=lgmres,pside=left,maxiter=500} precond.{relax.type=ilu0,coarsening.type=aggregation}
Solver
======
Type:             LGMRES(30,3)
Unknowns:         17304
Memory footprint: 5.03 M

Preconditioner
==============
Number of levels:    2
Operator complexity: 1.10
Grid complexity:     1.12
Memory footprint:    9.45 M

level     unknowns       nonzeros      memory
---------------------------------------------
    0        17304         217358      8.52 M (90.51%)
    1         1997          22779    955.32 K ( 9.49%)

Iterations: 141
Error:      9.32245e-09

[Profile:       1.488 s] (100.00%)
[  reading:     0.275 s] ( 18.49%)
[  setup:       0.074 s] (  4.98%)
[  solve:       1.138 s] ( 76.49%)
```
* LGMRES, right preconditioning:
```
./solver -A problems/kratos-3066/A_0.0128735_1.mm -f problems/kratos-3066/b_0.0128735_1.mm.rhs -p solver.{type=lgmres,pside=right,maxiter=500} precond.{relax.type=ilu0,coarsening.type=aggregation}
Solver
======
Type:             LGMRES(30,3)
Unknowns:         17304
Memory footprint: 5.03 M

Preconditioner
==============
Number of levels:    2
Operator complexity: 1.10
Grid complexity:     1.12
Memory footprint:    9.45 M

level     unknowns       nonzeros      memory
---------------------------------------------
    0        17304         217358      8.52 M (90.51%)
    1         1997          22779    955.32 K ( 9.49%)

Iterations: 131
Error:      9.43495e-09

[Profile:       1.379 s] (100.00%)
[  reading:     0.272 s] ( 19.73%)
[  setup:       0.026 s] (  1.91%)
[  solve:       1.080 s] ( 78.32%)
```
* GMRES, left:
```
./solver -A problems/kratos-3066/A_0.0128735_1.mm -f problems/kratos-3066/b_0.0128735_1.mm.rhs -p solver.{type=gmres,pside=left,maxiter=500} precond.{relax.type=ilu0,coarsening.type=aggregation}
Solver
======
Type:             GMRES(30)
Unknowns:         17304
Memory footprint: 4.23 M

Preconditioner
==============
Number of levels:    2
Operator complexity: 1.10
Grid complexity:     1.12
Memory footprint:    9.45 M

level     unknowns       nonzeros      memory
---------------------------------------------
    0        17304         217358      8.52 M (90.51%)
    1         1997          22779    955.32 K ( 9.49%)

Iterations: 327
Error:      9.63268e-09

[Profile:       3.022 s] (100.00%)
[  reading:     0.274 s] (  9.08%)
[  setup:       0.028 s] (  0.91%)
[  solve:       2.719 s] ( 89.99%)
```
* GMRES, right:
```
./solver -A problems/kratos-3066/A_0.0128735_1.mm -f problems/kratos-3066/b_0.0128735_1.mm.rhs -p solver.{type=gmres,pside=right,maxiter=500} precond.{relax.type=ilu0,coarsening.type=aggregation}
Solver
======
Type:             GMRES(30)
Unknowns:         17304
Memory footprint: 4.23 M

Preconditioner
==============
Number of levels:    2
Operator complexity: 1.10
Grid complexity:     1.12
Memory footprint:    9.45 M

level     unknowns       nonzeros      memory
---------------------------------------------
    0        17304         217358      8.52 M (90.51%)
    1         1997          22779    955.32 K ( 9.49%)

Iterations: 226
Error:      9.98567e-09

[Profile:       2.138 s] (100.00%)
[  reading:     0.291 s] ( 13.61%)
[  setup:       0.027 s] (  1.25%)
[  solve:       1.819 s] ( 85.11%)
```

**Comment by RiccardoRossi** [comment]
better solution proposed by @ddemidov in #3110 . closing

**Pull request closed without merging**
