### PR TITLE
Feature adjoint turbulent sensitivity optimization

### PR DESCRIPTION
**Pull request by sunethwarna**
AdjointFluidApplication:
This PR adds localized numerical diffusion to vms elements in adjoint fluid application based on singular value decompositon method with pressure coupling and pressure decoupled methods

ShapeOptimizationApplication:
This PR adds compatibility to use ShapeOptimizationApplication with AdjointFluidApplication and FluidDynamics applications for shape optimization. Test example is also included in the test_examples folder.

### CODE REVIEW

**Comment by msandre** [comment]
Remove the vscode json settings and add to local .git/info/exclude so it doesn't get included in the future.

**Comment by msandre** [comment]
Can you remove the boost files also?

**Comment by philbucher** [comment]
you are still requiring to link shapeoptimization against empire and hdf5, this should not be

also there is a lot of comments in your files that should be removed

**Review by dbaumgaertner — CHANGES_REQUESTED** [review]
This PR includes modifications in the ShapeOptimizationApp beyond the current concept. E.g. it creates (optional) links to libraries from an external software (EMPIRE). So for sure, as far as the optimization part is considered, this cannot be included straight away, especially not without a beforehand discussion with @KratosMultiphysics/optimization ! So I would like to block this PR until we clarified that.

**Comment by msandre** [comment]
@dbaumgaertner to clarify, the intent was not to merge straight away but rather to discuss it. I suggested to make the pr and tag you as reviewers for exactly this reason. Before it can be discussed though, we need to clean up a lot of the files that got included from boost etc. @sunethwarna I would suggest to leave the pr open. You can commit your new changes directly to it.

**Comment by armingeiser** [comment]
@msandre we discussed with @sunethwarna that it makes sense to create two separate PR:
- one for the adjoint fluid optimization (Here we can already try to incorporate the things we discussed last week: response classes, fluid analysis script)
- one for the nurbs based mapping with empire (probably inside empire_application) and then making it usable in ShapeOptimizationApplication.

We thougth that it might be the cleanest solution to create a new branch/pr for that.

**Comment by msandre** [comment]
If @sunethwarna agrees with it then I'm fine with that too.

**Comment by philbucher** [comment]
Putting the empire related stuff to the Empire-Application makes full sense also from my side.
I think we should have one place that contains all the empire related stuff.

@sunethwarna before you move your implementation there please talk to me first since I am currently also working in the application

**Comment by loumalouomega** [comment]
Can we delete this branch?

**Comment by sunethwarna** [comment]
I was keeping it till i migrate parts of this branch to a separate one, now I will delete it.

**Pull request closed without merging**
