### PR TITLE
[Core] Fix Json Input Nurbs

### PR DESCRIPTION
**Pull request by tteschemacher**
Hi all,

I am fixing here a small bug within the reading of rational shape functions for nurbs geometries.

### CODE REVIEW

**Comment by tteschemacher** [comment]
Can someone please approve that PR? @KratosMultiphysics/technical-committee

**Review by philbucher — APPROVED** [review]

**Comment by tteschemacher** [comment]
Gracias!

**Review by philbucher — APPROVED** [review]
strange that this wasn't picked up by your tests :stuck_out_tongue_closed_eyes:

**Comment by tteschemacher** [comment]
Now it is covered by a test :P

**Pull request merged**
