### PR TITLE
[Core][StructuralMechanicsApplication] Missing steps of CL in base_solid_element

### PR DESCRIPTION
**Pull request by loumalouomega**
Right now not used, but could be used in the future

### CODE REVIEW

**Review by philbucher — APPROVED** [review]

**Review by philbucher — DISMISSED** [review]
this does not compile!

**Comment by loumalouomega** [comment]
Sorry in my computer I had removed the errors that are present in Initialize/FinalizeNonLinearIteration but not in Initialize/FinalizeSolutionStep.

**Comment by loumalouomega** [comment]
I added the technical committee, now it modifies the constitutive law base

**Comment by loumalouomega** [comment]
@KratosMultiphysics/technical-committee

**Review by RiccardoRossi — APPROVED** [review]

**Comment by loumalouomega** [comment]
Thanks

**Comment by loumalouomega** [comment]
@KratosMultiphysics/structural-mechanics We should add the call to CL InitializeNonLinearIteration and FinalizeNonLinearIteration to all the elements, even if right now does nothing, could be of interest

**Pull request merged**
