### PR TITLE
[WIP] Error example less elements than partitions

### PR DESCRIPTION
**Pull request by jrubiogonzalez**
We have found a strange error when there are less elements than partitions

### CODE REVIEW

**Comment by philbucher** [comment]
What does this do?

**Comment by jrubiogonzalez** [comment]
This is a test that shows an error when more partitions than elements are used

**Comment by loumalouomega** [comment]
Do we still need this branch @jrubiogonzalez ?, can we remove it?

**Comment by jrubiogonzalez** [comment]
It can be removed

**Pull request closed without merging**
