### PR TITLE
[ContactStructuralMechanicsApplication] Update app to use #5390 

### PR DESCRIPTION
**Pull request by loumalouomega**
This refactor the whole app to use #5390. The refactor is required due to the deep roots of the paired conditions in the app

### CODE REVIEW

**Comment by loumalouomega** [comment]
#5393 could reduce the size of this, but not to much

**Comment by philbucher** [comment]
Wow, didn’t think it would be that useful!

Does it make things a lot easier vicente?

**Comment by loumalouomega** [comment]
> Wow, didn’t think it would be that useful!
> 
> Does it make things a lot easier vicente?

For me not, it took me 4 hours to refactor all the app, I was happier before

**Comment by philbucher** [comment]
why did you do it then if it doesn't make things easier for you?

**Comment by loumalouomega** [comment]
> why did you do it then if it doesn't make things easier for you?

Because I though it would...but like I am very persistent now is done

**Comment by tteschemacher** [comment]
But it makes it more generic, doesn't it?

**Comment by loumalouomega** [comment]
Due to conflicts I reopened in #5399

**Comment by loumalouomega** [comment]
> But it makes it more generic, doesn't it?

Yes, but I did a refactor long time ago, when one condition was paired with N other conditions and now are paired with only one. Before that refactor it would be perfect, right now I remove one variable and a pointer stored per condition

**Pull request closed without merging**
