### PR TITLE
[Core] Clean up unused includes

### PR DESCRIPTION
**Pull request by loumalouomega**
This removes unused includes in the elimination B&S with constraints

### CODE REVIEW

**Review by philbucher — APPROVED** [review]
seems ok if it compiles without

How come you don't need those includes

also FYI @adityaghantasala

**Comment by philbucher** [comment]
@loumalouomega :
> How come you don't need those includes

?

**Comment by loumalouomega** [comment]
I don't know what I said...

**Comment by philbucher** [comment]
I think I was explaining myself badly, sorry

I meant, those classes are needed in the block-version of the constraint-B&S, how come you managed without them?

**Comment by loumalouomega** [comment]
Because I do the assemble by hand 🖐️

**Comment by philbucher** [comment]
ah ok, thx

**Pull request merged**
