### PR TITLE
Adding check to remove output files after test.

### PR DESCRIPTION
**Pull request by jcotela**
Otherwise they just remain there indefinitely....

### CODE REVIEW

**Comment by philbucher** [comment]
Hi @jcotela 
I thought of writing a process for this purpose, then it could be also used by other tests. What do you think?

**Comment by jcotela** [comment]
@philbucher I was also thinking about how to do this automatically, and was thinking that maybe adding some methods to the test base classes could work. Maybe we could make it a part of the context manager (the `WorkFolderScope` thing in other tests), so that it automatically deletes "new" files on exit?

**Comment by philbucher** [comment]
@jcotela I like your suggestion even more, but I don't know how it could be done

**Comment by jcotela** [comment]
I've been thinking about this some more. The simplest idea I can think of is to run the test in a specially-created folder and just delete it once the test is done. This could be done "automagically" by the `WorkFolderScope` thing. Any pre-existing files that are required by the test (mdpa, json,...) can either be copied into that folder or just read from their original location.
@roigcarlo you have more experience in tests, do you see any obvious problems with something like this?

**Comment by roigcarlo** [comment]
Yep it could be done that way. If you ask me the more neat solution would be to generate a temp directory somewhere copy everything you need/generate there, and after the test is finished remove it. 

And indeed the right place to do this would be within some context manager like WorkFolderScope, or setUp&tearDown functions.

**Review by RiccardoRossi — APPROVED** [review]

**Pull request merged**
