### PR TITLE
[CoSim][GS] checking also if Solvers are converged

### PR DESCRIPTION
**Pull request by philbucher**
@pooyan-dadvand suggested to add a check if the solvers are converged in the Gauss-Seidel convergence check

what do you think @AndreasWinterstein @adityaghantasala @shahrokh-shayegan @KratosMultiphysics/cosimulation 

we could also make this optional

If we do this we would need to also make the solvers return their state of convergence (very minor modification)

### CODE REVIEW

**Comment by adityaghantasala** [comment]
Though it is safe to do this, I think this shoud not be the reason  that a coupling iteration is repeated. It is ok if you print the convergence of individual solvers. 

Here Relaxation/acceleration is done because a participating solver is not converged.

**Comment by pooyan-dadvand** [comment]
@philbucher I think I didn't expressed myself correctly. My point was to make solvers return their convergence status to make this check possible. 

I am not against adding it to our strong coupling solver but it may cause more iterations in first time steps where the fluid solver does not converge.

**Comment by philbucher** [comment]
> My point was to make solvers return their convergence status to make this check possible.

Makes sense, I will add this
Then it is also consistent with Kratos

**Comment by adityaghantasala** [comment]
> Here Relaxation/acceleration is done because a participating solver is not converged.

I mean this is a problem. It should not be done like that. it will pollute the convergence accelerators data. 

Convergence of the non-linear coupling iterations should not be effected by the convergence of the individual solvers.

**Comment by shahrokh-shayegan** [comment]
It is a good idea to return convergence status of the individual solvers to have them available for checks and further (future) uses e.g. defining dynamic/adaptive tolerances for the coupled solver and the (sub) solvers. 
But as the others said, l i also think that the convergence of the solvers should not be involved in deciding whether the Gauss-Seidel loop has converged or not (at least until some type of smart idea is not applied to relate the convergence criteria of the solvers to that of the couple solver). It might lead to increased number of iterations, specially if one of the solvers happens to have a (rather unnecessary) tight tolerance and misses its convergence criteria by a small margin.

**Comment by philbucher** [comment]
I agree now with @adityaghantasala and @shahrokh-shayegan that this should not go in as is (for the reasons in the conversation above)

I will however in the future add the information about solver convergence to the baseclass
e.g. `SolveSolutionStep` will return true or false, same as what the Kratos solvers do.
This can be useful in the future

added it to the [CoSim-Project](https://github.com/KratosMultiphysics/Kratos/projects/32)

**Pull request closed without merging**
