### PR TITLE
[CI] activate MPI Fluid tests

### PR DESCRIPTION
**Pull request by philbucher**
Now that the trilinos extension and the mpi-tests are working again I would like to enable them asap
(still using the dirty solution until I have time to refactor)

### CODE REVIEW

**Comment by philbucher** [comment]
@KratosMultiphysics/fluid-dynamics I am removing the execution of the MPI-tests from the serial tests
This was a hack to begin with (I know I came up with it ;D) but now I am working on a better solution so I removed it, otherwise it gives problems in the CI

**Review by rubenzorrilla — DISMISSED** [review]
Thanks.

**Comment by philbucher** [comment]
I also had to take out the MPI-tests in the serial test-suites of RANS and StructuralMechanics, otherwise we get timeouts in the tests

As said before, this is only an intermediate solution and will be improved (a lot!) in the future

**Comment by philbucher** [comment]
Ok other builds are also failing bcs of timeouts :sweat_smile: 

Can someone approve this please?

**Review by rubenzorrilla — APPROVED** [review]
Thanks again :wink:

**Pull request merged**
