### PR TITLE
removing benchmarking folder

### PR DESCRIPTION
**Pull request by philbucher**
I think that these files are quite outdated
Also I saw several times already that it confuses new users that try to get into Kratos
 
This is a suggestion, decision is up to you @KratosMultiphysics/technical-committee

### CODE REVIEW

**Comment by jcotela** [comment]
In principle the @KratosMultiphysics/technical-committee agrees with deleting this, but the benchmarking files are still used by the cases in the `test_examples` folders in each application. Most of these test examples are terribly outdated, though.

@KratosMultiphysics/team-maintainers Can each of us check the remaining `test_examples` cases in our applications? They should be either removed, converted to tests or updated and moved to the Examples repository.

If it is just a case of removing, I would push the changes to this branch.

**Comment by jcotela** [comment]
Applications with test examples folders to be updated:
- [x] convection_diffusion_application
- [x] FluidDynamicsApplication @jcotela
- [x] incompressible_fluid_application @jcotela
- [x] MeshingApplication @loumalouomega?
- [x] mpi_search_application @roigcarlo?
- [x] OpenCLApplication @RiccardoRossi?
- [x] structural_application @RiccardoRossi?
- [ ] swimming_dem_application @maceligueta @GuillermoCasas
- [x] ThermoMechanicalApplication @jcotela
- [x] trilinos_application

**Comment by loumalouomega** [comment]
At least my test_examples are not related with benchmarking

**Comment by jcotela** [comment]
@loumalouomega look for `import benchmarking` from within the test_examples folder. The hits are the scripts that should be updated.

**Comment by loumalouomega** [comment]
OK, sorry for the noise

**Comment by RiccardoRossi** [comment]
the convection diffusion application has some bfecc benchmarks that should be working and need to be eventually ported...i would like to ask not to remove those until they are ported

**Comment by philbucher** [comment]
@RiccardoRossi I checked the bfecc benchmarks, they are not related to the benchmarking

There are however some test_examples in the convdiffapp that are using the benchmarking, should those be removed?

**Comment by philbucher** [comment]
ping @roigcarlo @maceligueta @GuillermoCasas 

ping @jcotela regarding the incompressible_fluid_app

also ping @RiccardoRossi what abt the benchmarks in the `structural_application` and the `OpenCLApplication`?

**Comment by roigcarlo** [comment]
Test in the mpi_search_application is totally outdated, you can remove it safely

**Comment by philbucher** [comment]
@roigcarlo as requested I removed the folder `test_examples` from the `mpi_search_application`

**Comment by philbucher** [comment]
ping @maceligueta @GuillermoCasas

ping @jcotela regarding the incompressible_fluid_app

also ping @RiccardoRossi what abt the benchmarks in the structural_application and the OpenCLApplication?

**Comment by RiccardoRossi** [comment]
openclapplication can be removed completely

structural_application is pure legacy to me, same as for incompressible_fluid...i simply would not touch them and let the mantainers @vryy @juliomarti to eventually fix/remove old stuff

**Comment by RiccardoRossi** [comment]
openclapplication can be removed completely

structural_application is pure legacy to me, same as for incompressible_fluid...i simply would not touch them and let the mantainers @vryy @juliomarti to eventually fix/remove old stuff

**Comment by philbucher** [comment]
thanks @RiccardoRossi 

I would say we can go ahead with this

If you give me a go then I can remove the OpenCLApp in a separate PR

**Comment by RiccardoRossi** [comment]
+1 for removing opencl (go!)

**Review by pooyan-dadvand — APPROVED** [review]
Thanks for cleanup!! 👍

**Pull request merged**
