### PR TITLE
Adding missing const to Mult operations

### PR DESCRIPTION
**Pull request by loumalouomega**

### CODE REVIEW

**Review by roigcarlo — CHANGES_REQUESTED** [review]
I agree with the const one but we have to leave the non-const as well, if we do it this way anyone using it with a none constant matrix will have their code broken

**Comment by loumalouomega** [comment]
You told me that it was possible to use it with not const matrices, besides it compiles

**Comment by loumalouomega** [comment]
Done

**Comment by roigcarlo** [comment]
Then ok to me, but I would like a second opinion as well

**Comment by loumalouomega** [comment]
Ok

**Comment by roigcarlo** [comment]
Actually I was wrong, is the other way around, you can leave it only with const sorry

Thx @RiccardoRossi for pointing that out

**Review by roigcarlo — APPROVED** [review]

**Comment by loumalouomega** [comment]
@roigcarlo This compilation in Travis is taking a looooooooong time several times

Slooooow...
imagen

**Pull request merged**
