### PR TITLE
[CI][Win] make C4804 an error

### PR DESCRIPTION
**Pull request by philbucher**
@AlejandroCornejo there is a small warning in the build:
~~~
D:\a\Kratos\Kratos\applications\StructuralMechanicsApplication\custom_advanced_constitutive\rule_of_mixtures_law.cpp(567,37): warning C4804: '+=': unsafe use of type 'bool' in operation (compiling source file D:\a\Kratos\Kratos\build\Custom\applications\StructuralMechanicsApplication\Custom\cotire\KratosStructuralMechanicsCore_CXX_unity_0_78.cxx) [D:\a\Kratos\Kratos\build\Custom\applications\StructuralMechanicsApplication\KratosStructuralMechanicsCore_unity.vcxproj]
~~~

can you please push the fix to this branch?

### CODE REVIEW

**Comment by AlejandroCornejo** [comment]
I've solved it in another branch that I'll merge soon #6890. Anyways I'll solve it here ASAP :)

**Comment by AlejandroCornejo** [comment]
Solved in #6890 I hope

**Comment by philbucher** [comment]
this is not solved!
in the future this warning will be turned into an error in the CI such that it doesn't reappear

**Comment by AlejandroCornejo** [comment]
Oops **sorry** :)

**Review by roigcarlo — APPROVED** [review]

**Pull request merged**
