### PR TITLE
[MeshingApplication] Remove Variable Component uses

### PR DESCRIPTION
**Pull request by marcnunezc**
**Description**
Adresses #7511 for the meshing app. 

**Changelog**
- Removed Variable component usage and methods.

### CODE REVIEW

**Comment by philbucher** [comment]
are those methods just copy pasted for Components and double variables? :sweat_smile:

**Review by loumalouomega — DISMISSED** [review]
None of these codes  are mine, maybe is from @miguelmaso . Ok from my side

**Comment by loumalouomega** [comment]
> None of these codes are mine, maybe is from @miguelmaso . Ok from my side

Nope, it is legacy...

imagen

**Review by philbucher — APPROVED** [review]

**Comment by marcnunezc** [comment]
Sorry left one file outside the first commit

> are those methods just copy pasted for Components and double variables? sweat_smile

Yes :sweat_smile:, added on 2012 though

**Comment by joaquinirazabal** [comment]
I think this was my first contribution to Kratos a very long time ago... Great idea to clean it up ;)

**Pull request merged**
