### PR TITLE
[CovectionDiffusion]Update read material process with cpp

### PR DESCRIPTION
**Pull request by loumalouomega**

### CODE REVIEW

**Comment by rubenzorrilla** [comment]
If tests run, I'm ok with the changes.

**Comment by loumalouomega** [comment]
Should we add these convection diffusion to the the Travis? @roigcarlo

**Comment by roigcarlo** [comment]
We should but we can't

**Comment by loumalouomega** [comment]
Compilation time too long?

**Comment by roigcarlo** [comment]
Yes. Right now worst case scenario is 45min, that left us with 4 minutes left of margin, which is not sufficient for that.,.. but feel free to activate it in appveyor if you want

**Comment by loumalouomega** [comment]
In any case can anyone approve?

**Review by philbucher — APPROVED** [review]
same as in StructuralMechanics, therefore approving

**Comment by loumalouomega** [comment]
Thanks

**Pull request merged**
