### PR TITLE
[StructuralMechanicsApplication] Adding missing overrides

### PR DESCRIPTION
**Pull request by loumalouomega**
On base_shell_element

### CODE REVIEW

**Review by philbucher — APPROVED** [review]
Sorry my bad, thx for fixing!

**Comment by loumalouomega** [comment]
@roigcarlo Looks like Travis tests are failing here too, and I just changed one three lines not related with the tests

**Comment by philbucher** [comment]
So Travis fails even if it compiles and the tests are running?

**Comment by loumalouomega** [comment]
The origin of the problem is this https://github.com/KratosMultiphysics/Kratos/blob/74c37705e750a402e4eebc852a87573a45957281/kratos/tests/test_model_part_io.py#L148

**Comment by loumalouomega** [comment]
But this is the behaviour expected and the test is from 2 years ago

**Pull request merged**
