### PR TITLE
[StructuralMechanics] Fix processes creation

### PR DESCRIPTION
**Pull request by philbucher**
Must have slipped in

### CODE REVIEW

**Comment by KlausBSautter** [comment]
fixes my problems, thanks !

**Review by KlausBSautter — APPROVED** [review]

**Comment by philbucher** [comment]
@loumalouomega @RiccardoRossi this might affect you in the rve-developments, please take care

**Review by loumalouomega — COMMENTED** [review]
What is the difference?

**Comment by philbucher** [comment]
the indentation level; the creation of processes given in the old format was incorrectly guarded by the wdeprecation-warning-flag

**Pull request merged**
