### PR TITLE
ACTIVE check for residualbased...componentwise

### PR DESCRIPTION
**Pull request by AFranci**

### CODE REVIEW

**Review by jcotela — APPROVED** [review]
👍

**Comment by RiccardoRossi** [comment]
Hi guys

Take care with this: what will happen for dogs belonging to nodes with no surrounding element?

**Comment by jcotela** [comment]
@RiccardoRossi That's a good point. I'm blocking this until we can discuss it with @AFranci

**Review by jcotela — CHANGES_REQUESTED** [review]
Blocking until we can discuss the issue of missing dofs

**Comment by AFranci** [comment]
Ok, I understand the point of Riccardo. I did not notice it in my problems because I cannot have that situation, but for other users it can occur.  
The Block builder and solver does consider the Active check, however I did some tests and, at least for my application, it seems to be much slower than the elimination one (above all in problems where large part of the domain is constrained). 
By the moment, I erase this pull request and think to the best alternative.
Thanks for the feedback!

**Comment by RiccardoRossi** [comment]
hi,

i am not clear on the status of this pull request. Is it to be considered "closed" or is it still active?

**Comment by philbucher** [comment]
Can this branch be deleted?

**Comment by AFranci** [comment]
done

**Pull request closed without merging**
