### PR TITLE
[Core] remove unused const

### PR DESCRIPTION
**Pull request by philbucher**
removing a compiler warning with Intel

### CODE REVIEW

**Comment by roigcarlo** [comment]
Good to me but, if its for intel why are we changing it in travis?

**Comment by philbucher** [comment]
This warning is not displayed by default in GCC, but it is default in Intel
I did quite some cleaning already (can dig up the PR if you want), but basically each time I pull there are warnings like this again

=> Hence I activate this warning also for GCC (in Travis) and treat it as an error such that we stay clean in the future

**Comment by roigcarlo** [comment]
Ok. Fine then :+1:

**Comment by philbucher** [comment]
can you approve pls?

**Review by roigcarlo — APPROVED** [review]

**Comment by philbucher** [comment]
thx

**Pull request merged**
