### PR TITLE
[Core] Adding Python to C++ wrapper

### PR DESCRIPTION
**Pull request by loumalouomega**
@roigcarlo Look if this solve the need of a wrapper for C++

### CODE REVIEW

**Comment by philbucher** [comment]
seems to be similar to https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/utilities/python_function_callback_utility.h

**Comment by loumalouomega** [comment]
Well, in fact that one is specific for casting python functions, this is more general.

**Comment by loumalouomega** [comment]
In any case @KratosMultiphysics/technical-committee needs to discuss this

**Comment by philbucher** [comment]
could one also pass classes to c++?

EDIT looks like it

**Comment by loumalouomega** [comment]
Yes, an object is literally everything in python, so it is a powerful tool 

imagen

**Comment by loumalouomega** [comment]
@roigcarlo apparently doesn't work on Windows, which is the target right now...

**Comment by loumalouomega** [comment]
For the interest of @roigcarlo this now allows to directly import from python, so I added the code of a "Main" that uses the analysis stage. Now we can run the simulation (without any additional modification) directly from C++. I added a main equivalent to the one of the structural, so:

(The interface on python in only for testing, can be removed, the final objective is to run everything from C++)

~~~py
import KratosMultiphysics
KratosMultiphysics.PythonObjectCppWrapperUtility.RunStructuralAnalysisStage("ProjectParameters.json")
~~~

is equal to:

~~~py
from __future__ import print_function, absolute_import, division #makes KratosMultiphysics backward compatible with python 2.6 and 2.7

import KratosMultiphysics
import KratosMultiphysics.StructuralMechanicsApplication

from structural_mechanics_analysis import StructuralMechanicsAnalysis

"""
For user-scripting it is intended that a new class is derived
from StructuralMechanicsAnalysis to do modifications
"""

if __name__ == "__main__":

    with open("ProjectParameters.json",'r') as parameter_file:
        parameters = KratosMultiphysics.Parameters(parameter_file.read())

    model = KratosMultiphysics.Model()
    simulation = StructuralMechanicsAnalysis(model,parameters)
    simulation.Run()
~~~

An example:

[test_wrapper.gid.zip](https://github.com/KratosMultiphysics/Kratos/files/2103585/test_wrapper.gid.zip)

**Comment by philbucher** [comment]
Very impressive!

Is this experimental or sth that will be merged for usage?

**Comment by loumalouomega** [comment]
It will be merged, I assume, right now just experimental

**Review by pooyan-dadvand — CHANGES_REQUESTED** [review]
As it is experimental I would block it just to avoid accidental merge

**Comment by loumalouomega** [comment]
Seems fair

**Comment by RiccardoRossi** [comment]
this is nice as a proof of  concept, however i don't think we should push in this direction...

**Comment by RiccardoRossi** [comment]
This issue has been discussed in @KratosMultiphysics/technical-committee 

we believe that this kind of usage should not be allowed. The reasoning behind this is that: 
1 - it breaks the organization in layers of kratos
2 - it opens quite a lot of security issues with the possibility of running malicious code written in a script

@loumalouomega would u agree closing this?

**Comment by loumalouomega** [comment]
I agree, but can I keep the code isolated in some place?, like in https://github.com/KratosMultiphysics/Kratos/pull/2372 

I would prefer not to waste this code. This way the use will be accessible but only in case you compile the application in purpose and you know what are you doing

**Comment by loumalouomega** [comment]
I will keep the branch alive until your reply

**Comment by loumalouomega** [comment]
Please don't delete the branch

**Comment by jcotela** [comment]
@loumalouomega I have not spoken with the rest of the committee about this, but personally, I'd suggest moving code you want to keep to your own repository. You can create a new repository with an empty application using charlie's tool and move anything you want to preserve there. I did something similar when we retired the wind turbine application https://github.com/jcotela/kratos-wind-turbine-application

**Comment by loumalouomega** [comment]
👌, I like the idea, thanks

**Comment by loumalouomega** [comment]
@jcotela Done, the repository for how has interest is here:

https://github.com/loumalouomega/KratosPythonWrapperApplication

**Pull request closed without merging**
