### PR TITLE
Kratos rom neighbouring elements candidates

### PR DESCRIPTION
**Pull request by SADPR**
**Overview:**
Previously, providing a model part without elements as initial candidates for the Empirical Cubature Method (ECM) would result in an empty list return. This update ensures that in such cases, a list of associated neighboring elements of the model part's nodes is provided instead, enhancing the functionality and reliability of the ECM in handling various model part configurations.

**Details:**
This pull request enhances the RomApplication in KratosMultiphysics, improving the ECM. It now adeptly handles cases where a user-provided model part has no associated elements. In such scenarios, the application automatically identifies and uses the neighboring elements of the nodes within the model part, ensuring uninterrupted and efficient operation of the ECM. Users are alerted to this automatic adjustment through a warning message.

**Changelog:**

- Added GetNodalNeighbouringElementIds function in rom_auxiliary_utilities.cpp.
- Included header and description for the new function in rom_auxiliary_utilities.h.
- Exported the new function to Python in add_custom_utilities_to_python.cpp.
- Modified hrom_training_utility.py to use GetNodalNeighbouringElementIds when a model part has no associated elements and added a warning message for the same.

**Files Changed:**

```
- applications/RomApplication/custom_utilities/rom_auxiliary_utilities.cpp
- applications/RomApplication/custom_utilities/rom_auxiliary_utilities.h
- applications/RomApplication/custom_python/add_custom_utilities_to_python.cpp
- applications/RomApplication/python_scripts/hrom_training_utility.py
```

### CODE REVIEW

**Review by loumalouomega — COMMENTED** [review]
Okay from my side (test?)

**Comment by SADPR** [comment]
> Okay from my side (test?)

Regarding the tests, we have been thinking to add corresponding tests to all utilities' functions. My question is, to which level should we think of testing. Do you think all new functions in for instance, "rom_auiliary_utilities.h/cpp" should have a corresponding small test? 

I have it on the TODO's list of the project. If you agrre, I would suggest to do a separate PR for testing all utilities' functions. @loumalouomega

**Comment by loumalouomega** [comment]
> > Okay from my side (test?)
> 
> Regarding the tests, we have been thinking to add corresponding tests to all utilities' functions. My question is, to which level should we think of testing. Do you think all new functions in for instance, "rom_auiliary_utilities.h/cpp" should have a corresponding small test?
> 
> I have it on the TODO's list of the project. If you agrre, I would suggest to do a separate PR for testing all utilities' functions. @loumalouomega

Okay, I am not blocking

**Review by Rbravo555 — APPROVED** [review]
Looks good to go

**Pull request merged**
