### PR TITLE
unitTest with h5py library active

### PR DESCRIPTION
**Pull request by farrufat-cimne**
PR with unitTest for ghost walls (h5py, numpy)

### CODE REVIEW

**Comment by maceligueta** [comment]
@roigcarlo . The modifications of Travis have been moved to this small PR. So we can use it as a playground.

**Comment by roigcarlo** [comment]
Roger that :+1:

**Comment by maceligueta** [comment]
What about doing `pip install h5py`?
Someone tried this with success here: https://github.com/clawpack/pyclaw/issues/552

**Comment by roigcarlo** [comment]
That will install it for p2

**Comment by roigcarlo** [comment]
actually we are almost there, let me try one last thing

**Comment by maceligueta** [comment]
No luck. Cannot import h5py. 
Maybe `python3 -m `**pip3**` install --user h5py `?

**Comment by roigcarlo** [comment]
Mm I don't think we can install it that way.  Anyway, hdf5 was installed properly this time, maybe runkratos is not able to locate it. If that is the case a tweak in the way the tests are called should do the trick

**Comment by roigcarlo** [comment]
Seems it does work :)

**Comment by maceligueta** [comment]
Awesome! I'll approve and merge, and let's hope Travis won't take that much after this change!

**Review by maceligueta — APPROVED** [review]

**Comment by philbucher** [comment]
I think this creates a lot of warnings in Travis...

**Comment by maceligueta** [comment]
Yes, you are right @philbucher , I thought all those warnings would be encapsulated and hidden inside the initial preparation of the system, but they actually show up and aren't minimized. I'll open an issue for this.

**Comment by roigcarlo** [comment]
Oh! but I though this was just for testing... Maybe it can be hidden but I wantet to iterate over this a little bit more

**Comment by maceligueta** [comment]
Then, I'm sorry I misunderstood. We can undo the last changes, no problem. Will the 'revert' button cause problems? Let's revert.

**Pull request merged**
