### PR TITLE
[Core] add function AddColors to the communicator

### PR DESCRIPTION
**Pull request by vryy**
add additional subroutines to communicator in order to add additional colors (SetNumberOfColors will remove existing meshes of old color)

### CODE REVIEW

**Review by loumalouomega — COMMENTED** [review]
Can you add a test?

**Comment by vryy** [comment]
> Can you add a test?

This does not do any specific operations. Instead the mesh container is expanded. Do we need a test for it?

**Comment by loumalouomega** [comment]
> > Can you add a test?
> 
> This does not do any specific operations. Instead the mesh container is expanded. Do we need a test for it?

It is good to always add a test with any small change. In this case is a test super basic, not a whole simulation. See tests in C++

**Review by RiccardoRossi — COMMENTED** [review]
i am ok in principle with the addition, however i cannot see thenuse. could u spend a word in what you intend to do?

**Comment by vryy** [comment]
> i am ok in principle with the addition, however i cannot see the use. could u spend a word in what you intend to do?

there is a case in parallel contact that a need to duplicate the master conditions in other process is necessary, together with its node for synchronization. Because the contact search is done after the mesh is partitioned so the coloring has to be modified after initiating. Technically, the modified coloring is not optimal anymore but i can't think of another way to maintain data consistency.

**Review by RiccardoRossi — APPROVED** [review]

**Pull request merged**
