### PR TITLE
Add vtk Biquadratic element

### PR DESCRIPTION
**Pull request by jginternational**
**📝 Description**
Add 9 noded quadrilaterals to VTK output

Implements #11703

### CODE REVIEW

**Comment by philbucher** [comment]
is the nodal ordering the same in kratos and vtk?

**Comment by jginternational** [comment]
In Kratos:
https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/geometries/quadrilateral_3d_9.h

```
 * The node ordering corresponds with:
 *      3-----6-----2
 *      |           |
 *      |           |
 *      7     8     5
 *      |           |
 *      |           |
 *      0-----4-----1
 ```

In VTK
https://vtk.org/doc/nightly/html/classvtkBiQuadraticQuad.html
image


The ordering of the eight points defining the cell are point ids (0-3,4-8) where ids 0-3 define the four corner vertices of the quad; ids 4-7 define the midedge nodes (0,1), (1,2), (2,3), (3,0) and 8 define the face center node.

> is the nodal ordering the same in kratos and vtk?

@philbucher it seems to be the same

**Comment by jginternational** [comment]
In GiD, just imagine that we start from 0, like real computer science engineers
image


https://gidsimulation.atlassian.net/wiki/spaces/GRM/pages/2385547733/Element+type

**Review by philbucher — APPROVED** [review]
nice!

**Comment by jginternational** [comment]
@AlejandroCornejo 

Cuando tus alumnos intenten mallar con malla de cuadrilateros de 9 nodos, les dará un fallo.
Tan solo tienes que decirles que en el arbol de datos vayan a Results > VTK  y deshabiliten la escritura de resultados para VTK

**Pull request merged**
