### PR TITLE
Fix trilinos extension

### LINKED ISSUE #7001: [FluidDyn] ImportError trilinos-extension
Happens in the CI and also on my local machine
@KratosMultiphysics/fluid-dynamics 

~~~
from KratosFluidDynamicsTrilinosExtension import *
ImportError: /__w/Kratos/Kratos/bin/Custom/libs/KratosFluidDynamicsTrilinosExtension.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZTI14Epetra_MpiComm
~~~

### PR DESCRIPTION
**Pull request by roigcarlo**
This should solve #7001 

I also removed the copy unity as its the default behavior in cotire >1.7, which is what we have so its not necessary.

closes #7001

### CODE REVIEW

**Review by philbucher — APPROVED** [review]
thanks!

Tests in the FLuidDynApp are failing, but this is a different issue :)

**Comment by philbucher** [comment]
tests are fixed in #7101

**Review by sunethwarna — APPROVED** [review]
nice :) thanks :)

**Comment by philbucher** [comment]
The rest of the cotire build still works right?
I remember last time problems with this made some parts of the core to recompile

**Comment by roigcarlo** [comment]
Yep, the only change is the order of creation of the cotire target, as it was before seeting the linking flags not even the "COPY_UNITY" option was able to inherit the dependecy for epetra, as it was not set.

I loot at other projects that may were using this and seems that only another app had it and it was ok.

**Comment by rubenzorrilla** [comment]
Thanks @roigcarlo

**Pull request merged**
