### PR TITLE
Remove modelpart constructor

### PR DESCRIPTION
**Pull request by philbucher**
I think most of the apps are updated in the meantime
Would be nice to have this cleaned for the release

### CODE REVIEW

**Comment by philbucher** [comment]
ping @RiccardoRossi

**Comment by RiccardoRossi** [comment]
I am ok about this. I am setting this as todo for @KratosMultiphysics/technical-committee

**Comment by pooyan-dadvand** [comment]
I would like to put a reminder to @KratosMultiphysics/altair team about this.

**Comment by pooyan-dadvand** [comment]
@KratosMultiphysics/technical-committee approves this but please wait until 1st of February for applying it

**Comment by philbucher** [comment]
can someone approve pls? Its 1st of february :)

**Comment by roigcarlo** [comment]
I think the idea is to approve after the initial freeze, could you wait just until past noon? ( We will probably do the freeze in a couple of hours)

**Comment by philbucher** [comment]
ah ok sure

I can also wait until Monday, I don't mind, just don't want to forget abt it

**Comment by pooyan-dadvand** [comment]
In Altair we are not ready yet for the move. Would you please wait a little bit more?

@KratosMultiphysics/altair we should move before the deprecation

**Comment by philbucher** [comment]
well it is deprecated and throws a huge warning for many months already ...

I suggest we go ahead with this and then @KratosMultiphysics/altair can update it locally
=> the problem is clear and the solution is straight forward

**Comment by pooyan-dadvand** [comment]
I understand your opinion but we need some time. we have arrived to the current master last week and still is not merged to our stable. So some more time would be great

**Comment by philbucher** [comment]
ok please let me know when you are ready

**Comment by pooyan-dadvand** [comment]
In progress, we will made it before release branch.

**Comment by philbucher** [comment]
Guess this won’t make it to the release ...

**Comment by pooyan-dadvand** [comment]
Actually we were ready by that time but I missed the issue as it was not in the milestone. Fortunately it is not crucial for the release.

**Comment by philbucher** [comment]
ok no worries :)

Can you approve then?

**Comment by pooyan-dadvand** [comment]
I will make a review of the changes

**Comment by philbucher** [comment]
ping @pooyan-dadvand

**Review by pooyan-dadvand — APPROVED** [review]
:+1: 

Thanks for your patience!

**Pull request merged**
