### PR TITLE
[DEM] RIgid Body Motion

### PR DESCRIPTION
**Pull request by joaquinirazabal**
This PR transforms all the fem submodelparts into rigid_elements. Now those submodelparts can be moved due to contact, gravitational and external forces imposing any Dof.
The rigid_element can also be moved as a grid of nodes (as before) due to the fact that it is quicker.

### CODE REVIEW

**Review by salvalatorre — DISMISSED** [review]
Looks OK... :)

**Comment by joaquinirazabal** [comment]
Do you know why it is not passing the Travis build? I tried to figure out the reason, but I don't know...

**Comment by maceligueta** [comment]
@joaquinirazabal , I can't see the output of the DEM tests (just those two tests that are still active). Maybe the problem is there...

**Comment by joaquinirazabal** [comment]
Thanks, @maceligueta that's the problem, I did not know how those test work. I will solve this as soon as possible.

**Comment by farrufat-cimne** [comment]
it seems that the normal impact velocity against a FEM wall is not the expected with tolerance = 1e-3:

def CheckValueOfNormalImpactVelocity(self, normal_impact_vel, expected_value, tolerance):
        if normal_impact_vel > expected_value + tolerance or normal_impact_vel < expected_value - tolerance:
            raise ValueError('Incorrect value for NORMAL_IMPACT_VELOCITY')

I dont think the error is related to the value itself but probably with the new format of the FEM_boundary.mdpa  

I will take a look at the code.

**Comment by joaquinirazabal** [comment]
Ok, thanks @farrufat-cimne, anything you need tell me!

**Comment by farrufat-cimne** [comment]
Well it seems that for some reason the normal impact velocity of the particle after hitting the FEM wall changed a bit in this branch. The difference is barely noticeable but it causes the test to fail:
expected value of normal velocity was : 
elif time > 0.43:
                    expected_value = 10.268
                   with tolerance = 1e-3 (10.267 to 10.269)

current achieved value is 10.266796428966513

changing the tolerance to 2e-3 (10.266 - 10.270) solves the problem but I don't know what part of the new code produced this change in the impact value. Maybe there was some small change in the contact between particle and FEM walls (scheme ?).

**Comment by farrufat-cimne** [comment]
Update.

I just updated my master in kratos and noticed the same error. The problem is not in your branch but in the master.

**Comment by joaquinirazabal** [comment]
Ok, thanks @farrufat-cimne

**Comment by maceligueta** [comment]
If it's in master, how could it be merged? The tests are not passing, so Travis shouldn't have allowed the merge...

**Comment by farrufat-cimne** [comment]
That's true. The problem found in this branch was related to the value being out of tolerance for test_1.

I tried to run tesst_1, test_2 and test_3 from the master and after modifying the tolerance I found that test 2 and 3 were failing since they appear marked as @KratosUnittest.expectedFailure (not sure about this decorator tho) :

@classmethod
    def test_Analytics_1(self):
        AnalyticsTestSolution().Run()

    @classmethod
    @KratosUnittest.expectedFailure
    def test_Analytics_2(self):
        GhostsTestSolution().Run()

    @classmethod
    @KratosUnittest.expectedFailure
    def test_Analytics_3(self):
        MultiGhostsTestSolution().Run()

**Comment by joaquinirazabal** [comment]
The problems with the DEM tests have been solved.
IMPORTANT: now PROPERTIES_ID of the submodelparts inside the DEM_FEM_boundary modelpart should be specified as:

Begin SubModelPart Sleeper1 // DEM-FEM-Wall. Group name: Sleeper1
  Begin SubModelPartData // DEM-FEM-Wall. Group name: Sleeper1
  PROPERTIES_ID 1
  RIGID_BODY_MOTION 0
  FREE_BODY_MOTION 1
  RIGID_BODY_MASS 186.0
  RIGID_BODY_CENTER_OF_MASS [3] (0.3,2.67,0.465)
  RIGID_BODY_INERTIAS [3] (1.0,1.0,1.0)
  IMPOSED_ANGULAR_VELOCITY_X_VALUE 0.0
  IMPOSED_ANGULAR_VELOCITY_Y_VALUE 0.0
  IMPOSED_ANGULAR_VELOCITY_Z_VALUE 0.0
  IDENTIFIER Sleeper1
  FORCE_INTEGRATION_GROUP 0
  End SubModelPartData
  Begin SubModelPartNodes
  104639
  105023
  107669
  107935
  110377
  110698
  113394
  113752
  End SubModelPartNodes
End SubModelPart

This feature has already been developed in the new GiD problemtype, however, it could be problematic for previous problems.

**Comment by maceligueta** [comment]
In the Method 'ModifyProperties' we could add a couple of lines with a check. If PROPERTIES_ID does not exist, we should give it the correct value... In this way, we ensure backward compatibility for some time.

**Comment by joaquinirazabal** [comment]
Thanks @maceligueta, but the problem was not that, it was when creating the Rigid Elements in the strategy. I solved the problem in the last commit: https://github.com/KratosMultiphysics/Kratos/pull/2272/commits/1e66203fa3bb13fe9a82ba1998ac72ccbc818bad

**Comment by maceligueta** [comment]
Great, so now we don't need to modify our old examples, do we?

**Comment by joaquinirazabal** [comment]
No, I ran the benchmarks and other tests with the old configuration and they work properly.

**Review by maceligueta — APPROVED** [review]

**Comment by joaquinirazabal** [comment]
Merged!

**Pull request merged**
