### PR TITLE
[Docs] Kratos Documentation

### PR DESCRIPTION
**Pull request by sunethwarna**
**📝 Description**
This PR adds the initial framework required to create documentation content for Kratos. How to create documentation is explained in "Kratos->Documentation Guide".

This documentation is made mainly to represent the theoratical and base of the formulations. Comprehensive implementation details are to be explained using the doxygen documentation which is the next phase of the documentation.

All the help in populating this documentation is highly appreciated.

Merry christmas and happy new year.

**🆕 Changelog**
- Added documentation
- Added completed documentation on `Statistics Application`
- Added documentation guide.

### CODE REVIEW

**Review by loumalouomega — DISMISSED** [review]

**Comment by loumalouomega** [comment]
image

**Review by loumalouomega — DISMISSED** [review]

**Comment by matekelemen** [comment]
I love this, but is there a way to avoid adding all these template HTML and PNG files to the repo, and maybe pull them in locally when generating the documentation?

**Comment by sunethwarna** [comment]
@matekelemen I am trying to do that with github actions at the moment.

**Review by loumalouomega — DISMISSED** [review]

**Review by rubenzorrilla — APPROVED** [review]
I'd merge this ASAP to start promoting it. Any minor we can correct it in the future.

**Pull request merged**
