### PR TITLE
update pybind to 2.7.0

### PR DESCRIPTION
**Pull request by philbucher**
This PR updates pybind to version 2.7.
From what I understand nothing major has changed, but there are a bunch of QOL updates that are nice to have (including my tiny contribution)

Note that this includes important fixes for the Intel compiler, since we didn't get to merge #8167 !

### CODE REVIEW

**Comment by RiccardoRossi** [comment]
i am positive about merging this.

**Comment by ddiezrod** [comment]
Sorry, I completely forgot about this. I just launched a pipeline in our side with these changes. In a couple of hours I will confirm this is fine from our side.

**Review by roigcarlo — COMMENTED** [review]
I think for this kind of PR we should approve as soon as it passes the CI. So :+1: from my side.

**Comment by ddiezrod** [comment]
The pipeline passed correctly, thanks and sorry for the delay!

**Comment by philbucher** [comment]
> The pipeline passed correctly in our side, thanks and sorry for the delay!

thx and no worries!

**Comment by philbucher** [comment]
@pooyan-dadvand I would also like to get your approval before merging :)

**Comment by pooyan-dadvand** [comment]
Ok for me!

**Review by pooyan-dadvand — APPROVED** [review]
As all agreed I approve it

**Review by rubenzorrilla — APPROVED** [review]
Ready to be merged then.

**Pull request merged**
