### PR TITLE
fixes clang compilation error 'for loop is not in canonical form'

### PR DESCRIPTION
**Pull request by marandra**

### CODE REVIEW

**Review by roigcarlo — APPROVED** [review]
Odd but Ok. I wonder why the compiler is not removing the () by itself...

**Review by pooyan-dadvand — APPROVED** [review]
Even the compilers are not what they were....
👍

**Comment by marandra** [comment]
It may be related to OpenMP. I think the code is here (lines 80-110): https://github.com/clang-omp/clang_trunk/blob/master/test/OpenMP/target_teams_distribute_loop_messages.cpp

**Comment by roigcarlo** [comment]
Yep it is openmp complaining that doesn't know how to handle the for
condition, but I would expect parèntesis not to be a problem, my clang at
least does not complain about that (5.0). Just for curiosity, which version
of the compiler are you using?

**Comment by marandra** [comment]
Me too: clang version 5.0.0 (tags/RELEASE_500/final), installed with Xcode in macOS (Target: x86_64-apple-darwin16.7.0)

**Comment by roigcarlo** [comment]
Ok, I will take a look wit the OSX VM, but I am very clumsy with mac.

Now that you mention it, probably the problem is mac :smiling_imp:

**Pull request merged**
