### PR TITLE
[StructuralMechanics] removing dynamic dofs from solvers

### PR DESCRIPTION
**Pull request by philbucher**
@KratosMultiphysics/structural-mechanics for some reason we were adding dynamic dofs in dynamic problems, even though none of our elements has those dofs ...

I think this is wrong but please let me know if we have to do this

all the tests are still working, including the dynamic ones

### CODE REVIEW

**Comment by RiccardoRossi** [comment]
@philbucher honestly i am not understanding what/why you are doing this

**Comment by philbucher** [comment]
The elements in StructuralMechanics have DISPLACEMENT (and ROTATION) as dofs, these are added in the baseclass of the solvers

The Dynamic solver also add Dynamic dofs (VELOCITY, ACCELERATION, etc), even tough the elements do not need them from how I understand it

Therefore I think we are adding dofs that are not being used

**Review by loumalouomega — APPROVED** [review]
Certainly this is something that I has been wondering for long time, approved

**Comment by RiccardoRossi** [comment]
You need the VELOCITY and ACCELERATION dofs since they are used to understand if you want to impose VELOCITY/ACCELERATION instead of DISPLACEMENT

a trick is done with those in the Predict

**Comment by philbucher** [comment]
thx for the explanation @RiccardoRossi 

Still it seems weird to me that we have to add dofs that ... Isn't this quite some overhead?
Could it be done in a different way?

Either way we can discuss this somewhere else, closing for now

**Pull request closed without merging**
