### PR TITLE
PFEM/SMA update

### PR DESCRIPTION
**Pull request by lluis-mv**
* Comment a line in BuildModelPartBoundaryProcess that (sometimes) generates a seg fault when echo>0
* Add model.CleanModel() in MainSolid.py [not completely sure, but, at the first step boundary conditions are doubled, inside a CompositeCondition and as a condition itself]
* Update the assignation of initial stress state (it was executed before elements where created, so it was useless)

### CODE REVIEW

**Comment by josep-m-carbonell** [comment]
I don't know about the segmentation fault, we must know why this occurs. 

I add a commit to make some scripts compatible with the MainSolid.py

**Comment by lluis-mv** [comment]
Hi, my impression is that i_cond->GetValue(MASTER_ELEMENTS) points to some elements that are no longer there. In fact, in the following line there is a i_cond->SetValue(MASTER_ELEMENTS, XXX).
[I do not understand the code, I just commented it since valgrind showed the place and it is a "writting to the screen" line]

**Comment by lluis-mv** [comment]
I took the liberty of introducing a couple of changes

**Comment by josep-m-carbonell** [comment]
@lluis-mv I forgot about this, I have been disconnected the whole last week. I will give you back my corrections and approval during nexts days.

**Comment by lluis-mv** [comment]
Hey @josep-m-carbonell , there is no rush, I have lots of other things to do.

**Review by josep-m-carbonell — APPROVED** [review]
Everything seems ok.

**Comment by lluis-mv** [comment]
thanks @josep-m-carbonell

**Pull request merged**
