### PR TITLE
[Core][Hotfix] Avoid ExecuteBeforeSolutionLoop on assign processes

### PR DESCRIPTION
**Pull request by loumalouomega**
Running a very simple case I realized that the solution was wrong, and it was because the process was setting an initial displacement in the first step, but also on the non-existent previous step, due to the ExecuteBeforeSolutionLoop, which solution will be modified during  step 1 due to CloneTimeStep. This did the delta displacement in the first step equal to zero, breaking all my computation

I think it is not dessirable the current behaviour. Besides maybe we need to modify the other assign processes

### CODE REVIEW

**Comment by philbucher** [comment]
good catch
Are the tests still running?

**Comment by loumalouomega** [comment]
In my computer it does

**Comment by rubenzorrilla** [comment]
I'm ok with the changes. Just to be sure, which application tests did you run?

**Comment by loumalouomega** [comment]
FluidDynamicsApplication, StructuralMechanicsApplication and
ContactStructuralMechanicsApplication

**Comment by rubenzorrilla** [comment]
Would you mind to run the FSIApp ones? Thank you!!!

**Comment by loumalouomega** [comment]
@rubenzorrilla I found some tests failing even in the master, be careful:
imagen

**Comment by loumalouomega** [comment]
In any case, some test of FSI are failing with the change, so I will suggest a modification that will keep the current workflow unchanged

**Comment by loumalouomega** [comment]
I create the fill_buffer parameter, which is true by default, the behaviour by default is the current one, but if you set to false will change to the desired one

**Comment by loumalouomega** [comment]
I added the.dat to gitignore, these are generated by the Fluid tests

**Comment by rubenzorrilla** [comment]
@loumalouomega we are aware of that. The fix to that is in another branch, but until we reach an agreement for the MPI case we won't do the merge.

Concerning the fill_buffer, in my opinion it's a good solution. Maybe we should update the test results according to the new behaviour...

**Comment by loumalouomega** [comment]
Right now it is true by default, so no need to change results

**Comment by rubenzorrilla** [comment]
But the proper behaviour is false, and this would imply to change the expected results of some tests. Am I wrong? 
My point is that maybe it's worth it to put some effort on that.

**Comment by loumalouomega** [comment]
We can do this now, and change it in a future PR

**Comment by philbucher** [comment]
Why not wait 2 weeks until @KratosMultiphysics/technical-committee is back from vacation and make a good solution?

**Comment by loumalouomega** [comment]
This is quite a solution :D

**Comment by loumalouomega** [comment]
One month passed, can we discuss this?

**Comment by RiccardoRossi** [comment]
I would say that this makes sense, however i have the feeling that "fill_buffer" should default to false to keep the current behaviour.

what are the views on this?

**Comment by jcotela** [comment]
Regarding the fluid dynamics application in particular (because it motivated some of the changes) I believe that there we should always write on the current step... If something needs to be assigned for step 0, it should be done as an initial condition, not as a boundary condition.

**Comment by loumalouomega** [comment]
What do we do with this?

**Comment by RiccardoRossi** [comment]
ping @KratosMultiphysics/technical-committee

**Comment by philbucher** [comment]
@loumalouomega whatever happens with this, please make sure to apply the same to the process added in #2940

**Comment by loumalouomega** [comment]
Can anyone approve?

**Comment by RiccardoRossi** [comment]
we are really not clear about this. blocking to be sure it is not merged by error ... and removing the FastPR label

**Comment by loumalouomega** [comment]
Ping

**Comment by adityaghantasala** [comment]
The thing is `ExecuteBeforeSolutionLoop`  is calling `ExecuteInitializeSolutionStep` which I think is the root of this problem. 

Can we do it like this : 
Make two functions First one for doing necessary checks and `ApplyFixity` and the second one `ForApplyingValues`

Like this `ExecuteBeforeSolutionLoop` calls only the first one and `ExecuteInitializeSolutionStep` calls both of them ?

**Comment by loumalouomega** [comment]
> The thing is `ExecuteBeforeSolutionLoop` is calling `ExecuteInitializeSolutionStep` which I think is the root of this problem.
> 
> Can we do it like this :
> Make two functions First one for doing necessary checks and `ApplyFixity` and the second one `ForApplyingValues`
> 
> Like this `ExecuteBeforeSolutionLoop` calls only the first one and `ExecuteInitializeSolutionStep` calls both of them ?

I don't follow you, sorry

**Comment by philbucher** [comment]
why did you close?

I thought this was giving problems for you?

**Comment by loumalouomega** [comment]
Yes, but apparently despite this doesn't change the current behavior and it is totally optional the cons are bigger than the pros for a core process

**Comment by AlejandroCornejo** [comment]
Dear all,

I've been working with the Newmark scheme and I was surprised to check that the velocities and accelerations are WRONG (in fact, **0.5 the expected!!**) as @loumalouomega  says.
I think that this is quite urgent and dangeorus... We really should look into this and solve it.

pls @KratosMultiphysics/technical-committee can  we reach an agreement? :)

Regards

**Comment by AlejandroCornejo** [comment]
I have to test more

**Comment by RiccardoRossi** [comment]
it looks like structural app is not affected....

**Comment by philbucher** [comment]
If we decide to change this (and to me makes sense to change the default and probably even remove the current behavior completely) then I think it would make sense to leave the default as is and issue a deprecation warning telling ppl to check and update their examples.
At least I have several cases of mine and others at the chair in mind that could be strongly affected by this
After some transition period we could then change the default

I know this way is overhead but at least gives ppl a chance to test for themselves rather than silently change at some point

**Comment by jcotela** [comment]
Just a suggestion, since @philbucher is proposing adding the new mechanism in parallel (instead of as a replacement):

In my opinion (and I am speaking mostly about the FluidDynamicsApplication here, not sure if it is completely applicable to Structural), the problems we are having with the use of the assign* processes ultimately come from the fact that we use the same class for two different tasks: applying *initial* conditions and *boundary* conditions. The imposed displacement condition situation described here sounds more like a boundary condition than an initial condition.

For initial conditions (which typically apply to the entire modelpart), it should be enough to apply them once before the simulation, and ensure that they "fill" all old steps when we do CloneSolutionStep to fill the nodal data buffer (maybe this is an implementation detail of the Fluid?). `ExecuteBeforeSolutionLoop` seems like a natural fit for this task. Also note that at no point we checked for/applied fixity.

We want boundary conditions to be applied at each iteration, so `ExecuteInitializeSolutionStep` seems like a more natural place to assign them. They also must apply fixity.

I am sure there are cases that do not fit the two categories here, but I think that separating the two concepts in different process classes might help reduce the confusion, rather than trying to cram everything into a single process with conditional checks.

**Comment by RiccardoRossi** [comment]
I second @jcotela  on this

**Comment by loumalouomega** [comment]
@jcotela this was exactly what I was doing, if you see manually the file you will see this was execute in the ExecuteBeforeSolutionLoop

**Comment by jcotela** [comment]
@loumalouomega seems like the branch is gone, or I could not find it... Note that I am not discussing about the procedure, which I think is correct. My point is about having separate classes to reduce confusion. If it was already done like this, then I misunderstood.

**Comment by loumalouomega** [comment]
It was done that way, indeed the branch is gone, but the code can be seen. I can just be copy paste the old proposal and reopen this

**Pull request closed without merging**
