### PR TITLE
[Core] read materials unique

### PR DESCRIPTION
**Pull request by philbucher**
This PR adds a check if the Materials specified in the json-file are assigned in a unique way.
Implemented both in python and c++

Otherwise they can be overwritten in a non-deterministic order!

several tests are added,

### CODE REVIEW

**Review by loumalouomega — APPROVED** [review]
I hope his does not conflict a lot with subproperties PR

**Comment by philbucher** [comment]
> I hope his does not conflict a lot with subproperties PR

if it does then there is sth wrong with the subprops!
This only makes sure that nothing is overdefined => having overdefined materials would be a bug

**Comment by RiccardoRossi** [comment]
@philbucher even though this is an interesting feature, it changes the behaviour ... so it does not qualify as FastPR ...

**Comment by philbucher** [comment]
@RiccardoRossi I am not sure if this is a feature, I think it is more to prevent overdefining materials, which can easily happen in more complex models => happened to me, debugging this is a pain :/
More complex models in the sense that there is a larger hierarchy of sub-, subsub- etc modelparts

**Comment by RiccardoRossi** [comment]
@philbucher ok, i will take a deep look into this asap ... still... it is not a FastPR ...

**Comment by philbucher** [comment]
@RiccardoRossi sorry for putting FastPR, I honestly thought this is nothing to be looked at in detail

Take your time

**Review by RiccardoRossi — APPROVED** [review]
ok to me.

**Comment by philbucher** [comment]
thx

**Pull request merged**
