### PR TITLE
Core/mp name point

### PR DESCRIPTION
**Pull request by philbucher**
I think it is a good idea to prevent modelparts with "." in the name, this might give problems with the model!
e.g. `SomeModelPartName.ThatIsInvalid` is not allowed

### CODE REVIEW

**Comment by RiccardoRossi** [comment]
i agree ... but i leave this for approval in the next @KratosMultiphysics/technical-committee meeting since it is a changes that affects everyone

**Comment by philbucher** [comment]
any updates @KratosMultiphysics/technical-committee ?

**Comment by philbucher** [comment]
ping

**Comment by RiccardoRossi** [comment]
we will discuss this tomorrow

**Comment by philbucher** [comment]
did you discuss this?

Now that the model is here one can run into quite nasty bugs without this ...

**Review by RiccardoRossi — COMMENTED** [review]
we didn't sorry. on my side i would agree though.

@KratosMultiphysics/technical-committee do you mind if i approve?

**Comment by jcotela** [comment]
I am OK with the change. My only question would be: should we allow spaces?

**Comment by maceligueta** [comment]
The name of the SubModelPart can come from a GUI. People will for sure write spaces eventually. If possible, I would let them use spaces. Forbidding the '.' is already a limitation for them, but we use it as a delimiter.
For me, this PR can be approved.

**Review by jcotela — DISMISSED** [review]

**Comment by philbucher** [comment]
I forgot to update after the Model wass merged, can someone reapprove pls?

**Comment by philbucher** [comment]
regarding the names that are forbidden, we could create a separate issue if there is a need for discussion

**Review by jcotela — APPROVED** [review]
Re-approving. Regarding the names, I do not have a strong opinion either way, I was just thinking out loud.

**Pull request merged**
