### PR TITLE
Adding mapping application to nightly runs

### PR DESCRIPTION
**Pull request by roigcarlo**
I added mapping app to the nightly tests as a petition of @philbucher.

Is everything ok? (Tip: it is!)
Can someone from @KratosMultiphysics/kratos-core-team approve? Normally I would do it myself with this sort of PR but since I issued it...

### CODE REVIEW

**Review by RiccardoRossi — APPROVED** [review]
just one question: doesn't this need mpi?

**Comment by roigcarlo** [comment]
Honestly I don't know.  Does it?

**Comment by philbucher** [comment]
No, it works both with and without mpi

**Comment by roigcarlo** [comment]
Ok then I'll merge it, if it fails we can rollback tomorrow

**Pull request merged**
