### PR TITLE
Fixed error with base pointer holder type in trilinos application

### PR DESCRIPTION
**Pull request by msandre**
This is a fix for a problem detected in the last commit.

### CODE REVIEW

**Review by jcotela — APPROVED** [review]
Thanks @msandre, looks like we skipped a few processes in #2120.

@roigcarlo: was #2120 included in the release branch? If so, we need to merge this there too.

**Comment by roigcarlo** [comment]
Yep #2120 was included. Those are the process I was afraid of missing. Seems that some get through sorry. I will flag this to add to the release, just don't delete the branch after the merge 👍

**Comment by msandre** [comment]
@roigcarlo I left the branch. Can you delete it when you are finished?

**Comment by roigcarlo** [comment]
Sure!

**Pull request merged**
