### PR TITLE
[DEM]update to the benchmarking system.

### PR DESCRIPTION
**Pull request by farrufat-cimne**
Added single and grid compatibility

### CODE REVIEW

**Comment by farrufat-cimne** [comment]
The complete list of benchmarks are included at the end of this message as a quick reference.
DEM Benchmark 7: OK!........ Test 7 SUCCESSFUL (error: 0.0, time: 12.6s.)
DEM Benchmark 1: OK!........ Test 1 SUCCESSFUL (error: 0.4, time: 29.79s.)
DEM Benchmark 2: OK!........ Test 2 SUCCESSFUL (error: 0.13, time: 88.81s.)
DEM Benchmark 9: OK!........ Test 9 SUCCESSFUL (error: 0.97, time: 75.02s.)
DEM Benchmark 6: OK!........ Test 6 SUCCESSFUL (error: 3.38, time: 108.43s.)
DEM Benchmark 4: OK!........ Test 4 SUCCESSFUL (error: 4.63, time: 110.35s.)

==== THORNTON PAPER TESTS. FULL REGIME. HERTZIAN LAW ====

DEM Benchmark 11: OK!........ Test 11 (e=0.25) SUCCESSFUL
DEM Benchmark 8: OK!........ Test 8 SUCCESSFUL (error: 4.16, time: 104.99s.)
DEM Benchmark 11: OK!........ Test 11 (e=0.50) SUCCESSFUL
DEM Benchmark 11: OK!........ Test 11 (e=0.75) SUCCESSFUL

===== THORNTON PAPER TESTS. FULL REGIME. LINEAR LAW =====

DEM Benchmark 10: OK!........ Test 10 (e=0.25) SUCCESSFUL
DEM Benchmark 11: OK!........ Test 11 (e=0.90) SUCCESSFUL
DEM Benchmark 3: OK!........ Test 3 SUCCESSFUL (error: 0.75, time: 151.75s.)
DEM Benchmark 5: OK!........ Test 5 SUCCESSFUL (error: 1.52, time: 152.7s.)


======== DE/FE CONTACT BENCHMARKS ==========

DEM Benchmark 13: OK!........ Test 13 SUCCESSFUL


== BASIC CONTINUUM TESTS ==

DEM Benchmark 20: OK!........ Test 20 SUCCESSFUL
DEM Benchmark 21: OK!........ Test 21 SUCCESSFUL
DEM Benchmark 22: OK!........ Test 22 SUCCESSFUL
DEM Benchmark 23: OK!........ Test 23 SUCCESSFUL
DEM Benchmark 24: OK!........ Test 24 SUCCESSFUL
DEM Benchmark 25: OK!........ Test 25 SUCCESSFUL


===== DISCONTINUUM CLUSTERS TESTS =====

DEM Benchmark 30: OK!........ Test 30 SUCCESSFUL
DEM Benchmark 31: OK!........ Test 31 SUCCESSFUL
DEM Benchmark 14: OK!........ Test 14 SUCCESSFUL
DEM Benchmark 10: OK!........ Test 10 (e=0.50) SUCCESSFUL


==== WENSRICH PAPER TEST. ROLLING FRICTION ====

DEM Benchmark 12: OK!........ Test 12 SUCCESSFUL
DEM Benchmark 16: OK!........ Test 16 SUCCESSFUL
DEM Benchmark 15: OK!........ Test 15 SUCCESSFUL
DEM Benchmark 10: OK!........ Test 10 (e=0.75) SUCCESSFUL
DEM Benchmark 40: OK!........ Test 40_0 SUCCESSFUL (spheres)
DEM Benchmark 40: OK!........ Test 40_1 SUCCESSFUL (spheres)
DEM Benchmark 40: OK!........ Test 40_2 SUCCESSFUL (spheres)
DEM Benchmark 40: OK!........ Test 40_3 SUCCESSFUL (spheres)
DEM Benchmark 40: OK!........ Test 40_4 SUCCESSFUL (spheres)
DEM Benchmark 40: OK!........ Test 40_5 SUCCESSFUL (spheres)
DEM Benchmark 40: OK!........ Test 40_6 SUCCESSFUL (spheres)
DEM Benchmark 40: OK!........ Test 40_7 SUCCESSFUL (spheres)
DEM Benchmark 40: OK!........ Test 40_8 SUCCESSFUL (spheres)
DEM Benchmark 40: OK!........ Test 40_9 SUCCESSFUL (spheres)
DEM Benchmark 40: OK!........ Test 40_10 SUCCESSFUL (spheres)
DEM Benchmark 40: OK!........ Test 40_11 SUCCESSFUL (spheres)
DEM Benchmark 40: OK!........ Test 40_12 SUCCESSFUL (spheres)
DEM Benchmark 40: OK!........ Test 40_13 SUCCESSFUL (spheres)
DEM Benchmark 40: OK!........ Test 40_14 SUCCESSFUL (spheres)
DEM Benchmark 40: OK!........ Test 40_0 SUCCESSFUL (finite elements)
DEM Benchmark 40: OK!........ Test 40_1 SUCCESSFUL (finite elements)
DEM Benchmark 40: OK!........ Test 40_2 SUCCESSFUL (finite elements)
DEM Benchmark 40: OK!........ Test 40_3 SUCCESSFUL (finite elements)
DEM Benchmark 40: OK!........ Test 40_4 SUCCESSFUL (finite elements)
DEM Benchmark 40: OK!........ Test 40_5 SUCCESSFUL (finite elements)
DEM Benchmark 40: OK!........ Test 40_6 SUCCESSFUL (finite elements)
DEM Benchmark 40: OK!........ Test 40_7 SUCCESSFUL (finite elements)
DEM Benchmark 10: OK!........ Test 10 (e=0.90) SUCCESSFUL
DEM Benchmark 32: OK!........ Test 32 SUCCESSFUL
DEM Benchmark 33: OK!........ Test 33 SUCCESSFUL
DEM Benchmark 17: OK!........ Test 17 SUCCESSFUL

**Comment by philbucher** [comment]
@maceligueta are you planning to move your benchmarking-system to the Kratos-testing framework?
I am asking bcs this way it would be easier to check if sth breaks during refactoring e.g. in the Core

**Comment by maceligueta** [comment]
@philbucher . Sure. Long ago we decided to migrate it to the standard way. However, it is low in the list of priorities, plus they take too long to run (8 minutes in my PC) and can't be added to Travis. Can't wait to see if the new CI system can afford them.

**Comment by maceligueta** [comment]
@farrufat-cimne , thanks for the effort. Let me try the branch in Python 2.7 and will approve after that.

**Comment by philbucher** [comment]
> @philbucher . Sure. Long ago we decided to migrate it to the standard way. However, it is low in the list of priorities, plus they take too long to run (8 minutes in my PC) and can't be added to Travis. Can't wait to see if the new CI system can afford them.

sounds good! I realize it is a lot of work
Just to add, there are several suites (small, nightly & validation), depending on how long the test runs you would add it to the corresponding suite

**Comment by maceligueta** [comment]
@philbucher . Yes, actually we have some 'more standard' tests in a different folder that actually run in Travis. We saw those suites. However, the Amazon servers are really slow and even for the nightly runs it would be too much (Charlie needed to increase the time limit short ago because it was failing every night). The new CI will be the trigger for us to migrate to the standard system. We all agree that it's the way to go.

**Review by maceligueta — APPROVED** [review]

**Pull request merged**
