### PR TITLE
[StructuralMechanicsApplication] Adding NORMAL as GP post-process on load conditions

### PR DESCRIPTION
**Pull request by loumalouomega**
This would make easier to debug #4933

### CODE REVIEW

**Review by AlejandroCornejo — DISMISSED** [review]
thx!!

**Review by philbucher — CHANGES_REQUESTED** [review]
Can you please add this to the SurfaceCondition instead of the baseclass?
This cannot be used e.g. with the PointLoad or the PointMomentCondition

**Comment by loumalouomega** [comment]
> Can you please add this to the SurfaceCondition instead of the baseclass?
> This cannot be used e.g. with the PointLoad or the PointMomentCondition

I will add then to the line load and the surface load, sorry i haven't thought on those  conditions (I did it to avoid adding in two conditions doing exactly the same)

**Comment by philbucher** [comment]
Hm I think this would be ok for now, if we need it in more conditions then we can refactor it

Thing is that if you have e.g. SurfaceLoad & PointLoadConditinons in a MP and print the Normal, it will fail because `UnitNormal` throws for the Points

**Comment by loumalouomega** [comment]
Done @philbucher

**Review by philbucher — APPROVED** [review]
Thanks

**Pull request merged**
