### PR TITLE
[FluidDynamics] Using fast test suite by default

### PR DESCRIPTION
**Pull request by marcnunezc**
Switching the default suite when running the cpp tests, to run all Fluid tests. Only the sensitivity tests were selected by default

### CODE REVIEW

**Review by rubenzorrilla — DISMISSED** [review]
So this file was running nothing?

**Comment by marcnunezc** [comment]
It was running the sensitivity tests (13 cpp tests instead of ~60 of the whole suite).

**Comment by philbucher** [comment]
Dont worry, Travis runs then all  :)

**Comment by jcotela** [comment]
I do not think this file should be in the repository at all, but it is already there, so whatever...

In any case you are now not running the sensitivity tests anymore... I would recommend running both suites, one after the other.

**Comment by philbucher** [comment]
Side comments, I would not put the sensitivity tests in a different suite

Either way, I would in the long term also make the c-tests run in `test_App.py`, but this requires some more work (also taking into account the MPI-tests)

**Comment by marcnunezc** [comment]
> I do not think this file should be in the repository at all, but it is already there, so whatever...
> 
> In any case you are now not running the sensitivity tests anymore... I would recommend running both suites, one after the other.

You are right, I thought they were included in the FastSuite.

**Comment by marcnunezc** [comment]
Actually, the sensitvity tests that are run by the SensitivitySuite are the sensitivity tests from the core! 

[here](https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/tests/cpp_tests/utilities/test_sensitivity_builder.cpp) and [here](https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/tests/cpp_tests/utilities/test_geometrical_sensitivity_utility.cpp).

I would say that this file (run_cpp_unit_tests.py) should run only the cpp test from the Fluid right? Im reverting back to only run the FluidDynamicsSuite.

**Comment by rubenzorrilla** [comment]
> I do not think this file should be in the repository at all, but it is already there, so whatever...
> 
> In any case you are now not running the sensitivity tests anymore... I would recommend running both suites, one after the other.

Actually I didn't know about this file. For me makes no sense at all but afaik several applications have it so I'd keep it for the sake of consistency.

**Comment by marcnunezc** [comment]
> > I do not think this file should be in the repository at all, but it is already there, so whatever...
> > In any case you are now not running the sensitivity tests anymore... I would recommend running both suites, one after the other.
> 
> Actually I didn't know about this file. For me makes no sense at all but afaik several applications have it so I'd keep it for the sake of consistency.

I've been using this file (and the equivalent in the CompressiblePotentialFlowApp) to run only the cpp tests when developing something purely in cpp (not saying that for this reason it has to stay, just saying that I thought that was the purpose).

**Comment by marcnunezc** [comment]
Hi all!

This was left open unsolved! 

Do you agree on merging this in order to run the actual cpp FluidDynamics tests (instead of tests from the core) when running the test_FlluidDynamics.py script? 

We can continue the discussion of which test files should be present in the applications in a new issue.

**Comment by rubenzorrilla** [comment]
The point is if we want this file in the repository or not. The changes make sense if it has to be in the FluidDynamicsApplication.

However, I think that this should be customized by each developer according to his necessities.

After reconsidering it and taking into account the simplicity of the script, I'd be in favor of removing the file.

**Comment by jcotela** [comment]
I fully agree with @rubenzorrilla's view on this.

**Comment by marcnunezc** [comment]
Hi!
I see!
Does this include the `test_FluidDynamicsApplications.py` file or only the `run_cpp_unit_test.py` file?

If so, shall we do the removal here or would you rather do it yourself?

**Comment by rubenzorrilla** [comment]
> Hi!
> I see!
> Does this include the `test_FluidDynamicsApplications.py` file or only the `run_cpp_unit_test.py` file?
> 
> If so, shall we do the removal here or would you rather do it yourself?

This only concerns the `run_cpp_unit_test.py`. We can take the chance to do it in this PR.

**Comment by marcnunezc** [comment]
Hi,

As discussed, I removed the `run_cpp_unit_tests.py` file and updated the test_Fluid....py file accordingly to run the fluid cpp tests along the python tests.

**Review by philbucher — COMMENTED** [review]
looks good to me, approval I leave to @KratosMultiphysics/fluid-dynamics 

Just for the record, my idea for the better integration of the C-tests also goes in this direction

**Review by rubenzorrilla — APPROVED** [review]

**Pull request merged**
