### PR TITLE
Moving to initial configuaration and moving back to current

### LINKED ISSUE #1492: Problem in TotalStructuralMassProcess
I use the new process to calculate the mass of my case
The problem I had was that I get different results before and after the calculation. This is because the Geometry functions (e.g. `Length`, `Area` etc) always refer to the current configuration, which in a problem for this process.
I am not sure how to solve this but I think we should be aware of this problem.

@KratosMultiphysics/technical-committee  maybe it would be good to have for these functions also the Initial-Configuration Counterpart. I think this would also be useful for other applications.

### PR DESCRIPTION
**Pull request by loumalouomega**
Fixes #1492

### CODE REVIEW

**Comment by philbucher** [comment]
Thx!
I am testing it now

Btw what do you think abt removing the unit from the print? In case the density is not defined in m³/kg the print is wrong

=> `std::cout << "The total mass of the system is: " << total_mass << "\nCheck variable NODAL_MASS in the process info in order to access to it in any moment" << std::endl;`

**Comment by loumalouomega** [comment]
Well I assume we work in IS, something that is consistent with the rest of the code

**Comment by philbucher** [comment]
I think the code does not assume IS

I recommend to remove it, but it is up to you

It works btw, thx for fixing it

**Review by philbucher — APPROVED** [review]

**Comment by loumalouomega** [comment]
I can remove it in #1481 if that satisfies you

**Comment by philbucher** [comment]
thx :D

**Pull request merged**
