### PR TITLE
[PythonSolver] adding option for reorder_consecutive

### PR DESCRIPTION
**Pull request by philbucher**
Esp useful for testing in MPI => then the reference result files will have the same node-ids
needed bcs the partitioners in MPI have to reorder the Ids

### CODE REVIEW

**Review by RiccardoRossi — DISMISSED** [review]

**Comment by RiccardoRossi** [comment]
oops, i just realized that this might be in conflict with the work on mpi_io done by @roigcarlo .

Carlos, could u take a quick look to be sure this dosn't break anything?

**Comment by philbucher** [comment]
@roigcarlo I couldn't find a branch that has a name indicating the mentioned changes.
If you don't have time then could you tell me the name of the branch such that I can check myself?

@RiccardoRossi I am modifying the serial version here, has nothing to do with MPI ...

**Comment by roigcarlo** [comment]
I think its ok, @RiccardoRossi speaks about the memory partitioner I think, but that one is only for trilinos.

Just run the trilinos tests to be sure but should be safe.

**Comment by philbucher** [comment]
I am quite convinced that this is completely unrelated but I will run the tests nevertheless :)

**Comment by philbucher** [comment]
except the tests also failing in Master (see #3694 ) everything works

**Comment by philbucher** [comment]
can I get an approval pls?

**Comment by philbucher** [comment]
anyone?

**Review by roigcarlo — APPROVED** [review]

**Pull request merged**
