### PR TITLE
[DEM] improve free body motion

### PR DESCRIPTION
**Pull request by joaquinirazabal**
Some problems have been fixed when a velocity start and stop is assigned to a rigid body. Moreover, the possibility of applying external forces and moments from the python script is included.

### CODE REVIEW

**Review by maceligueta — APPROVED** [review]

**Comment by maceligueta** [comment]
Do we have tests of this? If not, let us know, @joaquinirazabal , and we'll find the time to add some.

**Comment by joaquinirazabal** [comment]
No, we don't have tests of this, I came through those problems in my calculations. It would be great to have some!

**Comment by maceligueta** [comment]
Just referencing @farrufat-cimne  to be aware of this.

**Comment by joaquinirazabal** [comment]
Merged

**Pull request merged**
