### PR TITLE
[Core][BruteForcePointLocator] expose search tolerance

### PR DESCRIPTION
**Pull request by philbucher**
This PR exposes the search tolerance such that it can be set from outside

Furthermore it adds warnings in case there are no entities to search (e.g if I want to find an element but there are no elements in the ModelPart that I gave as input)

### CODE REVIEW

**Comment by philbucher** [comment]
@jcotela unfortunately this has a minor conflict with #4852 but only in one line
Since I copied and used your implementation from #4852 it might not even be a conflict

**Comment by philbucher** [comment]
ping @AndreasWinterstein

**Comment by pooyan-dadvand** [comment]
Just to mention that in #4928 we have take the tolerance as relative from input and scaling it with the characteristic size of the domain

**Review by AndreasWinterstein — COMMENTED** [review]
For me this works.
What about the comment of @pooyan-dadvand ?

**Comment by philbucher** [comment]
These are local tolerances so no need to scale them :)

**Review by rubenzorrilla — APPROVED** [review]

**Pull request merged**
