### PR TITLE
[ContactStructuralMechanicsApplication] Adding name to license

### PR DESCRIPTION
**Pull request by loumalouomega**

### CODE REVIEW

**Comment by AlejandroCornejo** [comment]
image

**Review by AlejandroCornejo — APPROVED** [review]
As we agreed, ok

**Comment by philbucher** [comment]
2 questions, why do you remove Mohamed? And why does contact need a separate license?

**Comment by loumalouomega** [comment]
> 2 questions, why do you remove Mohamed? And why does contact need a separate license?

@RiccardoRossi that the license can just have two names. @AlejandroCornejo is going to start to work with the application. The individual files keep the authorship, that's not changing

**Comment by loumalouomega** [comment]
> And why does contact need a separate license?

Well, why not?

**Comment by philbucher** [comment]
Unnecessary duplication if it is the same as the core one ?
I mean, you decide, just wondering

**Comment by loumalouomega** [comment]
> Unnecessary duplication if it is the same as the core one ?
> I mean, you decide, just wondering

I can add a Beerware clause...

**Pull request merged**
