### PR TITLE
Feature bin based locator conditions

### PR DESCRIPTION
**Pull request by adityaghantasala**
This PR adds a new bin based locator on conditions and corresponding configure.
Adds the following files :  

- bin_based_fast_point_locator_on_conditions.h  which is exactly bin_based_fast_point_locator using conditions. 

- spatial_containers_conditions_configure.h which is exactly spatial_containers_configure.h which internally use conditions.

### CODE REVIEW

**Review by loumalouomega — CHANGES_REQUESTED** [review]
Please don't create a new utility hardcopying the code, use templates or expand the current code

**Comment by adityaghantasala** [comment]
@loumalouomega  I tried .. in this case it was not possible because of the use of container types from modelpart class. There is this usage in spatial_containers_configure.h for which I did not find any solution .. can you suggest how to proceed in this case ?

**Comment by loumalouomega** [comment]
Yes, we need to add a template definition to spatial_containers_configure.h instead of hardcoding the a copy

**Comment by loumalouomega** [comment]
Besides you are not adding a test, if some day the code is broken how are we going to know when happened?, imagine that even with the current existing tests we have problems to detect problems, @bodhinandach  is having problems with the binbased and he had test for that. Copying entirely methods and functions is dangerous because is very error prone

**Comment by loumalouomega** [comment]
I opened a PR with an alternative design

**Comment by adityaghantasala** [comment]
@jcotela  @roigcarlo  I am closing this, we can discuss and follow the other PR made by @loumalouomega

**Pull request closed without merging**
