### PR TITLE
[StructuralMechanicsApplication] Doing the optimization pending 4 years

### PR DESCRIPTION
**Pull request by loumalouomega**
**Description**
Doing the optimization pending 4 years

**Changelog**
- Doing the optimization pending 4 years

### CODE REVIEW

**Comment by philbucher** [comment]
I don't know this 
maybe someone that has experience in this can take a look?

@KlausBSautter @RiccardoRossi ?

**Comment by KlausBSautter** [comment]
hi, I leave this to someone else. I do not know how to review this

**Comment by philbucher** [comment]
ping @RiccardoRossi

**Comment by loumalouomega** [comment]
Ping @RiccardoRossi

**Comment by loumalouomega** [comment]
imagen

**Review by rubenzorrilla — APPROVED** [review]
These are equivalent.

However, while checking, I came across with this https://github.com/KratosMultiphysics/Kratos/blob/cfe30570594cd796ddb699db38be438ecff9fc29/kratos/utilities/math_utils.h#L1649-L1650
Shouldn't it be?
```c++
        const SizeType size1 = rB.size1();
        const SizeType size2 = rB.size2();
```

**Comment by loumalouomega** [comment]
> These are equivalent.
> 
> However, while checking, I came across with this
> 
> https://github.com/KratosMultiphysics/Kratos/blob/cfe30570594cd796ddb699db38be438ecff9fc29/kratos/utilities/math_utils.h#L1649-L1650
> 
> Shouldn't it be?
> 
> ```c++
>         const SizeType size1 = rB.size1();
>         const SizeType size2 = rB.size2();
> ```

Nope, it is a very particular multiplication, it is like that.

**Comment by rubenzorrilla** [comment]
> > These are equivalent.
> > However, while checking, I came across with this
> > https://github.com/KratosMultiphysics/Kratos/blob/cfe30570594cd796ddb699db38be438ecff9fc29/kratos/utilities/math_utils.h#L1649-L1650
> > 
> > Shouldn't it be?
> > ```c++
> >         const SizeType size1 = rB.size1();
> >         const SizeType size2 = rB.size2();
> > ```
> 
> Nope, it is a very particular multiplication, it is like that.

OK. I didn't went through it. I just checked that the arguments were correct. Thanks!

**Pull request merged**
