### PR TITLE
[FastPR][Core][PFEM2] VOLUMETRIC_STRAIN migration from PFEM2 to Core

### PR DESCRIPTION
**Pull request by rubenzorrilla**
We need a nodal variable to store the volumetric strain. I realise that there already exists a `VOLUMETRIC_STRAIN` in the `pfem_2_application` so I migrated it to the core. Aside of this, I think that it could be useful for future developments.

@miguelmaso AFAIK you are the most active developer of the `pfem_2_application` so I'm tagging you. If you think I forgot to tag someone please let me know.

### CODE REVIEW

**Review by miguelmaso — APPROVED** [review]
All right

**Comment by miguelmaso** [comment]
Maybe @dcagri and @juliobarna are interested. You can go ahead

**Comment by philbucher** [comment]
Do you need it in the core?

**Comment by dcagritan** [comment]
There is no problem by my side.

**Comment by rubenzorrilla** [comment]
> Do you need it in the core?

I think it is something general enough to be in the core.

**Comment by philbucher** [comment]
personally I would try to avoid adding more variables to the core unless they are used there as there are a lot of them existing already
my opinion though, please go ahead if you think it makes sense to have it in the core

**Comment by rubenzorrilla** [comment]
> personally I would try to avoid adding more variables to the core unless they are used there as there are a lot of them existing already
> my opinion though, please go ahead if you think it makes sense to have it in the core

I'm aware of it but in this case I think that it really makes sense since the `VOLUMETRIC_STRAIN` can be used in any fluid or structure formulation in Kratos, something that represents a wide range of applicability.

Aside of this, I think we should start thinking in the other way around. I mean to migrate variables from the core to their proper application, despite the changes in this direction are way more painful than in the opposite one :disappointed:

**Comment by philbucher** [comment]
makes sense!
please go ahead then

(I already have a list of vars I would like to move but did not have the time yet)

**Pull request merged**
