### PR TITLE
[CI] Adding Rocky image build to CI

### PR DESCRIPTION
**Pull request by loumalouomega**
**📝 Description**

Adding Rocky image build to CI

**🆕 Changelog**

- [Adding Rocky image build to CI](https://github.com/KratosMultiphysics/Kratos/commit/aec00c38d04b4ff1823f841178cc0e2166ebf419)

### CODE REVIEW

**Review by roigcarlo — COMMENTED** [review]
:+1:  But wait approval until I build the image and we can test it pls :pray:

**Comment by loumalouomega** [comment]
Ci is broken :P

**Comment by roigcarlo** [comment]
#12891

**Comment by loumalouomega** [comment]
What is the status of this @roigcarlo ?

**Comment by roigcarlo** [comment]
On it, its top of the list but still didn't have time.

**Comment by loumalouomega** [comment]
Huum, Centos Ci is still there?

**Comment by roigcarlo** [comment]
mm odd, let me see

**Comment by roigcarlo** [comment]
Yep the one governing the Centos build is unchanges, you modified the workflow that autobuilds de CI image

**Comment by loumalouomega** [comment]
> Yep the one governing the Centos build is unchanges, you modified the workflow that autobuilds de CI image

ah, sorry

**Comment by loumalouomega** [comment]
@roigcarlo I just realized that in our installations Boost is installed manually so I installed in the DokerFile the boost as well, for the moment in order to check that the Rocky image works in the other PR I will manually download the boost, but eventually we should update the image (IMO)

**Comment by roigcarlo** [comment]
With #12936 merged we can close this one right?

**Comment by loumalouomega** [comment]
> With #12936 merged we can close this one right?

Nope, https://github.com/KratosMultiphysics/Kratos/pull/12937 can be closed, but this one is to build the Image

**Review by roigcarlo — APPROVED** [review]
Ok, anyway sees that win is failing, I just set it to rerun, seems fault of MPM

**Pull request merged**
