### PR TITLE
[Core] Improving CSR interface and low overhead conversion to PETSc

### PR DESCRIPTION
**Pull request by RiccardoRossi**
**📝 Description**
Provide copy free access to indices and values_vector and a low overhead interface to PETSC matrix.

Interface is in python only so no compile dependency is added. Dependency at runtime is needed only if one explicitly imports the feature

**🆕 Changelog**
- Provide copy free access to indices and values_vector and a low overhead interface to PETSC matrix.

### CODE REVIEW

**Review by loumalouomega — CHANGES_REQUESTED** [review]
No test?

**Comment by RiccardoRossi** [comment]
no ... i do not want to add the dependency

**Comment by loumalouomega** [comment]
> no ... i do not want to add the dependency

Okay, but you can add one and use the decorator to skip the test

**Review by loumalouomega — APPROVED** [review]

**Comment by RiccardoRossi** [comment]
and btw, the methods were already present and are used in some of the tests, for example for the scipy conversion. the difference is that now they do not do a copy

**Pull request merged**
