### PR TITLE
Core/fix file deletion mpi

### LINKED ISSUE #2169: When compiling KratosMPI, Python test ends with a Segfault.
I compiled kratos with
`-DMPI_NEEDED=ON`
Then I ran a Python Unit Test of the DEM Application. At the end of the test, it showed a Segmentation Fault.
Then I ran a regular case of the DEM Application and everything was fine.
I deleted the file `libs/mpipython.so`. Then all tests ran without problems.

### PR DESCRIPTION
**Pull request by philbucher**
As discussed with @roigcarlo I removed the trial import of KratosMPI which seems to give problems, see #2169 

The new solution works without any mpi

@sunethwarna I think you were using the comparisonprocess in MPI right?
On my machine the mpi tests in the FluidDynamicsApp run, but you could also take a look

fixes #2169

### CODE REVIEW

**Comment by maceligueta** [comment]
I just tried the DEM tests and now they do not SegFault. Looks good to me.

**Comment by philbucher** [comment]
van I get an approval pls? :)

**Comment by philbucher** [comment]
ping @maceligueta

**Review by roigcarlo — APPROVED** [review]

**Comment by philbucher** [comment]
thx

**Pull request merged**
