### PR TITLE
Fix blames

### PR DESCRIPTION
**Pull request by roigcarlo**
…create-hist-divergence

### CODE REVIEW

**Comment by roigcarlo** [comment]
This should trick git into thinking that the files deleted existed in other branch in that time so blame should work. 

this way we don't need to rebase anything :D

Can you check it before merge?.
It does basically nothing but I had conflicts in one test so maybe I re-added something that someone deleted.

**Comment by pooyan-dadvand** [comment]
@loumalouomega it seems that all the conflicts are in your tests. So please check your tests after merge

**Comment by loumalouomega** [comment]
I had many conflicts with the tests too, but the diff was empty, a false
positive

**Comment by roigcarlo** [comment]
@pooyan-dadvand Thumbs up?

**Review by pooyan-dadvand — APPROVED** [review]
:+1:

**Pull request merged**
