### PR TITLE
[Core] Reorder generate triangle edge/tetrahedra face

### LINKED ISSUE #7148: geometry.GenerateFaces() numbering convention
Dear all,

As far as I understand, GenerateFaces (3D tetrahedral elements and GenerateEdges for 2D triangular elements) use the following convention for numbering
Face 0: nodes 0, 2, 1
Face 3: nodes 2, 3, 1

https://github.com/KratosMultiphysics/Kratos/blob/617f45ecf0fba902aee5f7685df5ddcada36cb17/kratos/geometries/tetrahedra_3d_4.h#L1132

It seems inconsistent with the node based numbering used for (e.g.) NEIGHBOUR_ELEMENTS. In the latter case, the first neighbouring element is in front of node 0 (expected face 0 but being in fact face 3). 

Is this numbering intentionally chosen for GenerateFaces?

### PR DESCRIPTION
**Pull request by loumalouomega**
Fixes #7148

This just reorders following the criteria of the neighbouring

### CODE REVIEW

**Comment by loumalouomega** [comment]
@miguelmaso the test failing is yours, can you check what is happening?

**Comment by mrhashemi** [comment]
Perfect.

**Review by mrhashemi — DISMISSED** [review]

**Comment by philbucher** [comment]
please wait for approval of @RiccardoRossi, this is a behavior change in the core after all

**Comment by miguelmaso** [comment]
> @miguelmaso the test failing is yours, can you check what is happening?

The utility was failing because uses the edges to generate sub triangles.

Initial triangles:
initial_triangles

Expected triangles:
expected_triangles

Obtained triangles:
triangles

**Comment by miguelmaso** [comment]
Now it's fixed

**Comment by miguelmaso** [comment]
I've found another bug, but I will fix it in another PR

**Comment by loumalouomega** [comment]
Reapproval is required @RiccardoRossi

**Comment by loumalouomega** [comment]
> Reapproval is required @RiccardoRossi

Ping @RiccardoRossi

**Comment by loumalouomega** [comment]
> > Reapproval is required @RiccardoRossi
> 
> Ping @RiccardoRossi

Ping @RiccardoRossi

**Comment by loumalouomega** [comment]
> > > Reapproval is required @RiccardoRossi
> > 
> > 
> > Ping @RiccardoRossi
> 
> Ping @RiccardoRossi

Ping @RiccardoRossi

**Comment by loumalouomega** [comment]
> > > > Reapproval is required @RiccardoRossi
> > > 
> > > 
> > > Ping @RiccardoRossi
> > 
> > 
> > Ping @RiccardoRossi
> 
> Ping @RiccardoRossi

Ping @RiccardoRossi

**Review by mrhashemi — APPROVED** [review]

**Comment by philbucher** [comment]
> please wait for approval of @RiccardoRossi, this is a behavior change in the core after all

Why did you merge?
This is a behavior change in the core!

**Comment by loumalouomega** [comment]
> > please wait for approval of @RiccardoRossi, this is a behavior change in the core after all
> 
> Why did you merge?
> This is a behavior change in the core!

Do I revert?

**Comment by philbucher** [comment]
For me is ok but please wait in the future 
I know myself very very well that it is super frustrating having to wait so long
But the Core is used my everyone and thats why it is good to having ppl with more experience look over it

**Comment by loumalouomega** [comment]
> For me is ok but please wait in the future
> I know myself very very well that it is super frustrating having to wait so long
> But the Core is used my everyone and thats why it is good to having ppl with more experience look over it

Sorry I forgot this was behavior change, i just saw the approval and I merged without remembering that

**Pull request merged**
