### PR TITLE
[fluid] Warnings removal

### PR DESCRIPTION
**Pull request by maceligueta**

### CODE REVIEW

**Review by jcotela — APPROVED** [review]
OK, but what warning is this fixing?

**Comment by maceligueta** [comment]
Very similar to that one pasted in #2576

**Comment by jcotela** [comment]
Also related to the Pybind macros? If so I'd also be concerned we are just hiding some deeper error.

**Comment by maceligueta** [comment]
This is the actual warning in the External Solvers Application:
```
In file included from /usr/include/python2.7/Python.h:8:0,
                 from /home/maceli/kratos/external_libraries/pybind11/detail/common.h:111,
                 from /home/maceli/kratos/external_libraries/pybind11/pytypes.h:12,
                 from /home/maceli/kratos/external_libraries/pybind11/cast.h:13,
                 from /home/maceli/kratos/external_libraries/pybind11/attr.h:13,
                 from /home/maceli/kratos/external_libraries/pybind11/pybind11.h:43,
                 from /home/maceli/kratos/kratos/python/add_linear_solvers_to_python.h:21,
                 from /home/maceli/kratos/applications/ExternalSolversApplication/custom_python/add_linear_solvers_to_python.cpp:22:
/usr/include/python2.7/pyconfig.h:1193:0: warning: "_POSIX_C_SOURCE" redefined
 #define _POSIX_C_SOURCE 200112L
 ^
In file included from /usr/include/c++/5/x86_64-suse-linux/bits/os_defines.h:39:0,
                 from /usr/include/c++/5/x86_64-suse-linux/bits/c++config.h:2255,
                 from /usr/include/c++/5/complex:41,
                 from /home/maceli/kratos/applications/ExternalSolversApplication/custom_python/add_linear_solvers_to_python.cpp:16:
/usr/include/features.h:225:0: note: this is the location of the previous definition
 # define _POSIX_C_SOURCE 200809L
 ^
In file included from /usr/include/python2.7/Python.h:8:0,
                 from /home/maceli/kratos/external_libraries/pybind11/detail/common.h:111,
                 from /home/maceli/kratos/external_libraries/pybind11/pytypes.h:12,
                 from /home/maceli/kratos/external_libraries/pybind11/cast.h:13,
                 from /home/maceli/kratos/external_libraries/pybind11/attr.h:13,
                 from /home/maceli/kratos/external_libraries/pybind11/pybind11.h:43,
                 from /home/maceli/kratos/kratos/python/add_linear_solvers_to_python.h:21,
                 from /home/maceli/kratos/applications/ExternalSolversApplication/custom_python/add_linear_solvers_to_python.cpp:22:
/usr/include/python2.7/pyconfig.h:1215:0: warning: "_XOPEN_SOURCE" redefined
 #define _XOPEN_SOURCE 600
 ^
In file included from /usr/include/c++/5/x86_64-suse-linux/bits/os_defines.h:39:0,
                 from /usr/include/c++/5/x86_64-suse-linux/bits/c++config.h:2255,
                 from /usr/include/c++/5/complex:41,
                 from /home/maceli/kratos/applications/ExternalSolversApplication/custom_python/add_linear_solvers_to_python.cpp:16:
/usr/include/features.h:166:0: note: this is the location of the previous definition
 # define _XOPEN_SOURCE 700
 ^
```

**Comment by maceligueta** [comment]
And this is the actual warning in the Fluid Dynamics Application:

```
In file included from /usr/include/python2.7/Python.h:8:0,
                 from /home/maceli/kratos/external_libraries/pybind11/detail/common.h:111,
                 from /home/maceli/kratos/external_libraries/pybind11/pytypes.h:12,
                 from /home/maceli/kratos/external_libraries/pybind11/cast.h:13,
                 from /home/maceli/kratos/external_libraries/pybind11/attr.h:13,
                 from /home/maceli/kratos/external_libraries/pybind11/pybind11.h:43,
                 from /home/maceli/kratos/applications/FluidDynamicsApplication/custom_python/add_custom_utilities_to_python.h:20,
                 from /home/maceli/kratos/applications/FluidDynamicsApplication/custom_python/add_custom_utilities_to_python.cpp:25:
/usr/include/python2.7/pyconfig.h:1193:0: warning: "_POSIX_C_SOURCE" redefined
 #define _POSIX_C_SOURCE 200112L
 ^
In file included from /usr/include/c++/5/x86_64-suse-linux/bits/os_defines.h:39:0,
                 from /usr/include/c++/5/x86_64-suse-linux/bits/c++config.h:2255,
                 from /usr/include/c++/5/string:38,
                 from /home/maceli/kratos/kratos/includes/model_part.h:22,
                 from /home/maceli/kratos/applications/FluidDynamicsApplication/custom_python/add_custom_utilities_to_python.cpp:23:
/usr/include/features.h:225:0: note: this is the location of the previous definition
 # define _POSIX_C_SOURCE 200809L
 ^
In file included from /usr/include/python2.7/Python.h:8:0,
                 from /home/maceli/kratos/external_libraries/pybind11/detail/common.h:111,
                 from /home/maceli/kratos/external_libraries/pybind11/pytypes.h:12,
                 from /home/maceli/kratos/external_libraries/pybind11/cast.h:13,
                 from /home/maceli/kratos/external_libraries/pybind11/attr.h:13,
                 from /home/maceli/kratos/external_libraries/pybind11/pybind11.h:43,
                 from /home/maceli/kratos/applications/FluidDynamicsApplication/custom_python/add_custom_utilities_to_python.h:20,
                 from /home/maceli/kratos/applications/FluidDynamicsApplication/custom_python/add_custom_utilities_to_python.cpp:25:
/usr/include/python2.7/pyconfig.h:1215:0: warning: "_XOPEN_SOURCE" redefined
 #define _XOPEN_SOURCE 600
 ^
In file included from /usr/include/c++/5/x86_64-suse-linux/bits/os_defines.h:39:0,
                 from /usr/include/c++/5/x86_64-suse-linux/bits/c++config.h:2255,
                 from /usr/include/c++/5/string:38,
                 from /home/maceli/kratos/kratos/includes/model_part.h:22,
                 from /home/maceli/kratos/applications/FluidDynamicsApplication/custom_python/add_custom_utilities_to_python.cpp:23:
/usr/include/features.h:166:0: note: this is the location of the previous definition
 # define _XOPEN_SOURCE 700
 ^
```

**Comment by jcotela** [comment]
looks like your python is not compatible with your C++ compilation... (the conflicting files are /usr/include/features.h, from the C++ compiler and /usr/include/python2.7/pyconfig.h from the Python headers). 

This comment in my features.h might be relevant:
```
   The `-ansi' switch to the GNU C compiler, and standards conformance
   options such as `-std=c99', define __STRICT_ANSI__.  If none of
   these are defined, or if _DEFAULT_SOURCE is defined, the default is
   to have _POSIX_SOURCE set to one and _POSIX_C_SOURCE set to
   200809L, as well as enabling miscellaneous functions from BSD and
   SVID.  If more than one of these are defined, they accumulate.  For
   example __STRICT_ANSI__, _POSIX_SOURCE and _POSIX_C_SOURCE together
   give you ISO C, 1003.1, and 1003.2, but nothing else.
```
I guess that some of these compile flags are not compatible with the python installation (because the python header assumes a different set of values for these macros).

**Comment by jcotela** [comment]
Note that I do not object to the changes, I just don't understand why changing the include order fixes the warnings. I also have no idea of what set of macros your compiler ends up using in either case.

**Comment by maceligueta** [comment]
Changing the order fixes the warning because one of the files has an `#ifdef` and the other one doesn't.
I don't really know the importance of this macro either...

**Comment by maceligueta** [comment]
I'll merge. Do not hesitate to re-open the discussion if you guys think that it is necessary. I did not notice anything weird in the behavior of the code so far.

**Pull request merged**
