### PR TITLE
Enable RANS in Windows CI

### PR DESCRIPTION
**Pull request by roigcarlo**
**Description**
Enable RANs in CI for windows. Hopefully this will not have cache problems, if it does I will fix it in this same PR

**Changelog**
- Enables RANS ci

### CODE REVIEW

**Comment by sunethwarna** [comment]
It still fails :/ @roigcarlo

**Comment by roigcarlo** [comment]
Yep, looking into it :S, seems it was not the cache

**Comment by roigcarlo** [comment]
Seems that it was not a cache problem after all. The name of the Application.so had a unwanted prefix because it was cotired bfore changing the name, so the install instruction was looking for something else. I've have changed the cmake to it behaves like the rest of apps.

**Comment by roigcarlo** [comment]
@sunethwarna Seems that now is working but all windows test for the RANS fail. Any idea? (I can confirm it also happens in my machine)

**Comment by sunethwarna** [comment]
I also checked the log file, It is really strange. My first guess is something related to #7574 or something like that with msvc compilers. I am not sure how I can check it. I'll also think of a way to test this in windows. Thanks a lot for everythin @roigcarlo.

**Comment by roigcarlo** [comment]
@sunethwarna I am quite conviced that the problem is the random number generator that you are using. 
If I understand the code correctly, you are using the "node id + string + variable name" as a seed.

According to various sources, std random number generator and specifically the `default_random_engne` (but also possibly the `std::seq_seed`) is platform dependant, so all results are going to change when changing SO, I would expect the same to happen in mac (More on that [here](http://anadoxin.org/blog/c-shooting-yourself-in-the-foot-4.html))

I would say that best change is to initialize your tests with deterministic values, which is what we do with the other tests, so we can deterministically ensure that initial conditions are the same.

**Comment by sunethwarna** [comment]
@roigcarlo thanks for this... I'll change it here in this PR :)

**Comment by sunethwarna** [comment]
Hi @roigcarlo, I changed the random number generator, now those tests pass, but then some of the other tests fail due to unreachable directory. I have no clue how the folder structure should look like in windows. Could you please have a look when you have time?

**Comment by roigcarlo** [comment]
There is something odd with the dirs, 
It appears that it is looking the reference files in:
`D:\\a\\Kratos\\Kratos\\bin\\Custom\\KratosMultiphysics\\tests\\ChannelFlowTest`
but that should be located in:
`D:\\a\\Kratos\\Kratos\\bin\\Custom\\applications\RANSApplication\\tests\\ChannelFlowTest`

I suppose that `test_folder = os.path.join("..", "tests", work_folder)` is getting the bad location because the utility lives in the scripts folder of the app, not in the tests directory. Not sure how you manage to make it work in linux but I suspect the problem is that.

Changing this or moving the test_utility to the tests should fix it.

**Comment by sunethwarna** [comment]
> I suppose that test_folder = os.path.join("..", "tests", work_folder) is getting the bad location because the utility lives in the scripts folder of the app, not in the tests directory. Not sure how you manage to make it work in linux but I suspect the problem is that.

No idea :|, It was working, so i let it (I thought `__file__` should give the actual path where file resides, at least i think it does it in linux. Not sure what is happening in windows )

**Comment by sunethwarna** [comment]
@roigcarlo Finally it is passing all the tests.... Thank a lot :) ...

can some one approve please?

**Review by philbucher — APPROVED** [review]
awesome thx guys!

**Pull request merged**
