### PR TITLE
non-linear term linearized using velocity from the previous step

### PR DESCRIPTION
**Pull request by ddiezrod**
@jcotela As we discussed, using velocity from previous step allows us to solve "instability" problems related to the predict step when only 1 non linear iteration is run.

### CODE REVIEW

**Comment by jcotela** [comment]
@pooyan-dadvand @RiccardoRossi: @ddiezrod and myself are happy with the changes on this branch, but I'd rather not approve it myself after contributing significantly to it. Can you take a look?

**Comment by ddiezrod** [comment]
@RiccardoRossi @pooyan-dadvand  Can any of you please review this PR?

**Review by pooyan-dadvand — APPROVED** [review]
:+1: 

I agree with @jcotela that there are a lot of boiler plate in an empty element.....

**Comment by ddiezrod** [comment]
@pooyan-dadvand I understand, but we did not find any other way to do it. Suggestions are welcome...

**Comment by pooyan-dadvand** [comment]
I know that @ddiezrod , it was a comment for myself!

**Pull request merged**
