### PR TITLE
remove super arguments from StructuralMechanicsApplication

### PR DESCRIPTION
**Pull request by matekelemen**
Update base class member function calls to python3 syntax (by removing arguments from super) in StructuralMechanicsApplication.

### CODE REVIEW

**Review by loumalouomega — APPROVED** [review]
I thought that this was python 3, @philbucher ?

**Review by loumalouomega — CHANGES_REQUESTED** [review]
Blocking just in case

**Comment by mpentek** [comment]
> I thought that this was python 3, @philbucher ?

@loumalouomega this PR was discussed with Philipp and Mate. It is exactly going to pure python3 syntax by removing the parameters passed to the super() call. So could you please clarify what you first approved than blocked? Perhaps there is a misunderstanding. Philipp is on holiday until next week.

**Review by loumalouomega — APPROVED** [review]

**Comment by philbucher** [comment]
as @mpentek says
@matekelemen works for us (@mpentek and me), all his PRs are agreed and discussed beforehand

@loumalouomega the `super` syntax becomes easier with python3, this is basically what this PR is :)

**Review by philbucher — APPROVED** [review]
thx @matekelemen

**Pull request merged**
