### PR TITLE
[Core] cleaning includes II

### PR DESCRIPTION
**Pull request by philbucher**
some includes were cleaned.
Especially the include of ModelPart was moved to source-files if possible, since this is quite a heavy include

### CODE REVIEW

**Review by RiccardoRossi — CHANGES_REQUESTED** [review]
guus, we already discussed this also with popyan.

we do not agree on using forward declaration this way

**Review by RiccardoRossi — CHANGES_REQUESTED** [review]
guys, we already discussed this also with popyan.

we do not agree on using forward declaration this way

**Comment by philbucher** [comment]
Could you please briefly tell why?

**Comment by RiccardoRossi** [comment]
https://google.github.io/styleguide/cppguide.html

i agree about this.

also my peronal point of view is that using includes obliges one to a tidier structure

just for curiosity, since we cannot use for now, but the proble of compilation time and with includes has been addressed by c++20 modules (approved to be in the standard about 15 days ago)

**Comment by loumalouomega** [comment]
> [google.github.io/styleguide/cppguide.html](https://google.github.io/styleguide/cppguide.html)
> 
> i agree about this.
> 
> also my peronal point of view is that using includes obliges one to a tidier structure
> 
> just for curiosity, since we cannot use for now, but the proble of compilation time and with includes has been addressed by c++20 modules (approved to be in the standard about 15 days ago)

C++20, so I assume will be used here in 6 years?

**Comment by philbucher** [comment]
I have no problem with closing this but @pooyan-dadvand @RiccardoRossi you have to acknowledge that each time we change sth that is included in `ModelPart` (many things!) we basically have to recompile Kratos bcs `ModelPart` is included in many places ( even some elements ;) ) 

I already now think that we have many (probably too many) dependencies in the code
We have to be careful, otherwise this will blow up even more and this makes development very tedious.

I will add this to the @KratosMultiphysics/technical-committee project to at least briefly discuss this in person

> > [google.github.io/styleguide/cppguide.html](https://google.github.io/styleguide/cppguide.html)
> > i agree about this.
> > also my peronal point of view is that using includes obliges one to a tidier structure
> > just for curiosity, since we cannot use for now, but the proble of compilation time and with includes has been addressed by c++20 modules (approved to be in the standard about 15 days ago)
> 
> C++20, so I assume will be used here in 6 years?

if we are lucky :laughing:

**Comment by RiccardoRossi** [comment]
hi Vicente,

modules were approved now for c++20 which will go official in february next year.

so far we have been very slow at allowing use of new standards, so it looks like we will not be able to take full advantage of them for quite a while (the blocker to adopt new standards is that for example now we need to compile kratos as far back as redhat 6.5, which is already nontrivial)

the good news is that the std lub will start using modules internally much faster, so compiles times should hopefulky go down because of this already over the next few years

**Comment by RiccardoRossi** [comment]
@philbucher

your observation actually showcases my objection to the use of forward declaration.

if you change the modelpart (changing the inclides is equivalent if you have inline functions) YOU NEED TO ENSURE that everything that includes the modelpart is recompiled. if this is not guaranteed by using the forward declaration then to me it is an excellent reason for not allowing it.
i am also very afraid on the use of forward declaration when we go across compilation units (for example different applications)

**Comment by loumalouomega** [comment]
If the problem is modify the model_part.h I would move all the methods to the cpp. Then it will be a problem only when new methods are added (or removed)

**Comment by RiccardoRossi** [comment]
the point is that template and inlone methods should be left in the header

**Comment by pooyan-dadvand** [comment]
The inlining can be addressed by a careful forward declaration in headers. But finally, you should include them in all the source files which cause again to recompile everything. Without that, I imagine that compiler would skip many inline functions.

**Pull request closed without merging**
