### PR TITLE
[Dem] Change function definiton in CLs to avoid warnings and update

### PR DESCRIPTION
**Pull request by joaquinirazabal**
**Description**
The functions with Warnings when compiling with clang have been changed. Two CLs have also been updated.

**Changelog**
- ContactInfoSphericParticle was changed when possible in DEM_D_Stress_Dependent_Cohesive CL
- Pending changes in DEM_D_Stress_Dependent_Cohesive were added
- Pending changes in DEM_D_Conical_damage were added
- The ContactInfoSphericParticle element was updated to meet the requirements of the CLs
- Two new variables were created (PARTICLE_INITIAL_COHESION and WALL_INITIAL_COHESION)

### CODE REVIEW

**Comment by maceligueta** [comment]
Let's use this PR to make sure that the clang compilation is clean of warnings for the DEM app....

**Comment by joaquinirazabal** [comment]
Warnings still appear. I will continue tomorrow.

**Comment by philbucher** [comment]
> Let's use this PR to make sure that the clang compilation is clean of warnings for the DEM app....

just to say that I want to turn this warning into an error in the CI as soon as it is fixed everywhere to keep the build clean
(I first have to fix the warnings in the Structural so you have time don't worry)
It is not urgent though...

**Comment by joaquinirazabal** [comment]
Finally,  the clang compilation is clean of warnings for the DEM app :)

**Review by maceligueta — APPROVED** [review]

**Comment by maceligueta** [comment]
Awesome! Thanks @joaquinirazabal !!

**Pull request merged**
