### PR TITLE
[Dem] Adding control module process for 2D DEM and radial control module option for 3D FEMDEM

### PR DESCRIPTION
**Pull request by ipouplana**
Summary:

- A new control module process for 2D DEM has been added
- A new radial option for the control module process of 3D FEMDEM has been added
- Control module variables have been moved from DemStructuresApp. to DEMApp.

### CODE REVIEW

**Comment by maceligueta** [comment]
Thanks @ipouplana !! Having the control module in a process will help us a lot!

**Review by maceligueta — DISMISSED** [review]

**Review by maceligueta — DISMISSED** [review]

**Comment by ipouplana** [comment]
I just addressed the codacy suggestions.

**Comment by ipouplana** [comment]
Can you take a look at this @maceligueta ?

**Review by salvalatorre — APPROVED** [review]
Good job!

**Pull request merged**
