### PR TITLE
Core/improving testing

### LINKED ISSUE #1691: run_tests.py - error
I have a problem to run the tests

-first, the command `python.exe kratos\python_scripts\run_tests.py` does not work (ModuleNotFoundError: No module named 'KratosMultiphysics')
I added Kratos as well as Kratos\libs into the windows path. 

-using `runkratos.exe kratos\python_scripts\run_tests.py` I have the error 

>  |  /           |
>  ' /   __| _` | __|  _ \   __|
>  . \  |   (   | |   (   |\__ \
> _|\_\_|  \__,_|\__|\___/ ____/
>            Multi-Physics 5.3.0-da61790ec0
> Running tests for KratosCore
> Traceback (most recent call last):
>   File "kratos\python_scripts\run_tests.py", line 326, in <module>
>     main()
>   File "kratos\python_scripts\run_tests.py", line 287, in main
>     signalTime
>   File "kratos\python_scripts\run_tests.py", line 95, in RunTestSuitInTime
>     self.RunTestSuit(application, applicationPath, path, level, verbose, command)
>   File "kratos\python_scripts\run_tests.py", line 146, in RunTestSuit
>     print(script)
> OSError: [WinError 1] Incorrect function
> Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
> OSError: [WinError 1] Incorrect function

I think it is because of `CaptureStdout()` -- line 265 of run_tests.py

### PR DESCRIPTION
**Pull request by roigcarlo**
Should fix #1691 (@PhilippeBussetta can you check it works?)
Fixes the problem of #1643 with the printing of too much info.
Also, should fix a problem with the return code not capturing some outputs.
And finally it also fixes a problem in the Structural mechanics application that was preventing *.ref files from being copied.

### CODE REVIEW

**Review by loumalouomega — APPROVED** [review]
Ok

**Comment by PhilippeBussetta** [comment]
Ok, #1691 has been fixed
Thanks @roigcarlo 
Nevertheless, some tests are failed:
For example with: 
`run_tests.py -l small -a StructuralMechanicsApplication`
```
ERROR: test_model_part_io_write_model_part (test_model_part_io.TestModelPartIO)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\KratosOff\kratos\tests\test_model_part_io.py", line 143, in test_model_part_io_write_model_part
    kratos_utils.DeleteFileIfExisting(GetFilePath("test_model_part_io_write.out.mdpa"))
  File "D:\KratosOff\KratosMultiphysics\kratos_utilities.py", line 18, in DeleteFileIfExisting
    os.remove(file_name)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'D:\\KratosOff\\kratos\\tests\\test_model_part_io_write.out.mdpa'

----------------------------------------------------------------------
Ran 105 tests in 5.985s

FAILED (errors=1, skipped=5, expected failures=2)
Running tests for StructuralMechanicsApplication
.................................................................
----------------------------------------------------------------------
Ran 65 tests in 1.094s

OK
Running cpp tests
................................................F.................................F..........................................................................................................................................................
Ran 237 of 238 test cases in 0.482145s. 2 failed:
    TestLoggerMessageStream Failed with message:
        Error: Check failed because message.GetLocation().GetFunctionName() is not equal to "virtual void Kratos::Testing::TestLoggerMessageStream::TestFunction()"
in kratos/tests/input_output/test_logger.cpp:46:Testing::TestLoggerMessageStream::TestFunction

    TestModelPartIOWriteModelPart Failed with message:
        Error: Error deleting test output file: main_model_part_output.mdpa
in kratos/tests/sources/test_model_part_io.cpp:270:Testing::TestModelPartIOWriteModelPart::TestFunction
```

**Comment by roigcarlo** [comment]
@PhilippeBussetta Glad to hear!
@RiccardoRossi There is one test failing and we cannot merge:
```
Traceback (most recent call last):
  File "/home/travis/build/KratosMultiphysics/Kratos/kratos/tests/test_redistance.py", line 47, in test_model_part_sub_model_parts
    self.assertAlmostEqual(max_distance, 0.44733610591604156)
AssertionError: 0.4473497760454683 != 0.44733610591604156 within 7 places
```

Where does this come from?

**Review by PhilippeBussetta — APPROVED** [review]

**Comment by roigcarlo** [comment]
@PhilippeBussetta I will open a separate issue for the windows errors

**Comment by roigcarlo** [comment]
@RiccardoRossi Now it works, seems to be a problem with travis then? We will have to keep a look on that one. Merging

**Pull request merged**
