### PR TITLE
[Pfemfluid] improve analysisstage

### PR DESCRIPTION
**Pull request by philbucher**
**Description**
This PR cleans significantly the `PfemFluidAnalysis`. Now it is much more aligned with what the baseclass does!
I made the following improvements:
- Remove unnecessary checks for `HasNodalSolutionStepVariable`
- Make the usage of the processes like in the baseclass, no more custom treatment required

I know that these are rather large changes, hence this is a proposal. One can also do the changes in smaller steps, but this is my overall proposal for improvements

I ran the tests, they work but please check this yourself!

### CODE REVIEW

**Comment by philbucher** [comment]
BTW @AFranci what is the relation btw the PfemFluid and the DelaunayApp?
It is C++ but I cannot really see why. Would a python dependency be enough?

**Comment by philbucher** [comment]
ping @AFranci

**Comment by AlejandroCornejo** [comment]
Thank you @philbucher for this cleaning and optimization work!! :)
I think that it will increase the efficiency of the App. I suppose that the tests are passing ;)

What do you think @AFranci ?

This could be the start of a more in deep cleaning?@AFranci 👍

**Comment by philbucher** [comment]
I did run the tests but there are not that many so it would be good if one of you could try with one of your examples :)=

**Comment by AFranci** [comment]
HI i @philbucher
The tests and the solver work well, but it does not print outputs anymore.

**Comment by philbucher** [comment]
@AFranci could you please provide me the case you use?
This should be much easier for me to debug
Thx

**Comment by AFranci** [comment]
[test_PFEM.gid.zip](https://github.com/KratosMultiphysics/Kratos/files/6547439/test_PFEM.gid.zip)

**Pull request closed without merging**
