### PR TITLE
[GeoMechanicsApplication] Fixed warnings related to "GeometryType::Pointer"

### LINKED ISSUE #10870: [GeoMechanicsApplication] Fix warning based on SonarCloud suggestions
**Description**
Warning type:
_Use "std::make_shared" to construct "std::shared_ptr"._

**Scope**
In  _general_U_Pw_diff_order_condition.cpp_

**To Reproduce**
SonarCloud shows these warnings.

**Expected behavior**
To be green on SonarCloud.

### PR DESCRIPTION
**Pull request by mnabideltares**
**📝 Description**
Warning type:
Use "std::make_shared" to construct "std::shared_ptr".

**🆕 Changelog**
Change "GeometryType::Pointer" to make_shared

### CODE REVIEW

**Comment by matekelemen** [comment]
What kind of warnings did you get? The original seemed perfectly fine to me.

**Comment by mnabideltares** [comment]
> What kind of warnings did you get? The original seemed perfectly fine to me.

    mpPressureGeometry = GeometryType::Pointer( new Line2D3< Node<3> >(rGeom(0), rGeom(1), rGeom(2)));

* Use "std::make_shared" to construct "std::shared_ptr".

It suggest to change it to:
    mpPressureGeometry = make_shared<Line2D2<Node<3>>>(rGeom(0), rGeom(1));

**Comment by matekelemen** [comment]
so it wasn't the compiler complaining but some other tool, right?

**Comment by matekelemen** [comment]
Got it, thanks!

Unless it's in a performance-critical region, I tend to use the constructor + `new` combo because it doesn't make any assumptions on the type of the smart pointer (construction with `new` can be used for `std::shared_ptr`, `std::unique_ptr`, `intrusive_ptr`, etc. while `std::make_shared` is only valid for `std::shared_ptr`) but I understand the point.

**Review by roigcarlo — APPROVED** [review]
:+1:

**Pull request merged**
