### PR TITLE
Adding travis compilation information

### PR DESCRIPTION
**Pull request by loumalouomega**
@roigcarlo branch Release5.2 is not compiled by travis, so I put the 5.1

### CODE REVIEW

**Comment by roigcarlo** [comment]
@loumalouomega This can be misleading, if we re-enable the branch build we can add this but otherwise I'd preffer not to use it as it will be outdated...

**Comment by roigcarlo** [comment]
At least the badge for the Release 5.1 the rest is ok

**Comment by loumalouomega** [comment]
It was kind of prove of concept, I can modify it to 5.2, but will not look as fancy because currently is not compiled

**Comment by loumalouomega** [comment]
Done

**Review by roigcarlo — APPROVED** [review]
👍

**Comment by loumalouomega** [comment]
Hurray, now we look like a real github project

**Comment by pooyan-dadvand** [comment]
@loumalouomega thanks for improving the readme!

**Pull request merged**
