### PR TITLE
[StructuralMechanicsApplications] Proper exponential flow computation in finite strain plasticity

### PR DESCRIPTION
**Pull request by loumalouomega**
This solves the "chapuza" done before, where the computation of the plastic flow was done with a linear hypothesis. Now the proper exponential computation is done:

imagen

The finite strain yield surfaces and plastic flows are removed because are not required anymore

### CODE REVIEW

**Review by AlejandroCornejo — APPROVED** [review]
okkey! this weekend I was looking this part and was rare for me, now it's solved!

**Comment by loumalouomega** [comment]
Maybe I will take an extra time to merge, trying to  solve a real case give a lot of problems of convergence

**Comment by AlejandroCornejo** [comment]
should we merge vicente?

**Comment by loumalouomega** [comment]
I am doing some checks now, wait a moment

**Comment by loumalouomega** [comment]
Now working for  now my corrections, I will merge I will try t find a solution later

**Pull request merged**
