### PR TITLE
RELEASE 5.2: Retrocompatibilty in StructuralSolvers

### PR DESCRIPTION
**Pull request by loumalouomega**
These changes are done to fit the interface (GiD Interface PR: 163).

### CODE REVIEW

**Comment by rubenzorrilla** [comment]
Ok, but lets wait for @philbucher and @AndreasWinterstein approval.

**Review by rubenzorrilla — APPROVED** [review]

**Comment by jginternational** [comment]
I assume that this PR works with [the one in the GUI](/KratosMultiphysics/GiDInterface/pull/163)

**Review by philbucher — APPROVED** [review]
fine from our side

**Comment by philbucher** [comment]
you can merge if you want @loumalouomega

**Pull request merged**
