### PR TITLE
[Core] Missing tetrahedron split patterns

### PR DESCRIPTION
**Pull request by rubenzorrilla**
Here they are! @pablobecker sorry for this...

### CODE REVIEW

**Comment by pooyan-dadvand** [comment]
Just a curiosity, when there is only one element returned, why you are changing the order of the nodes?

**Comment by pablobecker** [comment]
I thought exactly the same thing. seems unessary

**Comment by pablobecker** [comment]
in the original code it was not altered.

**Comment by pablobecker** [comment]
can you modify your script so that if it is 0123 it keeps it that way?

**Comment by rubenzorrilla** [comment]
All the patterns were automatically generated. If we modify these I'd modify the rest in the file to be coherent.

**Comment by pablobecker** [comment]
can't you add a line in the generation script so that if the is no splitting, it keeps the original pattern?
I mean, taking the triangle as an example, if i understood correctly what is going on here, your script is writing 120 or 201 instead of writing the original 012 . The resulting mesh is exactly the same, but it forces you to create it again since local nodes have changed.

**Comment by rubenzorrilla** [comment]
> can't you add a line in the generation script so that if the is no splitting, it keeps the original pattern?
> I mean, taking the triangle as an example, if i understood correctly what is going on here, your script is writing 120 or 201 instead of writing the original 012 . The resulting mesh is exactly the same, but it forces you to create it again since local nodes have changed.

I got your point. What I was wondering if we take the chance to not only change these no-split patterns but all the no-split ones.

**Comment by rubenzorrilla** [comment]
> > can't you add a line in the generation script so that if the is no splitting, it keeps the original pattern?
> > I mean, taking the triangle as an example, if i understood correctly what is going on here, your script is writing 120 or 201 instead of writing the original 012 . The resulting mesh is exactly the same, but it forces you to create it again since local nodes have changed.
> 
> I got your point. What I was wondering if we take the chance to not only change these no-split patterns but all the no-split ones.

Just for the record, after a brief discussion with @pablobecker we decided to change al the no-split patterns to keep the standard 0 - 1 - 2 - 3 convention.

**Comment by rubenzorrilla** [comment]
@pablobecker done! Now the original connectivity is preserved if there is no splitting.

**Review by pooyan-dadvand — APPROVED** [review]
Thanks!

**Pull request merged**
