### PR TITLE
[StructuralMechanicsApplication] Missing clone on SurfaceLoadCondition

### PR DESCRIPTION
**Pull request by frastellini**
Missing clone on SurfaceLoadCondition

### CODE REVIEW

**Review by loumalouomega — APPROVED** [review]
Thanks

**Comment by philbucher** [comment]
Nice!

Did you check if this is properly implemented in the other conditions?

**Comment by frastellini** [comment]
The clone is also missing in following surface conditions:
SurfaceLoadFromDEMCondition3D,
SurfaceLoad3DDiffOrderCondition,
SurfaceNormalFluidFlux3DDiffOrderCondition,
SurfaceNormalLoad3DDiffOrderCondition

**Comment by frastellini** [comment]
More Clone functions are missing in the following conditions:
AxisymPointLoadCondition,
LineHeatFluxCondition,
PointContactCondition,
PoinLoadCondition,
PointPointJointCondition,
PairedCondition
and many mores in PoromechanicsApplication

**Comment by frastellini** [comment]
In StructuralMechanicsApplication,
the Clone function is also missing in:
PointMomentCondition3D

In ContactMechanicsApplication:
BeamPointRigidContactLM3DCondition,
BeamPointRigidContactPenalty3DCondition

**Comment by loumalouomega** [comment]
> In StructuralMechanicsApplication,
> the Clone function is also missing in:
> PointMomentCondition3D
> 
> In ContactMechanicsApplication:
> BeamPointRigidContactLM3DCondition,
> BeamPointRigidContactPenalty3DCondition

ContactMechanicsApllication is part of Solid application

**Comment by frastellini** [comment]
Should we mention somebody in particular to check the need of completing these missings?

**Comment by frastellini** [comment]
More clone functs missing in StructuralMechanics:
AxisymLineLoadCondition2D,
LineLoadCondition2D

**Comment by frastellini** [comment]
Thank you @loumalouomega for adding some of the missing clones.

**Comment by frastellini** [comment]
Just a warning of missing clone methods in some conditions. Special attention to: @ipouplana @josep-m-carbonell @antonialarese @RiccardoRossi @pooyan-dadvand

**Comment by josep-m-carbonell** [comment]
Thank you @frastellini, I will check it.  I think it will be good if you expose why Clone is needed. 
We have noticed that some applications haven't Clone method neither in conditions and elements. See for example FluidDynamicsApplication.

**Comment by frastellini** [comment]
Since we detected that there were some clone functions missing in StructuralMechanics, I have detected that there were many more clone missing in others applications. This is just a warning for developers, not an error. I do not have any specific need outside StructuralMechanicsApplication.

**Comment by pooyan-dadvand** [comment]
Clone is needed for creating the elements and conditions from input. Some application does this by manually creating the elements and conditions.

**Pull request merged**
