### PR TITLE
renaming c2c variables from mould to mold

### PR DESCRIPTION
**Pull request by ddiezrod**
To be consistent in both codes, all the "mould" (english) variables have been renamed as "mold" (american).

### CODE REVIEW

**Review by jrubiogonzalez — APPROVED** [review]

**Comment by ddiezrod** [comment]
@pooyan-dadvand @RiccardoRossi @roigcarlo  AppVeyor build is failing, it seems that it stopped before finishing. I don't think it is related to this particular PR, any idea?

**Comment by roigcarlo** [comment]
Hi @ddiezrod , there is a problem with the time indeed, if there is no other error apart from the time feel free to merge, right now appveyor is only informative, not required

**Comment by ddiezrod** [comment]
@roigcarlo Hi Carlos. But merging is blocked right now, I am not sure why as Jordi approved the changes before...

**Comment by roigcarlo** [comment]
@jrubiogonzalez is not in any Kratos team, so his approval is only testimonial (sorry @jrubiogonzalez) 

I will approve it since its you app and it was already checked by him.

Probably it  will be a good idea to create an Altair team so you can approve your own PR's. @RiccardoRossi can we do that?

**Review by roigcarlo — APPROVED** [review]

**Comment by ddiezrod** [comment]
@roigcarlo @RiccardoRossi  Thanks!! +1 to the idea of creating an Altair team

**Comment by pooyan-dadvand** [comment]
:+1 altair team

**Comment by jrubiogonzalez** [comment]
+1 :P

**Pull request merged**
