### PR TITLE
[Core][Variable] make CopyConstructor explicit

### PR DESCRIPTION
**Pull request by philbucher**
**Description**
This PR makes the Copy Constructor of `Variable` `explicit`

This way no implicit copies of variables can be created any more, which is the desired situation.
Now if copies are created it will be a compiler error

**Additional info**
Note that this is not the final solution for the issues with the variable copies

>> also note that this will require some updates in the code before it can be merged <<

### CODE REVIEW

**Review by sunethwarna — COMMENTED** [review]
This is ok for me, this makes debugging easier :) thanks :+1:

**Comment by maceligueta** [comment]
A good one. This should prevent the creation of vectors of variables, etc., which have been problematic in the past.

**Comment by maceligueta** [comment]
Now I see that the compilation failed due to the presence of some of those vectors... :-)

**Comment by philbucher** [comment]
All problems were fixed in different PRs, now this one only includes making the copy-ctor `excplicit` which compiles fine in the CI
In any case those problems are not difficult to fix

**Comment by maceligueta** [comment]
I would approve, but I see that the @KratosMultiphysics/technical-committee  is a reviewer, too, so I step aside.

**Review by roigcarlo — APPROVED** [review]

**Comment by philbucher** [comment]
the @KratosMultiphysics/technical-committee reached a consensus, merging

**Pull request merged**
