### PR TITLE
fix the compilation issue of kDOP with other compilers (~=gcc)

### PR DESCRIPTION
**Pull request by vryy**
typedef'ed some type as suggested by @roigcarlo and add override

### CODE REVIEW

**Review by roigcarlo — APPROVED** [review]
@vryy It works for me, thx!

Just a minor question (I will approve the change anyway), taking another look at the code, wouldn't it possible to remove:

```C++
static ArrayType msDirection[];
virtual Array2DType Direction() const;
```

From the derived classes and move it to the base? I don't see any relevant difference for which this has to be derived?

**Comment by pooyan-dadvand** [comment]
👍

**Comment by vryy** [comment]
@roigcarlo msDirection is different in each sub-classes and different to the base. Are you sure that if I only keep that in the base, I still can re-initialize it statically in all the sub-classes?

That's also the reason, Direction() must be implemented in sub-classes to access the private data.

**Comment by roigcarlo** [comment]
If it is strictly necessary to maintain the vector as a static member no.

The thing is, since `msDirections` seems to be ( if i haven't miss anything ) the only thing that changes from one class to another, I was thinking that maybe it could be done something like:

```C++
class kDOP
{
public:
    KRATOS_CLASS_POINTER_DEFINITION(kDOP);
    kDOP() : kDOP() {
        this->msDirectionsLength = 1
        this->msDirections = {{1, 1, 1}};
        this->Initialize();
    }
    virtual ~kDOP() {}

    // ... code ....

    virtual std::size_t NumberOfDirections() const {
        return this->msDirectionsLength;
    }
    virtual std::vector<std::vector<double>> & Direction() {
        return msDirectionsLength;
    }
protected:
    std::size_t msDirectionsLength;
    std::vector<std::vector<double>> msDirectionsLength;  // Or pointer
};
```

Then one derived class could be simplified as 

```C++
class _6DOP : public kDOP // AABB
{
public:
    KRATOS_CLASS_POINTER_DEFINITION(_6DOP);
    _6DOP() : _6DOP() {
        this->msDirectionsLength = 3
        this->msDirections = {{1, 0, 0}, {0, 1, 0}, {0, 0, 1}};
        this->Initialize();
    }
    virtual ~_6DOP() {}
};

// I didn't compile the code*
```

Or maybe even supress the derived classes if you pass the size and the `msDirection` vector as a parameter of the constructor (maybe even as a pointer to the vector if duplication is a concern). 

But again just an idea, I don't a have the full view of where this class is being used so maybe it does not make sense because I am omitting something important.

Anyway, I believe we can just merge as is. :+1:

**Comment by vryy** [comment]
@roigcarlo this is valid. But this will not be initialized at the compile time as I would expect.

This is used in one of my application for fast contact search. I believe it would be useful for others. Of course there are other fast contact search algorithms in other application (i.e bucket search, kD search). And I never see a benchmark comparing their performance so I would think it's wise to give people alternatives to choose. By the way, kDOP/BVH is quite a popular contact proximity search algorithm nowadays, see here:
Yang & Laursen, A contact searching algorithm including bounding volume trees applied to finite sliding mortar formulations, CM, 2006

@RiccardoRossi it needs to be lightweight, and it's better to be initialized at compile time. Using array_1d won't do.

**Comment by roigcarlo** [comment]
@vryy Ok!, thx for explaining it. Then we should merge it right away

**Comment by RiccardoRossi** [comment]
@vryy array_1d<...> is a stack array hence it should not be any different from doing double[]

**Pull request merged**
