### PR TITLE
[MPI] Fix compilation warning due to unused variable

### PR DESCRIPTION
**Pull request by jcotela**
**📝 Description**
This is giving us some trouble on a test machine where unused variable warnings are upgraded to errors. Since it is a simple fix I am just asking to include it in the codebase.

**🆕 Changelog**
- Adjusting variable scope to avoid an unused variable compilation warning

### CODE REVIEW

**Review by loumalouomega — APPROVED** [review]
Okay, thanks

**Review by sunethwarna — APPROVED** [review]
Nice catch :)

**Comment by sunethwarna** [comment]
curious, which is this smartest compiler of yours? my one does not give this warning :|

**Comment by jcotela** [comment]
> curious, which is this smartest compiler of yours? my one does not give this warning :|

gcc 8.3.1 on CentOS7, weirdly enough 🤷

**Comment by sunethwarna** [comment]
Hmm... maybe gcc is becoming dumber ;)

**Comment by loumalouomega** [comment]
@sunethwarna feel free to merge

**Comment by sunethwarna** [comment]
:+1:

**Pull request merged**
