### PR TITLE
[StructuralMechanicsApplication] Fixing test after #3242

### LINKED ISSUE #3259: Tests failing in StructuralMechanics
The following tests are failing in my machine: (master, GCC 7.3, without cotire)

~~~
======================================================================
FAIL: test_execution (structural_mechanics_test_factory.SmallDeformationPlasticityTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/philipp/software/Kratos_MasterBranch/applications/StructuralMechanicsApplication/tests/structural_mechanics_test_factory.py", line 59, in test_execution
    self.test.RunSolutionLoop()
  File "/home/philipp/software/Kratos_MasterBranch/kratos/python_scripts/analysis_stage.py", line 60, in RunSolutionLoop
    self.FinalizeSolutionStep()
  File "/home/philipp/software/Kratos_MasterBranch/kratos/python_scripts/analysis_stage.py", line 134, in FinalizeSolutionStep
    process.ExecuteFinalizeSolutionStep()
  File "/home/philipp/software/Kratos_MasterBranch/kratos/python_scripts/from_json_check_result_process.py", line 208, in ExecuteFinalizeSolutionStep
    self.assertTrue(isclosethis, msg=(str(value[gp]) + " != " + str(value_json) + ", rel_tol = " + str(reltol) + ", abs_tol = " + str(tol) + " : Error checking elem " + str(elem.Id) + " " + variable_name + " results."))
AssertionError: False is not true : nan != 3000002.499994993, rel_tol = 1e-06, abs_tol = 0.001 : Error checking elem 1 UNIAXIAL_STRESS results.
~~~

~~~
Ran 36 of 585 test cases in 0.0112561s. 1 failed:
    TestTestSPRErrorProcess2 Failed with message: 
        Error: Check failed because (0.122409 - process_info[ERROR_OVERALL])/0.122409 is greater than 1.0e-5
in /home/philipp/software/Kratos_MasterBranch/applications/StructuralMechanicsApplication/tests/cpp_tests/test_spr_error_process.cpp:289:virtual void Testing::TestTestSPRErrorProcess2::TestFunction()
~~~

Plus there are a lot of warnings now:
`Backward Euler Plasticity: Maximum number of iterations in plasticity loop reached...` but I guess until we found a global solution those cannot be avoided

### PR DESCRIPTION
**Pull request by loumalouomega**
Fixes #3259

### CODE REVIEW

**Review by AlejandroCornejo — COMMENTED** [review]
this is the final version??

**Comment by loumalouomega** [comment]
Yep. Try to run in your machine

**Comment by loumalouomega** [comment]
@AlejandroCornejo or @philbucher ?

**Review by philbucher — APPROVED** [review]
works for me, thx

**Pull request merged**
