### PR TITLE
[Core] Remove PythonProcess

### PR DESCRIPTION
**Pull request by loumalouomega**
**Description**
Derive PythonProcess from Process to avoid to update the script each time Process class is updated. This alsos reduces a little bit the code.

It also reduces the warnings that appear in the FSI Mok test (which is the only pace where this is used)

**Changelog**
- Derive PythonProcess from Process to avoid to update the script each time Process class is updated.

### CODE REVIEW

**Review by philbucher — CHANGES_REQUESTED** [review]
This is a leftover that should be removed instead. Have this on my todo list but never got to it 😅
@rubenzorrilla can you please update your test?

**Comment by loumalouomega** [comment]
> This is a leftover that should be removed instead. Have this on my todo list but never got to it sweat_smile
> @rubenzorrilla can you please update your test?

I though the same, but I think he needs a dummy process for the test

**Comment by philbucher** [comment]
ping @rubenzorrilla

**Comment by rubenzorrilla** [comment]
The point is that the GiD interface always requires a process in order to apply conditions (this is why it is written in the json). Therefore, we need to update the GUI accordingly before removing this. I'll try to have a look to it ASAP. As a temporary solution, I'm fine with @loumalouomega 's changes.

**Comment by loumalouomega** [comment]
> The point is that the GiD interface always requires a process in order to apply conditions (this is why it is written in the json). Therefore, we need to update the GUI accordingly before removing this. I'll try to have a look to it ASAP. As a temporary solution, I'm fine with @loumalouomega 's changes.

Do we agree then?

**Comment by philbucher** [comment]
I do not agree, this has been deprecated forever, the gui must be updated so that we can remove this class

**Comment by loumalouomega** [comment]
> I do not agree, this has been deprecated forever, the gui must be updated so that we can remove this class

I don't know, @rubenzorrilla can you clean up your process?

**Comment by loumalouomega** [comment]
> > I do not agree, this has been deprecated forever, the gui must be updated so that we can remove this class
> 
> I don't know, @rubenzorrilla can you clean up your process?

Ping

**Comment by loumalouomega** [comment]
> > > I do not agree, this has been deprecated forever, the gui must be updated so that we can remove this class
> > 
> > 
> > I don't know, @rubenzorrilla can you clean up your process?
> 
> Ping

Reping

**Comment by loumalouomega** [comment]
> > I do not agree, this has been deprecated forever, the gui must be updated so that we can remove this class
> 
> I don't know, @rubenzorrilla can you clean up your process?

Remember @rubenzorrilla

**Comment by rubenzorrilla** [comment]
The ball is on my court now. I'll try to update the GUI ASAP.

**Comment by rubenzorrilla** [comment]
> The ball is on my court now. I'll try to update the GUI ASAP.

Just mentioning that I've already spoken with @jginternational to update this.

**Comment by loumalouomega** [comment]
What is the status of this @rubenzorrilla ?

**Comment by rubenzorrilla** [comment]
My apologies. I completely forgot. @jginternational we should try to take care of this ASAP.

**Comment by jginternational** [comment]
I don't know what has to be done. But I agree that it must be done asap

**Comment by loumalouomega** [comment]
> I don't know what has to be done. But I agree that it must be done asap

ASAP->29 days after...

**Comment by loumalouomega** [comment]
> > I don't know what has to be done. But I agree that it must be done asap
> 
> ASAP->29 days after...

@jginternational what is the status of this?

**Comment by jginternational** [comment]
> > > I don't know what has to be done. But I agree that it must be done asap
> > 
> > 
> > ASAP->29 days after...
> 
> @jginternational what is the status of this?

I still don't know what has to be done by my side

**Comment by rubenzorrilla** [comment]
> > > > I don't know what has to be done. But I agree that it must be done asap
> > > 
> > > 
> > > ASAP->29 days after...
> > 
> > 
> > @jginternational what is the status of this?
> 
> I still don't know what has to be done by my side

In a nutshell, we need to avoid writing `PythonProcess` in the `ProjectParameters.json`. The point is that we need some kind of "fake process" in order to assign some of the BCs, mainly the coupled problems interfaces. Having said this, what I'd do is to create an `AuxiliaryProcess` in the GUI side to do this sort of things, use this in the places we're currently using the `PythonProcess` to then, in the main writing of the `ProjectParameters.json` skip it.

**Comment by philbucher** [comment]
Maybe to avoid all this hassle, @rubenzorrilla cannot you use the BaseClass as the dummy?

**Comment by rubenzorrilla** [comment]
> Maybe to avoid all this hassle, @rubenzorrilla cannot you use the BaseClass as the dummy?

mmm... depends on how we do the writing in the GUI. But you raised something to consider. Thanks for the hint.

@jginternational please take note so we try this first.

**Comment by philbucher** [comment]
Well instead of writing the string "PythonProcess" you could just write "Process" in the file 😃

**Comment by rubenzorrilla** [comment]
> Well instead of writing the string "PythonProcess" you could just write "Process" in the file smiley

Yes. But, ideally, we should write nothing in these (we only need the "fake" process in the GUI in order to enable the tree assignation).

**Comment by philbucher** [comment]
Ok I understand 

Since this is a problem of the GUI and not Kratos then we can finally remove PythonProcess?

**Comment by rubenzorrilla** [comment]
> Ok I understand
> 
> Since this is a problem of the GUI and not Kratos then we can finally remove PythonProcess?

@jginternational already did the necessary changes so there shouldn't be any problem. In any case I will also remove it from the GUI.

Having said this, I think we can now remove it from the main repo too.

**Comment by loumalouomega** [comment]
> > Ok I understand
> > Since this is a problem of the GUI and not Kratos then we can finally remove PythonProcess?
> 
> @jginternational already did the necessary changes so there shouldn't be any problem. In any case I will also remove it from the GUI.
> 
> Having said this, I think we can now remove it from the main repo too.

You mean totally remove instead of derive?

**Comment by loumalouomega** [comment]
Done

**Comment by loumalouomega** [comment]
@rubenzorrilla approval?

**Review by philbucher — APPROVED** [review]
nice, finally :tada:

**Comment by loumalouomega** [comment]
> nice, finally 🎉

**Pull request merged**
