### PR TITLE
[ContactStructuralMechanicsApplication] Transition PR for #2779

### PR DESCRIPTION
**Pull request by loumalouomega**
This separates the search utilities, the generation scripts and the templates from #2779

### CODE REVIEW

**Review by philbucher — COMMENTED** [review]
the tree search only has cosmetic changes right?

**Comment by loumalouomega** [comment]
Nope, there is the possibility to consider not symmetric meshes (tri-quad)

**Review by philbucher — APPROVED** [review]
approving but I am not sure if I saw all the important changes due to the cosmetic changes

**Comment by loumalouomega** [comment]
In this PR there are not cosmetic changes, many of the changes is the refactor due to the template argument change, the cosmetic ones are basically in #2779

**Comment by philbucher** [comment]
still a lot of `std::size_t` => `SizeType` & `conditions_array` => `r_conditions_array` etc
Fine for now but pls consider in the future

**Comment by loumalouomega** [comment]
True, sorry for that

**Pull request merged**
