### PR TITLE
Adding RomApplication to CI

### PR DESCRIPTION
**Pull request by Rbravo555**
This PR adds the RomApplication to the Continuous Integration for both Linux and Windows.

### CODE REVIEW

**Comment by philbucher** [comment]
who are the maintainers?

**Comment by Rbravo555** [comment]
> who are the maintainers?

That would be myself, @RiccardoRossi and @SADPR

**Comment by philbucher** [comment]
the failure in the nightly build is known and not your mistake

BTW I would also add your app to the [Codeowners](https://github.com/KratosMultiphysics/Kratos/blob/master/.github/CODEOWNERS) file if you add it to the CI

**Review by pooyan-dadvand — APPROVED** [review]
@KratosMultiphysics/technical-committee approves it

**Comment by Rbravo555** [comment]
> the failure in the nightly build is known and not your mistake
> 
> BTW I would also add your app to the [Codeowners](https://github.com/KratosMultiphysics/Kratos/blob/master/.github/CODEOWNERS) file if you add it to the CI

We'll be doing this in a separate PR later

**Pull request merged**
