### PR TITLE
again disabling potentialflow

### PR DESCRIPTION
**Pull request by philbucher**
for now testing, lets see what happens to the memory error :(

### CODE REVIEW

**Comment by philbucher** [comment]
@inigolcanalejo @marcnunezc I am afraid but we have to disable potentialflow again because the memory error reappeared :((
Otherwise we block everyone from merging
I am looking into this again with valgrind and `-D_GLIBCXX_DEBUG`
Sorry for the inconvenience

FYI @roigcarlo @KratosMultiphysics/technical-committee

**Review by marcnunezc — APPROVED** [review]
I understand!

**Comment by philbucher** [comment]
I have some things in mind that I want to check, will keep you posted

**Comment by philbucher** [comment]
So I did some checking and it seems like the order of the execution of the tests seems to be important

I have the impression that if the compressible tests are run first it is fine, but it crashed if the fluid-tests are run first.

furthermore I noticed that even though the RANS app is linking against fluid it does not import it in the init 
@sunethwarna can you please update that?

In #6423 I am making the order of execution of the tests deterministic. Before that for some reason the regex gave different orderings for the Applications, but I don't understand how this works and why it is no deterministic.

**Pull request merged**
