### PR TITLE
[several apps] Removing macro KRATOS_CHECK_VARIABLE_KEY from all applications

### PR DESCRIPTION
**Pull request by maceligueta**
**Description**
The macro KRATOS_CHECK_VARIABLE_KEY makes no longer sense, as the key can never be 0. All appearances are removed in this PR. It is throwing warnings currently.

### CODE REVIEW

**Comment by VeronikaSinger** [comment]
thanks @maceligueta

**Review by philbucher — APPROVED** [review]
thx @maceligueta !

Note for others: this macro is not always used, sometimes the check is performed manually (i.e. `if var.Key() == 0`) => those can be safely removed too in future PRs

**Comment by maceligueta** [comment]
> thx @maceligueta !
> 
> Note for others: this macro is not always used, sometimes the check is performed manually (i.e. `if var.Key() == 0`) => those can be safely removed too in future PRs

I just found 425 places where this is being used...

**Comment by philbucher** [comment]
> > thx @maceligueta !
> > Note for others: this macro is not always used, sometimes the check is performed manually (i.e. `if var.Key() == 0`) => those can be safely removed too in future PRs
> 
> I just found 425 places where this is being used...

yes there are quite a few and it requires some more refactoring, not just removing a macro. But in time I think we can clean it :)

**Pull request merged**
