### PR TITLE
[TrilinosApplication] Fix `CopyMatrixValues` method when column map does not coincide

### PR DESCRIPTION
**Pull request by loumalouomega**
**📝 Description**

This PR makes several improvements to the code in the `TrilinosSpace` class:

1. Introduced conditional logic based on the comparison of column maps:
   - Checked if the column maps of matrices `rA` and `rB` are the same.
   - When the column maps are the same, the code directly operates on local rows.
   - When the column maps differ, it converts column indices to global indices before updating the matrix `rA`.

2. Improve matrix graph combination, ensuring that indices are properly global, instead of assume indices retrievng from only one of the matrices (this may fail if row structure differs).

3. Improved error handling for Epetra operations:
   - Added error checks and messages for Epetra functions to provide better feedback in case of failures.
   - Added error messages indicating the rank and specific row (local or global) where the failure occurred, which can help in debugging.

4. Fixed a typo: Changed "Gettings" to "Getting" in a comment.

**🆕 Changelog**

- [Fix `CopyMatrixValues` method when column map does not coincide](https://github.com/KratosMultiphysics/Kratos/commit/c4ba436cc0802b593e32a19794878aa714d009ad)

### CODE REVIEW

**Comment by loumalouomega** [comment]
@roigcarlo

**Review by roigcarlo — COMMENTED** [review]
Code looks ok, but hard for me to see what are you trying to solve without a test (specially using epetra, not very familiar). 

Do we have a minimal test in which this fails?

**Comment by roigcarlo** [comment]
:+1: Again I feel more comfortable if someone else also looks at it. If its urgent tell me and I will approve

**Comment by loumalouomega** [comment]
> 👍 Again I feel more comfortable if someone else also looks at it. If its urgent tell me and I will approve

Well, I am going to push more PR and this is a dependency

**Review by roigcarlo — APPROVED** [review]
OK I approve in case someone detect changes we can address them in the following PR then

**Pull request merged**
