### PR TITLE
[CI] add Intel compiler to Docker image

### PR DESCRIPTION
**Pull request by philbucher**
**Description**
improved version of #8499 

This PR adds the Intel compiler, Intel-MPI and MKL to the docker container (all through the oneAPI)

in the next step we can add an Intel build in the CI

### CODE REVIEW

**Comment by philbucher** [comment]
Ok this seems to work / is ready :)

I disabled MKL temporarily bcs I have to do minor adjustments in the CI after this is merged and would block the CI otherwise!

FYI @armingeiser @oberbichler I will reenable it asap after this PR is merged, sorry for the inconvenience

**Comment by philbucher** [comment]
for reference this commit in the pybind repo is also very interesting: https://github.com/pybind/pybind11/commit/20e467d142ba3ac7e3d6a687482851b7f9c62765

**Comment by philbucher** [comment]
cool now it worked :)

FYI @marcnunezc I removed the old MMG to save space in the docker file, is that ok for you?

**Comment by marcnunezc** [comment]
> cool now it worked :)
> 
> FYI @marcnunezc I removed the old MMG to save space in the docker file, is that ok for you?

Is this a big blocker? This would mean that new changes in the MMG stuff might break in version v5.4 without us noticing via the CI. 

This is fine to me as it does not make sense to support an old version forever, but I think it would be better to do this while adding the corresponding Deprecation messages in the functionalities that are not supported in v5.4

So:
1) If the space is a limiting factor, you can go ahead and remove it and we will start adding the deprecation messgaes/errors where it corresponds.
2) If the space is not a limiting factor, would you agree on removing this when proper deprecation errors are added into the code?

**Comment by philbucher** [comment]
> > cool now it worked :)
> > FYI @marcnunezc I removed the old MMG to save space in the docker file, is that ok for you?
> 
> Is this a big blocker? This would mean that new changes in the MMG stuff might break in version v5.4 without us noticing via the CI.
> 
> This is fine to me as it does not make sense to support an old version forever, but I think it would be better to do this while adding the corresponding Deprecation messages in the functionalities that are not supported in v5.4
> 
> So:
> 
>     1. If the space is a limiting factor, you can go ahead and remove it and we will start adding the deprecation messgaes/errors where it corresponds.
> 
>     2. If the space is not a limiting factor, would you agree on removing this when proper deprecation errors are added into the code?

space is the issue :(

I try now again, but if it doesn't work I would say the intel compiler has a higher prio than the old mmg version

did you already add deprecation warnings in case someone uses still the old version of MMG?

**Comment by marcnunezc** [comment]
> space is the issue :(
> 
> I try now again, but if it doesn't work I would say the intel compiler has a higher prio than the old mmg version
> 
Ok I understand.

> did you already add deprecation warnings in case someone uses still the old version of MMG?

No, currently both versions are supported using #IF clauses in the cpp class. After this what I would do is throw a deprecation message if v5.4 is detected. (this is only for some selected funcionatlities of MMG, not the whole process)

**Comment by philbucher** [comment]
ok seems like it also worked without removing MMG 5.4 after some other cleaning :)

@marcnunezc can you add a warning at configure time i.e. in CMake if 5.4 is used?

**Comment by philbucher** [comment]
My plan is:
1. Merge this on Monday
2. update the usage of MKL and reenable it
3. Add a build with Intel

**Review by rubenzorrilla — APPROVED** [review]

**Comment by philbucher** [comment]
I am waiting until #8546 is in to merge this

**Comment by philbucher** [comment]
the MKL related issues in #8546 are solved, merging this so that I can update the usage of MKL

**Comment by philbucher** [comment]
@marcnunezc building the dockerimage keeps failing, it is really at the edge of the the space limitations
I will keep trying but if it doesn't work I will have to remove the old version of MMG :/

**Comment by marcnunezc** [comment]
Ok I understand, as I said it is not a big issue, I will add deprecation messages asap.

**Comment by philbucher** [comment]
> Ok I understand, as I said it is not a big issue

I made i work in #8560 without removing!

> I will add deprecation messages asap

that would be great

**Pull request merged**
