### PR TITLE
[Core][Geometry] Adding GetGeometryData to the geometry base class

### PR DESCRIPTION
**Pull request by tteschemacher**
Hi all,

I am adding a get function to get direct access to the geometry data of a certain geometry.

### CODE REVIEW

**Comment by tteschemacher** [comment]
@pooyan-dadvand is that ok?

**Comment by pooyan-dadvand** [comment]
For @KratosMultiphysics/technical-committee

**Comment by tteschemacher** [comment]
IMG-20190828-WA0012

**Comment by loumalouomega** [comment]
😍

**Comment by tteschemacher** [comment]
@KratosMultiphysics/technical-committee can I merge this function?

**Review by pooyan-dadvand — APPROVED** [review]
I approve it since It is needed for coupled geometries and no objection to it.

**Pull request merged**
