### PR TITLE
[Core] Point output process adapting header to current changes

### PR DESCRIPTION
**Pull request by mpentek**
**Description**
Point output process: enhancing the header to be in line current changes with additional information about the search configuration, according to the changes in #7932 

**Changelog**

- Added the chosen configuration information to the point output process
- Updated unit tests for the related processes
- Updated application tests (which showed a dependency) in -> only found tests in FluidDyn, CoSim

### CODE REVIEW

**Review by sunethwarna — COMMENTED** [review]
I am ok with the changes. My only small concern is there is no output.ref file for `search_config == "current"`, Which was never there....

**Comment by mpentek** [comment]
> I am ok with the changes. My only small concern is there is no output.ref file for `search_config == "current"`, Which was never there....

Perhaps one of the FSI cases would make sense to have one. It is only needed if there is mesh movement. @philbucher ? Any suggestion for what to add it?

**Comment by philbucher** [comment]
I don't understand why this is necessary, the position is being written there too, why does it matter where it comes from?
To me this is like mixing the settings with the output
In a sense, why don't we then also write if e.g. the variable is historical or not?

**Comment by mpentek** [comment]
> I don't understand why this is necessary, the position is being written there too, why does it matter where it comes from?
> To me this is like mixing the settings with the output
> In a sense, why don't we then also write if e.g. the variable is historical or not?

Use-case: analysis with various stages, where the mesh deforms between (or during) stages ->Perhaps the output is only turned on for different stages. Should help differentiate between the results and check correctness.

**Review by philbucher — DISMISSED** [review]
hm ok
I still think this should not be there as IMO it is part of the settings which btw we also don't write for vtk, hdf etc, but if you feel strongly about it please go ahead :)

regarding the comment of @sunethwarna, ofc having a test is always good, up to you to add one

**Review by philbucher — APPROVED** [review]

**Pull request merged**
