### PR TITLE
Change size transient test

### PR DESCRIPTION
**Pull request by Rbravo555**
This PR simply reduces the size of the MDPA file of the thermal transient test for the RomApplication. Other MDPA files are already less than 1000 lines.

### CODE REVIEW

**Review by philbucher — DISMISSED** [review]
Cool thx

I thinkyou committed *ExpectedOutput.npy* by accident

**Comment by Rbravo555** [comment]
The ExpectedOutput.npy is the numpy binary where the Full Order Model solution is stored. So, since the mesh changed, this expected output also changed. It was not an error to include it...

**Review by philbucher — APPROVED** [review]
Thx!

**Comment by Rbravo555** [comment]
Merci

**Pull request merged**
