### PR TITLE
add patch test with mpc using the elementwise builder and solver

### PR DESCRIPTION
**Pull request by vryy**
For some reason, when I replace the ResidualBasedBlockBuilderAndSolver by ResidualBasedBlockBuilderAndSolverWithConstraintsElementWise, the test is failed and the displacement is zero. Is the method to prescribe contraints in https://github.com/KratosMultiphysics/Kratos/issues/4531 working with the elementwise builder_and_solver?

### CODE REVIEW

**Comment by adityaghantasala** [comment]
Currently The element wise builder and solver is not working as it supposed to be ... i will have to make a separate pr to correct it and then this can go through .. !

**Comment by vryy** [comment]
@adityaghantasala Thanks for your clarification. Do you have an estimated timeline, when it can be done? so that we can finish this pull request.

**Comment by philbucher** [comment]
@adityaghantasala I thought the plan was to remove the elementwise to the ChimeraApp since now the normal BlockBuilder can handle the MPCs?

**Comment by RiccardoRossi** [comment]
aside of this i think that the test is useful for the block builder and solver, so i would propose to at least add it for that case

**Comment by RiccardoRossi** [comment]
ping

**Comment by vryy** [comment]
any news on the status of the element wise builder and solver so that I can close this case?

**Comment by philbucher** [comment]
The Elementwise B&S is now removed (1. Because it was broken and 2. because the baseclass can handle constraints)

Since the same test (?) was added for the Regular B&S in #4666 I guess we can delete this branch?
@vryy

**Comment by vryy** [comment]
hi @philbucher, just FYI, we fixed that internally but we have to make test and make sure that works with latest Kratos. We will commit when it's done.

**Comment by loumalouomega** [comment]
Do we need this branch?

**Comment by loumalouomega** [comment]
Is the brach still needed?

**Comment by adityaghantasala** [comment]
No deleting !

**Pull request closed without merging**
