### PR TITLE
[Meshing] Windows compile error

### PR DESCRIPTION
**Pull request by miguelmaso**
@AlejandroCornejo  does this temporary change fix the compiling error?

I will appreciate any help because I'm used to compile with linux

### CODE REVIEW

**Comment by AlejandroCornejo** [comment]
I'm compiling it! I'll say something... thx

**Comment by AlejandroCornejo** [comment]
hello @miguelmaso , it compiles now! thank you!!

**Review by AlejandroCornejo — APPROVED** [review]

**Review by loumalouomega — COMMENTED** [review]
This should not be a problem, if this is not compiling on Windows could be related with a different reason

**Comment by AlejandroCornejo** [comment]
it is normal to require so much time to check the travis? @roigcarlo

**Comment by loumalouomega** [comment]
@AlejandroCornejo yes, because we are pushing many PR at the time, you can chekc the cue at :  
https://travis-ci.org/KratosMultiphysics/Kratos/pull_requests

**Comment by rubenzorrilla** [comment]
@AlejandroCornejo can we delete the branch?

**Comment by AlejandroCornejo** [comment]
yes.. I was waiting for @miguelmaso  just in case

**Pull request merged**
