### PR TITLE
Core/hotfix silent vector array conversion

### PR DESCRIPTION
**Pull request by jcotela**
There were some functions in the python interface to access the nodal databases that allowed silently converting from Vector to array_1d<double,..> without checking the size of the vector. With @philbucher we are removing them and creating instead new python bindings for Array4, Array6 and Array9 classes. We have also added a test to check that the variables are no longer implicitly converted.

@loumalouomega can you try that your code is still working for Array4, 6 or 9 variables with this PR? It should, but we are not testing it because no such variables exist in the core. (that is why the API Breaker tag is here).

### CODE REVIEW

**Comment by philbucher** [comment]
Thanks @jcotela 
This was a nasty bug

**Comment by loumalouomega** [comment]
I don have any variable with 4 and 9, I just added them for the sake of generality

**Comment by philbucher** [comment]
for me the test crahses @jcotela , guess we will have to take another look tmr

**Comment by philbucher** [comment]
I added the node-tests to the test-suite, lets see if it works in Travis

**Comment by philbucher** [comment]
I think it didn't work in Travis,
also fails in my Laptop

**Comment by jcotela** [comment]
@philbucher Looks like the segmentation fault came from the error messages. I still don't understand why we didn't get this yesterday.

**Comment by jcotela** [comment]
@loumalouomega ok. I think they should still work anyways, but please let me know if you encounter problems when initializing array_1d from Vectors.

**Comment by loumalouomega** [comment]
OK :+1:

**Comment by philbucher** [comment]
Now it does not segfault any more, thanks @jcotela

**Review by philbucher — DISMISSED** [review]
Thanks for fixing @jcotela 
@loumalouomega if you want to test this we wait until next week
Should work though, since the exposing fct is a template

**Comment by loumalouomega** [comment]
Don't worry about me, I am not using it, as I a said I just added for generality

**Comment by jcotela** [comment]
@loumalouomega at least the METRIC_TENSOR_2D/3D variables in the MeshingApplication would be affected by this. We can go ahead just fine, but please keep this change in mind if you encounter problems with those.

**Comment by loumalouomega** [comment]
Oh, i forgot about that, Ok I will check

**Comment by philbucher** [comment]
@jcotela I just checked elements & conditions, they might have the same problem, not sure though:
https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/python/add_mesh_to_python.cpp#L448

**Comment by jcotela** [comment]
@philbucher That looks suspicious, I think an interface as in this PR would be at least safer.

**Review by loumalouomega — DISMISSED** [review]
Ok, looks like the tests of the MeshingApplication work

**Comment by jcotela** [comment]
@philbucher I have deleted similar methods in the Element, Condition and Properties interfaces and added related tests. The test file is now called `test_array_1d_interface.py` to reflect the checks within. I tested it on a debug compilation, lets see if travis finds the same results (since some ublas checks are different in release).

**Comment by philbucher** [comment]
thanks @jcotela I will test it
Btw you commited sth from the mpi-core which I guess should be removed

**Comment by jcotela** [comment]
@philbucher good catch, I removed the file.

**Comment by philbucher** [comment]
output in Release:
~~~
======================================================================
ERROR: test_SetConditionalArrayValueFromPython_WrongInput (__main__.TestArray1DInterface)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_array_1d_interface.py", line 106, in test_SetConditionalArrayValueFromPython_WrongInput
    self._InvalidAssignments(condition)
  File "test_array_1d_interface.py", line 153, in _InvalidAssignments
    tested_object.SetValue(KM.VORTICITY, v)
TypeError: SetValue(): incompatible function arguments. The following argument types are supported:
    1. (self: Kratos.Condition, arg0: Kratos.Array1DVariable3, arg1: Kratos.Array3) -> None
    2. (self: Kratos.Condition, arg0: Kratos.Array1DVariable4, arg1: Kratos.Array4) -> None
    3. (self: Kratos.Condition, arg0: Kratos.Array1DVariable6, arg1: Kratos.Array6) -> None
    4. (self: Kratos.Condition, arg0: Kratos.Array1DVariable9, arg1: Kratos.Array9) -> None
    5. (self: Kratos.Condition, arg0: Kratos.VectorVariable, arg1: Kratos.Vector) -> None
    6. (self: Kratos.Condition, arg0: Kratos.IntegerVectorVariable, arg1: boost::numeric::ublas::vector<int, boost::numeric::ublas::unbounded_array<int, std::allocator<int> > >) -> None
    7. (self: Kratos.Condition, arg0: Kratos.MatrixVariable, arg1: Kratos.Matrix) -> None
    8. (self: Kratos.Condition, arg0: Kratos.IntegerVariable, arg1: int) -> None
    9. (self: Kratos.Condition, arg0: Kratos.DoubleVariable, arg1: float) -> None
    10. (self: Kratos.Condition, arg0: Kratos.BoolVariable, arg1: bool) -> None

Invoked with: Geometrical Condition #1, VORTICITY variable #287440896, [4](1,2,3,4)

Did you forget to `#include <pybind11/stl.h>`? Or <pybind11/complex.h>,
<pybind11/functional.h>, <pybind11/chrono.h>, etc. Some automatic
conversions are optional and require extra headers to be included
when compiling your pybind11 module.

======================================================================
ERROR: test_SetElementalArrayValueFromPython_WrongInput (__main__.TestArray1DInterface)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_array_1d_interface.py", line 94, in test_SetElementalArrayValueFromPython_WrongInput
    self._InvalidAssignments(element)
  File "test_array_1d_interface.py", line 153, in _InvalidAssignments
    tested_object.SetValue(KM.VORTICITY, v)
TypeError: SetValue(): incompatible function arguments. The following argument types are supported:
    1. (self: Kratos.Element, arg0: Kratos.Array1DVariable3, arg1: Kratos.Array3) -> None
    2. (self: Kratos.Element, arg0: Kratos.Array1DVariable4, arg1: Kratos.Array4) -> None
    3. (self: Kratos.Element, arg0: Kratos.Array1DVariable6, arg1: Kratos.Array6) -> None
    4. (self: Kratos.Element, arg0: Kratos.Array1DVariable9, arg1: Kratos.Array9) -> None
    5. (self: Kratos.Element, arg0: Kratos.VectorVariable, arg1: Kratos.Vector) -> None
    6. (self: Kratos.Element, arg0: Kratos.IntegerVectorVariable, arg1: boost::numeric::ublas::vector<int, boost::numeric::ublas::unbounded_array<int, std::allocator<int> > >) -> None
    7. (self: Kratos.Element, arg0: Kratos.MatrixVariable, arg1: Kratos.Matrix) -> None
    8. (self: Kratos.Element, arg0: Kratos.IntegerVariable, arg1: int) -> None
    9. (self: Kratos.Element, arg0: Kratos.DoubleVariable, arg1: float) -> None
    10. (self: Kratos.Element, arg0: Kratos.BoolVariable, arg1: bool) -> None

Invoked with: Geometrical Element #1, VORTICITY variable #287440896, [4](1,2,3,4)

Did you forget to `#include <pybind11/stl.h>`? Or <pybind11/complex.h>,
<pybind11/functional.h>, <pybind11/chrono.h>, etc. Some automatic
conversions are optional and require extra headers to be included
when compiling your pybind11 module.

======================================================================
ERROR: test_SetPropertyArrayValueFromPython_WrongInput (__main__.TestArray1DInterface)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_array_1d_interface.py", line 118, in test_SetPropertyArrayValueFromPython_WrongInput
    self._InvalidAssignments(prop)
  File "test_array_1d_interface.py", line 153, in _InvalidAssignments
    tested_object.SetValue(KM.VORTICITY, v)
TypeError: SetValue(): incompatible function arguments. The following argument types are supported:
    1. (self: Kratos.Properties, arg0: Kratos.Array1DVariable6, arg1: Kratos.Array6) -> None
    2. (self: Kratos.Properties, arg0: Kratos.Array1DVariable3, arg1: Kratos.Array3) -> None
    3. (self: Kratos.Properties, arg0: Kratos.VectorVariable, arg1: Kratos.Vector) -> None
    4. (self: Kratos.Properties, arg0: Kratos.MatrixVariable, arg1: Kratos.Matrix) -> None
    5. (self: Kratos.Properties, arg0: Kratos.StringVariable, arg1: str) -> None
    6. (self: Kratos.Properties, arg0: Kratos.BoolVariable, arg1: bool) -> None
    7. (self: Kratos.Properties, arg0: Kratos.IntegerVariable, arg1: int) -> None
    8. (self: Kratos.Properties, arg0: Kratos.DoubleVariable, arg1: float) -> None
    9. (self: Kratos.Properties, arg0: Kratos.ConstitutuveLawVariable, arg1: Kratos::ConstitutiveLaw) -> None

Invoked with: Properties, VORTICITY variable #287440896, [4](1,2,3,4)

----------------------------------------------------------------------
~~~

**Comment by jcotela** [comment]
@philbucher great, it raises a different error in release...

**Comment by philbucher** [comment]
output in fulldebug:
~~~
======================================================================
ERROR: test_SetConditionalArrayValueFromPython_WrongInput (__main__.TestArray1DInterface)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_array_1d_interface.py", line 106, in test_SetConditionalArrayValueFromPython_WrongInput
    self._InvalidAssignments(condition)
  File "test_array_1d_interface.py", line 153, in _InvalidAssignments
    tested_object.SetValue(KM.VORTICITY, v)
TypeError: SetValue(): incompatible function arguments. The following argument types are supported:
    1. (self: Kratos.Condition, arg0: Kratos.Array1DVariable3, arg1: Kratos.Array3) -> None
    2. (self: Kratos.Condition, arg0: Kratos.Array1DVariable4, arg1: Kratos.Array4) -> None
    3. (self: Kratos.Condition, arg0: Kratos.Array1DVariable6, arg1: Kratos.Array6) -> None
    4. (self: Kratos.Condition, arg0: Kratos.Array1DVariable9, arg1: Kratos.Array9) -> None
    5. (self: Kratos.Condition, arg0: Kratos.VectorVariable, arg1: Kratos.Vector) -> None
    6. (self: Kratos.Condition, arg0: Kratos.IntegerVectorVariable, arg1: boost::numeric::ublas::vector<int, boost::numeric::ublas::unbounded_array<int, std::allocator<int> > >) -> None
    7. (self: Kratos.Condition, arg0: Kratos.MatrixVariable, arg1: Kratos.Matrix) -> None
    8. (self: Kratos.Condition, arg0: Kratos.IntegerVariable, arg1: int) -> None
    9. (self: Kratos.Condition, arg0: Kratos.DoubleVariable, arg1: float) -> None
    10. (self: Kratos.Condition, arg0: Kratos.BoolVariable, arg1: bool) -> None

Invoked with: Geometrical Condition #1, VORTICITY variable #287440896, [4](1,2,3,4)

Did you forget to `#include <pybind11/stl.h>`? Or <pybind11/complex.h>,
<pybind11/functional.h>, <pybind11/chrono.h>, etc. Some automatic
conversions are optional and require extra headers to be included
when compiling your pybind11 module.

======================================================================
ERROR: test_SetElementalArrayValueFromPython_WrongInput (__main__.TestArray1DInterface)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_array_1d_interface.py", line 94, in test_SetElementalArrayValueFromPython_WrongInput
    self._InvalidAssignments(element)
  File "test_array_1d_interface.py", line 153, in _InvalidAssignments
    tested_object.SetValue(KM.VORTICITY, v)
TypeError: SetValue(): incompatible function arguments. The following argument types are supported:
    1. (self: Kratos.Element, arg0: Kratos.Array1DVariable3, arg1: Kratos.Array3) -> None
    2. (self: Kratos.Element, arg0: Kratos.Array1DVariable4, arg1: Kratos.Array4) -> None
    3. (self: Kratos.Element, arg0: Kratos.Array1DVariable6, arg1: Kratos.Array6) -> None
    4. (self: Kratos.Element, arg0: Kratos.Array1DVariable9, arg1: Kratos.Array9) -> None
    5. (self: Kratos.Element, arg0: Kratos.VectorVariable, arg1: Kratos.Vector) -> None
    6. (self: Kratos.Element, arg0: Kratos.IntegerVectorVariable, arg1: boost::numeric::ublas::vector<int, boost::numeric::ublas::unbounded_array<int, std::allocator<int> > >) -> None
    7. (self: Kratos.Element, arg0: Kratos.MatrixVariable, arg1: Kratos.Matrix) -> None
    8. (self: Kratos.Element, arg0: Kratos.IntegerVariable, arg1: int) -> None
    9. (self: Kratos.Element, arg0: Kratos.DoubleVariable, arg1: float) -> None
    10. (self: Kratos.Element, arg0: Kratos.BoolVariable, arg1: bool) -> None

Invoked with: Geometrical Element #1, VORTICITY variable #287440896, [4](1,2,3,4)

Did you forget to `#include <pybind11/stl.h>`? Or <pybind11/complex.h>,
<pybind11/functional.h>, <pybind11/chrono.h>, etc. Some automatic
conversions are optional and require extra headers to be included
when compiling your pybind11 module.

======================================================================
ERROR: test_SetPropertyArrayValueFromPython_WrongInput (__main__.TestArray1DInterface)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_array_1d_interface.py", line 118, in test_SetPropertyArrayValueFromPython_WrongInput
    self._InvalidAssignments(prop)
  File "test_array_1d_interface.py", line 153, in _InvalidAssignments
    tested_object.SetValue(KM.VORTICITY, v)
TypeError: SetValue(): incompatible function arguments. The following argument types are supported:
    1. (self: Kratos.Properties, arg0: Kratos.Array1DVariable6, arg1: Kratos.Array6) -> None
    2. (self: Kratos.Properties, arg0: Kratos.Array1DVariable3, arg1: Kratos.Array3) -> None
    3. (self: Kratos.Properties, arg0: Kratos.VectorVariable, arg1: Kratos.Vector) -> None
    4. (self: Kratos.Properties, arg0: Kratos.MatrixVariable, arg1: Kratos.Matrix) -> None
    5. (self: Kratos.Properties, arg0: Kratos.StringVariable, arg1: str) -> None
    6. (self: Kratos.Properties, arg0: Kratos.BoolVariable, arg1: bool) -> None
    7. (self: Kratos.Properties, arg0: Kratos.IntegerVariable, arg1: int) -> None
    8. (self: Kratos.Properties, arg0: Kratos.DoubleVariable, arg1: float) -> None
    9. (self: Kratos.Properties, arg0: Kratos.ConstitutuveLawVariable, arg1: Kratos::ConstitutiveLaw) -> None

Invoked with: Properties, VORTICITY variable #287440896, [4](1,2,3,4)
~~~

**Comment by philbucher** [comment]
for me this works, it seems like different errors are thrown:
~~~
    def _InvalidAssignments(self, tested_object):

        # Forbidden implicit conversion from wrong-size Array
        with self.assertRaisesRegex(TypeError, ".*incompatible function arguments.*"):
            u = KM.Array6([1,2,3,4,5,6])
            tested_object.SetValue(KM.VORTICITY, u)

        # Forbidden implicit conversion from wrong-size Vector
        with self.assertRaisesRegex(TypeError, ".*incompatible function arguments.*"):
            v = KM.Vector([1,2,3,4])
            tested_object.SetValue(KM.VORTICITY, v)

        # Forbidden implicit conversion from wrong-size list
        with self.assertRaisesRegex(TypeError, ".*incompatible function arguments.*"):
            l = [1,2,3,4]
            tested_object.SetValue(KM.VORTICITY, l)
~~~

**Comment by jcotela** [comment]
@philbucher Apparently it depends on whether pybind (TypeError) or ublas (ValueError) catches the error first... I'm working on a version that passes the test on either.

**Comment by jcotela** [comment]
Ok this version works both for debug and release on my machine... Let's see what appveyor and travis think.

**Comment by philbucher** [comment]
now for me also both versions work

**Review by philbucher — APPROVED** [review]
approving, since the tests are now working and it can prevent some nasty bugs
Thanks again @jcotela

**Pull request merged**
