### PR TITLE
[EigenSolversApplication] dense multi rhs solve

### PR DESCRIPTION
**Pull request by armingeiser**
Extends the (real) dense direct solvers for equation systems with multiple right hand sides.

### CODE REVIEW

**Comment by philbucher** [comment]
@armingeiser the EigenSovlersApp is currently being renamed (#6888)
I am not sure what the status of @oberbichler is, but I would suspend all developments in the EigenSolversApp until this is done, otherwise there will be very nasty conflicts

**Comment by armingeiser** [comment]
> otherwise there will be very nasty conflicts.

Its not urgent, i can wait with this.

**Comment by armingeiser** [comment]
As discussed with @oberbichler - this can be merged first - would someone have a look and approve?

**Review by philbucher — APPROVED** [review]
:+1:

**Comment by armingeiser** [comment]
No just forgot to delete

**Pull request merged**
