### PR TITLE
Fluid/more test updates

### PR DESCRIPTION
**Pull request by jcotela**
The main change here is that I am moving the test `testSteadyCylinder` defined in the `AdjointVMSSensitivity2D` class from the nightly queue to the validation one. Unfortunately, this tests takes about half of the total time used by fluid tests and I suspect it to be to blame for #3512 (fluid tests not finishing in nightly).

I used the opportunity to do some more updating of test json to current standard.

@rubenzorrilla the test `embedded_couette_imposed_test.EmbeddedCouetteImposedTest` has linear solver convergence problems in my machine (although it passes). Do you also see this result? Maybe some tolerances should be adjusted.

### CODE REVIEW

**Comment by rubenzorrilla** [comment]
It might be the case for the very first non-linear iterations. Maybe we can take the change to increase the number of linear solver iterations.

**Comment by jcotela** [comment]
@rubenzorrilla the solver for that test is SuperLU, we don't have a lot to play with... I was trying to use more non-linear iterations earlier, but the convergence error seems to flatten out after a few iterations, never decreasing beyond 1e-2 ~ 1e-3. If you have other ideas, I could try them. However, we can also check this test more carefully in a future PR (for now, it passes).

Just for reference, this is the list of tests in the current `all` queue, sorted by time:
```
testCalculateSensitivityMatrix (adjoint_vms_element_2d.AdjointVMSElement2D) (0.001s, 0.01%)
testCalculateFirstDerivativesLHS2 (adjoint_vms_element_2d.AdjointVMSElement2D) (0.002s, 0.01%)
testCalculateSecondDerivativesLHS (adjoint_vms_element_2d.AdjointVMSElement2D) (0.002s, 0.01%)
testCalculateFirstDerivativesLHS1 (adjoint_vms_element_2d.AdjointVMSElement2D) (0.002s, 0.01%)
testEmbeddedSlipReservoir2D (embedded_reservoir_test.EmbeddedReservoirTest) (0.017s, 0.11%)
testEmbeddedAusasDevelopmentCouette2D (embedded_couette_test.EmbeddedCouetteTest) (0.024s, 0.16%)
testEmbeddedReservoir2D (embedded_reservoir_test.EmbeddedReservoirTest) (0.024s, 0.16%)
testSteadyAnalysisSmall (test_statistics_process.IntegrationPointStatisticsTest) (0.026s, 0.17%)
testEmbeddedAusasCouette2D (embedded_couette_test.EmbeddedCouetteTest) (0.026s, 0.18%)
testEmbeddedSlipCouette2D (embedded_couette_test.EmbeddedCouetteTest) (0.036s, 0.24%)
testEmbeddedSlipDevelopmentCouette2D (embedded_couette_test.EmbeddedCouetteTest) (0.041s, 0.28%)
testEmbeddedDevelopmentCouette2D (embedded_couette_test.EmbeddedCouetteTest) (0.041s, 0.28%)
testEmbeddedCouetteImposed2D (embedded_couette_imposed_test.EmbeddedCouetteImposedTest) (0.043s, 0.29%)
testThermalExpansionCoefficient (buoyancy_test.BuoyancyTest) (0.044s, 0.30%)
testEmbeddedCouette2D (embedded_couette_test.EmbeddedCouetteTest) (0.049s, 0.33%)
testEulerian (buoyancy_test.BuoyancyTest) (0.049s, 0.33%)
testEmbeddedAusasCouette3D (embedded_couette_test.EmbeddedCouetteTest) (0.058s, 0.39%)
testEmbeddedAusasDevelopmentCouette3D (embedded_couette_test.EmbeddedCouetteTest) (0.072s, 0.49%)
testSteadyAnalysisSmall (fluid_analysis_test.FluidAnalysisTest) (0.081s, 0.55%)
testInputOutput (hdf5_io_test.HDF5IOTest) (0.093s, 0.63%)
testEmbeddedSlipCouette3D (embedded_couette_test.EmbeddedCouetteTest) (0.095s, 0.64%)
testEmbeddedCouette3D (embedded_couette_test.EmbeddedCouetteTest) (0.109s, 0.74%)
testArtificialCompressibility (artificial_compressibility_test.ArtificialCompressibilityTest) (0.115s, 0.78%)
testEmbeddedSlipReservoir3D (embedded_reservoir_test.EmbeddedReservoirTest) (0.123s, 0.83%)
testEmbeddedReservoir3D (embedded_reservoir_test.EmbeddedReservoirTest) (0.124s, 0.84%)
testEmbeddedDevelopmentCouette3D (embedded_couette_test.EmbeddedCouetteTest) (0.124s, 0.84%)
testEmbeddedSlipDevelopmentCouette3D (embedded_couette_test.EmbeddedCouetteTest) (0.126s, 0.85%)
testCavityQSASGS (fluid_element_test.FluidElementTest) (0.133s, 0.90%)
testSymbolic (time_integrated_fluid_element_test.TimeIntegratedFluidElementTest) (0.139s, 0.94%)
testCavityDASGS (fluid_element_test.FluidElementTest) (0.143s, 0.96%)
testEmbeddedCouetteImposed3D (embedded_couette_imposed_test.EmbeddedCouetteImposedTest) (0.180s, 1.22%)
testNavierStokesWallCondition (navier_stokes_wall_condition_test.NavierStokesWallConditionTest) (0.189s, 1.28%)
testCavity (time_integrated_fluid_element_test.TimeIntegratedFluidElementTest) (0.203s, 1.37%)
testDarcyNonLinear (darcy_channel_test.DarcyChannelTest) (0.240s, 1.62%)
testDarcyLinear (darcy_channel_test.DarcyChannelTest) (0.243s, 1.64%)
testDarcyDensity (darcy_channel_test.DarcyChannelTest) (0.254s, 1.72%)
testCavityDOSS (fluid_element_test.FluidElementTest) (0.345s, 2.33%)
testOneElement (adjoint_vms_sensitivity_2d.AdjointVMSSensitivity2D) (0.362s, 2.45%)
testCavityQSOSS (fluid_element_test.FluidElementTest) (0.370s, 2.50%)
testFluidDynamicsAnalysis (fluid_analysis_test.FluidAnalysisTest) (0.468s, 3.17%)
testSteadyCylinder (fluid_analysis_test.FluidAnalysisTest) (0.514s, 3.47%)
testSteadyCavity (fluid_analysis_test.FluidAnalysisTest) (0.516s, 3.49%)
testCylinder (adjoint_fluid_test.AdjointFluidTest) (0.747s, 5.05%)
testCylinder (adjoint_vms_sensitivity_2d.AdjointVMSSensitivity2D) (3.863s, 26.11%)
testManufacturedSolution (manufactured_solution_test.ManufacturedSolutionTest) (4.342s, 29.34%)
Total (14.796s, 100.00%)
```
(the removed test was taking 25s). We may still want to still drop the last two to get all tests under 1s, but I hope that this will be enough to fit our tests in nightly.

**Comment by rubenzorrilla** [comment]
@jcotela Let me try to figure out what's happening with the Couette test. I will let you know as soon as I have any clue.

**Comment by rubenzorrilla** [comment]
@jcotela The problem was in the outer nodes BCs, which used to induce a non-physical behaviour. I modified the fixity in such nodes so no more warnings should appear.

**Comment by jcotela** [comment]
Just confirming that all tests exit clean now. Thanks @rubenzorrilla

**Review by rubenzorrilla — APPROVED** [review]

**Pull request merged**
