### PR TITLE
[CI] disabling PotentialFlow

### PR DESCRIPTION
**Pull request by philbucher**
apparently this takes longer than expected :/
Problem is that now the CI is always failing and this may cover up an actual error if none is looking at the output anymore since it always fails anyway

ofc it can be reenabled once it is working, but I think it makes more sense now to get the docker image and try locally

### CODE REVIEW

**Review by inigolcanalejo — COMMENTED** [review]
Sounds good, I hope we find a solution soon.

**Review by inigolcanalejo — APPROVED** [review]

**Review by marcnunezc — APPROVED** [review]
Ok to me as well. I agree this is now annoying and it's better to disable it.

However from what I have seen here  https://github.com/KratosMultiphysics/Kratos/pull/6268#issuecomment-578091239 the problem also seems to depend in other apps (for instance disabling only the MappingApplication also avoids the error). Since no app depends on the potential flow I think its a good idea to just disable the PotentialFlow application instead of others. 

I have tried to build and run locally the docker container and everything was working fine :/ @roigcarlo  commented that if it works locally the issue might come from the libraries used by the host in the CI container. I will keep trying different things

**Comment by philbucher** [comment]
I checked now myself, and apparently the MappingApp also leads to the same error, I didn't notice this before.

I will merge this now, but if you want we can also take out the MappingApp, it has to remain fair.

I will also try to look into this again 
When you tried locally with docker did you also try to compile with FullDebug?

**Comment by marcnunezc** [comment]
I just tried in FullDebug with docker and got the following error in the cpp tests (probably not the cause of the problem):
```
Ran 1341 of 1469 test cases in 13.9817s (1 skipped). 1 failed:
    TestCouplingGeometryNode Failed with message: 
        Error: Test Failed: p_coupling_geometry->GetGeometryPart(2) did not throw the expected error.
Expected:
Index 2 out of range. Composite contains only of: 2 geometries.
Got:
Error: Index 2 out of range. CouplingGeometry #39053120 has 2 geometries.

in kratos/geometries/coupling_geometry.h:203:CouplingGeometry<TPointType>::GeometryPointer CouplingGeometry<TPointType>::pGetGeometryPart(CouplingGeometry<TPointType>::IndexType) [with TPointType = Node<3>; CouplingGeometry<TPointType>::GeometryPointer = shared_ptr<Geometry<Node<3> > >; CouplingGeometry<TPointType>::IndexType = long unsigned int]


in kratos/tests/cpp_tests/geometries/test_coupling_geometry.cpp:97:virtual void Testing::TestCouplingGeometryNode::TestFunction()
```

**Pull request merged**
