### PR TITLE
fixed strain energy computation (removed dependency on integration we…

### PR DESCRIPTION
**Pull request by marandra**
…ight), removed redundant calculation of material response

### CODE REVIEW

**Review by RiccardoRossi — COMMENTED** [review]
makes complete sense to me. However @loumalouomega could u take a brief look?

**Review by RiccardoRossi — APPROVED** [review]
accepting. please wait until sunday, if @loumalouomega doesn't say anything just merge

**Comment by loumalouomega** [comment]
It can be merged, no worries

**Comment by RiccardoRossi** [comment]
@marandra i am merging it now, to avoid having the Travis crowded on monday

**Pull request merged**
