### PR TITLE
[AppVeyor] Enabling MeshMovingApplication

### PR DESCRIPTION
**Pull request by philbucher**
Since appveyor has some resources we (Statik) are proposing to add the MeshMovingApplication to the build.
It is a stable application that is used by quite a number of ppl (FSI, Optimization and others), also often in Windows

### CODE REVIEW

**Comment by philbucher** [comment]
I think this requires #2146

**Comment by roigcarlo** [comment]
We have plenty of time to spare on appveyor so as long as it compiles :+1:

**Comment by pooyan-dadvand** [comment]
👍

**Comment by philbucher** [comment]
seems not to work, I don't know how to fix it

ping @rubenzorrilla

**Comment by armingeiser** [comment]
If i remove the ```KRATOS_API``` Macro in the class definition of ```ExplicitMeshMovingUtilities``` it works on my local Windows machine. But i don't know what it does and if its save to remove it...

**Comment by philbucher** [comment]
now it works

what do you think @roigcarlo ?

**Review by roigcarlo — APPROVED** [review]
Good to me!

**Comment by rubenzorrilla** [comment]
Thanks @armingeiser !

**Comment by philbucher** [comment]
FYI @longchentum now it should compile again

**Pull request merged**
