### PR TITLE
[Core] VariationalDistanceCalculation Tests

### PR DESCRIPTION
**Pull request by sunethwarna**
**Description**
This PR changes `max_iterations` to have a converged test results for test_redistance.py

**Changelog**
- Changed `max_iterations`
- Changed reference values

### CODE REVIEW

**Comment by RiccardoRossi** [comment]
inthink a small iteration number was used to check that the iterate
remained the same

**Comment by sunethwarna** [comment]
Would it be ok to increase them? Otherwise the solution would be different when an mdpa is used with and without `Conditions` block as in PR #7132 . ( Corresponding line of cause is explained in this PR)

**Comment by RiccardoRossi** [comment]
we can increase it as a different test...
the point is that with what we havr now we check the convergence process in
a sense, and i think this is worth...

**Comment by sunethwarna** [comment]
In that case, I have few concerns and I am not sure how to go around those. :/

The problem is following,
Currently in `test_normal_utils.py` we use `SkinDetectionProcess` to create on the fly `Conditions` for mdpas which only have `Elements`. (I coudn't find any mdpa which has `Conditions`(triangle) and `Elements`(tetrahedrals) in kratos core). In this case, we cannot use same test designed for OMP in MPI which is dangerous. So I included `Conditions` block to one of the mdpas (coarse_sphere.mdpa) and designed OMP tests such that they will give same result when run in MPI.

OMP tests:
https://github.com/KratosMultiphysics/Kratos/blob/247c619e848042c401b2fc334e303f32ba0e2019/kratos/tests/test_KratosCore.py#L102-L103
MPI test:
https://github.com/KratosMultiphysics/Kratos/blob/247c619e848042c401b2fc334e303f32ba0e2019/kratos/mpi/tests/test_KratosMPICore.py#L54-L55

Addition of `Conditions` block to mdpa will fail following test
https://github.com/KratosMultiphysics/Kratos/blob/1d5ddbd3b218c8e7e3cb49566ede6d4898fd3453/kratos/tests/test_redistance.py#L23-L51

This is because, when `Conditions` block is added to mdpa, it will mark `BOUNDARY` flag for nodes belonging to `Conditions` in following line
https://github.com/KratosMultiphysics/Kratos/blob/1d5ddbd3b218c8e7e3cb49566ede6d4898fd3453/kratos/processes/variational_distance_calculation_process.h#L496-L504

Then `DistanceCalculationElementSimplex` element will have a different RHS because of the following line leading to different convergence process.
https://github.com/KratosMultiphysics/Kratos/blob/1d5ddbd3b218c8e7e3cb49566ede6d4898fd3453/kratos/elements/distance_calculation_element_simplex.h#L259-L264

So in order to have the same test in `test_redistance.py` to pass with and without `Conditions` block in mdpa, I had to increase `max_iterations`. If we are to keep this test as it is, then I need to introduce another mdpa with `Conditions` block for 3D with simplex elements, or we need to design two different tests for OMP and MPI since on the fly `Conditions` creation cannot be done because `SkinDetectionProcess` is not designed to work in MPI.

**Comment by sunethwarna** [comment]
This is no longer required since, after discussing with @philbucher , We agreed to introduce new `coarse_sphere_with_conditions.mdpa` file to core to be used in #7132 . Thanks :)

**Comment by RiccardoRossi** [comment]
i understand your problem, however one way of seeing this is that the test
is correctly detecting that mpi does not the same as serial...

the good way to have this would be to create the conditions also in mpi...

**Comment by sunethwarna** [comment]
@RiccardoRossi I like the good way you are suggesting :), So in that case we have to make `SkinDetectionProcess` compatible with MPI. I guess this needs to be done in a separete PR.

**Pull request closed without merging**
