### PR TITLE
[Test] Hotfixes for win wheels

### PR DESCRIPTION
**Pull request by roigcarlo**
**Description**
Porting some urgent changes from https://github.com/KratosMultiphysics/Kratos/compare/wheels/add-action as I need them now.
This should become obsolete when the other branch is finished.

It will cause some conflicts, sorry for that.

**Changelog**
- Adjusting wheel build for win

### CODE REVIEW

**Comment by roigcarlo** [comment]
@HubertBalcerzak quick question, I made some tests and the ``%cmake%` command in the win configure seems to fail, is there any reason it is called this way and not directly through regular `cmake`? (I've changed the way cmake is installed to choco, maybe that has something to do)

**Comment by roigcarlo** [comment]
I know these are duplicated, but until we merge the other branch can approve this?

**Review by philbucher — APPROVED** [review]
makes sense to merge this now, until we have time to finish the other one
Hopefully will not give as many conflicts

**Comment by roigcarlo** [comment]
thx!

**Pull request merged**
