### PR TITLE
[Core] Remove use of FLAG_VARIABLE in variational distance process

### PR DESCRIPTION
**Pull request by marcnunezc**
**📝 Description**
This PR removes the use of FLAG_VARIABLE and replaces it with a flag. This will avoid defining it in the solver. 

Is there a reason to use the historical container instead of the non-historical or a flag?

**🆕 Changelog**
Please summarize the changes in one list to generate the changelog:
E.g.
- Use a flag to track the fixity in the variational distance process instead of FLAG_VARIABLE

### CODE REVIEW

**Review by rubenzorrilla — COMMENTED** [review]
Indeed, rather than using a nodal variable, we should use a nodal flag for the sake of performance.

In any case, I'm positive about this change.

**Comment by ddiezrod** [comment]
I agree with @rubenzorrilla, if I remember correctly it was not possible to use a flag some years ago, I guess thats why we had to use this at that moment. I did a quick search and it seems this can be changed without any problem.

**Comment by rubenzorrilla** [comment]
> I agree with @rubenzorrilla, if I remember correctly it was not possible to use a flag some years ago, I guess thats why we had to use this at that moment. I did a quick search and it seems this can be changed without any problem.

Yes. The problem was the synchronization of the MPI flags, which was not present when we implemented this. This is no longer a problem.

**Comment by marcnunezc** [comment]
I changed the use of FLAG_VARIABLE to the BLOCKED flag since it was a fast change.

If you prefer to do this in two PRs we can revert to the first commit.

**Review by rubenzorrilla — APPROVED** [review]
Very good. Thanks for the upgrade.

**Pull request merged**
