### PR TITLE
correct accent of Vicente

### PR DESCRIPTION
**Pull request by philbucher**
this is all over the place and in every PR :D

### CODE REVIEW

**Review by loumalouomega — DISMISSED** [review]
My poor mother, if she knows...

**Comment by philbucher** [comment]
should be fine, I assume she is not developing Kratos actively...?

**Comment by loumalouomega** [comment]
Nope :)

**Comment by philbucher** [comment]
reapproval is needed :)

**Review by loumalouomega — APPROVED** [review]

**Pull request merged**
