### PR TITLE
Adding unsigned int interface for MPI communicator

### PR DESCRIPTION
**Pull request by jcotela**
This PR adds the interface for unsigned int communication using the DataCommunicator. Since it essentially requires duplicating the entire interface of both `DataCommunicator` and `MPIDataCommunicator`, I refactored both classes so that the related methods are declared through macros. I am not at all happy with the approach, but I could not figure out any solution that didn't require a complete redefinition of the public interface of the classes (since templated methods can not be virtual).

The positive part of this is that it now should be straightforward to support new arithmetic types (std::size_t?) by adding the corresponding macros for the new type and a couple of one-line templates.

This PR also adds tests for unsigned int communication.

Since the PR is already quite big, I decided to postpone the next feature (Serialization-based communication) for a future PR.

### CODE REVIEW

**Review by pooyan-dadvand — COMMENTED** [review]
About the implementation via macro I understand that you don't have much better solutions. The same happened to me in implementing the serializer. 

Just a small comment: Why are you using KRATOS_DEBUG macro in test to change their behaviour?

**Comment by jcotela** [comment]
@pooyan-dadvand the data communicator does extra checking when compiled in debug mode (essentially, checking that buffer sizes match across the different processes involved in communication). There are some tests designed to trip these checks (sending three values when the receiver expects only two and things like that), which would produce memory errors in release mode.

**Comment by pooyan-dadvand** [comment]
I see. Thanks for the explanation!

**Comment by RiccardoRossi** [comment]
@pooyan-dadvand i would approve, but i let it to you

**Review by pooyan-dadvand — APPROVED** [review]
👍

**Pull request merged**
