### PR TITLE
[dem] Missing include

### LINKED ISSUE #8805: [DEM] #include <random> in random_variable.h
Since the class `RandomVariable` and its derived one use some generators such as `std::mt19937`, I think it would be nice to include the header `#include <random>` to avoid compilation problems.

### PR DESCRIPTION
**Pull request by maceligueta**
**Description**
A missing include is added. I wonder how this was passing the Windows CI. Both @AlejandroCornejo and me noticed this compilation error in Windows. 
Closes #8805

### CODE REVIEW

**Review by rubenzorrilla — DISMISSED** [review]

**Comment by maceligueta** [comment]
It seems to me that the "without Unity" CI compilation would have yielded an error, had it included the applications.

**Comment by jgonzalezusua** [comment]
I would add the missing include in `random_variable.h` rather than in the derived class. If you do so, you only need to implement the include in one script.

**Comment by maceligueta** [comment]
@jgonzalezusua can you approve it plz?

**Comment by jgonzalezusua** [comment]
Of course

**Review by jgonzalezusua — APPROVED** [review]

**Pull request merged**
