### PR TITLE
[PotentialFlow] Hotfix adjoint condition

### PR DESCRIPTION
**Pull request by marcnunezc**
This file still was using the historical distance variable (after #5160), switching now to non historical

### CODE REVIEW

**Comment by rubenzorrilla** [comment]
I assume you are copying the nodal distance from the historical database to the non-historical one.

**Comment by marcnunezc** [comment]
Hi @rubenzorrilla , I know this is confusing but I will try to explain it here.

This DISTANCE function is the distance used for the WAKE in the **body-fitted geometry** case, where we do NOT use CalculateDistanceToSkinProcess, so this distance is not historical at any point of the analysis (after @inigolcanalejo changes to improve memory usage in #5160).

We compute the distance to the wake analytically here, and store it in the NonHistorical container:

https://github.com/KratosMultiphysics/Kratos/blob/e5da883b8f20ac68bc138e07fe92bbc7bbc6bf0b/applications/CompressiblePotentialFlowApplication/custom_processes/define_2d_wake_process.cpp#L150-L172

This is different from what I have been showing you and asking about recenlty, with **embedded geoemtries** , where we have two distance functions that will use CalculateDistanceToSkin processes (embedded wake not currently in the master yet).

**Comment by rubenzorrilla** [comment]
> Hi @rubenzorrilla , I know this is confusing but I will try to explain it here.
> 
> This DISTANCE function is the distance used for the WAKE in the **body-fitted geometry** case, where we do NOT use CalculateDistanceToSkinProcess, so this distance is not historical at any point of the analysis (after @inigolcanalejo changes to improve memory usage in #5160).
> 
> We compute the distance to the wake analytically here, and store it in the NonHistorical container:
> 
> https://github.com/KratosMultiphysics/Kratos/blob/e5da883b8f20ac68bc138e07fe92bbc7bbc6bf0b/applications/CompressiblePotentialFlowApplication/custom_processes/define_2d_wake_process.cpp#L150-L172
> 
> This is different from what I have been showing you and asking about recenlty, with **embedded geoemtries** , where we have two distance functions that will use CalculateDistanceToSkin processes (embedded wake not currently in the master yet).

Now I see. I think that using `DISTANCE`, which has been historically used in Kratos for the level-set, is way misleading. I'd suggest to create a `WAKE_DISTANCE` variable in your application to store such magnitude.

**Review by inigolcanalejo — APPROVED** [review]
I agree with @rubenzorrilla that having two versions of the same variables, one historical and one non historical, doing different things can be misleading. This was however not the case before having the embedded solver in the potential application.

I also like his idea of creating a new variable to store the nodal wake distance, shall we call it NODAL_WAKE_DISTANCE since it stores the wake distance at the nodes?

Shall we merge this PR and do this change in a different one?

**Comment by rubenzorrilla** [comment]
> I agree with @rubenzorrilla that having two versions of the same variables, one historical and one non historical, doing different things can be misleading. This was however not the case before having the embedded solver in the potential application.
> 
> I also like his idea of creating a new variable to store the nodal wake distance, shall we call it NODAL_WAKE_DISTANCE since it stores the wake distance at the nodes?
> 
> Shall we merge this PR and do this change in a different one?

I'd merge this one since it's a hotfix. However, I suggest to take care of this as soon as possible, since the more we wait, the more painful the change will be.

**Comment by marcnunezc** [comment]
+1 on doing a separate PR

**Pull request merged**
