### PR TITLE
[Core] Reactivating OMP in residual criteria with constraints

### PR DESCRIPTION
**Pull request by loumalouomega**
Replacing std::vector of booleans with std::vector of integers. This should work in OMP

### CODE REVIEW

**Comment by loumalouomega** [comment]
> Replacing std::vector of booleans with std::vector of integers. This should work in OMP

@philbucher how this change affects the MPI?

**Comment by loumalouomega** [comment]
Ping @RiccardoRossi

**Comment by loumalouomega** [comment]
Ping

**Comment by loumalouomega** [comment]
@RiccardoRossi @roigcarlo if this has been merged on the release branch why do we don't merge to the master?

**Review by philbucher — APPROVED** [review]

**Pull request merged**
