### PR TITLE
Dem/radial multidofs control module

### PR DESCRIPTION
**Pull request by salvalatorre**
Integrating the Radial MultiDOFs module.
Fixed many bugs.
Fixed also the tests and added different features to improve the behavior of the simulations.

### CODE REVIEW

**Comment by salvalatorre** [comment]
I didn't request reviews from anyone, just trying to make things work... Why that automatic actions?

**Comment by maceligueta** [comment]
Apparently, you changed files in many applications @salvalatorre

**Comment by salvalatorre** [comment]
Yes, yes, I'm working on it. What I mean is that there is no need to annoy anyone and send spam when it is still work in progress...

**Comment by maceligueta** [comment]
Close the PR temporarily, then

**Pull request closed without merging**
