### PR TITLE
Adding missing line

### PR DESCRIPTION
**Pull request by loumalouomega**

### CODE REVIEW

**Review by roigcarlo — APPROVED** [review]
Apologies if it was my fault :flushed:

**Comment by loumalouomega** [comment]
imagen

**Comment by philbucher** [comment]
I will merge once travis is done. I need it asap
Unless you are faster Vicente :)

**Comment by roigcarlo** [comment]
No If I can merge it first :sunglasses: 

And apologies again for the line...

**Comment by philbucher** [comment]
No worries :D

**Pull request merged**
