### PR TITLE
[Struct] remove getValuesOnIntegrationPoints

### PR DESCRIPTION
**Pull request by KlausBSautter**
Hi, w.r.t. to @philbucher commands ;) I started cleaning the StructuMechApp to continue the work of #6643.

### CODE REVIEW

**Review by philbucher — DISMISSED** [review]
perfect, thx :+1:

**Review by philbucher — DISMISSED** [review]

**Comment by philbucher** [comment]
I think this will need also some updates in Contact to be ready, let me check

**Comment by philbucher** [comment]
@loumalouomega I updated Contact right away, please take a look

**Comment by loumalouomega** [comment]
Ok from my side

**Comment by philbucher** [comment]
ok now works

**Review by philbucher — APPROVED** [review]
I tried locally, all the tests are working

**Pull request merged**
