### PR TITLE
[Core] AMatrix fix for SparseMatrixMultiplicationUtilities

### PR DESCRIPTION
**Pull request by loumalouomega**
This is a fix for the SparseMatrixMultiplicationUtilities with AMatrix

### CODE REVIEW

**Comment by philbucher** [comment]
@loumalouomega are you available?

We are trying to reach you in skype and via email for some time now...

**Comment by loumalouomega** [comment]
I was at lunch, sorry

**Comment by philbucher** [comment]
now?

**Comment by philbucher** [comment]
I mean skype now?

**Comment by loumalouomega** [comment]
Better Hangouts, skype is not working in my machine right now

**Comment by philbucher** [comment]
ok give me 5min to set it up

**Comment by loumalouomega** [comment]
Can anyone approve this BTW?

**Comment by philbucher** [comment]
do you have the Statik account in Hangouts?

**Comment by loumalouomega** [comment]
Nope

**Comment by philbucher** [comment]
For some reason I cannot start a new conversation with you

**Comment by loumalouomega** [comment]
> For some reason I cannot start a new conversation with you

Fine

**Review by philbucher — APPROVED** [review]
There is no function in Amatrix to initialize a vector?

@pooyan-dadvand ?

**Comment by pooyan-dadvand** [comment]
> There is no function in Amatrix to initialize a vector?

You can initialize it while constructing it:

```c++
Matrix a = ScalarMatrix(2,2,1.0);
```
or filling it:
```c++
Matrix a(2,2);
a.fill(2.1);
Matrix i(2,2)
i.fill_identity();
```

**Pull request merged**
