### PR TITLE
Change selected build type

### PR DESCRIPTION
**Pull request by roigcarlo**
To prevent problems with the default debug configuration of MSVC.

It may need to tweaking,

### CODE REVIEW

**Comment by oberbichler** [comment]
What was the problem?

**Comment by roigcarlo** [comment]
It was ignoring build type and building in debug. Seems to be happening the same in appveyor.

Technically is doing the same, but now its consistent.

**Comment by roigcarlo** [comment]
Provalby better to merge directly into #6508. Sorry for the noise

**Comment by rubenzorrilla** [comment]
@roigcarlo can we delete the branch?

**Comment by roigcarlo** [comment]
Of course not

**Pull request closed without merging**
