### PR TITLE
[DEM]Compatibility tweaks hotfix for main_script

### PR DESCRIPTION
**Pull request by farrufat-cimne**
removed old benchmark script

### CODE REVIEW

**Review by AlejandroCornejo — APPROVED** [review]

**Comment by AlejandroCornejo** [comment]
I've tried and now it works! thx @farrufat-cimne @maceligueta

**Comment by farrufat-cimne** [comment]
@AlejandroCornejo if some other issue show up I will try to fix it asap.
Also, as soon as you decide to migrate to the new DEM_analysis_stage I will help with that if necessary.

**Comment by maceligueta** [comment]
I see that the old function was KRATOSprint, but in DEM_procedures.py we have deprecated KratosPrint.
Is this really consistent?

**Comment by farrufat-cimne** [comment]
I left it just in case, but I guess it could be removed completely.
It has the deprecated warning, but I would wait a bit before deleting it.

**Comment by maceligueta** [comment]
The deprecation warning must be there, for the function you are deprecating. The old function was KRATOSprint. But you deprecated KratosPrint. Is that right? I just looked at it fast.

**Comment by farrufat-cimne** [comment]
Well, I just checked yesterday's PR and it seems that was already modified.
Old method in procedures was:
def KratosPrint(*args):
    Logger.Print(*args, label="DEM")
    Logger.Flush()

after merging my branch:
def KratosPrint(*args):
    Logger.PrintInfo("This method is deprecated since 01/03/2019", label="DEM")
    Logger.PrintInfo(*args, label="DEM")
    Logger.Flush()

def KratosPrintInfo(*args):
    Logger.PrintInfo(*args, label="DEM")
    Logger.Flush()

def KratosPrintWarning(*args):
    Logger.PrintWarning(*args, label="DEM")
    Logger.Flush()

**Pull request merged**
