### PR TITLE
[Structural] added const process info for elements

### PR DESCRIPTION
**Pull request by KlausBSautter**
**Description**
Changed function arguments for ProcessInfo to const.

**Changelog**
- Changed const ProcessInfo in elements
- Fixed a test by changes in the base finite differences adjoint element

### CODE REVIEW

**Review by philbucher — DISMISSED** [review]
perfect thx!

**Comment by philbucher** [comment]
@MFusseder you can afterwards clean the temp process info that you create, but not urgent

**Comment by KlausBSautter** [comment]
> @MFusseder you can afterwards clean the temp process info that you create, but not urgent

done

**Comment by philbucher** [comment]
> > @MFusseder you can afterwards clean the temp process info that you create, but not urgent
> 
> done

you are not @MFusseder ! :D

there might be more, all of them can be removed now

**Review by philbucher — APPROVED** [review]

**Comment by KlausBSautter** [comment]
> > > @MFusseder you can afterwards clean the temp process info that you create, but not urgent
> > 
> > 
> > done
> 
> you are not @MFusseder ! :D
> 
> there might be more, all of them can be removed now

I am not ???
Yeah, I just deleted the two which are part of this pr

**Comment by MFusseder** [comment]
yap, I will have a look at the temp process infos and remove them

**Pull request merged**
