### PR TITLE
[PFEMFluid] vtk output

### PR DESCRIPTION
**Pull request by KlausBSautter**
Hi, I'd like to use the vtk output from the core for the PFEMFluid app.
So I added the `output_processes` to the process list and deleted the empty `OutputSolutionStep` so that the base class is called.

### CODE REVIEW

**Comment by philbucher** [comment]
@AFranci it seems like the `PfemFluidDynamicsAnalysis` doesn't follow much the Kratos standards, even though I don't see the reason why not.

I am not sure what your plans are, if you want together with @KlausBSautter we could clean up and streamline some things to improve it?

**Comment by mpentek** [comment]
I think @RiedlAndreas managed with HDF output. Or did you also just try with VTK and failed?

**Comment by RiedlAndreas** [comment]
I tried vtk_output_process in auxiliary_process_list -> no error message, but no output created
also tried vtk_output in output_processes -> error message. I think output_processes is not used in Pfem

But:
hdf5 output in auxiliary_process_list works fine for me. 
Use multiple_mesh_temporal_output_process for saving the mesh at each step (not only once at the beginning)
I had to add the "DISPLACEMENT" variable to use it later in Paraview to show the deformed Mesh.

**Comment by KlausBSautter** [comment]
with this pr, `output_processes` is used

**Review by AFranci — APPROVED** [review]

**Comment by AFranci** [comment]
Hi all, 
for me the change is ok.
@philbucher of course you are welcome if you want to improve something in the code.

**Pull request merged**
