### PR TITLE
[Trilinos] fixing mpi-gid-output-process after #3644

### PR DESCRIPTION
**Pull request by philbucher**
this should be initialized in the constructor, but then also other things should be improved in this class, so fixing it like this ...

I am quite looking forward to mpi-testing :D

**EDIT**
I got annoyed bcs I fixed this for the third time in the previous months
I refactored the processes in order to remove the duplicated code

@jcotela @swenczowski @rubenzorrilla please have a look and try it out, much appreciated
For me it worked with some simple examples

### CODE REVIEW

**Comment by armingeiser** [comment]
#3644 broke the mpi output?

**Comment by philbucher** [comment]
Yes, due to unfortunate code duplication

**Comment by armingeiser** [comment]
Ah i see, now i also understand your comment above. Sorry about that.

**Review by jcotela — APPROVED** [review]
Works for me, approving.

**Review by rubenzorrilla — APPROVED** [review]
Works for me as well. BTW, I tested it with the 100Re cylinder test case in the GiD GUI. With this case (I don't know if this is extensible to other cases) it appears an spurious warning related to the recently added VTK output.

**Comment by swenczowski** [comment]
Yes, also for my application cases it seems to work. Thank you.

**Comment by philbucher** [comment]
>  With this case (I don't know if this is extensible to other cases) it appears an spurious warning related to the recently added VTK output.

We are aware of this, thanks for reminding us

@adityaghantasala guess we really should solve this

**Comment by philbucher** [comment]
thx for testing

**Pull request merged**
