### PR TITLE
Add wheel build for python 3.8

### PR DESCRIPTION
**Pull request by HubertBalcerzak**

### CODE REVIEW

**Review by loumalouomega — APPROVED** [review]
Thanks

**Comment by loumalouomega** [comment]
The gitlab pipeline failed, but I assume is still WIP

**Comment by loumalouomega** [comment]
Question, are we going to build 3.8 by default?, Currently the most extended is 3.7 and even the lastest Ubuntu supports officially 3.7

**Comment by HubertBalcerzak** [comment]
> Question, are we going to build 3.8 by default?, Currently the most extended is 3.7 and even the lastest Ubuntu supports officially 3.7

It would be really weird for me if we didn't. Python 3.8 is officially released and is the default version on windows and Arch linux.

**Comment by loumalouomega** [comment]
> 
> 
> > Question, are we going to build 3.8 by default?, Currently the most extended is 3.7 and even the lastest Ubuntu supports officially 3.7
> 
> It would be really weird for me if we didn't. Python 3.8 is officially released and is the default version on windows and Arch linux.

Arch Linux is far from the norm...I would consider the version considered in the Ubuntu LTS as the default. Besides I still use python 3.7 in Windows due to linking issues with GCC in MSYS2

**Comment by roigcarlo** [comment]
@HubertBalcerzak Can we delete the branch?

**Pull request merged**
