### PR TITLE
[StructuralMechanicsApplication] Transition PR for removing warning in CLs

### PR DESCRIPTION
**Pull request by loumalouomega**
This adds to the base_solid_element the missing methods in order to prepare the transition and remove the deprecated methods fro the CLs

### CODE REVIEW

**Comment by loumalouomega** [comment]
I think I will close this, some CL's are failing for not overriding the base class

**Comment by loumalouomega** [comment]
This should work, I run the tests

**Comment by philbucher** [comment]
> This should work, I run the tests

but why do you change results of tests?

**Comment by loumalouomega** [comment]
> > This should work, I run the tests
> 
> but why do you change results of tests?

This is a merge from another PR, I wanted to avoid conflict

**Comment by loumalouomega** [comment]
@philbucher https://github.com/KratosMultiphysics/Kratos/pull/3532

**Comment by philbucher** [comment]
Can you merge that one first then such that it is easier to review

**Comment by loumalouomega** [comment]
> Can you merge that one first then such that it is easier to review

It is approved, but you know how slow is lately Travis?

**Review by AlejandroCornejo — DISMISSED** [review]

**Comment by loumalouomega** [comment]
I did some clean to reduce code duplication

**Review by AlejandroCornejo — APPROVED** [review]

**Pull request merged**
