### PR TITLE
[Core][Constitutivelaw] make Check const

### PR DESCRIPTION
**Pull request by philbucher**
**Description**
Following #7381 the @KratosMultiphysics/technical-committee decided to also make the `Check` function of the `ConstitutiveLaw` `const`

Unlike for #7381 we decided to do it all in one PR as there are less changes and it avoids the backward compatibility struggles

@KratosMultiphysics/all please compile your applications against this branch and push the necessary changes to this branch
Please let us know if you encounter any problems or issues

We didn't agree yet on a timeline, I would say this should be merged ~end of January.

### CODE REVIEW

**Comment by maceligueta** [comment]
I did not detect problems when compiling DEM and Swimming DEM.

**Review by loumalouomega — DISMISSED** [review]
Okay

**Comment by rubenzorrilla** [comment]
I added the missing constitutive laws changes. Note that I required to make the `GetStrainSize` `const` to do that (I think that this method should be `const` too).

**Comment by AlejandroCornejo** [comment]
The `FemToDemApp `is ok, The `PfemFluidDynamicsApp `is not compiling though @AFranci (`fluid_constitutive_law.h`)

**Comment by rubenzorrilla** [comment]
> The `FemToDemApp `is ok, The `PfemFluidDynamicsApp `is not compiling though @AFranci (`fluid_constitutive_law.h`)

Should compile now.

**Comment by AlejandroCornejo** [comment]
> 
> 
> > The `FemToDemApp `is ok, The `PfemFluidDynamicsApp `is not compiling though @AFranci (`fluid_constitutive_law.h`)
> 
> Should compile now.

Indeed it **is compiling now in Windows**. Could be nice to run your tests @AFranci just to be sure

**Review by roigcarlo — APPROVED** [review]

**Comment by philbucher** [comment]
Thx for the help guys!

**Pull request merged**
