### PR TITLE
[Core] Remove deprecartion warnings for VariableComponent

### PR DESCRIPTION
**Pull request by sunethwarna**
**Description**
Cleanup PR following #7506 

**Changelog**
- Removing uses of `VariableComponent`
- Removing uses of `VectorComponentAdapter`

### CODE REVIEW

**Comment by philbucher** [comment]
@HubertBalcerzak can you please take a look at the `CSharkWrapperApp`? => #6686 changed / removed the `VariableComponents` so minor updates are necessary for your App to work with this
Thx

**Comment by philbucher** [comment]
@loumalouomega @marcnunezc can you please take a look at the necessary changes in the MeshingApp?
@maceligueta @GuillermoCasas also some minor updates are necessary in the swimmingDEMApp, can you please take a look when you have time?
Thx for the help

**Review by rubenzorrilla — APPROVED** [review]

**Comment by rubenzorrilla** [comment]
Changes make sense. Re-approving once the rest of apps are updated accordingly.

**Comment by philbucher** [comment]
I recommend making separate PRs for the Apps to go in before this one

After all apps are updated we can just merge master into this branch and it should work

**Comment by sunethwarna** [comment]
StatApp - Done 👍

**Review by philbucher — APPROVED** [review]

**Comment by sunethwarna** [comment]
@philbucher Can we merge this?

**Comment by philbucher** [comment]
it is approved, not sure why you wait?

**Pull request merged**
