### PR TITLE
Fix visited flag

### PR DESCRIPTION
**Pull request by roigcarlo**
That should be an OR

### CODE REVIEW

**Comment by roigcarlo** [comment]
Also we should improve the tests for this, its alarming that this were not catch :S

**Comment by philbucher** [comment]
Eieiei this should solve the problem right?
Basically you were again accumulating multiple times the values like before right?

**Comment by roigcarlo** [comment]
Actually it was worst than before :P. 
Was a corner case before, with the and and or swaped it turned it quite more frequent

**Comment by mpentek** [comment]
For me it works, seems to solve the problem in #7109. Perhaps @AndreasWinterstein can also say if this solves it for him as well, but I am quite confident it should.

**Comment by philbucher** [comment]
@roigcarlo should we port this also to the release?

**Comment by roigcarlo** [comment]
Well release is done, we should add it to the next one (probably 8.0.1) with a couple of other important bugfixes. I can make a release once this is merged.

**Comment by philbucher** [comment]
> Well release is done, we should add it to the next one (probably 8.0.1) with a couple of other important bugfixes. I can make a release once this is merged.

ok makes sense

**Comment by philbucher** [comment]
@roigcarlo can you add a small test? I.e. it should give the same results in OpenMP and MPI, this way I think we are on the safe side in the future

**Review by mpentek — APPROVED** [review]
Thanks!

**Comment by roigcarlo** [comment]
Will add the test next week

**Comment by loumalouomega** [comment]
> Will add the test next week

There is a OMP test in https://github.com/KratosMultiphysics/Kratos/pull/7062

**Pull request merged**
