### PR TITLE
Reading and writing both the fluid and the particles history

### PR DESCRIPTION
**Pull request by GuillermoCasas**

### CODE REVIEW

**Review by GuillermoCasas — COMMENTED** [review]
For me the DEM benchmarks nº 12, 16 and 32 fail. I have checked with the others and 12 and 16 fail for them too. nº 32 seems to fail inconsistently and we still do not know why. In any case, this is clearly not the fault of these commits.

**Comment by maceligueta** [comment]
I've just tested the master and all tests were succesful in my PC (Python 2.7).

**Comment by maceligueta** [comment]
How could test 12 run fine in some computers if the Json file was wrong? What do you think, @farrufat-cimne ?

**Review by maceligueta — APPROVED** [review]

**Comment by farrufat-cimne** [comment]
the 12 was not in the list. Also there was a mistake in the json so it was impossible for it to run at all.

**Pull request merged**
