### PR TITLE
[DRAFT] Experimenting with testing libs.

### PR DESCRIPTION
**Pull request by roigcarlo**
**📝 Description**
This is a draft comes from a discussion in #10693 and wants to be a preview on how this can be ported to Kratos as a whole. This has been a long overdo from our side (~10.5K items after #83 ...)

The aim is to provide a mechanism to generate stand-alone unitary test for the C++ layer of Kratos. Both for the kernel and for the apps, without having to perform any major refactor.

Disclaimer:
- **Why gtest and not doctest/xxxxtest/....**: So far, because I need mocking to make the kernel fixture and some very handy matching patterns for the asserts that are not present in doctest. This does not mean we will use this backed. Its just that it comes in handy to prototype something fast without spending much time.

Summary:
- Checks and Asserts/Expects are now separate classes. This means that you can still keep using the old `KRATOS_CHECK_XXXX` if you want to throw exceptions or check assertions in debug mode etc... but also have the same family of macros to produce results for asserts in checks.
- Tests are now compiled as individual executable. Each *.cpp test file defines its own suite. This is done automatically through CMake but is not the ideal solution. I would change this to better organize tests and reuse some helper classes, but as for now it let us use the current tests without changes.
- I am aware that are tests failing. To my knowledge:
  - The test testing the internal tester class (for obvious reasons)
  - Tests that check exception throwing for out of bounds accesses or other undefined behaviors, as are not captured (and shouldn't be)
  - Some few tests that are reporting memleaks. I will investigate those individually, but I suspect that we are detecting hidden errors derived from the fact of using a new Kernel in each test.

### CODE REVIEW

**Review by loumalouomega — CHANGES_REQUESTED** [review]
Blocking for the moment

**Comment by loumalouomega** [comment]
There are plenty of conflicts @roigcarlo

**Comment by roigcarlo** [comment]
I know. I created the branch with a perfect timing, as always.

**Comment by loumalouomega** [comment]
> I know. I created the branch with a perfect timing, as always.

Todo ha salido deacuerdo con el flan

**Comment by huhaas** [comment]
I like the redirect macros to have an easier transition.

Creating a dependency on GoogleTest can be done with this instruction:
https://google.github.io/googletest/quickstart-cmake.html#set-up-a-project
Locally it works and looks quite elegant. CMake will take care of the building and include logic.
Later, updating will be as easy as updating a single hash.
The downside is that the build servers need to reach the zip.

I'm not in favor of creating individual executables per test file. The list of 'possible build targets' will explode.
Each executable will create its own test report file and has an execution overhead (I'm guessing this will be noticeable).
Combining test reports is a pain.

I would expect 1 executable for the core and 1 for each application.
The built-in argument mechanism should be sufficient to run a single or subset of tests.

**Pull request closed without merging**
