### PR TITLE
[ShapeOpt] add missing init files

### PR DESCRIPTION
**Pull request by armingeiser**
**📝 Description**
The subfolders of the python scripts folder in the ShapeOptApp had no `__init__.py` files. 

I don't know why it works without but its good practice to have those files in each folder. 

**🆕 Changelog**
- Added `__init__.py` to all submodules in ShapeOptimizationApplication

### CODE REVIEW

**Comment by miguelmaso** [comment]
> I don't know why it works without but its good practice to have those files in each folder.

it was introduced in #3217

**Comment by philbucher** [comment]
> > I don't know why it works without but its good practice to have those files in each folder.
> 
> it was introduced in #3217

actually the solution from #3217 was only an intermediate solution that was removed when we switched to the new installation mechanism (#5825). 
Basically #3217 enabled us to use the python-scripts properly (i.e. `from Kratos.AppName import py_script.py` instead of `import py_script.py`) This was a prerequisite for #5825

I am not sure why it works without the `__init__.py`. The CoSimApp has many subfolders but so far it was always working without

@roigcarlo do you know better?

**Comment by sunethwarna** [comment]
Isn't it because of the following that we can use python imports eventhough we don't have `__init__.py` files?

https://docs.python.org/3/whatsnew/3.3.html#pep-420-implicit-namespace-packages

**Comment by armingeiser** [comment]
Hm, maybe it works because of the namespace package thing as @sunethwarna says. 

But from what i understand we are not actually using namespace packages, but all our apps should rather be "standard" packages, thus the `__init__.py``files should be there.

**Review by roigcarlo — APPROVED** [review]
Exactly as @sunethwarna says. As we had support for 2.x when we make the change to use standard python modules it wouldn't have worked without. In any case I still think is a good idea to have the `__init__.py` file, among other reasons because not all our folders are sub-modules and this is a clean way to differentiate them.

**Pull request merged**
