### PR TITLE
[StructMech] add virtual to structural response base class functions

### LINKED ISSUE #4175: [StructuralMechanics] clang compiler warnings from nightly build
~~~
/home/ubuntu/Kratos/applications/StructuralMechanicsApplication/custom_response_functions/response_utilities/adjoint_nodal_displacement_response_function.h:84:10: warning: 'Kratos::AdjointNodalDisplacementResponseFunction::CalculateGradient' hides overloaded virtual function [-Woverloaded-virtual]
/home/ubuntu/Kratos/applications/StructuralMechanicsApplication/custom_response_functions/response_utilities/adjoint_local_stress_response_function.h:81:10: warning: 'Kratos::AdjointLocalStressResponseFunction::CalculateGradient' hides overloaded virtual function [-Woverloaded-virtual]
~~~

### PR DESCRIPTION
**Pull request by armingeiser**
attempt to solve #4175

closes #4175

### CODE REVIEW

**Comment by philbucher** [comment]
I a almost 100% sure this won't solve the warning
Check out https://stackoverflow.com/questions/18515183/c-overloaded-virtual-function-warning-by-clang, I think this will solve it

before mreging maybe @jcotela can compile with clang to confirm the warnings are gone :)

**Comment by armingeiser** [comment]
You are probably right.

**Comment by msandre** [comment]
Try adding `using AdjointResponseFunction::CalculateGradient;` to the public part of the derived classes.

**Comment by armingeiser** [comment]
I added the `using base::method` idea as suggested.
For me it compiles and the tests are still running. But i don't have clang...
@jcotela you mentioned that you have clang installed, maybe you could do a test compilation of StructuralMechanicsApplication if you have time and check if the warning is still there?

**Comment by jcotela** [comment]
@armingeiser I had to add the same `using` in some more classes, but clang compiles clean now.

**Comment by armingeiser** [comment]
Thanks @jcotela. Maybe @philbucher or @MFusseder can approve it.

**Review by MFusseder — APPROVED** [review]

**Pull request merged**
