### PR TITLE
Solvers in DamApplication have been redesigned

### PR DESCRIPTION
**Pull request by ipouplana**
Summary of changes:

- Solvers in DamApplication have been adapted to be compatible with OMP and MPI.

- Some files from DamApplication and PoromechanicsApplication have been modified as they are related to the solvers in one way or another. 

- The old problemtype in DamApplication has been erased as it is incompatible with the new solvers. The only problemtype available will be the one in KratosMultiphysics/GiDInterface.

- Some minor corrections have been introduced both in DamApplication and PoromechanicsApplication.

### CODE REVIEW

**Comment by loumalouomega** [comment]
NICE WORK

**Comment by lorenzogracia** [comment]
This is something that was needed.

Nice work as @loumalouomega  says, just comment that dividing the work in small commits makes the code more understandable and easier to review.  Well done!!

**Review by lorenzogracia — CHANGES_REQUESTED** [review]
I don't approve this merge until the new GUI is completed, also new test examples must be included.

**Review by pooyan-dadvand — CHANGES_REQUESTED** [review]
There is a comment and uncomment mechanism for enabling the trilinos. I would strongly avoid such a mechanism due to following problems:
- It would be too easy that an accidental commit make the code uncompilable in windows
- It would be several unnecessary history change 
- It is not modular

I would suggest to have another file "add_mpi_strategies_to_python.cpp" in which you include the trilinos and only the mpi compatible strategies. Then you may control the build in cmake directly.

**Comment by lorenzogracia** [comment]
The new test examples as well as the new GUI are already available, so I am going to approve your pull request. It is just needed that @pooyan-dadvand approves the changes related to MPI.

**Review by lorenzogracia — APPROVED** [review]

**Review by pooyan-dadvand — COMMENTED** [review]
Thanks for your changes.

There are several .csv files in your commit. Are they really necessary?

**Comment by lorenzogracia** [comment]
Hi pooyan, 

the .csv files are needed for the GUI. These .csv are related to the input tables, so if someone opens the test_example with GiD and run it, if .csv files are not there, the simulation is not going to run since the scipt will not find the required files.  

Thanks for your comments.

**Comment by pooyan-dadvand** [comment]
Now I see, sorry for my ignorance!

**Review by pooyan-dadvand — APPROVED** [review]

**Pull request merged**
