### PR TITLE
[Core][ModelPart][Constraint] removed unused exposure

### PR DESCRIPTION
**Pull request by philbucher**

### CODE REVIEW

**Comment by adityaghantasala** [comment]
I had this also in mind 

https://github.com/KratosMultiphysics/Kratos/blob/f1f93b2694e9f63f6da8446c479ac43359eef5e6/kratos/includes/model_part.h#L742

This is explicit with a variable component !

**Comment by philbucher** [comment]
> I had this also in mind
> 
> https://github.com/KratosMultiphysics/Kratos/blob/f1f93b2694e9f63f6da8446c479ac43359eef5e6/kratos/includes/model_part.h#L742
> 
> This is explicit with a variable component !

you are right, done

**Review by philbucher — COMMENTED** [review]
@KlausBSautter I think this is broken since #6686 

With this it should work again

**Comment by philbucher** [comment]
replaced by #6994

**Pull request closed without merging**
