### PR TITLE
[Core] Adding consistent inertia tensor (symmetric matrix)

### PR DESCRIPTION
**Pull request by loumalouomega**
To replace in current implementations where not product inertias are considered

### CODE REVIEW

**Comment by GuillermoCasas** [comment]
Just curious: what does the nodal tensor of inertia represent?

**Comment by loumalouomega** [comment]
> Just curious: what does the nodal tensor of inertia represent?

This will be the equivalent to NODAL_MASS for inertia, which means the "condensed" inertia tensor in the node (in order to compute rigid movements of rotations)

**Comment by GuillermoCasas** [comment]
> > Just curious: what does the nodal tensor of inertia represent?
> 
> This will be the equivalent to NODAL_MASS for inertia, which means the "condensed" inertia tensor in the node (in order to compute rigid movements of rotations)

Thanks. I assume there is a proper way to use the condensed inertia, although it is not as straight-forward as the mass, since the condensation process implies a geometrical transformation that will not leave the inertia unchanged. I will research this.

**Comment by loumalouomega** [comment]
> > > Just curious: what does the nodal tensor of inertia represent?
> > 
> > 
> > This will be the equivalent to NODAL_MASS for inertia, which means the "condensed" inertia tensor in the node (in order to compute rigid movements of rotations)
> 
> Thanks. I assume there is a proper way to use the condensed inertia, although it is not as straight-forward as the mass, since the condensation process implies a geometrical transformation that will not leave the inertia unchanged. I will research this.

Yep, you need to apply the Steiner principle, we still have pending to change that in the explicit schemes. But that requires extra work.

**Comment by loumalouomega** [comment]
Ping

**Review by philbucher — DISMISSED** [review]
sorry missed it

no python exposure?

**Comment by loumalouomega** [comment]
True

**Comment by loumalouomega** [comment]
@philbucher I exposed to python

**Review by philbucher — APPROVED** [review]

**Comment by loumalouomega** [comment]
Hurray

**Pull request merged**
