### PR TITLE
Pybind11/updating to 2.2.4

### LINKED ISSUE #2867: Pybind11 produces many deprecation warnings when compiling with Python 3.7
As it says on the title. This makes it hard to detect real kratos warnings in compilation output.

Apparently pybind developers have already solved it (https://github.com/pybind/pybind11/issues/1444) so I'd like to ask the @KratosMultiphysics/technical-committee permission to update the pybind version in this repo.

### PR DESCRIPTION
**Pull request by jcotela**
Opening the PR for discussion in the @KratosMultiphysics/technical-committee 

Updating pybind11 to newer version to silence the Python 3.7 warnings reported in #2867.

I have tested it in linux (manjaro) and it works, but I'd like to ask someone to try it in windows or with older pythons in case it breaks something.

closes #2867

### CODE REVIEW

**Comment by pooyan-dadvand** [comment]
@philbucher would you please check if this work with the newest intel compiler?

**Comment by philbucher** [comment]
yes I will check, but only after next week, I am not at work next week

**Comment by philbucher** [comment]
I had time to test it now with the following configuration:
Intel Compiler 2018 (with GCC 5.4 in the background)
It compiles without warnings both with OMP enables and disabled (via `DKRATOS_EXCLUDE_OPENMP`)
As before, it segfaults if I compile with OMP-support but it seems to work if I disable it

**Comment by jcotela** [comment]
Thanks a lot for checking @philbucher

**Comment by pooyan-dadvand** [comment]
Thanks @philbucher

**Comment by RiccardoRossi** [comment]
is there anyone with gcc4.9 or gcc4.8 installed to try this?

note that if the answer is NO we may be tempted to assume we do not need to support it any longer

**Comment by philbucher** [comment]
Afaik some industry still uses 4.8.4 ...
Maybe check that first?

@RiccardoRossi how are we explicitly supporting these compilers?

**Comment by RiccardoRossi** [comment]
hi @philbucher i don't have a forma answer for this.

we support c++11, which means gcc4.9, however so far it has also been possible to compile kratos with 4.8+ and --std=gnu11

i think that a decision to break such compatibility should be conscient...

**Comment by philbucher** [comment]
@jcotela could you please wait with merging, I want to port the rest of the apps this week such that the "hack" is no longer necessary?

**Comment by jcotela** [comment]
@philbucher no hurry, we are anyway blocked until we check the gcc4.8 compatibility.

**Comment by philbucher** [comment]
@jcotela I made PRs for all remaining apps
Only the AdjointFluidApp is missing (it is removed in #3153 ) and the mpi-search-app, which is not fully ported to pybind (fyi @roigcarlo )

**Comment by jcotela** [comment]
@philbucher I believe these two can be left out. At least the AdjointFluidApp is going away soon as you say.

@roigcarlo do you remember which was the motivation for the hack? I mean in order to test if we can live without it now.

**Comment by philbucher** [comment]
@jcotela I think the reasons for the hack are explained in #2264 and #2326

**Comment by jcotela** [comment]
@philbucher I see... I need to get my hands on a working windows setup, then.

**Comment by philbucher** [comment]
@jcotela FYI all PRs are merged

**Comment by philbucher** [comment]
@jcotela can you revert the hack?
Then I would test it again with Intel

**Comment by jcotela** [comment]
@philbucher there you go

**Comment by philbucher** [comment]
So I tested it with Intel compiler and here are some prelim results:
In FullDebug the OpenMP problems seem to have gone, but in Release it still crashes xD
@roigcarlo do you have an idea if there are certain compiler-flags that could influence this?

**Comment by roigcarlo** [comment]
Sorry I lost the notification for this issue at some point.
We added the hack because both of us were defining size_t, and we were using the pybind11 module by

```c++
using namespace pybind11
```

So we were importing everything and some compilers complaint there were multiple definitions of `size_t`

@philbucher Which exactly is the error now in release?

**Comment by philbucher** [comment]
@roigcarlo the same one as before, omp seems to be the problem
Strange though that it seems to be working in FullDebug
Are there different flags defined related to omp?

**Comment by roigcarlo** [comment]
Probably is an optimization flag that is messing up the code from openmp...
Maybe we could try to compile with the custom mode and adding the flags manually, for example everything except the -OX ( I think its 03 in release for intel) to see what happens

**Comment by philbucher** [comment]
what is the status of this PR?

**Comment by jcotela** [comment]
@philbucher the PR is ready, but we need to check that we are not introducing additional restrictions to the minimum supported gcc version. The problem is that no-one here seems to have a working gcc 4.8 anymore...

**Comment by roigcarlo** [comment]
Compiling it right now with 4.8.5. 

I Will post the results.

**Comment by loumalouomega** [comment]
I will be happy to get rid of those dammed warnings

**Comment by roigcarlo** [comment]
List of applications I've tested (Gcc 4.8.5 ubuntu 14.04, the oldest thing I could fine)

- ExternalSolvers
- ConstitutiveModels
- ConvectionDiffusion
- MeshMoving
- SolidMechanics
- FluidDynamics
- FSI
- StructuralMechanics (with mmg)
- Metis
- Poromechanics
- Trilinos
- Dem
- SwimmingDem
- EigenSolver
- ParticleMechanics
- Dam

I did not test FEAST and Pastix solvers because they are not enabled in the release, apart from that the rest seems to work just fine.

**Comment by jcotela** [comment]
@KratosMultiphysics/altair can you confirm that you updated the `namespace py = pybind11;` (intead of `using namespace pybind11`) in your applications? This PR would force you to use the new syntax. If it is a problem, let us know and we can roll back this particular change.

**Comment by ddiezrod** [comment]
@jcotela Yes, we did! Thanks for reminding us! @KratosMultiphysics/altair

**Comment by philbucher** [comment]
Awesome!
Once this is merged I will give the problems with the Intel-Compiler #2690 another try :)

**Comment by pooyan-dadvand** [comment]
@KratosMultiphysics/technical-committee approves this PR. Thanks!

**Review by roigcarlo — APPROVED** [review]
👍

**Pull request merged**
