### PR TITLE
Hotfix cpp tests

### PR DESCRIPTION
**Pull request by roigcarlo**
@pooyan-dadvand  There was a missing import.
Also. I set the tests to TESTS_LIST instead of PROGRESS because otherwise it dosn't tell wich test is failing :S.

Not sure if this is intended. Right now there is one failing that I am aware of.

### CODE REVIEW

**Comment by pooyan-dadvand** [comment]
Are you sure it is failing? if it fails it shows the failed one separately. if it is saying that 140 of 141 ran means one is disabled.

**Comment by roigcarlo** [comment]
While running with progress I get this:

```
Running cpp tests
/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/7.1.1/../../../../include/c++/7.1.1/debug/vector:417:
Error: attempt to subscript container with out-of-bounds index 4, but 
container only holds 4 elements.

Objects involved in the operation:
    sequence "this" @ 0x0x7ffd199095f0 {
      type = std::__debug::vector<std::__debug::array<double, 3ul>, std::allocator<std::__debug::array<double, 3ul> > >;
    }
[1]    14707 abort (core dumped)  python run_tests.py
```

**Review by pooyan-dadvand — APPROVED** [review]
:+1:

**Comment by pooyan-dadvand** [comment]
oh oh, this is a serious error... ok so let's put it as progress list. Would you please run the tests manually to see which one is?

**Comment by roigcarlo** [comment]
@pooyan-dadvand Seems that it was a problem in my side. Now it works as intended, so i left progress as you suggested. Also i changed the way the output is captured so the progress dots will be shown (were hiden before)

**Comment by pooyan-dadvand** [comment]
:+1:

**Pull request merged**
