### PR TITLE
[StructuralMechanicsApplication] Some explicit optimization

### PR DESCRIPTION
**Pull request by loumalouomega**
This reduces slightly the creation destruction operations, which are expensive in explicit simulations

### CODE REVIEW

**Review by philbucher — APPROVED** [review]
looks good to me

did ou run the tests in fulldebug?

**Comment by loumalouomega** [comment]
I run in Release, but now one of them is failing in full debug. Fixing

**Comment by loumalouomega** [comment]
False alarm, it was a local change

**Review by frastellini — APPROVED** [review]
Thank you for the improvements

**Pull request merged**
