### PR TITLE
[Core][GidPost]Adding elemental and conditional flags to post process

### PR DESCRIPTION
**Pull request by loumalouomega**
This add the possibility to get the flags from elements and conditions to post process

### CODE REVIEW

**Comment by loumalouomega** [comment]
Related with #2495

**Comment by loumalouomega** [comment]
BTW it is used adding: "elemental_conditional_flags_results" to the gid post process configuration

**Comment by philbucher** [comment]
You write the flag result on every GP of the elem/condition?

**Comment by loumalouomega** [comment]
Yes, the alternative would be to extrapolate to the nodes, but does implies extra calculus and an utility that is in the MeshingApplication. And it is not possible to define the minim number of GP for the element or condition, because if the element has a different number GiD is not able to read the solution

**Comment by jcotela** [comment]
@loumalouomega I see quite a bit of potential for merge conflicts here with #2194. Can you contact me before merging so that we can coordinate the changes? Thanks!

**Comment by loumalouomega** [comment]
@jcotela I have no problem to contact you. A priori this should not be very problematic, it uses the GiD GP, but just because it avoid certain problems. But this doesn't call in any moment the CalculateOnIntegrationPoints methods or equivalent

In any case tell me when you are available, and I will manage

**Comment by jcotela** [comment]
@loumalouomega I know, but we are touching the same files... It is just to coordinate. Just let me know when this is ready to merge and I'll try to see what happens with the other branch (since I'm sure that one will take longer...)

**Comment by loumalouomega** [comment]
Ok

**Comment by loumalouomega** [comment]
I mean, this is ready

**Comment by loumalouomega** [comment]
After speaking with @josep-m-carbonell we decided to change the name to a consistent one, additionally I added the equivalent for non historical values of elements and conditions

**Comment by loumalouomega** [comment]
I forgot to add the test, on it

**Comment by loumalouomega** [comment]
@jcotela I tried to merge #2194 with this one. The conflict is very small, just the file gid_gauss_point_container.h, and it can be corrected from GitHub interface

**Review by jcotela — CHANGES_REQUESTED** [review]
I agree with the new variant methods for flags, but I do not understand what is going on with the new `NonHistorical` gauss point results. As far as I can tell, they are calling `GetValue` instead of `GetValue/CalculateOnGaussPoints` (which is called by the pre-existing methods).

What is the use case for the new methods? Coming from the discussions in #523, I am not in favour of adding yet a new method to interact with integration points (additionally, the GetValue/SetValue methods have never been specifically associated to integration points so far).

**Comment by loumalouomega** [comment]
The NonHistorical is for consistency with the nodal, where the name is to differentiate the values from GetSolutionStepValuye and GetValue

**Comment by loumalouomega** [comment]
The methods doesn't use anything related with integration points, the use of Gauss Points is only a technique to represent on GiD without extrapolate values.The only GaussPoints used are the ones from GiD

**Comment by jcotela** [comment]
The "historical" name comes from the fact that the nodal `GetSolutionStepValue` accesses a database that has a concept of time step (current vs old time step results), while the `GetValue` accesses one that doesn't. This does not happen in the case of integration points: neither the GetValuesOnIntegrationPoints nor the GetValue methods have an associated notion of time-step, at least not in any standard way. I think that trying to differentiate between them by using "Non-historical" in the function name is not helpful, since it is not a meaningful description.

**Comment by loumalouomega** [comment]
I know, any suggested name?, I just choose that name for consistency with the nodes, which implies a lack of consistency with what it does

**Comment by josep-m-carbonell** [comment]
can be  *_local_results    or    *_local_data

**Comment by loumalouomega** [comment]
I will consider "_local_data", I think is the more descriptive

**Comment by loumalouomega** [comment]
Done

**Comment by loumalouomega** [comment]
@jcotela can we proceed now?

**Comment by jcotela** [comment]
@loumalouomega sorry for the delay, I was away for most of the week.
To be honest, I still do not see the need for the new methods. The modification of the flags is good and I would have approved it straight away if you just added one feature per PR... The new ones, I think will just complicate things. Elements and conditions are already huge classes with lots of boilerplate and vaguely related methods, and this is not making them better.

I would suggest the following, which has worked for me in the past:
- The base Element/Condition::GetValueOnIntegrationPoints prints elemental data (it gets whatever variable is requested from this->GetValue())
- Derived Elements implement some type of if/else depending on variable:
```
if (rVariable == <some variable this element stores/calculates>)
{
  // do element specific things and provide custom result
}
else
{
  // call base class behaviour (get from data)
}
```

in this way, we don't need to duplicate the interface methods. Would this work for you?

**Comment by loumalouomega** [comment]
Ok, do I revert the last commits?

**Comment by jcotela** [comment]
@loumalouomega as you prefer. We can also finish this here, since we are discussing it here anyway...

**Comment by loumalouomega** [comment]
Already reverting...compiling and running tests, one sec

**Comment by loumalouomega** [comment]
BTW sorry if I was that recursive, I didn't know you were out

**Comment by loumalouomega** [comment]
Done

**Review by jcotela — APPROVED** [review]

**Comment by jcotela** [comment]
@loumalouomega approving the flag methods. What should we do with the rest? I think it is a worthwhile feature, it's just that I'm not sure how to best implement it.
(If we go with the base-class proposal, I'd implement it after the new GaussPoint methods, since they are re-writting those same functions)

**Comment by loumalouomega** [comment]
If we implement in the base class 95% of the derived elements will override it, I think we can define in the base class, but derived classes should call it too (at least the call to the base class)

**Pull request merged**
