### PR TITLE
Applying changes from #1178 to Release-5.2

### PR DESCRIPTION
**Pull request by roigcarlo**
#1178 to Release-5.2

I had problems with the merge so I made a patch. The diff should remain the same.

### CODE REVIEW

**Comment by loumalouomega** [comment]
@roigcarlo @lorenzogracia Maybe is a good idea to do the same with last changes in the Damm application

**Comment by roigcarlo** [comment]
I 'd like 5.2.1 to be scheduled before christmas, so if you want, hurry up!

**Comment by rubenzorrilla** [comment]
Thanks @roigcarlo! There are some aesthetic pending changes in that branch (the ones related with the applications import). If I'm not wrong, this is not relevant from the release point of view. Isn't it?

**Comment by roigcarlo** [comment]
No, even more if we merge that it won't compile here. If this is ok i will merge as is.

**Review by rubenzorrilla — APPROVED** [review]

**Comment by lorenzogracia** [comment]
@loumalouomega  thanks for mentioning! Yes, It would be nice include the current dam state but it is also needed to update the scripts of the problemtype (@jginternational )

**Pull request merged**
