### PR TITLE
[FastPR][Core] Remove c2c variables

### PR DESCRIPTION
**Pull request by rubenzorrilla**
**Description**
As discussed yesterday, remove the unused C2C variables. This fixes the `TEMPERATURE_GRADIENT` variable issues we are experiencing in the CI of  #7831 .

**Changelog**
- Remove C2C variables
- The unique include of these is found in the PFEM2Application. I tried in my machine and this compiles perfectlty.

### CODE REVIEW

**Review by RiccardoRossi — COMMENTED** [review]
ok to me.

@ddiezrod @pooyan-dadvand  this might affect u, can u approve?

**Comment by loumalouomega** [comment]
Clean up

imagen

**Comment by rubenzorrilla** [comment]
> ok to me.
> 
> @ddiezrod @pooyan-dadvand this might affect u, can u approve?

@pooyan-dadvand confirmed yesterday that these can be removed.

**Review by roigcarlo — APPROVED** [review]

**Review by ddiezrod — CHANGES_REQUESTED** [review]
Please, give me some time to solve this in our side.

**Comment by rubenzorrilla** [comment]
> Please, give me some time to solve this in our side.

OK. But note that we are a bit in a hurry as #7831 is waiting for this to hotfix the MPI end of execution issue.

**Comment by ddiezrod** [comment]
Well, ok, then I'll let you merge this. I will try to solve this on our side before we merge from master next time.

**Review by ddiezrod — APPROVED** [review]

**Comment by rubenzorrilla** [comment]
Thanks @ddiezrod !

**Pull request merged**
