### PR TITLE
[ParticleMechanicsApplication]/add const elements conditions

### PR DESCRIPTION
**Pull request by VeronikaSinger**
update of interfaces according to #8090 
Can you check please @KratosMultiphysics/mpm @philbucher

### CODE REVIEW

**Review by philbucher — DISMISSED** [review]
:+1: 
cool thx

**Comment by philbucher** [comment]
@VeronikaSinger there are still some updates missing, did you try to compile this agains #8090 ?

**Review by philbucher — APPROVED** [review]
now it works

**Comment by VeronikaSinger** [comment]
sorry...thanks @philbucher

**Comment by peterjwilson** [comment]
Bless you @VeronikaSinger 🙌 🥳

**Pull request merged**
