### PR TITLE
FSI application tests variable bug correction

### PR DESCRIPTION
**Pull request by rubenzorrilla**

### CODE REVIEW

**Review by jcotela — APPROVED** [review]
:+1: Is the other issue (new function names in the structural strategy) also solved?

**Comment by rubenzorrilla** [comment]
The tests output in my machine is ok. So I think it is already solved... In any case I'm checking it again.

**Comment by pooyan-dadvand** [comment]
Please don't forget to merge it to the master and also to the release branch!!

**Comment by jcotela** [comment]
@rubenzorrilla Yes, it is fixed in master

**Comment by pooyan-dadvand** [comment]
@rubenzorrilla Have you also merged it to the release?

**Comment by rubenzorrilla** [comment]
@pooyan-dadvand  I've just done it. As soon as I run the tests I will pull the changes.

**Pull request merged**
