### PR TITLE
Adding _DEBUG for win under fulldebug.

### PR DESCRIPTION
**Pull request by roigcarlo**

### CODE REVIEW

**Comment by philbucher** [comment]
Good luck with debugging ;)

**Comment by RiccardoRossi** [comment]
@Rbravo555 @AlejandroCornejo you guys have win. could u take a look if it works as expected?

**Comment by Rbravo555** [comment]
Hello,

I have compiled it in Release and it passed the Core tests, however it
doesn’t find the ExternalSolversApplication for the tests of the other
applications.

So, two questions:

-Is there some setup that I forgot to perform to get the external solvers
app working? I have only changed from the standard configure file: the
paths to Boost, liblapack, libblas and Python. Plus adding the flag “-A
x64” for Visual Studio...

-Should I have compiled in FullDebug?

**Comment by roigcarlo** [comment]
ping @RiccardoRossi

**Comment by Rbravo555** [comment]
I have compiled the branch in FullDebug in Windows, and it works well. 

The tests of the StructuralMechanicsApplication have passed, and we are able to set breakpoints from VisualStudio.

image

**Review by RiccardoRossi — APPROVED** [review]

**Pull request merged**
