### PR TITLE
[MeshingApplication] Adding utility to transform hexahedra mesh into tetrahedra mesh

### PR DESCRIPTION
**Pull request by loumalouomega**
This utility splits the hexa into 5 tetrahedra. Test included

### CODE REVIEW

**Comment by rubenzorrilla** [comment]
When you perform the splitting, are the tetrahedra faces conformant with the neighbour ones? (just wondering, I see some potential uses of this)

**Comment by loumalouomega** [comment]
> When you perform the splitting, are the tetrahedra faces conformant with the neighbour ones? (just wondering, I see some potential uses of this)

Good point, I will ensure it. Let me one moment

**Comment by loumalouomega** [comment]
Closing for now, reopening when fixed

**Comment by loumalouomega** [comment]
(BTW, this explain the weird results I was getting)

**Pull request closed without merging**
