### PR TITLE
[Core] Update badge Release. Also adding cool badges related

### PR DESCRIPTION
**Pull request by loumalouomega**
**Description**
Update badge Release. Also adding cool badges related

**Changelog**
- Update badge Release. 
- Also adding cool badges related.

imagen

### CODE REVIEW

**Comment by loumalouomega** [comment]
Ping @roigcarlo

**Comment by rubenzorrilla** [comment]
This lacks the current Twitter badge.

**Comment by loumalouomega** [comment]
> This lacks the current Twitter badge.

It is there:

imagen

**Comment by rubenzorrilla** [comment]
> > This lacks the current Twitter badge.
> 
> It is there:
> 
> imagen

Ouch, it wasn't there in your previous pic. Sorry.

**Comment by loumalouomega** [comment]
> > > This lacks the current Twitter badge.
> > 
> > It is there:
> > 
> > imagen
> 
> Ouch, it wasn't there in your previous pic. Sorry.

Then it is OK?

**Comment by rubenzorrilla** [comment]
> > > > This lacks the current Twitter badge.
> > > 
> > > 
> > > It is there:
> > > imagen
> > 
> > 
> > Ouch, it wasn't there in your previous pic. Sorry.
> 
> Then it is OK?

For me it's OK if @roigcarlo has no objection.

**Comment by roigcarlo** [comment]
Ok

**Review by rubenzorrilla — APPROVED** [review]

**Pull request merged**
