### PR TITLE
[External] Update VexCL to its latest release

### LINKED ISSUE #11795: [External] VexCL out of date
The version of `VexCL` we have right now is incompatible with our `AMGCL` version. I've said this before, but our dependencies could use an update.

@roigcarlo is there a special trick to updating our dependencies, or can I go ahead and grab a copy of `VexCL`, copy it into `Kratos` and open a PR myself?

By the way, I'm not much of a fan of `git submodule`, but it's a lot more appropriate than just copying parts of other repositories into Kratos. We're lacking basic information of our dependencies (version, license, etc.) that make debugging extremely difficult. Furthermore, it makes `Kratos` more difficult to be adopted by companies since they must vet any software they're using (including dependencies), and they're completely in the blind about our external libs.

### PR DESCRIPTION
**Pull request by matekelemen**
Copy + paste the latest [VexCL](https://github.com/ddemidov/vexcl) release's (1.4.3) source to our external libs directory.

Addresses #11795.

### CODE REVIEW

**Comment by matekelemen** [comment]
I'm marking this PR as a draft until I get home and can test it on a beefier GPU.

**Review by loumalouomega — APPROVED** [review]

**Comment by ddemidov** [comment]
@matekelemen , current vexcl should work with current amgcl, but just in case, did you run some tests with GPUs on the Kratos side?

**Comment by matekelemen** [comment]
> @matekelemen , current vexcl should work with current amgcl, but just in case, did you run some tests with GPUs on the Kratos side?

Unless I messed something up on my system, the current AMGCL and VexCL versions are incompatible. The problem I ran into was that `vex::gather` and `vex::scatter` are templated in the current VexCL version, while the AMGCL backend expects non-template classes:

https://github.com/KratosMultiphysics/Kratos/blob/4adfb7c82a0ce6cacdb2cdccc28187ecc20d3b92/external_libraries/vexcl/vexcl/gather.hpp#L91-L92

https://github.com/KratosMultiphysics/Kratos/blob/4adfb7c82a0ce6cacdb2cdccc28187ecc20d3b92/external_libraries/vexcl/vexcl/gather.hpp#L132-L133

https://github.com/KratosMultiphysics/Kratos/blob/4adfb7c82a0ce6cacdb2cdccc28187ecc20d3b92/external_libraries/amgcl/backend/vexcl.hpp#L211

https://github.com/KratosMultiphysics/Kratos/blob/4adfb7c82a0ce6cacdb2cdccc28187ecc20d3b92/external_libraries/amgcl/backend/vexcl.hpp#L234

The [commit](https://github.com/ddemidov/vexcl/commit/6ff7e175329817711d89819fd00de797e6a5de59) that removed template parameters from VexCL's `gather` and `scatter` is dated Dec. 27. 2019, but the [last change](https://github.com/KratosMultiphysics/Kratos/commit/a034674b0605753f8d584808341b62c5fd09ad9f) to Kratos' version of  VexCL is dated Feb. 8. 2019.

**Comment by ddemidov** [comment]
Sorry, by "current" I meant upstream current.

**Comment by matekelemen** [comment]
> Sorry, by "current" I meant upstream current.

Ah, right. Unfortunately, we don't have any tests for GPU acceleration so I'll have to check it out manually. The machines I have access to right now don't have a GPU that would be capable enough, so I'll have to wait until I get home.

**Comment by matekelemen** [comment]
I ran some cases (AMD GPU with OpenCL backend) and the results seem to be OK.

**Review by ddemidov — APPROVED** [review]

**Pull request merged**
