### PR TITLE
rename EigenSolversApp to LinearSolversApp

### PR DESCRIPTION
**Pull request by philbucher**
After some discussion on #6888 and in person this is an improved attempt to #6888 

This is a purely local change to the Application, with this solution we will only loose the history in `CMakeLists.txt` and `EigenSolversApplication.py`

The big advantage of this change is that it is fully backward compatible, i.e. the remaining changes can be done one by one

@oberbichler please have a look

FYI @KratosMultiphysics/technical-committee

### CODE REVIEW

**Comment by armingeiser** [comment]
> This is a purely local change to the Application, with this solution we will only loose the history in CMakeLists.txt and EigenSolversApplication.py 

Nice!

**Comment by armingeiser** [comment]
Question is if the renaming of the term "EigenSolversApplication" to "LinearSolversApplication" should also be done here? I think the important difference to  #6888 is that there are no duplicated files at any time, i am not concerned with the amount of changes ("EigenSolversApplication" appears only ~60 times)

**Comment by philbucher** [comment]
> Question is if the renaming of the term "EigenSolversApplication" to "LinearSolversApplication" should also be done here?

In principle yes, but this PR already touches 376 files, so I would prefer to do it in a separate PR, following right after this one is merged. Is that ok for you?

**Comment by oberbichler** [comment]
Very good idea!

**Review by oberbichler — DISMISSED** [review]

**Comment by philbucher** [comment]
@armingeiser do you agree with this?
If so I would merge it soon, otherwise I again forget what other things have o be updated afterwards :D
Plus less chances for conflicts

**Review by armingeiser — APPROVED** [review]

**Pull request merged**
