### PR TITLE
Hotfix/applying #2910 to 6.0

### PR DESCRIPTION
**Pull request by roigcarlo**
Title

### CODE REVIEW

**Comment by roigcarlo** [comment]
Fixes #2151

**Comment by RiccardoRossi** [comment]
as i told in the other PR, this "fix" is actually changing the behaviour... i am not convinced we should do it this way...

**Comment by roigcarlo** [comment]
I don't understand this topic enough for me to catch the nuances. If we need to change it can be done, but pls fast. Just tell me what to change and I will updload it.

We are far behind the schedule for the release.

**Comment by loumalouomega** [comment]
As I said the GeneralizedInverse checks the size before compute, and if the matrix is square performs the standard procedure, only adds one extra check, so it is not super expensive.

https://github.com/KratosMultiphysics/Kratos/blob/68cd91f4180fa872e10d932e046a22fe64c73584/kratos/utilities/math_utils.h#L377

**Review by loumalouomega — APPROVED** [review]
Ok

**Comment by roigcarlo** [comment]
So, can we merge it or not?

**Comment by RiccardoRossi** [comment]
I am not blocking this for the release, but we should think if this is the
long term solution or not.

Vicente, it is not only about cost...you are asking for the inverse or
determinant of a non square matrix...you d better know what is happening.
The rationale until now was to throw an error so that one would get the
Jacobian and call the generalized set or inverse as needed.
With this commit this behaviour is silently changed. Whether for good or
not should be discussed

**Comment by loumalouomega** [comment]
Mathematically the inverse of a non square matrix is defined,
https://ocw.mit.edu/courses/mathematics/18-06sc-linear-algebra-fall-2011/positive-definite-matrices-and-applications/left-and-right-inverses-pseudoinverse/MIT18_06SCF11_Ses3.8sum.pdf

**Pull request merged**
