### PR TITLE
[Core] SpansLocalSpace to geometry

### PR DESCRIPTION
**Pull request by tteschemacher**
**Description**
This adds the interface SpansLocalSpace to geometry and adapts all dependencies

It has been discussed if SpansGlobalSpace would be required, however, at the current stage this would only be advantageous for curves and can be avoided easily. Accordingly, I kept it with SpansLocalSpace.

**Changelog**
- SpansLocalSpace in geometry.h
- Adapting access in all Nurbs and Brep classes

### CODE REVIEW

**Comment by tteschemacher** [comment]
A small description of the newly introduced interfaces as I have the feeling that some people might have lost a bit the track what is for what.

image
	
- *ProjectPoint* - it maps globally defined points into the local space of the respective geometry. It is meant to purely apply mathematical projection functionalities, as for typical cases this is a Newton-Raphson search. Those methods are usually highly dependent on the initial guess (see figure~\ref{fig:CADProjectionScenario}) and additionally some convergence parameters. Accordingly, it is chosen that this interface does not make any complex advanced estimations to ensure a solution quality, instead it follows mathematical rules for provided input parameters, whereby, using different initial guesses might be of advantage if multiple contact points are required.
- *ClosestPointLocalSpace* - considering a projection was successful, however, the mapped point does not lay within a physical domain, this function provides methodologies to obtain the closest boundary of the respective geometry.	In a 1D cases this would be the delimiter of the curve which is closest to the local coordinate, in 2D cases this mapping would be more sophisticated, considering a projection to the boundary curves. 
- *CosestPoint* - probably the most sophisticated interface and accordingly computationally most costliest is basically relying on the previous methods. In contrast, there the local coordinates are already provided, whereby here the closest point computation will require to obtain those first. Accordingly, it does a search of appropriate initial guesses for the projection, ensuring that the global minimum instead of a local optimum is found, which in some cases might lead to multiple calls of the projection function. After getting the projected point, it is checked whether the resulting point lays within the physical domain, which would lead to the call of the ClosestPointLocalSpace function.

**Review by rubenzorrilla — DISMISSED** [review]
After discussing this with @roigcarlo we both think that this can go in. Concerning the base geometry, it only adds a new method, which is defaulted to throw an error in case a non CAD type calls it.

Let us know to reapprove again once the conflicts are solved.

**Review by roigcarlo — APPROVED** [review]
:+1:

**Comment by tteschemacher** [comment]
Thanks a lot for the review!! 👍 

Thanks also @pooyan-dadvand for your help during the developments.

**Pull request merged**
