### PR TITLE
[Structural] remove linear_solver_settings from defaults

### LINKED ISSUE #8208: [StructMech][Eigenvalue] Correct way of getting the number of eigenvalues and shapes wanted
**Description**
I am using the StructuralMechanicsApplication to solve for eigenvalues. As far as I see, the solve is correct, but I am not getting the amount of eigenvalues that I would need. Independent of the settings, I get 5 which I can display and also in the terminal I see only 5 once the solve is done.

Here are 2 small examples:

- [a cantilever modeled with beam elements](https://syncandshare.lrz.de/dl/fiTEqtAe2sgfDhLof4QvoKKP/cantilever_beam_model.gid)
- [a cantilever modeled with solid elements](https://syncandshare.lrz.de/dl/fiA5FomorWmkYSUzaz7gc1tw/cantilever_solid_model.gid)

**Scope**
What is the correct usage for getting the number of eigenvalues intended?

### PR DESCRIPTION
**Pull request by philbucher**
**Description**
To avoid problems as in #8208

@mpentek now you should get a proper error, can you try please?

closes #8208

### CODE REVIEW

**Review by loumalouomega — DISMISSED** [review]
Okay

**Comment by philbucher** [comment]
hm how can this fail in gcc but not in Win and clang ...
I will investigate

**Review by mpentek — DISMISSED** [review]
Functionality is correct. I cannot comment on why it is failing with some compilations.

**Comment by philbucher** [comment]
> Functionality is correct. I cannot comment on why it is failing with some compilations.

basics error in testing, I will take care of it :)
Glad it works now!

**Comment by philbucher** [comment]
> hm how can this fail in gcc but not in Win and clang ...
> I will investigate

https://github.com/KratosMultiphysics/Kratos/blob/fae94525d9d69b2b29a0ba784724819e5c9b1798/applications/StructuralMechanicsApplication/tests/test_StructuralMechanicsApplication.py#L434-L443

thats the issue

I will refactor this soon, then it should also run in Win & Clang

**Review by mpentek — APPROVED** [review]

**Pull request merged**
