### PR TITLE
[Core] SpecificationUtils addition of GetDofsListFromSpecifications

### PR DESCRIPTION
**Pull request by rubenzorrilla**
**📝 Description**
This PR adds a new method to the `SpecificationUtils` namespace (:fearful:). The idea is to get a list with the DOFs that are specified in the `required_dofs`  field of the elements and/or conditions `GetSpecifications` method.

Note that these methods are not MPI-compatible compatible yet as we don't have the capability to synchronize the list/set (yet).

### CODE REVIEW

**Comment by loumalouomega** [comment]
> **memo Description** This PR adds a new method to the `SpecificationUtils` namespace (fearful). The idea is to get a list with the DOFs that are specified in the `required_dofs` field of the elements and/or conditions `GetSpecifications` method.
> 
> Note that these methods are not MPI-compatible compatible yet as we don't have the capability to synchronize the list/set (yet).

We can change to a static class (in my time we did namespaces)

**Review by loumalouomega — DISMISSED** [review]

**Comment by rubenzorrilla** [comment]
> > **memo Description** This PR adds a new method to the `SpecificationUtils` namespace (fearful). The idea is to get a list with the DOFs that are specified in the `required_dofs` field of the elements and/or conditions `GetSpecifications` method.
> > Note that these methods are not MPI-compatible compatible yet as we don't have the capability to synchronize the list/set (yet).
> 
> We can change to a static class (in my time we did namespaces)

Up to you.

**Review by loumalouomega — DISMISSED** [review]

**Comment by loumalouomega** [comment]
I will also refactor #9121 into a static class instead of namespace

**Comment by rubenzorrilla** [comment]
> I will also refactor #9121 into a static class instead of namespace

As I said, as you wish :wink:

**Review by loumalouomega — APPROVED** [review]
Thanks

**Pull request merged**
