### PR TITLE
[Core] Use parameters in distance processes 

### PR DESCRIPTION
**Pull request by marcnunezc**
**📝 Description**
This is a first step to enable #3070 ( solved in  #9568). 

The use of flags as options is replaced and deprectaed (upon agreement) by the parameters.

Then the addition of user-defined variables is much easier. 

If you agree, the flag constructor would be deprecated. 

**🆕 Changelog**
Please summarize the changes in one list to generate the changelog:
E.g.
- Added new constructor with parameters for both discontinuous and continuous distance processes.
- Deprecated flag constructor. 
- Tests updated using the new constructor.

### CODE REVIEW

**Review by rubenzorrilla — COMMENTED** [review]
I'm very very positive about this (the local flags export has been always a pain in the neck...). However, I don't see why we need to save the entire `mParameters` since we're saving the input values in the `mOptions` flag container. Alternatively, we could get rid of this `mOptions` by saving three `bool` type member variables.

**Comment by marcnunezc** [comment]
> I'm very very positive about this (the local flags export has been always a pain in the neck...). However, I don't see why we need to save the entire `mParameters` since we're saving the input values in the `mOptions` flag container. Alternatively, we could get rid of this `mOptions` by saving three `bool` type member variables.

Actually, I started implementing your suggestion but I switched to the current one as I thought it was cleaner. 

Thinking about it again, I agree it's better to use bool member variables.

**Comment by marcnunezc** [comment]
I defined bool member variables and updated the tests with the new constructor.

**Review by rubenzorrilla — COMMENTED** [review]
Very good.  However I think that there are some more usages (at least in the `FSIApplication`) that will start throwing a warning. These should be amended (we can do it in a follow-up PR). Besides, I think that once this is merged, we can open another PR removing the deprecated constructors (this could be more tedious to be merged, @KratosMultiphysics/altair not sure if this will affect you).

**Comment by marcnunezc** [comment]
> Very good. However I think that there are some more usages (at least in the `FSIApplication`) that will start throwing a warning. These should be amended (we can do it in a follow-up PR). Besides, I think that once this is merged, we can open another PR removing the deprecated constructors (this could be more tedious to be merged, @KratosMultiphysics/altair not sure if this will affect you).

Seems resonable.

I just checked the usage on the FSIApplication, and it appears to be here:
https://github.com/KratosMultiphysics/Kratos/blob/6c863e447d39b09c4ea9b0fc2bd2227009bc4ac2/applications/FSIApplication/python_scripts/partitioned_embedded_fsi_base_solver.py#L216-L229

However it does not seem to be covered by the tests (I put an Exception there and tests run fine), but we can take a look in a separate PR as you comment.

**Comment by rubenzorrilla** [comment]
> > Very good. However I think that there are some more usages (at least in the `FSIApplication`) that will start throwing a warning. These should be amended (we can do it in a follow-up PR). Besides, I think that once this is merged, we can open another PR removing the deprecated constructors (this could be more tedious to be merged, @KratosMultiphysics/altair not sure if this will affect you).
> 
> Seems resonable.
> 
> I just checked the usage on the FSIApplication, and it appears to be here:
> 
> https://github.com/KratosMultiphysics/Kratos/blob/6c863e447d39b09c4ea9b0fc2bd2227009bc4ac2/applications/FSIApplication/python_scripts/partitioned_embedded_fsi_base_solver.py#L216-L229
> 
> However it does not seem to be covered by the tests (I put an Exception there and tests run fine), but we can take a look in a separate PR as you comment.

Might be not covered as the cases involving this solver are potentially big... In any case, lets do it in another one.

**Review by rubenzorrilla — APPROVED** [review]
:rocket:

**Pull request merged**
