### PR TITLE
[StructuralMechanics] some AMatrix changes

### PR DESCRIPTION
**Pull request by philbucher**

### CODE REVIEW

**Comment by philbucher** [comment]
@pooyan-dadvand if I change [this](https://github.com/KratosMultiphysics/Kratos/blob/master/applications/StructuralMechanicsApplication/custom_utilities/EICR.hpp#L226) also then I get the following compiler error:
~~~
/home/philippb/software/Kratos_prod/applications/StructuralMechanicsApplication/custom_utilities/EICR.hpp:252:16: error: could not convert ‘Kratos::P’ from ‘Kratos::EICR::MatrixType (*)(Kratos::IdentityMatrix) {aka boost::numeric::ublas::matrix<double> (*)(boost::numeric::ublas::identity_matrix<double>)}’ to ‘Kratos::EICR::MatrixType {aka boost::numeric::ublas::matrix<double>}’
         return P;
~~~

**Review by loumalouomega — DISMISSED** [review]
OK

**Review by pooyan-dadvand — DISMISSED** [review]
:+1:

**Comment by philbucher** [comment]
had to solve conflicts, can someone reapprove pls?

**Comment by philbucher** [comment]
Someone?

**Review by loumalouomega — APPROVED** [review]

**Comment by philbucher** [comment]
Thanks

**Comment by RiccardoRossi** [comment]
does

P =IdentityMatrix

work?

**Comment by philbucher** [comment]
> does P =IdentityMatrix work?

@RiccardoRossi I don't know, haven't tried

**Pull request merged**
