### PR TITLE
[Hotfix] SetVariablesList on the new nodes created

### PR DESCRIPTION
**Pull request by loumalouomega**
This sets the variable list (necessary for real computing, until now the tests used just played with the mesh and this wasn't necessary)

### CODE REVIEW

**Comment by philbucher** [comment]
do you only want to set it or copy it?

**Comment by loumalouomega** [comment]
I only want the list of  variables

**Comment by philbucher** [comment]
what i mean is the function is called **CopyVariablesList** but internally (besides copying the VariablesList) you also set the SolutionStepData from the old to the new node. => Is this desired?
If so, then what abt the non-historical data?

**Comment by loumalouomega** [comment]
Maybe the name is not well chosen

**Comment by loumalouomega** [comment]
This process is supposed to be run at the beginning before doing anything, so this is the easiest way to make it work.

**Review by philbucher — APPROVED** [review]
ok

**Comment by loumalouomega** [comment]
Thanks

**Pull request merged**
