### PR TITLE
[Core] Avoiding error when loading Kratos modules

### PR DESCRIPTION
**Pull request by loumalouomega**

### CODE REVIEW

**Review by philbucher — CHANGES_REQUESTED** [review]
That won't work with the new format, let me fix it

**Comment by loumalouomega** [comment]
@philbucher many tests stop working, if your fix will take long to come, better to merge this and fix it properly later

**Comment by philbucher** [comment]
give me at least a couple of minutes ...

**Review by philbucher — DISMISSED** [review]
Fixed it, can you try please?

BTW I think your tests are wrong, I though we always have to specify the full name, i.e. `KratosMultiphysics.ContactStrucutalMechanicsApplication`

Now it works both with and without the preceding `KratosMultiphysics`

**Comment by loumalouomega** [comment]
> Fixed it, can you try please?
> 
> BTW I think your tests are wrong, I though we always have to specify the full name, i.e. `KratosMultiphysics.ContactStrucutalMechanicsApplication`
> 
> Now it works both with and without the preceding `KratosMultiphysics`

I am on it

**Comment by philbucher** [comment]
Should we still merge this? Increases the user-friendlyness and apparently was working before #3608 

maybe an opinion from @jcotela ?

**Review by jcotela — DISMISSED** [review]
I approve. I do not know if you want someone else to take a look, however, I rarely use this directly.

**Review by philbucher — APPROVED** [review]

**Pull request merged**
