### PR TITLE
[Core] Create with properties in constitutive law

### LINKED ISSUE #6019: A proposal for a more flexible handling of material properties in constitutive laws
The `MGISApplication` aims at allowing `MFront` constitutive laws to be used in `Kratos`.  Constitutive laws are loaded dynamically in shared libraries generated by `MFront`. As such, the number of material properties and their names required by a constitutive law is no more known at compile time. Thus, relying on `Kratos`' `Variable`s is not an option.

Note that this issue may also be relevant to any applications interfacing external CLs (the `UmatApplication` maybe (?)).

Issue #5950 is an in-depth discussion about why a more flexible handling of material properties and discusses various solutions, none of which were considered satisfactory so far.

The object of this issue is to discuss one new proposal which:

- is backward compatible (i.e. does not lead to any modification of existing CLs)
- allows a complete flexibility,
- allows only a slight and controlable deviation from the standard `Kratos` variaable mechanisms.
- may improve the performances of `MFront` behaviours
- seems quite straightforward to implement.

Again the arguments that back this proposal can be found in Issue #5950.

The proposal can be expressed as follows:

- modify the parsing of the `Variables` section of the input file, so the variables' names are not check.
- create an overloaded version of the `Create` method for CLs which takes the material properties read in the `Variables` section as an argument. The default version of this method would check the variables' names and call the current `Create` methods. This way, backward compatibility in ensured and no change to existing CLs is required.

In the `MGISApplication`, the `MGISConstitutiveLawFactory` will overload this new `Create` function and checks that only the material properties expected by the constitutive law are declared. This allows full flexibility. A mechanism, too long to be described here, is meant to ensure a maximal compatibility with `Kratos`: a variable named `YOUNG_MODULUS`, which is the standard Kratos' naming can be used whenever the behaviour requires the young modulus to be defined.

Concerning performances (efficiency and memory footprint), the `MGIS` library requires the material properties to be stored in a continous array. This proposal allows this array to be build in the `Create` method and be shared among all the clones of the generated CL.

### PR DESCRIPTION
**Pull request by loumalouomega**
Fixes #6019

Adds a Create method which also considers a Properties as input

### CODE REVIEW

**Review by RiccardoRossi — APPROVED** [review]
this looks ok to me (it is what we agreed)

i am approving but please wait 24 more h before merging to see if there is any other comment

**Comment by loumalouomega** [comment]
According to github 2 days have passed since approval

**Comment by thelfer** [comment]
@loumalouomega Great. Thank you very much.

**Comment by loumalouomega** [comment]
> 
> 
> @loumalouomega Great. Thank you very much.

imagen

**Pull request merged**
