### PR TITLE
[Pfem] Arrangement to use properties tables 

### PR DESCRIPTION
**Pull request by josep-m-carbonell**
New properties_layout for table configuration.
There is a name change that shows a lot of changed files. But the main change is the properties layout class.

### CODE REVIEW

**Comment by maceligueta** [comment]
Is the idea of properties layout similar to the 'accessor`?

**Comment by josep-m-carbonell** [comment]
Yes, this was a proposal that I commented to Pooyan. I have seen that the design of the properties accessor is not clear, and a little bit blocked. The purpose of the accesor is having functions for variables. This properties_layout object is focussed in improving the access to tables in an automatic way. I guess that something similar can be made for functions. It is a first version, is working and I hope it can be improved and extended.

**Review by maceligueta — APPROVED** [review]

**Comment by maceligueta** [comment]
I can't block this pull request, as you are the Maintainer of the applications being modified. However, I think  that merging now might mean be double work when the discussion about the accessor is unblocked (double work or divergence between both implementations).

**Comment by josep-m-carbonell** [comment]
I have already done the work. It is only considering two column tables of scalar variables. If there is something better I will use the best option.Take into account that is only an extra variable that is passed to properties with three main methods RegisterTable, Configure and GetValue. If it doesn't exist is not used.
I will wait for something better and more general, however maybe it will take a year to arrive. Well, maybe if now there is a similar class to follow, it will be faster.

**Pull request merged**
