### PR TITLE
[Core] Missing distance check in Line3D2 `IsInside`

### PR DESCRIPTION
**Pull request by loumalouomega**
**📝 Description**

Missing distance check in Line3D2 `IsInside`. With this the `IsInside` could give false positive. Consistent with 2D line https://github.com/KratosMultiphysics/Kratos/blob/5c587c1a8f9c6f4adf7502b960709572f0345156/kratos/geometries/line_2d_2.h#L950

Tests are passing

**🆕 Changelog**

- [Missing check in Line3D2 LocalCoordinates](https://github.com/KratosMultiphysics/Kratos/commit/6e3eb8be4b5265be07f32cddee93e75e633ebf34)
- [Moving to IsInside (consistent with 2D line)](https://github.com/KratosMultiphysics/Kratos/commit/faa711a3d5d0defc0c49bc7001bac5c6336badf8)
- [Minor clean upo line 2D (fix typo + pragma once)](https://github.com/KratosMultiphysics/Kratos/commit/aac99a30cc58a5090a43c91988c661b5438e26de)

### CODE REVIEW

**Review by philbucher — CHANGES_REQUESTED** [review]
this is conflicting with #7401, lets discuss first what should be the desired behavior

**Comment by loumalouomega** [comment]
> this is conflicting with #7401, lets discuss first what should be the desired behavior

Okay, now I remember the PR, thanks. In any case this is inconsistent, if we fix we should fix globally. BTW, conflict in that PR

**Comment by loumalouomega** [comment]
> this is conflicting with #7401, lets discuss first what should be the desired behavior

Maybe the best solution would be to create a method IsInsideWithChecks, @pooyan-dadvand suggested something like that

**Comment by loumalouomega** [comment]
> > this is conflicting with #7401, lets discuss first what should be the desired behavior
> 
> Maybe the best solution would be to create a method IsInsideWithChecks, @pooyan-dadvand suggested something like that

Better thinking about FastInside in fact

**Comment by loumalouomega** [comment]
For the moment I will solve my issue with a lambda, so this doesn't block my work

**Comment by pooyan-dadvand** [comment]
I was saying something like `ProjectionIsInside` because is not the question if you do checks or if you do it faster. The question is if you consider out of plan or our of line as out or you want to check if projected point is inside.

Another option is to distinguish it with the tolerance. (In this case the tolerance should be the same in plana and out plane as we have only one argument)

**Comment by loumalouomega** [comment]
Closing this as @KratosMultiphysics/implementation-committee reached a consensus and this will be replaced by a new method

**Pull request closed without merging**
