### PR TITLE
[CI] re-enable PotentialFlow

### PR DESCRIPTION
**Pull request by philbucher**

### CODE REVIEW

**Comment by philbucher** [comment]
now seems to work again 
FYI @KratosMultiphysics/technical-committee

**Comment by roigcarlo** [comment]
So it was something related with the variables after all?

**Review by marcnunezc — APPROVED** [review]
Nice, thank you! What was the main cause of the problem?

**Comment by philbucher** [comment]
I cannot tell for sure, but there was a minor memory problem in the MappingTests: #6354
However when I first started debugging this problem I think I also disabled all C-tests and it didn't solve the problem then
So also the corrections with the variables #6352 might have an impact

I will merge it now and then I suggest to make it required asap such that it does not break again :)
also thanks for the help of others

**Pull request merged**
