### PR TITLE
Removing std::pow just in case is the root of evil

### PR DESCRIPTION
**Pull request by loumalouomega**
Concerning #566

### CODE REVIEW

**Comment by rubenzorrilla** [comment]
Indeed, AFAIK, naive multiplication is faster for power of 2.

**Comment by loumalouomega** [comment]
@rubenzorrilla When the exponent is an integer the compilers have internal optimizations

**Comment by loumalouomega** [comment]
On modern compilers, like e.g. g++ 4.x, std::pow(x,2) will be inlined, if it is not even a compiler-builtin, and strength-reduced to x*x. If not by default and you don't care about IEEE floating type conformance, check your compiler's manual for a fast math switch (g++ == -ffast-math).

**Comment by pooyan-dadvand** [comment]
I don't think that the problem is for power of two..... 

let me check it.

**Comment by pooyan-dadvand** [comment]
Still random crashes....

**Comment by loumalouomega** [comment]
Ok, I close this

**Pull request closed without merging**
