### PR TITLE
Fixed wrong error messages

### PR DESCRIPTION
**Pull request by qaumann**
In the residual based bossak displacement scheme

### CODE REVIEW

**Review by loumalouomega — CHANGES_REQUESTED** [review]
Can you use KRTOS_ERROR instead of KRATOS_THROW_ERROR, it works similarly to std::cout

**Comment by qaumann** [comment]
Sure, I can change this. Should I do it for all error messages in the scheme?

**Comment by rubenzorrilla** [comment]
@qaumann yes, indeed, for all the KRATOS_THROW_ERROR you found.

**Comment by qaumann** [comment]
@loumalouomega, @rubenzorrilla 
Thanks for pointing that out, I changed all KRATOS_THROW_ERROR

**Review by loumalouomega — APPROVED** [review]

**Pull request merged**
