### PR TITLE
[Trilinos] cleanup

### PR DESCRIPTION
**Pull request by philbucher**
I made a draft for deleting old things

I am not sure if I deleted to much, but to me those things seem old

Please let me know if sth has to remain

Related to cleaning the Apps such that they can become core apps

### CODE REVIEW

**Comment by jcotela** [comment]
The only one of these I remember using is  applications/TrilinosApplication/custom_utilities/trilinos_refine_mesh.h, which is the MPI version of a MeshingApplication utility and was working the last time I needed it (maybe 2-3 years ago?)

**Comment by pooyan-dadvand** [comment]
@roigcarlo was working on zoltan application

**Comment by RiccardoRossi** [comment]
trilinis refine mesh was working

the zoltan stuff wad not, but i would like to take a look at it "soon".

i will not be able to take a look at this now. if you could keep this on
hold untik sept...or otherwose lease be very conservative

**Comment by philbucher** [comment]
No rush here, just wanted to initiate the discussion 
Seems like I will bring back the refine-mesh

**Comment by philbucher** [comment]
I brought back the trilinos refine mesh

The zoltan is quite messy, I would prefer to remove it for now, esp if it is not working.
You can bring it back once it is working again

**Comment by philbucher** [comment]
ping

**Comment by philbucher** [comment]
ping if none has more objections then can we please go ahead?
This is blocking further improvements/cleanup

**Review by RiccardoRossi — APPROVED** [review]
we should remind to add the Assemble command to the base convection diffusion strategy, but it is definitely a part of a different PR

**Pull request merged**
