### PR TITLE
[MeshingApplication] Allocation memory error

### PR DESCRIPTION
**Pull request by loumalouomega**

### CODE REVIEW

**Comment by AlejandroCornejo** [comment]
another error removed nice!

**Review by AlejandroCornejo — DISMISSED** [review]

**Comment by loumalouomega** [comment]
I think I found another one, I will reuse this very same PR :D

**Comment by loumalouomega** [comment]
imagen

**Comment by AlejandroCornejo** [comment]
ooh perfect!

**Comment by loumalouomega** [comment]
Done

**Review by AlejandroCornejo — APPROVED** [review]

**Pull request merged**
