### PR TITLE
[Core] Bugfix - Initialize DOF set flag in residual-based block builder and solver

### PR DESCRIPTION
**Pull request by ddiezrod**
It seems this was removed by mistake on the latest PR (https://github.com/KratosMultiphysics/Kratos/pull/12700) , so now the dof set is being rebuilt at every time step! 

ping @jrubiogonzalez as he was the one that found the error.

### CODE REVIEW

**Comment by rubenzorrilla** [comment]
But isn't this what @loumalouomega fixed yesterday?

**Comment by ddiezrod** [comment]
@rubenzorrilla upss yeah, I did not see it, well I'd merge this instead as it also adds a test that covers the bug...

**Comment by rubenzorrilla** [comment]
I'd leave the other one, which is about to be automerged, to then update the corresponding tests in this one (after merging the master OFC).

**Comment by ddiezrod** [comment]
@rubenzorrilla Done. I have to say, I'm not a fan of adding so many obvious comments to the code, but I'll let it slide this time. 😄

**Comment by loumalouomega** [comment]
> @rubenzorrilla Done. I have to say, I'm not a fan of adding so many obvious comments to the code, but I'll let it slide this time. 😄

image

**Review by rubenzorrilla — APPROVED** [review]

**Pull request merged**
