### PR TITLE
[Core] LineSearch - bugfix - using user provided settings

### PR DESCRIPTION
**Pull request by ddiezrod**
default settings were overriding user provided values. Not sure if its the cleanest way to do it, what do you think @philbucher ?

### CODE REVIEW

**Comment by philbucher** [comment]
thanks for the fast response!
I agree, as you say its not the cleanest solution :)

I just spoke to @jcotela, he is trying to do the same, do you mind waiting for his findings? Then we could hopefully find a better solution
For me this is not urgent...

**Comment by jcotela** [comment]
@philbucher as far as I can tell, my findings coincide with yours, there is no magic solution. I think that the solution in this PR is good enough given the limitations. @ddiezrod the only way I see to make this a bit cleaner is to implement a `GetDefaultSettings` type function to be called on both constructors.

**Comment by ddiezrod** [comment]
@jcotela mm I do not get what you mean. There is already a GetDefaultSettings function that is called in all the constructors, what do you mean more specifically?

**Comment by jcotela** [comment]
@ddiezrod essentially, you are adding the same three parameters in both constructors, you could simplify future maintenance by implementing that operation on a separate function.

Just for context, @philbucher and I had been discussing a structure of the style
```C++
class Base {
public:
  Base(ModelPart& rModelPart, Parameters Settings)
  : mrModelPart(rModelPart)
  {
    mSettings = Settings.ValidateAndAssignDefaults(this->GetDefaults());
  }
protected:
  Base(ModelPart& rModelPart, Parameters Settings, Parameters Defaults)
  : mrModelPart(rModelPart)
  {
    mSettings = Settings.ValidateAndAssignDefaults(Defaults);
  }

 virtual Parameters GetDefaults();
};

class Derived: public Base {
public:
  Derived(ModelPart& rModelPart, Parameters Settings)
  : Base(rModelPart, Settings, this->GetDefaults())
  {}
protected:
  Derived(ModelPart& rModelPart, Parameters Settings, Parameters Defaults)
  : Base(rModelPart, Settings, Defaults)
  {}

 Parameters GetDefaults() override;
};
```

This approach allows you to transfer the correct defaults to the base class through the protected constructor and is scalable, in the sense that an eventual class
```C++
class Derived2 : public Derived {};
```
can call the protected constructor of `Derived` and pass the correct defaults (from Derived2) along.

The main drawback of this approach is that you need to define an extra constructor (the protected one) on each class you want to derive from. In your case, you have **two** different constructors (with/without builder and solver), so you would also need two protected constructors with each set of arguments plus the inherited defaults. I do not think it is worth the effort here, but it is our current "least bad idea" for a standard/cleaner solution for this kind of problems in the future.

**Comment by ddiezrod** [comment]
Is this ok @jcotela ?

**Review by jcotela — APPROVED** [review]

**Pull request merged**
