### PR TITLE
Core/corrections elimination builder reactions whole domain

### PR DESCRIPTION
**Pull request by adityaghantasala**
This pr includes changes to resize the reaction vector constructed in elimination builder and solvers to calculate the reactions over the whole domain. 
This solves errors in  #1660 
and the fail is solved in #1664

### CODE REVIEW

**Review by jcotela — APPROVED** [review]
Tests pass now :+1:

**Review by philbucher — APPROVED** [review]
tests are working

**Comment by loumalouomega** [comment]
I am cherrypicking, my tests are failing too

**Comment by loumalouomega** [comment]
Still failing...huuuum

**Comment by philbucher** [comment]
which tests are failing?

**Comment by loumalouomega** [comment]
The tests based on components in the ContactStructuralMechanicsApplication

**Comment by loumalouomega** [comment]
I found the error, I need to define necessary a reaction for the LM

**Comment by loumalouomega** [comment]
I would prefer to avoid this, can we check if there is a reaction defined before assign?

**Comment by loumalouomega** [comment]
can we define HasReaction method or equivalent?

**Comment by jcotela** [comment]
@loumalouomega I'd expect that, if you don't want/need reactions, you'll set the compute_reactions (or whatever the actual name is) to false for the builder and solver.

If you are doing that and still getting errors due to this, then we have a bug somewhere (but I'd say not in this PR).

**Comment by loumalouomega** [comment]
Don't worry, I solved the problem with a dummy reaction until a better solution is available. Not compute the reaction is a easy choose, but I prefer to do it correctly

**Comment by jcotela** [comment]
Well, for me the correct solution is not to set the flag to calculate reactions in the builder and solver if I don't want to calculate reactions...

Another thing we can discuss is to make the builder and solver to check if the DOFS have a reaction variable defined at some point if the problem is set to compute reactions, but I think the current design is generally OK.

**Comment by loumalouomega** [comment]
The problem is with the dof of the LM, could be understood just as a dummy residual more than like a pure reaction (in fact the LM is already like a reaction). So I could be interested in compute the reactions of the displacements, but not have any interest in compute the LM reactions (because are meaningless).

In #1670 I suggested precisely to check before assign

**Comment by philbucher** [comment]
guys can we merge this?

**Comment by jcotela** [comment]
I'd say yes, but let's wait to hear from @loumalouomega

**Comment by loumalouomega** [comment]
Ok for me

**Comment by RiccardoRossi** [comment]
+1 for merging if this fixes the tests. Hover @adityaghantasala please take a look at my coment, since i think it is actually relevant

**Comment by adityaghantasala** [comment]
@RiccardoRossi  are you pointing to the comment you made in #1513 ??

**Comment by adityaghantasala** [comment]
@RiccardoRossi  I got it in #1670  sure .. I think it makes it more robust. I will make this change and make a new PR.

**Pull request merged**
