### PR TITLE
DEM fix GUI's bug after unification and publication

### PR DESCRIPTION
**Pull request by maceligueta**

### CODE REVIEW

**Comment by maceligueta** [comment]
@KlausBSautter , this should fix a couple of problems detected, apart from one you said by email. 
Are you using a relatively new version of GID? We recommend using the latest possible.

**Comment by KlausBSautter** [comment]
@maceligueta  I just updated to the newest version I still get following error with this branch

> python: can't open file 'KratosDEM.py': [Errno 2] No such file or directory

when I run a problem

**Comment by maceligueta** [comment]
Ok, this is because inside the folder ‘G-DEMpack/kratos.gid/python/’ there should be a symbolic link to KratosDEM.py. For more robustness, I will put the real file there and push.

Also, be careful with the file ‘G-DEMpack/kratos.gid/python/kratos.unix.bat’. Look at the last line: it is using ‘python’ not ‘python3’. So you should edit this file if you are using python3, or make an alias in your pc so that whenever you type ‘python’ it is actually calling ‘python3’.

**Comment by KlausBSautter** [comment]
works now for me. thanks for your help !

**Review by KlausBSautter — DISMISSED** [review]

**Comment by maceligueta** [comment]
Finally! Appveyor test passed. Can you approve again? @KlausBSautter

**Review by salvalatorre — APPROVED** [review]
Fine!

**Comment by KlausBSautter** [comment]
sry @maceligueta  I was too late :)

**Comment by maceligueta** [comment]
No worries! you approved it before.

**Pull request merged**
