### PR TITLE
[ContactStructuralMechanicsApplication] Update README.md

### PR DESCRIPTION
**Pull request by loumalouomega**
New gifs and link to examples

### CODE REVIEW

**Comment by tteschemacher** [comment]
Nice gif!

**Comment by loumalouomega** [comment]
> Nice gif!

https://www.youtube.com/watch?v=ZqhAFOtqn0Y&feature=youtu.be

Ice cream for your eyes

**Review by AlejandroCornejo — APPROVED** [review]

**Comment by tteschemacher** [comment]
> 
> 
> > Nice gif!
> 
> https://www.youtube.com/watch?v=ZqhAFOtqn0Y&feature=youtu.be
> 
> Ice cream for your eyes

Haha but not for the ears :P

**Comment by loumalouomega** [comment]
> > > Nice gif!
> > 
> > 
> > [youtube.com/watch?v=ZqhAFOtqn0Y&feature=youtu.be](https://www.youtube.com/watch?v=ZqhAFOtqn0Y&feature=youtu.be)
> > Ice cream for your eyes
> 
> Haha but not for the ears :P

That's because you haven't grown up in the Spanish Levante: https://www.youtube.com/watch?v=d_lLPZKfkc8

**Pull request merged**
