### PR TITLE
[Core] SpansLocalSpace of CouplingGeometry

### PR DESCRIPTION
**Pull request by tteschemacher**
**Description**
This PR separates the CreateIntegrationPoint creating in the coupling geometry with the computation of the interface SpansLocalSpace.

Additionally, it fixes a tolerance error within the curve axis intersection estimation.

### CODE REVIEW

**Comment by tteschemacher** [comment]
@rickyaristio I quite remember that you had a similar error once with some examples. Do you think this is resolved as well? Or do you specifically have any test case which we could add, here?

**Comment by rickyaristio** [comment]
> @rickyaristio I quite remember that you had a similar error once with some examples. Do you think this is resolved as well? Or do you specifically have any test case which we could add, here?

Yes, this resolves the error in an example where all the knots are negative. I'll provide the test here soon.

**Comment by tteschemacher** [comment]
Thank you very much, @rickyaristio for adding this crucial test!

**Comment by tteschemacher** [comment]
This PR, would be ready for review.

ping @manuelmessmer @dagmawibekel .

**Comment by tteschemacher** [comment]
@rickyaristio I think this PR was ready, right? if so, could you please approve it?

**Comment by rickyaristio** [comment]
> @rickyaristio I think this PR was ready, right? if so, could you please approve it?

Surely!

**Review by rickyaristio — APPROVED** [review]

**Pull request merged**
