### PR TITLE
Feature check orphaned nodes in partitioner

### PR DESCRIPTION
**Pull request by msandre**
added check for invalid mesh. useful for detecting orphaned nodes.

### CODE REVIEW

**Comment by jcotela** [comment]
Can I ask what is the problem with the orphaned nodes? This may be something we want to check for even in non-MPI problems.

**Comment by msandre** [comment]
This problem occurred when we tried importing a mesh from a different meshing program for the olympic roof example. The mesher included the geometric points in the mesh which were not connected to any elements. The partioning algorithm only works on the element connectivity until the last line mrIO.DivideInputToPartitions() is called. The IO then throws in the DivideNodesBlock() with "Invalid node id : ...  [Line ... ]". 

We found out later how to clean these points, but it took some time to figure out the problem because the of the error message coming from the partitioner was not clear and we had to dig several levels down to understand what the code was doing. The modification detects the error as soon as the nodal connectivity is read and should make it easier/faster to detect invalid meshes.

**Comment by jcotela** [comment]
OK so it is a partitioner problem then. This is strange, because I had this same issue in a project I worked on a couple of years ago (an external mesher that automatically deleted elements that had all of its nodes fixed, but left the nodes themselves). I know we did something to account for that, it is unfortunate you had to solve this again.

**Comment by msandre** [comment]
I just checked what happens in serial version if I add an orphaned node to the mdpa. It reads the model without throwing any errors and start calculating. Are there kratos application which ony have nodes and no element connectivities? If valid mesh connectivity is a precondition for kratos, then this should also throw and error.

**Comment by jcotela** [comment]
I don't think orphaned nodes are a problem if the application developer is aware that they may exist. The fluid solver takes care to ignore orphaned nodes, and I know others do the same. In fact, since the assembly loop is element-based, orphaned nodes can go unnoticed in some applications (in the fluid they are only a problem when calculating the projections, because there is an 1/nodal_area there).

I think some applications in kratos do in fact only read nodes from the mdpa (the DEM did at some point, but I'm not up to date). In any case, node-based applications would not use a graph-based partitioner such as this one, so I would be in favor of incorporating this modification.

I have been looking into my old scripts to see how we solved this issue in the past, and it turns out we just used this partitioner. In fact, the issue with the orphaned nodes appeared later in the solution phase, so I suspect that your issue is related to some changes to the model part IO in the meantime. We just need to decide if it is a bug or a feature...

**Comment by RiccardoRossi** [comment]
just to say that some apps do need the orphaned ones,

for example the PFEM
<http://www.cimne.com/>

**Comment by jcotela** [comment]
@RiccardoRossi According to @pooyan-dadvand, orphaned nodes (used to?) crash metis, so I think that having a clear error message is a good idea. We can always improve the algorithm when we need to have this feature.

**Review by jcotela — APPROVED** [review]

**Pull request merged**
