### PR TITLE
[PfemApplication] Erase obsolete and unused PfemApplication 

### PR DESCRIPTION
**Pull request by AFranci**
The PfemApplication is erased.  The app is not used anymore and it needs a constant and time-consuming maintenance.

### CODE REVIEW

**Comment by roigcarlo** [comment]
@AFranci I will make a copy into the legacy repo, its ok?

**Comment by AFranci** [comment]
@roigcarlo ok!

**Review by AlejandroCornejo — APPROVED** [review]
👍

**Comment by josep-m-carbonell** [comment]
Why you erase application from  others ?  @AFranci @AlejandroCornejo @roigcarlo

**Comment by roigcarlo** [comment]
@josep-m-carbonell Application is not erased, as I told @AFranci the policy in this case is to move it to the legacy rep. You can still find the application here: https://github.com/KratosMultiphysics/KratosLegacyApplications/tree/master/PfemApplication

**Comment by AFranci** [comment]
HI @josep-m-carbonell 

I put here some of the things we have just discussed privately to answer the question that you made. 

According to what I could see in the Kratos Github repository, the PfemApp (like the PfemSolidMechanicsApp) was not maintained and could not even compile. The recent (and not so recent) changes in the App were done by people from the kratos technical committee and not by the app developers. Furthermore, it was not invoked by any other application.  

The presence of three PFEM-named applications, among which only one compiles at the actual state, is confusing.

For these reasons, I proposed the elimination of the app (which is entirely stored in the legacy as @roigcarlo just said).

**Comment by josep-m-carbonell** [comment]
Hello @AFranci 

I am the responsible developer for this application. I am still using it. 
I am not synchronized with the Legacy repository, it is not updated.  @roigcarlo 
Nobody said me anything about moving it to another place.

Why you didn't tell me anything about before doing the deletion request? I still wait for a credible answer.
Why you didn't request for an update instead? I find this behaviour is somehow strange.

I don't think this is the correct way to proceed, however I have checked that your opinion is not the same.

**Comment by maceligueta** [comment]
@josep-m-carbonell  can we understand from your message that there is someone who will update the application in case of request?

**Comment by josep-m-carbonell** [comment]
@maceligueta  yes, there is a branch solid/release-8.0 where it was compiling. I have not made a pull request because nobody requested it. Only related changes to component adaptor must be added to compile nowadays. They will be added soon, then we can merge them.

**Comment by josep-m-carbonell** [comment]
Take a look and decide #7675 or #7676.
Thank you

**Comment by RiccardoRossi** [comment]
I think that the question is slightly different: if something is changed in the core which which breaks the Solid, who will fix it?

**Comment by josep-m-carbonell** [comment]
This is exactly what happened. People touching the core broke the applications. They must try to fix what they are breaking.

**Comment by AFranci** [comment]
Hi @josep-m-carbonell 

The point that I cannot get is why to maintain the app in the Kratos repository if it cannot work at the current state and, I suppose, you're overwriting most of it in your fork? Why you cannot use directly the PfemApp of your fork and abandon this? We would avoid doing maintenance of something that is not used, besides deciding who is supposed to do the maintenance.

Apart from this, I am fully available to revert this PR if it is creating trouble for your work, so that we can discuss it more calmly.

**Comment by josep-m-carbonell** [comment]
Hello Alessandro,

   A fork is like a branch of a repository. There are different branches for different purposes and developments.  Not all of them are in the same update status, some of them remain quiet some time. The point is that you decided and applied a deletion without asking or discussing anything with the code developer.  It is strange that the same recipe has not been applied to the DelaunayMeshingApplication, for example. I guess you want to keep it.
    If this criterion is applied extensively, you will delete everything you are not using or interested with.  
The revert is applied in #7675, if you want to review it.

**Comment by AFranci** [comment]
Thank you @josep-m-carbonell for the impeccable reply.
I suggest you approving #7683 so you will restore quickly the situation as before my PR. In #7675 there are many more changes and I prefer to leave to the technical committee the review work.

**Pull request merged**
