### PR TITLE
Feature improve cmake

### PR DESCRIPTION
**Pull request by roigcarlo**
This prevents #794 from happening again by activating the tests by default.
Change is made this way so we don't have to touch one by one all CMakeList.txt from every application

Since the change I had to make will cause a full compilation to trigger for KratosCore/Kratos I included some other details/cleanups that I wanted to push some time ago as well.
* Setting the CMP0054 policy to old. Prevents warnings from 3.9 onwards with the FindOpenMP module
* Cleaned some old unused code
* Clarifying some misleading comments
* Activated `INSTALL_TESTING_FILES` and `INSTALL_PYTHON_FILES` if a install path is set so the user does not have the problem of having the libs installed but the python files not being there.

Probably is a good time to add something else. Any suggestions?

Do not merge this until #795 is merged. Tests will fail until #795 is merged here.

### CODE REVIEW

**Comment by pooyan-dadvand** [comment]
It seems that the test is failing in calculate distance process.... I should take a look at it.

**Comment by pooyan-dadvand** [comment]
Meanwhile, what is the change you made for prefix installation?

**Comment by roigcarlo** [comment]
@pooyan-dadvand I think tests fails because of #794, since this was branch before merging #795. i have to merge master into this one first.

**Comment by roigcarlo** [comment]
I change it so python and testing files are copied by default if someone changes the installation path.

Until now, if you define a different install path you also have to set those variables to ON, otherwise no *.py, *.mpda *.json etc... are copied. It does not happen without modifying the path since there are already in the source.

This was causing a fair amount of people having problems...

**Comment by pooyan-dadvand** [comment]
No I see, would you please do the merge to make it work?

**Comment by roigcarlo** [comment]
Sure, let me reactivate the builds to check it works

**Comment by roigcarlo** [comment]
Ready, someone approve ?

**Review by pooyan-dadvand — APPROVED** [review]
👍

**Pull request merged**
