### PR TITLE
Multipoint constraints

### PR DESCRIPTION
**Pull request by adityaghantasala**
Other than some formatting modifications, this PR 

1. introduces IsWeak flag for multipoint constraints (enforces constraints without adding stiffness from slave to master).

2. Makes slave part of the system an Identity so as to solve conditioning problems with some linear solvers.

Formatting of code with guidelines is not yet done but will be performed in a different (next) pull request.

### CODE REVIEW

**Review by KlausBSautter — APPROVED** [review]
I can just judge about the identity matrix but this looks fine

**Comment by RiccardoRossi** [comment]
question a bit off topic. Are reactions correctly calculated on MPCs?

**Comment by RiccardoRossi** [comment]
@aditya, what is this "isweak"?

**Comment by adityaghantasala** [comment]
@RiccardoRossi  this is deleted .. this is a very old implementation and will not be used  ... this is irrelevant ... !! I also deleted the branch ... !!

**Pull request closed without merging**
