### PR TITLE
[StructuralMechanicsApplication] Update readme

### PR DESCRIPTION
**Pull request by loumalouomega**

### CODE REVIEW

**Review by philbucher — COMMENTED** [review]
some things are outdated, e.g. the MPC-B&S, the processes,...

**Comment by loumalouomega** [comment]
Anything else?

**Comment by philbucher** [comment]
- Only one membrane is there now
- Cable Element
- The utilities listed are replaced by the `PostProcessEigenvalueProcess`
- Maybe list also the other processes? (ShellToSolid, th mass-calc?)
- You could refer to the sensitivity stuff in custom_response_function, there is a separate Readme
- SpringDamper Element
- SolidShellElement?

**Comment by philbucher** [comment]
Different thought, what do you think abt a process for computing the center of gravity / one for computing the moment of inertia about a given axis? Similar to the MassProcess you wrote
I think this would make sense and be useful, what do you think?

**Comment by loumalouomega** [comment]
Done

**Review by philbucher — APPROVED** [review]
thx

**Comment by loumalouomega** [comment]
That was fast

**Comment by philbucher** [comment]
had it open :)

**Comment by loumalouomega** [comment]
imagen

**Pull request merged**
