### PR TITLE
[Structural] update deprecated Scheme interfaces

### PR DESCRIPTION
**Pull request by philbucher**
next step in the updating

tests are working

### CODE REVIEW

**Comment by philbucher** [comment]
final step is then to update the Elements & Conditions

**Review by loumalouomega — APPROVED** [review]
OK, let's see the tests

**Comment by philbucher** [comment]
> OK, let's see the tests

looks good :)

Also worked locally

**Review by KlausBSautter — APPROVED** [review]
my examples still run too, so I guess this is fine ;)

**Comment by philbucher** [comment]
thx, then I merge such that I can update Elements & Conditions

**Pull request merged**
