### PR TITLE
[Core] Variational Distance Calculation Process Variable Lists

### PR DESCRIPTION
**Pull request by sunethwarna**
At the moment, ConnectivityPreserveModeler throws lots of warnings when I use VariationalDistanceCalculationProcess in my case which has an existing model part with lots of other variables. Adding this line makes those warnings dissapear. Is this the correct way to do it?

### CODE REVIEW

**Comment by rubenzorrilla** [comment]
Well, this solves the warning since you are assigning the same database. The point is that the distance calculation doesn't need all of them, so it is a useless memory overhead, which might be significant in 3D cases.

**Comment by rubenzorrilla** [comment]
To make things clear, I'm not against removing the warnings but I think we need to find a better solution to this.

**Comment by rubenzorrilla** [comment]
Actually, I think that we had this discussion in the past and we decided to inform the user but to assume that he controls the variables addition when using the ConnectivityPreserveModeler (because of the reasoning above).

**Comment by RiccardoRossi** [comment]
note that you are not allocating more memory. you are just ensuring tjat
tje variable lost is the same

**Comment by sunethwarna** [comment]
I read #4267 which is about having this same line. If it is up to the user of connectivity_preserve_modeller to handle the variable lists, and if the VariationalDistanceCalculationProcess uses a copy of existing MP with existing nodes, then there is no harm in assigning the same variable list to the  new model part right?, anyways those variables will exist in the new model part even though those aren't accessible without the modification, right?

**Comment by sunethwarna** [comment]
ping @rubenzorrilla

**Comment by sunethwarna** [comment]
Hi @RiccardoRossi @rubenzorrilla @philbucher , Since this doesn't add any overhead on memory consumption and its only small overhead on computational cost, will this change be ok? Otherwise, where ever I use VariationalDistanceCalculationProcess, I end up having lots of warnings which makes my output harder to read.

**Comment by philbucher** [comment]
I agree that the correct use case must not throw warnings because this gives false impressions

and if the mem-overhead is not a problem (according to @RiccardoRossi) then I think this is ok to go in

FYI @KratosMultiphysics/altair

**Review by pooyan-dadvand — APPROVED** [review]
Thanks for spotting the error

**Pull request merged**
