### PR TITLE
Improve readme

### PR DESCRIPTION
**Pull request by roigcarlo**
As discussed, Improved Install.md

If you all agree, we could just redirect the install instructions from of the wiki to here.

### CODE REVIEW

**Review by loumalouomega — APPROVED** [review]

**Comment by maceligueta** [comment]
If someone needs to install Kratos from scratch (no CMake, no Boost, ...) where does he need to go to make sure he is ready to follow these instructions?

**Comment by roigcarlo** [comment]
Mm there is no place right now that explains how to install Cmake and all that stuff.
We can restore that in the wiki under "How to install dependencies". Or maybe add a list of the other software needed?

**Comment by roigcarlo** [comment]
@maceligueta Let's merge this and then I will take care of the dependencies on the wiki. Ok?

**Comment by maceligueta** [comment]
Yes, no problem from my side. I thought you would merge, as it is approved already.

**Review by maceligueta — APPROVED** [review]

**Pull request merged**
