### PR TITLE
[Core][Mortar] clean includes

### PR DESCRIPTION
**Pull request by philbucher**
just a minor cleanup, to hopefully reduce compilation time a bit

### CODE REVIEW

**Review by loumalouomega — APPROVED** [review]
OK, thanks. We should do the same with other classes

**Comment by philbucher** [comment]
> OK, thanks. We should do the same with other classes

yep, I guess over time this can be done if we are aware

**Comment by loumalouomega** [comment]
(I thought @RiccardoRossi was against this)

**Comment by philbucher** [comment]
hm ok then I guess we should discuss it

However I don't see a reason why we should not try to reduce dependencies
I guess with proper dependencies (i.e. not including e.g. `ModelPart` everywhere) we could reduce the compilation time a lot, esp when changing sth in the core

**Comment by loumalouomega** [comment]
I am completely in favor, @roigcarlo just told me that

**Comment by roigcarlo** [comment]
Just for the record I am also in favor of using forward declarations. (Not everywhere but when we can)

**Comment by loumalouomega** [comment]
Let's proceed with the merge ⛜ :)

**Pull request merged**
