### PR TITLE
[Core]Removing copy constructor of ModelPart

### PR DESCRIPTION
**Pull request by loumalouomega**
I remove this KRATOS_WATCH that I assume was left during debugging process

### CODE REVIEW

**Review by RiccardoRossi — COMMENTED** [review]
I agree with this change, however i don't think it is a good idea that this copy constructor exists at all...

@pooyan-dadvand why shall we allow this? we **DO NOT** want to have two modelparts with the same name, father etc. That is, i would remove this method at all

**Comment by pooyan-dadvand** [comment]
The idea was to copy and modify afterward but I’m not strongly support it

**Comment by RiccardoRossi** [comment]
I really think we should disallow it... particularly in view of automatically registering in the Model.

@loumalouomega does Kratos compile if you comment it out?

**Comment by loumalouomega** [comment]
I just remove it a KRATOS_WATCH, of course it compiles

**Comment by RiccardoRossi** [comment]
i am asking what happens if you comment out the entire copy constructor. (you will need to say that it is non-copyable in the python interface as a minimum)

**Comment by RiccardoRossi** [comment]
better even, try to define the copy constructor = deleted

**Comment by maceligueta** [comment]
What if somebody wants to actually deepcopy a whole modelpart? Will the assignment operator be accessible? @RiccardoRossi

**Comment by loumalouomega** [comment]
I can do it, but my intention was to to clean that

**Comment by RiccardoRossi** [comment]
@maceligueta i think that the operation you describe is not well defined. (i mean, we should tell explicitly what is expected to happen)

Do you mean cloning everything? should the pointers be preserved? are the submodelparts the same? (if so...what happens with their parent??)

**Comment by loumalouomega** [comment]
@RiccardoRossi bounding_box_utilities.h uses the copy method, do I replace it?. In line 883 it declares mr_model_part as ModelPart I switched to ModelPart&

**Comment by RiccardoRossi** [comment]
@loumalouomega i believe what you just spotted in the bounding_box_utility it is a rather big performance error...
@pooyan-dadvand i think you did that utility. Do you accept replacing 

      ModelPart mr_model_part

to

      ModelPart& mr_model_part

**Comment by loumalouomega** [comment]
Do we proceed?

**Comment by pooyan-dadvand** [comment]
This utility is not developed by me but I agree with adding the & to store member. I would add this to the list of discussions in the next @KratosMultiphysics/technical-committee meeting.

**Comment by maceligueta** [comment]
@loumalouomega , at the @KratosMultiphysics/technical-committee  we agreed to approve these changes. However, the _Operator =_ should bet marked as _delete_ as well, and check that nothing is broken with that.

**Comment by loumalouomega** [comment]
Ok, on it

**Comment by loumalouomega** [comment]
geometry_tester is using the assigment operator, solving...

**Comment by loumalouomega** [comment]
Done @KratosMultiphysics/technical-committee

**Comment by loumalouomega** [comment]
Ping @KratosMultiphysics/technical-committee

**Comment by marandra** [comment]
Hi @loumalouomega 
In PR #1866, waiting approval by @RiccardoRossi , I modified bounding_box_utilities.h to avoid a compilation warning and to cleanup the code. The branch was made from master and it does NOT include your modification `ModelPart& mr_model_part`. Maybe you want to merge that branch before merging this PR?

**Comment by loumalouomega** [comment]
PING @KratosMultiphysics/technical-committee

**Review by RiccardoRossi — DISMISSED** [review]
this was what agreed with the @KratosMultiphysics/technical-committee

**Comment by maceligueta** [comment]
Travis did not pass. Does this require a merge from master first?

**Comment by loumalouomega** [comment]
Done, sorry, I run the tests at the moment without problem, maybe I has some old library pending to clear

**Comment by loumalouomega** [comment]
Can anyone approve?

**Review by RiccardoRossi — DISMISSED** [review]

**Comment by loumalouomega** [comment]
I solved a conflict with the master, can you re-approve?

**Review by philbucher — APPROVED** [review]
I hope I am acceptable as reapprover :)

**Comment by loumalouomega** [comment]
Thanks

**Pull request merged**
