### PR TITLE
[Core] VTK folder output - Makedirs more robust

### PR DESCRIPTION
**Pull request by mpentek**
As in title

### CODE REVIEW

**Comment by philbucher** [comment]
Thanks, didn’t know this didn’t work for multiple dirs

In any case, I want to solve this in cpp level, let me check later, has been on the todo list for long

**Comment by mpentek** [comment]
> Thanks, didn’t know this didn’t work for multiple dirs
> 
> In any case, I want to solve this in cpp level, let me check later, has been on the todo list for long

For the quick fix, perhaps the current solution is a good solution.

If part of a large effort, I would suggest tackling #6120 and #6118: so probably all folders relative to current working directory (perhaps with an overwrite for abs path possible). This would affect from my perspective, ascii time write, outputs (gid, vtk, hdf5) and restart. Could help out with these.

Pesonally, I am more comfortable with file and folder handling at the python level, unless there are clear cons.

**Comment by adityaghantasala** [comment]
so with this change we can give a folder name like ` folderA/folderB/folderC` .. Nice ... !!

**Comment by adityaghantasala** [comment]
I suggest we can accept this as currently the folder creation is done in Python. 
@philbucher  when this is moved to the C++ layer, this feature will serve as a reminder that it (c++ impl) should have the same behaviour.

**Review by adityaghantasala — APPROVED** [review]

**Pull request merged**
