### PR TITLE
[ContactStructuralMechanicsApplication] Adjust default tangent factor

### PR DESCRIPTION
**Pull request by loumalouomega**
Default reduced to the 2.5% of the normal factor

### CODE REVIEW

**Comment by AlejandroCornejo** [comment]
this is the change that we talk about? The one that the penalty in tangent direction should be lower?

**Comment by loumalouomega** [comment]
Yep

**Review by AlejandroCornejo — APPROVED** [review]

**Comment by AlejandroCornejo** [comment]
It improves the convergence?? :)

**Comment by loumalouomega** [comment]
Only in complex cases, for the tests which are simple is more or less the
same thing

**Comment by loumalouomega** [comment]
> 
> Only in complex cases, for the tests which are simple is more or less the same thing 

In any case it is a compromise value, in some cases 1.0e-1 is better than 1.0e-2. I put the default I thought was fitting best

**Pull request merged**
