### PR TITLE
[Trilinos][restart] correcting rank-access

### PR DESCRIPTION
**Pull request by philbucher**
this way always the correct data-communicator is used

### CODE REVIEW

**Comment by philbucher** [comment]
I realized that the mpi-comm is not set yet in the constructor, @jcotela we should think of a better way of doing this in the future

**Comment by philbucher** [comment]
can someone approve pls?
The current master is broken otherwise

**Comment by jcotela** [comment]
@philbucher the idea is that classes that require mpi communication to work should either get a datacommunicator in construction or receive its name through parameters and retrieve it from ParallelEnvironment.

**Review by jcotela — APPROVED** [review]

**Comment by philbucher** [comment]
Thanks

> @philbucher the idea is that classes that require mpi communication to work should either get a datacommunicator in construction or receive its name through parameters and retrieve it from ParallelEnvironment.

ok, this will become relevant once we have different communicators.
=> I added a TODO comment for this

**Pull request merged**
