### PR TITLE
[Core] Fix filesystem include issue

### PR DESCRIPTION
**Pull request by loumalouomega**
**📝 Description**

Fix filesystem include issue after @rubenzorrilla noticed compilation failing some compilers 

**🆕 Changelog**

- Fix filesystem include

### CODE REVIEW

**Review by roigcarlo — APPROVED** [review]
:+1: 

Is the problem reproducible via a test?

**Comment by loumalouomega** [comment]
> 👍
> 
> Is the problem reproducible via a test?

I don't know how

**Comment by rubenzorrilla** [comment]
> > +1
> > Is the problem reproducible via a test?
> 
> I don't know how

I noticed when compiling with clang13.

**Comment by roigcarlo** [comment]
In my machine was working with clang 13 :/

**Comment by loumalouomega** [comment]
FYI @philbucher https://github.com/p-ranav/glob

**Pull request merged**
