### PR TITLE
[ContactStructuralMechanicsApplication] Replace row operation with direct assigment

### PR DESCRIPTION
**Pull request by loumalouomega**
This avoid some errors, row operation may fail (due to unknown reasons)

### CODE REVIEW

**Review by philbucher — DISMISSED** [review]
does this fix the problem in the nightly tests?

**Comment by loumalouomega** [comment]
> 
> 
> does this fix the problem in the nightly tests?

Nope, but fix this. I found it looking the nightly error BTW

**Comment by loumalouomega** [comment]
The plan B would be to move those tests to validation... (and research the fail later)

**Comment by loumalouomega** [comment]
@philbucher I needed to trigger Travis

**Review by philbucher — APPROVED** [review]

**Pull request merged**
