### PR TITLE
[Structural] clean harmonic analysis tests

### PR DESCRIPTION
**Pull request by philbucher**
This still uses the ExternalSolversApp hardcoded, can you please refactor and add tests in case the App does not exist?
If you can drop completely the usage of the ExternalSolversApp and use the solvers from the EigenSolversApp that would be even better 
Thx

BTW `ControlledExecutionScope` is now (with a different name) available in `KratosUnittest`

### CODE REVIEW

**Comment by philbucher** [comment]
@qaumann I saw that you also hardcoded the ExternalSolversApp in `test_spring_damper_element`. Can you please take a look there too and refactor if possible?
Thx a lot

**Comment by qaumann** [comment]
I will take care of it

**Comment by qaumann** [comment]
The tests are now skipped, if the ExternalSolverApplication is not available. The hdf5 harmonic analysis test now uses the EigensystemSolver.

I also reduced the simulation times in some tests, so they should be now fasst enough for the small tests again.

The other tests can unfortunately not be ported to the EigensystemSolver. They use the spring and mass elements, which lead to systems with zeros on the diagonal and can therefore not be solved using the strategy employed in the EigensystemSolver (and also require Pastix as a complex linear solver). This could be avoided, if a elimination builder and solver is used, but this results in segfaults for me. Is there any way to use the elimination in this context?

**Comment by philbucher** [comment]
looks perfect, thx
Since I opened the PR can you please approve it?

Regarding the ElimB&S I only know that it is not as often used. I think I remember that there were still some problems with it. @RiccardoRossi @loumalouomega do know you more?

In any case this can be updated in a future PR

**Comment by loumalouomega** [comment]
> 
> 
> looks perfect, thx
> Since I opened the PR can you please approve it?
> 
> Regarding the ElimB&S I only know that it is not as often used. I think I remember that there were still some problems with it. @RiccardoRossi @loumalouomega do know you more?
> 
> In any case this can be updated in a future PR

The problem is onlynin OMP and only with constraints (I think)

**Review by qaumann — APPROVED** [review]

**Pull request merged**
