### PR TITLE
[Core] Adding tests for hashers and comparors

### PR DESCRIPTION
**Pull request by loumalouomega**
**📝 Description**
 Adding tests for hashers and comparors

**🆕 Changelog**
-  Adding tests for hashers and comparors
- Adding missing template

### CODE REVIEW

**Review by roigcarlo — DISMISSED** [review]

**Comment by loumalouomega** [comment]
@roigcarlo I forgot something that failed in debug, please repproval

**Review by roigcarlo — DISMISSED** [review]
Np :+1:

**Comment by loumalouomega** [comment]
> Np 👍

Marvelous, the hasher doesn't work in the same manner in Windows and Linux...

**Comment by loumalouomega** [comment]
> > Np 👍
> 
> Marvelous, the hasher doesn't work in the same manner in Windows and Linux...

@roigcarlo I fixed the tests in Windows

**Review by roigcarlo — APPROVED** [review]

**Comment by roigcarlo** [comment]
> Marvelous, the hasher doesn't work in the same manner in Windows and Linux...

odd, that one should not depend on rng, I specifically looked at FNV1a32Hash code because of the test to see if they were generating the same hash from the same string. Anyway if it is under control no problem

**Pull request merged**
