### PR TITLE
[JsonCheckProcess] fixing formatting for py2

### LINKED ISSUE #4715: [Core] mortar mapper tests fail in python 2.7
Hi @loumalouomega , can you take a look?

image

### PR DESCRIPTION
**Pull request by philbucher**
fixes #4715 

I think this works now, at least it works if I try it in pure py-2 (where also the current version works for some reason)

can you please try @ddiezrod ?

### CODE REVIEW

**Comment by ddiezrod** [comment]
Thanks @philbucher ! Let me try it and I will tell you if this works.

**Review by loumalouomega — DISMISSED** [review]

**Review by ddiezrod — CHANGES_REQUESTED** [review]
it's still failing :(
image

**Comment by philbucher** [comment]
hm no clue :/

can you please try again @ddiezrod ?

**Review by ddiezrod — APPROVED** [review]
it is working now! problem was the relevant digits. Thank you very much @philbucher

**Comment by philbucher** [comment]
perfect, thanks for testing

**Pull request merged**
