### PR TITLE
[FastPR][KratosCore] Remove Dimension() warning

### PR DESCRIPTION
**Pull request by rubenzorrilla**
**📝 Description**
Remove geometry `Dimension` deprecation warning.

### CODE REVIEW

**Comment by loumalouomega** [comment]
The point of the warning was to stop using `Dimension`, no?

**Review by loumalouomega — APPROVED** [review]

**Comment by rubenzorrilla** [comment]
@loumalouomega peligrosa y sospechosamente rápido :rofl:

**Comment by roigcarlo** [comment]
Can we assume that 99% of the usages are `WorkingSpaceDimension` and change it elsewhere :D?

**Comment by rubenzorrilla** [comment]
> Can we assume that 99% of the usages are `WorkingSpaceDimension` and change it elsewhere :D?

Though this is true in the majority of cases, I wouldn't do it.

**Pull request merged**
