### PR TITLE
[Core] Delete deprecated variable_component.h

### PR DESCRIPTION
**Pull request by loumalouomega**
**Description**
Delete deprecated variable_component.h and vector_component_adaptor.h

**Changelog**
- Delete deprecated variable_component.h
- Delete deprecated vector_component_adaptor.h

### CODE REVIEW

**Comment by philbucher** [comment]
@KratosMultiphysics/altair did you remove all occurences?

**Comment by ddiezrod** [comment]
> @KratosMultiphysics/altair did you remove all occurences?

I see there is still one, but it should be possible to fix it very quickly, so you can merge this, thanks!

**Comment by ddiezrod** [comment]
Everything is ok from our side, you can proceed ;)

**Comment by loumalouomega** [comment]
@philbucher  ?

**Review by philbucher — APPROVED** [review]

**Pull request merged**
