### PR TITLE
[FastPR][Core][Structure] Common SetAndFillBuffer

### PR DESCRIPTION
**Pull request by rubenzorrilla**
**📝 Description**
Ass suggested in #9592 this adds a `SetAndFillBuffer` function to the `auxiliary_solver_utitlities.py`.

### CODE REVIEW

**Review by loumalouomega — APPROVED** [review]

**Review by philbucher — APPROVED** [review]
Thx

**Comment by rubenzorrilla** [comment]
I can't understand why this is affecting the mass conservation tests :confused:

**Comment by philbucher** [comment]
> I can't understand why this is affecting the mass conservation tests confused

It is not

the nightly tests have been failing for a few days. I pinged the fluid team in #9591 but didn't get a reply

**Comment by rubenzorrilla** [comment]
> > I can't understand why this is affecting the mass conservation tests confused
> 
> It is not
> 
> the nightly tests have been failing for a few days. I pinged the fluid team in #9591 but didn't get a reply

Sorry. I didn't note.

**Pull request merged**
