### PR TITLE
[Core] Update README.md formatting and add emojis for better readability

### PR DESCRIPTION
**Pull request by loumalouomega**
**📝 Description**

This PR updates the README.md file for the Kratos Multiphysics project. The changes include the addition of emojis to various headings to improve readability and make the content more visually appealing. Section headings have also been converted to use proper Markdown hierarchy, improving the document's overall structure. No changes have been made to the actual content or meaning of the text.

**🆕 Changelog**

- [Update README.md](https://github.com/KratosMultiphysics/Kratos/commit/df52268730ca9265b46a9be01451f690945712bc)

### CODE REVIEW

**Comment by matekelemen** [comment]
I´m fine with memes and emojis in the source code, but I can´t say I´m thrilled about putting them in the docs, especially in the main readme.

**Comment by loumalouomega** [comment]
> I´m fine with memes and emojis in the source code, but I can´t say I´m thrilled about putting them in the docs, especially in the main readme.

We can add some, but not all of them

**Comment by loumalouomega** [comment]
I guess I should close this?

**Review by rubenzorrilla — COMMENTED** [review]
Just saying that I'm fine with the changes.

**Comment by RiccardoRossi** [comment]
well, to be honest i share @matekelemen 's opinion on this. Do we really want the emoticons in the readme??

**Comment by loumalouomega** [comment]
> well, to be honest i share @matekelemen 's opinion on this. Do we really want the emoticons in the readme??

UwU (okay I remove them)

**Comment by RiccardoRossi** [comment]
waitwait, let's see what other think about

**Comment by loumalouomega** [comment]
> waitwait, let's see what other think about

I left one

**Review by rubenzorrilla — APPROVED** [review]

**Pull request merged**
