### PR TITLE
Fixed race condition in non-historical omp loop

### PR DESCRIPTION
**Pull request by msandre**

### CODE REVIEW

**Review by jcotela — APPROVED** [review]
:+1: Thanks for the fix. Looking through the application, I think this fixes all instances of this problem.

**Comment by philbucher** [comment]
may I ask why is the current code not working?

It looks correct to me

**Comment by jcotela** [comment]
If the variable in question is not set, the non-const access will initialize it to zero. Within a parallel loop, this can introduce a race condition, since you may be allocating memory. Even if it is not always a problem, kratos will throw an error there in debug mode, just in case...

**Review by sunethwarna — APPROVED** [review]
It works in full debug. Thanks :)

**Pull request merged**
