### PR TITLE
Fixing size_t problems

### PR DESCRIPTION
**Pull request by roigcarlo**
It seems that some versions of visual studio have problems with the `size_t` as pybind also defines the type inside for some reason. 

The proposal is to replace `size_t` for `std::size_t` so we use the one defined in the std ( which is the correct one, `size_t` without namespace is part of the C standard)

If you agree I will modify the applications as well.

Tests will pass anyway so don't trust them. We are testing this is @Vahid-Galavi 's computer.

### CODE REVIEW

**Comment by Vahid-Galavi** [comment]
It works for my case.

**Review by jcotela — APPROVED** [review]
:+1: I guess it is fine, since it solves the problem.

**Comment by roigcarlo** [comment]
Actually, we should change all appearances of 'size_t' I intended to do it, but there are quite a few...

**Comment by Vahid-Galavi** [comment]
It solved many errors but there are still some errors in ExternalSolversApplication.

**Comment by roigcarlo** [comment]
Ok, let me try to fix the external solvers one and we can try to fix the ones in other applications as they appear

**Comment by roigcarlo** [comment]
@Vahid-Galavi Can you copy here the error with the external solvers app?

**Comment by philbucher** [comment]
I think this is solved in #2326 right?

**Comment by roigcarlo** [comment]
Yup, not the best solution out there but we have to stick with #2326 for now. closing this one.

**Pull request closed without merging**
