### PR TITLE
[Mapping] cleanup for extension I

### PR DESCRIPTION
**Pull request by philbucher**
**Description**
This PR is a preparation for #8611 
It does not yet do the splitting into core and MPIExtension but it prepares it. 
Unfortunately there are quite a few things to be done, hence I would like to merge smaller PRs with cleanups first

This PR contains:
- turn the `MappingMatrixUtilities` from a `namespace` to a `class`
- make the `InterpolativeMapperBase` header-only. This is unfortunately required for the splitting of the extension to avoid the MPI dependency. Same issue/principle that we have with the strategies

### CODE REVIEW

**Comment by philbucher** [comment]
Can someone approve please?

**Review by pooyan-dadvand — APPROVED** [review]
Thank you @philbucher!

**Review by rubenzorrilla — APPROVED** [review]
No behavior change. Only refactor. :ok:

**Comment by philbucher** [comment]
thx guys

**Pull request merged**
