### PR TITLE
[core] Unused and not defined constructor

### PR DESCRIPTION
**Pull request by maceligueta**
Detected with Windows warnings

### CODE REVIEW

**Review by philbucher — DISMISSED** [review]

**Comment by maceligueta** [comment]
It seems like the windows compilation is getting cleaner. I will keep compiling with my laptop and let's see if we get to a completely clean log.
@philbucher . The AdjointSolidElement is implemented correctly, but the fact that it is implemented in the cpp file misleads the compiler a bit and it spits 10-12 warnings. They are false positives, so I let you decide if it's a good idea to have the definitions in the .h file.

**Comment by philbucher** [comment]
> It seems like the windows compilation is getting cleaner. I will keep compiling with my laptop and let's see if we get to a completely clean log.

Awesome, thx a lot
Could you please take a look if we can add the corresponding compiler flags that turns warnings into errors also on Win? This way the build would stay clean. see https://docs.microsoft.com/en-us/cpp/build/reference/compiler-option-warning-level?view=vs-2019 
Using `/WX` is probably not possible atm unless we have no warnings at all, but maybe in the future

> @philbucher . The AdjointSolidElement is implemented correctly, but the fact that it is implemented in the cpp file misleads the compiler a bit and it spits 10-12 warnings. They are false positives, so I let you decide if it's a good idea to have the definitions in the .h file.

I agree to move it, I think this was also done for the `KratosComponents`. As long as it compiles clean I think it is ok

**Comment by maceligueta** [comment]
Following your link:

`/wennnn	Treats the compiler warning that is specified by nnnn as an error.`

So the flag `/we4661` would treat as errors those warnings about undefined methods, for example.

**Comment by philbucher** [comment]
> Following your link:
> 
> `/wennnn Treats the compiler warning that is specified by nnnn as an error.`
> 
> So the flag `/we4661` would treat as errors those warnings about undefined methods, for example.

can you please try adding it?

**Review by RiccardoRossi — DISMISSED** [review]
thx

**Comment by maceligueta** [comment]
@philbucher I've tried to push it from two different computers and it was not possible. Apparently, I don't have permissions.

**Comment by philbucher** [comment]
What do you mean you don’t have permissions?
To push?

**Comment by maceligueta** [comment]
When I click Push it gives an error. I tried from two different computers, it's weird.

**Comment by maceligueta** [comment]
Well it's not a problem of permissions, it's the GUI. It probably does not like the .github folder. Anyways, I pushed from the terminal and it worked. Sorry about the noise.

**Comment by philbucher** [comment]
I assume you use gitkraken right?
I had the same problems with it, couldn’t yet figure it out
I anyway use more and more the git of vscode whivh doesn’t have this problem

Did you test this locally?

**Comment by maceligueta** [comment]
Yes, I tested it locally and it gave errors instead of warnings.

**Comment by maceligueta** [comment]
We need to add this as an error in the future, too (4804):
`D:\a\Kratos\Kratos\applications\StructuralMechanicsApplication\custom_advanced_constitutive\rule_of_mixtures_law.cpp(567,37): warning C4804: '+=': unsafe use of type 'bool' in operation`
@AlejandroCornejo  told me he is going to fix this one soon.

**Comment by maceligueta** [comment]
> I assume you use gitkraken right?
> I had the same problems with it, couldn’t yet figure it out
> I anyway use more and more the git of vscode whivh doesn’t have this problem

Yes, it was the Kraken. And I am also moving to VSCode, but I had a couple of problems with it and lost files, so I am very careful with it now...

**Review by philbucher — APPROVED** [review]
Perfect thanks

**Pull request merged**
