### PR TITLE
[WIP] Travis-ci

### PR DESCRIPTION
**Pull request by roigcarlo**
This adds Travis-ci support for KratosCore.

Some remarks:
* This PR is mostly a test, please do not merge it... yet.
* Only KratosCore is being built
* Only PR are being built

Todo
- [x] Use -j2 to use all travis cores
- [x] Compile artifacts cache
- [x] Add tests
- [x] Modify tests so the exit code is not 0 if they fail
- [x] Use python3 so tests actually run / make tests run with python2

Drop
- [ ] Apt cache

### CODE REVIEW

**Comment by pooyan-dadvand** [comment]
Bravoooooo Charli!!! 🥇  👍 
It just compiles or also run tests?

**Comment by roigcarlo** [comment]
Just compiles right now, but tests are easy to add :)

**Comment by roigcarlo** [comment]
@pooyan-dadvand when we merge #374 this will be almost ready to deploy ( just resolve the merge conflicts that will appear as I wrongly used this to tests the changes from #374 before making a PR....  my bad :cry: )

Currently it compiles with -O0, which allows to compile:
* Kratos
* KratosCore
* StructuralMechanics
* FluidDyanamics
* ExternalSolvers

Since time is relatively low with -O0, we use ccache, and tests can either run ( KratosCore ) or are just simple too slow and get killed ( FluidDynamics, StructuralMechanics... ). There is room to compile more applications. At least for the time being before adding -03...

Is there any other "Core" applications that would be interesting to add here?

**Comment by roigcarlo** [comment]
@pooyan-dadvand  This is ready now for a first blow. Should we add something else or can we ahead and merge?

Also, maybe its a good idea to open a new issue regarding the slow tests once this starts to run.... I will be comfortable increasing the nightly timer to 2min, but be aware that this escalates quickly in time as more apps are added.

**Comment by pooyan-dadvand** [comment]
I think that we should add the compilation of the core and start to add some applications. Then we will add the tests to the core and applications one by one. (considering the time of the tests). At this moment we have the confirmation of the @jcotela for FluidDynamicApplication and @RiccardoRossi from @KratosMultiphysics/structural-mechanics team for StructuralMechanicApplication. @maceligueta would you please tell us if you want to add DEM or any other related applications to be added?

Just to clarify, correct compilation of these application is required to make a Pull request mergable.

We will gradually add more application to it when application maintainers ask for.

**Comment by maceligueta** [comment]
It would be great if we can add the DEM app! I think it would be positive to add the Swimming DEM App as well (unless @GuillermoCasas says something against this).

**Comment by GuillermoCasas** [comment]
Nothing against it at all!

**Comment by loumalouomega** [comment]
One question. Will these checks include the fast tests implemented in CPP?

**Comment by roigcarlo** [comment]
@loumalouomega Currently it won't run any test. We decided with @pooyan-dadvand  that we be gradually adding new features.

With this first merge ( after #381 or DEM will fail ) It will compile the core.
After this we will start to work on making the core tests run alongside the python ones. At that point will probably enable the KratosCore tests in Travis.

Finally if everything goes as expected and times are ok, we will start to activate the "small" test suit and cpp tests for other applications as well.

**Review by pooyan-dadvand — APPROVED** [review]
Good job!! 👍

**Comment by maceligueta** [comment]
@pooyan-dadvand and @roigcarlo . I guess the criterion for a 'correct compilation' was 'no errors'. Wouldn't it be interesting to impose 'no warnings'??

**Comment by roigcarlo** [comment]
Yup that would be the goal, but I would say to wait a little bit until we activate `-Werror` mainly for two reasons. 

1 - I wouldn't recommend to be too punitive right away, lets this settle down a bit, get the people used to this, then we can add tests, then we don't allow warnings, then we check code style, etc.... If we roll out all possible restrictions people will just get angry because they cannot work.

2 - The intention is to compile with clang as well, and currently it gives some warnings that are being hard to chew and some others that we simply don't understand. I would said is not fair to tell people not to introduce warnings when they are some in the code.

**Pull request merged**
