### PR TITLE
[CI] running nightly build for Core changes

### PR DESCRIPTION
**Pull request by philbucher**
we had and have issues with breaking tests in the nightly build
In this PR I propose to run the nightly tests for changes to the Core (and the backbone apps)

The consequence of this is most probably a bit of congestion on the CI, not sure how much we will notice this

Advantage: More security when changing things in the Core
Disadvantage: Potentially congestion in CI. Not sure if this is soo bad, as rapid changes in the Core have the potential to introduce bugs. Hence slowing it down a bit could even be beneficial

mentioning the devs that were involved in the past
@riccardotosi @loumalouomega @maceligueta

### CODE REVIEW

**Comment by loumalouomega** [comment]
This runs just after merge?

**Comment by philbucher** [comment]
before
This way we know beforehand if sth breaks

**Comment by philbucher** [comment]
also important: The additional nightly runs cannot be made "Required"
But I think by now everyone has gotten used to the CI

**Comment by maceligueta** [comment]
I think it's a good move. I also think that safety is the priority over a possible (and maybe beneficial) CI slow down,

**Comment by maceligueta** [comment]
Is there a way to call the nightly tests of individual applications? Maybe we could resort to external CI services (back to Travis?)

**Comment by philbucher** [comment]
> 
> 
> Is there a way to call the nightly tests of individual applications? Maybe we could resort to external CI services (back to Travis?)

As it is now it runs the complete nightly build (same as is run every night, with all Apps) BUT only when the Core changes

Sure we can also use external services, adding more stuff is never a problem. BTW I read that Travis has changed ownership and now it is a bit annoying to work with, I read that CircleCI seems to be a good alternative

**Comment by philbucher** [comment]
Idea what we could do by ourselves (but is more work):
We have a CI for the Apps that detects if an App is changed. If an app is changed, it will compile it and run the NIGHTLY tests
E.g. if there are changes in the DEM App, it will run the nightly build (aka release compilation with nightly tests) of the DEM App an potentially depending Apps (such as SwimmingDEM)

Actually I think this would even be relatively easy to implement:
The CI workflow gets triggered if anything in the `applications` folder is changed
Then we have to manually parse which apps are changed
Once we know that we can
- Add this app to the compilation
- Optionally also check if other apps depend on it and add those too

**Comment by philbucher** [comment]
@maceligueta could you add this to the next community meeting?
This is sth that affect every dev, since on busy days, the CI will become slower and slower the more configurations we add

I think it makes sense to be on the "safe" side at the cost of being a bit slower in development, but this has to be discussed with the community

**Comment by rubenzorrilla** [comment]
> @maceligueta could you please add this to the next community meeting?
> This is sth that affects every dev, since on busy days, the CI will become slower and slower the more configurations we add
> 
> I think it makes sense to be on the "safe" side at the cost of being a bit slower in development, but this has to be discussed with the community

Although I agree with the open discussion proposal, I'd add it for the moment. My point is that, this would give people an idea of how they daily development is affected by this before the discussion. If it becomes in a bottleneck we can easily remove it.

**Comment by philbucher** [comment]
> > @maceligueta could you please add this to the next community meeting?
> > This is sth that affects every dev, since on busy days, the CI will become slower and slower the more configurations we add
> > I think it makes sense to be on the "safe" side at the cost of being a bit slower in development, but this has to be discussed with the community
> 
> Although I agree with the open discussion proposal, I'd add it for the moment. My point is that, this would give people an idea of how they daily development is affected by this before the discussion. If it becomes in a bottleneck we can easily remove it.

makes sense to me, I see that this has been around again for 2 months
and since currently the nightly build is working, we can add it

@rubenzorrilla you mind approving? :)

**Review by rubenzorrilla — APPROVED** [review]

**Pull request merged**
