### PR TITLE
cps/Bug Fix in Lift Coefficient Jump

### PR DESCRIPTION
**Pull request by inigolcanalejo**
I found a bug in the implementation of the lift coefficient when it is computed using the potential jump. The current implementation is based on this formula:

formula_lift_coefficient

which is implemented in this line: https://github.com/KratosMultiphysics/Kratos/blob/df29b6f07cdb937ec6d5f796b46ae23762295576/applications/CompressiblePotentialFlowApplication/python_scripts/compute_lift_process.py#L95

However, the above formula has a mistake because we are forgetting to divide by the reference chord. This can also be recognized by looking at the units. The correct formula is:

formula_lift_coefficient_correct

Being the new proposed implementation: https://github.com/KratosMultiphysics/Kratos/blob/6178fea72462c28559465ae1cad05d2e56d3aec2/applications/CompressiblePotentialFlowApplication/python_scripts/compute_lift_process.py#L95

This doesn't brake any test because the reference chord is always taken as 1.0 in the tests.

@marcnunezc since the computation of the adjoints are also based on this formula this minor bug is also inside the computation of the adjoints. Until know we didn't really notice it because we were assuming that the reference chord is always 1. Shall we fix this also within this PR?

### CODE REVIEW

**Comment by marcnunezc** [comment]
Nice catch! 

Yes I would take the chance to do this here. Do you want to do it yourself or shall I do the changes?

We would need to add a parameter in the response function settings to be read here (throwing an error if its not defined):

https://github.com/KratosMultiphysics/Kratos/blob/9df0946210c8e90f8df697fbc9b0364b63736382/applications/CompressiblePotentialFlowApplication/custom_response_functions/adjoint_lift_response_function_coordinates_jump.cpp#L24-L33

and store it in a "mReferenceArea" variable to be used in both CalculateValue() and CalculateGradient()

**Comment by inigolcanalejo** [comment]
Ok, I can give it a shot. I will make some suggestion commits how I imagine it could be done and you can check whether it is the same as you thought.

**Comment by inigolcanalejo** [comment]
@marcnunezc feel free to hard reset my commits if you don't like how it is done. Let me briefly explain:

I didn't add the reference chord in the response function settings because we were also having it in the lift process and I don't think it is a good idea to have it duplicated defined in two different places. For this reason I added a new variable REFERENCE_CHORD that reads the reference chord from the parameters of the wake process (I had to change it from the lift process to the wake process because one can run an adjoint analysis without the lift process)

**Comment by marcnunezc** [comment]
> @marcnunezc feel free to hard reset my commits if you don't like how it is done. Let me briefly explain:
> 
> I didn't add the reference chord in the response function settings because we were also having it in the lift process and I don't think it is a good idea to have it duplicated defined in two different places. For this reason I added a new variable REFERENCE_CHORD that reads the reference chord from the parameters of the wake process (I had to change it from the lift process to the wake process because one can run an adjoint analysis without the lift process)

Yep that was my concern as well, but note that this way we still need to define twice the reference chord! Am i wrong? 

Imagine we have a profile with ref_area = 2.0, we would need to set it in the Parameters of the DefineWakeProcess of the PrimalProblem, and in the Parameters of the DefineWakeProcess of the AdjointProblem. In fact, the python test would fail if the reference area was different from 1.0 right now because there is not synchronization of this parameter.

Since this "synchronization" has to happen either way (unless we come up with a different solution), I would keep the reference chord in the compute lift process for the primal problem and add it in the response function settings of the adjoint problem.

As users we would have to either set manually both parameters, or synchronize automatically in the script that runs both primal and adjoint problem.

Do you agree?

**Comment by inigolcanalejo** [comment]
I think that if you do sensitivity analysis you would only need to set the reference area in the wake process of the adjoint problem, since from the primal the only thing you are interested in is the values of the potential which are independent of the reference area. Unless of course you also want to compute the lift in the primal (like in the test), in which case you also need the reference area in the primal.

Since primal and adjoint are run as separated analysis with different json parameters, I don't see a solution to this duplication (other than synchronizing it automatically in the script that runs both as you suggest), however I would still try to keep the setting on the same place for both analysis to avoid confusion.

Still, my proposal might not be the best solution. What about setting the reference area within the solver_settings? In this manner we can read it in the constructor of the python solvers.

I'll commit a last attempt and if you are still not convinced we can set it in the response function settings as you suggest.

**Comment by inigolcanalejo** [comment]
@marcnunezc so I kind of tried to find a compromise between both ideas:

As you suggested I added a parameter in the response function settings that is read in the constructor (throwing an error it it is not defined or 0):

https://github.com/KratosMultiphysics/Kratos/blob/5593fe7a4f8b62d66379f14ca09cfbd1460cd731/applications/CompressiblePotentialFlowApplication/custom_response_functions/adjoint_lift_response_function_coordinates_jump.cpp#L32-L36

This is stored in the member variable mReferenceChord and used in CalculateValue and CalculateGradient.

The only thing is that I put this parameter in the solver_settings and then add it to the response function settings (see implementation).

As I said, if you still don't like it we can put it directly in the response function settings. Let me know what you think.

**Review by marcnunezc — APPROVED** [review]
I like the current implementation! Thanks!

**Comment by inigolcanalejo** [comment]
Perfect! Thanks!

**Pull request merged**
