### PR TITLE
[Core] Stage new ModifyAfterSolverInitialize() method

### PR DESCRIPTION
**Pull request by rubenzorrilla**
This PR adds a new method to the analysis_stage.py. It's intended to collect all the geometrical operations that require the solver to be initialized.

### CODE REVIEW

**Comment by philbucher** [comment]
+1 for this change 

Could you please wait to give @jcotela and @RiccardoRossi also time to have a look?

**Comment by RiccardoRossi** [comment]
+1 on my side

**Comment by rubenzorrilla** [comment]
@RiccardoRossi can we merge then?

**Review by loumalouomega — APPROVED** [review]
Nice

**Pull request merged**
