### PR TITLE
[CI] switch to release

### PR DESCRIPTION
**Pull request by philbucher**
lets see how long it takes

### CODE REVIEW

**Comment by philbucher** [comment]
It works, here are the results:
Build time with `Custom` or `FullDebug`: ~45-50min
Build time with `Release`: 2hrs (~1/3 aka 40min for ContactStructuralMechanics @loumalouomega )

Tests execution timewith `Custom` or `FullDebug`: ~5min
Tests execution timewith `Release`: ~45 sec

Conclusion: Once #6372 is fixed I think this can go in, we are still far from the time limit of 6hrs. Especially considering that this test was done without caching, which could ofc speed it up a lot
Also if we can make use of Artifacts we can decrease the time a lot probably, hence I see the 2hrs as a worst case scenario

**Comment by loumalouomega** [comment]
> It works, here are the results:
> Build time with `Custom` or `FullDebug`: ~45-50min
> Build time with `Release`: 2hrs (~1/3 aka 40min for ContactStructuralMechanics @loumalouomega )
> 
> Tests execution timewith `Custom` or `FullDebug`: ~5min
> Tests execution timewith `Release`: ~45 sec
> 
> Conclusion: Once #6372 is fixed I think this can go in, we are still far from the time limit of 6hrs. Especially considering that this test was done without caching, which could ofc speed it up a lot
> Also if we can make use of Artifacts we can decrease the time a lot probably, hence I see the 2hrs as a worst case scenario

It is because of the nightly? I already move most of them to validation

**Comment by philbucher** [comment]
No that’s only compilation

**Comment by loumalouomega** [comment]
> No that’s only compilation

huuuuum, I can add a compilation flag to disable conditions that are not used by default (like the penalty ones, this will reduce in 1/3 the times at least)

**Comment by loumalouomega** [comment]
> > No that’s only compilation
> 
> huuuuum, I can add a compilation flag to disable conditions that are not used by default (like the penalty ones, this will reduce in 1/3 the times at least)

In the same way the advanced CL

**Comment by philbucher** [comment]
hm I would leave it for the moment
We should just be aware that the heavy templating affects the times a lot

Same also for Structural, even though it took not as long as Contact also there the build time was a bit higher than for the other apps

**Comment by philbucher** [comment]
@roigcarlo this will be ready once the CI passed

**Comment by philbucher** [comment]
@roigcarlo should we remove the `O0` in the configure?
https://github.com/KratosMultiphysics/Kratos/blob/1dd182e8d025ff3e83dd26397ad0fca19d08f809/.github/workflows/configure.sh#L55

**Comment by roigcarlo** [comment]
Yes and no. Yes for the release, not in that file or the others CI will crash

**Comment by philbucher** [comment]
so then I do nothing?

**Comment by roigcarlo** [comment]
mm you can create another configuration file and call that one. But yes, leaving it as is should be enough as currently  -O2 overrides -O0 because of the flag order.

**Comment by philbucher** [comment]
> mm you can create another configuration file and call that one. But yes, leaving it as is should be enough as currently -O2 overrides -O0 because of the flag order.

ok then I will leave it as is in this PR and improve it in a different one, have to make some improvements there anyway

**Comment by philbucher** [comment]
@roigcarlo can we merge this or do you want to wait?
Asking bcs I would like to finalize the Clang-CI PR

**Review by roigcarlo — APPROVED** [review]
Good to me :+1:

**Comment by roigcarlo** [comment]
But you intend this to run on every PR? Maybe we could set this only for chron jobs :S

**Comment by philbucher** [comment]
> But you intend this to run on every PR? Maybe we could set this only for chron jobs :S

hm yes. you think it is not a good idea?
Alternatively we could do `Custom`&`FullDebug` in the CI and `Release` in the nightly
What do you think?

**Comment by roigcarlo** [comment]
> Alternatively we could do Custom&FullDebug in the CI and Release in the nightly
What do you think?

I think that would be better, I am not sure what will happen in the queue if every PR triggers a potential 2h job :S

**Comment by philbucher** [comment]
ok then I will do this

**Pull request closed without merging**
