### PR TITLE
[Core] Expose ElementSizeCalculator to python

### PR DESCRIPTION
**Pull request by sunethwarna**
**Description**
Exposes element size calculator to python

**Changelog**
- Expose `ElementSizeCalculator` to python

### CODE REVIEW

**Review by philbucher — APPROVED** [review]

**Review by rubenzorrilla — CHANGES_REQUESTED** [review]
What would be the use case? These utilities were created to be used in the elemental formulations so I don't see the need to expose them.

**Comment by sunethwarna** [comment]
May be @akodakkal can explain the used case?

**Comment by akodakkal** [comment]
> What would be the use case? These utilities were created to be used in the elemental formulations so I don't see the need to expose them.

The use case was to do some post processing on the mesh sizes

**Comment by rubenzorrilla** [comment]
> > What would be the use case? These utilities were created to be used in the elemental formulations so I don't see the need to expose them.
> 
> The use case was to do some post processing on the mesh sizes

If this is the case I'd make the required changes locally as this would be (in my opinion) rarely used outside the elements and conditions. Note that the current utilities interface is extremely large.

**Comment by mpentek** [comment]
For any validation (or verification) case some metrics for the mesh are typically required. I do not see this as an untypical or highly case-dependent request. We also used to have the CFL calculation solely used for internal purposes at C++ level, but the usage prospects changed.

Maybe the utilities interface itself needs to be adjusted in terms of how and where the implementations happen?

**Comment by rubenzorrilla** [comment]
> 
> 
> For any validation (or verification) case some metrics for the mesh are typically required. I do not see this as an untypical or highly case-dependent request. We also used to have the CFL calculation solely used for internal purposes at C++ level, but the usage prospects changed.
> 
> Maybe the utilities interface itself needs to be adjusted in terms of how and where the implementations happen?

I'm still not conviced at all, note that the element size might vary a lot depending on the formula used, specially in real cases in which distorted elements are much prone to appear. With this I mean that this could be a bit sensitive if it is to be used in validation. In any case I wouldn't block if you guys will need it in the future.

In case we add it, I'll add the gradient-based formula exposure, which is quite common for simplex elements. This means that it cannot be added to the current `AddElementSizeCalculator` as this will expose it to the non-simplex elements too (something that would be theoretically wrong).

**Comment by mpentek** [comment]
> > For any validation (or verification) case some metrics for the mesh are typically required. I do not see this as an untypical or highly case-dependent request. We also used to have the CFL calculation solely used for internal purposes at C++ level, but the usage prospects changed.
> > Maybe the utilities interface itself needs to be adjusted in terms of how and where the implementations happen?
> 
> I'm still not conviced at all, note that the element size might vary a lot depending on the formula used, specially in real cases in which distorted elements are much prone to appear. With this I mean that this could be a bit sensitive if it is to be used in validation. In any case I wouldn't block if you guys will need it in the future.
> 
> In case we add it, I'll add the gradient-based formula exposure, which is quite common for simplex elements. This means that it cannot be added to the current `AddElementSizeCalculator` as this will expose it to the non-simplex elements too (something that would be theoretically wrong).

@rubenzorrilla thanks for your considerations. I totally agree about the real-word use cases. Without wanting to go into a lengthier conversation about this, this goes a bit towards the question whether to use/present a metric because it is useful or because it is simply expected...

Probably a case-by-case decision.

**Pull request closed without merging**
