### PR TITLE
[Core] removing call to Check for Elements and Conditions in SolvingStrategy

### PR DESCRIPTION
**Pull request by philbucher**
this is already done in Scheme

### CODE REVIEW

**Comment by philbucher** [comment]
see Scheme: https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/solving_strategies/schemes/scheme.h#L723-L752

**Comment by pooyan-dadvand** [comment]
@KratosMultiphysics/technical-committee delegates the followup and approval of this PR to @KratosMultiphysics/implementation-committee

**Comment by adityaghantasala** [comment]
Looks fine ! Thanks !

**Comment by philbucher** [comment]
ping @KratosMultiphysics/implementation-committee

**Comment by philbucher** [comment]
can anyone approve pls?

**Review by loumalouomega — APPROVED** [review]

**Pull request merged**
