### PR TITLE
[Core] using model in test of master-slave constraints

### PR DESCRIPTION
**Pull request by adityaghantasala**
Changing the test of master-slave constraints to use Model.

### CODE REVIEW

**Comment by loumalouomega** [comment]
How did this passed the test?, did you added to tests on core?

**Comment by adityaghantasala** [comment]
was just doing that .. :-p

**Review by loumalouomega — DISMISSED** [review]
That's why the test "passed", it was not added

**Comment by adityaghantasala** [comment]
there is a spelling mistake in the test file name. I corrected it in latest commit

**Comment by loumalouomega** [comment]
Strange, I copy pasted

**Review by loumalouomega — DISMISSED** [review]

**Comment by adityaghantasala** [comment]
no no .. its not from you .. it was there before .. thanks by the way.

**Review by loumalouomega — APPROVED** [review]

**Pull request merged**
