### PR TITLE
Fixing Poromechanics compilation in Windows

### PR DESCRIPTION
**Pull request by ipouplana**
This PR solves the compilation error pointed out in #2729

### CODE REVIEW

**Review by loumalouomega — DISMISSED** [review]
It is OK

**Comment by ipouplana** [comment]
It seems AppVeyor does not compile... @loumalouomega do you know how to restart it? Or is it true that there is something wrong with this PR?

**Comment by roigcarlo** [comment]
Seems an error fetching the PR, just commit something else and it should trigger again

**Comment by ipouplana** [comment]
Thanks @roigcarlo ! AppVeyor already passed. (Could you approve this PR? ^_^')

**Review by roigcarlo — APPROVED** [review]

**Pull request merged**
