### PR TITLE
Adapting existing mapper to work with double sided surfaces

### PR DESCRIPTION
**Pull request by rubenzorrilla**
Creation of a new mapper Python class which considers a positive and a negative fluid sides and maps to a unique structure interface, which is suppose to be shell or membrane shaped. A test which checks this feature has been created as well.

### CODE REVIEW

**Comment by philbucher** [comment]
@rubenzorrilla I am curious how you model the fluid case. Do you have a small gap to create the two submodelparts?
I think @AndreasWinterstein @msandre and @adityaghantasala are also interested

**Review by RiccardoRossi — APPROVED** [review]
+1

**Comment by rubenzorrilla** [comment]
@philbucher it is a bit tricky, but I will try to summarize the steps to follow in GiD:

1. Create 3 layers: one for the "positive" skin, one for the "negative" skin and an extra one for all the other entities.
2. Set up the "skeleton" of your model (points and lines). Note that the skeleton has no duplicities, meaning that the lines and points that will conform the immersed shell (or membrane) will be shared between the positive and negative fluid faces. Of course you can duplicate these entities as well if needed.
3. Switch to the "positive" fluid face layer and set up the surface.
4. Switch to the "negative" fluid face layer and set up the surface.
NOTE: At this point you must have two different surface entities (located at the same position) but sharing its boundary lines and points.
5. Create the outer volume with the "positive" fluid face.
6. Create the inner volume with the "negative" fluid face.

At the end, this can be viewed as the creation of an immersed object with null volume.

**Comment by philbucher** [comment]
@rubenzorrilla ok thx I will try

**Pull request merged**
