### PR TITLE
[StructuralMechanicsApplication] Minor typo correction in base solid element

### PR DESCRIPTION
**Pull request by loumalouomega**
mConstitutiveLawVector->ConstitutiveLawVector in serializer

### CODE REVIEW

**Comment by philbucher** [comment]
did you check the derived elements? I am a bit hesitant to approve since this will break all existing cases where these elements were used, just to fix sth that is not even a real typo. Its just an identifier

**Comment by loumalouomega** [comment]
> 
> 
> did you check the derived elements? I am a bit hesitant to approve since this will break all existing cases where these elements were used, just to fix sth that is not even a real typo. Its just an identifier

It is not the member variable, it is the name use to serialize, which is arbitrary, but consistently we should write it without the m, of member variable.

**Comment by philbucher** [comment]
it is not arbitrary, if you serialize with trace_all this name will be in the file and checked when reloading

I will approve in a few days if none is against it

**Comment by loumalouomega** [comment]
> 
> 
> it is not arbitrary, if you serialize with trace_all this name will be in the file and checked when reloading
> 
> I will approve in a few days if none is against it

OK, I understand, you mean that if someone has saved already the databse will not be able to restore because of this. I understand, therefore a typo in this is not a joke..., I do not have any issue waiting

**Comment by loumalouomega** [comment]
Ping

**Review by philbucher — APPROVED** [review]

**Pull request merged**
