### PR TITLE
[StructuralMechanicsApplication] Adding pyramid solid element

### PR DESCRIPTION
**Pull request by loumalouomega**
**📝 Description**
Adding pyramid solid element

**🆕 Changelog**
- Adding pyramid solid element
- Added test
- Correcting missing methods in geometries
- Expose python

### CODE REVIEW

**Review by philbucher — APPROVED** [review]
thx!

**Comment by AlejandroCornejo** [comment]
interesting! which is the main application of this element? :)

**Comment by loumalouomega** [comment]
> interesting! which is the main application of this element? :)

To mix hexa and tetra meshes, or just a regular element with a very strange shape

**Comment by loumalouomega** [comment]
> interesting! which is the main application of this element? :)

https://arxiv.org/pdf/1705.02451.pdf

**Pull request merged**
