### PR TITLE
[Core] Adding serializer test that fails in current master - Loading twice same model

### PR DESCRIPTION
**Pull request by marcnunezc**
Hi @roigcarlo,

As discussed in person, when trying to load a serialized model a second time, it gives a bad_alloc error:

```
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_serializer.py", line 78, in test_serializer_fluid_analysis
    self.serialized_model.Load("ModelSerialization", second_model)
MemoryError: std::bad_alloc


```

You can reproduce this with the test added in this branch.

Not sure if it is related to #3520.

### CODE REVIEW

**Comment by roigcarlo** [comment]
Thx!, Taking a look at it right now

**Comment by roigcarlo** [comment]
So, the last commit fixes the issue not allowing to load the same model twice. 
Now, we have to discuss if we want to allow this or not. Ping @KratosMultiphysics/technical-committee

As @marcnunezc this is related with #3520, so also ping @riccardotosi in case he wants to add something to the discussion.

**Comment by riccardotosi** [comment]
Just to say that now the `test_serializer_loading` is independent from the FluidDynamicsApplication.

**Comment by roigcarlo** [comment]
Mark this for discuss in the next @KratosMultiphysics/technical-committee meeting

**Comment by pooyan-dadvand** [comment]
I more or less understand the `SetLoadState` method usage, (Although the name doesn't help) but what is the use case for `SeekBegin` and `SeekEnd` method outside of Serializer?

**Comment by roigcarlo** [comment]
@KratosMultiphysics/technical-committee Decided to remove the interface from python and just add a `LoadFromBegining` which will reset the buffer pointer and all the internal pointer list.

**Comment by RiccardoRossi** [comment]
@marcnunezc we need to refresh this. can u get in sync with @roigcarlo about the implementation?

**Comment by marcnunezc** [comment]
Sure!

**Comment by marcnunezc** [comment]
@roigcarlo confirm me if you agree with the current implementation

**Review by roigcarlo — COMMENTED** [review]
Looks good to me. Just a small comment, since `SeekBegin` and `SeekEnd` are not exported now maybe its a good idea to make them private. (`SetLoadState` should remain public)

**Review by roigcarlo — APPROVED** [review]
:+1:

**Comment by marcnunezc** [comment]
> Looks good to me. Just a small comment, since `SeekBegin` and `SeekEnd` are not exported now maybe its a good idea to make them private. (`SetLoadState` should remain public)


Makes sense 👍! SeekBegin and SeekEnd are now private

**Pull request merged**
