### PR TITLE
Add BOOST_ROOT config variable to linux and mingw build scripts

### PR DESCRIPTION
**Pull request by marandra**

### CODE REVIEW

**Review by roigcarlo — APPROVED** [review]

**Review by roigcarlo — CHANGES_REQUESTED** [review]
Actually, I think this cannot be enabled by default. Let me check

**Comment by loumalouomega** [comment]
@marandra if you follow https://github.com/KratosMultiphysics/Kratos/wiki/Windows-Install-(MinGW)
you don't need to specify the boost root, just:

~~~sh
pacman -S mingw64/mingw-w64-x86_64-boost
~~~

**Comment by roigcarlo** [comment]
actually its the same for linux, it should work with any version of boost added through apt-get install or similar.

If it defaults to the system lib even with that we can add it, but we cannot let in the standard script if it blocks the detection of the default lib, as now it is used by several services.

**Comment by marandra** [comment]
Oh, I see. In my case I use a downloaded version of boost, so I have to set it (but I'd rather use a version installed by the package system). I was confused due to the fact that in the install instructions BOOST_ROOT is listed as a basic configuration, and in the mac script it is set. 

Anyways, I'm closing this PR and sorry for the noise. Thanks

**Pull request closed without merging**
