### PR TITLE
[PotentialFlow] Renaming wake distance

### PR DESCRIPTION
**Pull request by marcnunezc**
Hi,

Proposal to rename the distance used for the WAKE:

double -> `WAKE_DISTANCE`
vector -> `WAKE_ELEMENTAL_DISTANCES`

This follows the convention I chose for the embedded geoemetries distance: `GEOMETRY_DISTANCE`

### CODE REVIEW

**Comment by inigolcanalejo** [comment]
Sounds good! :+1:  What about using WAKE_NODAL_DISTANCE instead of WAKE_DISTANCE? I find that it follows more the same criteria as in WAKE_ELEMENTAL_DISTANCES.

**Comment by marcnunezc** [comment]
I went for WAKE_DISTANCE to follow the "default" names that we have in Kratos:

DISTANCE
ELEMENTAL_DISTANCES

I would say that it is redundant to specify WAKE_NODAL_DISTANCE since the distance is always? defined at the nodes (correct me if im wrong @rubenzorrilla )

**Comment by rubenzorrilla** [comment]
> I went for WAKE_DISTANCE to follow the "default" names that we have in Kratos:
> 
> DISTANCE
> ELEMENTAL_DISTANCES
> 
> I would say that it is redundant to specify WAKE_NODAL_DISTANCE since the distance is always? defined at the nodes (correct me if im wrong @rubenzorrilla )

Correct. I'm also in favour of following the Kratos core convention.

By the way, Travis is crashing.

**Comment by marcnunezc** [comment]
It seems it failed by something unrelated to the code, when installing kratos dependancies:


> Reading package lists...
> W: http://ppa.launchpad.net/couchdb/stable/ubuntu/dists/trusty/Release.gpg: Signature by key 15866BAFD9BCC4F3C1E0DFC7D69548E1C17EAB57 uses weak digest algorithm (SHA1)
> W: GPG error: https://packagecloud.io/github/git-lfs/ubuntu trusty InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 6B05F25D762E3157
> W: The repository 'https://packagecloud.io/github/git-lfs/ubuntu trusty InRelease' is not signed.
> W: There is no public key available for the following key IDs:
> 6B05F25D762E3157  
> E: Failed to fetch http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu/dists/trusty/main/binary-amd64/Packages.gz  Hash Sum mismatch
> E: Failed to fetch http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu/dists/trusty/main/binary-i386/Packages.gz  Hash Sum mismatch
> E: Some index files failed to download. They have been ignored, or old ones used instead.
> The command "sudo -E apt-get -yq --no-install-suggests --no-install-recommends $(travis_apt_get_options) install gcc-6 g++-6 gfortran-6 libboost-dev libblas-dev liblapack-dev" failed and exited with 100 during .

I will do a dummy commit to restart it

**Review by inigolcanalejo — APPROVED** [review]
Ok, in that case I think we can merge this

**Pull request merged**
