### PR TITLE
Converting new variable checks to macros

### PR DESCRIPTION
**Pull request by jcotela**
As discussed in #726.

### CODE REVIEW

**Comment by jcotela** [comment]
@pooyan-dadvand Should we also define `KRATOS_DEBUG` versions of the new macros?

**Comment by pooyan-dadvand** [comment]
It would be helpful for cases in which we have to check the variables in all nodes or elements

**Comment by jcotela** [comment]
Done. I also added debug versions of `KRATOS_CHECK_NEAR` and `KRATOS_CHECK_DOUBLE_EQUAL`, which were missing.

**Review by pooyan-dadvand — APPROVED** [review]
👍

**Pull request merged**
