### PR TITLE
[Core] using AtomicUtils in constraint

### PR DESCRIPTION
**Pull request by philbucher**
**Description**
See title
depends on #8154 & #8155

### CODE REVIEW

**Comment by loumalouomega** [comment]
Nope...it is not supported by MSVC

**Comment by philbucher** [comment]
> Nope...it is not supported by MSVC

fails bcs of the missing KRATOS_API (which I added in the other PR)

**Comment by loumalouomega** [comment]
> > Nope...it is not supported by MSVC
> 
> fails bcs of the missing KRATOS_API (which I added in the other PR)

OK, I have not blocked, I just though was not supported

**Comment by philbucher** [comment]
now worries

This PR will compile once I merged #8154

**Comment by philbucher** [comment]
this is also ready for approval :)

**Review by rubenzorrilla — APPROVED** [review]

**Pull request merged**
