### PR TITLE
[MeshingApplication] Adding level-set based isosurface descretization to mmg

### PR DESCRIPTION
**Pull request by swenczowski**
The following changes to the _mmg_ process are suggested to make it capable of iso-surface discretization. In this context, a huge "thank you" goes to @loumalouomega for his help.

- The function `MMGLibCallIsoSurface()` is added, which calls the _mmg_ library functions `MMG2D_mmg2dls` or `MMG3D_mmg3dls`. These functions evaluate a distance field and adapt the boundary of the domain to follow the surface defined by the zero iso-value of the field. A rough description can be found at https://github.com/MmgTools/mmg/tree/master/libexamples/mmg3d/IsosurfDiscretization_example0 ("the elephant example")

- The functionality is activated if `"discretization_type" : "IsoSurface" is chosen. A new parameter sub-dictionary was added to the C++ and Python process.

- If the option `"remove_regions" : true` is specified, the regions with negative distance values are removed and new conditions are created to close the domain. A proper state of the model part is assured by removing isolated points. 

- A test case was added.

Examples: 

- An arch remeshed from from an analytically specified distance field.

bildschirmfoto vom 2019-02-04 15-13-02

- A house remeshed from a distance field based on a predefined hull geometry.

bildschirmfoto vom 2019-02-06 22-29-45

### CODE REVIEW

**Review by philbucher — CHANGES_REQUESTED** [review]
- please merge master first, this PR contains changes in the core that I think were already merged (always merge master before making a PR)
- the example you push is too large for the Kratos-repo. Please add it to the Examples-repo instead, which was created for this purpose

**Comment by loumalouomega** [comment]
>     * please merge master first, this PR contains changes in the core that I think were already merged (always merge master before making a PR)
> 
>     * the example you push is too large for the Kratos-repo. Please add it to the Examples-repo instead, which was created for this purpose

The  merge is already done

**Review by loumalouomega — DISMISSED** [review]
OK from my side

**Comment by philbucher** [comment]
the test is too large, please refactor it to reduce the size
Otherwise the size of the repo (already ~1GB) blows up even more

**Comment by loumalouomega** [comment]
> the test is too large, please refactor it to reduce the size
> Otherwise the size of the repo (already ~1GB) blows up even more

It is not easy to create a simple case for remeshing

**Comment by philbucher** [comment]
nobody said writing tests was easy :)

the mdpa-file has 1.6MB, which I would say is way too large
Please try to refactor

You could also add a smaller test here and leave the bigger one in the examples-repo

**Comment by loumalouomega** [comment]
> nobody said writing tests was easy :)
> 
> the mdpa-file has 1.6MB, which I would say is way too large
> Please try to refactor
> 
> You could also add a smaller test here and leave the bigger one in the examples-repo

Fine

**Comment by loumalouomega** [comment]
@philbucher more reduction?

**Review by philbucher — APPROVED** [review]
Awesome thx!

Simon you could still think abt putting the example you had initially to the Examples repo

**Pull request merged**
