### PR TITLE
Cps/adding auxiliary historical variables list

### PR DESCRIPTION
**Pull request by inigolcanalejo**
Right now we have many historical variables that are only used in the embedded case:

https://github.com/KratosMultiphysics/Kratos/blob/6fbc5e8e0e866f5183267d5ea84cac6ed9713a79/applications/CompressiblePotentialFlowApplication/python_scripts/potential_flow_solver.py#L119-L127

This brings a large overhead in terms of memory for the rest of simulations where the variables are not needed and anyway added. Following the recommendation of @msandre I have added an auxiliary variables list that allows to add variables only when needed.

Also the variable DISTANCE was always defined as historical even though it was not needed.

### CODE REVIEW

**Comment by inigolcanalejo** [comment]
This PR intends to solve https://github.com/KratosMultiphysics/Kratos/issues/5159

**Review by marcnunezc — APPROVED** [review]
Very cool! Thanks!

**Comment by rubenzorrilla** [comment]
> Right now we have many historical variables that are only used in the embedded case:
> 
> https://github.com/KratosMultiphysics/Kratos/blob/6fbc5e8e0e866f5183267d5ea84cac6ed9713a79/applications/CompressiblePotentialFlowApplication/python_scripts/potential_flow_solver.py#L119-L127
> 
> This brings a large overhead in terms of memory for the rest of simulations where the variables are not needed and anyway added. Following the recommendation of @msandre I have added an auxiliary variables list that allows to add variables only when needed.
> 
> Also the variable DISTANCE was always defined as historical even though it was not needed.

This is just to note that the level-set calculation algorithms assume that the `DISTANCE` is a historical value. This means that it is mandatory to declare `DISTANCE` as historical value.

**Comment by marcnunezc** [comment]
> > Right now we have many historical variables that are only used in the embedded case:
> > https://github.com/KratosMultiphysics/Kratos/blob/6fbc5e8e0e866f5183267d5ea84cac6ed9713a79/applications/CompressiblePotentialFlowApplication/python_scripts/potential_flow_solver.py#L119-L127
> > 
> > This brings a large overhead in terms of memory for the rest of simulations where the variables are not needed and anyway added. Following the recommendation of @msandre I have added an auxiliary variables list that allows to add variables only when needed.
> > Also the variable DISTANCE was always defined as historical even though it was not needed.
> 
> This is just to note that the level-set calculation algorithms assume that the `DISTANCE` is a historical value. This means that it is mandatory to declare `DISTANCE` as historical value.

I answered to this as well in https://github.com/KratosMultiphysics/Kratos/pull/5174#issuecomment-508489736

**Pull request merged**
