### PR TITLE
[Core] Removes legacy explicit strategy

### LINKED ISSUE #7273: [Core] After #7138 do we need strategies/explicit_strategy.h?
https://github.com/KratosMultiphysics/Kratos/blob/65a31c45ee18626c1092a3b2fdf7fad0e912e649/kratos/solving_strategies/strategies/explicit_strategy.h#L1

This file I assume is no longer required and could be cleared. @KratosMultiphysics/technical-committee

### PR DESCRIPTION
**Pull request by loumalouomega**
**Description**
Fixes #7273

**Changelog**
- Old legacy, unused explicit strategy. Removing after #7138

### CODE REVIEW

**Comment by philbucher** [comment]
did you check if the old strategy is still used?

**Comment by loumalouomega** [comment]
> did you check if the old strategy is still used?

I did a grep and I cannot find any reference

**Review by philbucher — APPROVED** [review]
:+1:

**Comment by loumalouomega** [comment]
I did a second grep and now I see is used in pfem_2_application @miguelmaso @pablobecker ?, it is still required?

**Comment by miguelmaso** [comment]
I think it's legacy code. Be careful, this class is used in several python scripts. @pablobecker knows better than me those files.

**Comment by loumalouomega** [comment]
> I think it's legacy code. Be careful, this class is used in several python scripts. @pablobecker knows better than me those files.

Thats why I am asking, because otherwise the most practical would be to move this class to pfem_2_application, avoiding breaking stuff and at the same time avoiding confusions (we already have a "duplicated" explicit strategy in the StructuralMechanicsApplication, we should avoid duplicated calsses)

**Comment by loumalouomega** [comment]
> > I think it's legacy code. Be careful, this class is used in several python scripts. @pablobecker knows better than me those files.
> 
> Thats why I am asking, because otherwise the most practical would be to move this class to pfem_2_application, avoiding breaking stuff and at the same time avoiding confusions (we already have a "duplicated" explicit strategy in the StructuralMechanicsApplication, we should avoid duplicated calsses)

Ping @pablobecker

**Comment by dcagri** [comment]
Dear all,
PFEM2 does not compile right now. Next time please don't forget to mention my name in case something related to PFEM2 comes up. I'll work it around and send a PR during the week.
Regards

**Pull request merged**
