### PR TITLE
pushing the changes needed to remove tetgen from the kratos repository

### PR DESCRIPTION
**Pull request by RiccardoRossi**
Dear All,

i have been looking in detail into the licensing issues with tetgen. The first observation is that there are actually multiple licenses of tetgen:

- version 1.4.3 which was originally included in the Meshing application is BSD-like + non commerciale clause
- version 1.5.x **changed its license to AGPL, which is a more restrictive version of GPL.**

It is my understanding that we definitely cannot include the newer version in the Kratos code base (and most probably not even the older version)

**Current branch removes tetgen from the repository and defines internally a macro USE_TETGEN_NONFREE_TPL to avoid compilations of things depending on Tetgen.**

The idea is that a developer should download and compile his own tetgen (compilation is trivial, you just need to ensure adding -fPIC in the Makefile) and add to the configure something like 
-DUSE_TETGEN_NONFREE_TPL=ON \
-DTETGEN_INCLUDE_DIR="/home/rrossi/Downloads/tetgen1.4.3" \
-DTETGEN_LIBRARY_DIR="/home/rrossi/Downloads/tetgen1.4.3" \

with this in principle the behaviour should be as before. Note however that I did not update the PFEM applications and the ULF application, so if you depend on tetgen i'll be very glad to help. I expect porting effort to be very small anyway.

A **problematic aspect however is that we CANNOT distribute Tetgen together with the release version** of Kratos. My original idea was to put the precompiled version of the tetgen somewhere, so that one may manually copy the libtet.so in the right place. However i am not clear at all if this would be an admissible solution.

my suggestion @KratosMultiphysics/pfem is to contact with the author of Tetgen and obtain (in writing) a statement of which approach he would consider as acceptable for us to distribute Tetgen together with the Kratos.

### CODE REVIEW

**Comment by pooyan-dadvand** [comment]
I agree with @RiccardoRossi about the solution and also suggestion of contacting the author.

I would suggest to add a TetGenApplication (like MKLApplication) which encapsulates the interface to Tetgen so we can easily include or exclude it separately from PFEM or Meshing applications.

**Comment by RiccardoRossi** [comment]
@maceligueta @playpaolo @josep-m-carbonell @AFranci can anyone approve this?

**Comment by maceligueta** [comment]
It can't be approved because it's not compiling so far. In this branch PFEM uses the tetgen in external_libraries, which has been removed. @josep-m-carbonell or @AFranci , do you have time to switch to the tetgen inside PFEM?

**Comment by RiccardoRossi** [comment]
you need to do the same change as in the MeshingApplication/CMakeLists.txt,

but i will help you with that. It should be a trival change

**Review by maceligueta — APPROVED** [review]

**Comment by maceligueta** [comment]
It is compiling now. I approve it. Can you test it? @josep-m-carbonell @AFranci

**Comment by josep-m-carbonell** [comment]
It compiles yes.

**Comment by RiccardoRossi** [comment]
after this commit, to compile MeshingApplication including tetgen, one should compile by hand the tetgen
and add to the configure.sh the local equivalent to

-DUSE_TETGEN_NONFREE_TPL=ON
-DTETGEN_INCLUDE_DIR="/home/rrossi/Downloads/tetgen1.4.3"
-DTETGEN_LIBRARY_DIR="/home/rrossi/Downloads/tetgen1.4.3" \

**Pull request merged**
