### PR TITLE
[CI] running nightly tests in nightly build

### PR DESCRIPTION
**Pull request by philbucher**
title says all
not 100% sure this works but quite sure :)

### CODE REVIEW

**Comment by philbucher** [comment]
I will merge this now, to get some output over the next two weeks
I added many apps, mainly the most used ones.

for the record, I tried to add the following apps but it was not possible due to failures:
- ContactStructural: Small tests take too long
- SwimmingDEM: small tests crash bcs of dependenices
- ParticleMechanics: Does not compile with Cotire
- HDF5: does not compile bcs of cotire

**Comment by loumalouomega** [comment]
> for the record, I tried to add the following apps but it was not possible due to failures:
> 
>     * ContactStructural: Small tests take too long

Do you mean nightly or just small?, I will move some small to nightly

**Comment by philbucher** [comment]
small, does exactly the same as travis

**Comment by loumalouomega** [comment]
> 
> 
> small, does exactly the same as travis

OK, then I will move several ones to nightly

**Comment by philbucher** [comment]
can you please make a separate PR?
I want to go home now and not again wait for travis :)

**Review by roigcarlo — APPROVED** [review]
Since it works :+1: Good joob!!!

**Comment by loumalouomega** [comment]
> 
> 
> can you please make a separate PR?
> I want to go home now and not again wait for travis :)

Yep :)

**Pull request merged**
