### PR TITLE
[Travis] enable trilinos again

### PR DESCRIPTION
**Pull request by philbucher**
after the things have been moved from the TrilinosApp to the FluidApp, some things get recompiled in Fluid, causing the build to fail
This was working before #5327 
Can you please have a look?

### CODE REVIEW

**Comment by jcotela** [comment]
Looks like the trilinos extension is always linking to the non-cotire version of the base FluidDynamics, so it gets compiled once with cotire in the standard build and again without as a requirement of the trilinos extension...

I'm working on a fix, I'll keep you updated.

**Comment by jcotela** [comment]
Looks like there is something strange going on with the cmake/cotire configuration of the TrilinosExtension (and also the KratosMPICore). In the original "setting" there were separate KratosFluidDynamicsApplication and KratosFluidDynamicsApplication_unity compilation targets.

I pushed a "fix" where the only thing I should be changing is where the cotire compilation is configured (before defining the libraries to link to instead of after). I also define explicitly how to "replace" targets by their cotired equivalents, but I am setting it to the default value, according to the cotire documentation.

The order of instruction matches how the cotire documentation does it in its examples, but I do not understand why this is only a problem here and not in regular applications (Maybe because the TrilinosExtension target is defined *before* the FluidDynamics target, due to the order of cmake includes??).

With the fix, the KratosFluidDynamicsApplication  target is correctly replaced by KratosFluidDynamicsApplication_unity, so travis should be able to finish again.

However, I also noticed that there are separate KratosCore_unity and KratosCore targets in the compilation (!!). I believe that the wrong KratosCore target comes from the KratosMPICore definition, but trying to apply the same fix as for the TrilinosExtension results in many linking errors. @roigcarlo any ideas?

**Comment by philbucher** [comment]
thanks @jcotela for testing
I opened #5780 to check if the MPI-Core triggers the rebuild of the core

**Comment by philbucher** [comment]
So it #5780 I disabled the MPI-Core and [looking at the Travis output](https://travis-ci.org/KratosMultiphysics/Kratos/builds/598109122?utm_source=github_status&utm_medium=notification) one can see that the core is no longer compiled twice!
So this seems to be the reason for the recompilation! Also explains why it works in appveyor but not in Travis :)

Now we know what is the reason, but I don't know how to solve it ...

**Comment by jcotela** [comment]
@philbucher moving the includes for the folder of the "problem" libraries to after their dependencies have been configured seems to do the trick on my machine (that is, not including the mpi folder until the KratosCore target is defined). If it works on travis, I will implement the same approach for the TrilinosExtension, since it looks simpler than playing with the ordering of the cotire commands.

**Comment by philbucher** [comment]
@jcotela now it works!
I will push the fix for the MeshMoving tests, but your change solved the original problem :)

**Comment by philbucher** [comment]
Travis passed in 6 minutes :D

**Comment by jcotela** [comment]
Ok, if this works, it should be good to go. @roigcarlo you may want to review this one, since you know more of the cotire stuff...

**Comment by roigcarlo** [comment]
:+1: I will take a deep look tonight, but if it compiles in a reasonable time I don't see any problem

**Comment by philbucher** [comment]
Compiles faster than ever :)

**Review by jcotela — APPROVED** [review]
Approving since this seems to work and gives us better travis coverage.

**Pull request merged**
