### PR TITLE
[StructuralMechanicsApplication] Fix error detected in #6979

### PR DESCRIPTION
**Pull request by loumalouomega**
@ddiezrod  does this fix the error? I cannot replicate the error

### CODE REVIEW

**Comment by ddiezrod** [comment]
Still same error Im afraid :/

**Comment by ddiezrod** [comment]
@loumalouomega test passes if I a put critical for this line

https://github.com/KratosMultiphysics/Kratos/blob/972ae13fa376f7a752fbd147bf2a35d600ea8f7c/applications/StructuralMechanicsApplication/custom_processes/spr_error_process.cpp#L218

worst case, we can simply leave the critical...

**Comment by loumalouomega** [comment]
> @loumalouomega test passes if I a put critical for this line
> 
> https://github.com/KratosMultiphysics/Kratos/blob/972ae13fa376f7a752fbd147bf2a35d600ea8f7c/applications/StructuralMechanicsApplication/custom_processes/spr_error_process.cpp#L218
> 
> worst case, we can simply leave the critical...

I don't understand..., this is thread safe, it is just calculating the stress...I tried to use const elements, but CalculateOnIntegrationPoints does not work with constant elements, FYI @philbucher

**Comment by philbucher** [comment]
It depends on what the element does in this function 
It might be threadsafe or not...
@loumalouomega did you check that?

**Comment by philbucher** [comment]
> @loumalouomega test passes if I a put critical for this line
> 
> https://github.com/KratosMultiphysics/Kratos/blob/972ae13fa376f7a752fbd147bf2a35d600ea8f7c/applications/StructuralMechanicsApplication/custom_processes/spr_error_process.cpp#L218
> 
> worst case, we can simply leave the critical...

Is it only this line or the next one too?
If only this one I would take a very close look at what the element does for that particular variable

**Comment by ddiezrod** [comment]
@philbucher Yes, I should have stressed that out. Its just this line. Variable is `CAUCHY_STRESS_VECTOR` which has a special treatment in the BaseSolidElement. I have to say that at first sight, I did not find anything wrong.

**Comment by loumalouomega** [comment]
@ddiezrod now?, i don't understand, this is completely thread safe

**Comment by ddiezrod** [comment]
hmm not sorry, I think the error its not there at the end. I fails quite randomly so I got it wrong, :( It seems that problem is related to `RECOVERED_STRESS`. If you comment the lines where its being set, 
https://github.com/KratosMultiphysics/Kratos/blob/b473bc7740e11a1e24d6e01956a1a2f5c5a8ffd7/applications/StructuralMechanicsApplication/custom_processes/spr_error_process.cpp#L120

then everything goes fine (at least I ran the test 50 times without any failure). I tried adding a critical but its still failing...

**Comment by ddiezrod** [comment]
btw that loop is super-expensive: you have something like:
```
for node in nodes:
 for neigh in node.neighbours:
    for node in nodes:
        ....
```
I think its the most expensive loop I've ever seen XD, probably should be refactored...

**Comment by loumalouomega** [comment]
> btw that loop is super-expensive: you have something like:
> 
> ```
> for node in nodes:
>  for neigh in node.neighbours:
>     for node in nodes:
>         ....
> ```
> 
> I think its the most expensive loop I've ever seen XD, probably should be refactored...

I know, there is a TODO there for that reason, but I don't know how to solve it :P

**Comment by loumalouomega** [comment]
Now @ddiezrod ?

**Comment by ddiezrod** [comment]
Well, it seems its fixed (I ran it ~60 times without any error) I am still not sure where the error was, but I would merge this.

**Review by ddiezrod — APPROVED** [review]

**Comment by ddiezrod** [comment]
Thank you very much @loumalouomega !

**Comment by philbucher** [comment]
thx guys!

**Comment by RiccardoRossi** [comment]
> > btw that loop is super-expensive: you have something like:
> > ```
> > for node in nodes:
> >  for neigh in node.neighbours:
> >     for node in nodes:
> >         ....
> > ```
> > 
> > 
> > I think its the most expensive loop I've ever seen XD, probably should be refactored...
> 
> I know, there is a TODO there for that reason, but I don't know how to solve it :P

a loop like this should not be admitted in production code.

what are u trying to do?

**Comment by loumalouomega** [comment]
> what are u trying to do?

Check the neighbor nodes of the neighbor nodes, I need to think about this...

**Pull request merged**
