### PR TITLE
Extend gitignore

### LINKED ISSUE #21: gitignore files generated  by visual studio
Some files generated by Visual Studio during compilation should be added to gitignore:

image

@roigcarlo

### PR DESCRIPTION
**Pull request by roigcarlo**
This fixes #21.

Probably this needs to be extended so it's open to additions

### CODE REVIEW

**Comment by roigcarlo** [comment]
@jginternational Does this work ok on win?

**Comment by maceligueta** [comment]
I just wanted to point out that there are other mechanisms to ignore files and folders. I wrote this in the wiki:
http://kratos-wiki.cimne.upc.edu/index.php/How_to_make_Git_ignore_the_files_resulting_from_a_compilation_without_conflicts_in_.gitignore

**Comment by roigcarlo** [comment]
Thx @maceligueta, I was suggesting the same thing in #21, but some of these may be needed here since we recommend to install kratos in the source dir, so not having it probably is inconsistent.

**Comment by pooyan-dadvand** [comment]
Actually I usually advice the people to install the KratosMultiphysics in the same directory. And I should add that the installation to another directory is somehow buggy in windows.

**Comment by loumalouomega** [comment]
I added *.time

**Comment by roigcarlo** [comment]
If is it ok, can someone approve to merge?

**Comment by maceligueta** [comment]
Forgive my ignorance but... *.time are files that are generated during the compilation?

**Comment by roigcarlo** [comment]
Not quite, but we can put more things apart form the compilation files.
For example, ```*.pyc``` are already there.

But since you say this, @loumalouomega  why ```*.time``` and not ```*.post.bin``` ?

**Comment by maceligueta** [comment]
Or *.mdpa. I guess @loumalouomega has tests inside the application and he need to ignore many files of the standard runs. I have no inconvenient.

**Comment by roigcarlo** [comment]
But ```*.mpda``` need to be there, since there are internal tests/examples relying on it.
Maybe we can add a rule for every application specific output though...

Something in the lines of:

```
# Common Output for every app
*.time

# Specific Only for FooApplication
applications/FooApplication/*.FooWhatever
```

**Comment by maceligueta** [comment]
You are right, *.mdpa will have versioning.

**Review by maceligueta — APPROVED** [review]

**Comment by loumalouomega** [comment]
Right, the *.time is because I use tests to check that I didn't broke anything

**Pull request merged**
