### PR TITLE
Hotfix/malformed elements

### PR DESCRIPTION
**Pull request by roigcarlo**
**Description**

Seems that about 90 elements are still using the old class pointer definition which makes them incorrect if someone tries to use them with an interface which has already been changed (all of them).

This is hard to detect because if obtained from KratosCommponents the base element do have the correct ::Pointer definition, and hence no problems are detected are compile/runtime.

@KratosMultiphysics/technical-committee I would like to confirm that this is right and this is whats happening. (@farrufat-cimne ping, this is probably your compilation problem)

~~This PR is not to be merged**, has been generated automatically and is only testing / discussion purposes.~~
**Edit**: seems we are merging it afterall...

Once we agree this is a problem / not I will make a clean one.

### CODE REVIEW

**Review by loumalouomega — APPROVED** [review]

**Comment by roigcarlo** [comment]
@loumalouomega

> This PR is not to be merged, has been generated automatically and is only testing / discussion purposes.

**Review by philbucher — APPROVED** [review]
thx!

FYI @KlausBSautter

**Review by marcnunezc — APPROVED** [review]

**Comment by philbucher** [comment]
> ~This PR is not to be merged**, has been generated automatically and is only testing / discussion purposes.~
> **Edit**: seems we are merging it afterall...

:smile: :smile: :smile:

**Comment by farrufat-cimne** [comment]
Thanks @roigcarlo, quite sure this will get rid of the make_instrusive issue.

**Pull request merged**
