### PR TITLE
Update test_CompressiblePotentialFlowApplication.py

### PR DESCRIPTION
**Pull request by philbucher**

### CODE REVIEW

**Comment by marcnunezc** [comment]
Sorry for commiting on your branch, in my other comment ( https://github.com/KratosMultiphysics/Kratos/pull/6227#issuecomment-574647915 ), i was referring to  disable only the embedded_circle test. As far as I am concerned this is the test that was causing trobules (still no idea what is causing the issue though :( im not able to reporduce the error in my machine).

If there were more test causing troubles you can revert my commit.

**Comment by inigolcanalejo** [comment]
I think in this PR @philbucher just wanted to check if disabling the python tests removes the error. I dont think he wanted to merge this. The issue with the embedded_circle test is another issue and was already solved in https://github.com/KratosMultiphysics/Kratos/pull/6228

**Comment by marcnunezc** [comment]
Ok sorry! I will let @philbucher decide then.

In any case, I was referring to the issue in the embedded test mentioned here: https://github.com/KratosMultiphysics/Kratos/pull/6168#issuecomment-569416661

Which seems to be an OpenMP issue rather than an import error

**Comment by philbucher** [comment]
no problem, both commits are currently running, lets see

I was checking with @inigolcanalejo and I got (once!) the following error:
~~~
======================================================================
ERROR: test_EmbeddedCircle (potential_flow_test_factory.PotentialFlowTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/philippb/software/Kratos_prod/install/applications/CompressiblePotentialFlowApplication/tests/potential_flow_test_factory.py", line 98, in test_EmbeddedCircle
    self._runTest(settings_file_name)
  File "/home/philippb/software/Kratos_prod/install/applications/CompressiblePotentialFlowApplication/tests/potential_flow_test_factory.py", line 258, in _runTest
    potential_flow_analysis.Run()
  File "/home/philippb/software/Kratos_prod/install/KratosMultiphysics/analysis_stage.py", line 50, in Run
    self.RunSolutionLoop()
  File "/home/philippb/software/Kratos_prod/install/KratosMultiphysics/CompressiblePotentialFlowApplication/potential_flow_analysis.py", line 105, in RunSolutionLoop
    self.InitializeSolutionStep()
  File "/home/philippb/software/Kratos_prod/install/KratosMultiphysics/analysis_stage.py", line 129, in InitializeSolutionStep
    self.ApplyBoundaryConditions() #here the processes are called
  File "/home/philippb/software/Kratos_prod/install/KratosMultiphysics/analysis_stage.py", line 197, in ApplyBoundaryConditions
    process.ExecuteInitializeSolutionStep()
  File "/home/philippb/software/Kratos_prod/install/KratosMultiphysics/CompressiblePotentialFlowApplication/define_embedded_wake_process_2d.py", line 37, in ExecuteInitializeSolutionStep
    CPFApp.DefineEmbeddedWakeProcess(self.main_model_part, self.wake_model_part).Execute()
RuntimeError: Error: the element with Id 13817991322220671538 does not exist in the root model part


in kratos/sources/model_part.cpp:877:void ModelPart::AddElements(const vector<long unsigned int>&, ModelPart::IndexType)
   kratos/sources/model_part.cpp:891:void ModelPart::AddElements(const vector<long unsigned int>&, ModelPart::IndexType)
   /home/philippb/software/Kratos_prod/applications/CompressiblePotentialFlowApplication/custom_processes/define_embedded_wake_process.cpp:42:virtual void DefineEmbeddedWakeProcess::Execute()
~~~

so probably sth fishy is going on somewhere

also here is the valgrind output when running test_CompressiblePotentialFlowApplication.py:
[valgrindout_test_CompressiblePotentialFlowApplication.py.log](https://github.com/KratosMultiphysics/Kratos/files/4065177/valgrindout_test_CompressiblePotentialFlowApplication.py.log)

**Comment by philbucher** [comment]
One of the very early problems I had when I wrote tests that I didn't save sth as a member.
I.e. in the setup-fct I would create a ModelPart, but I didn't save it as `self`
Then the tests failed randomly bcs sometimes the GC of python decided it was time to clean, and sometimes not
Somehow what we experience here could have a similar source, I recommend going through your code

**Comment by philbucher** [comment]
hm still crashes, even with all py-tests disabled :/
@marcnunezc could you instead please disable (commenting I guess works best) also the cpp tests?

**Comment by philbucher** [comment]
> no problem, both commits are currently running, lets see
> 
> I was checking with @inigolcanalejo and I got (once!) the following error:
> 
> ```
> ======================================================================
> ERROR: test_EmbeddedCircle (potential_flow_test_factory.PotentialFlowTests)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/home/philippb/software/Kratos_prod/install/applications/CompressiblePotentialFlowApplication/tests/potential_flow_test_factory.py", line 98, in test_EmbeddedCircle
>     self._runTest(settings_file_name)
>   File "/home/philippb/software/Kratos_prod/install/applications/CompressiblePotentialFlowApplication/tests/potential_flow_test_factory.py", line 258, in _runTest
>     potential_flow_analysis.Run()
>   File "/home/philippb/software/Kratos_prod/install/KratosMultiphysics/analysis_stage.py", line 50, in Run
>     self.RunSolutionLoop()
>   File "/home/philippb/software/Kratos_prod/install/KratosMultiphysics/CompressiblePotentialFlowApplication/potential_flow_analysis.py", line 105, in RunSolutionLoop
>     self.InitializeSolutionStep()
>   File "/home/philippb/software/Kratos_prod/install/KratosMultiphysics/analysis_stage.py", line 129, in InitializeSolutionStep
>     self.ApplyBoundaryConditions() #here the processes are called
>   File "/home/philippb/software/Kratos_prod/install/KratosMultiphysics/analysis_stage.py", line 197, in ApplyBoundaryConditions
>     process.ExecuteInitializeSolutionStep()
>   File "/home/philippb/software/Kratos_prod/install/KratosMultiphysics/CompressiblePotentialFlowApplication/define_embedded_wake_process_2d.py", line 37, in ExecuteInitializeSolutionStep
>     CPFApp.DefineEmbeddedWakeProcess(self.main_model_part, self.wake_model_part).Execute()
> RuntimeError: Error: the element with Id 13817991322220671538 does not exist in the root model part
> 
> 
> in kratos/sources/model_part.cpp:877:void ModelPart::AddElements(const vector<long unsigned int>&, ModelPart::IndexType)
>    kratos/sources/model_part.cpp:891:void ModelPart::AddElements(const vector<long unsigned int>&, ModelPart::IndexType)
>    /home/philippb/software/Kratos_prod/applications/CompressiblePotentialFlowApplication/custom_processes/define_embedded_wake_process.cpp:42:virtual void DefineEmbeddedWakeProcess::Execute()
> ```
> 
> so probably sth fishy is going on somewhere
> 
> also here is the valgrind output when running test_CompressiblePotentialFlowApplication.py:
> [valgrindout_test_CompressiblePotentialFlowApplication.py.log](https://github.com/KratosMultiphysics/Kratos/files/4065177/valgrindout_test_CompressiblePotentialFlowApplication.py.log)

@inigolcanalejo @marcnunezc did you take a look at this test?

**Comment by marcnunezc** [comment]
> > no problem, both commits are currently running, lets see
> > I was checking with @inigolcanalejo and I got (once!) the following error:
> > ```
> > ======================================================================
> > ERROR: test_EmbeddedCircle (potential_flow_test_factory.PotentialFlowTests)
> > ----------------------------------------------------------------------
> > Traceback (most recent call last):
> >   File "/home/philippb/software/Kratos_prod/install/applications/CompressiblePotentialFlowApplication/tests/potential_flow_test_factory.py", line 98, in test_EmbeddedCircle
> >     self._runTest(settings_file_name)
> >   File "/home/philippb/software/Kratos_prod/install/applications/CompressiblePotentialFlowApplication/tests/potential_flow_test_factory.py", line 258, in _runTest
> >     potential_flow_analysis.Run()
> >   File "/home/philippb/software/Kratos_prod/install/KratosMultiphysics/analysis_stage.py", line 50, in Run
> >     self.RunSolutionLoop()
> >   File "/home/philippb/software/Kratos_prod/install/KratosMultiphysics/CompressiblePotentialFlowApplication/potential_flow_analysis.py", line 105, in RunSolutionLoop
> >     self.InitializeSolutionStep()
> >   File "/home/philippb/software/Kratos_prod/install/KratosMultiphysics/analysis_stage.py", line 129, in InitializeSolutionStep
> >     self.ApplyBoundaryConditions() #here the processes are called
> >   File "/home/philippb/software/Kratos_prod/install/KratosMultiphysics/analysis_stage.py", line 197, in ApplyBoundaryConditions
> >     process.ExecuteInitializeSolutionStep()
> >   File "/home/philippb/software/Kratos_prod/install/KratosMultiphysics/CompressiblePotentialFlowApplication/define_embedded_wake_process_2d.py", line 37, in ExecuteInitializeSolutionStep
> >     CPFApp.DefineEmbeddedWakeProcess(self.main_model_part, self.wake_model_part).Execute()
> > RuntimeError: Error: the element with Id 13817991322220671538 does not exist in the root model part
> > 
> > 
> > in kratos/sources/model_part.cpp:877:void ModelPart::AddElements(const vector<long unsigned int>&, ModelPart::IndexType)
> >    kratos/sources/model_part.cpp:891:void ModelPart::AddElements(const vector<long unsigned int>&, ModelPart::IndexType)
> >    /home/philippb/software/Kratos_prod/applications/CompressiblePotentialFlowApplication/custom_processes/define_embedded_wake_process.cpp:42:virtual void DefineEmbeddedWakeProcess::Execute()
> > ```
> > 
> > 
> > so probably sth fishy is going on somewhere
> > also here is the valgrind output when running test_CompressiblePotentialFlowApplication.py:
> > [valgrindout_test_CompressiblePotentialFlowApplication.py.log](https://github.com/KratosMultiphysics/Kratos/files/4065177/valgrindout_test_CompressiblePotentialFlowApplication.py.log)
> 
> @inigolcanalejo @marcnunezc did you take a look at this test?

Hi! I took a quick look but did not see an obvious error or race condition. I will try to carefully check it with valgrind asap.

**Pull request closed without merging**
