### PR TITLE
[Core] Adding support to Prism3D6 to VtkOutput

### PR DESCRIPTION
**Pull request by loumalouomega**
Adding support to Prism3D6 to VtkOutput. Additionally adding some static conversion to avoid "pedantic" warnings and separating methods with code separators

### CODE REVIEW

**Review by philbucher — DISMISSED** [review]
looks good to me

Can you add a small test?

**Comment by loumalouomega** [comment]
> looks good to me
> 
> Can you add a small test?

OK

**Comment by loumalouomega** [comment]
@philbucher I added a 3D test

**Review by philbucher — APPROVED** [review]
thanks

**Pull request merged**
