### PR TITLE
Deprecate Python2 in CoSimulationApplication and MeshMovingApplication

### PR DESCRIPTION
**Pull request by matekelemen**
**Description**
Changes to deprecate python2 in CoSimulationApplication and MeshMovingApplication.

**Changelog**
Remove __future__ imports and arguments from super() calls from CoSimulationApplication and MeshMovingApplication

### CODE REVIEW

**Review by philbucher — COMMENTED** [review]
perfect thanks!

**Review by philbucher — APPROVED** [review]

**Comment by philbucher** [comment]
@matekelemen can you please check if you can merge this PR? I.e. are you able to click the "Merge pull request" button?
I think you cannot since you are not a member of the repo, but I would like to know for sure
After I know this I will merge the PR

**Comment by matekelemen** [comment]
No, it says I need write access to the repo.

**Comment by philbucher** [comment]
cool, thx for confirming

**Pull request merged**
