### PR TITLE
Fixing porting shallow water application to Pybind

### PR DESCRIPTION
**Pull request by miguelmaso**
I have realized that in PR #1724 I made a mistake.
The bug is fixed removing the unused custom strategies.
I have also added a first test to my application in PR #1801

### CODE REVIEW

**Review by RiccardoRossi — COMMENTED** [review]
you also need changing the CMakeLists.txt

**Comment by miguelmaso** [comment]
The file is not in CMakeLists.txt. This is the mistake I did

**Comment by RiccardoRossi** [comment]
Hi @miguelmaso the point is that you also need to change the CMakeLists.txt of your application, otherwise it will not compile with pybind.

that file is not included here

**Comment by miguelmaso** [comment]
I am deleting a file which is not in CMakeLists...

**Review by RiccardoRossi — APPROVED** [review]

**Pull request merged**
