### PR TITLE
[Solid] Solid Strategies to SolversApp

### PR DESCRIPTION
**Pull request by josep-m-carbonell**
New SolversApplication, moving custom Strategies and Schemes from SolidMechanicsApplication.

### CODE REVIEW

**Comment by josep-m-carbonell** [comment]
@lluis-mv, well there are no tests yet

**Comment by lluis-mv** [comment]
[yes, I noticed that] but by running python3 test_SolversApplication.py it raised an error due to an improper addition of tests. Now it runs correctly.

**Review by lluis-mv — DISMISSED** [review]
It looks cool to me

**Review by maceligueta — CHANGES_REQUESTED** [review]
@KratosMultiphysics/technical-committee is reviewing this and comments will be posted briefly.

**Comment by maceligueta** [comment]
Dear @josep-m-carbonell and @lluis-mv ,
After taking a look at this PR, the @KratosMultiphysics/technical-committee has discussed for some time about requesting changes or not. The discussion took us to the very roots of the 'Kratos Multiphysics' concept, to the 'Open Source' concept, to the 'fork' concept, to the 'repository' concept , to the 'collaborative work' concept and to the idea of a Technical Committee . Our understanding of these concepts led us to summarize some ideas that we thought were already clear for everyone:

1. Kratos Multiphysics is a multiphysics code, intended for including couplings (though not only for couplings).
2. Kratos Multiphysics is a repository of know-how, and a set of tools to be used in engineering analyses.
3. The Kratos repository is a source code maintained by a community, which makes efforts to improve it and enlarge it. Usually the work made by one developer is used by other developers (one of the advantages of sharing a single code...)
4. The community is heterogeneous and can reach conficts, where the Technical Committee tries to push for the best solution.
5. Without a certain discipline, chaos can easily reign in a repository, as we have seen in the past for Kratos itself. This is something that you (@josep-m-carbonell) complain frequently in informal or formal conversations.
6. Of course, being an Open Source code, developers enjoy a certain freedom. But logically this freedom has limits, as in every aspect of life.

Concerning this pull request, the @KratosMultiphysics/technical-committee detected at least two major problems:

- The addition of libraries that can be located in External Solvers Application in a different application (Solvers Appplication), namely SuperLU and Feast.
- Renamig of files and changing authorship with no further reference to the original author: https://github.com/KratosMultiphysics/Kratos/pull/4034/files#diff-b42ee7864ffc90b2b2c7f57b8ae6b915

The first problem goes directly against points 1, 3 and 5: 
In case of future couplings, it might happen that, in the same run, some applications use one SuperLU instance while others use another instance. The set of tools gets mixed up: the same linear solver (which is not coded by the Kratos developers) is repeated in different applications. Apart from the fact that is chaotic in terms of order, consumes more memory when coupling. The general aspect of this PR is that of a 'fork' which is coded in the same repository, inducing internal divergence in Kratos, which can be acceptable in terms of science, but not _to this extent_ in terms of coding.
Many developers wrote their opinion in this direction in PR #4001, which was closed recently.
The @KratosMultiphysics/technical-committee does not consider acceptable duplicating external libraries, as it is a known error that happened in the past in Kratos and does not promote collaborative sinergy.

The second problem is more a lack of etiquette (but probably illegal in terms of Law). @KratosMultiphysics/technical-committee thinks that the original author should be referenced.

Maybe I forgot something, so if any other member of the @KratosMultiphysics/technical-committee wants to add something, go ahead.

@josep-m-carbonell and @lluis-mv , we can set up a meeting if you want to discuss this in person, as it might take long if we write all our replies through GitHub.

**Comment by josep-m-carbonell** [comment]
Thank you.

**Pull request closed without merging**
