### PR TITLE
[Structural] improving efficiency of DampingMatrix calculation

### PR DESCRIPTION
**Pull request by philbucher**
**Description**
Motivated by looking at #8426 I took another look at my implementation of the computation of the DampingMatrix. I noticed that I create too many temporary matrices which can be avoided.
Now the code creates the least amount of temporaries possible, on average half of what it did before :)

Since the same is done in MPM I am planning to move this function to the Core in a followup PR

FYI @peterjwilson

### CODE REVIEW

**Comment by AlejandroCornejo** [comment]
looks nice! Have you thought about the use of the initial stiffness matrix issue? :)

**Comment by philbucher** [comment]
> looks nice! Have you thought about the use of the initial stiffness matrix issue? :)

thought about: yes
solutions available: yes
are those solutions efficient? No :/

The basic issue is that storing matrices is inefficient no matter what we do
Example with storing the initial damping matrix in the element:
Quad Shell Elements with 24 dofs. Each matrix has 24*24*8byte storage => 4.5KB storage per element. Sounds like little but if you have 1 Million elements (which is a large but not uncommon number) that makes ~4,3 **GB** of additional memory! I could imagine that this is more than the entire system matrix has since this one is sparse (never measured it though)

Another way would be to have a sparse damping matrix in the initial state but that would require large changes in the Strategy, B&S and Scheme since Kratos has only one "system matrix" and not multiple

I think the "easiest" solution would be to add the storing of the initial damping matrix in the implicit_time_scheme and then assemble it instead of recomputing it. That has the memory overhead price though. Additionally we need to be able to associate the elements with probably the Id so we also need an `unordererd_map<Id, InitialDampingMatrix>`

**Comment by philbucher** [comment]
approval anyone?
I would like to move it to the Core in a followup PR so that it can also be used in other apps like MPM

**Review by AlejandroCornejo — APPROVED** [review]

**Comment by philbucher** [comment]
thx

**Pull request merged**
