### PR TITLE
[Core] Made Condition::GetIntegrationMethod const

### PR DESCRIPTION
**Pull request by EduardGomezEscandell**
This PR changes the function signature from
```c++
virtual IntegrationMethod Condition::GetIntegrationMethod();
```
to
```c++
virtual IntegrationMethod Condition::GetIntegrationMethod() const;
```
**Deprecation warning**
This breaks the API so a deprecation warning has been added for some time (See https://github.com/KratosMultiphysics/Kratos/pull/9789).

@KratosMultiphysics/all :
- This PR will be merged on April 19th, 2022.
- Applications in the CI run have been adapted.
- Any other applications and forks will break.

**🆕 Changelog**
- Makes GetIntegrationMethod method of Condition const
- Changed overrides to const

**How to fix my condition?**
If this change breaks any of your `Condition`s, simply add the const in your `GetIntegrationMethod` declaration in the `.h` header file:
```diff
- IntegrationMethod GetIntegrationMethod() override
+ IntegrationMethod GetIntegrationMethod() const override
```
You will also need to modify the method definition in the `cpp` source file if it is separate from the declaration:
```diff
- IntegrationMethod YourCondition::GetIntegrationMethod() {
+ IntegrationMethod YourCondition::GetIntegrationMethod() const {
```

### CODE REVIEW

**Comment by AlejandroCornejo** [comment]
@loumalouomega I've seen some of your implementations. Just for you to know

**Comment by loumalouomega** [comment]
> @loumalouomega I've seen some of your implementations. Just for you to know

I don't understand. May I have written wrong code in the past. Anyway I was just asking

**Review by roigcarlo — APPROVED** [review]
Approving on behalf of the https://github.com/orgs/KratosMultiphysics/teams/technical-committee.

Please merge the other one first.

**Comment by EduardGomezEscandell** [comment]
@KratosMultiphysics/all 
A reminder that this PR will be merged right after easter. You will be affected if:
- Your application is not in the CI.
- You have your own fork.

AND

- You have overloaded `Condition::GetIntegrationMethod`

**Pull request merged**
