### PR TITLE
Reducing dependencies of PfemFluid on SolidMechanicsApplication

### PR DESCRIPTION
**Pull request by AFranci**

### CODE REVIEW

**Comment by maceligueta** [comment]
Hello @AFranci . There is no description of this PR, but I think I more or less understood the main changes. It would be nice to have a description, like the other pull requests.
It seems you are copying the file `transfer_entities_between_pfem_model_parts_process.hpp ` from SolidMechanics app to DelaunayMeshing app, so there is no need to import the SolidMechanics app.
I think that copying code is always harmful. Can we avoid this copy? Can we _move_ the file and modify the PfemSolidMechanics app accordingly? Or is it being used by SolidMechanics app? I can't really find how this process is called...

**Comment by AFranci** [comment]
The aim of this pull request is to start to cancel the dependencies of the PfemFluidApplication on the SolidMechanicsApplication (and ConstitutiveModelApplication). The transfer_entities_between_pfem_model_parts_process.hpp has been copied and not moved because there may be people using the SolidMechanics (it is called in model_manager.py) but not compiling the DelaunayApplication.

**Comment by loumalouomega** [comment]
There is a process in the core for transfering entities. It is called
something like fast_transfer_enti... Or something similar.

**Comment by maceligueta** [comment]
It must be this file: https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/processes/fast_transfer_between_model_parts_process.cpp
I think that using this process would be a lot better. It is really weird to have two processes doing so similar tasks. 
I don't really know if it's possible, but people from SolidMechanics application should take a look at it, too.

**Comment by loumalouomega** [comment]
The branch is still open

**Pull request closed without merging**
