### PR TITLE
[Shallow] Printing the topography

### PR DESCRIPTION
**Pull request by miguelmaso**
Shallow water equations are a 2D reduced model, however, the user would like to see the how the "volume" looks like.

In this PR there is a derived output process which prints the mesh two times:
- The first time prints the computational mesh with the results
- The second time prints the same mesh with an offset which represents the topography

In the picture is shown a simple test: a linear wave on a parabolic bowl. This custom output is printing two meshes in order to see at the same time the bathymetry and the free surface.

Captura de pantalla de 2019-04-24 17-37-41

I have found a trouble when deriving a private method of **GiDOutputProcess**. This is the easiest workaround I have found:

https://github.com/KratosMultiphysics/Kratos/blob/880bbf796ad1d06e5eedae4e934be313557c549e/applications/ShallowWaterApplication/python_scripts/shallow_water_gid_output_process.py#L82

### CODE REVIEW

**Comment by rubenzorrilla** [comment]
I had a similar problem in the past to postprocess the skin when solving embedded problems. What I did is to create a visualization model part that distinguishes the GiD layers using the properties ids. (I guess that you did something similar). Then, I create a unique instance of the GiD output that prints such model part, so there is no necessity to derive a new GiD output process. Why do you need to derive it?

**Comment by miguelmaso** [comment]
I did it on another branch, but it's quite sophisticated. On my visualization model part I need to duplicate all the nodes and elements to build the topographic layer. The main drawback of this visualization model part are the duplicated nodes: in case the topography changes due to erosion, the duplicated nodes won't be updated since they have another nodal database.
This derived GiD output process prints the mesh twice with an offset and with dummy properties. I find it easier than the visualization model part.

**Comment by rubenzorrilla** [comment]
OK! I think that now I get your point. Your case it different than mine. How you did implement this in another branch? I would have done it using an unordered map which pair entry is the duplicated node / element id and a pointer to the "origin" node / element. This is not too complex and would allow you to have different ids. and to exchange the info between databases when looping the origin model part. This information exchange and erosion modification should be done before the print of the GiDoutput.

My point is that I'd rather keep a unique output utility as much as possible. Now you want to print in GiD but in the future it might be needed to use another output format (e.g. vtk) so this would imply to derive a new vtk output utility, while a process that create a visualization model part can be used with any output utility, or ever to do other operations.

**Comment by miguelmaso** [comment]
[branch with possible output](https://github.com/KratosMultiphysics/Kratos/compare/shallow/nodes-renumbering)

Having a visualization and a computing model part would be the most versatile solution. But actually I have a big headache with the ids: the current implementation of pfem2 is renumbering the nodes. A new implementation of pfem2 is in my todo list...

**Comment by miguelmaso** [comment]
Does vtk support repeated ids?

**Comment by rubenzorrilla** [comment]
> [branch with possible output](https://github.com/KratosMultiphysics/Kratos/compare/shallow/nodes-renumbering)
> 
> Having a visualization and a computing model part would be the most versatile solution. But actually I have a big headache with the ids: the current implementation of pfem2 is renumbering the nodes. A new implementation of pfem2 is in my todo list...

Oh... I wasn't aware of this... This makes things much more complicated since it would be needed to reconstruct it each time the nodes are renumbered.

**Comment by rubenzorrilla** [comment]
> Does vtk support repeated ids?

I guess it doesn't... but maybe @adityaghantasala or @philbucher can reliably answer to this question.

**Comment by philbucher** [comment]
two comments, since I am not entirely sure what your algorithm is doing/what you want to achieve
- I would say it can handle repeated IDs since it needs to creates its own ids for vtk: https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/input_output/vtk_output.cpp#L190-L196
- It is possible to display the same data multiple times in Paraview, i.e. it loads each dataset separately which means that they can have repeated ids. E.g. for FSI you can load both Fluid&Structure independent of the numbering

**Comment by miguelmaso** [comment]
> two comments, since I am not entirely sure what your algorithm is doing/what you want to achieve
> 
>     * I would say it can handle repeated IDs since it needs to creates its own ids for vtk: https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/input_output/vtk_output.cpp#L190-L196
> 
>     * It is possible to display the same data multiple times in Paraview, i.e. it loads each dataset separately which means that they can have repeated ids. E.g. for FSI you can load both Fluid&Structure independent of the numbering

thanks for the comments, they are very useful. I was doing a renumbering on an experimental branch

**Comment by miguelmaso** [comment]
> I had a similar problem in the past to postprocess the skin when solving embedded problems. What I did is to create a visualization model part that distinguishes the GiD layers using the properties ids. (I guess that you did something similar). Then, I create a unique instance of the GiD output that prints such model part, so there is no necessity to derive a new GiD output process. Why do you need to derive it?

Are you creating that visualization model part on the python solver?

**Comment by rubenzorrilla** [comment]
> > I had a similar problem in the past to postprocess the skin when solving embedded problems. What I did is to create a visualization model part that distinguishes the GiD layers using the properties ids. (I guess that you did something similar). Then, I create a unique instance of the GiD output that prints such model part, so there is no necessity to derive a new GiD output process. Why do you need to derive it?
> 
> Are you creating that visualization model part on the python solver?

I create it in the Python constructor of the process.

**Pull request closed without merging**
