### PR TITLE
[Core] Revert pure regex solution in kratos/utilities/function_parser_utility.cpp

### LINKED ISSUE #10077: Reading out of bounds in function_parser_utility
**Description**
Accessing element -1 of a string

**Scope**
If the expression string starts with 'x', then we reach line 38 with `i=0`.
https://github.com/KratosMultiphysics/Kratos/blob/fc2e6d1b32d98dbbedb06b244eb81deedd1ad30b/kratos/utilities/function_parser_utility.cpp#L28-L46
Then we access element `MAX_LONG -1`.
Testing it, I've seen that:
- With `libstdc++` (GNU's standard library implementation), this is understood as reading the `\0` sentinel, so no issue. [This reduced example](https://godbolt.org/z/scW1qTPW7) shows it reading `\0`.
- With `libc++` (LLVM's standard library), this is understood as a good old read outside limits, hence undefined behaviour. [This reduced example](https://godbolt.org/z/Ybvz58oaT) shows the sanitizer complaining and reading `\20`, some random ASCII character.

I haven't tested with Microsoft's implementation (Compiler explorer doesn't allow for running the minimal example either).

**To Reproduce**
This piece of code runs on Centos only, so it can be quite niche. Furthermore, it seems that with gcc it won't break. But it is still undefined behaviour.

**Expected behavior**
No illegal memory accessing.

### PR DESCRIPTION
**Pull request by loumalouomega**
**📝 Description**

Revert pure regex solution in kratos/utilities/function_parser_utility.cpp

**🆕 Changelog**

- [Revert pure regex solution in kratos/utilities/function_parser_utility.cpp](https://github.com/KratosMultiphysics/Kratos/pull/10251/commits/970623ac1d63b05789ea95809c6df961196b77a9)

### CODE REVIEW

**Comment by EduardGomezEscandell** [comment]
Can we add tests to validate it? I had these in the deprecated branch:

```c++
 // kratos/tests/cpp_tests/utilities/test_function_parser_utility.cpp:70
    {
        auto fun = GenericFunctionUtility("2 + 0xB0B0");
        KRATOS_CHECK_IS_FALSE(fun.DependsOnSpace());
    }
    {
        auto fun = GenericFunctionUtility("3*y");
        KRATOS_CHECK(fun.DependsOnSpace());
    }
    {
        auto fun = GenericFunctionUtility("Z");
        KRATOS_CHECK(fun.DependsOnSpace());
    }
    {
        auto fun = GenericFunctionUtility("x + 0x34321");
        KRATOS_CHECK(fun.DependsOnSpace());
    }
```
First and last ones are the most relevant.

**Comment by loumalouomega** [comment]
> Can we add tests to validate it? I had these in the deprecated branch:
> 
> ```c++
>  // kratos/tests/cpp_tests/utilities/test_function_parser_utility.cpp:70
>     {
>         auto fun = GenericFunctionUtility("2 + 0xB0B0");
>         KRATOS_CHECK_IS_FALSE(fun.DependsOnSpace());
>     }
>     {
>         auto fun = GenericFunctionUtility("3*y");
>         KRATOS_CHECK(fun.DependsOnSpace());
>     }
>     {
>         auto fun = GenericFunctionUtility("Z");
>         KRATOS_CHECK(fun.DependsOnSpace());
>     }
>     {
>         auto fun = GenericFunctionUtility("x + 0x34321");
>         KRATOS_CHECK(fun.DependsOnSpace());
>     }
> ```
> 
> First and last ones are the most relevant.

You can add it yourself. A priori there are already tests... and @philbucher removed an old Spanish Easter egg that I put with a song of Alaska :(

**Comment by EduardGomezEscandell** [comment]
Ok I'll do that later. Current tests don't check for hex numbers (see https://github.com/KratosMultiphysics/Kratos/issues/10041), hence why I said it.

**Comment by loumalouomega** [comment]
> Ok I'll do that later. Current tests don't check for hex numbers (see #10041), hence why I said it.

Okay, adding now

**Comment by loumalouomega** [comment]
@EduardGomezEscandell look like it works

**Review by EduardGomezEscandell — APPROVED** [review]
Great!

**Pull request merged**
