### PR TITLE
[CI] adding ParticleMechanics

### PR DESCRIPTION
**Pull request by philbucher**
lets see...

### CODE REVIEW

**Comment by philbucher** [comment]
@KratosMultiphysics/mpm can you please fix the errors? Then from my side this can go in

**Review by bodhinandach — COMMENTED** [review]
Thanks, @philbucher. I think @tteschemacher and @PeterJosephWilson are on it. Can we push it to this branch too?

**Comment by philbucher** [comment]
Up to you, you can either push to this branch or make separate PRs

**Comment by philbucher** [comment]
can we delete this branch?

**Pull request merged**
