### PR TITLE
[Mapping] python mapper wrappers

### PR DESCRIPTION
**Pull request by philbucher**
Improving the py-mapper factory

The goal is to provide a unified interface for other mappers (e.g. the ones of Empire or the one in the core/ the FSIApp). Furthermore it simplifies the creation of MPI-mappers (automatic now, this is not possible from C++)

The next steps are to use this in the CoSimApp and do the implementation of the empire-mappers

### CODE REVIEW

**Comment by jcotela** [comment]
Two questions for the review:
1. Why not derive the EmpireMapper python class directly from the C++ Mapper class? (I think this is what we do for processes)
2. What exactly can you not do from C++ (regarding selection of MPI variants)? It would be helpful to know the limitations and either expand the current interface or keep them in mind as a design requirement for the eventual generic factories.

**Comment by philbucher** [comment]
Thx for the fast review

1 makes sense, hadn’t thought abt that, thx. Will change it. Not sure how to handle the pure virtual functions but I will see

2 the mapper is templated with the space, hence same mechanism/problem as with the other classes that have this template

**Comment by philbucher** [comment]
I tried to make it derive from the c++ mapper but it is too much effort, so I would leave it as is.
The problem is basically the pure virtual functions. In order to treat them properly I would have to do some tricks, and I would prefer not to. After all the py-wrappers are not forever, just until Kratos itself has more Mappers.

**Review by jcotela — APPROVED** [review]
:+1: looks good to me. Thanks for giving a try to the base class issue.

**Comment by philbucher** [comment]
Thanks

**Pull request merged**
