### PR TITLE
Fix README and clean some application folders

### PR DESCRIPTION
**Pull request by FabienPean**
Hi please take a look at this minor PR. This PR includes:
* Fix some typo and style in the readme
* Remove undesired project files from the git repository
Best Regards, Fabien

### CODE REVIEW

**Review by RiccardoRossi — CHANGES_REQUESTED** [review]
Hi,
     the "project" files should not be committed.
i am referring specifically to:
.depend
.project
.config
.creator
.files
.includes

**Review by RiccardoRossi — APPROVED** [review]

**Comment by RiccardoRossi** [comment]
sorry i understood it wrong. You already removed the files. My bad...(approving)

**Comment by RiccardoRossi** [comment]
Dear Fabien, 
     You should be the one to click on merge for your commits once they are accepted.

I have no problem of doing it for you if you prefer,however the custom is as I am saying

Cheers
Riccardo

**Comment by FabienPean** [comment]
Dear Riccardo, 
As a simple user, I do not have write privileges, and therefore cannot merge it myself. It is up to one of the kratos developers to do it.

Cheers,
Fabien

**Comment by RiccardoRossi** [comment]
Hi Fabien

i thought you were allowed to do it.

sorry for the noise then...
Riccardo

<http://www.cimne.com/>

**Pull request merged**
