### PR TITLE
[Core] Add 2D Variable Macros

### PR DESCRIPTION
**Pull request by tteschemacher**
Hi all!

**Description**
Adds the macro which allows 2D variables, which are similar as the 3d variables.

It can be used for local parameters, or collections. Thus, we went for _1 and _2 instead of _U/_V or _X/_Y.

Thank you for the implementation @rath3t (Alexander Müller from IBB in Stuttgart).

Thanks for the review!

**Changelog**
- Added macros name##_1 and name##_2

### CODE REVIEW

**Comment by loumalouomega** [comment]
The only problem I see is that many algorithms assume that the default array is 3D, so it won't work

**Comment by tteschemacher** [comment]
> The only problem I see is that many algorithms assume that the default array is 3D, so it won't work

It is more for formulations which requires variables with 2 components only. Like e.g. shells, but also many other procedures will profit from this as part of an optimization. Nevertheless, I agree that this is not a 2D - 3D working space issue.

**Comment by loumalouomega** [comment]
> > The only problem I see is that many algorithms assume that the default array is 3D, so it won't work
> 
> It is more for formulations which requires variables with 2 components only. Like e.g. shells, but also many other procedures will profit from this as part of an optimization. Nevertheless, I agree that this is not a 2D - 3D working space issue.

Just saying

**Comment by philbucher** [comment]
Why 1/2 and not X/Y?

**Comment by rath3t** [comment]
> Why 1/2 and not X/Y?

For our use case #7384 this would be two restrictive since a 2D plane does not necessarily align with the X,Y-plane when it is embedded into X,Y,Z-3D space. 

The rotational degrees of freedom change their direction in every iteration and are therefore not aligned with X,Y.

On the other hand we can just ignore this fact and think about X,Y as parameters for a local plane which do not correlate with the X,Y,Z embedding space.
This can be misleading since the user may assume that the degrees of freedom do have a relation to the embedding space.

**Comment by RiccardoRossi** [comment]
normwlly we start in 0,

so wouldn t it be better *_0 *_1 ?

**Comment by rath3t** [comment]
Therefore, the option are
X,Y which are the most consistent one to the 3D case but not the most generic one
_1,_2 which i thing can be neglected due to
> normwlly we start in 0, so wouldn t it be better *_0 *_1 ?

_0,_1 does make more sense in my opinion

**Comment by tteschemacher** [comment]
I know that for many applications this is not the most convenient way to name it. However, to align with the existing naming I renamed it to X and Y. Now at least it is consistent throughout the variables.

**Comment by RiccardoRossi** [comment]
guys, actually it was a specific design decision that 2D would have to be treated as a special case of 3D.

i will block because of this

**Review by RiccardoRossi — CHANGES_REQUESTED** [review]
2D variables were avoided by design decision

**Comment by philbucher** [comment]
@RiccardoRossi can you explain a bit more in detail?

I am asking bcs we also have array 4, 6, 9 which are hardly ever used (and could have been easily manually without the macros)

The 2D vars however are a very useful tool for the CAD/IGA stuffs which we strongly integrate in the Core

**Comment by rubenzorrilla** [comment]
In this I tend to agree Riccardo. Misuses of the 2D variables may arise outside the IGA context. Note that the code designed for 3D variables wouldn't be compatible with 2D ones. In this regard I don't think it is the same as 4, 6 and 9 component variables. Taking the `DISPLACEMENT`as example, it makes no sense to have a 4 components displacement, however you may have 2 and 3 components one...

**Comment by tteschemacher** [comment]
Beautiful...

Many variables have 2 components. It starts from shears, to also parameters like raleigh alpha or beta and as in my scenario local tangents and local coordinates and much more. It is possible to define them with separate variables each time or with defining it like shown, here. This is not a reduced dimension this is just a variable for different types. It is also not IGA only.

Now the thing is, all variables end with X, Y, Z even though that the tensors would be never called like this. They're always 11, 12, 22 or similar. If you think that with 1 and 2 it is better I am happy with that, otherwise to make it more consistent I chose X and Y.

**Comment by tteschemacher** [comment]
I still have hopes to convince you guys ;). I changed it back to 1/2. This would remove the first confusion like this it is not 2D like X/Y but it is component wise. 

If you think it would be more convenient we could also rename it to 2_COMPONENT_VARIABLE or something like this. What do you think about this @RiccardoRossi ?

The thing is, I pretty much need that one. If I want to use the variable as a dof, I cannot just define an array_1d. Going always for 3D is less efficient, probably not even too much but it is also not very beautiful. Also abusing ROTATION for every second type of dofs is more ugly than having 2D and 3D.

**Comment by tteschemacher** [comment]
Closing this PR as it seems not wanted to add 2D variable macros at this stage.

**Pull request closed without merging**
