### PR TITLE
[Hotfix][Core] Fixing the trait size to avoid overflow

### PR DESCRIPTION
**Pull request by pooyan-dadvand**
Fixes the overflow causes by #4002

### CODE REVIEW

**Review by jcotela — APPROVED** [review]
The warnings are gone. I have also checked that tests pass, but they also did with the previous version, so that is not saying much.

**Comment by philbucher** [comment]
what was the problem?

**Comment by pooyan-dadvand** [comment]
> The warnings are gone. I have also checked that tests pass, but they also did with the previous version, so that is not saying much.

Thanks for checking it. In fact, I could not find a way to make a test for it. We should rely on CLang warning then.

**Comment by pooyan-dadvand** [comment]
> what was the problem?

That I put 3 bits for the type of the Dof variable (if is variable or component of array3, array6, etc.) and results that meanwhile there was a new type making the total number 5 types overflowing the type trait.

**Pull request merged**
