### PR TITLE
[LinearSolversApp][EigensystemSolver] Change default MKL solver from EigenPardisoLDLTSolver to EigenPardisoLUSolver

### PR DESCRIPTION
**Pull request by emiroglu**
**Description**
This PR replaces the default linear solver to EigenPardisoLUSolver. EigenPardisoLDLTSolver solver cannot handle unsymmetric matrices. For robustness purpose it makes sense to use EigenPardisoLUSolver.

**Changelog**
- `eigensystem_solver.h`

### CODE REVIEW

**Review by oberbichler — APPROVED** [review]
Makes sense as a general solution 👍

**Comment by philbucher** [comment]
is this one faster?

**Comment by armingeiser** [comment]
No it will be (slightly) slower in general as it does not assume the matrix to be Symmetric Positive Definite.

**Comment by philbucher** [comment]
maybe makes sense then to make it selectable? (I know there is an issue) => I mean only among the solvers in the LinearSolversApp
It is already quite slow :sweat_smile:

**Comment by armingeiser** [comment]
Ev. with a setting like `"symmetric_positive_definite_system_matrix": false` as a default and it can be switched on if desired. 
So we have the robustness and if someone wants speed its possible to switch solver. 
The setting would not do anything without MKL. 

But ev. we should see first how much of a difference it even makes.

**Comment by philbucher** [comment]
@emiroglu can you test the difference with one of your models?
I will also do that (please wait with merging)

If the difference is small then I would not bother with a new setting (that I will have forgotten the meaning of in two weeks ... :) )

**Comment by oberbichler** [comment]
[About the difference](https://github.com/KratosMultiphysics/Kratos/pull/1132#issuecomment-349960185). In this case the linear solve is just a part of the computation so I would expect the influence is even smaller.

Selection by the json would be nice but I would put it into a separate PR.

**Comment by emiroglu** [comment]
the thing is `pardiso_ldlt` does not work at all in my case. so either it should be like this or optional to use `pardiso_lu`. otherwise, i will have to start diverging

my case is as follows:
i have a model with volume, shell, truss elements. i do an initial static nonlinear analysis under some loading to update the system matrices. then at this equilibrium state i do an eigenvalue analysis. this is something called "operational eigenvalues" of the system, which corresponds to the actual eigenfrequencies of the system under the operational conditions. so this is actually the correct way of computing the eigenfrequencies. with the current implementation of shells the system will almost always be unsymmetric so either `pardiso_lu` or `eigen_lu` is suitable. on the other hand `eigen_lu` is not able to deal with big systems with a reasonable RAM size. then it is again a blocker...

@oberbichler already took a look at the stiffness matrix for my case and it is unsymmetric. 
image

**Comment by emiroglu** [comment]
just wanted to mention #8097 :)

**Comment by philbucher** [comment]
I tested with main main model and it is indeed a diff (aka slower) of ~5%

Not sure how to proceed.
For me we can merge this and address the selection of different solvers in a followup PR (would be nice if @emiroglu could push this ;) )

**Comment by oberbichler** [comment]
In my opinion it makes sense to merge.
- Kratos does not guarantee to produce symmetric matrices
- with LDLT the results are useless
- with LU the result looks good (we compared with scipy)
- Pardiso is still the fastest LU solver

Of course it would make sense to
- Add an option for selecting the solver
- Add an optional check for symmetry
- Understand how non-symmetric matrices are affecting the results (btw: does somebody know why this shell produces asymmetric stiffness?)

But in a first step the most important thing is to get some usable results

**Comment by RiccardoRossi** [comment]
we could add an option "automatic" that xhecks for symmetry and decides

**Comment by emiroglu** [comment]
If the consensus ok is, I would like to merge this and discuss the further implementation in detail under #8097

**Review by philbucher — APPROVED** [review]

**Comment by philbucher** [comment]
@emiroglu this seems to have broken the nightly tests:
~~~
FAIL: test_harmonic_mdpa_input (test_harmonic_analysis.HarmonicAnalysisTestsWithHDF5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/__w/Kratos/Kratos/bin/Release/applications/StructuralMechanicsApplication/tests/test_harmonic_analysis.py", line 215, in test_harmonic_mdpa_input
    test.Run()
  File "/__w/Kratos/Kratos/bin/Release/KratosMultiphysics/analysis_stage.py", line 48, in Run
    self.RunSolutionLoop()
  File "/__w/Kratos/Kratos/bin/Release/KratosMultiphysics/analysis_stage.py", line 67, in RunSolutionLoop
    self.FinalizeSolutionStep()
  File "/__w/Kratos/Kratos/bin/Release/KratosMultiphysics/analysis_stage.py", line 149, in FinalizeSolutionStep
    process.ExecuteFinalizeSolutionStep()
  File "/__w/Kratos/Kratos/bin/Release/KratosMultiphysics/StructuralMechanicsApplication/check_eigenvalues_process.py", line 38, in ExecuteFinalizeSolutionStep
    self.assertAlmostEqual(evs[0],evs[1],5)
AssertionError: 148225.7497280745 != 145801.00267211083 within 5 places (2424.7470559636713 difference)
~~~

can you please have a look?

**Comment by emiroglu** [comment]
The result of the eigenvalue analysis is not exactly the same when a different linear solver is used. We actually checked this with @oberbichler . Either the reference values [here](https://github.com/KratosMultiphysics/Kratos/blob/f2857667dc94b60a99ee532cea5b86c39f6708a8/applications/StructuralMechanicsApplication/tests/harmonic_analysis_test/harmonic_analysis_test_parameters.json#L102) have to be recomputed or the default MKL linear solver has to be set back to the original.

**Comment by RiccardoRossi** [comment]
Well, if there is a doibt about symmetry then LU should be considered as
the reference.

just one question: are u applying a pressure load?

**Comment by emiroglu** [comment]
Just something that I remembered; @oberbichler also mentioned that the algorithm implemented in `eigensystem_solver` is designed for symmetric matrices. So there are in general some doubts there.
@RiccardoRossi I observed the unsymmetry on a case without any loading, particularly when the shell elements are used. It would actually be interesting to be able to compute the eigenvalues of a system with follower loads.

**Comment by RiccardoRossi** [comment]
some times back with @manuelmessmer we were discussing about the possibility of optionally simmetrizing the matrix prior to passing it to the solver.

Even though i agree that it would be good to understand why the shell is non symmetric (it should not be the case) it may be useful to ensure symmetry at discrete level

**Comment by oberbichler** [comment]
Symmetrize the local matrix of the shell?

The algorithm was made for symmetric matrices but for the example of @emiroglu it produces good results. I do not know if this also works for other examples. Since there is no guarantee that the matrix is symmetric it is up to the user.

Maybe we should check the symmetry of the failed nightly test and compute a reference solution with another program.

**Comment by manuelmessmer** [comment]
I noticed this problem in the buckling solver. There the difference of two consecutive stiffness matrices is computed. Therefore, the asymmetry was a bit more pronounced and led to slightly different results of the eigenvalue solver with and without MKL support.

**Comment by armingeiser** [comment]
> The algorithm was made for symmetric matrices

That was also the reason we used the PardisoLDLT solver internally, since we assumed this would always be called just with symmetric input. 

Using PardisoLU will not fail if an unsymmetric matrix is given, but we don't know how good the rest of the aglorithm works for these cases. 

Idea for a "robust" solution that does not hide errors:
- add a flag `allow_unsymmetric_matrices` that activates PardisoLU.
- check for symmetry (not sure how expensive that is) and give a warning/error depending on said flag

**Comment by RiccardoRossi** [comment]
i would also add a function symmetrize_matrix (making it symmetric by
Amodified=(A+A.transpose)/2 should be approximately the same cost as
checking the symmetry)

**Comment by oberbichler** [comment]
it should be cheap if we assume that the sparse structure is symmetric

**Comment by armingeiser** [comment]
So, what i understand:

default:
* check for symmetry and use LDLT
* if input is not symmetric throw an error, mentioning what can be done to deal with unsymmetric matrices and warn that the results have to be treated with care in that case

unsymmetric case:
* `allow_unsymmetric_matrices` to simply switch to PardisoLU in case of MKL support
* or `symmetrize_input_matrices` to symmetrize matrix (in this case we could keep using PardisoLDLT
* print warning about "Algorithm was not originally designed for unsymmetric matrices, treat results with care!"

I am really encouraging to be very explicit about the fact that unsymmetric matrices are not recommended as input, since this has never been tested or compared to reference solutions.

**Comment by oberbichler** [comment]
> since this has never been tested or compared to reference solutions.

We compared it for the example of @emiroglu and the result was OK. But I agree that allowing unsymmetric matrices is just a temporary workaround.

**Comment by emiroglu** [comment]
> some times back with @manuelmessmer we were discussing about the possibility of optionally simmetrizing the matrix prior to passing it to the solver.
> 
> Even though i agree that it would be good to understand why the shell is non symmetric (it should not be the case) it may be useful to ensure symmetry at discrete level

@RiccardoRossi 
I agree that we should take a look at why the element matrices are unsymmetric. This would cause problems in #8174 because then both right and left eigenvectors would be necessary. Also, adjoint formulations could be effected from it because the transpose of the system matrix is necessary for the adjoint system.

**Comment by emiroglu** [comment]
I did some tests on an example case with TrussElement3D2N, TotalLagrangianElement3D4N, ShellThinElementCorotational3D3N, NodalConcentratedElement3D1N and master slave constraints using different linear solvers. I ran the cases also with and without locally symmetrized (element level) shell element matrices. I computed first 4 eigenvalues. Following are the results for a regular eigenvalue analysis (**u_0** = **0**):

| Linear Solver | Element Matrix Symmetrized | Solution Successful | Eigenvalue 1       | Eigenvalue 2       | Eigenvalue 3      | Eigenvalue 4      |
|---------------|----------|---------------------|--------------------|--------------------|-------------------|-------------------|
| eigen_lu      | no       | no (singular)       | N/A                | N/A                | N/A               | N/A               |
| pardiso_lu    | no       | yes                 | 171.28057448382688 | 171.36965040593805 | 9007.373753360871 | 9026.737231270217 |
| pardiso_ldlt  | no       | yes                 | 171.280574523656   | 171.36965232774716 | 9007.373755385104 | 9026.737236341429 |
| eigen_lu      | yes      | no (singular)       | N/A                | N/A                | N/A               | N/A               |
| pardiso_lu    | yes      | yes                 | 171.28057585525767 | 171.36965051420046 | 9007.373757599527 | 9026.737232669226 |
| pardiso_ldlt  | yes      | yes                 | 171.28057553568777 | 171.36964778754316 | 9007.373762155557 | 9026.737241267305 |

I also computed the eigenvalues after applying an initial loading and performing a static nonlinear analysis to find the equilibrium point (**u_0** != **0**) and take the stress stiffening, varying tangent stiffness etc. effects into account

| Linear Solver | Element Matrix Symmetrized | Solution Successful | Eigenvalue 1        | Eigenvalue 2        | Eigenvalue 3       | Eigenvalue 4       |
|---------------|----------|---------------------|---------------------|---------------------|--------------------|--------------------|
| eigen_lu      | no       | yes                 | 172.31278883922684  | 173.43695569186713  | 8964.903411360452  | 9016.913725557402  |
| pardiso_lu    | no       | yes                 | 172.31278918216188  | 173.4369567550114   | 8964.903442048775  | 9016.913693909542  |
| pardiso_ldlt  | no       | incorrect (?)       | -226545.19681885446 | -134744.19260443404 | -6015.520485467581 | 3898.3729645123717 |
| eigen_lu      | yes      | yes                 | 172.31278928884504  | 173.43695676339482  | 8964.903411373789  | 9016.913711821244  |
| pardiso_lu    | yes      | yes                 | 172.31278968655067  | 173.4369544633999   | 8964.903427595098  | 9016.913698605418  |
| pardiso_ldlt  | yes      | yes                 | 172.31279149784203  | 173.43695350894615  | 8964.903459002619  | 9016.913680895379  |

From this, it still looks like `pardiso_lu` is the most reliable one which gives consistently comparable results to those when other linear solvers are used and give sensible results in the iterative eigensystem solver. I can't really judge where the problem in #8424 comes from. Maybe the reference results should be updated using `pardiso_lu`. Can @qaumann please comment on this?

Here I would like to point out another issue with symmetrizing the global system matrices, if they are **only** symmetrized in the eigensystem solver. It may cause a consistency problem when the results are compared to other analysis types in the following scenarios:
- FFT on transient analysis results to find the eigenfrequencies of the system. Then compare the eigenfrequencies that are computed from FFT to eigenfrequencies from the `eigensystem_solver`. The displacement results are computed with asymmetric system matrices while the eigenfrequencies are not.
- Computation of "operational" eigenvalues and eigenmode shapes: initial static nonlinear analysis would be performed with asymmetric system matrix whereas the eigenvalue analysis not.
- Eigenvalue analysis of systems under follower loads: Such systems actually have asymmetric matrices which lead to separate left and right eigenvectors. Well.. the iterative solution in eigensystem solver is meant to deal only with symmetric problems so in this case an improvement is necessary to overcome this issue anyways.
- Modal derivative analysis from #8174 or the modal derivative analysis of "operational" eigenvalues: In this case if the left and right eigenvectors are not same then all the assumptions in the derivation are wrong which lead to quite wrong results.

From this point (if the asymmetry in shell element matrices is erroneous) it makes sense to symmetrize the local element matrices (probably in `BaseShellElement::CalculateLocalSystem` or `BaseShellElement::CalculateLeftHandSide`) to consistently remove the problems; this might cause a lot of tests to break though.

**Pull request merged**
