### PR TITLE
[Release] Hotfix for Fractional Step strategy issue.

### PR DESCRIPTION
**Pull request by jcotela**
Porting #4431 to the release branch

### CODE REVIEW

**Comment by jcotela** [comment]
Tests fail, but it does not seem to be a test that should be affected by this change...

**Comment by roigcarlo** [comment]
We have the same problem in another branch... @loumalouomega we need a hotfix or disable that test until we can ensure it works....

**Comment by loumalouomega** [comment]
> We have the same problem in another branch... @loumalouomega we need a hotfix or disable that test until we can ensure it works....

Indeed

**Review by roigcarlo — DISMISSED** [review]

**Comment by philbucher** [comment]
I reduced the tolerance, now it should work

This only seems to be a problem on the release-branch, the Master is fine

**Comment by roigcarlo** [comment]
@philbucher What bugs me off is that Release branch should not have any change which is not in the master.

Edit: I mean, for the fail in the test, not your fix.

**Comment by philbucher** [comment]
This bugs me a lot too!
there were several fixes in major classes (BlockBuilder & ResidualCriterion) that were done after the release-branch was made and I am not sure which of those changes were ported to the release-branch
Also the EliminationB&S has some problems, even on master

I guess we cannot just merge master into the release-branch right?

**Comment by roigcarlo** [comment]
Nop, that would be unwise at best, there have been many changes in the master that were intentionally delayed after this branch because we didn't want to enter in the release...

**Comment by philbucher** [comment]
I see

@loumalouomega @RiccardoRossi you did the most important changes, could you compare the release branch and the master for changes in the B&S and the conv-crit? I think by porting those changes most of the problems should disappear

**Comment by loumalouomega** [comment]
> I see
> 
> @loumalouomega @RiccardoRossi you did the most important changes, could you compare the release branch and the master for changes in the B&S and the conv-crit? I think by porting those changes most of the problems should disappear

I think we already ported, in any case the idea is top cherry-pick. How can we do know the exact list of commits to cherry-pick?

**Comment by roigcarlo** [comment]
@loumalouomega, If @jcotela agrees make the cherry picks you want in this PR and whn this passes clean I will open a separate PR with the initial pick of this PR and nother ones with the ones need no solve the tolerance problem

**Comment by jcotela** [comment]
@roigcarlo @loumalouomega feel free to add commits to this PR if it is convenient for you. However, I think the same changes will be required for #4427 too.

**Comment by roigcarlo** [comment]
Yep. I am holding that one for the same reason.

**Pull request closed without merging**
