### PR TITLE
[DelaunayMeshingApplication] Error compilation with CMake if USE_TRIANGLE_NONFREE_TPL not set

### LINKED ISSUE #9339: Error when compiling the DelaunayMeshingApplication
**Description**
Here the error:

```
/usr/bin/ld: cannot find -ltriangle
collect2: error: ld returned 1 exit status
applications/DelaunayMeshingApplication/CMakeFiles/KratosDelaunayMeshingCore.dir/build.make:281: recipe for target 'applications/DelaunayMeshingApplication/libKratosDelaunayMeshingCore.so' failed
make[2]: *** [applications/DelaunayMeshingApplication/libKratosDelaunayMeshingCore.so] Error 1
CMakeFiles/Makefile2:3413: recipe for target 'applications/DelaunayMeshingApplication/CMakeFiles/KratosDelaunayMeshingCore.dir/all' failed
make[1]: *** [applications/DelaunayMeshingApplication/CMakeFiles/KratosDelaunayMeshingCore.dir/all] Error 2
```

**Scope**
Where in Kratos is this bug happening. 
E.g.
- Kratos DelaunayMeshingApplication
- As a dependency to PfemFluidDynamicsApplication

**Environment**
Please specify your operating system, kratos branch, python version or any other library versions that you consider relevant.
E.g.:
- OS: Ubuntu 18.04
- Branch: master

### PR DESCRIPTION
**Pull request by loumalouomega**
**📝 Description**
Fix #9339

**🆕 Changelog**
- Error compilation with CMake if USE_TRIANGLE_NONFREE_TPL not set

### CODE REVIEW

**Comment by roigcarlo** [comment]
Sadly this does not work. We cannot automatically enable triangle based on an app dependency.

It needs to be a message informing the user that he needs to add that flag manually.

**Comment by loumalouomega** [comment]
> Sadly this does not work. We cannot automatically enable triangle based on an app dependency.
> 
> It needs to be a message informing the user that he needs to add that flag manually.
> 
> **Edit**: Unless delaunay remains the only app using it, in that case adding a
> 
> ```
> add_subdirectory(${KRATOS_SOURCE_DIR}/external_libraries/triangle)
> ```
> 
> would works as well.

Now?

**Comment by roigcarlo** [comment]
Ok, but I will leave it as a FATAL_ERROR

**Comment by loumalouomega** [comment]
> **Edit**: Unless delaunay remains the only app using it, in that case adding a
> 
> ```
> add_subdirectory(${KRATOS_SOURCE_DIR}/external_libraries/triangle)
> ```
> 
> would works as well.

Why do we ask for a flag if later we are goind to do like the flag does not matter

**Comment by roigcarlo** [comment]
Because we need to user to manually specify that he is willing to compile Kratos with that dependency. Is not technical, is legal.

**Comment by loumalouomega** [comment]
> Because we need to user to manually specify that he is willing to compile Kratos with that dependency. Is not technical, is legal.

I know, you were suggesting the automatic add

**Comment by roigcarlo** [comment]
If only Delaunay uses it then is like tetgen and we can move it here and avoid the flag, since then its enough that in the Readme of the app specifies that compiling it enable this specific component.

The problem is that right now the `add_subdirectory` for triangle that generates the .so is in the core. Hence the problem.

**Review by roigcarlo — APPROVED** [review]

**Comment by philbucher** [comment]
nice, thx for this!

**Pull request merged**
