### PR TITLE
Creating licence in order to appear in the menu

### PR DESCRIPTION
**Pull request by loumalouomega**
Doing this the menu of GitHub will show the type of license used

### CODE REVIEW

**Comment by pooyan-dadvand** [comment]
This is somehow a delicate subject because some applications have different licenses (our license owner). Before adding it like this we should see how we can emphasise this heterogeneous nature of our license.

**Comment by loumalouomega** [comment]
OK, I understand

**Comment by RiccardoRossi** [comment]
+1 for Pooyan's comment.

the point is that we want to preserve that BSD is for everything (in this repository) however that there may be different copyright holders for the different apps.

**Comment by loumalouomega** [comment]
OK, it was because the typical thing in the GitHub is to have a license once you enter in the web of the project, maybe it is a good idea to split the core and the other applications in subprojects and create an script that automatically assembles the different apps

**Comment by loumalouomega** [comment]
Do I remove this?

**Comment by RiccardoRossi** [comment]
i would close this branch...

**Comment by loumalouomega** [comment]
Done

**Pull request closed without merging**
