### PR TITLE
[Core][MPI] fix Serializer flags in  distributed_restart_utility

### LINKED ISSUE #9468: [TwoFluid] RestartProcess for TwoFluidSolver in MPI
**Description**
I tried to use the RestartProcess "save_restart_process" with the TwoFluidSolver in MPI. Unfortunately, it is throwing errors.

For OpenMP it does work. For the structural solver the RestartProcess also works for MPI. 

This ist the error log:

``
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
mpiexec noticed that process rank 1 with PID 0 on node johannes-stud03 exited on signal 11 (Segmentation fault).
``

Any hints or ideas ?

### PR DESCRIPTION
**Pull request by philbucher**
This PR set correctly the flags for the `Serializer` in the `distributed_restart_utility` when used in MPI

closes #9468

@mpentek can you test this please?

### CODE REVIEW

**Comment by philbucher** [comment]
this can only be merged after #9614, otherwise most fluid restarts are broken

**Comment by philbucher** [comment]
with #9614 being merged, this is the last step for having the two-fluid restart working :)

In fact this should be the fix for any restart that involves the use of `GlobalPointer`

**Comment by mpentek** [comment]
Is there still some pending change  because of which the tests are failing?

**Comment by philbucher** [comment]
> Is there still some pending change because of which the tests are failing?

there are some tests failing in the Fluid bcs of some recent change
ping @KratosMultiphysics/fluid-dynamics

**Comment by mpentek** [comment]
Because of this? #9592

**Comment by philbucher** [comment]
did you merge master into this branch before testing?

**Comment by mpentek** [comment]
> did you merge master into this branch before testing?

yes, same error.

**Comment by mpentek** [comment]
Here the error on LoadRestart in OpenMP:

```
Restart Utility: Loading restart file: /home/mate/Documents/CaarcWithController/TestTwoFluid/restart/strong/cfd_x/FluidModelPart_0.06.rest 
Traceback (most recent call last):
  File "MainKratos.py", line 36, in <module>
    simulation.Run()
  File "/home/mate/Repositories/KratosTest/install/KratosMultiphysics/analysis_stage.py", line 47, in Run
    self.Initialize()
  File "/home/mate/Repositories/KratosTest/install/KratosMultiphysics/analysis_stage.py", line 81, in Initialize
    self._GetSolver().ImportModelPart()
  File "/home/mate/Repositories/KratosTest/install/KratosMultiphysics/FluidDynamicsApplication/fluid_solver.py", line 86, in ImportModelPart
    self._ImportModelPart(self.main_model_part,self.settings["model_import_settings"])
  File "/home/mate/Repositories/KratosTest/install/KratosMultiphysics/python_solver.py", line 157, in _ImportModelPart
    RestartUtility(model_part, self._GetRestartSettings(model_part_import_settings)).LoadRestart()
  File "/home/mate/Repositories/KratosTest/install/KratosMultiphysics/restart_utility.py", line 127, in LoadRestart
    serializer.Load(self.model_part_name, self.model_part)
ValueError: vector::_M_default_append
[Inferior 1 (process 16222) exited with code 01]
(gdb) bt full
No stack.
(gdb) bt full

```

**Comment by philbucher** [comment]
I checked it now again, conclusion is as follows:
1. OpenMP works perfectly for me, both saving and restarting
2. With MPI sth seems to have been merged in the past 10 days which makes it hang now (I checked with a commit from 10 days ago, there obviously the restart is not working but at least the case runs) With the current master the case stopped working (and I also get the warnings)

**Comment by philbucher** [comment]
with #9651 it also works correctly for me in MPI

**Comment by mpentek** [comment]
> with #9651 it also works correctly for me in MPI

So when I merge #9651 into #9531, both OpenMP as well as MPI will succeed in the SaveRestart. With this I also agree with the necessity of #9651.

Still, for me when trying out the LoadRestart, whether OpenMP or MPI, I get the following error (now consistent for both parralelism types):

```
    self.distributed_model_part_importer.ImportModelPart()
  File "/home/mate/Repositories/KratosTest/install/KratosMultiphysics/mpi/distributed_import_model_part_utility.py", line 130, in ImportModelPart
    RestartUtility(self.main_model_part, restart_settings).LoadRestart()
  File "/home/mate/Repositories/KratosTest/install/KratosMultiphysics/restart_utility.py", line 127, in LoadRestart
    serializer.Load(self.model_part_name, self.model_part)
ValueError: (on rank 3): vector::_M_default_append

```

@philbucher you cannot reproduce this error, which makes me think whether it is OS or some other dependency-related (boost?).

**Review by mpentek — CHANGES_REQUESTED** [review]
Like this the restart works, both OpenMP as well as MPI, as long as the material properties are given in the MDPA.

The last revert in #9615 seems to be now causing an error when importing the material properties from the json file.

```
Traceback (most recent call last):
  File "MainKratos.py", line 36, in <module>
    simulation.Run()
  File "/home/mate/Repositories/KratosTest/install/KratosMultiphysics/analysis_stage.py", line 47, in Run
    self.Initialize()
  File "/home/mate/Repositories/KratosTest/install/KratosMultiphysics/analysis_stage.py", line 81, in Initialize
    self._GetSolver().ImportModelPart()
  File "/home/mate/Repositories/KratosTest/install/KratosMultiphysics/FluidDynamicsApplication/trilinos_navier_stokes_two_fluids_solver.py", line 33, in ImportModelPart
    self.distributed_model_part_importer = DistributedImportModelPartUtility(self.main_model_part, self.settings)
  File "/home/mate/Repositories/KratosTest/install/KratosMultiphysics/mpi/distributed_import_model_part_utility.py", line 17, in __init__
    self.comm = KratosMultiphysics.ParallelEnvironment.GetDataCommunicator(data_comm_name)
RuntimeError: Error: Requesting unknown DataCommunicator World.
```

Also, the mistery is solved why previously it was working for @philbucher but not myself. During the various testing rounds, there was a conflict in settings, specifically:

the `"save_restart_process"` needs to have the flag for `"serializer_trace"` the same as when it is used during the loading in `"model_import_settings"` for the same flag. Certain combinations work, such as `"trace_all"` while saving and `"trace_error"` while loading, but not in combination with `"no_trace"`. There is no check to verify for compatibility.

**Review by mpentek — APPROVED** [review]
Changes done in #9654

**Comment by mpentek** [comment]
The failing tests are due to another reason, as in #9628, with results updated in #9592.

**Pull request merged**
