### PR TITLE
Changing _get_element_num_nodes for python2 compatibility.

### LINKED ISSUE #1592: __next__() function breaks python 2 compatibility
Seems that `FluidDynamicsApplication/python_scripts/navier_stokes_base_solver.py
` crashes when executen in python2 due to `__next__()` being used. I did a bit of research and this was names `next()` in p2 while it is `__next__()` in p3.

Not sure how to solve this :S

### PR DESCRIPTION
**Pull request by jcotela**
This fixes #1592.
@roigcarlo Can you check that this works in python2? I have no machine to confirm
@rubenzorrilla Can you try a test with trilinos? I removed the duplication of code, so it should now work both with and without mpi.

### CODE REVIEW

**Comment by roigcarlo** [comment]
Bulding it. May take some time I didn't have the libs in my pc.... but looks good!

**Comment by rubenzorrilla** [comment]
@jcotela I did some minor corrections. Now is working both in serial and MPI.

**Review by roigcarlo — APPROVED** [review]
Works in my computer with p3.6 & p2.7 :+1:

**Review by rubenzorrilla — COMMENTED** [review]
Done!

**Pull request merged**
