### PR TITLE
Experimental fix for clang undefined-var-template warning.

### LINKED ISSUE #188: warning on clang
clang 3.9+ gives million of warnings about uninitialized components.

they disappear if we add the following lines

KratosComponents<Variable<bool> > bool_components();
KratosComponents<Variable<int> >int_components();
KratosComponents<Variable<unsigned int> >uint_components();
KratosComponents<Variable<double> >double_components();
KratosComponents<Variable<array_1d<double, 3> > >array1d_components();
KratosComponents<Variable<Quaternion<double> > >quaternion_components();
KratosComponents<Variable<Vector> >vector_components();
KratosComponents<Variable<Matrix> >matrix_components();
KratosComponents<Variable<std::string> >string_components();
KratosComponents<VariableComponent<VectorComponentAdaptor<array_1d<double, 3> > > >var_component_components();
KratosComponents<Variable<Flags> >var_flags_components();
KratosComponents<Flags>flags_components();

at the end of kratos components.

this is a bit ugly since i don't love the idea of instantiating a few global objects in the global kratos namespace just for silencing a warning.

however the warning is very noisy, so we should decide where to do this, and eventually immediately destroy the objects. @roigcarlo @pooyan-dadvand 
proposals are welcome...

### PR DESCRIPTION
**Pull request by jcotela**
I think I may have found a way to fix the source of the clang warnings reported in #188
```
/home/rrossi/kratos_git/kratos/includes/kratos_components.h:85:9: warning: instantiation of variable 'Kratos::KratosComponents<Kratos::Variable<boost::numeric::ublas::vector<double,
      boost::numeric::ublas::unbounded_array<double, std::allocator<double> > > > >::msComponents' required here, but no definition is available [-Wundefined-var-template]
```
Apparently the issue is related to the template instantiation being created as an independent object in all binaries that use it. The answer to [this question](https://stackoverflow.com/questions/8130602/using-extern-template-c11) is the simplest overview I could find of the problem.

This is not to be considered for merging right now, I created the PR to see if appveyor can compile it in windows.

Big thank you to @msandre for teaching me about explicit template instantiation.

If it works, it closes #188.

(Edit: related link, for my reference https://social.msdn.microsoft.com/Forums/vstudio/en-US/1cdfb076-ca3c-4469-a4fd-48201ac97714/how-do-i-handle-static-members-of-template-classes?forum=vclanguage)

### CODE REVIEW

**Comment by jcotela** [comment]
Note: It compiles with clang and runs + test pass on my machine for the core and a few applications. I still need to try trilinos and external solvers though, which may be the more critical ones.

**Comment by jcotela** [comment]
@roigcarlo could you take a look? Appveyor compiles but throws a lot of warnings. I guess I can move the KRATOS_API to the non-extern instantiation, but that one is on a cpp... Any ideas?

**Comment by roigcarlo** [comment]
@jcotela I'll take a look tomorrow but @RiccardoRossi and I tried that once and didn't find a way to remove it. 

The problems is the combination of `extern` and `KRATOS_API` when the macro is set to import

**Comment by jcotela** [comment]
Ok, the current version seems to compile clean in clang, MSVC and gcc and tests run for all compilers.

It is not nice though... I particularly dislike adding the template instantiation of msComponents in the header file, but apparently that is the way to go for windows :(

**Comment by pooyan-dadvand** [comment]
My only comment is about the macro name which does not give any feedback how to use it.

**Comment by jcotela** [comment]
What would be a better name? I used `KRATOS_API_EXTERN`  because it is an `extern` to be used in conjunction with `KRATOS_API(KRATOS_CORE)` but I agree that it is not clear. To be honest all of this is just acrobatics to make the different compilers play nice, and I could not see a way to communicate it clearly to users.

**Comment by pooyan-dadvand** [comment]
I see @jcotela . In fact I don't have a suggestion....

**Comment by jcotela** [comment]
@KratosMultiphysics/technical-committee I added this PR to the release milestone to remind ourselves about this issue. We can always drop it later if there is no time to include it in the release.

**Review by pooyan-dadvand — APPROVED** [review]
Thanks! 👍

**Pull request merged**
