### PR TITLE
Adding Poromechanics and Dam to CI

### LINKED ISSUE #10364: Update DAMApplication Status
Dear @KratosMultiphysics/dam

Currently DAMapplication is included in the release list, but is not compiling and not present in the CI, which is causing the pip installation to break.

We have been able to fix this but we would need you to either to add the app to the CI list or remove it from the release list.

### PR DESCRIPTION
**Pull request by roigcarlo**
**📝 Description**
Adding apps. Should fix #10364

**🆕 Changelog**
- Adding PoromechanicsApp to CI
- Adding DamApp to CI

### CODE REVIEW

**Review by joaquinirazabal — DISMISSED** [review]
Nice, thank you, @roigcarlo.

**Comment by ipouplana** [comment]
Thank you @roigcarlo

**Comment by ipouplana** [comment]
I'll try to look at it this week.

**Comment by roigcarlo** [comment]
OK I will take a look next week, but conflicting names between apps should not be a problem, as they exist in different spaces (even with the unity builds enabled)

**Comment by philbucher** [comment]
They are a problem, remember the module_local discussion?

In a nutshell, the names need to be different in python 

Also the need to be registered with different names in the KratosCompoments

**Comment by roigcarlo** [comment]
@ipouplana or @joaquinirazabal are you ok with the changes?

**Comment by joaquinirazabal** [comment]
Ok from my side. Thanks, @roigcarlo

**Comment by ipouplana** [comment]
It is also ok from my side. Thank you @roigcarlo.

**Review by ipouplana — APPROVED** [review]

**Pull request merged**
