### PR TITLE
[Delaunay App] NOW compiling -> Was broken

### PR DESCRIPTION
**Pull request by AlejandroCornejo**
In this PR I'm correcting the Delaunay App in order to be able to work. Related to the "new" `const `
PR changes of today.

### CODE REVIEW

**Comment by AlejandroCornejo** [comment]
I'm having problems to compile the following lines:

~~~c++
void CompositeCondition::EquationIdVector( EquationIdVectorType& rResult, 
                                          const ProcessInfo& rCurrentProcessInfo ) const
{

  rResult.resize(0,false);

  EquationIdVectorType LocalResult;

  for (ConditionIterator cn = mChildConditions.begin() ; cn != mChildConditions.end(); ++cn)
    {
      if( IsActive(cn, rCurrentProcessInfo) ){

	cn->EquationIdVector(LocalResult,rCurrentProcessInfo);

	for(unsigned int i=0; i<LocalResult.size(); i++)
	  {
	    rResult.push_back(LocalResult[i]);
	  }
      }

    }

}
~~~

It says:

D:\KRATOS_MULTIPHYSICS\Kratos\applications\DelaunayMeshingApplication\custom_conditions\composite_condition.cpp(229):
error C2440: 'inicializando': no se puede realizar la conversión de 'boost::iterators::indirect_iterator<std::_Vector_
const_iterator<std::_Vector_val<std::_Simple_types<_Ty>>>,boost::iterators::use_default,boost::iterators::use_default,
boost::iterators::use_default,boost::iterators::use_default>' a 'boost::iterators::indirect_iterator<std::_Vector_iter
ator<std::_Vector_val<std::_Simple_types<_Ty>>>,boost::iterators::use_default,boost::iterators::use_default,boost::ite
rators::use_default,boost::iterators::use_default>' [D:\KRATOS_MULTIPHYSICS\Kratos\build\Release\applications\Delaunay
MeshingApplication\KratosDelaunayMeshingCore.vcxproj]
          with
          [
              _Ty=Kratos::Condition::Pointer
          ]
  D:\KRATOS_MULTIPHYSICS\Kratos\applications\DelaunayMeshingApplication\custom_conditions\composite_condition.cpp(229)
  : note: Ningún constructor ha podido aceptar el tipo de origen o bien la resolución de sobrecarga del constructor er
  a ambigua
D:\KRATOS_MULTIPHYSICS\Kratos\applications\DelaunayMeshingApplication\custom_conditions\composite_condition.cpp(231):
error C2662: 'bool Kratos::CompositeCondition::IsActive(Kratos::CompositeCondition::ConditionIterator,const Kratos::Pr
ocessInfo &)': no se puede convertir el puntero 'this' de 'const Kratos::CompositeCondition' a 'Kratos::CompositeCondi
tion &' [D:\KRATOS_MULTIPHYSICS\Kratos\build\Release\applications\DelaunayMeshingApplication\KratosDelaunayMeshingCore
.vcxproj]

@philbucher @RiccardoRossi

**Comment by AlejandroCornejo** [comment]
In linux:

/home/acornejo/Projects/Kratos/applications/DelaunayMeshingApplication/custom_conditions/compos                                                     ite_condition.cpp: In member function ‘virtual void Kratos::CompositeCondition::EquationIdVecto                                                     r(Kratos::Condition::EquationIdVectorType&, const Kratos::ProcessInfo&) const’:
/home/acornejo/Projects/Kratos/applications/DelaunayMeshingApplication/custom_conditions/compos                                                     ite_condition.cpp:229:53: error: conversion from ‘indirect_iterator<__normal_iterator<const Kra                                                     tos::intrusive_ptr<Kratos::Condition>*,[...]>,[...],[...],[...],[...]>’ to non-scalar type ‘ind                                                     irect_iterator<__normal_iterator<Kratos::intrusive_ptr<Kratos::Condition>*,[...]>,[...],[...],[                                                     ...],[...]>’ requested
   for (ConditionIterator cn = mChildConditions.begin() ; cn != mChildConditions.end(); ++cn)
                               ~~~~~~~~~~~~~~~~~~~~~~^~
/home/acornejo/Projects/Kratos/applications/DelaunayMeshingApplication/custom_conditions/compos                                                     ite_condition.cpp:231:43: error: passing ‘const Kratos::CompositeCondition’ as ‘this’ argument                                                      discards qualifiers [-fpermissive]
       if( IsActive(cn, rCurrentProcessInfo) ){
                                           ^
In file included from /home/acornejo/Projects/Kratos/applications/DelaunayMeshingApplication/cu                                                     stom_conditions/composite_condition.cpp:15:
/home/acornejo/Projects/Kratos/applications/DelaunayMeshingApplication/custom_conditions/compos                                                     ite_condition.hpp:475:10: note:   in call to ‘bool Kratos::CompositeCondition::IsActive(Kratos:                                                     :CompositeCondition::ConditionIterator, const Kratos::ProcessInfo&)’
     bool IsActive(ConditionIterator iChildCondition, const ProcessInfo& rCurrentProcessInfo);

**Comment by philbucher** [comment]
I am pretty sure that `IsActive` is not a `const` function

**Comment by philbucher** [comment]
can you try with my commit?

**Comment by AlejandroCornejo** [comment]
Now it says:

D:\KRATOS_MULTIPHYSICS\Kratos\applications\DelaunayMeshingApplication\custom_conditions\composite_condition.cpp(229):
error C2440: 'inicializando': no se puede realizar la conversión de 'boost::iterators::indirect_iterator<std::_Vector_
const_iterator<std::_Vector_val<std::_Simple_types<_Ty>>>,boost::iterators::use_default,boost::iterators::use_default,
boost::iterators::use_default,boost::iterators::use_default>' a 'boost::iterators::indirect_iterator<std::_Vector_iter
ator<std::_Vector_val<std::_Simple_types<_Ty>>>,boost::iterators::use_default,boost::iterators::use_default,boost::ite
rators::use_default,boost::iterators::use_default>' [D:\KRATOS_MULTIPHYSICS\Kratos\build\Release\applications\Delaunay
MeshingApplication\KratosDelaunayMeshingCore.vcxproj]

**Comment by philbucher** [comment]
hm I think my spanish is too limited to full understand the error :sweat_smile: 
I am guessing sth and pushed, can you try?

**Comment by AlejandroCornejo** [comment]
> 
> 
> hm I think my spanish is too limited to full understand the error 😅
> I am guessing sth and pushed, can you try?

I've tried! srry abouth the Spanish hehe Here you have the result in linux:

/home/acornejo/Projects/Kratos/applications/DelaunayMeshingApplication/custom_conditions/composite_condition.cpp: In member function ‘virtual void Kratos::CompositeCondition::EquationIdVector(Kratos::Condition::EquationIdVectorType&, const Kratos::ProcessInfo&) const’:
/home/acornejo/Projects/Kratos/applications/DelaunayMeshingApplication/custom_conditions/composite_condition.cpp:229:53: error: conversion from ‘indirect_iterator<__normal_iterator<const Kratos::intrusive_ptr<Kratos::Condition>*,[...]>,[...],[...],[...],[...]>’ to non-scalar type ‘indirect_iterator<__normal_iterator<Kratos::intrusive_ptr<Kratos::Condition>*,[...]>,[...],[...],[...],[...]>’ requested
   for (ConditionIterator cn = mChildConditions.begin() ; cn != mChildConditions.end(); ++cn)


seems somtehing related with the type of the iterator

**Comment by philbucher** [comment]
I think the iterator needs to be `const`

can you try again?

**Comment by AlejandroCornejo** [comment]
> 
> 
> I think the iterator needs to be `const`
> 
> can you try again?

it says:


/home/acornejo/Projects/Kratos/applications/DelaunayMeshingApplication/custom_conditions/composite_condition.cpp: In member function ‘virtual void Kratos::CompositeCondition::GetFirstDerivativesVector(Kratos::Vector&, int) const’:
/home/acornejo/Projects/Kratos/applications/DelaunayMeshingApplication/custom_conditions/composite_condition.cpp:293:81: error: no match for ‘operator++’ (operand type is ‘const boost::iterators::indirect_iterator<__gnu_cxx::__normal_iterator<const Kratos::intrusive_ptr<Kratos::Condition>*, std::vector<Kratos::intrusive_ptr<Kratos::Condition>, std::allocator<Kratos::intrusive_ptr<Kratos::Condition> > > >, boost::iterators::use_default, boost::iterators::use_default, boost::iterators::use_default, boost::iterators::use_default>’)
   for (const auto cn = mChildConditions.begin() ; cn != mChildConditions.end(); ++cn)

**Comment by philbucher** [comment]
ok give me a few minutes, I am compiling it myself

sorry for the inconvenience

**Comment by AlejandroCornejo** [comment]
> 
> 
> ok give me a few minutes, I am compiling it myself
> 
> sorry for the inconvenience

Don't worry! this one is more challenging error ;)

**Comment by philbucher** [comment]
now it compiles, I cleaned it a bit

can you check if this works for you @AlejandroCornejo ?

**Comment by AlejandroCornejo** [comment]
> 
> 
> now it compiles, I cleaned it a bit
> 
> can you check if this works for you @AlejandroCornejo ?

Mow it ocmpiles in Win and Linux! :)

**Review by philbucher — APPROVED** [review]

**Pull request merged**
