### PR TITLE
Correcting selfweight calculation

### PR DESCRIPTION
**Pull request by loumalouomega**
Concerning #567

### CODE REVIEW

**Comment by jginternational** [comment]
I've compiled it and tested, everything seems to run fine. Exactly the same results than the old process (Solid) are achieved
@pooyan-dadvand Bug fixed! 
@loumalouomega Good and fast job!

**Comment by loumalouomega** [comment]
@jginternational approve the PR!!!!

**Review by jginternational — APPROVED** [review]
Compiles and runs ok

**Comment by loumalouomega** [comment]
@jginternational Merci

**Pull request merged**
