### PR TITLE
[Core] Adding clear to assign processes

### LINKED ISSUE #6291: Missbehaviour regarding "interval" with loads in StructuralMechanicsApplication
Dear all,

@Rbravo555 is trying to reproduce a simple case (cantilever with a pressure load applied durint a certain time period [0, 3] s) and we have noticed that after the 3.0 s the load remains applied:

imagen

We have tried to solve this by:

1. Adding Damping -> Not working

1. Non-linear simulation  -> Not working

1. decrease the dt  -> Not working

1. using static simulation  -> Not working

1. using a Total Lagrangian element  -> Not working

So my impression is that the `assign_vector_by_direction_to_condition_process` is not working properly... Anyone knows why?

@Rbravo555 will upload the cases to test.

### PR DESCRIPTION
**Pull request by loumalouomega**
Fixes #6291

This PR adds a clear method for the non-historical assign processes. It check the interval, if outside of the interval clears (set to zero) the variable. In order to avoid conflict between different processes with different intervals, the MARKER flag is considered

### CODE REVIEW

**Comment by pooyan-dadvand** [comment]
But the process doesn't have a clear method. How do you want to call this in a list of processes?

**Comment by loumalouomega** [comment]
> 
> 
> But the process doesn't have a clear method. How do you want to call this in a list of processes?

Like  #6291 is still in discussion this PR may not be the final solution

**Comment by loumalouomega** [comment]
> 
> 
> But the process doesn't have a clear method. How do you want to call this in a list of processes?

Ok, I have not understand the point. the idea was to be clled only in these processes as these are the conflictive ones, but sure. It makes more sense as you say

**Review by RiccardoRossi — CHANGES_REQUESTED** [review]
blocking to prevent accidental merges on behalf of the @KratosMultiphysics/technical-committee

**Comment by loumalouomega** [comment]
> blocking to prevent accidental merges on behalf of the @KratosMultiphysics/technical-committee

Ping?

**Review by RiccardoRossi — CHANGES_REQUESTED** [review]
As discussed in the comments, the solution of adding a Clear is not generic, and the current behaviour is the expected one.
A user can set to zero the loads either by prescribing a new loading on the next interval or eventually by adding a load by table.

for this reason @KratosMultiphysics/technical-committee does not agree about this PR

**Comment by loumalouomega** [comment]
> As discussed in the comments, the solution of adding a Clear is not generic, and the current behaviour is the expected one.
> A user can set to zero the loads either by prescribing a new loading on the next interval or eventually by adding a load by table.
> 
> for this reason @KratosMultiphysics/technical-committee does not agree about this PR

In any case, would you mind if I do an independent PR in order to define a virtual Clear function in the base Process?, many processes define a Clear function and every-time that this process is exposed to python the Clear must be re-declared

**Comment by rubenzorrilla** [comment]
> > As discussed in the comments, the solution of adding a Clear is not generic, and the current behaviour is the expected one.
> > A user can set to zero the loads either by prescribing a new loading on the next interval or eventually by adding a load by table.
> > for this reason @KratosMultiphysics/technical-committee does not agree about this PR
> 
> In any case, would you mind if I do an independent PR in order to define a virtual Clear function in the base Process?, many processes define a Clear function and every-time that this process is exposed to python the Clear must be re-declared

@KratosMultiphysics/technical-committee strongly agrees with this. The addition of the `Clear` should be straightforward.

**Comment by loumalouomega** [comment]
> > > As discussed in the comments, the solution of adding a Clear is not generic, and the current behaviour is the expected one.
> > > A user can set to zero the loads either by prescribing a new loading on the next interval or eventually by adding a load by table.
> > > for this reason @KratosMultiphysics/technical-committee does not agree about this PR
> > 
> > 
> > In any case, would you mind if I do an independent PR in order to define a virtual Clear function in the base Process?, many processes define a Clear function and every-time that this process is exposed to python the Clear must be re-declared
> 
> @KratosMultiphysics/technical-committee strongly agrees with this. The addition of the `Clear` should be straightforward.

It is done, I added the Clear in the Base Process and override the existing one. Also added some Clear functions to important assign processes

**Comment by philbucher** [comment]
You misunderstood, we meant a separated PR with only adding the Clear in the baseclass and fixing the overrides

**Comment by loumalouomega** [comment]
After #7324 this is ready to review

**Comment by philbucher** [comment]
> 
> 
> As discussed in the comments, the solution of adding a Clear is not generic, and the current behaviour is the expected one.
> A user can set to zero the loads either by prescribing a new loading on the next interval or eventually by adding a load by table.
> 
> for this reason @KratosMultiphysics/technical-committee does not agree about this PR

see comment above

**Comment by loumalouomega** [comment]
> > As discussed in the comments, the solution of adding a Clear is not generic, and the current behaviour is the expected one.
> > A user can set to zero the loads either by prescribing a new loading on the next interval or eventually by adding a load by table.
> > for this reason @KratosMultiphysics/technical-committee does not agree about this PR
> 
> see comment above

Therefore do I close this, or rename the method?

**Comment by loumalouomega** [comment]
> > > As discussed in the comments, the solution of adding a Clear is not generic, and the current behaviour is the expected one.
> > > A user can set to zero the loads either by prescribing a new loading on the next interval or eventually by adding a load by table.
> > > for this reason @KratosMultiphysics/technical-committee does not agree about this PR
> > 
> > 
> > see comment above
> 
> Therefore do I close this, or rename the method?

#6291 is not solved yet

**Comment by loumalouomega** [comment]
> > As discussed in the comments, the solution of adding a Clear is not generic, and the current behaviour is the expected one.
> > A user can set to zero the loads either by prescribing a new loading on the next interval or eventually by adding a load by table.
> > for this reason @KratosMultiphysics/technical-committee does not agree about this PR
> 
> see comment above

Solved

**Comment by loumalouomega** [comment]
> > > As discussed in the comments, the solution of adding a Clear is not generic, and the current behaviour is the expected one.
> > > A user can set to zero the loads either by prescribing a new loading on the next interval or eventually by adding a load by table.
> > > for this reason @KratosMultiphysics/technical-committee does not agree about this PR
> > 
> > 
> > see comment above
> 
> Solved

Solved long time ago

**Comment by philbucher** [comment]
The @KratosMultiphysics/technical-committee discussed this and agrees to add the method `Clear` to the baseclass of `Process` but it does NOT agree with the other implementations of this PR

my personal suggestion: Open a new PR where you add the `Clear` method to `Process` and close this one

**Comment by loumalouomega** [comment]
> The @KratosMultiphysics/technical-committee discussed this and agrees to add the method `Clear` to the baseclass of `Process` but it does NOT agree with the other implementations of this PR
> 
> my personal suggestion: Open a new PR where you add the `Clear` method to `Process` and close this one

What is the problem with the implementation?

**Comment by philbucher** [comment]
> What is the problem with the implementation?

This:

> As discussed in the comments, the solution of adding a Clear is not generic, and the current behaviour is the expected one.
> A user can set to zero the loads either by prescribing a new loading on the next interval or eventually by adding a load by table.
> 
> for this reason @KratosMultiphysics/technical-committee does not agree about this PR

**Comment by loumalouomega** [comment]
> > As discussed in the comments, the solution of adding a Clear is not generic, and the current behaviour is the expected one.
> > A user can set to zero the loads either by prescribing a new loading on the next interval or eventually by adding a load by table.
> > for this reason @KratosMultiphysics/technical-committee does not agree about this PR

Ok, but this PR was done in order to solve an issue. Of course, it changes behaviour, that's the point of the PR. The problem is that it requires explicitly to the user to clear the load after is applied, when it is supposed to disappear once the interval is finished

**Comment by philbucher** [comment]
well the @KratosMultiphysics/technical-committee does NOT agree with this change. What might be expected for Structures is exactly the opposite for fluids!
I don't know what to say otherwise :sweat_smile:

**Comment by loumalouomega** [comment]
> well the @KratosMultiphysics/technical-committee does NOT agree with this change. What might be expected for Structures is exactly the opposite for fluids!

But I don't understand, if you want to set some value until the end you can set an interval [something, "End"]. Can I discuss this with @KratosMultiphysics/technical-committee ?

**Comment by loumalouomega** [comment]
BTW, there is already a clear in the base class...

**Comment by loumalouomega** [comment]
What is the status of this¿? @KratosMultiphysics/technical-committee

**Comment by loumalouomega** [comment]
What is the status of this¿? https://github.com/orgs/KratosMultiphysics/teams/technical-committee

**Comment by loumalouomega** [comment]
Do I close this or I try to update it? @KratosMultiphysics/technical-committee

**Comment by rubenzorrilla** [comment]
IMO, we should close it. My point is that what I'd expect from the `Clear` method of a process is to clear itself (e.g., reset its member variables) but not to set to zero the values in the dataset it is using.

**Pull request closed without merging**
