### PR TITLE
Print info in file process updated

### PR DESCRIPTION
**Pull request by AlejandroCornejo**
**📝 Description**
I discovered that `double` entities where not printed correctly. Now it works. Initially was implemented supposing that tensors were printed.

### CODE REVIEW

**Comment by AlejandroCornejo** [comment]
> Can you add a test please?
hi, sure! One problem that I see of adding a test of IP variables is that I need some kind of `Element`... The elements that could work are inside the SMApp... What should we do?

**Comment by philbucher** [comment]
In those cases you can add a `skiptest` when using elements from apps. E.g.:
https://github.com/KratosMultiphysics/Kratos/blob/dd7ee6320f8185188856331fb0ad21ba2d289884/kratos/tests/test_linear_constraints.py#L365-L367

**Comment by AlejandroCornejo** [comment]
> In those cases you can add a `skiptest` when using elements from apps. E.g.:
> 
> https://github.com/KratosMultiphysics/Kratos/blob/dd7ee6320f8185188856331fb0ad21ba2d289884/kratos/tests/test_linear_constraints.py#L365-L367

That's magnificent! I'll do it

**Comment by AlejandroCornejo** [comment]
@philbucher I've added a test in which I check the print of integration point variables: vectors (were working previously) and scalar entities (now bugfixed). THX!

**Review by philbucher — APPROVED** [review]
nice!
Also I recommend using the `pathlib` module instead of `os.path`. It is a "new" module that handles everything related to file paths much nicer and natively
https://docs.python.org/3/library/pathlib.html

**Pull request merged**
