### PR TITLE
Some warnings in the DEM application are fixed

### PR DESCRIPTION
**Pull request by maceligueta**

### CODE REVIEW

**Review by GuillermoCasas — APPROVED** [review]
Nice. I see fabs is only for float. I would suggest just turning to std::abs for all cases. Otherwise fine.

**Comment by maceligueta** [comment]
Looks like there's some discussion about what to use:
https://stackoverflow.com/questions/3118165/when-do-i-use-fabs-and-when-is-it-sufficient-to-use-stdabs 
Some people are against using std::abs, because it is more prone to recover the usual error (using abs for doubles).
Maybe @pooyan-dadvand @RiccardoRossi @jcotela have a recommendation.

**Comment by jcotela** [comment]
Regarding the issue with abs, I have had some hard to debug issues in the past where I was doing the wrong thing with `abs` (I missed the `std::`). Now I tend to use fabs when working with doubles to avoid doing the same mistake again. In fact, since the Python `abs` behaves like the C++ `std::abs`, for me forgetting the `std` is a very easy mistake to make when switching languages.

Having said that, I think the code you are reviewing here is a good candidate for abs (it is an `int` function that is saved in an `int` variable, there is no need to introduce a conversion to `double` and back with fabs)

**Comment by pooyan-dadvand** [comment]
Recently I started to use std::abs instead of fabs. Nevertheless I see the point @jcotela mentioning and maybe sticking to old solution may result less harmful!

**Comment by maceligueta** [comment]
Let's leave the code as it is, then. 'fabs' for doubles and 'abs' for integers. If the general policy changes for Kratos, we will replace them all.
One possibility would be to create the macro KRATOS_ABS, equivalent to std::abs. In this way we would never forget 'std'.

**Comment by pooyan-dadvand** [comment]
Another solution would be to default abs in kratos namespace which gives an error saying please use std::abs instead.

**Pull request merged**
