### PR TITLE
[TrilinosApplication] Adding CopyMatrixValues

### PR DESCRIPTION
**Pull request by loumalouomega**
**📝 Description**

Adding CopyMatrixValues

**🆕 Changelog**

- [Adding CopyMatrixValues](https://github.com/KratosMultiphysics/Kratos/commit/ab488536aa672043af55ea473eb3cd75eedf6c75)
- [Adding test for CopyMatrixValues](https://github.com/KratosMultiphysics/Kratos/commit/78d2410d1e11d44d5fb070589d3e067418430ded)

### CODE REVIEW

**Review by jcotela — COMMENTED** [review]
The copy function iterates twice on the rows of both matrices to insert values one by one, which seems quite expensive. Can we use the ReplaceGlobalValues method of the distributed matrix to do it row by row?

https://docs.trilinos.org/dev/packages/epetra/doc/html/classEpetra__CrsMatrix.html#a36048758bcfe082ca07090569607d574

**Comment by loumalouomega** [comment]
> The copy function iterates twice on the rows of both matrices to insert values one by one, which seems quite expensive. Can we use the ReplaceGlobalValues method of the distributed matrix to do it row by row?
> 
> [docs.trilinos.org/dev/packages/epetra/doc/html/classEpetra__CrsMatrix.html#a36048758bcfe082ca07090569607d574](https://docs.trilinos.org/dev/packages/epetra/doc/html/classEpetra__CrsMatrix.html#a36048758bcfe082ca07090569607d574)

Thanks, I haven't seen that!

**Comment by loumalouomega** [comment]
Fixed @jcotela

**Comment by loumalouomega** [comment]
This is ready @jcotela

**Comment by loumalouomega** [comment]
It was included in another PR

**Pull request closed without merging**
