### PR TITLE
[Iga] Shell 3p test

### PR DESCRIPTION
**Pull request by tteschemacher**
This PR updates the test for the shell_3p.

### CODE REVIEW

**Comment by dagmawibekel** [comment]
This branch doesn't compile, because of this line 713 in shell_3p_element.cpp
```
        KRATOS_CHECK_VARIABLE_KEY(DISPLACEMENT);
```
Does this also happen to you @tteschemacher?

**Comment by tteschemacher** [comment]
Can be, actually. You can merge core/add_iga_to_ci into this branch. 

Fell free to push it afterwards. I don't know why this flag does not work here. However, I removed it anyways.

**Comment by tteschemacher** [comment]
core/add_create_quadrature_points_to_python merge also that one...

**Comment by tteschemacher** [comment]
closing this PR. the test is now added within #9116

**Pull request closed without merging**
