### PR TITLE
WIP removing outdated python scripts from the FluidDynamicsApplication

### LINKED ISSUE #871: Standard Python solvers for the Fluid Dynamics Application
We need to do a bit of clean-up of the FluidDynamicsApplication python solvers: right now we have a lot of them and abundant duplication. I think this would also be a good opportunity to settle on a common solver class and a uniform way of dealing with processes or, at the very least, have a set of "clean and nice" solvers that work from GiD.

Tasks:

- [x] Identify minimal set of needed python solvers for the different combinations: monolithic/embedded/fractional step, openMP/MPI...

- [x] Ensure that all "clean" solvers derive from the base fluid_solver class, modifying it if needed.

- [x] Ensure that this minimal set of solvers work properly from the GiD interface.

- [x] Remove as many of the "old" solvers as possible.

### PR DESCRIPTION
**Pull request by jcotela**
Closes #871

### CODE REVIEW

**Comment by philbucher** [comment]
@jcotela I don't think this closes #871 , the issue also contains a "todo" list of things that should be updated in the fluid solvers

**Comment by philbucher** [comment]
ping, this conflicts a lot with #5192

**Review by rubenzorrilla — DISMISSED** [review]
This has been opened for 7 weeks with no complains. Taking into account what @philbucher points out, I think we should merge it.

**Comment by philbucher** [comment]
ping @jcotela

**Comment by jcotela** [comment]
Guys this is not ready. Several tests in the FluidDynamicsApplication still use the outdated solvers, I need to rewrite them before trying to merge it (hence why I created this as a draft)

**Comment by philbucher** [comment]
oh ok, sorry for the noise

**Comment by jcotela** [comment]
All tests in the fluid dynamics application have been updated to use the latest solvers. Some minor changes were required in some of the solvers, but most are bugfixes in rarely used parts of the code. I think I can move them to a separate PR if required.

@roigcarlo please let me know how should we proceed in terms of updating the python imports. I tried to fix those that I found in this PR, but I do not think I got all of them.

**Comment by roigcarlo** [comment]
@jcotela I am afraid its handwork :( I made a filter that more or less marks all the incorrect imports if you want to take a look 

`grep -Prn '^[\s\t\r]*(import|from) ((?!(Kratos)).)*$'` 

Which should mark possible problematic problems. But we can take care in the other Pr after merging this. I think it will be easier.

**Comment by jcotela** [comment]
@roigcarlo does it help if I do the change for the solvers in this PR?

**Comment by roigcarlo** [comment]
It dosn't break anything. If its better to solve them here good for me

**Comment by jcotela** [comment]
@roigcarlo I tried to fix the files in this PR to match the changes in yours, hopefully this will help in merging the eventual conflicts...

**Review by philbucher — APPROVED** [review]
Looks good to me, thx for the effort

**Review by rubenzorrilla — APPROVED** [review]
Thanks!

**Pull request merged**
