### PR TITLE
[External] Remove AMatrix library

### PR DESCRIPTION
**Pull request by loumalouomega**
**📝 Description**

`AMatrix` migration was initialized long time ago but never finalized. After all this time we can remove it and focus in future transition for `mdpan` in STL.

**🆕 Changelog**

- [Remove AMatrix library](https://github.com/KratosMultiphysics/Kratos/commit/87b4f59fb89032ec7b7adf88830c32f0bef5db43)
- [Remove from CMake](https://github.com/KratosMultiphysics/Kratos/commit/06b30e155829b066f4be4b895b9751284f07bc7f)
- [Clean up AMatrix usage](https://github.com/KratosMultiphysics/Kratos/commit/4fe61e24031fce87b17c41777cce21de8cd7bccf)

### CODE REVIEW

**Review by rubenzorrilla — COMMENTED** [review]
I checked all the changes one by one and all of them are correct. I also think that it's time to remove the A-matrix support.

My opinion is that this can be merged. However, I'd briefly discuss it in the next @KratosMultiphysics/technical-committee meeting just in case.

@loumalouomega thanks for the effort (I should also acknowledge the no-aesthetics :smiling_face_with_tear:)

**Comment by loumalouomega** [comment]
> @loumalouomega thanks for the effort (I should also acknowledge the no-aesthetics 🥲)

image

**Comment by philbucher** [comment]
RIP :skull:

**Comment by roigcarlo** [comment]
FMatrix. 

Also agree

**Review by rubenzorrilla — APPROVED** [review]
@KratosMultiphysics/technical-committee agrees with the `AMatrix` removal. Thanks for the clean up.

**Pull request merged**
