### PR TITLE
updated to pybind 2.6.0

### PR DESCRIPTION
**Pull request by philbucher**
**Description**
This PR updates Kratos to [pybind 2.6](https://github.com/pybind/pybind11/releases/tag/v2.6.0) (so far we used 2.4.3 => #6496)

best additions:
- When overridding classes and not calling `__init__` in python it now gives a proper error and doesn't segfault! See #3000
    e.g.: `TypeError: Kratos.Process.__init__() must be called when overriding __init__`
- better fix for #7106 

**TODOs**:
- [x] @KratosMultiphysics/altair please check this with your toolchain
- [x]  check with Intel compiler
- [x] check if warnings from #7106 are really still gone with Clang 10

### CODE REVIEW

**Comment by philbucher** [comment]
now it works, we even had two bugs in the code which I found through the new version :) (I will make separate PRs)

**Comment by ddiezrod** [comment]
We're in the middle of a quite difficult merge from master branch to our private repository, so it might take a few days for us to check if this works for usl

**Comment by philbucher** [comment]
updates:
- detected issues are fixed on master
- compiles clean and works on Clang 10 :tada:

**Comment by philbucher** [comment]
also works with the Intel compiler :+1:

**Comment by ddiezrod** [comment]
I ran a pipeline in our repository using this branch and evrything ran smoothly. I think its ok from our side @KratosMultiphysics/altair @pooyan-dadvand

**Comment by philbucher** [comment]
thx for checking @ddiezrod 

then everything is checked @KratosMultiphysics/technical-committee

**Comment by pooyan-dadvand** [comment]
I agree with merging it.

**Review by roigcarlo — APPROVED** [review]
🎉

**Review by rubenzorrilla — APPROVED** [review]

**Comment by philbucher** [comment]
the @KratosMultiphysics/technical-committee approves this PR

FYI @KratosMultiphysics/all, please let us know if you encounter problems

**Pull request merged**
