### PR TITLE
DEM fix tests 20 to 25

### PR DESCRIPTION
**Pull request by maceligueta**
The python interface was not exported correctly

### CODE REVIEW

**Comment by maceligueta** [comment]
@roigcarlo I added you as a reviewer because I don't know very well the new pybind interface. I just copied your style from a few lines above.

**Review by roigcarlo — CHANGES_REQUESTED** [review]
Sorry I must have missed that block when porting.

Anyway, the correct way to do this is derive the same python class from which the C++ class is deriving, so instead of everything having `DEMContinuumConstitutiveLaw` as base, should be something like:

```C++
class_<DEM_Dempack, DEM_Dempack::Pointer, DEMContinuumConstitutiveLaw>(m, "DEM_Dempack")
class_<DEM_Dempack2D, DEM_Dempack2D::Pointer, DEM_Dempack>(m, "DEM_Dempack2D")
```
etc...

Could you change that?

**Comment by maceligueta** [comment]
Thanks! great that you saw it. I had done it, but it was unsaved in my IDE!

**Review by roigcarlo — APPROVED** [review]
Jaja fine then 👍

**Pull request merged**
