### PR TITLE
Clean structural mechanics python solver scripts

### PR DESCRIPTION
**Pull request by msandre**
The point of this PR is to clean up the code structure in the python solver scripts.

The main issues were:
- having a common interface to all solvers (through the base class)
- providing internal getter methods to access linear solver, schemes, builder, etc. without having to check if or where they were created. 
- reducing copies of the default settings and other code as much as possible

All structural mechanics tests passed.

### CODE REVIEW

**Review by loumalouomega — APPROVED** [review]
Thanks a lot for all this work, probably I will commit the same changes in my solvers for contact

**Comment by msandre** [comment]
Thanks for approving.

**Comment by e-dub** [comment]
Getting the following error after this pull:

```
  File "/home/user/opt/kratos/applications/StructuralMechanicsApplication/python_scripts/structural_mechanics_static_solver.py", line 53, in __init__
    super().__init__(main_model_part, custom_settings)
TypeError: super() takes at least 1 argument (0 given)
```

See attached for a minimum script in which this error occurs.

Am i doing something wrong here? Or is there an error?

[BarTestError.py.txt](https://github.com/KratosMultiphysics/Kratos/files/1104587/BarTestError.py.txt)

**Comment by msandre** [comment]
It's probably because of the python version you are using. The above syntax is specific to python3. I will try pushing the older syntax so it works for python2 as well.

**Comment by msandre** [comment]
@e-dub The change has been merged. Please tell me if you still have a problem.

**Comment by e-dub** [comment]
Thanks!  That solves the one problem, but it looks like there are some further errors (or changes that I have not taken care of):

I previously created the mechanical solver with
```
Solver._CreateMechanicalSolver(...options...)
```
Am I correct in seeing that this is no completed with 
```
Solver._create_mechanical_solver()
```
It now looks like I am missing an assignment for computing_model_part_name that was previously completed with 
```
Solver.computing_model_part_name = "BarTest"
```

The full error message:
```
Traceback (most recent call last):
  File "/home/user/DesOpt/Models/Truss3BarKratos/BarTestError.py", line 59, in <module>
    Solver._create_mechanical_solver()
  File "/home/user/opt/kratos/applications/StructuralMechanicsApplication/python_scripts/structural_mechanics_static_solver.py", line 105, in _create_mechanical_solver
    mechanical_solver = self._create_linear_strategy()
  File "/home/user/opt/kratos/applications/StructuralMechanicsApplication/python_scripts/structural_mechanics_static_solver.py", line 131, in _create_linear_strategy
    computing_model_part = self.GetComputingModelPart()
  File "/home/user/opt/kratos/applications/StructuralMechanicsApplication/python_scripts/structural_mechanics_solver.py", line 198, in GetComputingModelPart
    return self.main_model_part.GetSubModelPart(self.settings["computing_model_part_name"].GetString())
RuntimeError: Error: There is no sub model part with name : computing_domain

in kratos/includes/model_part.h:1052:ModelPart& ModelPart::GetSubModelPart(const string&)
```

Any suggestions would be much appreciated!
Thanks!

**Comment by msandre** [comment]
Yes, the internal functions of the python solver have changed. The computing_model_part_name is now a parameter (the default name is computing_domain). Your assignment Solver.computing_model_part_name = "BarTest" will be ignored in the new solvers. If you want to give a special name, specify it in the parameters.

**Comment by e-dub** [comment]
Thanks for the quick explanation. Though something is still funky and I am getting the same error message with my part being renamed "computing_domain".  Does it want a part or subpart with this name?

**Comment by msandre** [comment]
It should be a sub model part.

**Pull request merged**
