### PR TITLE
fixing metis compilation

### PR DESCRIPTION
**Pull request by philbucher**
after #3340

### CODE REVIEW

**Review by jcotela — APPROVED** [review]
Thanks for fixing it... I'm sorry I missed this one, I was sure I was compiling metis while developing this, but I guess I was wrong...

**Comment by loumalouomega** [comment]
I will try if this fixes my error with Trilinos

**Comment by philbucher** [comment]
> I will try if this fixes my error with Trilinos

@loumalouomega what do you mean?
For me trilinos compiler fine

**Comment by loumalouomega** [comment]
I was unable to run anything in Trilinos for something related with metis

**Pull request merged**
