### PR TITLE
[IGA] Update python scripts

### PR DESCRIPTION
**Pull request by tteschemacher**
Yo,

as nurbs/brep geometries are now part of the core it is time to remove the deprecated solvers and analysis from the IgaApplication to avoid confusion. In the future it will use those directly from the StructuralMechanicsApplication.

**Changelog**
- Removes the iga python analysis and the iga python solvers
- Updates the kratos_main_iga.py

### CODE REVIEW

**Review by dagmawibekel — APPROVED** [review]
Thanks for cleaning up the app even further. As i was mentioning before, I think we should talk about adding a dependency to the structural mechanics application in the cmakelist. Are there any cons in doing so?

**Comment by tteschemacher** [comment]
Thanks a lot!

I actually wouldn't. In your case that you use an IgaApp Modeler to tesselate and then run a cfd analysis you're not really needing the structural mechanics. I wouldn't mind if you want it. Also soon as soon cls are on the core we are less dependent on it.

**Review by dagmawibekel — COMMENTED** [review]
I didn't know that there is a plan to move the cls into the core. I thought there were just moved from a standalone app into the structural mechanics app. I was just thinking out loud, in order to simplify the workflow as much as possible.

**Comment by tteschemacher** [comment]
Sure. Thanks for that issue. If you prefer to have it I am fine with it.

**Pull request merged**
