### PR TITLE
Pybind/porting fda

### PR DESCRIPTION
**Pull request by roigcarlo**
Porting FD application to pybind11. 

It compiles and works, but the application was for my master thesis and its currently unmaintained, so should be fine.

### CODE REVIEW

**Review by RiccardoRossi — APPROVED** [review]
looks fine to me. i did not compile it though...

**Comment by roigcarlo** [comment]
Mmm its compiling the core twice for some reasom. Seems to be related with the structural application. Let me see.

**Comment by roigcarlo** [comment]
Hooo I see, we destroyed de unity build while we separated the python interface from the structural. I will fix it in a separate PR and merge it here later. I take care.

**Comment by roigcarlo** [comment]
Now should work. At least it was useful for something to port this app :D

**Review by RiccardoRossi — APPROVED** [review]

**Pull request merged**
