### PR TITLE
[Core] replacing boost::array for std::array

### PR DESCRIPTION
**Pull request by philbucher**
Some leftovers I came across
No need to hurry, this can for sure wait until after the vacation

@roigcarlo for me it compiles without including `<array>`, should I do it nevertheless?

### CODE REVIEW

**Comment by roigcarlo** [comment]
Technically we should put it, but being this one in particular I would leave it like that. But just an opinion

**Comment by RiccardoRossi** [comment]
@roigcarlo i would be in favor of the change.

the only thing that worries me a bit is that no include is added, and this is sort of strange...(this is a comment for @philbucher )

**Comment by philbucher** [comment]
@RiccardoRossi I have looked around and I think that `<array>` is included in Boost somewhere.
I will include it to not get problems once we remove boost

**Comment by philbucher** [comment]
the header `<array>` is now included

**Review by RiccardoRossi — COMMENTED** [review]
to me this can be merged, however since i saw @roigcarlo was commenting i will wait for him to comment

**Comment by philbucher** [comment]
ping @roigcarlo

**Review by roigcarlo — APPROVED** [review]
:+1:

**Comment by philbucher** [comment]
thx

**Pull request merged**
