### PR TITLE
[Metis] cleanup

### PR DESCRIPTION
**Pull request by philbucher**
same as #5313 , I deleted the things that I think are not used
This is the first step to cleaning the MetisApp more properly

Let me know if I deleted too much, then I can bring it back.

### CODE REVIEW

**Comment by philbucher** [comment]
ping @pooyan-dadvand @roigcarlo

**Comment by roigcarlo** [comment]
Just to comment, if the DEM guys are still running in mpi the morton partitioner was the one giving good scalability.
Not sure if it is interesting to keep it. In any case I can rewrote it if necessary at any time.

**Comment by philbucher** [comment]
ok thx then I bring back the Morton

**Comment by pooyan-dadvand** [comment]
I think the metis ones are safe to be removed. @jcotela, is it ok for you?

**Comment by jcotela** [comment]
@pooyan-dadvand yes, I think I have only ever used the heterogeneous partitioner and its "in memory" version.

**Comment by philbucher** [comment]
ok now I brought Morton back
Two thoughts in Morton: 
- It has nothing to do with Metis, maybe could be moved to the core (does also NOT depend on MPI)?
- the `MortonDivideInputToPartitionsProcess` is exposed as `MetisDivideNodalInputToPartitionsProcess`

other than that i think this is ready

**Comment by pooyan-dadvand** [comment]
> ok now I brought Morton back
> Two thoughts in Morton:
> 
>     * It has nothing to do with Metis, maybe could be moved to the core (does also NOT depend on MPI)?
> 
>     * the `MortonDivideInputToPartitionsProcess` is exposed as `MetisDivideNodalInputToPartitionsProcess`
> 
> 
> other than that i think this is ready

ping @roigcarlo and @maceligueta

**Comment by maceligueta** [comment]
Currently, DEM does not work in MPI. On top of that, the last person who ran DEM with MPI was @roigcarlo . So Charlie, I will believe your opinion on this.

**Comment by philbucher** [comment]
ping

**Comment by philbucher** [comment]
ping if none has more objections then can we please go ahead?
This is blocking further improvements/cleanup

**Review by pooyan-dadvand — APPROVED** [review]
👍

**Pull request merged**
