### PR TITLE
[Core] thread safe folder creation

### LINKED ISSUE #8863: [MPI] What is the safest way to create folders?
**Description**
@KratosMultiphysics/mpi 

In https://github.com/KratosMultiphysics/Kratos/pull/8835#discussion_r644181533, the following issue was pointed out by @sunethwarna when creating a folder in parallel, especially in clusters:

```
if rank==0:
   os.makedirs(folder_name)
data_comm.Barrier()
```

> Not related to this PR, FYI :)
> 
> We already have problems with this barrier (@adityaghantasala can also confirm). Even in VTK this barrier is not working as it is suppose to. The problem is as following.
> 
> For some reason in the few clusters we checked, even if the rank 0 creates the folder successfully, the folder structure is not updated in some of the computing nodes, hence after the barrier the process complains that the folder is not found when the process uses that created folder in some nodes. The same exact block is present in vtk, which is also sometimes does not help at all. This is not related to this code segment, but it might fail in some clusters. I have experienced this failing a lot. Only way is to run the process ones, and once it fails run it again so in the second time the folder structure is there.
> 
> https://github.com/KratosMultiphysics/Kratos/blob/8e95a20f9984988c33a98e77074f74edf1ce6d45/kratos/input_output/vtk_output.cpp#L234-L241
> 
> So I would not expect this barrier to solve the problem in MPI (This is evident a lot in large MPI cases)

Is this something we can prevent from our side?

@philbucher also proposed replacing the barrier with some wait time so that the filesystem is correctly updated in all ranks:

> It is really only the folder creation at runtime that causes the issues, both in C++ and in Python. This problem has in fact been known for years and I was already in contact with the cluster support but we couldn't figure it out. From the programming POV the code above is (still) correct to me.
> 
> The only thing I haven't tried yet is to change the `Barrier` to an explicit wait for the folder to exist
> ie.e. sth lke this:
> 
> ```
> if !folder_exists && rank==0:
>     create folder
> WaitForFolderToExist() // instead of Barrier
> ```
> 
> My thinking is that there is some latency in the filesystem (this is common in cluster filesystems afaik) and hence the folder is not yet "visible" on all ranks

### PR DESCRIPTION
**Pull request by philbucher**
**📝 Description**
The PR solves the issues with folder creation that we have in MPI parallel simulations, esp on Clusters that have slow filesystems. Up until now we had to create any directory structure upfront to avoid runtime failure.

---

**Brief problem description**
Oftentimes we would do sth like this:
~~~py
if rank==0:
   os.makedirs(folder_name)
data_comm.Barrier()
~~~

unfortunately as discussed in #8863 the barrier might not work here as slow filesystems might need more time to create the dir. Hence on some ranks the dir might not be visible yet and hence the succeeding calls that use the dir might fail

one solution to this problem would be to wait until the folder exists:
~~~py
if rank == 0:
    os.makedir(file_path)

while not os.path.exists(file_path):
    time.sleep(1)
~~~

While this theoretically works, still one problem remains: This requires that all the ranks do the same calls to create the directories, however this is not the case
Consider that e.g. rank 0 creates folder "results/abc" and rank 1 creates "results/def". At the time when they create the dirs, they don't know abt each other hence syncronization cannot be used

---

**Solution**
My solution is quite straight forward in the sense that without any synchronization it attempts to create the directories and fails silently if it fails (bcs e.g. some rank might have already created it, or does so at the same time). 
It then waits for a short period and checks if the dir exists now. If it does, then perfect, if not, then it attempts again to create it

@mpentek @mtnzguillermo @sunethwarna could you please give this a test run on the cluster, I already modified the parts of the code where folders are created

---

@marcnunezc can you try it too please? I don't know where you create directories, so maybe you need to update some calls

closes #8863

### CODE REVIEW

**Review by roigcarlo — DISMISSED** [review]
I've been looking all weekend for a clean solution bull all of them are ugly or are linux specific. :(

I can't make it fail so :+1:

**Comment by philbucher** [comment]
> Ok that would be great!

done!

**Review by roigcarlo — APPROVED** [review]

**Comment by philbucher** [comment]
FYI @roigcarlo @rubenzorrilla @jginternational for me this worked great so far
I used this extensively with > 2000 processes and it has not failed me once :D

**Comment by jginternational** [comment]
> FYI @roigcarlo @rubenzorrilla @jginternational for me this worked great so far
> I used this extensively with > 2000 processes and it has not failed me once :D

Thanks @philbucher

**Pull request merged**
