### PR TITLE
[CORE] Move BUILD_LEVEL variable to core

### PR DESCRIPTION
**Pull request by qaumann**
I would like to propose to move BUILD_LEVEL to the core. It can be used to tell the scheme which part of the system (mass, stiffness, damping, etc.) to build. At the moment, it is used in `StructuralMechanics`' `EigensolverStrategy` and in #6111, it is used to obtain the mass resp. stiffness matrix in Python.

Perhaps @KratosMultiphysics/hromapplication needs something like this, too?

### CODE REVIEW

**Comment by philbucher** [comment]
ok to me, seems general enough :+1: 
(you know that you could define the same var in two apps right?)

**Comment by RiccardoRossi** [comment]
i would propose to define an enum for the BUILD_LEVEL.

so that one could write something like

~~~cpp
rCurrentProcessInfo[BUILD_LEVEL] = BuildLevels.COMPUTE_MASS_MATRIX
~~~

**Comment by philbucher** [comment]
but what does the lumped mas matrix have to do with the build-level?

**Comment by rubenzorrilla** [comment]
> i would propose to define an enum for the BUILD_LEVEL.
> 
> so that one could write something like
> 
> ```c++
> rCurrentProcessInfo[BUILD_LEVEL] = BuildLevels.COMPUTE_MASS_MATRIX
> ```

I'm wondering if it makes sense to enhance or replicate this enum to use it for other purposes (e.g. Fractional Step strategy steps).

**Comment by philbucher** [comment]
@RiccardoRossi @rubenzorrilla I think for such purposes sth like `SolverFlags` would make more sense, `enum` seems a bit limited to me for this purpose. I discussed this with @jcotela some time ago:
Basically the `ProcessInfo` would get a `Variable` of type `Flags` for solver-specific things
we then thought mainly about e.g. `COMPUTE_REACTIONS` but other things like the MassMatrix I could also see there
i.e.
~~~c++
class SolverFlags
CREATE_FLAG(COMPUTE_REACTIONS);
CREATE_FLAG(COMPUTE_LUMPED_MASS_MATRIX);
// ...
~~~
The fractionalstep not really, since it is fluid specific, there I think the way it is currently done is good.

this would also make it possible to set them from e.g. processes. E.g. for the computation of the drag the reactions have to be computed. Right now there is no way for the drag-process to set or even check it.

**Comment by loumalouomega** [comment]
My problem with enums is that you cannot register as variables directly, you register int, and do static casts

**Comment by qaumann** [comment]
> 
> 
> ok to me, seems general enough 👍
> (you know that you could define the same var in two apps right?)

@philbucher yes, I did it like this in the first place. But are the variables cross-compatible regarding the apps? So if I set some application's BUILD_LEVEL and access StructuralMechanic's BUILD_LEVEL  (e.g. in an element), do I access the same variable?

I actually like the flag idea. I am now using the build level as some kind of switch in the elements to determine which kind of damping matrix should be built (so a similar problem as choosing a consistent or a lumped mass matrix). Right now, this is only possible using integer codes for each kind of matrix, but a flag would enhance the readability, in my opinion. Is the availability of flags somehow limited or can they be accesses everywhere where process info is available?

**Comment by RiccardoRossi** [comment]
guys, the difference is that an enum is a named int and can contain mutiple
options.

i not against ALSO adding flags, but remember that we will have to define
the flags in the core and that we will not be able to add freely new ones
(definitely not by app).

**Comment by roigcarlo** [comment]
What is the status of this?

**Comment by philbucher** [comment]
lets reopen if relevant
Nothing in 4 years kinda shows its outdated

**Pull request closed without merging**
