### PR TITLE
[Core] Add resize to pointer vector

### PR DESCRIPTION
**Pull request by tteschemacher**
A new intent.

This is #6275 with a small bug fix and a little bit of clean up.

### CODE REVIEW

**Review by loumalouomega — COMMENTED** [review]
I prefer to @RiccardoRossi to approve

**Comment by tteschemacher** [comment]
@pooyan-dadvand , this is as discussed today.

**Review by pooyan-dadvand — APPROVED** [review]
Just for the record, using resize would fill the vector with nullptr and should be filled correctly afterward.

**Comment by tteschemacher** [comment]
Thank you. 

For use with advanced users, or the ones who love to debug. ;)

**Pull request merged**
