### PR TITLE
[Core] Remove Incorrect Members from PointerHashMapSet

### PR DESCRIPTION
**Pull request by matekelemen**
## Description

`PointerHashMapSet` wraps an `std::unordered_map`, yet has members associated with contiguous arrays (`PointerHashMapSet::front` and `PointerHashMapSet::back`).

I took the liberty of making some cosmetic updates as well, but the main change is this one: c951dec.

### CODE REVIEW

**Comment by matekelemen** [comment]
ping @KratosMultiphysics/technical-committee

**Review by RiccardoRossi — APPROVED** [review]

**Comment by roigcarlo** [comment]
I also think changes are good, can we merge?

**Comment by loumalouomega** [comment]
> I also think changes are good, can we merge?

I agree

**Comment by rubenzorrilla** [comment]
@matekelemen what about this?

**Pull request merged**
