### PR TITLE
[StructuralMechanicsApplication] Replace Warning for Info

### PR DESCRIPTION
**Pull request by loumalouomega**
Generating to much verbosity and this is not a warning if doesn't inform about something wrong or potentially wrong

### CODE REVIEW

**Comment by philbucher** [comment]
I disagree abt this warning not being informative 
If you dont add the submodelparts to the computingmodelpart then it wont be considered!
Esp for larger models this is annoying to debug!
Where do you get the warnings?

I made this based on experiences I made with larger models (that can have many submodelparts and also subsubmodelparts)

**Comment by loumalouomega** [comment]
> I disagree abt this warning not being informative
> If you dont add the submodelparts to the computingmodelpart then it wont be considered!
> Esp for larger models this is annoying to debug!
> Where do you get the warnings?
> 
> I made this based on experiences I made with larger models (that can have many submodelparts and also subsubmodelparts)

In the problems we added today, I don't know what this is informing about. It is just printing the name of the submodelparts, nothing else

**Comment by philbucher** [comment]
Oh I see
Will fix it tmr, sorry for the inconvenience

**Comment by loumalouomega** [comment]
Not a problem

**Comment by philbucher** [comment]
Fixed it, now it only issues a warning if sth is actually missing
I also updated most of the tests, except the adjoint ones since I did not get how they work

@armingeiser @MFusseder can you please do this along with the other adjoint-related cleanup that I told you about?

**Review by philbucher — APPROVED** [review]

**Pull request merged**
