### PR TITLE
[StructuralMechanicsApplication] Solid. Adding missing Set/GetValueOnIntegrationPoints for CL

### PR DESCRIPTION
**Pull request by loumalouomega**

### CODE REVIEW

**Comment by philbucher** [comment]
just curious: what is the use-case of this?

**Comment by loumalouomega** [comment]
It is used by the internal values interpolation process from the Meshing
Application. I am cleaning and improving the process, and I cherry picked
this commit.

**Comment by loumalouomega** [comment]
Anyone?

**Comment by philbucher** [comment]
Seems ok to me :)

**Review by philbucher — APPROVED** [review]

**Comment by loumalouomega** [comment]
Thanks

**Pull request merged**
