### PR TITLE
[DEM] Spheres glued to walls 

### PR DESCRIPTION
**Pull request by maceligueta**
This pr adds the capability to glue some spheres to FEM walls (rigid or coming from a structure).
Test included for the rigid walls.
Also a fix for a change in the API of the conditions slipped in.

### CODE REVIEW

**Review by GuillermoCasas — COMMENTED** [review]
If I am not mistaken, you are taking the velocity of the particle center as that of the sticking point. However, there should be a differece WRT the center of the particle. That difference can be calculated as (minus) r X omega, where r is the position of the sticking point WRT the particle center.

**Comment by maceligueta** [comment]
You are right, in principle that’s what I’m doing in line 98 and previous. For the velocity of the sphere, we must consider the omega of the triangle.

**Comment by GuillermoCasas** [comment]
Oh, I see, I missed that bit. I suggest you to add a comment indicating this part as a separate section, just like you did above. Good job

**Comment by maceligueta** [comment]
If everything is OK, can someone approve? It would be nice to have this in master branch.

**Review by salvalatorre — APPROVED** [review]

**Pull request merged**
