### PR TITLE
Adding single value send/recv implementation.

### PR DESCRIPTION
**Pull request by jcotela**
**📝 Description**
We are missing single-value send/recv implementations (as opposed to std::vectors of values), but those are being used in the tests, which means that MPIDataCommunicator defaults to the serialized send/recv version and generates a warning.
This PR implements single-value send/recv reusing the existing std::vector implementation.

FYI @sunethwarna, let me know if we should wait to merge this one too (or feel free to merge yourself when you think it is safe)

**🆕 Changelog**
- Add single value send-recv

### CODE REVIEW

**Comment by sunethwarna** [comment]
Hi @jcotela, would it be ok if I integrate this change to the #11433 PR?

**Comment by jcotela** [comment]
@sunethwarna as you prefer, either that or we wait until #11433 is merged, as I don't think this is particularly critical

**Comment by jcotela** [comment]
Note: I expect the version after merge to fail some mpi tests (at least it is doing so on my machine), switching to draft until I can look into it some more

**Comment by sunethwarna** [comment]
I am also on this :)

**Review by sunethwarna — APPROVED** [review]
Thanks @jcotela ...

**Comment by sunethwarna** [comment]
Apparently still the CI fails with a weird error. My PC, all tests are passing without a problem... :/ I'll also keep checking...

**Comment by sunethwarna** [comment]
Ok, #11458 fixed the problem. :)

**Comment by jcotela** [comment]
Thanks @sunethwarna, merging.

**Pull request merged**
