### PR TITLE
[Trilinos] remove custom gid io

### PR DESCRIPTION
**Pull request by philbucher**
I want to clean up the trilinos-app a bit and move/clean the appropriate things to the MPI-Core (#2945)

The custom-gid stuffs from the Trilinos-App is not being used anywhere, so I think we can let it go :)

### CODE REVIEW

**Comment by philbucher** [comment]
FYI @KratosMultiphysics/technical-committee

**Comment by jcotela** [comment]
I am in favor of going ahead and removing this, but we should check whether someone is using it. I will raise this in the next meeting of the @KratosMultiphysics/technical-committee

**Review by jcotela — APPROVED** [review]
@KratosMultiphysics/technical-committee approves.

**Comment by philbucher** [comment]
thanks

**Pull request merged**
