### PR TITLE
Methods converted into function templates, so they can be applied to isolated particles or clusters

### PR DESCRIPTION
**Pull request by maceligueta**
**📝 Description**
As reported in #9791, the code was crashing when trying to acces information from a cluster. The dynamic cast was being done to SphericParticle, hence the problem when it is a Cluster3D

**🆕 Changelog**
Some methods have been 'templated' ('templatized'?) to accept single particles or clusters. This should fix the issue

If it works, this PR solves #9791 @VeronikaSinger @KlausBSautter

### CODE REVIEW

**Comment by VeronikaSinger** [comment]
Dear @maceligueta 
unfortunately it does not compile on my windows machine. The error is reported here: https://github.com/KratosMultiphysics/Kratos/blob/master/applications/DEMApplication/custom_python/add_custom_utilities_to_python.cpp#:~:text=.def(%22DestroyParticlesOutsideBoundingBox%22%2C%20%26ParticleCreatorDestructor%3A%3ADestroyParticlesOutsideBoundingBox)

**Comment by maceligueta** [comment]
The last trick did not work @roigcarlo . We can always move everything to the header file, no?

**Comment by maceligueta** [comment]
It seems it is compiling now. I checked that it does not crash in linux. @VeronikaSinger can you check if it crashes in Windows? Also please check if the overall behaviour is as expected. I need to write a test for this. If merging is urgent I can add the test in a different PR.

**Comment by KlausBSautter** [comment]
thanks @maceligueta I'll check my simulations

**Comment by VeronikaSinger** [comment]
Thanks for fixing the issue. The example now works as expected.

**Review by roigcarlo — DISMISSED** [review]

**Comment by KlausBSautter** [comment]
Let me check my example, for a second. I am still compiling :/

**Comment by KlausBSautter** [comment]
Thanks, it works :). I'll let you merge as soon as you are ready.

**Comment by maceligueta** [comment]
The example provided by @VeronikaSinger showed a problem with conflicting ids when printing for GiD. I fixed it for that example, but now the thests are failing. I am on it.

**Comment by maceligueta** [comment]
Finally, everything seems to work fine. The example provided by @VeronikaSinger was added as a test and some extra improvements were made to prevent (to some extent) the repetition of similar problems.
This can be merged in my opinion.

**Comment by VeronikaSinger** [comment]
Thanks @maceligueta my examples are all working perfectly now.

**Review by VeronikaSinger — APPROVED** [review]

**Pull request merged**
