### PR TITLE
[StructuralMechanics] removing validation suite from allsuite

### PR DESCRIPTION
**Pull request by philbucher**
after #3472 the validation tests take very long, therefore I am removing the validationsuite from the allsuite

I am not particularly happy about this change but this is also done in other apps
I am just concerned that now the test won't be run any more bcs they take too long

@KratosMultiphysics/technical-committee do you have a guideline for how long validation-tests should run?

### CODE REVIEW

**Comment by loumalouomega** [comment]
All suite is supposed to be all, I am still thinking that is easier to just run:

~~~sh
python3 test_StructuralMechanicsApplication.py -l nightly/small
~~~

**Comment by philbucher** [comment]
hm either way it should be consistent across apps
lets wait for @KratosMultiphysics/technical-committee

**Comment by roigcarlo** [comment]
We decided some time ago that validation tests were excluded from the `all` option, and `validation` should instead contain all. What I don't know right know if there is a option to run the validation (should exists).

so you should be able to run 
-l nightly/small/all(default)/validation

**Review by loumalouomega — APPROVED** [review]

**Comment by philbucher** [comment]
thanks @roigcarlo :+1: 
@loumalouomega I would still be happy if the validation-tests would not take hours ;)

**Comment by roigcarlo** [comment]
Part of the problem is our current infrastructure. Lets hope soon I can set up the new server to see if we can scale this up :)

**Comment by loumalouomega** [comment]
> thanks @roigcarlo +1
> @loumalouomega I would still be happy if the validation-tests would not take hours ;)

I reduced the original time of the test from 10 s to 3 s. And if we want to avoid new problems from the CL it is an important test

**Comment by philbucher** [comment]
wait, the "TensileTestStructuralTest" takes over 6 MINUTES on my machine, are you sure it is that fast in yours?

**Comment by loumalouomega** [comment]
> wait, the "TensileTestStructuralTest" takes over 6 MINUTES on my machine, are you sure it is that fast in yours?

I mean that I was computing from second 0.854 to second 10 s with Delta Time= 0.005

**Comment by philbucher** [comment]
ah ok now I got it

**Comment by pooyan-dadvand** [comment]
@roigcarlo I don't remember when we have decided that and I don't like the idea of taking out the some cases from all. I understand that we should take them from nightly but not from all.

Of course we should all try our best to reduce the time of any individual test....

**Comment by roigcarlo** [comment]
I believe we decided that when we agreed to add the validation tests as a different level of tests. If we did not, I apologize.

The idea of validation cases, if I remember correctly, were to act as a replacement of the old benchmarks, and were not meant to run with the rest (or at least that's what I understood)

Probably if the case takes only 5 minutes there is no need to even add it there.

**Comment by pooyan-dadvand** [comment]
Sorry, I didn't wanted to question your memory which is better than mine! I simply was not remember it so I could not justify it correctly....

**Comment by roigcarlo** [comment]
Just for the record at @KratosMultiphysics/technical-committee we have rediscussed this and we have a solution, which will requiere some changes of names, I will implement it during next week

**Pull request merged**
