### PR TITLE
NavierStokesTwoFluidsSolver with BFECC LS convection

### PR DESCRIPTION
**Pull request by mrhashemi**
**Description**
Resolving the segmentation fault.

### CODE REVIEW

**Review by rubenzorrilla — COMMENTED** [review]
If there's a memory leak, I don't see how this modification can solve it. Can you point to where the segfault is occurring? (I'm afraid that the error is still there).

**Comment by mrhashemi** [comment]
> If there's a memory leak, I don't see how this modification can solve it. Can you point to where the segfault is occurring? (I'm afraid that the error is still there).

Code stops at
https://github.com/KratosMultiphysics/Kratos/blob/5d33e770a09c2111fbc871e99c74a23ba14900f8/applications/ConvectionDiffusionApplication/custom_utilities/bfecc_convection.h#L233

This implies the problem with the search database.

**Comment by rubenzorrilla** [comment]
> > If there's a memory leak, I don't see how this modification can solve it. Can you point to where the segfault is occurring? (I'm afraid that the error is still there).
> 
> Code stops at
> 
> https://github.com/KratosMultiphysics/Kratos/blob/5d33e770a09c2111fbc871e99c74a23ba14900f8/applications/ConvectionDiffusionApplication/custom_utilities/bfecc_convection.h#L233
> 
> This implies a problem with the search database. Without any provisions during the definition, locator would look for what is returned by UpdateSearchDatabase().

My point is that the modifications that you suggest are equivalent to the previous version of the code, so I don't understand how the memory leak is fixed. The unique thing that comes to my mind is that the `locator` could destroyed when leaving the scope of the function (however I don't think this is what it's happening as the BFECC uses a shared pointer).

**Comment by mrhashemi** [comment]
> > > If there's a memory leak, I don't see how this modification can solve it. Can you point to where the segfault is occurring? (I'm afraid that the error is still there).
> > 
> > 
> > Code stops at
> > https://github.com/KratosMultiphysics/Kratos/blob/5d33e770a09c2111fbc871e99c74a23ba14900f8/applications/ConvectionDiffusionApplication/custom_utilities/bfecc_convection.h#L233
> > 
> > This implies a problem with the search database. Without any provisions during the definition, locator would look for what is returned by UpdateSearchDatabase().
> 
> My point is that the modifications that you suggest are equivalent to the previous version of the code, so I don't understand how the memory leak is fixed. The unique thing that comes to my mind is that the `locator` could destroyed when leaving the scope of the function (however I don't think this is what it's happening as the BFECC uses a shared pointer).

Any suggestion?

**Comment by rubenzorrilla** [comment]
> > > > If there's a memory leak, I don't see how this modification can solve it. Can you point to where the segfault is occurring? (I'm afraid that the error is still there).
> > > 
> > > 
> > > Code stops at
> > > https://github.com/KratosMultiphysics/Kratos/blob/5d33e770a09c2111fbc871e99c74a23ba14900f8/applications/ConvectionDiffusionApplication/custom_utilities/bfecc_convection.h#L233
> > > 
> > > This implies a problem with the search database. Without any provisions during the definition, locator would look for what is returned by UpdateSearchDatabase().
> > 
> > 
> > My point is that the modifications that you suggest are equivalent to the previous version of the code, so I don't understand how the memory leak is fixed. The unique thing that comes to my mind is that the `locator` could destroyed when leaving the scope of the function (however I don't think this is what it's happening as the BFECC uses a shared pointer).
> 
> Any suggestion?

Bf... Have you tried with GDB?

**Comment by mrhashemi** [comment]
> > > > > If there's a memory leak, I don't see how this modification can solve it. Can you point to where the segfault is occurring? (I'm afraid that the error is still there).
> > > > 
> > > > 
> > > > Code stops at
> > > > https://github.com/KratosMultiphysics/Kratos/blob/5d33e770a09c2111fbc871e99c74a23ba14900f8/applications/ConvectionDiffusionApplication/custom_utilities/bfecc_convection.h#L233
> > > > 
> > > > This implies a problem with the search database. Without any provisions during the definition, locator would look for what is returned by UpdateSearchDatabase().
> > > 
> > > 
> > > My point is that the modifications that you suggest are equivalent to the previous version of the code, so I don't understand how the memory leak is fixed. The unique thing that comes to my mind is that the `locator` could destroyed when leaving the scope of the function (however I don't think this is what it's happening as the BFECC uses a shared pointer).
> > 
> > 
> > Any suggestion?
> 
> Bf... Have you tried with GDB?

**GDB:**

Thread 1 "python3" received signal SIGSEGV, Segmentation fault.
0x00007fffef1365e2 in std::__shared_ptr<Kratos::BinsObjectDynamic<Kratos::SpatialContainersConfigure<2ul, Kratos::Element> >, (__gnu_cxx::_Lock_policy)2>::get (this=0x10)
    at /usr/include/c++/9/bits/shared_ptr_base.h:1310
1310	      { return _M_ptr; }

**Comment by mrhashemi** [comment]
> > > > > > If there's a memory leak, I don't see how this modification can solve it. Can you point to where the segfault is occurring? (I'm afraid that the error is still there).
> > > > > 
> > > > > 
> > > > > Code stops at
> > > > > https://github.com/KratosMultiphysics/Kratos/blob/5d33e770a09c2111fbc871e99c74a23ba14900f8/applications/ConvectionDiffusionApplication/custom_utilities/bfecc_convection.h#L233
> > > > > 
> > > > > This implies a problem with the search database. Without any provisions during the definition, locator would look for what is returned by UpdateSearchDatabase().
> > > > 
> > > > 
> > > > My point is that the modifications that you suggest are equivalent to the previous version of the code, so I don't understand how the memory leak is fixed. The unique thing that comes to my mind is that the `locator` could destroyed when leaving the scope of the function (however I don't think this is what it's happening as the BFECC uses a shared pointer).
> > > 
> > > 
> > > Any suggestion?
> > 
> > 
> > Bf... Have you tried with GDB?
> 
> **GDB:**
> 
> Thread 1 "python3" received signal SIGSEGV, Segmentation fault.
> 0x00007fffef1365e2 in std::__shared_ptr<Kratos::BinsObjectDynamic<Kratos::SpatialContainersConfigure<2ul, Kratos::Element> >, (__gnu_cxx::_Lock_policy)2>::get (this=0x10)
> at /usr/include/c++/9/bits/shared_ptr_base.h:1310
> 1310 { return _M_ptr; }

@rubenzorrilla any idea?

**Review by rubenzorrilla — APPROVED** [review]
I finally had time to go through it. At the end the issue is way simpler than what I thought at the beginning. It doesn't find anything because the `locator` variable is empty as what it is stored in there is the return of the `UpdateSearchDataBase` function.

Thanks for the fix and sorry for the delay :wink:.

**Pull request merged**
