### PR TITLE
[Core][Geometry] Geometry data number of geometries and scoped enum

### PR DESCRIPTION
**Pull request by rubenzorrilla**
**📝 Description**
Though the large number of modified files, this PR has only two minor changes:

1. It makes the `IntegrationMethod`, `KratosGeometryFamily` and `KratosGeometryType` in the  `GeometryData` class scoped enums instead of plain enums. This is possible since c++11 and avoids automatic casting to `int` as well as (in my opinion) makes clearer from where are these retrieved, as the `GeometryData` scope needs to be specified.
2. According to what we decided in #8852 it adds the `NumberOfGeometryFamilies` and `NumberOfGeometryTypes` entries, which can be used to retrieve the number of geometry families and types.

All the other changes are required to accomplish with these two modifications of the `geometry_data.h`.

closes #8852

### CODE REVIEW

**Comment by tteschemacher** [comment]
cool. Thanks!

**Review by loumalouomega — APPROVED** [review]

**Comment by loumalouomega** [comment]
The fastest we merge this, the less conflict we will have

**Comment by rubenzorrilla** [comment]
> The fastest we merge this, lesser conflict we will have

Thanks @loumalouomega

**Review by roigcarlo — APPROVED** [review]
:+1:

**Pull request merged**
