### PR TITLE
[FSIApplication] Use parameter constructor to create discontinuous distance process

### PR DESCRIPTION
**Pull request by marcnunezc**
**📝 Description**
After #9567, this creates the discontinuous distance process using parameters instead of flags. 

Could we add a test that uses this or test this PR with a working example?

**🆕 Changelog**
- Use parameters to construct discontinuous distance process in partitioned embedded solver.

### CODE REVIEW

**Review by rubenzorrilla — APPROVED** [review]
Thanks! About the test... we could try to create a "fake" problem to only check the first step. I'll think about it.

**Comment by marcnunezc** [comment]
No longer needed as it was added in #9881. Closing PR

**Comment by loumalouomega** [comment]
Do I delete the branch?

**Comment by marcnunezc** [comment]
> Do I delete the branch?

Sorry I forgot!

**Comment by loumalouomega** [comment]
> > Do I delete the branch?
> 
> Sorry I forgot to delete it!

image

**Pull request closed without merging**
