### PR TITLE
Navier-Stokes symbolic element modifications

### PR DESCRIPTION
**Pull request by rubenzorrilla**
Linearisation of the convective term is now done by default.

### CODE REVIEW

**Comment by pooyan-dadvand** [comment]
I agree with the changes but IMO it is somehow misleading that you have your python file in the documentation folder. It is not more appropriate to have  them in some symbolic generation folder?

**Comment by rubenzorrilla** [comment]
The symbolic generator script comes with a .lyx file explaining the implemented formulation. In my opinion this files should be in the same directory. Maybe we can rename the "documentation" folder to "symbolic_generation" and keep it as it is?

**Comment by loumalouomega** [comment]
I don't think so, the documentation can be necessary for different purposes, not just symbolic formulation. In any case I am not very friend of LyX, because they are changing the standard for the file every time, and this is not a procedure. Maybe a simple *.tex file with the corresponding pdf willbe better

**Comment by RiccardoRossi** [comment]
i personally prefer the .lyx since it is much more visual and easier to maintain than a .tex

**Comment by pooyan-dadvand** [comment]
I respect your personal preference for tex editor and we don't have any standard for that. (Meanwhile I agree with Vicente about non standard features of lyx) but my point was the .py file which is there. it is like putting the cpp file of element also there to be with the documentation. I would still move the .py file to the some symbolic_generation folder. And always you can have a comment in .py file mentioning the documentation file (i.e. a link to the repository)

**Comment by loumalouomega** [comment]
I ma agree with @pooyan-dadvand , I was speaking with Ruben, I can create the template for the *.tex file. We can add custom_symbolic_generation folder to the application folder. The discussion is if to include the documentation in the application folder or create a different repository just for documentation (I personally vote for this solution). Doing this we can reuse some files

**Comment by pooyan-dadvand** [comment]
I am even OK with having them in the application folder but in separate folders

**Comment by rubenzorrilla** [comment]
Thus, we have a "custom_symbolic_generation" folder which contains:
- the symbolic generation *.py files
- the required *.ccp or *.h template files
Besides, a "documentation" folder contains all the *.tex files to generate de application documentation. 

What I like about @loumalouomega  suggestion about having an independent repo.  for the documentation is that we can include all the *.tex files compiled in *.pdf format.

**Comment by RiccardoRossi** [comment]
+1 for Pooyan's comment

**Comment by RiccardoRossi** [comment]
my preference would be to have the documentation to contain
1  the py for the generator
2 the lyx, tex, doc or whatever file that describes the implementation
3 the header and cpp used in the same element.

i think however that this is something to be voted. I'll comply with the decision.

Riccardo

**Comment by RiccardoRossi** [comment]
@loumalouomeg

**Comment by RiccardoRossi** [comment]
sorry, i closed without wanting it

**Review by RiccardoRossi — COMMENTED** [review]
there are some files that should not be in there (the gifs)

**Pull request closed without merging**
