### PR TITLE
[Mapping] Split into core/py-interface and minor cleanup

### PR DESCRIPTION
**Pull request by philbucher**

### CODE REVIEW

**Review by roigcarlo — DISMISSED** [review]

**Comment by philbucher** [comment]
guess I need to spilt into appCore and app-PyInterface

**Comment by roigcarlo** [comment]
Yup, if its not splitted this PR basically would break the app :S

**Comment by philbucher** [comment]
@roigcarlo here what we discussed some days ago happens: for some reason the mappers that get registered disappear :/
This mechanism hasn't changed in a long time, no clue why this happens now. IMO this PR should be unrelated

Could you please have a look?
The mappers get registered here: https://github.com/KratosMultiphysics/Kratos/blob/master/applications/MappingApplication/mapping_application.cpp#L46-L49

they are saved in a static var: https://github.com/KratosMultiphysics/Kratos/blob/master/applications/MappingApplication/custom_utilities/mapper_factory.h#L182-L189

I think I asked this before, do you think the `static` var in the header could be a problem? I think it is ok but not sure

I would really appreciate if you could take a look :)

**Comment by philbucher** [comment]
hmmm I think the `static` in the header is the problem.

By separating the core from the py-interface this header gets included in both and I think then two versions exist.
Now it is quite interesting that this works with GCC :)

@pooyan-dadvand @roigcarlo any idea?
@pooyan-dadvand the CoSimIO will have the same problem
=> here I can ofc move it to the cpp, but this will not work for the CoSimIO...

**Comment by philbucher** [comment]
@pooyan-dadvand this is what I mean. I think it is the same problem as here...
https://github.com/KratosMultiphysics/CoSimIO/blob/master/co_sim_io/impl/co_sim_io_impl.hpp#L32

**Comment by philbucher** [comment]
Summary of this PR:
- MappingApp was splitten into core/py-interface
- `KRATOS_API` was added
- mpi-related files were moved to subdirectories
- CMake was cleaned (using `GLOB`)
- the registration issue in the `MapperFactory` was fixed by moving the `static` member to cpp

Lets hope this also works in Win :)

**Comment by philbucher** [comment]
@peterjwilson could you please try to run the MappingApp-tests on this branch? I want to make sure I didn't break it for you
Thx

**Comment by philbucher** [comment]
Finally it works :D

**Comment by philbucher** [comment]
can someone approve please?
(I spoke with @peterjwilson he said it works for him)

**Review by roigcarlo — APPROVED** [review]

**Comment by philbucher** [comment]
thx

**Pull request merged**
