### PR TITLE
[Core] removing deprecated interface of Element, Condition & Scheme

### LINKED ISSUE #7381: Interfaces of Element, Condition and Scheme updated
Dear @KratosMultiphysics/all

After many issues in the past (e.g. with race conditions) the @KratosMultiphysics/technical-committee decided to clean up and improve the interfaces of `Element`, `Condition` and `Scheme`. See #4938, #6643 and #5290.

The changes are done **FULLY BACKWARD COMPATIBLE** (please check the PRs for technical details), hence he updating can be done in multiple steps!!!
The Core and many applications have already been updated!

The main changes are adding `const` to the `ProcessInfo` that is passed to the functions. This is to avoid race conditions.

The following changes were done:
- `Element` & `Condition`:
    - All instances of `ProcessInfo` are being passed as `const`
    - The following functions are `const` functions now:
        - `GetValuesVector`
        - `GetFirstDerivativesVector`
        - `GetSecondDerivativesVector`
        - `Check`
    - `Initialize` gets an instance of `const ProcessInfo&` now
    - `CalculateLocalSystem` with `std::vector` is removed as unused
    - `GetValueOnIntegrationPoints` is deprecated in favor of `CalculateOnIntegrationPoints`. The functions have the same signature, hence search-replace is sufficient

- `Scheme`:
    - All instances of `ProcessInfo` are being passed as `const`
    - Element and Condition are no longer passed as `Pointer` but as reference
    - The function names starting with `Condition_` have the `Condition_` removed i.e. the names for Element and Condition are the same now

The following procedure is suggested for updating the code:
1. Update the c++ tests (if existing) to use the new interfaces, see e.g. #7366
2. Update the interfaces see e.g. #7371
In case some results change it is very likely that a race condition. If you cannot find the issue please let us know

Please check & update your applications. The timeline is (to be confirmed by @KratosMultiphysics/technical-committee):
- activating the deprecation warnings: 2 months from now, end of October
- removing the deprecated functions: 5 months from now, end of January

Please don't hesitate to ask questions if something is unclear!

The following applications have been updated already (if it was necessary)

- CableNetApplication
- ChimeraApplication
- CompressiblePotentialFlowApplication
- ConstitutiveModelsApplication
- ContactStructuralMechanicsApplication
- CoSimulationApplication
- CSharpWrapperApplication
- EigenSolversApplication
- ExaquteSandboxApplication
- ExternalSolversApplication
- FluidDynamicsApplication (partly)
- FreeSurfaceApplication
- FSIApplication
- HDF5Application
- LinearSolversApplication
- MappingApplication
- MeshingApplication
- MeshMovingApplication
- MetisApplication
- MultilevelMonteCarloApplication
- RomApplication
- ShapeOptimizationApplication
- StatisticsApplication
- StructuralMechanicsApplication (mostly)
- TrilinosApplication
- UmatApplication

### PR DESCRIPTION
**Pull request by philbucher**
**Description**
This is the very last step in updating the interfaces, as described thoroughly in #7381 

closes #7381

will be merged end of January

### CODE REVIEW

**Comment by philbucher** [comment]
It seems like there are still quite a few applications not updated:
- DEM @KratosMultiphysics/dem 
- FluidDynamics @KratosMultiphysics/fluid-maintainers Note that this also causes 4 other apps to fail (SwimmingDEM, Chimera, PotentialFlow & RANS) due to dependencies
- ParticleMechanics @KratosMultiphysics/mpm 
- Iga: @tteschemacher 
- ConvectionDiffusion @rubenzorrilla (not sure who else to tag)
- StructuralMechanics @loumalouomega it fails in the Solids and the SolidShell, can you please have a look

(Side node for @rubenzorrilla: The FSIApp tests fail without StructuralMechanics, you are missing a `SkipTest`)

For fixing the problems can you please push your changes to master (if possible) as this branch contains sensitive changes and I would like to keep it as small as possible to keep the overview of the changes.

Thx for the help!

**Comment by loumalouomega** [comment]
> It seems like there are still quite a few applications not updated:
> 
>     * DEM @KratosMultiphysics/dem
> 
>     * FluidDynamics @KratosMultiphysics/fluid-maintainers Note that this also causes 4 other apps to fail (SwimmingDEM, Chimera, PotentialFlow & RANS) due to dependencies
> 
>     * ParticleMechanics @KratosMultiphysics/mpm
> 
>     * Iga: @tteschemacher
> 
>     * ConvectionDiffusion @rubenzorrilla (not sure who else to tag)
> 
>     * StructuralMechanics @loumalouomega it fails in the Solids and the SolidShell, can you please have a look
> 
> 
> (Side node for @rubenzorrilla: The FSIApp tests fail without StructuralMechanics, you are missing a `SkipTest`)
> 
> For fixing the problems can you please push your changes to master (if possible) as this branch contains sensitive changes and I would like to keep it as small as possible to keep the overview of the changes.
> 
> Thx for the help!

I have done my part :+1:

**Comment by philbucher** [comment]
thx @loumalouomega
it seems like the Contact also doesn't compile, can you take another look? Thx

@riccardotosi also the MultiLevelMC App is not compiling, can you please have a look?

**Comment by loumalouomega** [comment]
> thx @loumalouomega
> it seems like the Contact also doesn't compile, can you take another look? Thx

Where?

**Comment by philbucher** [comment]
Idk exactly, but the CI complains. I think in the py-interface

**Comment by riccardotosi** [comment]
> 
> 
> thx @loumalouomega
> it seems like the Contact also doesn't compile, can you take another look? Thx
> 
> @riccardotosi also the MultiLevelMC App is not compiling, can you please have a look?

Done in #8098. In my machine the application compiles now.

**Comment by loumalouomega** [comment]
> Idk exactly, but the CI complains. I think in the py-interface

I see warnings, not errors, can you point me where is the problem

**Comment by philbucher** [comment]
> > Idk exactly, but the CI complains. I think in the py-interface
> 
> I see warnings, not errors, can you point me where is the problem

you are right, sorry for the noise
there are too many warnings in the build, even I lost the overview...

**Comment by philbucher** [comment]
@riccardotosi it seems like you are missing a `skiptest` for the FluidApp in the MLMC tests, can you please add it (in a separate PR) Thx

**Comment by riccardotosi** [comment]
> @riccardotosi it seems like you are missing a `skiptest` for the FluidApp in the MLMC tests, can you please add it (in a separate PR) Thx

I will. However, why the FluidApp is not being found?

**Comment by philbucher** [comment]
> > @riccardotosi it seems like you are missing a `skiptest` for the FluidApp in the MLMC tests, can you please add it (in a separate PR) Thx
> 
> I will. However, why the FluidApp is not being found?

I disabled it temp as it doesn't compile

in any case all apps should be able to have their tests run even if other apps are not there without crashing (except if apps are dependent like PotentialFlow on FluidDynamics)

**Comment by philbucher** [comment]
@sunethwarna seems like also RANS doesn't compile, can you take a look please?

**Comment by philbucher** [comment]
@maceligueta @GuillermoCasas seems like SwimmingDEM also needs some updates, can you please take a look?

**Comment by maceligueta** [comment]
> @maceligueta @GuillermoCasas seems like SwimmingDEM also needs some updates, can you please take a look?

Sure, I am following this, but did not have time today to fix it. It's one of my first priorities.

**Comment by sunethwarna** [comment]
I'm also on it now

**Comment by maceligueta** [comment]
As requested, I put my changes in a different PR: #8121

**Comment by sunethwarna** [comment]
I checked RANSApplication compiled with clang in release, I don't see much difference in the test time. I am not sure why this has a time out now :/

**Comment by philbucher** [comment]
Now everything works, thx for the efforts everyone :heart: 

I will merge this next Friday, 29.

**Review by RiccardoRossi — APPROVED** [review]
This is the final commit for the cleanup announced in #7381 .
approving on behalf of @KratosMultiphysics/technical-committee .

@KratosMultiphysics/all please note that this might break some thing that was left unported.

**Review by rubenzorrilla — APPROVED** [review]
I cross-checked the changes again. Everything seem fine to me to.

**Comment by philbucher** [comment]
Merging at 00:01 as per request of @rubenzorrilla

**Pull request merged**
