### PR TITLE
[FastPR][FSI] Enabling contact FSI

### PR DESCRIPTION
**Pull request by rubenzorrilla**
Activating the contact process list in the FSI analysis.

### CODE REVIEW

**Review by loumalouomega — APPROVED** [review]

**Comment by philbucher** [comment]
I am curious, why is this necessary?
It is not necessary to prescribe the order of the processes in a pure structural simulation

**Comment by rubenzorrilla** [comment]
> I am curious, why is this necessary?
> It is not necessary to prescribe the order of the processes in a pure structural simulation

Otherwise the contact processes wouldn't be considered in the FSI analysis.

**Comment by philbucher** [comment]
hm then there is sth very wrong happening
This list only specifies the order in which the processes are constructed
as long as the processes are inside the `processes` block in the json the should be constructued. If not we have a global problem in the `AnalysisStage`

**Comment by rubenzorrilla** [comment]
> hm then there is sth very wrong happening
> This list only specifies the order in which the processes are constructed
> as long as the processes are inside the `processes` block in the json the should be constructued. If not we have a global problem in the `AnalysisStage`

mmmm... I think you're right. Otherwise the old cases wouldn't work and this is not the case. In any case I'd keep it for the sake of consistency.

**Comment by philbucher** [comment]
> I'd keep it for the sake of consistency.

up to you but now it is inconsistent with the `StucturalAnalysis`

**Pull request merged**
