### PR TITLE
Cleaned ALE solvers.

### PR DESCRIPTION
**Pull request by msandre**
This PR cleans up the python scripts for ALE mesh motion solvers. The main reasons for this are to make the code easier to maintain/extend by

1) removing/cleaning unused code
2) eliminating copied code
3) making the python solvers conform to kratos (Initialize(), InitializeSolutionStep(), etc.)

 I added as reviewers those who might be affected by these changes.

### CODE REVIEW

**Review by rubenzorrilla — APPROVED** [review]
For me it's ok. I will update the FSI solvers once this is merged to the master. Thanks @msandre !

**Comment by rubenzorrilla** [comment]
@msandre , just a simple doubt. In these updated solvers, is there still the option of just doing the MoveNodes() without solving the mesh problem as before?

**Comment by msandre** [comment]
I renamed MoveNodes to MoveMesh. It does the same thing as before. The reason for this was that MoveMesh is defined in the base strategy and according to the comments there, it should be overridden by the derived class to do the same operation that MoveNodes was doing. The renaming just makes it more conforming to the base class methods.

**Comment by rubenzorrilla** [comment]
Ok @msandre ! Thank you again.

**Comment by rubenzorrilla** [comment]
@msandre last but not least, do you think that these changes should be in the release version? After a short discussion, @RiccardoRossi and me agree that we should keep them for the next one. The reason is to avoid modifications in the FSI module. In any case I will add your modifications to my FSI branch (which will be merged to the master during the next days).

**Comment by msandre** [comment]
Hi @rubenzorrilla, I agree with your decision to postpone these changes until the next release.

**Comment by msandre** [comment]
The only thing is I already merged the changes into master so depending on how you guys are compiling the release, you may need to checkout the ALEApplication from the older commit.

**Comment by jcotela** [comment]
@msandre The Relase thing is on a separate branch, so it should be ok to merge all new stuff to master.

**Pull request merged**
