### PR TITLE
[Core[Element/Condition] removing GetValuesVec, 7381

### PR DESCRIPTION
**Pull request by philbucher**
**Description**
Part of #7381 
I am removing those functions already now, as calling the const fct is quite painful if the non-const one still exists.
Hence they still give many deprecation warnings and we want to remove as many as possible for the release
AFAIK most apps are updated already, and even if we missed sth adding a few `const` will solve the issue

### CODE REVIEW

**Comment by tteschemacher** [comment]
Sweet. Thanks a lot!

**Review by tteschemacher — APPROVED** [review]

**Review by RiccardoRossi — COMMENTED** [review]
Hi @philbucher we cannot yet remove such functions for good since there may be some "untracked" apps off the repository that would get broken (I wish we could!).

Let's set a deadline (@KratosMultiphysics/technical-committee ) and enforce it

**Review by RiccardoRossi — COMMENTED** [review]
i would propose to merge the changes in the app, but not the ones in element.h and condition.h

**Comment by philbucher** [comment]
> Hi @philbucher we cannot yet remove such functions for good since there may be some "untracked" apps off the repository that would get broken (I wish we could!).
> 
> Let's set a deadline (@KratosMultiphysics/technical-committee ) and enforce it

@RiccardoRossi I am well aware. Here are the reasons why I still think this should go it ASAP:
- this change was announced months ago
- all apps that are in the CI are updated
- to my knowledge also many/most apps in the repo that are not in the CI are updated
- in the worst case sth does no longer compile, but updating the code is super easy, only adding a few `const`
- **Main reason 1**: As we (@RiccardoRossi and I) have experienced a lot is that those updates can cause nasty problems if the caller (e.g. the `Scheme`) doesn't force the compiler to use the `const` version of this method. Hence this can lead to segfaults if the new fct is implemented in the Element, but still the old one is called from the (custom) Scheme (Core schemes are working fine). I think that especially for code in non-CI apps it would be much better to have the compiler tell me what I did wrong (aka using an old fct) rather than random segfaults
- **Main reason 2**: For the upcoming release we want to be as warning free as possible. And there are still some warnings related to this that would be completely gone with this change

**Review by RiccardoRossi — APPROVED** [review]
approving on behalf of @KratosMultiphysics/technical-committee 

@KratosMultiphysics/all please beware that this may break code that is not in the CI. Please look into #7381 for instructions about how to do the porting

**Comment by pooyan-dadvand** [comment]
@KratosMultiphysics/altair  This may affect us in some elements.

**Pull request merged**
