### PR TITLE
Contatc clean python-scripts

### PR DESCRIPTION
**Pull request by philbucher**
this should work, but please also check it yourself

### CODE REVIEW

**Review by loumalouomega — DISMISSED** [review]
This is going to conflict a lot....

**Comment by philbucher** [comment]
If you don’t want it then we don’t have to merge it
I just thought I‘d be nice and update the apps since I change sth in the core :)
Up to you

**Comment by loumalouomega** [comment]
> If you don’t want it then we don’t have to merge it
> I just thought I‘d be nice and update the apps since I change sth in the core :)
> Up to you

Let's do it

imagen

**Comment by philbucher** [comment]
did you run the tests?

We could also update the py-interface to the final version after this I think (i.e. the one that no longer adds `python_scripts` to the `PYTHON_PATH`)
This way you will be on the safe side once the old interface becomes deprecated

**Comment by loumalouomega** [comment]
> did you run the tests?
> 
> We could also update the py-interface to the final version after this I think (i.e. the one that no longer adds `python_scripts` to the `PYTHON_PATH`)
> This way you will be on the safe side once the old interface becomes deprecated

Ok, then wait until tomorrow

**Comment by loumalouomega** [comment]
I checked, now it runs

**Review by loumalouomega — APPROVED** [review]

**Pull request merged**
