### PR TITLE
[IGA] 3p shell tests using the iga test factory

### PR DESCRIPTION
**Pull request by tteschemacher**
**Description**
This adds the test examples by @MichaelLoibl for the KL-3p shell.

**Changelog**
- linear beam
- non linear beam
- non linear beam - more refined
- scordelis lo-roof

### CODE REVIEW

**Comment by philbucher** [comment]
can you please reduce the size of the files you add?
Rule of thumb is < 1000lines for input files

then they should also run fast enough for the CI

**Comment by tteschemacher** [comment]
The examples are not that huge (between 25 - 320 nodes). CAD files cannot really be compared to standard mdpa files as the json format produces a lot of overhead in lines.

**Review by MichaelLoibl — COMMENTED** [review]
The nonlinear_beam_thick_sd_p3_nCP83 was included in order to check the accuracy of the computation of the internal forces, which required the recomputation of the internal force vector (therefore, nonlinear computation). I don't know if you have already included the computation of the internal forces but they are not included in the results file. Therefore, I would remove the example for shortness because it doubles with the example nonlinear_beam_thick_p2_nCP22.

**Comment by tteschemacher** [comment]
Closing as this has been merged already within a different branch.

**Pull request closed without merging**
