### PR TITLE
cmake fix policy

### PR DESCRIPTION
**Pull request by philbucher**

### CODE REVIEW

**Comment by philbucher** [comment]
hm @oberbichler @roigcarlo could you please have a look? The CI started failing today, but I don't understand why
and only in Win :sweat_smile:

**Comment by roigcarlo** [comment]
@philbucher I been searching and seems that problem can come from the fact that BOOST_ROOT is technically not set, maybe it had a residual value and they have deleted now, so that causes a lot of warnings and errors to pop out. 

The policy error is extrange because if a relative path is used on BOOST_INCLUDE_DIR that means it has been set by the FindBOOST module, which is part of cmake and we use the new policy for the BOOST_ROOT var anyway, so I doubt that is the problem.

Anyway, just elucubrating, let's see if this works :S.

**Comment by philbucher** [comment]
ok cool now it works again, thx @roigcarlo 

Can someone approve this please? CI is failing until this is merged!

**Review by peterjwilson — APPROVED** [review]

**Comment by loumalouomega** [comment]
Ups I thought this was already merged, and I conflicted many PR :P

**Comment by roigcarlo** [comment]
I am lost. what happened? Why are all the tests failing now?

**Comment by philbucher** [comment]
Its fine, only some tests in the nightly fail. This happens sometimes, those checks are not required

**Comment by roigcarlo** [comment]
Ok but we should take a look. I didn't remember this happening. Half of them are due to windows not being able to read scaped chars and at least one is because is trying to use the external solvers app without checking if it exists. I think those could be fixed...

**Comment by philbucher** [comment]
> windows not being able to read scaped chars

those are my tests, sorry I am on it

>  use the external solvers app without checking if it exists

@loumalouomega

**Comment by loumalouomega** [comment]
> 
> 
> > windows not being able to read scaped chars
> 
> those are my tests, sorry I am on it
> 
> > use the external solvers app without checking if it exists
> 
> @loumalouomega

which tests?

**Comment by philbucher** [comment]
nightly on all systems
https://github.com/KratosMultiphysics/Kratos/actions/runs/84305105

**Comment by loumalouomega** [comment]
OK, these are MPC tests, that fail due to OMP error, but I need time to find the origin

**Comment by philbucher** [comment]
that is ok, but many tests use the `ExternalSolversApp` but don't have the corresponding `skipTest`

**Comment by loumalouomega** [comment]
OK; I will change the solvers when I find a moment

**Comment by philbucher** [comment]
@loumalouomega check the new methods: 
https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/python_scripts/KratosUnittest.py#L38-L42
https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/python_scripts/KratosUnittest.py#L106-L112

**Pull request merged**
