### PR TITLE
Added IsInside Function

### PR DESCRIPTION
**Pull request by philbucher**
Copy Pasted from the other lines, for some reason missing for this type
UPDATE: Found another missing Function (ShapeFunctionValues), also copy pasted from the 2D version

### CODE REVIEW

**Review by jcotela — CHANGES_REQUESTED** [review]
Please do not modify .gitignore, to get git to ignore your files you should follow the procedure described in 
https://github.com/KratosMultiphysics/Kratos/wiki/How-to-make-Git-ignore-the-files-resulting-from-a-compilation-without-conflicts-in-.gitignore

**Comment by philbucher** [comment]
@jcotela Thanks for the comment, was my bad

**Review by pooyan-dadvand — CHANGES_REQUESTED** [review]
I see that you are using the shape function values for checking is inside. This check is only valid if the node is in the line (but may or not in the segment) So I would suggest you to first find the projection and if it is on the line use the shape functions.

**Comment by loumalouomega** [comment]
@pooyan-dadvand I did that for the line_2d, it is in the #270, the previous LocalCoordinates was giving problems

**Comment by philbucher** [comment]
@pooyan-dadvand I see your point and changed my implementation
I think it is necessary to define a clear behavior then, i.e. do IsInside() functions do projections or not? I mean what I did was just copy paste from the other Lines, so I am a bit confused
According to what @loumalouomega  does the IsInside() function should do projection?

**Comment by jcotela** [comment]
As an external user, I'd expect the IsInside() functions to project the input if the geometry has less dimensions than the space it is defined on (lines in 2D and 3D, triangles in 3D,...), otherwise it will simply be wrong for inputs that do not lie on the same line or plane as the geometry. For geometries that have the same dimension as the work space (lines in 1D, triangles in 2D, tetras in 3D) no projection is necessary.

If it is not the case in existing geometries, I'd be inclined to think it is a bug.

**Pull request closed without merging**
