### PR TITLE
[Core] Clean up exception.h

### PR DESCRIPTION
**Pull request by loumalouomega**
Just that, little bit of clean up

### CODE REVIEW

**Review by philbucher — APPROVED** [review]

**Comment by philbucher** [comment]
@roigcarlo here CI also crashes :/

**Comment by loumalouomega** [comment]
> @roigcarlo here CI also crashes :/

Strange, this just changes tabulations and add some documentation

**Comment by philbucher** [comment]
Its an msvc bug, see #6583

**Comment by philbucher** [comment]
Only now it also appears in our CI 
Since two hours or so

**Pull request merged**
