### PR TITLE
[MeshingApplication] Using non-historical NODAL_H

### PR DESCRIPTION
**Pull request by loumalouomega**

### CODE REVIEW

**Review by AlejandroCornejo — APPROVED** [review]

**Comment by pooyan-dadvand** [comment]
@loumalouomega and @AlejandroCornejo this is a very important behaviour change and as members of @KratosMultiphysics/implementation-committee you should be guardian against such a silent changes instead of promoting it in a very small PR with no comment, no discussion, no alarm,  nor a convincing reason...  

Considering that each value in data value container has a pointer as overhead, for a double it would double the size....

**Comment by pablobecker** [comment]
I can see the point in being non-historical since this is not a historical value, so we have the cost of the pointer but we save on not being historical. I can see the non-historical being better if only a minor part of the model part uses it.

Still, other apps/processes may be relying on this, we should make sure no other apps use this before prcoeeding.

**Comment by loumalouomega** [comment]
This only affects the MeshingApplication and processes and utilities that I implemented myself, besides this was the reason of a memory problem in Windows that was solved with this

**Comment by pablobecker** [comment]
how did this fix a memory problem?

**Comment by loumalouomega** [comment]
I don't know exactly the reasons, it only happened in the Windows compilation and it was solved with this change

**Comment by pooyan-dadvand** [comment]
@loumalouomega My argument is not about why (which I don't agree neither) but about the way you have pushed the changes. If something is public in core applications you cannot assume that you are the only user of it without consulting it publicly....

**Comment by loumalouomega** [comment]
Understood. I have a similar branch ready (to reduce the number of templates and reduce the compilation time), but I am doing tests to be sure that nothings is broken

**Comment by AlejandroCornejo** [comment]
@loumalouomega @pooyan-dadvand I agree that we could have informed more, sorry about that. We thought that no one was using that except us. We will take this comments into account.

Again, sorry for the inconvenience

**Pull request merged**
