### PR TITLE
Merging ConnectivityPreserveModeler and MPIConnectivityPreserveModeler

### PR DESCRIPTION
**Pull request by jcotela**
Now we have a ConnectivityPreserveModeler which correctly processes SubModelParts and MPIConnectivityPreserveModeler which does not understand SubModelParts but correctly copies the Communicator in MPI. I'm proposing to merge both in a single class.

I have also tried to clean up the code, and divided it into header and source parts. In addition, I moved the ConnectivityPreserveModeler header to kratos/modelers (it was in utilities despite deriving from modeler).
Regarding issue #172, for now I'm throwing an error if the Destination is a SubModelPart and we are trying to change its SolutionStepVariablesList.

@jrubiogonzalez: Can you try this branch? C2C is one of the main users of this class, so I'll wait for the merge until I hear back from you.

### CODE REVIEW

**Comment by jrubiogonzalez** [comment]
Ok, give some days.

**Comment by pooyan-dadvand** [comment]
I'm ok with the changes, waiting for @jrubiogonzalez feedback

**Review by RiccardoRossi — APPROVED** [review]
just to tell that i am also in favour of this change. 

my only concern is that since this involves moving from 
the directory "utility" to "modeler" (a correct change) it may break the compilations of some applications

**Comment by jcotela** [comment]
@RiccardoRossi I just checked with grep, I could not find any C++ includes in the application folder (I think most people use this through the Python interface). I agree that it may be a problem for third-party applications, though.

**Comment by RiccardoRossi** [comment]
yes, i guessed so.

my comment was mostly intended "for the records" so that eventually someone may read about this in the future

**Comment by pooyan-dadvand** [comment]
@jrubiogonzalez have you had time to check this?

**Comment by ddiezrod** [comment]
I have checked this in c2c. As far as I can see tables are not being copied into the destination model part. Just by adding something like

      rDestinationModelPart.Tables() = rOriginModelPart.Tables();

everything seems to work fine (at least in my version)

**Comment by jcotela** [comment]
Just added the table copy... It got lost in the upgrade. Thanks @ddiezrod !

**Comment by RiccardoRossi** [comment]
@jcotela i would suggest you push this asap, otherwise if we create a release branch it will require extra work

**Comment by jcotela** [comment]
@RiccardoRossi I don't think this is essential for the release, I'd rather wait.

**Comment by RiccardoRossi** [comment]
Ok

**Pull request merged**
