### PR TITLE
[Core][To Discuss] Add Modeler Stages

### PR DESCRIPTION
**Pull request by tteschemacher**
According to #6343 I added the stages that I see to the modeler. 

Please let me know what you think about it.

### CODE REVIEW

**Comment by rubenzorrilla** [comment]
Just to let you know, we discussed about the possibility of creating a stage between the geometry and the model part ones to do the eventual discretization of the model (something like `DiscretizeGeometry`).

**Comment by tteschemacher** [comment]
Thanks for the update. I suppose that would be corresponding to the GenerateModelPart.

**Comment by rubenzorrilla** [comment]
> Thanks for the update. I suppose that would be corresponding to the GenerateModelPart.

Not sure at all, If I'm not wrong we thought in an extra intermediate step.

**Comment by tteschemacher** [comment]
I am closing this PR as it got renewed by #6605 . Thanks @rubenzorrilla for your review!

**Pull request closed without merging**
