### PR TITLE
[StructuralMechanicsApplication] Extending structural solver wrapper to work with contact solvers

### PR DESCRIPTION
**Pull request by loumalouomega**
This is a transition PR, the tests are not updated and the duplicated files are not removed yet. It allows to use the structural analysis with contact problems. The only thing needed is to add the import of the ContactStructuralMechanicsApplication to the main script (so it can import the modules). With this I will be able to remove the duplicated wrappers and analysis in the contact app

### CODE REVIEW

**Comment by loumalouomega** [comment]
FYI @rubenzorrilla

**Comment by philbucher** [comment]
Cool feature!
Please wait until I had a closer look, I think this is an important improvement

**Comment by loumalouomega** [comment]
I will extend to adaptive remeshing as soon as https://github.com/KratosMultiphysics/Kratos/pull/4558 is merged

**Comment by philbucher** [comment]
I simplified it, now it is less intrusive
you do NOT need to import the ContactApp in the MainKratos! => importlib takes care of it, I tested it
=> now we can have the same main for pure structural cases and for cases with contact! :)

@loumalouomega if you remove the preceeding `contact_` from your solver names it would be even simpler. To me would make sense, since one has to import from the ContactApp, but up to you

**Review by philbucher — APPROVED** [review]

**Comment by loumalouomega** [comment]
@philbucher Your last change implies to refactor all my current solvers, can you revert for now that last change?, I will not work until I refactor the solvers and  @rubenzorrilla needs this in order to do FSI-Contact test and if this is merged as it is right now he will not able to try anything. We can simplify this later

**Comment by philbucher** [comment]
> @loumalouomega if you remove the preceeding contact_ from your solver names it would be even simpler. To me would make sense, since one has to import from the ContactApp, but up to you

this is only a suggestion, I didn't do this

As it is now it works without any change in the ContactApp

**Comment by loumalouomega** [comment]
OK, thanks. I did a dummy mistake, hehe

**Comment by loumalouomega** [comment]
@rubenzorrilla now the analysis is the same for the contact and the structural. I will remove duplicated scripts in a near future

**Comment by rubenzorrilla** [comment]
Cool. I also thought about this solution.

**Pull request merged**
