### PR TITLE
[Core] Making AssingMaterialToProperty virtual in ReadMaterialsUtility

### PR DESCRIPTION
**Pull request by loumalouomega**
(and protected instead of private)
See #5950

### CODE REVIEW

**Comment by philbucher** [comment]
are you sure you want to make the entire reading optinal
essentially inside `AssingMaterialToProperty` first the CLaw is read, followed by the variables and the tables.
To my understanding only the variables reading will be different right?

**Comment by loumalouomega** [comment]
> 
> 
> are you sure you want to make the entire reading optinal
> essentially inside `AssingMaterialToProperty` first the CLaw is read, followed by the variables and the tables.
> To my understanding only the variables reading will be different right?

Good point, we can decompose in smaller functions. Any case maybe is not so bad idea to make all of them virtual

**Comment by loumalouomega** [comment]
@philbucher Done, divided in different methods

**Review by philbucher — APPROVED** [review]
looks good to me

**Pull request merged**
