### PR TITLE
[Core][All] Fix 4439. Remove deprecated conditions (Condition3D, Condition2D,...)

### LINKED ISSUE #4439: [Core] GetRegisteredName fails for mSurfaceCondition3D3N
The deprecated Conditions like the `mCondition3D` defined in 
https://github.com/KratosMultiphysics/Kratos/blob/d274c0596833d653e4b1996ae60dc1d1a921e8c9/kratos/includes/kratos_application.h#L378

cause the ` CompareElementsAndConditionsUtility::GetRegisteredName` to return the wrong name for the new conditions like e.g. `mSurfaceCondition3D3N`. This is because both are of the type `MeshCondition` and have a `Triangle3D3` geometry. These are the only two things that are compared.

If the deprecated conditions can not be removed for backwardcompatibility reasons, an intermediate solution could be to create a derived class `DeprecatedMeshCondition` that does fully inherit the `MeshCondition`. Like this they could be distinguished.

### PR DESCRIPTION
**Pull request by loumalouomega**
Fixes #4439. Also this PR helps for learning roman numbers

### CODE REVIEW

**Review by rubenzorrilla — APPROVED** [review]
Let's wait for the CI but as far as I see, there shouldn't be any problem.

**Comment by loumalouomega** [comment]
> 
> 
> Let's wait for the CI but as far as I see, there shouldn't be any problem.

Just one thing, ping @jginternational (remove the old ones of the interface)

**Review by rubenzorrilla — CHANGES_REQUESTED** [review]
I thought the GUI was already updated. Blocking until it is ready.

**Comment by loumalouomega** [comment]
> I thought the GUI was already updated. Blocking until it is ready.

I don't know, it is something I asked @jginternational 1 year ago or even more...

**Comment by philbucher** [comment]
seems like you missed some in the RansApp

I also thought the interface was already updated.

**Review by philbucher — APPROVED** [review]
looks good to me, thanks @loumalouomega 
I would have this in asap, we can fix whatever is left afterwards, since it is a very minor thing

**Comment by loumalouomega** [comment]
@rubenzorrilla GUI is fixed in https://github.com/KratosMultiphysics/GiDInterface/pull/730

**Review by rubenzorrilla — APPROVED** [review]
Thanks!

**Pull request merged**
