### PR TITLE
[Core][MeshingApplication] Add appveyor compilation (and fix #5…

### LINKED ISSUE #5: No version in "kratos_version.h"
Due to #4 CMake no longer adds the old svn number to 'kratos_version.h', so version is always X.X.0

The SHA1 must be set by cmake while configuring the project.

### LINKED ISSUE #5656: [Windows] Compilation ERROR in MeshingApplication
Hi!

I've just pulled the master branch and now the code it's not compiling...

One error says:

`Error	C2280	'std::unique_ptr<TDofType,std::default_delete<_Ty>>::unique_ptr(const std::unique_ptr<_Ty,std::default_delete<_Ty>> &)': se está intentando hacer referencia a una función eliminada.	KratosMeshingCore	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include\xmemory0	881	`

And the other is regarding the add_custom_utilities_to_python in the MeshingApp:

`Error	LNK2019	símbolo externo "__declspec(dllimport) void __cdecl Kratos::MeshingUtilities::RecursiveEnsureModelPartOwnsProperties(class Kratos::ModelPart &,bool)" (__imp_?RecursiveEnsureModelPartOwnsProperties@MeshingUtilities@Kratos@@YAXAEAVModelPart@2@_N@Z) sin resolver al que se hace referencia en la función "void __cdecl Kratos::Python::RecursiveEnsureModelPartOwnsProperties(class Kratos::ModelPart &)" (?RecursiveEnsureModelPartOwnsProperties@Python@Kratos@@YAXAEAVModelPart@2@@Z)	KratosMeshingApplication	D:\KRATOS_MULTIPHYSICS\Kratos\cmake_build\applications\MeshingApplication\add_custom_utilities_to_python.obj	1	`

`Error	LNK2019	símbolo externo "__declspec(dllimport) void __cdecl Kratos::MeshingUtilities::EnsureModelPartOwnsProperties(class Kratos::ModelPart &,bool)" (__imp_?EnsureModelPartOwnsProperties@MeshingUtilities@Kratos@@YAXAEAVModelPart@2@_N@Z) sin resolver al que se hace referencia en la función "void __cdecl Kratos::Python::EnsureModelPartOwnsProperties(class Kratos::ModelPart &)" (?EnsureModelPartOwnsProperties@Python@Kratos@@YAXAEAVModelPart@2@@Z)	KratosMeshingApplication	D:\KRATOS_MULTIPHYSICS\Kratos\cmake_build\applications\MeshingApplication\add_custom_utilities_to_python.obj	1	
`

Anyone knows what's happening??

Thank you in advance,

Alejandro

### PR DESCRIPTION
**Pull request by loumalouomega**
Fixes #5656 ?¿ (can you check @AlejandroCornejo, in your error appeared these files, so maybe is related)

Additionally adds the MeshingApplication (no MMG for now) to the appveyor, so we can notices if it breaks

### CODE REVIEW

**Comment by AlejandroCornejo** [comment]
I'll try ASAP to compile it

**Review by philbucher — CHANGES_REQUESTED** [review]
Blocking to wait for the review of @KratosMultiphysics/technical-committee

**Comment by loumalouomega** [comment]
@philbucher and @AlejandroCornejo now it passes the appveyor

**Review by AlejandroCornejo — DISMISSED** [review]
let's see if it solves the problem in Win

**Comment by loumalouomega** [comment]
> let's see if it solves the problem in Win

It does in appveyor

**Comment by philbucher** [comment]
@loumalouomega I think @RiccardoRossi had some comments on the hasing
can you please make a separate PR?

**Comment by loumalouomega** [comment]
> @loumalouomega I think @RiccardoRossi had some comments on the hasing
> can you please make a separate PR?

Ok

**Comment by loumalouomega** [comment]
The modification of key_hash is now #5662 @philbucher @RiccardoRossi

**Review by philbucher — DISMISSED** [review]
ok for me, I think makes sense and somewhere I read that Riccardo is also ok
used by many ppl hence pls go ahead

**Comment by loumalouomega** [comment]
I fixed a compilation error, can you re-approve please?

**Review by AlejandroCornejo — APPROVED** [review]

**Pull request merged**
