### PR TITLE
Fix segfault while ending Kratos

### LINKED ISSUE #1310: Kratos error in windows at the end of the script
In Windows (7 and 10) Kratus currently throws an error after the script has finished.

image

Unfortunately I have only a german windwos: The message says: "runkratos.exe is not working anymore"

The results and everything look fine, it seems that the programm is just not exiting properly.

### PR DESCRIPTION
**Pull request by roigcarlo**
Fixes #1310

### CODE REVIEW

**Comment by jcotela** [comment]
I'm not getting any segfault with this branch (in Linux). The Valgrind errors are gone too (I still get something strange, but I think it is from my test itself).

**Comment by roigcarlo** [comment]
@pooyan-dadvand Ready to merge?

**Comment by pooyan-dadvand** [comment]
I am waiting for codacy...

**Comment by roigcarlo** [comment]
It broke, there was a warning while parsing:

```
CURRENT STATUS: Not Analysed    View logs 1 WARNING
```

**Comment by pooyan-dadvand** [comment]
Meanwhile I have wrote it so I hope someone else review it! @maceligueta, @jcotela or @RiccardoRossi ?

**Review by jcotela — CHANGES_REQUESTED** [review]
Can you use the new Kratos::make_shared, as @loumalouomega is suggesting?
Other than that, 👍

**Comment by pooyan-dadvand** [comment]
This branch was before merging the `Kratos::make_shared `and I would not put another ingredient to it....

**Review by jcotela — APPROVED** [review]
ok go ahead

**Pull request merged**
