### PR TITLE
[DEM] reducing tests computation time

### PR DESCRIPTION
**Pull request by farrufat-cimne**
**Description**
from  #8908 Decreased computation time of the slower tests.

~~~
______________
python3 test_DEM_3D_continuum_vs_discontinuum.py 
 |  /           |
 ' /   __| _` | __|  _ \   __|
 . \  |   (   | |   (   |\__ \
_|\_\_|  \__,_|\__|\___/ ____/
           Multi-Physics 9.0."Dev"-3fff561d625-Release
Compiled with threading support.
Maximum number of threads: 1.
.
----------------------------------------------------------------------
Ran 1 test in 0.455s

Ok

python3 test_DEM_2D_contact.py
 |  /           |
 ' /   __| _` | __|  _ \   __|
 . \  |   (   | |   (   |\__ \
_|\_\_|  \__,_|\__|\___/ ____/
           Multi-Physics 9.0."Dev"-91ebcc0c1d5-Release
Compiled with threading support.
Maximum number of threads: 1.
.
----------------------------------------------------------------------
Ran 1 test in 0.134s

OK


python3 test_kinematic_constraints.py
 |  /           |
 ' /   __| _` | __|  _ \   __|
 . \  |   (   | |   (   |\__ \
_|\_\_|  \__,_|\__|\___/ ____/
           Multi-Physics 9.0."Dev"-91ebcc0c1d5-Release
Compiled with threading support.
Maximum number of threads: 1.
.
----------------------------------------------------------------------
Ran 1 test in 0.233s

OK




NIGHTLY:
python3 test_DEM_search_tolerance.py  |  /           |
 ' /   __| _` | __|  _ \   __|
 . \  |   (   | |   (   |\__ \
_|\_\_|  \__,_|\__|\___/ ____/
           Multi-Physics 9.0."Dev"-3fff561d625-Release
Compiled with threading support.
Maximum number of threads: 1.
....
----------------------------------------------------------------------
Ran 4 tests in 5.300s

OK
~~~

### CODE REVIEW

**Comment by philbucher** [comment]
dont you have to move them back to another suite?

BTW you could use #7818 for checking which tests are slow

**Comment by maceligueta** [comment]
> dont you have to move them back to another suite?
> 
> BTW you could use #7818 for checking which tests are slow

Yep! I used this feature to list all the times. It was great! I sent the results to @farrufat-cimne and @salvalatorre in private email.

**Comment by maceligueta** [comment]
@farrufat-cimne can you move the shrinked tests to the 'small' suite?

**Comment by farrufat-cimne** [comment]
> @farrufat-cimne can you move the shrinked tests to the 'small' suite?

sure

**Review by maceligueta — APPROVED** [review]

**Pull request merged**
