### PR TITLE
[Core] Remove legacy `contact_pair.h`

### PR DESCRIPTION
**Pull request by loumalouomega**
**📝 Description**

In this PR I am removing legacy `contact_pair.h`. It is only use in the `SearchContact` methods, which are unused and completely legacy. So this PR cleans up all related with  `contact_pair.h`, including some inclusion in `MappingApplication` despite not being actually called.

**🆕 Changelog**

- [Remove legacy contact_pair.h](https://github.com/KratosMultiphysics/Kratos/commit/895b3d711f28409d119477d4dda02e817e1af75e)
- [Clean InterfaceObjectConfigure](https://github.com/KratosMultiphysics/Kratos/commit/e4d48982f41af7eb55073f23ae783562e39fe546)
- [Clean up node_configure.h](https://github.com/KratosMultiphysics/Kratos/commit/acddf159458e587a9a6edcefc8dc08a4323d4623)
- [Remove legacy (and unused) SearchContact methods](https://github.com/KratosMultiphysics/Kratos/commit/709be1aa4edcc491735547c8186f66c6a755a746)
- [Cleaning up spatial_containers_configure.h](https://github.com/KratosMultiphysics/Kratos/commit/5896cac1e5a7d4787d553b4c794f837a1eae8cb4)
- Changes from #10970 (unused include)

### CODE REVIEW

**Comment by roigcarlo** [comment]
From the spatial containers point of view, ok. I am unsure what was the usage of the ContactPair class, so lets wait for someone from the contact to confirm changes are ok as well.

**Comment by loumalouomega** [comment]
> From the spatial containers point of view, ok. I am unsure what was the usage of the ContactPair class, so lets wait for someone from the contact to confirm changes are ok as well.

I am the one from the contact, and I don't use it (neither is used in JM contact app). I guess this was used in the legacy StructuralApplication as it was implemented by Nelson.

**Comment by loumalouomega** [comment]
> > From the spatial containers point of view, ok. I am unsure what was the usage of the ContactPair class, so lets wait for someone from the contact to confirm changes are ok as well.
> 
> I am the one from the contact, and I don't use it (neither is used in JM contact app). I guess this was used in the legacy StructuralApplication as it was implemented by Nelson.

Not even: https://github.com/search?q=repo%3AKratosMultiphysics%2FKratosLegacyApplications+SearchContact&type=code

**Review by roigcarlo — DISMISSED** [review]
Ok then

**Comment by loumalouomega** [comment]
> Ok then

I needed to clean up legacy code from DEM app, sorry for the nuisance

**Review by philbucher — APPROVED** [review]

**Pull request merged**
