### PR TITLE
[Pfem2] modularity

### PR DESCRIPTION
**Pull request by miguelmaso**
This PR adds a new python process in order to use PFEM2 with other apps

### CODE REVIEW

**Review by ipouplana — DISMISSED** [review]
Great!

**Review by GuillermoCasas — CHANGES_REQUESTED** [review]
Great! However, as we discussed in person, there is quite a lot of copied code in the derived strategy. This is not really your fault, since the way in which the scheme is set in class `PFEM2NavierStokesMonolithicSolver` that derives from `NavierStokesSolverMonolithic` forces you to. I would suggest encapsulating this part in the father class `NavierStokesSolverMonolithic` if, e.g.,  @rubenzorrilla agrees and just modifying the corresponding function (e.g., 'GetScheme') in the derived class.
In addition to this, the name of PFEM2 application is not in camelCase; perhaps you could think about fixing that too, here or in an upcoming PR.

**Comment by philbucher** [comment]
> Great! However, as we discussed in person, there is quite a lot of copied code in the derived strategy. This is not really your fault, since the way in which the scheme is set in class `PFEM2NavierStokesMonolithicSolver` that derives from `NavierStokesSolverMonolithic` forces you to. I would suggest encapsulating this part in the father class `NavierStokesSolverMonolithic` if, e.g.,  @rubenzorrilla agrees and just modifying the corresponding function (e.g., 'GetScheme') in the derived class.
In addition to this, the name of PFEM2 application is not in camelCase; perhaps you could think about fixing that too, here or in an upcoming PR.

I agree with @GuillermoCasas, we had the same struggle too

@jcotela @rubenzorrilla one way to reduce the necessary code-duplication would be to define e.g. `_GetScheme` or `_GetBuilderAndSolver` like we do in the python-solvers in StructuralMechanics (where it has proven to be useful imo)

**Comment by rubenzorrilla** [comment]
Hi all!

I am currently arranging the monolithic solver. I agree on creating such `_GetScheme` and `_GetBuilderAndSolver`methods. But I will ask you for finishing the current implementation, which actually modifies the scheme selection part of the solver. If @jcotela agrees, I can do the changes in that branch.

**Review by GuillermoCasas — APPROVED** [review]

**Comment by GuillermoCasas** [comment]
Removing block since @miguelmaso has agreed to write an issue discussing the reasons for the original block, which are external.

**Review by GuillermoCasas — CHANGES_REQUESTED** [review]
Re-blocking until the obvious Codacy complaints are resolved

**Review by GuillermoCasas — APPROVED** [review]

**Pull request merged**
