### PR TITLE
[Core] Geometry - missing max_dihedral_angle

### PR DESCRIPTION
**Pull request by ddiezrod**
This qualitty measure was missing in #3955 , a cpp test was added.

### CODE REVIEW

**Comment by pablobecker** [comment]
in the test, replace 1.57... by globals::pi * 0.5

**Comment by ddiezrod** [comment]
@pablobecker Done!

**Review by pablobecker — APPROVED** [review]
Perfect!

**Comment by ddiezrod** [comment]
If nobody complains I merge this branch this afternoon

**Pull request merged**
