### PR TITLE
[DEM] Bug corrected in a omp for loop

### PR DESCRIPTION
**Pull request by joaquinirazabal**
There were forces summing up from different threads leading to errors.

### CODE REVIEW

**Review by maceligueta — CHANGES_REQUESTED** [review]
Nice finding. Thanks @joaquinirazabal !
I would try to avoid criticals as much as possible, though. I propose something like:

        Node<3>& central_node = GetGeometry()[0]; //CENTRAL NODE OF THE RBE
        #pragma omp parallel
        {        
        array_1d<double, 3>& center_forces = central_node.FastGetSolutionStepValue(TOTAL_FORCES);
        array_1d<double, 3>& center_torque = central_node.FastGetSolutionStepValue(PARTICLE_MOMENT);
        center_forces[0] = center_forces[1] = center_forces[2] = center_torque[0] = center_torque[1] = center_torque[2] = 0.0;

        #pragma omp for schedule(dynamic, 100)
        for (int k = 0; k < (int)mListOfNodes.size(); k++) {
            ModelPart::NodeIterator i = mListOfNodes.begin() + k;

And no criticals. In this way, those variables declared inside the parallel region won't intefere with each other.

**Comment by joaquinirazabal** [comment]
Great, @maceligueta, I changed what you suggested and tested it. Everything ok!

**Review by maceligueta — DISMISSED** [review]

**Comment by joaquinirazabal** [comment]
Sorry @maceligueta, yesterday I made a mistake in my test. Declaring the variables inside the parallel region still gives some strange results. Finally, I have opted to use the reduction statement, and after testing it carefully it seems that it is a good choice. What do you think about it?

**Comment by maceligueta** [comment]
Sorry, I made a mistake, too. It's true that all iterations contribute to the same shared variable. Let's leave reduction, like you did. Thanks.

**Review by maceligueta — APPROVED** [review]

**Comment by joaquinirazabal** [comment]
Merged

**Pull request merged**
