### PR TITLE
Mpi/migrating normal utility

### LINKED ISSUE #2945: Identifying utilities to be moved to the MPI core
I am opening this issue to collect Kratos objects (C++ or Python classes, mostly) that should belong to the MPI core. These should be things that call MPI methods directly or that explicitly use tools that have a dependency on MPI. They should not be trilinos-specific (trilinos things will remain on the trilinos application). So far, I have identified the following
- [x] mpi_communicator (currently in kratos core). Done in `experimental/mpi-core` branch
- [x] mpi_python (external libraries). Partially removed in #3821, finally removing the folder in #4215.
- [x] ParallelFillCommunicator (trilinos_application). #5210 
- [x] SetMPICommunicatorProcess (metis_application). Done in `experimental/mpi-core` branch
- [x] the trilinos_gid_output is also a likely candidate (trilinos_application). Removed in #4201 
- [x] GatherModelPartUtility. WIP:  #5355
- [x] custom_gid_io in trlinos application. Removed in #4200.
- [x] mpi_normal_calculation_utilities (trilinos_application). PR #5452.
- [x] trilinos_restart_utility.py Moved in #5243
- [x] trilinos_import_model_part_utility.py Moved in #5243

If anyone can think of something else, please let me know.

Related to #781 

[Last updated on 17.07.19]

### PR DESCRIPTION
**Pull request by jcotela**
Moving `MPINormalCalculationUtils` from TrilinosApplication to MPICore.

Cleaning up raw MPI calls and replacing them by the corresponding DataCommunicator calls. Also including some minor refactoring and renaming of variables to conform to our guidelines for the modified functions.

Note that this class is only needed for a very specific application and may still be removed in the near future if possible (so I did not try to perform a more through clean-up).

This completes and closes #2945.

### CODE REVIEW

**Review by philbucher — APPROVED** [review]
looks good to me

This has nothing to do yet with #2376 right?

**Comment by jcotela** [comment]
@philbucher no, it is unrelated.

**Review by roigcarlo — APPROVED** [review]
Also good here Thx 👍

**Comment by loumalouomega** [comment]
I will take a look as soon as I can. I was supposed to unify the normal
calculation :P.

**Pull request merged**
