### PR TITLE
[Core] Add resize to pointer_vector

### PR DESCRIPTION
**Pull request by tteschemacher**
Thanks!

### CODE REVIEW

**Comment by tteschemacher** [comment]
Can we add the resize to the pointer vector or will this conflict any other use? I am not fully aware of the other use cases of the pointer vector. But it seems that it is only used with the std::vector, which allows the resize.

Or is there a better recommended way to use it?

@pooyan-dadvand @loumalouomega @philbucher

**Review by loumalouomega — APPROVED** [review]
Ok

**Comment by RiccardoRossi** [comment]
sorry but i don't think this change is correct.

for example if mdata was a std::map you would not be able to do this change

please remove this function until it is approved by @KratosMultiphysics/technical-committee

**Comment by tteschemacher** [comment]
ok

**Comment by RiccardoRossi** [comment]
can you post here what you are trying to do?

**Comment by tteschemacher** [comment]
I need to resize the
>      typedef PointerVector<TPointType> PointsArrayType;
>      typedef PointerVector<GeometryType> GeometriesArrayType;
As they come from the geometry.h base class I am restricted to them. 

Other than using resize, I would need to clear and then make push_back, which is not very efficient.

**Comment by RiccardoRossi** [comment]
Oh, it is "PointerVector", i understood you were using "PointerVectorSet"

Indeed PointerVector is not an ordered vector, and doesn't have gaps. So it looks like my comment was wrong... (that is that Resize is admissible)

@pooyan-dadvand can u confirm this?

**Comment by tteschemacher** [comment]
I think the the map should anyways just be used in the pointer_map_set.

I don't want to open a discussion now but I put the argument as SizeType but the others were int. I think they should all be SizeType, because STD uses SizeType. Am I wrong here?

**Pull request merged**
