### PR TITLE
[ShapeOpt] feature remove shape opt conditions

### LINKED ISSUE #4387: [ShapeOpt] replace shape optimization conditions with default conditions from the core
@armingeiser side question, I though you no longer need the ShapeOptCondition?

_Originally posted by @philbucher in https://github.com/KratosMultiphysics/Kratos/pull/4338_

As the ShapeOptimizationConditions are only used to be able to generate a geometry from the mdpa file, but do not contain any meaningful code, they could be replaced with the default conditions from the core. 

See variables.cpp:
```
      mPointCondition2D1N( 0, GeometryType::Pointer(new Point2D<NodeType >(GeometryType::PointsArrayType(1)))),
      mPointCondition3D1N( 0, GeometryType::Pointer(new Point3D<NodeType >(GeometryType::PointsArrayType(1)))),
      // Line conditions
      mLineCondition2D2N( 0, GeometryType::Pointer(new Line2D2<NodeType >(GeometryType::PointsArrayType(2)))),
      mLineCondition2D3N( 0, GeometryType::Pointer(new Line2D3<NodeType >(GeometryType::PointsArrayType(3)))),
      mLineCondition3D2N( 0, GeometryType::Pointer(new Line3D2<NodeType >(GeometryType::PointsArrayType(2)))),
      mLineCondition3D3N( 0, GeometryType::Pointer(new Line3D3<NodeType >(GeometryType::PointsArrayType(3)))),
      // Surface conditions
      mSurfaceCondition3D3N( 0, GeometryType::Pointer(new Triangle3D3<NodeType >(GeometryType::PointsArrayType(3)))),
      mSurfaceCondition3D6N( 0, GeometryType::Pointer(new Triangle3D6<NodeType >(GeometryType::PointsArrayType(6)))),
      mSurfaceCondition3D4N( 0, GeometryType::Pointer(new Quadrilateral3D4<NodeType >(GeometryType::PointsArrayType(4)))),
      mSurfaceCondition3D8N( 0, GeometryType::Pointer(new Quadrilateral3D8<NodeType >(GeometryType::PointsArrayType(8)))),
      mSurfaceCondition3D9N( 0, GeometryType::Pointer(new Quadrilateral3D9<NodeType >(GeometryType::PointsArrayType(9)))),
```

@dbaumgaertner is there any objection against this?

### PR DESCRIPTION
**Pull request by armingeiser**
Contains also a minor fix for the mapper_test, that is currently failing on the nightly build.

closes #4387

### CODE REVIEW

**Comment by armingeiser** [comment]
@dbaumgaertner removing the conditions completely from the .mdpa leads to a segfault, i think that should  be considered separately

**Comment by dbaumgaertner** [comment]
At which step and in which example does the segfault appear?

**Comment by armingeiser** [comment]
I fixed the segfault problem and another minor issue. The SurfaceConditions can indeed be removed if the following conditions are met:
* standard optimization: `"project_gradient_on_surface_normals" : false`
* bead optimization: user defined bead direction is used and not automatic normal one.

I removed the conditions where possible from the tests. 
However not from the test_examples given that we often modify them to quickly try out some things and it is quite some effort to manually add the conditions to the mdpa again.

**Comment by dbaumgaertner** [comment]
Nice move! Makes things a lot cleaner and allows us to only use nodes for opt. On top of that, tests are running and I resolved the merge conflict.

**Review by dbaumgaertner — APPROVED** [review]

**Pull request merged**
