### PR TITLE
[PfemSolid] removing pastix-archive

### PR DESCRIPTION
**Pull request by philbucher**
for some reason there is an archive containing the pastix-solver committed

This occupies 15MB which can be always downloaded from the website

Furthermore I am not sure abt the license, it is sth that I am not familiar with and if it is compatible with BSD of Kratos

### CODE REVIEW

**Comment by philbucher** [comment]
related to #4996

**Comment by pooyan-dadvand** [comment]
ping @KratosMultiphysics/pfem

**Comment by pooyan-dadvand** [comment]
ping @KratosMultiphysics/pfem

**Comment by pooyan-dadvand** [comment]
ping @KratosMultiphysics/pfem

**Comment by pooyan-dadvand** [comment]
ping @KratosMultiphysics/pfem

**Comment by ipouplana** [comment]
Thanks @philbucher , we are currently looking into it and we'll let you know.

**Comment by ipouplana** [comment]
I think you can delete it. If nobody else is against it, go ahead

**Comment by RiccardoRossi** [comment]
ok, thx @ipouplana 

approving on behalf of @KratosMultiphysics/technical-committee

**Review by roigcarlo — APPROVED** [review]
:+1:

**Pull request merged**
