### PR TITLE
[Core] Removing deprecated Line2D

### PR DESCRIPTION
**Pull request by loumalouomega**
The line_2d (which duplicates line_2d_2) has been deprecated from long time. Removing (removing includes, no one of them is actually used, I assume is a copy/paste thing)

### CODE REVIEW

**Comment by pablobecker** [comment]
@loumalouomega , if you want the implementation comitee to approve something, it would be better to add it to the list of tasks of the comittee and wait for its approval

**Comment by loumalouomega** [comment]
> @loumalouomega , if you want the implementation comitee to approve something, it would be better to add it to the list of tasks of the comittee and wait for its approval

How  do I do that?

**Comment by loumalouomega** [comment]
Ping

**Comment by pablobecker** [comment]
I see it's here now https://github.com/KratosMultiphysics/Kratos/projects/19 , so it is fine.
the downside is that you'll have to wait up to 2 weeks to get something approved.

**Comment by pooyan-dadvand** [comment]
@pablobecker I understand that it would take time to be approved but this should be the procedure. (I mean passing by committee) Meanwhile this PR is not very urgent.

**Comment by GuillermoCasas** [comment]
The @KratosMultiphysics/implementation-committee has decided to vote in favour of this PR. Passing the decision on to the @KratosMultiphysics/technical-committee.

**Comment by loumalouomega** [comment]
Ping @elafnm @josep-m-carbonell @armingeiser

**Comment by armingeiser** [comment]
Good from @KratosMultiphysics/optimization point of view, thanks!

**Review by GuillermoCasas — APPROVED** [review]

**Comment by maceligueta** [comment]
The @KratosMultiphysics/technical-committee  agrees with the decision from the @KratosMultiphysics/implementation-committee . Thanks.
@GuillermoCasas  and @loumalouomega : the only comment is that this should have been merged after this message, according to the procedures currently established.

**Comment by loumalouomega** [comment]
I am sorry, when I noticed that the approval from technical committee was
missing it was to late.

**Pull request merged**
