### PR TITLE
[Script][Core] Proper number of processors detected on MacOSX

### PR DESCRIPTION
**Pull request by loumalouomega**
**Description**
proc does not exist in Mac, using proper one

**Changelog**
- Replace proc by proper Mac alternative

### CODE REVIEW

**Comment by loumalouomega** [comment]
FYI @ipouplana

**Review by roigcarlo — COMMENTED** [review]
Seems to work :+1:

Would be better if someone with a real mac approves anyway

**Comment by loumalouomega** [comment]
> Seems to work +1
> 
> Would be better if someone with a real mac approves anyway

(it works in my VM)

**Review by roigcarlo — APPROVED** [review]
Also in mine, that's why I said real :P. Well I approve it should be safe in any case.

**Pull request merged**
