### PR TITLE
[ConvDiff] Application name according to standard

### PR DESCRIPTION
**Pull request by rubenzorrilla**
Requested long time ago in #2682 . @loumalouomega you can remove it from the VMataix TODO list :wink: .

Tagging all the potential users of the ConvectionDiffusionApplication that come to my mind: @RiccardoRossi @pooyan-dadvand @jcotela @msandre @Rbravo555 @juliobarna @playpaolo @pablobecker @ddiezrod 
Please let me know if I've forgotten someone.

### CODE REVIEW

**Review by loumalouomega — DISMISSED** [review]
OK. 182 files changed, only +4-4 lines added :)

**Comment by jcotela** [comment]
:+1: from my side.

**Comment by jcotela** [comment]
@rubenzorrilla I merged a separate PR in ConvDiff yesterday, I updated this branch to solve the conflict.

**Review by jcotela — APPROVED** [review]
re-approving, since last commit cancelled the positive review.

**Pull request merged**
