### PR TITLE
[CI] add ICC build

### PR DESCRIPTION
**Pull request by philbucher**
**Description**
Finally it seems to work :D

### CODE REVIEW

**Comment by philbucher** [comment]
this mostly works, only few problems:
- Tests in the FluidDynApp still take too long, this is a known issue @rubenzorrilla 
- Tests in Contact fail, maybe same problems as in Win? (Thats why Contact is not in the WIN CI) @loumalouomega 
~~~
Running ContactStructuralMechanicsApplication tests
.............F.........F.......F.......
======================================================================
FAIL: test_execution (SmallTests.PenaltyFrictionlessHyperSimplePatchFrictionalTestContact)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/__w/Kratos/Kratos/bin/Custom/applications/ContactStructuralMechanicsApplication/tests/contact_structural_mechanics_test_factory.py", line 76, in test_execution
    self.test.RunSolutionLoop()
  File "/__w/Kratos/Kratos/bin/Custom/KratosMultiphysics/analysis_stage.py", line 67, in RunSolutionLoop
    self.FinalizeSolutionStep()
  File "/__w/Kratos/Kratos/bin/Custom/KratosMultiphysics/analysis_stage.py", line 149, in FinalizeSolutionStep
    process.ExecuteFinalizeSolutionStep()
  File "/__w/Kratos/Kratos/bin/Custom/KratosMultiphysics/from_json_check_result_process.py", line 54, in ExecuteFinalizeSolutionStep
    self.assertTrue(self.process.IsCorrectResult(), "Results do not coincide with the JSON reference\n" + self.process.GetErrorMessage())
AssertionError: False is not true : Results do not coincide with the JSON reference
Error checking for variable DISPLACEMENT_Y, results:
Node 3 -0.02429503!=-0.01941737; rel_tol=1e-06, abs_tol=0.001
Error checking for variable DISPLACEMENT_Y, results:
Node 5 -0.01518856!=-0.02046151; rel_tol=1e-06, abs_tol=0.001
Error checking for variable DISPLACEMENT_Y, results:
Node 4 -0.01565867!=-0.01941737; rel_tol=1e-06, abs_tol=0.001
Error checking for variable DISPLACEMENT_Y, results:
Node 6 -0.02462485!=-0.02046151; rel_tol=1e-06, abs_tol=0.001


======================================================================
FAIL: test_execution (SmallTests.ALMPerfectStickHyperSimplePatchFrictionalTestContact)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/__w/Kratos/Kratos/bin/Custom/applications/ContactStructuralMechanicsApplication/tests/contact_structural_mechanics_test_factory.py", line 76, in test_execution
    self.test.RunSolutionLoop()
  File "/__w/Kratos/Kratos/bin/Custom/KratosMultiphysics/analysis_stage.py", line 67, in RunSolutionLoop
    self.FinalizeSolutionStep()
  File "/__w/Kratos/Kratos/bin/Custom/KratosMultiphysics/analysis_stage.py", line 149, in FinalizeSolutionStep
    process.ExecuteFinalizeSolutionStep()
  File "/__w/Kratos/Kratos/bin/Custom/KratosMultiphysics/from_json_check_result_process.py", line 54, in ExecuteFinalizeSolutionStep
    self.assertTrue(self.process.IsCorrectResult(), "Results do not coincide with the JSON reference\n" + self.process.GetErrorMessage())
AssertionError: False is not true : Results do not coincide with the JSON reference
Error checking for variable DISPLACEMENT_X, results:
Node 3 2.775558e-17!=0.01422514; rel_tol=1e-06, abs_tol=0.001
Error checking for variable DISPLACEMENT_X, results:
Node 5 -0.0002007644!=-0.01422514; rel_tol=1e-06, abs_tol=0.001
Error checking for variable DISPLACEMENT_X, results:
Node 4 5.551115e-17!=-0.01422514; rel_tol=1e-06, abs_tol=0.001
Error checking for variable DISPLACEMENT_X, results:
Node 6 0.0002007644!=0.01422514; rel_tol=1e-06, abs_tol=0.001
Error checking for variable DISPLACEMENT_Y, results:
Node 5 -0.1992963!=-0.110236; rel_tol=1e-06, abs_tol=0.001
Error checking for variable DISPLACEMENT_Y, results:
Node 3 -4.163336e-17!=-0.109236; rel_tol=1e-06, abs_tol=0.001
Error checking for variable DISPLACEMENT_Y, results:
Node 6 -0.1992963!=-0.110236; rel_tol=1e-06, abs_tol=0.001
Error checking for variable DISPLACEMENT_Y, results:
Node 4 5.551115e-17!=-0.109236; rel_tol=1e-06, abs_tol=0.001


======================================================================
FAIL: test_execution (SmallTests.PenaltyHyperSimplePatchFrictionalStickTestContact)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/__w/Kratos/Kratos/bin/Custom/applications/ContactStructuralMechanicsApplication/tests/contact_structural_mechanics_test_factory.py", line 76, in test_execution
    self.test.RunSolutionLoop()
  File "/__w/Kratos/Kratos/bin/Custom/KratosMultiphysics/analysis_stage.py", line 67, in RunSolutionLoop
    self.FinalizeSolutionStep()
  File "/__w/Kratos/Kratos/bin/Custom/KratosMultiphysics/analysis_stage.py", line 149, in FinalizeSolutionStep
    process.ExecuteFinalizeSolutionStep()
  File "/__w/Kratos/Kratos/bin/Custom/KratosMultiphysics/from_json_check_result_process.py", line 54, in ExecuteFinalizeSolutionStep
    self.assertTrue(self.process.IsCorrectResult(), "Results do not coincide with the JSON reference\n" + self.process.GetErrorMessage())
AssertionError: False is not true : Results do not coincide with the JSON reference
Error checking for variable DISPLACEMENT_X, results:
Node 3 -0.003501837!=4.495567e-08; rel_tol=1e-06, abs_tol=0.001
Error checking for variable DISPLACEMENT_X, results:
Node 5 0.002513946!=-0.001500374; rel_tol=1e-06, abs_tol=0.001
Error checking for variable DISPLACEMENT_X, results:
Node 4 -0.01624244!=4.495567e-08; rel_tol=1e-06, abs_tol=0.001
Error checking for variable DISPLACEMENT_X, results:
Node 6 -0.02440858!=0.002052505; rel_tol=1e-06, abs_tol=0.001
Error checking for variable DISPLACEMENT_Y, results:
Node 5 -0.04283434!=-0.037413; rel_tol=1e-06, abs_tol=0.001
Error checking for variable DISPLACEMENT_Y, results:
Node 4 -0.01018404!=-0.00695614; rel_tol=1e-06, abs_tol=0.001
Error checking for variable DISPLACEMENT_Y, results:
Node 6 -0.075394!=-0.0400616; rel_tol=1e-06, abs_tol=0.001


----------------------------------------------------------------------
Ran 39 tests in 18.763s
~~~

**Comment by loumalouomega** [comment]
I don't know why the contact is not in Windows CI, I don't remember when it was deactivated

**Comment by philbucher** [comment]
> I don't know why the contact is not in Windows CI, I don't remember when it was deactivated

Due to some unfortunate circumstances it was never there (speaking of the github actions), see  #7601

**Comment by philbucher** [comment]
some comments:
- Intel is much slower (factor of ~2 compared to clang and ~1,5 compared to GCC)
- it requires more memory, hence it sometimes fails as it runs out of memory
- there are still some issues when running the tests. This should hopefully be fixed with #8167, as the pybind guys put a lot of fixed especially for intel in the preparation of v2.6.2

**Comment by philbucher** [comment]
closing as it was replaced by #8582

**Pull request closed without merging**
