### PR TITLE
Update constraint_utilities.cpp

### PR DESCRIPTION
**Pull request by RiccardoRossi**
fix OpenMP bug reported in #6148

### CODE REVIEW

**Comment by philbucher** [comment]
Wow this is strange 
To me this looks ok and should be backported

Do you want to merge this now or wait until next year?

**Comment by RiccardoRossi** [comment]
i would at least merge this to master soon. this should definitely not break anythin, rather fix problems

for the backporting we can wait.

**Review by loumalouomega — APPROVED** [review]
But why???

**Comment by RiccardoRossi** [comment]
why the bug? because the std::vector<bool> is very specific. VERY. kind of evil too.

essentially if you say that you want to allocate say 100 bools, it will allocate 100/32 (possibly 64) ints. the first 32 bools are allocated in the first int, then the next 32 in the second...

now the point is that if you try to write in parallel let s say the bits 1 and 2, you are actually modifying in parallel the entire first int..leading to unexpected behaviour

**Comment by RiccardoRossi** [comment]
not deleting the branch to use it for backporting

**Comment by loumalouomega** [comment]
OK, then for proper fix we should consider a std::vector of integers and
store ones and zeros?, that way we use again openmp

**Comment by pooyan-dadvand** [comment]
You got a very tricky one!! :+1:

**Pull request merged**
