### PR TITLE
[PFEM] Cleaning and styling some files in PFEMFluidApp

### PR DESCRIPTION
**Pull request by AlejandroCornejo**
that's it, only style changes and removed the comments -> now it's easier to read

### CODE REVIEW

**Review by AFranci — DISMISSED** [review]
Thank you for the cleaning and the new comments!
If you have already checked that the tests are working, for me it is nice!

**Comment by AlejandroCornejo** [comment]
I've calculated the same case and it's okkey. Sincerely I cannot run the tests because in Win it's not possible :S. Maybe you can check just in case.

**Comment by AFranci** [comment]
It gives the error of below while running the tests. We should keep using print() there

  File "/home/falessandro/Kratos/applications/PfemFluidDynamicsApplication/tests/TestFactory.py", line 41, in test_execution
    self.test.Run()
  File "/home/falessandro/Kratos/kratos/python_scripts/analysis_stage.py", line 51, in Run
    self.Finalize()
  File "/home/falessandro/Kratos/applications/PfemFluidDynamicsApplication/python_scripts/pfem_fluid_dynamics_analysis.py", line 240, in Finalize
    self.KratosPrintInfo("::[KPFEM Simulation]:: [Elapsed Time = %.2f" % (tfw - self.t0w),"seconds] (%.2f" % (tfp - self.t0p),"seconds of cpu/s time)")
TypeError: KratosPrintInfo() takes 2 positional arguments but 4 were given

**Comment by AlejandroCornejo** [comment]
> 
> 
> It gives the error of above while running the tests. We should keep using print() there
> 
> File "/home/falessandro/Kratos/applications/PfemFluidDynamicsApplication/tests/TestFactory.py", line 41, in test_execution
> self.test.Run()
> File "/home/falessandro/Kratos/kratos/python_scripts/analysis_stage.py", line 51, in Run
> self.Finalize()
> File "/home/falessandro/Kratos/applications/PfemFluidDynamicsApplication/python_scripts/pfem_fluid_dynamics_analysis.py", line 240, in Finalize
> self.KratosPrintInfo("::[KPFEM Simulation]:: [Elapsed Time = %.2f" % (tfw - self.t0w),"seconds] (%.2f" % (tfp - self.t0p),"seconds of cpu/s time)")
> TypeError: KratosPrintInfo() takes 2 positional arguments but 4 were given

that's right, changing...

**Review by AFranci — APPROVED** [review]

**Pull request merged**
