### PR TITLE
[DEM] Bugfix in old GUI

### PR DESCRIPTION
**Pull request by maceligueta**
Though we are moving to the new GUI, we should keep these GUIs working for a while. This bug was my fault in a previous PR.

### CODE REVIEW

**Comment by KlausBSautter** [comment]
`  File "KratosDEMAnalysis.py", line 31, in <module>
    project_parameters = KratosMultiphysics.Parameters(parameter_file.read())
RuntimeError: [json.exception.parse_error.101] parse error at line 26, column 22: syntax error while parsing object - unexpected string literal; expected '}'
`

**Comment by KlausBSautter** [comment]
I get this error message now

**Comment by farrufat-cimne** [comment]
Hi @KlausBSautter, could you please post the json file.

thx!

**Comment by KlausBSautter** [comment]
[aa.gid.zip](https://github.com/KratosMultiphysics/Kratos/files/3069355/aa.gid.zip)

**Comment by farrufat-cimne** [comment]
Found the error in the old wfcfdem.tcl. Opening PR

thx Klaus

**Comment by farrufat-cimne** [comment]
Moved fix from another PR into here.

**Comment by KlausBSautter** [comment]
thanks fixes my problems :)

**Review by KlausBSautter — APPROVED** [review]

**Pull request merged**
