### PR TITLE
Added serializer for std::array and saving array instead of iterator

### LINKED ISSUE #1463: Serializer problem in win
Serializer crashes with:

```Bash
C:\KratosSource\kratos\includes/serializer.h(207): error C2039: 'load': is not a member of 'std::_Array_iterator<_Ty,1>

with
          [
              _Ty=Kratos::Table<double,double,1>::result_type
          ]
```

Seems to be related with Kratos::Tables. @pooyan-dadvand any idea?

### PR DESCRIPTION
**Pull request by roigcarlo**
Fixes #1463.

Someone please double check it.

### CODE REVIEW

**Comment by philbucher** [comment]
compiles and tests are running

can you wait a bit, then I will add the tests for the `std::array` ?

**Comment by philbucher** [comment]
done, can you please check if it still compiles?
Should be, but just to make sure this time...

**Comment by roigcarlo** [comment]
Working ok in win :+1:

**Comment by roigcarlo** [comment]
But I cannot approve the PR, so someone else has to :(

**Comment by philbucher** [comment]
should I approve or do we wait for @pooyan-dadvand ?

**Comment by roigcarlo** [comment]
I believe its safe to approve

**Review by philbucher — APPROVED** [review]
ok

**Pull request merged**
