### PR TITLE
[StructuralMechanicsApplication]Cleaning SPrism element

### PR DESCRIPTION
**Pull request by loumalouomega**

### CODE REVIEW

**Comment by philbucher** [comment]
could you please update or remove the SprismPanTests? that one is currently commented bcs not working afaik

**Comment by loumalouomega** [comment]
Requires the arc-length than some day I will finish

**Comment by philbucher** [comment]
ok fine for me

one more question, did you rewrite the element completely or just cleaned it?
In git it shows as completely new bcs the file name changed

**Comment by loumalouomega** [comment]
I clean it and I change the name for consistency, but git recognizes like I removed it, I will try something

**Comment by loumalouomega** [comment]
Ok, I did it now in two steps, at least in my machine recognizes as name change

**Review by philbucher — COMMENTED** [review]
I looked through it a bit and there seems nothing wrong with the modifications

**Comment by loumalouomega** [comment]
Can anyone approve?

**Review by PhilippeBussetta — APPROVED** [review]

**Comment by loumalouomega** [comment]
Thanks

**Pull request merged**
