### PR TITLE
[StructuralMechanics] fixing meshmoving test

### PR DESCRIPTION
**Pull request by philbucher**
@loumalouomega you changed values in #2577 
I thought this was only cleanup?

this is a partial fix for #2631

### CODE REVIEW

**Comment by philbucher** [comment]
strange though that it does not fail i Travis ...

**Review by loumalouomega — DISMISSED** [review]
👌

**Comment by philbucher** [comment]
needs reapproval :)

**Review by loumalouomega — APPROVED** [review]

**Comment by philbucher** [comment]
thx

**Pull request merged**
