### PR TITLE
[MPM] Create particle vtk output

### PR DESCRIPTION
**Pull request by peterjwilson**
**Description**
This introduces a basic VTK output for mpm particles. The process is a combination of the DEM vtk particle output and the MPM GiD output.

image

### CODE REVIEW

**Comment by VeronikaSinger** [comment]
cool! Thanks @peterjwilson

**Review by philbucher — CHANGES_REQUESTED** [review]
no offense but this is quite ugly @peterjwilson :D

Is there a reason you are not directly using / deriving from the vtk-output in the core
The advantages would be that it is very well tested and supports lots of features already

Briefly looking at your code it seems like the core output would already work. If not, then I suggest deriving from it (it was designed for that) like I did [here](https://github.com/KratosMultiphysics/Kratos/blob/master/applications/StructuralMechanicsApplication/custom_io/vtk_eigen_output.h)

also the you wouldn't need the `pyevtk` dependency

**Review by philbucher — APPROVED** [review]
@peterjwilson ok then for me. As long as it is agreed that this is only a quick&dirty solution and better than nothing I agree to add it (whitout tests, as those would most probably not be valid any more when implementing it properly)

In the meantime I discussed with @KlausBSautter to implement this porperly for the DEM output, as it is very similar. Maybe if we have some time before Christmas we can do this one right away

also note that according to @KlausBSautter this is not compatible with the latest version of Paraview!

**Comment by KlausBSautter** [comment]
We had problems with the last FSI group. Apparently they finally used 5.8.1. and it worked. 
I do not know which is the latest version.

**Comment by peterjwilson** [comment]
Sounds good @philbucher @KlausBSautter - I'm happy to adapt the fancy DEM vtk output to MPM when it's ready - just ping me 😄 .

**Pull request merged**
