### PR TITLE
[Core] Add Step index for SetVariable in VariableUtils

### PR DESCRIPTION
**Pull request by sunethwarna**
**📝 Description**
Adds the ability to set values based on `Step` index for `SetVariable` method in `VariableUtils`. Respective python interfaces are also added.

Only issue is, there is no way to check the buffersize of the nodal historical data base.

**🆕 Changelog**
- Adds `Step` argument to `SetVariable` method
- Adds respective python exposures.

### CODE REVIEW

**Review by rubenzorrilla — COMMENTED** [review]
I think that it should be possible to do the export with a lambda to avoid the auxiliary function. Aside of this, I'm fine with the addition.

**Review by philbucher — DISMISSED** [review]
Since it is used many times you would need to duplicate the lambda many times, hence I think the aux function makes full sense here

**Comment by sunethwarna** [comment]
I am ok with both. @philbucher @rubenzorrilla  :) Using an aux function is more readable than the lambdas in my opinion as well since we dont have any doc on python side explaning use cases.

**Review by philbucher — COMMENTED** [review]
exactly, this is what is much more messy and error prone IMO

**Comment by rubenzorrilla** [comment]
> exactly, this is what is much more messy and error prone IMO

OK, I like the lambdas because you have it together to the export clause, so you don't need to browse the file to see what's happening. As this is a matter of taste take the option you like the most.

**Comment by rubenzorrilla** [comment]
Adding to my previous comments that I agree with both observations.

**Review by philbucher — APPROVED** [review]
ok as you wish :)

**Pull request merged**
