### PR TITLE
[Structural ] Typo in PrepareModelPart function name

### PR DESCRIPTION
**Pull request by rubenzorrilla**
The serial communicator was always created because of this :sweat_smile:

### CODE REVIEW

**Review by philbucher — APPROVED** [review]
Thx!

Note to myself: I really have to get the mpi tests running again!

**Comment by philbucher** [comment]
@rubenzorrilla you could try to run the MPI-tests in the structuralapp
=> either directly with 2 mpi-procs or by running the regular test_StructuralMechanicsApplication.py with having MPI compiled

**Comment by rubenzorrilla** [comment]
@philbucher Actually, I did try the MPI tests but they are not working. At a first glance it seems to be a minor issue (I was about to open and issue).

**Comment by philbucher** [comment]
@rubenzorrilla for me the mpi test is working again.
Thx for fixing :+1: 

Is it still failing for you? It might not be the most robust one, it was more a first draft ...

**Pull request merged**
