### PR TITLE
[Core][Template] Allowing custom tree CMakeLists.txt

### PR DESCRIPTION
**Pull request by loumalouomega**
This generates the @{APP_NAME_CAMEL}Application.py on the fly, I use this on my apps outside the tree, like https://github.com/loumalouomega/KratosPythonWrapperApplication

### CODE REVIEW

**Comment by philbucher** [comment]
the idea makes sense to me but how would this work for non-standard cases (e.g. TrilinosApp)

**Comment by loumalouomega** [comment]
> the idea makes sense to me but how would this work for non-standard cases (e.g. TrilinosApp)

technically yes, but technically current approach it is just suited for standard cases

**Comment by loumalouomega** [comment]
Ping @philbucher, @roigcarlo  any additional comment?

**Review by roigcarlo — CHANGES_REQUESTED** [review]
Sorry didn't saw the PR. We cannot do that, as we require the file to exist prior installation in case we want to use the link install system (see #5825). Otherwise application cannot be loaded as a module.

To expand a little more, the problem is that, if the file is created on the fly and we install links to the python scripts we either create the file on the fly in the source dir, and we need to add it in the .gidignore or it will be appearing for every commit or we create it in the module, in which case we have two problems: we don't have direct access to the contents without installing, which is something @RiccardoRossi is very against (I am also very against for this particular file), and second, we are mixing links and real files in the module dir, which can cause a lot of confusion.

**Comment by loumalouomega** [comment]
OK

**Pull request closed without merging**
