### PR TITLE
[Core] Adding Set methods for Stress and Strain measures

### PR DESCRIPTION
**Pull request by loumalouomega**
By default does nothing, must be implemented in the derived CL

### CODE REVIEW

**Comment by josep-m-carbonell** [comment]
The constitutive law is not storing the stress or strain measure variable. In fact, they are not unique. The GetStressMeasure() method was there for legacy with the structural_application.  If you are using it to obtain certain information maybe you are doing something wrong. What do you try to set and get?

**Comment by loumalouomega** [comment]
I know that the CL doesn't stores the StressMeasure and StrainMeasure, I was wondering why there is Get and not  a Set, because that emplies that one law is only compatible with one type of measure. Adding this as member variables is expensive, maybe we can add it to the Properties or something

**Comment by loumalouomega** [comment]
In order to get The constitutive tensor from the CalculateValue interface, but this limits me to only one Measure at a time

**Comment by loumalouomega** [comment]
I think how to avoid modify the base class, I can define two additional variables, one called CONSTITUTIVE_MATRIX_PK2 and the other CONSTITUTIVE_MATRIX_KIRCHOFF. Sorry for the noise

**Comment by josep-m-carbonell** [comment]
I am not against adding something. Just I asked about it to know the usage.

**Comment by loumalouomega** [comment]
Yes, but if we want to make the CL faster and less memory consuming better to avoid to add new things to the class.

**Pull request closed without merging**
