### PR TITLE
[StructuralMechanics] minor solver cleaning after #2767

### PR DESCRIPTION
**Pull request by philbucher**
after #2767, the import of the ModelPart can be skipped by setting it in the Parameters

also what I recently introduced in #2746 is not necessary any more

FYI @dbaumgaertner @armingeiser

### CODE REVIEW

**Comment by philbucher** [comment]
@armingeiser this requires some modifiactions in the responses, I am not sure how to do it properly.
Can you please have a look when you have time?

**Review by loumalouomega — APPROVED** [review]
OK

**Comment by armingeiser** [comment]
@philbucher I will have a look soon.

**Comment by philbucher** [comment]
merging since the ppl involved had a look and such that we can go ahead with #2863

**Pull request merged**
