### PR TITLE
GiDOutputProcess commenting problematic code related to restarting

### PR DESCRIPTION
**Pull request by philbucher**
explanation in #2378 

This is not a proper fix, since I don't know how to do it in a proper way
This seems to be broken for a while already and constantly creates problems for us.

I will not close the corresponding issue, such that it can be fixed properly at some point

### CODE REVIEW

**Comment by jcotela** [comment]
@philbucher I believe this version should solve our problem without breaking the existing functionality. However I agree that a proper fix is needed.

**Comment by philbucher** [comment]
works, thanks @jcotela

**Comment by philbucher** [comment]
I tested it fully now, works in OpenMP and MPI

**Comment by philbucher** [comment]
@mpentek can you please have a look since you also had problems with this?

**Review by mpentek — APPROVED** [review]

**Pull request merged**
