### PR TITLE
[MPM][To discuss Not to Merge] Explicit dynamic solver

### PR DESCRIPTION
**Pull request by tteschemacher**
I am adding here the first drafts for an explicit solver for MPM. Those files are copied and modified from the structural mechanics application.

### CODE REVIEW

**Review by bodhinandach — CHANGES_REQUESTED** [review]
Blocking just in case...

**Comment by loumalouomega** [comment]
Maybe is better to add a generic one to the core

**Comment by tteschemacher** [comment]
The functions in the element are always copy and pasted, thus, could be moved to the base element. I would be fine with this. What do you think @RiccardoRossi and @KlausBSautter.

**Comment by tteschemacher** [comment]
Haha @bodhinandach, you waited for a long time to finally block something right? :P

**Comment by bodhinandach** [comment]
@tteschemacher the implementation of explicit scheme going to take us some time. It is again not the same as the traditional FEM, e.g. USF, USL, MUSL. It should be discussed properly, especially who are going to devote the time for the implementation.

**Review by philbucher — CHANGES_REQUESTED** [review]
without going into detail, the amount of code that is copy-pasted from StructuralMechanics gets out of hand here
I would say that we should strongly consider deriving the solvers from StructuralMechanics

**Comment by PeterJosephWilson** [comment]
@bodhinandach I know what you mean Nanda, however, I think the complexity depends on what scope we limit the explicit integrator to. 

For example, if we limit the scope to take nodal force and mass contributions and compute resulting accelerations it would be equally applicable to all MPM stress update options and FEM too. Being so generic, it may be worthwhile adding it to the core then, as @loumalouomega suggested.

**Comment by loumalouomega** [comment]
> @bodhinandach I know what you mean Nanda, however, I think the complexity depends on what scope we limit the explicit integrator to.
> 
> For example, if we limit the scope to take nodal force and mass contributions and compute resulting accelerations it would be equally applicable to all MPM stress update options and FEM too. Being so generic, it may be worthwhile adding it to the core then, as @loumalouomega suggested.

https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/solving_strategies/schemes/residual_based_bdf_custom_scheme.h Works with generic types of dofs, which are provided on the constructor. This way can be generalized to any dofs set

**Comment by bodhinandach** [comment]
@PeterJosephWilson I do agree, and then some specific implementation for MPM will be added in derived classes.

**Comment by peterjwilson** [comment]
I guess this can be closed now @tteschemacher ?

**Comment by tteschemacher** [comment]
Yes, thank you!

**Pull request closed without merging**
