### PR TITLE
Trying to use the Kratos log from amgcl.

### PR DESCRIPTION
**Pull request by jcotela**
follow-up of the discussion in #3237

### CODE REVIEW

**Comment by jcotela** [comment]
@RiccardoRossi note that I have not tested it, as I am unsure about how to provoke the warning.

**Review by ddemidov — APPROVED** [review]
This looks good to me, but I did not try to compile or test it.

**Comment by RiccardoRossi** [comment]
i compiled and tested. it works ...

**Comment by RiccardoRossi** [comment]
@jcotela i didn't delete the other branch. I am not deleting it since you are basing on that. when you merge please also delete my branch

**Comment by RiccardoRossi** [comment]
@jcotela just add a random parameter in the defaults of the amgcl_solver.h that should trigger the warning

**Pull request merged**
