### PR TITLE
Core/linear solver factory const

### PR DESCRIPTION
**Pull request by adityaghantasala**
Solves #5193

### CODE REVIEW

**Comment by loumalouomega** [comment]
Have you checked the derived classes (MPI)?

**Comment by adityaghantasala** [comment]
I did not. I do not have a mpi compilation available now. 
Can you check maybe ?

Also just curious, should it effect ?

**Comment by loumalouomega** [comment]
I cannot compile MPI now, yes it can be important. @philbucher, can you try?

**Review by philbucher — APPROVED** [review]

**Comment by philbucher** [comment]
Looks ok to me but I can compile it later

**Comment by philbucher** [comment]
compiles in MPI :+1:

**Review by loumalouomega — APPROVED** [review]
Ok then

**Pull request merged**
