### PR TITLE
[DEMApplication] Fixed some bugs and added a smooth-joint model

### PR DESCRIPTION
**Pull request by ChengshunShang1996**
**📝 Description**
For the constitutive laws, some bugs were fixed and a smooth-joint model was established in Kratos DEMApplicaiton. 
For the post-processing part, the 'VtkOutput' class was expanded for exporting more particle variables and contact variables. 

**🆕 Changelog**
- Added a BoundingBox moving method for applying force with periodic boundary.
- Added a global viscous damping force for simulating quasi-static problem.
- Fixed the bug of the viscous damping force calculation for the unbonded part in ParallelBondModelCL.
- Fixed a bug related to the periodic boundary.
- Added a smooth-joint model for joint simulation in geomaterial.
- Added a void model for particle contact, as its name, no force will be calculated when we apply this model to a group of particles.

joints2

- Expanded the .vtk output class to more particle variables.
- Expanded the .vtk output class to contact variables, which could be very useful to display force chains.

paraview_contact

### CODE REVIEW

**Comment by maceligueta** [comment]
In order to ensure that any feature does not break with future changes, we should add tests for every new feature, with small cases (they must run fast). For the moving BB and the smooth-joint model, for example, we/you need to make sure nobody breaks them with apparently independent changes.

**Comment by ChengshunShang1996** [comment]
Please help me review the PR. Thanks! @KratosMultiphysics/dem

**Comment by salvalatorre** [comment]
It's a fairly big PR... Anyway, if you had the corresponding tests implemented and they work fine, I don't see any objection in approving this once the Codacy SCA is successful... ;)

**Comment by salvalatorre** [comment]
Oh, only Codacy errors with severity higher or equal to medium, don't worry about minors :)

**Comment by ChengshunShang1996** [comment]
> It's a fairly big PR... Anyway, if you had the corresponding tests implemented and they work fine, I don't see any objection in approving this once the Codacy SCA is successful... ;)

At the beginning, it's a small one. But, it grown up day by day :). The corresponding tests has been implemented and work good.

**Comment by ChengshunShang1996** [comment]
> Oh, only Codacy errors with severity higher or equal to medium, don't worry about minors :)

The Codacy analysis errors seem mainly because of the using of C++ function in Python part. I tried to improve them but I didn't find a proper way to make it. If anyone could give me some advice on it, I will appreciate it.

**Review by salvalatorre — APPROVED** [review]
We will discuss a bit about Codacy, not a big issue at all...

**Pull request merged**
