### PR TITLE
[Core][Geometry]Missing methods Prism3D6

### PR DESCRIPTION
**Pull request by loumalouomega**
Title says all

### CODE REVIEW

**Comment by pooyan-dadvand** [comment]
Are there any tests for these modified and added methods?

**Comment by loumalouomega** [comment]
No, the missing methods are quite standard, but I can add the tests

**Comment by loumalouomega** [comment]
Tests added

**Comment by loumalouomega** [comment]
Can anyone approve?

**Review by pooyan-dadvand — APPROVED** [review]
👍

**Comment by philbucher** [comment]
branch can be deleted?

**Comment by loumalouomega** [comment]
Ups

**Pull request merged**
