### PR TITLE
[core] List of apps to be compiled are printed on screen

### PR DESCRIPTION
**Pull request by maceligueta**
Just a list clarifying what apps have been requested for compilation

### CODE REVIEW

**Comment by roigcarlo** [comment]
Fine to me, but bear in mind that dependencies will not be printed.

**Comment by philbucher** [comment]
thanks a lot @maceligueta , I will test it later today

**Comment by maceligueta** [comment]
I added the print of those apps added through dependencies. I would have loved to print:
FluidDynamicsApplication **(through SwimmingDEMApplication)**
But I did not know how.

**Comment by roigcarlo** [comment]
> I added the print of those apps added through dependencies

Great! :+1: 

> I would have loved to print:
> FluidDynamicsApplication (through SwimmingDEMApplication)

Don't think that is even doable as we have crossed dependencies (For example Fluid being added through Swimming and Pfem?) and corner cases... It is quite a mess already to resolve the dependencies I cannot image to print them ordered

**Review by philbucher — APPROVED** [review]
works perfectly, thanks a lot @maceligueta !

**Comment by philbucher** [comment]
Hi @maceligueta 
I used this for some time now and I noticed that if an application is added AND coming from a dependency, it is printed that it comes from the dependency, which IMO should not be the case.
Could you please take another look?
Thanks a lot and sorry for bothering

**Comment by maceligueta** [comment]
Well, that's weird because I only append the application if it is added as a dependency and the message
`-- [Info] Adding dependency ${application_name} `
is printed.
I only append the app if we are inside this if. 
https://github.com/KratosMultiphysics/Kratos/blob/8d4dcdce074afc9a8dfac84b2fa5432e79a08778/cmake_modules/KratosDependencies.cmake#L9
I will take a careful look at it.

**Comment by philbucher** [comment]
thanks!
It is a bit weird, I also don't fully get what is happening

**Comment by roigcarlo** [comment]
I guess the problem is that, if added as a dependency, it takes precedence over the list of manually added apps.

The order in which are added in the script is respected, so if dependencies are included before apps that depend on them they should appear in the main list.

**Comment by maceligueta** [comment]
solved in #6140

**Pull request merged**
