### PR TITLE
[MeshingApplication] Reverting conflict that crashed the tests

### PR DESCRIPTION
**Pull request by loumalouomega**
That, error introduced on #5201

### CODE REVIEW

**Comment by philbucher** [comment]
thanks, ok from my side, @AlejandroCornejo can you try please?
I don't have MMG

**Comment by loumalouomega** [comment]
@AlejandroCornejo can you please check this?

**Comment by loumalouomega** [comment]
Please @AlejandroCornejo can you check this before leaving for holydays?

**Comment by AlejandroCornejo** [comment]
Hi @loumalouomega, I've compiled this branch and run the `test_MeshingApplication.py` and several errors arise:

```
Ran 26 of 665 test cases in 0.915929s. OK.
Unittests: Finished running cpp unit tests!
Unittests:
Running python tests ...
Unittests: TetrahedraReconnectUtility process is not compiled and the corresponding tests will not be executed
Unittests: TetrahedraReconnectUtility process is not compiled and the corresponding tests will not be executed
...Triangle3D3: The [3](-0.00841796,-0.480796,-0.136297) is in a distance: 0.00164565
Triangle3D3: The [3](0.441501,-0.0450113,0.223748) is in a distance: 0.00969658
Triangle3D3: The [3](-0.351819,-0.304748,0.177182) is in a distance: 0.00117434
Triangle3D3: The [3](0.112221,-0.371227,0.312282) is in a distance: 0.0272063
Triangle3D3: The [3](-0.263419,0.338901,0.252524) is in a distance: 0.00577466
Triangle3D3: The [3](0.0604449,0.37817,0.318612) is in a distance: 0.0166365
Triangle3D3: The [3](-0.06218,-0.495917,0.00377325) is in a distance: 0.00620845
Triangle3D3: The [3](0.188049,0.199199,-0.415604) is in a distance: 0.0104827
Triangle3D3: The [3](-0.406118,-0.116707,0.259395) is in a distance: 0.0180281
Triangle3D3: The [3](-0.175526,0.458274,0.0892903) is in a distance: 0.0256271
Triangle3D3: The [3](0.0890529,-0.486855,0.0674224) is in a distance: 0.0113554
.  ## WARNING: WRONG SOLUTION NUMBER. IGNORED
Geometry: Computation of local coordinates failed at iteration 0
Geometry: Computation of local coordinates failed at iteration 0
Geometry: Computation of local coordinates failed at iteration 0
Geometry: Computation of local coordinates failed at iteration 0
Geometry: Computation of local coordinates failed at iteration 0
Geometry: Computation of local coordinates failed at iteration 0
Geometry: Computation of local coordinates failed at iteration 0
Geometry: Computation of local coordinates failed at iteration 0
Geometry: Computation of local coordinates failed at iteration 0
Geometry: Computation of local coordinates failed at iteration 0
Geometry: Computation of local coordinates failed at iteration 0
Geometry: Computation of local coordinates failed at iteration 0
Geometry: Computation of local coordinates failed at iteration 0
Geometry: Computation of local coordinates failed at iteration 0
Geometry: Computation of local coordinates failed at iteration 0
Geometry: Computation of local coordinates failed at iteration 0
Geometry: Computation of local coordinates failed at iteration 0
Geometry: Computation of local coordinates failed at iteration 0
Geometry: Computation of local coordinates failed at iteration 0
Geometry: Computation of local coordinates failed at iteration 0
Geometry: Computation of local coordinates failed at iteration 0
Geometry: Computation of local coordinates failed at iteration 0
Geometry: Computation of local coordinates failed at iteration 0
Geometry: Computation of local coordinates failed at iteration 0
Geometry: Computation of local coordinates failed at iteration 0
Geometry: Computation of local coordinates failed at iteration 0
Geometry: Computation of local coordinates failed at iteration 0
Geometry: Computation of local coordinates failed at iteration 0
.EEEEEEEE
======================================================================
ERROR: test_execution (meshing_application_test_factory.TwoDDynamicBeamTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\KRATOS_MULTIPHYSICS\Kratos\applications\MeshingApplication\tests\meshing_application_test_factory.py", line 64, in test_execution
    self.test.RunSolutionLoop()
AttributeError: 'TwoDDynamicBeamTest' object has no attribute 'test'

======================================================================
ERROR: test_execution (meshing_application_test_factory.TwoDDynamicBeamTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\KRATOS_MULTIPHYSICS\Kratos\applications\MeshingApplication\tests\meshing_application_test_factory.py", line 69, in tearDown
    self.test.Finalize()
AttributeError: 'TwoDDynamicBeamTest' object has no attribute 'test'

======================================================================
ERROR: test_execution (meshing_application_test_factory.TwoDDynamicBeamLineLoadTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\KRATOS_MULTIPHYSICS\Kratos\applications\MeshingApplication\tests\meshing_application_test_factory.py", line 64, in test_execution
    self.test.RunSolutionLoop()
AttributeError: 'TwoDDynamicBeamLineLoadTest' object has no attribute 'test'

======================================================================
ERROR: test_execution (meshing_application_test_factory.TwoDDynamicBeamLineLoadTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\KRATOS_MULTIPHYSICS\Kratos\applications\MeshingApplication\tests\meshing_application_test_factory.py", line 69, in tearDown
    self.test.Finalize()
AttributeError: 'TwoDDynamicBeamLineLoadTest' object has no attribute 'test'

======================================================================
ERROR: test_execution (meshing_application_test_factory.ThreeDShellTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\KRATOS_MULTIPHYSICS\Kratos\applications\MeshingApplication\tests\meshing_application_test_factory.py", line 64, in test_execution
    self.test.RunSolutionLoop()
AttributeError: 'ThreeDShellTest' object has no attribute 'test'

======================================================================
ERROR: test_execution (meshing_application_test_factory.ThreeDShellTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\KRATOS_MULTIPHYSICS\Kratos\applications\MeshingApplication\tests\meshing_application_test_factory.py", line 69, in tearDown
    self.test.Finalize()
AttributeError: 'ThreeDShellTest' object has no attribute 'test'

======================================================================
ERROR: test_execution (meshing_application_test_factory.ThreeDDynamicBeamTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\KRATOS_MULTIPHYSICS\Kratos\applications\MeshingApplication\tests\meshing_application_test_factory.py", line 64, in test_execution
    self.test.RunSolutionLoop()
AttributeError: 'ThreeDDynamicBeamTest' object has no attribute 'test'

======================================================================
ERROR: test_execution (meshing_application_test_factory.ThreeDDynamicBeamTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\KRATOS_MULTIPHYSICS\Kratos\applications\MeshingApplication\tests\meshing_application_test_factory.py", line 69, in tearDown
    self.test.Finalize()
AttributeError: 'ThreeDDynamicBeamTest' object has no attribute 'test'

----------------------------------------------------------------------
Ran 9 tests in 9.247s

FAILED (errors=8)
```

**Comment by loumalouomega** [comment]
Are you sure?, this branch?

**Comment by AlejandroCornejo** [comment]
> Are you sure?, this branch?

yes I do! 
image

**Comment by loumalouomega** [comment]
> > Are you sure?, this branch?
> 
> yes I do!
> image

imagen

**Comment by loumalouomega** [comment]
imagen
Works in my machine, can you try again?

**Comment by AlejandroCornejo** [comment]
I've just tried again (performing the pull even)  and shows the same... Maybe is the version of the MMG?

**Comment by AlejandroCornejo** [comment]
okkey! I've re-changed the branch a now it works... Something weird happens with the VStudio o smthg :S

image

**Review by AlejandroCornejo — APPROVED** [review]
now the tests are OK

**Pull request merged**
