### PR TITLE
[Core] Missing dummy elements

### PR DESCRIPTION
**Pull request by loumalouomega**
Triangle2D6, Quadrilateral2D8, Quadrilateral2D9, Prism3D15, Hexahedra3D20 and Hexahedra3D27 were missing

### CODE REVIEW

**Review by philbucher — APPROVED** [review]
looks ok to me

@loumalouomega can you please fix the nightly tests in the ContactApp?
https://github.com/KratosMultiphysics/Kratos/runs/376637649

**Comment by loumalouomega** [comment]
> 
> 
> looks ok to me
> 
> @loumalouomega can you please fix the nightly tests in the ContactApp?
> https://github.com/KratosMultiphysics/Kratos/runs/376637649

Strange, it wasn't failing before?

**Comment by philbucher** [comment]
> Strange, it wasn't failing before?

was always failing in Github, since we added it before christmas

**Comment by loumalouomega** [comment]
Ok, I thought started failing now

**Pull request merged**
