### PR TITLE
[Core][Strategies] using global num constraints to skip Apply for constraints

### PR DESCRIPTION
**Pull request by adityaghantasala**
The changes stem from my implementations in a different branch. 

Currently the `Apply` and `ResetSlaveDofs` function calls of the MS constraints and the `TSparseSpace::SetToZero(rDx);`  in the Predict of Newton-Raphson strategy are guarded by an if statement which checks if there are any constraints on the modelpart. 

In MPI checking if the constraints exist locally is not sufficient as `TSparseSpace::SetToZero(rDx);`  would require a all to all communication in the comm. 

https://github.com/KratosMultiphysics/Kratos/blob/bb911f5415e24c0304e4af22cc2729ec771dbf6a/kratos/solving_strategies/strategies/residualbased_newton_raphson_strategy.h#L518

This pr changes the check to use the global_number_of_constraints. 

In serial the r_comm.SumAll() will have no effect.

### CODE REVIEW

**Review by loumalouomega — DISMISSED** [review]
Should this method be defined in the base strategy (to avoid code duplication), and be called in each strategy?

**Comment by loumalouomega** [comment]
Appveyor fails

**Comment by adityaghantasala** [comment]
@loumalouomega The mpDx is not available in the base solver. So we cannot move it to the base strategy.

**Comment by loumalouomega** [comment]
> 
> 
> @loumalouomega The mpDx is not available in the base solver. So we cannot move it to the base strategy.

It can be done as a method with the corresponding input (rDx)

**Comment by philbucher** [comment]
> Should this method be defined in the base strategy (to avoid code duplication), and be called in each strategy?

I suggest to discuss this separately

**Comment by loumalouomega** [comment]
> 
> 
> > Should this method be defined in the base strategy (to avoid code duplication), and be called in each strategy?
> 
> I suggest to discuss this separately

I approved the PR, I was just simply introducing a question

**Comment by adityaghantasala** [comment]
@loumalouomega  Thank you. I will do that once I am done with other PR I have in line. 
Can anyone re-approve ?

**Review by loumalouomega — APPROVED** [review]

**Comment by adityaghantasala** [comment]
@loumalouomega  Thank you .. !

**Review by RiccardoRossi — COMMENTED** [review]
ok to me

**Pull request merged**
