### PR TITLE
[Structural] restore test

### PR DESCRIPTION
**Pull request by philbucher**
I noticed the CI started failing since the beam uses the consistent mass matrix now
Hence I am making a pretty tight tolerance in a test slightly less tight

### CODE REVIEW

**Comment by RiccardoRossi** [comment]
probably we should update the reference result and keep it tight

**Comment by philbucher** [comment]
On clang it gives the original result and on gcc it is slightly (5e-11) different

I even made that comment when I initially wrote the test that this might be too tight

**Comment by philbucher** [comment]
I will go back to use the lumped MM then I can keep it tight

**Review by loumalouomega — DISMISSED** [review]

**Comment by philbucher** [comment]
now it does exactly the same as before, same tight tolerance

**Comment by philbucher** [comment]
can someone reapprove to not block the CI?

**Review by loumalouomega — APPROVED** [review]

**Pull request merged**
