### PR TITLE
[CMake] Defaulting the coloring of the `Logger`

### PR DESCRIPTION
**Pull request by loumalouomega**
**📝 Description**

Defaulting the coloring of the `Logger`.

**🆕 Changelog**

- [Defaulting the coloring of the `Logger`](https://github.com/KratosMultiphysics/Kratos/commit/03ddb69b0cd7e58fb8189e2c74790dc8890d9b00)

### CODE REVIEW

**Review by roigcarlo — COMMENTED** [review]
Won't this print a lot of noise if run on terminals with no support for colors?

Sorry to ask but I am completely clueless about the implementation of this feature.

**Comment by loumalouomega** [comment]
> Won't this print a lot of noise if run on terminals with no support for colors?
> 
> Sorry to ask but I am completely clueless about the implementation of this feature.

Right, I can just sinly put it in false by default, but until now was there but hidden.

**Comment by roigcarlo** [comment]
Pls

**Comment by roigcarlo** [comment]
Well if it was there already and was enabled by default ok. (I was not aware if it)

**Review by roigcarlo — APPROVED** [review]

**Comment by loumalouomega** [comment]
> Well if it was there already and was enabled by default ok. (I was not aware if it)

Huum, i was cahnging it, a priori was not defaulted, I can change the default

**Pull request merged**
