### PR TITLE
[Core][CompareTwoFilesCheckProcess] adding relative tolerance

### PR DESCRIPTION
**Pull request by philbucher**
requires #3229

### CODE REVIEW

**Review by loumalouomega — APPROVED** [review]
OK

**Comment by philbucher** [comment]
I need a reapproval :)

EDIT: I think I don't

**Comment by loumalouomega** [comment]
Nope

**Comment by philbucher** [comment]
And again you were faster :)

**Comment by loumalouomega** [comment]
Gotta go faster!!!

https://www.youtube.com/watch?v=paZcBwCLLBM

**Pull request merged**
