### PR TITLE
[legacy] removed incompressiblefluidapp

### PR DESCRIPTION
**Pull request by philbucher**
app already moved to the legacy repo

### CODE REVIEW

**Comment by sunethwarna** [comment]
All the unit tests are passing in Fluid, Trilinos, Structural, FSI, Mapping, MeshMoving, Meshing, Metis, ExternalSolvers, Eigen, ShapeOptimization.

**Comment by rubenzorrilla** [comment]
Cool. No complaints from my side. But let's wait a few days to merge this.

I'm tagging here the users of the incompressiblefluidappliccation that come to my mind
@playpaolo 
@juliobarna 
Guys, if I forgot someone, please let him know.

**Review by RiccardoRossi — APPROVED** [review]
ok, this has been posted for a while. Also the code is simply moved to legacy, right?

**Comment by philbucher** [comment]
> ok, this has been posted for a while. Also the code is simply moved to legacy, right?

Yes its already there

**Comment by philbucher** [comment]
early Christmas present:
this reduced the size of the repo from 311.8MB to 277.7MB!

**Pull request merged**
