### PR TITLE
Merge external_libraries/amgcl with upstream

### LINKED ISSUE #3066: [AMGCL] is less robust than the one with release 5.1
After updating the AMGCL from the one in release 5.1 of Kratos to the newer ones we observed that our solutions become unstable and examples that are working with AMGCL 5.1 start crashing with newer versions. 

We have tested two different versions which gave different behaviors;
- AMGCL which is packed with release 6.0 after some time steps starts to diverge from the results given by the older solver and finally crashes both in fluid and thermal problems
- AMGCL in master ( dcc5cd85ba7e58c4a2e41a30ee0537a22e102850 ) gives very similar results comparing to the previous version but crashes randomly in some cases

I have attached the [matrices](https://github.com/KratosMultiphysics/Kratos/files/2482093/failing_example.zip) of a solution in which in step 6 the solver start diverging and in step 8 it just crashes. The  lgmres solver and ilu0 preconditioner combining with multigrid is used for this solution

@ddemidov would you please take a look at it.

### PR DESCRIPTION
**Pull request by ddemidov**
This should fix #3066 and close #3106. The relevant upstream changes are:

* ddemidov/amgcl@65c0467
  Remove store_Av option from lgmres
  The option is broken with right preconditioning
* ddemidov/amgcl@af31e4e
   One cycle of LGMRES(M,K) should have (M+K), not M vectors
* ddemidov/amgcl@d49a108
   Append, rather than prepend augmentation vectors in LGMRES
   This brings the code in accordance with the original LGMRES paper.

### CODE REVIEW

**Review by loumalouomega — DISMISSED** [review]
Let's wait for @RiccardoRossi

**Comment by ddemidov** [comment]
I would also ping @ddiezrod.

**Comment by ddiezrod** [comment]
Just to make things clear, this should work also with the "right" preconditioner, am I correct? @ddemidov

**Comment by ddemidov** [comment]
Yes, see some experiments here: https://github.com/KratosMultiphysics/Kratos/pull/3106#issuecomment-431290373

**Comment by ddiezrod** [comment]
With this change, the solver passes the tests that I had. It will need some more validation but apparently the problem is solved. Thanks @ddemidov !

**Review by RiccardoRossi — APPROVED** [review]

**Review by RiccardoRossi — DISMISSED** [review]

**Comment by ddemidov** [comment]
Please hold on, I think there is another potential bug in amgcl lgmres. I'll push more commits here if that is the case.

**Comment by ddemidov** [comment]
I've pushed two more changes upsteam. Those are fixes backported from scipy lgmres:

* ddemidov/amgcl@af31e4e
  One cycle of LGMRES(M,K) should have (M+K), not M vectors
* ddemidov/amgcl@d49a108
  Append, rather than prepend augmentation vectors in LGMRES.
  This brings the code in accordance with the original LGMRES paper.

The first change increases LGMRES(M,K) cycle size from M to M+K, so in order to get somewhat equivalent result to the old code, one should test with LGMRES(M-K,K). This may be important if the problem is sensitive to number of GMRES iterations before restart.

Both of these seem to have minor influence on performance with the matrices I tested, and are only included for the sake of correctness.

**Review by RiccardoRossi — APPROVED** [review]

**Comment by pooyan-dadvand** [comment]
Thank @ddemidov for your fast reaction in solving the issue! 👍

**Pull request merged**
