### PR TITLE
Defining Core and Python libs for TrilinosApplication.

### PR DESCRIPTION
**Pull request by jcotela**
I need this in order to invert the dependency between FluidDynamicsApplication and TrilinosApplication (I cannot link directly from FluidDynamics to the trilinos python module).

closes #4705

### CODE REVIEW

**Comment by philbucher** [comment]
this properly implements #4705 

To me looks good but I don't feel fully confident with the CMake, hence I would prefer for @roigcarlo to approve

**Review by roigcarlo — DISMISSED** [review]
Looks good to me :+1: .  Just a minor comment

If we want to be perfectly safe, we should add `KRATOS_API(TRILINOS_APPLICATION)` to the class definition of the application:
```C++
/// Short class definition.
/** Detail class definition.
*/
class KRATOS_API(TRILINOS_APPLICATION) KratosTrilinosApplication : public KratosApplication {
   public:
    ///@name Type Definitions
    ///@{
```

And in all the classes with source files that are used in the python api (probably only `mpi_normal_calculation_utilities`and `trilinos_linear_solver_factory`, but I am not 100% sure)

Anyway I am going to approve since the changes are only needed in win and its trilinos so it dosn't really matter, so as you see (if you do the changes ping me and I will reaprove).

**Comment by jcotela** [comment]
@roigcarlo I added the API, but I have no clue if the linear solver factory one in particular is correct (the `KratosComponents` thing at the end is the same thing that gave us all those clang warnings last year in the core).

**Comment by jcotela** [comment]
For what is worth, the code as in this branch compiles cleanly in cmake and gcc. No idea about windows though...

**Review by roigcarlo — APPROVED** [review]
I think that should be enough thx!

**Pull request merged**
