### PR TITLE
[StructuralMechanics] removing Solve

### PR DESCRIPTION
**Pull request by philbucher**
this method is very deprecated and only gives problems (see #3375)

in a standard-workflow this is not used for a while already

Btw this brings also back the possibility to use `clear_storage` in a standard-case

### CODE REVIEW

**Comment by philbucher** [comment]
@armingeiser @MFusseder you should also remove `Solve` from `StructuralMechanicsAdjointStaticSolver` but I don't know how
EDIT: I think you can just remove it

**Review by loumalouomega — DISMISSED** [review]
Ok

**Comment by MFusseder** [comment]
Okay, I will have a look on it.

**Comment by MFusseder** [comment]
@philbucher you are right. ```Solve()``` of the ```StructuralMechanicsAdjointStaticSolver``` is useless and can just removed. Shall we do this within this PR or in a separate one? What do you prefer?

**Comment by philbucher** [comment]
I suggest to push it here directly

**Comment by MFusseder** [comment]
Okay, one moment.

**Review by armingeiser — APPROVED** [review]
I approve the change in the adjoint solver, i think the rest has already been approved before.

**Pull request merged**
