### PR TITLE
Update amgcl

### PR DESCRIPTION
**Pull request by ddemidov**
This updates AMGCL and the corresponding wrapper code in Kratos. Among immediate advantages should be reduced compile time, reduce compile-time memory requirements (important for windows users), and a couple of fixed bugs improving runtime efficiency.

I did not run any tests locally in hope CI setup here will take care of that.

Note to reviewers: the first commit just updates amgcl, only the second one deals with internal Kratos code.

### CODE REVIEW

**Comment by ddemidov** [comment]
Ok, Travis and Appveyor tests are working now.

**Review by RiccardoRossi — APPROVED** [review]
this looks good to me and i think it is quite an improvement

@ddemidov still i would hold on one-two days to see if anyone volunteers to check this branch. (I would "volunteer" myself but i am travelling)

**Comment by RiccardoRossi** [comment]
@ddemidov,

please feel free  go ahead with the merging

**Comment by ddemidov** [comment]
Someone with write access will have to do this :).

**Comment by loumalouomega** [comment]
Volunteer

**Pull request merged**
