### PR TITLE
[Core][VtkOutput] move parameters to top of file and switch to binary format by default

### PR DESCRIPTION
**Pull request by philbucher**
**Description**
Whenever I search sth in the defaults of the vtk output it is annoying to scroll down to the end of the long file.
With this change the default parameters are easily visible

### CODE REVIEW

**Comment by adityaghantasala** [comment]
Now that we are here, the default output is of "ascii" type. Shall we change it to "binary" ? 
I remember the reason to write ascii files was that binary was not completely implemented. Now that we know it is working robustly, I believe we can change it  to binary. 
@philbucher  what do you think ?

**Comment by philbucher** [comment]
> Now that we are here, the default output is of "ascii" type. Shall we change it to "binary" ?
> I remember the reason to write ascii files was that binary was not completely implemented. Now that we know it is working robustly, I believe we can change it to binary.
> @philbucher what do you think ?

I think we didn't do that right away bcs we were not sure abt how it works on win
now I think it is safe to switch

btw changin it now was super easy bcs I didn't have to scroll to the end of the file :)

**Review by adityaghantasala — DISMISSED** [review]

**Comment by philbucher** [comment]
marked it as behavior change as we now use binary instead of ascii by default

**Comment by philbucher** [comment]
@armingeiser seems like you have a test that relies on the default to be ascii
can you please check?

**Comment by philbucher** [comment]
thx
can you reapprove pls?

**Review by adityaghantasala — DISMISSED** [review]

**Comment by philbucher** [comment]
@armingeiser seems like your solution doesn't work :)

**Comment by philbucher** [comment]
now seems to work
but I still need approval :)

**Review by armingeiser — APPROVED** [review]

**Pull request merged**
