### PR TITLE
[Core][Apps] C++ classes derived settings

### PR DESCRIPTION
**Pull request by philbucher**
**Description**
This PR introduces the recursive validation for the `SolvingStrategy`. It works the same as the python version that I added in #4736.
After this PR is through the same mechanism can and should be used for the other classes with `Parameters` constructors

The mechanism is a bit more complicated than in python bcs of how the classes are instantiated. Basically I cannot call functions of derived classes in the base-constructor

In a nutshell the mechanism works in the following way:
~~~c++
class Base
{
public:
    // regular CTor that gets called from outside
    class Base(params) : Base(params, Base::Defaults()) { }

    static Parameters Defaults()
    {
        // defaults = ...
        return defaults;
    }

protected:
    // protected CTor, called from regular CTor AND derived classes
    Base(params, defaults)
    {
        params.ValidateAndAssignDefaults(defaults)
        // assign settings of base class
    }
};

class Derived : Base
{
public:
    // regular CTor that gets called from outside
    class Derived(params) : Derived(params, Derived::Defaults()) { }

    static Parameters Defaults()
    {
        // defaults = ...
        defaults.AddMissingParameters(Base::Defaults());
        return defaults;
    }

protected:
    // protected CTor, called from regular CTor AND derived classes
    Derived(params, defaults) : Base(params, defaults)
    {
        // assign settings of this class
        // ...
    }
};
~~~

**Additional info**
necessary for #5939

### CODE REVIEW

**Comment by loumalouomega** [comment]
I did the very same thing in my machine, I will push in one hour and create a new PR. This will include all the changes needed in #3185

**Review by loumalouomega — CHANGES_REQUESTED** [review]
Conflicts with local changes, wait

**Comment by philbucher** [comment]
:D

good things I didn't spend hours on this... :man_facepalming:

**Comment by loumalouomega** [comment]
> :D
> 
> good things I didn't spend hours on this... man_facepalming

We almost thought in the same design :D

**Comment by loumalouomega** [comment]
@philbucher tests do not pass

**Comment by philbucher** [comment]
I didn't check the tests, this is a proposal

the line search and the NR do some hacky stuff there that can be done properly with this proposal

I am checking it now

**Comment by philbucher** [comment]
I checked again, the problem with this approach is that all the Ctors that are called from derived classes need a protected version that also accepts the default settings

I don't really like neither this approach nor #7290. 

In a nutshell the problems are:
- We cannot call virtual functions from base-CTors (this is what works in Python and what makes it easy)
- **Who does the validation?** => doing it in the baseclass fails (unless the defaults of the derived class are known) bcs things from the derived class will be present, but then who does it? Note that every class can be a baseclass for another class => that what I did the trick with the CTor that passes the defaults to the baseclass.

**Comment by loumalouomega** [comment]
> I checked again, the problem with this approach is that all the Ctors that are called from derived classes need a protected version that also accepts the default settings
> 
> I don't really like neither this approach nor #7290.
> 
> In a nutshell the problems are:
> 
>     * We cannot call virtual functions from base-CTors (this is what works in Python and what makes it easy)
> 
>     * **Who does the validation?** => doing it in the baseclass fails (unless the defaults of the derived class are known) bcs things from the derived class will be present, but then who does it? Note that every class can be a baseclass for another class => that what I did the trick with the CTor that passes the defaults to the baseclass.

But at least #7290 works...

**Comment by loumalouomega** [comment]
> > I checked again, the problem with this approach is that all the Ctors that are called from derived classes need a protected version that also accepts the default settings
> > I don't really like neither this approach nor #7290.
> > In a nutshell the problems are:
> > ```
> > * We cannot call virtual functions from base-CTors (this is what works in Python and what makes it easy)
> > 
> > * **Who does the validation?** => doing it in the baseclass fails (unless the defaults of the derived class are known) bcs things from the derived class will be present, but then who does it? Note that every class can be a baseclass for another class => that what I did the trick with the CTor that passes the defaults to the baseclass.
> > ```
> 
> But at least #7290 works...

Which is the main problem of #7290?

**Comment by philbucher** [comment]
#7290 skips the problems by not calling the Ctors which means that important things have to be copy pasted

**Comment by loumalouomega** [comment]
> #7290 skips the problems by not calling the Ctors which means that important things have to be copy pasted

I don't copy paste, see the code, it does a recursion

**Comment by philbucher** [comment]
> > #7290 skips the problems by not calling the Ctors which means that important things have to be copy pasted
> 
> I don't copy paste, see the code, it does a recursion

but how do you use this for non-parameter inputs?

**Comment by loumalouomega** [comment]
> > > #7290 skips the problems by not calling the Ctors which means that important things have to be copy pasted
> > 
> > 
> > I don't copy paste, see the code, it does a recursion
> 
> but how do you use this for non-parameter inputs?

What do you mean?

**Comment by philbucher** [comment]
e.g parameters that get scheme and parameters

**Comment by loumalouomega** [comment]
> e.g a CTor that get scheme and parameters

Originally the code there was already duplicated..., in any case that interface should be deprecated and we should use full parameters in order to avoid duplication

**Comment by philbucher** [comment]
I am not sure if this is always possible
imagine using the same scheme (just an example) fro two strategies

**Comment by loumalouomega** [comment]
> I am not sure if this is always possible
> imagine using the same scheme (just an example) fro two strategies

I see, in that case I can think a way to minimize code duplication, which BTW I only added 6  lines in those constructors, and technically does not duplicate assigning

**Comment by loumalouomega** [comment]
> > I am not sure if this is always possible
> > imagine using the same scheme (just an example) fro two strategies
> 
> I see, in that case I can think a way to minimize code duplication, which BTW I only added 6 lines in those constructors, and technically does not duplicate assigning

Look at #7290 and comment there which needs to be changed

**Comment by philbucher** [comment]
closing as #7290 is the accepted solution

**Pull request closed without merging**
