### PR TITLE
[Core] Update SubModelPartContainer in Python

### PR DESCRIPTION
**Pull request by tteschemacher**
As we add the map within the container interfaces (#6288) we can update the SubModelPartContainer accordingly. That brings us more of the map functions within python.

### CODE REVIEW

**Review by loumalouomega — COMMENTED** [review]
Travis fails, besides if the interface is specific for this class I would define it directly

**Comment by tteschemacher** [comment]
The issue is about the id. Geometries are sorted by id. SubModelParts by name.

**Comment by loumalouomega** [comment]
@tteschemacher can we delete the branch?

**Comment by tteschemacher** [comment]
I think this one could still be merged. Not sure what it actually does, though...

**Comment by loumalouomega** [comment]
> I think this one could still be merged. Not sure what it actually does, though...

I am just asking. Check if it is relevant.

**Pull request closed without merging**
