### PR TITLE
Fixed DEM main script (broken due to the previous repo corruption)

### PR DESCRIPTION
**Pull request by maceligueta**
Benchmarks are also fixed in this PR.

### CODE REVIEW

**Comment by maceligueta** [comment]
@farrufat-cimne : I am having problems with the benchmarks. Can you please check what is the problem? Apparently, some Ids are not found...
Maybe there's some other file that was corrupted, you are the expert with the benchmarks.

**Comment by pooyan-dadvand** [comment]
This affects the release?

**Comment by maceligueta** [comment]
Totally. Sorry about that but we were not aware that this files wer corrupted during the accident of last week.

**Comment by pooyan-dadvand** [comment]
I perfectly understand! It was only to add it to milestone to see it in release related problem. (as you added)

**Comment by farrufat-cimne** [comment]
the benchmarking systems seems to be working as intended.

**Review by farrufat-cimne — APPROVED** [review]
good

**Comment by maceligueta** [comment]
do not merge yet, please.

**Pull request merged**
