### PR TITLE
[Trilinos] clean python scripts

### PR DESCRIPTION
**Pull request by philbucher**
as discussed, only deleting unused/outdated things, moving the ones related to the structural application there

### CODE REVIEW

**Comment by RiccardoRossi** [comment]
@philbucher we were discussing the other day if the history is preserved when a file is renamed.

any clue on that?

**Comment by philbucher** [comment]
Yes, see the discussion in #3772
Use git log —follow file-name

Unfortunately it is not visible through the github webpage
But there seems to be a chrome extension for this

**Comment by philbucher** [comment]
ping @jcotela

**Comment by jcotela** [comment]
I am OK with the changes, but I'd like confirmation from @jrubiogonzalez @KratosMultiphysics/altair that applications/trilinos_application/python_scripts/trilinos_levelset_solver.py is no longer needed.

**Comment by ddiezrod** [comment]
@jcotela We do not use anything from trillinos application yet. Thanks for the comment!

**Comment by philbucher** [comment]
@KratosMultiphysics/altair even if you need sth in the future, you can get it through the history of git or from an older release-branch

**Comment by roigcarlo** [comment]
I understand that there is no proble, so I'll approve

**Review by roigcarlo — APPROVED** [review]

**Comment by philbucher** [comment]
thanks

**Comment by philbucher** [comment]
apparently I deleted files that were no longer existing bcs renamed :)
I will make a new PR, sorry for the noise

**Pull request merged**
