### PR TITLE
CompareTwoFilesCheckProcess: removing trailing whitespaces

### PR DESCRIPTION
**Pull request by philbucher**
just that, otherwise it can screw up the file comparison even if it is a valid file

### CODE REVIEW

**Review by loumalouomega — DISMISSED** [review]
OK

**Comment by philbucher** [comment]
@loumalouomega I had forgotten sth, can you reapprove pls?

**Comment by philbucher** [comment]
Hm sth is wrong, I have to check

**Review by loumalouomega — DISMISSED** [review]
OK

**Comment by philbucher** [comment]
@loumalouomega I found a minor error I fixed, can you please give it another go? :)

**Review by loumalouomega — APPROVED** [review]

**Comment by philbucher** [comment]
Thx

**Pull request merged**
