### PR TITLE
cps/moving find nodal neightboursprocess

### PR DESCRIPTION
**Pull request by inigolcanalejo**
Small PR where the FindNodalNeighboursProcess is moved from the wake process 2d to the far field process.

The reason is that the far field process is always called.

### CODE REVIEW

**Comment by marcnunezc** [comment]
Hi @inigolcanalejo !

Can we move it to the Initialize() of the solvers instead?
For instance:

in the potential_solver:
```
    def _ComputeNeighbours(self):
        # Find nodal neigbours util call
        avg_elem_num = 10
        avg_node_num = 10
        KratosMultiphysics.FindNodalNeighboursProcess(
            self.main_model_part, avg_elem_num, avg_node_num).Execute()

    def Initialize(self):
        self._ComputeNeighbours()

        time_scheme = KratosMultiphysics.ResidualBasedIncrementalUpdateStaticScheme()
        if "incompressible" in self.settings["formulation"]["element_type"].GetString():
            # TODO: Rename to self.strategy once we upgrade the base FluidDynamicsApplication solvers
            self.solver = KratosMultiphysics.ResidualBasedLinearStrategy(
                self.GetComputingModelPart(),
                time_scheme,
                self.linear_solver,
                self.settings["compute_reactions"].GetBool(),
                self.settings["reform_dofs_at_each_step"].GetBool(),
                self.settings["calculate_solution_norm"].GetBool(),
                self.settings["move_mesh_flag"].GetBool())
        elif "compressible" in self.settings["formulation"]["element_type"].GetString():
        .......

```

in the adjoint_solver:
```
    def Initialize(self):

        self._ComputeNeighbours()

        """Perform initialization after adding nodal variables and dofs to the main model part. """
        if self.response_function_settings["response_type"].GetString() == "adjoint_lift_jump_coordinates":
            self.response_function = KCPFApp.AdjointLiftJumpCoordinatesResponseFunction(self.main_model_part, self.response_function_settings)
        else:
       ............
```

The reason is that in the embedded case, we are doing the refinement in a process.Initialize(). If we have this method in the cosntructor of the processes, the neighbour computation will be performed BEFORE remeshing. After remeshing, new elements and conditions are genereated so the previous neighbours are wrong.

If we do this in the solver initialize it works because this is perfromed after doing all the process.Initialize() (so we are remeshed already).

With this change we can also remove these lines in the level_set_remeshing_process.py:

https://github.com/KratosMultiphysics/Kratos/blob/df2f7b36825806c2623a3357bab23a43e2989680/applications/CompressiblePotentialFlowApplication/python_scripts/level_set_remeshing_process.py#L86-L93

**Comment by philbucher** [comment]
I would say that if your solver always needs it it should be in the solver not in a process

**Comment by inigolcanalejo** [comment]
@marcnunezc and @philbucher thanks for the quick review. I moved it to the Initialize of the solvers as you suggested.

**Comment by marcnunezc** [comment]
Can you also remove these lines from the level_set_remeshing process?

https://github.com/KratosMultiphysics/Kratos/blob/df2f7b36825806c2623a3357bab23a43e2989680/applications/CompressiblePotentialFlowApplication/python_scripts/level_set_remeshing_process.py#L86-L93

**Comment by inigolcanalejo** [comment]
Sorry I forgot, now it should be ok

**Review by marcnunezc — APPROVED** [review]

**Pull request merged**
