### PR TITLE
Defining kratos shared ptr

### PR DESCRIPTION
**Pull request by RiccardoRossi**
hello

i am making this PR to centralize the definition of shared_ptr being used in kratos (definition is in define.h)

the goal is to make ready for switching (in a future) to std::shared_ptr by a one-line change

### CODE REVIEW

**Review by RiccardoRossi — COMMENTED** [review]
just to make it clear

Kratos::shared_ptr IS STILL boost::shared_ptr,

just an alias to it

**Comment by loumalouomega** [comment]
I will fix the conficts after the merge of my PR

**Comment by RiccardoRossi** [comment]
i am closing this since we decided to split this commit in multiple ones to minimize conflicts

**Comment by loumalouomega** [comment]
@RiccardoRossi, should the branch be deleted?

**Comment by philbucher** [comment]
@RiccardoRossi isn't this the branch you were looking for yesterday?

**Comment by philbucher** [comment]
@RiccardoRossi I believe this branch can be deleted ...?

**Comment by RiccardoRossi** [comment]
@philbucher the branch with the pybind11 port is derived from this. I would keep it alive as long as we didn't merge the pybind11 just to be sure not to break anything...

**Pull request closed without merging**
