### PR TITLE
[Core] move DataLocation to Globals

### PR DESCRIPTION
**Pull request by philbucher**
This has been on my todo list for a while, but never got to it
Now motivated by #11217 
FYI @AlejandroCornejo

### CODE REVIEW

**Review by loumalouomega — DISMISSED** [review]
It's okay IMHO

**Comment by matekelemen** [comment]
while we're here, can you expose it to python plz?

Mesh types could also have their own ```enum``` as well (local, ghost, interface - whatever that is).

**Comment by philbucher** [comment]
> while we're here, can you expose it to python plz?

Done @matekelemen

**Review by matekelemen — APPROVED** [review]
thanks!

**Pull request merged**
