### PR TITLE
[Structural] update shell tests

### LINKED ISSUE #7469: [StructuralMechanicsApp] failing Shell tests
Some shell tests in the StructuralMechanicsApp are failing.
I compiled older versions of Kratos, up to 10 Months ago, there they already fail.
I didn't yet further investigate as before that we used the old compilation mechanism which I have no longer set up

The Shells haven't really been modified, I think this is a more global thing

@KratosMultiphysics/structural-mechanics 

~~~
======================================================================
FAIL: test_execution (structural_mechanics_test_factory.ShellT3ThickNonLinearStaticTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/philippb/software/Kratos_aux/applications/StructuralMechanicsApplication/tests/structural_mechanics_test_factory.py", line 72, in test_execution
    self.test.RunSolutionLoop()
  File "/home/philippb/software/Kratos_aux/install/KratosMultiphysics/analysis_stage.py", line 69, in RunSolutionLoop
    self.FinalizeSolutionStep()
  File "/home/philippb/software/Kratos_aux/install/KratosMultiphysics/analysis_stage.py", line 151, in FinalizeSolutionStep
    process.ExecuteFinalizeSolutionStep()
  File "/home/philippb/software/Kratos_aux/install/KratosMultiphysics/from_json_check_result_process.py", line 55, in ExecuteFinalizeSolutionStep
    self.assertTrue(self.process.IsCorrectResult(), "Results do not coincide with the JSON reference\n" + self.process.GetErrorMessage())
AssertionError: False is not true : Results do not coincide with the JSON reference
Error checking for variable REACTION_Y, results:
Node 1 -206.5734!=-140.6796; rel_tol=1e-06, abs_tol=0.001


======================================================================
FAIL: test_execution (structural_mechanics_test_factory.ShellQ4ThinNonLinearStaticTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/philippb/software/Kratos_aux/applications/StructuralMechanicsApplication/tests/structural_mechanics_test_factory.py", line 72, in test_execution
    self.test.RunSolutionLoop()
  File "/home/philippb/software/Kratos_aux/install/KratosMultiphysics/analysis_stage.py", line 69, in RunSolutionLoop
    self.FinalizeSolutionStep()
  File "/home/philippb/software/Kratos_aux/install/KratosMultiphysics/analysis_stage.py", line 151, in FinalizeSolutionStep
    process.ExecuteFinalizeSolutionStep()
  File "/home/philippb/software/Kratos_aux/install/KratosMultiphysics/from_json_check_result_process.py", line 55, in ExecuteFinalizeSolutionStep
    self.assertTrue(self.process.IsCorrectResult(), "Results do not coincide with the JSON reference\n" + self.process.GetErrorMessage())
AssertionError: False is not true : Results do not coincide with the JSON reference
Error checking for variable REACTION_Y, results:
Node 1 -160.0308!=-138.1294; rel_tol=1e-06, abs_tol=0.001
~~~

### PR DESCRIPTION
**Pull request by philbucher**
**Description**
closes #7469

I am updating the test results of tests that fail since a very long time. I suspect that the changes came from the changes we did in the ConvCrit & NR strategy 2 years ago

I am using the shells extensively hence I am quite confident abt this change

also added some missing `skipTest`

### CODE REVIEW

**Comment by philbucher** [comment]
looking at the new results I noticed that only the very first step has different results, hence I am quite sure this is related to the changes I mentioned above

**Review by AlejandroCornejo — DISMISSED** [review]
ok!!! THX

**Comment by AlejandroCornejo** [comment]
Let me know when you're done and I'll apporove 👯

**Comment by philbucher** [comment]
now is ready :)

**Review by AlejandroCornejo — APPROVED** [review]
okkkk

**Pull request merged**
