### PR TITLE
[Core] Encapsulation of the prints showing the progress of the analysis

### PR DESCRIPTION
**Pull request by maceligueta**
For applications where the time step is very small, this print is very annoying. For example we do not print every time step in DEM, but one out of many.
I am proposing this encapsulation in a method, such that it can be overriden by the derived classes and customized.

### CODE REVIEW

**Comment by maceligueta** [comment]
@KratosMultiphysics/technical-committee

**Comment by philbucher** [comment]
+1 from my side, I agree that we need a better solution for this

**Comment by loumalouomega** [comment]
In the contactstructural some info is just printed when generating a post
file.

**Comment by maceligueta** [comment]
@loumalouomega  You are adding prints here:
https://github.com/KratosMultiphysics/Kratos/blob/d7cec62eb3ef0d212e3b735f90d541940eb56b52/applications/ContactStructuralMechanicsApplication/python_scripts/contact_structural_mechanics_analysis.py#L39
But I am talking about removing the prints by the base class, or modifying them.

**Review by philbucher — APPROVED** [review]
Approving since this is a small improvement and @KratosMultiphysics/technical-committee has many things to be discussed

Also it has been open for some time such that ppl coould have a look

@KratosMultiphysics/technical-committee if you have any comments pls add them

thanks @maceligueta

**Pull request merged**
