### PR TITLE
[Core] Making Trilinos detection more automatic (at least for Ubuntu)

### PR DESCRIPTION
**Pull request by loumalouomega**
**Description**
This avoid to manually define TRILINOS_LIBRARY_PREFIX at least in Ubuntu

**Changelog**
- Added default value to TRILINOS_LIBRARY_PREFIX

### CODE REVIEW

**Comment by philbucher** [comment]
this is a behavior change no?
i.e. if the trilinos libs have no prefix with this change it will no longer work? I.e. one would manually have to set the prefix to "" in cmake?

(not the expert for CMake)

**Review by roigcarlo — CHANGES_REQUESTED** [review]
No against the idea, but implemented like this makes libraries compiled with the default setting unable to be located (tested in my env, but possibly clusters too).

If this has to work for ubuntu that code should be on a operating system switch

**Comment by philbucher** [comment]
well even in ubuntu if you compile the libs with the default settings it will no longer be found by default

**Comment by philbucher** [comment]
@roigcarlo do you know if it would be possible to make CMake try to find the libs without the prefix and if it is not found then it tries again with the prefix?

**Comment by roigcarlo** [comment]
We could define a `TRILINOS_FOUND` variable so the module behaves like python, metis, etc... 
```CMake
find(Trilinos)
```

Then you can put the prefix deduction logic there, but you will need to have a list or set it as optional parameter from the outside ( like we are doing now)

**Comment by loumalouomega** [comment]
This does not break current behavior, currently if not defined it just crashes, it adds a default value

**Comment by roigcarlo** [comment]
It does not crash if it can find a non_prefix library in the trilinos_libs folder. For instance:

```
**** configuring KratosTrilinosApplication ****
EPETRA_INCLUDE_PATH: /home/roigcarlos/libraries/build/trilinos/include
EPETRA_LIBRARY: /home/roigcarlos/libraries/build/trilinos/lib/libepetra.so
-- Found EPETRA: /home/roigcarlos/libraries/build/trilinos/lib/libepetra.so  
TEUCHOS_INCLUDE_PATH: /home/roigcarlos/libraries/build/trilinos/include
TEUCHOS_LIBRARIES: /home/roigcarlos/libraries/build/trilinos/lib/libteuchoscomm.so/home/roigcarlos/libraries/build/trilinos/lib/libteuchoscore.so/home/roigcarlos/libraries/build/trilinos/lib/libteuchosnumerics.so/home/roigcarlos/libraries/build/trilinos/lib/libteuchosparameterlist.so/home/roigcarlos/libraries/build/trilinos/lib/libteuchosremainder.so
-- Found TEUCHOS: /home/roigcarlos/libraries/build/trilinos/lib/libteuchoscomm.so  
-- Found TRIUTILS: /home/roigcarlos/libraries/build/trilinos/lib/libtriutils.so  
-- Found AMESOS: /home/roigcarlos/libraries/build/trilinos/lib/libamesos.so  
-- Found AZTECOO: /home/roigcarlos/libraries/build/trilinos/lib/libaztecoo.so  
-- Found IFPACK: /home/roigcarlos/libraries/build/trilinos/lib/libifpack.so  
-- Found ML: /home/roigcarlos/libraries/build/trilinos/lib/libml.so  
-- Found EPETRAEXT: /home/roigcarlos/libraries/build/trilinos/lib/libepetraext.so  
-- Found ZOLTAN: /home/roigcarlos/libraries/build/trilinos/lib/libzoltan.so  
-- Trilinos packages found.
Trilinos libs to be installed/home/roigcarlos/libraries/build/trilinos/lib/libepetra.so/home/roigcarlos/libraries/build/trilinos/lib/libteuchoscomm.so/home/roigcarlos/libraries/build/trilinos/lib/libteuchoscore.so/home/roigcarlos/libraries/build/trilinos/lib/libteuchosnumerics.so/home/roigcarlos/libraries/build/trilinos/lib/libteuchosparameterlist.so/home/roigcarlos/libraries/build/trilinos/lib/libteuchosremainder.so/home/roigcarlos/libraries/build/trilinos/lib/libtriutils.so/home/roigcarlos/libraries/build/trilinos/lib/libamesos.so/home/roigcarlos/libraries/build/trilinos/lib/libaztecoo.so/home/roigcarlos/libraries/build/trilinos/lib/libifpack.so/home/roigcarlos/libraries/build/trilinos/lib/libml.so/home/roigcarlos/libraries/build/trilinos/lib/libepetraext.so/home/roigcarlos/libraries/build/trilinos/lib/libzoltan.so
EPETRA_INCLUDE_PATH: /home/roigcarlos/libraries/build/trilinos/include
EPETRA_LIBRARY: /home/roigcarlos/libraries/build/trilinos/lib/libepetra.so
TEUCHOS_INCLUDE_PATH: /home/roigcarlos/libraries/build/trilinos/include
TEUCHOS_LIBRARIES: /home/roigcarlos/libraries/build/trilinos/lib/libteuchoscomm.so/home/roigcarlos/libraries/build/trilinos/lib/libteuchoscore.so/home/roigcarlos/libraries/build/trilinos/lib/libteuchosnumerics.so/home/roigcarlos/libraries/build/trilinos/lib/libteuchosparameterlist.so/home/roigcarlos/libraries/build/trilinos/lib/libteuchosremainder.so
-- Trilinos packages found.
```

That's the log I get with the current master. With the changes in this PR I get he following result:

```
**** configuring KratosTrilinosApplication ****
-- The trilinos library prefix not defined, will be assumed as: trilinos_
EPETRA_INCLUDE_PATH: /home/roigcarlos/libraries/build/trilinos/include
EPETRA_LIBRARY: EPETRA_LIBRARY-NOTFOUND
-- Could NOT find EPETRA (missing: EPETRA_LIBRARY) 
TEUCHOS_INCLUDE_PATH: /home/roigcarlos/libraries/build/trilinos/include
TEUCHOS_LIBRARIES: 
-- Could NOT find TRIUTILS (missing: TRIUTILS_LIBRARY) 
CMake Error at cmake_modules/FindTRILINOS.cmake:217 (MESSAGE):
  Could not find Trilinos or one of its packages.  Please set the cmake var
  TRILINOS_ROOT or the environment vars TRILINOS_INCLUDE_DIR and
  TRILINOS_LIBRARY_DIR, note also that if in your system the library have a
  prefix, like "libtrilinos_epetra.so" instead of "libepetra.so" you can
  specify the prefix by the variable -DTRILINOS_LIBRARY_PREFIX="trilinos_"
Call Stack (most recent call first):
  applications/TrilinosApplication/CMakeLists.txt:27 (find_package)
```

Also, `-DTRILINOS_LIBRARY_PREFIX=""` does not solve the problem in case non prefix is used because you are checking if the content of the variable is not-empty, but the check should test if the variable is defined, even with empty content. In any case I would avoid that solution as in many situations use of trilinos is clusters or at the very best medium-advanced users. Ubuntu in this case would be the exception.

**Comment by loumalouomega** [comment]
> It does not crash if it can find a non_prefix library in the trilinos_libs folder. For instance:
> 
> ```
> **** configuring KratosTrilinosApplication ****
> EPETRA_INCLUDE_PATH: /home/roigcarlos/libraries/build/trilinos/include
> EPETRA_LIBRARY: /home/roigcarlos/libraries/build/trilinos/lib/libepetra.so
> -- Found EPETRA: /home/roigcarlos/libraries/build/trilinos/lib/libepetra.so  
> TEUCHOS_INCLUDE_PATH: /home/roigcarlos/libraries/build/trilinos/include
> TEUCHOS_LIBRARIES: /home/roigcarlos/libraries/build/trilinos/lib/libteuchoscomm.so/home/roigcarlos/libraries/build/trilinos/lib/libteuchoscore.so/home/roigcarlos/libraries/build/trilinos/lib/libteuchosnumerics.so/home/roigcarlos/libraries/build/trilinos/lib/libteuchosparameterlist.so/home/roigcarlos/libraries/build/trilinos/lib/libteuchosremainder.so
> -- Found TEUCHOS: /home/roigcarlos/libraries/build/trilinos/lib/libteuchoscomm.so  
> -- Found TRIUTILS: /home/roigcarlos/libraries/build/trilinos/lib/libtriutils.so  
> -- Found AMESOS: /home/roigcarlos/libraries/build/trilinos/lib/libamesos.so  
> -- Found AZTECOO: /home/roigcarlos/libraries/build/trilinos/lib/libaztecoo.so  
> -- Found IFPACK: /home/roigcarlos/libraries/build/trilinos/lib/libifpack.so  
> -- Found ML: /home/roigcarlos/libraries/build/trilinos/lib/libml.so  
> -- Found EPETRAEXT: /home/roigcarlos/libraries/build/trilinos/lib/libepetraext.so  
> -- Found ZOLTAN: /home/roigcarlos/libraries/build/trilinos/lib/libzoltan.so  
> -- Trilinos packages found.
> Trilinos libs to be installed/home/roigcarlos/libraries/build/trilinos/lib/libepetra.so/home/roigcarlos/libraries/build/trilinos/lib/libteuchoscomm.so/home/roigcarlos/libraries/build/trilinos/lib/libteuchoscore.so/home/roigcarlos/libraries/build/trilinos/lib/libteuchosnumerics.so/home/roigcarlos/libraries/build/trilinos/lib/libteuchosparameterlist.so/home/roigcarlos/libraries/build/trilinos/lib/libteuchosremainder.so/home/roigcarlos/libraries/build/trilinos/lib/libtriutils.so/home/roigcarlos/libraries/build/trilinos/lib/libamesos.so/home/roigcarlos/libraries/build/trilinos/lib/libaztecoo.so/home/roigcarlos/libraries/build/trilinos/lib/libifpack.so/home/roigcarlos/libraries/build/trilinos/lib/libml.so/home/roigcarlos/libraries/build/trilinos/lib/libepetraext.so/home/roigcarlos/libraries/build/trilinos/lib/libzoltan.so
> EPETRA_INCLUDE_PATH: /home/roigcarlos/libraries/build/trilinos/include
> EPETRA_LIBRARY: /home/roigcarlos/libraries/build/trilinos/lib/libepetra.so
> TEUCHOS_INCLUDE_PATH: /home/roigcarlos/libraries/build/trilinos/include
> TEUCHOS_LIBRARIES: /home/roigcarlos/libraries/build/trilinos/lib/libteuchoscomm.so/home/roigcarlos/libraries/build/trilinos/lib/libteuchoscore.so/home/roigcarlos/libraries/build/trilinos/lib/libteuchosnumerics.so/home/roigcarlos/libraries/build/trilinos/lib/libteuchosparameterlist.so/home/roigcarlos/libraries/build/trilinos/lib/libteuchosremainder.so
> -- Trilinos packages found.
> ```
> 
> That's the log I get with the current master. With the changes in this PR I get he following result:
> 
> ```
> **** configuring KratosTrilinosApplication ****
> -- The trilinos library prefix not defined, will be assumed as: trilinos_
> EPETRA_INCLUDE_PATH: /home/roigcarlos/libraries/build/trilinos/include
> EPETRA_LIBRARY: EPETRA_LIBRARY-NOTFOUND
> -- Could NOT find EPETRA (missing: EPETRA_LIBRARY) 
> TEUCHOS_INCLUDE_PATH: /home/roigcarlos/libraries/build/trilinos/include
> TEUCHOS_LIBRARIES: 
> -- Could NOT find TRIUTILS (missing: TRIUTILS_LIBRARY) 
> CMake Error at cmake_modules/FindTRILINOS.cmake:217 (MESSAGE):
>   Could not find Trilinos or one of its packages.  Please set the cmake var
>   TRILINOS_ROOT or the environment vars TRILINOS_INCLUDE_DIR and
>   TRILINOS_LIBRARY_DIR, note also that if in your system the library have a
>   prefix, like "libtrilinos_epetra.so" instead of "libepetra.so" you can
>   specify the prefix by the variable -DTRILINOS_LIBRARY_PREFIX="trilinos_"
> Call Stack (most recent call first):
>   applications/TrilinosApplication/CMakeLists.txt:27 (find_package)
> ```
> 
> Also, `-DTRILINOS_LIBRARY_PREFIX=""` does not solve the problem in case non prefix is used because you are checking if the content of the variable is not-empty, but the check should test if the variable is defined, even with empty content. In any case I would avoid that solution as in many situations use of trilinos is clusters or at the very best medium-advanced users. Ubuntu in this case would be the exception.

Therefore, what do you suggest?

**Comment by roigcarlo** [comment]
As @philbucher suggested first you should test if trilinos can be found with the options the user provides (as odd as they can be), and only if that does not work try to find it with a custom prefix or have a fallback mechanism.

**Comment by roigcarlo** [comment]
For the record, I do not see a problem with the current behavior.

**Comment by philbucher** [comment]
> For the record, I do not see a problem with the current behavior.

same

Compiling on the cluster is nasty enough, I don't think we should overcomplicate things.

Plus it is even documented how to compile with trilinos: https://github.com/KratosMultiphysics/Kratos/blob/master/INSTALL.md#trilinos

**Comment by loumalouomega** [comment]
> > For the record, I do not see a problem with the current behavior.
> 
> same
> 
> Compiling on the cluster is nasty enough, I don't think we should overcomplicate things.
> 
> Plus it is even documented how to compile with trilinos: [`master`/INSTALL.md#trilinos](https://github.com/KratosMultiphysics/Kratos/blob/master/INSTALL.md?rgh-link-date=2020-08-03T15%3A27%3A15Z#trilinos)

I didn't want to define by had, I will close this

**Pull request closed without merging**
