### PR TITLE
[Structural] Post-processing energy for truss and membrane

### PR DESCRIPTION
**Pull request by KlausBSautter**
**Description**
With this PR the truss and the membrane element can post-process strain, kinetic, external, and damping dissipation energy.

**Changelog**
- Added post-processing of strain, kinetic, external, and damping dissipation energy for truss
-  Added post-processing of strain, kinetic, external, and damping dissipation energy for membrane
 - TrussClaw calculates strain energy now
 - ElasticIsotropic3D claw differentiates between element provided strain and self calculated strain for strain energy now
 - Added `ENERGY_DAMPING_DISSIPATION` to StructMech variables (could not find an appropriate variable)
 - Wrote tests

### CODE REVIEW

**Comment by KlausBSautter** [comment]
@loumalouomega this fails in the 
`test_spr_error_process`
with `SmallDisplacementElement`.

I would guess the results are currently wrong because `SmallDisplacementElement` sets 
`UseElementProvidedStrain = True` but in the claw this was not considered yet and the claw calculated the strain itself for `STRAIN_ENERGY`, so this is inconsistent. Should we change the results to which this test compares the simulation result?

Currently it is 0.257196, the new one (which I think is correct because it uses the element provided strain as written by the code) is 0.244949

respectively 0.148492 vs. 0.141421

**Comment by loumalouomega** [comment]
Probably I take the values from the results, so I am OK to change them.

**Comment by KlausBSautter** [comment]
can someone approve? or check this pr :)

**Comment by KlausBSautter** [comment]
@philbucher

**Review by philbucher — APPROVED** [review]
wouldn't it make sense to also check a few Elements explicitly for the computed energy and not only the sum?

**Comment by KlausBSautter** [comment]
> wouldn't it make sense to also check a few Elements explicitly for the computed energy and not only the sum?

maybe, in the end we are interested in the sum which should stay constant

**Pull request merged**
