### PR TITLE
[CI] bringing back CompressiblePotentialFlowApp

### PR DESCRIPTION
**Pull request by philbucher**
Quite a number of errors were fixed in the meantime, hopefully now it works stable

### CODE REVIEW

**Comment by philbucher** [comment]
seems to work again
should we go ahead and see how it works out?

**Review by inigolcanalejo — APPROVED** [review]
It seems to work now. Thanks @philbucher!

**Review by marcnunezc — APPROVED** [review]
Nice! The changes from #6430 made the CI work again with the potential flow right? Are there any other meaningful changes that could have solved the issue?

**Comment by philbucher** [comment]
well #6430 seems more like a bugfix, the order should not matter
However now we are at (hopefully) able to reproduce the CI-errors

there are also some other things that might play a role, such as #6431 or #6460 but those have (I think) nothing to do with PotentialFlow, hence I think if it works we can reenable it (hopefully for good this time :D)

**Pull request merged**
