### PR TITLE
write conditions on elements of boundary surfaces

### PR DESCRIPTION
**Pull request by merceln**
Added a procedure that searches all the surfaces in the model (belonging to a volume or not). These surfaces are necessary for the ExcludeBoundary option for inlets in GUI. This proc is also compatible with non-nurb surfaces.
This fixes the incompatibility with swimming application when applying conditions.

### CODE REVIEW

**Comment by farrufat-cimne** [comment]
ok

**Review by farrufat-cimne — APPROVED** [review]
ok

**Comment by philbucher** [comment]
is this branch still needed?

**Comment by loumalouomega** [comment]
Can we delete this branch? @farrufat-cimne

**Pull request merged**
