### PR TITLE
[Structuralmechanics][ResidulCrit] fixing criteria when MPCs are present

### PR DESCRIPTION
**Pull request by KlausBSautter**
This fixes problems and inconsistencies with the residual-criterion in StructuralMechanics when MPCs are present => ports the changes from the residual-criterion in the core
When MPCs are present the problems were not converging!

### CODE REVIEW

**Review by philbucher — DISMISSED** [review]

**Review by loumalouomega — DISMISSED** [review]
OK

**Comment by KlausBSautter** [comment]
there was a wrong line, fixed now

**Review by philbucher — DISMISSED** [review]

**Comment by philbucher** [comment]
@roigcarlo this also needs to go to the release-branch

sorry for the mess

**Review by loumalouomega — APPROVED** [review]

**Comment by philbucher** [comment]
@roigcarlo can you please port this to the release?

**Pull request merged**
