### PR TITLE
[Meshing] Reducing verbosity in mmg when null reference is obtained

### PR DESCRIPTION
**Pull request by loumalouomega**
Just that @RiccardoRossi

### CODE REVIEW

**Comment by loumalouomega** [comment]
Ping @RiccardoRossi

**Comment by loumalouomega** [comment]
Fixes #6880

**Comment by loumalouomega** [comment]
@RiccardoRossi ping

**Comment by loumalouomega** [comment]
Ping @RiccardoRossi

**Comment by loumalouomega** [comment]
Ping @RiccardoRossi this is super short, and you asked for this!!

**Review by RiccardoRossi — APPROVED** [review]

**Pull request merged**
