### PR TITLE
[PfemFluid] Add thermal coupling files

### PR DESCRIPTION
**Pull request by MZecchetto**
Just that. Few notes:
- requires https://github.com/KratosMultiphysics/Kratos/pull/6504;
- implements the last part of https://github.com/KratosMultiphysics/GiDInterface/issues/713;
- maybe small changes will be required to suit the GiD interface;
- preliminary test is enabled by default;

Massimiliano

### CODE REVIEW

**Review by ipouplana — COMMENTED** [review]
Hi @MZecchetto , why have you modified DamApplication files here ?

**Comment by MZecchetto** [comment]
I never modified Dam files. now it should be ok

**Comment by ipouplana** [comment]
I see that you are adding CLs here... I guess that you have the same changes as in PR #6504, right?
If so, I would first merge that PR and then, once you merge the updated master branch over this one, you can merge this PR too. Was that your idea ?

**Comment by MZecchetto** [comment]
Yes, this is also my idea. I rebased this branch onto https://github.com/KratosMultiphysics/Kratos/pull/6504 because I needed it. It was not 100% clear to me how the rebase is managed in a PR.

**Review by AFranci — APPROVED** [review]

**Pull request merged**
