### PR TITLE
Disabled TotalLagrangian2D3_TransientSensitivity and slow tests

### PR DESCRIPTION
**Pull request by roigcarlo**
Twin PR for #4450

### CODE REVIEW

**Review by philbucher — DISMISSED** [review]

**Review by philbucher — DISMISSED** [review]

**Comment by philbucher** [comment]
how is this still failing -,-

**Comment by roigcarlo** [comment]
I am starting to run out of ideas :S

**Comment by philbucher** [comment]
Now it should output which test is failing, then we will know more ...

**Comment by roigcarlo** [comment]
Pretty sure is this one: test_truss3D2N_linear_plasticity

As for the time, maybe there is something wrong in the cache... Or not because the master one is failing too...

**Comment by philbucher** [comment]
but it works on master, thats what I don't get
Also not too long ago I cleaned the tests, then it was fine

**Comment by philbucher** [comment]
it is this one indeed
what should I do? Move it?

**Comment by roigcarlo** [comment]
Yep `test_truss3D2N_linear_plasticity` fails, and the executions halts with `test_cr_beam_dynamic_consistent_mass_matrix` halts the execution.

To be honest can't tell you what to do. It should work if it does in master.

i've taken a diff from the master to here but its to big. I can send it to you by mail.

**Comment by roigcarlo** [comment]
```diff
--- a/applications/StructuralMechanicsApplication/tests/truss_test/nonlinear_3D2NTruss_plastic_snapthrough_test_parameters.json
+++ b/applications/StructuralMechanicsApplication/tests/truss_test/nonlinear_3D2NTruss_plastic_snapthrough_test_parameters.json
@@ -3,7 +3,7 @@
         "problem_name"    : "nonlinear_3D2NTruss_snapthrough_plasticity_test",
         "parallel_type"   : "OpenMP",
         "start_time"      : 0.0,
-        "end_time"        : 44,
+        "end_time"        : 46,
         "echo_level"      : 0
     },
     "solver_settings"          : {
```

May this be related with the `test_truss3D2N_linear_plasticity` ?

**Comment by roigcarlo** [comment]
Nope...

**Comment by philbucher** [comment]
> ```diff
> --- a/applications/StructuralMechanicsApplication/tests/truss_test/nonlinear_3D2NTruss_plastic_snapthrough_test_parameters.json
> +++ b/applications/StructuralMechanicsApplication/tests/truss_test/nonlinear_3D2NTruss_plastic_snapthrough_test_parameters.json
> @@ -3,7 +3,7 @@
>          "problem_name"    : "nonlinear_3D2NTruss_snapthrough_plasticity_test",
>          "parallel_type"   : "OpenMP",
>          "start_time"      : 0.0,
> -        "end_time"        : 44,
> +        "end_time"        : 46,
>          "echo_level"      : 0
>      },
>      "solver_settings"          : {
> ```
> 
> May this be related with the `test_truss3D2N_linear_plasticity` ?

this is a different test


I moved the failing test to the nightsuite now, lets see what happens ...

**Comment by roigcarlo** [comment]
the `test_disp_temp` from https://github.com/KratosMultiphysics/Kratos/blob/master/applications/StructuralMechanicsApplication/tests/test_patch_test_truss.py#L265

This is also different from the master, rings any bell?
I've tested the branch with the values of the master and causes more tests to fail :S

**Comment by roigcarlo** [comment]
@philbucher 
Divergence comes from: #4286 and #4350
Seems that github let me merge the change with a failure and its being propagated everywhere.
Still, somethings seems to be off between the PR. I am seeing different commit numbers and that should not happend. 

When I get something I will post it here

**Comment by philbucher** [comment]
> @philbucher
> Divergence comes from: #4286 and #4350
> Seems that github let me merge the change with a failure and its being propagated everywhere.
> Still, somethings seems to be off between the PR. I am seeing different commit numbers and that should not happend.
> 
> When I get something I will post it here

I know, thats what I keep telling all along :D
Those changes can slightly change the results, which is why some of the values in the tests were adapted

Those two PRs were not ported to the release?

I have to leave now, but in case sth urgent comes up I think I will still be available

Sorry for the mess, but it is not really my fault I think

**Comment by roigcarlo** [comment]
Nono, but you are the only one that's been answering :+1:

**Pull request closed without merging**
