### PR TITLE
Ci Enable windows tests

### PR DESCRIPTION
**Pull request by roigcarlo**
Testing if we can enable CI in appveyor while maintaining cotire.

- [x] Compatilation
- [x] Installation
- [ ] Testing

### CODE REVIEW

**Comment by philbucher** [comment]
some CLaw tests are failiing, can you please have a look @AlejandroCornejo @loumalouomega ?

**Comment by loumalouomega** [comment]
> 
> 
> some CLaw tests are failiing, can you please have a look @AlejandroCornejo @loumalouomega ?

Those are mine, but in my Windows machine work :P, can anyone else try?

**Comment by roigcarlo** [comment]
Yep that needs to be fixed, but let me just run the small tests. I didn't tell the machine to skip the nightly ones and maybe that's one of them

**Comment by philbucher** [comment]
its one of the cpp ones, so this wont solve it ...

We could disable it for the moment to not block this PR

**Comment by loumalouomega** [comment]
> 
> 
> its one of the cpp ones, so this wont solve it ...
> 
> We could disable it for the moment to not block this PR

Maybe we should add something to remeber that it is needed to be fixed, like the deprecated warnings of the compilers

**Comment by philbucher** [comment]
or just am issue?

**Comment by philbucher** [comment]
or maybe a print in the test itself?
Issue a warning before the failing checks (that are commented?)

This way whenever the tests are run, the warning will be issued as a reminder?

**Comment by loumalouomega** [comment]
Ok

**Comment by philbucher** [comment]
hm looking at your latest commits I realize again that the Strctural Tests always use the ExternalSolversApp, we should refactor that but haven't yet

Will this be a problem?

**Comment by roigcarlo** [comment]
Yes, right now there is no blas in appveyor so we cannot run the external solvers app ( that is why we are not compiling it ).
If it does not run I need o be aware of that it cannot. Otherwise it will try to run everything. :S

**Comment by philbucher** [comment]
ok 
So I just checked, probably it already works, but I am not sure. Just try, then we can see :)

**Comment by philbucher** [comment]
ok thats what I thought would happen:
~~~
ERROR: test_execution (structural_mechanics_test_factory.SimpleMeshMovingTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\kratos\applications\StructuralMechanicsApplication\tests\structural_mechanics_test_factory.py", line 44, in setUp
    self.test.Initialize()
  File "C:\projects\kratos\applications\StructuralMechanicsApplication\python_scripts\structural_mechanics_analysis.py", line 56, in Initialize
    super(StructuralMechanicsAnalysis, self).Initialize()
  File "C:\projects\kratos\kratos\python_scripts\analysis_stage.py", line 89, in Initialize
    self._GetSolver().Initialize()
  File "C:\projects\kratos\applications\StructuralMechanicsApplication\python_scripts\structural_mechanics_solver.py", line 191, in Initialize
    mechanical_solution_strategy = self.get_mechanical_solution_strategy()
  File "C:\projects\kratos\applications\StructuralMechanicsApplication\python_scripts\structural_mechanics_solver.py", line 289, in get_mechanical_solution_strategy
    self._mechanical_solution_strategy = self._create_mechanical_solution_strategy()
  File "C:\projects\kratos\applications\StructuralMechanicsApplication\python_scripts\structural_mechanics_solver.py", line 422, in _create_mechanical_solution_strategy
    mechanical_solution_strategy = self._create_linear_strategy()
  File "C:\projects\kratos\applications\StructuralMechanicsApplication\python_scripts\structural_mechanics_solver.py", line 437, in _create_linear_strategy
    linear_solver = self.get_linear_solver()
  File "C:\projects\kratos\applications\StructuralMechanicsApplication\python_scripts\structural_mechanics_solver.py", line 272, in get_linear_solver
    self._linear_solver = self._create_linear_solver()
  File "C:\projects\kratos\applications\StructuralMechanicsApplication\python_scripts\structural_mechanics_solver.py", line 398, in _create_linear_solver
    return linear_solver_factory.ConstructSolver(linear_solver_configuration)
  File "C:\projects\kratos\kratos\python_scripts\python_linear_solver_factory.py", line 159, in ConstructSolver
    import_module("KratosMultiphysics." + app_name)
  File "C:\Python36-x64\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'KratosMultiphysics.ExternalSolversApplication'
----------------------------------------------------------------------
~~~

I will think of sth

~~~
======================================================================
ERROR: test_PostprocessEigenvaluesProcess_GiD (test_postprocess_eigenvalues_process.TestPostprocessEigenvaluesProcess)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\kratos\applications\StructuralMechanicsApplication\tests\test_postprocess_eigenvalues_process.py", line 108, in test_PostprocessEigenvaluesProcess_GiD
    """ % (GetFilePath("eigen_postprocess_ref_files/test_postprocess_eigenvalues_process.post.res.ref"), "EigenResults/Structure_EigenResults_15_0.post.res"))
RuntimeError: [json.exception.parse_error.101] parse error at line 3, column 43: syntax error while parsing value - invalid string: forbidden character after backslash; last read: '"C:\p'
======================================================================
ERROR: test_PostprocessEigenvaluesProcess_Vtk (test_postprocess_eigenvalues_process.TestPostprocessEigenvaluesProcess)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\kratos\applications\StructuralMechanicsApplication\tests\test_postprocess_eigenvalues_process.py", line 138, in test_PostprocessEigenvaluesProcess_Vtk
    """ % (GetFilePath("eigen_postprocess_ref_files/Structure_EigenResults_15_{}.vtk.ref".format(i)), "EigenResults/Structure_EigenResults_15_{}.vtk".format(i)))
RuntimeError: [json.exception.parse_error.101] parse error at line 3, column 47: syntax error while parsing value - invalid string: forbidden character after backslash; last read: '"C:\p'
======================================================================
~~~

Also this I should fix, sorry for the inconvenience

It seems like SDEM uses numpy, would it be possible to use it here too?

**Comment by philbucher** [comment]
also it seems like it was hanging when trying to import the SDEM-App

**Comment by roigcarlo** [comment]
mmm numpy should be possible to use but we have to install it. I can try

**Comment by roigcarlo** [comment]
@philbucher Aside from the tests in the structural, looks like we also have problems in the core, so probably we will need to iterate over this.

What really bother me is that same tests are running fine in the machine you have on TUM: https://gitlab.com/KratosMultiphysics/Kratos/-/jobs/332841626 for example.

So I am investigating this.

**Comment by philbucher** [comment]
hm ok ...

So in the other machine you have compiled the ExternalSolversApp?

**Comment by roigcarlo** [comment]
Yep, because we installed the blas libraries manually

**Comment by roigcarlo** [comment]
Dem tests seems to take a lot of time :S. 

I was thinking on change the 60 second rule to 10 seconds per tests instead of 60 for all. Maybe that is more realistic.

Still I don't know why some core tests are failing. Anyone using win has a clue?

**Comment by philbucher** [comment]
I think the filecmp also fails in linux when there are whitespaces / newlines

**Comment by roigcarlo** [comment]
I wil lclose this one since the Github one is working

**Comment by philbucher** [comment]
well tests are not enabled there yet but probably makes more sense to put the effort into the github one

**Comment by roigcarlo** [comment]
Yup. the problem with tests here is that with the time restrictions of win we have to decrease the applications compiled or change how cmake generate projects. Otherwise it won't work. Having github actions with plenty of time this is just pointless and not worth the effor.

**Pull request closed without merging**
