### PR TITLE
[TEST] add CableNetApplication to workflow windows

### PR DESCRIPTION
**Pull request by VeronikaSinger**
The CableNetApplication does not compile in windows 
This is a test if the compilation fails in Github as well.

### CODE REVIEW

**Comment by KlausBSautter** [comment]
it's failing. I'll check this out later

**Comment by KlausBSautter** [comment]
Is there anyone using windows? This seems to be the problem `COMPILER_HAS_DEPRECATED_ATTR`

**Comment by matekelemen** [comment]
Looks like the python bindings aren't linked correctly to core.

`KratosCableNetCore` links privately.
https://github.com/KratosMultiphysics/Kratos/blob/41b18282425f5a4a81c6ac6b3bf8870f1da00e7d/applications/CableNetApplication/CMakeLists.txt#L32

And so does `KratosCableNetApplication`, but only against `KratosCableNetCore` and not `KratosCore`.
https://github.com/KratosMultiphysics/Kratos/blob/41b18282425f5a4a81c6ac6b3bf8870f1da00e7d/applications/CableNetApplication/CMakeLists.txt#L38

I'm guessing MSVC can't find the symbols matching the core declarations you're using in the python bindings, which is understandable because `KratosCore` is completely invisible to `KratosCableNetApplication`. What I don't understand is why this links successfully on Linux.

Anyway, try linking `KratosCableNetApplication` with `KratosCore` explicitly:
```
target_link_libraries(KratosCableNetApplication PRIVATE KratosCableNetCore KratosCore)
```

**Review by sunethwarna — DISMISSED** [review]
Nice.... Now this is nicely working in all systems, may be we can add it to wheels as well?
https://github.com/KratosMultiphysics/Kratos/tree/master/scripts/wheels

@roigcarlo ?

**Comment by roigcarlo** [comment]
Np from my side, just add it in:

https://github.com/KratosMultiphysics/Kratos/blob/master/scripts/wheels/windows/configure.bat
https://github.com/KratosMultiphysics/Kratos/blob/master/scripts/wheels/linux/build_mpi.sh
https://github.com/KratosMultiphysics/Kratos/blob/master/scripts/wheels/linux/build.sh

**Comment by VeronikaSinger** [comment]
The CableNetApplication is added to wheels, too.
@sunethwarna could you please reapprove? Thanks

**Review by roigcarlo — APPROVED** [review]

**Pull request merged**
