### PR TITLE
[Cleaning] Remove duplicated (and old) README.md

### PR DESCRIPTION
**Pull request by loumalouomega**
**📝 Description**

This is inside the wheels folders, and it is duplicated and old. Automatically copying the current one in the corresponding folder. Ignored by git.

**🆕 Changelog**

- [Remove duplicated (and old) README.md](https://github.com/KratosMultiphysics/Kratos/commit/b1e2af7432ef5b39d78d867201a15205182b9ac5)
- [Automatically copy](https://github.com/KratosMultiphysics/Kratos/pull/10330/commits/bef20fc93e0bf4e6346617997d66ca3342d1be41)

### CODE REVIEW

**Comment by loumalouomega** [comment]
Why do we have CI if I removed a markdown file?

**Review by roigcarlo — COMMENTED** [review]
If you delete this, we have to change the:
* kratos/KratosMultiphysics.json
* kratos/KratosMultiphysics-all.json

Because are fetching the readme from there.

**Comment by loumalouomega** [comment]
> If you delete this, we have to change the:
> 
>     * kratos/KratosMultiphysics.json
> 
>     * kratos/KratosMultiphysics-all.json
> 
> 
> Because are fetching the readme from there.

In that case we can update it...

**Comment by loumalouomega** [comment]
> If you delete this, we have to change the:
> 
>     * kratos/KratosMultiphysics.json
> 
>     * kratos/KratosMultiphysics-all.json
> 
> 
> Because are fetching the readme from there.

Maybe we can add it to the gitignore and install the one in the root directory everytime is compiled

**Comment by loumalouomega** [comment]
> > If you delete this, we have to change the:
> > ```
> > * kratos/KratosMultiphysics.json
> > 
> > * kratos/KratosMultiphysics-all.json
> > ```
> >   
> > Because are fetching the readme from there.
> 
> Maybe we can add it to the gitignore and install the one in the root directory everytime is compiled

Agree?

**Comment by loumalouomega** [comment]
> > > If you delete this, we have to change the:
> > > ```
> > > * kratos/KratosMultiphysics.json
> > > 
> > > * kratos/KratosMultiphysics-all.json
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Because are fetching the readme from there.
> > 
> > 
> > Maybe we can add it to the gitignore and install the one in the root directory everytime is compiled
> 
> Agree?

I adapted the CMake so the main README.md is copied every time Kratos is compiled, but will be ignored by git

**Review by roigcarlo — APPROVED** [review]

**Pull request merged**
