### PR TITLE
Added one method that can create a single particle.

### PR DESCRIPTION
**Pull request by maceligueta**
It's exported to Python, too.
Unit tests have been created for the first time in the DEM application.
This required adapting part of the structure of the DEM application related to the Properties Proxies. Now they are stored in the model part (so they are accessible from everywhere the ModelPart is sent and arguments can be removed from some methods).

### CODE REVIEW

**Review by GuillermoCasas — APPROVED** [review]
Very nice. A long needed utility. Just one question: could the python implementation not return an element pointer as well, so that it is possible to do do:
elem = CreateSphericalParticle(...)
for node in elem.Nodes:
    etc...

**Comment by maceligueta** [comment]
It's a good point. I will add this feature before merging.
Still, I don't want to lose the return as a raw pointer because it can be a lot faster in some situations (I am thinking about massive injections of particles, like a big inlet, where we want to avoid the copy of shared pointers with the subsequent atomic and loss of parallelism).

**Comment by maceligueta** [comment]
@GuillermoCasas : It's working as you proposed now (though I kept the raw pointers return in other versions of those methods, with the suffix 'Raw'.

**Comment by GuillermoCasas** [comment]
Great job. I think the raw pointer option, being more advanced, is well distinguished by adding the word 'Raw'.

**Pull request merged**
