### PR TITLE
Adding missing overrides to the StructuralMechanicsApplication

### PR DESCRIPTION
**Pull request by loumalouomega**
Many warnings due to missing overrides after last updates

### CODE REVIEW

**Comment by loumalouomega** [comment]
Additionally some other warning ins in the MPC:

~~~c
In file included from /home/vicente/bin/Kratos/applications/StructuralMechanicsApplication/custom_python/add_custom_utilities_to_python.cpp:31:                                                                                           
/home/vicente/bin/Kratos/applications/StructuralMechanicsApplication/custom_processes/apply_multi_point_constraints_process.h:288:10: warning:                                                                                            
      'Kratos::ApplyMultipointConstraintsProcess::PrintData' hides overloaded virtual function [-Woverloaded-virtual]
    void PrintData()                                                                                                 
         ^                                                                                                           
/home/vicente/bin/Kratos/kratos/processes/process.h:155:10: note: hidden overloaded virtual function                 
      'Kratos::Process::PrintData' declared here: different number of parameters (1 vs 0)                            
    void PrintData(std::ostream& rOStream) const override  
~~~

**Comment by philbucher** [comment]
why do you delete the `virtual` keywords? In case someone wants to derive from those classes...?

mpc is @adityaghantasala

**Comment by loumalouomega** [comment]
OK, I just had many warnings due to missing override. This PR compensates
that.

El 15 oct. 2017 1:25 p. m., "Philipp Bucher" <notifications@github.com>
escribió:

why do you delete the virtual keywords? In case someone wants to derive
from those classes...?

mpc is @adityaghantasala <https://github.com/adityaghantasala>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/KratosMultiphysics/Kratos/pull/844#issuecomment-336705062>,
or mute the thread

**Comment by loumalouomega** [comment]
Besides, the virtual is only needed to be defined in the first class, the derived ones all will use the override https://stackoverflow.com/questions/28163187/why-override-is-at-the-end-in-c11

**Comment by adityaghantasala** [comment]
@loumalouomega 
I will make the correction for the warning in the mpc process.

**Comment by loumalouomega** [comment]
👍 @adityaghantasala

**Comment by loumalouomega** [comment]
@adityaghantasala More warnings:

~~~c
In file included from /home/vicente/bin/Kratos/applications/StructuralMechanicsApplication/custom_python/add_custom_strategies_to_python.cpp:42:0:
/home/vicente/bin/Kratos/applications/StructuralMechanicsApplication/custom_strategies/custom_builder_and_solver/residualbased_block_builder_and_solver_with_mpc.h: In instantiation of ‘void Kratos::ResidualBasedBlockBuilderAndSolverWithMpc<TSparseSpace, TDenseSpace, TLinearSolver>::Element_ApplyMultipointConstraints(Kratos::Element::Pointer, Kratos::ResidualBasedBlockBuilderAndSolverWithMpc<TSparseSpace, TDenseSpace, TLinearSolver>::LocalSystemMatrixType&, Kratos::ResidualBasedBlockBuilderAndSolverWithMpc<TSparseSpace, TDenseSpace, TLinearSolver>::LocalSystemVectorType&, Kratos::Element::EquationIdVectorType&, Kratos::ProcessInfo&) [with TSparseSpace = Kratos::UblasSpace<double, boost::numeric::ublas::compressed_matrix<double>, boost::numeric::ublas::vector<double> >; TDenseSpace = Kratos::UblasSpace<double, boost::numeric::ublas::matrix<double>, boost::numeric::ublas::vector<double> >; TLinearSolver = Kratos::LinearSolver<Kratos::UblasSpace<double, boost::numeric::ublas::compressed_matrix<double>, boost::numeric::ublas::vector<double> >, Kratos::UblasSpace<double, boost::numeric::ublas::matrix<double>, boost::numeric::ublas::vector<double> > >; Kratos::Element::Pointer = boost::shared_ptr<Kratos::Element>; Kratos::ResidualBasedBlockBuilderAndSolverWithMpc<TSparseSpace, TDenseSpace, TLinearSolver>::LocalSystemMatrixType = boost::numeric::ublas::matrix<double>; Kratos::ResidualBasedBlockBuilderAndSolverWithMpc<TSparseSpace, TDenseSpace, TLinearSolver>::LocalSystemVectorType = boost::numeric::ublas::vector<double>; Kratos::Element::EquationIdVectorType = std::vector<long unsigned int>]’:
/home/vicente/bin/Kratos/applications/StructuralMechanicsApplication/custom_strategies/custom_builder_and_solver/residualbased_block_builder_and_solver_with_mpc.h:279:21:   required from ‘void Kratos::ResidualBasedBlockBuilderAndSolverWithMpc<TSparseSpace, TDenseSpace, TLinearSolver>::Build(typename Kratos::ResidualBasedBlockBuilderAndSolverWithMpc<TSparseSpace, TDenseSpace, TLinearSolver>::BaseType::TSchemeType::Pointer, Kratos::ModelPart&, Kratos::ResidualBasedBlockBuilderAndSolverWithMpc<TSparseSpace, TDenseSpace, TLinearSolver>::TSystemMatrixType&, Kratos::ResidualBasedBlockBuilderAndSolverWithMpc<TSparseSpace, TDenseSpace, TLinearSolver>::TSystemVectorType&) [with TSparseSpace = Kratos::UblasSpace<double, boost::numeric::ublas::compressed_matrix<double>, boost::numeric::ublas::vector<double> >; TDenseSpace = Kratos::UblasSpace<double, boost::numeric::ublas::matrix<double>, boost::numeric::ublas::vector<double> >; TLinearSolver = Kratos::LinearSolver<Kratos::UblasSpace<double, boost::numeric::ublas::compressed_matrix<double>, boost::numeric::ublas::vector<double> >, Kratos::UblasSpace<double, boost::numeric::ublas::matrix<double>, boost::numeric::ublas::vector<double> > >; typename Kratos::ResidualBasedBlockBuilderAndSolverWithMpc<TSparseSpace, TDenseSpace, TLinearSolver>::BaseType::TSchemeType::Pointer = boost::shared_ptr<Kratos::Scheme<Kratos::UblasSpace<double, boost::numeric::ublas::compressed_matrix<double>, boost::numeric::ublas::vector<double> >, Kratos::UblasSpace<double, boost::numeric::ublas::matrix<double>, boost::numeric::ublas::vector<double> > > >; Kratos::ResidualBasedBlockBuilderAndSolverWithMpc<TSparseSpace, TDenseSpace, TLinearSolver>::TSystemMatrixType = boost::numeric::ublas::compressed_matrix<double>; Kratos::ResidualBasedBlockBuilderAndSolverWithMpc<TSparseSpace, TDenseSpace, TLinearSolver>::TSystemVectorType = boost::numeric::ublas::vector<double>]’
/home/vicente/bin/Kratos/applications/StructuralMechanicsApplication/custom_python/add_custom_strategies_to_python.cpp:174:1:   required from here
/home/vicente/bin/Kratos/applications/StructuralMechanicsApplication/custom_strategies/custom_builder_and_solver/residualbased_block_builder_and_solver_with_mpc.h:680:72: warning: variable ‘itOther’ set but not used [-Wunused-but-set-variable]
                                     std::vector<std::size_t>::iterator itOther = std::find(localNodalSlaveEquationIds.begin(), localNodalSlaveEquationIds.end(), localSlaveEqIdOther);
                                                                        ^~~~~~~
In file included from /home/vicente/bin/Kratos/applications/StructuralMechanicsApplication/custom_python/add_custom_strategies_to_python.cpp:42:0:
/home/vicente/bin/Kratos/applications/StructuralMechanicsApplication/custom_strategies/custom_builder_and_solver/residualbased_block_builder_and_solver_with_mpc.h: In instantiation of ‘void Kratos::ResidualBasedBlockBuilderAndSolverWithMpc<TSparseSpace, TDenseSpace, TLinearSolver>::Condition_ApplyMultipointConstraints(Kratos::Condition::Pointer, Kratos::ResidualBasedBlockBuilderAndSolverWithMpc<TSparseSpace, TDenseSpace, TLinearSolver>::LocalSystemMatrixType&, Kratos::ResidualBasedBlockBuilderAndSolverWithMpc<TSparseSpace, TDenseSpace, TLinearSolver>::LocalSystemVectorType&, Kratos::Element::EquationIdVectorType&, Kratos::ProcessInfo&) [with TSparseSpace = Kratos::UblasSpace<double, boost::numeric::ublas::compressed_matrix<double>, boost::numeric::ublas::vector<double> >; TDenseSpace = Kratos::UblasSpace<double, boost::numeric::ublas::matrix<double>, boost::numeric::ublas::vector<double> >; TLinearSolver = Kratos::LinearSolver<Kratos::UblasSpace<double, boost::numeric::ublas::compressed_matrix<double>, boost::numeric::ublas::vector<double> >, Kratos::UblasSpace<double, boost::numeric::ublas::matrix<double>, boost::numeric::ublas::vector<double> > >; Kratos::Condition::Pointer = boost::shared_ptr<Kratos::Condition>; Kratos::ResidualBasedBlockBuilderAndSolverWithMpc<TSparseSpace, TDenseSpace, TLinearSolver>::LocalSystemMatrixType = boost::numeric::ublas::matrix<double>; Kratos::ResidualBasedBlockBuilderAndSolverWithMpc<TSparseSpace, TDenseSpace, TLinearSolver>::LocalSystemVectorType = boost::numeric::ublas::vector<double>; Kratos::Element::EquationIdVectorType = std::vector<long unsigned int>]’:
/home/vicente/bin/Kratos/applications/StructuralMechanicsApplication/custom_strategies/custom_builder_and_solver/residualbased_block_builder_and_solver_with_mpc.h:309:21:   required from ‘void Kratos::ResidualBasedBlockBuilderAndSolverWithMpc<TSparseSpace, TDenseSpace, TLinearSolver>::Build(typename Kratos::ResidualBasedBlockBuilderAndSolverWithMpc<TSparseSpace, TDenseSpace, TLinearSolver>::BaseType::TSchemeType::Pointer, Kratos::ModelPart&, Kratos::ResidualBasedBlockBuilderAndSolverWithMpc<TSparseSpace, TDenseSpace, TLinearSolver>::TSystemMatrixType&, Kratos::ResidualBasedBlockBuilderAndSolverWithMpc<TSparseSpace, TDenseSpace, TLinearSolver>::TSystemVectorType&) [with TSparseSpace = Kratos::UblasSpace<double, boost::numeric::ublas::compressed_matrix<double>, boost::numeric::ublas::vector<double> >; TDenseSpace = Kratos::UblasSpace<double, boost::numeric::ublas::matrix<double>, boost::numeric::ublas::vector<double> >; TLinearSolver = Kratos::LinearSolver<Kratos::UblasSpace<double, boost::numeric::ublas::compressed_matrix<double>, boost::numeric::ublas::vector<double> >, Kratos::UblasSpace<double, boost::numeric::ublas::matrix<double>, boost::numeric::ublas::vector<double> > >; typename Kratos::ResidualBasedBlockBuilderAndSolverWithMpc<TSparseSpace, TDenseSpace, TLinearSolver>::BaseType::TSchemeType::Pointer = boost::shared_ptr<Kratos::Scheme<Kratos::UblasSpace<double, boost::numeric::ublas::compressed_matrix<double>, boost::numeric::ublas::vector<double> >, Kratos::UblasSpace<double, boost::numeric::ublas::matrix<double>, boost::numeric::ublas::vector<double> > > >; Kratos::ResidualBasedBlockBuilderAndSolverWithMpc<TSparseSpace, TDenseSpace, TLinearSolver>::TSystemMatrixType = boost::numeric::ublas::compressed_matrix<double>; Kratos::ResidualBasedBlockBuilderAndSolverWithMpc<TSparseSpace, TDenseSpace, TLinearSolver>::TSystemVectorType = boost::numeric::ublas::vector<double>]’
/home/vicente/bin/Kratos/applications/StructuralMechanicsApplication/custom_python/add_custom_strategies_to_python.cpp:174:1:   required from here
/home/vicente/bin/Kratos/applications/StructuralMechanicsApplication/custom_strategies/custom_builder_and_solver/residualbased_block_builder_and_solver_with_mpc.h:859:72: warning: variable ‘itOther’ set but not used [-Wunused-but-set-variable]
                                     std::vector<std::size_t>::iterator itOther = std::find(localNodalSlaveEquationIds.begin(), localNodalSlaveEquationIds.end(), localSlaveEqIdOther);
~~~

**Review by philbucher — APPROVED** [review]

**Pull request merged**
