### PR TITLE
[Fluid] Fixing CMakeLists.txt in Fluid

### PR DESCRIPTION
**Pull request by sunethwarna**
Hi, 
I couldn't find the cmake fix for trilinos extension in current master, nor in the pull requests. Is it done in a branch already?, Or can we go ahead with this? And Is this the correct way to do it?

Thanks :)

### CODE REVIEW

**Comment by AndreasWinterstein** [comment]
I do not know if this makes sense, but probably it makes sense to add a common flag like COMPILE_TRILINOS_EXTENSIONS=ON/OFF as a global flag in order to compile the trilinos extensions for the added applications.

**Comment by roigcarlo** [comment]
@AndreasWinterstein we were considering this yesterday but It would be better if we can keep MPI and Trilinos as a bundle. 

If you have a use case where it is mandatory to compile with MPI but exclude trilinos please tell us and we will add the flag. Ping @KratosMultiphysics/technical-committee to be aware.

@sunethwarna Isn't this PR changing the same as #6037 ?

**Comment by sunethwarna** [comment]
@roigcarlo yes it is changing the same in RANS application as well in #6037. I will merge #6037 after #6036. #6036 only changes the Fluid CMakelists file.

Regarding the USE_MPI=ON flag bundling with TrilinosApplication:
I was using USE_MPI flag to link Kratos with Parallel HDF5 libraries without compiling Trilinos application since I only had Parallel HDF5 libraries (in arch linux i had conflicts between serial and parallel libraries). Now I'm also compiling HDF5 Parallel with Trilinos always, so for me also bundle it with trilinos works. But, there might be some others have some different uses of the USE_MPI flag like what I did. So, if untill someone raises the noise, we can go ahead with bundling i guess?

**Comment by roigcarlo** [comment]
@sunethwarna Ok. Then let's keep it this way until someone complains about it. 

I have the same problems in arch btw, it is a known issue (https://github.com/h5py/h5py/issues/891) but looks like nobody has solved it.

**Comment by rubenzorrilla** [comment]
@sunethwarna can we delete the branch?

**Comment by sunethwarna** [comment]
@rubenzorrilla  sorry, forgot to delete :|
@roigcarlo I guess not :/

**Pull request merged**
