### PR TITLE
[Core] Fix computation of nodal distances to the skin in the model part allocating `DISTANCE`

### LINKED ISSUE #12265: [Core][CI] `TestCalculateNodalDistanceToSkinProcessCoarseSphere` Fails in FullDebug
Both the Clang and GCC CI fails in `FullDebug` while executing core python tests. @loumalouomega git says you've touched `CalculateNodalDistanceToSkinProcess` last.

The failure is consistent, which really makes me wonder how the offending change was introduced to master.

```
 Traceback (most recent call last):
  File "/__w/Kratos/Kratos/bin/FullDebug/kratos/tests/test_calculate_nodal_distance_to_skin_process.py", line 144, in test_ComputeDistanceToSkin
    KratosMultiphysics.CalculateNodalDistanceToSkinProcess(self.current_model, settings).Execute()
RuntimeError: Error: The following errors occured in a parallel region!
Thread #2 caught exception: Error: attempting to do a GetValue for: DISTANCE variable #594256384DISTANCE variable #594256384 #594256384 unfortunately the variable is not in the database and the operations is not threadsafe (this function is being called from within a parallel region)
```

### PR DESCRIPTION
**Pull request by loumalouomega**
**📝 Description**

Fix computation of nodal distances to the skin in the model part allocating `DISTANCE`

Fixes https://github.com/KratosMultiphysics/Kratos/issues/12265

**🆕 Changelog**

- [Fix computation of nodal distances to the skin in the model part allocating `DISTANCE`](https://github.com/KratosMultiphysics/Kratos/commit/bc75ba4cd8c6c6e09ffb07a4109b8f946e383353)

### CODE REVIEW

**Review by matekelemen — DISMISSED** [review]
:ok_hand: 

Can you please check how it managed to get past the CI? It'd be great if you could figure it out, so we could make the CI checks more rigorous.

Also, it's weird that that other setups compiled in `Custom` mode didn't run into segfaults or exceptions.

**Comment by loumalouomega** [comment]
Sorry, I wrote wrongly the variable @matekelemen

**Review by matekelemen — APPROVED** [review]
> Can you please check how it managed to get past the CI? It'd be great if you could figure it out, so we could make the CI checks more rigorous.

**Comment by loumalouomega** [comment]
It passed the CI because that ci is not mandatory anymore because is
failing anyway due to lack of resources

**Pull request merged**
