### PR TITLE
[Docs] Workshops

### PR DESCRIPTION
**Pull request by sunethwarna**
**📝 Description**
This PR creates a palce to store details of Kratos workshops in the documentation page of the Kratos. Please feel free to suggest any feedback on how this should be aranged.

The workshop name "2024 UNIPD" is a dummy one for illustration purposes. @antonialarese can change it to fit the workshop  in November.

Following is a screenshot of the current proposal
image

**🆕 Changelog**
- Adds documentation pages for workshops

### CODE REVIEW

**Comment by rubenzorrilla** [comment]
Makes perfect sense to me. My unique comment is that the materials section points to the already existent Tutorial pages so to avoid duplicated content. In this regard, I note that @roigcarlo is making an effort to clean it up.

**Comment by antonialarese** [comment]
Hi! 

Thanks @sunethwarna and @rubenzorrilla.
While we were proceeding with this discussion @ncrescenzio  created a github page for the workshop. (Thanks!!! @ncrescenzio )

Here you can see a 1st draft (to be polished) https://ncrescenzio.github.io/km2024/

As it is a very nice page and could be very useful for future events, and easy to be custumized,  I would like to ask if you agree on using this reposoitory/web page for the workshop.

We can move it wherever you prefer (also in Kratos Organization in Github).

Let us know!!

Thanks and regards,

**Comment by rubenzorrilla** [comment]
I also like it. As @antonialarese is pointing, I'd move to our organisation repository, possibly to the Documentation repo.

**Comment by sunethwarna** [comment]
Just a small reminder @ncrescenzio, As I remember, we can only have 10 web site builds per hour. So, you may not see the website getting updated at the rate you are pushing :wink:

**Comment by ncrescenzio** [comment]
Thanks for the info @sunethwarna!! I think i have finished 😅

**Comment by roigcarlo** [comment]
If its done can we merge it?

**Comment by sunethwarna** [comment]
I would say, let's keep it until the end or at least the start of the workshop. So we can make the last minute adjustments if there are any....

**Comment by roigcarlo** [comment]
Then please, let me upload here the changes I am doing to the doc, otherwise I cannot se if the changes work live

**Comment by ncrescenzio** [comment]
@roigcarlo sure, no problem from my side

**Comment by ncrescenzio** [comment]
I think we have to merge this PR. At the moment the webpage is not available due to a recent update in #11719.

**Review by ncrescenzio — APPROVED** [review]

**Pull request merged**
