### PR TITLE
[StructuralMechanics] Updating names

### PR DESCRIPTION
**Pull request by philbucher**
Hi,
this is a small PR to change the name of the internal solver from `mechanical_solver` to `mechanical_solving_strategy`
The issue with the current situation was that we had two solvers, i.e. the python class is called mechanical solver and the it has a member mechanical solver. This causes quite some confusion esp when talking to ppl who are not familiar with Kratos
@loumalouomega I also updated the names in the ContactApp, tests are running
@rubenzorrilla I don't think this affects you, at least the tests in the FSIapp are still running.

Also I added the option to skip the partitioning in the mpi case

### CODE REVIEW

**Comment by loumalouomega** [comment]
I am scare of the consequences of this PR in y current working branch

**Review by loumalouomega — DISMISSED** [review]
It looks OK

**Review by rubenzorrilla — DISMISSED** [review]
At a first glance, there won't be any interaction with the FSI app.

**Comment by philbucher** [comment]
I took the opportunity and also updated the python_wrappers (very minor)

**Comment by philbucher** [comment]
Can someone reapptove pls? :)

**Review by loumalouomega — APPROVED** [review]

**Pull request merged**
