### PR TITLE
[StructuralMechanicsApplication]Wrong sign on LineCondition2D

### PR DESCRIPTION
**Pull request by loumalouomega**
Part of #4599. Only fixing wrong sign

### CODE REVIEW

**Review by philbucher — APPROVED** [review]
Thx :)

this does not change tests?

**Comment by philbucher** [comment]
no change in tests?

**Comment by loumalouomega** [comment]
> no change in tests?

There are not test for Pressure load I think, checking it out

**Comment by rubenzorrilla** [comment]
I was having lots of troubles with the FSI interface load... hopefully they are related to this. Thanks for the fix!

**Comment by loumalouomega** [comment]
> I was having lots of troubles with the FSI interface load... hopefully they are related to this. Thanks for the fix!

if it was a problem of convergence can be related.

**Comment by rubenzorrilla** [comment]
> > I was having lots of troubles with the FSI interface load... hopefully they are related to this. Thanks for the fix!
> 
> if it was a problem of convergence can be related.

It is! ;)

**Comment by loumalouomega** [comment]
> > > I was having lots of troubles with the FSI interface load... hopefully they are related to this. Thanks for the fix!
> > 
> > 
> > if it was a problem of convergence can be related.
> 
> It is! ;)

BTW @rubenzorrilla and @RiccardoRossi  I was thinking I can move the part of derivatives utilities for the Jacobian that I use for the Contact, so we can have a better and more consistent following load. (AKA pressure load, with greater convergence)

**Pull request merged**
