### PR TITLE
Update CI

### PR DESCRIPTION
**Pull request by philbucher**

### CODE REVIEW

**Review by loumalouomega — DISMISSED** [review]
I assume the MMG is not compiled, we should update that, later

**Comment by philbucher** [comment]
yep right now is not there but we can easily add it in the docker imeage

**Comment by loumalouomega** [comment]
Okay

**Comment by philbucher** [comment]
~~~
[Error]: Tests for ContactStructuralMechanicsApplication took to long. Process Killed.
~~~

**Comment by loumalouomega** [comment]
OK, do I move tests in this PR directly?

**Comment by philbucher** [comment]
yes I would

**Review by loumalouomega — DISMISSED** [review]

**Comment by philbucher** [comment]
can you please make an issue abt the mmg stuff [here](https://github.com/oberbichler/kratos-dev) as a reminder? (instead of putting it in the configure)

**Review by loumalouomega — DISMISSED** [review]

**Review by loumalouomega — APPROVED** [review]

**Comment by philbucher** [comment]
Some tests in the nightly are failing, can you please check?

**Pull request merged**
