### PR TITLE
[Core][VariableUtils] Adding set methods with flags

### PR DESCRIPTION
**Pull request by loumalouomega**

### CODE REVIEW

**Comment by rubenzorrilla** [comment]
I'd add an argument containing the value of the flag with a default value of True.

**Comment by loumalouomega** [comment]
Not necessary, already a method for that (the ones without flag)

**Comment by rubenzorrilla** [comment]
And what if I want to set a variable value to a set of nodes if a flag is false?

**Comment by loumalouomega** [comment]
When a flag is registered the False one is registered too as NOT_WHATEVER_FLAG

**Comment by loumalouomega** [comment]
https://github.com/KratosMultiphysics/Kratos/blob/9e6fed1ac207f4f1a20a55803a854be16e047f68/applications/ContactStructuralMechanicsApplication/python_scripts/alm_contact_process.py#L321

**Comment by rubenzorrilla** [comment]
I'd set `True`as default value for the new argument.

**Comment by loumalouomega** [comment]
is true

**Comment by rubenzorrilla** [comment]
That's true. My bad.

**Review by rubenzorrilla — APPROVED** [review]

**Pull request merged**
