### PR TITLE
[Trilinos] protect import

### PR DESCRIPTION
**Pull request by philbucher**
as discussed in #6843 

@roigcarlo do you know how to catch all errors in python?

### CODE REVIEW

**Comment by roigcarlo** [comment]
You can catch `Exception` or `BaseException` that should catch everything. Probably segfault and system erros will only be catch by the later

**Comment by philbucher** [comment]
> You can catch `Exception` or `BaseException` that should catch everything. Probably segfault and system erros will only be catch by the later

according to the internet the `BaseException` is the more appropriate here, it should catch everything

**Comment by philbucher** [comment]
@rubenzorrilla can you please try this on your cluster and please post the complete log?
Just to see what it looks like

**Comment by rubenzorrilla** [comment]
> @rubenzorrilla can you please try this on your cluster and please post the complete log?
> Just to see what it looks like

OK. I'll try ASAP.

**Comment by philbucher** [comment]
did you get a chance to try this @rubenzorrilla ?

**Comment by rubenzorrilla** [comment]
Sorry I completely forgot. I'll do it right now.

**Comment by rubenzorrilla** [comment]
It didn't worked... I'm attaching the output (which as far as I can remember is pretty similar to the one that raised the issue).

Importing the `MetisApplication` before the `TrilinosApplication` in the MainKratos.py works as expected.

```
[pez036:9064 :0] Caught signal 11 (Segmentation fault)
==== backtrace ====
 2 0x000000000006749c mxm_handle_error()  /var/tmp/OFED_topdir/BUILD/mxm-3.5.3092/src/mxm/util/debug/debug.c:641
 3 0x00000000000679ec mxm_error_signal_handler()  /var/tmp/OFED_topdir/BUILD/mxm-3.5.3092/src/mxm/util/debug/debug.c:616
 4 0x0000000000035250 killpg()  ??:0
 5 0x00000000000eeb74 METIS_WPartGraphRecursive()  ??:0
 6 0x00000000000ef052 METIS_PartGraphRecursive()  ??:0
 7 0x0000000000042363 libmetis__InitKWayPartitioning()  ??:0
 8 0x0000000000042497 libmetis__MlevelKWayPartitioning()  ??:0
 9 0x00000000000427c7 METIS_PartGraphKway()  ??:0
10 0x00000000000d49a8 _ZNSt6vectorIlSaIlEE17_M_default_appendEm()  ??:0
11 0x00000000000ec77d _ZNSt10_HashtableImmSaImENSt8__detail9_IdentityESt8equal_toImESt4hashImENS1_18_Mod_range_hashingENS1_20_Default_ranged_hashENS1_20_Prime_rehash_policyENS1_17_Hashtable_traitsILb0ELb1ELb1EEEE9_M_assignIZNSC_C4ERKSC_EUlPKNS1_10_Hash_nodeImLb0EEEE_EEvSF_RKT_()  ??:0
12 0x0000000000352966 _ZN6Kratos25CalculateNodalAreaProcessILb0EEC1ERNS_9ModelPartEm()  ??:0
13 0x0000000000149516 _ZN6Kratos18DataValueContainer8SetValueIN5boost7numeric5ublas6vectorIdNS4_15unbounded_arrayIdSaIdEEEEEEEvRKNS_8VariableIT_EERKSB_()  ??:0
14 0x00000000000cbb5d _PyCFunction_FastCallDict()  /root/src/python/Python-3.6.7/Objects/methodobject.c:231
15 0x0000000000164d48 call_function()  /root/src/python/Python-3.6.7/Python/ceval.c:4861
16 0x00000000001687b2 _PyEval_EvalFrameDefault()  /root/src/python/Python-3.6.7/Python/ceval.c:3335
17 0x0000000000164270 _PyFunction_FastCall()  /root/src/python/Python-3.6.7/Python/ceval.c:4919
18 0x0000000000165194 fast_function()  /root/src/python/Python-3.6.7/Python/ceval.c:4954
19 0x0000000000165194 call_function()  /root/src/python/Python-3.6.7/Python/ceval.c:4858
20 0x00000000001687b2 _PyEval_EvalFrameDefault()  /root/src/python/Python-3.6.7/Python/ceval.c:3335
21 0x0000000000164270 _PyFunction_FastCall()  /root/src/python/Python-3.6.7/Python/ceval.c:4919
22 0x0000000000165194 fast_function()  /root/src/python/Python-3.6.7/Python/ceval.c:4954
23 0x0000000000165194 call_function()  /root/src/python/Python-3.6.7/Python/ceval.c:4858
24 0x00000000001687b2 _PyEval_EvalFrameDefault()  /root/src/python/Python-3.6.7/Python/ceval.c:3335
25 0x0000000000164270 _PyFunction_FastCall()  /root/src/python/Python-3.6.7/Python/ceval.c:4919
26 0x0000000000165194 fast_function()  /root/src/python/Python-3.6.7/Python/ceval.c:4954
27 0x0000000000165194 call_function()  /root/src/python/Python-3.6.7/Python/ceval.c:4858
28 0x00000000001687b2 _PyEval_EvalFrameDefault()  /root/src/python/Python-3.6.7/Python/ceval.c:3335
29 0x0000000000164270 _PyFunction_FastCall()  /root/src/python/Python-3.6.7/Python/ceval.c:4919
30 0x0000000000165194 fast_function()  /root/src/python/Python-3.6.7/Python/ceval.c:4954
31 0x0000000000165194 call_function()  /root/src/python/Python-3.6.7/Python/ceval.c:4858
32 0x00000000001687b2 _PyEval_EvalFrameDefault()  /root/src/python/Python-3.6.7/Python/ceval.c:3335
33 0x0000000000164bde _PyEval_EvalCodeWithName()  /root/src/python/Python-3.6.7/Python/ceval.c:4166
34 0x000000000016520d PyEval_EvalCodeEx()  /root/src/python/Python-3.6.7/Python/ceval.c:4187
35 0x000000000016525b PyEval_EvalCode()  /root/src/python/Python-3.6.7/Python/ceval.c:731
36 0x00000000001a1552 run_mod()  /root/src/python/Python-3.6.7/Python/pythonrun.c:1025
37 0x00000000001a1552 PyRun_FileExFlags()  /root/src/python/Python-3.6.7/Python/pythonrun.c:978
38 0x00000000001a16b7 PyRun_SimpleFileExFlags()  /root/src/python/Python-3.6.7/Python/pythonrun.c:419
39 0x00000000001bdccd run_file()  /root/src/python/Python-3.6.7/Modules/main.c:340
40 0x00000000001bdccd Py_Main()  /root/src/python/Python-3.6.7/Modules/main.c:810
41 0x0000000000400b1c main()  /root/src/python/Python-3.6.7/./Programs/python.c:69
42 0x0000000000021b35 __libc_start_main()  ??:0
43 0x0000000000400bdd _start()  ??:0
===================

```

**Comment by philbucher** [comment]
hm

did you play around a bit?

I.e. catch all exceptions or do a try with the entire TrilinosApplication?

Just to understand the problem better, essentially if this sort of errors can be caught at all

To bad I cannot reproduce it :/

**Comment by philbucher** [comment]
So I did some testing myself and I made it fail by reproducing #5373 and got the following output:
~~~
Using 2 OpenMP threads

 |  /           |
 ' /   __| _` | __|  _ \   __|
 . \  |   (   | |   (   |\__ \
_|\_\_|  \__,_|\__|\___/ ____/
           Multi-Physics 9.0."Dev"-ab01d9f3f4-Release
Compiled with OpenMP and MPI support.
Maximum OpenMP threads: 2.
Running without MPI.
TrilinosApplication: The import of the TrilinosApplication failed with the following error: 
TrilinosApplication: /home/philipp/software/Kratos_MasterBranch/install/libs/KratosTrilinosApplication.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN6Kratos24ParallelFillCommunicatorC1ERNS_9ModelPartE 
TrilinosApplication: Please visit the following website for known issues: 
TrilinosApplication: https://github.com/KratosMultiphysics/Kratos/tree/master/applications/TrilinosApplication#known-issues 
Segmentation fault (core dumped)
~~~

so for me it works, but for you @rubenzorrilla it just crashes?

**Comment by rubenzorrilla** [comment]
The simulation crash occurs if the `MetisApplication` is imported after the `TrilinosApplication` (I'm not sure if #5373 reproduces this). 

I tried to aply the `try` and `catch` approach you propose to the `MetisApplication` import and it didn't worked... It seems that the error is not raising at the import moment but just after...

**Comment by philbucher** [comment]
closing as not working, the issue is when importing the MetisApp AFTER the TrilinosApp

**Pull request closed without merging**
