### PR TITLE
[Core] Adding typename to compile in Windows

### PR DESCRIPTION
**Pull request by tteschemacher**
Hi all,

I would need to add twice a typename to compile KRATOS in Windows.

Thanks!
Tobias

### CODE REVIEW

**Comment by philbucher** [comment]
Does it compile again for you with this change?

**Comment by tteschemacher** [comment]
It does.

**Review by roigcarlo — APPROVED** [review]
I suppose its ok

**Comment by philbucher** [comment]
ping @tteschemacher

**Pull request merged**
