### PR TITLE
[Core] proper pybind namespace

### PR DESCRIPTION
**Pull request by philbucher**

### CODE REVIEW

**Comment by loumalouomega** [comment]
This is the mother of all conflicts

**Comment by philbucher** [comment]
> This is the mother of all conflicts

but not much we can do abt it :/

**Review by RiccardoRossi — APPROVED** [review]

**Comment by philbucher** [comment]
I am merging this now, to avoid conflicts as much as possible

**Comment by maceligueta** [comment]
Just for curiosity, what was the problem before this PR?

**Comment by philbucher** [comment]
Afair the size_t definition of pybind clashes with the one of the windows compiler
-> due to this we currently habe to hack pybind -> 
https://github.com/KratosMultiphysics/Kratos/pull/2877/commits/fd3429803ac84d4cabc99a523bbf6bab35fb3414

Once all the apps are updated this hack is no longer necessary 

Jordi/Charlie please correct me if I explained it wrong

**Comment by philbucher** [comment]
@maceligueta also the [pybind-docs](https://pybind11.readthedocs.io/en/latest/basics.html#header-and-namespace-conventions) show to do it this way

**Pull request merged**
