### PR TITLE
Added ListImportedApp and MapImportedApps utilities

### PR DESCRIPTION
**Pull request by roigcarlo**
**Description**
Adds a couple of utilities to retrieve the list of applications that are loaded or have been loaded through an execution. 
It also adds a utility to retrieve it in form of a map with nested dependencies.

It detects applications automatically imported from process by the stage, but does not resolve third party dependencies.

It can be expanded to list all symbols and not only modules if needed.

**Example** (a fluid script that prints in hdf5):

List:
```
['KratosMultiphysics', 'KratosMultiphysics.FluidDynamicsApplication', 'KratosMultiphysics.HDF5Application', 'KratosMultiphysics.HDF5Application.core.operations', 'KratosMultiphysics.HDF5Application.core']
```

Map:
```json
{
	"KratosMultiphysics": {
		"FluidDynamicsApplication": {},
		"HDF5Application": {
			"core": {
				"operations": {}
			}
		}
	}
}
```

**Note**
Tests are missing because I cannot tests this in the core without importing an app, which is the solo purpose of this utility

**Changelog**
- Added GetListOfImportedApplications utility
- Added GetMapOfImportedApplications utility

### CODE REVIEW

**Comment by roigcarlo** [comment]
Now its module agnostic, in case you want to use it over things that are not `KratosMultiphysics` :eyes:

**Review by philbucher — COMMENTED** [review]
you can add tests (I recommend with the main apps) in the core if you add `skipTest`

**Comment by roigcarlo** [comment]
I can add it but it will be a mess. It has to hang form test_KratosCore.py, which import all the tests from the core. Some of them, like `test_gid_io_gauss_points` make use of conditional imports which, if executed before this tests, would make the results to change.

So in order to get consistent results I would have to either know beforehand if an application has been imported elsewhere ( and when) or either disable it if I know other applications have been compiled, which would render the tests useless. 
The main problem with this situation is not getting the list now, but if someone in the future adds another import, it has to take care of making the necessary changes to this test or it could break because of changes that are not related to the test itself.

If its only to show how to use it I can add a tests that always is skipped, but we won¡t be able to make this run as it is.

**Review by philbucher — APPROVED** [review]
I don't understand what this can be  used for but I trust you :)

**Comment by roigcarlo** [comment]
It has to do with restarting apps with use custom processes from different apps or something like that. Don't know the exact details, anyway it does not harm anyone to have :P

**Pull request merged**
