### PR TITLE
Adding fancy ouput to the core

### PR DESCRIPTION
**Pull request by loumalouomega**
The fancy output (with table) has been moved to the core

### CODE REVIEW

**Comment by loumalouomega** [comment]
imagen
Example

**Comment by loumalouomega** [comment]
Right now it is available for the the core, StructuralMechanics, and the FluidDynamicsApplication

**Comment by rubenzorrilla** [comment]
Vicente is back :metal:

**Comment by RiccardoRossi** [comment]
@pooyan-dadvand, you are working on the logger etc. Please share your point of view on this one

**Comment by pooyan-dadvand** [comment]
Indeed it is nice and fancy, nevertheless I'm not sure if it worth to make the convergence criteria depend to an additional external library. Moreover it is not passing through the logger as @RiccardoRossi is mentioning. So I would suggest @loumalouomega to put this as a new output in the logger. Unfortunately I had not have time to write a wiki for logger so I will talk to him directly and show him how it is.

**Comment by loumalouomega** [comment]
OK, but the dependency is just one file, and can be recoded easily. Besides if I recode it, it will be 95% the same (it is very simple indeed). So I think it is OK to respect the original author

**Comment by loumalouomega** [comment]
Dependency removed, basically I rewrote the table stream, was not so complicated but I feel that the original library must be at least referenced

**Comment by pooyan-dadvand** [comment]
@loumalouomega we should add this to the logger output not to the convergence criteria. Let talk about it and make it work there so it will be available for other parts too.

**Comment by loumalouomega** [comment]
OK, I will go in a momment

**Comment by loumalouomega** [comment]
After speaking with @pooyan-dadvand I will close this PR and create a new one with the log utils

**Comment by loumalouomega** [comment]
I will not delete the branch right now because there are some things I want to reuse

**Pull request closed without merging**
