### PR TITLE
Fix GidIO test

### PR DESCRIPTION
**Pull request by philbucher**
Hi @roigcarlo 
The test fails in nightly, but runs in my machine. (form test and from python_scripts directory)
This is another attempt of fixing it
The problem is that it does not find the file for some reason

### CODE REVIEW

**Comment by roigcarlo** [comment]
Let me build it in my machine, maybe the problem are of some files not being copied

**Comment by roigcarlo** [comment]
I added a commit, the problem seems to be the *.ref files, which are not copied to the test directory. 

In the nightly machine (and in pretty much any other machine is not user for development) we copy the test files to a different install directory. The copy mechanism is a white-list and *.ref files were not allowed. That should fix it.

**Review by roigcarlo — DISMISSED** [review]
Feels wrong that I approve this after making changes but anyway :stuck_out_tongue_winking_eye:

**Comment by philbucher** [comment]
hi @roigcarlo 
thx for your help!
I reverted my initial change since I think it was correct already.
Could you please re-approve :)

**Review by roigcarlo — APPROVED** [review]
:+1:

**Comment by roigcarlo** [comment]
Let me merge this, I need to modify yhis file in another PR

**Pull request merged**
