### PR TITLE
[CI] enable parallel build

### PR DESCRIPTION
**Pull request by philbucher**
**Description**
This seems to work now, tested it a few times
almost cuts the build times in half!!!

### CODE REVIEW

**Comment by philbucher** [comment]
ok now I also confirmed for the nightly build, the times decreased by a factor of ~2!

**Comment by philbucher** [comment]
ping @roigcarlo :)

**Review by roigcarlo — APPROVED** [review]
Wait, were we building with 1 core???

**Comment by philbucher** [comment]
> Wait, were we building with 1 core???

yes

I think with Cotire it was not possible to use more bcs the compiler ran out of memory
with the unity build it is better :)

**Comment by philbucher** [comment]
this is so much faster, what a joy :D

**Pull request merged**
