### PR TITLE
Adding app destructor overrides

### PR DESCRIPTION
**Pull request by philbucher**
see #2748 
This is already done in the big Apps like FluidDynamics and StructuralMechanics

I didn't want to mess up the repo with individual PRs, so I put them in one, sorry for the inconvenience

I will leave this for a couple of days but I think it shouldn't influence anyone
Please tell if otherwise

FYI @rubenzorrilla @msandre @sunethwarna @AndreasWinterstein @dbaumgaertner @armingeiser

### CODE REVIEW

**Review by loumalouomega — DISMISSED** [review]
Is this OK in the application creator?

**Comment by philbucher** [comment]
good question
I looked it up but it is too cryptic, @roigcarlo could you please have a look if you have time?

**Comment by roigcarlo** [comment]
Yep, give me a moment

**Comment by philbucher** [comment]
since nobody complains I think we can go ahead with merging
can someone approve pls?

**Review by loumalouomega — APPROVED** [review]
OK

**Comment by loumalouomega** [comment]
@philbucher you forgot to merge

**Pull request merged**
