### PR TITLE
[StructuralMechanicsApplication] Allowing to use again the EliminationBuilderAndSolver

### PR DESCRIPTION
**Pull request by loumalouomega**
It was deactivated after we considered by default the MPC builder and solver

### CODE REVIEW

**Comment by philbucher** [comment]
I think you can already now use it if you set ‚multi_point_constraints_used‘ to false in your json

**Comment by loumalouomega** [comment]
I already set block_builder as false

**Review by AlejandroCornejo — APPROVED** [review]

**Comment by philbucher** [comment]
@loumalouomega I would appreciate if you would wait with merging until discussions are resolved. Wasn’t there an agreement some time ago to leave PRs at least 24hrs open until ppl had time to comment, even for „small“ things?
I wouldn’t want to block PRs just so that I have time to think abt it and give my thoughts.

IMO now the behavior is wrong
Previously you could have used the elim-B&S by setting „block_builder“ and „use_mpcs“ to false, which I think is correct
I.e. even if I have mpcs present I actively choose to neglect them
Now it throws if I have MPCs but am fine with not considering them

**Comment by loumalouomega** [comment]
Right now the B&S wasn't even working, and I am currently working in an elimination builder and solver with constraints. So this issue will be outdated in few time

**Comment by loumalouomega** [comment]
BTW @rubenzorrilla told me that now the Trilinos tests are not working in the Structural due to the MPC check builder and solver check

**Comment by pooyan-dadvand** [comment]
I agree with @philbucher that this kind of changes should stay and discussed and also labelled as behaviour change. Note that there are applications built over structural application

**Comment by RiccardoRossi** [comment]
Ok so here my two cents (@KratosMultiphysics/structural-mechanics @KratosMultiphysics/fluid-dynamics :

1 - i think we should try to respect the 24h rule (not including weekends, blame to myself) for anything but the smallest PRs 
2 - I would propose that for changes to structural mechanics and fluid mechanics that we try to have approval both from CIMNE & TUM
3 - +1 for the Behaviour Change label (and we should have also "InputChange" and "APIchange")
4 - I think you are both right in what can be selected and how. Meaning that i am of the opinion that the check should be something like

    if(block_builder)
           if(use_mpc) 
                return block_with_mpc
           else
                if( there are mpcs ):
                         errror
                else
                      return block
    ...same for elimination ...

**Comment by loumalouomega** [comment]
I just want to say that this change the behaviour to better, before this change it wasn't even working.

 If you selected in the interface the elimination builder and solver, it was a hotfix to avoid complains of the elimination builder and solver not working.

**Comment by RiccardoRossi** [comment]
@loumalouomega the point is not wheter it is for good (it is) ,
however we do need to be more strict with changes that affect behaviour

**Comment by loumalouomega** [comment]
@RiccardoRossi I completely understand, I am sorry. I considered this as hotfix, besides we don't have any test (yet) that checks if we are using an elimination builder and solver

**Pull request merged**
