### PR TITLE
Addition of missing overrides in interface geometries

### PR DESCRIPTION
**Pull request by rubenzorrilla**

### CODE REVIEW

**Comment by loumalouomega** [comment]
Strange, I used the clang tidy yesterday before merge

**Comment by RiccardoRossi** [comment]
@loumalouomega this means that you took the geometries from a old branch and you copied them on the top of the more modern one. NOT good practice...

**Comment by loumalouomega** [comment]
No, this is because I work in my branch to avoid recompiling from zero every time and then I cherrypick. But some of the last updates have been problematic with conflicts because some of my PR where in the limbo. Not a good practice, but many of my PR have been waiting months and some of then still waiting

**Comment by RiccardoRossi** [comment]
Dear Vicente,

unfortunately the fact that a commit is waiting long is not a sufficiently good reason. Your commits are waiting since there is no agreement on them (for whatever reason, not necessarily your fault). 

What should be avoided is to overwrite newer code with older version to get rid of a conflict. The conflict must be resolved instead... even if this may be painful. Not doing this would be extremely risky since it may imply loosing corrections already done (like the overrides in this case)

It doesn't help at the moment of doing a merge (or of reviweing your code) if you make a lot of "cosmetic" changes... which is the reason for which we constantly ask you from refraining from that ;-)

**Comment by loumalouomega** [comment]
Of course, the thing is sometimes when I do the merge and solve the conflicts I can do mistakes, and basically when I did the merge with PR of the overrides I selected wrongly the correct file to solve the conflict. Too many conflicted files.

**Review by RiccardoRossi — APPROVED** [review]

**Comment by loumalouomega** [comment]
@rubenzorrilla did you used clang tidy or was it added manually?

**Comment by rubenzorrilla** [comment]
Thanks @ipouplana!
@loumalouomega I added the overrides manually. My bad... I'm fixing it right now.

**Comment by rubenzorrilla** [comment]
@ipouplana I've just fixed it (check #659). There were two different issues:

- In one method I added a wrong override (my bad...)
- Some of the overrided methods in the derived classes were not exactly equal to the base class ones

**Comment by ipouplana** [comment]
Thanks @rubenzorrilla! I'll review it in a moment

**Pull request merged**
