### PR TITLE
Adding M_PI def

### PR DESCRIPTION
**Pull request by roigcarlo**
With the upcoming change to quaternion.h geometry tests will stop compiling in win since they lack definition of `M_PI`

Probably we should centralize the definition of M_PI anyway...

### CODE REVIEW

**Comment by loumalouomega** [comment]
can we just use #define _USE_MATH_DEFINES and cmath?

**Comment by roigcarlo** [comment]
Yes and no. It solves the problem, but some classes right now are not using M_PI from math.h / or cmath. Hence the "should centralize". This PR is just to prevent the release from breaking

P.s. When I say "some" I mean "A lot"

**Comment by pooyan-dadvand** [comment]
I would take this opportunity to change them to constant variables (Not macro) in Globals namespace:

```c++
namespace Globals{
constexpr double Pi=3.14159265359;
}
```
and a place to put it would be in [global_variables.h](https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/includes/global_variables.h)

**Comment by roigcarlo** [comment]
Ok, with the idea but in the particular case of M_PI I will simply put in in `namespace Kratos {}` in [global_variables.h](https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/includes/global_variables.h) and call it M_PI. 

`Pi` as a name looks misleading, since everyone (I think) is used to M_PI. Also if it is defined inside globals we have to either add `using namespace Kratos::Globals` in every file or ```Globals::M_PI``` every time we use it, which feels too verbose to me at least.

**Comment by jcotela** [comment]
👍 for `Globals::Pi`. Call it `Math::Pi` if you want it a bit shorter, but I think it is clearer that `M_PI`.

**Comment by roigcarlo** [comment]
Ok, Let it be `Globals::Pi` then

**Comment by RiccardoRossi** [comment]
i think therr is a KRATOS_PI defined somewhere

**Comment by roigcarlo** [comment]
Edit: Found it.

**Comment by pooyan-dadvand** [comment]
So let also change the KRATOS_PI macro to a variable....

**Comment by roigcarlo** [comment]
Yep already done, let's check that it compiles

**Comment by roigcarlo** [comment]
@pooyan-dadvand @josep-m-carbonell 
I have this almost ready but there is a problem. Since the new definition of `Pi` lives in global_variables.h there is a cyclic include:

> quaternion -> global_variables
> global_variables -> variable_list
> variable_list -> kratos_components
> kratos_components -> quaternion

which prevents global_variables from seeing the definition of `KratosComponents` class. 

Is there a way to remove the quaternion include from KratosComponents or should we move the definition of Pi elsewhere?

**Comment by pooyan-dadvand** [comment]
We should take out the default variables list from this file....

**Comment by roigcarlo** [comment]
@josep-m-carbonell Last commit should solve the remaining issues 
@pooyan-dadvand I think we better left the remaining pi's ( the ones people has locally declared) to a future PR....

**Comment by roigcarlo** [comment]
Last commits fix a couple of problems in e47540bf9d675e184db086f4210cfde963f5d55b

**Comment by roigcarlo** [comment]
Ok it compiles now. Maybe I still have missed something, if you can please take a second look at it

**Review by josep-m-carbonell — APPROVED** [review]
All grep PI have been changed and now it compiles in windows and linux.

**Comment by roigcarlo** [comment]
Well since we are changing this and "from the lost to the river", probably is better to define Globals::Pi as a function with: 
```c++
constexp double Pi() { return std::atan(1)*4; }
```

**Comment by josep-m-carbonell** [comment]
it is good, so it will always have the machine precision

**Comment by pooyan-dadvand** [comment]
> Well since we are changing this and "from the lost to the river", probably is better to define Globals::Pi as a function with:
> 
> constexp double Pi() { return std::atan(1)*4; }

Have you test it in Windows?

**Comment by roigcarlo** [comment]
No, on a second though maybe is a good idea not to mess more with the release, if it works we can integrate it later.

**Comment by oberbichler** [comment]
Hi!
At the moment I get an error under Windows because of [some remaining M_PI in test_quadrilateral_3d_4.cpp](https://github.com/KratosMultiphysics/Kratos/blob/3bc6044330615a243e4afcff3404b02797a5bfd2/kratos/tests/geometries/test_quadrilateral_3d_4.cpp#L61).

**Comment by roigcarlo** [comment]
Ups, seems that one got through. Thx @oberbichler, fixing it now

**Comment by roigcarlo** [comment]
Will be fixed in #1089

**Pull request merged**
