### PR TITLE
[ContactStructuralMechanicsApplication] Get rid of ExternalSolversApplication

### PR DESCRIPTION
**Pull request by loumalouomega**
It is deprecated, so I remove the dependency. I also update the results of a test that is giving a slightly different results

### CODE REVIEW

**Review by philbucher — APPROVED** [review]
I am not sure how this works but I recommend adding skipTests if not already there

**Comment by loumalouomega** [comment]
> 
> 
> I am not sure how this works but I recommend adding skipTests if not already there

I just removed dependence from ExternalSolversApplication. Not needed anymore

**Comment by philbucher** [comment]
But which solver are u using now?
If you use a solver from an app then I recommend adding a skiptest
Otherwise the test will fail if the app is not compiled

**Comment by loumalouomega** [comment]
> 
> 
> But which solver are u using now?
> If you use a solver from an app then I recommend adding a skiptest
> Otherwise the test will fail if the app is not compiled

Just the default

**Pull request merged**
