### PR TITLE
Fixes problems with condition number utility

### PR DESCRIPTION
**Pull request by loumalouomega**
Fixex #1411

Valgring still detects error with ublas_space.h
~~~sh
3,072 bytes in 1 blocks are still reachable in loss record 4,364 of 4,376
==18040==    at 0x4C2FB0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==18040==    by 0xCFC6818: ??? (in /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0)
==18040==    by 0xCFD3F6C: ??? (in /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0)
==18040==    by 0xCFCAD45: GOMP_parallel (in /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0)
==18040==    by 0x9DC3605: Kratos::UblasSpace<double, boost::numeric::ublas::compressed_matrix<double, boost::numeric::ublas::basic_row_major<unsigned long, long>, 0ul, boost::numeric::ublas::unbounded_array<unsigned long, std::allocator<unsigned long> >, boost::numeric::ublas::unbounded_array<double, std::allocator<double> > >, boost::numeric::ublas::vector<double, boost::numeric::ublas::unbounded_array<double, std::allocator<double> > > >::TwoNorm(boost::numeric::ublas::compressed_matrix<double, boost::numeric::ublas::basic_row_major<unsigned long, long>, 0ul, boost::numeric::ublas::unbounded_array<unsigned long, std::allocator<unsigned long> >, boost::numeric::ublas::unbounded_array<double, std::allocator<double> > > const&) (ublas_space.h:268)
~~~

and with super_lu solver

~~~sh
==18040==    by 0xE8449B1: Kratos::SuperLUSolver<Kratos::UblasSpace<double, boost::numeric::ublas::compressed_matrix<double, boost::numeric::ublas::basic_row_major<unsigned long, long>, 0ul, boost::numeric::ublas::unbounded_array<unsigned long, std::allocator<unsigned long> >, boost::numeric::ublas::unbounded_array<double, std::allocator<double> > >, boost::numeric::ublas::vector<double, boost::numeric::ublas::unbounded_array<double, std::allocator<double> > > >, Kratos::UblasSpace<double, boost::numeric::ublas::matrix<double, boost::numeric::ublas::basic_row_major<unsigned long, long>, boost::numeric::ublas::unbounded_array<double, std::allocator<double> > >, boost::numeric::ublas::vector<double, boost::numeric::ublas::unbounded_array<double, std::allocator<double> > > >, Kratos::Reorderer<Kratos::UblasSpace<double, boost::numeric::ublas::compressed_matrix<double, boost::numeric::ublas::basic_row_major<unsigned long, long>, 0ul, boost::numeric::ublas::unbounded_array<unsigned long, std::allocator<unsigned long> >, boost::numeric::ublas::unbounded_array<double, std::allocator<double> > >, boost::numeric::ublas::vector<double, boost::numeric::ublas::unbounded_array<double, std::allocator<double> > > >, Kratos::UblasSpace<double, boost::numeric::ublas::matrix<double, boost::numeric::ublas::basic_row_major<unsigned long, long>, boost::numeric::ublas::unbounded_array<double, std::allocator<double> > >, boost::numeric::ublas::vector<double, boost::numeric::ublas::unbounded_array<double, std::allocator<double> > > > > >::Solve(boost::numeric::ublas::compressed_matrix<double, boost::numeric::ublas::basic_row_major<unsigned long, long>, 0ul, boost::numeric::ublas::unbounded_array<unsigned long, std::allocator<unsigned long> >, boost::numeric::ublas::unbounded_array<double, std::allocator<double> > >&, boost::numeric::ublas::vector<double, boost::numeric::ublas::unbo
~~~

### CODE REVIEW

**Comment by loumalouomega** [comment]
The valgring file

[out.out.zip](https://github.com/KratosMultiphysics/Kratos/files/1740419/out.out.zip)

**Review by pooyan-dadvand — COMMENTED** [review]
I have the feeling that the test is working better for your change on `1.0/normk` and not due to random initialization. Would you please verify it?

**Comment by loumalouomega** [comment]
Indeed, but with the random initialize the valgring still give some errors (sometimes)

**Comment by pooyan-dadvand** [comment]
Good to know!

@loumalouomega would you please investigate a little more about if this is a known valgrind issue?

**Comment by loumalouomega** [comment]
I assume that not using a fix seed is troublesome sometimes due to the random generation

Besides:

https://sourceforge.net/p/valgrind/mailman/valgrind-users/thread/20080514134032.64ab23cd%40br2wsl15.hb.orthogon.com/

**Review by RiccardoRossi — APPROVED** [review]

**Comment by loumalouomega** [comment]
Finally 

imagen

**Pull request merged**
