### PR TITLE
[DEM] clang compiler warnings

### LINKED ISSUE #4176: [DEM] clang compiler warnings from nightly build
~~~
/home/ubuntu/Kratos/applications/DEMApplication/custom_utilities/../custom_elements/spheric_continuum_particle.h:111:22: warning: 'Kratos::SphericContinuumParticle::CalculateOnContactElements' hides overloaded virtual function [-Woverloaded-virtual]
/home/ubuntu/Kratos/applications/DEMApplication/custom_utilities/analytic_tools/analytic_face_watcher.h:200:16: warning: private field 'mRelVelNormalxMass' is not used [-Wunused-private-field]
/home/ubuntu/Kratos/applications/DEMApplication/custom_utilities/analytic_tools/analytic_face_watcher.h:201:16: warning: private field 'mRelVelTangentialxMass' is not used [-Wunused-private-field]
/home/ubuntu/Kratos/applications/DEMApplication/custom_elements/spheric_continuum_particle.h:111:22: warning: 'Kratos::SphericContinuumParticle::CalculateOnContactElements' hides overloaded virtual function [-Woverloaded-virtual]
~~~

### PR DESCRIPTION
**Pull request by maceligueta**
Fixes #4176

### CODE REVIEW

**Comment by philbucher** [comment]
looks good to me, but I don't use CLANG, only saw it in the nightly build

@jcotela could you please compile DEM to see if there are some warnings? Thx

**Comment by maceligueta** [comment]
I am not getting warnings with my old clang 3.8.0. At least not in the DEM.
There's one in the json external library, but that's not coded by us I guess.

**Comment by jcotela** [comment]
The DEM application compiles clean for me too (clang 7.0.1)

**Review by philbucher — APPROVED** [review]
nice, thx guys

**Pull request merged**
