### PR TITLE
[ParticleMechanics] update py scripts

### PR DESCRIPTION
**Pull request by philbucher**
this PR does some cleaning and also updates the python-interface to the latest version

The GiD interface does not require updates, I just checked

tests are running, but there are some warnings, not sure if they are relevant:
~~~

 |  /           |
 ' /   __| _` | __|  _ \   __|
 . \  |   (   | |   (   |\__ \
_|\_\_|  \__,_|\__|\___/ ____/
           Multi-Physics 7.0.0-7d18bd7
Importing    KratosParticleMechanicsApplication 
    KRATOS  ____ __   ____ _____ _  ___ _   ____
           |  _ |  \ |  _ |_   _| |/   | | | ___|
           |   _| \ \|    | | | | |   (  |_| _|_
           |__|__/ \_\_|\_\ |_| |_|\___|___|____|MECHANICS
Initializing KratosParticleMechanicsApplication...
Unittests: 
Running cpp unit tests ... 
.................
Ran 17 of 619 test cases in 0.000392928s. OK.
Unittests: Finished running cpp unit tests! 
Unittests: 
Running python tests ... 
........................................................................................Geometry: Computation of local coordinates failed at iteration 46
Geometry: Computation of local coordinates failed at iteration 2
Geometry: Computation of local coordinates failed at iteration 43
Geometry: Computation of local coordinates failed at iteration 106
Geometry: Computation of local coordinates failed at iteration 6
Geometry: Computation of local coordinates failed at iteration 13
Geometry: Computation of local coordinates failed at iteration 160
Geometry: Computation of local coordinates failed at iteration 5
....Geometry: Computation of local coordinates failed at iteration 46
Geometry: Computation of local coordinates failed at iteration 2
Geometry: Computation of local coordinates failed at iteration 43
Geometry: Computation of local coordinates failed at iteration 106
Geometry: Computation of local coordinates failed at iteration 6
Geometry: Computation of local coordinates failed at iteration 13
Geometry: Computation of local coordinates failed at iteration 160
Geometry: Computation of local coordinates failed at iteration 5
.
----------------------------------------------------------------------
Ran 93 tests in 4.704s
~~~

### CODE REVIEW

**Comment by philbucher** [comment]
ping

**Comment by antonialarese** [comment]
thank you Philip!

**Review by antonialarese — APPROVED** [review]

**Comment by philbucher** [comment]
thanks

**Comment by bodhinandach** [comment]
@philbucher, Thanks for the update. I am sorry for the late response. I will take a look on it today. The warning is okay and expected.

**Pull request merged**
