### PR TITLE
[Core][Geometry] Bugfix which uses correct Normal computation in correspondence to the Integration Method

### PR DESCRIPTION
**Pull request by tteschemacher**

### CODE REVIEW

**Comment by philbucher** [comment]
ok for me if this tests pass
I triggered the nightly build with this: https://github.com/KratosMultiphysics/Kratos/actions/runs/675380653

**Comment by tteschemacher** [comment]
It would be a bit weird if the rest would fail...

**Comment by philbucher** [comment]
> It would be a bit weird if the rest would fail...

would you be surprised? :laughing:

**Comment by tteschemacher** [comment]
> > It would be a bit weird if the rest would fail...
> 
> would you be surprised? 😆

Well... 😅

**Review by philbucher — APPROVED** [review]
Tests are passing

**Comment by tteschemacher** [comment]
Yayy. Thanks.

**Pull request merged**
