### PR TITLE
[MetisApp] drop support for version 4

### PR DESCRIPTION
**Pull request by philbucher**
**Description**
Using Metis 4 has been long deprecated (Metis 5 was released 7 years ago)
Now using metis 4 is no longer supported, for a while also a proper error is thrown
This is another step towards cleaning the MetisApp

I would wait with the merge until after the release

FYI @KratosMultiphysics/mpi @KratosMultiphysics/altair

### CODE REVIEW

**Review by roigcarlo — COMMENTED** [review]
For me its ok,  did we already agree on the TC? if we did i can approve.

**Comment by philbucher** [comment]
hm not sure any more

it is in the next meeting TODO, probably better to confirm again to be sure

**Comment by pooyan-dadvand** [comment]
It makes sense. In @KratosMultiphysics/altair we are using metis 5.1.0

**Comment by philbucher** [comment]
if @rubenzorrilla and @RiccardoRossi agree here then we don't have to discuss it ...?

**Comment by rubenzorrilla** [comment]
Please go ahead. Just mentioning that we need to remove the `USE_METIS_5` from the [install](https://github.com/KratosMultiphysics/Kratos/blob/master/INSTALL.md) page once this is merged.

**Comment by philbucher** [comment]
> Please go ahead. Just mentioning that we need to remove the `USE_METIS_5` from the [install](https://github.com/KratosMultiphysics/Kratos/blob/master/INSTALL.md) page once this is merged.

makes perfect sense, done on #8058

**Review by RiccardoRossi — APPROVED** [review]

**Comment by philbucher** [comment]
merging, since everyone from @KratosMultiphysics/technical-committee agreed
Thx

**Pull request merged**
