### PR TITLE
[PotentialFlow] FullDebug hotfix non historical variables(2)

### PR DESCRIPTION
**Pull request by marcnunezc**
Hi,

After #5160 and #5174, a FullDebug execution error is introduced when accessing `GetValue(DISTANCE)` since it has not been initialized.

Here Im defining as const the geometry to later access it safely. There is an ongoing discussion in https://github.com/KratosMultiphysics/Kratos/pull/5146#discussion_r300564811 that is a bit unrelated to that  PR, so I open this here to 1) hotfix the application and 2) keep the discussion in this PR.

Same issue is happening with the TRAILING_EDGE variable in the adjoint element.

Not quite sure if this is the proper way to do this, or if Initializing the variable in `Initialize()` is preferred.

### CODE REVIEW

**Comment by inigolcanalejo** [comment]
Good question, I don't know the answer. Let me ping also @msandre and @jcotela  

@marcnunezc correct me if I am wrong. The question is: 

Is it better to initialize a non historical variable to make it threadsafe or to access it from a const object or both or it depends on the case?

**Comment by rubenzorrilla** [comment]
> Good question, I don't know the answer. Let me ping also @msandre and @jcotela
> 
> @marcnunezc correct me if I am wrong. The question is:
> 
> Is it better to initialize a non historical variable to make it threadsafe or to access it from a const object or both or it depends on the case?

Well, if you know a priori that you will never modify the value you can access from a const reference. However, this is of course impossible in case you need to modify it, so you end up with a first  `SetValue()` to avoid future memory leaks.

**Comment by marcnunezc** [comment]
> > Good question, I don't know the answer. Let me ping also @msandre and @jcotela
> > @marcnunezc correct me if I am wrong. The question is:
> > Is it better to initialize a non historical variable to make it threadsafe or to access it from a const object or both or it depends on the case?
> 
> Well, if you know a priori that you will never modify the value you can access from a const reference. However, this is of course impossible in case you need to modify it, so you end up with a first `SetValue()` to avoid future memory leaks.

If this is the case, then in this PR it makes sense to use the `const` definition since we are only reading the DISTANCE and TRAILING_EDGE value, we are not modifying them.

**Review by inigolcanalejo — APPROVED** [review]
I agree with @marcnunezc

**Pull request merged**
