### PR TITLE
[LinearSolversApplication] Reactivating MKL with Clang, because apparently now it compiles again

### PR DESCRIPTION
**Pull request by loumalouomega**
**📝 Description**

Reactivating MKL with Clang, because apparently now it compiles again

**🆕 Changelog**

- [Reactivating MKL with Clang, because apparently now it compiles again](https://github.com/KratosMultiphysics/Kratos/commit/d27fccbb28f85815d70b1dfb3126687c695ae9c9)

### CODE REVIEW

**Review by roigcarlo — APPROVED** [review]
Noice

**Review by philbucher — COMMENTED** [review]
Pretty sure it was a runtime and not a compiletime problem

Did you test it?

**Comment by loumalouomega** [comment]
> Pretty sure it was a runtime and not a compiletime problem
> 
> Did you test it?

Yes, I tested

**Comment by loumalouomega** [comment]
> Pretty sure it was a runtime and not a compiletime problem
> 
> Did you test it?

Yes, it was runtime, I tested

**Pull request merged**
