### PR TITLE
DUPLICATED FILE: Delete new_linear_solver_factory.py

### PR DESCRIPTION
**Pull request by loumalouomega**
I don't know why we have two solvers factory, but this one is older that the current linear_solver_factory.py

### CODE REVIEW

**Review by ipouplana — APPROVED** [review]
Hi @loumalouomega , me and Lorenzo import the linear_solver_factory.py, so it is not a problem for us to delete the new_linear_solver_factory.py

**Comment by loumalouomega** [comment]
OK, lets wait to @RiccardoRossi

**Comment by RiccardoRossi** [comment]
Hi @loumalouomega, @ipouplana  unfortunately i need to block this pull request, since the "new" one is "the good one".

let me explain this:
the "new_linear_solver_factory" employs the Parameters and it can be used directly with the input from the json. the "linear_solver_factory" is the old interface, which unfortunately is still used by some people.

in my opinion we should instead 
1 remove "linear_solver_factory" (or call it "legacy..")
2 rename the new_linear_solver_factory to linear_solver_factory

@ipouplana how can we make this so that it is the least possible pain to you?

**Review by RiccardoRossi — CHANGES_REQUESTED** [review]
unfortunately i need to block this (see my comment)

**Comment by loumalouomega** [comment]
@RiccardoRossi I assumed that, we can prepare a full PR for the migration in the future

**Comment by ipouplana** [comment]
Hi @RiccardoRossi , there is no problem in doing what you propose, i.e. removing the linear_solver_factory and renaming the new_linear_solver_factory to linear_solver_factory. We import the linear_sovler_factory.py but we call it with kratos Parameters so, in principle, I should not notice the change of the linear_solver_factory file.

**Comment by loumalouomega** [comment]
Let's try it

**Pull request closed without merging**
