### PR TITLE
Colors utility: using std::size_t instead of int

### PR DESCRIPTION
**Pull request by miguelmaso**
only a small change

### CODE REVIEW

**Review by roigcarlo — APPROVED** [review]

**Review by loumalouomega — APPROVED** [review]
Oki, thanks

**Comment by roigcarlo** [comment]
@miguelmaso Pending on #2015, the failing tests is not your problem, but we have to wait until this is solved somehow

**Comment by RiccardoRossi** [comment]
just to say that i just merged a correction for #2015, i am restarting the build...

btw, could u document somewhere how to use the coloring utility you wrote? it would be good also for @pablobecker

**Comment by loumalouomega** [comment]
@miguelmaso, do I write these doc or you?

**Review by RiccardoRossi — APPROVED** [review]

**Comment by miguelmaso** [comment]
I have started a small documentation

**Pull request merged**
