### PR TITLE
[Fluid] Update settings in Trilinos VMS solver

### PR DESCRIPTION
**Pull request by philbucher**
@jcotela if one properly defines the stabilization settings currently the Trilinos-VMS solver fails.

The solution I made seems to work, but please check it in detail.

Furthermore I think also the Fractional-Step solvers should be updated to use the new settings

### CODE REVIEW

**Review by RiccardoRossi — COMMENTED** [review]
@philbucher do we really need to change this? it will break existing examples (or throw warnings for until now perfectly fair stuff)

also the "dynamic_tau" switch is being used...

in any case overall i think we need to organize some sort of mechanism to have this sort of changes being discussed before going in. 
I guess this should include to routinely go through a meeting between TUM and Barcelona before approving this sort of changes. What do you think?
I mean this both the for the FluidDynamics and for the StructuralMechanics

**Comment by philbucher** [comment]
@RiccardoRossi I am only adapting the trilinos version of the vms solver to it's serial version => there the same is being done for a while already

In fact if I use the "correct" settings (i.e. the ones that don't give warnings in the serial version) it fails in MPI => therefore this PR

I agree abt the need for discussion, we should have skype more often again

@KratosMultiphysics/fluid-dynamics just for you to know I don't want to change your code without asking/discussing beforehand.
This is just intended as a fix for things that are not working

**Comment by jcotela** [comment]
@philbucher this is a fix that needs to be done, but just changing the json is not enough to make the solver work in the new mode. @ipouplana did a similar change on a different branch here 2174208b6755fde957540a206ab9cee828feb8f7, I think we need to combine the changes there with your commit for everything to be OK.

**Comment by jcotela** [comment]
@philbucher I went ahead and cherry-picked @ipouplana's changes into this branch. Can you test that the current version works for you?

**Comment by philbucher** [comment]
thx @jcotela I will test it and let you know

**Comment by RiccardoRossi** [comment]
Well, i am pretty sure this will break some of @rubenzorrilla 's solvers as well as what we are doing anew for the conjugate heat transfer problem...

we NEED to have a procedure to accept changes on the settings... and it must be a very slowly changing thing

**Comment by jcotela** [comment]
@RiccardoRossi I did not push for this to be done now, but it should not be disruptive. It does add warning messages if you use it "the old way", but otherwise it should still work as usual. The reason why I am willing to approve this quickly is that, as it is now, I would expect errors if you use a json developed for the "new" openmp version with the current mpi implementation.

**Comment by RiccardoRossi** [comment]
when did this change go in for the openmp version? i mean...the openmp one is the one that should be breaking our interface...

**Comment by jcotela** [comment]
May 8th: 364926c1bc5ff3588f69baf6e971810db0ae2bd3 (we needed this so that @ipouplana's element could work without having to define a new solver from scratch). Again, no interface-breaking, just deprecation warnings. I believe GiD still uses the old input format?

**Comment by rubenzorrilla** [comment]
@RiccardoRossi in principle, this shouldn't break any of the embedded solvers neither the new buoyancy and conjugate heat transfer ones. From the FSI side, it might break some of the examples, we should have a look to it. 

In any case, since this is something that needs to be done, I'm not blocking it.

**Comment by jcotela** [comment]
@philbucher did you test this in its current version?

**Comment by philbucher** [comment]
not yet, sorry
I will do it in the next days

**Comment by philbucher** [comment]
I tested it now, seems to work.
three questions:
- are the new settings used in a test?
- is the interface updated? I think it would be nice to have it working without deprecation warnings before the next release struggle begins
- Does the FractionalStep also need some updates?

@jcotela since I am the author of the PR I cannot approve it :)

**Comment by philbucher** [comment]
ping @jcotela

**Comment by jcotela** [comment]
@philbucher 
- There are tests using the solver with this format, but all of them just take the default value for this setting.
- I think the interface still writes in the "old mode" but I rewrite it in the main fluid_analysis.
- FractionalStep is not affected by this change (there is only one implementation, nothing to choose).

**Review by jcotela — APPROVED** [review]

**Pull request merged**
