### PR TITLE
Used os.path.join in CompareTwoFilesCheckProcess

### PR DESCRIPTION
**Pull request by philbucher**
I corrected what was mentioned in #1086 abt handling the paths by using os.path.join
@roigcarlo is this ok for you? I changed also the gid_io test to use the file comparison process instead of some custom thing. I hope this is ok bcs it is a little bit of overhead.
If you dont want this then i can revert it

@loumalouomega I checked and I think the meshing-app is the only app using this process. I don't have mmg, could you please check if the tests are still working? Thx.

FYI @KratosMultiphysics/technical-committee

### CODE REVIEW

**Comment by loumalouomega** [comment]
I can, but not right now, I have all my things meshed

**Review by roigcarlo — APPROVED** [review]
Good from my side! (I only tested the paths)

**Comment by philbucher** [comment]
Ping @Vicente

**Comment by loumalouomega** [comment]
OK, it works, at least in my machine, you can merge if you want

**Pull request merged**
