### PR TITLE
Fixing the inlet: now it moves the chicks with the eggs

### PR DESCRIPTION
**Pull request by GuillermoCasas**
All tests run OK (except after 33, that gives 0 error but a seg fault at the end of the program when run with all the others, although this is not new).

### CODE REVIEW

**Comment by maceligueta** [comment]
@salvalatorre , can you try this branch with your examples that contain moving inlets?

**Comment by salvalatorre** [comment]
G-DEMPack runs nice.
C-DEMPack gives a segfault in CreateElementsFromInletMesh. @GuillermoCasas, try to have a look at that. I'll try to check it too myself.

**Comment by salvalatorre** [comment]
The function DEM_Inlet::UpdateInjectedParticleVelocity gives problems at the line
Node<3>& central_node = particle.GetGeometry()[0].

**Comment by salvalatorre** [comment]
In fact, it looks like it only crashes with the continuum version of clusters, the continuum spheres work fine

**Comment by GuillermoCasas** [comment]
Sure, I will take a look this afternoon.

**Review by salvalatorre — APPROVED** [review]

**Pull request merged**
