### PR TITLE
[CoSim][NOT TO MERGE] install ping

### PR DESCRIPTION
**Pull request by philbucher**

### CODE REVIEW

**Comment by philbucher** [comment]
this is a test for #5771 

Locally this works, but in the CI the installing of aux-executables fails in all OSs

~~~
   CMake Error at applications/CoSimulationApplication/cmake_install.cmake:45 (file):
    file INSTALL cannot find
    "D:/a/Kratos/Kratos/build/Custom/applications/CoSimulationApplication/Custom/ping.exe":
    No such file or directory.
~~~

**Comment by philbucher** [comment]
any idea @roigcarlo @adityaghantasala ?

**Comment by roigcarlo** [comment]
My best guess here is that we are compiling with `make_all_unity` and those tests are not cotired, so they are not seen by the compiler

**Comment by philbucher** [comment]
> My best guess here is that we are compiling with `make_all_unity` and those tests are not cotired, so they are not seen by the compiler

I am pretty sure thats it :roll_eyes: :man_facepalming: 
Thx for the hint, I will try :)

**Comment by philbucher** [comment]
I checked again and I cannot get it to work when using cotire

on the other hand this is working somehow for blas and lapack: https://github.com/KratosMultiphysics/Kratos/blob/master/applications/ExternalSolversApplication/CMakeLists.txt#L125-L127

Any idea? :sweat_smile:

**Pull request closed without merging**
