### PR TITLE
Apps/improve py init

### PR DESCRIPTION
**Pull request by philbucher**
This PR updates how the new python-init scripts are being used.

Initially I had put them into the python_scripts folder of the apps and named the `__init__.py`, but this introduces the problem that then this folder can be imported as a python-modules, which should not be the case.

Therefore I moved them back where they were initially and used the original name
=> CMake does the renaming now when installing the file to `KratosMultiphysics`
=> this way we can avoid all problems with the potentially dangerous `__init__.py`

NOTE: this PR does not change the behavior, the apps still work as python-modules (introduced in #3217 )

sorry for the inconvenience

Wiki is updated

### CODE REVIEW

**Comment by philbucher** [comment]
seems like I messed up sth, fixing it now

**Comment by philbucher** [comment]
now it works, I had forgotten to rename some files

**Review by adityaghantasala — COMMENTED** [review]
The changes look fine according to what was discussed ..! 
@jcotela  do you also agree with these changes ?

**Comment by jcotela** [comment]
@adityaghantasala I discussed it briefly in person with @philbucher yesterday, but I think it makes a lot of sense.

**Comment by philbucher** [comment]
sorry for messing this up in the first place :/

**Review by jcotela — APPROVED** [review]

**Comment by philbucher** [comment]
thx

**Pull request merged**
