### PR TITLE
Update cmake file for particle mechanics application

### PR DESCRIPTION
**Pull request by tteschemacher**
Hello!

**Party**

This PR updates the cmake file for the particle mechanics application to the new KRATOS standard.

### CODE REVIEW

**Comment by tteschemacher** [comment]
@philbucher do you have any idea why windows doesn't like that change?

**Comment by philbucher** [comment]
I think there are still a lot of KRATOS_API missing for this to work :)
Currently it complains about the utilities

**Comment by philbucher** [comment]
https://github.com/KratosMultiphysics/Kratos/wiki/KRATOS_API-for-Windows-Compilation

positing this link to make it more popular

**Review by philbucher — APPROVED** [review]
looks good to me, thx

all good if it passes the CI

**Comment by tteschemacher** [comment]
Sweet. Thanks!

**Pull request merged**
