### PR TITLE
[Travis] Adding CSHARP_WRAPPER_APPLICATION to Travis compilation

### PR DESCRIPTION
**Pull request by loumalouomega**
The application is small, and add in it to Travis will avoid future breaks of the app. This only will test the inner functions (enough to avoid future issues like the last one). The C# properties cannot be testes for now

### CODE REVIEW

**Comment by roigcarlo** [comment]
Good for me but it fails installing the so for the new app :S

**Comment by philbucher** [comment]
I don't have a strong opinion on this one, maybe we can briefly discuss it later @KratosMultiphysics/technical-committee

**Comment by loumalouomega** [comment]
> Good for me but it fails installing the so for the new app :S

How is that even possible?

**Comment by roigcarlo** [comment]
> How is that even possible?

To begin with, we should add the app to cotire or it will trigger a multibuild, maybe is not being compiled for this reason and it tries to install something that is not there,

**Comment by loumalouomega** [comment]
> > How is that even possible?
> 
> To begin with, we should add the app to cotire or it will trigger a multibuild, maybe is not being compiled for this reason and it tries to install something that is not there,

OK

**Comment by pooyan-dadvand** [comment]
@KratosMultiphysics/technical-committee normally would not accept this (as it is not a core application) but in this case we accept it due to the following reasons:

1. It is a wrapper with a tiny code which is used by external devlopers
2. The compilation time is very small (order of some seconds)
3. Doesn't need any new requirements on the test machines

So after fixing the CI you may proceed with it.

**Comment by loumalouomega** [comment]
Done @KratosMultiphysics/technical-committee

**Comment by philbucher** [comment]
~~~
/home/travis/build/KratosMultiphysics/Kratos/applications/CSharpWrapperApplication/mesh_converter.cpp:54:30: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
             if (nodes.size() <= e.nodes[i]) {
                 ~~~~~~~~~~~~~^~~~~~~~~~~~~
/home/travis/build/KratosMultiphysics/Kratos/applications/CSharpWrapperApplication/mesh_converter.cpp: In function ‘void fixFace(CSharpKratosWrapper::face&, Kratos::intrusive_ptr<Kratos::Element>)’:
/home/travis/build/KratosMultiphysics/Kratos/applications/CSharpWrapperApplication/mesh_converter.cpp:85:31: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
             if (face.nodes[i] == kratosElement->pGetGeometry()->pGetPoint(j)->Id()) {
~~~

**Comment by loumalouomega** [comment]
Done

**Review by philbucher — APPROVED** [review]

**Comment by loumalouomega** [comment]
@Hubertus248 I recommend to move the source code file of the application in order to follow the typical structure of a Kratos application

**Comment by philbucher** [comment]
For some reason this broke the nightly tests, can you please check?
loading initial cache file SHARP_WRAPPER_APPLICATION=ON
CMake Error: Error processing file: SHARP_WRAPPER_APPLICATION=ON

**Comment by loumalouomega** [comment]
True, I forgot the D

**Comment by philbucher** [comment]
Seems like it also fails in Travis sometimes:
~~~
    TestCSharpWrapperUpdateNodePosition Failed with message: 
        Error: Check failed because z[i] = 1.875 is not near to 0.0 = 0 within the tolerance 1.19209e-07
in /home/travis/build/KratosMultiphysics/Kratos/applications/CSharpWrapperApplication/tests/cpp_tests/test_calculate.cpp:124:virtual void Testing::TestCSharpWrapperUpdateNodePosition::TestFunction()
~~~

**Comment by loumalouomega** [comment]
> Seems like it also fails in Travis sometimes:
> 
> ```
>     TestCSharpWrapperUpdateNodePosition Failed with message: 
>         Error: Check failed because z[i] = 1.875 is not near to 0.0 = 0 within the tolerance 1.19209e-07
> in /home/travis/build/KratosMultiphysics/Kratos/applications/CSharpWrapperApplication/tests/cpp_tests/test_calculate.cpp:124:virtual void Testing::TestCSharpWrapperUpdateNodePosition::TestFunction()
> ```

The original code is not mine, @Hubertus248 can you take a look?

**Comment by philbucher** [comment]
If you cannot fix it today then I suggest to disable it again until fixed, otherwise it blocks PRs from being merged

**Comment by loumalouomega** [comment]
Let me take a sneaky look, probably is something related with OMP

**Comment by loumalouomega** [comment]
I have run it 2000 times, no error

**Comment by philbucher** [comment]
Then I suggest to disable it again until fixed

**Comment by loumalouomega** [comment]
One question, could you replicate this in your PC?

**Comment by philbucher** [comment]
haven't tried

**Pull request merged**
