### PR TITLE
Feature fldyn addocumentation

### PR DESCRIPTION
**Pull request by rubenzorrilla**
"documentation" folder, which used to contain the symbolic implementations of the FluidDynamicsApplication has been renamed to "symbolic_generation". Besides a slight modification has been done in the symbolic NavierStokes element.

### CODE REVIEW

**Comment by loumalouomega** [comment]
I recommend to use a README.md instead of readme.txt, this way can be preview in Github and you can add images or any kind of Markdown content

**Comment by loumalouomega** [comment]
I changed the readme.txt by a README.md as I suggested

**Comment by rubenzorrilla** [comment]
Thanks Vicente. @jcotela I think that there is nothing else to be done (I will modify the .lyx file as soon as we found a new standard for the documentation).

**Review by jcotela — APPROVED** [review]
:+1:, but I won't approve .lyx files next time :stuck_out_tongue_winking_eye:

**Pull request merged**
