### PR TITLE
properties.h (std::map does not have [] const operator,  .at() must be used instead)

### PR DESCRIPTION
**Pull request by josep-m-carbonell**
Correction  needed for compilation of the properties when a GetTable is called

### CODE REVIEW

**Comment by RiccardoRossi** [comment]
normally "at" in std is a "safe" yet slower method. I admit however i am not sure in this specific case. Would the "find" method do here?

**Comment by josep-m-carbonell** [comment]
Looking into the documentation, at() returns a reference if the object exists and an error if not. find() returns an iterator, pointing to the end if the object does not exist. Well,  if we know that object exists it is better to use at(), else we can use find()  and check where the iterator is pointing.

**Comment by pooyan-dadvand** [comment]
I see the issue and I think using  at (from c++11) is a good fix. Let me check it in windows 

Meanwhile I see the point of @RiccardoRossi by using the find and check for error in debug mode is faster but I'm not sure how much is faster and if we should sacrifice the user experience for such improvement

**Comment by RiccardoRossi** [comment]
a discussion on the subject is here.

http://stackoverflow.com/questions/38734808/use-of-find-vs-at-in-map-unordered-map

i would have used 

     return *(mymap.find(..))

but this is mainly because "at" is very slow on vectors. 
@josep-m-carbonell, you are right that it may be a good usecase here

**Comment by pooyan-dadvand** [comment]
@RiccardoRossi as you said the difference  is more significant for vector. But still I don't know how is for map.

**Review by RiccardoRossi — APPROVED** [review]
ok, i have no serious reason not to accept the at.

The only "formal" one is that "at" has the meaning of a debug access for vectors, so i would personally not use it here. However it is not incorrect nor less performant so please go ahead.

**Comment by josep-m-carbonell** [comment]
Ok, if we detect in future that the performance of find() is better we will change it.
The change was needed to solve a compilation error.

**Pull request merged**
