### PR TITLE
Bugfix fluid dynamics bad memory

### PR DESCRIPTION
**Pull request by jcotela**
Fixing a couple of memory errors in FluidDynamicsApplication that were causing tests to fail when compiling in debug mode.

### CODE REVIEW

**Review by rubenzorrilla — APPROVED** [review]
Thanks a lot @jcotela !

**Comment by pooyan-dadvand** [comment]
@jcotela Do you think we should merge this also to the release 5.1?

**Comment by jcotela** [comment]
@pooyan-dadvand It does fix potential issues due to memory errors, so it may be interesting to include it in the release. What is required?

**Comment by jcotela** [comment]
I've also added these commits to the Relase-5.1 branch (via cherrypick)

**Pull request merged**
