### PR TITLE
[ContactStructuralMechanicsApplication] Update app to use #5390 

### PR DESCRIPTION
**Pull request by loumalouomega**
Now this PR is smaller

### CODE REVIEW

**Comment by tteschemacher** [comment]
Why did you close this?

**Comment by loumalouomega** [comment]
Because I need to update to the last changes and create a new PR to merge into the master

**Comment by tteschemacher** [comment]
Ok, let me know if you need something?

**Comment by loumalouomega** [comment]
15 minutes and will be done

**Pull request closed without merging**
