### PR TITLE
[Core] Mortar mapper ResetDatabase() implementation

### PR DESCRIPTION
**Pull request by rubenzorrilla**
Short function to clean the database in case the destination model part has changed.

### CODE REVIEW

**Review by loumalouomega — DISMISSED** [review]
Everything is fine

**Comment by philbucher** [comment]
Why not use „UpdateInterface“ like in the MappingApp?

**Comment by rubenzorrilla** [comment]
> Why not use „UpdateInterface“ like in the MappingApp?

Makes sense. @loumalouomega , do you agree?

**Comment by loumalouomega** [comment]
> > Why not use „UpdateInterface“ like in the MappingApp?
> 
> Makes sense. @loumalouomega , do you agree?

I don't have any problem with that

**Review by philbucher — APPROVED** [review]

**Pull request merged**
