### PR TITLE
[StructuralMechanics] Making modelpart-adding optional

### PR DESCRIPTION
**Pull request by philbucher**
This is needed if there are subsubmodelparts with the same name
This is currently not possible due to backwards-compatibility, but will be ok in the future / natively supported

### CODE REVIEW

**Review by loumalouomega — DISMISSED** [review]
This will change after the new model is merged, so is OK

**Review by loumalouomega — DISMISSED** [review]

**Comment by philbucher** [comment]
sorry for the noise, I simplified it.
Now it properly works with the new Format of the Model

**Comment by loumalouomega** [comment]
imagen

**Review by loumalouomega — DISMISSED** [review]

**Comment by philbucher** [comment]
Its not :D

One Process had to be updated :)

**Comment by philbucher** [comment]
Wait, sth else is odd, I have to check again -,-

**Comment by philbucher** [comment]
Now I am done, sorry, I am doing too many things at once

**Review by loumalouomega — APPROVED** [review]

**Pull request merged**
