### PR TITLE
[CI] reenable PotentialFlow

### PR DESCRIPTION
**Pull request by philbucher**

### CODE REVIEW

**Comment by philbucher** [comment]
@tteschemacher there is an error related to your things:
~~~
     TestCouplingGeometryNode Failed with message: 
        Error: Test Failed: p_coupling_geometry->GetGeometryPart(2) did not throw the expected error.
Expected:
Index 2 out of range. Composite contains only of: 2 geometries.
Got:
Error: Index 2 out of range. CouplingGeometry #4611686018469382544 has 2 geometries.

in kratos/geometries/coupling_geometry.h:203:CouplingGeometry<TPointType>::GeometryPointer CouplingGeometry<TPointType>::pGetGeometryPart(CouplingGeometry<TPointType>::IndexType) [with TPointType = Node<3>; CouplingGeometry<TPointType>::GeometryPointer = shared_ptr<Geometry<Node<3> > >; CouplingGeometry<TPointType>::IndexType = long unsigned int]


in kratos/tests/cpp_tests/geometries/test_coupling_geometry.cpp:97:virtual void Testing::TestCouplingGeometryNode::TestFunction()
~~~

@inigolcanalejo @marcnunezc there is also an error in the potentialApp:
~~~
   what():  Error: attempting to do a GetValue for: WAKE variable #3016772864 unfortunately the variable is not in the database and the operations is not threadsafe (this function is being called from within a parallel region)


in kratos/containers/data_value_container.h:220:TDataType& DataValueContainer::GetValue(const Variable<TDataType>&) [with TDataType = int]
   kratos/solving_strategies/schemes/residualbased_incrementalupdate_static_scheme.h:322:void ResidualBasedIncrementalUpdateStaticScheme<TSparseSpace, TDenseSpace>::Calculate_RHS_Contribution(Element::Pointer, ResidualBasedIncrementalUpdateStaticScheme<TSparseSpace, TDenseSpace>::LocalSystemVectorType&, ResidualBasedIncrementalUpdateStaticScheme<TSparseSpace, TDenseSpace>::EquationIdVectorType&, ProcessInfo&) [with TSparseSpace = UblasSpace<double, boost::numeric::ublas::compressed_matrix<...>, boost::numeric::ublas::vector<double> >; TDenseSpace = UblasSpace<double, boost::numeric::ublas::matrix<double>, boost::numeric::ublas::vector<double> >; Element::Pointer = intrusive_ptr<Element>; ResidualBasedIncrementalUpdateStaticScheme<TSparseSpace, TDenseSpace>::LocalSystemVectorType = boost::numeric::ublas::vector<double>; ResidualBasedIncrementalUpdateStaticScheme<TSparseSpace, TDenseSpace>::EquationIdVectorType = vector<long unsigned int>]
~~~

can you please take a look?

**Comment by tteschemacher** [comment]
Thanks Phillip. Sorry.

#6342 fixes that issue.

**Comment by philbucher** [comment]
@loumalouomega can you please take a look at the [output of the execution with valgrind](https://github.com/KratosMultiphysics/Kratos/pull/6338/checks?check_run_id=426434974)
There are many things related to your code, can you please check?
I guess you can reproduce it locally

**Comment by philbucher** [comment]
Another observation:
those lines appear often:
~~~
Kratos::Python::pybind11_init_KratosCompressiblePotentialFlowApplication(pybind11::module&) (compressible_potential_flow_python_application.cpp:36)
by 0x2654DFE0: PyInit_KratosCompressiblePotentialFlowApplication (compressible_potential_flow_python_application.cpp:32)
~~~

this refers to the variable `DRAG_COEFFICIENT`, which also exists in the DEMApp. I the DEMApp they use `KRATOS_DEFINE_VARIABLE`, whereas in the PotentialFlow they use `KRATOS_DEFINE_APPLICATION_VARIABLE`
@roigcarlo could this have an effect?

**Comment by philbucher** [comment]
should be fixed in #6366

**Comment by roigcarlo** [comment]
KRATOS_DEFINE_APPLICATION_VARIABLE should only affect to compilations in windows. 
For linux it should be the same. 

What the macro does is to append: `KRATOS_API(application)` to the definition of the variable, but that macro itself is empty or used only for making the variable visible in the DLL.

**Pull request closed without merging**
