### PR TITLE
[CI] Remove useless command in Win build

### PR DESCRIPTION
**Pull request by marcnunezc**
**Description**
Removing unused command in Windows build when downloading boost.

**Changelog**
Please summarize the changes in one list to generate the changelog:
E.g.
- Remove useless command

### CODE REVIEW

**Comment by marcnunezc** [comment]
@philbucher the big improvement I see here is to create a custom Dockerfile that we can push to our docker hub as we have with Ubuntu (where all dependancies will be downloaded/installed already), not sure if it's worth as windows is not a bottleneck right now.

**Comment by philbucher** [comment]
> @philbucher the big improvement I see here is to create a custom Dockerfile that we can push to our docker hub as we have with Ubuntu (where all dependancies will be downloaded/installed already), not sure if it's worth as windows is not a bottleneck right now.

the @KratosMultiphysics/technical-committee is discussing exactly that ;)

**Review by philbucher — APPROVED** [review]
thx
ok if CI passes

**Comment by marcnunezc** [comment]
Well it does not work :D. It seems to find BOOST correclty but then it fails with this:

```
C:\Users\runneradmin\AppData\Local\Temp\boost\boost_1_74_0\boost/bind.hpp(41): message : The practice of declaring the Bind placeholders (_1, _2, ...) in the global namespace is deprecated. Please use <boost/bind/bind.hpp> + using namespace boost::placeholders, or define BOOST_BIND_GLOBAL_PLACEHOLDERS to retain the current behavior. [D:\a\Kratos\Kratos\build\Custom\kratos\KratosCore_unity.vcxproj]
D:\a\Kratos\Kratos\external_libraries\amgcl\backend\builtin.hpp(253): fatal error C1002: compiler is out of heap space in pass 2 [D:\a\Kratos\Kratos\build\Custom\kratos\KratosCore_unity.vcxproj]
D:\a\Kratos\Kratos\external_libraries\amgcl\coarsening\smoothed_aggregation.hpp(202): fatal error C1002: compiler is out of heap space in pass 2 [D:\a\Kratos\Kratos\build\Custom\kratos\KratosCore_unity.vcxproj]
D:\a\Kratos\Kratos\external_libraries\amgcl\coarsening\detail\galerkin.hpp(45): fatal error C1002: compiler is out of heap space in pass 2 [D:\a\Kratos\Kratos\build\Custom\kratos\KratosCore_unity.vcxproj]
D:\a\Kratos\Kratos\external_libraries\amgcl\coarsening\detail\scaled_galerkin.hpp(47): fatal error C1002: compiler is out of heap space in pass 2 [D:\a\Kratos\Kratos\build\Custom\kratos\KratosCore_unity.vcxproj]
cl : command line error D8040: error creating or communicating with child process [D:\a\Kratos\Kratos\build\Custom\kratos\KratosCore_unity.vcxproj]
  Building Custom Rule D:/a/Kratos/Kratos/applications/MeshingApplication/custom_external_libraries/tetMeshOpt/CMakeLists.txt
cl : command line warning D9025: overriding '/W1' with '/w' [D:\a\Kratos\Kratos\build\Custom\applications\MeshingApplication\custom_external_libraries\tetMeshOpt\tetMeshOpt.vcxproj]
  Math3D.cpp
  u_delphiClasses.cpp
  u_elementCluster.cpp
  u_MeshLoaders.cpp
  u_ParallelFunctions.cpp
  u_ProcessTime.cpp
  u_qualityMetrics.cpp
  u_ShowMetrics.cpp
  u_TetraFunctions.cpp
  u_tools.cpp
  u_Types.cpp
  u_MeshSmooth.cpp
  Generating Code...
  tetMeshOpt.vcxproj -> D:\a\Kratos\Kratos\build\Custom\applications\MeshingApplication\custom_external_libraries\tetMeshOpt\Custom\tetMeshOpt.lib
Failed with error #1.
```

**Comment by philbucher** [comment]
~~~
D:\a\Kratos\Kratos\external_libraries\amgcl\backend\builtin.hpp(253): fatal error C1002: compiler is out of heap space in pass 2 [D:\a\Kratos\Kratos\build\Custom\kratos\KratosCore_unity.vcxproj]
~~~

that happens sometimes, you could just restart the build

**Comment by marcnunezc** [comment]
Ok it works, merging then!

**Pull request closed without merging**
