### PR TITLE
[DEM] Unified error criteria for the benchmarking system

### PR DESCRIPTION
**Pull request by farrufat-cimne**
Running DEM Benchmark 40... Generic test for code functionalities verification

The complete list of benchmarks are included at the end of this message as a quick reference.
DEM Benchmark 7: OK!........ Test 7 SUCCESSFUL (error: 0.0, time: 15.03s.)
DEM Benchmark 1: OK!........ Test 1 SUCCESSFUL (error: 0.0, time: 37.99s.)
DEM Benchmark 2: OK!........ Test 2 SUCCESSFUL (error: 0.0, time: 111.82s.)
DEM Benchmark 9: OK!........ Test 9 SUCCESSFUL (error: 0.0, time: 93.25s.)
DEM Benchmark 6: OK!........ Test 6 SUCCESSFUL (error: 0.0, time: 137.6s.)
DEM Benchmark 4: OK!........ Test 4 SUCCESSFUL (error: 0.0, time: 139.35s.)

==== THORNTON PAPER TESTS. FULL REGIME. HERTZIAN LAW ====

DEM Benchmark 11: OK!........ Test 11 (e=0.25) SUCCESSFUL
DEM Benchmark 8: OK!........ Test 8 SUCCESSFUL (error: 0.0, time: 138.89s.)
DEM Benchmark 11: OK!........ Test 11 (e=0.50) SUCCESSFUL
DEM Benchmark 11: OK!........ Test 11 (e=0.75) SUCCESSFUL

===== THORNTON PAPER TESTS. FULL REGIME. LINEAR LAW =====

DEM Benchmark 10: OK!........ Test 10 (e=0.25) SUCCESSFUL
DEM Benchmark 11: OK!........ Test 11 (e=0.90) SUCCESSFUL
DEM Benchmark 3: OK!........ Test 3 SUCCESSFUL (error: 0.0, time: 194.21s.)
DEM Benchmark 5: OK!........ Test 5 SUCCESSFUL (error: 0.0, time: 195.17s.)

======== DE/FE CONTACT BENCHMARKS ==========

DEM Benchmark 13: OK!........ Test 13 SUCCESSFUL

== BASIC CONTINUUM TESTS ==

DEM Benchmark 20: OK!........ Test 20 SUCCESSFUL
DEM Benchmark 21: OK!........ Test 21 SUCCESSFUL
DEM Benchmark 22: OK!........ Test 22 SUCCESSFUL
DEM Benchmark 23: OK!........ Test 23 SUCCESSFUL
DEM Benchmark 24: OK!........ Test 24 SUCCESSFUL
DEM Benchmark 25: OK!........ Test 25 SUCCESSFUL

===== DISCONTINUUM CLUSTERS TESTS =====

DEM Benchmark 30: OK!........ Test 30 SUCCESSFUL
DEM Benchmark 31: OK!........ Test 31 SUCCESSFUL
DEM Benchmark 10: OK!........ Test 10 (e=0.50) SUCCESSFUL
DEM Benchmark 14: OK!........ Test 14 SUCCESSFUL

==== WENSRICH PAPER TEST. ROLLING FRICTION ====

DEM Benchmark 12: OK!........ Test 12 SUCCESSFUL
DEM Benchmark 16: OK!........ Test 16 SUCCESSFUL
DEM Benchmark 15: OK!........ Test 15 SUCCESSFUL
DEM Benchmark 10: OK!........ Test 10 (e=0.75) SUCCESSFUL
DEM Benchmark 40: OK!........ Test 40_0 SUCCESSFUL (spheres)
DEM Benchmark 40: OK!........ Test 40_1 SUCCESSFUL (spheres)
DEM Benchmark 40: OK!........ Test 40_2 SUCCESSFUL (spheres)
DEM Benchmark 40: OK!........ Test 40_3 SUCCESSFUL (spheres)
DEM Benchmark 40: OK!........ Test 40_4 SUCCESSFUL (spheres)
DEM Benchmark 40: OK!........ Test 40_5 SUCCESSFUL (spheres)
DEM Benchmark 40: OK!........ Test 40_6 SUCCESSFUL (spheres)
DEM Benchmark 40: OK!........ Test 40_7 SUCCESSFUL (spheres)
DEM Benchmark 40: OK!........ Test 40_8 SUCCESSFUL (spheres)
DEM Benchmark 40: OK!........ Test 40_9 SUCCESSFUL (spheres)
DEM Benchmark 40: OK!........ Test 40_10 SUCCESSFUL (spheres)
DEM Benchmark 40: OK!........ Test 40_11 SUCCESSFUL (spheres)
DEM Benchmark 40: OK!........ Test 40_12 SUCCESSFUL (spheres)
DEM Benchmark 40: OK!........ Test 40_13 SUCCESSFUL (spheres)
DEM Benchmark 40: OK!........ Test 40_14 SUCCESSFUL (spheres)
DEM Benchmark 40: OK!........ Test 40_0 SUCCESSFUL (finite elements)
DEM Benchmark 40: OK!........ Test 40_1 SUCCESSFUL (finite elements)
DEM Benchmark 40: OK!........ Test 40_2 SUCCESSFUL (finite elements)
DEM Benchmark 40: OK!........ Test 40_3 SUCCESSFUL (finite elements)
DEM Benchmark 40: OK!........ Test 40_4 SUCCESSFUL (finite elements)
DEM Benchmark 40: OK!........ Test 40_5 SUCCESSFUL (finite elements)
DEM Benchmark 40: OK!........ Test 40_6 SUCCESSFUL (finite elements)
DEM Benchmark 40: OK!........ Test 40_7 SUCCESSFUL (finite elements)
DEM Benchmark 10: OK!........ Test 10 (e=0.90) SUCCESSFUL
DEM Benchmark 32: OK!........ Test 32 SUCCESSFUL
DEM Benchmark 33: OK!........ Test 33 SUCCESSFUL
DEM Benchmark 17: OK!........ Test 17 SUCCESSFUL

### CODE REVIEW

**Comment by philbucher** [comment]
@KratosMultiphysics/dem I am curious, do you have concrete plans of moving to the standard-testing framework? It would be a shame to break things only because tests are not run in the CI :/

**Comment by maceligueta** [comment]
We would be super happy to migrate these tests (the ones inside 'test_examples') to the Kratos standards, as soon as there's enough available time to run them. We have been told repeatedly that they are too heavy, so we kept them in a separate folder. Currently we only expect the tests in the 'tests' folder to be run by the CI.

**Comment by farrufat-cimne** [comment]
@maceligueta 

The complete list of benchmarks are included at the end of this message as a quick reference.
DEM Benchmark 7: OK!........ Test 7 SUCCESSFUL (error: 0.0, time: 16.22s.)
DEM Benchmark 1: OK!........ Test 1 SUCCESSFUL (error: 0.0, time: 36.19s.)
DEM Benchmark 2: OK!........ Test 2 SUCCESSFUL (error: 0.0, time: 116.07s.)
DEM Benchmark 9: OK!........ Test 9 SUCCESSFUL (error: 0.0, time: 101.17s.)
DEM Benchmark 6: OK!........ Test 6 SUCCESSFUL (error: 0.0, time: 138.65s.)
DEM Benchmark 4: OK!........ Test 4 SUCCESSFUL (error: 0.0, time: 138.91s.)

==== THORNTON PAPER TESTS. FULL REGIME. HERTZIAN LAW ====

DEM Benchmark 11: OK!........ Test 11 (e=0.25) SUCCESSFUL
DEM Benchmark 8: OK!........ Test 8 SUCCESSFUL (error: 0.0, time: 136.96s.)
DEM Benchmark 11: OK!........ Test 11 (e=0.50) SUCCESSFUL
DEM Benchmark 11: OK!........ Test 11 (e=0.75) SUCCESSFUL

===== THORNTON PAPER TESTS. FULL REGIME. LINEAR LAW =====

DEM Benchmark 10: OK!........ Test 10 (e=0.25) SUCCESSFUL
DEM Benchmark 11: OK!........ Test 11 (e=0.90) SUCCESSFUL
DEM Benchmark 3: OK!........ Test 3 SUCCESSFUL (error: 0.0, time: 197.54s.)
DEM Benchmark 5: OK!........ Test 5 SUCCESSFUL (error: 0.0, time: 198.14s.)


======== DE/FE CONTACT BENCHMARKS ==========

DEM Benchmark 13: OK!........ Test 13 SUCCESSFUL


== BASIC CONTINUUM TESTS ==

DEM Benchmark 20: OK!........ Test 20 SUCCESSFUL
DEM Benchmark 21: OK!........ Test 21 SUCCESSFUL
DEM Benchmark 22: OK!........ Test 22 SUCCESSFUL
DEM Benchmark 23: OK!........ Test 23 SUCCESSFUL
DEM Benchmark 24: OK!........ Test 24 SUCCESSFUL
DEM Benchmark 25: OK!........ Test 25 SUCCESSFUL


===== DISCONTINUUM CLUSTERS TESTS =====

DEM Benchmark 30: OK!........ Test 30 SUCCESSFUL
DEM Benchmark 31: OK!........ Test 31 SUCCESSFUL
DEM Benchmark 14: OK!........ Test 14 SUCCESSFUL
DEM Benchmark 10: OK!........ Test 10 (e=0.50) SUCCESSFUL


==== WENSRICH PAPER TEST. ROLLING FRICTION ====

DEM Benchmark 12: OK!........ Test 12 SUCCESSFUL
DEM Benchmark 16: OK!........ Test 16 SUCCESSFUL
DEM Benchmark 15: OK!........ Test 15 SUCCESSFUL
DEM Benchmark 10: OK!........ Test 10 (e=0.75) SUCCESSFUL
DEM Benchmark 40: OK!........ Test 40_0 SUCCESSFUL (spheres)
DEM Benchmark 40: OK!........ Test 40_1 SUCCESSFUL (spheres)
DEM Benchmark 40: OK!........ Test 40_2 SUCCESSFUL (spheres)
DEM Benchmark 40: OK!........ Test 40_3 SUCCESSFUL (spheres)
DEM Benchmark 40: OK!........ Test 40_4 SUCCESSFUL (spheres)
DEM Benchmark 40: OK!........ Test 40_5 SUCCESSFUL (spheres)
DEM Benchmark 40: OK!........ Test 40_6 SUCCESSFUL (spheres)
DEM Benchmark 40: OK!........ Test 40_7 SUCCESSFUL (spheres)
DEM Benchmark 40: OK!........ Test 40_8 SUCCESSFUL (spheres)
DEM Benchmark 40: OK!........ Test 40_9 SUCCESSFUL (spheres)
DEM Benchmark 40: OK!........ Test 40_10 SUCCESSFUL (spheres)
DEM Benchmark 40: OK!........ Test 40_11 SUCCESSFUL (spheres)
DEM Benchmark 40: OK!........ Test 40_12 SUCCESSFUL (spheres)
DEM Benchmark 40: OK!........ Test 40_13 SUCCESSFUL (spheres)
DEM Benchmark 40: OK!........ Test 40_14 SUCCESSFUL (spheres)
DEM Benchmark 40: OK!........ Test 40_0 SUCCESSFUL (finite elements)
DEM Benchmark 40: OK!........ Test 40_1 SUCCESSFUL (finite elements)
DEM Benchmark 40: OK!........ Test 40_2 SUCCESSFUL (finite elements)
DEM Benchmark 40: OK!........ Test 40_3 SUCCESSFUL (finite elements)
DEM Benchmark 40: OK!........ Test 40_4 SUCCESSFUL (finite elements)
DEM Benchmark 40: OK!........ Test 40_5 SUCCESSFUL (finite elements)
DEM Benchmark 40: OK!........ Test 40_6 SUCCESSFUL (finite elements)
DEM Benchmark 40: OK!........ Test 40_7 SUCCESSFUL (finite elements)
DEM Benchmark 10: OK!........ Test 10 (e=0.90) SUCCESSFUL
DEM Benchmark 32: OK!........ Test 32 SUCCESSFUL
DEM Benchmark 33: OK!........ Test 33 SUCCESSFUL
DEM Benchmark 17: OK!........ Test 17 SUCCESSFUL

**Comment by farrufat-cimne** [comment]
updated with current master.

**Review by maceligueta — APPROVED** [review]

**Pull request merged**
