### PR TITLE
[Core] TEMP commenting Chunk related code

### LINKED ISSUE #7743: Thread safety issue in test_chunk.cpp
**Description**
I have been running kratos tests and I noticed that test_chunk is failing from time to time for different num threads. I get this error message:
Error: Error: Check failed because the_vector[i] is equal to nullptr for i = 98 and repeat = 21
   in: kratos/tests/cpp_tests/sources/test_chunk.cpp:137:virtual void Testing::TestChunkParallelAllocateDeallocate::TestFunction()Exception

**Scope**
- cpp tests

**To Reproduce**
I am running run_tests.py and run_cpp_tests.py. Specially it fails when I set OMP_NUM_THREADS=16. 

**Environment**
- OS: Fedora 7.7
- Branch: master
- Python 3.6

### PR DESCRIPTION
**Pull request by philbucher**
**Description**
There are currently several issues with the Chunk, see #7743 and #7697

@pooyan-dadvand is it ok for you to temp disable this part of the code? As we discussed the `Chunk` anyway needs a bigger rework and we want to have all tests passing for the upcoming release

closes #7743 
required for #7697

### CODE REVIEW

**Comment by pooyan-dadvand** [comment]
I would disable the test rather than commenting on the entire code. There are other tests that are going well and not everything should be refactored.

**Comment by philbucher** [comment]
I commented everything as this also blocks the cleanup of the `LockObject` => #7697

**Comment by pooyan-dadvand** [comment]
I am also aware of #7697 and I think it is the reason that we should not comment the chunk. Simply because if there is an error there we should find out what is the problem and why the chunk is not working rather than commenting it. The usage of the LockObject in the chunk is a valid use and in fact I wrote the LockObject while implementing the chunk. 

I think that the pculiarity of the chunk is its inplace construction in the vector. Maybe, I am doing something wrong there but we should be clear about it before going with the LockObject change without a clear idea.

**Comment by philbucher** [comment]
this is no longer required, a better solution was found in #7697

**Pull request closed without merging**
