### PR TITLE
[Release] Release 9.6

### PR DESCRIPTION
**Pull request by roigcarlo**
**📝 Description**
Bump version and adding new app for the upcoming Release.

### CODE REVIEW

**Review by sunethwarna — DISMISSED** [review]
Thanks @roigcarlo :) minor comment: SIApp at the moment depends on StructApp at runtime. So if possible just change it, otherwise we can keep that small change for the next time.

**Comment by loumalouomega** [comment]
Next release is not 10?

**Comment by rubenzorrilla** [comment]
> Next release is not 10?

I'd also say so...

**Comment by roigcarlo** [comment]
Ok I'll change it

**Pull request closed without merging**
