### PR TITLE
[Meshing] removing old test examples

### PR DESCRIPTION
**Pull request by philbucher**
This PR removes the old test examples in the MeshIngApp => 45MB of files!
I somehow missed them in the cleanup that we did some time ago of the old benchmarking

Those examples would not work bcs they still use the long deleted benchmarking system, also they are ~5 Years old!

### CODE REVIEW

**Comment by loumalouomega** [comment]
Unfortunately I am not responsible for this files @playpaolo and @juliobarna

**Review by loumalouomega — APPROVED** [review]
Ok from my side in any way

**Comment by philbucher** [comment]
related to #4996

**Comment by philbucher** [comment]
I will merge this end of next week unless someone objects

The files can ofc be restored through the history if necessary @playpaolo @juliobarna

**Pull request merged**
