### PR TITLE
Missing cotired KratosMeshingCore

### PR DESCRIPTION
**Pull request by roigcarlo**
This was probably doubling the build time in travis :_D

### CODE REVIEW

**Review by philbucher — APPROVED** [review]
Thanks soo much :D

Btw it doubles the time in appveyor

**Comment by philbucher** [comment]
I cancelled all other builds in appveyor, once this is in I will merge master to the other branches

**Comment by roigcarlo** [comment]
Seems that something is still using KratosCore without cotire....

**Comment by philbucher** [comment]
in appveyor or travis?

**Comment by roigcarlo** [comment]
Travis

**Comment by philbucher** [comment]
didn't you say that that was the tests?

**Comment by roigcarlo** [comment]
no no, tests appear there because are part of the core, but something is still triggering that...

**Comment by loumalouomega** [comment]
I recently added MEshingApp to appveyor, sorry

**Comment by roigcarlo** [comment]
But still travis is compiling the core twice, and I don't get why

**Comment by philbucher** [comment]
> But still travis is compiling the core twice, and I don't get why

this does not happen in appveyor?

**Comment by philbucher** [comment]
now it runs in less than 40min
The influence of this is quite impressive!

**Pull request merged**
