### PR TITLE
[MPI] unittest.main can now work in MPI

### PR DESCRIPTION
**Pull request by philbucher**
`unittest.main` cannot parse the `--using-mpi` argument, hence I remove it and pass the call

### CODE REVIEW

**Comment by philbucher** [comment]
probably better to to import `unittest` without the `*` such that the overriding of `main` is not ambiguous
What do you think?
(at least thats what codacy complains about)

**Comment by jcotela** [comment]
I would agree with cleaning the import of `unittest`, since now it is imported both with relative and absolute import... Possibly the relative import is cleaner, yes.

**Comment by philbucher** [comment]
> I would agree with cleaning the import of `unittest`, since now it is imported both with relative and absolute import... Possibly the relative import is cleaner, yes.

I just tried changing the import but then I would need to import manually EVERY function that is defined in unittest OR change every test

I think neither is a good solution, therefore I would leave both imports. I did some minor cleanup now to make things clearer though

**Comment by jcotela** [comment]
In that case, I would suggest putting the relative import inside the `main` function itself, but it is a minor issue.

**Comment by philbucher** [comment]
> In that case, I would suggest putting the relative import inside the `main` function itself, but it is a minor issue.

done

**Review by jcotela — APPROVED** [review]
:+1: I know it was already like that, but this issue of defining things with the same name as their base class is hard to look at...

**Comment by philbucher** [comment]
> +1 I know it was already like that, but this issue of defining things with the same name as their base class is hard to look at...

but that is still the case, it is not really possible to solve it I think
Unless we import manually every method from `unittest` such that they are available also in `KratosUnittest`

**Pull request merged**
