### PR TITLE
[Core][NR-Strategy] nicer prints

### PR DESCRIPTION
**Pull request by philbucher**
**Description**
Only unifying the prints

### CODE REVIEW

**Review by rubenzorrilla — COMMENTED** [review]
Shouldn't we print the class name `ResidualBasedNewtonRaphsonStrategy` to make it consistent? (even though I'd prefer `NewtonRaphsonStrategy`).

Maybe makes sense to call the `Info()` method, which prints `ResidualBasedNewtonRaphsonStrategy`, within the output macros.

**Comment by philbucher** [comment]
> Shouldn't we print the class name `ResidualBasedNewtonRaphsonStrategy` to make it consistent? (even though I'd prefer `NewtonRaphsonStrategy`).
> 
> Maybe makes sense to call the `Info()` method, which prints `ResidualBasedNewtonRaphsonStrategy`, within the output macros.

I fully agree

**Comment by philbucher** [comment]
I didn't use the `Info` method as this might be used for sth else at some point, it is called `Info` and not `Name` after all

**Comment by rubenzorrilla** [comment]
> I didn't use the `Info` method as this might be used for sth else at some point, it is called `Info` and not `Name` after all

Makes sense. Maybe the `Name` one should print the name of the class...

**Review by rubenzorrilla — APPROVED** [review]

**Pull request merged**
