### PR TITLE
[FSI] py-module

### PR DESCRIPTION
**Pull request by philbucher**
@rubenzorrilla please test it yourself too

### CODE REVIEW

**Comment by rubenzorrilla** [comment]
There were some modules failing in the tests. Should work now. Thanks!!

**Comment by philbucher** [comment]
> There were some modules failing in the tests. Should work now. Thanks!!

Did you have the latest changes?
I also added those imports when I ran the tests

**Comment by philbucher** [comment]
either way, I don't see conflicts, feel free to merge if you like

BTW I updated the gid-mainFSI already some time ago so there you are also on the safe side

**Comment by rubenzorrilla** [comment]
> > There were some modules failing in the tests. Should work now. Thanks!!
> 
> Did you have the latest changes?
> I also added those imports when I ran the tests

It was strange for me as well... Probably the latest changes were not pushed.

**Review by rubenzorrilla — APPROVED** [review]

**Pull request merged**
