### PR TITLE
Separation compressible 2D 3D element

### PR DESCRIPTION
**Pull request by reginadicuori**
Additional Unit tests for 3D element

### CODE REVIEW

**Comment by jcotela** [comment]
I believe that the merge conflicts you got are because of the ublas-related changes (which we recently merged for the FluidDynamicsApplication). Can you follow the procedure in #1931 to update your c++ files and templates?

**Comment by RiccardoRossi** [comment]
Ok this should now be ok. At least it does work on my computer.

still to be seen if 3D works.

I believe that for the onera testcase the problem is that we should start with a solution that is a little closer to the real one than the one we are starting with. 

@inigolcanalejo maybe we could generate one starting solution with the potential solver.

in any case if the compilations succeeds i think we can merge this. It should also fix the compressible warnings

**Comment by philbucher** [comment]
codacy has a lot of complaint

**Comment by RiccardoRossi** [comment]
@philbucher codacy failed in the last run :-(

I think this branch is an advancment since it implements both 2D and 3D AND it resolves some warnings.
My suggestion would be to accept merging, and to iterate on the top of it.

The point is that @reginadicuori has finished her period @CIMNE and will be back @TUM in the next days, so you can directly ask her to do the relevant corrections, so i would like to have this in the master as a solid starting point.

**Comment by philbucher** [comment]
Fine by me , I wasn’t blocking

Just wanted to piont it out :)

**Review by jcotela — DISMISSED** [review]
Approving to get this on the master.

Most of the codacy complaints @philbucher mentioned are in the template files (that is, not in real code).  Maybe we should change the extension of the template files, so that they are not scanned?

**Review by RiccardoRossi — APPROVED** [review]

**Pull request merged**
