### PR TITLE
[Travis] Adding error for unused-but-set-variable

### PR DESCRIPTION
**Pull request by philbucher**
Another easy thing to fix and to prevent potential bugs (#3020)

### CODE REVIEW

**Review by roigcarlo — APPROVED** [review]
Agree :+1: lets see if it returns a clean build as it is right now...

**Comment by philbucher** [comment]
There was a warning but it is fixed in #3022

**Comment by philbucher** [comment]
now it should compile @roigcarlo

**Comment by roigcarlo** [comment]
Nice! (merging with the master do not require re approval)

**Comment by philbucher** [comment]
> Nice! (merging with the master do not require re approval)

awesome!
Since when is this possible?

**Pull request merged**
