### PR TITLE
[CLApp] shortening cl name

### PR DESCRIPTION
**Pull request by ddiezrod**
**📝 Description**
Same as https://github.com/KratosMultiphysics/Kratos/pull/10275

### CODE REVIEW

**Review by AlejandroCornejo — DISMISSED** [review]
ok!

**Comment by ddiezrod** [comment]
I misssed one sorry, it will need reapproval @AlejandroCornejo

**Review by rubenzorrilla — APPROVED** [review]
Approving since @AlejandroCornejo already did.

**Comment by ddiezrod** [comment]
A test from MeshMovingApplication failed, I do not think it is related to the changes here https://github.com/KratosMultiphysics/Kratos/actions/runs/3066273188/jobs/4951259110

**Pull request merged**
