### PR TITLE
[dem] CONTACT_FORCES variable is added to cluster and computed, so it can be printed

### PR DESCRIPTION
**Pull request by maceligueta**
**Description**
@KlausBSautter noted that the code was crashing when trying to print CONTACT_FORCES in the presence of clusters.
Now the variable is added and computed (it receives the value of TOTAL_FORCES before the additional forces have been computed).

### CODE REVIEW

**Comment by philbucher** [comment]
I recommend adding a test so that it doesn't break again in the future :)

**Comment by maceligueta** [comment]
I was actually thinking of how to add a  test to test all variables and not require a lot of time. The test should contain walls, spheres, inlets and clusters, and activate all postprocess variables or just part of them. I will add something to this PR.

**Comment by KlausBSautter** [comment]
thanks @maceligueta for the fast response. I'll check it out tmr

**Review by KlausBSautter — DISMISSED** [review]
thanks, this works for my cases!

**Comment by maceligueta** [comment]
Thanks for testing. Still, I will updload a test to this branch, to prevent future errors.

**Comment by maceligueta** [comment]
The FluidDynamics tests took too long at first, but then I restarted the Checks and everything went fine.

**Review by KlausBSautter — APPROVED** [review]

**Pull request merged**
