### PR TITLE
[Core] cleanup AMGCL disable macro

### PR DESCRIPTION
**Pull request by philbucher**
**Description**
This was introduced in #1360 as a workaround but as we can now exclude files from COTIRE is no longer necessary

### CODE REVIEW

**Review by roigcarlo — APPROVED** [review]
And we also have more ram too :+1:

**Comment by RiccardoRossi** [comment]
well,

i think that the possibility of disabling it if needed is not bad. do we really want to take  it out?

**Comment by philbucher** [comment]
What would be the use?

It is anyway broken, because there are now also cpp files (e.g.: https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/linear_solvers/amgcl_solver_impl.cpp) which would have to be disabled through cmake etc
I.e. maintaining it for no use is IMO not worth it

**Comment by RiccardoRossi** [comment]
ok

**Pull request merged**
