### PR TITLE
Change modelpart init in potential fluid

### PR DESCRIPTION
**Pull request by jginternational**
Potential fluid app was not compiling

### CODE REVIEW

**Review by loumalouomega — APPROVED** [review]
It is related with model.h, so it is OK, don't need to wait for @RiccardoRossi

**Comment by loumalouomega** [comment]
#3157

**Comment by philbucher** [comment]
I am merging this bcs the nightly tests are not compiling bcs of this

**Comment by philbucher** [comment]
thanks @jginternational

**Pull request merged**
