### PR TITLE
[Core] Exposing missing fct of Geometry

### PR DESCRIPTION
**Pull request by philbucher**
Having access to `WorkingSpaceDimension` and `LocalSpaceDimension` can be quite helpful

### CODE REVIEW

**Comment by philbucher** [comment]
ping @KratosMultiphysics/technical-committee 
Related to #2969

**Comment by jcotela** [comment]
@philbucher :+1: for the change, but I'd wait for #2969 before merging.

**Comment by philbucher** [comment]
now that #2969 is merged, can I merge this one too?

**Comment by philbucher** [comment]
since everyone agrees can someone approve pls? :)

**Review by loumalouomega — APPROVED** [review]

**Comment by philbucher** [comment]
thx

**Pull request merged**
