### PR TITLE
[Core] Fix triangle win64 compilation

### PR DESCRIPTION
**Pull request by pooyan-dadvand**
Adding CPU86 only for win32 to avoid assert fail in windows FullDebug

### CODE REVIEW

**Comment by pooyan-dadvand** [comment]
@KratosMultiphysics/technical-committee It would be great to think about having a FullDebug build in windows. The core and almost all of the applications are failing....

**Comment by philbucher** [comment]
> @KratosMultiphysics/technical-committee It would be great to think about having a FullDebug build in windows. The core and almost all of the applications are failing....

compilation or tests?

**Comment by roigcarlo** [comment]
Well, both...

**Review by roigcarlo — APPROVED** [review]

**Comment by philbucher** [comment]
> @KratosMultiphysics/technical-committee It would be great to think about having a FullDebug build in windows. The core and almost all of the applications are failing....

see #6988

**Pull request merged**
