### PR TITLE
[dem] 2D control module starts working. Several bugfixes related to walls in 2D

### PR DESCRIPTION
**Pull request by maceligueta**
The 2D projection of forces and pressures onto walls was not working. That is why the control module was behaving strangely. 
An averaging of the measured reaction has been added to the control module.
This was tested with a radial compression, but should be tested extensively with different geometries and load paths.

### CODE REVIEW

**Comment by ipouplana** [comment]
Thanks @maceligueta ! I am compiling the branch right now.

**Comment by maceligueta** [comment]
It seems like the error in the Ubuntu check is general for all PRs, not related to this one.

**Comment by ipouplana** [comment]
I am running a test example. As soon as I see it works fine, I'll approve.

**Review by ipouplana — APPROVED** [review]
It seems the example is working ok

**Pull request merged**
