### PR TITLE
[StructuralMechanicsApplication] Removing unused exports and unused serializer (static classes)

### PR DESCRIPTION
**Pull request by loumalouomega**
Header files only don't require (and should not have) KRATOS_API aka export

### CODE REVIEW

**Comment by roigcarlo** [comment]
:+1: I still want to know why this is currently compiling... I'let @AlejandroCornejo approve as after he tests it, just to check that we are not breaking anything

**Comment by AlejandroCornejo** [comment]
i'll compile it this afternoon ASAP

**Comment by loumalouomega** [comment]
@AlejandroCornejo does it work?

**Comment by AlejandroCornejo** [comment]
srry I haven't had time to compile it yet...

**Comment by AlejandroCornejo** [comment]
it doesn't compile in windows... @loumalouomega

**Comment by loumalouomega** [comment]
damm

**Comment by loumalouomega** [comment]
any specific error

**Comment by AlejandroCornejo** [comment]
Gravedad	Código	Descripción	Proyecto	Archivo	Línea	Estado suprimido
Error	LNK2001	símbolo externo "public: virtual void __cdecl Kratos::GenericFiniteStrainIsotropicPlasticity<class Kratos::HyperElasticIsotropicKirchhoff3D,class Kratos::GenericFiniteStrainConstitutiveLawIntegratorPlasticity<class Kratos::FiniteStrainVonMisesYieldSurface<class Kratos::FiniteStrainVonMisesPlasticPotential<6> > > >::CalculateMaterialResponsePK1(struct Kratos::ConstitutiveLaw::Parameters &)" (?CalculateMaterialResponsePK1@?$GenericFiniteStrainIsotropicPlasticity@VHyperElasticIsotropicKirchhoff3D@Kratos@@V?$GenericFiniteStrainConstitutiveLawIntegratorPlasticity@V?$FiniteStrainVonMisesYieldSurface@V?$FiniteStrainVonMisesPlasticPotential@$05@Kratos@@@Kratos@@@2@@Kratos@@UEAAXAEAUParameters@ConstitutiveLaw@2@@Z) sin resolver	KratosStructuralMechanicsCore	D:\MasterKratos\cmake_build\applications\StructuralMechanicsApplication\structural_mechanics_application.obj	1	

or

Gravedad	Código	Descripción	Proyecto	Archivo	Línea	Estado suprimido
Error	LNK2001	símbolo externo "public: virtual bool __cdecl Kratos::GenericFiniteStrainIsotropicPlasticity<class Kratos::HyperElasticIsotropicKirchhoff3D,class Kratos::GenericFiniteStrainConstitutiveLawIntegratorPlasticity<class Kratos::FiniteStrainVonMisesYieldSurface<class Kratos::FiniteStrainVonMisesPlasticPotential<6> > > >::Has(class Kratos::Variable<class boost::numeric::ublas::matrix<double,struct boost::numeric::ublas::basic_row_major<unsigned __int64,__int64>,class boost::numeric::ublas::unbounded_array<double,class std::allocator<double> > > > const &)" (?Has@?$GenericFiniteStrainIsotropicPlasticity@VHyperElasticIsotropicKirchhoff3D@Kratos@@V?$GenericFiniteStrainConstitutiveLawIntegratorPlasticity@V?$FiniteStrainVonMisesYieldSurface@V?$FiniteStrainVonMisesPlasticPotential@$05@Kratos@@@Kratos@@@2@@Kratos@@UEAA_NAEBV?$Variable@V?$matrix@NU?$basic_row_major@_K_J@ublas@numeric@boost@@V?$unbounded_array@NV?$allocator@N@std@@@234@@ublas@numeric@boost@@@2@@Z) sin resolver	KratosStructuralMechanicsCore	D:\MasterKratos\cmake_build\applications\StructuralMechanicsApplication\test_plasticity_constitutive_laws_3d.obj	1	


like 1661 times

**Comment by loumalouomega** [comment]
Why can we use clang on windows!!!!!!, using right now my VM to see if I find the error

**Comment by loumalouomega** [comment]
imagen

**Comment by loumalouomega** [comment]
Mine works, are you sure?

**Comment by loumalouomega** [comment]
@AlejandroCornejo can you check again please?

**Comment by AlejandroCornejo** [comment]
@loumalouomega I'll try this afternoon again but...

**Comment by AlejandroCornejo** [comment]
it compiles in my laptop so OK

**Review by AlejandroCornejo — APPROVED** [review]

**Pull request merged**
