### PR TITLE
[Core] Using concurrent queue in GlobalPointerMapCommunicator

### PR DESCRIPTION
**Pull request by sunethwarna**
**Description**
This demonstrates one of the use cases of concurrent queue as explained in #7893.

**Changelog**
- Adds concurrentqueue header only external library
- Updates `GlobalPointerMapCommunicator` to use concurrent queues.

### CODE REVIEW

**Review by RiccardoRossi — DISMISSED** [review]
approving on behalf of @KratosMultiphysics/technical-committee

**Comment by RiccardoRossi** [comment]
@sunethwarna sorry even if i approved please wait because it has not been tested in msvc and intel compilers

**Comment by RiccardoRossi** [comment]
mmm we should add a test for the concurrentqueue implementation alone.

something on the line of 

~~~cpp
#include <vector>
#include <iostream>
#include <chrono>
#include "concurrentqueue/concurrentqueue.h"
#include "omp.h"

int main() {
    
    std::cout << " n threads = " << omp_get_max_threads() << std::endl;    

    std::size_t total_items = 100e6;
    std::size_t nitems = total_items/omp_get_max_threads(); //items per thread
    moodycamel::ConcurrentQueue<std::size_t> q;
    
    std::size_t expected_sum=0;

    auto start = std::chrono::system_clock::now();
    #pragma omp parallel
    {
        std::size_t ithread=omp_get_num_threads();

        #pragma omp atomic
        expected_sum += nitems*ithread;

        for(std::size_t i=0; i<nitems; ++i)
            q.enqueue(ithread);
    }
    auto stop = std::chrono::system_clock::now();
    auto elapsed = std::chrono::duration_cast<std::chrono::milliseconds>(stop - start).count();
    std::cout << "enqueuing time = " << elapsed << std::endl;
    std::cout << "expected sum = " << expected_sum << std::endl;

    start = std::chrono::system_clock::now();
    std::vector<std::size_t> all;
    all.reserve(q.size_approx());
    bool found = true;
    while(found)
    {
        std::size_t item;
        found = q.try_dequeue(item);
        if(found)
            all.push_back(item);
    }
    stop = std::chrono::system_clock::now();
    elapsed = std::chrono::duration_cast<std::chrono::milliseconds>(stop - start).count();
    std::cout << "push_back time = " << elapsed << std::endl;

    std::size_t sum = 0;
    for(auto item : all)
        sum += item;
    std::cout << "obtained sum = " << sum << std::endl;

    assert(sum == expected_sum);

    return 0;
}
~~~
just to have the CI check for parallelism errors due to mixing openmp and other kind of threading

**Comment by philbucher** [comment]
@sunethwarna if you add a test then I can test it with Intel :)

**Comment by sunethwarna** [comment]
I'll try to add a `concurrent_queue` only test :)

**Comment by sunethwarna** [comment]
@RiccardoRossi @philbucher I added a simple test. Could you have a look?

**Review by RiccardoRossi — APPROVED** [review]
thx @sunethwarna

**Comment by sunethwarna** [comment]
I accidently merged this, can some one please check this with MSVC? @roigcarlo ?

**Comment by philbucher** [comment]
> I accidently merged this, can some one please check this with MSVC? @roigcarlo ?

It exists!!!
The legendary „accidental merge“ exists 😂😂😂

**Comment by RiccardoRossi** [comment]
It is checked in the CI.

that is actually the point of asking you to make the test

**Pull request merged**
