### PR TITLE
Application Template/Fix spelling

### PR DESCRIPTION
**Pull request by oberbichler**

### CODE REVIEW

**Comment by msandre** [comment]
+1 for getting rid of Assamble in kratos. There are around a dozen applications which have copies of this typo. Can we update these in this PR as well?

**Review by roigcarlo — DISMISSED** [review]
:+1: Also for the typo.

**Comment by roigcarlo** [comment]
Yep it is safe here, that file is not being touched that much so it should not cause problems

**Comment by oberbichler** [comment]
image

I think that should do the job

**Review by msandre — APPROVED** [review]

**Pull request merged**
