### PR TITLE
Core/expose build type to python

### PR DESCRIPTION
**Pull request by jcotela**
This allows us to check the value of the `KRATOS_BUILD_TYPE` macro from python. The feature was suggested by @oberbichler, who would use it to do some python test checks differently if kratos is/is not compiled in debug mode.

Things I do not like:
- The variable is exported as a module attribute, so it can be changed by the user at runtime. I was not able to find a way to make module (not class!) attributes read-only, so if someone knows a way, I'll happily use it.
- I had to add some macro magic to print the value of the `KRATOS_BUILD_TYPE` macro as a string, since we do not currently define it as a C string in kratos_version.h.

@KratosMultiphysics/technical-committee: do you see any inconvenient to using, for example,
```C++
#define KRATOS_BUILD_TYPE "Release"
```
instead of the current (not a string)
```C++
#define KRATOS_BUILD_TYPE Release
```

The only other place where this macro is used now is in the DEM application, and they have to use the same macro trick to turn it into a string.

### CODE REVIEW

**Comment by roigcarlo** [comment]
As far as I know that is not even used (the one printed in screen in `kratos_version.h` is directly added as a part of the `KRATOS_VERSION` macro), so I see no problem in changing it to a string.

**Comment by jcotela** [comment]
@roigcarlo in that case, if no-one objects, I'll change KRATOS_BUILD_TYPE to a string as part of this PR.

**Comment by msandre** [comment]
I'm just wondering if the macro KRATOS_VERSION should be part of the Kernel both in python and c++ since it is already part of the c++ class implementation. In python it could either be the __doc__ string or a readonly property or returned by Info().

**Comment by jcotela** [comment]
@msandre readonly property would be the best option in my opinion, since it can be cleanly queried at runtime from the python script. I did not initially go for adding this to the kernel because I did not want to modify it unilaterally but, if everyone agrees, this could be the way to go.

**Comment by oberbichler** [comment]
For the readonly property solution we would need a class (e.g. `KratosInfo.Version`). AFAIK python has no readonly attributes(?)

I think storing it as an default attribute is fine.

Btw I would try to use less macros in Kratos

**Comment by pooyan-dadvand** [comment]
What about adding `Version` and `BuildType` to the `Kernel` class as static methods?

**Review by pooyan-dadvand — APPROVED** [review]
👍

**Comment by pooyan-dadvand** [comment]
Can the bridge be deleted?

**Pull request merged**
