### PR TITLE
[Core] fixing compilation Intel

### PR DESCRIPTION
**Pull request by philbucher**
Now it compiles
Will run the tests once it finishes

No clue if this change is ok though / no clue what it changes

related to #4757

### CODE REVIEW

**Review by RiccardoRossi — APPROVED** [review]
this looks ok to me...

**Comment by philbucher** [comment]
@rubenzorrilla could you please check if this compiles with CLANG 3.8?

**Comment by philbucher** [comment]
tests seem to work

**Comment by philbucher** [comment]
ping @rubenzorrilla @roigcarlo should I merge or do you also want to test it?

**Comment by roigcarlo** [comment]
Good to me

**Comment by rubenzorrilla** [comment]
Good to me as well.

**Comment by RiccardoRossi** [comment]
go ahead

**Pull request merged**
