### PR TITLE
Tests StructrualMechanics Cleanup und small fixes

### PR DESCRIPTION
**Pull request by philbucher**
Hi @KratosMultiphysics/structural-mechanics 
I found some small mistakes in the tests and did also some cleanup.

I also used the opportunity to remove the necessity of having to add the tests twice, bcs ofc there were some tests forgotten. Now it is done nice and clean, same as in the FluidDynamicsApp

@KlausBSautter I added the patch tests for the truss and the beam, they were not added

@adityaghantasala the mpc test is failing, but now bcs you add the variables after adding the nodes, which can create bad segfaults, see #492. I coulnd't fix it on the fly, can you please have a look?

Other than that I didn't change anything

### CODE REVIEW

**Comment by RiccardoRossi** [comment]
hi philip,  i will take a look tokorrow. however, don t you fet the expected error message after my fix?

**Comment by philbucher** [comment]
Hi Riccardo,
I do get the error message, so your solution works correct. 
The thing is that the test is set up in a wrong way, first nodes and elements are added and then the variables

**Review by loumalouomega — APPROVED** [review]

**Comment by philbucher** [comment]
mpc test is fixed in #972

**Review by RiccardoRossi — APPROVED** [review]
looks nice to me too.

**Pull request merged**
