### PR TITLE
[CMake][TrilinosApplication][MPI] Allow to compile MPI without Trilinos

### PR DESCRIPTION
**Pull request by loumalouomega**
**📝 Description**

Allow to compile MPI without Trilinos. Due to recent change (mine) it fails if compiling MPI without Trilinos.

**🆕 Changelog**

- [Allow to compile MPI without Trilinos](https://github.com/KratosMultiphysics/Kratos/commit/c0c12f38b134f735a4f8cd96374c77023149d699)

### CODE REVIEW

**Comment by loumalouomega** [comment]
@rubenzorrilla this is a good opportunity to reduce verbosity in FindTrilinos if needed

**Comment by philbucher** [comment]
Hm the intel CI compiles MPI but without Trilinos

what exactly is the problem?

**Comment by loumalouomega** [comment]
> Hm the intel CI compiles MPI but without Trilinos
> 
> what exactly is the problem?

Maybe depends on the CMake version, in my machine the FATAL_ERROR is triggered

**Comment by loumalouomega** [comment]
Any approval?

**Review by roigcarlo — APPROVED** [review]

**Comment by roigcarlo** [comment]
I also did not get any error. My guess is that there is some extension that is activating the use of Trilinos. That happened with the Fluid and the structural some time ago.

Nevertheless, the change does not hurt, so :+1:

**Pull request merged**
