### PR TITLE
9981 update the admin of the geomechanicsapplication ie codeownersconfigure files

### LINKED ISSUE #9981: [GeoMechanicsApplication] Update the Admin of the GeoMechanicsApplication. (i.e. CODEOWNERS/Configure files)
Add the administration to the GeoMechanicsApplication to run the automated testing correctly and the administration of review\acceptance for pull requests.

Update - Configure.sh/cmd and CODEOWNERS

### PR DESCRIPTION
**Pull request by mcgicjn2**
**📝 Description**
Adding the test and ownership admistration for the GeoMechanicsApplication to the workflow and Github files.

**Tags**
- GeoMechanicsApplication

**🆕 Changelog**
- Updated the CODEOWNERS File - Added the GeoMechanics Team from Github
- Updated the workflow configuration files - Added Geomechanics Application to build (and automated testing)

### CODE REVIEW

**Comment by mcgicjn2** [comment]
**Failing tests**

ERROR: test_interface_on_beam (test_interface.KratosGeoMechanicsInterfaceTests)
----------------------------------------------------------------------
======================================================================
ERROR: test_interface_side_cohesive (test_interface.KratosGeoMechanicsInterfaceTests)
----------------------------------------------------------------------
======================================================================
ERROR: test_weak_interface_on_beam (test_interface.KratosGeoMechanicsInterfaceTests)
----------------------------------------------------------------------
======================================================================
ERROR: test_normal_load_quad_8n (test_water_pressure.KratosGeoMechanicsWaterPressureTests)
----------------------------------------------------------------------
======================================================================
ERROR: test_normal_load_tetra_10n (test_water_pressure.KratosGeoMechanicsWaterPressureTests)
----------------------------------------------------------------------
======================================================================
ERROR: test_normal_load_triangle_6n (test_water_pressure.KratosGeoMechanicsWaterPressureTests)
----------------------------------------------------------------------
======================================================================
ERROR: test_benchmark2_1 (test_benchmark_set_2.KratosGeoMechanicsBenchmarkSet2)
----------------------------------------------------------------------
======================================================================
ERROR: test_benchmark2_2 (test_benchmark_set_2.KratosGeoMechanicsBenchmarkSet2)
----------------------------------------------------------------------

**Comment by mcgicjn2** [comment]
The tests in this workflow for windows show only 4 tests failing, and these tests are : 

======================================================================
ERROR: test_interface_on_beam (test_interface.KratosGeoMechanicsInterfaceTests)
----------------------------------------------------------------------
======================================================================
ERROR: test_interface_side_cohesive (test_interface.KratosGeoMechanicsInterfaceTests)
----------------------------------------------------------------------
======================================================================
ERROR: test_weak_interface_on_beam (test_interface.KratosGeoMechanicsInterfaceTests)
----------------------------------------------------------------------
======================================================================
ERROR: test_reset_displacement_truss (test_reset_displacement.KratosGeoMechanicsResetDisplacementTests)
----------------------------------------------------------------------

They seem to have a problem with indexing, @EleniSmyrniou @aronnoordam Lets revisit each one and see if we can see the problem, for now I will place those tests on ignore.

**Comment by roigcarlo** [comment]
@mcgicjn2 Aside from the DLL, seems that there is a problem with some element override methods.

I think that the problem is caused because the inheritance of the `transient_Pw_element.hpp` does not fully propagate the overloads of the `CalculateOnIntegrationPoints`. I think the solution is as easy as extending the overloads of `U_Pw_base_element` with `array_1d<double,3>`

**Comment by mcgicjn2** [comment]
@roigcarlo Hi Charlie, having trouble recreating the issues with the ubuntu build and a clang script. Can you help point me in the directoion of the setup needed to build/test the clang builds using the docker images and scripts? Cheers Jon

**Comment by roigcarlo** [comment]
Hi @mcgicjn2, sorry no to answer sooner, I was on vacations.

to reproduce this you have to add the `-DCMAKE_UNITY_BUILD=ON` flag.

The problem is because our usage of unitary builds in CI. In order to speed up the compilation we merge the source and create single compilation units (all_code.cpp -o app instrad of code1.cpp, code2.cpp, ... codeN.cpp -o app).

This practice is normally safe, but there are corner cases like the use of explicit instantiations where it can be problematic as it may case some headers to be included before the sources containing the specialization of a given template are processed.

Usually our solution is just to exclude the problem files and compile them separately, since geo is not heavy it should not represent an increment in the compilation time anyway.

For what I can see I think its enough just adding a couple of files to the exclusion list:

```CMake
if(CMAKE_UNITY_BUILD MATCHES ON)
    set_source_files_properties (${CMAKE_CURRENT_SOURCE_DIR}/custom_elements/U_Pw_small_strain_element.cpp PROPERTIES SKIP_UNITY_BUILD_INCLUSION TRUE)
    set_source_files_properties (${CMAKE_CURRENT_SOURCE_DIR}/custom_elements/U_Pw_small_strain_FIC_element.cpp PROPERTIES SKIP_UNITY_BUILD_INCLUSION TRUE)
    set_source_files_properties (${CMAKE_CURRENT_SOURCE_DIR}/custom_elements/geo_truss_element_base.cpp PROPERTIES SKIP_UNITY_BUILD_INCLUSION TRUE)
    set_source_files_properties (${CMAKE_CURRENT_SOURCE_DIR}/custom_elements/geo_cable_element_base.cpp PROPERTIES SKIP_UNITY_BUILD_INCLUSION TRUE)
endif(CMAKE_UNITY_BUILD MATCHES ON)
```

If it still does not work ping me and I will have it fixed.

**Comment by roigcarlo** [comment]
Perfect!

**Review by roigcarlo — APPROVED** [review]
I don't see anything wrong, GJ!

**Pull request merged**
