### PR TITLE
[StructuralMechanicsApplication] Hotfix convergence criteria

### PR DESCRIPTION
**Pull request by RiccardoRossi**
Fixes #553

i did this in a hurry, so @KlausBSautter please take the time of checking a little more carefully if this works. Please note that one of the tests is failing, my guess that because of a tolerance issue.

I am leaving on trip now, so if modifications are needed please go ahead (i will not be able to make them... and once accepted this should go in for the release too)

~~~
======================================================================
FAIL: test_execution (structural_mechanics_test_factory_mpi.ShellT3AndQ4LinearStaticStructPinchedCylinderTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/riccardo/Kratos/applications/StructuralMechanicsApplication/tests/structural_mechanics_test_factory.py", line 55, in test_execution
    self.test.RunSolutionLoop()
  File "/home/riccardo/Kratos/kratos/python_scripts/analysis_stage.py", line 66, in RunSolutionLoop
    self.FinalizeSolutionStep()
  File "/home/riccardo/Kratos/kratos/python_scripts/analysis_stage.py", line 141, in FinalizeSolutionStep
    process.ExecuteFinalizeSolutionStep()
  File "/home/riccardo/Kratos/kratos/python_scripts/from_json_check_result_process.py", line 126, in ExecuteFinalizeSolutionStep
    self.assertTrue(isclosethis, msg=(str(value) + " != " + str(value_json) + ", rel_tol = " + str(reltol) + ", abs_tol = " + str(tol) + " : Error checking node " + str(node.Id) + " " + variable_name + " results."))
AssertionError: False is not true : -1.1499871897079825e-05 != -1.1642426393641229e-05, rel_tol = 1e-12, abs_tol = 1e-09 : Error checking node 24 DISPLACEMENT_Z results.

----------------------------------------------------------------------
Ran 1 test in 3.270s
~~~

aside of this and looking into the tests i see for example the following

~~~
test_execution (structural_mechanics_test_factory.Simple3D2NTrussNonLinearSnapthroughPlasticTest) ... ResidualBasedBlockBuilderAndSolver: ATTENTION! setting the RHS to zero!
::[MechanicalSolver]::  Solver did not converge for step 5
corresponding to time 2.5
: 
::[MechanicalSolver]::  Solver did not converge for step 9
corresponding to time 4.5
: 
ResidualBasedBlockBuilderAndSolver: ATTENTION! setting the RHS to zero!
ResidualBasedBlockBuilderAndSolver: ATTENTION! setting the RHS to zero!
ResidualBasedBlockBuilderAndSolver: ATTENTION! setting the RHS to zero!
::[MechanicalSolver]::  Solver did not converge for step 34
corresponding to time 17.0
: 
::[MechanicalSolver]::  Solver did not converge for step 39
corresponding to time 19.5
: 
::[MechanicalSolver]::  Solver did not converge for step 40
corresponding to time 20.0
: 
::[MechanicalSolver]::  Solver did not converge for step 43
corresponding to time 21.5
: 
::[MechanicalSolver]::  Solver did not converge for step 44
corresponding to time 22.0
: 
::[MechanicalSolver]::  Solver did not converge for step 45
corresponding to time 22.5
: 
::[MechanicalSolver]::  Solver did not converge for step 47
corresponding to time 23.5
: 
ResidualBasedBlockBuilderAndSolver: ATTENTION! setting the RHS to zero!
::[MechanicalSolver]::  Solver did not converge for step 58
corresponding to time 29.0
: 
ResidualBasedBlockBuilderAndSolver: ATTENTION! setting the RHS to zero!
::[MechanicalSolver]::  Solver did not converge for step 71
corresponding to time 35.5
: 
ok **
~~~
<--- HOW CAN THIS BE OK IF WE DO NOT GET CONVRGENCE!!!!???**

### CODE REVIEW

**Comment by philbucher** [comment]
Man how could we ovesee this :)

It is really time that I finish the general conv-crit !

Regarding the tests, until I added the warning it was not noticed that they don’t converge

**Comment by KlausBSautter** [comment]
> <--- HOW CAN THIS BE OK IF WE DO NOT GET CONVRGENCE!!!!???**

this should be ok as the tolerance is really small `1e-14`, when I set it to `1e-12` it does convergence . Should I update this?

**Comment by RiccardoRossi** [comment]
@philbucher i did not notice that you had this residual_criterion in the StructuralMechanics. I should have updted it ... my bad

@KlausBSautter ok for setting the tolerance at 1e-12.

also in the longer term we should take the time to do something equivalent to what is done here

https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/solving_strategies/convergencecriterias/residual_criteria.h#L240

since otherwise we will never get convergence by this criteria when MPCs are used.
This is however a larger change and i really did not have the time to change it...

**Comment by loumalouomega** [comment]
Sorry I didn't remember I did an uncoupled convergence check. We will update to the core residual criteria features.

**Review by loumalouomega — APPROVED** [review]
Thanks

**Comment by philbucher** [comment]
To me the changes look fine.

In any case first thing I will do after the workshop is to finish the general conv-crit, then we will not have those problems in the future.
It is general in the sense that it can handle the separation of variables, i.e. check the convergence for DISPLACEMENT/ROTATION or VELOCITY/PRESSURE separately

**Comment by loumalouomega** [comment]
We should merge this to the Release too.

**Comment by philbucher** [comment]
@roigcarlo

**Comment by philbucher** [comment]
this crashes some shell tests in FullDebug
They still work in release

**Comment by loumalouomega** [comment]
> this crashes some shell tests in FullDebug
> They still work in release

Why?, exact error?

**Comment by philbucher** [comment]
I am checking the reactions and the values are now different in Release and FullDebug
No clue though why

**Comment by philbucher** [comment]
I checked, these tests are the only shell tests that check the reactions
The error could be anywhere :D :+1:

**Pull request merged**
