### PR TITLE
[Contact] add dependency on StructuralMechanics in CMake

### PR DESCRIPTION
**Pull request by philbucher**
Contact links against StructuralMechanics, hence it cannot be used without

### CODE REVIEW

**Comment by loumalouomega** [comment]
You cannot use contact without structural...

**Comment by loumalouomega** [comment]
> Contact links against StructuralMechanics, hence it cannot be used without

What are you trying to do without the structural?

**Comment by philbucher** [comment]
Checking #6569

**Comment by loumalouomega** [comment]
> Checking #6569

**Review by loumalouomega — APPROVED** [review]

**Pull request merged**
