### PR TITLE
contact and solid update to match interface

### PR DESCRIPTION
**Pull request by josep-m-carbonell**
some corrections in the GetVariables for the python scripts, and others concerning to pfem meshing for contact. Update to match with the GiD interface. Set tetgen 1.5.0 as default external module.

### CODE REVIEW

**Review by RiccardoRossi — DISMISSED** [review]
this only affects your own branches and compiles on my computer, so i accept.

however, please bear in mind that i did not do a proper code review

**Comment by josep-m-carbonell** [comment]
Thank you Riccardo. However I will wait for @lluis-mv to take a look on changes, to not break anything.

**Review by lluis-mv — DISMISSED** [review]
I took a look on the code and run a couple tests and everything looks OK.

However, I merged this branch with a branch we are working with Pedro and I am having a segmentation fault when I apply restart. I am not sure why, but I think you may merge it, since in we did not merged our branch with the master since long time ago.

**Comment by lluis-mv** [comment]
I found the problem. Dynamic matrices are not initialized in the scheme if a restart is applied. I wil try to solve it ASAP

**Comment by lluis-mv** [comment]
Hi @josep-m-carbonell ,
I introduced some changes. Now, in the case of a restart, "dynamic" matrices and vectors in the scheme (i.e. the mass matrix,....) are allocated in the Check. 
[The time integration method is also set there, since in the no-restart case they are created at the Initialize].
This solves my problem, but I do not know if it is the correct way to do it.

**Comment by josep-m-carbonell** [comment]
Hi @lluis-mv, it is not a good way to solve the problem, Check is a method for checking things not for initializing something in particular cases. Have you tried to call initialize of the scheme after the restart?, just releasing the if clause in the  solid_mechanics_solver.py. It must work.

**Comment by lluis-mv** [comment]
hi,
I think this time I did it correctly: in the solid_mechanics_solver.py  the Scheme is initialized.

**Review by lluis-mv — APPROVED** [review]

**Pull request merged**
