### PR TITLE
[Core] cleanup json check process

### PR DESCRIPTION
**Pull request by philbucher**
this PR cleans and unifies the way the values are checked, to reduce code duplication

Tests in the Main-Apps are working

This is a cleanup before some minor enhancement to make it useable also for MPI testing

### CODE REVIEW

**Review by loumalouomega — DISMISSED** [review]
Thanks, I am planning anyway to migrate this to C++, I think in certain way reduce the performance of the tests

**Comment by philbucher** [comment]
> Thanks, I am planning anyway to migrate this to C++, I think in certain way reduce the performance of the tests

I guess we first need #3673 for this

**Comment by philbucher** [comment]
can you reapprove pls?
I added a minor correction

**Review by loumalouomega — APPROVED** [review]

**Comment by loumalouomega** [comment]
> > Thanks, I am planning anyway to migrate this to C++, I think in certain way reduce the performance of the tests
> 
> I guess we first need #3673 for this

Not in the short term

**Pull request merged**
