### PR TITLE
[Core] Moving all core cpp_test to one folder

### PR DESCRIPTION
**Pull request by loumalouomega**
This simplifies the tests folder, which is currently bloated of many files and is confusing to find anything

My idea is to move the auxiliary files for the python tests to a common folder (so the tests in the parent tests folder are only tests )

### CODE REVIEW

**Comment by loumalouomega** [comment]
@roigcarlo We should decide about this, or basically a conflict will appear everyday

**Comment by roigcarlo** [comment]
I cannot speak for the whole @KratosMultiphysics/technical-committee. 
I really do not care where the cpp are, but I see it usefull to separate them from the py, so ok for me...

**Comment by pooyan-dadvand** [comment]
@loumalouomega would you please put an image of folder structure you are proposing?

**Comment by loumalouomega** [comment]
Current:
imagen
Proposed:
imagen

This is the combination of this PR and #3380

**Comment by loumalouomega** [comment]
The folder processes_test_files will not be there, there are some .time files that keep the folder

**Comment by philbucher** [comment]
Thanks @loumalouomega , this looks very good!
It was getting messy...

**Comment by loumalouomega** [comment]
I know, and it could get even worse

**Comment by loumalouomega** [comment]
I just realized there is a utilities folder, probably a new test added

**Comment by pooyan-dadvand** [comment]
Why we are not doing the same with the python tests?

**Comment by loumalouomega** [comment]
I do in #3380

**Comment by pooyan-dadvand** [comment]
What are the aux files?

**Comment by loumalouomega** [comment]
The aux files are for the python tests

**Comment by loumalouomega** [comment]
I combined two branches to how the final strcuture

**Comment by loumalouomega** [comment]
Can we merge this before more conflicts arrise?

**Comment by pooyan-dadvand** [comment]
Personally I don't like this redistribution:
- If we want to have test_cpp, IMO we should also have test_python
- aux_files gives a very incomplete image of what goes there.... and encourages the developers to  put several auxiliary files there... This goes against the unit-testing philosophy that tests should be self contained. 
- There are many files that can go directly into the test cpps at the end of the file and some of them are just too big and should be avoided....

Meanwhile, this was my opinion.... I am open to other opinions...

**Comment by loumalouomega** [comment]
Well, in particular this PR only moves the cpp tests to one folder, the python tests are moved in a different PR (#3380), we can merge this and think how to deal with the python test later

**Comment by pooyan-dadvand** [comment]
Forwarding to @KratosMultiphysics/implementation-committee

**Comment by loumalouomega** [comment]
I cannot approve myself :P

**Comment by loumalouomega** [comment]
I solved the conflict. @KratosMultiphysics/implementation-committee  I vote in favour of accepting this

**Comment by adityaghantasala** [comment]
@loumalouomega  is the screen shot you posted still actual ? I see that `utilities` is left outside the `cpp_tests ` is this intended ? There are only cpp tests in that folder !

**Comment by loumalouomega** [comment]
No, it is not, it was just conceptual. The python files are in a different
PR

**Comment by loumalouomega** [comment]
@adityaghantasala 

With current branch:

imagen


Without:

imagen

It will be fine if @KratosMultiphysics/implementation-committee can reach an agreement, because everytime a cpp test is modified in the core I need to patch this PR

**Comment by adityaghantasala** [comment]
@loumalouomega  looks good I agree with the changes. Together with the other PR for the python tests, this will make the tests folder more organized. I have some more ideas which we can discuss (putting the reference results and mpda in corresponding folders, using a similar structure in the applications too ... ) ... !

**Comment by loumalouomega** [comment]
> @loumalouomega looks good I agree with the changes. Together with the other PR for the python tests, this will make the tests folder more organized. I have some more ideas which we can discuss (putting the reference results and mpda in corresponding folders, using a similar structure in the applications too ... ) ... !

Agreed, step by step

**Comment by loumalouomega** [comment]
Can we proceed @KratosMultiphysics/implementation-committee

**Comment by GuillermoCasas** [comment]
Well, I do not particularly like the idea of splitting tests into different folders, perhaps in line with what was pointed out by @pooyan-dadvand above. Could we not instead keep all necessary files in individual folders, more like one would have with different cases in normal Kratos use. Is that not possible/desirable?

**Comment by loumalouomega** [comment]
> Well, I do not particularly like the idea of splitting tests into different folders, perhaps in line with what was pointed out by @pooyan-dadvand above. Could we not instead keep all necessary files in individual folders, more like one would have with different cases in normal Kratos use. Is that not possible/desirable?

Yes, but @pooyan-dadvand was referring to the python tests, that is a different PR and I agree with him that a better system should be agreed. This PR just moves the C++ tests to a common folder in the same way is done in the applications in order to reduce confusion with the folders of the python tests (the CMakeLists looks recursively for the source files in the tests folder, so there is not problem with that)

**Comment by GuillermoCasas** [comment]
@loumalouomega Oh, yes, I see. I have no problems with this :)

**Comment by loumalouomega** [comment]
Ok, so can we merge this before more conflicts arise?

**Comment by loumalouomega** [comment]
I will fix a new conflict, but after that I will ask for approval if in principle we are OK. These conflicts are not automatic because the GitHub doesn't find the old files

**Comment by loumalouomega** [comment]
I hope this is the last conflict

**Comment by loumalouomega** [comment]
Oh no, not again!!!

**Comment by loumalouomega** [comment]
Solved again

**Comment by RiccardoRossi** [comment]
I am blocking until a reccomendation is reached by the @KratosMultiphysics/implementation-committee  and the @KratosMultiphysics/technical-committee gives the final approval

**Review by RiccardoRossi — DISMISSED** [review]
blocking while waiting for reccomendation

**Comment by loumalouomega** [comment]
@RiccardoRossi I think that the whole @KratosMultiphysics/implementation-committee committee agrees, there were some points to explain, that I already adressed

**Review by AlejandroCornejo — APPROVED** [review]
approved by the implementation committee

**Comment by philbucher** [comment]
:tada:

**Comment by roigcarlo** [comment]
@KratosMultiphysics/implementation-committee Please this first weeks, do not automatically merge when you reach a conclusion, just add the issue at our project so we are aware it is solved and we will merge.

We would like to see how things evolve during the first weeks

**Comment by loumalouomega** [comment]
OK

**Comment by pooyan-dadvand** [comment]
@KratosMultiphysics/technical-committee does not encourage such a fast merge in this kind of changes

Reorganization of the the code directories creates a lot of conflicts in open branches in which many developers would be affected. So, even in this case where the changes are not affecting the behavior or API, it affects many developers and we would have given more weight to this aspect in the final decision.

**Pull request merged**
