### PR TITLE
[Structural] correcting criterion

### PR DESCRIPTION
**Pull request by philbucher**
no wonder we always had problems with this one -,-

I don't think this is used in any test

### CODE REVIEW

**Review by loumalouomega — DISMISSED** [review]
Ups

**Comment by philbucher** [comment]
ok it is being used in some tests, will update the tests later

**Review by RiccardoRossi — COMMENTED** [review]
ouch, this hurts.

I would approve but i am not using this systematically, so i would prefer someone else to give the ok

**Comment by philbucher** [comment]
we used/tries this often but it never really worked
some ppl here are trying right now

**Comment by mpentek** [comment]
Yes, we tested it. It seems to be working fine and delivering the same results as the residual criterion.

**Comment by philbucher** [comment]
tests are fixed, can someone approve pls?

**Review by KlausBSautter — APPROVED** [review]

**Pull request merged**
