### PR TITLE
Adding #include "includes/model_part.h"

### LINKED ISSUE #2240: Release branch does not compile when building testing
As the title says, I get the following error:
~~~
In file included from /home/philippb/software/Kratos_Master/kratos/tests/processes/test_replace_elements_and_condition_process.cpp:23:0:
/home/philippb/software/Kratos_Master/kratos/processes/replace_elements_and_condition_process.h: In constructor ‘Kratos::ReplaceElementsAndConditionsProcess::ReplaceElementsAndConditionsProcess(Kratos::ModelPart&, Kratos::Parameters)’:
/home/philippb/software/Kratos_Master/kratos/processes/replace_elements_and_condition_process.h:73:32: error: ‘Element’ was not declared in this scope
         if( !KratosComponents< Element >::Has( Settings["element_name"].GetString() ) )
                                ^
/home/philippb/software/Kratos_Master/kratos/processes/replace_elements_and_condition_process.h:73:40: error: template argument 1 is invalid
         if( !KratosComponents< Element >::Has( Settings["element_name"].GetString() ) )
                                        ^
/home/philippb/software/Kratos_Master/kratos/processes/replace_elements_and_condition_process.h:75:32: error: ‘Condition’ was not declared in this scope
         if( !KratosComponents< Condition >::Has( Settings["condition_name"].GetString() ) )
                                ^
/home/philippb/software/Kratos_Master/kratos/processes/replace_elements_and_condition_process.h:75:42: error: template argument 1 is invalid
         if( !KratosComponents< Condition >::Has( Settings["condition_name"].GetString() ) )
                                          ^
/home/philippb/software/Kratos_Master/kratos/processes/replace_elements_and_condition_process.h: In member function ‘virtual void Kratos::ReplaceElementsAndConditionsProcess::Execute()’:
/home/philippb/software/Kratos_Master/kratos/processes/replace_elements_and_condition_process.h:114:15: error: ‘Element’ does not name a type
         const Element& rReferenceElement = KratosComponents<Element>::Get(mSettings["element_name"].GetString());
               ^
/home/philippb/software/Kratos_Master/kratos/processes/replace_elements_and_condition_process.h:115:15: error: ‘Condition’ does not name a type
         const Condition& rReferenceCondition = KratosComponents<Condition>::Get(mSettings["condition_name"].GetString());
               ^
/home/philippb/software/Kratos_Master/kratos/processes/replace_elements_and_condition_process.h:118:47: error: invalid use of incomplete type ‘class Kratos::ModelPart’
         for(int i=0; i< (int)r_root_model_part.Elements().size(); i++)

etc ...
~~~

It compiles if I set build_testing to off

It seems like the process is not including `model_part.h`, which then for some reason only does not work if the testing is built.
Maybe it finds it somehow when it is exposed to python through the other files, but not sure

### PR DESCRIPTION
**Pull request by loumalouomega**
fixes #2240

### CODE REVIEW

**Review by philbucher — COMMENTED** [review]
I check once more before approving if this really solves the issue

**Comment by loumalouomega** [comment]
OK

**Review by philbucher — APPROVED** [review]
now it works

This is for the release, how do we proceed with master?
Will you still merge your cleanup? Then this branch wont have to be merged to master?

**Review by RiccardoRossi — APPROVED** [review]

**Comment by loumalouomega** [comment]
This process is already changed in the master. Look https://github.com/KratosMultiphysics/Kratos/pull/2221

**Comment by roigcarlo** [comment]
@loumalouomega Please ping me in every Release PR or at least add it to the milestone...

**Comment by loumalouomega** [comment]
Ping @roigcarlo

**Comment by loumalouomega** [comment]
Ping @roigcarlo

**Pull request merged**
