### PR TITLE
SumAll MinAll and MaxAll communicator functions exported to Python

### PR DESCRIPTION
**Pull request by rubenzorrilla**

### CODE REVIEW

**Comment by jcotela** [comment]
I am wiling to approve the review, but I want to see @pooyan-dadvand's opinion too.

**Review by pooyan-dadvand — APPROVED** [review]
👍

**Comment by pooyan-dadvand** [comment]
Meanwhile we should find a better place for this kind of communications that are not model part dependent.

**Review by jcotela — APPROVED** [review]
👍

**Pull request merged**
