### PR TITLE
Nurbs geometry kernel

### PR DESCRIPTION
**Pull request by oberbichler**
A simple Nurbs geometry kernel for the IGA/BRep applications.

Adding as a submodule OK? It would be perfect because I use the same library in other projects.

### CODE REVIEW

**Comment by loumalouomega** [comment]
Where is the licence defined?

**Comment by oberbichler** [comment]
It's my code... I can add MIT

**Comment by loumalouomega** [comment]
Even if it is your code I recommend to define the licence in the repository and in every file (or mentioning the licence used as we do), it is just a good practice to avoid conflicts in the future

Very nice work :+1:

**Comment by loumalouomega** [comment]
Well apparently by default GitHub protects with copyright everything:

Code without an explicit license is protected by copyright and is by default All Rights Reserved. The person or people who wrote the code are protected as such. Any time you're using software you didn't write, licensing should be considered and abided.

https://www.infoworld.com/article/2615869/open-source-software/github-needs-to-take-open-source-seriously.html

I thought I was licenseless if not defined

**Comment by oberbichler** [comment]
Thank you!

I just want my name mentioned. I think MIT would do the job. But I can also use the KRATOS licence if that makes things easier.

BTW: I add an use-case-example in #2463

**Comment by loumalouomega** [comment]
MIT is compatible with BSD, so no problem with MIT

**Comment by pooyan-dadvand** [comment]
Adding a new dependency to the core should be approved by @KratosMultiphysics/technical-committee 

Meanwhile, I will take a look to your library.

**Comment by philbucher** [comment]
is this branch still needed?

**Pull request closed without merging**
