### PR TITLE
Feature removing deprecated processes

### PR DESCRIPTION
**Pull request by rubenzorrilla**
This PR removes the deprecated processes. The deprecated processes are all the apply_* and impose_* processes:

- apply_constant_value_process.py
- apply_custom_function_process.py
- apply_variable_value_process.py
- impose_scalar_value_process.py
- impose_vector_value_by_components_process.py
- impose_vector_value_by_direction_process.py

Furthermore, the ExecuteBeforeSolutionLoop(), which calls the ExecuteInitializeSolutionStep(), has been added to the three core main processes. The purpose of this addition is to allow the main processes to be used in the application of initial conditions (when the time interval is [0,0]).

We are aware that this probably will break some features. By this reason we encourage @KratosMultiphysics/team-maintainers who use processes in the BCs imposition to update their application tests before the release date. 

We apologize for the inconveniences that these changes might yield.

### CODE REVIEW

**Review by RiccardoRossi — APPROVED** [review]
I am approving, however
i would like 
@philbucher @AndreasWinterstein @lorenzogracia 

who as i understand may be affected to give their green light before actually merging this

**Comment by lorenzogracia** [comment]
For me it's ok, I am updated in the branch that I am working. 
Regards

**Comment by philbucher** [comment]
@rubenzorrilla thx fro removing the old stuff. What for me however is still unclear which processes replaces the removed ones. I tried once to update my stuff but failed, that was why I asked in issue #836 also abt the documentation

**Comment by rubenzorrilla** [comment]
@philbucher Actually, these processes does not substitute the deprecated ones. We could say that they are an enhanced version that allow to join all the capabilities required in three processes:

- assign_scalar_variable_process.py: this one allows to set, with or without fixing, a scalar variable value. This value can be a double or a x,y,z,t function. It also supports time intervals.
- assign_vector_variable_process.py: same as above but considering a vector variable.
- assign_vector_by_direction_process.py: same capabilities as the processes above, but considering a vector variable. In this case the value is given by a direction vector plus its modulus.

These three processes have a conditions version.

I will try to help @loumalouomega to update your structural mechanics struff.

**Comment by philbucher** [comment]
ok thx for the explanation
I will try to change it tmr

**Comment by philbucher** [comment]
Cool thx a lot!

**Comment by rubenzorrilla** [comment]
@philbucher and @KratosMultiphysics/structural-mechanics I've already updated your tests. However, the Q4ThinNonLinearDynamicTest does not work in my machine. If I change the time scheme from Newmark to Bossak it works (of course the result is slightly different). Besides, the TestMultipointConstraints test gives nan when checking the results...

Can you please have a look to these ones? Thanks.

**Comment by philbucher** [comment]
@rubenzorrilla The shell test issue is known, I am working on this in another branch

the mpc issue is @adityaghantasala

**Comment by RiccardoRossi** [comment]
@philbucher, @adityaghantasala  does it mean we can merge this?

**Comment by philbucher** [comment]
I am fine, but lets wait for @adityaghantasala s answer

**Comment by rubenzorrilla** [comment]
@KratosMultiphysics/team-maintainers I've removed all the deprecated processes I've found in Kratos/applications except the DamApplication ones (@lorenzogracia  asked to keep them since he is already updating them in his current branch). 
Regarding the AdjointFluidApplication, I couldn't run the tests, @msandre would you mind to run them? Same happens for LagrangianMPMApplication (@iiaconeta). 
For the ShapeOptimizationApplication (@dbaumgaertner), I did change the *.json files in the "test_examples" folder. 

If there are no complains, we will proceed to merge the branch.

**Comment by lorenzogracia** [comment]
Go ahead!

**Comment by msandre** [comment]
The tests for AdjointFluidApplication all pass :+1:

**Comment by philbucher** [comment]
@rubenzorrilla I just checked the Q4ThinNonLinearDynamicTest and it is not failing for the reason I expected. It only fails with the new process, on another branch with the old process it works. An idea what could be the reason for this?

**Comment by rubenzorrilla** [comment]
No idea... Have you tried to substitute the Newmark scheme by the Bossak one? (in my machine this change made the test work).

**Comment by philbucher** [comment]
I can get it to work with either the bossak scheme or the displacement_criterion

For me the question is what the new process does different from the old one
Is the time in the solution when the BC's are applied different?

**Comment by rubenzorrilla** [comment]
The BCs are now applied before the solution loop (ExecuteBeforeSolutionLoop()) and at the beginning of each time step (ExecuteInitializeSolutionStep()). In the deprecated ones was done in the same manner.

**Pull request merged**
