### PR TITLE
Hotfix update convection diffusion solver

### PR DESCRIPTION
**Pull request by jcotela**
I am updating the convection_diffusion_solver to be more consistent with standard python solvers.
@loumalouomega will use it as a starting point for the workshop tutorials.

@loumalouomega I think this will still contain some errors. Feel free to report any problems to me or just update the branch yourself. Take a look into the bouyancy_test in the FluidDynamicsAppliaction to see an example of use.

@roigcarlo We should not delete this branch once it is merged, since we will want to do a similar update to master.

### CODE REVIEW

**Review by loumalouomega — APPROVED** [review]
I was already working on this, I will use as base

**Comment by loumalouomega** [comment]
Can I merge this?

**Comment by jcotela** [comment]
@loumalouomega can you confirm that you have already added these changes to #2224 and #2229? If so, we can close this.

**Comment by loumalouomega** [comment]
Yes, but I restored the old solver and change the name of the new one in
order to pass the tests.

**Comment by roigcarlo** [comment]
So there is no need to merge this?

**Comment by loumalouomega** [comment]
We don't need a priori

**Comment by roigcarlo** [comment]
Closing.

**Pull request closed without merging**
