### PR TITLE
[Core] Adding missing Access methods to PointerVectorSet 

### PR DESCRIPTION
**Pull request by loumalouomega**
**📝 Description**
Adding missing Access methods to PointerVectorSet, making the inteface inconsistent. this is part of afuture and more complex PR.

**🆕 Changelog**
- Added GetMaxBufferSize
- Added GetSortedPartSize/SetSortedPartSize

### CODE REVIEW

**Comment by matekelemen** [comment]
Why do we need the non-const getters? (I know all other getters have non-const couterparts here, just wondering what the reason behind them is)

**Comment by rubenzorrilla** [comment]
> Why do we need the non-const getters? (I know all other getters have non-const counterparts here, just wondering what the reason behind them is)

Agree. We're returning copies in this case so I think there is no point on adding the non-const getters.

**Comment by loumalouomega** [comment]
> > Why do we need the non-const getters? (I know all other getters have non-const counterparts here, just wondering what the reason behind them is)
> 
> Agree. We're returning copies in this case so I think there is no point on adding the non-const getters.

Agree. Done

**Comment by loumalouomega** [comment]
Ready

**Review by rubenzorrilla — APPROVED** [review]

**Pull request merged**
