### PR TITLE
[MappingApplication] Expose to master non historical flags

### PR DESCRIPTION
**Pull request by riccardotosi**
Following #5885. I added also other flags that were missing.

### CODE REVIEW

**Comment by philbucher** [comment]
Can you please only add the exposure for the two flags related to non-hist variables?
The other ones are not working properly and will be removed soon
Thanks!

**Comment by riccardotosi** [comment]
Sure

**Comment by riccardotosi** [comment]
Done

**Review by philbucher — APPROVED** [review]
👍 

I will let you know if sth related to these flags change in the future.

**Comment by riccardotosi** [comment]
Thanks!

**Pull request merged**
