### PR TITLE
Printing the eigenvalues in a new file

### PR DESCRIPTION
**Pull request by lorenzogracia**
New python process for printing the computed eigenvalues in a new file.

### CODE REVIEW

**Comment by lorenzogracia** [comment]
Hi Josep Maria. I have created a new process for printing the eigenvalues in a text file. About the computation of the modal participation, how do you want to perform it? using a flag inside of the strategy? We can use this branch for finishing it.

**Review by josep-m-carbonell — APPROVED** [review]
Hello Lorenzo, 
  I have added the flag to activate the computation of the modal contribution. Take a look on it if it is ok
Regards

**Comment by lorenzogracia** [comment]
Hi Josep Maria. I have been checking your changes and it is necessary to add a default parameter in the FeastSolver, inside of the ExternalSolverApplication.  In order to avoid possible issues with other users, I propose to create a ProcessInfo boolean variable which can be set at the main script (COMPUTE_MODAL_CONTRIBUTION), what do you think?

**Comment by loumalouomega** [comment]
Maybe for that reason it is preferable to use a local flag, it is far more
efficient, besides is less straightforward.

**Comment by josep-m-carbonell** [comment]
Hi Lorenzo, please can you explain me why you need this parameter, are you asking something extra to the Feast solver?. The ExternalSolverApplication has to be modified for that ?

**Comment by josep-m-carbonell** [comment]
Thank you Lorenzo, just check it again if it is solved.

**Comment by lorenzogracia** [comment]
I have corrected some typos in others files. Tomorrow I will run the tests and if there is no problems I will merge it. Thanks.

**Comment by lorenzogracia** [comment]
I have updated the dam solver and I have run the tests and everything seems right. I am going to merge it.

**Pull request merged**
