### PR TITLE
[Structural][EigenPost] improve ordering in Paraview

### PR DESCRIPTION
**Pull request by philbucher**
**Description**
This PR improves the ordering of the EigenValues in Paraview (it uses lexicographic order), see the following pics

### CODE REVIEW

**Comment by loumalouomega** [comment]
Why do you do a photo with the phone instead of a screenshot?, just asking

**Review by loumalouomega — APPROVED** [review]
Okay

**Comment by philbucher** [comment]
> Why do you do a photo with the phone instead of a screenshot?, just asking

I didn't manage to make the screenshot when the dropdown menu was open
do you know a way to do this? For me with some programs it works with some it doesn't

**Comment by loumalouomega** [comment]
> > Why do you do a photo with the phone instead of a screenshot?, just asking
> 
> I didn't manage to make the screenshot when the dropdown menu was open
> do you know a way to do this? For me with some programs it works with some it doesn't

In GNU/Linux as I use the screenshot tool of KDE (@roigcarlo) called [Spectacle](https://apps.kde.org/es/spectacle/) you can define a delay:

imagen

**Comment by roigcarlo** [comment]
I also use spectacle, didnt know it was a kde tool. Now I will have to change...

**Comment by loumalouomega** [comment]
> I also use spectacle, didnt know it was a kde tool. Now I will have to change...

**Pull request merged**
