### PR TITLE
[Core][All] GetDefaultSettings->GetDefaultParameters for consistency

### LINKED ISSUE #7431: GetDefault... is inconsistent btw Python and C++
In Python it is `GetDefaultSettings`, in C++ it is `GetDefaultParameters`

I don't have a strong opinion except that they should be consistent

Since it is not a heavily used feature I think we could easily rename either of them

@KratosMultiphysics/technical-committee

### PR DESCRIPTION
**Pull request by loumalouomega**
**Description**
Fixes #7431. Changes all the GetDefaultSettings to GetDefaultParameters

Should be merged ASAP in order to avoid conflicts

**Changelog**
- Refactor some conflicting static methods in order to compile and work
- Changes all the GetDefaultSettings to GetDefaultParameters

### CODE REVIEW

**Review by armingeiser — COMMENTED** [review]
Good for ShapeOpt - thanks for updating!

**Comment by sunethwarna** [comment]
Good for StatApp also... Thanks :+1:

**Comment by marcnunezc** [comment]
Ok regarding potential flow changes! :+1:

**Review by philbucher — CHANGES_REQUESTED** [review]
fine for me but why did you change (and refactor!) some cpp files too?
=> please make a separate PR for them

after that i will approve, thx for taking care

**Comment by loumalouomega** [comment]
> fine for me but why did you change (and refactor!) some cpp files too?
> => please make a separate PR for them
> 
> after that i will approve, thx for taking care

Because total consistency

**Review by rubenzorrilla — COMMENTED** [review]
Fine from my side too.

**Review by philbucher — APPROVED** [review]
nice thx

**Pull request merged**
