### PR TITLE
[Core] using glob_recurse for py-interface

### PR DESCRIPTION
**Pull request by philbucher**
Porting the core in small steps
lets see if Travis is happy this time :)

### CODE REVIEW

**Comment by philbucher** [comment]
appveyor has the following error:
~~~
  C:\projects\kratos\kratos\geometries/triangle_3d_3.h(1943): fatal error C1075: '{': no matching token found (compiling source file C:\projects\kratos\cmake_build\kratos\Debug\cotire\Kratos_CXX_unity_22_42.cxx) 
~~~

I would say that this is not related to this PR, but in the end I have no idea ...
I think I deleted all the files that are not used and are detected by the glob_recurse

when you have time, @roigcarlo could you please take a look?

**Comment by roigcarlo** [comment]
Sure, let me take a look

**Comment by pooyan-dadvand** [comment]
So the integration points are not exported to python anymore or they are exported in other files? Seems that @RiccardoRossi had imported them to pybind.

**Comment by philbucher** [comment]
> So the integration points are not exported to python anymore or they are exported in other files? Seems that @RiccardoRossi had imported them to pybind.

I don't know
@RiccardoRossi do you know?

**Comment by RiccardoRossi** [comment]
not sure...

**Comment by philbucher** [comment]
Do you want them to be exposed or not?

**Comment by pooyan-dadvand** [comment]
If nobody is using it I don't have reason to expose them.

**Comment by philbucher** [comment]
ping @roigcarlo :)

**Comment by philbucher** [comment]
Ping @roigcarlo :)

**Comment by roigcarlo** [comment]
@philbucher Sorry wasn't here for the week. i will look at it asap

**Comment by philbucher** [comment]
closing for now, this takes too much time for too little benefit ...
Maybe we can re-attempt this in the future

**Pull request closed without merging**
